### ISSUE TITLE
How to disable "Running slow: try frameskip, sound is choppy when slow "?

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#9531] opened 2017-04-02 02:42 UTC
It display in v1.4 and later version,when I playing game sometime.But I don't feel lag. It seems to display only once until restart game.
It don't display in v1.3.(v1.3.1xx,not test later vertion.)
I tested Win-32 version.Not sure, if the same as Android and Win-64 version.
Then,how to disable it?

**Comment by ijoinit** [comment] 2017-04-02 03:25
Try edit psp/system/ppsspp.ini,set it like this HideSlowWarnings = True

**Comment by leoxxx** [comment] 2017-04-02 04:27
THX.I'll try it.

**Comment by hrydgard** [comment] 2017-04-02 08:35
Well, this is working as intended, so that people will try the frameskipping option.

**Comment by hrydgard** [comment] 2017-04-02 08:36
Though if it's happening even though it's not running slowly, that might be a bug.

**Comment by leoxxx** [comment] 2017-04-02 12:23
It doesn't display after I edit the .ini file.

**Comment by leoxxx** [comment] 2017-04-05 12:53
It's not available in v1.4-20 after editing .ini file.

**Comment by hrydgard** [comment] 2017-04-07 09:12
Fixed an issue where this showed up when it shouldn't. closing for now.

**Closed by hrydgard** 2017-04-07 09:12 UTC

**Comment by Octavio1994** [comment] 2020-08-20 00:35
> Try edit psp/system/ppsspp.ini,set it like this HideSlowWarnings = True

Thanks this helped me

**Comment by jcchikikomori** [comment] 2020-08-20 03:47
> Though if it's happening even though it's not running slowly, that might be a bug.

IDK if it's possible. When i am playing Wipeout Pure, i turn frameskip on by 2, set CPU clock, sound is good, but still shows message
