### ISSUE TITLE
Some (DBZ) games are slow and/or laggy in 1.2.2

### ISSUE THREAD

**Issue by fluffyltu** [hrydgard/ppsspp#8692] opened 2016-04-11 12:52 UTC
Hello. I have issue, then i install ppsspp version 1.1.1 i cant open the program, newest version works, but 1.1.1 dont want open. I need 1.1.1 version play the games cuz with newiest version lagiing games

**Comment by hrydgard** [comment] 2016-04-11 14:21
We're not going to go back and fix 1.1.1

Instead, please tell us what games lag in 1.2.2. We'd rather fix that.

**Comment by fluffyltu** [comment] 2016-04-11 15:57
Dbz tenkachi tag team.. Imposible to play. Hard laging my device iphone 5s

**Comment by fluffyltu** [comment] 2016-04-11 17:17
What about dbz budokai another road? Perfomance is good , but sound hard laging and missin?

**Comment by LunaMoo** [comment] 2016-04-13 05:15
@fluffyltu previous version crashing suggests that your iPhone 5s has iOS 9+, so that's your problem - apple x64 devices with iOS 9+ doesn't have JIT and will not have it until Apple stops being stupid or it gets a full jailbreak that would allow for it, nothing of which seems like happening.
 You will have to suffer from poor performance unless you can downgrade it to whatever pre-iOS9 version had last full jailbreak that allowed JIT, not even sure if that's possible since I don't use any apple products.

 Sound is synchronized with game, which means if you run the game below full speed it will break even if performance feels fine for you. Since your limiting factor is cpu emulation, there's really not much you can do about it, maybe changing PSP clock to a value below 222, but above 0, could help a bit, but that's actually underclocking emulated psp and WILL cause various other issues in many games, maybe even completely breaking some.

 Closing this as a duplicate of #8122 where you can find more info about this problem and why it can't be fixed on the emulator side.

 If you really want to have any impact on this issue and aren't some hardcore hacker which could release a better jailbreak, the only thing you can do is to bother Apple about it. Maybe if enough consumers that buy their products will demand allowing JIT - it will happen, however as long as apple users find it easier to bother emulator developers about it, nothing will ever change and even if someone releases a jailbreak which would allow for it, apple will just update breaking it again.

**Closed by LunaMoo** 2016-04-13 05:15 UTC
