### ISSUE TITLE
[Feature Request] Ability to disable Function keys

### ISSUE THREAD

**Issue by DavidTamas** [hrydgard/ppsspp#12197] opened 2019-07-26 21:44 UTC
Several emulator features are bound to the function (F1-F12) keys. These features are not allowed during speedruns and if you accidentally press the keys you invalidate your runs. I've had a friend who once accidentally used the alternative speed function by pressing a wrong button instead of his split key which resulted in an invalid personal best. I have also found myself lately pressing F1 instead of Esc and accidentally changing the internal resolution to my annoyance.

The emulator should provide a way to unbind these features from the function keys (eg. have them listed in the control setup) or completely disable these keys for the application itself (eg. same way it does for the Win key).

**Comment by LunaMoo** [comment] 2019-07-27 02:34
Not interested in speedrunning in any way, but AFAIK inaccurate emulators that produce different results than real hardware are banned from speedrunning anyway and PPSSPP runs way faster than the real thing ever could.

 Either way we already have a generic issue about accidently pressing hardcoded mappings with a potential solution to provide option to just disable those completely. So I'll close this as a duplicate of #11255

**Closed by LunaMoo** 2019-07-27 02:34 UTC
