### ISSUE TITLE
Gta Vice City Stories pedestrian render bug

### ISSUE THREAD

**Issue by metehan989** [hrydgard/ppsspp#14514] opened 2021-06-07 06:53 UTC
### What happens?

The pedestrians won't load in properly.
![image](https://user-images.githubusercontent.com/82084917/120969795-e5280c80-c76a-11eb-9470-5550d165129e.png)
![image](https://user-images.githubusercontent.com/82084917/120969829-f07b3800-c76a-11eb-970f-04964678bc87.jpeg)
### What *should* happen?
The pedestrians should load in with a whole character.

### What are you using?
Iphone XR
#### What hardware / device and operating system?
Ios

#### What PPSSPP version (standalone/official), and did it work before?
1.11.3 . The characters were normal before on 1.11.2 .
#### Which game or games?

Grand theft auto: Vice city stories

#### Graphics backend (Vulkan, OpenGL, etc.)?
Tried both, same result. I have in on OpenGl now.

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [x] Try changing graphics settings to determine if one causes the bug.
 - [x] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-06-07 07:09
@metehan989 what iOS are you using?

**Comment by metehan989** [comment] 2021-06-07 07:30
I am using version 14.5.1

**Comment by hrydgard** [comment] 2021-06-07 07:32
Could you check if it still happens with the latest build of PPSSPP for iOS? One place to download that is https://p.xx.wtf/

**Comment by metehan989** [comment] 2021-06-07 07:48
I am actually using this one right here ![image](https://user-images.githubusercontent.com/82084917/120979059-7ac89980-c775-11eb-97e1-b1fc4341a619.jpeg)

**Comment by hrydgard** [comment] 2021-06-07 07:58
Ah, okay. Strange..

**Comment by metehan989** [comment] 2021-06-07 08:01
Ive been noticing that other games have some bugs in it on version 1.11.3 . For example the game "driver 76". It lags really hard even with the lowest graphics on it.

**Comment by metehan989** [comment] 2021-06-07 20:51
I even tried socom 2 and it shows me a black screen. Tried different ways to fix it but it wont help. I think the ppsspp version is broken.

**Comment by metehan989** [comment] 2021-06-08 17:08
I am gonna try redownloading the ppsspp IPA. Hope it works.

**Comment by metehan989** [comment] 2021-06-08 17:16
Nope it didnt work. The characters are still glitched. It also happens in cars (see picture below)
![image](https://user-images.githubusercontent.com/82084917/121229266-05042100-c88e-11eb-9b12-3dc80c0a29f0.png)

**Comment by metehan989** [comment] 2021-06-20 20:13
This issue still exists in the newer versions. I see that the save date issue is fixed.

**Comment by unknownbrackets** [comment] 2021-06-21 00:33
Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by metehan989** [comment] 2021-06-27 20:45
I just encountered another bug. When you try to grapple the bugged npc’s (R + square, triangle) you get soft locked in the game. Here is a frame dump of that:[ULUS10160_0001](zip)

**Comment by BlackGor** [comment] 2021-06-28 02:26
Did someone have a fix ?

**Comment by metehan989** [comment] 2021-06-28 06:03
> Did someone have a fix ?

No. We are still looking for one.

**Comment by BlackGor** [comment] 2021-08-08 15:50
> > Did someone have a fix ?
> 
> No. We are still looking for one.

Still here even with the last build , so sad :/ I don't know if is the emulator itself (because i don't test in another plateform) or IOS.

**Comment by unknownbrackets** [comment] 2021-10-10 02:44
> 
> 
> [ULUS10160_0001.zip](https://github.com/hrydgard/ppsspp/files/6722286/ULUS10160_0001.zip) I just encountered another bug. When you try to grapple the bugged npc’s (R + square, triangle) you get soft locked in the game. Here is a frame dump of that. (The link)

Sorry, must've missed this reply before.  When I look at this dump, I see it just displaying black to the screen.  It looks like an intro screen.  Did you take this while you saw the issue?

GE frame dumps are like 3D screenshots - but they only capture what's being shown.  It has to be taken while the issue is visible.

-[Unknown]

**Comment by hrydgard** [comment] 2022-07-26 19:00
Due to the similarity in compiler and architecture between iOS and Mac M1, this is almost certainly the same bug as #15149 , we have more technical discussion there so closing this one as a duplicate.

**Closed by hrydgard** 2022-07-26 19:00 UTC
Labels: Platform-specific (iOS), Platform-specific (Mac OS X), GE emulation
