### ISSUE TITLE
Deleting save data issues

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12505] opened 2019-12-07 06:35 UTC
When I have 2 save data for each game when I select delete save data option in most games it displays new game when I select it displays unable to delete data.

In GTA LCS for example
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/37503397/70370146-a2c80a00-18fe-11ea-8bab-8acd5191491a.gif)

However in burnout legends, 2 save datas disguised as a new game icon but it able to delete it:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/37503397/70370170-becbab80-18fe-11ea-93bc-47b81d55453e.gif)

**Comment by unknownbrackets** [comment] 2019-12-31 20:45
Going to close this as a duplicate of #7685 since it has a bit more information.

-[Unknown]

**Closed by unknownbrackets** 2019-12-31 20:45 UTC
