### ISSUE TITLE
Spiderman3

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#17829] opened 2023-08-01 15:36 UTC
Hi again @hrydgard 
![Screenshot_2023-08-01-23-35-26-71_2f85358b2198d26f8aca533d68bee793](https://github.com/hrydgard/ppsspp/assets/67460268/5fa18308-bb9c-4e5a-99ee-690c5e655ed1)

**Comment by Gelo021** [comment] 2023-08-01 15:38
I've tried twice to confirm, same scene at the tutorial when square, square, triangle pops up this happens

**Comment by hrydgard** [comment] 2023-08-02 10:02
This is a duplicate of #10196 , an old mystery we haven't solved :(

**Closed by hrydgard** 2023-08-02 10:02 UTC
