### ISSUE TITLE
USE_SYSTEM_FFMPEG : crashes PPSSPP with system ffmpeg 3.2

### ISSUE THREAD

**Issue by substring** [hrydgard/ppsspp#9273] opened 2017-02-02 10:10 UTC
When trying to build for Raspberry, using the system FFMPEG results in:
`38:05:962 Draw         E[ME]: HW/MediaEngine.cpp:82 FF: Assertion 0 failed at libavcodec/utils.c:596`

system ffmpeg details:
 ```
# ffmpeg -version 
ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.1 (Linaro GCC 5.3-2016.05) 20160412
configuration: --enable-cross-compile --cross-prefix=/home/subs/git/recalbox-build-pi3/output/host/usr/bin/arm-linux-gnueabihf- --sysroot=/home/subs/git/recalbox-build-pi3/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot --host-cc=/usr/bin/gcc --arch=arm --target-os=linux --disable-stripping --pkg-config=/home/subs/git/recalbox-build-pi3/output/host/usr/bin/pkg-config --enable-static --enable-shared --prefix=/usr --enable-avfilter --disable-version3 --enable-logging --enable-optimizations --disable-extra-warnings --enable-avdevice --enable-avcodec --enable-avformat --disable-x11grab --enable-network --disable-gray --enable-swscale-alpha --disable-small --enable-dct --enable-fft --enable-mdct --enable-rdft --disable-crystalhd --disable-dxva2 --enable-runtime-cpudetect --disable-hardcoded-tables --disable-memalign-hack --disable-mipsdsp --disable-mipsdspr2 --disable-msa --enable-hwaccels --disable-avisynth --disable-frei0r --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libcdio --disable-libdc1394 --disable-libgsm --disable-libilbc --disable-libnut --disable-libopenjpeg --disable-libschroedinger --disable-libvo-amrwbenc --disable-symver --disable-doc --enable-gpl --disable-nonfree --enable-ffmpeg --disable-ffplay --disable-ffserver --enable-avresample --disable-ffprobe --enable-postproc --enable-swscale --enable-indevs --enable-outdevs --enable-pthreads --enable-zlib --enable-bzlib --disable-libfdk-aac --disable-gnutls --disable-openssl --disable-libopenh264 --enable-libvorbis --enable-muxer=ogg --enable-encoder=libvorbis --enable-vaapi --disable-vdpau --disable-libopencv --enable-libopus --disable-libvpx --enable-libass --disable-libbluray --enable-librtmp --enable-libmp3lame --enable-libmodplug --disable-libspeex --enable-libtheora --disable-libwavpack --enable-libfreetype --enable-fontconfig --enable-libx264 --disable-libx265 --disable-yasm --disable-mmx --disable-sse --disable-sse2 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-avx2 --enable-armv6 --enable-vfp --enable-neon --disable-altivec --enable-pic --cpu=cortex-a8
libavutil      55. 34.100 / 55. 34.100
libavcodec     57. 64.100 / 57. 64.100
libavformat    57. 56.100 / 57. 56.100
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100
```

This makes ARM64 impossible to use as you have no prebuilt ffmpeg libraries for aarch64

**Comment by LunaMoo** [comment] 2017-02-02 15:18
Closing this as a duplicate of #9026

 You should also see #9177 and since you'll likely have to do the same thing anyway, you should consider contributing yourself following the advices there. PPSSPP doesn't need the whole FFMPEG for psp emulation and it changes too much, too often, so it's unlikely it'll ever be kept updated.

**Closed by LunaMoo** 2017-02-02 15:18 UTC

**Comment by substring** [comment] 2017-02-02 15:32
oh sorry for the annoyance, and thank you for pointing me to the right issues. I'll dig in compiling ffmpeg for ARM64.
