### ISSUE TITLE
I found a very weird way about ppsspp emu speedup

### ISSUE THREAD

**Issue by ijion** [hrydgard/ppsspp#10511] opened 2018-01-06 09:03 UTC
What happens?

![img_0736](https://user-images.githubusercontent.com/29668230/34638091-00112602-f308-11e7-8f7b-9602399fd065.PNG)

It's a screen record tweak from cydia,i don't know if anyone believe me but,when it's recording the ppsspp will be speed up. I only tested two games ,same result ,it's alleviating the lag problem,i don't know why it's a opposite effect
What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

It's Jail broken iOS 10 on 
IPad mini 4

**Comment by unknownbrackets** [comment] 2018-01-06 09:11
As described in #9197, the problem is that iOS is lowering the CPU clock speed because it wants to save your battery power.

That makes PPSSPP run worse.

By running another CPU consuming app, you're convincing iOS not to slow down PPSSPP, that's why this can sometimes help.  It will also burn battery power.

Another way we could solve this problem is by making PPSSPP mine bitcoins while you play it, wasting your CPU but convincing iOS not to slow things down.

Anyway, closing this as a duplicate of #9197.  We only need one issue for the cpu throttling iOS is doing.

-[Unknown]

**Closed by unknownbrackets** 2018-01-06 09:11 UTC
