### ISSUE TITLE
Problem with immersive mode enabled on PPSSPP on smartphone

### ISSUE THREAD

**Issue by Deivmsr** [hrydgard/ppsspp#11869] opened 2019-03-04 19:39 UTC
### What happens?
I am having problems with PPSSPP since my smartphone was upgraded to Android Pie. In Android 9 the immersive mode is not working properly. When activated, the image will "cut". When changing the internal resolution in the emulator the main menu returns to normal size, but when exiting the application and entering it again the problem returns. The situation only completely normalizes when the immersive mode is disabled in the emulator settings.

### What *should* happen?
What should happen is that PPSSPP would adjust the screen of the smartphone as it did in the previous version of Android, 8.0.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
My smartphone is the Galaxy Note 8, Exynos version, with Android Pie 9.0, version of PPSSPP v.1.7.5-553-gc77af182a.

**Comment by Emulatorer** [comment] 2019-03-05 00:03
@Deivmsr Can you upload a screenshots?

**Comment by AkiraJkr** [comment] 2019-03-05 00:04
Uploading the ones he sent to me on Discord.
![something](https://cdn.discordapp.com/attachments/478192501438677002/552205627263549490/Screenshot_20190304-160813_PPSSPP.jpg)

**Comment by unknownbrackets** [comment] 2019-03-05 03:42
Pretty sure this is a duplicate of #11526, which itself is probably a duplicate of #9758 and #8728.

We end up getting weird size info from Android, and what works in one device fails on another (possibly related to os version or screen resolution.)

-[Unknown]

**Comment by hrydgard** [comment] 2019-03-13 20:47
For now, disable immersive mode. The feature seems buggy, I don't think we're misusing it somehow

**Comment by AlternativeZero** [comment] 2019-03-15 03:18
It might be an issue with 9.0, I tested PPSSPP on a Nokia 6.1 Plus running 8.1.0 and immersive mode works normally.

1.  I enabled immersive mode.
2. Exit PPSSPP.
3. Open PPSSPP and it doesn't stretch.

On my Asus Zenfone Max Pro M1 running 9.0, immerisve mode has an issue.

**Comment by unknownbrackets** [comment] 2019-03-16 00:05
Maybe we can just swap immersive multiple times on startup / device restore after lost.  It'd look ugly, but that always seems to workaround the issue.

-[Unknown]

**Closed** 2019-05-13 11:34 UTC
