### ISSUE TITLE
Unstable Frame on PPSSPP core Retroarch on Android Phone

### ISSUE THREAD

**Issue by yudhiyou** [hrydgard/ppsspp#15255] opened 2021-12-28 05:48 UTC
### Game or games this happens in

All Games

### What area of the game

It happen on a whole game. The framerate is very choppy and unstable.

### Platform

Android

### Mobile phone model or graphics card

Vivo V9 Pro

### PPSSPP version affected

The latest version

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

Actually already tried both OpenGL and Vulkan but it is not affected at all.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by yudhiyou** [comment] 2021-12-28 05:50
But I tried on standalone PPSSPP on same device is working fine.
So this is happened only on Retroarch core.

**Comment by LunaMoo** [comment] 2021-12-28 06:19
Libretro is known to be slower and limited by it's "retro" design, so doubt this will change. It's just not ment for modern emulation.

**Comment by yudhiyou** [comment] 2021-12-28 06:48
About that "retro" design on libretro, I can argue with that. I have tried Duckstation and Snes9x core on Retroarch and they are a lot of smoother than their standalone app.
Also I have tried PPSSPP core Retroarch on Windows PC with potato specs and it is also a lot of smoother than on Android.

**Comment by unknownbrackets** [comment] 2021-12-31 05:42
Your assumption there that a "potato" PC can't still be better than a mobile phone is probably not correct.

People have complained about PPSSPP not running well with > 2x PSP render resolution or other graphics enhancements on PCs released *before the PSP was released in 2005*.  Any potato that uses an Intel or AMD CPU is likely going to get a stable framerate and almost all games at reasonable settings.

This simply isn't true of Android devices.  In many cases, it's down to terrible graphics drivers (desktop graphics drivers are far more mature.)  Weaker Android devices tend to have less powerful CPUs and GPUs than even low spec laptops.

We've done a lot in PPSSPP to optimize for Android devices, and use threading and other things as much as we can to maximize performance.  In contrast, libretro was designed for simpler systems - like the SNES (the PSP is 93x as powerful) or PS1 (the PSP is 10x as powerful) and interferes with some of the threading we do in how its API is designed.  It's not some magic dust that makes any emulator better, it's just an implementation of some parts of an emulator that could in theory be common.

Since those parts are common and generic, it's not really surprising to me that they're slower and worse than equivalent parts in a specialized and very optimized emulator.  Especially when using threads seems like a foreign concept to them and they've designed everything thinking about emulating little things like the NES or SNES.  It also doesn't really surprise me if other emulators for weaker systems, which haven't worked so hard to optimize, benefit from the generic, but optimized, parts of libretro.

It might be there's something that can be fixed here, but it may also just be limitations of libretro.

-[Unknown]

**Closed by unknownbrackets** 2021-12-31 05:42 UTC
Labels: Libretro
