### ISSUE TITLE
✨ADD the posibility of edit on value the IP ADRESS and PORT using keyboard on ANDROID ver✨

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#15680] opened 2022-07-12 17:16 UTC
### Game or games this happens in

ALL

### What area of the game / PPSSPP

edit any value the IP ADRESS and PORT using keyboard on ANDROID ver

https://user-images.githubusercontent.com/82737672/178552349-c4c7dd23-0063-4af4-a9a7-6fb4ac83073f.mp4

### What should happen

edit any value the IP ADRESS and PORT using keyboard on ANDROID ver

https://user-images.githubusercontent.com/82737672/178552765-7af0704a-615d-40a0-a330-b5229cea3533.mp4

### Platform

Android

### Mobile phone model or graphics card

POCO DE PRO ADRENO

### PPSSPP version affected

ALL

### Last working version

ALL

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by MojoJojoDojo** [comment] 2022-07-12 18:58
While you cant input anything via a OSK , you can copy and paste numbers/words into the text boxes for now.

**Comment by Gamemulatorer** [comment] 2022-07-13 04:51
Duplicate #13716

**Comment by unknownbrackets** [comment] 2022-07-13 06:30
This issue is being closed as a duplicate of #13716.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-07-13 06:30 UTC
Labels: Platform-specific (Android), Feature Request, User Interface
