### ISSUE TITLE
Assassin's Creed: Bloodlines broken russian fonts

### ISSUE THREAD

**Issue by dante3732** [hrydgard/ppsspp#13956] opened 2021-01-21 19:11 UTC
Broken russian fonts. If i use original psp fonts it work fine
v1.10.3-1596-g48bb797ff
Windows 10 Pro x64 20H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
2x8 Gb DDR4 3200
![image](https://user-images.githubusercontent.com/66036249/105400140-97848a80-5c35-11eb-99e8-6add673638f9.png)
![image](https://user-images.githubusercontent.com/66036249/105400150-9c493e80-5c35-11eb-9005-4619d6cf4bfe.png)

**Comment by Panderner** [comment] 2021-01-22 00:01
Have you tried stable version of PPSSPP?

**Comment by nassau-tk** [comment] 2021-01-22 03:08
@dante3732 

Yes, I reproduced your issue.
So, I will try remaking russian fonts A.S.A.P. on this weekend.

Can you feel appearance Good? or Bad? (just feeling.)

(Because, I don't have any knowledge for russian=Cyrillic alphabet.)

[I tested fixingfor  PPSSPP PGF on Latest jpn0.pgf.]
![Assassin_My_PGF_01](https://user-images.githubusercontent.com/48179091/105440368-cf2d1a00-5ca9-11eb-81c6-70266f3220df.png)
![Assassin_My_PGF_02](https://user-images.githubusercontent.com/48179091/105440381-d3f1ce00-5ca9-11eb-930f-a893eca7fd78.png)
![Assassin_My_PGF_03](https://user-images.githubusercontent.com/48179091/105440389-d5bb9180-5ca9-11eb-9b23-76c9aea5c4a8.png)
![Assassin_My_PGF_04](https://user-images.githubusercontent.com/48179091/105440396-d81deb80-5ca9-11eb-9904-89d07764c5f5.png)

**Comment by nassau-tk** [comment] 2021-01-22 07:40
Character hight & width are Fixing now.
It Look good isn't it?
But Of course, I can't read them. :laughing:

![Assassin_My_PGF_A1](https://user-images.githubusercontent.com/48179091/105461004-f4cd1a00-5ccf-11eb-8512-acab4a5d0bea.png)

I will go back home!!
Later!

**Comment by hrydgard** [comment] 2021-01-22 09:04
Great stuff nassau-tk!

**Comment by dante3732** [comment] 2021-01-22 09:44
![image](https://user-images.githubusercontent.com/66036249/105474584-72ccf900-5caf-11eb-99fc-34499305b6f4.png)
Need to make a little more distance between the letters, here is the original psp font.

**Comment by nassau-tk** [comment] 2021-01-22 10:59
Yes, Your feeling is right!

Because, My font is "all different with original".
It's maked from other font.
Because, Original font is can't use by the restrictions.
So, We are making for "PPSSPP's custom font" by other font.

The reason of exist?
Because, Many people don't have the original. :grin:
It's to say a substitute.
Don't you think it's good appearance when thinking so?:laughing:


[Maybe, I think that the Russian characters will use fix bearings value(4096).]
![image](https://user-images.githubusercontent.com/48179091/105481175-0c190100-5cea-11eb-8781-0f3541283e44.png)

I will try more fixing.

**Comment by dante3732** [comment] 2021-01-22 11:53
I think for all letters need similar width.

**Comment by nassau-tk** [comment] 2021-01-22 14:26
OK.
Finished!!

![image](https://user-images.githubusercontent.com/48179091/105502384-bb64d080-5d08-11eb-9a8f-ab21ded86ab3.png)

![image](https://user-images.githubusercontent.com/48179091/105502406-c3247500-5d08-11eb-8e26-e6ffbaac9ec2.png)

![image](https://user-images.githubusercontent.com/48179091/105502434-c7e92900-5d08-11eb-93fa-6cc7008fc067.png)

![image](https://user-images.githubusercontent.com/48179091/105502455-ccaddd00-5d08-11eb-9833-2fae2dd24f08.png)

![image](https://user-images.githubusercontent.com/48179091/105502485-d46d8180-5d08-11eb-83d6-4b6eb7f13d55.png)

![image](https://user-images.githubusercontent.com/48179091/105502537-e0594380-5d08-11eb-967b-eeaa26013127.png)

![image](https://user-images.githubusercontent.com/48179091/105502570-e94a1500-5d08-11eb-807f-415a77f22b51.png)

![image](https://user-images.githubusercontent.com/48179091/105502616-f535d700-5d08-11eb-84fc-d6142a4a1966.png)

![image](https://user-images.githubusercontent.com/48179091/105502643-fbc44e80-5d08-11eb-88a6-8bef5d79d036.png)

![image](https://user-images.githubusercontent.com/48179091/105502694-0d0d5b00-5d09-11eb-8a9b-5f6afb8a7de6.png)

![image](https://user-images.githubusercontent.com/48179091/105502735-18f91d00-5d09-11eb-8615-2f934ac717b9.png)

**Comment by hrydgard** [comment] 2021-01-22 15:09
I don't read more than a few words of Russian, but I think that looks much improved!

**Comment by dante3732** [comment] 2021-01-22 15:11
Very good, but have problem with punctuation marks and dashes.
![105502643-fbc44e80-5d08-11eb-88a6-8bef5d79d036](https://user-images.githubusercontent.com/66036249/105508282-4203b880-5cdd-11eb-8b19-adaaf1559978.png)
![105502694-0d0d5b00-5d09-11eb-8a9b-5f6afb8a7de6](https://user-images.githubusercontent.com/66036249/105508286-4334e580-5cdd-11eb-9b48-29828f0ad576.png)

**Comment by nassau-tk** [comment] 2021-01-22 15:48
Oops!

OK. I fixed it.

**Comment by nassau-tk** [comment] 2021-01-22 15:49
![image](https://user-images.githubusercontent.com/48179091/105512689-c58ccc00-5d14-11eb-9567-110fbef8082b.png)
![image](https://user-images.githubusercontent.com/48179091/105512730-d2a9bb00-5d14-11eb-92e2-b5609807ae19.png)
![image](https://user-images.githubusercontent.com/48179091/105512741-d9383280-5d14-11eb-9063-6e8fcf302873.png)

**Comment by hrydgard** [comment] 2021-01-22 15:56
I'm gonna wait for a comment from @dante3732 , before I merge the next one :)

**Comment by nassau-tk** [comment] 2021-01-22 15:58
Yes, Your way is right! :grin:

**Comment by dante3732** [comment] 2021-01-22 16:10
I think it fine.

**Comment by nassau-tk** [comment] 2021-01-22 23:34
@dante3732 

OK.
It's merged.
It will be upload on download page later.

So, Please close this issue.

Thank you for your test & report!

**Comment by nassau-tk** [comment] 2021-01-23 11:00
@hrydgard 

Can you close? 😄

**Closed** 2021-01-23 12:25 UTC
