### ISSUE TITLE
Crash report when switching backends

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11752] opened 2019-01-31 16:36 UTC
This issue Is only when i switch from OpenGL→Vulkan NOT Vulkan→ OpenGL
Tested device: Xiaomi redmi note 5 (SD 636)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/whyred/whyred:8.1.0/OPM1.171019.011/V10.2.1.0.OEIMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 14336, tid: 14434, name: Emu  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7fe648000
    x0   00000007fe648000  x1   0000007b4880d040  x2   00000000000038d0  x3   00000007fe648000
    x4   0000007b48810910  x5   00000007fe64b8d0  x6   ffffffff397fda40  x7   00000000448a6000
    x8   0000000000000000  x9   0000000000000000  x10  0000007b5a56d5c0  x11  0000000000000000
    x12  0000000000000000  x13  3e9a600b00000000  x14  0000007b4a1f5538  x15  0000000000000000
    x16  0000007b4a1a02b0  x17  0000007be46f97b0  x18  0000000000000000  x19  000000000000025e
    x20  0000007b4621b800  x21  0000007b4621b840  x22  0000000000000000  x23  0000007b5a43a0d0
    x24  0000007b4880d040  x25  00000000000038d0  x26  00000000000038d0  x27  0000000000000002
    x28  0000007b4a1b4000  x29  0000007b4718c0f0  x30  0000007b49742e44
    sp   0000007b4718c0b0  pc   0000007be46f98a8  pstate 0000000020000000

backtrace:
    #00 pc 000000000001c8a8  /system/lib64/libc.so (memcpy+248)
    #01 pc 0000000000662e40  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (Draw::OpenGLContext::DrawUP(void const*, int)+152)
    #02 pc 0000000000644b64  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (DrawBuffer::Flush(bool)+280)
    #03 pc 000000000067d85c  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (UIContext::Flush()+28)
    #04 pc 00000000005d0e38  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (DrawGameBackground(UIContext&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+372)
    #05 pc 000000000067ee84  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (UIScreen::render()+140)
    #06 pc 000000000067cafc  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (ScreenManager::render()+208)
    #07 pc 00000000005b252c  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (NativeRender(GraphicsContext*)+648)
    #08 pc 00000000005ac260  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (UpdateRunLoopAndroid(_JNIEnv*)+44)
    #09 pc 00000000005adb60  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so
    #10 pc 0000000000348e1c  /data/app/org.ppsspp.ppsspp-UB4RsM20JHytyaeJwU7yvA==/lib/arm64/libppsspp_jni.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvvEEEEEEPvSA_+44)
    #11 pc 0000000000067ec4  /system/lib64/libc.so (__pthread_start(void*)+36)
    #12 pc 000000000001f2f4  /system/lib64/libc.so (__start_thread+68)

**Comment by hrydgard** [comment] 2019-01-31 18:04
Yeah, I noticed this too the other day. Will fix.

**Comment by unknownbrackets** [comment] 2019-02-02 19:11
This issue is being closed as a duplicate of #11715.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-02-02 19:11 UTC
Labels: OpenGL, Platform-specific (Android)
