### ISSUE TITLE
Afterburner Black Falcon - Freezes after Dev Logo/Copyright Screen

### ISSUE THREAD

**Issue by 4XPG** [hrydgard/ppsspp#6794] opened 2014-08-27 00:52 UTC
I recall this game used to be working back on v0.9.1 (according to the forum entry, it doesn't work since 0.9.5-0.9.6 and still never been fixed since then), but it freezes after the dev logo FMV/copyright screen on the later version (I'm using v0.9.9-80 in this case).

The sound thread appears to be stuck at endless loop, here's the log:
https://gist.github.com/4XPG/1a529bc99d1959f6c4fc

**Comment by sum2012** [comment] 2015-01-05 22:21
Can we have a work around ?

**Comment by 4XPG** [comment] 2015-04-21 07:10
Just my (wild) speculation, since the game hangs right before this screen: https://gfycat.com/FeistyFragrantChimneyswift (I'm using older playable build here), perhaps the hang caused because the emulator unable to render specific effects (in this case, the smoke effect since the initial screen in which the plane zooms away the screen is not prerendered), like how sunlight effects make PSP Armored Core games to freeze (https://github.com/hrydgard/ppsspp/issues/5999) ?

**Comment by sum2012** [comment] 2015-10-18 07:18
Update the log to v1.1.1-43-g6c31612
(I have switched to USA version to debug)
https://gist.github.com/sum2012/d062601b36159dde64d6

**Comment by sum2012** [comment] 2015-10-18 08:02
I change the log to
WARN_LOG(ME, "Audio end reach. pts: %i dts: %i m_videopts %i m_audiopts %i", (int)atracAu.pts, (int)ctx->mediaengine->getLastTimeStamp(), ctx->mediaengine->m_videopts, ctx->mediaengine->m_audiopts);

output:
01:53:818 decodeThread W[ME]: HLE\sceMpeg.cpp:1609 Audio end reach. pts: 866654 dts: 780780 m_videopts 774774 m_audiopts 780834

**Comment by unknownbrackets** [comment] 2015-10-18 08:42
So then `getAudioTimeStamp()` is ahead of the video indeed?  Hmm.  That implies to me that it's decoding audio frames faster than video...

-[Unknown]

**Comment by sum2012** [comment] 2015-10-18 09:14
So just return 0 would solve the problem

**Comment by LunaMoo** [comment] 2015-10-18 15:41
More like a hack than solution, since 0 just means no error when it clearly got one it was designed to detect. You can do that via CWCheat if you want to, just find the syscall in ppsspp disassembly and force v0 or whatever v0 is passed to after that syscall to 0 - this can be done by setting it's value to 0(li v0,0) or by moving value of zero register(move v0,zero).

BTW is that code related - https://github.com/hrydgard/ppsspp/blob/c2f4fad56aada331bbd8dd7db99037285bab853f/Core/HLE/sceMpeg.cpp#L1503
It seems like it was stopping this from happening, disabled because it does't happen on psp?

**Comment by sum2012** [comment] 2015-10-18 18:18
In the real PSP,this game of video don't return ERROR_MPEG_NO_DATA
JPCSPTrace log:
https://gist.github.com/sum2012/43a7a73f9a0dac1175a0

**Comment by unknownbrackets** [comment] 2015-10-18 18:56
Yes, but maybe something else is causing it to call that too frequently.  Does it call it the same number of times?

The real firmware returns no data when there's no audio remaining.  It doesn't even mean end; it means there's no audio data in the buffer, afaict.  So the issue here can be any of:

1. It's reading audio data out faster than video data, and shouldn't be.
2. It's not filling the buffer as fast as it should be.
3. There's some other bug somewhere (e.g. it's ignoring data that was fed to it.)

I'm pretty sure it should NOT return 0 when there's no audio data, and doing so will DEFINITELY break other games.  I'm also pretty sure it should not delay to manually sync audio with video, since that is the game's job, and iirc, doing that again will ALSO break other games.

-[Unknown]

**Comment by sum2012** [comment] 2015-10-18 22:54
If I make change,at least the following:
		if ((int)ctx->mediaengine->getLastTimeStamp() > ctx->mediaengine->m_audiopts)
			result = ERROR_MPEG_NO_DATA;

Don't break Obscure the Aftermath,Pacman land 3 ,it still hit ERROR_MPEG_NO_DATA;

**Comment by sum2012** [comment] 2015-10-21 04:46
@unknownbrackets jpcsp fix this game by https://github.com/jpcsp/jpcsp/commit/f4a49b818ce743b73ce65995aa3c280bd7e230ae
//It seems that sceMpegGetAtracAu returns ERROR_MPEG_NO_DATA only when both  
// the audio and the video have reached the end of the stream.  
// No error is returned when only the audio has reached the end of the stream.

**Comment by unknownbrackets** [comment] 2015-10-21 04:58
I'm really not sure that's correct, since that sounds like it contradicts firmware tests I did previously, although it's been a while.  I'd like to see actual firmware tests confirming this.

-[Unknown]

**Comment by sum2012** [comment] 2015-10-21 05:02
This game 's firmware is 2.82

**Comment by sum2012** [comment] 2015-10-21 05:07
(no wrong)
This game's firmware is 2.82

**Comment by slowfellow** [comment] 2015-10-29 19:06
Can someone please adress this issue?, I very much like to play After Burner on the latest version.
Regards

**Comment by sum2012** [comment] 2015-10-29 22:08
@slowfellow what device are you using ? Windows 32 bit,Windows 64 bit,Android

**Comment by slowfellow** [comment] 2015-10-30 07:47
I am using both Windows32 and Android 5.1.1 (Xperia Z5 compact)

**Comment by sum2012** [comment] 2015-10-30 13:34
The is test build
Windows 32 build
https://drive.google.com/file/d/0B3OaSdeV0L8kVTI1MG1GRUlaaWc/view?usp=sharing
Android  build
https://drive.google.com/file/d/0B3OaSdeV0L8kaHlCbmRkWWctcW8/view?usp=sharing
If it break other game of video  ,I would appreciate that you tell me.Thanks

**Comment by sum2012** [comment] 2015-10-31 12:16
oop ,my change break Obscure The Aftermath

**Comment by slowfellow** [comment] 2015-10-31 23:16
Thanx, I will try them out, windows version now supports Afterburner. Thanx, will try android later.

**Comment by slowfellow** [comment] 2015-10-31 23:17
Why not make it an optional switch if it breaks some games, but supports others?

**Comment by sum2012** [comment] 2015-10-31 23:25
Becuase I didn't test when I compiled

**Comment by slowfellow** [comment] 2015-11-10 20:30
Well I have tested some 20 games so far everything works, maybe this Obscure, The Aftermath is a combination of things

**Comment by unknownbrackets** [comment] 2016-01-27 04:01
If you un-revert e866d835472cb36f629343ced21d6cd7bdca7793, does this work?  Just wondering, since it's related to the jpcsp change.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-27 04:07
No,it doesn't.

**Comment by daniel229** [comment] 2016-08-08 01:55
Fixed in https://github.com/hrydgard/ppsspp/pull/8867

**Comment by unknownbrackets** [comment] 2016-08-08 02:04
Oh, that makes sense.  So it was likely related to how it was reading the header.

Thanks for testing.

-[Unknown]

**Closed by unknownbrackets** 2016-08-08 02:04 UTC

**Comment by sum2012** [comment] 2016-08-08 02:07
Video flicking in beginning.
Old version (eg: v1.1.1-577-gefc1768) no problem.
I post here or open new issue ?

**Comment by unknownbrackets** [comment] 2016-08-08 02:09
Hmm, probably a new issue is better since it started at a different time - better to avoid getting confused with the old issue.

-[Unknown]
