### ISSUE TITLE
Me and My Katamari, PPSSPP Android Graphical Bug

### ISSUE THREAD

**Issue by Gabi1117** [hrydgard/ppsspp#11459] opened 2018-10-08 14:38 UTC
Me and My Katamari. In the turtle level, glass appears black. You can see the bug in this video:
https://youtu.be/N-XgHtxPBfc   at about 3:00

I've seen actual psp playthroughs of the game, and it's not supposed to be that way. Is it just an android thing or can I do something about it? It doesn't really ruin the gameplay in any way, but I'd still like to get it fixed. Any suggestions would help. Thanks.

PowerVR, Android, PPSSPP 1.6.3

**Comment by Emulatorer** [comment] 2018-10-08 14:59
Try to use the latest git build
https://buildbot.orphis.net/ppsspp/

**Comment by hrydgard** [comment] 2018-10-08 16:41
Yeah, this is one of the major remaining graphics mysteries. The game uses the depth buffer as a texture for tricks like custom fog, but when I last traced through it that did not seem to be the issue here. A CLUT (color palette) that's used when drawing the glass is black when I don't think it should be. So the game is clearly doing some really nasty tricks that we haven't managed to implement support for yet...

**Comment by Gabi1117** [comment] 2018-10-09 01:35
When software rendering is enabled, the game shows the first "Now Loading" screen. And then it's just black after that. I can't see the Namco logo which I know should be there because the guy starts singing. I couldn't get past it either because my OSD has disappeared.

**Comment by Panderner** [comment] 2020-03-12 06:52
![Screenshot_2020-03-12-14-48-11-69_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/76495016-053a2480-6471-11ea-9570-ecd321d9a0e9.png)
Here's a GE Dump for fog:
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4322688/recording.ppdmp.zip)

**Comment by LunaMoo** [comment] 2020-03-12 07:19
That's #6411, known issue with cheat workaround. Use search before posting Panderer as those two are not related.

**Comment by Panderner** [comment] 2020-03-12 09:12
Oops. wrong issue

**Comment by hrydgard** [comment] 2020-08-06 09:32
The glass in the turtle level is no longer black, for whatever reason. 

As for the rest, it's a duplicate of #6411. Closing.

**Closed by hrydgard** 2020-08-06 09:32 UTC
