### ISSUE TITLE
Grand Theft Auto: Vice City stories crash

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#15221] opened 2021-12-10 08:54 UTC
### Game or games this happens in

ULES-00502 - Grand Theft Auto: Vice City Stories

### What area of the game / PPSSPP

![PPSSPP_2021-12-10-09-25-14](https://user-images.githubusercontent.com/65356692/145544653-94fcb63e-a359-4474-b43e-a27726db1d02.jpg)

I'm using the cheat of "Right Analog v1.1 [X/R No Swap]"

Game device http://cheatdeviceremastered.com/?fbclid=IwAR3nZ8DCsdUrrc_bQewNJ-ZgbTGqBa7WqBf7z39QiVrOckrb5nrhQJZ1IDo

### What should happen

It shouldn't crash.

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy Note 10 plus exynos

### PPSSPP version affected

ppsspp-v1.12.3-423-g51dce175a-android.apk

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-12-10 09:23
@MiguelCardonaG and then what happens when you disable cheats?.

**Comment by MiguelCardonaG** [comment] 2021-12-10 09:43
The same.

![PPSSPP_2021-12-10-10-42-07](https://user-images.githubusercontent.com/65356692/145552794-f7ad3662-06a3-4c68-8946-edcc1a3a6b58.jpg)

**Comment by hrydgard** [comment] 2021-12-10 10:00
It says "Plugins: Y" -  what plugin is that? plugins can make games unstable.

**Comment by MiguelCardonaG** [comment] 2021-12-10 10:52
If I don't use cheats or cheat device it works fine.

**Comment by hrydgard** [comment] 2021-12-10 11:09
Okay, well, then the problem is with the cheat - it's broken in some way.

**Comment by unknownbrackets** [comment] 2021-12-10 17:51
Does it work with the cheat in some older version of PPSSPP?  Where did you get the cheat from, and can you ask the author for help?  Maybe it only works if you enable it in certain areas or is otherwise buggy.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-04-15 11:15
Try to use cheat from this github
https://github.com/Saramagrean/CWCheat-Database-Plus-

**Comment by unknownbrackets** [comment] 2022-08-21 21:15
We fixed some bugs in how this game loads, which may have corrected issues in memory allocation.  This means that the addresses cheats target may no longer be valid, and the cheat may have to be recreated.

Anyway, the exception error message shows that the cheat tried to make the game jump to a very weird memory address which is invalid.  This means some value is wrong.

I'm going to close this because it's an issue with the cheat.

-[Unknown]

**Closed by unknownbrackets** 2022-08-21 21:15 UTC
