### ISSUE TITLE
Layer glitch 

### ISSUE THREAD

**Issue by YatoGami** [hrydgard/ppsspp#7727] opened 2015-05-04 01:21 UTC
In the game Super Robot Taisen Z2: Saisei-Hen, there is an issue with the screen which I believe to be an issue with the layers. Each time a cutscene, the images seem to be messed up. I have tried re-downloading the game and getting the game from different sources however, that does not seem to fix it. I am on a jailbroken Iphone 5. Please fix this issue if you could.
![image](https://cloud.githubusercontent.com/assets/12226791/7447950/40871da4-f1da-11e4-882b-b01937631a68.jpg)

**Comment by unknownbrackets** [comment] 2015-05-04 01:23
Pretty sure this is a duplicate of #1313.  Unfortunately, those GPUs just don't deal with some OpenGL features correctly.  We haven't found a workaround yet.

-[Unknown]

**Closed by unknownbrackets** 2015-05-04 01:23 UTC
