### ISSUE TITLE
[Android] hardbinded 'built-in.Back as Call PPSSPP system menu' key makes unable to use 'Select key' on pad

### ISSUE THREAD

**Issue by hong620** [hrydgard/ppsspp#10966] opened 2018-04-25 18:41 UTC
sorry for posting duplicated issue of #7254

it's seriously critical issue lefted many years on uncore part of the ppsspp.
but no one attend about that and those thread so i've repost issue as new thread.

as already posted in that thread, works fine on other android apps that using Android Gamepad and other Controller API.

those are doesn't apeared this kind of 'hardbined key' issues.
even ppsspp on RetroArch doesn't have that issue cause this is uncore part issue.

my android device is impossible to record this issue cause so outdated, (and reproduce it makes device and entirr OS itself hang)
but if you wanna more specific enviorment to reproduce this issues, ping to me.

**Comment by unknownbrackets** [comment] 2018-04-25 19:41
This issue is being closed as a duplicate of #7254.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-04-25 19:41 UTC
