### ISSUE TITLE
Gamepad menu navigation

### ISSUE THREAD

**Issue by uberushaximus** [hrydgard/ppsspp#6565] opened 2014-07-17 03:27 UTC
Gamepad menu navigation doesn't work at all on linux, but works fine on android. Perhaps the button mapping for in-game usage could be used for navigating the UI?

**Comment by unknownbrackets** [comment] 2015-12-22 03:28
Closing this as a duplicate of #7847 which had more discussion.

-[Unknown]

**Closed by unknownbrackets** 2015-12-22 03:28 UTC
Labels: Platform-specific (Linux)
