### ISSUE TITLE
Vulkan: V-sync not working on Nvidia GPU

### ISSUE THREAD

**Issue by Narugakuruga** [hrydgard/ppsspp#11742] opened 2019-01-23 04:13 UTC
Vulkan V-sync not working on Nvidia GPU. When using fullscreen and v-sync turned on, the frames still tear.
This actually is a barrier for Nvidia users to choose vulkan backend.
Dolphin's vulkan works properly on Nvidia GPU(only Nvidia GPU on system).
PPSSPP's vulkan works properly on Intel GPU(only Intel GPU on system).

System info:
Nvidia GTX 1050 Ti.
Graphics Driver 417.71, Graphics options is controlled by PPSSPP.
Windows 10 19H1.
PPSSPP from 1.3 to 1.7.5-3719 (any version).

**Comment by hrydgard** [comment] 2019-01-23 09:45
That's weird, I don't see that at all...

**Comment by unknownbrackets** [comment] 2019-01-25 23:06
Remember that you can disable vsync in the NVIDIA settings, and prevent the "application" (PPSSPP) from controlling it.  Usually, when people have reported this so far, that has been the cause.

I'm not sure if Dolphin does something different, though.

-[Unknown]

**Comment by unknownbrackets** [comment] 2019-01-25 23:07
This issue is being closed as a duplicate of #11136.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-01-25 23:07 UTC
Labels: Platform-specific (Windows)

**Comment by Narugakuruga** [comment] 2019-01-26 03:41
That doesn't explain why PPSSPP's OpenGL v-sync option works normally. When off, the screen tears. When on, the screen doesn't tear.

**Comment by Narugakuruga** [comment] 2019-01-26 03:45
NVIDIA setting pannel does not turn off vsync, but lets 3D applications decide whether they want to usu vsync

**Comment by Narugakuruga** [comment] 2019-03-03 11:32
I found Dolphin's vulkan vsync option will cause a small stuttering when unthrottling, is that the difference compared with PPSSPP?
