### ISSUE TITLE
[OpenGL&Vulkan][Freeze] Saru Getchu PipoSaruRacer (UCJS10032)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12768] opened 2020-03-28 01:18 UTC
### What happens?
[Issue No.1]
Graphic(Text?) drawing issue.
Some Text become to very small. (Only first letter)
This issue happen only OpenGL.
Vulkan is drawing correctly.
**See attached Screenshots & Dumpfile.**

[Issue No.2]
IF you start NewGame then play intro movie.
And game freeze when finish the movie.
You can play the game when if You skip the movie.

Like  a... #11060 
But,This game is not shutdown.
Just, Freeze.

### What *should* happen?
Drawing graphic correctly.(OpenGL)
Don't crash after the intro movie.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-577
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

Dump file here!!
[UCJS10032_0001.zip](https://github.com/hrydgard/ppsspp/files/4396470/UCJS10032_0001.zip)

**[OpenGL ==> Vulakn]**
![pipo_opengl_00](https://user-images.githubusercontent.com/48179091/77811198-3dca3700-70dc-11ea-8702-6fc25e402ee2.png)
![pipo_vulkan_00](https://user-images.githubusercontent.com/48179091/77811218-50dd0700-70dc-11ea-9592-64ce8df4b460.png)

![pipo_opengl_01](https://user-images.githubusercontent.com/48179091/77811225-59354200-70dc-11ea-93bb-2ac1e6a8ff45.png)
![pipo_vulkan_01](https://user-images.githubusercontent.com/48179091/77811226-5cc8c900-70dc-11ea-8a85-7dae628d6eb6.png)

![pipo_opengl_02](https://user-images.githubusercontent.com/48179091/77811229-60f4e680-70dc-11ea-93a9-a38baf03a511.png)
![pipo_vulkan_02](https://user-images.githubusercontent.com/48179091/77811232-65210400-70dc-11ea-8878-4a20cd605716.png)

![pipo_opengl_03](https://user-images.githubusercontent.com/48179091/77811236-6b16e500-70dc-11ea-972c-5390079f0e49.png)
![pipo_vulkan_03](https://user-images.githubusercontent.com/48179091/77811240-6fdb9900-70dc-11ea-8c8a-3b131e1dab4d.png)

**Comment by hrydgard** [comment] 2020-03-28 09:37
This feels like it might be related to https://github.com/hrydgard/ppsspp/issues/12498 . Some wacky viewport invalidation issue maybe?

**Comment by nassau-tk** [comment] 2020-03-28 12:17
I feel similar it.

**Comment by unknownbrackets** [comment] 2020-04-12 00:40
Excitingly, despite likely being a flushing issue, this does reproduce in the GE dump.  The red character is at 21/34.

The problem is that ApplyDrawState is updating shader uniforms, but we only check for that when getting the vshader (before ApplyDrawState.)  It only affects GLES, though.

-[Unknown]

**Comment by nassau-tk** [comment] 2020-04-12 01:57
@hrydgard 
@unknownbrackets 
If I provided with useful information of improvement, I'm happy.

**Comment by unknownbrackets** [comment] 2020-04-12 02:00
Yep, the detail and dump were very useful indeed.

Unfortunately, I'm not sure about the crash.  There are other games that crash when you do or don't skip the video, and I suspect it's a timing issue.

-[Unknown]

**Comment by nassau-tk** [comment] 2020-04-14 06:08
Good!
The issue of strange text was solved!!

And, some movie issue is happend many games.
I hope you beat them future!

**Comment by sum2012** [comment] 2020-05-03 03:00
v1.9.3-731-gf82e7a4e7-windows-amd64 media log:
https://gist.github.com/sum2012/ac1a6122c313b2acdcb04e3f4b36eb6f
The game did not call ScempegDelete so that  the game  hang,

**Comment by sum2012** [comment] 2020-05-03 05:09
JPCSPTrace log:
https://gist.github.com/sum2012/a944dcc12bd10fa945945410540f4eb8

Change UNIMPL sceMpegAvcDecodeStopY
Memory::Write_U32(0, statusAddr);	 to  Memory::Write_U32(1, statusAddr);
No help

**Comment by sum2012** [comment] 2020-12-23 13:22
I might want to do again jpcsptrace with more mpeg function to more understand in future

**Comment by sum2012** [comment] 2020-12-23 14:34
update ppsspp log to v1.10.3-1375-g52c6169a5
https://gist.github.com/sum2012/52e616ba085f81b91fc887bf2c0b488c/raw/8f7907ac64e9b0544da0eac954df493847be249e/gistfile1.txt

**Comment by sum2012** [comment] 2020-12-24 13:37
@nassau-tk I cannot reproduce freeze in this build.
Please check again.Thanks
https://drive.google.com/file/d/1YamV2gBdOSZWHFSrFxda2HmdCa87FcBM/view?usp=sharing

**Comment by nassau-tk** [comment] 2020-12-24 14:29
@sum2012 

I got log by your customized PPSSPP files.
https://gist.github.com/nassau-tk/e5c51b988d70cf24e04dfcc6f4f4df77

And, I got a movie of Issue point.
Please see below. (My Google Drive.)
https://drive.google.com/file/d/1imb6XBSldLz8xhKv03GSJzxkHdjwDEiW/view?usp=sharing

This issue is not appear "Invalid Memory Access(Blue Screen)".
Just freeze.

**Comment by sum2012** [comment] 2020-12-24 14:55
Please see my video,I cannot reproduce anymore
https://youtu.be/PjTVhsmf8U4

**Comment by nassau-tk** [comment] 2020-12-24 15:13
What!?
Why!?

I tested on other PC too.
PPSSPP: sum2012 custom
OpenGL
OS: Windows10(64-bit)
CPU: Intel i7-4770K
GPU: NVIDIA GeForce GTX750Ti
RAM:16GB

But, Result is same.(Freeze)

Um.... I don't have any idea.

**Comment by sum2012** [comment] 2020-12-24 15:16
Let @hrydgard  merge that change,then we test again

**Comment by nassau-tk** [comment] 2020-12-25 04:33
@sum2012

Oh!! Sorry!!
I misstake the extract target folder.
So,I couldn't check right on your custom PPSSPP.

And, I re-tested the it.

"Result"
Saru Getchu PipoSaruRacer (UCJS10032) #12768 Freeze issue is solved!!

ppsspp-v1.10.3-1375m1-g52c6169a5-windows-amd64
ppsspp-v1.10.3-1383m-windows-amd64
Both OK!

**Comment by sum2012** [comment] 2020-12-26 21:48
@nassau-tk 
My 's mpeg warm up patch have merged.Can you test again ?

**Comment by nassau-tk** [comment] 2020-12-27 06:40
@sum2012 

Yes, I tested on Windows(64-bit).
Result : Not happen the freeze.

And, I tested on Xperia Z1 Compact (Android 9)
Result : Not happen the freeze.

**Comment by sum2012** [comment] 2020-12-27 07:09
Good news :)
Closing

**Comment by sum2012** [comment] 2021-02-01 12:31
My warm up staff now only for firmware >= 6
Reopening this.

**Comment by sum2012** [comment] 2021-02-01 12:31
Hope find correct fix in v1.12

**Comment by sum2012** [comment] 2021-02-01 12:33
The game's firmware is 2.81

**Comment by sum2012** [comment] 2021-02-01 13:30
JPCSPTrace log: (I play 2 times video to get scempegfinish logging)
https://gist.github.com/sum2012/aa23043a93538ff6bed7520776c51fd7

Real psp  sceMpegGetAvcAu return ERROR_MPEG_NO_DATA near at the end of video.
sceMpegGetAtracAu return 0

**Comment by sum2012** [comment] 2022-10-04 11:03
@nassau-tk  Yes,it is solved

**Closed by sum2012** 2022-10-04 11:03 UTC
Labels: PSMF / MPEG

**Comment by sum2012** [comment] 2022-10-04 11:24
Fix by my pull request #16106 :)
