### ISSUE TITLE
Fate unlimited blade codes online issue 

### ISSUE THREAD

**Issue by mainsaber** [hrydgard/ppsspp#14457] opened 2021-05-13 22:41 UTC
The fps in online adhoc servers with this game up the fps limit to 40 or 60 making the game too fast or looking like playing in 2x velocity, there is no way to make the fps limit to 30 to correct this? because offline the game is native 30fps

**Comment by MojoJojoDojo** [comment] 2021-05-14 09:37
There is already an issue on it https://github.com/hrydgard/ppsspp/issues/13452
The workaround for now is to underclock the CPU to approx 100 MHZ (emulated CPU option in System settings).
And then it will be 30 fps. @mainsaber

**Comment by mainsaber** [comment] 2021-05-14 10:11
![Screenshot_20210514-070910](https://user-images.githubusercontent.com/84158054/118256144-8a5d0700-b483-11eb-9986-d5736ccfc108.png)

**Comment by mainsaber** [comment] 2021-05-14 10:12
The change emulated psp cpu clock? I dont need to activate the force real clock sync to play online or i need it?

**Comment by MojoJojoDojo** [comment] 2021-05-14 10:12
you can also use that but not have to.
Yeah the emulated psp cpu clock option.

**Comment by mainsaber** [comment] 2021-05-14 10:14
Ah thanks, i hope they can put a fps limiter or a option to play in 30fps or 60fps in online

**Comment by mainsaber** [comment] 2021-05-14 10:15
Just a final question both players need to do this? Or just one of the players?

**Comment by MojoJojoDojo** [comment] 2021-05-14 10:17
both players

**Comment by mainsaber** [comment] 2021-05-14 10:18
Thanks for the help my friend

**Comment by unknownbrackets** [comment] 2021-05-21 05:12
This issue is being closed as a duplicate of #13452.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-05-21 05:12 UTC
Labels: Networking / adhoc
