### ISSUE TITLE
Savedata IO broken every other time

### ISSUE THREAD

**Issue by Linblow** [hrydgard/ppsspp#14355] opened 2021-04-05 18:12 UTC
### What happens?

The game cannot load or write to savedata.
The game says it's loading/saving, and remains stuck like that forever.
Curiously though, it happens every other time in the same PPSSPP instance:
- Game 1st time run: FAIL infinite savedata loading/writing
- 2nd run: OK savedata gets normally loaded/written
- 3rd run: FAIL
- 4th run: OK
- etc

### What *should* happen?

The game should succesfully load or write to savedata every time.

### Which games?

So far, the only games which I know are affected are the following:
- SOCOM: FireTeam Bravo 2 (UCUS98645)
- SOCOM: FireTeam Bravo 1 (UCUS98615)

I don't know whether other games are affected by this issue.
You can [get FTB2_US here](https://static.socom.cc/original_iso/) for testing.

### Context

OS: Windows 7 x64 (windows-amd64)
Tested with both PPSSPP x32/x64 and Debug/Release.
Tested with both my PPSSPP settings, and the default settings.
Cheats and plugins are off.

The issue appeared between `v1.11.2-46-g0a1303b06` and `v1.11.2-52-g5ed594780`.
Issue still exists in the latest dev build (`v1.11.2-384` as of writting).
**Savedata IO works normally in `v1.11.2-44-g9b13220f4` and earlier.**

See [video for comparison between issue vs normal](https://youtu.be/A9xSSKr_3uU).

**Comment by ANR2ME** [comment] 2021-04-05 19:20
Have you tried changing the I/O Timing method? may be need to use Simulate UMD

**Comment by Linblow** [comment] 2021-04-05 19:35
Yeah I have. Regardless, the settings remain exactly the same between v1.11.2-44-g9b13220f4 and older.
Therefore, the change is not specific to user settings.

**Comment by ANR2ME** [comment] 2021-04-05 21:19
Okay i can reproduce this on Socom Bravo 1, probably Bravo 2 too (didn't tested this), while Bravo 3 didn't have this issue.

This is the Logs when it stuck forever
![image](https://user-images.githubusercontent.com/7974720/113628521-347c8e80-968f-11eb-93f1-d7c24dce4d31.png)

And this is the Logs when it successfully loaded the savedata
![image](https://user-images.githubusercontent.com/7974720/113628596-4eb66c80-968f-11eb-988f-e1264e44eff8.png)

**Comment by Linblow** [comment] 2021-04-05 22:01
Perhaps this is related to the volatile memory lock

**Comment by Linblow** [comment] 2021-04-05 22:06
Perhaps it is related to the volatile memory lock

**Comment by Linblow** [comment] 2021-04-05 23:33
Issue is caused by `PSPDialog.cpp:47` :
`volatileLocked_ = KernelVolatileMemLock(0, 0, 0) == 0;`

It can't acquire the lock every other time, and thus won't update the status (`changeAllowed` always `false`)

**Comment by Linblow** [comment] 2021-04-06 01:41
Alright I fixed it. Will send PR tomorrow.

**Comment by unknownbrackets** [comment] 2021-04-06 03:37
It is necessary for volatile status to be tracked.  Is something on the dialog not being reset?

-[Unknown]

**Comment by Linblow** [comment] 2021-04-06 21:19
Nevermind my fix was a bad workaround. 
I know for sure the following facts:
- Game makes lots of calls to `sceKernelVolatileMemTryLock()` and `sceKernelVolatileMemUnlock()`
- The savedata dialog is GUI-less
- Every other time, the PSPDialog won't be able to acquire the lock

**Comment by Linblow** [comment] 2021-04-06 23:50
Here is what happens in order:
1. Game calls `sceKernelVolatileMemTryLock()` and gets the lock.
2. Game calls `sceUtilitySavedataGetStatus` ->`PSPDialog::GetStatus()` which calls `KernelVolatileMemLock()`.
Utility dialog doesn't get the lock since the game currently has it.
Dialog status code remains the same (initialized).
3. Game calls `sceKernelVolatileMemUnlock()` and releases the lock

Repeat step 1 to 3 forever, thus blocking forever..
I then exit the game (Ctrl+W), and the log shows one successfull call to `KernelVolatileMemLock()` (without the step 1)
Member `volatileLocked_` of PSPDialog is now `true`

I boot the game again.
This time, no call to `KernelVolatileMemLock()` is done since `volatileLocked_` is `true`.
Game proceeds to load savadata, and run.

I exit the game again, and we are back to our problem.

The PSP dialog utility runs in the same thread as the game (user_main), doesn't it?
On the PSP, utility dialogs are run in seperate thread(s).
Perhaps that's the real issue, I don't know

**Comment by ANR2ME** [comment] 2021-04-07 00:53
As i remembered on JPCSP Dialog runs on it's own thread, not sure if this is true on a real PSP or not tho.

One thing for sure that it should show the same behavior on each attempt to run the game after ending/exiting, instead of switching from stuck and not stuck on each attempt like that.

**Comment by unknownbrackets** [comment] 2021-04-07 01:09
Okay, so we're missing a state reset on the dialogs.  That won't fix this issue, but it'll make it consistent.

We do use a PSP thread:
https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceUtility.cpp#L263

But currently only for shutdown.  Sounds like we'll need the same for init.

-[Unknown]

**Comment by ANR2ME** [comment] 2021-04-08 11:29
It seems to be fixed on the latest dev build, it's no longer stuck
![image](https://user-images.githubusercontent.com/7974720/114019118-3a918b80-9898-11eb-876b-707aa9658f1d.png)

Btw, @Linblow are you the owner of socom.cc ?

**Comment by Linblow** [comment] 2021-04-08 17:52
#14364 has fixed apparently the issue. Thanks unknownbrackets

@ANR2ME That's correct. You should know I'm working on a remake of the whole adhoc client/server, as well as the PSP sockets API

**Closed** 2021-04-08 18:04 UTC

**Comment by ANR2ME** [comment] 2021-04-08 22:28
> 
> 
> #14364 has apparently fixed the issue. Thanks unknownbrackets
> 
> @ANR2ME That's correct. You should know I'm working on a remake of the whole adhoc client/server, as well as the PSP sockets API

Will it still be compatible with pro-online client/plugin on PSP and PSP emulators?

I do wished they use number of bytes at the start the opcode packet, so we can add additional info like version, port offset, etc. this can allow players to use different port offset, thus allowing the same IP (as long their port offset are different), and the port offset value can also be used as tunneling port if we later support tunneling.
