### ISSUE TITLE
add FSR upscaling filter

### ISSUE THREAD

**Issue by Deka710** [hrydgard/ppsspp#17580] opened 2023-06-14 23:09 UTC
### What should happen

would be nice if PPSSPP could add this feature
![Screenshot_2023-06-15-06-05-26-670_org yuzu yuzu_emu](https://github.com/hrydgard/ppsspp/assets/97207704/709c5deb-5589-43dc-a020-2329f7d57d94)

### Who would this benefit

.

### Platform (if relevant)

None

### Games this would be useful in

.

### Other emulators or software with a similar feature

yuzu Android/PC and Vita3K android/PC

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment] 2023-06-15 00:31
Closing as a duplicate of #14689

 IMO FSR is pretty useless for PPSSPP, it benefits a scenario of GPU intensive games on weak gpu's.
 PPSSPP is light enough to run on pretty much any potato and users with really low end hardware might hope to run games with higher res with it due to how it's advertised on PC's, however while FSR appears free on desktop gaming hardware, it's NOT actually "free" and is actually pretty heavy compared to typical post process shaders which those low-end-hardware PPSSPP users already might find too slow to use.

**Closed by LunaMoo** 2023-06-15 00:31 UTC

**Comment by Deka710** [comment] 2023-06-15 00:34
> Closing as a duplicate of #14689
> 
> IMO FSR is pretty useless for PPSSPP, it benefits a scenario of GPU intensive games on weak gpu's. PPSSPP is light enough to run on pretty much any potato and users with really low end hardware might hope to run games with higher res with it due to how it's advertised on PC's, however while FSR appears free on desktop gaming hardware, it's NOT actually "free" and is actually pretty heavy compared to typical post process shaders which those low-end-hardware PPSSPP users already might find too slow to use.

well its an option and low end users should not use it

**Comment by ani917** [comment] 2026-07-04 10:21
> [](https://github.com/hrydgard/ppsspp/issues/14689)
> 
> IMO FSR is pretty useless for PPSSPP, it benefits a scenario of GPU intensive games on weak gpu's. PPSSPP is light enough to run on pretty much any potato and users with really low end hardware might hope to run games with higher res with it due to how it's advertised on PC's, however while FSR appears free on desktop gaming hardware, it's NOT actually "free" and is actually pretty heavy compared to typical post process shaders which those low-end-hardware PPSSPP users already might find too slow to use.

fsr easu is a relatively lightweight shader by modern standards
