### ISSUE TITLE
Sound stuttering

### ISSUE THREAD

**Issue by ThienNTran73** [hrydgard/ppsspp#9292] opened 2017-02-08 02:30 UTC
Hi, 
I have some issues with my sound when I play Ultimate Ninja Storm Impact...
Basically, when multiple enemy spawn or when I try to use some combos, the sound sometimes stutter a little bit. I've tried lowering my settings but nothing changed :(
Version: Dev-Working (iOS) 0v1.3-530-ge5c20b4
Phone: iPhone SE
OS: iOS 10.2 (Jailbroken with Yalu)
Please help :(

**Comment by LunaMoo** [comment] 2017-02-08 03:35
Sound stutters when your device can't maintain full speed.
 It's also a duplicate of #9197 which was introduced by new iOS version and might never be solved on ppsspp side, quite likely ppsspp is just blocked from using full power of the device by new iOS hence the slowdown causing stutters, but either way we don't want duplicates, so I'll close this one.

 Next ppsspp release version might include #8717 which should help in situations like this, "stretching"/slowing down sound to avoid dropping it completely so best just wait for when that get's merged and trying it out.

**Closed by LunaMoo** 2017-02-08 03:35 UTC
