### ISSUE TITLE
native JIT for PPSSPP on trollstore (non jailnroken) 

### ISSUE THREAD

**Issue by ansinerd** [hrydgard/ppsspp#16814] opened 2023-01-16 22:16 UTC
### What should happen

PPPSSP has been wonderful emulator. 
the native jit debug works jailbroken devices and on jailed devices the interpreter works most of time except when it doesnt.
Trollstore provides solution to many who are not jailbroken but can use entitlement to achieve native JIT on ppsspp.

pojavalaumcher, dolphin and UTM etc are already taking advantage of it.
Ptrace method to achieve JIT
and entitlements to achieve it on trollstore.
Right now ppsspp when installed through trollstore doesn’t appear in Files/Documents/PPSSPP instead appears in var/mobile/Documents/PPSSPP 
But running certain entitlements would ensure it appears in files app.
entitlements :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.private.security.storage.AppDataContainers</key>
    <true/>
    <key>com.apple.private.security.no-sandbox</key>
    <true/>
    <key>com.apple.developer.kernel.extended-virtual-addressing</key>
    <true/>
    <key>com.apple.developer.kernel.increased-memory-limit</key>
    <true/>
    <key>get-task-allow</key>
    <true/>
    <key>com.apple.security.iokit-user-client-class</key>
    <array>
        <string>IOSurfaceRootUserClient</string>
        <string>AGXDeviceUserClient</string>
        <string>AGXSharedUserClient</string>
        <string>AGXCommandQueue</string>
        <string>AGXDevice</string>
    </array>
    <key>platform-application</key>
    <true/>
</dict>
</plist>
```

### Who would this benefit

It will benefit thousands of ios users who are on trollstore compatible firmware but not on jailbroken firmware / don’t want to jailbreak for certain reasons. It will help people with older devices to have advantage of JIT and may be extended VRAM as well.

its a humble request. Please do make it a possibility.

thanking you in advance.

### Platform (if relevant)

iOS

### Games this would be useful in

Almost all games. Especially Metal Gear Solid.

### Other emulators or software with a similar feature

Pojavalauncher, dolphinios and UTM.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment] 2023-01-16 22:48
Closing as a duplicate of #16019

**Closed by LunaMoo** 2023-01-16 22:48 UTC
