### ISSUE TITLE
Cannot build with option -DVULKAN=ON in Linux and solution

### ISSUE THREAD

**Issue by bugalo** [hrydgard/ppsspp#16330] opened 2022-11-03 22:10 UTC
### Platform

Linux / BSD

### Compiler and build tool versions

gcc-12.2.1 and cmake 3.24.2

### Operating system version

Gentoo Linux

### Build commands used

cmake . -DLIBRETRO=ON -DVULKAN=ON -DUSE_FFMPEG=ON -DUSE_SYSTEM_FFMPEG=OFF -DUSE_DISCORD=OFF -DUSE_MINIUPNPC=OFF

gmake platform="unix-opengl" -j16 CC="gcc" CXX="g++" DLIBRETRO=ON DVULKAN=ON DUSE_FFMPEG=ON DUSE_SYSTEM_FFMPEG=OFF DUSE_DISCORD=OFF DUSE_MINIUPNPC=OFF

### What happens

I only get this error when including the flag -DVULKAN=ON

```
/home/libretro-super/libretro-ppsspp/ext/libzip/zip_name_locate.c:65:41: error: ‘strcasecmp’ undeclared (first use in this function); did you mean ‘strncmp’?
```

I was able to fix it by adding 

```
#include "config.h"
```

Right at the beginning of file: ```ext/libzip/zip_name_locate.c```

### PPSSPP version affected

Latest git build

### Last working version

N/A

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment] 2022-11-13 19:09
Well, it seems like zipint.h should actually be higher, but that's how it is in libzip.

Does https://github.com/nih-at/libzip build for you as-is?

I wonder if this is actually a libretro build script issue, because this is a `.c` file anyway.  It should be a warning, not an error.  As an example:
https://stackoverflow.com/questions/50496264/why-does-c-allow-me-to-call-an-undeclared-function

I'm pretty sure PPSSPP standalone compiles fine on Gentoo as well?

-[Unknown]

**Comment by gouchi** [comment] 2024-04-08 09:12
Hi,

Is it still an issue ?

On Lakka, we are [building it](https://github.com/libretro/Lakka-LibreELEC/blob/139b8c19dec564e63b31d9ecf4e894e3a4232cc5/packages/lakka/libretro_cores/ppsspp/package.mk#L11-L19) without issue when we enabled `-DVULKAN=ON`.

If the issue is specific to `libretro-super`, please open an issue to the [dedicated repository](https://github.com/libretro/libretro-super).

Thank you.

**Comment by hrydgard** [comment] 2024-04-10 07:19
I'll close this as outdated. Please re-open if it happens again.

**Closed by hrydgard** 2024-04-10 07:19 UTC
Labels: Libretro
