### ISSUE TITLE
Phantasy star portable

### ISSUE THREAD

**Issue by ilego1** [hrydgard/ppsspp#19508] opened 2024-10-04 21:44 UTC
### Game or games this happens in

ULUS-10410

### What area of the game / PPSSPP

The job skill max cheat from cheat.db doesn’t work

### What should happen

I should have hunter level maxed

### Platform

iOS

### Mobile device model or graphics card (GPU)

A13 apple

### PPSSPP version affected

PPSPP 1.17.4-1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment] 2024-10-04 22:08
This is an issue tracker it's a place for posting issues with the emulator, not with cheats which if poorly made to work by patching variables in memory instead of game code can be affected by #11167 and aren't compatible between psp and ppsspp.

 Closing as a duplicate of the mentioned issue as well as not being place to talk about specific cheat compatibility. To talk about that, talk to the person that shared the cheat.db you're using.

**Closed by LunaMoo** 2024-10-04 22:08 UTC
