### ISSUE TITLE
(SDL) The fullscreen keybind toggle does not work in the menu

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#11992] opened 2019-04-24 14:13 UTC
### What happens?

When using the SDL frontend the fullscreen keybind toggle does not work.

In `Settings -> Controls -> Control mapping -> Toggle fullscreen` I set it to `F11` where it shows `kbd.F11` and found it does nothing. I next set it to the `f` key (`kbd.F`) and it still does nothing.

The menu toggle however does work while the Qt frontend which has the opposite issue where the menu toggle does not work and the keybind toggle does work with `F11`. (Issue https://github.com/hrydgard/ppsspp/issues/11626).

This is followup to issue https://github.com/hrydgard/ppsspp/issues/11625 where fullscreen has been problematic with the SDL frontend for a long time.

### What *should* happen?

The fullscreen keybind toggle should work in the SDL frontend.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

OS: `Slackware64-current`
ppsspp: https://github.com/hrydgard/ppsspp/commit/d15a6cf6bff3bea6adbebeaf2ee6dd973d381b19
SDL: `2.0.9`
GPU: `AMD RX Vega 56` (amdgpu + radeonsi)

**Comment by unknownbrackets** [comment] 2019-04-25 02:09
Is this different from #11974?  It sounds like you get entirely different behavior which is possibly distro or window manager specific?

-[Unknown]

**Comment by orbea** [comment] 2019-04-25 04:05
Yes, both of my two recent issues are different than that issue. I can't reproduce that issue with the master since it was fixed recently for me.

**Comment by vnctdj** [comment] 2020-06-24 21:08
I can't reproduce this (not sure if I have ever reproduced it though).
What about you @orbea?

**Comment by orbea** [comment] 2020-06-25 03:27
Yes, its broken here still...

**Comment by hrydgard** [comment] 2020-06-25 06:59
In game or in the menu? Works for me in-game but not in the PPSSPP menu screens.

Though, that probably should be fixed.

**Comment by orbea** [comment] 2020-06-25 13:22
I see what you mean, but its kind of both.

* Like you say, in the menu its entirely ignored.
* If I start ppsspp with fullscreen disabled and then start a game, it works fine.
* If I start ppsspp with fullscreen enabled and then start a game, I can see that it leaves fullscreen mode, but the it never resizes the window accordingly like when its started without fullscreen.

I think this needs two fixes.

1. It should work in the menu as well as in game.
2. When started fullscreen it should still know the size of the window when not fullscreen in case the player toggles it.

**Comment by hrydgard** [comment] 2020-06-25 13:47
Aha! That's a much better report, thank you, now it makes sense. Yeah in this case it should avoid remembering the fullscreen window size indeed.

**Comment by orbea** [comment] 2020-06-25 14:20
@hrydgard I now remember I made a second issue for the fullscreen size here. https://github.com/hrydgard/ppsspp/issues/11991

**Comment by vnctdj** [comment] 2020-06-25 21:07
So... This issue can now be closed as a duplicate of https://github.com/hrydgard/ppsspp/issues/7542 :)

**Comment by hrydgard** [comment] 2020-06-25 21:12
Duplicate of #7542.

**Closed by hrydgard** 2020-06-25 21:12 UTC
Labels: SDL2
