### ISSUE TITLE
PSPo2i Crash On Startup or Entering New game

### ISSUE THREAD

**Issue by Chriszxz** [hrydgard/ppsspp#13680] opened 2020-11-20 08:41 UTC
### What happened?
Phantasy Star Portable 2 Infinity crashes on start of the game or when entering new game

### What *should* happen?
It probably shouldn't crash

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Oppo A37
Qualcomm MSM8916 Snapdragon 410
Adreno 306
Android 5.1 (ColorOS 3)

### Additional Info
[demo1.zip](https://github.com/hrydgard/ppsspp/files/5572281/demo1.zip)
[Crash on startup.txt](https://github.com/hrydgard/ppsspp/files/5572283/Crash.on.startup.txt)

[demo2.zip](https://github.com/hrydgard/ppsspp/files/5572286/demo2.zip)
[Crash when entering new game.txt](https://github.com/hrydgard/ppsspp/files/5572294/Crash.when.entering.new.game.txt)

**Comment by sum2012** [comment] 2020-11-20 11:57
Patched game does not officially solve

**Comment by sum2012** [comment] 2020-11-20 12:49
Can you test original japan version ?

**Comment by Chriszxz** [comment] 2020-11-20 15:12
Nope still crashes.

**Comment by Chriszxz** [comment] 2020-11-20 15:13
@sum2012  do I also need to provide the logs in jpn version?

**Comment by Chriszxz** [comment] 2020-11-20 15:32
``28:21:858 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [68:ba:0e:0c:37:4f]
28:23:420 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /storage/emulated/0/MIUI/ShareMe/Phantasy Star Portable 2 Infinity JPN PSP-Caravan/Phantasy Star Portable 2 Infinity JPN PSP-Caravan.iso...
28:23:880 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
28:23:897 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
28:23:927 user_main    E[SCEKERNEL]: HLE/sceKernel.cpp:693 UNIMPL sceKernelReferGlobalProfiler(deadbeef)
28:25:834 SOUND_THREAD E[ME]: HLE/sceAtrac.cpp:1696 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range
28:29:169 SOUND_THREAD E[ME]: HLE/sceAtrac.cpp:1696 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range

**Comment by Chriszxz** [comment] 2020-11-20 15:33
> 28:21:858 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [68:ba:0e:0c:37:4f]
28:23:420 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /storage/emulated/0/MIUI/ShareMe/Phantasy Star Portable 2 Infinity JPN PSP-Caravan/Phantasy Star Portable 2 Infinity JPN PSP-Caravan.iso...
28:23:880 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
28:23:897 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
28:23:927 user_main    E[SCEKERNEL]: HLE/sceKernel.cpp:693 UNIMPL sceKernelReferGlobalProfiler(deadbeef)
28:25:834 SOUND_THREAD E[ME]: HLE/sceAtrac.cpp:1696 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range
28:29:169 SOUND_THREAD E[ME]: HLE/sceAtrac.cpp:1696 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range

**Comment by Chriszxz** [comment] 2020-11-20 15:36
``28:21:858 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [68:ba:0e:0c:37:4f]
28:23:420 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /storage/emulated/0/MIUI/ShareMe/Phantasy Star Portable 2 Infinity JPN PSP-Caravan/Phantasy Star Portable 2 Infinity JPN PSP-Caravan.iso...
28:23:880 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
28:23:897 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
28:23:927 user_main    E[SCEKERNEL]: HLE/sceKernel.cpp:693 UNIMPL sceKernelReferGlobalProfiler(deadbeef)
28:25:834 SOUND_THREAD E[ME]: HLE/sceAtrac.cpp:1696 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range
28:29:169 SOUND_THREAD E[ME]: HLE/sceAtrac.cpp:1696 80630016=sceAtracResetPlayPosition(0, 0, 0, 0): first byte count not in valid range``

**Comment by Chriszxz** [comment] 2020-11-20 15:37
[logcat.txt](https://github.com/hrydgard/ppsspp/files/5574477/logcat.txt)

**Comment by sum2012** [comment] 2020-11-20 22:39
What is render mode result ?
OpenGL and Vulkan

**Comment by Chriszxz** [comment] 2020-11-21 03:38
My phone doesn't support Vulkan so my render mode is OpenGl.

**Comment by sum2012** [comment] 2020-11-21 04:52
Do just this game has problem?

在 2020年11月21日週六 上午11:39，Chriszxz <notifications@github.com> 寫道：

**Comment by Chriszxz** [comment] 2020-11-21 09:18
All of the other games are working. I even tried the dumped psn version of this game hoping it would work for the reason that it have a different hash than the dumped umd. But it didn't.

**Comment by Chriszxz** [comment] 2020-11-21 09:25
This game runs perfectly on my realme c2, but in this particular device it wouldn't. Does it mean that it's a device specific bug?

**Comment by sum2012** [comment] 2020-11-21 13:14
From mywindows log just it is ineresting
33:55:442 user_main    W[SCEKERNEL]: hle\scekernel.h:462 Kernel: Bad DirListing handle -2147418110 (80010002)
Full log: https://gist.github.com/sum2012/52332089373baa20f1fdff78ca21781a

**Comment by Chriszxz** [comment] 2020-11-22 01:36
Did you replicate it?

**Comment by sum2012** [comment] 2020-11-22 01:37
no

在 2020年11月22日週日 上午9:36，Chriszxz <notifications@github.com> 寫道：

**Comment by sum2012** [comment] 2020-11-22 08:18
Can you try v1.7.4 ?
https://apkpure.com/ppsspp-psp-emulator/org.ppsspp.ppsspp/download/17040000-APK

**Comment by Chriszxz** [comment] 2020-11-22 14:38
The game worked in this version. It's the same problem then.

**Comment by sum2012** [comment] 2020-11-22 14:41
Does it mean that can open the iso ,then same problem?

在 2020年11月22日週日 下午10:38，Chriszxz <notifications@github.com> 寫道：

**Comment by sum2012** [comment] 2020-11-22 14:44
i get you mean now.It is same issue as #13542

在 2020年11月22日週日 下午10:38，Chriszxz <notifications@github.com> 寫道：

**Comment by Chriszxz** [comment] 2020-11-22 14:44
Yes, probably.

**Comment by Chriszxz** [comment] 2020-11-22 14:44
What can I do to further help in this problem.

**Comment by sum2012** [comment] 2020-11-22 14:51
you should also v1.08 have problem
There is no offical build between v1.74 and 1.08
When i have time,I compile the middle version to test
You might need  to 15 times to test
Sorry,I need to sleep now

在 2020年11月22日週日 下午10:44，Chriszxz <notifications@github.com> 寫道：

**Comment by Chriszxz** [comment] 2020-11-22 14:57
Okay then. Thanks!

**Comment by sum2012** [comment] 2020-11-22 22:35
I don't compile on time this day.
So that I just keep you test v1.8 to ensure the problem
https://www.ppsspp.org/files/1_8_0/ppsspp.apk

**Comment by Chriszxz** [comment] 2020-11-23 00:28
Doesn't work in 1.8.0.

**Comment by sum2012** [comment] 2020-11-23 13:34
Sorry,I forget how to compile in android
I am too long don't do it

**Comment by sum2012** [comment] 2020-11-23 13:38
@hrydgard  can you help to follow up ?
I forget that how to compile in android.
He answered that work in v1.7.4 not work in v1.8.0

**Comment by CrimsonSZ-Q** [comment] 2020-11-24 01:09
> This game runs perfectly on my realme c2, but in this particular device it wouldn't. Does it mean that it's a device specific bug?

Why on my Realme C2 got blackscreen after intro ?

**Comment by Chriszxz** [comment] 2020-11-24 01:11
Maybe your iso is corrupted. Check the hash if it matches the original.

**Comment by Gamemulatorer** [comment] 2021-06-12 12:11
It doesn't crash on my phone redmi note 9
using ppsspp github apk and ppsspp gold version 🤔

**Comment by Chriszxz** [comment] 2021-06-13 02:08
> @Chriszxz It doesn't crash on my phone redmi note 9
> using ppsspp github apk and ppsspp gold version 🤔
> ![Screenshot_2021-06-12-20-12-16-061_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/121775492-a7881100-cbba-11eb-8c9a-fb9bf8a23bf5.jpg)
> ![Screenshot_2021-06-12-20-12-24-092_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/121775497-ab1b9800-cbba-11eb-9854-eb3b424c60da.jpg)
> 

Of course it won't crash because your device uses a Mediatek SoC and the problem only exists on any device that uses Adreno 306 GPU.

**Comment by unknownbrackets** [comment] 2021-06-13 04:14
Do we know that it's Adreno 306 only, or all Adreno 3xx?  If it works on other Adreno 3xx, it would make me think this is actually a driver bug - which might be hard to workaround.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-06-13 04:15
> 
> Of course it won't crash because your device uses a Mediatek SoC and the problem only exists on any device that uses Adreno 306 GPU.

So this should probably be a duplicate of https://github.com/hrydgard/ppsspp/issues/13542

**Comment by unknownbrackets** [comment] 2021-06-13 04:19
If so, that issue says it used to work.  If this also behaves the same, working in v1.7.4 and crashing in v1.8.x, then I'd close one of these as a duplicate.  It'd help to narrow down what change was made, but since the version is pretty old, that'd probably involve a compiler.

-[Unknown]

**Comment by Chriszxz** [comment] 2021-06-13 15:25
> If so, that issue says it used to work.  If this also behaves the same, working in v1.7.4 and crashing in v1.8.x, then I'd close one of these as a duplicate.  It'd help to narrow down what change was made, but since the version is pretty old, that'd probably involve a compiler.
> 
> -[Unknown]

Indeed

**Closed** 2021-06-13 15:26 UTC
