### ISSUE TITLE
Vulkan: Crash after a while in all games

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10220] opened 2017-12-01 15:29 UTC
this problem occurs in all psp games for ppsspp plus the interesting and that games that weigh more have more textures and elements makes the emulator close faster in 30 minutes and light games makes the emulator close in 1 hour or 1 hour and 30 minutes I have several psp games on my memory cards and I would like to commit myself to the ppsspp team to stabilize the vulkan as soon as possible I can help with testing as soon as I build the builds focused on the ppsspp crash I do the tests in all games and sent to the team as fast as possible with the test report

**Comment by hrydgard** [comment] 2017-12-01 15:34
I don't think you've tried all the games that are available for the PSP, but can you list some examples of light and heavy games that crash after a while?  

Most likely we have some sort of memory or resource leak that eventually grows too big.

Also, what device are you running on?

**Comment by SamueldeSena** [comment] 2017-12-02 00:40
êsbecause these are the games that I tested in vulkan and that are giving error and closing the emulator growing between 30 minutes to 1 hour and 30 minutes this occurs after a certain time inevitably I will separate them are heavy and light games that have between many textures and elements and few textures and elements Light matches from 30 minutes to 1 hour: DRAGON BALL BUDOKAI: DRAGON BALL BUDOKAI 2: DRAGON BALL TENKAICH TAG TEAM: BEN 10 PRETECT OF EARTH: BEN 10 ALIEN FORCE VILKAX ATTAKS: BEN 10 ALIEN FORCE: BEN 10 ULTIMATE ALIEN COSMO DESTRICTION: BLEACH 7: CALL OF DUTY ROADS OF VICTORY: CRASH MIND OVER MUTANT: CRASH OF THE TITANS: CRASH TAG TEAM RANCING: CRISIS CORE FINAL FANTASY: DISSIDIA 012: EVERYBODY`S TENNIS: GOD OF WAR GHOST OF SPARTA: GOD OF WAR OF THE OLYMPUS: THE KING OF FIGHTERS THE OROCHI SAGA: BATMAN THE VIDEO GAME LEGO: MEGAMAN MAVERICK HUNTER X: MARVEL SUPER HERO SQUAD: MARVEL NEMESIS RISE OF THE IMPERFECTS: METAL SLUG ANTHOLOGY: METAL SLUG DOUBLE X : NARUTO HEROS NARUTO ULTIMATE NINJA IMPACT: PATAPON: PATAPON 2: PATAPON 3: TEKKEN 5: SOUL CALIBUR BROKEN DESTINY: VIEWTIFUL JOE RED HOT RUMBLE: YU-GI-OH 5Ds TAG FORCE 5: STREET FIGHTER ALPHA 3 MAX: THE 3rd BIRTHDAY: DEF JAM FIGHT FOR NY THE TAKEOVER: 7TH DRAGON 2020: ASTERIX OBELIX XXL 2: CHILI WITH CARNEGE: BLACK ROCK SHOOTER THE GAME: DEAD RIGHTS RECKONING: FROGGER HELMET CHAOS: FINAL FANTASY TACTICS: THE WAR OF THE LIONS: ULTIMAT GHOSTS`N GOBLINS: GHOST IN THE SHELL: GUILTY GEAR JUDGMENT: GLADIATOR BEGINS: MEDIEVIL: KINGDOM HEARTS BIRTH BY SLEEP FINEL MIX: OBSCURE THE AFTERMATH: PEGGLES: PAC MAN WORLD 3: PERSON 3 POTABLE: STAR WARS 2 BATLEFRONT: WOLVERINE ORIGINS: DEAD JR: HATSUNE MIKU PROJECT DIVA: HATSUNE MIKU PROJECT DIVA 2: HATSUNE MIKU PROJECT DIVA EXTEND: CASTLEVANIA THEDRACULA X CHRONICLES: HUNTER X HUNTER: HELLBAY THE SCIENCE OF EVIL: MEGAMEN POWER UP: MIAMI VICE: PAC MAN WORLD RALLY: VALKYRIA CHRONICLES 3 : MONKEI BALL ADVENTURE: TRANSFORMES THE GAME: TRANSFORMES REVEGE OF THE FALLEN: SEIYA OMEGA ULTIMATE COSMO: LEGO STAR WARS 3 THE CLONE WARS: UNDEAD KNIGHTS: RESISTANCE RETRIBUTION: SOCOM FIRE BRAVE 3: PRINCE OF PERSIA RIVAL SWORDS: PRINCE OF PERSIA REVELATIONS: DAXTER: FIFA STREET: MONSTER HUNTER FREEDOM UNITER: MORTAL KOMBAT UNCHAINED Heavy games that closes in 30 minutes or less: ARMY OF TWO: METAL GEAR SOLID PEACE WALKER: TEKKEN 6: TOMB RAIDER LEGEND: SPLINTER CELL ESSENTIALS: MIDNIGHT CLUB 3 DUB ADITION: CODED ARMS CONTAGION: 50 CENT BULLETPROOF G UNIT EDITION: BLAZBLUE PORTABLE - SERIOUS ERROR CLOSING IN 10 MINUTES: BLAZBLUE CONTINUUM SHIFT - SERIOUS ERROR CLOSING IN 10 MINUTES: BLAZBLUE CONTINUUM SHIFT EXTEND - SERIOUS ERROR CLOSING IN 10 MINUTES: SIMPSONS THE GAME - MANHUNT 2: ASSASSINS CREED BLOODLINES: GUILTYGEAR XX ACORE PLUS - SERIOUS ERROR CLOSING IN 10 MINUTES: FINAL FANTASY 0: GODS EATER BURTS: GODS EATER 2 THESE ARE GAMES THAT I TESTED IN THE LAST BUILD v1.5.2-43-GA67357db0 I hope my test can help give in the discovery of the problem of vulkan my cell phone and a moto g5s plus ARMv 7 Processor rev 4 (v71) core 8 adreno 506 api version 1.0.31 vesao of vulkan

**Comment by SamueldeSena** [comment] 2017-12-02 21:55
When that problems will be resolved because up to 1.5.3 this problem is occurring

**Comment by hrydgard** [comment] 2017-12-02 23:31
It will be solved when the cause is found...

**Comment by SamueldeSena** [comment] 2017-12-02 23:42
Por favor se você fizer um teste no jogo guilta gear xx acente core plus pela vulkan você provavelmente vai percerber que a uma instabilidade e que esse jogo fecha em 3 minutos por favor faça este teste

**Comment by SamueldeSena** [comment] 2017-12-02 23:46
Please if you take a test in the game guilta gear xx accent core plus by vulkan you will probably notice that to an instability and that this game closes in 3 minutes please do this test

TRADUZIR

**Comment by SamueldeSena** [comment] 2017-12-02 23:52
And I also weight apologies to LunaMoo for having redone another topic with this same problem is that guilta gear xx accent core plus and the game that I most play in this emulator and this problem of closing in 3 minutes by vulkan left me very sorry LunaMoo no excuses I will make this mistake again

**Comment by unknownbrackets** [comment] 2017-12-03 02:45
Does it stop happening if you disable the vertex cache?

-[Unknown]

**Comment by SamueldeSena** [comment] 2017-12-03 02:52
Nao

**Comment by SamueldeSena** [comment] 2017-12-03 03:18
No

**Comment by SamueldeSena** [comment] 2017-12-03 19:18
the build v1.5.3-35-gcc2e162a0 solved the crash problem in guilta gear xx accent core plus after 30 minutes it was still running smoothly

**Comment by SamueldeSena** [comment] 2017-12-03 19:22
I am going to do an intense test of 1 hour with this build in several psp games and I will send the report from here 3 days

**Comment by leopard20** [comment] 2017-12-04 14:18
I've played some games for over 1 hour and I haven't noticed any issue (some even over 2 hours!).
Tested games:
SOCOM Fire team Bravo 1,2 and 3.
Def Jam.
MGS Peace Walker.
PoP Revalations.
Mortal Kombat Unchained.
Assassin's Creed Bloodlines.
Gun Showdown.
Spider-Man 2
Syphon Filter: Dark Mirror AND Logan's Shadow.

I don't assume any of them are light games!

**Comment by hrydgard** [comment] 2017-12-04 14:23
Yeah, seems we're in a pretty good place now. I'm gonna release 1.5.4 tomorrow.

**Comment by unknownbrackets** [comment] 2017-12-04 14:49
Sweet.  May have been related to the hashmaps or other fixes?

I'm going to close this issue - if you're still seeing crashes in some games, we can reopen, or perhaps open more specific issues about those crashes.

-[Unknown]

**Closed by unknownbrackets** 2017-12-04 14:49 UTC
Labels: Vulkan

**Comment by SamueldeSena** [comment] 2017-12-04 21:55
I finished the tests and the new builds fixed the problem of vulkan thanks hrydgard

**Comment by hrydgard** [comment] 2017-12-04 23:25
@SamueldeSena thanks for testing!

**Comment by Lymphocytes** [comment] 2018-01-03 18:57
@hrydgard sorry if its not appropriate to write on old threads so I apologize in advance, but vulkan still seems very unstable on my device. I have an ASUS ZenPad Z8 and the games I've tested are Kingdom Hearts Birth By Sleep, Dissidia Final Fantasy 012 Duodecim, and Silent Hill Shattered Memories. Khbbs and dffd last 30 mins to an hour, and Silent hill hardly works for 10 seconds after loading a save state

**Comment by leopard20** [comment] 2018-01-04 19:57
I can confirm that vulkan is unstable when you load a saved state.
Games having this issue for me:
Splinter Cell Essentials
Soul Calibur

**Comment by hrydgard** [comment] 2018-01-04 23:50
Oh, only when you've loaded a state? Is it a very noticeable difference in stability for when starting games from scratch?

**Comment by leopard20** [comment] 2018-01-05 01:20
I haven't notices any instability in the case you mentioned (v1.5.4)
 
BTW, why do I get a feeling like the development versions are changing for the worse lately.
I haven't tested all games, so while there could be improvements in some games, others (like Brothers in Arms that I mentioned in an issue) have problems now.

Are you changing the codes from the ground up? That could explain a lot!

**Comment by unknownbrackets** [comment] 2018-01-05 02:27
What's the first version that has new problems, and the last version that was fine?  If you narrow it down, we can investigate.

Does loading a save state when using OpenGL not have the same problems?  It's only Vulkan?

-[Unknown]
