### ISSUE TITLE
Crashes when opening from standby on Android when using Vulkan

### ISSUE THREAD

**Issue by genos1213** [hrydgard/ppsspp#13800] opened 2020-12-20 15:56 UTC
When using Vulkan on Android, the app stutters/stalls for a couple seconds when opening from standby and crashes about 1/10th of the time. This doesn't seem to happen with openGL though.

Using a Snapdragon 855 on Android 10, not sure if this issue is known or not.

**Comment by hrydgard** [comment] 2021-01-03 18:22
I'm having some trouble reproducing this. Are we talking in-game? Any specific game that seems to trigger the problem?

**Comment by hrydgard** [comment] 2021-01-04 23:36
Are you using 1.10.3 or the latest builds from https://buildbot.orphis.net/ppsspp/ ?

**Comment by genos1213** [comment] 2021-01-07 23:25
I'm using the latest Play Store version, so 1.10.3. It seems to happen with every game, regardless of what's being rendered, but only with Vulkan. If I just press the menu button and select the app 5-10x times it stutters at first and eventually crashes. I don't think I've ever seen anybody else with the issue so it could just be my phone's GPU drivers? I'm using a Xiaomi Mi 9T Pro.

**Comment by unknownbrackets** [comment] 2021-01-08 06:43
That sounds a lot like #10850.

-[Unknown]

**Comment by hrydgard** [comment] 2021-01-08 09:06
I think this has improved a bit since 1.10.3, some bugs have been fixed. Try the latest from https://buildbot.orphis.net/ppsspp/ .

Might not be perfect yet though, assuming #10850 is still reproducible...

**Comment by genos1213** [comment] 2021-01-08 17:37
I tried the latest version and unless it's my imagination it's a bit better, but assuredly still crashes within around 10 rounds of minimising the app. So I guess it's the same issue as #10850?

**Comment by hrydgard** [comment] 2021-01-30 22:29
I've tried to reproduce with very limited success. More work on this will have to wait. The current state is pretty usable for most people I think...

**Comment by Gamemulatorer** [comment] 2021-08-09 00:20
I try to reproduce this but it seems fixed maybe by 
https://github.com/hrydgard/ppsspp/pull/14702?

**Comment by Gamemulatorer** [comment] 2021-11-22 08:40
This is now become very agreesive using the latest ppsspp github build, once you minimize the ppsspp it's automatically reset and sometimes crash

```
<<< log_count = 15 >>>
[11-22 15:20:04.997 29493:29493 F/DEBUG]
      #03 pc 00000000006abe18  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::PerformRenderPass(VKRStep const&, VkCommandBuffer_T*)+1816) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:04.997 29493:29493 F/DEBUG]
      #04 pc 00000000006ab514  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::RunSteps(VkCommandBuffer_T*, std::__ndk1::vector<VKRStep*, std::__ndk1::allocator<VKRStep*> >&, QueueProfileContext*)+264) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:04.997 29493:29493 F/DEBUG]
      #05 pc 00000000006a53d0  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::Run(int)+92) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:04.997 29493:29493 F/DEBUG]
      #06 pc 00000000006a4568  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::ThreadFunc()+108) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:04.997 29493:29493 F/DEBUG]
      #07 pc 00000000006a87d4  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (VulkanRenderManager::*)(), VulkanRenderManager*> >(void*)+64) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:46.147 29821:29821 F/DEBUG]
      #03 pc 00000000006abe18  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::PerformRenderPass(VKRStep const&, VkCommandBuffer_T*)+1816) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:46.147 29821:29821 F/DEBUG]
      #04 pc 00000000006ab514  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::RunSteps(VkCommandBuffer_T*, std::__ndk1::vector<VKRStep*, std::__ndk1::allocator<VKRStep*> >&, QueueProfileContext*)+264) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:46.147 29821:29821 F/DEBUG]
      #05 pc 00000000006a53d0  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::Run(int)+92) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:46.147 29821:29821 F/DEBUG]
      #06 pc 00000000006a4568  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::ThreadFunc()+108) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 15:20:46.147 29821:29821 F/DEBUG]
      #07 pc 00000000006a87d4  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (VulkanRenderManager::*)(), VulkanRenderManager*> >(void*)+64) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 16:09:18.583 3573:3573 F/DEBUG]
      #03 pc 00000000006abe18  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::PerformRenderPass(VKRStep const&, VkCommandBuffer_T*)+1816) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 16:09:18.583 3573:3573 F/DEBUG]
      #04 pc 00000000006ab514  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanQueueRunner::RunSteps(VkCommandBuffer_T*, std::__ndk1::vector<VKRStep*, std::__ndk1::allocator<VKRStep*> >&, QueueProfileContext*)+264) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 16:09:18.583 3573:3573 F/DEBUG]
      #05 pc 00000000006a53d0  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::Run(int)+92) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 16:09:18.583 3573:3573 F/DEBUG]
      #06 pc 00000000006a4568  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::ThreadFunc()+108) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

[11-22 16:09:18.583 3573:3573 F/DEBUG]
      #07 pc 00000000006a87d4  /data/app/~~S0FmTmtcTQ8dnqn8V9-hAQ==/org.ppsspp.ppsspp-vaMVcYx1nbTqBA6CxXEAVQ==/lib/arm64/libppsspp_jni.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (VulkanRenderManager::*)(), VulkanRenderManager*> >(void*)+64) (BuildId: 89b8a4491402965a0aab4d82ce6d48cfab108bab)

```

**Comment by hrydgard** [comment] 2021-11-22 08:56
thanks for reporting, that's not good. will prioritize.

**Comment by hrydgard** [comment] 2021-12-10 12:30
Seems that #15220 fixed or at least improved this. I'm closing, let's reopen if it becomes an issue again.

**Closed by hrydgard** 2021-12-10 12:30 UTC
Labels: Platform-specific (Android), Vulkan
