### ISSUE TITLE
Ppsspp unfortunately has stopped message in last build

### ISSUE THREAD

**Issue by ekkysw** [hrydgard/ppsspp#8576] opened 2016-02-11 04:49 UTC
I try build 1.1.1-928 on Android, when i exit program i get that message "ppsspp unfortunately has stopped", game still working but sometimes lag...last build i try work fine is build 1.1.1-912 ,i dont get that message...my phone Asus Zenfone 4

**Comment by unknownbrackets** [comment] 2016-02-13 14:32
Is this a duplicate of #8546?

-[Unknown]

**Comment by ekkysw** [comment] 2016-02-13 15:06
No, this not duplicate that issue.... i try new build anda when exit i get that message

**Comment by unknownbrackets** [comment] 2016-02-13 15:49
But that other issue says exactly the same thing; it says that person is also getting an error message when exiting.

I'm not saying this problem doesn't happen, I'm just saying that there's already an issue for it.  I mean, you wouldn't put "buy bread" on a to do list 8 times, right?  You only need it once to know that it needs to be done.

Closing as duplicate.

-[Unknown]

**Closed by unknownbrackets** 2016-02-13 15:49 UTC
