### ISSUE TITLE
hello admin help me please.

### ISSUE THREAD

**Issue by NEARNIPER** [hrydgard/ppsspp#8982] opened 2016-09-15 16:22 UTC
I have problem after update PPSSPP (Dev-Laster) version 0v1.2.2-973g2019542, icon PPSSPP is missing and I can't play sad :(

**Comment by hrydgard** [comment] 2016-09-15 18:34
Duplicate of #8978 . We're looking into it.

**Closed by hrydgard** 2016-09-15 18:34 UTC
