### ISSUE TITLE
Silent Hill Shattered Memories Flashlight issues

### ISSUE THREAD

**Issue by Hurikejn** [hrydgard/ppsspp#14265] opened 2021-03-05 07:01 UTC
### What happens?
-Silent Hill Shattered Memories is known for having issues but this issue is something new or at least something different, what happens is, that, the flashlight uses text/text textures from the paper sheet you answer at the beginning. 

### What *should* happen?
-The flashlight should be a normal "circle" instead of a text/text texture

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
-PC Desktop, Windows 10 Pro with a newest update, PPSSPP with a newest update too, it is a portable edition and it is on my HDD instead of SSD (the game is on an HDD too), my GPU is RX580 with AMD Ryzen 5 2600 processor with newest drivers (20.12.1).
![SilentHillShatteredMemories](https://user-images.githubusercontent.com/79256506/110078013-61cfd700-7d87-11eb-9397-62b7ee74b0c0.png)

**Comment by Panderner** [comment] 2021-03-05 09:16
Maybe duplicate of #6265?

**Comment by nassau-tk** [comment] 2021-03-05 11:29
Probably, same as https://github.com/hrydgard/ppsspp/issues/6265#issuecomment-678740520.

**Comment by MiguelCardonaG** [comment] 2021-03-05 14:09
In addition, this game has problems saving game.

https://github.com/hrydgard/ppsspp/issues/13781

**Comment by crazyrexz** [comment] 2021-03-07 14:38
is it still slowing down on some area and flashlight framerate get dropped?

wanna play it if framerate is good

**Comment by alanwake24** [comment] 2021-03-27 19:57
Issue still exists. The flashlight is text. Maybe bring back Disable Stencil Test? It worked when it was in.

**Comment by Gamemulatorer** [comment] 2021-05-02 14:13
Duplicate of #6265

**Comment by unknownbrackets** [comment] 2021-05-02 16:40
This issue is being closed as a duplicate of #6265.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-05-02 16:40 UTC
Labels: GE emulation
