### ISSUE TITLE
Silent hill zero part of the body disappear

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8497] opened 2016-01-24 09:02 UTC
Since https://github.com/hrydgard/ppsspp/pull/8467
![12](https://cloud.githubusercontent.com/assets/3481559/12535382/3617162c-c2bc-11e5-96d5-b30a74c9c900.png)

**Comment by unknownbrackets** [comment] 2016-01-24 16:15
So then, this is probably depth related.  What happens if you put a `return;` at the top of `BlitFramebufferDepth`?

-[Unknown]

**Comment by daniel229** [comment] 2016-01-25 01:20
<code>return;</code>at the top of <code>BlitFramebufferDepth</code> solves it
![1](https://cloud.githubusercontent.com/assets/3481559/12540487/ec4b41ce-c344-11e5-8b2b-c2fddd9eb48d.png)

**Comment by unknownbrackets** [comment] 2016-01-25 03:20
Okay, so then that probably means something else should be happening to depth, and isn't.

Since the w/h match, and z addr / stride match, my guess is that it's one of:
 * Rendering on top of a framebuffer (e.g. targetting the framebuffer address and doing a clear.)
 * CPU / block transfer (writing to the address of the framebuffer.)
 * Flushing / flag issue (depth modified but flags not affected.)

For the last one, it's easy - find this:

```c++
if (!prevVfb->fbo || !vfb->fbo || !useBufferedRendering_ || !prevVfb->depthUpdated || isClearingDepth) {
```

And change to:

```c++
if (!prevVfb->fbo || !vfb->fbo || !useBufferedRendering_) {
```

If that helps, then we're missing some depth update flags.

For the first one, it's also easy, if you pause to menu and resume, the FBO creation - if it shows any FBOs that also use the depth address as being destroyed, then that is likely.

And for the second one, a breakpoint on the depth address (possibly also its mirrors) would do the trick.  So if the z_address is 0x00088000, a memory breakpoint on: 0x04088000, 0x04288000, 0x04488000, and 0x04688000 each of size 0x00044000.

If it's clearing depth in a simple way, that's probably detectable and uploadable.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-25 04:24
That change also works.
There are 5 addresses for FBO reusing depthbuffer
```
18:11:651 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1934 Destroying FBO for 000d4000 : 1024 x 272 x 0
18:11:653 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1934 Destroying FBO for 0004c000 : 480 x 272 x 3
18:11:654 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1934 Destroying FBO for 00170000 : 480 x 272 x 3
18:11:655 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1934 Destroying FBO for 00020000 : 1024 x 64 x 0
18:11:655 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1934 Destroying FBO for 00000000 : 480 x 272 x 3
18:11:679 main         I[SCEGE]: Common\FramebufferCommon.cpp:412 Creating FBO for 000d4000 : 1024 x 272 x 0
18:11:682 main         I[SCEGE]: Common\FramebufferCommon.cpp:412 Creating FBO for 0004c000 : 128 x 128 x 3
18:11:684 main         I[SCEGE]: Common\FramebufferCommon.cpp:412 Creating FBO for 00020000 : 1024 x 64 x 0
18:11:684 main         W[SCEGE]: Common\FramebufferCommon.cpp:449 FBO reusing depthbuffer, 00020000/00000000 and 000d4000/00000000
18:11:685 main         I[SCEGE]: GLES\Framebuffer.cpp:620 Resizing FBO for 0004c000 : 256 x 256 x 0
18:11:686 main         I[SCEGE]: Common\FramebufferCommon.cpp:412 Creating FBO for 00170000 : 256 x 256 x 0
18:11:687 main         W[SCEGE]: Common\FramebufferCommon.cpp:449 FBO reusing depthbuffer, 00170000/00000000 and 000d4000/00000000
18:11:691 main         I[SCEGE]: GLES\Framebuffer.cpp:620 Resizing FBO for 0004c000 : 480 x 272 x 3
18:11:694 main         I[SCEGE]: GLES\Framebuffer.cpp:620 Resizing FBO for 00170000 : 512 x 256 x 3
18:11:699 main         I[SCEGE]: GLES\Framebuffer.cpp:620 Resizing FBO for 00170000 : 480 x 272 x 3
18:11:703 main         I[SCEGE]: Common\FramebufferCommon.cpp:412 Creating FBO for 00000000 : 480 x 272 x 3
18:11:793 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1918 Decimating FBO for 00170000 (256 x 256 x 0), age 6
18:12:698 main         I[MODULE]: HLE\sceKernelModule.cpp:2109 sceKernelGetModuleId()
```

**Comment by daniel229** [comment] 2016-01-25 04:43
only break at 0x04170000

**Comment by unknownbrackets** [comment] 2016-01-25 05:45
Hmm, maybe it's because we're not copying the depth when it isn't rendered, but it's switching between three different buffers?

But also, `Destroying FBO for 00000000` is a color buffer, and does indeed overlap with depth buffers: `00020000/00000000 and 000d4000/00000000` / `00170000/00000000 and 000d4000/00000000`.

So all three of these are using 0x04000000 as the depth buffer, and there's ALSO a render target there.  So many different sizes, though...

-[Unknown]

**Comment by daniel229** [comment] 2016-01-30 12:30
But the way I found the demo.
![01](https://cloud.githubusercontent.com/assets/3481559/12695644/b4460120-c78f-11e5-82d5-e0a5507dc956.png)

demo and the savestate
https://drive.google.com/folderview?id=0BzGZGDfFE68zdXR6QVZNbGpkekE&usp=sharing

**Comment by unknownbrackets** [comment] 2016-01-31 17:38
Hmm.  At least some of this is using a == depth test.  Anyway, There's also, it's switching depth buffers.  The biggest issue is that it draws to framebuffer A, fills depth, and then draws to framebuffer B... and then draws to framebuffer C, expecting the depth to be there from A.  But A and B have different depth buffers, so we don't copy.

This game does some crazy stuff also.

-[Unknown]

**Comment by daniel229** [comment] 2016-02-07 11:20
This is also a regression after v1.1.1

**Comment by unknownbrackets** [comment] 2016-02-07 17:28
Was this game ever really working well, though?

I think the issue in this game is that some, but not all, of the depth copies are happening.  Before, possibly none were.

-[Unknown]

**Comment by hrydgard** [comment] 2016-07-24 20:01
Does this still reproduce?

**Comment by Zetchzie** [comment] 2016-07-24 22:18
nope

**Comment by unknownbrackets** [comment] 2016-07-24 22:50
Okay, so closing this based on that - but feel free to reopen/comment if I've misunderstood.

-[Unknown]

**Comment by daniel229** [comment] 2016-07-24 23:08
Still happens in the latest build.
![01](https://cloud.githubusercontent.com/assets/3481559/17087182/8d87953a-5236-11e6-9ff6-71fc3ecc86e2.png)

**Comment by Markeron** [comment] 2016-09-28 11:22
Flashlight works normally on Direct3D9, it's a bit slower for me but works.

**Comment by Ps3itaTeam** [comment] 2018-06-04 13:40
If you turn off the flashlight, open/close the map and turn on again the flashlight, the issues disappear..

When indeed you leave the flashlight on and open/close the map the issues reappear..

**Comment by Gamemulatorer** [comment] 2021-05-27 08:01
Silent Hill Origin and Zero are the same?
I also experience this issue using ppsspp latest git build.
### vulkan
![Screenshot_2021-05-27-15-58-10-770_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119788446-b9a05900-bf04-11eb-84e1-debe1f150f50.jpg)
### opengl
![Screenshot_2021-05-27-15-58-28-911_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119788339-a2fa0200-bf04-11eb-945a-d939512f37a6.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-27 08:02
Also on that part the fps is drastically drop

**Comment by Gamemulatorer** [comment] 2021-06-01 12:50
So the gdx

> If you turn off the flashlight, open/close the map and turn on again the flashlight, the issues disappear..
> 
> When indeed you leave the flashlight on and open/close the map the issues reappear..

You are right 👍
![Screenshot_2021-06-01-20-48-05-376_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/120325943-bfd67100-c31a-11eb-9524-fbbb1c74226e.jpg)
Hope this issue will fix by this https://github.com/hrydgard/ppsspp/pull/14042 on OpenGL but how about Vulkan 🤔

**Comment by Panderner** [comment] 2021-06-01 12:56
> Hope this issue will fix by this #14042 on OpenGL but how about Vulkan 🤔

@Gamemulatorer Yes but Unfortunately that #14042 quoted:

> Only works on desktop, this currently requires GL_ARB_depth_clamp which is not really supported on mobile (there is an extension, GL_EXT_depth_clamp, but few mobile devices support it).
 
This will not work on mobile but it only works on desktop.

**Comment by Gamemulatorer** [comment] 2022-08-25 14:17
This is also finally fix 🎉
![Screenshot_2022-08-25-22-15-35-999_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/186689405-5c08a44b-dbcf-459b-821c-2f91430c9572.jpg)

**Comment by ryzenvideous** [comment] 2022-08-25 22:01
> This is also finally fix 🎉 ![Screenshot_2022-08-25-22-15-35-999_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/186689405-5c08a44b-dbcf-459b-821c-2f91430c9572.jpg)

How, what, where, when, what do I do?!

**Comment by Gamemulatorer** [comment] 2022-08-25 22:48
> How, what, where, when, what do I do?!

Use the latest build from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by unknownbrackets** [comment] 2022-08-26 03:56
See #6265.  Since this was fixed around the same time, I'm going to close it.  It seems clear they were both involving depth texturing of some kind and it was the same underlying issue.

If you're reading this and still experiencing the issue, it probably has to do with your GPU driver capabilities or may be a new bug.  Please take a look at #6265 before creating a new issue or commenting.

-[Unknown]

**Closed by unknownbrackets** 2022-08-26 03:56 UTC
Labels: Depth / Z
