### ISSUE TITLE
Burnout legends game crash iOS

### ISSUE THREAD

**Issue by Alfaracer** [hrydgard/ppsspp#11169] opened 2018-06-10 22:18 UTC
### What happens?
The game crashes after selecting a race on the world tour map, or when proceeding to the select car screen after selecting a race type in the quick race menu. The select car screen never loads or appears. The game just crashes to my iOS homescreen out of the PPSSPP app.

### What *should* happen?
The select car screen should appear and next the game should start.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhone X, iOS 11.4, non-jailbroken, PPSSPP v1.6.2-2
Settings: 
OpenGL 
Buffered rendering
Simulate block transfer effects v
Frameskipping 1
Auto frameskip v
Prevent exceeding 60FPS v
Alt. speed unlimited
postprocessing off
rendering 1:1
hardware transform v
software skinning v
vertex cache v
Spline/bezier curves quality high
upscale auto
upscale type xBRZ
deposterize v
anisotropic filtering 16x
texture filter auto
screen scaling linear
disable stencil test v
low res for effects off

**Comment by Alfaracer** [comment] 2018-06-17 07:02
Can someone help me with this? I am dying to play this game and have seen video’s of others running this game onbios without any problems.

**Comment by unknownbrackets** [comment] 2018-06-17 08:12
It's hard to say because we don't always get great debug information out of iOS.

You can try going to developer tools and switching from "jit" to "ir interpreter" - it will be much slower, but if it works that might tell us something.  If it still crashes, that would narrow it down too.

If you can try to get any log information or run it with Xcode possibly (it's a free download), it would help a lot to see where it's crashing.

-[Unknown]

**Comment by leopard20** [comment] 2018-06-23 10:51
It most probably has something do with 3D graphics if it crashes at that point.
Can you run other 3D games ok?

**Comment by hrydgard** [comment] 2019-02-26 11:30
Does this still happen?

**Comment by McEoy** [comment] 2020-04-26 18:09
Still happens. Just tried it with 1.9.3-80-g373bf6098e

**Comment by hrydgard** [comment] 2020-04-26 20:13
Very strange that this would affect only iOS, this game has long been pretty stable on the other platforms..

**Comment by unknownbrackets** [comment] 2021-10-01 20:27
This issue is being closed as a duplicate of #14559.  They're the same issue, but that one has a bit more information and confirms it happens on Android with IR interpreter as well.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-10-01 20:27 UTC
Labels: Platform-specific (iOS)
