### ISSUE TITLE
Surf's Up Glitched Textures - 1.10.2

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#13110] opened 2020-07-09 17:39 UTC
Hi,it is me again.I'm working on updating Ad-Hoc list from GuenosNoLife on forums,i decided to make my guide for Ad-Hoc for my Guilded server as well,and i had to test game Surf's Up.I got game,booted,and played at some point where i came to Volcano tracks,and i had really funny issue.Now,if Rendering Res is set to 3x,there is wrong behaviour of textures,but if 2x or below,it works just fine.I hope this gets fixed in new update

2x or 1x:
![Screenshot_2020-07-09-19-31-56-437_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87072200-aff20200-c21b-11ea-8a49-711a12d6ae46.png)

3x or higher:
![Screenshot_2020-07-09-19-32-17-554_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87072243-c0a27800-c21b-11ea-8c3d-4b3fe48fea3e.png)

TIA

**Comment by hrydgard** [comment] 2020-07-10 13:40
That is... weird.

Can you take a GE capture? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by EX-e-LD** [comment] 2020-07-11 03:39
Hi,i made dump,exactly like you asked.

[recording.zip](https://github.com/hrydgard/ppsspp/files/4906226/recording.zip)

**Comment by hrydgard** [comment] 2020-07-11 13:03
Thank you! I have some more critical issues to attend to but that's very helpful for when I get around to it.

**Comment by EX-e-LD** [comment] 2020-07-11 18:39
If you need anything else from my end,i would be happy to exist.

**Comment by Gamemulatorer** [comment] 2020-07-12 02:55
I try the dump but I have a dark overlay issue on this game most likely similar to #11430
![Screenshot_2020-07-12-10-53-30](https://user-images.githubusercontent.com/37603562/87237881-2403f400-c42e-11ea-838c-56d944fb4206.png)

**Comment by EX-e-LD** [comment] 2020-07-12 09:42
> I try the dump but I have a dark overlay issue on this game most likely similar to #11430
> ![Screenshot_2020-07-12-10-53-30](https://user-images.githubusercontent.com/37603562/87237881-2403f400-c42e-11ea-838c-56d944fb4206.png)

Game runs native at 30 FPS,your game runs at 60 FPS,how come?

**Comment by hrydgard** [comment] 2020-12-01 00:23
Does this still happen?

**Comment by EX-e-LD** [comment] 2020-12-07 15:35
Hi,me again.sadly yes,this issue still happens,even with latest builds from buildbot.orphis.net.

**Comment by unknownbrackets** [comment] 2021-02-20 04:53
At 1092/1113, it textures from 0x04088000 to 0x04110000.  In the dump, it seems weirdly stretched.  It looks like the top left of a 3x version of the scene.

The dark overlay is drawn as the last prim in the scene - not sure if it's out of order in some way in the dump...

The bloom being from the top left ninth is consistent with the graphical glitches, which makes me think it's not a dump problem, but I'm not sure what would cause this...

-[Unknown]

**Comment by hrydgard** [comment] 2021-08-11 12:03
Why did you close it?

**Comment by Gamemulatorer** [comment] 2021-10-06 22:30
> Hi,it is me again.I'm working on updating Ad-Hoc list from GuenosNoLife on forums,i decided to make my guide for Ad-Hoc for my Guilded server as well,and i had to test game Surf's Up.I got game,booted,and played at some point where i came to Volcano tracks,and i had really funny issue.Now,if Rendering Res is set to 3x,there is wrong behaviour of textures,but if 2x or below,it works just fine.I hope this gets fixed in new update
> 
> 2x or 1x: ![Screenshot_2020-07-09-19-31-56-437_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87072200-aff20200-c21b-11ea-8a49-711a12d6ae46.png)
> 
> 3x or higher: ![Screenshot_2020-07-09-19-32-17-554_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87072243-c0a27800-c21b-11ea-8c3d-4b3fe48fea3e.png)
> 
> TIA

I cannot reproduce this on my phone
5X Rendering Resolution
**Vulkan**
![Screenshot_2021-10-07-06-26-23-577_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136292449-f3b1ef43-a029-4d8a-89c2-96956c29b564.jpg)
**OpenGL**
![Screenshot_2021-10-07-06-29-01-077_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136292477-e36886ff-109b-4cc9-9087-3c095ed545b7.jpg)

**Comment by unknownbrackets** [comment] 2021-10-08 04:51
Okay, cool.  Closing as fixed, especially given the reporter deleted their account and we can't reproduce.

-[Unknown]

**Closed by unknownbrackets** 2021-10-08 04:51 UTC
Labels: GE emulation
