### ISSUE TITLE
[OpenGL ES] PoP Revelations - Funny loading screen when unthrottling

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#11122] opened 2018-06-02 09:21 UTC
On OpenGL ES, when I unthrottle the game during the mission loading screen, I see this weird screen instead:
![screenshot_2018-06-02-13-43-12-494_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/40872909-f57a5f56-666b-11e8-820a-48b563606064.png)

It becomes like this as soon as I press the unthrottle button (I don't have to hold it)
It doesn't appear without unthrottling.

**Comment by unknownbrackets** [comment] 2018-06-02 17:07
Is this new or has this been happening in older versions on your device?

What you're seeing is the UI texture, so maybe when we create it and are unthrottled we're accidentally drawing it somewhere?

-[Unknown]

**Comment by leopard20** [comment] 2018-06-02 21:51
I think it's new. I was just testing OpenGL ES after the latest fix. Other times I always use Vulkan.

**Comment by unknownbrackets** [comment] 2018-06-02 22:09
Does it reproduce in any other games?

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-06-03 20:34
@hrydgard hmm, not sure what's happening here - I guess it could be a regression from the ui texture change somehow?

-[Unknown]

**Comment by hrydgard** [comment] 2018-06-03 20:37
I doubt this is new from those changes (but could be, I guess...). Seems somehow we fail to rebind the proper texture before doing the first draw that frame, I guess the game leaves the texture bound between frames, but still, our dirty flags should take care of that...

**Comment by leopard20** [comment] 2018-06-10 11:34
@hrydgard @unknownbrackets This looks very simlar to the one here: https://github.com/hrydgard/ppsspp/issues/11131

**Comment by unknownbrackets** [comment] 2018-06-10 13:59
And you're not using "slower effects" right?  I'm inclined to close one or the other of these since they appear to be basically the same bug... we must be drawing without setting the texture to anything in some case.

-[Unknown]

**Comment by leopard20** [comment] 2018-06-10 14:31
No. Not using it. Although to get past certain parts of the game (most notorious of which is the Dahaka chase scene) it should be on.

**Comment by unknownbrackets** [comment] 2021-02-16 07:48
Is this still an issue with the latest git builds after #13865?  This no longer frameskips on unthrottle.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-08-23 00:06
I can't reproduce this issue but it's lag on this area using opengl
![Screenshot_2021-08-23-08-03-33-261_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130374470-3c792042-1d39-4003-90f2-1ba50016a06e.jpg)
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7028368/recording.ppdmp.zip)

**Comment by hrydgard** [comment] 2021-08-23 07:10
Seems like a difference issue though. I'm closing this.

**Closed by hrydgard** 2021-08-23 07:10 UTC
