### ISSUE TITLE
ULES-00516 MOH Heroes Vulkan bad vshader cached 

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#16612] opened 2022-12-17 22:32 UTC
### Game or games this happens in

ULES-00561 - Medal of Honor Heroes

### What area of the game / PPSSPP

After title screen emulator prompt Vulkan vshader cached error.

### What should happen

No vshader error.

### Logs

![image](https://user-images.githubusercontent.com/4381277/208268238-bebbb039-81ab-4c84-9d67-7d0fe2e6b9bd.png)

[DebugLog.zip](https://github.com/hrydgard/ppsspp/files/10252840/DebugLog.zip)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA Geforce RTX 3070

### PPSSPP version affected

v1.14-37-g4942ab7d8

### Last working version

v1.12.3-1469-gcc197415b

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment] 2022-12-18 08:15
Can't reproduce this on my phone might be a windows issue only.

**Comment by hrydgard** [comment] 2022-12-18 10:13
Thanks for reporting this one!

No, we just ignore the error on Android (debug asserts aren't on there by default) but it's still a bug, even though there might not be any big graphical consequence. Will look into it.

**Comment by hrydgard** [comment] 2022-12-18 10:34
We hit the case where the game uses GE_PRIM_KEEP_PREVIOUS where prevPrim_ == GE_PRIM_INVALID. Think this might later somehow confuse CanUseHardwareTransform(prim) leading us to generate a different useHwTransform flag, for what should be the same inputs to the shader cache ID generators. Haven't quite understood this yet.

I think maybe we shouldn't set prevPrim_ to GE_PRIM_INVALID in Flush, btw...

**Comment by unknownbrackets** [comment] 2022-12-18 15:15
That sounds right to me.  It seems like `CanUseHardwareTransform(GE_PRIM_INVALID)` would only mean `DoFlush()` had prevPrim_ set to GE_PRIM_INVALID, unless it's a curve.... but then how does it get there?  `SubmitPrim()` looks like it should always set `prevPrim_`.

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-12-18 15:26
Okay, I saw it so opened up #16614.  We were never setting `prevPrim_` if it was GE_PRIM_INVALID, I changed it to use points in that unlikely case (can only happen now on very first draw.)

-[Unknown]

**Comment by hrydgard** [comment] 2022-12-18 20:44
#16614 fixes this, closing.

**Closed by hrydgard** 2022-12-18 20:44 UTC
Labels: Vulkan
