### ISSUE TITLE
Games Closing or having problems

### ISSUE THREAD

**Issue by basedgamer** [hrydgard/ppsspp#7145] opened 2014-12-07 00:33 UTC
I just tried to play Megaman Powered up on my IPhone 6 with the updated software. it worked before, but now it doesn't. when I load up the game it just closes! second game having issues is The godfather mob Wars. game runs fine, but cutscenes are always flickering! 3rd game having problems is Crisis Core. once I click on New game, I just get a black screen. I tried downloading a completed save and loading the game, but unfortunately just closes the game. I hope this gets fixed in the next update, because the emulator is so awesome and I'm in love with it. I'll definitely, but I hope these fixes. THX!!!

**Comment by unknownbrackets** [comment] 2015-12-29 20:47
Unfortunately, we don't really know what causes the iOS crashes.  Some people have found workarounds like starting other apps first or changing certain settings.  We don't really understand what's going on.

I'm going to close this as a duplicate of #7360 though, which is more general.

If the latest version happens to work for you, that'd be great to know, though.

-[Unknown]

**Closed** 2015-12-30 17:38 UTC
Labels: Platform-specific (iOS)
