### ISSUE TITLE
Rendering bugs in Silent Hill Shattered Memories

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#9001] opened 2016-09-22 13:25 UTC
Hello. I launch Silent Hill Shattered memories on PPSSPP 1.3.0. In OpenGL-backend, it has a bug's with shadows:
![1](https://cloud.githubusercontent.com/assets/11344982/18749588/f140b332-811a-11e6-994d-ff5228edc5f9.png)
![2](https://cloud.githubusercontent.com/assets/11344982/18749595/fed7f492-811a-11e6-8fa0-ffb65f4b3494.png)

In Direct3D-backend, it has a lighting bug's:
![3](https://cloud.githubusercontent.com/assets/11344982/18749711/781a02aa-811b-11e6-8f04-614996fa7bb4.png)
![4](https://cloud.githubusercontent.com/assets/11344982/18749716/7e3a9e9c-811b-11e6-9a88-adec087345da.png)
![5](https://cloud.githubusercontent.com/assets/11344982/18749721/836bfcda-811b-11e6-90b1-27d4b9d82cbf.png)
![6](https://cloud.githubusercontent.com/assets/11344982/18749726/87efc4c6-811b-11e6-8df6-0dc5d8645710.png)

My testing system: Windows 8.1, Intel Core i3-550, 8G RAM, GeForce GTX 760, driver 372.90

**Comment by geraq** [comment] 2017-03-06 14:25
Unchecking "Disable slower effects" and checking "Disable stencil test" worked for me.

**Comment by Sunderland93** [comment] 2017-04-01 03:52
DirectX 11 mode solve this problem!

**Comment by hrydgard** [comment] 2017-04-02 08:28
Well, it's presumably still a problem in the other backends, so I'm reopening.

**Comment by unknownbrackets** [comment] 2017-05-28 05:31
Does this happen in the software renderer?

-[Unknown]

**Comment by leopard20** [comment] 2018-06-10 11:19
@hrydgard @unknownbrackets C'mon guys! It's a duplicate AFAICT!

**Comment by hrydgard** [comment] 2018-06-10 18:52
@leopard20 Of which one? Too lazy to search :)

**Comment by leopard20** [comment] 2018-06-10 19:07
@hrydgard It seems they're just similar: https://github.com/hrydgard/ppsspp/issues/6265
My bad! :)

**Comment by Emulatorer** [comment] 2019-02-10 10:27
Flashlight bug still present in the latest git build :(
### Flashlight OFF
![screenshot_2019-02-10-18-22-52](https://user-images.githubusercontent.com/37603562/52532497-1e017380-2d61-11e9-86cf-feab99abf756.png)
### Flashlight On
![screenshot_2019-02-10-18-22-34](https://user-images.githubusercontent.com/37603562/52532511-57d27a00-2d61-11e9-94fd-6e3a256d67fe.png)

Is there a cheat how to force enable the flashlight???
I think this issue is also a duplicate of #6265

**Comment by MichaelPhoenix46** [comment] 2021-01-28 02:14
> Well, it's presumably still a problem in the other backends, so I'm reopening.

right now, is a problem in every in every backend. not sure if it was fixed before, but directx 11 is still broken

**Comment by hrydgard** [comment] 2021-01-28 08:09
Duplicate of #6265

**Closed by hrydgard** 2021-01-28 08:09 UTC
