### ISSUE TITLE
Tekken 5 DR black sceen bug On stage 5 and final stage

### ISSUE THREAD

**Issue by JayKode** [hrydgard/ppsspp#9995] opened 2017-10-03 06:59 UTC
I still get this issue regardless of the build i Use
![screenshot_20171003-013822](https://user-images.githubusercontent.com/32477276/31113339-73fe9e34-a7de-11e7-9d29-0c969d98597c.png)

**Comment by JayKode** [comment] 2017-10-03 13:24
It recently turned into this
![screenshot_20171003-082316](https://user-images.githubusercontent.com/32477276/31127349-42f2525a-a814-11e7-8cf2-bbc848513a94.png)

**Comment by TediExcaliber** [comment] 2017-10-09 08:20
I think the problem is on your setting, try to don't mark the "Disable Slower Effect (Faster)" on graphic setting in the ppsspp

**Comment by SamueldeSena** [comment] 2017-12-06 16:08
this problem and on the part of configuration try rederisation with buffet or without buffet or check or uncheck simulate transfer of pictures this helped me in that cases this topic can already be closed

**Comment by hrydgard** [comment] 2017-12-06 22:10
@JayKode Please verify that turning off "Disable slower effects" setting helps.

**Comment by unknownbrackets** [comment] 2018-10-28 16:02
Did that help?

-[Unknown]

**Comment by Emulatorer** [comment] 2019-03-26 03:47
The blackscreen issue in that stage is cause by "Disable Slower Effects"

But in ppsspp v1.8.0 even "Disable Slower Effects" is blackscreen isn't happened 🙂

**Comment by unknownbrackets** [comment] 2019-03-26 04:42
Great, closing then.  Thanks for verifying.

-[Unknown]

**Closed by unknownbrackets** 2019-03-26 04:42 UTC
