### ISSUE TITLE
[Android][Vulkan] Midnight Club L.A. Remix

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13834] opened 2020-12-29 08:52 UTC
### What happens?

Hello!

This game has the map broken.

![IMG_20201229_094016](https://user-images.githubusercontent.com/65356692/103271755-62c93e80-49bb-11eb-8daa-8f4ef269ce40.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 10 Plus Exynos.
Ppsspp-v1.10.3-1404-g8d2fdfc73-android.apk

Dump:
[ULES01144_0001.zip](https://github.com/hrydgard/ppsspp/files/5750090/ULES01144_0001.zip)

**Comment by Panderner** [comment] 2020-12-29 08:59
@MiguelCardonaG have you tried OpenGL?

**Comment by Panderner** [comment] 2020-12-29 09:04
Duplicate of #13833 so you don't need to add another issue

**Comment by hrydgard** [comment] 2020-12-29 09:27
Yeah that's 99% sure to be the same bug, since it's a game with the same engine. Let's keep it in #13833 indeed.

**Closed by hrydgard** 2020-12-29 09:27 UTC
