### ISSUE TITLE
Bust a move deluxe bug

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#10806] opened 2018-03-26 10:19 UTC
I can't show taito logo

**Comment by hrydgard** [comment] 2018-03-26 10:59
https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly

**Comment by benderscruffy** [comment] 2018-04-27 04:36
please close this as it is a duplicate of #8795

**Closed** 2018-04-27 07:07 UTC
Labels: No Feedback / Outdated?
