### ISSUE TITLE
PPSSPP occasionally, randomly closes out with no error messages.

### ISSUE THREAD

**Issue by NaturalHarmonia** [hrydgard/ppsspp#10028] opened 2017-10-24 01:13 UTC
I use PPSSPP for my phone and have had this happen two times today.

**Comment by hrydgard** [comment] 2017-10-24 13:41
When you see this, could you check your ADB logs? (google to find out a few ways how to do that).

What games are you playing when this happens? And what phone do you have?

**Comment by NaturalHarmonia** [comment] 2017-10-27 19:02
This happens when I play both Yu-Gi-Oh! 5D's Tag Force 5 and Yu-Gi-Oh! 5D's Tag Force 6. I have a ZTE N817. I tried to download and use SDK manager to get the ADB log but couldn't really install it.

**Comment by NaturalHarmonia** [comment] 2017-10-31 17:35
I fI found a way to use SDK Manager but I'm still confused on how to actually run it.

https://www.b4x.com/android/forum/threads/gui-sdk-manager-for-newer-versions-of-android-tools.80090/

**Comment by unknownbrackets** [comment] 2018-03-25 19:19
This, #10003, and #10044 seem related.  The latest one was closed, and we haven't gotten any feedback on #10003.  It's possible all of these were caused by hashmap bugs we've since fixed (which included a memory leak, I think.)

I'm going to close this now, but please comment with more details if it's still an issue.

-[Unknown]

**Closed by unknownbrackets** 2018-03-25 19:19 UTC
