### ISSUE TITLE
ppsspp new version crash pleas fix 😔

### ISSUE THREAD

**Issue by dilmanr** [hrydgard/ppsspp#8167] opened 2015-11-04 18:11 UTC

**Comment by deadair3210** [comment] 2015-11-04 18:14
Version? PC Specs? Game? Procedure?

**Comment by dilmanr** [comment] 2015-11-04 18:18
Iphone 6g 128g ios 9.0.2 jailbrek thanks plesc fix 🌹

**Comment by erks89** [comment] 2015-11-04 19:27
I don't think it's working for iOS 9+ it crashes every time I open a game. Disappointed @dilmanr

**Comment by LunaMoo** [comment] 2015-11-04 19:59
![kitten dies every time](https://cloud.githubusercontent.com/assets/5485237/10949954/cb23759c-8335-11e5-9ca8-6140ee6f0677.jpg)
Stop killing kittens!

 And if you want to bother someone at fault, go to apple headquarters, since they broke all emulators, it's nothing new and will likely happen again in the future. As repeated multiply times it's a duplicate of #8122 don't open new issues about something which is already tracked here, it only deorganizes(read as - slows down) efforts of fixing the problem, at best you can even anger developers who can ignore that issues completely ~ I don't think that lies in your interest.

**Closed** 2015-11-04 20:09 UTC
