### ISSUE TITLE
Assassin's creed problem while saving the game in ppsspp build current on Android

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10460] opened 2017-12-27 10:50 UTC
![screenshot_20171227-085047](https://user-images.githubusercontent.com/34135636/34379584-12905384-eae3-11e7-8fa6-d987038fdc46.png)
I tried everything but the game does not want to save and this problem only occurs in the android I use a European version ULES01367 my cell phone and a moto g5s plus adreno 506 snapdragon 625 this problem occurs in both the vulka and OpenGL
![screenshot_20171227-084242](https://user-images.githubusercontent.com/34135636/34379555-ef8fbd70-eae2-11e7-8ab3-a374cb177617.png)

**Comment by unknownbrackets** [comment] 2017-12-27 15:30
This issue is being closed as a duplicate of #7669.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-12-27 15:30 UTC
