### ISSUE TITLE
Ad-hoc network chat blocked [android bug]

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14723] opened 2021-08-13 01:01 UTC
### Game or games this happens in

All?

### What area of the game / PPSSPP

Sometimes network chat gets bugged. What happens is the beginning of the line is blocked or not visible from view. Only way to get around this is by inserting a bunch of characters (___________ie underscores) before writing the actual message. Not exactly sure what triggers it. But seems to happen when you host and then swap (friend hosts instead and you join).

![Screenshot_20210812-184248](https://user-images.githubusercontent.com/30265284/129288617-90e4432d-5496-439e-b907-456c7f92ebd8.png)
![Screenshot_20210810-204552](https://user-images.githubusercontent.com/30265284/129288629-fe687e0c-0c12-41cd-8c42-064146329cff.png)

### What should happen

This bug shouldn't occur at all. Mobile users should get exact same experience as pc users. (I assume this bug doesn't happen for pc users as I've not heard any complaints about chat bugs so far from them)

### Platform

Android 11.

### Mobile phone model or graphics card

Pixel 4a.

### PPSSPP version affected

Should affect all versions I assume. As I've heard network chat code hasn't been worked on in ages? But I tested on 1.11.3-842.

### Last working version

Dunno, to my knowledge it was never working properly.

### Graphics backend (3D API)

Vulkan

### Checklist

- [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2021-08-13 02:18
From the screenshots, it looks like the text is cropped to the screen.  If you change the screen position or size using the display layout editor, does that hold true?  It's not clear if it isn't true in some of your screenshots already.

-[Unknown]

**Comment by hrydgard** [comment] 2021-08-13 10:45
I think this might be a scissor rect hanging around somehow, although the draw order makes it quite confusing that it can happen like that...

**Comment by samosaphile** [comment] 2021-08-20 19:14
> From the screenshots, it looks like the text is cropped to the screen. If you change the screen position or size using the display layout editor, does that hold true? It's not clear if it isn't true in some of your screenshots already.
> 
> -[Unknown]

Unfortunately, haven't got to test this yet. As the people I usually test and play with have gone on a hiatus. And the few times I did play, it only happened once.

> I think this might be a scissor rect hanging around somehow, although the draw order makes it quite confusing that it can happen like that...
> 
> Does it happen with OpenGL, btw?

I have been unable to reproduce on OpenGL so far. Interesting, could be a vulkan specific bug?

**Comment by hrydgard** [comment] 2021-08-29 20:23
It's very strange. But the chat window is also implemented a bit strangely, which appears to cause other issues too, including a shutdown problem.

I'm going to slightly rework it soon, it might possibly help this issue too.

**Comment by samosaphile** [comment] 2021-09-09 17:37
@unknownbrackets 

Ok, I finally did get to test this. (Was worried I'd lose connection to a game if I go into setting to change chat position, but this game I had already lost connection anyway...)

It does not seem to hold true if I move chat window position to center or right (away from default left position). I can see all text then. But going back to original position, text is again blocked.

Another thing I'd like to add is, when I close game then go back into game, it still shows blocked text. But closing game, then opening a different game it the chat bug doesn't happen there. I mostly use same ports / server for all games. Ofcourse, closing the emu completely then opening same game (that had blocked text) also makes bug go away too.

**Comment by hrydgard** [comment] 2021-09-09 17:54
Super weird, but thanks for the detailed report!

**Comment by unknownbrackets** [comment] 2021-09-13 07:13
If you wait an hour after the time of this comment, it'd help if you could try the latest git build and see if there's any improvement.  We changed the way the chat log display is implemented to hopefully help this issue.

-[Unknown]

**Comment by MojoJojoDojo** [comment] 2021-09-14 16:13
I tried it on Linux and now when someone else chats you can't see what he says until you chat as well afterwards.
So this is actually worse then how it was before lol.

**Comment by MojoJojoDojo** [comment] 2021-09-14 16:26
Here is an example on Windows:
![image](https://user-images.githubusercontent.com/33392696/133296552-680ae92c-b3ec-44f4-90c1-40929e553df6.png)

You can see the other player on the right is not seeing the chat until he will also chat as well.

**Comment by hrydgard** [comment] 2021-09-14 21:07
Huh, looks like we're missing something that should trigger updating of the UI.

**Comment by iota97** [comment] 2021-09-14 22:42
MojoJojoDojo does it happen only if the chat windows is closed while you send the message? If it happen when the chat is open as well there might be some thing else too...

**Comment by unknownbrackets** [comment] 2021-09-15 01:16
Sorry for missing that.  If you can check the artifacts for #14855, would be great for you to confirm if both the original issue and the updating are resolved.

-[Unknown]

**Comment by MojoJojoDojo** [comment] 2021-09-15 06:49
It does show up now but now when you chat you cant see if there any new messages as the counter for it is not working next to the word "chat".
TBH you might as well remove that counter.

**Comment by unknownbrackets** [comment] 2021-09-15 07:25
Oops, sorry, dumb mistake - fixed in 433daf1ee.  I can see the argument for removing the counter, but trying to avoid changing that when we're hopefully approaching the next stable release.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-09-16 07:02
Can anyone who could previously reproduce the issue with text not being visible confirm if things are better now?

Are there any other regressions or issues?

-[Unknown]

**Comment by hrydgard** [comment] 2021-09-19 19:15
@MojoJojoDojo Can you try again on master?

**Comment by MojoJojoDojo** [comment] 2021-09-20 12:16
Last time I tried it worked fine.

**Comment by hrydgard** [comment] 2021-09-20 13:04
Thanks, closing.

**Closed by hrydgard** 2021-09-20 13:03 UTC
Labels: Networking / adhoc, User Interface

**Comment by MojoJojoDojo** [comment] 2021-09-20 19:06
Thought you gonna wait for Android results because that was the issue.
I dont use Android.
