### ISSUE TITLE
Silent Hill Origin Issues

### ISSUE THREAD

**Issue by strangehero** [hrydgard/ppsspp#9714] opened 2017-05-23 06:49 UTC
hellow im no developer or a programer im playing silent hill origins as of the moment android device qualcom chipset snapdragon 805 adreno 420.. whenever im entering doors in the game with open flashlight sometimes travis have missing body parts.. i have disable the stencil test.. but the bug reappears if i reenter to a room.. just like in the elevator to the next room..

**Comment by strangehero** [comment] 2017-05-23 06:52
https://drive.google.com/file/d/0B-nSgVOxoiineFlfaFZuZkFzY28/view?usp=drivesdk

**Comment by strangehero** [comment] 2017-05-23 06:53
https://drive.google.com/file/d/0B-nSgVOxoiinTjc0d1VPZXd3OEk/view?usp=drivesdk

**Comment by strangehero** [comment] 2017-05-23 07:00
https://drive.google.com/file/d/0B-nSgVOxoiinWjZpNzRaYXBLRFU/view?usp=drivesdk

https://drive.google.com/file/d/0B-nSgVOxoiinRVZfZUxhNzlwNUk/view?usp=drivesdk

**Comment by strangehero** [comment] 2017-05-23 07:02
the game is smooth.. but how can i fix this missing graphics, or graphical errors is there anything to fix it in the settings? the disable stencil test is check on.

**Comment by unknownbrackets** [comment] 2017-05-23 23:38
This issue is being closed as a duplicate of #8497 and #8173.

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-05-23 23:38 UTC
