### ISSUE TITLE
Fast forward button not functioning 

### ISSUE THREAD

**Issue by Mattlava** [hrydgard/ppsspp#19317] opened 2024-07-08 19:52 UTC
### Game or games this happens in

All games

### What area of the game / PPSSPP

Using touch controls the fast forward button will work for a sec then stops working entirely. I've found a temporary fix where when I flip my phone and the screen auto rotates it completely solves the issue, however the fix needs to be performed again after leaving the app. 
It seems it's the act of the screen rotating that fixes it and not the specific orientation of the phone that matters as when i tested starting a game up with the front camera on the right of my screen (usually play with the camera on the left) the problem  persisted until rotating the screen.

Have not tested with a controller. Made screen recording into gif to fit file size limit hence the poor quality 

![20240708_154951](https://github.com/hrydgard/ppsspp/assets/175055577/d6fefd09-fee7-430f-8f82-b3bcf68e78da)

### What should happen

It should fast forward 

### Platform

Android

### Mobile device model or graphics card (GPU)

S24 ultra with snapdragon 

### PPSSPP version affected

1.17.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2024-07-18 12:37
Weird. Does the VSync setting affect it?

**Comment by Mattlava** [comment] 2024-07-19 05:38
> Weird. Does the VSync setting affect it?

Yup that was it. Just tried turning VSync off and now fast forward is working perfectly.

**Comment by hrydgard** [comment] 2024-07-19 09:16
Hm, did you change the fast-forward mode in development settings? otherwise, it should switch to a different method in this case that does work.

**Comment by Mattlava** [comment] 2024-07-19 12:17
> Hm, did you change the fast-forward mode in development settings? otherwise, it should switch to a different method in this case that does work.

For the most part my settings are all default as I haven't messed with them much. After searching through dev tools I think I found the setting your mentioning and it says it's set too frame skipping. When I changed it to render all frames and tested with vsync back on the fast forward button went back to being broken. 

If dev tools and dev settings are different then I definitely haven't messed with the setting you mentioned as I don't know how to access the latter.

**Comment by hrydgard** [comment] 2024-07-19 12:22
Hm, with that setting set to frame skipping, it indeed should have worked even without turning off vsync. Oh well..

**Comment by hrydgard** [comment] 2024-09-25 22:54
Can not reproduce this in the latest builds. Closing for now..

**Closed by hrydgard** 2024-09-25 22:54 UTC
Labels: Platform-specific (Android)

**Comment by Levan7** [comment] 2025-01-01 20:13
I have started to have this issue, if is capped at 60 fps and i can't go over 60 fps - I can't fast forward anymore (latest dev) even with frame skip on 
if it is running on 30 fps with fast forwarding it goes up to 60 fps and than stops

**Comment by hrydgard** [comment] 2025-01-01 21:45
hm, @Levan7 , using vsync? which backend, gl or vulkan? what device?

**Comment by Levan7** [comment] 2025-01-02 09:52
@hrydgard vsync is disabled - using vulkan

**Comment by hrydgard** [comment] 2025-01-02 14:58
did you enforce VSync in your driver settings?

**Comment by Levan7** [comment] 2025-01-03 09:01
@hrydgard well in nvidia control settings panel global settings is set to use app specific. 
I still gave a try running ppsspp in full screen mode but same issue

**Comment by Levan7** [comment] 2025-04-21 19:52
I really want to point out thing, I kinda believe that this was an Nvidia driver issue because when the driver got updated this fast forwarding glitch want away

**Comment by hrydgard** [comment] 2025-04-21 21:05
Thanks for reporting that @Levan7 !
