### ISSUE TITLE
Severe graphic glitches on "newer" Konami baseball games.

### ISSUE THREAD

**Issue by demodanza** [hrydgard/ppsspp#13582] opened 2020-10-24 06:58 UTC
### What happens?
On the later Jikkyou Powerful Pro Yakyuu and Pro Yakyuu Spirits games, once in a game, the character shadow frames get stuck on the screen. As the game goes on the screen gets filled with more and more repeating shadows obscuring the field. Tested on Jikkyou Powerful Pro Yakyuu 2013 and Pro Yakyuu Spirits 2014, If I remember correctly happened in JPPY 2012 and 2011, but could not test with those games this time.

Also, didn't remember it even happening a couple of years ago, so tested on build ppsspp-v1.8.0-2-g7f1e10a93-windows-amd64 and aside from running slower, the shadow glitch does not happen, so something on more recent ppsspp versions broke something somewhere.

Images attached of the first minute of a game for reference.

Jikkyou Powerful Pro Yakyuu 2013:
![JIKK13](https://user-images.githubusercontent.com/47835860/97070086-e1fd5900-15ab-11eb-8276-78fa9b79c9a4.png)
![JIKK132](https://user-images.githubusercontent.com/47835860/97070093-f6415600-15ab-11eb-939f-3ba656381a84.png)
Pro Yakyuu Spirits 2014:
![PRO](https://user-images.githubusercontent.com/47835860/97070099-ff322780-15ab-11eb-84d7-42dc9a5e2d55.png)
![PRO2](https://user-images.githubusercontent.com/47835860/97070101-02c5ae80-15ac-11eb-85cd-d6a98e19d507.png)

### What *should* happen?
Shadow frames should not get stuck on the screen.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Windows 10, 64 bits, 12gb ram, Intel core i5-6200U, Intel HD 520.
Windows 7 64bits, 8gb ram, intel core i5, Intel HD 3000.
Android.
PPSSPP standalone latest stable release, 1.10.3.
PPSSPP latest core on Retroarch (redundant, but nevertheless)

**Comment by Panderner** [comment] 2020-10-24 08:00
Maybe Duplicate of https://github.com/hrydgard/ppsspp/issues/13391?

**Comment by hrydgard** [comment] 2020-11-10 22:55
Closing as duplicate of #13391

**Closed by hrydgard** 2020-11-10 22:55 UTC
Labels: GE emulation
