### ISSUE TITLE
Video Driver fullscreen toggle bugs (Libretro) 

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#14151] opened 2021-02-16 00:57 UTC
### What happens?
When toggling fullscreen when RA is set to the glcore video driver the emulator will only display a balck screen, emulation is still running. With d3d11 toggling fullscreen crashes RA. Toggling fullscreen with gl and vulkan behaves correctly.

### What *should* happen?
Fullcreen toggle should function correctly. 

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
i7 8086k, GTX 1080 ti, Windows 10 2004, Latest core build.

**Comment by unknownbrackets** [comment] 2021-02-16 00:59
This issue is being closed as a duplicate of #10784.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-02-16 00:59 UTC

**Comment by BParks21** [comment] 2021-02-16 01:13
@unknownbrackets My apologies
