### ISSUE TITLE
Twisted Metal: Head-On sounds broken

### ISSUE THREAD

**Issue by KevThePurpleFox** [hrydgard/ppsspp#14704] opened 2021-08-08 20:37 UTC
### Game or games this happens in

UCUS 98601 - Twisted Metal: Head-On

### What area of the game / PPSSPP

The sounds aren't working in-game. Only the music, and the Special weapon sounds are working. Nothing else. I really want the sounds, it bothers me. It isn't game breaking, it is fully playable, it's just bothering.
Everything else is fine.
I saw in another post that 1.5.4 appearently fixed it, but I tried that version and it didn't work.

Just realized after posting this, it seems the last post is still kinda active and I was unaware.

### What should happen

It should have all sound playing normally like the car sounds when driving and being idle and all other weapon noises.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon(TM) Graphics

### PPSSPP version affected

v1.11.3

### Last working version

?

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-08-08 23:38
Duplicate of #10933

**Closed** 2021-08-08 23:39 UTC
