### ISSUE TITLE
How to build PPSSPP with enabled Vulkan on Linux?

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#8694] opened 2016-04-14 11:09 UTC
It is possible?

**Comment by unknownbrackets** [comment] 2016-04-17 02:29
Sure, but someone needs to implement the integration pieces.  Right now, Android doesn't work either.  We only have it working on Windows so far.

The actual rendering code should all be the same - just the hookups with SDL / Qt / whatever are going need to be implemented.  Pull requests welcome.

-[Unknown]

**Comment by hrydgard** [comment] 2017-11-14 10:02
Marking this as duplicate of #9031 as that has more info.

**Closed by hrydgard** 2017-11-14 10:02 UTC
Labels: Platform-specific (Linux/POSIX), Vulkan
