### ISSUE TITLE
Vulkan issue with hardware transform on Mali

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#15661] opened 2022-07-08 13:48 UTC
![Screenshot_2022-07-07-02-51-20-51_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/178004320-28639c16-6087-4ea0-8fd0-98dfa6146a12.jpg)
 As you can see no effect at vulkan
 Unlike openGL
![Screenshot_2022-07-07-02-51-57-22_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/178004475-5e77c3ea-09a6-4aea-be79-b40384ce2aa8.jpg)

im using realme8i

**Comment by hrydgard** [comment] 2022-07-08 13:49
Need more detail, what game is this? Can you take a GE frame capture? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

(See

**Comment by Gelo021** [comment] 2022-07-08 14:02
Can i ask how can i put here the recording.ppmdp???

Btw its Monster hunter 3rd Hd ver.

**Comment by hrydgard** [comment] 2022-07-08 14:09
you'll have to do it on a PC, just drag drop the file into a post you're typing right here in this issue.

**Comment by Gelo021** [comment] 2022-07-08 14:10
Can i just email it dont own one 🙄

**Comment by hrydgard** [comment] 2022-07-08 14:17
sure. hrydgard@gmail.com

**Comment by Gelo021** [comment] 2022-07-08 14:24
[recording.zip](https://github.com/hrydgard/ppsspp/files/9072790/recording.zip)

**Comment by hrydgard** [comment] 2022-07-09 11:49
Thanks, I'll take a look soon.

**Comment by Gelo021** [comment] 2022-07-13 16:24
@Gamemulatorer even toukiden kiwami


https://user-images.githubusercontent.com/67460268/178783454-386c5dd4-ad6d-4945-8cc9-197b119869ff.mp4

No effects at all

**Comment by Gamemulatorer** [comment] 2022-07-14 02:20
> @Gamemulatorer even toukiden kiwami
> 
>  Record_2022-07-14-00-22-57_2f85358b2198d26f8aca533d68bee793.mp4 
> No effects at all

Are you using default settings only?

**Comment by Gelo021** [comment] 2022-07-14 17:27
Maybe my android just recently updated to android 12 dont know, just maybe

**Comment by Gamemulatorer** [comment] 2022-07-15 12:49
Yes HW transform is kinda buggy on vulkan mali gpu.

**Comment by hrydgard** [comment] 2022-07-16 09:11
I need to get a .ppdmp from a place where the difference is obvious between hardware and software transform on Mali.

I've tried messing around with the Toukiden Kiwami demo, but I can't seem to find a difference myself.

A savestate from the demo showing the issue would also work to debug this.

**Comment by Gelo021** [comment] 2022-07-16 19:20
@hrydgard how can i help 😊

**Comment by Gelo021** [comment] 2022-07-16 19:23
Okay i get it u want ne to upload an existing bug 
With a non exisitingbug

So i will get 1 with hardware tranform on and off someting like that ????

**Comment by unknownbrackets** [comment] 2022-07-16 20:13
The GE frame dump is like a "3D screenshot."  It only has the things you see in it.  If the screenshot doesn't show the issue, then it doesn't help with fixing the issue.

I'd suggest you turn OFF hardware transform, and then make the effect happen.  Create the frame dump right then.

I see the issue in the video, but the video is 2D (just a picture of the 3D.)  We need a 3D screenshot (frame dump) to investigate the issue.  But we need it to show the issue, just like the video does.

-[Unknown]

**Comment by Gelo021** [comment] 2022-07-16 20:47
[NPJH50878.zip](https://github.com/hrydgard/ppsspp/files/9126578/NPJH50878.zip)

@unknownbrackets u mean like this ?

**Comment by Gamemulatorer** [comment] 2022-07-17 12:21
What is this?
![Screenshot_2022-07-17-20-20-53-401_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179398036-e2c47258-7988-4a51-8858-e8e6fca755dc.jpg)

**Comment by Gelo021** [comment] 2022-07-17 14:12
[NPJH50878.zip](https://github.com/hrydgard/ppsspp/files/9127842/NPJH50878.zip)

**Comment by Gelo021** [comment] 2022-07-17 14:14
Dont know what happen there, ill make a new one

**Comment by hrydgard** [comment] 2022-07-17 14:29
That one also looks weird, without textures etc. Might be that PPSSPP has some bug that prevents frame dumps to work correctly in this game.

How about a save state file? Those sometimes work for this purpose even without the game.

**Comment by Gamemulatorer** [comment] 2022-07-17 14:30
Are you using the latest build android ppsspp @Gelo021?

**Comment by Gamemulatorer** [comment] 2022-07-17 14:32
Can you uploaded your savestate instead where this issue is can reproduce @Gelo021.

**Comment by Gamemulatorer** [comment] 2022-07-17 15:28
> Hi @hrydgard kinda figured out whats the problem
> 
>  Record_2022-07-15-02-09-51_2f85358b2198d26f8aca533d68bee793.mp4

Looks right to me the effects works properly with hw transform on.
![Screenshot_2022-07-17-23-27-03-638_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179405344-50bb0c17-5c4e-4eda-bcf8-7ab69d133da8.jpg)

**Comment by hrydgard** [comment] 2022-07-17 17:48
@Gamemulatorer since you can seem to get the same effect going at least, can you take a nice frame dump or save state right when that effect is visible? Wanna try on a couple of devices

**Comment by Gelo021** [comment] 2022-07-17 18:09
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/9128281/PPSSPP_STATE.zip)

**Comment by Gamemulatorer** [comment] 2022-07-17 18:10
> @Gamemulatorer since you can seem to get the same effect going at least, can you take a nice frame dump or save state right when that effect is visible? Wanna try on a couple of devices

[Toukiden Kiwami.zip](https://github.com/hrydgard/ppsspp/files/9128282/Toukiden.Kiwami.zip)

**Comment by Gamemulatorer** [comment] 2022-07-17 18:18
@G

**Comment by Gamemulatorer** [comment] 2022-07-17 18:21
Gelo21 can you show your device info and driver bugs screenshots.
![Screenshot_2022-07-18-02-17-35-374_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179419467-e80075f5-47cb-470a-8d8e-8c4794634111.jpg)
![Screenshot_2022-07-18-02-17-50-434_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179419474-9dda21f8-75e5-4138-86a0-b375877420f0.jpg)

**Comment by hrydgard** [comment] 2022-07-17 18:23
Thanks, that state actually loads fine on top of the demo, at least in interpreter. I was able to do a GE dump, which although a little corrupted, does show the effect, so should be usable for debugging: 
[NPJH90348_0001.zip](https://github.com/hrydgard/ppsspp/files/9128301/NPJH90348_0001.zip)

**Comment by Gelo021** [comment] 2022-07-17 18:24
Yes im using the latest build if u want my specs i can upload it

**Comment by Gelo021** [comment] 2022-07-17 18:28
![Screenshot_2022-07-18-02-27-00-93_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/179419685-4d8270ce-bf0c-49e9-a5da-e957c577a72b.jpg)
![Screenshot_2022-07-18-02-26-54-49_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/179419686-5f1533db-e462-43d4-8e77-725f22dc5050.jpg)
![Screenshot_2022-07-18-02-26-46-59_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/179419687-13599fc8-34b5-49c7-a27a-5fc50ab944bd.jpg)
![Screenshot_2022-07-18-02-26-05-71_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/67460268/179419690-11e005ca-9e5a-4784-a93a-a3d030c2a3dd.jpg)

**Comment by hrydgard** [comment] 2022-07-17 18:28
Your specs would be these, right? https://www.gsmarena.com/realme_8i-11069.php

The closest phone I have in terms of GPU is my Galaxy S8+, but cannot reproduce the problem on it :(   I don't have that many other phones with Mali GPUs unfortunately...

**Comment by Gelo021** [comment] 2022-07-17 18:30
@hrydgard yes but it kinda updated recently from android 11 to 12 and  ui 2 to 3

**Comment by Gelo021** [comment] 2022-07-17 18:31
Maybe it have a bug couz of the update last time it works fine

**Comment by Gamemulatorer** [comment] 2022-07-17 18:43
Yeah, this is maybe a driver bug after your phone is updated to android 12.

**Comment by hrydgard** [comment] 2022-07-17 18:48
Wow, it does repro on my Galaxy S21 which indeed has Android 12 and thus a newer driver I guess. That's both good and a shame, for the driver! Gonna have to investigate and report the driver bug...

**Comment by hrydgard** [comment] 2022-07-17 19:10
If I force alpha to 1.0 in the vertex shader:

```
			if (lmode)
				WRITE(p, "  %sv_color1 = splat3(0.0);\n", compat.vsOutPrefix);
		}

		WRITE(p, "  %sv_color0.w = 1.0;\n", compat.vsOutPrefix);
```

It actually draws. So yeah, that tracks with "Hardware Transform", something is going badly wrong in the vertex shader on this driver.

**Comment by hrydgard** [comment] 2022-07-17 19:57
Even simpler, just adding the small increment to red here:

```
else {
  WRITE(p, "  %sv_color0 = u_matambientalpha;\n", compat.vsOutPrefix);
  WRITE(p, "  %sv_color0.r += 0.0000001;\n", compat.vsOutPrefix);
}
```
"fixes" it... 

Rather bizarre.

**Comment by Gelo021** [comment] 2022-07-17 21:50
@hrydgard its hard to understand, kinda think to my self that your is kinda hard hahaha i guess i just a regular person, btw thumbs up fir u lad, best emu ever !!!

**Comment by hrydgard** [comment] 2022-07-17 22:02
Hehe, I'm just posting for myself and anyone interested, to keep track of what potential fixes I've tried.

Anyway, I've just merged a change now that will hopefully fix it, it does for me. So the next available build should have it.

**Comment by Gamemulatorer** [comment] 2022-07-18 02:11
Turning OFF HW Transform introduce this new issue on Burnout Legend using the latest build.
![Screenshot_2022-07-18-09-27-43-883_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179435842-c90f897b-a3a6-4748-9b45-c0f814c61f31.jpg)
[ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9129074/ULUS10025.ppdmp.zip)

**Comment by hrydgard** [comment] 2022-07-18 07:28
That is weird and I'll look into it. But is that really new? Can't see how any recent change could have caused that...

**Comment by Gelo021** [comment] 2022-07-18 11:56
Thank for the fix @hrydgard  ♥️

**Comment by hrydgard** [comment] 2022-07-18 14:28
Thanks for reporting!

**Comment by hrydgard** [comment] 2022-07-19 15:43
That's ... weird. Clearly have an issue with software transform there...

**Comment by Gamemulatorer** [comment] 2022-08-07 07:35
> Turning OFF HW Transform introduce this new graphic issue on Burnout Legend using the latest build. ![Screenshot_2022-07-18-15-10-44-638_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179460847-85821cf8-0c37-4116-b0bf-3b43d6190ea7.jpg)
> 
> HW Transform ON ![Screenshot_2022-07-18-15-10-55-697_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179460958-e53e7d26-deac-4528-9ad9-ac45ad870d8f.jpg)
> 
> **GE Dump** [ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9129074/ULUS10025.ppdmp.zip)

This issue getting worst in latest version.
![Screenshot_2022-08-07-15-34-23-199_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/183280414-1833fe61-c20b-4abc-81fb-83c3c4a54b52.jpg)

**Comment by hrydgard** [comment] 2022-08-07 08:28
Thanks, gonna fix that up.

**Comment by Gamemulatorer** [comment] 2022-11-01 16:57
> Turning OFF HW Transform introduce this new graphic issue on Burnout Legend using the latest build. ![Screenshot_2022-07-18-15-10-44-638_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179460847-85821cf8-0c37-4116-b0bf-3b43d6190ea7.jpg)
> 
> HW Transform ON ![Screenshot_2022-07-18-15-10-55-697_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179460958-e53e7d26-deac-4528-9ad9-ac45ad870d8f.jpg)
> 
> **GE Dump** [ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9129074/ULUS10025.ppdmp.zip)

@IrfanH495 can you please try to reproduce this issue on your Samsung M20 Exynos Mali GPU 😁

**Comment by IrfanH495** [comment] 2022-11-01 18:27
@Gamemulatorer 
default settings
![Screenshot_20221102-011738_PPSSPP](https://user-images.githubusercontent.com/78854859/199309242-6ead3676-0e0c-45d1-bc1e-0c30441cf350.jpg)
![Screenshot_20221102-011751_PPSSPP](https://user-images.githubusercontent.com/78854859/199309269-097482a0-2898-462b-8f71-04a31d74bed4.jpg)

**Comment by IrfanH495** [comment] 2022-11-01 18:28
> > Turning OFF HW Transform introduce this new graphic issue on Burnout Legend using the latest build. ![Screenshot_2022-07-18-15-10-44-638_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179460847-85821cf8-0c37-4116-b0bf-3b43d6190ea7.jpg)
> > HW Transform ON ![Screenshot_2022-07-18-15-10-55-697_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179460958-e53e7d26-deac-4528-9ad9-ac45ad870d8f.jpg)
> > **GE Dump** [ULUS10025.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9129074/ULUS10025.ppdmp.zip)
> 
> @IrfanH495 can you please try to reproduce this issue on your Samsung M20 Exynos Mali GPU 😁

the screenshot you shared is different, what is a different map.

**Comment by IrfanH495** [comment] 2022-11-01 18:35
@Gamemulatorer 
![Screenshot_20221102-013303_PPSSPP](https://user-images.githubusercontent.com/78854859/199311164-9f37d9c4-6a77-4906-b55b-4769c16362a3.jpg)
![Screenshot_20221102-013314_PPSSPP](https://user-images.githubusercontent.com/78854859/199311263-012ee504-06e7-4014-a3c5-515142fe0830.jpg)

**Comment by Gamemulatorer** [comment] 2022-11-02 02:32
> @Gamemulatorer ![Screenshot_20221102-013303_PPSSPP](https://user-images.githubusercontent.com/78854859/199311164-9f37d9c4-6a77-4906-b55b-4769c16362a3.jpg) ![Screenshot_20221102-013314_PPSSPP](https://user-images.githubusercontent.com/78854859/199311263-012ee504-06e7-4014-a3c5-515142fe0830.jpg)

So still causes glitches if hw transform is off...

**Comment by unknownbrackets** [comment] 2022-11-02 06:06
Have the issues changed?  It looks like only the sky is missing in that last one.

-[Unknown]

**Comment by hrydgard** [comment] 2022-11-02 06:20
Sky in this game is notorious for issues on Mali btw, it's the motivation for the EQUAL_WZ_CORRUPTS_DEPTH bug...

**Comment by Gamemulatorer** [comment] 2022-11-03 11:47
@IrfanH495 can you experience crash/freeze on this game using vulkan? see https://github.com/hrydgard/ppsspp/issues/16295#issuecomment-1298735846

**Comment by Saramagrean** [comment] 2022-11-03 15:51
@Gamemulatorer Crash on Vulkan every game since [v1.13.2-1384-gd6bd08cae](https://github.com/hrydgard/ppsspp/commit/d6bd08cae7e42a8838eaec3ccdb15a17a17fd831). if enabled Geometry shader setting (OPPO F5 - Mediatek MT6763T Helio P23, Mali G71 MP2).

**Comment by unknownbrackets** [comment] 2022-11-03 15:53
What driver version is shown under system information?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-11-03 15:57
> @Gamemulatorer Crash on Vulkan every game since [v1.13.2-1384-gd6bd08cae](https://github.com/hrydgard/ppsspp/commit/d6bd08cae7e42a8838eaec3ccdb15a17a17fd831). if enabled Geometry shader setting (OPPO F5 - Mediatek MT6763T Helio P23, Mali G71 MP2).

But my vivo y11 is snapdragon 439 vulkan version 1.1.128

**Comment by Gamemulatorer** [comment] 2022-11-03 17:23
Always freeze during selecting cars
![Screenshot_20221104_012210_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/199791425-9ab378c3-f4ee-448a-8b8b-6b9b3cf07155.jpg)

**Comment by Saramagrean** [comment] 2022-11-04 05:28
> What driver version is shown under system information?
> 
> -[Unknown]

Here.
![313220464_192060573310245_3275530360197185918_n](https://user-images.githubusercontent.com/26355472/199897082-5c1f7dec-59b8-4544-8b11-02884d00a101.jpg)

**Comment by Gamemulatorer** [comment] 2022-11-06 03:11
> Always freeze during selecting cars ![Screenshot_20221104_012210_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/199791425-9ab378c3-f4ee-448a-8b8b-6b9b3cf07155.jpg)

This was regress by https://github.com/hrydgard/ppsspp/commit/b92ea74fb346ba8e56cc8aaa977d01bbc282e012

**Comment by hrydgard** [comment] 2022-11-06 05:32
Thanks for testing, that's quite surprising! Will look into it.

**Comment by Gamemulatorer** [comment] 2022-11-06 05:54
> Thanks for testing, that's quite surprising! Will look into it.

I will create a separate issue for that.

**Comment by hrydgard** [comment] 2022-11-24 22:23
The issue has become a misnomer since the remaining problem is with software transform, not hardware transform, heh.

Anyway, I can repro this in Burnout Legends on my Galaxy S8, nothing else seems to have the problem.

The game has a similar problem on S8 in hardware transform if you disable vendor driver bug workarounds, EQUAL_WZ_CORRUPTS_DEPTH, but it doesn't really look the same, there the clearing draw is corrupt, with this issue the clearing draw doesn't seem to happen (so the z buffer quickly becomes useless leading to the artifacts).

Turning off culling in software transform "fixes" it (it's the clearing draw that's not happening)

SoftwareTransformCommon.cpp line ~593:
```
		// If we don't support custom cull in the shader, process it here.
		if (false && !gstate_c.Use(GPU_USE_CULL_DISTANCE) && vertexCount > 0 && !throughmode) {
```

So yeah, this is basically software triangle culling that's probably very slightly off. It's not used on PC since we have cull and clip planes there, so that's why it doesn't repro there.

**Comment by hrydgard** [comment] 2022-11-24 22:26
Although, hm, I forced it to take this path on PC with 	

```
	// features |= GPU_USE_CULL_DISTANCE;
```

but it doesn't repro..

**Comment by unknownbrackets** [comment] 2022-11-27 07:58
An interesting thing here: for 2/7602, 5/7602, and 6/7602 (which is where depth gets cleared for me), the viewport Z scale here is -0.0f, and the offset is 0.0f.  I didn't think that was common.  It doesn't use that later in the draw.

On Mali, we don't always use accurate depth.  Created #16442.  I do wonder if we still need to disable accurate depth ever, though.  I think as long as you have depth clamp + (clip/cull OR geometry)  then you probably are best off with accurate depth.

Anyway, I guess from the screenshots bad things are happening even for 2/7602.  For that draw, nothing should be culled - z should be approximately 80% of w for all verts.  This is true whether accurate depth is on or off, though... I don't see any reason this would get culled.

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-11-28 03:43
Are there any issues left here or is this fixed now?

-[Unknown]

**Comment by hrydgard** [comment] 2022-11-28 07:02
I think we can close this now

**Closed by hrydgard** 2022-11-28 07:02 UTC
Labels: Vulkan, Mali GPU, GE emulation
