### ISSUE TITLE
Online Chess Kingdoms - black screen at startup (starting with build 0.9.8.1365)

### ISSUE THREAD

**Issue by vitality19** [hrydgard/ppsspp#6924] opened 2014-09-18 21:19 UTC
On Windows and Android this game shows black screen (with 100% speed) starting with build 0.9.8.1365, sorry for delayed report, I was hoping it will be fixed.
![psp](https://cloud.githubusercontent.com/assets/6116857/4327462/58858df0-3f79-11e4-806e-592c44291359.JPG)
![psp2](https://cloud.githubusercontent.com/assets/6116857/4327690/cb5157d6-3f7b-11e4-8ed7-c56ba31b0415.JPG)

**Comment by unknownbrackets** [comment] 2016-05-28 21:01
What if you log `sceIoGetstat` or `sceUtilityGetSystemParamInt` instead in JpcspTrace?

-[Unknown]

**Comment by sum2012** [comment] 2016-05-29 23:15
Only gid15 version of jpcsptrace work,
log:
https://gist.github.com/sum2012/a7ee790553e5bd60270626a6df60dbeb

**Comment by unknownbrackets** [comment] 2016-05-30 04:57
Okay, interesting.  I found that I can reproduce this behavior... but it's strange.

```c++
#include <common.h>
#include <pspthreadman.h>

volatile bool shouldLoop = true;

int doSleep(SceSize argc, void *argp) {
	sceKernelSleepThreadCB();
	return 0;
}

int doDelay(SceSize argc, void *argp) {
	while (shouldLoop) {
		sceKernelDelayThread(0);
	}
	return 0;
}

extern "C" int main() {
	SceUID sleepThread = sceKernelCreateThread("sleep", &doSleep, 32, 4000, 0, NULL);
	sceKernelStartThread(sleepThread, 0, NULL);
	SceUID delayThread = sceKernelCreateThread("delay", &doDelay, 16, 4000, 0, NULL);
	sceKernelStartThread(delayThread, 0, NULL);

	shouldLoop = false;

	sceKernelWaitThreadEnd(delayThread, NULL);
	sceKernelTerminateDeleteThread(delayThread);
	sceKernelTerminateDeleteThread(sleepThread);

	checkpoint("Great success");

	return 0;
}
```

With the above, `sceKernelDelayThread(0)` DOES delay.  However, ithis does not delay:

```c++
#include <common.h>
#include <pspthreadman.h>

volatile int delayAmount = 0;
volatile bool shouldLoop = true;

int doDelay(SceSize argc, void *argp) {
	int c = 0;
	u64 st = sceKernelGetSystemTimeWide();
	while (shouldLoop) {
		c++;
		sceKernelDelayThread(delayAmount);
		schedf("  * Loop: %lld (%d)\n", sceKernelGetSystemTimeWide() - st, delayAmount);
	}
	checkpoint("  Got to %d", c);
	return 0;
}

extern "C" int main() {
	SceUID delayThread = sceKernelCreateThread("delay", &doDelay, 16, 4000, 0, NULL);
	sceKernelStartThread(delayThread, 0, NULL);

	delayAmount = 1000;
	shouldLoop = false;

	sceKernelWaitThreadEnd(delayThread, NULL);
	sceKernelTerminateDeleteThread(delayThread);

	checkpoint("Great success");

	return 0;
}
```

I'm not really sure why.  If you comment out `schedf("  * Loop: %lld (%d)\n", sceKernelGetSystemTimeWide() - st, delayAmount);` it only does 3-5 iterations before finishing, so it almost seems like a timeslice thing?

Anyway, seems fair enough to allow 0 to delay for a short amount of time.  Sometimes it does, that's good enough for me.  The JpcspTrace seems to be showing it not delaying, but it must be sometimes delaying - just enough for it to eventually recover.

-[Unknown]

**Comment by sum2012** [comment] 2016-05-30 11:41
Test v1.2.2-607-g21ba67e
fixed,closing
log:
https://gist.github.com/sum2012/e3a6765a88a09704d757da65e1286f9a

**Closed by sum2012** 2016-05-30 11:41 UTC
