### ISSUE TITLE
(Android) Silent Hill Original graphical glitches in the fog and the hospital dark areas

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10188] opened 2017-11-24 23:45 UTC
In your first visit to Silent Hill you can see some glitches when the fog is shown. It can be fixed by using the "Lower resolution for effects" option.
However, later in the game when you go to the hospital (second floor) the same glitches appear when you switch the flashlight on and off.
As with the fog, this issue can be temporary fixed if I use the above option, but as soon as I use the flashlight you can see the glitches again.

**Comment by unknownbrackets** [comment] 2017-11-30 15:03
This issue is being closed as a duplicate - the flash light issue is already #6265.

The bad fog is a natural result of upscaling rendering, which is what that setting was introduced for.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-11-30 15:03 UTC
Labels: Platform-specific (Android)
