### ISSUE TITLE
Flickering textures in Heroes of Phantasia

### ISSUE THREAD

**Issue by 716Girl** [hrydgard/ppsspp#8051] opened 2015-10-11 08:50 UTC
https://www.youtube.com/watch?v=C0DuGFFUMSA Not my video but i found it on youtube, I have the same problem

**Comment by hrydgard** [comment] 2015-10-11 10:24
Duplicate of #6485 , closing. The cause is that the game relies on getting ordered rendering when it draws a bunch of things with nearly, but not the same, depth value, and on OpenGL we get a 24-bit depth buffer while the PSP only has a 16-bit. This extra precision causes things to get jumbled.

I thought #7920 would have helped, but it appears that the depth is not uniform per triangle so it doesn't. 

#7922 mostly works around it, but eats performance.

We might have to do a per-game hack...

**Closed by hrydgard** 2015-10-11 10:24 UTC
