### ISSUE TITLE
The 3rd Birthday (fog in some GLES gpus)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#6526] opened 2014-07-09 06:44 UTC
in beffered rendering (block transfer on/off is the same,also dissable alpha mask hack do nothing)
![img_0063](https://cloud.githubusercontent.com/assets/4172898/3520635/1550c1c6-0734-11e4-91ca-187f6fa4bdf5.PNG)

in read buffer to memory (gpu) looks a bit better
![img_0062](https://cloud.githubusercontent.com/assets/4172898/3520667/68613ec2-0734-11e4-86f6-063b5a1a26e6.PNG)
test build 0.9.8-1574

**Comment by unknownbrackets** [comment] 2015-02-23 21:41
Has this improved at all in the latest version (v1.0-101-g1170331 or newer)?

-[Unknown]

**Comment by brujo5** [comment] 2015-02-24 06:57
Will test tomorrow early.

**Comment by brujo5** [comment] 2015-02-24 17:32
@unknownbrackets 
Think fixed, what you think?

![image](https://cloud.githubusercontent.com/assets/4172898/6355013/633efd4e-bc10-11e4-9ec5-0a89d3bab402.jpg)

**Comment by hrydgard** [comment] 2015-02-24 17:35
That looks right.

**Comment by brujo5** [comment] 2015-02-24 17:43
@hrydgard 

Here in non-befered rendering 
![image](https://cloud.githubusercontent.com/assets/4172898/6355227/abcb9ee0-bc11-11e4-961b-10cae844bab9.jpg)

Here in befered rendering + slow effects ON+ GPU block transfer ON
![image](https://cloud.githubusercontent.com/assets/4172898/6355247/d1455bc0-bc11-11e4-9758-b73c7cee93a8.jpg)

**Comment by unknownbrackets** [comment] 2015-02-24 18:53
That doesn't look any different from before.  I think it's just that you had slow effects disabled.

-[Unknown]

**Comment by brujo5** [comment] 2015-02-24 20:09
Yeap that whit befered rendering+ slow effects offs 
Note: Powervr alphatest off/on is the same
![image](https://cloud.githubusercontent.com/assets/4172898/6358091/67347f94-bc26-11e4-903f-a625afbff393.jpg)

**Comment by unknownbrackets** [comment] 2015-12-30 18:23
The above screenshot doesn't really look wrong to me.  It's a bit bluer and darker as hrydgard mentioned.  Closing.

-[Unknown]

**Comment by daniel229** [comment] 2015-12-31 01:47
The fog is not rendering in above screenshot.

**Comment by unknownbrackets** [comment] 2017-06-17 03:21
FWIW, checked quickly - this is what would happen if depal resulted in a completely white texture.  It doesn't seem related to dual source blending or framebuffer fetch or anything.

The stages of depal are (may be noted elsewhere, but just to recap):
 * Screen -> temporary, extracting top 4 bits of G from 8888 to 4444, but only the R channel has values in CLUT.
 * Temporary -> temporary, to blur using blending.  In this case all components are set to the same value as R, creating a grayscale blurry version of the top 4 bits of G.
 * Temporary -> screen, again mapping R to all components (this is why dualsrc doesn't matter.)

White could occur if the depal index became `15` for all pixels, since that color is white.

Also worth noting is that a single temporary is used, so the `temporary -> temporary` step is render-to-self (but since it's depal, we should be using a temporary buffer...)

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-05-06 18:35
How does this look now?

-[Unknown]

**Comment by psennermann** [comment] 2018-05-07 17:04
On my Samsung Galaxy Tab 2 official PPSSPP 1.5.4 still has this problem...is there a particular reason (presumed fix) to test a new development version?

**Comment by unknownbrackets** [comment] 2018-05-08 02:46
Latest git builds have lots of changes to OpenGL, some state handling fixes, and recent fixes to depal handling.  So yes - worth testing, I think.  Will soon be 1.6.0.

When it still has this problem - does it still have wrong fog, or missing fog?

-[Unknown]

**Comment by psennermann** [comment] 2018-05-08 16:44
Ok, I've tried 1.5.4-971 and from what I can see the problem is fixed only using Vulkan, while OpenGL still has the "overbrightness" (fixed only by disabling slow effects)

**Comment by unknownbrackets** [comment] 2018-05-08 23:26
Okay - it could be the depal stuff then, we have some disabled code to do the same thing for OpenGL we do for Vulkan (on GPUs that support it), but we don't plan to enable until after 1.6.0.

Noting #10908 here so we remember to take another look.  Hopefully it's related to that.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-08-21 16:46
Great.  Going to close this then.

-[Unknown]

**Closed by unknownbrackets** 2018-08-21 16:46 UTC
Labels: OpenGL
