### ISSUE TITLE
Zettai Zetsumei Toshi 3: Kowareyuku Machi to Kanojo no Uta stuck on character selection

### ISSUE THREAD

**Issue by ivyking007** [hrydgard/ppsspp#8245] opened 2015-11-29 15:47 UTC
latest dev build also have this problem dont know why

**Comment by daniel229** [comment] 2015-11-29 23:30
Duplicate of https://github.com/hrydgard/ppsspp/issues/4901

**Closed** 2015-11-29 23:44 UTC

**Comment by ivyking007** [comment] 2015-11-30 08:29
#4901 i followed all the instrustions on this post also dont work

**Comment by ivyking007** [comment] 2015-11-30 08:30
v1.1.1 340 dev build

**Comment by ivyking007** [comment] 2015-11-30 08:30
@unknownbrackets

**Comment by ivyking007** [comment] 2015-11-30 08:32
dont close this issue , this also exist on latest dev build @unknownbrackets

**Comment by ivyking007** [comment] 2015-11-30 13:10
@unknownbrackets

**Comment by deadair3210** [comment] 2015-11-30 16:03
Stop spamming the devs with mentions! If the issues is the same as the other issue, post that the issue still stands on the other report. This issue was closed because it is a duplicate of the other issue

**Comment by unknownbrackets** [comment] 2015-11-30 19:32
Well aware that #4901 exists in the latest dev build.  There's no reason to keep ourselves disorganized and confused with lots of different versions of the same issue in the same latest dev build open.

If you're looking for a support forum, that's over here:
http://forums.ppsspp.org/

This is not a support forum.  It's a bug tracker, like a todo list.  In a todo list, duplicates are supposed to be removed as soon as they are found.  You don't list "buy bread" on a todo list 20 times when you only want to buy bread once, right?

-[Unknown]
