### ISSUE TITLE
Text in R-Type Tactics II -Operation Bitter Chocolate- renders as white blocks with OpenGL on android, Vulkan renders properly.

### ISSUE THREAD

**Issue by padoverc** [hrydgard/ppsspp#15503] opened 2022-04-25 04:31 UTC
### Game or games this happens in

NPJH-50119 - R-Type Tactics II -Operation Bitter Chocolate-

### What area of the game / PPSSPP

All non-pre-rendered text is shown as white blocks, rather than the proper kana/kanji. This can be seen from the very first text box after selecting 'New Game'. This only happens when using OpenGL as the graphics back end, Vulkan renders text properly. 

### What should happen

Text should appear normally.

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy Note 9 (Snapdragon, Android 10)

### PPSSPP version affected

v1.12.3-1098-gec05bce06

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-04-25 04:33
Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

Also, does this happen in v1.12.3 stable?

-[Unknown]

**Comment by padoverc** [comment] 2022-04-25 05:02
1.12.3 stable works fine. Phone is being a pain on connecting for the GE Dump, sorry.

**Comment by Gamemulatorer** [comment] 2022-04-25 07:03
I have a similar issue in Digimon Adventure using opengl the background turns white.
![Screenshot_2022-04-25-14-59-58-511_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/165036789-0c188256-02f8-496f-88ff-ce30bca74b8a.jpg)

**Comment by hrydgard** [comment] 2022-04-25 07:06
@Gamemulatorer did that just happen in the last few commits, or do you know if it's been around a while? I'll look into it soon anyway

**Comment by Gamemulatorer** [comment] 2022-04-25 07:06
Can't use ge debbuger using mobile data 😔

**Comment by Gamemulatorer** [comment] 2022-04-25 07:10
> @Gamemulatorer did that just happen in the last few commits, or do you know if it's been around a while? I'll look into it soon anyway

It's been around awhile but forget to report I already knew this since https://github.com/hrydgard/ppsspp/issues/12188#issuecomment-1102589344 I report that issue.

**Comment by hrydgard** [comment] 2022-04-25 07:11
ok, thanks. seems to be a few more texturing regressions with GL after the recent optimizations, I'll get them sorted soon, hopefully it will take care of it.

**Comment by Panderner** [comment] 2022-04-25 10:02
@Gamemulatorer here:
[Digimon.zip](https://github.com/hrydgard/ppsspp/files/8553537/Digimon.zip)

**Comment by Gamemulatorer** [comment] 2022-04-25 13:29
Can also reproduce this in Soul Eater Battle Resonance.

ogl
![Screenshot_2022-04-25-20-03-23-493_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/165098620-ca6ee208-d819-4e6e-8e2d-0a3eca49a5d7.jpg)

vk
![Screenshot_2022-04-25-20-03-45-229_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/165098707-909d0352-d86d-4360-89d1-5e6796f9744f.jpg)

**Comment by hrydgard** [comment] 2022-04-25 15:32
Thanks guys, that'll be enough to debug it. Will do soon.

**Comment by unknownbrackets** [comment] 2022-04-25 18:18
Any issues left in the latest git build with these specific cases?

-[Unknown]

**Comment by Panderner** [comment] 2022-04-25 18:53
It's now fixed for Digimon & Soul Eater:
![Screenshot (27)](https://user-images.githubusercontent.com/37503397/165154968-0cf23bc0-671a-4bda-8ddf-a66d7773eed9.png)

**Comment by padoverc** [comment] 2022-04-25 20:04
R-TYPE Tactics II is fixed on gl with the new build.

**Comment by unknownbrackets** [comment] 2022-04-25 20:09
Thanks for confirming. I'll close this as it sounds like it's fixed now.

-[Unknown]

**Closed by unknownbrackets** 2022-04-25 20:09 UTC
Labels: OpenGL, GE emulation
