### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by aa89080900** [hrydgard/ppsspp#13433] opened 2020-09-15 03:19 UTC

**Comment by Panderner** [comment] 2020-09-15 03:32
what?

**Comment by Gamemulatorer** [comment] 2020-09-15 03:33
😂 duplicate of #13120 and #13376 useless report

**Comment by fahadrashid7705** [comment] 2020-09-15 04:33
maybe he sliped

**Comment by unknownbrackets** [comment] 2020-09-15 04:44
Fixed in 4f7ad15.

-[Unknown]

**Closed by unknownbrackets** 2020-09-15 04:44 UTC
