### ISSUE TITLE
GCC "sorry, unimplemented: non-trivial designated initializers not supported" while building.

### ISSUE THREAD

**Issue by tuankiet65** [hrydgard/ppsspp#7958] opened 2015-09-11 08:47 UTC
Error log: https://gist.github.com/tuankiet65/cd41f2ed375e1c428376 (failed at ext/xbrz/xbrz.cpp)
GCC version:
````
tuankiet65@localhost:[~/sources/ppsspp/build][Fri Sep 11 03:10 PM]$ gcc --version
gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Comment by LunaMoo** [comment] 2015-09-11 11:01
Duplicate of #7717 ~ as you can read there, it's caused by a bug in gcc fixed in v5.2.0.

**Closed** 2015-09-11 13:23 UTC
