### ISSUE TITLE
NBA Live 2010 texture problems

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#11117] opened 2018-06-01 18:31 UTC
I am using the v1.6.2-5-gaadced94f x64  version and in game i am getting texture glitches

![ff](https://user-images.githubusercontent.com/5770076/40857174-720f26a4-65eb-11e8-9cfa-02f6df12eb83.gif)

log

[InfoLog.zip](https://github.com/hrydgard/ppsspp/files/2063758/InfoLog.zip)

**Comment by unknownbrackets** [comment] 2018-06-02 03:16
This issue is being closed as a duplicate of #6614.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-06-02 03:16 UTC
