### ISSUE TITLE
Two shaders request

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13422] opened 2020-09-12 20:28 UTC
Just want to ask if it's possible using two diferrent shader at one time? If it possible, will it make PPSSPP lag? Cause i like to merge shaders if possible so i can get the graphic effect that I want. But if it's not possible please just close this thread. Thanks

**Comment by Gamemulatorer** [comment] 2020-09-12 22:38
duplicate of #11909

**Comment by hrydgard** [comment] 2020-09-12 22:47
Indeed, closing as dupe of #11909

**Closed by hrydgard** 2020-09-12 22:47 UTC
