### ISSUE TITLE
Patapon 3 Multiplayer

### ISSUE THREAD

**Issue by Tail870** [hrydgard/ppsspp#11685] opened 2018-12-20 17:09 UTC
**### What happens?**
We've tried to play Patapon 3 [EU] using PPSSPP in multiplayer, but with two players (host+client) it gliches to 1st player (which are host's - second player can't control it's own character, skills gliches, etc). With  [fix](https://www.youtube.com/watch?v=xv2FNJigjew) two players can play it.

When tried to play with 2+ players all players are losing connection.

The game are licensed from PSN, eboot.pbp format, not modyfied. Code: UCES-01421

**### What *should* happen?**
Normal multiplayer gameplay up to 4 players in co-op mode.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Different hardware x64 systems with Windows 10.
Tested PPSSPP versions: 
**1.7.4** x64
**v1.7.5-308-gfb3ba7007** x64

**Comment by LunaMoo** [comment] 2018-12-20 21:44
Closing as a duplicate of #8771

**Closed by LunaMoo** 2018-12-20 21:44 UTC
Labels: Networking / adhoc
