### ISSUE TITLE
魔法少女リリカルなのはA"s PORTABLE-THE GEARS OF DESTINY graphical glitch after enabled vulkan

### ISSUE THREAD

**Issue by ss8688** [hrydgard/ppsspp#13599] opened 2020-10-29 09:36 UTC
after enabled vulkan images on upper left corner and upper right corner just disappear.

**Comment by ss8688** [comment] 2020-10-29 09:46
I can  not upload screenshots on github now. maybe later

**Comment by ss8688** [comment] 2020-10-29 09:49
![Screenshot_20201010_132152_org ppsspp ppsspp](https://user-images.githubusercontent.com/59367202/97552102-cc09f100-1a0e-11eb-89a2-79df96cb6e59.jpg)

opengl

**Comment by ss8688** [comment] 2020-10-29 09:50
![Screenshot_20201010_132252_org ppsspp ppsspp](https://user-images.githubusercontent.com/59367202/97552372-25722000-1a0f-11eb-8b51-4b3a4b6a9b3c.jpg)

vulkan

**Comment by ss8688** [comment] 2020-10-29 09:51
Emui 10(Android10)
ppsspp latest version

**Comment by hrydgard** [comment] 2020-10-29 10:04
can you grab a GE frame dump and upload it here?

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by ss8688** [comment] 2020-10-29 10:06
> 您可以抓住GE帧转储并将其上传到这里吗？
> 
> https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

Ok, but maybe later,because I don't have time now

**Comment by hrydgard** [comment] 2020-10-29 10:09
it will greatly help investigation if you do :)

**Comment by ss8688** [comment] 2020-10-29 10:31
[ULJS00385_0002.zip](https://github.com/hrydgard/ppsspp/files/5457696/ULJS00385_0002.zip)
@hrydgard

**Comment by hrydgard** [comment] 2020-10-29 11:08
Thanks, the frame dump works - on my PC though, it works fine in Vulkan. I'll try on some phones later to see if I can get a repro, so I can try some things.

**Comment by Panderner** [comment] 2021-01-11 02:24
This does not reproduce this issue on POCO M3 using Vulkan
![Screenshot_2021-01-11-10-22-52-989_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104142560-1805e880-53f7-11eb-89d1-050fd5453109.jpg)

**Comment by ss8688** [comment] 2021-01-11 04:14
But I have two honor 9x have the same problem


> This does not reproduce this issue on POCO M3 using Vulkan
> ![Screenshot_2021-01-11-10-22-52-989_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104142560-1805e880-53f7-11eb-89d1-050fd5453109.jpg)

**Comment by Panderner** [comment] 2021-01-11 08:06
> But I have two honor 9x have the same problem
> 
> > This does not reproduce this issue on POCO M3 using Vulkan
> > ![Screenshot_2021-01-11-10-22-52-989_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104142560-1805e880-53f7-11eb-89d1-050fd5453109.jpg)

@ss8688 have you updated to latest build?

**Comment by ss8688** [comment] 2021-01-11 09:54
> > But I have two honor 9x have the same problem
> > > This does not reproduce this issue on POCO M3 using Vulkan
> > > ![Screenshot_2021-01-11-10-22-52-989_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104142560-1805e880-53f7-11eb-89d1-050fd5453109.jpg)
> 
> @ss8688 have you updated to latest build?

Yes，I have

**Comment by Panderner** [comment] 2021-01-11 11:48
This does reproduce this issue for @ss8688's Honor 9X. It does not reproduce on my POCO M3

**Comment by hrydgard** [comment] 2021-01-11 12:14
Mali driver bug then probably... gah.

**Comment by ss8688** [comment] 2021-02-22 04:26
@hrydgard I have a same problem as https://github.com/hrydgard/ppsspp/issues/11980
So，It might not a mail drvier problem.

**Comment by ss8688** [comment] 2021-02-22 04:30
![Uploading Screenshot_20210222_123037_org.ppsspp.ppsspp.jpg…]()

**Comment by ss8688** [comment] 2021-02-22 04:31
![Screenshot_20210222_123037_org ppsspp ppsspp](https://user-images.githubusercontent.com/59367202/108662678-d09c6d00-7509-11eb-9b3f-9014577fdaad.jpg)

**Comment by ss8688** [comment] 2021-02-22 04:35
all test is ok 
![Screenshot_20210222_123348_org ppsspp ppsspp](https://user-images.githubusercontent.com/59367202/108662894-46a0d400-750a-11eb-878e-e92e09b2c9ba.jpg)
![Uploading Screenshot_20210222_123350_org.ppsspp.ppsspp.jpg…]()

**Comment by ss8688** [comment] 2021-02-22 04:36
![Screenshot_20210222_123350_org ppsspp ppsspp](https://user-images.githubusercontent.com/59367202/108663003-810a7100-750a-11eb-9a35-8ac6ee271d4e.jpg)

**Comment by hrydgard** [comment] 2021-02-22 08:59
It could be a bug that only affects certain versions of the Mali driver, of course.

**Comment by ss8688** [comment] 2021-02-22 09:27
@hrydgard 
I don't think a gpu driver bug can affects both Mail  
gpu and Adreno gpu (see https://github.com/hrydgard/ppsspp/issues/11980)

**Comment by unknownbrackets** [comment] 2021-02-23 05:41
This happens on draw 4657/4696, which is a ALWAYS REPLACE 02, alpha a >= 1, with depth test disabled.  Basically same situation as #11980.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-02-23 14:48
Is this working now?

**Comment by ss8688** [comment] 2021-02-23 15:24
@unknownbrackets Not working properly. 
![Screenshot_20210223_231539_org ppsspp ppsspp](https://user-images.githubusercontent.com/59367202/108865257-033f8600-762e-11eb-8153-faa5797c9e77.jpg)
But I am still using the old config files

**Comment by ss8688** [comment] 2021-02-23 15:28
I hear that Huawei mate 30 seems have this problem too.

**Comment by unknownbrackets** [comment] 2021-02-23 16:15
Since this is really the same issue and both reproduce only on specific drivers for Adreno and Mali devices due to a known bug, I'm going to close this as a duplicate of #11980.

-[Unknown]

**Closed by unknownbrackets** 2021-02-23 16:15 UTC
Labels: Mali GPU, Vulkan
