### ISSUE TITLE
"Record display" produces video with frames out of order

### ISSUE THREAD

**Issue by boringhexi** [hrydgard/ppsspp#12068] opened 2019-05-27 15:37 UTC
### What happens?
Affected games include:
* Gitaroo Man Lives! [Korea, possibly other regions are affected too] (ULKS46071)
* Dissidia Final Fantasy [USA demo] (NPUH90029)
* Gangs of London [USA demo] (UCUS98689)

In some games, the video output in the emulator window looks just fine, but using "Record display" results in a video file with a weird blur-like effect, seemingly caused by video frames being in the wrong order.

Example video: https://youtu.be/29zkoUCzJaU

This problem does not seem to happen when Software rendering is enabled.

### What *should* happen?
The recorded video should match what is displayed in the emulator window, without the blur-like effect.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
GPU: Intel HD Graphics 3000
Operating system: Windows 10 Pro (Version 1803 OS Build 17134.472)
PPSSPP version: 1.8.0-237-gd0d8ea3fb (Windows buildbot build)
Rendering backend: Direct3D 11

**Comment by LunaMoo** [comment] 2019-05-27 18:21
Closing as a duplicate of #10632, please DON'T open duplicate issues, it will make things slower to solve, not faster.

**Closed by LunaMoo** 2019-05-27 18:21 UTC
