### ISSUE TITLE
Windows 10 not recognized 

### ISSUE THREAD

**Issue by daniellegal** [hrydgard/ppsspp#7894] opened 2015-08-08 23:38 UTC
When i see my info in ppsspp it shows that i have windows 8 and not windows 10
please fix it i dont think is that hard to fix this

**Comment by ppmeis** [comment] 2015-08-10 00:10
Issue Confirmed with latest build:
![image](https://cloud.githubusercontent.com/assets/4381277/9157612/f393a6f2-3f04-11e5-9dec-05d125259981.png)

**Comment by thedax** [comment] 2015-10-15 05:55
Re-opening since it's now an "issue" again.

**Comment by unknownbrackets** [comment] 2015-12-26 17:49
I guess the best we can do here is detect using `cmd /c ver` or something?  Ugly, though.  Not sure if it's that important, really...

-[Unknown]

**Comment by helloimowen** [comment] 2016-04-22 14:39
Changed the string to "Microsoft Windows 8 or greater" to hold us over until using VersionHelpers.h commands is viable. (If ever.) 
I found [someone](https://github.com/lordmulder/stdutils/releases/tag/1.06) who fixed this bug using getFileVersionInfo and kernel32.dll . Interesting work-around.

**Comment by unknownbrackets** [comment] 2018-09-30 07:43
Fixed in #11432.  Used the product version on kernel32.dll, which is even suggested in MSDN.

-[Unknown]

**Closed by unknownbrackets** 2018-09-30 07:43 UTC
Labels: Feature Request, Platform-specific (Windows)
