### ISSUE TITLE
Phantasy Star Portable 2 floor clipping on ppsspp 1.7 and above

### ISSUE THREAD

**Issue by CaioVdmm** [hrydgard/ppsspp#11649] opened 2018-12-08 16:57 UTC
the game Phantasy Star Portable 2 is with the texture of the floor disappearing like the photo below:
![screenshot_20181208_144519](https://user-images.githubusercontent.com/38089667/49688419-b298ec80-faf8-11e8-9b13-9a64c6e098b7.png)
see the lower left corner

and here is the frame dump: [https://drive.google.com/file/d/1q39CsBfa17HJtTKGs-Qy9G0dD7kRutOP/view?usp=sharing](url)

sorry for my english, i'm braziliam

**Comment by Abbanon** [comment] 2018-12-08 17:15
Duplicate of #11576

**Comment by unknownbrackets** [comment] 2018-12-08 19:33
This issue is being closed as a duplicate of #11576.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-12-08 19:33 UTC
