### ISSUE TITLE
Kurohyo 2 missing blur effect in battle

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8390] opened 2016-01-05 08:26 UTC
PPSSPP
![02](https://cloud.githubusercontent.com/assets/3481559/12110605/f1e9f0b6-b3c8-11e5-9d82-8f7ee5ccccae.png)

PSP
![201601051610_001](https://cloud.githubusercontent.com/assets/3481559/12110606/f1ea9a34-b3c8-11e5-9c79-51daf373ff74.png)

**Comment by daniel229** [comment] 2016-01-05 08:30
Same as https://github.com/hrydgard/ppsspp/issues/5205 ?

**Comment by unknownbrackets** [comment] 2016-01-05 08:36
I think this is somehow depth buffer related.  It textures from 0x04288000, which is the (swizzled) address of the depth buffer.  It actually does this using a CLUT.

It builds a bloom mask and everything, but this always has alpha/stencil = 0.  When it blends it back in, it never blends any of it.  Additionally, it does rendering using mode 565, and then uses this mask as 4444.

My suspicion is that it uses the depth buffer to establish the alpha component of the bloom mask, which would then establish the amount of bloom for the farther away things.

-[Unknown]

**Comment by hrydgard** [comment] 2022-07-26 19:05
This one could be fun to investigate in detail, as it's kinda related to some recent and not so recent work - basically seems like a combination of depth stuff and 565/4444 reinterpret (can maybe even use the blue-to-alpha hack?). Anyone got some GE dumps?

**Comment by Gamemulatorer** [comment] 2022-07-28 13:53
I don't know if this right?😅
[NPJH50333.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9210287/NPJH50333.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2023-03-14 04:37
This is also look fix now
![Screenshot_20230314_123415_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/224894415-172d4620-c51d-4fab-aeb7-c5577b4487e1.jpg)

But during that scene the game fps is drop drastically.
Here's a ge dump
[NPJH50333.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10964142/NPJH50333.ppdmp.zip)

**Comment by hrydgard** [comment] 2023-03-14 08:26
It's an expensive effect to emulate, I guess.. 

I'll close this since it's technically fixed. May look at performance later.

**Closed by hrydgard** 2023-03-14 08:26 UTC
Labels: Depth Texture

**Comment by Gamemulatorer** [comment] 2023-03-14 08:43
> It's an expensive effect to emulate, I guess..
> 
> I'll close this since it's technically fixed. May look at performance later.
> 
> If you turn on debug statistics, do you see any readbacks?

![Screenshot_20230314_164234_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/224944626-697bb794-f0a8-4f63-b3e6-d4f1a80924f4.jpg)

**Comment by hrydgard** [comment] 2023-03-14 09:15
Yeah, since it says "readbacks: 0", that's not the cause of the slowdown indeed. Was just curious, since the slow down is so large.

Does reducing the rendering resolution help a lot here?

**Comment by Gamemulatorer** [comment] 2023-03-14 09:26
> Yeah, since it says "readbacks: 0", that's not the cause of the slowdown indeed. Was just curious, since the slow down is so large.
> 
> Does reducing the rendering resolution help a lot here? "depal 11" means it's doing a lot of tricky framebuffer effects though..

Yes reducing rendering resolution improve the performance 😄
