### ISSUE TITLE
Crashing without even starting (OpenSL init crash)

### ISSUE THREAD

**Issue by TheCruzJ4v5** [hrydgard/ppsspp#14529] opened 2021-06-13 07:47 UTC
### What happens?
As soon as the app is even launched it ,crashes and the phone goes to landscape mode

### What *should* happen?
The app should open.

#### What hardware / device and operating system?
Poco F1(beryllium)
Android 11

#### What graphics card (GPU) or mobile phone model?
Adreno 630 GPU 
Sd 845 Soc

#### What PPSSPP version (standalone/official), and did it work before?
It used to work before but even the latest version doesn't work. 
#### Which game or games?
It doesn't even start.

#### Screen Recording
https://photos.app.goo.gl/ZkDwJ4QpsUyJP6Tg9

#### Checklist

 - [X ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ X] Try resetting settings or older versions and include if the issue is related.
 - [ X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2021-06-13 08:36
What does (beryllium) mean?

Can you get ADB logs?

**Comment by Gamemulatorer** [comment] 2021-06-13 08:53
> What does (beryllium) mean?
> 
I think that is Xiaomi phone codename like mine is Merlin (RN9)
https://c.mi.com/thread-1911812-1-1.html

**Comment by Gamemulatorer** [comment] 2021-06-13 08:54
@TheCruzJ4v5 please try the latest ppsspp development apk here~https://buildbot.orphis.net/ppsspp/

**Comment by TheCruzJ4v5** [comment] 2021-06-13 09:01
Actually beryllium is the codename of the phone(Xiaomi Pocophone F1).
https://docs.google.com/document/d/1Us7SwU-X-64RsGMGZ75HXlNR7KUloVuoBYiZVy4k0yw/edit?usp=drivesdk

**Comment by TheCruzJ4v5** [comment] 2021-06-13 09:02
@hrydgard  Thanks a lot for responding.
@Gamemulatorer  I tried but the same thing occurs.

**Comment by Gamemulatorer** [comment] 2021-06-13 09:05
I think @hrydgard also have a Poco F1 phone

**Comment by hrydgard** [comment] 2021-06-13 09:30
I do actually, but I didn't know beryllium was a code name.

Haven't had problems running PPSSPP on it, will try the latest build again...

**Comment by TheCruzJ4v5** [comment] 2021-06-13 11:34
What am I supposed to do now?😅

**Comment by Gamemulatorer** [comment] 2021-06-13 13:05
> What am I supposed to do now?😅

Try older version of ppsspp until where it works on your phone..

**Comment by hrydgard** [comment] 2021-06-14 07:20
OK, just tried booting up the very latest build on my Pocophone F1, and it works just fine. Not sure what's going on with yours.

Might need a hardware reset? Just reboot it? You don't have a custom Android build on it right?

**Comment by TheCruzJ4v5** [comment] 2021-06-14 08:14
Yes Im on a custom ROM

**Comment by hrydgard** [comment] 2021-06-14 09:08
Yeah, well, that's your problem then, your custom ROM is broken somehow.

Maybe it's possible to work around from PPSSPP, maybe not. All I know is that to do anything, I'm gonna need ADB logs. If you have ADB (from the Android SDK) installed, and your phone connected, here's a convenient line that captures everything from PPSSPP:

` adb logcat -s AndroidRuntime DEBUG PPSSPPNativeActivity PPSSPP NativeGLView NativeRenderer NativeSurfaceView PowerSaveModeReceiver InputDeviceState PpssppActivity`

But without that output, nothing I can do.

**Comment by TheCruzJ4v5** [comment] 2021-06-14 10:43
Here https://docs.google.com/document/d/1wW8Jmnpf_FNxfZBZtUwF2I8IXiSy6P1f6AG2yzsv-dw/edit?usp=drivesdk

**Comment by TheCruzJ4v5** [comment] 2021-06-14 10:43
Thanks

**Comment by Gamemulatorer** [comment] 2021-06-14 10:54
> Here https://docs.google.com/document/d/1wW8Jmnpf_FNxfZBZtUwF2I8IXiSy6P1f6AG2yzsv-dw/edit?usp=drivesdk

Pleae enable google access

**Comment by hrydgard** [comment] 2021-06-14 13:02
Thanks.

It crashes trying to initialize audio, it seems:

```
06-14 15:34:38.078 22685 22685 F DEBUG   :       #01 pc 000000000055d00c  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2308) (BuildId: edd92a7af1552c8e00b74ecfac823ad8)
06-14 15:34:38.078 22685 22685 F DEBUG   :       #02 pc 0000000000013978  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76) (BuildId: 5ddeb405cbf5aa6e6ee96e6f09211cdd)
06-14 15:34:38.078 22685 22685 F DEBUG   :       #03 pc 0000000000006e18  /system/lib64/liblog.so (__android_log_assert+336) (BuildId: b5b2ed9d2859e7c956635d8bdb685c6f)
06-14 15:34:38.078 22685 22685 F DEBUG   :       #04 pc 00000000006603a4  /data/app/~~znebrAhbl6TubRMjz6cfXw==/org.ppsspp.ppsspp-XItxXP74k3UfNSnJ0MJQEw==/lib/arm64/libppsspp_jni.so (HandleAssert(char const*, char const*, int, char const*, char const*, ...)+248) (BuildId: 8ecc372268c096479c6d71fb67f3f6bfe2f73cd4)
06-14 15:34:38.078 22685 22685 F DEBUG   :       #05 pc 0000000000670ee8  /data/app/~~znebrAhbl6TubRMjz6cfXw==/org.ppsspp.ppsspp-XItxXP74k3UfNSnJ0MJQEw==/lib/arm64/libppsspp_jni.so (OpenSLContext::Init()+812) (BuildId: 8ecc372268c096479c6d71fb67f3f6bfe2f73cd4)
```

This is a pretty commonly seen bug in crash reports, would be nice if we could figure out why it happens. You have a repro, even if it's on a hacked rom.

So I'm gonna try to make some fixes and ask you to try a new build soon.

**Comment by TheCruzJ4v5** [comment] 2021-06-14 13:13
Thanks a lot.❤️
Btw I have the audio bug from ages .
Not even notification sounds come from my phone.
I cant even call and talk to someone😔

**Comment by hrydgard** [comment] 2021-06-14 13:34
Well, in that case it sounds like you should maybe try to go back to original firmware...

But I'm gonna try to make it work without sound then.

repro means that you can easily reproduce (recreate) the error so that we can investigate.

**Comment by TheCruzJ4v5** [comment] 2021-06-14 16:53
Actually I switched to a custom ROM because the stock firmware was very buggy.
Actually after that Android webview crash a few months ago(it happened to many people around the globe)

**Comment by TheCruzJ4v5** [comment] 2021-06-14 16:54
Actually I switched to a custom ROM because the stock firmware was very buggy.
Actually after that Android webview crash a few months ago(it happened to many people around the globe) my phone won't even work for 1 min properly without crashing.

**Comment by ANR2ME** [comment] 2021-06-15 02:02
You might have a buggy audio driver on your phone, you should try updating your phone to the latest official firmware before changing to custom ROM so all the drivers gets updated.
Custom ROMs usually didn't come with their own drivers but use drivers that came from official firmware (Android Treble)

**Comment by TheCruzJ4v5** [comment] 2021-06-15 02:55
@ANR2ME 
Actually I did that, and even the OEM has stopped updates for this phone.
Can you tell another way to update our restart the audio drivers?

**Comment by ANR2ME** [comment] 2021-06-15 06:46
> 
> 
> @ANR2ME
> Actually I did that, and even the OEM has stopped updates for this phone.
> Can you tell another way to update or restart the audio drivers?

If reflashing the official firmware using PC still have audio issue, it could also be hardware issue. 
If it's hardware issue you should consult this with xiaomi's service center.

**Comment by TheCruzJ4v5** [comment] 2021-06-15 13:09
Actually it got fixed by a simple reboot once (even ppsspp worked fine, but after some days while rebooting this problem comes back.

**Comment by ANR2ME** [comment] 2021-06-15 16:17
Are you using Sound Enhancer (Dolby, Viper, etc) on your custom ROM?
Those things could cause issue if they're not compatible with the audio driver that came from official firmware.

**Comment by TheCruzJ4v5** [comment] 2021-06-15 16:20
No
I have root access can I do something with build.prop thing?

**Comment by hrydgard** [comment] 2021-06-15 21:46
One thing you can do: I just merged a new change "Remove asserts from OpenSL init".

Once that build is up on https://buildbot.orphis.net/ppsspp/ (probably an hour or so from when I post this), can you try it on your device? Best case, it manages to start, and in that case you can go to Settings/Audio and see an error message as the last item. Could your report that here, if possible?

**Comment by TheCruzJ4v5** [comment] 2021-06-16 02:25
Omg😱😱
It worked.
In settings it shows no context

**Comment by hrydgard** [comment] 2021-06-16 05:40
Cool, thanks for reporting!

If you don't mind, I made another build that should improve the error reporting a little: "Store the OpenSL error...". 

Can you try that too when it's up?

**Comment by TheCruzJ4v5** [comment] 2021-06-16 05:55
I will..
I'm a fan I must say🤩🤩

**Comment by TheCruzJ4v5** [comment] 2021-06-16 06:54
Yes I tried it and it too works without any problems❤️

**Comment by hrydgard** [comment] 2021-06-16 07:03
Is there a different error message now?

**Comment by TheCruzJ4v5** [comment] 2021-06-16 08:33
It shows player ->realize

**Comment by hrydgard** [comment] 2021-06-16 08:40
Great, thanks! Good to know where it fails.

I'm gonna close this now, since it works for you. Let me know if you see any other issues that seem related.

**Closed by hrydgard** 2021-06-16 08:40 UTC
Labels: Audio

**Comment by TheCruzJ4v5** [comment] 2021-06-16 09:43
Thanks a lot, I'll let you know if I have any other problems.
Thanks again. ❤️

**Comment by hrydgard** [comment] 2021-06-16 09:46
Thank you for helping by testing and providing logs!
