### ISSUE TITLE
IR Interpreter mode

### ISSUE THREAD

**Issue by zero2029** [hrydgard/ppsspp#8869] opened 2016-07-24 21:37 UTC
Latest version of iOS ppsspp 1.2.2-771-gd0b8e83 still crashes when loading games on IR Interpreter. 😞 Is there a way we can download a build from a ppsspp version when it didn't crash?

**Comment by hrydgard** [comment] 2016-07-24 22:01
Duplicate of #8848, closing. I hear you.

**Closed by hrydgard** 2016-07-24 22:01 UTC

**Comment by zero2029** [comment] 2016-07-24 23:45
Indeed. Thank you for working on it. 🙂
