### ISSUE TITLE
Gundam Age Cosmic Drive/Universe Accel Issues in Latest Version

### ISSUE THREAD

**Issue by dimasanom9708** [hrydgard/ppsspp#11561] opened 2018-11-15 02:55 UTC
Maybe this is an old issue, same as # 2509, # 6243 but my character is not visible at all, I have followed the instructions, even tried in the old version of v0.8.1, v0.9.8, and the others.

![screenshot_2018-11-13-10-12-39](https://user-images.githubusercontent.com/34290214/48526987-1fcfae00-e8bc-11e8-8be6-afadcb5bfbd8.png)

I play this game using the latest version (v1.7.1). but in the previous version, the results were the same

![screenshot_2018-11-13-10-14-22](https://user-images.githubusercontent.com/34290214/48527031-51487980-e8bc-11e8-9b3f-203b567c4870.png)
![screenshot_2018-11-13-10-14-17](https://user-images.githubusercontent.com/34290214/48527032-51e11000-e8bc-11e8-8898-fac6c608d324.png)
![screenshot_2018-11-13-10-14-10](https://user-images.githubusercontent.com/34290214/48527033-5279a680-e8bc-11e8-9ad6-4f1c5c8d601f.png)
![screenshot_2018-11-13-10-14-04](https://user-images.githubusercontent.com/34290214/48527034-53123d00-e8bc-11e8-8e41-e9778f18163b.png)
![screenshot_2018-11-13-10-13-13](https://user-images.githubusercontent.com/34290214/48527036-53123d00-e8bc-11e8-9a96-fdddd74c05f4.png)
![screenshot_2018-11-13-10-13-04](https://user-images.githubusercontent.com/34290214/48527037-53123d00-e8bc-11e8-8727-a1f73ae071cc.png)
![screenshot_2018-11-13-10-12-57](https://user-images.githubusercontent.com/34290214/48527038-53aad380-e8bc-11e8-810a-e6bbb61f5f96.png)

What should I do?

**Comment by LunaMoo** [comment] 2018-11-15 04:08
To answer your question what to do - buy a new hardware. This game(and few others) requires GLES 3.3 or higher to display correct graphics. It will not work on older devices like yours which is limited to GLES 2.0.

 Closing as a duplicate of #6243

**Closed by LunaMoo** 2018-11-15 04:08 UTC
