### ISSUE TITLE
Split screen issue on android

### ISSUE THREAD

**Issue by Nabokov86** [hrydgard/ppsspp#17099] opened 2023-03-12 17:01 UTC
The screen size and position do not change if you switch to split screen mode on android.

This issue started somewhere between v1.13.2-1986-gce5a1b8b7 and v1.13.2-1998-g5c2663e37.

This change looks suspicious: "Only check for display resized in emuscreen-under-pause-screen, not the other changes".
![split-git](https://user-images.githubusercontent.com/26260168/224559985-1fef3b11-5a8d-4fc8-8d48-170ee4a504ab.jpg)

### Last working version

v1.13.2-1986-g0f33a7838

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2023-03-12 17:08
This issue is being closed as a duplicate of #10848.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2023-03-12 17:08 UTC

**Comment by Nabokov86** [comment] 2023-03-12 17:26
@unknownbrackets I'm sorry, but I don't think this is a duplicate, could you review this again? I mean, resizing and centering the screen worked before correctly. I have used the split screen a lot before and the v1.13.2-1986 works absolutely fine.

**Comment by hrydgard** [comment] 2023-03-12 17:41
You're right, not quite a duplicate, but we could collect Android split screen issues over there in that issue instead. I'll add a comment to it.
