### ISSUE TITLE
Cars - Race-O-Rama (USA) graphics problem

### ISSUE THREAD

**Issue by scraggles80** [hrydgard/ppsspp#4112] opened 2013-10-11 08:43 UTC
no matter what rendering mode i change it to nothing fixes it
![capture](https://f.cloud.github.com/assets/4402150/1313159/3a1581ee-3251-11e3-882d-bba5c0df8680.PNG)

**Comment by ppmeis** [comment] 2015-07-25 21:46
Tested with latest build. Even worse than before:
![image](https://cloud.githubusercontent.com/assets/4381277/8891379/4bf67ab6-3327-11e5-9074-ca7667f1affe.png)

**Comment by unknownbrackets** [comment] 2015-07-25 23:19
Interesting.  It might help to find where it got worse.

-[Unknown]

**Comment by daniel229** [comment] 2015-07-31 11:00
That affected by https://github.com/hrydgard/ppsspp/pull/7509

**Comment by unknownbrackets** [comment] 2015-08-02 17:24
Interesting.  What does the source texture and settings look like when it draws the white?

Maybe it is now an alpha/stencil/blending issue.

-[Unknown]

**Comment by daniel229** [comment] 2015-08-02 23:27
These are when it drew the white.
![01](https://cloud.githubusercontent.com/assets/3481559/9028580/02980fde-39b1-11e5-971c-66c1aa656d82.png)
![02](https://cloud.githubusercontent.com/assets/3481559/9028582/029af32a-39b1-11e5-8541-96d39a35520e.png)
![03](https://cloud.githubusercontent.com/assets/3481559/9028584/029b3696-39b1-11e5-8e68-8c9d9a6c8ba4.png)
![04](https://cloud.githubusercontent.com/assets/3481559/9028581/029a5370-39b1-11e5-966b-c7546cb9f6f6.png)
![05](https://cloud.githubusercontent.com/assets/3481559/9028585/029dacbe-39b1-11e5-96c1-6f6e71d9c23a.png)
![06](https://cloud.githubusercontent.com/assets/3481559/9028583/029afeb0-39b1-11e5-9945-09517b723b57.png)

**Comment by benderscruffy** [comment] 2016-10-14 01:42
using v1.3-98-g492bda6 	
problem still there

**Comment by benderscruffy** [comment] 2018-11-26 02:12
this can be closed as duplicate of #9850

**Comment by unknownbrackets** [comment] 2018-11-26 02:33
Thanks.  I think the other bugs fixed got us to the point where it's just the depth texturing left, and #9850 indeed represents that issue more clearly.

-[Unknown]

**Closed by unknownbrackets** 2018-11-26 02:33 UTC
