### ISSUE TITLE
Add MoltenVK support for iOS

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13106] opened 2020-07-08 16:21 UTC
MoltenVK is vulkan on iOS,it will give a big speed boost

**Comment by Panderner** [comment] 2020-07-08 17:13
Duplicate of #10654. MoltenVK on Mac is already supported in 1.10.0

**Comment by boy13epic** [comment] 2020-07-08 17:24
iOS jailbroken

**Comment by boy13epic** [comment] 2020-07-08 17:25
its also on the new emulator DolphiniOS

**Closed** 2020-07-08 17:57 UTC
