### ISSUE TITLE
Problems with PPSSPP since build 1.8.0-316

### ISSUE THREAD

**Issue by Deivmsr** [hrydgard/ppsspp#12202] opened 2019-07-28 21:10 UTC
### What happens?
Since build v1.8.0-316-g068ec3059 PPSSPP has distorted the menu as you scroll down the emulator page using the Vulkan API only. Until build v1.8.0-303-g12ab276a7 this problem did not happen. This issue occurs even in the latest buildbot builds.

### What *should* happen?
I believe the ideal would be for the emulator not to present this distortion when using the Vulkan API.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I use Galaxy Note 8 with Exynos processor, Mali G71 GPU and Android 9.0.

**Comment by hrydgard** [comment] 2019-07-28 21:31
Yeah, I know what you mean, been meaning to investigate it for a while. Haven't quite understood what's going on here, maybe some kind of barrier issue. I think not using pretransform forced an extra copy of the display in the driver that hid the problem, and properly supporting pretransform (for speed) exposed the issue again.

**Comment by Deivmsr** [comment] 2019-07-28 21:41
When sliding my finger over the screen to drag the settings menu the image is distorting, a graphic error occurs at the moment.

**Comment by hrydgard** [comment] 2019-07-28 21:47
I'm saying that I know exactly what you mean, and it happens on my Galaxy S8+ too. I'm going to investigate soon.

**Comment by Deivmsr** [comment] 2019-07-28 21:48
Ok. Thanks. I am Brazilian and the translator has not helped much to translate from Portuguese to English.

**Comment by hrydgard** [comment] 2019-08-01 12:59
This is now fixed, thanks for reminding me! The problem was actually older than #12116 (.316) but it was hidden before - #12116 exposed it by increasing the speed of presenting images.

**Comment by hrydgard** [comment] 2019-08-01 15:13
Actually, the problem is still not completely fixed. That commit appears to have helped a bit, but I still see some tearing...

**Closed** 2019-08-01 15:47 UTC
