### ISSUE TITLE
gettimeofday sometimes "skips" time.

### ISSUE THREAD

**Issue by Fighter19** [hrydgard/ppsspp#8748] opened 2016-05-16 20:20 UTC
Creating a homebrew with SDL2.
Running it on the real PSP, it ticks correctly (I'm using SDL_GetTicks() to determine the delta time in milliseconds).
However when running it on the emulator it often skips the time (deltaTime should be 16(.6) for most of the time, but it seems it becomes bigger for no reason, meaning even though the frames stay at 60fps deltaTime becomes bigger than 1000/60).
As SDL2 uses gettimeofday and the pspsdk wraps gettimeofday to sceKernelLibcGettimeofday, I think there might be a bug in the way ppsspp handles this function.

**Comment by unknownbrackets** [comment] 2016-05-16 20:49
What's the period?  What skips exactly are you seeing?

If the device you're running on has a different framerate, it's possible there could be uneven parts, because we start each frame at a host frame, typically.  Does the behavior change if you enable auto frameskip?

Also, be aware that the PSP is not 1000 / 60, it's 1001 / 60 (NTSC 59.94.)

sceKernelLibcGettimeofday is calculated just based on ticks.  It's also possible for it to become uneven if you're changing the cpu frequency via scePower.  This could be a little more immediate than on a real PSP right now.

-[Unknown]

**Comment by Fighter19** [comment] 2016-05-17 00:46
I'm creating a rythm game (I'll plan to release the source, unfortunately
the assets could create some trouble right now, which is why I can't bundle
a complete version)
My code works by adding the time difference towards an object which then
moves circles which afterwards are going to be rendered (whenever the
render function of the object is called all circles on screen are
rendered). But when running my game on PPSSPP the game runs normally for
like 1 second then skips ahead. I can upload a footage and a tarball of the
source code if you want (The code is currently kinda dirty , in a state I
wouldn't like it to be on github).

I have logged a_DeltaTime, every time the object is ticked.
```
44:49:005 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 16
44:49:022 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 934
44:49:039 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 17
44:49:055 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 17
44:49:072 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 17
44:49:089 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 16
44:49:105 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 16
44:49:122 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 16
44:49:139 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 16
44:49:155 user_main    I[IO]: HLE/sceIo.cpp:940 stdout: Tick 16
```
As you can see it says 934 is the delta time, between 22 and 05, which for
me results in 17 not 934.

2016-05-16 22:50 GMT+02:00 Unknown W. Brackets <notifications@github.com>:

**Comment by Fighter19** [comment] 2016-05-17 01:15
Result: https://www.youtube.com/watch?v=mV3Q1venidQ
Expected (nearly the same on PSP, although this is an earlier PC version):
https://www.youtube.com/watch?v=cbmzUrZMsyU

2016-05-17 2:46 GMT+02:00 Pat Za <littlefighter1996@googlemail.com>:

**Comment by unknownbrackets** [comment] 2016-05-17 01:23
Well, the times on the left are real times, the times on the right are emulated times.  We don't expose the real system time to the program, except that we start the emulated time at the system time when you start emulation.

I didn't actually know SDL2 supported the PSP as a target.  But I will note:

 * sceKernelGetSystemTimeWide() will give you microsecond accuracy and is what many games use.  It's also fast.
 * sceKernelLibcGettimeofday() on the PSP is for some reason very slow and costs about 1ms of CPU time to call.  It's not commonly used by games, though I don't see why it wouldn't work correctly.

Anyway, I'm not sure what your code is doing, but 934 is almost a second.  Are you using multiple threads?  Are you just spinning in some other thread, perhaps?

Are you able to reproduce this with a simple loop just calling `sceKernelLibcGettimeofday()`?  I want to make sure this really is a bug in `sceKernelLibcGettimeofday()`, because it may not be.

-[Unknown]

**Comment by Fighter19** [comment] 2016-05-17 01:25
I'll try that.

2016-05-17 3:24 GMT+02:00 Unknown W. Brackets <notifications@github.com>:

**Comment by Fighter19** [comment] 2016-05-17 01:49
Okay, manually implemented GetTick by using sceKernelLibcGettimeofday and
to my surprise, it works (it's running smoothly).
Probably newlib implemented gettimeofday as well, which is what SDL2 uses.
However I still wonder, why it works on the real psp but not on the
emulator.

2016-05-17 3:25 GMT+02:00 Pat Za <littlefighter1996@googlemail.com>:

**Comment by Fighter19** [comment] 2016-05-17 02:02
Oh and regarding multiple threads.
Yes SDL creates multiple threads (I think there is a bug where a wrong
priority is being set).

```
00:54:333 SDL thread   E[KERNEL]: HLE/sceKernelThread.cpp:2328
80020193=sceKernelChangeThreadPriority(285, -20): bogus priority
```

However I don't really know if one is being created for the timer.
It creates at least one new thread for the music (Which is likely to be
replaced by the function the psp offers, instead of doing the decoding with
cpu intensive libraries).

2016-05-17 3:49 GMT+02:00 Pat Za <littlefighter1996@googlemail.com>:

**Comment by Fighter19** [comment] 2016-05-17 02:30
```
int SDL_SYS_SetThreadPriority(SDL_ThreadPriority priority)
{
    int value;

    if (priority == SDL_THREAD_PRIORITY_LOW) {
        value = 19;
    } else if (priority == SDL_THREAD_PRIORITY_HIGH) {
        value = -20;
    } else {
        value = 0;
    }

    return sceKernelChangeThreadPriority(sceKernelGetThreadId(),value);

}
```

Either -20 is a bogus priority or PPSSPP just doesn't know what to do with
it (I think it might belong here, if the priority should be higher for a
timer thread, but rendering or music gets the higher priority, the other
counter might not work properly).

2016-05-17 4:02 GMT+02:00 Pat Za <littlefighter1996@googlemail.com>:

**Comment by unknownbrackets** [comment] 2016-05-17 04:04
The valid thread priority range goes from 0x08 to 0x77.  0 is also accepted to indicate the current thread's priority.  We have tests for this in pspautotests.

Using -20 will result in a response code of 0x80020193, or SCE_KERNEL_ERROR_ILLEGAL_PRIORITY.  I just verified the -20 value on hardware now, in case somehow that value was special.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-05-17 05:46
Also, you can try using PPSSPP's disassembler and "Step HLE" to see what function is actually being called by newlib's gettimeofday().  It might be an sceRtc func.

-[Unknown]

**Comment by hrydgard** [comment] 2016-05-17 07:52
According to the first message in this thread it's indeed sceKernelLibcGettimeofday.

**Comment by unknownbrackets** [comment] 2016-05-17 08:03
But apparently calling sceKernelLibcGettimeofday directly made it work fine.  So something else is happening that is not sceKernelLibcGettimeofday.

-[Unknown]

**Comment by Fighter19** [comment] 2016-05-17 10:50
I thought it might be some kind of software clock used by newlib.
(The raspberry is also able to keep track of the time without an RTC).

**Comment by unknownbrackets** [comment] 2016-05-17 14:15
Hmm, if sceKernelLibcGettimeofday is supposed to only be since midnight, we don't do that.

Could be somehow it's often getting in a scenario where microseconds wrapped around.  Might be possible on a PSP too, but PPSSPP's timing is a bit more regular.

-[Unknown]

**Comment by unknownbrackets** [comment] 2017-05-24 02:49
Does this still cause problems with #9716?

`time()` and `gettimeofday()` didn't change the second value at the same time (they both progressed in constant time, they just didn't roll over simultaneously.)  It seems this confused other SDL2 games.

It's probably what caused this issue.

-[Unknown]

**Comment by LunaMoo** [comment] 2019-06-14 20:18
Closing since it had no feedback for a long time also it was likely fixed as noted above.

**Closed by LunaMoo** 2019-06-14 20:18 UTC
Labels: No Feedback / Outdated?
