### ISSUE TITLE
Leg Shaking in Tekken 6/5

### ISSUE THREAD

**Issue by tabnk** [hrydgard/ppsspp#7582] opened 2015-03-11 04:18 UTC
Latest version of PPSSPP v1.0.1-159-gdad8f5c. All default setting except Internal Resolution.

https://vid.me/xbFR 
See attached video.

**Comment by DonelBueno** [comment] 2015-03-11 05:02
Try turning off "Vertex Cache" and/or "Hardware Transform" and see if it helps.

**Comment by tabnk** [comment] 2015-03-11 05:11
Tried but still same shaking issue.

**Comment by thedax** [comment] 2015-03-11 17:35
Closing as dupe of https://github.com/hrydgard/ppsspp/issues/5399.

**Closed by thedax** 2015-03-11 17:35 UTC
