### ISSUE TITLE
Corrupt full motion videos

### ISSUE THREAD

**Issue by 71knight** [hrydgard/ppsspp#16528] opened 2022-12-08 19:27 UTC
### Game or games this happens in

Burnout dominator and need for speed shift

### What area of the game / PPSSPP

When full motion videos play in these games, video corruption squares can be seen in video.  Maybe related to incompatible FFmpeg libraries corrupting data.

### What should happen

Video should play without any breakup.

### Platform

Android 11

### Mobile phone model or graphics card

OnePlus 7t with adreno 640

### PPSSPP version affected

Most recent build

### Last working version

Dunno

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2022-12-09 05:43
Similar to this issue? https://github.com/hrydgard/ppsspp/issues/14645

**Comment by Gamemulatorer** [comment] 2022-12-11 01:57
This is definitely a dup of #14645

**Comment by unknownbrackets** [comment] 2022-12-19 04:18
This issue is being closed as a duplicate of #14645.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-12-19 04:18 UTC
