### ISSUE TITLE
[Android] Recent freezing issue in Project Diva games

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#13494] opened 2020-09-30 20:32 UTC
The game freezes randomly. Sometimes at startup loading screen, sometimes when playing songs. No crash or anything. It just freezes forever.
Tested: v1.10.3-803 and v1.10.3-785 and both had this issue
The last one I tested that worked without issues (not necessarily when it started): v1.10.3-634

Also, it is not backend specific.

**Comment by ANR2ME** [comment] 2020-10-01 00:27
Frozen forever could also be caused by a crash in PSP game if you disable Fast Memory settings.

**Comment by leopard20** [comment] 2020-10-01 01:37
It's new. So whatever it is a certain change has broken it.

**Comment by hrydgard** [comment] 2020-10-01 06:49
Weird, okay. Could you try some older versions to try to figure out about when this started happening?

**Comment by leopard20** [comment] 2020-10-01 07:59
@hrydgard It appears to start from v1.10.3-769. Previous builds work fine.
Also, this one is even worse that the more recent ones. It almost always froze at startup.

**Comment by hrydgard** [comment] 2020-10-01 08:55
thanks, that's useful info. will take a look at this later this week

**Comment by hrydgard** [comment] 2020-10-10 16:07
Got an email report that this was causing hangs, it's in the range (769):

https://github.com/hrydgard/ppsspp/pull/13477

Could be the same problem. Having problems reproducing it here.

**Comment by leopard20** [comment] 2020-10-10 22:44
It's strange. I tried the latest build and I couldn't reproduce the issue anymore.

Have you made any other changes to the time code again? Maybe you "accidentally" fixed it!

I can't tell for sure because it was a very brief test (<5 min). I will report back when I test it more properly.

**Comment by hrydgard** [comment] 2020-10-12 21:25
aliaspider helped me find a couple of bugs in #13477, fixed on master now, so please try again once the build is up.

**Comment by leopard20** [comment] 2020-10-13 21:34
The game is working fine after two play throughs. So I guess it's safe to say is it fixed. (although I'm think it was fixed before)

**Closed** 2020-10-13 21:35 UTC
Labels: HLE/Kernel
