### ISSUE TITLE
Silent Hill:SM

### ISSUE THREAD

**Issue by narayan2016** [hrydgard/ppsspp#11893] opened 2019-03-15 16:09 UTC
Silent Hill:shattered memoriesWorks well without slow effects.
![Screenshot_2019-03-14-14-42-05](https://user-images.githubusercontent.com/48562416/54444725-2f291000-4765-11e9-896b-5173d2094df5.png)
 However, without slow effects, the flashlight does not work in the game.
![Screenshot_2019-03-14-14-42-12](https://user-images.githubusercontent.com/48562416/54444848-63043580-4765-11e9-8304-339309a9f8e1.png)

Here is a flashlight with slow effects on. 
![Screenshot_2019-03-14-14-49-17](https://user-images.githubusercontent.com/48562416/54445034-c9895380-4765-11e9-9e11-4762cc84dc14.png) Device Parameters 
![Screenshot_2019-03-14-21-51-42](https://user-images.githubusercontent.com/48562416/54445189-15d49380-4766-11e9-872d-6a0428cce99b.png)
![Screenshot_2019-03-14-21-51-57](https://user-images.githubusercontent.com/48562416/54445234-297ffa00-4766-11e9-9de8-8dbb12e6e56f.png)
![Screenshot_2019-03-14-21-52-07](https://user-images.githubusercontent.com/48562416/54445267-3ac90680-4766-11e9-94c8-48aaa1ad7480.png)
 PPSSPP 1.7.5 GP

**Comment by Emulatorer** [comment] 2019-03-16 13:57
Similar #6265?

**Comment by unknownbrackets** [comment] 2019-03-16 14:32
If turning off slow effects had no negative impact, we would force it off for everyone and remove the setting.  The setting only exists because it's impossible to just skip graphics the game asks to be drawn without often causing worse graphics.

Otherwise, this seems to be a duplicate of #6265 indeed.  Closing.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-03-16 14:32 UTC
