### ISSUE TITLE
Graphic issue in video scenes

### ISSUE THREAD

**Issue by Kupo91** [hrydgard/ppsspp#11467] opened 2018-10-11 12:40 UTC
Hi, 

I have tested two different core versions of ppsspp and noticed two issues. The first core is included in Lakka 2.1.1. Unfortunatelly I can't see any version but change date from this core is 23 june 2018.
The second core is a very old one from 12 may 2017. This core was included in a build from MXQ Project for S905X devices.

So here are the issues:

### What happens?

1) Graphic issue:

In core version 1 (Lakka 2.1.1) all video scenes look like this:
![need for speed - most wanted 5-1-0 d ules-00186 -181011-135728](https://user-images.githubusercontent.com/41426906/46803518-8a8f4600-cd60-11e8-81fa-a5eefed4119c.png)

Meanwhile it looks in the old core version from 2017 correctly:
![need for speed - most wanted 5-1-0 d ules-00186 -181011-140301](https://user-images.githubusercontent.com/41426906/46803559-a85cab00-cd60-11e8-9f58-4bb6fd4e3785.png)

2) Font issue:

So first thought was 'Ok then I use the old core until graphics in a newer version get fixed' but then I experienced that.

While in core version 1 everything looks fine:
![need for speed - most wanted 5-1-0 d ules-00186 -181011-135703](https://user-images.githubusercontent.com/41426906/46803751-1e611200-cd61-11e8-8e95-b8aee1205c5b.png)

I get this in the older version:
![need for speed - most wanted 5-1-0 d ules-00186 -181011-140243](https://user-images.githubusercontent.com/41426906/46803812-42bcee80-cd61-11e8-9c19-09306dae0771.png)

So I have the choice between bad video scenes and bad/not understandable font characters.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I got a S905X device with arm chip. I tested both cores on two different platforms: latest Lakka 2.1.1 (should be Retroarch 1.7.3) and this old build from MXQ Project. Unfortunatelly there is no Retroarch version displayed but the build date in system information is 11 May 2017.
However it doesn't seem to be about the Retroarch version since I experienced the same issues of both cores on both platforms.

**Edit:** No, on Lakka 2.1.1 I only tested the core version that Lakka included not the old core because I couldn't manage to load other cores than the ones which are preinstalled.

**Comment by unknownbrackets** [comment] 2018-10-11 14:18
At least the second issue means that something is wrong with the way Lakka is packaging assets.  I don't know what's going on with the first one, but it could also be an issue in Lakka.

If you use PPSSPP itself, without using Retroarch, does the gmae work fine?

-[Unknown]

**Comment by Kupo91** [comment] 2018-10-11 16:59
I don't think that Lakka is the reason for this because:
While core 2 has this font issue core 1 has not. And I tested both with the same setup. Same with the graphic issue.
Actually I'm running LibreElec 8.2 and Retroarch is integrated in my Kodi addons. However this build is old and to test a newer version of Retroarch I flashed Lakka 2.1.1 to USB. However I can't change there anything but have to use the cores which are included.
However I know that the Sx05RE build has installed the ppsspp standalone emu. I will try it and tell you in 1-2 hours.

**Comment by Kupo91** [comment] 2018-10-11 18:57
Okay wasn't that easy as expected. What I was able to find out:
With standalone ppsspp I have neither the graphic issue nor the font issue. However I didn't come further than the main menu in the game because the buttons of my controller don't work. So I tried to test another game. In this game the video scenes at the beginning were correct aswell. However after the loading screen I got a black screen. Audio worked but I couldn't see anything. Maybe it's just a setting thing but I didn't find anything to configure. Neither graphic settings nor keyboard settings. With the Retroarch cores I also had the issue that half of my games were super choppy. Or just really slow I don't know. I wish I could have tested how they run with that standalone emu but can't do anything without controller buttons.

**Comment by Kupo91** [comment] 2018-10-12 01:03
I don't have a menu. I directly start the game out of Emulationstation. I don't see anything of the emu itself. I also don't know how to manage a standalone emu in libreelec. I just knew that the Sx05RE build has included the ppsspp standalone so I gave it a try and it worked.

The game I'm talking about is GTA Liberty City Stories. I chose it for a reason.
I told you that video scenes in the newer core are broken while they get displayed correctly in the old one. And for most of the games its true. Only GTA Liberty City Stories and GTA Vice City Stories showed a black screen when it came to the video scenes. However Audio was okay and when video scene was over the screen came back aswell.
So when I tested the standalone emu and the video scenes in game 1 were displayed correctly I was curious what GTA looks like. And it even showed the video scenes which the other core didn't displayed. However while in the Retroarch core the video scenes were all black but the actual game after looked normal the situation with the standalone emu is the other way round. Video scene normal but actual game black.

Its kinda funny there is always something good and bad in eachs core. A combination of all the good stuff in a single core would be nice xD

**Comment by Kupo91** [comment] 2018-10-12 12:18
Emulationstation is just a frontend I don't know if it's possible to start the emu without it in LibreElec.
However I will ask the author of Sx05RE what version of ffmpeg he has used. Although I don't know if he will reply because there are several questions in his thread that he didn't answer to

**Comment by Kupo91** [comment] 2018-10-12 17:16
I still try to configure my controller. I found these two files in my PSP system folder in LibreElec
controls.ini https://paste.ubuntu.com/p/GywxmdhDRj/
ppsspp.ini https://paste.ubuntu.com/p/pmkcSNWYPt/
Can you tell me what the numbers in file 1 mean? How can I find out what to enter there?
I also have ppsspp installed for pc (Windows). If I configure my controller there can I apply this settings for my ppsspp emulator in LibreElec?

**Comment by Kupo91** [comment] 2018-10-13 00:48
Okay after I have found exactly the same files in the memorystick folder of my ppsspp emulator in windows I configured my controller there and then just copied the controls.ini file to my tv box. However this standalone ppsspp I have installed on my tv box seems to hate my controller. While everything on ppsspp (Windows) worked fine I still was not able to use my direction buttons of my controller on ppsspp (TV Box). Even when it had exactly the same controls.ini. So my next try was to use a keyboard on my TV Box. With my keyboard I was able to open the emulator menu and bind my keys of the controller on the TV Box. However it showed no reaction when I pressed the direction buttons. So I gave up.
I also tested GTA with other graphic settings and I figured out that the black screen was caused by the non-buffered mode. If I change it to buffered rendering I don't have a black screen. Although it's really choppy. I only had 10-20 FPS. Unfortunatelly I experienced this with half of my games.
However the ppsspp standalone on my tv box is v1.5.4-6-g9a732fe. Don't know how old it is.

**Comment by unknownbrackets** [comment] 2020-03-08 20:30
#11490 exists for the FFmpeg issue already (using newer FFmpeg versions with PPSSPP isn't really supported.)

The assets file has recently been changed in PPSSPP to no longer require the PPSSPP version and the assets file to be so tightly in sync.  Once the kit you're using switches to the newer files, it should be simpler.

I'm going to close this since the original issues seem to be resolved or covered by other issues already.

Note: controls.ini is going to be necessarily OS-specific.  It's probably not portable between Windows and Linux/etc.  I can't tell if that's the cause of your problems, or if it's related to #10996, but that has also recently been fixed.

-[Unknown]

**Closed by unknownbrackets** 2020-03-08 20:30 UTC
Labels: Libretro
