### ISSUE TITLE
MGS: Peace Walker: Character model glitch with IR interpreter

### ISSUE THREAD

**Issue by awwang** [hrydgard/ppsspp#10650] opened 2018-02-26 06:19 UTC
In Metal Gear Solid: Peace Walker, character models do not show up properly, and and appear to be "stretched" off screen.

[Screenshot](https://i.imgur.com/ogRuMHP.jpg)

Everything else renders/runs fine as far as I can tell, except character models as mentioned.

I am running PPSSPP on iOS 11.1.2 (iPhone 8) and installed through Impactor. Using the IR Interpreter.

**Comment by soopsfiya** [comment] 2018-06-24 20:47
@hrydgard sorry for mentioning you, just incase this issue slipped by you, it has been affecting me as well

**Comment by unknownbrackets** [comment] 2018-08-12 17:40
Does this happen on desktop too (when using IR Interpreter)?

It'd help if someone has the game and wants to try debugging the IR:
https://github.com/hrydgard/ppsspp/wiki/How-to-debug-the-JIT

-[Unknown]

**Comment by hrydgard** [comment] 2018-10-06 11:51
Not a regression, while unfortunate I'm bumping this to 1.8.0.

**Comment by unknownbrackets** [comment] 2019-08-25 16:48
At least on Windows in the demo (using the workaround in #3365), this seems to be working correctly.

Is this still an issue in the latest git build?  Unfortunately, iOS is generally problematic as far as builds and the latest OS, so it may be necessary to use Xcode to compile to test.  Make sure the version says "v1.8.0-565-gd8db8ecfc" or higher.

-[Unknown]

**Comment by Chaseroni** [comment] 2019-10-20 06:36
Running PPSSPP 1.9.3 on iOS still exhibits this behavior with IR interpreter. Its a shame because the game runs beautifully otherwise. The character models remain glitched.

**Comment by FlutterOfficialGithub** [comment] 2021-09-12 00:08
Just Switch To Interpreter It works for me

**Comment by Gamemulatorer** [comment] 2021-09-15 08:33
> Just Switch To Interpreter It works for me

Too much slow on Interpreter.
![Screenshot_2021-09-15-16-30-36-849_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133399093-b65d977d-edb1-461c-9a0c-95fbaccfacc1.jpg)
IR Interpreter is close to dynaric performance.
![Screenshot_2021-09-15-16-30-49-541_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133399192-d5318153-2198-4197-b837-5d5818a29951.jpg)
[MGSPW_IR_INTERPRETER.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7168279/MGSPW_IR_INTERPRETER.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2021-10-01 16:07
Maybe related to https://github.com/hrydgard/ppsspp/issues/12991

**Comment by Gamemulatorer** [comment] 2022-07-12 05:22
Disabled JIT Functionality VFPU_VEC can fix this issue using the latest build 🎉

**Comment by ANR2ME** [comment] 2022-07-22 04:46
This issue seems to be exist only on mobile platform (ARM/ARM64 only?) since i can't reproduce it on Windows but can reproduce it on Android.

Does IR have a separated codes for ARM and x86 just like JIT?

**Comment by hrydgard** [comment] 2022-09-09 19:17
Yeah this is some kind of bug in the IR interpreter / compiler, probably repros on all platforms with that.

**Comment by unknownbrackets** [comment] 2022-09-10 03:46
I think I couldn't reproduce this in the demo, at least, on Windows.  I don't think I tried Android or WSL2.  Not sure why it'd be different, though...

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-10-30 05:54
VRot is VFPU_VEC, I suspect that's the most likely culprit here.  ARM and x86 don't do IR differently (currently, eventually it'd be nice to have a jti backend from IR), but sin() and cos() are used, which might differ between those platforms.

Some things to try:
1. DISABLE only `IRFrontend::Comp_VRot()` and see if that makes this work.
2. Check for an overlap hazard, i.e. if anything in #16302 helps.

-[Unknown]

**Comment by ANR2ME** [comment] 2022-11-18 10:54
I've tried inserting `DISABLE;` on the first line of `IRFrontend::Comp_VRot()` function, but it didn't fix this issue.
![image](https://user-images.githubusercontent.com/7974720/202689058-7e49f53a-3540-4c68-a964-1f923633b7c4.png)

**Comment by ANR2ME** [comment] 2022-11-18 18:35
To be more precise, disabling `case 2:  // vneg` inside `IRFrontend::Comp_VV2Op()` function will also fixes this issue.
![image](https://user-images.githubusercontent.com/7974720/202777936-7cbe45f2-b92f-48bc-9864-fa931d48449f.png)

**Comment by unknownbrackets** [comment] 2022-11-18 22:40
Okay, that's very interesting and pretty specific.  I'll dig into vneg soon and see what could be wrong.

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-11-19 02:01
Had a little to check and cleaned up something that MIGHT cause an issue there and COULD explain a difference between Windows and Linux.  Do these changes help at all?

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:ppsspp:ir-vneg

-[Unknown]

**Comment by ANR2ME** [comment] 2022-11-19 02:50
> Had a little to check and cleaned up something that MIGHT cause an issue there and COULD explain a difference between Windows and Linux. Do these changes help at all?
> 
> [master...unknownbrackets:ppsspp:ir-vneg](https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:ppsspp:ir-vneg)
> 
> -[Unknown]

Yes, this fixes the issue on Ubuntu(WSL2), not sure about Android as there is no android artifact yet

**Comment by unknownbrackets** [comment] 2022-11-19 06:03
Build should be available soon - will close if we can confirm this fixes it on Android or iOS too, but I expect it to.

-[Unknown]

**Comment by ANR2ME** [comment] 2022-11-19 08:31
> Build should be available soon - will close if we can confirm this fixes it on Android or iOS too, but I expect it to.
> 
> -[Unknown]

I've tried the Android build and it also got fixed now on the latest dev build

**Comment by unknownbrackets** [comment] 2022-11-19 14:57
Hurray, thanks for checking.

-[Unknown]

**Closed by unknownbrackets** 2022-11-19 14:57 UTC
Labels: IRInterpreter
