### ISSUE TITLE
tomb raider legend

### ISSUE THREAD

**Issue by vampire6666** [hrydgard/ppsspp#7188] opened 2014-12-16 05:38 UTC
hardware transform error: falling back to software and becomes super slow. galaxy s iii ppsspp-v0.9.9.1-1202-gc64681d-android

**Comment by unknownbrackets** [comment] 2015-12-29 17:25
This is basically a duplicate of #1816.  We added the "falling back to transform" feature because otherwise, it would just not draw a bunch of stuff (like characters and enemies, for example.)

We still have that open to look for a better solution, such as improving the performance of software transform.  Closing this.

-[Unknown]

**Closed by unknownbrackets** 2015-12-29 17:25 UTC
Labels: Platform-specific (Android)
