### ISSUE TITLE
Danball Senki W: Updates

### ISSUE THREAD

**Issue by DanSenki** [hrydgard/ppsspp#8673] opened 2016-03-27 14:20 UTC
Okay, since no one is bothering to respond to the threads I replied in, I'll just do it here.

Some video cutscenes (the all low and compressed looking ones.) are still skipping off but if viewing a 3D cutscene, it's all fine.

No graphic glitches throughout the game except in certain cutscenes where the screen glitches (at least for a second) and when accessing the Metamo bot.
![npjh50618_00004](https://cloud.githubusercontent.com/assets/15371521/14065773/11afa00e-f3ec-11e5-848d-bebfa803fae2.jpg)
![npjh50618_00006](https://cloud.githubusercontent.com/assets/15371521/14065786/5c865e4c-f3ec-11e5-8cff-fe348ddcfad8.jpg)

other than that, game plays all fine and dandy.

**Comment by unknownbrackets** [comment] 2016-04-10 20:51
This issue is being closed as a duplicate of #4786.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-04-10 20:51 UTC
