### ISSUE TITLE
TERRIBLE FPS in VUKAN and OPENGL Naruto - Ultimate Ninja Heroes 2 - The Phantom Fortress. 🇺🇲USA Ver...🇺🇲

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#15787] opened 2022-08-04 17:03 UTC
### Game or games this happens in

Naruto - Ultimate Ninja Heroes 2 - The Phantom Fortress. 🇺🇲USA Ver...🇺🇲

### What area of the game

menus and submenus...
muitos 

many problems with ONLINE AD-HOC SERVER and CLIENT mode

https://user-images.githubusercontent.com/82737672/182907902-586dd640-14b2-4519-9896-1aef541363fc.mp4

### Speed seen in PPSSPP

2/30

### Platform

Android

### Mobile phone model or graphics card

POCO X3 PRO 8gbRAM Adreno 840

### PPSSPP version affected

ALL

### Last working version

v1.13.1-171-g39cbc253f

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

all possible settings 
STOCK
PATTERN
PSP STANDARD
USER CONFIGURATION

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2022-08-04 17:25
@DavidSilvadeSa how's the in-game?

**Comment by DavidSilvadeSa** [comment] 2022-08-04 17:40
unplayable

**Comment by DavidSilvadeSa** [comment] 2022-08-04 17:45
unplayable in menus submenus and ONLINE ADHOC (SERVER) and (CLIENT) many error conections
playable in gameplay fighting

**Comment by LunaMoo** [comment] 2022-08-04 17:46
You didn't enabled dump textures by accident?
As this looks like a huge struggle when new textures are loaded possibly caused by saving them to storage.

**Comment by DavidSilvadeSa** [comment] 2022-08-04 17:52
the texture replacement option is enabled by default, but inside the TEXTURES folder there is no file to be loaded and even if there was a file to be loaded this kind of problem was not supposed to be happening After all, that doesn't happen in most other games.

🗣️"Google Translate"🗣️

**Comment by LunaMoo** [comment] 2022-08-04 17:57
I mean texture dumping(saving to storage), not replacement.
![dump and replace](https://user-images.githubusercontent.com/5485237/182918484-e532e701-4403-4403-b861-536374ee9773.png)
In some games textures would dump just once, in others it could dump new copies each run due to writing random data inside memory where textures are stored or just variable memory address and texture dumping is usually much more lag inducing than replacing those textures later on.

**Comment by DavidSilvadeSa** [comment] 2022-08-04 18:04
I understood i'm not using the DUMP TEXTURE option no I am using the default PPSSPP configuration and as I said before I tested several configurations pattern psp pattern and custom configuration this issue only happens with the overwrite textures option enabled but there's nothing to load in the textures folder so it kind of makes no sense to have this problem and likewise ONLINE mode can also vary ADHOC disconnection

🗣️"Google Translate"🗣️

**Comment by DavidSilvadeSa** [comment] 2022-08-04 18:09
✨Yes✨

**Comment by Panderner** [comment] 2022-08-05 02:35
POCO M3 Default Settings works fine:

https://user-images.githubusercontent.com/37503397/182989451-29908a17-0293-4a0d-80b2-175736b47323.mp4

**Comment by Gamemulatorer** [comment] 2022-08-05 02:56
Cannot reproduce this.

**Comment by Gamemulatorer** [comment] 2022-12-27 03:16
I cannot reproduce this issue using the recently build on android both opengl and vulkan backend.
![Screenshot_20221227_111355_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/209605507-8710d583-5277-428e-b8c1-d62122e287c0.jpg)
![Screenshot_20221227_110932_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/209605513-a38bbab7-dd8a-46e7-a270-51d3ad2e15f2.jpg)

Save new textures and replace texures are both enable.
![Screenshot_20221227_110817_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/209605602-0f51959e-3e30-4c78-abc2-d9562c36ab08.jpg)
![Screenshot_20221227_111059](https://user-images.githubusercontent.com/37603562/209605606-9a6daebd-eeec-43bc-8eb3-467f330e19cf.jpg)

**Comment by unknownbrackets** [comment] 2022-12-27 08:27
Thanks, I'm just going to close this as fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue with more information and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2022-12-27 08:27 UTC
Labels: Platform-specific (Android), Performance
