### ISSUE TITLE
Recursively scan subfolders within the PSP games folder

### ISSUE THREAD

**Issue by antoniodesousa** [hrydgard/ppsspp#16372] opened 2022-11-10 11:57 UTC
### What should happen

A checkbox button in the "Games list settings" to enable recursively scan subfolders.
Enabling it will scan all the folders inside of the PSP games folder.

### Who would this benefit

Everyone who has the games inside subfolders for different reasons.

### Games this would be useful in

It doesn't apply.

### Other emulators or software with a similar feature

PCSX2, Dolphin, RetroArch...

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment] 2022-11-12 17:16
Isn't this essentially a duplicate of #9649?

-[Unknown]

**Comment by antoniodesousa** [comment] 2022-11-12 17:39
He used a very strange title... but the main idea is the same, yes. This would be a very welcome feature for users (myself included obviously) that don't keep all their games in a single folder. I actually find it very strange that this option hasn't been included already because all major emulators out there offer this possibility since years ago.

**Comment by unknownbrackets** [comment] 2022-11-20 23:50
Okay, I'm going to close this as a duplicate of #9649, then.  It's best to keep the use cases and related information centralized.

-[Unknown]

**Closed by unknownbrackets** 2022-11-20 23:50 UTC
Labels: Feature Request, User Interface
