### ISSUE TITLE
Pursuit Force [UCET-00007] - Crashing PPSSPP

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8427] opened 2016-01-15 01:08 UTC
When playing **Pursuit Force**, the emulator crashes after the cut scene in the mission *Atomic Ambush*. I don't really know much about debugging or how to provide proper log data, so please enlight me!

**Game:** Pursuit Force
**Disk Name:** UCET-00007
**OS:** Windows 7 x64
**Version:** PPSSPP 1.1.1

**Crash Mission:** [2] The Warlords -> [3] Atomic Ambush

**Comment by unknownbrackets** [comment] 2016-01-15 02:13
Try a clean rip from your own disc.  As far as I know, UCET indicates a beta/test game that may be buggy or crashy.  It could be this crashes on a real PSP as well, unless this is a rip from a disc and just mislabeled game ID.

Also, try the latest git build, available on the downloads page.  Many things have been improved and fixed since the v1.1.1 release.

Lastly, try updating your video card drivers.  Emulators often use features of video drivers that aren't as commonly used by modern and normal games.  Sometimes crashes are caused by bugs in the drivers.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-15 02:53
UCES00019 works fine.

**Comment by unknownbrackets** [comment] 2016-01-15 03:28
I'm going to close this then.  If it still happens with an actual release version of a game (although that would mean it's probably a driver issue), or doesn't happen on an actual PSP with the test version, we can reopen.

-[Unknown]

**Closed by unknownbrackets** 2016-01-15 03:28 UTC
