### ISSUE TITLE
Blackscreen after pressing home button or recent apps button on Android.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#11213] opened 2018-06-24 19:20 UTC
What happens?
Using the ppsspp RetroArch core on Android if you load a psp game and then press the home button or the recent apps Android button and then go back to RetroArch to play you only get a blackscreen but the game's music is still playing and the game is controllable but you only see blackscreen.

What should happen?
It should resume correctly.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7 motog5 plus, using latest ppsspp core from the online updater and latest RetroArch nightly as of today.

**Comment by unknownbrackets** [comment] 2021-05-16 23:52
I suspect this is #10784.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-06-30 02:37
This issue is being closed as a duplicate of #10784.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-06-30 02:37 UTC
Labels: Libretro
