### ISSUE TITLE
VK_ERROR_DEVICE_LOST error

### ISSUE THREAD

**Issue by Pik-a-boo** [hrydgard/ppsspp#12379] opened 2019-09-30 12:13 UTC
### What happens?
When you close a game using the Vulkan renderer the error here : https://cdn.discordapp.com/attachments/480103153803460614/628195885775454231/unknown.png
will happen and repeat itself 3-4 times.
It might also happen when ingame but I am not sure.
### What *should* happen?
when exiting PPSSPP that error should not happen.
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
OS:Windows 10
GPU: Radeon 530 is the GPU in use for PPSSPP Intel UHD 620 is the secondary GPU.
CPU : I7-8550U.
PPSSPP Version : 1.9
I am using a laptop.

**Comment by hrydgard** [comment] 2019-09-30 12:18
Unless this also happens in-game, this is a dupe of https://github.com/hrydgard/ppsspp/issues/10646 .

**Closed** 2019-09-30 19:12 UTC
Labels: Vulkan
