### ISSUE TITLE
ppsspp iOS (dinamic recompiler broken in ios 9 jalibroken).

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#8066] opened 2015-10-14 18:25 UTC
now crash at start up.

**Comment by hrydgard** [comment] 2015-10-14 21:20
@angelXwind , sorry to summon you again, but do you know if anything changed in the new jailbreaks? no more jit?

**Comment by romi1996** [comment] 2015-10-14 21:34
@hrydgard receiving the same issue at PPSSPP 1.1.1 on iOS 9 . I don't know much about this programing except designing so if i can do anything to help you , just tell me . I'm glad !

**Comment by angelXwind** [comment] 2015-10-14 21:45
Are you sure that the crash is caused by JIT and not something else?

I currently do not have any devices on 9.0.2 to test, so...

**Comment by hrydgard** [comment] 2015-10-14 21:46
I am not sure about anything, just a theory from someone who reported the same thing over e-mail.

**Comment by angelXwind** [comment] 2015-10-14 21:51
@hrydgard Can we speak on IRC?

**Comment by romi1996** [comment] 2015-10-14 21:54
@hrydgard @angelXwind https://www.youtube.com/watch?v=bQo9e-O378o
For more information.

**Comment by hrydgard** [comment] 2015-10-14 21:56
@angelXwind yeah.

**Comment by brujo5** [comment] 2015-10-14 22:12
its happend in Retroarch emulator to when use mupen64 and pcsx rearmed cores.

so the only way to play is editing the config file and change dynamic recompiler for pure interpreter or cache interpreter.

or pangu jalibreak broken dynarec adress.

**Comment by angelXwind** [comment] 2015-10-14 22:44
The new iOS 9 untether works in a vastly different manner compared to previous jailbreaks — I won't go into the details, but all JIT implementations will need to be modified in order to continue working on iOS 9.

**Comment by brujo5** [comment] 2015-10-14 22:53
thank you very much for valuable help.

**Comment by angelXwind** [comment] 2015-10-15 04:06
Actually, I think what's happening here is in fact not **just** JIT being potentially broken (maybe if we're lucky, it's not broken at all?)

But rather... the fact that PPSSPP is an unsandboxed 32-bit binary.

Maybe `-Wl,-segalign,4000` needs to be added to the linker flags?

See: https://twitter.com/saurik/status/654198997024796672

**Comment by brujo5** [comment] 2015-10-15 04:24
That mean:
ppsspp needed support for the upcoming  Cydia Substrate update, right?

 CydiaSubstrate.framework need build with fix for pagesize on arm64 devices

**Comment by brujo5** [comment] 2015-10-15 14:32
@hrydgard 

![image](https://cloud.githubusercontent.com/assets/4172898/10516778/24649ebc-7317-11e5-9ef8-5e0455dae69c.png)

look at this picture. Thx

**Comment by hrydgard** [comment] 2015-10-15 21:45
Yes, thanks, we have that information in this thread already. 

It should be a simple matter of adding those parameters somewhere in CMakeLists.txt - I'm not sure exactly where though. I will not have more time to code this week, so I leave you guys to it, and if you can't figure out I'll give it a try next week.

**Comment by Rapsac11** [comment] 2015-10-16 10:08
Hi,

Gave this a go this evening. Was able to build and run on my 6S Plus 9.0.2 JB. Seems like there is indeed a problem with the dynamic recompiler. PPSSPP will die as soon as JIT is engaged, this happens immediately upon selection an .iso image. Turning off JIT in the developer tools inside the app will allow it to not fall over at the fist sign of JIT but will still crash shortly after for another reason (probably JIT related). However it will still get far enough along to load some other resources such as the on-screen control overlay.

It seems to be at the limit of my knowledge for now. Hope we can get this running soon!

Thanks!

**Comment by hrydgard** [comment] 2015-10-16 10:25
@Rapsac11 Pull requests accepted with whatever you have.

Try playing around with adding MAP_JIT to the flags of the mmap call in AllocateExecutableMemory in Common/MemoryUtil.cpp.

**Comment by Rapsac11** [comment] 2015-10-16 12:21
@hrydgard It seems errors are popping up in GPU/Common/VertexDecoderCommon.cpp as well as the Core/MIPS/ARM/ArmJit.cpp. Cant look at zombies though so its hard to tell whats going on. 

I tried adding MAP_JIT in the mmap call flags but didn't get much out of it. I also noticed some hard coded 4096 (page?) sizes in the Common/MemoryUtil.cpp.

Not sure theres much use in a pull request as I haven't changed much at all. Let me know if you'd like me to try anything else.

Cheers

**Comment by brujo5** [comment] 2015-10-16 14:45
@Rapsac11 

read 

![image](https://cloud.githubusercontent.com/assets/4172898/10544725/3dbf5f20-73e2-11e5-82d3-78a7fb330ce0.png)

**Comment by brujo5** [comment] 2015-10-18 05:56
more info

in iOS 9, applications that aren't natively capable of supporting 64-bit have to be recompiled due to a change in the way binaries work.
binaries can't be appropriately mapped to memory due to restrictions imposed by the instruction set architecture. Because of this, the applications can't be loaded into memory, and thus, cannot be ran. To make these applications work again, the creators need to recompile with these linker flags: -Wl,-segalign,4000

**Comment by angelXwind** [comment] 2015-10-21 17:44
I've figured it out.

However, I think I should create a new issue thread simply due to the incorrect information above?

@hrydgard

**Comment by angelXwind** [comment] 2015-10-21 17:45
![image](https://cloud.githubusercontent.com/assets/1980487/10645099/ee8bf014-77f9-11e5-9b0d-9b63e33aeffb.png)

Here's proof of PPSSPP running under iOS 9.0.2 (proof: yellow battery icon == low power mode == iOS 9-exclusive feature)

**Comment by hrydgard** [comment] 2015-10-21 17:56
@angelXwind sure, I'll close this when you created you new one, if you like. So what's the solution?

**Comment by brujo5** [comment] 2015-10-21 17:57
so is not related to jit?

**Comment by Fadi5555** [comment] 2015-10-21 18:37
@angelXwind wow that's fantastic.
Nice proof.

I hope we could also can use tweak called (controller for all) to play pep games with PS3/4 controller again like when we were on iOS 8

**Comment by Juxen** [comment] 2015-10-22 04:35
Nice work angel and hryd! I hope you can solve this soon!

**Comment by KingKongGato** [comment] 2015-10-22 15:13
The main reason why I won't upgrade to iOS 9 is because of this...

**Comment by brujo5** [comment] 2015-10-22 15:33
@angelXwind 

I hope to have a solution?

**Comment by brujo5** [comment] 2015-10-23 02:00
@hrydgard 

What about http://iphonedevwiki.net/index.php/Updating_extensions_for_iOS_9

**Comment by angelXwind** [comment] 2015-10-24 01:49
@brujo5 @hrydgard That wiki page is irrelevant — PPSSPP is an app, not a Substrate extension.

While I work on creating a pull request for a partial iOS 9 fix, here's the rundown:

1. Current JIT implementation is broken. I have already told @hrydgard how to fix it — I will be able to make this public info soon. (Also helps out the RetroArch guys).

2. The crash on launch is **unrelated** to the JIT issue.

**Comment by brujo5** [comment] 2015-10-24 02:17
@angelXwind 

redownloaded and still crash at lauch:(

**Comment by angelXwind** [comment] 2015-10-24 02:27
@brujo5 the buildbot hasn't completed the latest rebuild yet — wait a bit.

**Comment by brujo5** [comment] 2015-10-24 02:28
ok thank you:)

**Comment by brujo5** [comment] 2015-10-24 05:43
the ppsspp crash at lauch is fixed, homewever crash at load any rom (jit OFF)

thanks

what happend?

**Comment by hrydgard** [comment] 2015-10-24 08:34
Probably the vertex decoder jit. I thought we had code to disable it when jit is not available, but it's not activating on ios9.

**Comment by angelXwind** [comment] 2015-10-24 18:26
@hrydgard I think that is because PPSSPP is detecting iOS 9 as being jailbroken, and therefore `canUseJit` is set to `1`.

I'll be sending a pull request soon that modifies the `canUseJit` detection logic to take into account iOS 9 until the JIT is fixed.

**Comment by hrydgard** [comment] 2015-10-24 18:39
Great. I'll mess around with the JIT once the thing at least runs.

**Comment by brujo5** [comment] 2015-10-24 21:30
@angelXwind 

Update again and the crash at launch come back.

**Comment by loldante** [comment] 2015-10-24 23:53
Still crashing when you try run a room

**Comment by Juxen** [comment] 2015-10-25 00:47
Confirmed what loldante and brujo5 said.

**Comment by romi1996** [comment] 2015-10-25 10:06
It work perfectly for 32 bit chip such as ipad 3 tested by me . not sure about 64 bit

**Comment by Fadi5555** [comment] 2015-10-26 06:12
It's still crash when we select games however it's launch fine without crash
My device is iPad Air 2 (64 bit)

**Comment by Juxen** [comment] 2015-10-26 06:20
Now the app does not crash at open but it is still crashing when you select a game tested on (iPhone 5s jb 9.0.2).

**Comment by angelXwind** [comment] 2015-10-26 06:57
Don't need any more reports of what's happening — no changes are actually being made to the builds.

The situation will remain the same until I finish the pull request and it gets merged.

**Comment by Fadi5555** [comment] 2015-10-26 07:10
@angelXwind got the point. Best of luck.

**Comment by ruusseell06** [comment] 2015-10-27 06:50
still not working the app doesnt crash anymore when opening but when choosing a game it crash again :( please fix

**Comment by fuzhuo** [comment] 2015-10-27 12:54
With force set cpuCore from JIT to CPU_INTERPRETER mode, and disable vertexDecoderJit I can successfully loading and play game(God of War, and game crash after playing sometime..), there may have performance issues.

test patch: [http://jpst.it/CJnq](http://jpst.it/CJnq)

**Comment by angelXwind** [comment] 2015-10-30 02:54
@hrydgard I created issue #8122, this one can be closed now.

**Closed** 2015-10-30 03:01 UTC

**Comment by danyjl94** [comment] 2015-10-30 21:27
Provenance emulator runs roms on iPhone 6

**Comment by danyjl94** [comment] 2015-10-30 21:32
Provenance emulator runs roms on iPhone 6 iOS 9.0.2.
PPSSP still crashes when you load a rom on iOS 9.0.2
See how provenance is installed
Install run Ppsspp the same way may play roms 64bit devices

**Comment by brujo5** [comment] 2015-10-30 21:39
@danyjl94 

provenance emulator not use dynamic recompiler so will work OK on any device

**Comment by Fadi5555** [comment] 2015-11-25 13:30
Any new news about playing psp games on 64 bit devices?
We really miss that so much
