### ISSUE TITLE
Splinter Cell Essentials: Debugger crashes on loading

### ISSUE THREAD

**Issue by ThirteenAG** [hrydgard/ppsspp#15245] opened 2021-12-20 13:45 UTC
### Game or games this happens in

ULUS-10070

### What area of the game / PPSSPP

When starting the game, I open debugger, and at some point shortly after, ppsspp crashes. It doesn't crash without debugger opened, and it crashes upon opening debugger in menu or in-game.

https://user-images.githubusercontent.com/4904157/146776588-63be6643-4040-4b05-9e47-cb8ccb737355.mp4

### What should happen

Debugger should work.

### Logs

Attaching a crash dump just in case.

[PPSSPPWindows64.exe.16688.dmp.zip](https://github.com/hrydgard/ppsspp/files/7745694/PPSSPPWindows64.exe.16688.dmp.zip)

### Platform

Windows

### Mobile phone model or graphics card

1060

### PPSSPP version affected

v1.12.3-489-g31d7d1e55

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2021-12-20 14:38
Could you try to reproduce this with this build and attach a dmp file for it?

https://github.com/hrydgard/ppsspp/actions/runs/1599769449

The reason is that I need the exact exe and pdb that match your crash to use the dmp.  The Orphis buildbot doesn't provide the pdb and its build will be slightly different, so that's why I'm proposing the above one.

-[Unknown]

**Comment by ThirteenAG** [comment] 2021-12-20 23:55
[PPSSPPWindows64.exe.7220.dmp.zip](https://github.com/hrydgard/ppsspp/files/7748583/PPSSPPWindows64.exe.7220.dmp.zip)

```
 	PPSSPPWindows64.exe!XXH3_64bits(const void * input=0x0000000000000000, unsigned __int64 len=0x0000000000000008) Line 3867	C	Symbols loaded.
>	[Inline Frame] PPSSPPWindows64.exe!computeHash(unsigned int) Line 92	C++	Symbols loaded.
 	PPSSPPWindows64.exe!DisassemblyData::DisassemblyData(unsigned int _address, unsigned int _size, DataType _type) Line 906	C++	Symbols loaded.
 	PPSSPPWindows64.exe!DisassemblyManager::analyze(unsigned int address=0x00000000, unsigned int size) Line 255	C++	Symbols loaded.
 	PPSSPPWindows64.exe!DisassemblyManager::getLine(unsigned int address=0x00000000, bool insertSymbols, DisassemblyLineInfo & dest={...}, DebugInterface * cpuDebug=0x0000000000000000) Line 294	C++	Symbols loaded.
 	PPSSPPWindows64.exe!CtrlDisAsmView::getSelectedLineArguments() Line 432	C++	Symbols loaded.
 	PPSSPPWindows64.exe!CtrlDisAsmView::onPaint(unsigned __int64 wParam=0x000002a6261e87f0, __int64 lParam=0x0000000000000000) Line 514	C++	Symbols loaded.
 	PPSSPPWindows64.exe!CtrlDisAsmView::wndProc(HWND__ * hwnd=0x000000000009081e, unsigned int msg=0x0000000f, unsigned __int64 wParam=0x0000000000000000, __int64 lParam=0x0000000000000000) Line 91	C++	Symbols loaded.
```

**Comment by unknownbrackets** [comment] 2021-12-21 00:20
Thanks, that's very helpful.  I made a change in #15247.  Once the checks are complete, you can try the build from the Checks tab, under Artifacts.

-[Unknown]

**Comment by ThirteenAG** [comment] 2021-12-21 18:05
Doesn't crash anymore, although I noticed it doesn't update modules under Modules tab.
Here's the list of modules when debugger is opened right after launching the game:
![image](https://user-images.githubusercontent.com/4904157/146977502-43e668cd-0ba3-4824-b2db-3c9ab91e24bc.png)

And here's the list if debugger is opened during gameplay:

![image](https://user-images.githubusercontent.com/4904157/146977312-e26f2af8-30dd-4cc8-a445-fc6f56a873e6.png)

**Comment by unknownbrackets** [comment] 2021-12-27 00:27
Hm, for me the module list updates when I break, but not during regular game runtime.  I don't think that's different from before.

I think the threads and everything else work the same way, though.

Are you seeing it not update even when you hit Break?

-[Unknown]

**Comment by ThirteenAG** [comment] 2021-12-27 00:30
Yeah, it updates when I break too. Kinda strange if you ask me, would rather see info from current process state.

**Comment by unknownbrackets** [comment] 2022-02-20 22:26
I'm going to close this since the crash is fixed, and the crash was introduced in a recent build.

Currently a lot of things in both the debugger and GE debugger only change when you break, but the memory view only does update on a timer.  Maybe it makes sense to do this with the modules list as well, but it would be a separate issue.

-[Unknown]

**Closed by unknownbrackets** 2022-02-20 22:26 UTC
Labels: Debugger
