### ISSUE TITLE
Ghost Recon Predators - black screen

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#12050] opened 2019-05-19 11:39 UTC
Using PPSSPP v1.8.0-157-gecf3f4096 Windows 64 bit build 

![gif](https://user-images.githubusercontent.com/5770076/57981726-aa03f500-7a4c-11e9-8073-f6985187e4e4.gif)

After the first save menu the game shows a black screen and nothing happens. The Music is still going in the background though 
[InfoLog.zip](https://github.com/hrydgard/ppsspp/files/3195021/InfoLog.zip)
[DebugLog.zip](https://github.com/hrydgard/ppsspp/files/3195022/DebugLog.zip)

**Comment by Drasikk** [comment] 2019-05-19 17:49
When you get the keyboard you can write the name you want? I ask because I have that problem on Android. Here I explain: https://github.com/hrydgard/ppsspp/issues/12044

In Android does not pass that problem that you comment.

**Comment by Levan7** [comment] 2019-05-19 17:53
@Drasikk 

Yes i can enter the name

**Comment by Drasikk** [comment] 2019-05-19 17:56
> @Drasikk
> 
> Yes i can enter the name

Thanks you!

**Comment by hrydgard** [comment] 2020-03-08 23:50
Is this still an issue in the latest build? From what I understand, the game works fine. Please check that you have a clean ISO file as well.

**Comment by Levan7** [comment] 2020-03-09 15:11
@hrydgard It still blackscreens if you don't save the profile and it still has audio issue

**Comment by Gamemulatorer** [comment] 2021-09-23 18:53
> Using PPSSPP v1.8.0-157-gecf3f4096 Windows 64 bit build
> 
> ![gif](https://user-images.githubusercontent.com/5770076/57981726-aa03f500-7a4c-11e9-8073-f6985187e4e4.gif)
> 
> After the first save menu the game shows a black screen and nothing happens. The Music is still going in the background though
> [InfoLog.zip](https://github.com/hrydgard/ppsspp/files/3195021/InfoLog.zip)
> [DebugLog.zip](https://github.com/hrydgard/ppsspp/files/3195022/DebugLog.zip)

Cannot reproduce this on the latest build also there's a chance this was fixed by https://github.com/hrydgard/ppsspp/pull/14867/commits/24f1dcec98ad9d274261b8a6643dc72a5894d898

https://user-images.githubusercontent.com/37603562/134566786-93cc36b2-4306-4e11-a2a9-1b392b844030.mp4

**Comment by unknownbrackets** [comment] 2021-09-24 05:44
I think there's a good chance some of the savedata timing fixes improved this, so that makes sense.  Since you can't reproduce it, I'm going to close.

@Levan7 if you're still seeing this issue in the latest git builds, please comment and we'll reopen.

-[Unknown]

**Closed by unknownbrackets** 2021-09-24 05:44 UTC
