### ISSUE TITLE
Wait for emuthread timeout

### ISSUE THREAD

**Issue by SptolessMarrow** [hrydgard/ppsspp#9835] opened 2017-07-07 03:53 UTC
so i keep having this issue with ppsspp psp emulator 
every time I finish the tutorial on kingdom hearts birth by sleep the game crashes
with the error wait for emuthread timeout Anyone have some ideas?

thanks!!!

**Comment by Michal1324** [comment] 2017-07-09 14:42
Could you post your pc specs os type and os type x86 or x64

**Comment by SptolessMarrow** [comment] 2017-07-10 18:37
Sorry about the wait 
X64 Windows 10 
Gpu: Radeon RX 470 GDDR5 4GB
Cpu: AMD FX 4350 Quad Core Processor 4.2 ghz
Ram: Kingston HyperX FURY 16GB Kit (2x8GB) 1866MHz DDR3

**Comment by Michal1324** [comment] 2017-07-10 20:58
By the look of specs seems like compatibility issue try older or newer PPSSPP builds and see if that helps

**Comment by SptolessMarrow** [comment] 2017-07-10 21:00
Ok have any suggestions on were to start?

**Comment by Michal1324** [comment] 2017-07-10 21:23
Get lastest build 1st from buildbot check if it appears if so go down throught the main version

**Comment by Joelgp83** [comment] 2017-07-12 19:01
Just wanna note that I also encoutered this error yesterday when trying to boot Gods Eater Burst, so I don't think its particularly game related.  Tested on ver. 1.4.2-266-g2d5e7c8.

**Comment by unknownbrackets** [comment] 2017-07-13 02:08
This just means that the PSP emulation thread took too long to complete, while trying to quit emulation.

It can mean a video driver issue, or even mean that your hard disk went to sleep and so it's waiting for it to wake up in order to read data from the disk.

Is this happening without you clicking stop / quit?

-[Unknown]

**Comment by Joelgp83** [comment] 2017-07-13 10:43
Indeed, though in my case I'm not sure if it was cause or effect.  I attempted to boot gods eater boost, it stuck on a black screen for a rather long time, and was unable to access the ppsspp menu (running this in fullscreen, naturally), so started to go for task manager to get myself out of it.

During that process I found the error box in question, but it had been rendered _behind_ everything else.   You may want to check that, because if anything, an error display should both be on top of everything else if youre gonna have it steal input focus like it does.

**Comment by Michal1324** [comment] 2017-07-13 18:30
I only had this issue closing the emulator

**Comment by unknownbrackets** [comment] 2017-07-16 22:48
Did you figure out why the game was hanging?  Did you check the disc crc?

I've not seen this show up behind - it may be a factor of your version of Windows, or using the task manager to kill PPSSPP.  Does this reproduce each time?

-[Unknown]

**Comment by Joelgp83** [comment] 2017-07-17 00:20
Unfortunately, I haven't had time to reproduce the issue lately, but I later found out my Win10 was in the middle of an update cycle during the occurance.  If I can't get it to repro, this may simply be a case resource (scheduler?) starvation.  I'll be following up on this when I get a chance.

**Comment by unknownbrackets** [comment] 2017-12-24 15:48
We've actually removed this message now - if it's hanging, that may still be an issue, but it sounds like it could've been due to Windows Update.  I'm going to close, but feel free to comment if you have more information.

-[Unknown]

**Closed by unknownbrackets** 2017-12-24 15:48 UTC
Labels: No Feedback / Outdated?, Platform-specific (Windows)
