### ISSUE TITLE
Crazy Taxi: Fare Wars crash

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#7867] opened 2015-07-17 02:35 UTC
I have a problem running this game, when i run it on normal speed it runs fine until it gets to loading a stage, then freezes while the emulator spams the console. If I turn off the framelimiter it will crash the emulator at random spots in the menu.

ppsspp-v1.0.1-765-g47f68ae-windows-amd64
Celeron G1610 @ 2.6
Intel Integrated
Basic Graphics Settings

**Comment by daniel229** [comment] 2015-07-18 08:40
duplicate of https://github.com/hrydgard/ppsspp/issues/2451

**Closed** 2015-07-18 15:45 UTC
