### ISSUE TITLE
[Graphics, OGL && D3D] [Phantasy Star Portable 2 US][x64] Draw distance, draw priority bugs, and transparency.

### ISSUE THREAD

**Issue by eleriaqueen** [hrydgard/ppsspp#1788] opened 2013-05-12 19:21 UTC
In Phantasy Star Portable 2 US there's a few bugs but they don't appear everywhere. First the one cutting the feet of the characters when camera is default.
![image](http://img854.imageshack.us/img854/1032/legscutdefaultcamera.png)

When camera looks downwards the whole body is cut off.
![image](http://img194.imageshack.us/img194/7905/wholebodycutcameradownw.png)

When camera looks upwards the whole body is showing.
![image](http://img545.imageshack.us/img545/6528/fullbodynocut.png)

Also if you look closely, not only the body is cut off, but parts of the background too, light-like effects and transparent hologram-like screen don't show on default and downwards camera. And the door appears sometimes and sometimes it doesn't.

When in complete upwards looking camera position everything is displayed (it seems) but as soon as you move the camera just an inch up a lot of the background disappears.

---

Some Background Objects only appear when close to them  which is wrong. (notice the bug in the font, the "i" are too thin, and spacing is wrong)
![image](http://img7.imageshack.us/img7/948/tappear.png)
![image](http://img543.imageshack.us/img543/3953/crystalappears.png)

---

Also, photon weapons should be tranparent but they're not, they're also missing their glow (you know the glow that hovered over the characters quite a few revisions back)
Also weapons are not drawn correctly when a character is behind.
![image](http://img35.imageshack.us/img35/875/weapongoesthroughchars.png)

---

There are no errors in Debug Log, except the issue I mentioned there : https://github.com/hrydgard/ppsspp/issues/1785

Get this fixed and a lot of the game will be playable as now as of 0.7.6 - 547 there are character portraits and game is running pretty well, and I CAN LOAD MY PSP CHARACTERS FINE !!

**Comment by unknownbrackets** [comment] 2016-01-03 07:21
So, just to clarify and summarize what's going on here, at least from what I can tell.

1. It's not that the invisible things are being clipped.  They're drawing inside normal depth bounds.
2. Regular `src > dst` depth tests are simply failing; they are why things aren't drawing.
3. It's not really a rounding issue; the difference in the existing depth (e.g. 44304) and the drawn depth (e.g. 44051) is larger than that.

Now, the game, when drawing it's scenery, does a lot of drawing with wild coordinates.  They're probably not wrong, but many are significantly outside the valid window space, so it's *possible* this is a clipping issue; maybe the draw that's establishing the depth values that the future tests fail on is a draw that should be culled/clipped entirely.

Another possibility is that it's a vertex ordering issue; maybe somehow the later vertices that establish the wrong depth should be failing tests.

But, I don't really think it's that, because the scenery visually looks correct.  And also because of the hack which currently works around this issue.

So, when drawing the backgrounds, it uses this viewport:

Viewport Scale	240.000000, -136.000000, -27635.000000
Viewport Offset	2048.000000, 2048.000000, 26116.000000
Min Z	002710 (10000)
Max Z	00fef6 (65270)

When drawing the character (specifically the part that fails to show up), it uses this one:

Viewport Scale	240.000000, -136.000000, -27635.000000
Viewport Offset	2048.000000, 2048.000000, 37635.000000
Min Z	002710 (10000)
Max Z	00fef6 (65270)

Below, remember that the output of vertex depth (vz) is going to be in the range of [-1, 1].  Anything outside that is clipped.  So, while drawing the backgrounds, z works like this:

z = (vz * -27635) + 26116
z = [-1519, 53751]

After that, anything outside min/max z is clipped as well.  So the final range of z is [10000, 53751].

When drawing the character, the range is simply [10000, 65270] form the start.  In this case, minz/maxz are not needed, because the viewport is already equivalent.

Here's the issue, though: glDepthRange (which we use to establish the viewport range) CLAMPS its inputs.  I think this is mentioned above, but just clarifying it here.  What this means is that the scenery, which was supposed to use:

z = (vz * -27635) + 26116
z = [-1519, 53751]

Ends up using:

z = (vz * -26875.5) + 26875.5;
z = [0, 53751]

As you can see, this is a completely different formula.  And it'll bias the z output values higher by about 3% - just enough to make a depth tests near the floor and stuff fail.

With this, we arrive at the depth range hack.  This attempts to adjust the viewport (just as we do for X and Y) to account for this clamping.

Really, it should be completely possible to implement this in a way that works with all games and can simply be statically enabled, as we already do with x and y.  The only tricky part is that clipping needs to still work correctly.  I'm not sure what "correctly" means in this context; ultimately fragments outside minz/maxz should not be drawn.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-06 04:17
Some light flicker instead
![03](https://cloud.githubusercontent.com/assets/3481559/12134881/21fb6cde-b46f-11e5-936f-a15644195cef.png)

the 4 and 5 picture in the top post still happen.

**Comment by unknownbrackets** [comment] 2016-01-06 04:55
I'll reopen for the flicker.  But, picture 4 and 5 may simply be a render resolution issue.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-01-18 04:32
I'm not able to reproduce the font issue, even at higher resolutions?

Could you post a savestate that reproduces the photon weapon issue and the background object issue?  The glowing swords seem to be layering correctly...

For the flicker, maybe we need to use pixel depth rounding... hmm.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-18 06:51
The person seems brighter in software rendering.
![06](https://cloud.githubusercontent.com/assets/3481559/12384972/ac891158-bdf2-11e5-8109-65023d0863be.png)
![07](https://cloud.githubusercontent.com/assets/3481559/12384973/ac8c1c40-bdf2-11e5-8c89-eb1461e290c6.png)

If the savestate helps.
![npjh50043_2 00_2](https://cloud.githubusercontent.com/assets/3481559/12384983/d1aebf3c-bdf2-11e5-81b8-6c9b13d66e57.jpg)

**Comment by unknownbrackets** [comment] 2016-01-18 07:04
That seems right near the start, okay.  I will bust out my PSP, but the plasma sword or whatever it is seems to be layering properly.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-01-18 07:26
So, on a PSP-2000, using a US region game, the following notes:

 * Layering of the saber is the same.  It is behind her to a point, and there's an area where it overlaps partially, and then it's in front.  Nothing looks unsual.
 * All colors are visually greener than my PSP-2000 screen, which looks bluer.  This applies to the entire screen, which is probably colder.  I think my PSP-3000 had an option for color temperature.
 * The shield looks perhaps a bit duller and bluer on the PSP compared to OpenGL, but pretty much the same.  The software rendering above is differently different and wrong.
 * The red bars on the door appeared only when I entered the room.  The effect matched the PSP.
 * The girl, when out of view, faded out slightly.  The effect matched the PSP.

So at least in the intro area, I didn't notice any differences.  I might've just missed it, though.  Could it be the problems are different with the JP region game?

-[Unknown]

**Comment by daniel229** [comment] 2016-01-18 07:39
Yes, looks fine under 1x
![08](https://cloud.githubusercontent.com/assets/3481559/12385689/8a9bcf7a-bdf9-11e5-97ff-1303134535ba.png)

**Comment by thedax** [comment] 2018-09-07 02:33
Out of curiosity, I revisited the core issue of background objects and characters disappearing based on the camera angle and distance, and it seems that only OpenGL still needs the DepthRangeHack set to true in compat.ini. D3D9, D3D11, and Vulkan don't have the issue from what I could see (even with DepthRangeHack set to false). Tested with commit g562c5f648.

**Comment by unknownbrackets** [comment] 2018-09-07 03:17
Probably means that the "accurate depth" path used on the other backends is doing depth correctly in this case.

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-11-21 00:46
This hack is now only used when depth clamp is unsupported on GLES/OpenGL.  It's working correctly without the hack in situations where we are using the "accurate depth" path, so I'm going to close this.

-[Unknown]

**Closed by unknownbrackets** 2022-11-21 00:46 UTC
Labels: Depth / Z
