### ISSUE TITLE
FF II and Tactics Rendering Resolution Problem (Pixelated fonts and moving stuff)

### ISSUE THREAD

**Issue by gabourael** [hrydgard/ppsspp#11315] opened 2018-08-23 15:48 UTC
### What happens?
The font in textbox and moving things and characters got pixalated for a moment then become clear again (like a focus was made) when the rendering resolution goes higher then 1xPSP.  That "focus" phenom becomes more apparent with each higher resolution (being worst at 10xPSP). No modification in settings (other then drop the rendering resolution) seem to work.

### What *should* happen?
Stay clear all the time (not pixalated) like it does in FF1 per exemple

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows 10 64bits
PPSSPP 1.6.3.
GPU Nividia GTX 970M (laptop)

Backend OPENGL
Mode BUFFERED RENDERIGN
Simulate Block Transfer effects ON

FrameSkipping OFF
Auto Frame OFF
Prevent FPS from exceeding 60 ON

Post Processing Shader  Natural Colors No Blur
Fullscreen ON

Rendering Resolution 10xPSP (glitch not apparent at 1xPSP)
Vsync ON
Hardware Transform ON
Software skinning ON
Vertex Cache ON
Lazy texture Caching OFF
Retained changed textures OFF
Disable slower effects  OFF
Spline/Biezer curves quality HIGH
Hardware Tessellation OFF

Upscale level 5x
Upscale Type xBRZ
Deposterize OFF

Anisotropic filtering 16x
Texture filtering AUTO
Screen scaling filter LINEAR

Timer Hack OFF
Disable Stencil test OFF
Lower resolution for effects OFF

Show FPS Counter NONE
Show debug statistic OFF

**Comment by unknownbrackets** [comment] 2018-08-23 23:33
This is because of texture upscaling.  To prevent you from getting severe framedrops, texture scaling only scales so much per frame.  This game will sometimes change textures pointlesssly, causing them to need to be rescaled.  This causes them not to be rescaled immediately.

You might expect that your military grade, liquid-submerged supercomputer can actually handle any texture scaling the world could throw its way, but xBRZ - especially 5x - is very CPU heavy.  There are some plans to potentially use a different scaling method that could be more optimal, but it may not handle alpha as well and there are some problems.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-08-25 17:50
This issue is being closed as a duplicate of #1934.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-08-25 17:50 UTC
