### ISSUE TITLE
Minor texture scaling issue in MHP3rd(ULJM5800)

### ISSUE THREAD

**Issue by tywald** [hrydgard/ppsspp#9401] opened 2017-03-07 17:34 UTC
Texture scaling drops on some icons in the PSP version(non-HD version) of Monster Hunter Portable 3rd when you pick up a quest in the guild hall in multiplayer.

Even if you resize, change the multiplier, turn it off then back on to refresh the scaling it's still broken. If you drop the quest it seems to fix it but breaks again when you pick it up.

![uljm05800_00140](https://cloud.githubusercontent.com/assets/10337060/23668584/d70c1992-0361-11e7-8615-29cdf2d98bbd.png)
![uljm05800_00137](https://cloud.githubusercontent.com/assets/10337060/23668585/d72d6282-0361-11e7-962f-ef5031dde4a4.png)
![uljm05800_00136](https://cloud.githubusercontent.com/assets/10337060/23668587/d73addc2-0361-11e7-9786-dbcc9b96560b.png)
![uljm05800_00135](https://cloud.githubusercontent.com/assets/10337060/23668586/d7398b34-0361-11e7-97f7-b29c514dc71a.png)
![uljm05800_00134](https://cloud.githubusercontent.com/assets/10337060/23668588/d73f13ba-0361-11e7-9049-e23f842fdbc7.png)

**Comment by LunaMoo** [comment] 2017-03-07 19:45
Texture for those icons is only partially used by actual sprites, memory after them is keeping other data which depending on other things in game might change every frame.

 Avoiding scaling textures that change every frame is not a bug, but an important performance feature, also it's a duplicate of #1934 and as such I'll close this.

 Anyway all you can do about it is either try and use texture replacement for it("hashranges" there might work well for this game since it might keep the texture address of icons constant), or build yourself a custom version which kills all performance limitations and it will then run texture scaling every single frame, potentially causing stutter or slowdowns depending on the cpu.

**Closed by LunaMoo** 2017-03-07 19:45 UTC

**Comment by tywald** [comment] 2017-03-07 19:53
I see. 

This doesn't happen on the HD-version of the game so I thought there could be something trivial that causes it.
