### ISSUE TITLE
Dai-2-ji Super Robot Taisen Z: Hakai-hen   Graphics glitch

### ISSUE THREAD

**Issue by Isamiyuu** [hrydgard/ppsspp#17069] opened 2023-03-07 10:30 UTC
### Game or games this happens in

ULJS00379 : 第2次スーパーロボット大戦Z 破界篇

### What area of the game

ATTACK ANIME

### What happens

Graphics glitch
![2023-03-07 (3)](https://user-images.githubusercontent.com/89466031/223395440-39b60135-ad92-42bd-a41c-69ff85771186.png)

### What should happen

![2023-03-07 (4)](https://user-images.githubusercontent.com/89466031/223395645-85d7a25b-480c-49b6-a21d-bef6cd67ffa3.png)
correct picture

### Platform

Windows

### Mobile phone model or graphics card

RTX 3060 Ti

### PPSSPP version affected

V 1.14.4

### Last working version

v1.14.4-743-gb4c899440

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2023-03-07 12:52
the black thing on the left looks like you inadvertently enabled the experimental stereo mode in Settings / Tools / Developer Settings.

**Comment by Isamiyuu** [comment] 2023-03-07 15:14
> the black thing on the left looks like you inadvertently enabled the experimental stereo mode in Settings / Tools / Developer Settings.

![2023-03-07 (5)](https://user-images.githubusercontent.com/89466031/223464325-048748c6-c709-470e-85a6-8749b78ccc21.png)
Which one is it please?

**Comment by hrydgard** [comment] 2023-03-07 19:43
I only know a few Chinese characters, but looking in the zh_TW translation file, you wanna be sure that "立體轉譯" is unchecked (scroll down). (note that it'll only be visible if backend is set to Vulkan).

**Comment by Isamiyuu** [comment] 2023-03-07 22:13
> I only know a few Chinese characters, but looking in the zh_TW translation file, you wanna be sure that "立體轉譯" is unchecked (scroll down). (note that it'll only be visible if backend is set to Vulkan).
> 
> If it already is unchecked, then this is something else which needs to be looked into. In that case, a GE frame dump can help. See https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

[ULJS00379.zip](https://github.com/hrydgard/ppsspp/files/10914308/ULJS00379.zip)
The ppdmp file cannot be uploaded. I will make it into a ZIP first. Please rest assured that it is non-toxic. Thank you.

**Comment by hrydgard** [comment] 2023-03-07 22:26
This is interesting - when replaying the dump, it looks like we have a black screen but it does go through all the drawing steps, and I can reproduce the darkened glitch on the left. In D3D11 it doesn't appear, but same black screen in the end anyway.

To account for the black screen, I assume we're just presenting the wrong framebuffer or something, likely not relevant to this issue.

**Comment by Isamiyuu** [comment] 2023-03-07 22:53
> Thanks, perfect.
> 
> This is interesting - when replaying the dump, it looks like we have a black screen but it does go through all the drawing steps, and I can reproduce the darkened glitch on the left. In D3D11 it doesn't appear, but same black screen in the end anyway.
> 
> To account for the black screen, I assume we're just presenting the wrong framebuffer or something, likely not relevant to this issue.
> 
> Also, the issue doesn't appear if we enable multisampling, so this might have something to do with my input attachment optimization which is off in that mode, which I'm less and less fond of ... Thinking of turning it off entirely. Though not sure how this happens, nevertheless.

I just tried D3D11 and I did not see the black screen. Thank you. Should I close this place?

**Comment by hrydgard** [comment] 2023-03-08 05:03
No, I'll close it when it's fixed in vulkan.

**Comment by unknownbrackets** [comment] 2023-03-08 06:06
I think something we changed a while back with frame detection made it so we're not always getting dumps that display something.  If you step it's fine.  Usually this means the game does this internally:

START draw to buf 2
display buf 1
SYNC draw to buf 2
START draw to buf 1
display buf 2
SYNC draw to buf 1
START draw to buf 2
display buf 1
...

So when we only frame dump a single frame (before we often accidentally frame dumped multiple), you end up with a display tied to a frame that was not rendered within the frame dump.

```
<--- snip
START draw to buf 1
display buf 2
<--- snip
```

But there may be other causes.

-[Unknown]

**Closed** 2023-04-01 21:28 UTC
Labels: GE emulation
