### ISSUE TITLE
Toca Race Driver 3 demo (ULED90009) - Error code: 80110305

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#11037] opened 2018-05-12 23:43 UTC
Decrypted DATA.PSP but still get the following error
Error code: 80110305 - Load failed. The Memory Stick could not be accessed.

I guess this has something to do with the manifest.drm and rd3demo.drm files also? I tried decrypting them in prxdecrypted also but nothing was decrypted.

Here's the rebuilt EBOOT.PBP with decrypted DATA.PSP
http://anonfile.com/Hbf717eebc/ULED90009.rar

EDIT: Placing rd3demo.drm & manifest.drm in ppsspp\memstick\PSP\GAME\ULED90009 
makes it run but with a few graphical issuses. If both files are outside the memstick folder and just alongside the EBOOT.PBP it'll give the above error code.

**Comment by LunaMoo** [comment] 2018-05-13 01:01
Glitch needs #9527, as for the directory confusion - you should always launch homebrew and demos from GAME folder for compatibility, this can be seen like a DLC. That is - just like DLC's the game includes hardcoded path to those files and they can't be stored whenever you wish, but where the game wants to look for them;p.

 Closing since the only fixable issue here is a duplicate of #5001 and the non fixable one about having to decrypt it to begin with is a duplicate of #4676

**Closed by LunaMoo** 2018-05-13 01:01 UTC
