### ISSUE TITLE
Battleground 3 Homebrew shadow glitch on Mali gpu

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12851] opened 2020-04-23 23:23 UTC
### What happens?
This game is super lag and it has a graphic glitches see the shadow of the tank
![Screenshot_20200424-071453](https://user-images.githubusercontent.com/37603562/80158833-1fccf500-85fc-11ea-853d-4bea9653c122.png)

### What *should* happen?
Should running smooth and no graphics glitches.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 6.0.1
Mali-450 MP4
Octacore 1.36GHz
PPSSPP v1.9.3-702-gitbuild

For the GE Dump see my comment here https://github.com/hrydgard/ppsspp/issues/8923#issuecomment-618550272

**Comment by LunaMoo** [comment] 2020-04-23 23:54
Works fine on PC:
![BG3H00252_00001](https://user-images.githubusercontent.com/5485237/80160064-f3e64b00-85cc-11ea-9eb8-6c36afefefab.jpg)

So glitches are either Mali specific or caused by your settings.

As for performance, be realistic, that's an old phone with 8 very weak cores, meanwhile this game while not really that complex does run at 60 fps which is always harder to run smoothly on weak hardware.

**Comment by Emulatorer** [comment] 2020-04-24 00:04
Im currently using default settings :)

**Comment by Emulatorer** [comment] 2020-04-24 00:10
I tried psp x1 rendering resolution the game performance improve a little bit but the graphics glitches is getting worst or maybe it's only my GPU Mali-450 has this issue like Monster Hunter 3rd HD graphics glitches #7218

**Comment by LunaMoo** [comment] 2020-04-24 02:00
You can try this to improve performance ~ at the cost of framerate ofc:

```
//For Battlegrounds 3 v0.5.0 from PPSSPP homebrew store
_C0 30fps patch
_L 0xE0070ABB 0x00015DDC
_L 0x20015DDC 0x0A200800
_L 0x20002000 0x0E210ABB
_L 0x20002004 0x00000000
_L 0x20002008 0x0E210ABB
_L 0x2000200C 0x00000000
_L 0x20002010 0x0A205750
_L 0x20002000 0x00000000
_C0 30fps patch [Disable]
_L 0x20015DDC 0x0E210ABB
```

 Althrough I can't tell whatever it's much better than just using frameskipping.

**Comment by Emulatorer** [comment] 2020-04-24 02:08
> You can try this to improve performance ~ at the cost of framerate ofc:
> 
> ```
> //For Battlegrounds 3 v0.5.0 from PPSSPP homebrew store
> _C0 30fps patch
> _L 0xE0070ABB 0x00015DDC
> _L 0x20015DDC 0x0A200800
> _L 0x20002000 0x0E210ABB
> _L 0x20002004 0x00000000
> _L 0x20002008 0x0E210ABB
> _L 0x2000200C 0x00000000
> _L 0x20002010 0x0A205750
> _L 0x20002014 0x00000000
> _C0 30fps patch [Disable]
> _L 0x20015DDC 0x0E210ABB
> ```
> 
> Althrough I can't tell whatever it's much better than just using frameskipping.
> 
> Edit: sorry, messed up one line and it wasn't working;p, fixed now.

Thanks I will test this asap 👍

**Comment by Emulatorer** [comment] 2020-04-24 02:12
Thanks for the 30fps cheat the game performance improve much better
![Screenshot_20200424-101123](https://user-images.githubusercontent.com/37603562/80167899-249da300-8614-11ea-9f36-96cdf0492fc3.png)

**Comment by Panderner** [comment] 2020-04-24 11:42
How about the shadows

**Comment by Emulatorer** [comment] 2020-04-24 16:11
> How about the shadows

that's a driver bug I think..

**Comment by LunaMoo** [comment] 2020-04-24 20:26
Reopening since it's still an existing issue, just limited to Mali gpu.

**Comment by unknownbrackets** [comment] 2020-04-24 21:12
Can anyone test if this happens on newer Malis?  Just to confirm if it's the same as the known Mali driver bug.

-[Unknown]

**Comment by Saramagrean** [comment] 2020-04-24 23:20
Mali T-880 (GLES 3.2) broken shadow is happen on OpenGL only, Vulkan is fine.

OpenGL
![Screenshot_20200425-061503_PPSSPP](https://user-images.githubusercontent.com/26355472/80263975-af39dd00-86bc-11ea-825d-3cb0b5150c06.png)

Vulkan
![Screenshot_20200425-061529_PPSSPP](https://user-images.githubusercontent.com/26355472/80264009-cd9fd880-86bc-11ea-8b75-2d8a6ab98e7c.png)

**Comment by Emulatorer** [comment] 2020-04-24 23:50
> Mali T-880 (GLES 3.2) broken shadow is happen on OpenGL only, Vulkan is fine.
> 
> OpenGL
> ![Screenshot_20200425-061503_PPSSPP](https://user-images.githubusercontent.com/26355472/80263975-af39dd00-86bc-11ea-825d-3cb0b5150c06.png)
> 
> Vulkan
> ![Screenshot_20200425-061529_PPSSPP](https://user-images.githubusercontent.com/26355472/80264009-cd9fd880-86bc-11ea-8b75-2d8a6ab98e7c.png)

@Saramagrean thanks I thought this is only a driver bug of Mali-400 series..

Also noticed in your screenshot that this game performance are not good on your phone both OGL and Vulkan 😅

**Comment by Panderner** [comment] 2020-04-24 23:56
Anybody have you tried a GE Dump?

**Comment by Emulatorer** [comment] 2020-04-25 00:01
> Anybody have you tried a GE Dump?

https://github.com/hrydgard/ppsspp/issues/12851#issue-605935192

**Comment by Panderner** [comment] 2020-04-25 00:08
No. Not that comment here's a GE Dump:
[BG3H00252_0001.zip](https://github.com/hrydgard/ppsspp/files/4532053/BG3H00252_0001.zip)

**Comment by Emulatorer** [comment] 2020-04-25 00:14
> No. Not that comment here's a GE Dump:
> [BG3H00252_0001.zip](https://github.com/hrydgard/ppsspp/files/4532053/BG3H00252_0001.zip)

In that comment I already mentioned where's my GE Dump 🙂

**Comment by hrydgard** [comment] 2020-04-25 10:50
On Galaxy S8+ (Mali-G71), the game works correctly at full speed on both OpenGL and Vulkan. 

I don't think this one is really worth bothering with, since it is pretty clearly some sort of driver bug. Closing.

**Closed by hrydgard** 2020-04-25 10:50 UTC
Labels: Confirmed Driver Bug, Mali GPU, OpenGL

**Comment by Panderner** [comment] 2020-04-25 11:04
> On Galaxy S8+ (Mali-G71), the game works correctly at full speed on both OpenGL and Vulkan.
> 
> I don't think this one is really worth bothering with, since it is pretty clearly some sort of driver bug. Closing.

Are you using S8 Exynos? Let me see that bug exists for newer Mali GPUs running GLES 3.x?

**Comment by hrydgard** [comment] 2020-04-25 13:23
Yes, S8 Exynos
