### ISSUE TITLE
save state problem

### ISSUE THREAD

**Issue by revan9112** [hrydgard/ppsspp#11396] opened 2018-09-18 01:05 UTC
I'm testing this emulator **"Version 1.6.3"** with **"kidou_senshi_gundam_-_gundam_vs_gundam_next_plus_japan"** and **"Dante's Inferno"**

When i copy my save state from **Windows 10** or **Android 7.0** or **8.1** to the other platforms the saved state works great. But a saved state created on **Ubuntu 16.04** or **18.04**  appears corrupt on the other 2 platforms, the strange is this **"apparently"** weird saved states works great on **Ubuntu**.

Please forgive my English, is not my native language.

PD: Remember, always attack ideas, never people.

**Comment by unknownbrackets** [comment] 2018-09-18 01:26
Some comments here that would help to investigate:

http://forums.ppsspp.org/showthread.php?tid=24643&pid=132389#pid132389

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-12-01 19:30
Going to close this, as it was determined on the forum that the issue was related to using a newer version of PPSSPP on Linux than the other two platforms.  That's not a bug, because newer save states don't work in older versions.

-[Unknown]

**Closed by unknownbrackets** 2018-12-01 19:30 UTC
