### ISSUE TITLE
Socom fireteam bravo 3 crashing

### ISSUE THREAD

**Issue by zecolher** [hrydgard/ppsspp#11053] opened 2018-05-19 11:34 UTC
### What happens?
Socom fireteam bravo 3 crashes at the end of "stockpile" mission

### What *should* happen?

The game should return to the level select screen

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
 
Android 7.0 phone:Moto G5 ppsspp: 1.5.4

**Comment by unknownbrackets** [comment] 2018-05-26 18:37
This issue is being closed as a duplicate of #10461.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-05-26 18:37 UTC

**Comment by Frost-Wolfe** [comment] 2021-02-14 07:31
It doesn't crash under 0.9.8 version just tested it but Stockpile mission texture bugs and lens flare through wall still there. I got the 0.9.8 PPSSPP version from ppsspp.en.uptodown.com.

**Comment by Frost-Wolfe** [comment] 2021-02-14 07:36
Not sure if sight and link is safe. So I uninstalled for now, but yeah figure I share anyway incase anyone wants to experiment with the emus and game. Good luck.
