### ISSUE TITLE
Textures replacing and saving new textures won't work

### ISSUE THREAD

**Issue by WattanaGaming** [hrydgard/ppsspp#11059] opened 2018-05-21 01:28 UTC
### What happens?
Saving new textures doesn't work at all(Replace & Save new textures enabled)

### What *should* happen?
Textures should be replaced/saved when playing games

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

CPU: Ryzen 3 1200
GPU: GTX1050
RAM: 8GB
OS: Linux mint 18.3 Sylvia 64 bit

**Comment by unknownbrackets** [comment] 2018-05-21 04:09
Are you using Qt or SDL?  Does it not work on both?

I strongly suspect it won't work on Qt, since that uses different png handling.

-[Unknown]

**Comment by WattanaGaming** [comment] 2018-05-21 06:09
Nah I use gtk desktop

**Comment by WattanaGaming** [comment] 2018-05-21 06:31
ok i'll try the sdl version.
Do I have to replace or just install it with the normal ppsspp?

**Comment by WattanaGaming** [comment] 2018-05-21 06:35
![screenshot from 2018-05-21 13-34-34](https://user-images.githubusercontent.com/25323231/40293569-b7d5ae36-5cfb-11e8-9248-0283291aa5de.png)
RIP. the sdl version hangs immediately when i enter a game

**Comment by unknownbrackets** [comment] 2018-05-21 07:08
Hmm, that probably deserves its own issue.  You might want to try the git builds though:

For Ubuntu builds: https://launchpad.net/~ppsspp/+archive/ubuntu/testing
Or various: https://build.ppsspp.org/?page/downloads#linux
Or just compile it manually, it's fairly easy (see the wiki)

We're hopefully gonna release 1.6.0 soon as there have been a lot of improvements since 1.5.4.

-[Unknown]

**Comment by WattanaGaming** [comment] 2018-05-21 08:00
I already using the git build

**Comment by LunaMoo** [comment] 2018-05-21 10:04
Please open new issue for the SDL build problem, closing this as a duplicate of #9259 qt version doesn't have replacement implemented so obviously it doesn't work.

**Closed by LunaMoo** 2018-05-21 10:04 UTC
Labels: Qt

**Comment by WattanaGaming** [comment] 2018-05-21 11:48
I hope so @unknownbrackets 
BTW pls dont forgot to fix the texture issue on linux( mint)
