### ISSUE TITLE
[Feature Request] Windows ARM Builds

### ISSUE THREAD

**Issue by BenNottelling** [hrydgard/ppsspp#11872] opened 2019-03-07 17:48 UTC
Something which would be really nice to see come around would be ARM builds for windows.
I'm not sure if an ARM32 build is possible, but then the emulator could be played on windows NT devices and new ARM64 versions of windows.
Although, an ARM64 build would be ideal for those systems as the VS redists for ARM32 can't be easily installed on these systems. 

One issue with this request is that ARM64 computers only have DirectX support, not openGL or Vulcan.

**Comment by unknownbrackets** [comment] 2019-03-07 18:04
This issue is being closed as a duplicate of #11027.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-03-07 18:04 UTC

**Comment by BenNottelling** [comment] 2019-03-07 20:35
My apologies, was only paying attention to the github "similar issues" thing that pops up.
I have very little knowledge with porting things, VS, and C++ / C#, and I feel like this would be a big project to learn on. I'll see if I can nonethe less, although this broken hand is going to slow me down.

**Comment by hrydgard** [comment] 2019-03-07 20:38
This is likely to be quite straightforward. You'll simply add the architecture to the MSVC project, then try to build and fix any issues that come up. Very likely there will be a few cases where we assume that Windows mean x86, but overall I believe this won't be a huge thing to get running.

**Comment by BenNottelling** [comment] 2019-03-07 20:42
Oh ok! Doesn't sound too bad, one problem though, the only ARM64 device I have that can run windows 10 is a raspberry PI, which doesn't have working GPU drivers. 
Well, they work but only as a render driver, not a display one, not sure how I can test if it works that way.

**Comment by BenNottelling** [comment] 2019-03-12 16:51
When I tried to add ARM64 to the target list the build fails on a windows 8.1 SDK file, re-targeting from within VS does nothing for me, I'm building it with VS 2016
