### ISSUE TITLE
Gods Eater Burst random crashes

### ISSUE THREAD

**Issue by Trokinos** [hrydgard/ppsspp#8205] opened 2015-11-12 23:41 UTC
Using 1.1.1-273-g419ea84 on winXP ( win32 ) , european version of GEB

While GEB has always crashed randomly, fortunately very rarely, on PPSSPP in the past when i was playing it, as i am currently playing a new character , and so all the missions from scratch , i ran into a few crashes again (PPSSPP has encountered an error ...) but maybe it's my memory that betray me (as it has been a long while i didn't played the game), but it seems to me i encounter those crashes a bit more often now (though fortunately still rarely).

The problem with that report is that i can't reproduce them, i regularly make save states (always in case it crashes) but every single time i encounter a crash and replay from the saved state ... it does not crash.
I can play half a dozen of missions in a sitting or a lot more in multiple sitting without encountering any kind of crash too.

 when it crashes it happens always during an action , either i am hitting a monster or a monster is hitting myself. Could be related to a sound, i don't know, but as said this is impossible to reproduce as even if replaying a mission that crashed in the same condition (same allies , same equipment, etc...) the heavy majority of the time i play it will not crash.

Anyways, the last entries i see in the console when PPSSPP crashed in case it can help
http://i.imgur.com/C6yswYq.gif
There are a very lot of similar entries for the whole console.

Now if i look around where i created my last save state during that mission i noticed some message in red that may or may not be part of what's ultimately kill PPSSPP process
http://i.imgur.com/wCzW6VH.gif

And obviously, and what makes it hard to understand what is the problem, when i load the game from my saved state, as said before, i can complete the mission without a single problem.

edit : the atrac messages happen even during normal gameplay (i mean even when it does not crash)

**Comment by sum2012** [comment] 2015-11-13 11:48
Does it also happen in older version such as v1.1.1 formal edition ?

**Comment by vsub** [comment] 2015-11-13 17:02
I don't know if this will help in any way but I also encounter such problems long time ago when I played the game
http://forums.ppsspp.org/showthread.php?tid=1552&pid=81022#pid81022

**Comment by unknownbrackets** [comment] 2015-11-13 18:11
Does it _ever_ happen after loading a savestate - even if it doesn't happen every time you load a savestate?  Or is it something that e.g. happens after X amount of time since loading a savestate, on average (feeling is fine, not looking for hard science here)?

-[Unknown]

**Comment by Trokinos** [comment] 2015-11-15 15:22
I don't think it's due to loading a state becuase i only reload a save state when i crash in GEB.
And i don't think it's related to saving a state either as i usually do so regularly and can play dozen of missions without a problem.

It "feels" very random as i said i can replay a same mission multiple time without crashing, or just crash while playing that same after starting the game, or later.

I observed the crashes from much before 1.1.1 so i don't think it's related to a new change.
Now if only i could find a way to reproduce them , but they seem to be really random (though only thing i noticed is that it happen when i hit or i am hit, never had a crash when running around)

**Comment by Trokinos** [comment] 2015-11-28 20:36
I made a lot more test as i played a lot of mission and found out that unlike what i seemed to see, the fact you either save a state or load a state seems to improve a very lot the chance of that crash.

But oddly it does not happen everytime i save a state or load one, especially if i load a state after a crash -> relaunch PPSSPP -> relaunch of GEB but if i save the state or load a state at +/- mid battle, there are rather high chances a crash will happen a dozen of seconds later when i am hit or when i hit a monster.

It does not seem to happen if i only save a state at the beginning of a mission, but happen often if i do at +/- mid battle.

**Comment by unknownbrackets** [comment] 2016-01-28 03:56
I think it's very likely that #8471 (which was around a long time) was the cause here.  @daniel229 posted a very reliable way to reproduce that in #8459 - so if I'm right, he's the one to thank for the fix.

That bug has been there for as long as PPSSPP has supported savestates, and would definitely cause the behavior you describe above - an increased likelyhood of a crash whenever using save OR load state.

Based on recent comments in #5843, I'm going to close this.  If we start seeing crashes again, we can reopen.

-[Unknown]

**Closed by unknownbrackets** 2016-01-28 03:56 UTC

**Comment by Jinzombie** [comment] 2018-04-21 13:54
Still randomly crash in the latest build 1.5.4-924
Mali-450 GPU
2GB RAM
Octacore
