### ISSUE TITLE
Yu-Gi-Oh! GX Tag Force 2: Cut-off card

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8518] opened 2016-01-28 02:47 UTC
**System:** Windows 7 (x64)
**Version:** `PPSSPP 1.1.1` and above (testet until `1.1.1-709`)
**Renderer:** OpenGL and Direct3D9
**Problem:** Inside a duel, the card is cut off.

**PSP:**
![psp](https://cloud.githubusercontent.com/assets/7157389/12633321/01b22018-c571-11e5-95fe-d3c219b348f4.png)

**PPSSPP (Buffered rendering):**
![ppsspp1](https://cloud.githubusercontent.com/assets/7157389/12633329/111f36da-c571-11e5-906f-ec700ed6c7de.png)

Tested all settings, even 1x PSP, but it won't scale correctly.

**Comment by unknownbrackets** [comment] 2016-01-28 04:18
Closing this as a duplicate of #7124.

It's been happening for a while, and seems like it might be some sort of viewport issue.  But we still haven't figured out the exact cause.

It would really help to have a "story" of what the game does to draw this card.  I don't have the game myself, but it's clear that drawing this card goes through several different steps - it first draws the card to a buffer, and it seems like it gets cropped at that point.

If you want to give a shot and figuring out what it's doing, there's some instructions here - 
https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

If so, though, please post them in #7124 - it helps to have all the info in one place.

-[Unknown]

**Closed by unknownbrackets** 2016-01-28 04:18 UTC
