### ISSUE TITLE
Not able to Access Homebrew Menu - Need Home/PS Button

### ISSUE THREAD

**Issue by Smoker1** [hrydgard/ppsspp#8724] opened 2016-05-08 03:12 UTC
When running PPSSPP and you run a Homebrew Emulator, some of those Emulators require a Home Button or PS Button in order to Access that Emu's Menu/Settings in order to get things like Screen Settings Changed or need to reset the Button Mappings because they wont work right even though on a normal PSP, it works the way you set them.

**Comment by unknownbrackets** [comment] 2016-05-08 04:18
This issue is being closed as a duplicate of #6646.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-05-08 04:18 UTC
