### ISSUE TITLE
[Linux] Full screen is bugged

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#13050] opened 2020-06-23 19:03 UTC
What happens?
When toggling full screen, 3 differents windows pop up over each(windows of ppssppsdl) and it  locks up. Meaning I can't do anything else I restart my machine

### What *should* happen?
Full screen

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
intel i7 series with intel UHD 620 and 8gb ram Ubuntu 20.04

**Comment by hrydgard** [comment] 2020-06-23 19:09
Vulkan or OpenGL?

**Comment by InfamousKnight** [comment] 2020-06-23 19:36
Vulkan

**Comment by InfamousKnight** [comment] 2020-06-23 19:40
And one of the others things that happen, once full screen is toggled and on restart, it will have a maximized window(not full screen) saying initializing vulkan as the title. And doesn't go any further

**Comment by hrydgard** [comment] 2020-06-23 19:48
So I just kind of got this working on my own laptop with 620, in just the last few changes. Did you try to make a fresh build from the latest master?

**Comment by InfamousKnight** [comment] 2020-06-23 20:34
It works with opengl, but not vulkan on my end. I don't know. I'll test
more later. I recall it worked once, but don't remember what I did.

**Comment by hrydgard** [comment] 2020-06-23 21:52
Yeah just wanting to clarify whether you really are using a super fresh master build because the fixes are very recent....

**Comment by InfamousKnight** [comment] 2020-06-24 02:14
I think I found the issue:
https://launchpad.net/~ppsspp/+archive/ubuntu/testing oesn't seem to
support ubuntu 20.04 It says in the ppsspp header 1.7.0 with some link on
the bottom suggesting a new version. But mine doesn't look to be supported
yet.

**Comment by hrydgard** [comment] 2020-06-25 06:54
Ah, it seems that PPA is not being updated... 

Well, not a bug in PPSSPP then, just an old version. Closing - you'll need to find a newer build.

I hope to get official linux builds up and running again at some point, until then you'll need to build your own.

**Closed** 2020-06-25 06:54 UTC
Labels: Platform-specific (Linux/POSIX)
