### ISSUE TITLE
Resistance Retribution online

### ISSUE THREAD

**Issue by TigasZ8** [hrydgard/ppsspp#14425] opened 2021-05-02 01:10 UTC
Hello, Resistance Retribution is still very unstable, even using VPN, (without VPN most of them can't even find a match) and even with VPN there is still an error when trying to join a match for some players, we were switching between hosts and the  final result has always been identical, any possible correction related to the game to try to improve the current situation?

**Comment by MojoJojoDojo** [comment] 2021-05-02 04:50
@TigasZ8 you already got an issue here : https://github.com/hrydgard/ppsspp/issues/14316
Not need for 2 issues lol.

**Comment by Gamemulatorer** [comment] 2021-05-02 06:08
Duplicate of #14316

**Closed** 2021-05-02 06:44 UTC
