### ISSUE TITLE
Is the JIT working now for 64bit devices? (iPhone X)?

### ISSUE THREAD

**Issue by zeq2mapper** [hrydgard/ppsspp#10523] opened 2018-01-11 14:46 UTC
I was looking through the issues here and it was apparently fixed. Is there a way you guys can show me how to load the files and make a project out of it and compile it and build it (without debug) mode with Xcode? Thanks a lot

**Comment by XTutorials** [comment] 2018-01-11 19:12
JIT isn't yet working still. The app crashes when trying to run a game. Tested on my iPhone 7.

**Comment by unknownbrackets** [comment] 2018-01-11 19:52
This issue is being closed as a duplicate of #10399.  It does actually work, but there's a problem with the build server.

For building yourself, see #10509.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-01-11 19:52 UTC
