### ISSUE TITLE
Can't type in uppercase letters when prompted with keyboard.

### ISSUE THREAD

**Issue by mrwallace888** [hrydgard/ppsspp#15463] opened 2022-04-01 01:31 UTC
### Game or games this happens in

None

### What area of the game / PPSSPP

I noticed this with one game but then I needed it for Ridge Racer 2 and it was the same thing. The PPSSPP keyboard comes up so I can type my name but I noticed that I can't type uppercase letters. It forces me to use lowercase. None of the buttons do anything.

### What should happen

I don't know. All I can think of is that I'm missing a binding somewhere but I didn't see a binding anywhere in the PPSSPP control config regarding typing in uppercase.

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1660 Ti

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-04-02 14:44
This issue is being closed as a duplicate of #15010.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-04-02 14:44 UTC
Labels: HLE/Kernel, User Interface
