### ISSUE TITLE
Ui glitch

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#10373] opened 2017-12-08 05:36 UTC
On latest version the ui glitch reappear using vulkan api.

Ppsspp version 1.5.4 built 33
Samsung s7 edge exynos
Mali t880-mp12
Gpu driver openGL ES 3.2 v1 r12p1 03dev0.228
Vulkan v1.0.11

**Comment by unknownbrackets** [comment] 2017-12-09 18:46
Can you post a screenshot?  It may seem like a horrible and obvious glitch to you, but maybe no one else has noticed it, or maybe not everyone is getting the glitch.

What area of the UI?  This is not in a game, right?

-[Unknown]

**Comment by oli0371** [comment] 2017-12-10 05:18
It's not in game, for example when i scroll in graphics setting this happen, on some older version i got this issue then the issue was solved but with all latest version after build 23 this issue reappear and with screenshot all with appear good because only when scroll i got ui glitch

**Comment by M220** [comment] 2017-12-10 13:41
Yeah i have that bug too
@unknownbrackets 
I tried to take a video from bug but a very strange thing happened!
When you record video , bug is there but when you watch that video , video doesn't show that bug!
But if i have to describe it : 
- Bug is Android only
- Bug is only happening when your renderer is set to Vulkan
- Bug is something like tearing in video games but so much worse! ( in games it's happening fewer but with this bug , it's like tearing is happening every moment when you scrolling in settings or when you want select a game to run or... UI related works like that ) Like , Emulator can't sync Frames in the UI ( in games it's good and okay ) 
- Bug isn't in 1.5.4-30- build but it's in 1.5.4-33- and later So it's something between this commits ( related to NDK 16 )
Hope details was detailed enough and can help you solve the bug!
Love you guys :D♡

**Comment by hrydgard** [comment] 2017-12-10 13:59
I've seen it too, on Mali only, in much earlier versions. I'm hoping it has something to do with my last couple of commits, so please try 1.5.4-60 when it's done.

**Comment by oli0371** [comment] 2017-12-10 14:45
I update my mali gpu driver to r12p1 and issue gone

**Comment by oli0371** [comment] 2017-12-10 14:46
Sorry correction i change kernel and issue gone

**Comment by oli0371** [comment] 2017-12-10 14:50
Sorry for spam but the issue reappear when i restart ppsspp

**Comment by hrydgard** [comment] 2017-12-10 15:49
1.5.4-60?

**Comment by M220** [comment] 2017-12-10 16:20
Unlucky not fixed with 1.5.4-60 :(
Whatever the problem is , it is between 1.5.4-30- and 1.5.4-33- maybe a review can show where is the bug?

**Comment by M220** [comment] 2017-12-10 16:26
@hrydgard 
Don't expect much from ARM to Update their Drivers , their toooo lazy to fix Terrible bugs of their drivers and update them
I still Can't understand how you developed this emulator that can Emulate almost Every PSP Games With 60 FPS in ARM Devices!!!

**Comment by hrydgard** [comment] 2017-12-10 19:05
It was a ton of work, I can tell you that :) Once you tame Vulkan it really delivers on speed, but it's so new that drivers are still pretty buggy, leading to stuff like this..

**Comment by oli0371** [comment] 2017-12-14 17:19
Rip glitch issue is stil here on build 111 😭😭😭

**Comment by M220** [comment] 2017-12-15 16:03
Bad news :(
Now this issue can be seen ingame!
Test version : 1.5.4-113-
Galaxy S6
Mali

**Comment by oli0371** [comment] 2017-12-16 02:17
I got that too and i revert back to build 23 where all works

**Comment by unknownbrackets** [comment] 2017-12-17 02:22
Which build is the first build where it started appearing in game?

-[Unknown]

**Comment by M220** [comment] 2017-12-20 14:26
Issue is fixed thanks to latest commits! Both ingame and in menu!!! REALLY , NICE WORK GUYS!
This issue can be closed now :D 
Tested Version : 1.5.4-126- and 1.5.4-120-

**Comment by unknownbrackets** [comment] 2017-12-20 15:12
Interesting.  Does this mean that updating the Vulkan headers helped maybe?

-[Unknown]

**Comment by M220** [comment] 2017-12-20 15:25
Seems so.
cause this bug was only existed in vulkan renderer and not OpenGL renderer :)

**Comment by hrydgard** [comment] 2017-12-20 15:36
Weird. I dunno, for me, this bug seemed to come and go, it might appear the next time you reboot your device.. Haven't seen it in a while though... maybe it is actually fixed.

**Comment by M220** [comment] 2017-12-20 16:41
Just restarted my phone and still no issue ( no screenor ingame tearing and flickering )
In my opinion, bug is fixed for now :)

**Comment by hrydgard** [comment] 2017-12-20 21:26
Let's reopen if it reappears.

**Closed by hrydgard** 2017-12-20 21:26 UTC
Labels: Vulkan
