### ISSUE TITLE
"Record display" produces video with flickering/missing elements

### ISSUE THREAD

**Issue by boringhexi** [hrydgard/ppsspp#12067] opened 2019-05-27 15:01 UTC
### What happens?
Affected games include:
* Gitaroo Man Lives! [Korea, possibly other regions are affected too] (ULKS46071)
* Neverland Card Battles [USA demo] (NPUH90021 / ULUS10382)

In some games, the video output in the emulator window looks just fine, but using "Record display" results in a video file with flickering or missing 2D elements, such as characters sprites and the HUD.

Example video: https://youtu.be/f_wlpdi3ycA

(Given that other people have reported video recording issues with games running at 30 fps, I should note that Gitaroo Man Lives! runs at 30 fps and Neverland Card Battles runs at 60 fps.)

### What *should* happen?
The recorded video should match what is displayed in the emulator window, without flickering or missing elements.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
GPU: Intel HD Graphics 3000 (note: enabling Software rendering did not fix the issue)
Operating system: Windows 10 Pro (Version 1803 OS Build 17134.472)
PPSSPP version: 1.8.0-237-gd0d8ea3fb (Windows buildbot build)
Rendering backend: Direct3D 11

**Comment by LunaMoo** [comment] 2019-05-27 18:21
Closing as a duplicate of #10632, please DON'T open duplicate issues, it will make things slower to solve, not faster.

**Closed by LunaMoo** 2019-05-27 18:21 UTC
