### ISSUE TITLE
Problem with PS3 controller on iOS

### ISSUE THREAD

**Issue by Fadi5555** [hrydgard/ppsspp#7694] opened 2015-04-17 23:20 UTC
Hi @hrydgard.

Actually I facing a problem with PS3 controller when I play it with ppsspp.
Everything works just fine except two bottoms from right analog stick are left and down. Actually is not 
working at all. However, it works very well on retroarch.

This is a simple image for which bottoms not working 
![image](https://cloud.githubusercontent.com/assets/10546081/7212541/6e218b3e-e571-11e4-93d3-2179658bff45.jpg)

Please can you give a fix for this problem.

**Comment by pralima87** [comment] 2015-04-20 01:31
This is a old bug that no one is fixing :/..
This is happening since iOS 8.

**Comment by Fadi5555** [comment] 2015-04-20 01:49
Your are completely right.
I facing this problem for long time since I updated my iOS to 8.

Ppsspp is updated daily why they don't fixing this small bug.

We are here for sharing knowledge and report for issues to fix it.
To make the project more stable and useful for all.

**Comment by unknownbrackets** [comment] 2015-04-20 01:53
As long as the people who have iOS devices and care about this aren't the same people contributing to ppsspp, maybe it'll never be fixed.  I use an Android device and don't have anything to reproduce this problem.

Sounds like it broke in iOS 8, maybe it's an iOS 8 bug?  I have no way to tell, after all.

Please feel free to debug the problem and submit a fix.

Also, sounds like this is a duplicate.  I'm going to close it, but if you want to be even more sure this problem is never solved, try creating more duplicates.  By spreading out the information and annoying us, you'll be able to ensure that we never fix it no matter what.  Good luck.

-[Unknown]

**Closed by unknownbrackets** 2015-04-20 01:53 UTC
