### ISSUE TITLE
Some character fail to display (Gundam vs Gundam Next Plus)

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#13510] opened 2020-10-05 13:39 UTC
I convert sarasa-mono-slab-sc-regular.ttf to jpn0.pgf, then replace the default  jpn0.pgf(Microsoft YaHei Regular) in ppsspp.
It can be displayed. 

replace before
![QQ截图20201005183142](https://user-images.githubusercontent.com/5364709/95086865-90ec0900-0753-11eb-9656-3b31b9824cbc.png)
![QQ截图20201005183244](https://user-images.githubusercontent.com/5364709/95086922-a2351580-0753-11eb-9237-2f18e3d7808b.png)
![QQ截图20201005183330](https://user-images.githubusercontent.com/5364709/95086934-a7926000-0753-11eb-84fc-23002a498139.png)
![QQ截图20201005183408](https://user-images.githubusercontent.com/5364709/95086947-abbe7d80-0753-11eb-8472-39e9c40c0dbf.png)
![QQ截图20201005183520](https://user-images.githubusercontent.com/5364709/95086965-b11bc800-0753-11eb-8af0-733a78cfa030.png)

replace after
![QQ截图20201005212635](https://user-images.githubusercontent.com/5364709/95087025-c264d480-0753-11eb-8c68-5cdac3fccd33.png)
![QQ截图20201005212725](https://user-images.githubusercontent.com/5364709/95087034-c55fc500-0753-11eb-8eda-df28e7c73dff.png)
![QQ截图20201005212800](https://user-images.githubusercontent.com/5364709/95087042-c7c21f00-0753-11eb-94d4-6febe491eb10.png)
![QQ截图20201005212830](https://user-images.githubusercontent.com/5364709/95087052-ca247900-0753-11eb-8ab2-23fda353bccd.png)
![QQ截图20201005212908](https://user-images.githubusercontent.com/5364709/95087065-cd1f6980-0753-11eb-9cba-513634aaa60e.png)

Here is the font file. 
[jpn0.zip](https://github.com/hrydgard/ppsspp/files/5327744/jpn0.zip)

**Comment by hrydgard** [comment] 2020-10-05 13:43
did you mean to post screenshot?

**Comment by leoxxx** [comment] 2020-10-05 13:56
Yes. Have some network error. The pictures and font upload later.

**Comment by Panderner** [comment] 2020-10-05 14:16
@leoxxx what game are you using?

**Comment by leoxxx** [comment] 2020-10-05 14:44
@Panderner
You can see the game in the picture title.

**Comment by leoxxx** [comment] 2020-10-05 14:58
Microsoft YaHei is copyright font. I think jpn0.pgf change to a free font is better.

**Comment by nassau-tk** [comment] 2020-10-06 07:57
**[Real PSP Font]** for Reference.
![GvsGPlus](https://user-images.githubusercontent.com/48179091/95174290-d90f3800-07f4-11eb-8644-5cc1bf08e34f.png)

**Comment by nassau-tk** [comment] 2020-10-09 17:07
@hrydgard 

Please,tell me about Japanese font on of PPSSPP.
Question : Why useing Microsoft YaHei Regular font? Why you don't useing some Japanese license free Gothic  font?

If your reason is correspondence for "Chinese" then I can understand to useing "Microsoft YaHei Regular".
Because,"Microsoft YaHei Regular" is Simplified "Chinese" font.
"Microsoft YaHei Regular" is a little strange looks for japanese.

But,if it's not reason and you want find more good Japanese font then I recomend a [Ume-font](https://ja.osdn.net/projects/ume-font/wiki/FrontPage#h2-Licence).
This font support between "JIS level-1 kanji set" to "JIS level-4 kanji set".
PSP needs "JIS level-1 kanji set".
So,It's no problem.

Ume-font is free license for buisiness and private use.
And,The license accept any change as you like.
But,No warranty.  : )

And,I tested convert the ttf to pgf by "[ttf2pgfJ](http://www.mediafire.com/file/xvgvnzt24jl/ttf2pgfJ_v0.20jpVer-2.zip/file)".
I tested "[ume-pgs5.ttf](https://ja.osdn.net/projects/ume-font/releases/)".
Setting: Size18/With Shadow change/ No Bold/No Italic
Maybe It's good looking.

It couldn't be said that everything was perfect, but the movement of the following game was confirmed.
GUNDAM vs GUNDAM NEXT PLUS
![GvsGPlus_UmeFont_tgs5](https://user-images.githubusercontent.com/48179091/95610626-915e0a00-0a9b-11eb-98dc-2cd443fe7a3a.png)

And,No problem for copyright.
[jpn0_ume-pgs5.zip](https://github.com/hrydgard/ppsspp/files/5356432/jpn0_ume-pgs5.zip)

For reference!

**Comment by hrydgard** [comment] 2020-10-09 17:09
Nice. I see no reason not to switch to that, I think I will do that. I haven't done any work in this area because I don't know Japanese so it's very hard for me to tell if something is working or is drawing the wrong characters or if it looks wrong...

**Comment by hrydgard** [comment] 2020-10-09 17:33
Fonts are actually really special when it comes to licensing - if you render out a single or a few sizes of a fonts to bitmaps, as in a PSP fonts, it's actually okay to distribute that. You just can't distribute the original TTF file. 

However, of course, free fonts are best, so this is good.

**Comment by nassau-tk** [comment] 2020-10-09 17:44
OK! I understood it.
★and☆ is not appear.
Because,this font is not include "like emoji characters".
But,Maybe become a good more than before.

If I find more good font then I propose it!

**Comment by nassau-tk** [comment] 2020-10-09 18:08
@hrydgard 

Oh,Sorry.
It'll be right away and I'm sorry, but change in the kind of fonts is proposed.

Same,Ume-font.
But,Other-type.
Because,The proposed font type is not appear the  **" ( "**  correctly.
So,I will repropose below.

[jpn0jpn0_ume-hgo5.zip](https://github.com/hrydgard/ppsspp/files/5356789/jpn0jpn0_ume-hgo5.zip)

Sorry!!

**Comment by hrydgard** [comment] 2020-10-10 13:16
So, how's it now? Can we close this?

**Closed** 2020-10-10 13:35 UTC
Labels: PGF / sceFont
