### ISSUE TITLE
After Burner Black Falcon USA Black Screen after Opening

### ISSUE THREAD

**Issue by tabnk** [hrydgard/ppsspp#7551] opened 2015-03-03 05:06 UTC
ON Latest ppsspp-v1.0.1-97-g3e1e8f1-windows-amd64

Buffering Mode is ON and all default setting.

**Comment by daniel229** [comment] 2015-03-03 05:49
duplicate of https://github.com/hrydgard/ppsspp/issues/6794

**Closed** 2015-03-03 06:04 UTC
