### ISSUE TITLE
Lego Harry Potter years 5-7 slow down

### ISSUE THREAD

**Issue by andy0232** [hrydgard/ppsspp#12996] opened 2020-06-03 13:10 UTC
Everything in the game so far is fine,up until year 4 chapter 4, I have tested every level before it when i found out,but it is still the same.The first level in year 4 chapter 4 has a slowdown where it is going from 30fps to 19fps and it is slower than it should be.It still should be at the playable 30fps with no slowdowns.Every level before this is fine,I tested them just in case it was thermal throttling, it isn't. I am using a Samsung Galaxy S6, most games run fine.

**Comment by hrydgard** [comment] 2020-06-03 14:14
For this kind of late-game thing, a savegame could be helpful.

**Comment by andy0232** [comment] 2020-06-03 14:39
How do i savegame, you mean like send it to here?

**Comment by andy0232** [comment] 2020-06-03 15:12
https://drive.google.com/file/d/1QMgP_4Obop9YRFlJkm_A9NYnzKWdOA_y/view?usp=drivesdk

**Comment by andy0232** [comment] 2020-06-03 15:12
Thats in the save data files? Can I just send a video recording?

**Comment by andy0232** [comment] 2020-06-03 15:21
https://drive.google.com/file/d/1EIxb2WYK7o3PsI4BZrv2kzPmUFMCrbZD/view?usp=drivesdk para filw

**Comment by fahadrashid7705** [comment] 2020-06-03 17:21
Plz link share turn on

**Comment by andy0232** [comment] 2020-06-03 21:04
Alr....


https://drive.google.com/file/d/10oS_vFEPDfmVi4YhZ6_a9JcigBzSt1DH/view?usp=drivesdk

**Comment by andy0232** [comment] 2020-06-03 21:04
Full zip of file is above^

**Comment by Gamemulatorer** [comment] 2020-06-04 02:26
> Full zip of file is above^

@andy0232 hey :/
![_20200604_102559](https://user-images.githubusercontent.com/37603562/83707993-e1404680-a64d-11ea-9786-c948b0f43d4f.JPG)

**Comment by andy0232** [comment] 2020-06-04 02:38
How not make it do that

**Comment by Gamemulatorer** [comment] 2020-06-04 02:53
> How not make it do that

I request a permission access please accept it.

**Comment by jcchikikomori** [comment] 2020-06-04 04:47
> > Full zip of file is above^
> 
> @andy0232 hey :/
> ![_20200604_102559](https://user-images.githubusercontent.com/37603562/83707993-e1404680-a64d-11ea-9786-c948b0f43d4f.JPG)

Please set a shareable link on your Drive console

https://support.google.com/drive/answer/2494822

**Comment by fahadrashid7705** [comment] 2020-06-04 06:39
plz upload in drobbox

**Comment by andy0232** [comment] 2020-06-04 13:19
https://www.dropbox.com/s/idnqzws03s78kj0/Lego%20HP%205-7.zip?dl=0

**Comment by andy0232** [comment] 2020-06-04 13:21
Gamemulator has access, let me know if anyone has trouble with the Dropbox link

**Comment by hrydgard** [comment] 2020-06-04 13:22
You can just drag zip files into github posts, as long as they are not too large.

**Comment by andy0232** [comment] 2020-06-04 13:33
I actually am unable to move it as I am on an android phone and my files app won't let me move it to anything but my internal storage(its already there) or my google drive

**Comment by andy0232** [comment] 2020-06-04 13:40
[Lego HP 5-7.zip](https://github.com/hrydgard/ppsspp/files/4730385/Lego.HP.5-7.zip)

**Comment by andy0232** [comment] 2020-06-05 21:56
Anything?

**Comment by Gamemulatorer** [comment] 2020-06-06 04:16
> Anything?

Could you create a frame dump.? Doesn't matter if the frame dump is created on PC or Android.

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by andy0232** [comment] 2020-06-06 17:35
@Gamemulatorer ,I did the instructions and everytime I press record on the site and go back to psp the screen freezes

**Comment by andy0232** [comment] 2020-06-06 17:40
Yea, the file is not supported

**Comment by Gamemulatorer** [comment] 2020-06-07 01:52
> @Gamemulatorer ,I did the instructions and everytime I press record on the site and go back to psp the screen freezes

@unknownbrackets can only answer that.

**Comment by Panderner** [comment] 2020-11-29 11:28
@andy0232 what device are you using?

**Comment by andy0232** [comment] 2020-11-30 13:21
I use a samsung galaxy s6, but I have gotten other high graphic games
running perfectly, and it only seems to be that part

**Comment by unknownbrackets** [comment] 2021-01-19 05:49
It's likely using a new effect in this area.  We might've improved the performance in the latest git builds, though, so I recommend trying a recent git build from https://buildbot.orphis.net/ppsspp/.

Depending on your device's battery saving settings, using the debugger to create a GE frame dump on the same device may not work.  In that case, if you can use a laptop, tablet, desktop, or other device on the same network it should be able to capture the frame dump.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-08-23 09:53
This game is lag on the main menu savedata selection.
OPENGL
![Screenshot_2021-08-23-17-51-45-082_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130427863-5808fb5c-77f4-4d5c-bee2-68d24c87fd78.jpg)

[legohp5-7years.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7030932/legohp5-7years.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2021-08-23 10:00
> Everything in the game so far is fine,up until year 4 chapter 4, I have tested every level before it when i found out,but it is still the same.The first level in year 4 chapter 4 has a slowdown where it is going from 30fps to 19fps and it is slower than it should be.It still should be at the playable 30fps with no slowdowns.Every level before this is fine,I tested them just in case it was thermal throttling, it isn't. I am using a Samsung Galaxy S6, most games run fine.

@andy0232 using your savedata no framedrops on my phone both ogl and vk
![Screenshot_2021-08-23-17-58-47-955_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130428755-8060f0bf-31cd-4870-9bad-21a0e2055f13.jpg)
ppssspp latest build from buildbot.

**Comment by unknownbrackets** [comment] 2021-08-29 02:21
> This game is lag on the main menu savedata selection.

The frame dump doesn't indicate any particularly tricky graphics rendering.  If you use "show debug statistics", it may help to show what this says is taking the most time - maybe it's something on the CPU.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-08-29 03:39
> 
> The frame dump doesn't indicate any particularly tricky graphics rendering. If you use "show debug statistics", it may help to show what this says is taking the most time - maybe it's something on the CPU.
> 
> -[Unknown]

Here we go 
![Screenshot_2021-08-29-11-38-07-684_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131237492-1d1a95a6-ee23-4e02-81dc-0ce994041988.jpg)

**Comment by Panderner** [comment] 2021-08-29 05:17
Hmm strange I seen Gamemulatorer's screenshot got 30 fps with 50% speed I got 30 fps 100% speed for me.
![Screenshot_2021-08-29-13-14-24-876_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/131239365-e91cd32d-7b81-4d39-8618-89d1f88649cb.jpg)
I got some slowdowns in the first level of year 5 chapter 4 so i had to drop to 3x resolution.

**Comment by Gamemulatorer** [comment] 2021-08-29 05:35
> Hmm strange I seen Gamemulatorer's screenshot got 30 fps with 50% speed I got 30 fps 100% speed for me.
> ![Screenshot_2021-08-29-13-14-24-876_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/131239365-e91cd32d-7b81-4d39-8618-89d1f88649cb.jpg)
> I got some slowdowns in the first level of year 5 chapter 4 so i had to drop to 3x resolution.

Maybe because my game savedata is located to external storage and my phone is android 11 unlike your's?🤔

**Comment by Panderner** [comment] 2021-08-29 05:37
> > Hmm strange I seen Gamemulatorer's screenshot got 30 fps with 50% speed I got 30 fps 100% speed for me.
> > ![Screenshot_2021-08-29-13-14-24-876_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/131239365-e91cd32d-7b81-4d39-8618-89d1f88649cb.jpg)
> > I got some slowdowns in the first level of year 5 chapter 4 so i had to drop to 3x resolution.
> 
> Maybe because my game savedata is located to external storage and my phone is android 11 unlike your's?🤔

Please check your game save folder.

**Comment by Gamemulatorer** [comment] 2021-08-29 05:53
My game and savedata are both located to my external sdcard.

**Comment by Panderner** [comment] 2021-08-29 05:55
@Gamemulatorer can you move the savedata to internal storage?

**Comment by Gamemulatorer** [comment] 2021-08-29 06:22
> > The frame dump doesn't indicate any particularly tricky graphics rendering. If you use "show debug statistics", it may help to show what this says is taking the most time - maybe it's something on the CPU.
> > -[Unknown]
> 
> Here we go
> ![Screenshot_2021-08-29-11-38-07-684_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131237492-1d1a95a6-ee23-4e02-81dc-0ce994041988.jpg)

I will wait for unknownbrackets answer about this.

**Comment by unknownbrackets** [comment] 2021-08-29 06:44
Well, 1.61ms isn't that bad.  It's interesting that savedata is the slowest thing, though, so it may be related to storage indeed.

That said, if it doesn't really get slower than 1.61ms, it seems like it'd have to be something on another thread.  Maybe this screen is a bit sluggish even on real PSPs?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-08-29 07:38
No change I already move my iso and savedata to my phone internal storage.
![Screenshot_2021-08-29-15-36-02-320_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131242581-806ba6a5-b1f2-49ad-91a1-7f7140ced891.jpg)
[logcat_08-29-2021_15-36-59.txt](https://github.com/hrydgard/ppsspp/files/7072088/logcat_08-29-2021_15-36-59.txt)

**Comment by Gamemulatorer** [comment] 2021-08-29 08:02
PPSSPP Gold v1.11.3 no lag issue
![Screenshot_2021-08-29-16-01-39-942_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/131243275-0608bb96-902f-4be5-8675-e6b96fb38b5f.jpg)

**Comment by Gamemulatorer** [comment] 2021-09-09 17:26
It's ok now after updating my ppsspp to latest git 🤔
![Screenshot_2021-09-10-01-26-20-308_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132733561-3595c3ce-7656-4510-a703-751ff193e42e.jpg)

**Comment by benderscruffy** [comment] 2022-12-07 01:37
please close as this looks fixed

**Comment by unknownbrackets** [comment] 2022-12-07 04:46
Okay, closing, assuming this was fixed at some point (the initially reported performance, since it didn't reproduce later on another phone.)

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2022-12-07 04:46 UTC
Labels: Performance
