### ISSUE TITLE
Final Fantasy Type 0 - English Version - Cutscenes Issue

### ISSUE THREAD

**Issue by t3rr41n** [hrydgard/ppsspp#14980] opened 2021-10-07 10:49 UTC
### What happens?
Some cutscenes won't play, but still skip able. In rare cases the cutscenes play, but stop in the middle.

### What *should* happen?
The cutscenes play normally

#### Which game or games?

Final Fantasy Type 0 - NPJH50443

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-10-07 11:27
Can you find any parts of cutscenes?

**Comment by t3rr41n** [comment] 2021-10-07 23:30
I didn't try the original japanese version yet (2 separate version). I didn't speak Japanese too 😜

**Comment by unknownbrackets** [comment] 2021-10-08 03:00
Actually, CSO ought to theoretically solve the problem, if the file offset is the issue.  All of the CSO code handles uncompressed content > 2 GB fine, regardless of platform (but there still might be issues if the CSO itself is > 2 GB.)

What's the CRC of the patched disc?  Maybe something is wrong with your ISO.

-[Unknown]

**Comment by t3rr41n** [comment] 2021-10-08 04:28
> > The original size of the combined.iso was 2.2GB, but i already converted it to .cso and the size was 1.7GB, but the issue still persists
> 
> As expected since CSO is just a container, it still stores original unmodified game files and they are over 2gb, causing the problem on ancient android. You'd have to de-combine that patched game into two separate containers under 2gb, compression will not help.

Any tools suggestions to split the .iso ?,because i never found a tool to split the .iso

**Comment by t3rr41n** [comment] 2021-10-08 04:29
> I cannot reproduce this issue on my ancient phone android 5.1 lollipop 2gb of ram w/ mali-450 gpu.

When you play the game, did the first cutscenes play, or just black screen ?

**Comment by t3rr41n** [comment] 2021-10-08 04:33
> It could be that Android 5 doesn't make those file offsets 64 bit? This might be an issue only for older Android devices.
> 
> -[Unknown]

Oh, and i already tried the game on 3 different device, on 3 different android (All use the same .iso). The issue still persists

I already tried on Android : 4.2.2 Jelly bean, 4.4 Kitkat, 6.0 marshmallow

**Comment by Gamemulatorer** [comment] 2021-10-08 04:46
> > It could be that Android 5 doesn't make those file offsets 64 bit? This might be an issue only for older Android devices.
> > -[Unknown]
> 
> Oh, and i already tried the game on 3 different device, on 3 different android (All use the same .iso). The issue still persists
> 
> I already tried on Android : 4.2.2 Jelly bean, 4.4 Kitkat, 6.0 marshmallow

Because your iso is corrupted even if you try it on a different devices.

**Comment by t3rr41n** [comment] 2021-10-09 08:02
Yes, the website where i downloaded the .iso file state the CRC32 was bcf60901

Probably my CRC check fail because i converted it to .cso

**Comment by t3rr41n** [comment] 2021-10-09 08:03
I will try again to download another .iso and see did the issue still persists

**Comment by benderscruffy** [comment] 2022-11-30 01:51
is this still a problem ??

**Comment by Gamemulatorer** [comment] 2022-12-09 00:32
@t3rr41n can still reproduce this issue?

**Comment by unknownbrackets** [comment] 2022-12-09 02:34
I'm going to close this as it sounds like it was an issue with a bad rip.  If it's still happening, please comment with more detail and we'll reopen.

If you're seeing another issue with the same game, please open a new issue.

-[Unknown]

**Closed by unknownbrackets** 2022-12-09 02:34 UTC
Labels: PSMF / MPEG
