### ISSUE TITLE
MHP3 HD Hardware Transform Error 

### ISSUE THREAD

**Issue by cmrhere2play** [hrydgard/ppsspp#7328] opened 2015-01-14 04:50 UTC
Red message displaying hardware transform error- falling back to software then i get slow down This is the only game doing this 3rd birthday, Soul calibur BD all working well 

Device is THL T6 Pro
1.4GHZ Octacore
Mali400 
1GB of Ram

any fix possible??

**Comment by unknownbrackets** [comment] 2015-01-14 05:53
Closing as a duplicate of #1816.

-[Unknown]

**Closed by unknownbrackets** 2015-01-14 05:53 UTC
