### ISSUE TITLE
Outrun 2006, completely missing car reflections?

### ISSUE THREAD

**Issue by Tasosgemah** [hrydgard/ppsspp#11120] opened 2018-06-02 03:53 UTC
I noticed that the cars in Outrun look very flat and the reason is the lack of reflections or any kind of shine on the bodies. I tried every option i could, the only thing that makes reflections work is software mode.

Here's how they look:

![untitled](https://user-images.githubusercontent.com/12124465/40870137-7ebdce1e-6631-11e8-9eae-8980f670fb7d.png)

I'm using the latest version (1.6.1) on Windows. I was under the impression that the reflection effects did work a few years ago.

**Comment by unknownbrackets** [comment] 2018-06-02 04:14
This issue is being closed as a duplicate of #5506.  If it used to work in some version or with some settings, that would be useful information.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-06-02 04:14 UTC
