### ISSUE TITLE
Need UI(menu) for 320x160 resolution

### ISSUE THREAD

**Issue by tee4341** [hrydgard/ppsspp#13984] opened 2021-01-27 23:34 UTC
need menu UI for 320x160 resolution!!! please////
![GifMaker_lowquality16](https://user-images.githubusercontent.com/48321898/106072960-c326d980-613b-11eb-8a5e-26695a02101e.gif)
this game is run negative low resolution  to work fine/////
some effects is  highly GPU///// 
I can't turnoff some effects/////

**Comment by tee4341** [comment] 2021-01-27 23:59
need menu UI for 320x160 resolution!!! please////

**Comment by Panderner** [comment] 2021-01-28 00:01
Duplicate of #12644, PSP's resolution is 480x272 and it's not suitable for that resolution for games.

**Comment by Panderner** [comment] 2021-01-28 00:42
@tee4341 what device are you using?

**Comment by tee4341** [comment] 2021-01-28 01:06
lg g6  swith to low resolution for game

**Comment by Panderner** [comment] 2021-01-28 01:25
@tee4341 you have to switch to native resolution first

**Comment by unknownbrackets** [comment] 2021-01-28 02:13
This issue is being closed as a duplicate of #12644.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-01-28 02:13 UTC
