### ISSUE TITLE
Need For Speed Most Wanted 5-1-0 HUD and effects issues

### ISSUE THREAD

**Issue by Maarcis12** [hrydgard/ppsspp#15212] opened 2021-12-07 22:04 UTC
### Game or games this happens in

ULUS - 10036 - Need For Speed Most Wanted 5-1-0

### What area of the game

At any race event

### What happens

HUD and some effects seemed to regressed to garbled letters or not properly rendering
![ULUS10036_00002](https://user-images.githubusercontent.com/26842473/145110219-61454663-3f41-4034-b886-a323263b7da8.jpg)
![ULUS10036_00003](https://user-images.githubusercontent.com/26842473/145110223-87ec9d84-54a3-4c61-8fa2-6a5bf3c4e11d.jpg)

### What should happen

HUD and smoke effects should be like this (from 1.12.3. release) and text should white on black
![ULUS10036_00001](https://user-images.githubusercontent.com/26842473/145110376-14b6f2e2-1b6d-4509-89bf-8b2f4dfc4161.jpg)
![ULUS10036_00002](https://user-images.githubusercontent.com/26842473/145110379-747b8adc-3d0f-4025-9bce-26b748fac92b.jpg)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GTX 1050Ti Zotac OC Edition

### PPSSPP version affected

v1.12.3-401-g1f21796dd 	

### Last working version

v1.12.3-21-g236d02999

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2021-12-07 22:13
Looks like a duplicate of #15129, although it's new that it also happens in D3D11. Gonna look into this.

**Comment by Maarcis12** [comment] 2021-12-07 22:14
ok, thanks

**Closed** 2021-12-07 22:14 UTC
