### ISSUE TITLE
god of war GHOST OF SPARTA freeze (blue underground level)

### ISSUE THREAD

**Issue by dml360** [hrydgard/ppsspp#13612] opened 2020-11-01 17:44 UTC
![Desktop Screenshot 2020 11 01 - 14 19 19 68](https://user-images.githubusercontent.com/35852102/97810061-f4ccf900-1c4f-11eb-8fb7-0f9cd77c3491.png)

the game freezes occasionally in that part, I tried 4x and froze in 3x, the fourth I recorded the scene did not freeze (as soon as you press the L to drop it is when it occasionally freezes)

in addition to the video I also sent a log photo

https://www.youtube.com/watch?v=RLdsIfQ9keA

specs:

i5 8400
gtx 1060 6gb
w10 pro
ppsspp 1.10.3 - 1017
(OPENGL)

**Comment by hrydgard** [comment] 2020-11-01 18:11
Yes this is a known issue and has been reported multiple times, very difficult one to debug and fix though since it just crashes out of nowhere... 

Strangely I can't find any previous issue to link to though, so I'll leave this open for now.

**Comment by dml360** [comment] 2020-11-01 21:27
@hrydgard 
sorry friend, I was wrong about the title of the game, it's not the "chains of olympus" but the "ghost of sparta" already fixed the title

**Comment by hrydgard** [comment] 2020-11-01 22:04
Yeah, then this is a duplicate of a previous report: https://github.com/hrydgard/ppsspp/issues/6982 

Sorry it's still kinda broken :(

**Closed by hrydgard** 2020-11-01 22:04 UTC
