### ISSUE TITLE
Bug with innocent life futuristic harvest moon

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12263] opened 2019-08-21 05:15 UTC
### What happens?
The game freezes after island introduce

### What *should* happen?
The game would need to start

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Using Direct3d11 with PPSSPP 1.8.0 from site.
![ULUS10219_00000](https://user-images.githubusercontent.com/54099546/63404415-733ed180-c3e3-11e9-9ea8-d80a1d1044cc.jpg)

**Comment by unknownbrackets** [comment] 2019-08-21 05:23
This issue is being closed as a duplicate of #2830.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-08-21 05:23 UTC
