### ISSUE TITLE
Resistance retribution 

### ISSUE THREAD

**Issue by dml360** [hrydgard/ppsspp#11943] opened 2019-03-27 03:21 UTC
I tested this game with builds: 1.8.0 stable 1.8.0-15 1.8.0-30 1.8.0-38
in all builds the game crash in 90% of times, somethimes the texture bug.
build 1.8.0-39 this message appeared: "CRITICAL" "can´t have both THROUGH and USE_HW_TRANSFORM together! try to continue? click in yes appeared ASSERTION after click the game crash.
I used windows 10 64bits - cpu i5 7200U - gpu 920mx - 8gb memory

![55025307-7625c980-4fdf-11e9-97d0-9a0d917c1974](https://user-images.githubusercontent.com/35852102/55048217-30402400-5026-11e9-87bb-10c2a0215751.png)
![55025308-7625c980-4fdf-11e9-8979-767d14f580b9](https://user-images.githubusercontent.com/35852102/55048243-43eb8a80-5026-11e9-84b0-fdfaaf1c8280.png)

**Comment by Drasikk** [comment] 2019-03-28 16:20
Este juego se le atraganta a este emulador.

**Comment by unknownbrackets** [comment] 2019-03-29 02:53
This issue is being closed as a duplicate of #4626.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-03-29 02:53 UTC
