### ISSUE TITLE
Missing battle transition effect Valkyrie Profile Lenneth (Libretro)

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#12322] opened 2019-09-13 12:21 UTC
### What happens?
Missing distorted battle transition effect. 

### What *should* happen?
When making contact with an enemy in the libretro core the distorted transition is missing it just freezes then goes black then to the battle. The battles are fine, everything becomes visible after the black screen. The effect is present and works fine in upstream. The first image is upstream the other two are from libretro. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
i7 8086k, GTX 1080ti, Windows 10 desktop and the latest version of the core through the online updater. 
![ULUS10107_00000](https://user-images.githubusercontent.com/12180630/64862002-75213c80-d5ff-11e9-84c6-d2ba78635c2d.jpg)
![Valkyrie Profile Lenneth-190913-081235](https://user-images.githubusercontent.com/12180630/64862010-79e5f080-d5ff-11e9-9228-cb8119b464c5.png)
![Valkyrie Profile Lenneth-190913-081250](https://user-images.githubusercontent.com/12180630/64862014-7c484a80-d5ff-11e9-8143-3a13e81adeba.png)

**Comment by unknownbrackets** [comment] 2020-03-08 20:12
This may be caused by missing settings or lack of dual source blending or similar.

If you turn off block transfers, buffered rendering, or enable "disable slow effects", can you trigger the same behavior in PPSSPP proper?  That would point to a problem with how libretro handles or forces that setting.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-04-16 06:46
Recently someone in Discord reported that libretro was not exposing GLES3 / OpenGL 3+ features to PPSSPP.  On the same device, PPSSPP proper worked fine.  That might be related to this issue.

-[Unknown]

**Comment by BParks21** [comment] 2020-05-22 13:16
@unknownbrackets Strange i just discovered that enabling unsafe funreplacements fixes the effect, but why would disabling it break the effect. This doesn't happen when it's disabled in upstream.

**Comment by unknownbrackets** [comment] 2020-05-22 13:44
While most games draw using the GPU, some games update drawing from the CPU.  When using a hardware backend (i.e. not using software rendering), these effects won't normally be visible.

Func replacements (which includes hooks) are on by default in PPSSPP and there's normally no option to turn them off.  These hook standard library functions to detect attempts to change graphics and update the hardware renderer.

I wouldn't be surprised if they're needed for this effect.  If so, it probably means block transfer is needed too.  I can't imagine why that'd be different in PPSSPP proper.  I'm also not sure what "unsafe" refers to.

-[Unknown]

**Comment by BParks21** [comment] 2020-05-22 13:47
Well both versions of ppsspp have this option and having it off in proper still allows the effect to render.

**Comment by BParks21** [comment] 2021-02-14 08:49
@hrydgard What is the upstream equivalent setting of Unsafe FuncReplacements from the libretro port. Because with it off in the core options the battle transition affects in Valkyrie Profile Lenneth are gone. With it on the battle transition affect is fine. Should this be set to on in the libretro core options?

**Comment by unknownbrackets** [comment] 2021-02-14 15:45
That's not intended to be a user visible option.

-[Unknown]

**Comment by BParks21** [comment] 2021-02-14 22:21
@unknownbrackets Why have it exposed as a core option in the libretro port then? Seems confusing to show something on called "unsafe"

**Comment by hrydgard** [comment] 2021-02-14 23:17
It should be defaulted to true and not made visible as a user option. It's not that unsafe, we run with it by default in standalone PPSSPP.

**Comment by BParks21** [comment] 2021-02-14 23:26
> It should be defaulted to true and not made visible as a user option. It's not that unsafe, we run with it by default in standalone PPSSPP.

It is visible as a user option in libretro.

**Comment by hrydgard** [comment] 2021-02-15 06:32
Yes, I'm saying it should not be! It'll cause confusion like this.

**Comment by BParks21** [comment] 2021-02-15 06:34
> Yes, I'm saying it should not be! It'll cause confusion like this.

Ahhh I see, i misunderstood.

**Comment by unknownbrackets** [comment] 2021-02-15 14:06
Can we say this is fixed now?

-[Unknown]

**Comment by hrydgard** [comment] 2021-02-15 14:27
Yeah, I think so.

**Closed by hrydgard** 2021-02-15 14:27 UTC
Labels: Libretro

**Comment by BParks21** [comment] 2021-02-15 22:38
@hrydgard So it seems in the latest build of the core you have removed the ability to toggle the unsafe funcreplacements but have left the actual setting off by default. Now VP battle transition effects are always frozen/missing and crisis core will freeze when loading a save file.

**Comment by hrydgard** [comment] 2021-02-15 22:44
@BParks21 You may need to also delete memstick/psp/system/ppsspp.ini where PPSSPP stores its own settings?  (or just change the setting there)

I could rename it so it effectively gets reset for everyone. I guess that would make sense for something like this.

**Comment by BParks21** [comment] 2021-02-15 22:46
> @BParks21 You may need to also delete memstick/psp/system/ppsspp.ini where PPSSPP stores its own settings? (or just change the setting there)
> 
> I could rename it so it effectively gets reset for everyone. I guess that would make sense for something like this.

Ok i will try that and report back.

**Comment by BParks21** [comment] 2021-02-15 23:15
@hrydgard I can seem to find the path or file you're referring to for the libretro port. Memstick folder doesn't exsist. This is the path i have for retroarch in the save folder C:\Programs\Emulators\RetroArch\saves\PSP. There is no system or ppsspp.ini

**Comment by hrydgard** [comment] 2021-02-15 23:18
Never mind, it's not used in the retro build. 

There are a couple ways we can fix it. I'm gonna take a shortcut for now.

**Comment by BParks21** [comment] 2021-02-16 09:25
@hrydgard So I'm running ppsspp (1.11.2-75-gb0fdc7a) libretro now and it seems unsafe func is back on and Valkyrie Profile battle transition effects are working again but for some reason Crisis Core is still freezing after loading a save. It was working fine sometime before the frame duplication I think. Ugh frustrating.

**Comment by hrydgard** [comment] 2021-02-16 10:02
That would be a separate issue that should be reported.

**Comment by BParks21** [comment] 2021-02-16 10:10
> That would be a separate issue that should be reported.

Yeah I just wish i had an older version of the core. Is there somewhere i can download older versions? I only seem to be able to find the most recent build on the libretro nightly download page.
