### ISSUE TITLE
Yakuza Black Panther (Kurohyō: Ryū ga Gotoku Shinshō) backgound scenery issue

### ISSUE THREAD

**Issue by Peduls** [hrydgard/ppsspp#12998] opened 2020-06-05 03:55 UTC
### What happens?
In Yakuza Black Panther (Kurohyō: Ryū ga Gotoku Shinshō) people are rendered in front of scenery incorrectly.
![NPJH50333_00000](https://user-images.githubusercontent.com/34750422/83835365-da492080-a6ad-11ea-9d98-0af99c111572.png)

### What *should* happen?
People should render behind certain parts of the game's scenery such as signs and store shelves.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP version
	v1.9.3-994
Operating System
	Windows 10 Enterprise 64-bit
CPU
	Intel Core i7 4790K @ 4.00GHz
	Haswell 22nm Technology
RAM
	16.0GB Dual-Channel DDR3 @ 799MHz (9-9-9-24)
Motherboard
	ASUSTeK COMPUTER INC. Z97-A (SOCKET 1150)
Graphics
	VG248 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	2794GB TOSHIBA HDWD130 (SATA )
Optical Drives
	ASUS DRW-24B1ST j
Audio
	High Definition Audio Device

**Comment by Peduls** [comment] 2020-06-05 03:56
Here you can see the game on real hardware. The pedestrians heads are obscured by the sign above.
![35631-ingame-Kurohyou-2-Ryu-ga-Gotoku-Ashura-Hen](https://user-images.githubusercontent.com/34750422/83835539-4461c580-a6ae-11ea-9218-0b274dcf25de.jpg)

**Comment by LunaMoo** [comment] 2020-06-05 09:08
Closing as a duplicate of #9576

**Closed by LunaMoo** 2020-06-05 09:08 UTC
