### ISSUE TITLE
GTA Liberty City Stories always freezes at the exact same moment

### ISSUE THREAD

**Issue by bezin** [hrydgard/ppsspp#17614] opened 2023-06-22 17:19 UTC
### Game or games this happens in

ULES00151 v3.00 GTA Liberty City Stories

### What area of the game / PPSSPP

In the mission The Shoreside Redemption the game freezes always at the exact same moment: After the convoy has been attacked and truck and player have left the dam and then turned left, when the message "Illegal road block reported in the area" appears. I waited for a couple of minutes, before closing the emulator: once the game continued for a couple frames, but then freezed again. 

It is almost the last mission. The game worked flawlessly up until now. Would be happy to finish the last two or three missions :D

![Screenshot_20230622-185757_071350](https://github.com/hrydgard/ppsspp/assets/4400435/00d287f4-b3e4-4db9-893b-77a796867b92)

![Screenshot_20230622-181535_071419](https://github.com/hrydgard/ppsspp/assets/4400435/1f30be0a-b024-4bd2-9e9c-53316535e946)

### What should happen

The game should not freeze. 

### Platform

Android 11

### Mobile phone model or graphics card

Retroit Pocket Pro 3+

### PPSSPP version affected

1.15.4 (PPSSPP Gold) Testet with latest Git build, but the problem persists.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2023-06-22 19:43
Do you have a save game or save state close to the freeze?

**Comment by NABN00B** [comment] 2023-07-06 10:02
Together with the text "Illegal road block reported in the area" an audio file should be playing.

Please check and post the CRC of your game ROM.

![image](https://github.com/hrydgard/ppsspp/assets/22328803/4f11459f-4e69-4e6f-ae39-a0d25b97996e)

**Comment by bezin** [comment] 2023-07-06 10:38
@hrydgard Sorry for not coming back to you earlier. Please find the save state attached. Just keep going on the street, the game will freeze shortly after. In the end, an in-game save saved me. Before starting the mission I went and reloaded from within the game, then startet the faulty mission and everything was working again. 

[Broken savegame](https://github.com/hrydgard/ppsspp/files/11967290/archive_123337.zip)

@NABN00B I checked it and it is fine. The audio starts playing, too.

**Comment by justafella** [comment] 2023-10-05 16:14
Always check your game ROM file for any damage (bad dump, corrupted file, incomplete download, etc)

**Comment by bezin** [comment] 2023-10-05 16:24
I did. Checksum is fine

**Comment by sum2012** [comment] 2023-10-05 21:35
bezin 's Game is  Grand Theft Auto: Liberty City Stories eur v3
My friend have it ( and it match the crc in http://redump.org/disc/852/ )
I test the save status in v1.16.5-83-gb85f7e28a  ,it raise blue screen.
log: 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/12824142/ppsspplog.zip)

![1png](https://github.com/hrydgard/ppsspp/assets/2177532/7bde92c5-f856-4a08-8251-d8bbd5d00e9e)


@bezin Can you also upload real game save to me test in a real psp ?

**Comment by LunaMoo** [comment] 2023-10-05 22:13
> (...) In the end, an in-game save saved me. Before starting the mission I went and reloaded from within the game, then startet the faulty mission and everything was working again.
> (...)

Shouldn't the issue be closed then? To me this looks like just natural instability of the game caused by simulating very long time without restarting the game thanks to save states and was resolved by reloading in-game save.

**Comment by hrydgard** [comment] 2023-10-05 22:53
Yeah, it's a known problam with this game that you have to occasionally do a proper save and reload. That's one of the reasons we have that message to "save to avoid bugs" that pops up when you load a state on occasion.

**Closed** 2023-10-05 22:53 UTC

**Comment by Diesel2006** [comment] 2025-01-16 07:03
This exact problem happened to me today; Thanks for the fix guys, it worked more Flawlessly than Tony's Driving, thanks guys

(Note: The fix was to simply reload a save in game and not with the emulator from time to time)
