### ISSUE TITLE
DX11: Graphical issues in KHBBS & MGSPW

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11805] opened 2019-02-17 14:20 UTC
Just got a new computer and tried the DX11 renderer, only to find some weird graphical issues.

https://www.youtube.com/watch?v=Tf777--WXCQ
EDIT: Some images to make it more clear.

![image](https://user-images.githubusercontent.com/27028529/52914442-fc474580-32a6-11e9-9afc-5022a1a9398e.png)
![image](https://user-images.githubusercontent.com/27028529/52914446-0701da80-32a7-11e9-86a6-b65294854d53.png)
![image](https://user-images.githubusercontent.com/27028529/52914457-31539800-32a7-11e9-9873-6f3d71d1242c.png)

**Comment by AkiraJkr** [comment] 2019-09-01 06:53
This seems to be an issue in Metal Gear Solid Peace Walker too, but that only shows up when you equip the Night Vision Glasses.
![image](https://cdn.discordapp.com/attachments/478294170662862852/617458521897959434/unknown.png)
![image](https://cdn.discordapp.com/attachments/478294170662862852/617458500968382483/unknown.png)

![image](https://cdn.discordapp.com/attachments/478294170662862852/617458658753773667/unknown.png)
![image](https://cdn.discordapp.com/attachments/478294170662862852/617458626688319506/unknown.png)

![image](https://user-images.githubusercontent.com/27028529/64072822-a9921180-cc6b-11e9-8278-d0ba58f3a391.png)
![image](https://user-images.githubusercontent.com/27028529/64072826-b151b600-cc6b-11e9-9905-efa1ae590ce0.png)

![image](https://user-images.githubusercontent.com/27028529/64072836-d7775600-cc6b-11e9-93b0-9d5df9459537.png)
![image](https://user-images.githubusercontent.com/27028529/64072846-fe358c80-cc6b-11e9-8050-bbfb57dac434.png)

**Comment by AkiraJkr** [comment] 2019-09-01 16:13
![image](https://user-images.githubusercontent.com/27028529/64078947-9147e400-ccb7-11e9-8dbc-7c703c6981ed.png)

![image](https://user-images.githubusercontent.com/27028529/64078958-a3298700-ccb7-11e9-96af-5f2581cf29f9.png)

A GE Dump for this: https://cdn.discordapp.com/attachments/478294170662862852/617753132545343498/recording.ppdmp


![image](https://user-images.githubusercontent.com/27028529/64079125-0f0cef00-ccba-11e9-9728-956a2d7b2e09.png)

And it's GE Dump: https://cdn.discordapp.com/attachments/478294170662862852/617753847602872343/recording.ppdmp

**Comment by unknownbrackets** [comment] 2019-09-01 19:19
For Metal Gear Solid:

PSP:
![ULUS10509_#11805_mgs_static_dots](https://user-images.githubusercontent.com/191233/64081069-d7e61000-ccb0-11e9-9c3b-2d69be81b0e4.png)

Software:
![ULUS10509_#11805_mgs_static_dots_softgpu](https://user-images.githubusercontent.com/191233/64081072-e16f7800-ccb0-11e9-9416-04ba970a9be0.png)

GLES:
![ULUS10509_#11805_mgs_static_dots_gles](https://user-images.githubusercontent.com/191233/64081074-e6342c00-ccb0-11e9-8cb3-b599b3c45105.png)

Direct3D 11:
![ULUS10509_#11805_mgs_static_dots_directx11](https://user-images.githubusercontent.com/191233/64081111-4fb43a80-ccb1-11e9-825c-c95228c0ae57.png)

Looking at the dump, even at higher render resolutions, I'm not reproducing the problem.  Is it happening only with certain settings?  Does it happen for you when you load the dump?

-[Unknown]

**Comment by AkiraJkr** [comment] 2019-09-01 19:27
Indeed it does, and it doesn't matter the resolution, but the issue is more obvious at lower resolutions, that's for sure.

![image](https://user-images.githubusercontent.com/27028529/64081277-14c3fe00-ccd5-11e9-898c-9a62f07bee65.png)

I tried enabling Vertex cache, no change. Disabling Software Skinning and Hardware Transform, nothing either.

**Comment by unknownbrackets** [comment] 2019-09-01 20:55
More obvious at lower resolutions, you say?  How does it look at 1x?  Or did you just mean more obvious at higher?

It doesn't happen for me with Intel UHD 630 either, unfortunately.

-[Unknown]

**Comment by AkiraJkr** [comment] 2019-09-01 20:57
1x:
![image](https://user-images.githubusercontent.com/27028529/64082213-e862ae80-cce1-11e9-8bea-62c67b4426b2.png)

5x:
![image](https://user-images.githubusercontent.com/27028529/64082216-f0bae980-cce1-11e9-99be-e61bd67e806f.png)

Maybe it's an issue specific to the first gen Intel HD?

**Comment by unknownbrackets** [comment] 2022-10-23 17:59
It might be - this doesn't reproduce for me on an Intel device with Direct3D 11.

Maybe it's been fixed in latest drivers?  Does this still happen?

-[Unknown]

**Comment by AkiraJkr** [comment] 2022-10-23 20:30
It's hard to say since...I don't quite have that computer anymore, so it's something to be researched on Discord.

**Comment by hrydgard** [comment] 2022-10-23 20:33
Since we haven't had additional reports and testing seems to indicate it works, let's just close as outdated for now, and reopen if we do get more reports.

**Closed by hrydgard** 2022-10-23 20:33 UTC
Labels: No Feedback / Outdated?, D3D11
