### ISSUE TITLE
Old PPSSPP that support Gundam Vs Gundam Next Plus Adhoc

### ISSUE THREAD

**Issue by NgJinXiang14** [hrydgard/ppsspp#11497] opened 2018-10-27 15:32 UTC
Hello,is it possible to use the code from the old PPSSPP build that support Gundam VS Gundam Next Plus adhoc to merge into new version?
The newest version of PPSSPP (1.7) still could not support adhoc on this game.Or is there anything i can help with?

Old version PPSSPP by Onelight (Forum Thread): http://forums.ppsspp.org/showthread.php?tid=12357

**Comment by lightfirst** [comment] 2018-11-01 15:01
It was a hack build, help adhoc in Gundam VS Gundam Next Plus but broke Phantasy Star

**Comment by Emulatorer** [comment] 2018-11-02 05:15
And the modded apk v1.7-15 is buggy can't even touch the settings because the touchscreen doesn't respond :/

**Comment by NgJinXiang14** [comment] 2018-11-02 06:35
Uhhh,yeah,disable the immersive mode to make it works

**Comment by NgJinXiang14** [comment] 2018-11-02 06:43
@hrydgard I think you misunderstand my statement 😂,i mean it is a custom build ppsspp based on old version PPSSPP, Official one,from old to new cant support the multiplayer as it broke when starting the game at AdHoc Mode. What i want to ask if can merge the code and make it into a option in official build? Oh,and like @lightfirst  say,it broke the phantasy star so better make it a option in setting,right?
Sry for the bad english.
![screenshot_20181102-131320](https://user-images.githubusercontent.com/6142827/47897635-796ebc00-de6a-11e8-8eb9-045a4a25024b.png)

PS: The coder of that custom build PPSSPP just update it recently and heres the proof it can work.

**Comment by hrydgard** [comment] 2018-11-02 08:16
Well this custom build maker should share whatever changes he made, so we can incorporate them. He is required to do so by the GPL license.

**Comment by Emulatorer** [comment] 2018-11-02 09:05
There's already a PR for Adhoc Multiplayer Chat Support #7451 #9090

wait for it to merged?

ps, sorry for my bad english :)

**Comment by lightfirst** [comment] 2018-11-02 09:43
@hrydgard The change code at here https://github.com/lightfirst/PPSSPP/commit/0fd927db6cda206378d166f0b96884159a418a34

Do we really need this hack?

**Comment by lightfirst** [comment] 2018-11-02 09:51
@Emulatorer mod v1.7-15 working fine for me, maybe you should try Restore PPSSPP's settings to default or delete ppsspp.ini and controls.ini at /sdcard/PSP/SYSTEM

**Comment by hrydgard** [comment] 2018-11-02 09:53
I guess we could make it a game specific compatibility setting until a proper fix can be found.

**Comment by Emulatorer** [comment] 2018-11-02 10:18
@lightfirst I already fix the issue in touchscreen but some games seems running slow compare to the official build/version and also the graphics display is like force to X2 HW rendering resolution even if it set to native

**Comment by lightfirst** [comment] 2018-11-02 10:41
@Emulatorer Did you compare to the official 1.7-15?

**Comment by Emulatorer** [comment] 2018-11-02 10:43
Yes

**Comment by lightfirst** [comment] 2018-11-02 10:49
It can't be, I just add a hack for gvgnp and merged Chat Support #7451 #9090  the speed and graphics should same as official build

**Comment by NgJinXiang14** [comment] 2018-11-02 12:37
@lightfirst Actually,I also face the same problem,if official build I can use till 4x,with that version max resolution is only 2x

**Comment by lightfirst** [comment] 2018-11-08 06:31
@Emulatorer It should working fine after ppsspp-1.7.1-125-Chat-GVG

**Comment by adenovan** [comment] 2018-11-08 12:41
i guess jpcsp multiplayer working with this game  , i am on progress writing adhoc multiplayer relay micro service and deciding to implementing everything on SceNetAdhoc from scratch , HLE function LOG on successfull multiplayer should be a great help to troubleshoot the problem. 

PPSSPP networking code really need an update , some high level network library also can be helpfull than relying on C code networking api. working with buffer, endianess ,and many other network stuff on PPSSPP source code is really a pain. im really suggesting ppsspp use ENET as networking library and implement packet class to work on buffer like citra do on their networking folder,

[](https://github.com/citra-emu/citra/blob/master/src/network/packet.cpp)

this will make the development of networking part a lot easier and may can improve latency over internet.

**Comment by lightfirst** [comment] 2018-11-09 01:46
yes, jpcsp multiplayer working with this game and more games

**Comment by adenovan** [comment] 2018-11-13 11:45
looks like the code that fix phantasy star one is the broken one , it race within matching thread if the matching thread get incomplete data from pdprecv the multiplayer is broken. 

suggest fix don't use PDP function to handle the matching event , instead we must simulate it on other socket like jpcsp do, have one socket to arbitrate like scenetadhocctl does!

**Comment by unknownbrackets** [comment] 2018-12-04 02:13
Is this a duplicate of #7444?

-[Unknown]

**Comment by southern-dust** [comment] 2020-08-08 12:27
Does anyone try to figure out this issue on Newest version of PPSSPP for GVGNP?

**Comment by Gamemulatorer** [comment] 2020-08-08 14:37
This issue is already been fixed by https://github.com/hrydgard/ppsspp/pull/13182 or not?

**Comment by southern-dust** [comment] 2020-08-16 14:33
> 
> 
> This issue is already been fixed by #13182 or not?

yep, seems fixed!

**Comment by lightfirst** [comment] 2020-08-16 15:04
Well, it fixed, adhoc working fine on windows, but when play whith android, disconnect appeared in the middle of the multiplayer battle. Sometimes 10 - 40 seconds.

**Comment by innorage** [comment] 2020-08-18 05:47
May I know which version's fixed? I tried the latest 1.10.3, could see my friend in multiplayer, but the game wouldn't load after I clicked start.

**Comment by unknownbrackets** [comment] 2020-08-18 05:53
We close bugs as soon as they are fixed in git, we don't wait until the next stable release which might be weeks or months away.  This issue was fixed since v1.10.3 was released, so you'd have to use a git build.

That said, reopening if it's still an issue on Android.  Presumably that's a port # issue?

-[Unknown]

**Comment by lightfirst** [comment] 2020-08-18 07:31
> 
> 
> May I know which version's fixed? I tried the latest 1.10.3, could see my friend in multiplayer, but the game wouldn't load after I clicked start. Btw, this applies to multiplayer between PPSSPP right?

v1.10.3-198 and up. you can get PPSSPP builds from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by leoxxx** [comment] 2020-10-04 02:11
https://github.com/hrydgard/ppsspp/pull/13182
Can start game & linkable more games, but unstable.

**Comment by hrydgard** [comment] 2020-11-10 21:59
How is this now?

**Comment by leoxxx** [comment] 2020-11-11 12:05
@hrydgard
1.10.3-917 is better than before.
Thank for your work.

**Comment by hrydgard** [comment] 2020-11-11 12:32
Well, on this, mainly @ANR2ME 's work to be fair :)  I'll close this issue, feel free to open new ones with specific issues.

**Closed by hrydgard** 2020-11-11 12:32 UTC
Labels: Networking / adhoc
