### ISSUE TITLE
Developers can do an attention in Raspberry Pi3 for ppsspp ?

### ISSUE THREAD

**Issue by luizthiagor** [hrydgard/ppsspp#11317] opened 2018-08-24 15:45 UTC
### What happens?

until the new 1.6.3 mostly hardware, including the RPI3 run smootly (even with your weak hardware and videoCore ). The 1.5.4 commits i have testes are OK in majory and performance has OK. The only problems has some bugs like the overbrightness in some games like ratchet and clank and jak and daxter repported here previously. This is due an issue  that prevents the game from displaying images if this "hack" option is not selected (the option "disable slower effects (fast)". this is an error since this is a hack and if it is not active the game should work with images normally, as it happens in 1.6.3 currently! ...

### What *should* happen?

My main claims would be: 1) Do the developers have an exemplar of Raspberry PI 3 to be able to run the tests directly and check why the slow performance in the new version 1.6.3 on this hardware? (I believe that if the developers could investigate this in depth, they could come to the conclusive point of why this problem in this new ppsspp version.) - Note that several new builds of 1.6.3 have already been tested directly in RPI3 (not the core libreto) and the very low performance persists!) 2) If this is not feasible, however much the guideline is "we already abandoned version 1.5.4 while 1.6.3 is the new version under development", even so, you could not go back to 1.5.4 and verify why this problem occurs and perhaps post a fix for this version that has its normal performance in RPI3? - The problem occurs mainly in "High Impact Games" games like "ratchet and clank" and "jack and daxter" and refers to the overbrigthness that occurs in these games if "Disable slow effects (fast)" is selected ... Okay, you guys they would say: simply disable this option since it is a Hack and can break some games ... but then there is the true problem of 1.5.4 in RPI3: if I disable this option, as usual should be, the game simply runs out of image ... black screen and just listen to the sound! - This is the real problem that is happening today and should not happen! (the same problerm don't ocurring in 1.6.3 in my tests, if i disable this hack option the games still running ok and no more overbrigtness, but , in 1.6.3 all games, even other i have testes in RPI3 is very, very slow performance ....and i have tried several configs to can returned here and clain about it .... The developers can do some of this clains for help me ?? Thanks in advance

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

RPI3, Batocera Linux System (various versions to test ppsspp) , 1.5.4 have Blank / overbrithness problem  if the option mentioned above are "uncheck" and in 1.6.3 has the very, very slow performance on same hardware !!

**Comment by LunaMoo** [comment] 2018-08-24 19:17
The reason 1.6.3 displays proper graphics without hack activated while 1.5.4 didn't is exact reason why the never version is slower than older - more things are emulated correctly.

 You can't get both - fixed graphics AND same speed as with broken / not displayed graphics - it's impossible and no amount of wall of text spam and wishful thinking will ever change that.
 Closing as this isn't an emulation issue.

**Closed by LunaMoo** 2018-08-24 19:17 UTC

**Comment by unknownbrackets** [comment] 2018-08-25 04:28
This is also a duplicate of #11265.

Remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Comment by luizthiagor** [comment] 2018-08-27 19:08
Sorry for not being able to help .... but since I have no programming knowledge, I can not help correcting it.

And, I do not agree with what was related in reference to the problem, since, for me, this is a bug .... Version 1.5.4 in RPI3 could not fail to display the graphics of some games if a "HACK" is disabled ... even if it slows down in this game, the image should be displayed ....

I understand that ppsspp is open source and that you are working hard to help us for free!

Anyway: my idea remains the same: if the developers had how to run ppsspp 1.6.3 on a raspberry Pi 3, maybe they could figure out the reason for the abrupt drop in performance and, since this version was called "the fast one" , this is unfortunately being reversed on the hardware mentioned!

Maybe, if there was a front-line ppsspp project facing the raspberry, they could hit it specifically for this platform, but this could only be feasible by the developers ....

Unfortunately, if this does not happen, we are shutting down and doomed to eternally shut down in 1.5.4 with some bugs that will never be fixed and stopped in time since if nothing is done, we can not get out of the current state ...

Again, sorry for not being able to help and I am sad to know that I will have to stagnate in 1.5.4 and its problems will never be solved. we can not use 1.6.3 with the current performance in this architecture ....

but thank you anyway
