### ISSUE TITLE
PPSSPP 1.0 - Regressions and bugs to fix before release

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7246] opened 2014-12-31 14:50 UTC
Alright, time to do 1.0 finally, I'm aiming for end of January.

Please report anything that has gotten worse since the last release in this issue so we can fix it up before we release 1.0. 

Also bugs in new features, like if there are problems with the new savestate UI :)

Features:

  * ~~Low latency audio implemented for Windows and Android~~
  * ~~Adhoc branch merged~~

Bugs:

  * Prince of Persia Rival Swords black screen: #7314
  * ~~x86 SIMD regressions: https://github.com/hrydgard/ppsspp/issues/7292~~
  * ~~Resizing the window must work correctly in D3D, and new D3D crashes from the last attempt~~
  * ~~FIXED: #6898 (on screen buttons partly disappear in non-buffered rendering)~~
  * ~~#7324 Android screen resolution issue~~

Minor:

  * Savestate screenshots are sometimes black

**Comment by hrydgard** [comment] 2015-01-01 13:32
@Joelgp83 , just fixed the moga dpad in Mode A, can you retry on your setup?

**Comment by chaosjr7** [comment] 2015-01-01 14:04
The Mana Khemia Issue still exists I think, I will check the latest GIT, to be sure..If it helps and is still there like I think it might be , The unthrottle Button pressed with the quote "END" Key, seems to be a decent workaround for now. I have (U) Version of Mana Khemia so my "END" key is 'Cross'.
Good Luck. See Ya Later.

**Comment by vsub** [comment] 2015-01-01 16:08
About Mana Khemia(usa version),no matter how many times I tried with different settings,this was the only way to fix it

1.Either use this code that forces the game to run at 60fps(I always keep that code enabled for this game anyway because it looks too slow without it(I played the PS2 version too many times and it looks low in the PSP without this code))

_C1 60 FPS
_L 0x2001C238 0x0E26C5AB

2.Or Press and hold the key for rapid-file and press and hold the key for the x button immediately when the last enemy dies...in the results screen you have extremely small amount of time to start mashing the x button(rapid-fire)and if you wait for the results screen and wait too long,the game won't allow you to continue.

Here is a save before the boss battle(you can easily kill it because this is at least second playthrough)
http://www63.zippyshare.com/v/43650213/file.html

**Comment by unknownbrackets** [comment] 2015-01-01 18:24
Okay, with that save, I think I know the cause.  But is this an actual regression?  Did it ever work?

The game is running at that point at 20 fps, which I think is incorrect.  As I recall, 20 fps in this game is generally caused by sceCtrl delays.  It calls sceCtrl twice to grab input and iirc discards one.  So, I suppose it works when you mash X enough because you eventually get lucky and get the press and release both in events it doesn't discard, or something to that effect.

But even on a real PSP this game seems to run at inconsistent FPS and drops to 20 sometimes.  We're not accurate here, so it is a bug, but it's been this way for as long as I know.

-[Unknown]

**Comment by vsub** [comment] 2015-01-01 19:28
Hmm I guess I was wrong about the second method.
Even if all menus appear,when you mash the x button(rapid-fire)it will actually continue the game after 1-2 second of holding the rapid fire and the x button.

And yes,this problem didn't exist before(just for a test I tried something really old(0.9.1-542)and it was working fine there)

**Comment by Joelgp83** [comment] 2015-01-02 01:21
@hrydgard, I have work so i wont be able to test the android-moga changes for awhile.  Also, I have no idea when these new changes will propogate to the ppa i am using.

Finally, i must mention that linux mint sees the controller in mode a as a computer/phone, not a joypad.  Mode b is properly recognised as a HID joypad.

**Comment by sum2012** [comment] 2015-01-04 15:26
@hrydgard can we fix #6898 non buffered rendering ,button disappear bug ?

**Comment by hrydgard** [comment] 2015-01-04 16:11
Hm, I thought I fixed that, or a similar problem, a while ago... I'll have another look because yeah, it's pretty important.

**Comment by unknownbrackets** [comment] 2015-01-05 03:08
There's apparently a bug in Yu-Gi-Oh games on ARM only:

http://forums.ppsspp.org/showthread.php?tid=6466&pid=99587#pid99587

-[Unknown]

**Comment by trnzaddict** [comment] 2015-01-05 14:43
I don't know if this counts as regressions, but After Burner Climax WAS working on earlier versions. Now it hangs after displaying the Havok video and also has strobing FMV. Also Resistance:Retribution which did crash PPSSPP on earlier revisions now doesn't, but is now plagued with graphical bugs on both back ends as soon as you start walking around. That didn't happen before.

**Comment by hrydgard** [comment] 2015-01-05 14:50
@trnzaddict , thanks. could you create separate issues with screenshots for those two, unless they are already reported?

**Comment by sum2012** [comment] 2015-01-05 14:56
My game are a bit differance  After Burner Black Falcon EUR version
As a fast test,
work in -v0.9.6-120-g291d25f 
don't work in -v0.9.6-691-g4f2f8f0
I cannot search opened "After Burner" issue.
Anyway ,I sleep now

**Comment by daniel229** [comment] 2015-01-05 16:11
Afterburner Black Falcon thread
https://github.com/hrydgard/ppsspp/issues/6794

**Comment by Dhezta** [comment] 2015-01-05 23:48
Can you fix Final Fantasy II games? its very slow motion when  enter the world map.......thanks...

**Comment by 007flawless** [comment] 2015-01-08 10:40
GTA Vice City Stories and Liberty City Stories still have Serious Issues on PowerVR GPUs.. Main Character, Pedestrians and basically all Humans are Invisible except in Cutscenes.. Also Traffic and all Vehicles are Invisible.. Among other disappearing Objects like some Trees.. I wish this would be looked Into.. But Thanks for all the effort PPSSPP Devs

**Comment by Joelgp83** [comment] 2015-01-09 05:48
Finally got a chance to test your latest moga changes on Android, as well as do more linux testing.  

On Android, Mode A works flawlessly in-ui and in-game now, thank you.

Moga on Linux (ppsspp-sdl, can't get ppsspp-qt to recognize anything) is still a different story.  Where to start.....also, should this be split off and moved to a separate issue?

As stated before, Mode A is not seen as a joypad, but rather a phone/computer in linux mint, so I use mode B, pairing code 1234.  In game nearly all button/triggers work as designed, better than windows (can't use triggers on windows, moga devs are apparently not motivated enough to release proper driver support)! 

However, the default guesses for button assignements are way off, and that's partly due to what linux is calling the buttons.  I've attached some screenshots of my corrected control mapping, and they reveal some non-sensical button names, particularly for the A/B/X/Y buttons and Select/Back.  I don't know if this is the OSes fault or if key codes are being misunderstood, but sometimes select doesn't work in game, also.

And yes, my control mapping has the dpad mapped to both the controller's dpad and the right analog, for more naturally camera control purposes.

![screenshot from 2015-01-08 21 38 06](https://cloud.githubusercontent.com/assets/7368696/5675933/d2bcc328-977f-11e4-898f-faf89dad67c7.png)
![screenshot from 2015-01-08 21 38 16](https://cloud.githubusercontent.com/assets/7368696/5675932/d2bca082-977f-11e4-8c05-9687db186d56.png)
![screenshot from 2015-01-08 21 38 33](https://cloud.githubusercontent.com/assets/7368696/5675934/d2bd645e-977f-11e4-95a2-3fdb770bd71b.png)
![screenshot from 2015-01-08 21 39 34](https://cloud.githubusercontent.com/assets/7368696/5675935/d2c224e4-977f-11e4-8372-0eddf8c3ea7d.png)
![screenshot from 2015-01-08 21 39 37](https://cloud.githubusercontent.com/assets/7368696/5675936/d2c5ecb4-977f-11e4-9eba-a39be6b78c78.png)

**Comment by coolmisty45** [comment] 2015-01-10 00:33
hi i play wwe 2k14  it force closed after  3 mins of play,  but  the ppsspp from playstore didnt  force close when i play the game -plz fix

**Comment by hrydgard** [comment] 2015-01-10 00:44
@coolmisty45 thanks for reporting! Does this also happen in the Windows version of PPSSPP?

**Comment by coolmisty45** [comment] 2015-01-10 00:47
@hrydgard   i dont think so but i havent  played to it to much on windows computer

**Comment by Joelgp83** [comment] 2015-01-10 03:48
@hrydgard, got a chance to sideload and test v9.9.1-1442 on an current-gen Amazon FireTV.  Results were, well, less than optimal.  The FireTV supports controllers, and is beefy enough to theoretically play games very well, but I am practically unable to navigate the ui with the standard FireTV remote control with any reliability, and attempting to use my moga to navigate results in the same ui controls issues at linux mint had.  In short, I can't launch games or map controls or change settings, which means I can't test real-world performance either. :(

**Comment by LunaMoo** [comment] 2015-01-10 13:35
@hrydgard Seems that new savestate UI on pause screen(https://github.com/hrydgard/ppsspp/commit/6879f05eb069c87ea19badaca7035e90881a44c1) broke ability to store savestate slot into game config(slots from general config are remembered just fine).

**Comment by Some1Else46** [comment] 2015-01-10 19:01
Not sure if this is even worth the time looking into, but #5333 still seems to be an issue for me with the latest iOS git build from the buildbot on iOS 8.1.1.

**Comment by hrydgard** [comment] 2015-01-10 19:22
@LunaMoo , are you sure? The savestate UI saves the slot the same way as before..

**Comment by LunaMoo** [comment] 2015-01-10 20:26
@hrydgard well maybe it's just me, but changed slot after I create config is not saved when I leave the game:|.
For example to reproduce it, run the game change to slot 2, exit game, open it again and slot 2 should be highlighted. Then create custom config for that game, change it to other slot ie slot 3, and leave the game again, after returning to it, it'll continue to have slot 2 selected, and it'll forever start from that slot as long as custom config exists.

 Also when I was testing it on fresh build in new folder just now, to make sure it's not any weird setting leftover, I found out that games which have their custom config created during the first run(before exiting at least once) do not populate "recent" list, seems not related to new ui. Maybe @Bigpet could have a look at that.:3

**Comment by sum2012** [comment] 2015-01-11 23:06
Just a small note,I test Yu-Gi-Oh 6 crash with edit card

**Comment by unknownbrackets** [comment] 2015-01-11 23:12
Oh, cool, when did it start/end?  Is it that same BKPT thing?

-[Unknown]

**Comment by sum2012** [comment] 2015-01-11 23:17
I have to go to work.I cannot test deep now.
But I test disable JIT can temp solve the problem

**Comment by sum2012** [comment] 2015-01-12 14:05
@unknownbrackets git bisect result,this commit
https://github.com/hrydgard/ppsspp/commit/74d8a9bdba9b8348e60e8a6b40b01da26b5eb020

anyway, v0.9.9.1-1486-g7c3bc2b Android log
https://gist.github.com/sum2012/7a0d797f86f186782ed6

**Comment by unknownbrackets** [comment] 2015-01-13 02:27
Worst case I can think of is it's fiddling with instruction bits directly without rewriting the entire thing and we're jumping into space.  But in that case, was it just luck that it worked before?

Otherwise, we're probably not invalidating or clearing properly?  I guess?

-[Unknown]

**Comment by sum2012** [comment] 2015-01-13 05:31
@unknownbrackets it does not crash in windows,so that I do not think that it rated to invaliding and clearing.

**Comment by tiamat999** [comment] 2015-01-14 15:59
Edf 2 portable speed up?

**Comment by Bigpet** [comment] 2015-01-21 20:15
Just as a point of discussion since Minamoto-kun brought it up in the forums.

Fix Symbian regressions? (I don't really care since I don't have a symbian device but I think either dropping Symbian support or fixing these should be done)

[stasb-48 listed on the forums:](http://forums.ppsspp.org/showthread.php?tid=382&page=83) (currently still inquiring about details)

PPSSPP-v0.9.8-1149 - last version were save/load is work
PPSSPP-v0.9.9.1-49 - last version were on screen control buttons not cut off
PPSSPP-v0.9.9.1-186 - last version were videos are played

**Comment by sum2012** [comment] 2015-01-25 00:57
Hope today we can solve Online Chess Kingdoms black screen in latest version.
v0.9.8-46-g8b92dce work

**Comment by sum2012** [comment] 2015-01-25 01:05
oop,I tested before #6924

**Comment by vnctdj** [comment] 2015-01-26 23:48
@hrydgard What about improvements on the new savestate UI ? Will it be ready for v1.0 ? :)

**Comment by sum2012** [comment] 2015-01-27 23:20
@hrydgard Don't forget update font atlas,thanks

**Comment by sergiobenrocha2** [comment] 2015-01-28 01:06
@hrydgard , maybe could you include #3318 ? It stuck at all and becomes unresponsive now in git version, it seems in old versions you could press start button to skip access page.

**Comment by hrydgard** [comment] 2015-01-28 09:44
@sum2012 don't worry, I will :) Will do it just before release to make sure the latest translations are in.

**Comment by sum2012** [comment] 2015-01-28 13:05
Hope to solve #7386

**Comment by thedax** [comment] 2015-01-29 06:02
https://github.com/hrydgard/ppsspp/issues/7316 Fixing this would be lovely, since it's a regression.

**Comment by hrydgard** [comment] 2015-01-29 13:59
@thedax done.

**Comment by thedax** [comment] 2015-01-29 20:43
@hrydgard: Thank you.

**Comment by psennermann** [comment] 2015-01-29 21:41
Well as regression since last release there would also be #7336 , but at the moment it doesn't seem so easy to understand why ppsspp has got so much slowdown on PoverVR devices...

**Comment by 007flawless** [comment] 2015-01-29 22:11
Games like Obscure on PowerVR devices have serious Hooks and Hangs whenever u shoot Guns.. E.G: In Obscure, when u shoot a Gun, the game hangs for abt a second, then continues.. In Gunfights with monsters, it's really bad.. This can b fixed if Hardware Transform is disabled but it makes d overall game very slow.. 45 - 65% speed.. I hope this PowerVR issues are looked into

**Comment by 007flawless** [comment] 2015-01-29 22:12
Ohh.. And there is still the slow GTA games (which still don't display correctly on PowerVR using Buffered Rendering)

**Comment by hrydgard** [comment] 2015-01-29 23:14
Well, those would be nice things to fix, but won't make it into 1.0 unfortunately.

**Comment by 007flawless** [comment] 2015-01-30 00:59
Okk boss.. U're still the Best.. Appreciate all Efforts from u and all PPSSPP Devs 👍👏👏👏

**Comment by geenaxion** [comment] 2015-01-30 18:23
First of all thanks for a wonderful build. I don't know if this is just an isolated case but because my screen orientation are set to auto, when I changed the position of the screen when a game is on the screen goes black and hangs. Alhough it never happen before until recently.

**Comment by hrydgard** [comment] 2015-01-31 11:46
Strange, that works on my devices..

**Comment by geenaxion** [comment] 2015-01-31 13:19
It works fine before tho.
Don't know what caused it.

**Comment by geenaxion** [comment] 2015-01-31 13:19
It works fine before tho.
Don't know what caused it.

**Comment by geenaxion** [comment] 2015-01-31 13:19
It works fine before tho.
Don't know what caused it.

**Comment by sum2012** [comment] 2015-01-31 13:39
@geenaxion download old version
http://buildbot.orphis.net/ppsspp/index.php?m=fulllist
to find out which version started to have problem

**Comment by zackdreaver** [comment] 2015-01-31 14:40
Hi guys,
just want to report that i still getting crash when trying to enter fullscreen in d3d9
my build: 0.9.9.1-1623-g2df04ba

**Comment by hrydgard** [comment] 2015-01-31 14:42
Ugh. What GPU do you have, and does installing new drivers for it help?

On my machines fullscreen on d3d9 is solid.

**Comment by sum2012** [comment] 2015-01-31 14:48
@zackdreaver You may also need update directx 9 runtime http://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by zackdreaver** [comment] 2015-01-31 15:33
playing it in my netbook (1024x600 fullscreen)
latest driver and directx.

another try, sometime it not crash, just "hang" with sound ingame, then tried to enter window mode
"alt+enter" then it crash.

**Comment by sum2012** [comment] 2015-01-31 23:41
@zackdreaver Try change audio backend to DirectSound (required restart)

**Comment by zackdreaver** [comment] 2015-02-01 00:45
@sum2012
check this #7391 , that thing make my emulator crash.

**Comment by sum2012** [comment] 2015-02-01 09:16
@zackdreaver you maybe need install visual studio 2003 to give us crash struck to give us debug

**Comment by zackdreaver** [comment] 2015-02-01 09:51
@sum2012
sorry sir, afaik VS 2013 don't support winXP, i only have vc++ 2008 express
I really wish i can help with this bug.

Btw, the last build that work on fullscreen and direct sound is:
v0.9.9.1-1292-g2db9275

**Comment by sum2012** [comment] 2015-02-01 10:46
I have seem unknownbrackets tried to fix but fail.
Anyway,I can reproduce issue in vmware that installed in Windows XP

**Comment by sum2012** [comment] 2015-02-01 11:42
@zackdreaver Can you test this build ? It should revert to old behavior
https://drive.google.com/file/d/0B3OaSdeV0L8keGtLVDFqdHNudEE/view?usp=sharing

**Comment by zackdreaver** [comment] 2015-02-01 12:12
@sum2012
it's still crashing sir on any window size change

**Comment by sum2012** [comment] 2015-02-01 12:19
@zackdreaver Just a small update build that hrydgard remove a audio option in Windows XP
https://drive.google.com/file/d/0B3OaSdeV0L8kSTgyQ0VTVUlEejQ/view?usp=sharing

**Comment by sum2012** [comment] 2015-02-01 12:24
@zackdreaver Sorry,I don't have idea

**Comment by zackdreaver** [comment] 2015-02-01 12:33
@sum2012
it's okay sir, i really apreciate your help.

**Comment by sum2012** [comment] 2015-02-01 21:48
@hrydgard Cong finally v1.0
In the http://www.ppsspp.org
You should say "Temporarily drop Windows XP support"

**Comment by hrydgard** [comment] 2015-02-01 22:11
@sum2012 wait what? It doesn't work at all? It should! 

I don't have any XP machines though...

**Comment by sum2012** [comment] 2015-02-01 22:24
@zackdreaver can you confim again what problem now in directx 9 in windows xp ? (ppsspp v1.0)

**Comment by hrydgard** [comment] 2015-02-01 22:28
@sum2012 according to zackdreaver, it runs but crashes on window resize in D3D, and it should work fine in OpenGL on machines that can do that. So it's still usable but not great, heh.

I will look into the resizing problems more later, but I think it's at least playable on XP with some annoying workarounds..

**Comment by sum2012** [comment] 2015-02-01 22:44
@hrydgard ok

**Comment by zackdreaver** [comment] 2015-02-02 04:27
@hrydgard
hello sir,
so i just made a new test, when i set rendering mode to "non-buffered",
there is no crash.

**Comment by sergiobenrocha2** [comment] 2015-02-02 04:55
God Eater 2 (demo) no longer works in this new version, it crashes ppsspp. I could play it in 0.9.9.1.

**Comment by geenaxion** [comment] 2015-02-03 05:22
I have found out what seems to cause a black screen and freezes when orientation set to auto. 
It happens when texture scaling is set to auto, present on 0.9.9 and the latest build.

**Comment by hrydgard** [comment] 2015-02-03 09:49
@geenaxion , oh, good catch! I will investigate tonight.

**Comment by geenaxion** [comment] 2015-02-09 09:13
I was wondering if there is a way to hide the screenshot of the savestate on the gallery? Using android.

**Comment by hrydgard** [comment] 2015-02-09 09:57
No you can't - but why would you want to?

**Comment by geenaxion** [comment] 2015-02-09 10:11
I just thought of it. It's fine with me anyway. Thank you. :D

**Comment by thedax** [comment] 2015-02-12 07:36
We can close this, 1.0 has been out for 10 days now.

**Closed by thedax** 2015-02-12 07:36 UTC
