### ISSUE TITLE
6xBRZ 1.4 Update.

### ISSUE THREAD

**Issue by ADormant** [hrydgard/ppsspp#8013] opened 2015-09-28 06:16 UTC
https://sourceforge.net/projects/xbrz/files/xBRZ/

**Comment by unknownbrackets** [comment] 2015-09-28 06:33
This feels like as good enough place as any to mention that reporting shows desktop users with modern graphics cards are running out of video memory and switching the texture cache to "low memory mode."

-[Unknown]

**Comment by ADormant** [comment] 2015-10-30 18:54
@unknownbrackets @hrydgard @Zenju
Still it wouldn't hurt to update xBRZ to 1.4 for people with strong GPUs I can run 5xBRZ fine.

**Comment by ADormant** [comment] 2015-10-30 18:57
@unknownbrackets @hrydgard @Zenju
Still it wouldn't hurt to update xBRZ to 1.4 for people with strong GPUs I can run 5xBRZ fine even in Ishiiruka.

**Comment by ADormant** [comment] 2015-11-02 13:16
https://github.com/gonetz/GLideN64/commit/daf18efabbae16454c83562456a6cc19b53255a1
https://github.com/gonetz/GLideN64/commit/5bf7a4e4dea9bc7f1b0cb68db5781b386a5470b7
@unknownbrackets

**Comment by vgturtle127** [comment] 2015-12-06 14:53
@unknownbrackets @ADormant Actually, if I remember correctly xBRZ is actually a less resource intensive, lighter weight alternative to most other filters.

For instance, I can use HQ4X with massive slowdowns on SNES9X or Higan, but if I use xBRZ I get much faster speed. On mGBA the difference isn't so massive, but on VBA-M the difference is impressive. Then again, they all implement different versions of xBRZ, so updating to the latest version is probably best.

**Comment by unknownbrackets** [comment] 2015-12-06 15:04
What I'm saying is we already use xBRZ, and many desktop users are (probably unknowningly) setting it so high that their GPUs are running out of memory.  And 6x would require 44% more video memory, I suppose.

I'm not saying it shouldn't or can't be done, just saying that 6x gives some subset of desktop users a bigger shotgun to aim at their feet.  And honestly I'm not really sure that 6x will be significantly noticeable compared to 5x.  I mean, 5x is already higher resolution (for a full-screen texture) than 1080p.

-[Unknown]

**Comment by ADormant** [comment] 2015-12-06 19:22
Then maybe some kind of warning message about memory usage would suffice? At 4k or higher 5x is still quite low resolution for textures so 6x would help.

**Comment by vgturtle127** [comment] 2015-12-07 01:02
@unknownbrackets I agree, more than 4x usually is overkill for most systems. I think a warning and maybe some documentation would be a good idea.

**Comment by ADormant** [comment] 2015-12-23 21:42
@unknownbrackets How about texture cache for xBRZ scaler to increase performance like here http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/

**Comment by unknownbrackets** [comment] 2015-12-23 22:30
We already heavily cache xBRZ upscaled textures, and indeed all textures.  Our texture cache isn't even "lame" as that thing describes.

We also manage the amount of RAM to avoid going into "low memory mode", which is a mode of our texture cache where it throws things away much more quickly because your system is dangerously low on video memory.  We don't want this mode to be triggered, because PPSSPP may crash if you run out of video memory, or at least draw totally wrong, and things will get very slow.

-[Unknown]

**Comment by shinra358** [comment] 2017-06-04 19:38
10 years later, the wait continues : P

**Comment by vgturtle127** [comment] 2017-06-04 20:56
@shinra358 
Yeah, at the very least we need to update to the latest version. Please with sugar on top. 😃

**Comment by unknownbrackets** [comment] 2017-06-04 21:07
We're already using xBRZ 1.4 (#8338.)

I'm personally wholly uninterested in adding 6x texture scaling.  If I started messing with that code I'd be more likely to remove 5x.

-[Unknown]

**Comment by shinra358** [comment] 2017-06-04 21:11
Nothing has to be removed. Why cant it just have what everyone else has
that uses it? :P

**Comment by vgturtle127** [comment] 2017-06-04 21:47
@unknownbrackets 
Oh, alright. I guess I didn't realize, I usually keep up with the commit log of PPSSPP.

@shinra358 
There usually is no visible difference between 4x and 5x/6x. I usually use 3x just because I can't see much of a difference beyond that, for most games anyway.

**Comment by shinra358** [comment] 2017-06-04 21:58
5x has a bit more blur than 6x. 6x has bolder lines. 6x makes it look
better when youre running heavy shaders over it (because xbrz needs shaders
to look more awesome). Ive done plenty of these tests in retroarch, snes9x,
and epsxe. Some ppl can run 5x but not 6x. Xbrz is mostly for 2D elements
like sprites or hud graphics. Its not really for 3d. With that said if ppl
are worried about performance, an option can be coded for use w/2D elements
only.

Not only that, id like my gaming setup to match. If i have 6x in 95 percent
of the other emus, then id want the same quality here too.

**Comment by vgturtle127** [comment] 2017-06-04 23:50
@shinra358 
The reason I said what I said is because as far as I know, PPSSPP does it to 2D and 3D elements, so in some cases I thought it looked worse. I could be wrong, though.

And in general, having more options isn't a bad thing, I was just playing devil's advocate, and thinking aloud. 😃

**Comment by LunaMoo** [comment] 2019-06-23 01:02
Is it time, or not?
-----------------------
 Back when this issue was opened unknownbrackets was strongly against it and I respect that, so I'll not care about solving this if he's still against it, through I already updated the code for myself(by update I mean x6, not newer xBRZ which I guess didn't added anything new for PPSSPP). It only required adding higher scaling for bilinear and bicubic + ui stuff.

 As mentioned, we had x6 implemnted already for xBRZ from the 1.4 xBRZ merge just didn't exposed it to the users due to all the potential problems it's causing.


About the problems:
-----------------------
 I would not care much about video ram currently since modern gpu's have way more than few years ago, through I would understand such concern since many PPSSPP users tend to have a potato hardware due to generally low requirements. There are also cases which can eat up any kinds of Vram with texture scaling, but extreme cases shouldn't be decisive.

 I would worry more about performance through, modern multi-core highly clocked cpu's can handle texture scaling decently when it comes to xBRZ, however Hybrid and Hybrid+Bicubic are far more demanding and even with the strict limits will cause stutter/frame drops at least when using high scale multiplier and that of course leads to complains since many users assume their pc can handle everything they throw at it and don't even understand texture scaling is cached and ruins performance ocassionally, not constantly hence they often don't know the cause of the problems they're experiencing and assume PPSSPP is just awful.


 My opinion about x6 in PSP games:
-----------------------
 It is slightly sharper, but only on displays with 2880x1632 resolution or higher, at the same time it also has worse/uglier aliasing than x5 and doesn't really look objectively "better". In still most common standard 1080p it looks same and even at 4k the difference is subtle enough to not make visible difference without staring at screenshots.

**Comment by unknownbrackets** [comment] 2019-06-23 03:25
Well, people are already upscaling insane amounts and creating texture replacement packs with the same video memory problems, so I guess it's a bit less of a concern.  We also do more when we detect out of memory (though we still may definitely crash) by ratcheting down the texture scaling level.

That said, I still think people wanting 6x are comparing it to other things, like SNES.  Most SNES games are 256x224, so 6x is 1536x1344, and 5x is 1280x1120.  Compare to the PSP with 5x already at 2400x1360 (more than 6x SNES.)

But if people want it for 4K or something, I'm less against it now than 4 years ago.  But I still think it's overkill, and I still think some users will just naturally crank all the settings up to max (higher is better, right?) and then be confused when they get stutter and issues (and not even remember the setting.)

This would be generally much more interesting via #10393, but would probably mean some alpha-supporting upscale (such as xBRZ) being ported to a shader.  I think both the concerns (perf and OOM) would be handled much better that way.

-[Unknown]

**Comment by LunaMoo** [comment] 2019-06-23 16:11
Yeah comparing to other platforms is bad, especially snes-like which not only had much lower res, the scaling algorithm was pretty much designed for it's retro art style.

 Speaking of other ways, we also have #10818 which has some upscaling algorithms through compute shaders and is fast enough to work without hiccups in problematic games like Harvest Moon: Boy & Girl where limits skip scaling of many things.
 To compare I tried the same game with cpu based scaling just without limits and even while showing high FPS it does drop some frames whenever it has to scale more textures causing stutter even in the best case scenario of xBRZ limited to x2. So the problems it's causing aren't even reflected on FPS counter further confusing the users into thinking their pc's are fast enough.

**Comment by shinra358** [comment] 2019-06-23 16:26
i would like this to be in the menu not just hidden in the files. that
would mean id have to go in every game profile and change it manually. i
dnt see how ill have a problem considering the emu is the fastest emu ive
ever seen on 10x rez. If you guys are uncertain, all u gotta do is put a
note bside the options saying you need high video memory or experimental. i
myself have 8gb on my laptop.

**Comment by shinra358** [comment] 2019-06-23 16:44
not to mention we really need that bit off that's making the xbrz apply to
the image late. theres always pixelation for a full second b4 we see the
xbrz being applied. users should b able to control that themselves for this
is the only emu that has this issue. and watching the sprites in sfa3
constantly go pixelated back to smooth back to pixelated over and over
again is annoying.

**Comment by LunaMoo** [comment] 2019-06-23 16:45
I think other ways are the road to take as [Unknown] says so I'm not opening a PR with x6 here. Even with limits, frametime is pretty awful when scaling happens and just spreads on more frames, but can still lead to ocassional stutter in some games, increasing the multiplier just makes it worse and using scaling method like hybrid with high scale pretty much guarantees stutter in most games.

 Meanwhile gpu based scaling can do much more work in realtime with great frametime.
![ULUS10142_00004](https://user-images.githubusercontent.com/5485237/59979275-e398c480-95e5-11e9-89e1-b2c47586dd1d.jpg)
The scale of the frame profiling is 1ms here and user would not experience any stutter with it as long as the gpu is decent.

**Comment by LunaMoo** [comment] 2019-06-24 00:16
@shinra358 I disagree completely about even using texture scaling in  "Street Fighter" that you mentioned, it causes tons of glitches due to bleeding over between tiles within each texture.

 Post process shader is much better way to go in such games.
 I just modified 5xBR to work without standard upscaling, that is to be wasteful by keeping high render res to work around filtering smoothing in ports from older platforms and alsp to easily allow modifying the factor to match reduced texture size and it works and looks much better than texture scaling ever could.
This is a post process shader:
![ULUS10062_00003](https://user-images.githubusercontent.com/5485237/59983853-532da480-9624-11e9-9b46-72557440bcf1.jpg)

And this is the glitchfest from texture scaling:
![ULUS10062_00006](https://user-images.githubusercontent.com/5485237/59983982-9fc5af80-9625-11e9-92cd-9541332959fb.jpg)

 The shader might still need some tweaking as I guessed the factor since I don't remember PSOne res and will have to google it;p, but it's definitelly better than the glitchfest from the texture scaling could ever be.

**Comment by unknownbrackets** [comment] 2019-06-24 00:28
I wish there was a realistic method to detect 2D drawing, because then we could have an "auto" upscaling setting that automatically used a post shader or texture scaling as appropriate.

There are definitely some glitches that are very hard to avoid with texture scaling, mainly for 2D drawing.  Realistically, though, it's also a problem for HUDs (mixed 2D/3D), which is hard to solve with a post shader...

I didn't realize that D3D9 pull had ported versions of xBRZ with alpha support (or more likely, I forgot that it did.)

-[Unknown]

**Comment by shinra358** [comment] 2019-06-24 00:42
@luna  xbr is way too playdoughy. the only 'glitch' i see is the small
pivots in the lifebar which is nothing. and those do not exist when using
xbrz on the same game on other platforms. and just playing the other
version on the other platform is not a solution bcuz this is the best
version of the game. also the one second of pixelation before xbr or xbrz
still happens in the middle of animations on that game regardless of which
method is chosen. that minor lifebar issue could probably be fixed by
texture injection but texture injection can be used for everything else in
that game bcuz of the dozens of animations per character is too muxh to
deal with. ive nvr seen texture injection done in 2d fighters yet. probably
for that reason.

**Comment by LunaMoo** [comment] 2019-06-24 08:03
Lifebars aren't the only glitchy elements, whole stage and characters have such glitches, it doesn't depend on platform and other scaling methods are adaik even worse with it. The only reason it might look better for you is if it's not scaled, my screenshot with glitches is with scaling limits disabled. It's also less playdoughty only because glitches add sharp corners and lines of different color. It's awful.

**Comment by benderscruffy** [comment] 2022-12-11 09:57
is this going to be implemented ???

**Comment by unknownbrackets** [comment] 2022-12-11 17:32
I don't see any point these days.  5x CPU upscaling is already incredibly demanding and causes hitching and input lag on even powerful PCs, 6x would be 44% worse.  GPU based upscaling is obviously smarter - if someone wants 6x upscaling it'd be much better to find/contribute a 6x GPU-based texture upscaler.

-[Unknown]

**Comment by benderscruffy** [comment] 2022-12-13 10:35
ok please close it then

**Comment by hrydgard** [comment] 2022-12-13 10:46
I agree, I think it'll be more interesting to implement GPU upscaling for more backends, and more methods, and then possibly remove CPU upscaling entirely.

**Closed by hrydgard** 2022-12-13 10:46 UTC
Labels: Feature Request
