### ISSUE TITLE
Clickable areas become dislocated when switching to Fullscreen Mode in the menu with 1x Window Size

### ISSUE THREAD

**Issue by internetakias** [hrydgard/ppsspp#7792] opened 2015-05-31 16:46 UTC
PPSSPP version: v1.0.1-558-g268aed4
OS: Windows 7 64-bit
Resolution: 1920x1080
Graphics Card: Nvidia GTX 760
Backend: Open GL (Occurs in DirectX 9 also)
Basically what the title says. When you switch to fullscreen mode with the window size set to 1x, the clickable areas shift out of position from the buttons on screen, so trying to click on a button doesn't seem to work or return the desired result, while clicking at random positions on the screen sometimes triggers a function.
I suspect this may be because when switching to fullscreen in 1x the menu looks like this:
![menu_00000](https://cloud.githubusercontent.com/assets/5077063/7902773/81b1953a-07cd-11e5-9b09-9a75a009f079.png)
While with any other window size it looks like this:
![menu_00001](https://cloud.githubusercontent.com/assets/5077063/7902774/a9ec3aaa-07cd-11e5-8f63-77f89bbf5f4f.png)

**Comment by vsub** [comment] 2015-06-01 03:16
This was fixed once but I guess the problem is back again
v1.0.1-478-g5b75d5d 	- works fine
v1.0.1-485-g83182a0 - problem exist

Start ppsspp and switch to 1x window size and then press F11

**Comment by hrydgard** [comment] 2015-06-01 09:26
Thanks, I will have a look soon.

**Comment by unknownbrackets** [comment] 2015-12-20 03:35
I think this has been fixed already.  Please comment if you're still experiencing.

-[Unknown]

**Closed by unknownbrackets** 2015-12-20 03:35 UTC

**Comment by internetakias** [comment] 2016-01-27 09:56
It's been fixed
