### ISSUE TITLE
Sloooooow

### ISSUE THREAD

**Issue by ahmedyousry10000** [hrydgard/ppsspp#8707] opened 2016-04-23 16:20 UTC
hi
i have iphone 6s plus ios 9.1 jailbreak ...
pes 11/wwe/assassins creed  are toooooooo slow i don't know why 
except dragon ball z another road it's good for a while then it turns slow too
if this problem from my device or from emulator 
plz help me :)

**Comment by Anuskuss** [comment] 2016-04-23 18:12
#8122

**Comment by unknownbrackets** [comment] 2016-04-23 19:03
This issue is being closed as a duplicate of #8122.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-04-23 19:03 UTC

**Comment by ahmedyousry10000** [comment] 2016-04-23 20:31
;)
