### ISSUE TITLE
PPSSPP closes out after briefly showing a black screen when I try to create a save state in Yu-Gi-Oh! Arc-V Tag Force Special on my Android phone.

### ISSUE THREAD

**Issue by NaturalHarmonia** [hrydgard/ppsspp#10003] opened 2017-10-06 18:31 UTC
I'm using PPSSPP for the Android version 1.4.2 and I've been having this abrupt issue since yesterday. All my settings are the default settings.

**Comment by blackman91** [comment] 2017-10-07 00:47
Have you tried the latest dev build?

**Comment by NaturalHarmonia** [comment] 2017-10-07 01:14
What latest dev build? I downloaded the .apk from [here](https://ppsspp.org/downloads.html).

**Comment by blackman91** [comment] 2017-10-07 01:44
Download from here latest dev:
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by NaturalHarmonia** [comment] 2017-10-07 12:05
I'm still having the same problem even though I downloaded the latest android build.

**Comment by NaturalHarmonia** [comment] 2017-10-08 10:36
I think I found a solution. I disable Fast Memory from System and haven't had the problem since. [This](http://forums.ppsspp.org/showthread.php?tid=17492) thread helped me.

**Comment by hrydgard** [comment] 2017-10-08 17:26
More of a workaround than a solution, there's clearly some bug involved...

**Comment by NaturalHarmonia** [comment] 2017-10-09 01:22
I don't use PPSSPP on PC but I'll try when I get the chance.

**Comment by NaturalHarmonia** [comment] 2017-10-19 22:48
It didn't happen on the PC.

**Comment by unknownbrackets** [comment] 2017-11-12 19:04
Which Android device?  I wonder if this is a bug with the jit somehow.

Has it always happened in this game, or does it only happen when save stating from a certain area?

And to confirm: it crashes after CREATING a save state, not when loading, right?  This implies a bug in the save state creation, so just want to make sure.  It's strange that such a bug wouldn't affect PC since all the code is the same.

-[Unknown]

**Comment by hrydgard** [comment] 2018-03-24 15:16
@NaturalHarmonia  does this still happen on the latest builds?

**Comment by unknownbrackets** [comment] 2018-03-25 19:19
This, #10028, and #10044 seem related.  The latest one was closed, and we haven't gotten any feedback here.  It's possible all of these were caused by hashmap bugs we've since fixed (which included a memory leak, I think.)

I'm going to close this now, but please comment with more details if it's still an issue.

-[Unknown]

**Closed by unknownbrackets** 2018-03-25 19:19 UTC
Labels: No Feedback / Outdated?
