### ISSUE TITLE
Asphalt 2: Glowing things draw through roads and walls (also range culling, worked around)

### ISSUE THREAD

**Issue by SecularSteve** [hrydgard/ppsspp#14299] opened 2021-03-16 19:58 UTC
### What happens?

Easier just to show a link to a self-evident recording (sorry about the size, quality and all that), along with a screenshot:

https://ufile.io/ev5r1gux

![ULES00719_00002](https://user-images.githubusercontent.com/33793273/111369684-a61c7a80-8697-11eb-83ea-f1c531dba55f.jpg)

Basically, the artifacts still render weirdly (or disappear for a fraction of a second) when they get to the edges of the screen, some glowing items are visible through the walls where they shouldn't be, and shadows give some weird effects in some maps.

### What *should* happen?

None of the above.

### Include a GE frame capture

[DUMP.zip](https://github.com/hrydgard/ppsspp/files/6151843/DUMP.zip)

#### What hardware / device and operating system?

Intel i5-4200M 2.5 GHz
Windows 10

#### What graphics card (GPU) or mobile phone model?

Intel HD Graphics 4600

#### What PPSSPP version (standalone/official), and did it work before?

1.11.3
Same as in 1.9 (playable, but glitchy)

#### Which game or games?

ULES00719 - Asphalt Urban GT 2

#### Graphics backend (Vulkan, OpenGL, etc.)?

DirectX11 at 1x resolution (frameskip set to auto)

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Try changing graphics settings to determine if one causes the bug.
 - [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2021-03-16 20:32
The little triangular glitches are almost certainly an instance of the "Range culling" problem, where we don't yet understand perfectly why triangles that reach outside the clipping box should not get culled in some situations. 

I'll try the usual workaround shortly.

**Comment by SecularSteve** [comment] 2021-03-16 20:59
Thanks for responding immediately.
I myself own a still working soft-modded PSP-1008 (with a broken analogue unfortunately).
So really, I can confirm which things should and shouldn't be there.

I just have a couple of questions (if you don't mind answering):
-Is PPSSPP 2.0 going to have that tiny little video preview you get in the thumbnails on the normal PSP?
-Is it also going to have the option to run a BIOS (because I want this to be included, or at least a replica variation of it):
https://www.youtube.com/watch?v=ulb6Ic4517g

**Comment by hrydgard** [comment] 2021-03-16 22:55
The latest build from https://buildbot.orphis.net/ppsspp/ should have the workaround now, please test.

The little video previews I've been meaning to do for a long time, there's just always been more important things to do. At least the sound is there if you hold-press or rightclick a game (or keyboard navigate to it).

As for the XMB, this question has been answered many times - PPSSPP's main focus is playing the games, and getting the XMB to work is a lot of extra work that is not likely to be useful for running games. So, it's not gonna be prioritized, similarly to the video clips...

**Comment by SecularSteve** [comment] 2021-03-17 00:16
Well, now it mostly looks as it should (but the literal glow of the items can still be seen through objects).

![ULES00719_00004](https://user-images.githubusercontent.com/33793273/111395836-150cca00-86be-11eb-9e4e-a73983ca9249.jpg)
![ULES00719_00005](https://user-images.githubusercontent.com/33793273/111395839-15a56080-86be-11eb-9092-f7c3da26a72f.jpg)

Maybe it's a "render distance set to high" thing or something. Because I notice that the glows render only if you're close by on the PSP.

What I'm really curious about is what kind of disadvantages the workaround impedes?

**Comment by hrydgard** [comment] 2021-03-17 08:29
Oh, yeah the glow-shining-through issue is not fixed and a separate bug, but at least the very distracting triangular glitches are gone, so that's a plus for playability. 

There aren't really any disadvantages. Here's the problem: Triangles that have one corner far outside the screen are discarded by the PSP in some circumstances. Some games rely on that, like the DTM Race Driver series - without this behavior, the screen is full of glitches. 

Unfortunately there seems to be many factors that affect whether triangles are discarded or not, the PSP has some kind of clipping that we don't really know how it works that can reduce the size of these triangles. Our logic for this is not perfect and thus some games will get triangles discarded that shouldn't be. 

So for now, the games affected by that we add to a list, and disable discarding triangles in them. Usually there are no negative effects.

**Comment by Panderner** [comment] 2021-09-08 02:03
I tried to create GE dump for Asphalt Urban GT 2 unfortunately the frame dump is corrupted and only creates black screen image and the file size is 2KB.

**Comment by Gamemulatorer** [comment] 2021-09-08 05:08
This game is lag on selection :(
![Screenshot_2021-09-08-13-04-11-777_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132449780-b4f24376-8070-4729-b91a-4d05de67d57b.jpg)
![Screenshot_2021-09-08-13-05-23-373_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132449792-7799abf6-82ca-4ce4-b0fa-8a61be518660.jpg)
[selection.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7126013/selection.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2021-09-08 05:09
This is not related to https://github.com/hrydgard/ppsspp/issues/11013?

**Comment by Panderner** [comment] 2021-09-08 05:18
> This game is lag on selection :(
> ![Screenshot_2021-09-08-13-04-11-777_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132449780-b4f24376-8070-4729-b91a-4d05de67d57b.jpg)
> ![Screenshot_2021-09-08-13-05-23-373_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132449792-7799abf6-82ca-4ce4-b0fa-8a61be518660.jpg)
> [selection.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7126013/selection.ppdmp.zip)

Works fine in these sections:
![Screenshot_2021-09-08-13-17-07-812_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/132450638-337bcb55-8ba2-493b-ba8a-dca80f76931a.jpg)
![Screenshot_2021-09-08-13-17-13-516_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/132450642-7d960d7f-869f-4100-83c2-a2cb7ac7127f.jpg)

**Comment by Panderner** [comment] 2021-09-09 17:03
> Panderner because your android version is not 11 🤔

@Gamemulatorer Have you lowered the resolution to 1x and tried an older version of PPSSPP? Maybe it's not related to Scoped Storage.

**Comment by Gamemulatorer** [comment] 2021-09-09 17:25
> > Panderner because your android version is not 11 🤔
> 
> @Gamemulatorer Have you lowered the resolution to 1x and tried an older version of PPSSPP? Maybe it's not related to Scoped Storage.

It's ok now after updating my ppsspp to latest git 🤔
![Screenshot_2021-09-10-01-24-17-234_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132733316-b8380041-6e03-4f6a-bb66-1223d8368cd7.jpg)

**Comment by MojoJojoDojo** [comment] 2022-07-17 12:23
I have a feeling that this game uses the same engine as Street Riders...
So its basically the same as https://github.com/hrydgard/ppsspp/issues/14746

**Comment by hrydgard** [comment] 2022-07-17 14:09
This is a case where two framebuffers share the same depth buffer, but the blit from one to the other doesn't happen since we only do that blit when switching *directly* between two framebuffers with the same depth buffer (we don't directly share depth buffers because stencil is merged with depth on PC but not on PSP).

```c++
	if (prevVfb && !isClearingDepth) {
		BlitFramebufferDepth(prevVfb, vfb);
	}
```

It draws the arrows to a different framebuffer but expects testing against the main depth buffer.

Quite fixable, but a risky fix with some potential additional overhead in games that don't actually need it. Maybe yet another 
 compat flag...

**Comment by unknownbrackets** [comment] 2022-07-17 14:32
I definitely did the direct depth switching thing to be most cautious and thinking about perf.

My suspicion is that copying depth from A -> C when B is rendered in between would be pretty safe from a regression perspective (though, you never know) but would just have perf risk.  However, if any backend copies stencil while copying depth, that's a different story.

Feasibly, we could untether it from the actual switch event.  The most optimal thing MIGHT be to copy the depth prior to the first flush (if any) that reads or writes depth, from the most recent vfb with a matching z_address where a write (or copy) happened.  That might actually skip copies in some games.

-[Unknown]

**Comment by hrydgard** [comment] 2022-07-17 18:18
Yes, only doing the copy once depth is accessed would probably be the best indeed. Though, a little more involved, so feel like we can start with #15700 (or at least after 1.13) .

**Comment by Gamemulatorer** [comment] 2022-08-01 03:00
@Panderner can you test this game again?

**Comment by Panderner** [comment] 2022-08-01 07:35
Glowing through walls are gone
![Screenshot (9)](https://user-images.githubusercontent.com/37503397/182097081-3dae2c3b-f562-4f89-b189-9369fe91383c.png)

**Closed** 2022-08-01 07:46 UTC
Labels: Guardband / Range Culling
