### ISSUE TITLE
Capcom Classics Collection Reloaded - Black screen when exiting game 

### ISSUE THREAD

**Issue by arnoldsecret** [hrydgard/ppsspp#12535] opened 2019-12-29 04:44 UTC
### What happens?
Exiting the game after stats count will result in a black screen.

### What *should* happen?
It returns to the menu as normal.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Intel Core i7-4500U
NVIDIA GeForce 740M
Windows 10 Pro x64
PPSSPP 1.9.3 Stable

**Comment by unknownbrackets** [comment] 2020-01-01 22:56
This issue is being closed as a duplicate of #4671.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-01-01 22:56 UTC
