### ISSUE TITLE
crisis core ff7

### ISSUE THREAD

**Issue by luchi88** [hrydgard/ppsspp#7471] opened 2015-02-13 02:11 UTC
need a fix for crisis core ff7 after pressed new game,the game freeze and wont work unless if u di not load a external save state

**Comment by vsub** [comment] 2015-02-13 04:33
Works fine here(v1.0-38 x86)
Which ppsspp version are you using and on which device

**Comment by unknownbrackets** [comment] 2015-02-13 04:44
Almost sure this is a duplicate of #7360.

-[Unknown]

**Comment by luchi88** [comment] 2015-02-13 08:32
im using an iphone 6 "dev latest 0v1.0-53-g6f0ae8f, its a problem that persist in other versions to from cydia...i got the gold version for android and no problem there!

Inviato da Yahoo Mail su Android

Da:"vsub" <notifications@github.com>
Data:Ven, 13 Feb, 2015 alle 4:34
Oggetto:Re: [ppsspp] crisis core ff7 (#7471)

Works fine here(v1.0-38 x86)
Which ppsspp version are you using and on which device

**Comment by unknownbrackets** [comment] 2015-02-13 08:50
Then yes, definitely a duplicate.

-[Unknown]

**Closed by unknownbrackets** 2015-02-13 08:50 UTC

**Comment by luchi88** [comment] 2015-02-13 09:06
What do u mean sorry? Duplicate of what?

Inviato da Yahoo Mail su Android

Da:"Unknown W. Brackets" <notifications@github.com>
Data:Ven, 13 Feb, 2015 alle 8:50
Oggetto:Re: [ppsspp] crisis core ff7 (#7471)

Then yes, definitely a duplicate.

-[Unknown]

**Comment by Bigpet** [comment] 2015-02-13 09:24
It means that this is the same bug as issue https://github.com/hrydgard/ppsspp/issues/7360 
If you want to know when anything about this changes then subscribe to that issue
There's no reason to keep two issue reports of the same issue open.

**Comment by luchi88** [comment] 2015-02-13 09:30
well i got it..but if is the second time that this bag is been reported why has still not being fixed? i actually think this bug is on from long time

Inviato da Yahoo Mail su Android

Da:"Peter Tissen" <notifications@github.com>
Data:Ven, 13 Feb, 2015 alle 9:24
Oggetto:Re: [ppsspp] crisis core ff7 (#7471)

It means that this is the same bug as issue #7360 
If you want to know when anything about this changes then subscribe to that issue
There's no reason to keep two issue reports of the same issue open.

**Comment by Bigpet** [comment] 2015-02-13 09:38
>if is the second time that this bag is been reported why has still not being fixed?

It's the 8th time on Github I think. As for why it's not fixed, no one is actively maintaining iOS version and its apparently related to the different jailbreak methods or some other very iOS specific thing.
