### ISSUE TITLE
Every time I leave the emulator, this force closes

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13336] opened 2020-08-26 10:35 UTC
### What happens?

Hello.

Every time I finish playing a game and want to exit the emulator, I hit it where it says "come out to the menu", but it does not close and returns me to the launcher.

When this happens many times, the administrator of power apps sends me this error:

![1598436986447_Screenshot_20200826-111659_Device care](https://user-images.githubusercontent.com/65356692/91292827-5b88ee80-e797-11ea-8ed0-0653e0230f9f.jpg)

### What *should* happen?

Don't let this happen.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 10 Plus.

**Comment by hrydgard** [comment] 2020-08-26 11:31
Yeah, this is likely the same as #13223 . Will fix soon.

**Comment by hrydgard** [comment] 2020-08-26 11:32
Duplicate of #13223

**Closed by hrydgard** 2020-08-26 11:32 UTC
Labels: Platform-specific (Android)

**Comment by MiguelCardonaG** [comment] 2020-08-27 09:02
Ok, thanks.
