### ISSUE TITLE
Sengoku Musou 3 Z Special freeze and force close

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#12386] opened 2019-10-05 11:50 UTC
Always force close when you are selecting the DLC skin to start game.
Sometimes force close or freeze where as shown in the picture.
![TIM截图20191005194838](https://user-images.githubusercontent.com/5364709/66254497-7af6e180-e7a9-11e9-9920-f1c905b6427b.png)
This is the unlock character edit color scene.
In this scene, the chances are high that it will freeze or force close ppsspp when you move marquee from a character to another character.
![TIM截图20191005194944](https://user-images.githubusercontent.com/5364709/66254538-1d16c980-e7aa-11e9-8018-7c6d88afde16.png)
This is the character edit color scene.
In this scene, sometimes it will freeze or force close ppsspp when you move marquee from a character to another character. 
![333](https://user-images.githubusercontent.com/5364709/66254864-02931f00-e7af-11e9-9ab8-049b41428e64.gif)
You can see a map error when you move marquee from a character to another character in a flash.
https://img.vim-cn.com/de/56b4bc890c8499f91a68dcc710df052c21c0d5.gif

**Comment by Saramagrean** [comment] 2019-10-05 16:55
Duplicate https://github.com/hrydgard/ppsspp/issues/9993 ?

**Comment by unknownbrackets** [comment] 2019-10-05 17:10
This issue is being closed as a duplicate of #9993.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-10-05 17:10 UTC

**Comment by leoxxx** [comment] 2019-10-06 02:22
Editing color mode error is the same issue as the DLC?
