### ISSUE TITLE
Chat box iOS ppsspp not functioning v1.11.2

### ISSUE THREAD

**Issue by dmajor77** [hrydgard/ppsspp#14268] opened 2021-03-06 06:52 UTC
### What happens?
Chat box doesn’t function right. Plus if you try to exit out the chat it won’t let you exit or press anything else but the chat box quick messages 1,2,3,4. I have to restart the app 

### What *should* happen?
The chat box doesn’t have a letter typing system. It only have quick messages ex 1,2,3,4. That’s the only function tab.. it should exit out the chat when touch another part of the screen. Plus add a full letter display to type 
![A3708CBC-A173-4087-B271-920ABC2A7B6B](https://user-images.githubusercontent.com/63882139/110198123-3c41dc80-7e1e-11eb-8c1d-db81bc578e0b.jpeg)

### 1.11.2.301, ppsspp iOS Apple a10, iPhone 7Plus , gpu power vr 6

**Comment by unknownbrackets** [comment] 2021-03-12 06:49
Not having a text box is already #13065.

Not being able to close things anymore is strange, but is being tracked in #14240.

This issue is being closed as a duplicate of the above.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-03-12 06:49 UTC
