### ISSUE TITLE
Yu-Gi-Oh GX Tag Force graphic bug (card cut-off / cropped)

### ISSUE THREAD

**Issue by metaasza** [hrydgard/ppsspp#7501] opened 2015-02-18 16:55 UTC
When the card is summoned, the head of the card is disappear and the duel point table's text is also missing. Sorry if this post was annoying but I don't know how to do as I am a very newbie.

Thank you very much

I use Samsung Galaxy S III (GT-i9300)

PPSSPP Android version v1.0-80-ge89c881

![image](https://cloud.githubusercontent.com/assets/10046089/6251937/64d0df42-b7c9-11e4-9343-50d1e64403e5.jpg)

**Comment by ofek007** [comment] 2015-02-20 19:06
I have a problem too with this game, started playing yesterday.
When I duel with any character, the field and the summoned cards become invisible:
![screenshot_2015-02-20-21-02-43 1](https://cloud.githubusercontent.com/assets/11095211/6307386/eed74b6a-b943-11e4-9ee5-cdefad194bc8.png)
My device is Samsung Galaxy S2 Plus I9105,
PPSSPP version is: 1.0.0
Thank you!

**Comment by Warriors-Blade** [comment] 2015-04-19 21:42
Here is the screenshots and settings from the GE Debugger regarding the card cut off issue,

![Uploading Untitled 2.png . . .]()
![Uploading Untitled 3.png . . .]()
![Uploading Untitled 4.png . . .]()
![Uploading Untitled.png . . .]()

and here are the GE Debugger settings,

**Comment by Warriors-Blade** [comment] 2015-04-19 22:10
Here is the shots I took from the GE Debugger

![Uploading Untitled 4.png . . .]()
![Uploading Untitled 1.png . . .]()
![Uploading Untitled 2.png . . .]()
![Uploading Untitled 3.png . . .]()

**Comment by unknownbrackets** [comment] 2016-01-28 04:13
@metaasza please don't open duplicate issues, it just spreads out information and makes things get fixed slower.  It also makes people less interested because it forces e.g. me to waste time reading duplicate issues, merging them, etc. instead of writing code that might actually fix it.

Closing this as a duplicate of #7124.

-[Unknown]

**Closed by unknownbrackets** 2016-01-28 04:13 UTC

**Comment by TradeDraft** [comment] 2020-11-25 00:10
I still have the Same Problem with the latest PPSSPP Official Release 1.10.3

**Comment by hrydgard** [comment] 2020-11-25 08:06
@TradeDraft The fix will be in 1.11.0 . And also in the work-in-progress builds you can find in https://buildbot.orphis.net/ppsspp/

**Comment by TradeDraft** [comment] 2020-11-25 09:38
> 
> 
> @TradeDraft The fix will be in 1.11.0 . And also in the work-in-progress builds you can find in https://buildbot.orphis.net/ppsspp/

Thanks for the Reply and Great News you Fixed it mate
