### ISSUE TITLE
Silent Hill Shattered Memories - Memory Stick issue does not contain my profile save data

### ISSUE THREAD

**Issue by ElGalleg0** [hrydgard/ppsspp#19275] opened 2024-06-17 21:24 UTC
### Game or games this happens in

ULES-01352 - Silent Hill Shattered Memories

### What area of the game / PPSSPP

What happens is that when you want to save for the first time it saves normally, however, when you want to overwrite your save, it says "The Memory Stick already inserted does not contain the saved data of your profile. Insert again the Memory Stick that contains the saved data of your profile". It is as if you cannot overwrite the save.

This error as far as I have seen only affects android, I have tried on Windows and it does not occur. I have tried everything to solve it, try restarting the emulator, try uninstalling and reinstalling the emulator, try with other builds, also try to change the repositories of the most appropriate saves (similar to how they are in Windows), even if you delete and make new saves does not work.

![image](https://github.com/hrydgard/ppsspp/assets/173102947/461f5ecb-de55-4dae-92ff-e40307aad679)

I could try making savestates, but what happens is that this problem goes further and also does not let you save the photos taken with the game phone, a central element of the game and when you take the picture and try to save it you get stuck in the error box. 

I hope you can please help me and tell me what is happening, I saw that a similar error happens in Monster Hunter Freedom Unite, however the solution to this did not work when I tried with Silent Hill Shattered Memories. 

### What should happen

You should save normally, either in the start menu or using the cell phone. It should also let you take pictures normally and save them.

### Platform

Android

### Mobile device model or graphics card (GPU)

Adreno 610

### PPSSPP version affected

v1.17.1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by anr2me** [comment] 2024-06-17 23:54
Have you tried changing the I/O Timing method?

**Comment by ElGalleg0** [comment] 2024-06-18 02:33
> Have you tried changing the I/O Timing method?

Actually no, until you wrote that message, I tried all the options like "Simulate UMD Delays." and nothing changed, it's a bit frustrating since the PSP version is the one with the best controls for mobile devices.

**Comment by hrydgard** [comment] 2024-06-19 18:46
Hm, likely some kind of file attribute / permission issue, where the semantics of Android scoped storage doesn't match what the game expects well enough. Will try to look into it soon.

**Comment by ReallySmallNasX** [comment] 2024-07-02 05:09
![IMG_0701](https://github.com/hrydgard/ppsspp/assets/121740670/4c6a298e-da73-4e2f-800f-d324d6e5821e)
Same problem happens on iOS when I attempt saving

**Comment by anr2me** [comment] 2024-07-02 07:25
Btw, is this issue occurred on standalone version or libretro? or both?

**Comment by ElGalleg0** [comment] 2024-07-05 22:53
> Btw, is this issue occurred on standalone version or libretro? or both?

Both.

**Comment by hrydgard** [comment] 2024-07-14 14:10
Looks like a duplicate of #13781 , and also affects iOS. Closing (but will try to fix it).

**Closed by hrydgard** 2024-07-14 14:10 UTC
Labels: Saving issue, Platform-specific (Android), Scoped Storage
