### ISSUE TITLE
Libretro build fails on s390x

### ISSUE THREAD

**Issue by lgbaldoni** [hrydgard/ppsspp#14401] opened 2021-04-23 11:54 UTC
### What platform, compiler, and build tools?

openSUSE Leap 15.3, gcc 7.3.3, s390x arch.
Current (2021-04-22) git version.

### What happens (don't forget logs)?

`error: ambiguous overload for 'operator%' `, see full [build log](https://github.com/hrydgard/ppsspp/files/6365034/libretro-ppsspp_s390x.txt).

I do realise it's not the most common target, but I'm trying to get this fixed for the upcoming openSUSE Leap release and ideally it should build everywhere.

**Comment by Panderner** [comment] 2021-04-23 12:10
What hardware are you using?

**Comment by ANR2ME** [comment] 2021-04-23 12:20
May be `MT_SIZE` not recognized as an `int`?
`
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: error: ambiguous overload for 'operator%' (operand types are 'swap_struct_t<unsigned int, swap_32_t<unsigned int> >::swapped_t {aka swap_struct_t<unsigned int, swap_32_t<unsigned int> >}' and 'MersenneTwister::<unnamed enum>')
   index_ = (index_ + 1) % MT_SIZE;
            ~~~~~~~~~~~~~^~~~~~~~~
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(long unsigned int, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(long int, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(s32 {aka int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(u32 {aka unsigned int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(s64 {aka long long int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(u64 {aka long long unsigned int}, int) <built-in>
`

**Comment by lgbaldoni** [comment] 2021-04-23 12:38
> What hardware are you using?

I'm running the build on [OBS](https://build.opensuse.org), I think it's emulated via kvm.

> May be MT_SIZE not recognized as an int?

I bet it's some quirk of that architecture/toolchain. Is there a simple way to test that hypothesis?

**Comment by ANR2ME** [comment] 2021-04-23 12:44
>
> > May be MT_SIZE not recognized as an int?
> 
> I bet it's some quirk of that architecture/toolchain. Is there a simple way to test that hypothesis?

May be changing `index_ = (index_ + 1) % MT_SIZE` to `index_ = (index_ + 1) % (int)MT_SIZE`

**Comment by lgbaldoni** [comment] 2021-04-23 13:02
No apparent change:
```
Scanning dependencies of target Core
[ 56%] Building CXX object CMakeFiles/Core.dir/Core/MIPS/IR/IRCompALU.cpp.o
In file included from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/MIPS.h:24:0,
                 from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/IR/IRCompALU.cpp:20:
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h: In member function 'uint32_t MersenneTwister::R32()':
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: error: ambiguous overload for 'operator%' (operand types are 'swap_struct_t<unsigned int, swap_32_t<unsigned int> >::swapped_t {aka swap_struct_t<unsigned int, swap_32_t<unsigned int> >}' and 'int')
   index_ = (index_ + 1) % (int)MT_SIZE;
            ~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(long unsigned int, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(long int, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(s32 {aka int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(u32 {aka unsigned int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(s64 {aka long long int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:52:25: note: candidate: operator%(u64 {aka long long unsigned int}, int) <built-in>
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h: In member function 'void MersenneTwister::gen()':
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:66:27: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
    uint32_t y = (mt_[i] & 0x80000000) + (mt_[(i + 1) % MT_SIZE] & 0x80000000);
                           ^~~~~~~~~~
In file included from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:4:0,
                 from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/MIPS.h:24,
                 from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/IR/IRCompALU.cpp:20:
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Swap.h:473:3: note: candidate 1: S operator&(const swap_struct_t<T, F>&, const S&) [with S = unsigned int; T = unsigned int; F = swap_32_t<unsigned int>]
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Swap.h:308:12: note: candidate 2: swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = unsigned int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
In file included from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/MIPS.h:24:0,
                 from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/IR/IRCompALU.cpp:20:
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:66:67: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
    uint32_t y = (mt_[i] & 0x80000000) + (mt_[(i + 1) % MT_SIZE] & 0x80000000);
                                                                   ^~~~~~~~~~
In file included from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Data/Random/Rng.h:4:0,
                 from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/MIPS.h:24,
                 from /home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Core/MIPS/IR/IRCompALU.cpp:20:
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Swap.h:473:3: note: candidate 1: S operator&(const swap_struct_t<T, F>&, const S&) [with S = unsigned int; T = unsigned int; F = swap_32_t<unsigned int>]
 S operator&(const swap_struct_t<T, F>& v, const S &i) {
   ^~~~~~~~
/home/abuild/rpmbuild/BUILD/libretro-ppsspp-0~git20210422/Common/Swap.h:308:12: note: candidate 2: swap_struct_t<T, F>::swapped_t swap_struct_t<T, F>::operator&(const S&) const [with S = unsigned int; T = unsigned int; F = swap_32_t<unsigned int>; swap_struct_t<T, F>::swapped_t = swap_struct_t<unsigned int, swap_32_t<unsigned int> >]
  swapped_t operator &(const S &b) const {
            ^~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-tautological-pointer-compare'
cc1plus: warning: unrecognized command line option '-Wno-deprecated-register'
make[2]: *** [CMakeFiles/Core.dir/build.make:80: CMakeFiles/Core.dir/Core/MIPS/IR/IRCompALU.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:724: CMakeFiles/Core.dir/all] Error 2
```

**Comment by unknownbrackets** [comment] 2021-04-23 14:15
It sounds like this device might be big endian - that might be the reason for these errors.

-[Unknown]

**Comment by lgbaldoni** [comment] 2021-04-23 16:09
> It sounds like this device might be big endian - that might be the reason for these errors.

Its true. This package builds on x86_64, i586, arm64, armv7l and ppc64le. s390x is the only BE architecture.

So, if you think that's the problem and there is no solution, I will just exclude it from the build.

**Comment by hrydgard** [comment] 2021-04-23 19:58
Yeah, you're probably gonna be on your own debugging big-endian - I certainly don't have any big-endian hardware anymore, for example.

**Comment by unknownbrackets** [comment] 2021-04-24 01:54
I'm going to close this as a duplicate of #8823 then.

-[Unknown]

**Closed by unknownbrackets** 2021-04-24 01:54 UTC
