### ISSUE TITLE
Kingdom Hearts Birth By Sleep (Final Mix+ only?) crash(es)

### ISSUE THREAD

**Issue by VIRGINKLM** [hrydgard/ppsspp#5800] opened 2014-04-04 21:17 UTC
The game seems to always crash the emulator when an FMV cutscene is about to load. (example: Blank Points)
Console doesn't seem to show anything wrong.

**Comment by Gtavo21** [comment] 2015-06-27 02:47
![error bbs fm 3](https://cloud.githubusercontent.com/assets/13072513/8390184/cadc5338-1c4c-11e5-8681-5d10f43a021d.png)

help plz dont know what to do, i hace tried with many other versions and the game keep crashing

**Comment by deadair3210** [comment] 2015-06-27 14:36
can you try another of the versions and post a picture of the log, please? Right now, it is saying that there is a file missing in the iso

**Comment by VIRGINKLM** [comment] 2015-11-02 07:56
Those exa files are event files, more specificaly they are cutscenes and in the above case it's a cutscene in Disney Island. These are part of the inner structure of the game's data and not a file you will find directly by extracting the game's iso, so I doubt that the file is indeed missing so what PPSSPP is reporting is for sure a false alarm. I believe that for some reason PPSSPP fails to find the file inside one of those encrypted binaries of the game's iso.

**Comment by unknownbrackets** [comment] 2015-11-02 15:48
It's common that games will check to see if files exist in paths for debugging before going into an archive.  In many games, file not found errors are completely normal.

-[Unknown]

**Comment by Xemiru** [comment] 2015-12-13 23:35
Bumping; this bug still exists.

A savestate for this crash can be found [here,](https://dl.dropboxusercontent.com/u/46408976/ULJM05775_1.00_1.ppst) saved on version `1.1.1-360-g2083f22`. Two cutscenes after the point where this savestate loads is where the game crashes.

**Comment by daniel229** [comment] 2016-05-19 00:12
FIxed by https://github.com/hrydgard/ppsspp/pull/8725

**Comment by unknownbrackets** [comment] 2016-05-19 01:15
Hmm, that's slightly concerning.  Aside from the reverted vmmul change, the only change there that ought to affect non-IR is the one in Core/CoreTiming.cpp.

If you change it back to:

```c++
 	// This will cause us to check for new events immediately.
	currentMIPS->downcount = 0;
	// But let's not eat a bunch more time in Advance() because of this.
	slicelength = 0;
```

Does it not work again?  If not... could you check which commit caused it, if you have time?  Just want to make sure we don't accidentially undo the fix.

-[Unknown]

**Comment by daniel229** [comment] 2016-05-19 02:17
Sound like it just randomly working even in old version v1.1.1。

**Comment by edelgard** [comment] 2016-08-16 04:59
is there any solution for this in android? i dont understand a single thing, pls help, im dying 
i've played it at 1.1.1, 0.9.9, and 1.2.2 still no changes and crashes at the new cutscenes starts

**Comment by ProjectXsent** [comment] 2017-02-15 01:40
Same problem here. After I defeat Terra-Xehanort ppsspp crashes.

**Comment by ProjectXsent** [comment] 2017-02-15 01:44
On the Android version

**Comment by e88z4** [comment] 2018-09-08 02:12
I play BBS final mix and encouter this bug as well on final episode after fighting Terra-Xehanort. I compiled your source code with the following commit 562c5f6485b5eba9ec49caa9cd05b658d2ed89b5

The segmentation fault is caused by memcpy on BufferQueue.h
		if (end + addsize <= bufQueueSize) {
			memcpy(bufQueue + end, buf, addsize);
			end += addsize;

bufQueue address was 0x7ff7b6ce4550
end was 0
buf address was 0x2309ffed50
addsize was 8192

rep movsb %ds:(%rsi),%es:(%rdi)                        ! 0x00007ff808578e5f

I hope this bug can be fixed soon.

**Comment by AkiraJkr** [comment] 2018-09-08 02:55
Can confirm this happens on both Windows x64 and Android in specific, can't reproduce it on Theater Mode

Basically, Fight Terra-Xehanort(Final Episode), and on the second cutscene after defeat, as soon as it ends, the game crashes. I'm surprised this crash exists for soo long.

**Comment by e88z4** [comment] 2018-09-08 11:59
I forgot to attach my stack. The buf address is always 0x2309ffed50. 

```
BufferQueue::push BufferQueue.h:71
MediaEngine::loadStream MediaEngine.cpp:374
AnalyzeMpeg sceMpeg.cpp:336
sceMpegQueryStreamOffset sceMpeg.cpp:604
WrapI_UUU<sceMpegQueryStreamOffset> FunctionWrappers.h:206
<function called from gdb> 0x00007fa75fffe4ff
WrapI_UUU<sceMpegQueryStreamOffset> FunctionWrappers.h:206
CallSyscallWithoutFlags HLE.cpp:469
<unknown> 0x00000000408720b3
<unknown> 0x0000000000000000
```

**Comment by unknownbrackets** [comment] 2018-09-08 17:02
One thing we can try - but probably is the wrong fix, and might just cause it to fail to play the video - is adding a check.  Find this in Core/HLE/sceMpeg.cpp:

```c++
static int sceMpegQueryStreamOffset(u32 mpeg, u32 bufferAddr, u32 offsetAddr)
{
	if (!Memory::IsValidAddress(bufferAddr) || !Memory::IsValidAddress(offsetAddr)) {
		ERROR_LOG(ME, "sceMpegQueryStreamOffset(%08x, %08x, %08x): invalid addresses", mpeg, bufferAddr, offsetAddr);
		return -1;
	}
```

Add after that code:

```c++
	if (!Memory::IsValidRange(bufferAddr, 8192)) {
		return hleLogError(ME, -1, "invalid buffer address");
	}
```

This should cause it to fail here, but the game might get even more confused if this fails.

-[Unknown]

**Comment by e88z4** [comment] 2018-09-08 17:38
I added the if statement. The stack trace went into your new code and exit the function but it seems the program is doing an infinite loop like below. 

```
34:56:060 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:327 0=sceUtilityUnloadModule(00000303)
34:56:545 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000303)
34:56:578 user_main    I[ME]: HLE/sceMpeg.cpp:428 sceMpegInit()
34:56:578 user_main    I[ME]: HLE/sceMpeg.cpp:542 094615c0=sceMpegCreate(09268d50, 09461590, 65536, 09268d54, 512, 0, 0)
34:56:594 user_main    E[ME]: HLE/sceMpeg.cpp:595 ffffffff=sceMpegQueryStreamOffset(09268d50, 09ffed50, 09268f0c): invalid buffer address
34:56:627 user_main    I[ME]: HLE/sceMpeg.cpp:1618 sceMpegFinish(...)
34:56:627 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:327 0=sceUtilityUnloadModule(00000303)
34:57:113 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000303)
34:57:145 user_main    I[ME]: HLE/sceMpeg.cpp:428 sceMpegInit()
34:57:146 user_main    I[ME]: HLE/sceMpeg.cpp:542 094615c0=sceMpegCreate(09268d50, 09461590, 65536, 09268d54, 512, 0, 0)
34:57:161 user_main    E[ME]: HLE/sceMpeg.cpp:595 ffffffff=sceMpegQueryStreamOffset(09268d50, 09ffed50, 09268f0c): invalid buffer address
34:57:194 user_main    I[ME]: HLE/sceMpeg.cpp:1618 sceMpegFinish(...)
34:57:194 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:327 0=sceUtilityUnloadModule(00000303)
34:57:680 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000303)
34:57:713 user_main    I[ME]: HLE/sceMpeg.cpp:428 sceMpegInit()
34:57:713 user_main    I[ME]: HLE/sceMpeg.cpp:542 094615c0=sceMpegCreate(09268d50, 09461590, 65536, 09268d54, 512, 0, 0)
34:57:728 user_main    E[ME]: HLE/sceMpeg.cpp:595 ffffffff=sceMpegQueryStreamOffset(09268d50, 09ffed50, 09268f0c): invalid buffer address
34:57:762 user_main    I[ME]: HLE/sceMpeg.cpp:1618 sceMpegFinish(...)
34:57:762 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:327 0=sceUtilityUnloadModule(00000303)
34:58:247 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:306 0=sceUtilityLoadModule(00000303)
34:58:280 user_main    I[ME]: HLE/sceMpeg.cpp:428 sceMpegInit()
34:58:280 user_main    I[ME]: HLE/sceMpeg.cpp:542 094615c0=sceMpegCreate(09268d50, 09461590, 65536, 09268d54, 512, 0, 0)
34:58:295 user_main    E[ME]: HLE/sceMpeg.cpp:595 ffffffff=sceMpegQueryStreamOffset(09268d50, 09ffed50, 09268f0c): invalid buffer address
34:58:329 user_main    I[ME]: HLE/sceMpeg.cpp:1618 sceMpegFinish(...)
34:58:329 user_main    I[SCEUTIL]: HLE/sceUtility.cpp:327 0=sceUtilityUnloadModule(00000303)

```

**Comment by unknownbrackets** [comment] 2018-09-08 19:17
Do the changes in #11371 help?

-[Unknown]

**Comment by e88z4** [comment] 2018-09-08 20:26
Yes, your pull request #11371 resolves the issue. I was able to save at the end of the final episode chapter. I didn't play the blank point chapter yet but looking at the stack trace from solarmystic a few years ago, I think it was the issue reading unavailable bytes.

**Comment by ProjectXsent** [comment] 2018-09-08 22:29
Base on the issue #2395, the temporary fix for the game to play "Where the Heart Goes" and "Blank Points" is to change the Rendering Solution to 4x or 5x before opening the game.

**Closed** 2018-09-09 08:50 UTC

**Comment by PPSSPP-user** [comment] 2021-04-20 18:43
Regarding ProjectXsent's comment, this does also happen in Vulkan.
