### ISSUE TITLE
PPSSPP v1.6 ----> Vulkan (Error when exit emu)

### ISSUE THREAD

**Issue by roioros** [hrydgard/ppsspp#11077] opened 2018-05-26 19:58 UTC
Hi, I have a problem that I never had before.
In v1.6, when I choose Vulkan and exit the emu, I always have this error:

vkQueuePresentKHR failed! result=VK_ERROR_DEVICE_LOST

Then, asks me: Try to continue?

My PC:
Phenom II x4 965, 8 GB RAM, AMD HD 7970.
Windows 7 64 bits.

**Comment by roioros** [comment] 2018-05-27 01:51
Hi, the problem begins in "v1.4.2-701-gf014735eb" onwards, not with that error (vkQueuePresentKHR failed! result=VK_ERROR_DEVICE_LOST), but with crashes when I leave the emu.

**Comment by unknownbrackets** [comment] 2018-05-27 02:08
Thanks.  That implicates #10079.  It's interesting that it worked fine before that.

-[Unknown]

**Comment by roioros** [comment] 2018-05-27 03:48
Thanks to you, If you need me to do more tests, just tell me.

**Comment by Wyrick** [comment] 2018-06-09 00:17
Hello, I am also having this error when closing the emu. The error started showing up in "v1.5.4-528-g081e15d1c" for me and continues through to the latest build.

PC Specs
Windows 7 x64
AMD FX 6350
8GB Memory
AMD R9 290

**Comment by CrazySteve88** [comment] 2018-08-16 15:03
Hi. I wasn't sure if I should open another case since I'm also having the same issues but on a newer revision.

vkQueuePresentKHR failed! result=VK_ERROR_DEVICE_LOST

I have no problem with 1.5.4 but as soon as I update to 1.6.3 I start getting the same VK error on exit. The emulator works fine though as far as I can tell it's just giving an error on exit.

The last working revision was v1.5.4-526. As soon as I tried v1.5.4-528 I started getting the error. I also tested the latest revision (v1.6.3-352) and got the same error.

My specs are similar to the OP:
AMD Athlon II X4 630 2800 MHz, 16GB Ram, AMD Radeon HD 7950 (3GB).

I'm running Windows 8.1 Pro with AMD's Crimson ReLive Edition 17.7.1 (last supported version)
Vulkan API Version: 1.0.39

**Comment by hrydgard** [comment] 2018-08-16 17:54
Hm, if it only exposes 1.0.39 that driver can't be that new? Or last supported on Win8, or for that particular card? Either way, we're likely doing something wrong, but I guess it's not too terrible if it only happens on exit, even though it's probably worth fixing in the long run..

**Comment by CrazySteve88** [comment] 2018-08-16 20:03
AMD dropped support for Windows 8.1 last year for some reason and the last driver they released was 17.7.1 which includes 1.0.39. I tried manually updating Vulkan using the SDK but the vulkan driver crashes. My card's still supported on Windows 7 and 10 and I can even update to the latest vulkan drivers using the SDK.

**Comment by unknownbrackets** [comment] 2018-08-18 18:04
https://github.com/hrydgard/ppsspp/compare/39fd77b35...081e15d1c

Probably this range only means the error previously depended on *how* you shut down PPSSPP.

-[Unknown]

**Comment by roioros** [comment] 2018-11-01 16:08
Hi!
I just tried the latest version (1.7) and this problem keeps coming up, will there be any way to fix it?

Thanks!

**Comment by hrydgard** [comment] 2019-03-24 20:51
Closing as duplicate of #10646.

**Closed by hrydgard** 2019-03-24 20:51 UTC
Labels: Vulkan
