### ISSUE TITLE
Screen Flickering on OpenGL

### ISSUE THREAD

**Issue by torben656** [hrydgard/ppsspp#10635] opened 2018-02-22 04:39 UTC
The screen flickers when I run a game.

Windows 7
Processor: AMD A4-6300 APU with Radeon(tm) HD Graphics 3.70 GHz
RAM: 2.00 GB
System Type: 32-bit

**Comment by FlatOutPS2** [comment] 2018-02-22 11:44
See https://github.com/hrydgard/ppsspp/issues/10613 ;)

**Comment by hrydgard** [comment] 2018-02-22 13:29
Yeah, closing as duplicate of #10613

**Closed by hrydgard** 2018-02-22 13:29 UTC

**Comment by torben656** [comment] 2018-02-22 17:31
Oh, I'm really sorry. But thanks! The latest version(not the dev ones) worked with OpenGL like a charm.
