### ISSUE TITLE
CASTLEVANIA DRACULA X CHRONICLES AUDIO ISSUE

### ISSUE THREAD

**Issue by SMILYDi** [hrydgard/ppsspp#15637] opened 2022-06-29 07:35 UTC
### Game or games this happens in

ULJM05287

### What area of the game / PPSSPP

problem when i use 1.12.3 PPSSPP.The audio will disappear when i play the original rondo of blood in castlevania x chronicles.Whichever rom i use (eu us jp) the problem is still the same and the ppsspp settings are all default.I wonder if there is any way to solve this.And this bug has been raised 8 years ago at #5564 by [daniel229] and 4 years ago at #11091 by [eiendream-ar] but is has never been fixed which really confuses me.

### What should happen

The bgm should not stop in the op and should loop in the game.

### Platform

Windows

### Mobile phone model or graphics card

GTX 1650 laptop

### PPSSPP version affected

v1.12.3

### Last working version

none

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by SMILYDi** [comment] 2022-06-29 07:40
i cant do programing,so #5564 and #11091 contain more details.

**Comment by SMILYDi** [comment] 2022-06-29 07:45
the problem is similar to #13773 and when i use the build from [sum2012] the bgm continues but the sound and picture are out of sync.really hope someone can fix this.

**Comment by ANR2ME** [comment] 2022-06-30 04:02
> the problem is similar to #13773 and when i use the build from [sum2012] the bgm continues but the sound and picture are out of sync.really hope someone can fix this.

I think it's out of sync because the test build from sum2012 is seeking the sample back to the first(ie. 0) sample, where on Coded Arm Contagion the logs being generated is different than real PSP:
```
16:43:184 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1318 00000000=sceAtracDecodeData(2, 08472b84, 09fafa18[00000400], 09fafa1c[00000000], 09fafa10[175])
16:43:199 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1587 0=sceAtracGetRemainFrame(2, 09fafa14[000000af])
16:43:199 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1664 0=sceAtracGetStreamDataInfo(2, 09fafa00[08475c50], 09fafa0c[000107a0], 09fafa04[00021000])
16:43:199 FMOD Streame I[SCEKERNEL]: HLE\sceKernelThread.cpp:2018 534=sceKernelCreateThread(FMOD async FILE thread, 08ad4108, 00000024, 4096, 00000000, 00000000)
16:43:199 FMOD Streame I[SCEKERNEL]: HLE\sceKernelThread.cpp:2113 0=sceKernelStartThread(534, 4, 00000000)
16:43:199 FMOD Streame N[ME]: HLE\sceAtrac.cpp:1103 bufferState_ 5
16:43:200 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1138 0=sceAtracAddStreamData(2, 000107a0)
16:43:200 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1318 00000000=sceAtracDecodeData(2, 08496bb0, 09fafa18[00000081], 09fafa1c[00000000], 09fafa10[350])
16:43:202 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1587 0=sceAtracGetRemainFrame(2, 09fafa14[0000015e])
16:43:202 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1318 00000000=sceAtracDecodeData(2, 08496bb0, 09fafa18[00000400], 09fafa1c[00000000], 09fafa10[349])
16:43:202 FMOD Streame D[ME]: HLE\sceAtrac.cpp:1587 0=sceAtracGetRemainFrame(2, 09fafa14[0000015d])
```
where that `00000081` should only occurred once at he beginning of the music, not on the looped one, on a real PSP it should be `00000400` (based on the JPCSPTrace proveded there)

**Comment by MojoJojoDojo** [comment] 2022-07-02 05:26
I also had the sound disappear while playing  Taiko no Tatsujin Portable DX.
Funny thing because its a music rhythm game lol.

**Comment by unknownbrackets** [comment] 2022-07-03 19:25
This issue is being closed as a duplicate of #5564.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-07-03 19:25 UTC
Labels: Audio, HLE/Kernel

**Comment by HyenaPinetree** [comment] 2022-07-25 02:15
I’d argue you would put ‘bread’ on a shopping list multiple times if multiple shopping runs have gone by and still nobodies bought bread

**Comment by unknownbrackets** [comment] 2022-07-25 05:31
Great, I'm really glad to hear you're so excited to go get the bread.  Everyone's been waiting for you - thanks for showing up.

-[Unknown]
