### ISSUE TITLE
Req: Input Recording/Playback

### ISSUE THREAD

**Issue by greysondn** [hrydgard/ppsspp#12104] opened 2019-06-14 18:15 UTC
Basically, the first piece of what's needed to support TASing - recording inputs sent to the game and playing them back. This would also help with testing, as a player could just record the series of inputs that leads to a bug and submit it.

**Comment by unknownbrackets** [comment] 2019-06-15 05:33
You may be interested in #10888, although its goal isn't really TAS.  It does record controller inputs (and memory card inputs) for replay purposes.

-[Unknown]

**Comment by greysondn** [comment] 2019-06-15 16:32
> Took me sec to understand what all the file stuff is about, but it's for replay playbacks to function even when games were reading from disc during the recording by storing the data that was read.

This is not an acceptable solution for what I had in mind.

First, I want to be able to publicly share these recordings (the raw input files); if I understand that quote, such shares would not be a clean input recording, but - rather - inadvertent piracy.

Second, it's not atypical to hand-edit such recordings. Data chunks that aren't the input itself would only get in the way.

And the list only gets longer if I move from there to "... and I had hoped it to be a firm, first step for proper TAS support while I was trying to get this for my own reasons - among which were TAS potential anyway"

**Comment by unknownbrackets** [comment] 2019-06-15 16:40
Assuming you're using it for a UMD / ISO based game, it will (intentionally) only record reads to the memory stick.  Obviously, it's not intended to record fixed data, but rather to record save data and things that would change between runs.

Remember that, unlike with older systems, PSP games often autosave and autoload save data, and may refuse to run at all if you lack save storage.

Nevertheless, I just said you might be interested - if it doesn't work, that's fine.  I'm personally not very interested in TAS, so I'm not planning to do anything here.  But if you or someone else is interested, that implementation might help point you to what you'd want to do.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-04-11 22:15
Going to close this as a duplicate of #12501.

-[Unknown]

**Closed by unknownbrackets** 2020-04-11 22:15 UTC
Labels: Feature Request

**Comment by Panderner** [comment] 2020-04-12 00:08
> Going to close this as a duplicate of #12501.
> 
> -[Unknown]

@unknownbrackets this duplicate is earlier than this issue

**Comment by unknownbrackets** [comment] 2020-04-12 00:51
Sure, just trying to centralize information.  It doesn't always have to be the lowest numbered issue.

This issue is slightly more specific, but still has #12501 as its goal.  Anyway, we do actually have input recording as mentioned here, although it's not really suitable for hand-editing in TAS (which is really #12501 again.)

-[Unknown]

**Comment by Panderner** [comment] 2020-04-12 04:22
This issue is 6 months earlier than this as a duplicate of #12501
