### ISSUE TITLE
God of War: Ghost Of Sparta random freezes [PC]

### ISSUE THREAD

**Issue by nitanmarcel** [hrydgard/ppsspp#13031] opened 2020-06-16 09:29 UTC
Hi! I've been playing Ghost Of Sparta yesterday and the game runs smooth, but the only problem it has is that something the game freezes and I have to hit F11 to switch between fullscreen and vice versa for the game to unfreeze. It happens often, even when moving thought the level.

I'm playing on a laptop that's running a 2GB GPU GT740M, I even tried running with the integrated GPU but the same thing: Smooth gaming but random freezes . I've tried to switch between DX9 and DX11 but the problem doesn't go away. Vulkan back end lags the game so I can't use it so I'm stuck with those 2 problems.
Could the problem be with the CPU? My laptop uses a Intel Core i5-4200M turbo boosted to 3.1 GHz

**Comment by Gamemulatorer** [comment] 2020-06-16 09:55
Did you already tried the ppsspp latest git build? https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by nitanmarcel** [comment] 2020-06-16 14:27
> Did you already tried the ppsspp latest git build? https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Thanks, I've tried it right now. Using the Vulkan back-end works great and the random freezes are gone as long as the frame-skiping option is turned ofd

**Comment by Gamemulatorer** [comment] 2020-06-17 07:30
@nitanmarcel can you consider this issue is fixed? so that @hrydgard can closed this :)

**Comment by hrydgard** [comment] 2020-06-17 07:31
If it's still freezes weirdly with D3D9 and D3D11, it's not fixed. Though it's odd, haven't seen or heard of this behavior before.

**Comment by nitanmarcel** [comment] 2020-06-17 09:39
> If it's still freezes weirdly with D3D9 and D3D11, it's not fixed. Though it's odd, haven't seen or heard of this behavior before.

Well the main problem is the frame-skiping, with it's enabled freezes the game at random times

**Comment by nitanmarcel** [comment] 2020-06-17 09:40
Is there a way to take debug logs? I'll try as soon as I start my computer

**Comment by nitanmarcel** [comment] 2022-07-21 14:28
This issue is so old. I've since bought a more powerful laptop and I have no more access to the old one

**Comment by LunaMoo** [comment] 2022-07-22 01:02
This was more likely an frameskip issue(as can be read above in https://github.com/hrydgard/ppsspp/issues/13031#issuecomment-644801037, solvable by disabling frameskip) than GOW issue, due to OP no longer being able to reproduce will close this suspecting it's actually a case of #15525

**Closed by LunaMoo** 2022-07-22 01:02 UTC
Labels: D3D9, D3D11
