### ISSUE TITLE
Burnout Legends HUD disappears sometimes (Mali 400)

### ISSUE THREAD

**Issue by Ar37** [hrydgard/ppsspp#9331] opened 2017-02-19 15:12 UTC
OS: Android, GLES2

ppsspp-v1.3-676: Hud sometimes disappear in specific event, (e.g: world tour -> compact class -> winter city -> burning lap).

ppsspp-v1.3-615: Fine.

**Comment by Ar37** [comment] 2017-02-19 15:20
screenshot: https://i.imgsafe.org/9b6ec58c90.png there is no nitro bar, time, menu .etc disappear

**Comment by hrydgard** [comment] 2017-02-19 18:10
Strange. thanks for the commit range, that's super useful!

**Comment by mrcmunir** [comment] 2017-02-20 09:22
I can't reproduced it in PC 

![captura de 2017-02-20 10-19-44](https://cloud.githubusercontent.com/assets/1274014/23118907/4a73af02-f756-11e6-9407-4550a9059e11.png)

**Comment by hrydgard** [comment] 2017-02-20 09:57
Is that with the OpenGL backend on PC?

**Comment by mrcmunir** [comment] 2017-02-20 10:11
Yes the report is with OpenGL backend

With OpenGL ES in PC (untested) never working in my HW.

**Comment by Ar37** [comment] 2017-02-20 12:57
ok @hrydgard, here some of logcats wich frequently appearing:
02-20 19:45:46.646 W/NativeApp(3405): 45:46:646 user_main    W[G3D]: GLES/TextureCacheGLES.cpp:914 Got an error in texture upload: 00000500 (invalid_enum) (components=1908 components2=1908 dstFmt=1401 w=256 h=256 level=0)
02-20 19:45:47.116 E/NativeApp(3405): Thin3D GL: Error loading texture: 00000500
02-20 19:45:47.507 W/NativeApp(3405): frameCommand! 'event' 'mainscreen'
02-20 19:45:47.507 W/NativeApp(3405): frameCommand! 'event' 'exitgame

**Comment by hrydgard** [comment] 2017-02-20 13:31
Thanks!

**Comment by Ar37** [comment] 2017-02-20 13:35
Tekken 5 also has the same problem in specific stage.
screensot https://i.imgsafe.org/aef4a42ea3.png

**Comment by hrydgard** [comment] 2017-02-20 13:37
What device do you have (or which GPU does it have)?

**Comment by Ar37** [comment] 2017-02-20 14:10
sorry forgot to mentioned,
GPU Mali-400

**Comment by hrydgard** [comment] 2017-03-03 10:17
I believe that error comes from some earlier gl call, unfortunately GL does not make that easy to debug without sprinkling glGetError all over the code. I will do some experiments on my own Mali device (a Galaxy S3).

**Comment by hrydgard** [comment] 2017-03-06 16:01
OK so I managed to kill the error, but it turns out it was unrelated. Also I can't reproduced on my Galaxy S3. Can you try again with the latest build and see if it still happens?

**Comment by hrydgard** [comment] 2017-03-15 15:01
Moving to milestone 1.5 due to no feedback, can't reproduce and don't know what else to try.

**Comment by hrydgard** [comment] 2018-06-10 18:52
Time to close, yeah.

**Closed by hrydgard** 2018-06-10 18:52 UTC
