### ISSUE TITLE
a better pause menu

### ISSUE THREAD

**Issue by super-lurker** [hrydgard/ppsspp#15545] opened 2022-05-20 03:51 UTC
### What should happen

I got better than words, pictures!

![sshot-2022-05-20-11-41-23](https://user-images.githubusercontent.com/13076066/169446588-074c2fc8-20d4-4897-b85d-86f691f5cd35.png)

xemu emulator full screen menu

---------------------------------------------------------------------------------

![sshot-2022-05-20-11-42-55](https://user-images.githubusercontent.com/13076066/169446690-95cf6753-e58e-4384-b66a-a7f5933b9ed6.png)

duckstation pause menu

---------------------------------------------------------------------------------

I think pcsx2 is also getting the same menu as duckstation, but I dont have the dev build

### Who would this benefit

big picture/ steam deck users mostly, but desktop user aswell

### Games this would be useful in

everything

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment] 2022-05-20 07:53
You're right that the pause menu is overdue for a redesign, and it'll happen. PPSSPP's requirements are not exactly the same as other emulators, though similar.

I think everybody has different ideas of how prominent save states should be, how many actions like load a different game or show cheat list etc should be on display, etc. Why don't you list what you want on the pause screen, to start the discussion? Exactly what's on the two screenshots?

**Comment by ANR2ME** [comment] 2022-05-20 08:12
Both screenshot seems to shows the game in the background

**Comment by hrydgard** [comment] 2022-05-20 09:21
That's a good point, and would look cool. Only practically doable in "buffered rendering" mode though, but hardly anyone runs in non-buffered these days...

**Comment by super-lurker** [comment] 2022-05-20 10:01
> You're right that the pause menu is overdue for a redesign, and it'll happen at some point. PPSSPP's requirements are not exactly the same as other emulators, though similar.
> 
> I think everybody has different ideas of how prominent save states should be, how many actions like load a different game or show cheat list etc should be on display, etc. Why don't you list what you want on the pause screen, to start the discussion? Exactly what's on the two screenshots?

yeah my bad i should have pointed out that the duckstation one was my preferred example, literary copy it 1:1 specially the exit game part, ppsspp exits from menu and that take so much unnecessary clicks

**Comment by super-lurker** [comment] 2022-05-20 10:14
I dunno if its possible but since you asked:

yellow menu: only show load/save state when hovered like xmb style menu
red area: is most recent screenshot 
blue: system time / uptime / total play time

![169446690-95cf6753-e58e-4384-b66a-a7f5933b9ed6](https://user-images.githubusercontent.com/13076066/169507042-70d299ac-c246-4ae8-b784-048227f46052.png)

**Comment by ANR2ME** [comment] 2022-05-20 10:24
> > You're right that the pause menu is overdue for a redesign, and it'll happen at some point. PPSSPP's requirements are not exactly the same as other emulators, though similar.
> > I think everybody has different ideas of how prominent save states should be, how many actions like load a different game or show cheat list etc should be on display, etc. Why don't you list what you want on the pause screen, to start the discussion? Exactly what's on the two screenshots?
> 
> yeah my bad i should have pointed out that the duckstation one was my preferred example, literary copy it 1:1 specially the exit game part, ppsspp exits from menu and that take so much unnecessary clicks

Isn't PPSSPP already like that in regards to Exiting a Game?
You press ESC to pause the game and click on Exit to Menu (which is the same as Exit Game), unless you mean you want to exit the emulator.. in that case you can just click on the [X] button on top left of the window.

**Comment by super-lurker** [comment] 2022-05-20 10:53
> > > You're right that the pause menu is overdue for a redesign, and it'll happen at some point. PPSSPP's requirements are not exactly the same as other emulators, though similar.
> > > I think everybody has different ideas of how prominent save states should be, how many actions like load a different game or show cheat list etc should be on display, etc. Why don't you list what you want on the pause screen, to start the discussion? Exactly what's on the two screenshots?
> > 
> > 
> > yeah my bad i should have pointed out that the duckstation one was my preferred example, literary copy it 1:1 specially the exit game part, ppsspp exits from menu and that take so much unnecessary clicks
> 
> Isn't PPSSPP already like that in regards to Exiting a Game? You press ESC to pause the game and click on Exit to Menu (which is the same as Exit Game), unless you mean you want to exit the emulator.. in that case you can just click on the [X] button on top right of the window.

as I mention in my main post, this is mainly for big picture / controller only users

here a picture to give you a better idea of how I play emulated games

![sshot-2022-05-20-18-51-23](https://user-images.githubusercontent.com/13076066/169513120-d4398c66-1ced-4ce0-9a46-29b03bef25f2.png)

basically I want a console like experience without needing keyboard inputs

**Comment by unknownbrackets** [comment] 2022-05-21 01:14
For me the pause menu works great without keyboard inputs.  I don't personally use a loader so would see replacing the button that goes to the menu with a direct exit as a pretty negative change.

That said, you can use `--escape-exit` when starting PPSSPP to exit on pause, or `--pause-menu-exit` to exit from the pause menu.  We shouldn't assume everyone uses and prefers some loader (or doesn't) just because one person does.

Personally, I don't think the options on the pause menu necessarily need to change.  For example, just because other emulators lack game compatibility feedback [doesn't mean it's a bad or unused feature](https://report.ppsspp.org/games).  I do think potentially the save state / load state buttons could be better or maybe even expand on swipe or other things.

In any case, this is a duplicate of #13016.

-[Unknown]

**Comment by super-lurker** [comment] 2022-05-21 02:26
> For me the pause menu works great without keyboard inputs. I don't personally use a loader so would see replacing the button that goes to the menu with a direct exit as a pretty negative change.
> 
> That said, you can use `--escape-exit` when starting PPSSPP to exit on pause, or `--pause-menu-exit` to exit from the pause menu. We shouldn't assume everyone uses and prefers some loader (or doesn't) just because one person does.
> 
> Personally, I don't think the options on the pause menu necessarily need to change. For example, just because other emulators lack in-game compatibility feedback reporting [doesn't mean it's a bad or unused feature](https://report.ppsspp.org/games). I do think potentially the save state / load state buttons could be better or maybe even expand on swipe or other things.
> 
> In any case, this is a duplicate of #13016.
> 
> -[Unknown]

didn't know  `--pause-menu-exit` param existed, that pretty much solve my number one issue lol.

the pause menu definitely can use some work, like exposing network menu , controller mapping/testing and unlocked fps to name a few

**Comment by ANR2ME** [comment] 2022-05-21 07:15
Unlocked fps as in "fast forward"? you can always bind a key on your controller for fast forward, unless you don't have any button left than can be used to bind it with, that will certainly be a problem for people who have a limited number of buttons on their controller.

**Comment by unknownbrackets** [comment] 2022-05-21 15:02
I'm guessing these are all from not wanting to use the normal menu of PPSSPP.  Anything you can't change while a game is running is "inaccessible" if you only want to use a loader that starts a game and never use PPSSPP's menu itself.

I also agree that loading the pause screen with buttons and things that require PPSSPP to restart emulation would just lead to a bad experience.

-[Unknown]

**Comment by hrydgard** [comment] 2022-05-22 21:16
Yeah I'm not planning to do any huge changes, I mainly want to improve keyboard/gamepad navigation around save states somehow, making it harder to screw up (though we do have undo save/load now, it's nice to make it harder to make mistakes, if we can find a way). 

Either way, I agree that this can be considered a duplicate of #13016, so do post any additional feedback and ideas there.

**Closed by hrydgard** 2022-05-22 21:16 UTC
Labels: User Interface
