### ISSUE TITLE
New bug in vulkan API after passing pro mode: full video memory mode passing to slow cachig

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10372] opened 2017-12-08 00:39 UTC
![screenshot_20171207-171018](https://user-images.githubusercontent.com/34135636/33745663-f4b08d8a-db96-11e7-9467-27b4352c8d90.png)

![screenshot_20171207-171011](https://user-images.githubusercontent.com/34135636/33745585-711ed6e8-db96-11e7-961f-5d642428eed0.png)

![screenshot_20171207-171008](https://user-images.githubusercontent.com/34135636/33745575-5980278a-db96-11e7-9097-a41720f73b78.png)

this bug or error occurs in all games when using the vulkan API some black squares appears in the textures but what most stood out was guilta gear xx accent core plus I already used several configurations without any suses coml can see but images the velosity and FPS it falls and this problem and general really a serious error lra if you fix it please arrange this as soon as possible I'm using the build v
![screenshot_20171207-170945](https://user-images.githubusercontent.com/34135636/33745550-40f38108-db96-11e7-8d6e-1b06ff200309.png)
1.5.4-33-gc268e3781

**Comment by SamueldeSena** [comment] 2017-12-08 02:31
This problem occurs with all games

**Comment by SamueldeSena** [comment] 2017-12-08 17:23
Please hrydgard this problem occurs in all games after a while you would have more or less an idea of ​​what this would be

**Comment by unknownbrackets** [comment] 2017-12-09 19:07
This issue is being closed as a duplicate of #10377.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-12-09 19:07 UTC
