### ISSUE TITLE
PPSSPP doesn't resize with tiling window managers

### ISSUE THREAD

**Issue by uberushaximus** [hrydgard/ppsspp#6562] opened 2014-07-17 03:18 UTC
When using a tiling window manager like [dwm](http://dwm.suckless.org/) ppsspp fails to resize the window when switching from fullscreen mode. A workaround is to swap from tiling to floating and then retile the window when swapping between fullscreen and tiled window mode. PPSSPP also will stay at the same resolution when in floating mode after being pulled out of fullscreen rather than going back to the original resolution of windowed mode.

**Comment by unknownbrackets** [comment] 2015-12-22 03:26
Does this work now with SDL2?

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-12-04 04:48
Since there hasn't been any feedback on this for a few years, I'm going to close it as a duplicate of #11625 which is probably the same issue.  Feel free to reply and add more detail, though.

-[Unknown]

**Closed by unknownbrackets** 2018-12-04 04:48 UTC
Labels: Feature Request, No Feedback / Outdated?, SDL2
