### ISSUE TITLE
Languages with missing fonts make the UI unusable

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7126] opened 2014-12-02 22:26 UTC
Got this in an email report:

https://pbs.twimg.com/media/B34J3UGCEAAAuyw.jpg:large

We have a few translations that are supported on Windows where we use TrueType fonts but cannot be rendered with our Android font atlas. We need to blacklist them from being autoselected by the device language on Android, and should possibly hide them as well. Not sure exactly which languages these are..

**Comment by unknownbrackets** [comment] 2018-12-09 19:32
This is really a duplicate of #6681, so I'm going to close it.  Android font drawing has been implemented.

-[Unknown]

**Closed by unknownbrackets** 2018-12-09 19:32 UTC
Labels: Font Atlas
