### ISSUE TITLE
Silent hill shattered memories, shattered flash light 

### ISSUE THREAD

**Issue by tommy-sorce** [hrydgard/ppsspp#18290] opened 2023-10-02 22:15 UTC
### Game or games this happens in

ULUS-10450 silent hill shattered memories 

### What area of the game

After talking to the therapist. First moment player gains Control 

### What happens

Flash light is casting wired black blocks 

### What should happen

Black boxes should be absent 

### GE frame capture

![Screenshot_2023-10-02-23-59-50-72_2f85358b2198d26f8aca533d68bee793](https://github.com/hrydgard/ppsspp/assets/75146584/47550d8c-e7d4-4976-ad81-5d5068bf4dd9)

### Platform

Android

### Mobile phone model or graphics card

Snap 888 Soc with adreno 660 graphic 

### PPSSPP version affected

v1.16.5-84-g008055d24

### Last working version

First time

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2023-10-03 04:56
Could you provide a GE frame dump for testing? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by tommy-sorce** [comment] 2023-10-03 05:08
> Could you provide a GE frame dump for testing? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

Yeah, sure. Does this dump contain any private information about phone ? On the side your app crashes while launching the game and changing screen orientation at the same time. On the other, other side Silent Hill SM experiences many occasional slow downs.

**Comment by hrydgard** [comment] 2023-10-03 08:26
Duplicate of #6265 , investigated in #16126

**Closed by hrydgard** 2023-10-03 08:26 UTC

**Comment by tommy-sorce** [comment] 2023-10-03 12:44
> Duplicate of #6265 , investigated in #16126
> 
> Don't think we need any more framedumps. And for the record, they do not contain any private information, only a recording of graphics commands during a frame.

I'm sorry for not checking thoroughly, I don't spend too much time on GitHub. Found this and thought I'd share. After some time it appears that these blocks go away when I switch from original PSP resolution to my natives one. Hopefully silent hill games will work perfect in the future and keep up the updates coming ❤️
