### ISSUE TITLE
ppsspp crashes on jailbroken ios after clicking it

### ISSUE THREAD

**Issue by MarcoProlo** [hrydgard/ppsspp#11549] opened 2018-11-10 04:06 UTC
### What happens?
Most of the time, when I am trying to launch the app, the app icon would just turn dark and the app would not launch. Then, I tried to open up app switcher by double click the home button to see whether the app opened and my phone will just freeze. And I will have to reboot my phone and reactivate the jailbreak. However, the app would most likely to launch successfully on the first time after I tried to reactivate my jailbreak. If I try to open up the second time or more, it would most likely crashes my phone.

### What *should* happen?
If the app working properly, the app would be launched properly every time I clicked on the icon

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Device: iPhone 6S+ (iPhone8,2)
OS: ios 10.2(Jailbroken with DoubleH3lix)
Backend: OpenGL only
PPSSPP Ver: 1.6.3 (Tried on both Dev-Working & Latest)

**Comment by unknownbrackets** [comment] 2018-11-10 04:17
This issue is being closed as a duplicate of #9186.  See more detail there.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-11-10 04:17 UTC
