### ISSUE TITLE
Change icon of the widget 

### ISSUE THREAD

**Issue by Faz5814g** [hrydgard/ppsspp#9338] opened 2017-02-21 05:42 UTC
I like you can load games through the Widget, but it would also be cool if we could select the picture of the game widget instead of showing the ppsspp icon that would be really cool !!!

**Comment by Florin9doi** [comment] 2018-11-08 17:03
Duplicate of https://github.com/hrydgard/ppsspp/issues/10885 ?

**Comment by hrydgard** [comment] 2018-11-08 17:09
yup, closing

**Closed by hrydgard** 2018-11-08 17:09 UTC
Labels: Platform-specific (Android)
