### ISSUE TITLE
(Android) Jeanne Dark problem with text 

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10241] opened 2017-12-03 04:31 UTC
Just look on screenshots 
![screenshot_2017-12-03-12-25-38-671_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33522364-ce0c0642-d825-11e7-9f0c-82b40636ab5b.png)
![screenshot_2017-12-03-12-25-51-523_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33522365-ce3db318-d825-11e7-98a3-6887527a96e2.png)
![screenshot_2017-12-03-07-06-56-040_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33522366-ce6d9092-d825-11e7-9e45-272184d40c62.png)
![screenshot_2017-12-03-06-26-12-998_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33522367-ce9d7dde-d825-11e7-841c-80d1a16342e6.png)
![screenshot_2017-12-03-06-25-44-198_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33522368-cece2114-d825-11e7-8487-a27c72ea5f43.png)
![screenshot_2017-12-03-06-54-04-571_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33522369-cefe4b5a-d825-11e7-8cf3-e5713fbdf518.png)

**Comment by unknownbrackets** [comment] 2017-12-03 04:35
This issue is being closed as a duplicate of #2788.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-12-03 04:35 UTC
