### ISSUE TITLE
Tales of phantasia x Vulkan graphic issue 

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#11671] opened 2018-12-15 01:34 UTC

**Comment by asbel123** [comment] 2018-12-15 01:35
Hey do U remove stencil test that's fix for that game on Android Samsung galaxy s8 and s9 fix that's U can't see the text and grAphics

**Comment by asbel123** [comment] 2018-12-15 01:35
Vulkan issue not OpenGL issue

**Comment by asbel123** [comment] 2018-12-15 01:36
OpenGL works too very slow

**Comment by Emulatorer** [comment] 2018-12-15 01:45
Could you try exporting a GE frame dump? These help a lot.

See here for instructions - it's not hard and works on Android too:

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

**Comment by unknownbrackets** [comment] 2019-08-17 18:19
This isn't enough information.  Can you post screenshots and try to say more about the issue?  It's okay to use Google Translate - even if the text is a bit wrong, it's better than no text at all.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2020-05-22 23:03
@hrydgard this is a duplicate of #12890

**Comment by Gamemulatorer** [comment] 2020-05-24 12:08
@sum2012 this is duplicate of #12890

**Comment by hrydgard** [comment] 2020-05-24 12:13
Duplicate of #12890

**Closed by hrydgard** 2020-05-24 12:13 UTC
Labels: No Feedback / Outdated?
