### ISSUE TITLE
James Cameron's AVATAR™: The Game - flickering graphic / VFPU issue

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#8798] opened 2016-05-31 19:19 UTC
The only issue in this game now(yeah movies work/doesn't crash anywhere as far as I can tell) seems to be a slight flicker of some graphics mostly light effects and some flora, doesn't happen in new IR interpreter, log wasn't showing anything interesting, textures doesn't even show in ge debugger when the object disappear and seem pretty normal when they do, interestingly it get's fixed in IR even when loading from broken(made in JIT) savestate.

 Tried to bisect it in similar way to artdink games problem and it seems to be Comp_VecDo3 in IRCompVFPU, more specifically case 27: //VFPU3,
bug get's restored in IR whenever I disable vmax in either of those places:

```
                case 3:  // vmax
                    DISABLE;
                    ir.Write(IROp::FMax, tempregs[i], sregs[i], tregs[i]);
```

or

```
            case 3:  // vmax
                DISABLE;
                allowSIMD = false;
```

Following comments for x86 jit vmax "// TODO: Mishandles NaN.  Disabled for now." so it actually falls back to interpreter and that's where the bug is?

**Comment by unknownbrackets** [comment] 2016-05-31 19:30
Hmm, this could actually be another instruction mishandling NAN, since I've definitely tested a lot of the NAN handling here.  It isn't implemented for SIMD, but probably could be.

Does it make it work to replace this:

```c++
			for (int i = 0; i < numElements; i++) {
				// This is the same logic as vmin, just reversed.
				if (my_isnanorinf(s.f[i]) || my_isnanorinf(t.f[i])) {
					if (s.i[i] < 0 && t.i[i] < 0) {
						d.i[i] = std::min(t.i[i], s.i[i]);
					} else {
						d.i[i] = std::max(t.i[i], s.i[i]);
					}
				} else {
					d.f[i] = std::max(t.f[i], s.f[i]);
				}
			}
```

With:

```c++
			for (int i = 0; i < numElements; i++) {
				// This is the same logic as vmin, just reversed.
					d.f[i] = std::max(t.f[i], s.f[i]);
			}
```

I'm sure this is incorrect, though, so it might point to a nearby instruction handling the result wrong...

-[Unknown]

**Comment by LunaMoo** [comment] 2016-05-31 20:08
Seems slightly different, but that could be just placebo - still flickers anyway.

**Comment by unknownbrackets** [comment] 2016-06-06 05:04
Can you log the blocks where this occurs?  You may want to change the logging:

https://github.com/hrydgard/ppsspp/issues/6544#issuecomment-222555000

Just set `logBlocks = 1;` when it his the `vmax` instruction.  I'm hoping to see what other vfpu instructions it uses nearby.

-[Unknown]

**Comment by LunaMoo** [comment] 2016-06-06 07:35
When I set logBlocks = 1; under vmax cases in IRCompVFPU I don't get anything in the notice log even with that change and using IR interpreter, so I switched to JIT and searched for vmax in disassembly, found it only in 3 places but just 2 trigger when glitches happen:
![vmax1](https://cloud.githubusercontent.com/assets/5485237/15814865/930b8aea-2bc9-11e6-923d-aca74b2226b8.jpg)
Full block - https://gist.github.com/LunaMoo/35a70ea19e55a2e1ad5cb5ada8087963

![vmax2](https://cloud.githubusercontent.com/assets/5485237/15814872/a14a2148-2bc9-11e6-8606-5e294788dc2b.jpg)
Full block(much shorter than the other one) - https://gist.github.com/LunaMoo/a18790560fffc7fe0808ec6991fb4d73

**Comment by benderscruffy** [comment] 2018-11-26 01:47
still happens in v1.7.1-195-g04f57bd49
the guys weapon and the white lights continually flash
![james1](https://user-images.githubusercontent.com/2696404/48988367-297ccf80-f160-11e8-9578-83461d5fef2d.PNG)
![james2](https://user-images.githubusercontent.com/2696404/48988370-2bdf2980-f160-11e8-8b3d-af5b3aa9c292.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/2613784/DUMP.ZIP)

**Comment by hrydgard** [comment] 2018-11-26 08:41
Hm, there are indeed NaNs there in R430, looking at the first vmax. This is a real CPU bug and should be fixed (although unlikely to affect many other games).

**Comment by unknownbrackets** [comment] 2019-08-03 23:21
I think some handling in Interpreter (not IR Interpreter) has improved - does this still happen in that?  I'm wondering if it's multiple things not agreeing on NAN handling.

Also interested in if this branch has any impact:
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:vfpu-dot

In both cases, it'd be fine to test either with all VFPU DISABLE'd (would be faster to test), or in Interpreter.

-[Unknown]

**Comment by LunaMoo** [comment] 2019-08-11 18:20
Currently I have a hard time even replicating the issue and that's without even disabling any JIT. Maybe it was only happening in some place in game or maybe it's already fixed:). Will play a bit longer when I have time and for now just mark this as possibly outdated.

**Comment by unknownbrackets** [comment] 2020-01-01 03:17
Any improvements here?  Still not reproducing?

-[Unknown]

**Comment by benderscruffy** [comment] 2020-01-01 05:06
this can be closed
this is fixed

**Comment by unknownbrackets** [comment] 2020-01-01 05:38
Great, thanks for the update.

-[Unknown]

**Closed by unknownbrackets** 2020-01-01 05:38 UTC
Labels: CPU emulation, x86jit
