### ISSUE TITLE
Naruto shippuden ultimate impact white eight tails

### ISSUE THREAD

**Issue by Shadicbypass** [hrydgard/ppsspp#8118] opened 2015-10-28 22:38 UTC
The eight tails is white. There is no builds where it is not white.
Platform: android
Phone: lg g4
![screenshot_2015-10-28-18-33-23](https://cloud.githubusercontent.com/assets/11843731/10805305/0c3a14ac-7da3-11e5-9b34-ff39a39aa041.png)

**Comment by unknownbrackets** [comment] 2015-10-29 02:13
Duplicate of #4155.  Please search before creating issues.

-[Unknown]

**Closed by unknownbrackets** 2015-10-29 02:13 UTC
