### ISSUE TITLE
PPSSPP Crashing when switching apps

### ISSUE THREAD

**Issue by SavageJester** [hrydgard/ppsspp#12843] opened 2020-04-20 18:47 UTC
### What happens?
When I am in PPSSPP playing something I switch to a different app the game starts to crash. It is as if PPSSPP allows me switch apps for about 5 times before finally crashing.

### What *should* happen?
PPSSPP should not crash when switching between apps.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
REV1.0, Android 10, PPSSPP v.1.9.3-695-g15a785cac

**Comment by hrydgard** [comment] 2020-04-20 19:19
Does it seem to matter which game? Are you using the Vulkan or the OpenGL graphics backend?

**Comment by unknownbrackets** [comment] 2020-04-21 06:43
A log of the crash would be helpful:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by Kondraki643** [comment] 2020-05-08 00:30
Oh, I have like 3 audio devices on my pc installed. A dedicaded sound card (Sound Blaster Z), a usb dongle for wireless headphones (JBL Quantum 800) and an nvidia audio device. Will try unplugging the sound card and test it

**Comment by fahadrashid7705** [comment] 2020-06-04 06:43
you mean ppsspp minimized and switching other app and go back in ppsspp crash , same here

**Comment by hrydgard** [comment] 2021-01-06 15:49
I don't have a good repro for this, PPSSPP doesn't crash a lot for me when task switching. I'm gonna postpone further work until after 1.11.

**Comment by ANR2ME** [comment] 2021-01-06 18:23
I think it's possible to crashed if you're running out of freespace, which i experiencing recently.

There is also a possible crash when the logcat is flooded too much, increasing the Logger buffer size to the highest value through Developer options will prevent the crash related to logcat, 
But current PPSSPP shouldn't have this issue, because i only had this issue while i'm working on the multiplayer fix for Driver 76 and could make any PR yet because of this crash issue isn't resolved yet.

**Comment by unknownbrackets** [comment] 2021-04-09 02:30
Has this improved at all in recent git builds?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-07-13 05:19
@SavageJester this is only happen on vulkan backend?

**Comment by XiaomiRedmi9** [comment] 2021-08-09 01:19
@SavageJester @fahadrashid7705

**Comment by ResurrectionRedmi9** [comment] 2021-09-09 14:55
This is probably a duplicate of https://github.com/hrydgard/ppsspp/issues/13800

**Comment by Gamemulatorer** [comment] 2021-12-10 13:45
This is also safe to close assuming that this is also about vulkan minimizing/switching crash issue that is fix by https://github.com/hrydgard/ppsspp/commit/7b07a1385a91faf137089f513c8c0ebfae769d22

**Comment by hrydgard** [comment] 2021-12-10 13:55
Yeah, let's close.

**Closed by hrydgard** 2021-12-10 13:55 UTC
Labels: No Feedback / Outdated?, Platform-specific (Android)
