### ISSUE TITLE
Graphical glitch in Trails in the Sky

### ISSUE THREAD

**Issue by Moonmadness** [hrydgard/ppsspp#8053] opened 2015-10-11 14:37 UTC
I noticed a new graphical glitch in the Trails menu screen that wasn't there before last update. Here you can see some vertical black lines on the selected menu options and on the two gears on the side that shouldn't be there.
![screenshot_2015-10-11-16-23-35](https://cloud.githubusercontent.com/assets/13020077/10417251/4240c436-7035-11e5-9074-33300d11a6f6.png)
I tried disabling/enabling many options but nothing seems to work.

Also when I keep L or R inside a town to continuosly rotate the camera I sometimes experience black screen flickerings. I assume it's related to the amount of 3D elements since I don't have this problem outside town where there's none.
I'm on Android Lollipop on a Galaxy S2. I didn't enable multithreading which seems to worsen the problem.

[edit] Screen flickering happens also when the game zooms or changes the camera during dialogue sequences.

**Comment by unknownbrackets** [comment] 2015-10-11 17:31
What settings are you using?  Are you using frameskip?

These are the settings I'd recommend:

1. Make sure block transfers are ON.
2. Make sure "disable slow effects" is OFF.
3. Make sure rendering mode is Buffered Rendering.
4. Make sure all of the hacks in the settings (under the hacks section) are off.

With or without frameskip, I can't reproduce those issues.  I realize the S2 is an older device and might be slow with the above settings, though.

-[Unknown]

**Comment by Moonmadness** [comment] 2015-10-11 18:11
I'm not using frameskip. I tried all of the above and it seems all problems are solved by enabling Buffered Rendering. Game is still pretty playable now but menus slow down like hell :/

**Comment by unknownbrackets** [comment] 2015-10-11 19:03
Yes, I think that's the other looping issue discussed in #8011, or else the reset which that also improves.  It'll probably be after v1.1.1, though, so stay tuned for a git build sometime in the next week or two.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-10-13 05:26
Okay, "Skip buffer effects" mode basically can have various graphical glitches.  I'm not sure what's exactly happening in your case, though, and can't reproduce it (on a newer device, though.)

The game actually draws that pattern below the buttons, and you can see the pattern when one of the buttons is selected, but it moves the button down at the same time.

Anyway, I'm going to close this, as the whole point of "Skip buffer effects" is to give a speed improvement at the cost of various graphical glitches (some games don't even use buffer effects so it can possibly be a free speed improvement, but these games aren't that common.)

-[Unknown]

**Closed by unknownbrackets** 2015-10-13 05:26 UTC
