### ISSUE TITLE
Screen flickering on WWE SvR 06 and 07 with a potential clue?

### ISSUE THREAD

**Issue by QuesoBlanco12** [hrydgard/ppsspp#13812] opened 2020-12-26 03:09 UTC
### What happens?
When playing WWE Smackdown vs Raw 06 and 07 with default settings besides setting the render resolution to 4x, the screen does begin to flicker.

I know the current resolution is to play with OpenGL but Vulkan does run smoother overall IMO, and I don’t know if this next piece of information is known yet or not to you.

Enabling any option under “Lower resolution for effects” mid entrance or match actually fixes this issue, until a loading screen happens which by then the flickering continues until you change the setting to another one.

Disabling buffered rendering does correct the flicker but then the crowd goes missing.

### What *should* happen?
The 2D crowd should appear and move normally as opposed to being black boxes or causing the game to flicker.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Currently on the latest official build of PPSSPP(1.10.3) running it on an NVidia Shield TV 2017.

I’m so very sorry if this clue has been brought up before. I literally created this GitHub account to post what I found to maybe help with development. I appreciate the work you’ve put in it so far and I look forward to further development!

**Comment by Panderner** [comment] 2020-12-26 03:35
Duplicate of #13797

**Comment by hrydgard** [comment] 2020-12-26 15:13
Nice writeup with good information but indeed a duplicate:) The original one will auto-link to this one so it's easy to see both. Closing.

**Closed by hrydgard** 2020-12-26 15:13 UTC

**Comment by Panderner** [comment] 2020-12-27 02:04
There's a black box flickers inside 2d crowds in OpenGL:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/37503397/103162383-e99ae180-482a-11eb-86be-87c58bb77ba9.gif)

**Comment by hrydgard** [comment] 2020-12-27 10:29
I left  #13797 open so please post new information there.

Thanks for the video though! That does look pretty nasty.

**Comment by Kingrio313** [comment] 2023-05-31 20:50
I love you man😭
