### ISSUE TITLE
iOS larger screen support

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6962] opened 2014-09-29 14:27 UTC
On iPhone 6 and iPhone Plus, reportedly we are getting scaled "the compatibility way" instead of adapting properly to the resolution. We probably just need to set some metadata to mark us as big-screen-aware, as we can already adapt to any resolution.

**Comment by leira** [comment] 2015-09-25 01:53
I saw a LaunchScreen.xib was added in change 4dc6e26 but got reverted in ea67baa, and I just built ToT, but still see larger screen is not supported, any plan to fix this issue properly? thx.

**Comment by hrydgard** [comment] 2015-09-25 10:57
Apparently it broke something, otherwise it wouldn't have been reverted. Not sure what broke though.

**Comment by brujo5** [comment] 2015-09-25 18:50
broken retina support for iphone.

**Comment by thedax** [comment] 2015-09-26 00:29
I believe it was breaking the iOS buildbot or something: https://github.com/hrydgard/ppsspp/pull/6984

**Comment by unknownbrackets** [comment] 2018-05-28 17:21
Was this implemented by #10507?

-[Unknown]

**Comment by unknownbrackets** [comment] 2019-07-15 06:27
I'm going to close this assuming the answer was yes.  It also seems like it may be a duplicate of #8714 (or the other way around)?

-[Unknown]

**Closed by unknownbrackets** 2019-07-15 06:27 UTC
Labels: Feature Request, Platform-specific (iOS)
