### ISSUE TITLE
Monster hunter 3rd save data corrupted error (bugs)

### ISSUE THREAD

**Issue by omarguerrero5310** [hrydgard/ppsspp#9894] opened 2017-08-10 16:16 UTC
![screenshot_2017-08-10-09-10-10](https://user-images.githubusercontent.com/26820148/29180397-9195b948-7dac-11e7-85bd-6905957199b5.png)

**Comment by omarguerrero5310** [comment] 2017-08-10 16:18
This happen when you already save game and reload the game again this will happen

**Comment by omarguerrero5310** [comment] 2017-08-10 16:19
The only way to save your process is using savestate but no wants to use that because that would ruined the whole game play experience,

**Comment by tywald** [comment] 2017-08-10 18:21
Hm, I have never gotten this on either PSP version or HD version. Can you try reproduce it on a fresh PPSSPP?

It would be great if you can show in a video, I can also do it but I need to watch what you are doing first :p

**Comment by omarguerrero5310** [comment] 2017-08-10 20:00
How can I upload a video

**Comment by omarguerrero5310** [comment] 2017-08-10 20:13
https://youtu.be/S1oM8t5272w

**Comment by tywald** [comment] 2017-08-11 09:36
It looks like there is a PPSSPP setting that causes it since it fixed after you restored settings to default; cheats can also cause save corruption.

Try enable a setting one at a time until you get corrupt save again so we can know exactly what.

**Comment by Saramagrean** [comment] 2019-08-18 06:10
Turn off cheat before load savedata, it fixed.

**Comment by unknownbrackets** [comment] 2019-08-18 06:22
Thanks for confirming.  I'm going to close this then - most likely, cheats on a real PSP would also cause errors like this, then.

-[Unknown]

**Closed by unknownbrackets** 2019-08-18 06:22 UTC
Labels: Cheats
