### ISSUE TITLE
Phantasy Star Portable character creation issue

### ISSUE THREAD

**Issue by arnoldsecret** [hrydgard/ppsspp#12489] opened 2019-11-14 23:50 UTC
### What happens?
![Screenshot_20191114_105439](https://user-images.githubusercontent.com/41223243/68905480-4ac53a00-077c-11ea-9844-4fefdc4b5c05.png)

### What *should* happen?
The character appears and you can customize it.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP 1.9
Android 6.0.1

Note: This is a clone of issue #9151, but it's closed due to Android 7 fixing the issue, and my phone doesn't allow updating it to that version.

**Comment by unknownbrackets** [comment] 2020-01-02 01:00
What device though?  Is it an Adreno 4xx GPU?  If it's a driver bug, it's probably specific to the device.

We may not be able to do anything about a driver bug, though... especially one the vendor has already issued a fix for.

-[Unknown]

**Comment by arnoldsecret** [comment] 2020-01-02 01:55
It's an Adreno 3xx GPU.
![Screenshot_20200102_095334](https://user-images.githubusercontent.com/41223243/71648993-f420b900-2d45-11ea-92f0-1b26b942ef6b.png)

**Comment by Gamemulatorer** [comment] 2020-10-01 04:02
Duplicate of #11732

**Closed** 2020-10-01 06:49 UTC
