### ISSUE TITLE
Qix++ (Japan) (v1.02) Crash on now loading screen

### ISSUE THREAD

**Issue by Cibomatto2002** [hrydgard/ppsspp#9466] opened 2017-03-20 03:55 UTC
Qix++ (Japan) (v1.02) will crash on now loading screen. here is a video.

MD5: E696DEAAF6738895A0B99FFA2F418585
CRC32: 41212697
SHA1: A442BD2D575D76C4D93F345940FCBC58E8C86A7E

https://www.youtube.com/watch?v=JyX6ytV0C3k&feature=youtu.be

**Comment by unknownbrackets** [comment] 2017-03-20 04:01
Is this after you save, or before #8214?  Can you try an older version?  It would help to know if an older version worked, and if so, what the most recent build that worked was, and which build first started crashing.

If you try an older version from #8214 and it doesn't crash, you can go by half way in between and narrow it down fairly quickly.  If the one half way in between works, try halfway again to a newer build, otherwise try halfway the other direction to an older build.  Even if they are 2000 builds apart, you could find almost exactly when it started breaking by trying 11 builds.

-[Unknown]

**Comment by benderscruffy** [comment] 2017-03-20 04:21
it has something to do with the fonts
i used ppsspp fonts and it crashed
when i used my ones that i dumped from my psp there is no problems it goes ingame

**Comment by unknownbrackets** [comment] 2017-03-20 04:25
Ah, then perhaps a duplicate of #2788, unfortunately?

-[Unknown]

**Comment by Cibomatto2002** [comment] 2017-03-20 06:56
I had no idea you had to use fonts to get some games to work.

**Comment by hrydgard** [comment] 2017-03-20 08:11
It's unfortunate, and the free fonts we do have work "ok" in some games, but could really use improvement - as this example shows (and several where it's just ugly) they aren't good enough.

**Comment by sum2012** [comment] 2017-05-07 13:22
@hrydgard jpcsp just fix this game by real psp value of maxGlyphBaseYI ,maxBitmapWidth ,maxBitmapHeight
in https://github.com/jpcsp/jpcsp/commit/48cb223da4cfb031fbce5e12ff068e0709860efc 
So that we are possible to fix in ppsspp too.
I reopen this issue

**Comment by hrydgard** [comment] 2017-05-07 16:03
Did a quick attempt, please test!

**Comment by sum2012** [comment] 2017-05-07 22:20
@hrydgard Well done,fixed.
Log: https://gist.github.com/sum2012/d3340a5aeeb73c305abfd9c7684fe7d2

**Comment by hrydgard** [comment] 2017-05-07 23:08
Well, "worked around", the real fix would be fixing the font files, as Unknown correctly says in #9672.

**Comment by benderscruffy** [comment] 2018-11-26 03:08
in v1.7.1-195-g04f57bd49
using ppsspp fonts the menus are glitched then as you start the first stage  the screen goes black 
![qix](https://user-images.githubusercontent.com/2696404/48990834-14f20480-f16b-11e8-8a8e-14037391c4f3.PNG)
![qix1](https://user-images.githubusercontent.com/2696404/48990841-17545e80-f16b-11e8-83fe-edfc2da65dcb.PNG)
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2613929/ppsspplog.zip)
using my own dumped fonts no problem with the menus 
goes ingame but when you close it down and load up qix again it is stuck in an endless loop about no save  data found

**Comment by nassau-tk** [comment] 2020-09-17 11:44
@hrydgard 
@unknownbrackets 
@sum2012 
@benderscruffy 
@Cibomatto2002 
@shenweip 
@Panderner

I tested v1.10.3-700 on Windows10(64-bit) and 2 type font.

**Case1: All of Real PSP Font installed.(PSP-2000)**
![QIX++(NPJH50199)_Win10_All RealPSPFont_01](https://user-images.githubusercontent.com/48179091/93464933-0028c700-f925-11ea-8d03-536a91e06521.png)

**It's not glitched and don't happen Invalid Memory Access Error.**

**Case2: All of PPSSPP Original Font installed.**
![QIX++(NPJH50199)_Win10_All PPSSPPFont_01](https://user-images.githubusercontent.com/48179091/93465090-3ebe8180-f925-11ea-81ba-c1f528cddaee.png)

**It's glitched and happen Invalid Memory Access Error.**

**Installed Real Font below.**
![RealPSPFont](https://user-images.githubusercontent.com/48179091/93465422-b7254280-f925-11ea-97e0-a03c35a29097.png)

I understanding that Android Device is not use font of "Font folder Files".
But,Android is not happen glitch and Invalid Memory Access Error.
I don't know why.

**Comment by Panderner** [comment] 2020-09-17 12:27
> @hrydgard
> @unknownbrackets
> @sum2012
> @benderscruffy
> @Cibomatto2002
> @shenweip
> @Panderner
> 
> I tested v1.10.3-700 on Windows10(64-bit) and 2 type font.
> 
> **Case1: All of Real PSP Font installed.(PSP-2000)**
> ![QIX++(NPJH50199)_Win10_All RealPSPFont_01](https://user-images.githubusercontent.com/48179091/93464933-0028c700-f925-11ea-8d03-536a91e06521.png)
> 
> **It's not glitched and don't happen Invalid Memory Access Error.**
> 
> **Case2: All of PPSSPP Original Font installed.**
> ![QIX++(NPJH50199)_Win10_All PPSSPPFont_01](https://user-images.githubusercontent.com/48179091/93465090-3ebe8180-f925-11ea-81ba-c1f528cddaee.png)
> 
> **It's glitched and happen Invalid Memory Access Error.**
> 
> **Installed Real Font below.**
> ![RealPSPFont](https://user-images.githubusercontent.com/48179091/93465422-b7254280-f925-11ea-97e0-a03c35a29097.png)
> 
> I understanding that Android Device is not use font of "Font folder Files".
> But,Android is not happen glitch and Invalid Memory Access Error.
> I don't know why.

@nassau-tk This is why Qix++ needs an all PSP fonts to be installed because the texts in menus are glitched and it's crash when i started the game without the real PSP fonts. and same happens to Jeanne d'Arc needs a real PSP fonts to render the text correctly in dialogue.

**Comment by shenweip** [comment] 2020-09-17 12:57
Yeah, this game need a real PSP fonts for now, you can replace the font files in PSP with ppsspp font files, and then PSP will crash too, so as @hrydgard and @unknownbrackets say above, the real fix would be fixing the font files.

**Comment by nassau-tk** [comment] 2020-09-17 13:41
@shenweip 
@Panderner

Yes,I understand about this issue.
Thank you for your teaching!!

**Comment by nassau-tk** [comment] 2020-10-09 16:50
I tested finding important "ltn_X.pgf".
I found this.
Install only **"ltn8.pgf"** Real PSP Font to PPSSPP default fonts.
And I was able to through the invalid memory access error.
And,I tested other font that converted from ttf to pgf.
But,It was not able to through the error.

This game needs a "correct ltn8.pgf" for playing.
"Correct ltn8.pgf means?"
Um...I don't know...

**Comment by nassau-tk** [comment] 2020-10-15 16:32
I was able to understand the why text glitch will happen.

[ltn0.pgf]
[ltn0.pgf]
[ltn0.pgf]
[ltn0.pgf]
[ltn0.pgf]
[ltn0.pgf]
[ltn0.pgf]
[ltn0.pgf]

**Comment by nassau-tk** [comment] 2020-10-15 17:51
I was able to understand the why text glitch will happen.

[ltn0.pgf] Gothic Type Font about 24point **[Base Font1]**
[ltn1.pgf] Antique Type Font about 24point **[Base Font2]**
[ltn2.pgf] "ltn0.pgf" + Italic shape
[ltn3.pgf] "ltn1.pgf" + Italic shape
[ltn4.pgf] "ltn0.pgf" + Bold shape
[ltn5.pgf] "ltn1.pgf" + Bold shape
[ltn6.pgf] "ltn0.pgf" + Italic&Bold shape
[ltn7.pgf] "ltn1.pgf" + Italic&Bold shape
[ltn8.pgf] Gothic Type Font about 14 to 16point **[Base Font3]**
[ltn9.pgf] Antique Type Font about 14 to 16point **[Base Font4]**
[ltn10.pgf] "ltn8.pgf" + Italic shape
[ltn11.pgf] "ltn9.pgf" + Italic shape
[ltn12.pgf] "ltn8.pgf" + Bold shape
[ltn13.pgf] "ltn9.pgf" + Bold shape
[ltn14.pgf] "ltn8.pgf" + Italic&Bold shape
[ltn15.pgf] "ltn9.pgf" + Italic&Bold shape

These ltn[x].pgf is Real PSP font inforomation.
And,PPSSPP's fonts are not match specification these font.

I tested some patern of convert from ttf font.
But,"ttf2pgfj" will not convert "ltn1.pgf" ~ "ltn15.pgf" correctly.
It's can't be create characters margin (right & left) and bottom clearance.

![font_ltn_RealPSP](https://user-images.githubusercontent.com/48179091/96167265-1a70b780-0f5a-11eb-819b-056212fcec70.gif)


I will just Report!!

**Comment by nassau-tk** [comment] 2020-11-24 14:19
Hello every one!!

I'm testing for ltn8.pgf making.
And,It will working on QIX++.
(Character Balance is not tuned yet.)
https://drive.google.com/file/d/1fYpmrc8eDlokvdDn-_URR7hSxQFT6D1H/view?usp=sharing

The number of characters was squeezed and made.
![image](https://user-images.githubusercontent.com/48179091/100104682-d69e9580-2ea9-11eb-999f-d8e0936cfd72.png)

It was adjusted so that the following item might become same as the original.
""max glyph width  : 16""
""max glyph height : 14""
![image](https://user-images.githubusercontent.com/48179091/100104823-0188e980-2eaa-11eb-8e22-65225c12ddb2.png)

[Result]
![image](https://user-images.githubusercontent.com/48179091/100105090-5167b080-2eaa-11eb-8a6e-cd54183233bf.png)

![image](https://user-images.githubusercontent.com/48179091/100105186-69d7cb00-2eaa-11eb-8046-890dbe20ac2f.png)

![image](https://user-images.githubusercontent.com/48179091/100105223-73f9c980-2eaa-11eb-8a63-7e7d79eb768c.png)

![image](https://user-images.githubusercontent.com/48179091/100105262-7f4cf500-2eaa-11eb-8e05-cd7e1ba2261d.png)

![image](https://user-images.githubusercontent.com/48179091/100105319-90960180-2eaa-11eb-99b7-c794dcbf10be.png)

**Possibility coming?**
I will continue to try.

**Comment by hrydgard** [comment] 2020-11-24 15:08
Definitely looks like an improvement! Weird with those question marks though in "Hi?Score" etc.

**Comment by nassau-tk** [comment] 2020-11-24 22:24
> Weird with those question marks though in "Hi?Score" etc.

Yes,The reason is delete many characters from TTF file.:smiling_imp:
So,Maybe I deleted needed file.:laughing:

**Comment by nassau-tk** [comment] 2020-11-27 16:49
Help!!
#13718

**Comment by nassau-tk** [comment] 2020-11-29 13:30
@Cibomatto2002 
@hrydgard 
@unknownbrackets 
@sum2012 

This issue will solved.

v1.10.3-1268-gb5e230077
Change ltn x font (#13721) * Modified ltn8~15.pgf (Small Latin) This modified fonts will solved #9466.(QIX++) And,It will solved the few part of #2788 too.(Example:LUNAR)

**Comment by hrydgard** [comment] 2020-11-29 18:31
Great!

**Closed by hrydgard** 2020-11-29 18:31 UTC
Labels: PGF / sceFont
