### ISSUE TITLE
 monster Hunter portable 3rd wont boot up

### ISSUE THREAD

**Issue by omarsupercool5310** [hrydgard/ppsspp#9861] opened 2017-07-24 19:56 UTC
The whole ppsspp app crashes when loading the game

**Comment by tywald** [comment] 2017-07-24 21:01
You should probably fill more details, like PPSSPP version, device information etc. Try with older versions and see if it worked in the past or not and if it did, pinpoint which build started it.

If you are running the PSP version of the game(i.e not the HD version), you will need something called 'PAUTH' or the game won't work properly.

**Comment by unknownbrackets** [comment] 2017-07-30 18:07
Assuming it's the pauth thing - I'm going to close this as a duplicate of #5950.

If it's something else, feel free to reply to this issue and we'll reopen.

-[Unknown]

**Closed by unknownbrackets** 2017-07-30 18:07 UTC
