### ISSUE TITLE
Graphical bug on the 3rd birthday.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10951] opened 2018-04-21 23:19 UTC
What happens?
Using opengl renderer with default settings on latest ppsspp build for Android this happens:
![screenshot_20180421-175543](https://user-images.githubusercontent.com/6578180/39089580-5758c534-4590-11e8-9786-6f49863ae418.png)

What *should* happen?
Not that I think.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Motog5 plus Android 7.

**Comment by Drasikk** [comment] 2018-04-22 00:07
You have to activate the option that says "deactivate faster effects".

**Comment by marosis** [comment] 2018-04-22 06:27
Isn't it created when clicking to loading state?

**Comment by Jinzombie** [comment] 2018-04-22 09:51
![screenshot_2018-04-22-17-49-06](https://user-images.githubusercontent.com/37603562/39093659-96850bbe-4612-11e8-9560-7b086088f9a7.png)

**Comment by Jinzombie** [comment] 2018-04-22 09:52
weird also happen to me 😟
Using the latest build 1.5.4-931

**Comment by leopard20** [comment] 2018-04-22 10:28
Now that you're looking into this, you might also wanna fix the orange silhouette that appears when your do certain things, such as opening and closing the menu (or map)  and when you overdive.

**Comment by leopard20** [comment] 2018-04-22 10:30
P.S This issue (plus what I said above) has always been there since v1.5.4 on OpenGL, Vulkan works fine (not the above issue though)

**Comment by Jinzombie** [comment] 2018-04-22 10:33
![screenshot_2018-04-22-18-32-03](https://user-images.githubusercontent.com/37603562/39094020-85bb2218-4618-11e8-869f-ee45e01c8ba6.png)

**Comment by Jinzombie** [comment] 2018-04-22 10:34
In the build 1.5.4-530 enable disbale slower effects fix the issue unlike in the latest build 1.5.4-931 the graphic bug is still there even disable slower effects is on?

**Comment by unknownbrackets** [comment] 2018-04-22 14:00
We want this to work with "disable slower effects" unchecked.  Can anyone test backwards and find the first git build that started rendering wrong?

-[Unknown]

**Comment by Jinzombie** [comment] 2018-04-22 14:29
I tried build 1.5.4-484 where faster-multithreaded is enable? but the game crash after loading then I download build 1.5.4-501 the graphic bug is still there :(

*Sorry for my bad english

**Comment by unknownbrackets** [comment] 2018-04-22 17:01
Regression in #10411, range:

https://github.com/hrydgard/ppsspp/compare/2ae2dd7d406342deb4851f583b359a87d874a11f...970458a0c293f7fbba6520ed9e22156316d09983 (unfortunately it crashes or misbehaves differently in all of these.)

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-04-22 17:38
Seems like it's related to ApplyTexture moving maybe?
https://github.com/hrydgard/ppsspp/pull/10411/files#r160579027

It's only seeing 120px width of the depal and never blitting the rest, AFAICT.

-[Unknown]

**Closed** 2018-04-22 19:01 UTC
Labels: OpenGL
