### ISSUE TITLE
Mario boat 1.1 (homebrew)fails to load

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9076] opened 2016-10-15 02:10 UTC
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mario-boat/Mario%20Boat%201.1%20PSP.rar

failed to load executable

it loads on my psp-3000 no problems at all

**Comment by LunaMoo** [comment] 2017-05-30 08:54
Closing this as a duplicate of #4676.

This problem can't be solved by just writing some code, in fact we do have the code for decrypting stuff;p, just not all of the keys. Unfortunately people who sign/encrypt their homebrew choose keys that you can only find on psp, so you will only be able to run such homebrew after decrypting it's executable file(DATA.PSP packed inside EBOOT.PBP) on real psp with cfw(using decrypting homebrew).

**Closed by LunaMoo** 2017-05-30 08:54 UTC
