### ISSUE TITLE
Save states broken in v1.10.3-586-g901239c05 ?

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13395] opened 2020-09-06 21:07 UTC
I update to the latest version in automated build. This one v1.10.3-586-g901239c05. Whenever i load state and save state ppsspp crashed. But when i load from the memory and save state, it's not force closed. So in my case it only happen when i load my state and save my state.

**Comment by Lemoncak3** [comment] 2020-09-07 06:32
It only happen with old save state, i tried with new save state and it work fine.

**Comment by hrydgard** [comment] 2020-09-07 07:01
Thanks for reporting, I'll take a look.

**Comment by hrydgard** [comment] 2020-09-07 07:04
I can't reproduce this on Windows. Which game are you having this problem with? Or all games?

Which platform?

**Comment by hrydgard** [comment] 2020-09-07 07:57
How old was the savestate you tried_

**Comment by Lemoncak3** [comment] 2020-09-07 08:08
![Screenshot_20200907-150724](https://user-images.githubusercontent.com/67026697/92363601-ee247880-f11b-11ea-820e-c8c2f32eb23f.png)

The first one in this picture. But when i created another new save state and load it and save, it has no problem at all

**Comment by hrydgard** [comment] 2020-09-07 08:22
That game is Kingdom Hearts right?

Have you tried many builds? We had a save state break a little while ago, maybe you saved during that time...

**Comment by Lemoncak3** [comment] 2020-09-07 08:31
Oh okay i tried with other game then, will inform the result later

**Comment by Lemoncak3** [comment] 2020-09-07 08:35
Try with tales of radiant mithology, same issue using the june save state 
![Screenshot_20200907-153252](https://user-images.githubusercontent.com/67026697/92366600-91c35800-f11f-11ea-9251-af9909e3eeab.png)
Try with growlanser wayfarer of time, have same issu too using the july one 
![Screenshot_20200907-153242](https://user-images.githubusercontent.com/67026697/92366716-b7506180-f11f-11ea-96a3-085a738a6bab.png)
And last try using persona, same issue using the august one
![Screenshot_20200907-153316](https://user-images.githubusercontent.com/67026697/92366765-c46d5080-f11f-11ea-98e9-d0bcb5f38d72.png)

**Comment by hrydgard** [comment] 2020-09-07 09:06
Could you upload the broken Persona state file in a zip file here? (just drop the zip into the message)?

Can you go into Settings Tools/System Information on your device and take a screenshot?

**Comment by nassau-tk** [comment] 2020-09-07 11:30
@hrydgard 

Me too!! 
Ys YS I&II Chronicles (ULJM05474)
[Ys_I&II_Chronicle_savestate.zip](https://github.com/hrydgard/ppsspp/files/5182829/Ys_I.II_Chronicle_savestate.zip)
Master data is "ULJM05474_1.01_0.undo.ppst"
I tried overwrite the statesave.
The data is "ULJM05474_1.01_0.ppst"

Error warning was appear about 3times.
![Ys_state_issue](https://user-images.githubusercontent.com/48179091/92383035-994b2700-f148-11ea-8550-ca6fae30fcb7.png)

**Comment by MiguelCardonaG** [comment] 2020-11-12 10:50
@hrydgard Save state images do not look correctly:

![Screenshot_20201112-113920_PPSSPP](https://user-images.githubusercontent.com/65356692/98930359-d206d400-24dc-11eb-97dd-dbe0ce5da61e.jpg)

![Screenshot_20201112-113944_PPSSPP](https://user-images.githubusercontent.com/65356692/98930402-e0ed8680-24dc-11eb-93cc-21742bb37f12.jpg)

![Screenshot_20201112-113939_PPSSPP](https://user-images.githubusercontent.com/65356692/98930437-eea30c00-24dc-11eb-826c-5d1d6fac30b1.jpg)

A few days ago it was going well:

![Screenshot_20201112-113752_PPSSPP](https://user-images.githubusercontent.com/65356692/98930524-1003f800-24dd-11eb-94e4-e14e56cf0e2b.jpg)

In some games it goes well and in others it doesn't.

**Comment by MiguelCardonaG** [comment] 2020-11-20 14:41
@hrydgard It already works well with the latest builds, you can close it.

**Closed** 2020-11-20 14:58 UTC
