### ISSUE TITLE
PPSSPP game loading issue

### ISSUE THREAD

**Issue by burnthill** [hrydgard/ppsspp#8910] opened 2016-08-11 07:44 UTC
Recently I got an ipad mini 2 on ios 9.3.3 and jailbroke it through pangu with the intent of playing emulators. The only emulator giving me issues so far is PPSSPP. I tried downloading through cydia however on the summary page it says the newest version of PPSSPP can only work on idevices between ios5-7 (kinda silly). So instead I downloaded the "old" PPSSPP emulator from iemulator.com using the airplane mode trick. I can open the app but whenever I try to open/play a game the whole thung crashes (I have tried multiples games). I have tried different recommened settings also but still no luck. Can anyone at all please help?

**Comment by jccultima123** [comment] 2016-08-11 11:48
@burnthill It's may be your **old version** of PPSSPP provided for this kind of platform that is hard to coupe up/fix issues

**Comment by burnthill** [comment] 2016-08-11 15:18
@jccultima123 How do I go about downloading the new version as the date trick didn't seem to work for me? Is there anyway to download from Cydia which is for IOS 9.3.3?

**Comment by unknownbrackets** [comment] 2016-08-11 15:44
There exists no version of PPSSPP compatible with newer iOS versions on 64-bit devices.  The supported versions were changed because Apple broke PPSSPP by preventing jit from working.

This issue is being closed as a duplicate of #8122.

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2016-08-11 15:44 UTC
