### ISSUE TITLE
Menu decoration idea

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10103] opened 2017-11-12 21:12 UTC
THIS IS NOT PROBLEM IN GAME! ONLY IDEA. some  games also contain an ever-repeating video in psp menu. I think if the same thing was in ppsspp the overall look of the menu would look better. it's just my opinion :).

**Comment by LunaMoo** [comment] 2017-11-12 22:02
Closing as a duplicate of #2585

**Closed by LunaMoo** 2017-11-12 22:02 UTC

**Comment by marosis** [comment] 2017-11-12 22:11
Aha. Thanks lunamoo i didn't know about it
