### ISSUE TITLE
PPSSPP's Japanese keyboard unable to enter '・'  '。' '、' '「' '」' '『' '』' '〜' etc characters.

### ISSUE THREAD

**Issue by headHz** [hrydgard/ppsspp#14311] opened 2021-03-21 23:43 UTC
![image](https://user-images.githubusercontent.com/1572493/111924385-82737e80-8a61-11eb-9344-e7776514cbca.png)

There is no way to enter full-width Japanese punctuation with PPSSPP's Japanese keyboard. I noticed this when entering passwords in Lord of Apocalypse [NPJH50503], since two of the passwords 'いんぷれす・げーむうぉっち' and 'そうごうげーむじょうほうさいと・げーむすぽっとじゃぱん' contain ・. 

This is for both Windows and Android, using 1.11.3 on both.

**Comment by nassau-tk** [comment] 2021-03-23 12:14
Related & Duplicate #13712 .

**Comment by LunaMoo** [comment] 2021-03-26 01:50
It's not really a duplicate, through on platforms where using system native keyboard works without problems it is a legit workaround for any missing input.
 In most cases it's actually easier to just copy and paste things like game passwords via native keyboard support instead of typing it by selecting glyphs one by one.

**Comment by nassau-tk** [comment] 2021-03-26 16:07
@LunaMoo 

> @headHz try going to PPSSPP's system settings, and enable "Use native system keyboard" then just copy paste your passwords instead using that pad-controlled OSK.

Yes,But It can't do that on Windows Fullscreen mode. (#13712 )
We must change to window mode.

Android is no problem.

**Comment by nassau-tk** [comment] 2021-03-30 09:29
@headHz 

What did you want about the issue?

If you want use system native keyboard on Windows full screen mode then the issue meanings duplicate of #13712 .
So, You should close this issue.

But, If you say "No" then you should try and report your result for advice of @LunaMoo .

**Comment by unknownbrackets** [comment] 2021-06-17 02:27
Not all platforms have access to the native keyboard though.  Ideally, we should include all the characters that were available on a PSP...

-[Unknown]

**Comment by nassau-tk** [comment] 2021-06-17 07:18
> Not all platforms have access to the native keyboard though. Ideally, we should include all the characters that were available on a PSP...
> 
> -[Unknown]

Is it means thta include Kanji too?!

**Comment by hrydgard** [comment] 2021-06-17 07:19
Ideally, though I don't know enough about kanji to make a usable way to select between them..

**Closed** 2021-06-20 18:49 UTC
Labels: Input/Controller
