### ISSUE TITLE
Installing with Trollstore

### ISSUE THREAD

**Issue by omarc08** [hrydgard/ppsspp#16178] opened 2022-10-08 17:33 UTC
Hello. I would like to know how to install PPSSPP using Trollstore. When I tried before, it installed but I couldn't add any games because the folder where I was supposed to put them in wasn't there.

**Comment by Gamemulatorer** [comment] 2022-10-08 17:41
Related https://github.com/hrydgard/ppsspp/issues/16019

**Comment by unknownbrackets** [comment] 2022-10-08 18:11
This issue is being closed as a duplicate of #16019.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-10-08 18:11 UTC
