### ISSUE TITLE
Time stretch audio/asyncmix feature in future build

### ISSUE THREAD

**Issue by kenobizero** [hrydgard/ppsspp#15430] opened 2022-03-08 11:25 UTC
### What should happen

It would be better if ppsspp have this option to eliminate choppy sound on low specs

### Who would this benefit

Developers

### Platform (if relevant)

Android

### Games this would be useful in

All psp games

### Other emulators or software with a similar feature

Aethersx2,
 mupen64fz,  dolphin, citra. Pcsx2

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment] 2022-03-08 13:31
If i'm not mistaken, you just need to change the pitch to follow the performance percentage, thus the sound will be low pitch on slow performance and high pitch when fast forwarded.

**Comment by kenobizero** [comment] 2022-03-08 14:41
So you mean I have to change the volume about 30 percent to reduce the crackling sound ?

**Comment by hrydgard** [comment] 2022-03-08 14:46
No, ANR2ME is suggesting what PPSSPP could do. PPSSPP actually already does this to a small extent to cover up small deviations from the intended framerate, but limits itself to a few percent, then the sound starts breaking up instead. Larger frequency shifts will sound odd, instead we'd need a chop-and-overlap time stretcher or similar.

**Comment by EternalsDarkhole** [comment] 2022-03-08 15:15
Duplicate of https://github.com/hrydgard/ppsspp/issues/8412

**Closed** 2022-03-08 15:18 UTC

**Comment by EternalsDarkhole** [comment] 2022-03-12 07:36
There's is an attempt https://github.com/hrydgard/ppsspp/pull/8717 but no good results :(
