### ISSUE TITLE
Why does the PPA version still at 1.5.4?

### ISSUE THREAD

**Issue by WattanaGaming** [hrydgard/ppsspp#11311] opened 2018-08-19 09:50 UTC
I just cant accept it, the build version is just darn unstable on ubuntu 18.04 lts, crash everytime when entering a game that was already played and sometimes corrupt the ppsspp.ini and controls.ini. i just need the PPA version but it just stuck there

**Comment by unknownbrackets** [comment] 2018-08-19 15:25
This issue is being closed as a duplicate of #11138.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-08-19 15:25 UTC

**Comment by WattanaGaming** [comment] 2018-08-21 22:36
Thanks! the link is really useful
