### ISSUE TITLE
PPSSPP 1.5.4 - Post-processing error.

### ISSUE THREAD

**Issue by JhonLoveJoy** [hrydgard/ppsspp#10363] opened 2017-12-06 22:33 UTC
When active the post-processing effects i get this error message: i.imgur.com/adU45h6.png

**GPU:** 6630M 
**OS:** Windows 7 x64

**Comment by thedax** [comment] 2017-12-06 22:41
Related to https://github.com/hrydgard/ppsspp/issues/10362, perhaps?

**Comment by hrydgard** [comment] 2017-12-06 23:42
Yup, same thing there. I'll rename that one.

Closing as duplicate of #10362.

**Closed by hrydgard** 2017-12-06 23:42 UTC
Labels: OpenGL
