### ISSUE TITLE
[iOS 14.2] Texture error on "Kamen Rider: Super Climax Heroes" (NPJH50691)

### ISSUE THREAD

**Issue by xsm1997** [hrydgard/ppsspp#13675] opened 2020-11-18 12:25 UTC
There are texture errors when playing "Kamen Rider: Super Climax Heroes" (NPJH50691) using PPSSPP v1.10.3-1220 on iPad mini 5 (iOS 14.2), which leads the game almost unplayable.

![QQ20201118-0](https://user-images.githubusercontent.com/4453837/99528214-eebd7300-29d8-11eb-8d11-05885cbfe7b6.png)

Note that I was using JIT on iOS 14.2 (by adding the extended virtual address capability on XCode) when taking the screenshot. But whether I am using JIT or not, even with IR interpreter, the errors persist. Thus, it should has little things to do with JIT.

In addition, after I load another game which can be played normally, relaunching the game showed me another style of texture errors.

![img_0126](https://user-images.githubusercontent.com/4453837/99528609-83c06c00-29d9-11eb-875c-114302b3e1f9.png)
(Note the Japanese characters on the bottom are missing.)

Here is the log which was copied from XCode debugger output from a debug version of PPSSPP without JIT enabled (using IR interpreter, will be described later).

[log.txt](https://github.com/hrydgard/ppsspp/files/5559867/log.txt)

By the way, on iOS 14.2 with the extended virtual address capability enabled, it is already not necessary to do the debugger hack things. I removed the debugger hack code in main.mm, and it still works properly. But it seems that iOS 14.2 still only allow W^X JIT, for I removed the iOS check in PlatformIsWXExclusive() in MemoryUtil.cpp, and it crashed with a BAD_ACCESS error.

Weird enough that if I compiles the debug version and load this game, PPSSPP with JIT crashes with a BAD_ACCESS error in the Write32(u32 value) function in Arm64Emitter.h, while no crashes but texture errors on release version. But I can play other games without any crash or error using the debug version. When I uses IR interpreter, the debug version of PPSSPP no longer crashes. Are there any differences on JIT between debug and release versions? Should the JIT error consider unrelated from the texture error?

**Comment by xsm1997** [comment] 2020-11-18 12:30
I tried PPSSPP v1.10.3 release version and the texture errors persist. And PPSSPP v1.10.3 on Android seems not to have those errors.

**Comment by hrydgard** [comment] 2020-11-18 12:32
Yeah this bug seems to be something in the iOS 14.2 OpenGL driver. I have no other explanation.

I'm going to try to get my hands on a test device soon so I can investigate.

**Comment by Panderner** [comment] 2020-11-19 03:12
it works fine for me running on Realme C2
![Screenshot_2020-11-19-11-01-37-89_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/99616358-10aa0a80-2a58-11eb-985d-1eada8946773.png)

**Comment by hrydgard** [comment] 2020-11-29 18:01
Duplicate of #13451

**Closed by hrydgard** 2020-11-29 18:01 UTC
