### ISSUE TITLE
Full-screen mode on phones with a camera inside the screen (notched)

### ISSUE THREAD

**Issue by allfamebutme** [hrydgard/ppsspp#12261] opened 2019-08-20 19:55 UTC
### What happens?
PPSSPP doesn’t work in full screen mode, with the dive mode I get a white strip that cuts the space from the beginning of the camera.
![PEQpQmXZtO4](https://user-images.githubusercontent.com/54332092/63379591-4f589d00-c39d-11e9-91da-736b6339b5cf.jpg)

### What *should* happen?

The image will stretch to full screen including the space around the camera. As in other emulators.
![с](https://user-images.githubusercontent.com/54332092/63379719-8f1f8480-c39d-11e9-8a66-c7327577abcd.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy A60
Android 9.0
PPSSPP v1.8.0

**Comment by Abbanon** [comment] 2019-08-20 20:06
Just adding this here:
It was briefly mentioned in #12229 (after the issue was closed) by Henrik, so the issue is known to exist for notched phones it just hasn't been fixed yet.

**Comment by Florin9doi** [comment] 2019-08-21 09:56
May be fixed by #12264

**Comment by Halo-Michael** [comment] 2019-09-13 10:30
And please add FullScreen button for iOS

**Comment by hrydgard** [comment] 2020-03-30 22:50
See #12779 .

**Closed** 2020-03-31 01:10 UTC
Labels: Platform-specific (Android)

**Comment by Panderner** [comment] 2020-03-31 01:47
And how about iPhone X, XS, XR and 11 Devices? it has notches
![IMG_20200331_094428](https://user-images.githubusercontent.com/37503397/77978408-a7448280-7334-11ea-9ba1-04f1d99893cf.jpg)
