### ISSUE TITLE
Daedalusx64 crashing ppsspp (saw this issue but it was closed?)

### ISSUE THREAD

**Issue by Xbox-Series-X-User** [hrydgard/ppsspp#14771] opened 2021-08-29 09:23 UTC
### Game or games this happens in

none

### What area of the game / PPSSPP

Crashes at attempt to boot 1.1.8 version of dx64

### What should happen

![image](https://user-images.githubusercontent.com/86686097/131245229-f8036b56-4c12-4c8e-af24-777448abd079.png)
 should boot to the rom selection screen

### Logs

39:29:347 elf\elfreader.cpp:553 E[LOADER]: Trying to relocate non-loaded section (null)
39:29:430 root         N[BOOT]: ui\emuscreen.cpp:341 Loading C:/Users/sk/Downloads/ppsspp/memstick/PSP/GAME/DaedalusX64...
39:29:605 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:606 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:615 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: bfc00600 (00000149BD880600)
39:29:615 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: bfc00604 (00000149BD880604)
39:29:616 user_main    E[HLE]: hle\hle.cpp:733 Unimplemented HLE function sceKernelDcacheWritebackAll
39:29:616 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:616 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:616 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:616 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:616 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:616 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:627 user_main    E[HLE]: hle\hle.cpp:733 Unimplemented HLE function scePowerLock
39:29:628 user_main    E[FILESYS]: filesystems\directoryfilesystem.cpp:65 DirectoryFileSystem::OpenFile('/kd/registry.prx'): FAILED, 3 - access = 3 'The system cannot find the path specified.

'
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:634 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:635 user_main    E[FILESYS]: filesystems\directoryfilesystem.cpp:65 DirectoryFileSystem::OpenFile('/PSP/GAME/DaedalusX64/rom.db'): FAILED, 2 - access = 1 'The system cannot find the file specified.

'
39:29:869 user_main    E[SCEKERNEL]: util\blockallocator.cpp:142 Block Allocator (08800000-0c000000) failed to allocate 1573120 (00180100) bytes of contiguous memory
39:29:869 user_main    E[SCEKERNEL]: hle\scekernelmemory.cpp:1032 sceKernelAllocPartitionMemory(partition = 5, , type= 0, size= 1572887, addr= 00000000): allocation failed
39:29:869 user_main    E[SCEKERNEL]: util\blockallocator.cpp:142 Block Allocator (08800000-0c000000) failed to allocate 1048832 (00100100) bytes of contiguous memory
39:29:869 user_main    E[SCEKERNEL]: hle\scekernelmemory.cpp:1032 sceKernelAllocPartitionMemory(partition = 5, , type= 0, size= 1048584, addr= 00000000): allocation failed
39:29:869 user_main    E[SCEKERNEL]: util\blockallocator.cpp:142 Block Allocator (08800000-0c000000) failed to allocate 1048832 (00100100) bytes of contiguous memory
39:29:869 user_main    E[SCEKERNEL]: hle\scekernelmemory.cpp:1032 sceKernelAllocPartitionMemory(partition = 5, , type= 0, size= 1048584, addr= 00000000): allocation failed
39:29:870 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:870 user_main    E[HLE]: hle\hle.cpp:668 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
39:29:884 user_main    E[G3D]: gpu\gpucommon.cpp:695 sceGeListEnqueue: invalid address 40000000
39:29:884 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000000 (000001493DC80000)
39:29:884 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000004 (000001493DC80004)
39:29:884 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000008 (000001493DC80008)
39:29:884 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000000c (000001493DC8000C)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000010 (000001493DC80010)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000014 (000001493DC80014)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000018 (000001493DC80018)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000001c (000001493DC8001C)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000020 (000001493DC80020)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000024 (000001493DC80024)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000028 (000001493DC80028)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000002c (000001493DC8002C)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000030 (000001493DC80030)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000034 (000001493DC80034)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000038 (000001493DC80038)
39:29:885 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000003c (000001493DC8003C)
39:29:886 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000040 (000001493DC80040)
39:29:886 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000044 (000001493DC80044)
39:29:886 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000048 (000001493DC80048)
39:29:886 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000004c (000001493DC8004C)
39:29:886 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000050 (000001493DC80050)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000054 (000001493DC80054)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000058 (000001493DC80058)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000005c (000001493DC8005C)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000060 (000001493DC80060)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000064 (000001493DC80064)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000068 (000001493DC80068)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000006c (000001493DC8006C)
39:29:901 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000070 (000001493DC80070)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000074 (000001493DC80074)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000078 (000001493DC80078)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000007c (000001493DC8007C)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000080 (000001493DC80080)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000084 (000001493DC80084)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000088 (000001493DC80088)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000008c (000001493DC8008C)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000090 (000001493DC80090)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000094 (000001493DC80094)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000098 (000001493DC80098)
39:29:902 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 4000009c (000001493DC8009C)
39:29:903 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 400000a0 (000001493DC800A0)
39:29:903 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 400000a4 (000001493DC800A4)
39:29:903 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 400000a8 (000001493DC800A8)
39:29:903 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 400000ac (000001493DC800AC)
39:29:918 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000000 (000001493DC80000)
39:29:918 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 40000000 (000001493DC80000)
39:29:920 user_main    E[FILESYS]: filesystems\directoryfilesystem.cpp:65 DirectoryFileSystem::OpenFile('/PSP/GAME/DaedalusX64/preferences.ini'): FAILED, 2 - access = 1 'The system cannot find the file specified.

'
39:29:969 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 000002bc (00000148FDC802BC)
39:29:969 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 000002b8 (00000148FDC802B8)
39:29:969 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 000002c4 (00000148FDC802C4)
39:29:969 user_main    E[MEMMAP]: core\memfault.cpp:201 Bad memory access detected and ignored: 000002c8 (00000148FDC802C8)

### Platform

Windows

### Mobile phone model or graphics card

Intel hd 530

### PPSSPP version affected

all

### Last working version

none

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Xbox-Series-X-User** [comment] 2021-08-29 09:24
not sure how to find the log files so had to screenshot it sorry

**Comment by Panderner** [comment] 2021-08-29 09:56
This must be related to #12481

**Comment by Xbox-Series-X-User** [comment] 2021-08-29 10:00
thanks didn't see that

**Comment by LunaMoo** [comment] 2021-08-29 10:39
Closing as a duplicate of the mentioned issue, I don't think we need separate issues for each homebrew emulator written for PSP as they're a bunch of optimized/hackish software which by design has no chance of ever fully working with high level emulator like PPSSPP which by design doesn't emulate hardware nor all of it's quirks, so the issue stands more useful about sharing info how to try to run them for biggest chance of success and potential list of working ones than hoping it will ever be fixed.

 You should try to find a native emulator dedicated to your hardware/OS instead and if you're really desperate look around PPSSPP forums as a bunch of homebrew emulators has outdated(ie less optimized) versions which users reported working or require disabling specific features in those emulators to make them work.
 For example some user reported disabling dynamic recompilator and async audio in Daedalusx64 allows it to boot games(at least those few it works with, it's by no means a compatible nor fast N64 emu).

**Closed by LunaMoo** 2021-08-29 10:39 UTC

**Comment by Xbox-Series-X-User** [comment] 2021-08-29 11:16
it would be mostly for debugging the emulator to make it better thanks for the info i will look for a possible working version

**Comment by hrydgard** [comment] 2021-08-29 16:24
This and a few other emulators use the PSP's Media Engine extra CPU, which is normally not directly accessible by games so is not emulated.

We consider emulating it out-of-scope for now - it may happen one day, but there's little reason to do it just for emulators, you're better off running native emulators on your system than running them inside PPSSPP.
