### ISSUE TITLE
"Under water" bug in OpenGL / unbuffered

### ISSUE THREAD

**Issue by emuchicken** [hrydgard/ppsspp#16012] opened 2022-09-12 11:19 UTC
### Game or games this happens in

ULUS-10064 - OutRun 2006

### What area of the game

Throughout the entire race. 

### What happens

Half the screen is blue. Could be the reflections of the water as clouds seem to be reflected. 

### What should happen

The blue shouldn't be there at all.

Vulkan renderer works correctly 

### GE frame capture

![DSC_0742](https://user-images.githubusercontent.com/45140115/189640153-0cd16af6-d08c-4c0d-b41e-68daad0ef553.JPG)
`

### Platform

Android

### Mobile phone model or graphics card

Retroid pocket 3 / powervr rogue ge8300

### PPSSPP version affected

V1.13.2

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2022-09-12 12:20
Yeah, I haven't yet tested all the new stuff with old hardware, and apparently not enough with OpenGL. Tagging to fix before 1.14.

**Comment by unknownbrackets** [comment] 2022-09-18 17:06
Is this only happening when using "skip buffer effects" (unbuffered)?  Is it newly happening, or just always happening?

Some of the effects, especially in these racing games, are likely to not look great without buffers.  Since the PSP supported buffers, games relied on them.  When you take them away, rendering can break in weird ways.

If it used to look less bad, we might be able to make it at least look like it did before.  Knowing which version last looked better would help.

-[Unknown]

**Comment by hrydgard** [comment] 2022-11-07 12:22
Can't seem to reproduce this on any device I tried (including one with PowerVR).

Also as Unknown says, with Skip buffer effect on, all bets are really off with regards to rendering.

**Comment by Gamemulatorer** [comment] 2022-11-28 14:18
Game is crashing when switching from buffered rendering to skip buffered.

https://user-images.githubusercontent.com/37603562/204300202-ba4b27a8-2b05-4e16-9367-e6460ac91883.mp4

![Screenshot_2022_1128_205757](https://user-images.githubusercontent.com/37603562/204300226-6fe153ef-f41e-47df-8d22-c9c55d978c8f.jpg)

**Comment by hrydgard** [comment] 2022-11-29 08:41
Hm, I can't reproduce a crash, but I do reproduce an issue where it doens't take effect until you restart or change resolution. Fixing that.

**Comment by Gamemulatorer** [comment] 2022-11-29 09:01
> Game is crashing when switching from skip buffered rendering to buffered rendering with x1 resolution.
> 
>  XiaoYing_Video_1669645010466.mp4 
> ![Screenshot_2022_1128_205757](https://user-images.githubusercontent.com/37603562/204300226-6fe153ef-f41e-47df-8d22-c9c55d978c8f.jpg)

https://github.com/hrydgard/ppsspp/commit/b9dc206cf0a25f2137acd5d866c633858761b6c5 fixes this issue.

**Comment by ppmeis** [comment] 2022-12-17 00:35
Tested in latest Windows build. OpenGL works just fine. So is android specific issue.

**Comment by emuchicken** [comment] 2022-12-17 00:55
The underwater issue is still present in the most recent build (as of 12th December 2022), but it's only when using a device with the Unisoc T310, using skip buffer modes under OpenGL.

**Comment by Gamemulatorer** [comment] 2022-12-17 03:06
Can also reproduce this.
I think this is safe to close now since skip-buffer can introduce graphics issue unlike buffered rendering.

**Comment by emuchicken** [comment] 2022-12-17 03:32
I understand that skip-buffer can cause graphics issues, unsure if it's a good idea of closing as the problem has not actually been fixed. - But that's up to the developers ;-)

**Comment by Gamemulatorer** [comment] 2022-12-17 04:00
Because it will never be fixed 😆
Use the default settings that's all.

**Comment by unknownbrackets** [comment] 2022-12-17 05:05
As noted before - because the PSP itself allowed games to use graphics buffers, disabling them simply unavoidably results in bad graphics for some games.

Asking a chef to follow a recipe (emulate a game) that calls for a bunch of herbs and spices (graphics buffer effects) is fine, but telling them they can't use any herbs and spices while expecting it to taste even better (upscaling, higher render resolution) doesn't really make sense.  It's obviously going to taste worse in some ways at least, even if they're an amazing chef.

You could create a new recipe (romhack) and adjust the ingredients (game code) to not need spices to taste good, but that's an entirely different thing from following the original family recipe (emulation.)

If this looked better in some previous version using skip buffer effects, there might be some trick to bring that back.  But if it's just something that looks wrong without its full flavor, that's unfortunately expected.  As such, I'm going to close this indeed.

-[Unknown]

**Closed by unknownbrackets** 2022-12-17 05:05 UTC
Labels: No Feedback / Outdated?, OpenGL, GE emulation
