### ISSUE TITLE
resolution improvements

### ISSUE THREAD

**Issue by soundsnow** [hrydgard/ppsspp#17016] opened 2023-02-27 03:46 UTC
1 psp, 2 psp, 3 psp, 4 psp
so many psp, but it's not useful for somebody to understand
you bought 6 psp?
Although I have uninstalled ppsspp, I still want to suggest changing the default resolution to the same as psp to reduce the consumption of hardware life

Console Resolution, Device Resolution and Custom Resolution

![image110](https://user-images.githubusercontent.com/109885044/221468429-e6459fb3-9d4b-404d-8309-acfd4ab39726.png)

**Comment by Gamemulatorer** [comment] 2023-02-27 04:03
Duplicate of https://github.com/hrydgard/ppsspp/issues/5413 and https://github.com/hrydgard/ppsspp/issues/11369 both are close because dev is not going to support a feature like this :(

**Comment by hrydgard** [comment] 2023-02-27 09:41
Yeah sorry, will not be supported for a variety of reasons. The current resolution options are fine and are going to be the best for compatibility (though at some point we might want to add the ability to go higher than 10x)

**Closed by hrydgard** 2023-02-27 09:41 UTC

**Comment by Gamemulatorer** [comment] 2023-02-27 09:50
Although AetherSX2 have this custom resolution but it's not great.
![Screenshot_20230227_174649_e2246895d6daacc7940d53fa6d65ea44](https://user-images.githubusercontent.com/37603562/221530312-684f161b-2235-4b80-b336-226410ac2450.jpg)

Maybe add display resolution info on the screen beside fps/speed?
![IMG_20230227_175031](https://user-images.githubusercontent.com/37603562/221530720-4b6142ba-0a2b-42cd-84ca-d34c6fb1a3d1.jpg)
