### ISSUE TITLE
PPSSPP lag at exit menu after playing network

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13398] opened 2020-09-07 17:00 UTC
I have tried with the latest build and play together with friends, when want to exit to menu it's so lag and some game seems ro be stuck after pressing exit menu. When i play game normally without network, this issue didn't happen though. Tried it in phantasy star portable 2 and another game that have network mode. Not tested to can play together or not just test until network initialized thing and i press exit to menu and the issue happens.

**Comment by MojoJojoDojo** [comment] 2020-09-07 20:34
Does not happen on Linux if I am not mistaken so its Windows only.
On Linux PPSSPP might crash if you connecting to an Ad-hoc server that does not exist (exclusive to that OS for now).

**Comment by Lemoncak3** [comment] 2020-09-08 03:08
I am using android though, and have tested it with few game with network initialized worked, and when press the exit to menu either it's very lag or i am just stuck in there sometimes ppsspp will force close.

**Comment by ANR2ME** [comment] 2020-09-08 13:55
When exiting a game it need to cleanup some resources, and if you're using UPnP it might takes longer because it need to close open ports or restore it back to the original owner of all the ports used by the game on-by-one (unfortunately there isn't a batching way to do this from miniUPnP)

It's also possible for the lag to be caused by crashes, for example when i had the crash related to D3D11 i reported recently, i noticed a longer time to close down PPSSPP, but that's related to GPU so it's probably different issue with this one.

Anyway, it's hard to investigate this without checking the logs, even better if debugged directly from android studio to catch any crash.

Unfortunately, my laptop can no longer detects my android phone (not even as storage) when i plugged the usb cable, not sure why :( but i think it's started since i updated android studio/sdk tools that have a new google driver, and haven't found a way to solve this. So i can't test android anymore.

**Comment by MojoJojoDojo** [comment] 2020-09-08 14:18
There is also that issue of Linux crashing when connecting to a non existing adhoc server .
Is there a way to get a log after a crash though?

**Comment by ANR2ME** [comment] 2020-09-08 14:22
> 
> 
> There is also that issue of Linux crashing when connecting to a non existing adhoc server .
> Is there a way to get a log after a crash though?
> @Lemoncak3 can you check if that happens on Android too?
> connect to a random IP address.



> 
> 
> There is also that issue of Linux crashing when connecting to a non existing adhoc server .
> Is there a way to get a log after a crash though?
Well, i'm not familiar with linux (never use one) so not sure about it either.

I wonder if the crash on linux might be related to the SIGPIPE thing? have you tried to build it again with the latest commits which includes the SIGPIPE PR?

**Comment by MojoJojoDojo** [comment] 2020-09-08 14:33
It is with them.

**Comment by ANR2ME** [comment] 2020-09-08 15:36
@Lemoncak3  could you provide more info of what settings you are using?
Which GPU renderer you are using? Vulkan or OpenGL ES?
Did you use UPnP? If you do, Do you have a UPnP router?
Other than Phantasy Star Portable 2, which other games are having similar symptoms? And which game that was stuck when exit to menu?

I'll try to debug it from android studio if i managed to borrow some android phone later.

**Comment by Lemoncak3** [comment] 2020-09-08 21:26
I am using openGL, and no I am not using uPnP just playing through local network using wireless router. Some of the game i am ad hoc server, some are not. Other than phantasy star i tried Worm Open Warfare 2, X-Men legends, and also Valhalla knights 2. I can't remember which one are stuck probably phantasy star portable 2 since i played that a lot in network mode.

**Comment by iota97** [comment] 2020-09-09 08:41
> There is also that issue of Linux crashing when connecting to a non existing adhoc server .

Work on my machine™, I just get failed to connect to adhoc server but no crash on Manjaro.

You may get the log in the console if you launch PPSSPP from terminal

Also on bash the last command returned value is on the var `?`, so right after the crash you may get what error code PPSSPP returned using `echo $?`.

If that give no insight you may need to build PPSSPP with debug simbol and get a stack trace with gdb.

Still this issues is on other matter, you might want to open a new one about that.

**Comment by MojoJojoDojo** [comment] 2020-09-09 10:02
> > There is also that issue of Linux crashing when connecting to a non existing adhoc server .
> 
> Work on my machine™, I just get failed to connect to adhoc server but no crash on Manjaro.
> 
> You may get the log in the console if you launch PPSSPP from terminal
> 
> Also on bash the last command returned value is on the var `?`, so right after the crash you may get what error code PPSSPP returned using `echo $?`.
> 
> If that give no insight you may need to build PPSSPP with debug simbol and get a stack trace with gdb.
> 
> Still this issues is on other matter, you might want to open a new one about that.

Hmm tried another game and it only happens on Kingdom Hearts...
I will check this out later and open another issue if its that prevelant.

**Comment by ANR2ME** [comment] 2020-09-11 22:47
The crashes that occurred when losing connectivity to adhoc server might be related to this signal (android logcat)
```
2020-09-12 05:42:34.515 7851-8486/? E/PPSSPP: [SCENET] FriendFinder: Socket Error (32) when sending OPCODE_PING
2020-09-12 05:42:34.516 7851-8486/? A/libc: FORTIFY: FD_SET: file descriptor -1 < 0
2020-09-12 05:42:34.517 7851-8486/? A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8486 (FriendFinder), pid 7851 (androidInit)
```

**Comment by Lemoncak3** [comment] 2020-09-15 10:18
When i try strikeforce i didn't notice the delay anymore will test it more later.

**Comment by hrydgard** [comment] 2020-09-15 11:40
Yeah I think we can close this.

**Closed by hrydgard** 2020-09-15 11:40 UTC
Labels: Networking / adhoc
