### ISSUE TITLE
Outrun 2006 & PPSSPP Dunnos ?

### ISSUE THREAD

**Issue by inukaze** [hrydgard/ppsspp#15257] opened 2021-12-29 05:32 UTC
Hi there, i am playing this game a lot. i love it. Well the thing is some content of game should be unlocked via USB conection with PlayStation 2.

1 - Is possible emulate that connection from PCSX2 ?

Well in case that is not possible, i try to create cheat just for unlock the content available on this game.

2 - Why the QT Version for GNU/Linux not have the tools like « Memory Viewer » ? You can't fork part of Scanmem project for make it ?

Well the Outrun 2006 PSP (Europe) v1.01 can be unlocked via USB PS2 Connection is the follow : 

Cars : 
1. 328GTS (Intermediate B)
2. F430 (Professional)
3. 328GTS (Outrun)
4. F430 Spider (Outrun)
![001----Carro---328GTS--Intermedio-B](https://user-images.githubusercontent.com/1647332/147629590-60af271e-f5ba-495d-8601-93bc097cc9a3.png)
![002----Carro---F430---Profesional](https://user-images.githubusercontent.com/1647332/147629599-d6f6bb80-ac37-40b7-a029-3e88c207fd96.png)
![003----Carro---328GTS--OutRun](https://user-images.githubusercontent.com/1647332/147629607-e53044ab-5a95-4e7a-9920-5425245702ac.png)
![004----Carro---F430---OutRun](https://user-images.githubusercontent.com/1647332/147629622-5ed8fd58-c622-418d-b73e-594e37f62ad7.png)

Track / Stage : 
1. Sunny Beach
2. Sunny Beach Special [Inverted / Mirror]
![005----Recorrido---Sunny--Beach](https://user-images.githubusercontent.com/1647332/147629656-47ec0b43-5d23-4a14-8e7a-e9ed30e15f89.png)
![006----Recorrido---Sunny--Especial(Invertido)](https://user-images.githubusercontent.com/1647332/147629674-f09a396e-2803-4fd7-ae39-3861d13ea307.png)

BGM / BackGround Music : 
1. Shake The Street
2. Who Are You
3. Rush A Difficulty
4. Keep Your Heart
![007----MusicaDeFondo---Shake--The-Street](https://user-images.githubusercontent.com/1647332/147629775-00339205-38bc-437d-9e74-348ed42550d8.png)
![008----MusicaDeFondo---Who--Are-You](https://user-images.githubusercontent.com/1647332/147629804-f9e17fbc-ada5-4dd3-8a3c-ba135d65303f.png)
![009----MusicaDeFondo---Rush--A-Difficulty](https://user-images.githubusercontent.com/1647332/147629834-8c369c69-9f24-4cca-ac7c-1bca63fcb146.png)
![010----MusicaDeFondo---Keep--Your-Heart](https://user-images.githubusercontent.com/1647332/147629857-c3975441-f936-4e6e-8abb-d35f56e665c7.png)

Colors for Cars : 
328GT (Outrun) [ White, Blue ]
F430 (Outrun) [ Black, White, Green, Blue, Cyan ]
![011----Colores---328GTS--Blanco](https://user-images.githubusercontent.com/1647332/147629959-91803d1a-4ecb-4f44-a0cc-06c54d6764fa.png)
![012----Colores---328GTS--Azul](https://user-images.githubusercontent.com/1647332/147629991-6deb53d6-80bd-4591-919b-5970d9273da2.png)
![013----Colores---F430--Negro](https://user-images.githubusercontent.com/1647332/147630018-cab493b3-d4f2-46fd-b497-940aa824731b.png)
![014----Colores---F430--Blanco](https://user-images.githubusercontent.com/1647332/147630027-cb5725c6-5c59-4c92-a9b1-1b1e69930ecd.png)
![015----Colores---F430--Verde](https://user-images.githubusercontent.com/1647332/147630046-15fac3c1-9d94-4947-a5eb-36ff6345b462.png)
![016----Colores---F430--Azul](https://user-images.githubusercontent.com/1647332/147630053-58b5930f-291a-47a0-8ac1-ac0e0ac36feb.png)
![017----Colores---F430--Cyan](https://user-images.githubusercontent.com/1647332/147630070-ab049be5-53ff-410e-9399-ec27072a7e03.png)
![018----Colores---328GTS--Outrun-Blanco](https://user-images.githubusercontent.com/1647332/147630082-dbe5a8ac-5e98-4d95-b805-6a41b5b4dc25.png)
![019----Colores---328GTS--Outrun-Azul](https://user-images.githubusercontent.com/1647332/147630100-1cb49b88-aabd-4643-8f42-a06072cffa3b.png)
![020----Colores---F430Spider--Outrun-Negro](https://user-images.githubusercontent.com/1647332/147630113-97b06b0f-d4b2-460a-bdda-78385eae816a.png)
![021----Colores---F430Spider--Outrun-Blanco](https://user-images.githubusercontent.com/1647332/147630123-534b47ed-3f46-4b05-950b-b631cc6576f8.png)
![022----Colores---F430Spider--Outrun-Verde](https://user-images.githubusercontent.com/1647332/147630134-feb79a30-deeb-487e-928b-f6afccc5cf3a.png)
![023----Colores---F430Spider--Outrun-Azul](https://user-images.githubusercontent.com/1647332/147630142-10e0c91f-e07c-4ef6-8307-0893e08d83b9.png)
![024----Colores---F430Spider--Outrun-Cyan](https://user-images.githubusercontent.com/1647332/147630157-30cf6659-5c52-4d90-b70c-e14665be7253.png)

3 - My point is in case the PS2 USB Connection can not be emulated i prefer try to search for cheats (without anything related to Microsoft Windows). But the native version of PPSSPP (QT) for my Operating System not had the tools like the Microsoft Windows Version. 

That diffucultme a lot when i try to search and determine which ram region is accessed for read.

In that case, someone had a tutorial of how make cheats for PPSSPP from scratch, in a common form for GNU/Linux, Haiku, Mac OS X, and Microsoft Windows without use « Cheat Engine » ?

**Comment by Panderner** [comment] 2021-12-29 08:58
Maybe related to https://github.com/hrydgard/ppsspp/issues/13098?

**Comment by LunaMoo** [comment] 2021-12-29 09:01
You don't necessarily need Cheat Engine or windows to create cheats, but you do need:
 - some external software that can search through mapped memory,
 - a debugger and your own knowledge of MIPS.

 For the first, I have no idea, but as a linux user you probably know some tools yourself.
 For the second, I believe we have websocket based debugger interface which might or might not be enough, I never used it, but you probably don't need it for things like unlocking items in game.

 To create simple cheats that only change some variable stored in memory you don't have to change any code unless you want to patch the connectivity function to reward stuff when used instead of just writing it down, through you will also need to figure out how your game stores the data you want to edit. This can be very simple flag, value or anything else really, there's no rule how game can store it's data, but at least it's very unusual for that data to be specially protected in case of PSP games afaik there's only 1 game that has an anti-cheat - FFT0 - and it was easily disabled.

 PPSSPP info log prints out the address PSP memory is allocated when you boot first game in it, it shouldn't change until you exit PPSSPP and you also should know that PSP has 32 mb of memory with 8 of that for kernel, so the user memory starts at that address+8mb with game loading 0x4000 after that.

 Memory viewer from windows version is really not build for searching through data to create cheats, that's exactly why Cheat Engine is prefered and why external tools on other operating systems would be better suited for it as well.

 Once you have your PSP addresses and values, you just need to google for CWCheat formatting, how you should format your data to be seen as CWCheat. There was many sites for that in the past, but they mostly disappeared, maybe still something in japanese, at worst you can check PPSSPP source ~ https://github.com/hrydgard/ppsspp/blob/master/Core/CwCheat.cpp while looking at some example cheats to get the idea, it's not really hard, but most code types are useless, confusing and hard to debug in case of failures, it's always better to just learn MIPS when a cheat requires more effort.

 PPSSPP CWCheat does have some emulator specific code types, but that's really only for enhancements(ie, to trigger or change shader effects or gamepad vibrations based on values from game) and nothing that would benefit you here.

**Comment by MojoJojoDojo** [comment] 2021-12-29 16:46
> Maybe related to #13098?

Yeah its a duplicate of my issue.
Hopefully someone will understand how to do it maybe.

**Comment by inukaze** [comment] 2021-12-29 22:56
> > Maybe related to #13098?
> 
> Yeah its a duplicate of my issue. Hopefully someone will understand how to do it maybe.

The first point yes, is the same xD reading your post i see this

>> I know that Dolphin does something similar for GBA to GC connection by using VBA-M .
The PSP connect to the PS2 via the USB port.

and yes, i use Dolphin-Emu + VBAM or mGBA with that emulators the thing works for example with « Four Sword Adventures » & « Zelda : The Four Sword »

**Comment by ANR2ME** [comment] 2021-12-30 01:20
Wow opening this thread could cause my firefox to crash LOL probably due too so many screenshots >.<

Anyway, i'm sure you can find memory scanner/editor like Cheat Engine on linux, may be something like these? https://alternativeto.net/software/cheat-engine/?platform=linux

**Comment by inukaze** [comment] 2021-12-30 01:47
i already use Scanmem (cli) + GameConqueror (GTK Gui) but the GUI not had all options the cli program can use.

i try to compile "PINCE" another day but my software is old for that.

**Comment by unknownbrackets** [comment] 2021-12-31 05:15
The Qt version used to have an incomplete and somewhat broken debugger, but it made it harder to add new debugging features.  The web socket API is the new way.  It would be perfectly acceptable for you to make a separate Qt app that connected to PPSSPP using that API.  It could implement a memory viewer or anything else in whatever way you wanted.

I may add more to the web debugger, such as a memory viewer, and that would be not only cross platform but useful for PPSSPP running on mobile devices, TVs, consoles, or raspberry pis.  The reason I haven't added as much to the web UI is I've been worried about some new security restrictions being implemented by browsers.

http://ppsspp-debugger.unknownbrackets.org/

That said, you can also run PPSSPP in WINE on Linux, and use the Windows debugger.

I'm going to close this as a duplicate of #13098 for the rest.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-12-31 05:15 UTC

**Comment by inukaze** [comment] 2021-12-31 08:36
> The Qt version used to have an incomplete and somewhat broken debugger, but it made it harder to add new debugging features. The web socket API is the new way. It would be perfectly acceptable for you to make a separate Qt app that connected to PPSSPP using that API. It could implement a memory viewer or anything else in whatever way you wanted.
> 
> I may add more to the web debugger, such as a memory viewer, and that would be not only cross platform but useful for PPSSPP running on mobile devices, TVs, consoles, or raspberry pis. The reason I haven't added as much to the web UI is I've been worried about some new security restrictions being implemented by browsers.
> 
> http://ppsspp-debugger.unknownbrackets.org/
> 
> That said, you can also run PPSSPP in WINE on Linux, and use the Windows debugger.
> 
> I'm going to close this as a duplicate of #13098 for the rest.
> 
> This is an issue tracker - there's a forum if you want to discuss things. You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find new and useful information, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

Well thank you for the answer. 
1 - i think the web api is a right way

2 - "Security restrictions being implemented by browsers" included the browser for Gemini Protocol ? just for mention a few of them : Kristall (Qt), moonlander (GTK), deedum (Android / iOS), Bollux (CLI) 

3 -  A) "you can also run PPSSPP in WINE on Linux, and use the Windows debugger.". 
B) "You wouldn't add another "bread" item to a grocery list every time you thought about it, right?"

A) Yes i can run PPSSPP trought "Wine Is Not Emulator" on GNU.

B) You wouldn't install nested operating systems (like GNU/Linux, inside install Mac OS X, inside mac os x, install microsoft windows) when you really don't need a compat layer for execute binary executable maked for another operating system, when you can use a binary native executable for host operating system. right ?

4 - i dont know that issue the #13098 exist, my bad, sorry for that. and well i still trying my self, determine what does PSP when connect to PS2 for share data. Because on the PSCX2, the Outrun 2006 for PlayStation 2, had the same option of via usb and just got "PSP is not connected". i am thinking this is the things take too many years for get solved. Because need a lot information and test for determine which things are really need it.

Well if someone find the "cheats" for "Unlock PS2 Content" on this version of outrun, can publish on LunaMoo PPSSPP Workarounds, right there ( beware many screenshot can hang-up your device if not had enough power XD. ) -> https://github.com/LunaMoo/PPSSPP_workarounds/issues/7

**Comment by MojoJojoDojo** [comment] 2022-02-16 17:01
@inukaze JPCSP can do what you want now on its latest commits (incomplete implemetation tho).

**Comment by inukaze** [comment] 2022-02-17 01:03
@MojoJojoDojo : Thank you very much for the information

**Comment by unknownbrackets** [comment] 2022-02-17 06:19
> 2 - "Security restrictions being implemented by browsers" included the browser for Gemini Protocol ?

Sorry, missed this.  No - my concern is that browsers are starting to restrict local network access, because attacks on routers and things like that are starting to become a concern.  They're also very intentionally locking features behind valid TLS/SSL certificates, which are hard to get for a local connection.  Because of the way debugging works with PPSSPP, you're connecting to the local application over network.

-[Unknown]
