### ISSUE TITLE
Crash Persona 2 Innocent Sin after a while

### ISSUE THREAD

**Issue by jimkage** [hrydgard/ppsspp#15783] opened 2022-08-03 19:45 UTC
### Game or games this happens in

ULUS-10584 Persona 2 Innocent Sin

### What area of the game / PPSSPP

Game.crashes after a while in some areas: City maps, Lisas Home, Theater and etc.

Save: https://www.mediafire.com/file/ckac69wab43gojw/ULUS105840000.zip/file

### What should happen

Crash videos
Lisa's house
https://youtu.be/G41pO8eKNRE

Map select
https://youtu.be/oK7X6Bu1IQE

City (Inside the store has no crash)
https://youtu.be/JovmicRztK8

### Logs

https://www.mediafire.com/file/vr2wq45xz3tbfkj/ppsspp.rar/file

### Platform

Android

### Mobile phone model or graphics card

Moto G100

### PPSSPP version affected

v1.13.1-153-g4d519b49a	

### Last working version

Tested over a dozen builds and it still happens

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2022-08-03 22:38
Hm, this pretty much has to be some kind of memory leak. Will investigate

**Comment by jimkage** [comment] 2022-08-04 14:56
Not really sure if it helps but the japanese version does not crash in the same areas at all, everything runs fine.

**Comment by unknownbrackets** [comment] 2022-08-07 15:53
> Tested over a dozen builds and it still happens

How about the last stable release, v1.12.3?  Did it happen there?  If no, that gives us a starting point and trying halfway between the working and broken would help identify.

-[Unknown]

**Comment by jimkage** [comment] 2022-08-08 00:16
Just tested ppsspp-v1.12.3-1467-g6f4ec0fc4-android and it still happen.

**Comment by unknownbrackets** [comment] 2022-08-08 00:18
That contains almost all the changes in v1.13.x.  That means it's v1.12.3 plus 1467 changes.  v1.13.0 was v.12.3 plus 1469 changes, so that's virtually the same as testing v1.13.0.

-[Unknown]

**Comment by jimkage** [comment] 2022-08-08 00:44
Alright so I went all the way down to ppsspp-v1.12.2-9-g11b65ca22-android and got the game running for 15 minutres without any crashes. I hope this helps.

**Comment by hrydgard** [comment] 2022-08-08 04:59
So now we know the error is between -9 and -1467. How about trying one right in the middle? That will have the range. And once you find if it broke before or after, you can split the new range in the middle too. If you keep doing this, you'll find the change in 10 tries..

**Comment by jimkage** [comment] 2022-08-08 14:50
Alright heres the last working version: ppsspp-v1.12.3-8-gc75784351-android from ppsspp-v1.12.3-10-g1cd520ae3-android it crashes.

**Comment by hrydgard** [comment] 2022-09-16 07:56
I believe that this is the same as #15788 , which is fixed now.

Can you please test with the latest builds @jimkage ?

**Comment by Gamemulatorer** [comment] 2022-09-16 12:19
Cannot reproduce this crash in theater.
![Screenshot_2022-09-16-20-19-10-42](https://user-images.githubusercontent.com/37603562/190637368-7847ca4f-3ab0-4262-b687-7e753d557f83.png)

**Comment by hrydgard** [comment] 2022-09-16 12:44
For testing purposes, likely the bug and the fix only affect Android 12+ devices.

**Comment by hrydgard** [comment] 2022-09-18 09:00
Anyway, I'm gonna close. Let's re-open if we hear about this again.

**Closed by hrydgard** 2022-09-18 09:00 UTC
