### ISSUE TITLE
linux下中文显示有缺失

### ISSUE THREAD

**Issue by shouhuanxiaoji** [hrydgard/ppsspp#9318] opened 2017-02-17 14:38 UTC
![jietu](https://cloud.githubusercontent.com/assets/4121607/23069250/af135ad0-f561-11e6-9123-b1c6ce5e0184.jpg)

最后那个“音？”，实际上是“音乐”文件夹，乐字没有正常显示。
Ubuntu 16.04
请问这个问题怎么解决，官网下载的linux working amd64 通用包

**Comment by hrydgard** [comment] 2017-02-17 17:49
Sorry, don't speak Chinese.

Google Translate:

"Finally, the "sound", in fact, "music" folder, music is not a normal display.
Ubuntu 16.04
I would like to ask how to solve this problem, the official website to download linux working amd64 general package"

Oh, I guess it's a missing Chinese letter in our font. We really should use native font rasterization on all platforms, not just on Windows...

**Comment by shouhuanxiaoji** [comment] 2017-02-18 01:34
yes, I think it is because that problem of chinese font. But how to use another font?

**Comment by xiushudongfang** [comment] 2017-02-18 02:32
Add '乐' into chinese.txt and rebuild atlas.zim.

**Comment by unknownbrackets** [comment] 2020-04-11 22:36
It may work better using PPSSPPQt rather than PPSSPPSDL.

Going to close this as a duplicate of #9958.

-[Unknown]

**Closed by unknownbrackets** 2020-04-11 22:36 UTC
Labels: Font Atlas, SDL2
