### ISSUE TITLE
FMVs from some games affected by texture upscale (regression?)

### ISSUE THREAD

**Issue by ShadowLady** [hrydgard/ppsspp#9125] opened 2016-11-21 05:56 UTC
Enabling Texture Scaling of any kind affects the quality on the Intro FMV for Kingdom Hearts Birth by Sleep. It keeps switching from unfiltered and filtered even if you force Linear texture filtering. On top of that, if you use the heaviest of the upscale level/type it'll increase the CPU usage by huge amounts, where 5x hybrid+bicubic will use 100% of my CPU and the FMV will play at 1/3 of it's normal speed.

This behavior didn't happen on 1.2.2. Windows 64.

I narrowed it down to breaking on 1.2.2-371 which was this merge pull: #8720 
working fine on 1.2.2-360.

edit: FMVs on Dissidia 012 are affected as well.

edit2: the beginning of the intro FMVs for crisis core and soul calibur broken destiny are also affected but then they get better after a few seconds (same symptoms for the beginning with a huge cpu usage spike and no filtering).

**Comment by DonelBueno** [comment] 2017-01-16 19:56
I openned a duplicate (#9215), sorry.

I can confirm that this problem affects a lot of games.

**Comment by unknownbrackets** [comment] 2017-03-05 22:13
I think means `entry->status |= TexCacheEntry::STATUS_CHANGE_FREQUENT;` isn't happening properly.

A workaround would be to simply use the same `isVideo` check to definitely exclude videos.  But, that won't fix the underlying issue.  Ultimately, both should likely be done.

-[Unknown]

**Comment by hrydgard** [comment] 2017-03-05 22:25
Yep, I have considered doing the isVideo check, but indeed wanted to find the root cause first. I spent a little time on it recently but couldn't figure out why #8720 broke it but didn't dig too deeply yet...

**Comment by unknownbrackets** [comment] 2017-03-18 18:28
Oops, I see it.  Dumb mistake, pr incoming.

-[Unknown]

**Comment by hrydgard** [comment] 2017-03-18 18:42
Oh, glad you see it, I don't :)

**Closed** 2017-03-18 19:28 UTC
