### ISSUE TITLE
Savestate failed

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13236] opened 2020-08-02 08:34 UTC
I download v1.10.3-276-g4766e4fcb from githyb but when i use load state it says load state failed.

**Comment by hrydgard** [comment] 2020-08-02 10:32
Getting this too. I'm on it

**Comment by ANR2ME** [comment] 2020-08-02 11:26
@Lemoncak3 v1.10.3-276-g4766e4fcb doesn't have the default value on DoState, have you try to load it using v1.10.3-282-g914b6ce24 ?

**Comment by Lemoncak3** [comment] 2020-08-02 11:26
Okay will try it, wait

**Comment by Lemoncak3** [comment] 2020-08-02 11:29
![Screenshot_20200802-182846](https://user-images.githubusercontent.com/67026697/89122012-0b976e80-d4ee-11ea-8241-32d53fd55c4b.png)
Still has the same issue

**Comment by ANR2ME** [comment] 2020-08-02 11:35
May i know what game is that? and what was the version the save state created with? i'll try to create a new save state with that version

**Comment by Lemoncak3** [comment] 2020-08-02 11:37
i think i use this one v1.10.3-260-g70802e61d before updating to v1.10.3-276-g4766e4fcb

**Comment by ANR2ME** [comment] 2020-08-02 13:09
Could you provide your digimon/growlanser save state? i couldn't reproduce it using new save state created with older version

btw does growlanser have multiplayer? i didn't see in it in main menu

**Comment by hrydgard** [comment] 2020-08-02 13:09
It's an issue in the sceUsbMic savestate handling, it turns out. PR coming.

**Comment by hrydgard** [comment] 2020-08-02 13:29
Please confirm that it's fixed in new builds.

**Comment by Lemoncak3** [comment] 2020-08-02 14:40
It worked now, thanks a lot

**Closed** 2020-08-02 14:49 UTC
