### ISSUE TITLE
Does anyone send me a project that can be compiled?

### ISSUE THREAD

**Issue by 846524417** [hrydgard/ppsspp#12187] opened 2019-07-21 09:37 UTC
For the projects downloaded here, the NDK CMake submodules are all installed.Error, now I want a working project file.I don't know if there is a good heart!

###https://github.com/hrydgard/ppsspp/issues/12136

**Comment by unknownbrackets** [comment] 2019-07-23 01:40
This issue is being closed as a duplicate of #12136.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

Every build of PPSSPP is built on Travis and the current code builds fine.  You may need Python 3 installed currently.

https://travis-ci.org/hrydgard/ppsspp/builds/560316866

-[Unknown]

**Closed by unknownbrackets** 2019-07-23 01:40 UTC
