### ISSUE TITLE
Feature request: Ad-Hoc multiplayer chat support

### ISSUE THREAD

**Issue by lightfirst** [hrydgard/ppsspp#7451] opened 2015-02-07 12:30 UTC
when I play Multiplayer, PPSSPP will show some message such as  "Network Initialized".
Could PPSSPP show more, show some chatting message.
for example: nickname, ping value, someone join in this lobby, someone left.

**Comment by sum2012** [comment] 2015-02-09 22:41
Mark:
The ping value 's sample code is in
http://tangentsoft.net/wskfaq/examples/src/dllping.cpp

**Comment by hrydgard** [comment] 2015-02-09 23:00
@sum2012 , was that posted in the wrong thread?

@lightfirst  Yeah, I suppose that could be a good idea, where possible. I'll check and see what can be done soon.

**Comment by sum2012** [comment] 2015-02-09 23:34
If someone want to imp icmp,that link should be good ref

**Comment by hrydgard** [comment] 2015-02-10 00:03
Ah, I missed that he was asking for that.

**Comment by lightfirst** [comment] 2015-02-10 08:31
@hrydgard I try add this code " osm.Show( packet->base.message, 3.0);" It can make PPSSPP show the chat message from JPCSP or PSP.  looks like ppsspp also have a chat, but not enable/finished

**Comment by hrydgard** [comment] 2015-02-10 08:38
Ah, I see. Yeah, that doesn't look too hard... I'll put something in after 1.0.1 is finished

**Comment by lightfirst** [comment] 2015-03-08 01:34
1.0.1 is finished, what do you plan to do?
BTW, I try add some code myself:
proAdhoc.cpp
					// Add Incoming Chat to HUD
					-//printf("Receive chat message %s", packet->base.message);
					+// show message from adhocserver
                                        +char *name = (char *)packet->name.data, *blank = ": ", *message = packet->base.message;
					+std::string destination = std::string(name) + std::string(blank) + std::string(message);
					+osm.Show(destination, 3.0f);
					DEBUG_LOG(SCENET, "Received chat message %s", packet->base.message);
-----------
-----------

					// Add User
					addFriend(packet);

					// Update HUD User Count
                                        +//show play joined, so we can know who joined, it isn't list player name though
					+char *name = (char *)packet->name.data, *blank = " joined";
					+std::string destination = std::string(name) + std::string(blank);
					+osm.Show(destination, 3.0f);

-----------
-----------					// Delete User by IP, should delete by MAC since IP can be shared (behind NAT) isn't?
					deleteFriendByIP(packet->ip);

					// Update HUD User Count
                                        +// show play left. not work, do I did something long?
					+char *name = (char *)packet->name.data, *blank = " left";
					+std::string destination = std::string(name) + std::string(blank);
					+osm.Show(destination, 3.0f);
any one can finished Send Chat Messages?
		// Send Chat Messages
		//while(popFromOutbox(chat.message))
		//{
		//  // Send Chat to Server
		//  sceNetInetSend(metasocket, (const char *)&chat, sizeof(chat), 0);
		//}

**Comment by NgJinXiang14** [comment] 2016-09-25 07:27
Does this feature is done?I hope it can add to android because when i use openvpn to play with other player,we cant chat and cant use app such as facebook messager to chat because we cant use internet when connect to vpn.

**Comment by adenovan** [comment] 2016-10-15 05:21
sorry for bothering you @hrydgard , im trying to implement this chat feature but have many questions in my mind.

1. Can ppsspp make a chat screen without pausing the core, something that not like pause screen, i see the debug log if we pausing the emulator with esc key. the log is stopped that means the core game is paused too right?
2. is it possible to build something like osm but instead of a text only its display chat screen that contains chat data from proadhoc.cpp and and contains textbox to send chat to the server, something like this?
![chat](https://cloud.githubusercontent.com/assets/5246143/19407551/4e5ab56c-92d8-11e6-9971-242751f6f2cb.png)
3. Can android On screen touch used as toogle to hide or show the chat screen? like chat button on the image. android will call keyboard fullscreen if want to input something, an example like input nickname in system settings. so it will be a problem or not for the core to keep running?
4. for windows user that map game key to keyboard can we use the keyboard to input text and focused to textbox in chat screen, when core is still running?

thats a lot of question and im not sure what file to look for build an overlay screen on ppsspp, also i never had a GUI Programming in C++ this the first time but i really enjoy to learn something new :D.

**Comment by adenovan** [comment] 2016-10-19 17:50
i manage to create the GUI and send the text to server and this is so far the progress @hrydgard , is it good enough? 

![screenshot 112](https://cloud.githubusercontent.com/assets/5246143/19530711/9269bc3e-9667-11e6-9b78-e5bffb640b90.png)

To Do Next :
-display the chat into screen (its easy)
-add key to display the chat screen on windows ( didn't know how to do that)
-add options enable chat on networking(lazy to implement.

**Comment by hrydgard** [comment] 2016-10-19 18:36
Sorry for not responding above, I got the message when busy then forgot.

Looks like a good start, keep at it :) As you found out it's very possible to add UI on top of the game by adding it in EmuScreen.

**Comment by adenovan** [comment] 2016-10-20 06:32
@hrydgard  ah no problem, i learn a lot by not having the answer :D , basic chat is working i think , need a friend to test the chat, but we have GUI problem on Textview and TextEdit, TextEdit need to auto scroll right when the character exceed the Text Edit Width. and the TextView need a dynamic height so a long text exceed the width of textview not be a problem. here is the sample issues can we fix it?
![screenshot 118](https://cloud.githubusercontent.com/assets/5246143/19548389/ca973b40-96d0-11e6-886d-a5f23f2b278d.png)

im trying to use the layout params wrap content for the textview but it still not working

>
void ChatMenu::UpdateChat() {
        using namespace UI;
	chatVert_->Clear();
	std::vector<std::string> chatLog = getChatLog();
	for (auto i : chatLog) {
	        TextView *v = chatVert_->Add(new TextView(i, FLAG_DYNAMIC_ASCII, false,
                new LayoutParams(PopupWidth(), WRAP_CONTENT)));
		uint32_t color = 0xFFFFFF;
		v->SetTextColor(0xFF000000 | color);
	}
	toBottom_ = true;
}
`

**Comment by adenovan** [comment] 2016-10-21 08:40
@hrydgard it's done, need a options enable chat and better substring logic (on whitespace). should i make a pull request now? or just commit it on my branch? @sum2012  can you help add the options on the networking part and correct my substr logic ?
![image](https://cloud.githubusercontent.com/assets/5246143/19592056/abd5cbe0-97ac-11e6-83a5-981b00403436.png)

**Comment by sum2012** [comment] 2016-10-21 08:43
@adenovan  where is your code in your  branch ?

**Comment by adenovan** [comment] 2016-10-21 08:45
@sum2012  https://github.com/adenovan/ppsspp/commit/d254a8d44f7ea6805ebdb275eb034db4c1999ad6

**Comment by sum2012** [comment] 2016-10-21 08:58
@adenovan recent we have moved the lang folder,maybe you need re-fork the source again.
I cannot test your code becasue of conflict
![1](https://cloud.githubusercontent.com/assets/2177532/19592686/65121cec-97af-11e6-8085-d4cc60adee2b.jpg)

**Comment by sum2012** [comment] 2016-10-21 09:15
I try to ignore the conflict,build error

10>Core.lib(proAdhoc.obj) : error LNK2019: unresolved external symbol "public: void __cdecl ChatMenu::UpdateChat(void)" (?UpdateChat@ChatMenu@@QEAAXXZ) referenced in function "int __cdecl friendFinder(void)" (?friendFinder@@YAHXZ)
10>UI.lib(EmuScreen.obj) : error LNK2001: unresolved external symbol "public: virtual void __cdecl ChatMenu::CreatePopupContents(class UI::ViewGroup *)" (?CreatePopupContents@ChatMenu@@UEAAXPEAVViewGroup@UI@@@Z)
10>UI.lib(EmuScreen.obj) : error LNK2001: unresolved external symbol "public: virtual void __cdecl ChatMenu::CreateViews(void)" (?CreateViews@ChatMenu@@UEAAXXZ)
10>UI.lib(EmuScreen.obj) : error LNK2001: unresolved external symbol "public: virtual void __cdecl ChatMenu::dialogFinished(class Screen const *,enum DialogResult)" (?dialogFinished@ChatMenu@@UEAAXPEBVScreen@@W4DialogResult@@@Z)
10>UI.lib(EmuScreen.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl ChatMenu::touch(struct TouchInput const &)" (?touch@ChatMenu@@UEAA_NAEBUTouchInput@@@Z)
10>..\PPSSPPWindows64.exe : fatal error LNK1120: 5 unresolved externals

**Comment by adenovan** [comment] 2016-10-21 09:36
@sum2012  ok wait will do rebranch now

**Comment by adenovan** [comment] 2016-10-21 10:37
@sum2012 done https://github.com/adenovan/ppsspp/commit/b3db60bd7baa31ee5e27d92de7db53079563942a

**Comment by sum2012** [comment] 2016-10-21 11:17
@adenovan Well done,I test two computer chat okay.
![2](https://cloud.githubusercontent.com/assets/2177532/19596800/000f95d6-97c3-11e6-9d72-7dc63053a4d2.jpg)

**Comment by sum2012** [comment] 2016-10-21 11:29
@adenovan 
1:Do you mean that I neeed to add option of "Chat" button visable or not ?
2:For substr , I don't know it.

**Comment by adenovan** [comment] 2016-10-21 11:36
@sum2012 ok just help me with add options to enable and disable the chat buttons

its looks like good enough, but it still have random crash on chatScreen pointer. i give a chatscreen instance to proAdhoc.cpp , on EmuScreen.cpp , sometimes its crashed when joined message coming without opening the chat feature, sometimes its not. try to reproduce the issues but didn't get it. 
 
improvement we can make for future :
- Different chat color for send and receive
- Auto scroll TextEdit to the right when typing long text
- hide chat button when ChatScreen displayed
- Substring character on white space before 30 n character . so it will look better (ChatScreen.cpp) .
- Maybe change the packet headers for chat [64] character but it will make a problem or trimmed in original server (coldbird.server)

**Comment by sum2012** [comment] 2016-10-21 13:15
@adenovan I have made a pull request in https://github.com/adenovan/ppsspp/pull/1

**Comment by adenovan** [comment] 2016-10-21 13:31
@sum2012 ok sum merged thanks for the translation and the options, im trying to build on android now and test the chatScreen on mobile device

**Comment by sum2012** [comment] 2016-10-21 13:48
It is possable to make OSK for android 
see https://github.com/hrydgard/ppsspp/blob/master/UI/GameSettingsScreen.cpp#L981
I need to sleep now and torromow need to go to work,

**Comment by adenovan** [comment] 2016-10-21 13:52
@sum2012 yeah will do it now, thanks for the info.

**Comment by sum2012** [comment] 2016-10-21 20:22
how to join room 2 times without leave room ?
>> showchat > join room > hide chat > showchat > join room

**Comment by adenovan** [comment] 2016-10-22 00:12
I tried it with monster hunter game. It will crash if somone inside the guildhall and give joined message with second times chatlog instance. The main problem is Updating the chat from proadhoc.cpp. Ah my bad im leaving the room actually. Here is the flow, join room > showchat (new chatscreen1 ) > hidechat > leave room > showchat (new chatscreen2) > join room (crashed). Looks like when joining proadhoc.cpp chatmenu instance pointing to chatscreen1 address. Or maybe update chat is still in middle of loop and the address changed. Ah im really new to this C++ pointer and addressing. Not much I can do about this

**Comment by sum2012** [comment] 2016-10-22 12:48
Compile error in Android
![1](https://cloud.githubusercontent.com/assets/2177532/19619403/d816d07c-9898-11e6-8f9d-87fcad0ce7db.png)

**Comment by adenovan** [comment] 2016-10-22 16:12
@sum2012 its not added to android make yet. im still working in random crash issues and make a fix just a hour ago :) , right now i am still testing with my buddy over the internet :). will post the result tommorow if not encountering a crash again its ready for pull request. you can check the changes on my branch.

**Comment by adenovan** [comment] 2016-10-22 18:58
@hrydgard can i add more asset to ppsspp? its a sound asset to used when chat coming and the chatscreen is not visible so user know there is a chat coming from other player. is there any sample code to play sound asset in ppsspp? what is the best file format for that? avi,mp3,wav? 

still uploading a online gameplay video now https://youtu.be/Cj00RmIg6oI , so far so good there is no random crash again in 2 hours of gameplay

**Comment by domnicap** [comment] 2016-10-29 14:12
I'm looking the game so on ,where can we download it?

**Comment by unknownbrackets** [comment] 2020-03-15 18:13
I think some degree of chat support is now available.  Is this issue / feature request fixed?

-[Unknown]

**Comment by hrydgard** [comment] 2020-03-15 18:24
Yeah let's close this.

**Closed by hrydgard** 2020-03-15 18:24 UTC
Labels: Feature Request, Networking / adhoc
