### ISSUE TITLE
Blank Screen when Choosing Vulkan as Backend in PPSSPPSDL 1.13.1 macOS Build

### ISSUE THREAD

**Issue by jerrypc2036** [hrydgard/ppsspp#15744] opened 2022-07-29 07:19 UTC
### Game or games this happens in

None

### What area of the game / PPSSPP

Switch graphic backend to Vulkan, and let PPSSPP restart.
The main window will remain blank.

OpenGL backend doesn't have this issue.

### What should happen

Vulkan backend should work like PPSSPPSDL 1.12.3.

### Platform

macOS

### Mobile phone model or graphics card

Macbook Pro Mid 2017

### PPSSPP version affected

1.13.1

### Last working version

1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by jerrypc2036** [comment] 2022-07-29 07:34
Logs printed out in console.

VulkanMayBeAvailable: Device allowed ('SDL:macOS')
VulkanMayBeAvailable: Library loaded ('@executable_path/../Frameworks/libMoltenVK.dylib')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 13
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000002)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (0000000a)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000002)
VulkanMaybeAvailable: Instance extension found: VK_EXT_metal_surface (00000001)
VulkanMayBeAvailable: Found platform surface extension 'VK_EXT_metal_surface'
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
Info: We compiled against SDL version 2.0.16 and we are linking against SDL version 2.0.16. :)
ThreadManager::Init(compute threads: 8, all: 16)
33:34:930 Core/Config.cpp:647 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
Pixels: 960 x 544
Virtual pixels: 960 x 544
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!

**Comment by unknownbrackets** [comment] 2022-12-29 01:38
This issue is being closed as a duplicate of #15473.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-12-29 01:38 UTC
Labels: Platform-specific (Mac OS X)
