### ISSUE TITLE
it crashes when i play games at iphone se(1st) ,ios14.2 with JIT

### ISSUE THREAD

**Issue by rinnelin** [hrydgard/ppsspp#14505] opened 2021-06-05 09:59 UTC
### What happens?
it crashes

### What *should* happen?
it runs

#### What hardware / device and operating system?
iphone se(1st) ,ios14.2
#### What graphics card (GPU) or mobile phone model?
a9?
#### What PPSSPP version (standalone/official), and did it work before?
1.11.3
after i update to 14.2, ppsspp always crashes when i use JIT
i can play some games with ir simulator, but they don't run as well as with jit
#### Which game or games?

persona3 (NPJH50040)

#### Checklist

 - [X ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by rinnelin** [comment] 2021-06-05 10:02
i can't play persona3 with ir simulator either.

**Comment by rinnelin** [comment] 2021-06-05 10:03
i can run all games with jit at ios13 of before

**Comment by Gamemulatorer** [comment] 2021-06-05 12:22
Duplicate of #14196 ??

**Comment by rinnelin** [comment] 2021-06-05 12:29
> Duplicate of #14196 ??
sorry, but i didn't saw any notice as my iphone is under 14.4

**Comment by LunaMoo** [comment] 2021-06-05 13:08
From this comment:
 https://github.com/hrydgard/ppsspp/pull/14201#issuecomment-787874615
it appears the last iOS version which works also depends on hardware/device model, so in your case it just doesn't work and it is another case for #14196, you can't use JIT on that device with that iOS version.

 This issue will stay linked in the other one by mentions, but we don't need to keep it open separately as it's already known, just hard to solve or not possible to solve at all issue. As such I'm closing this a duplicate.

**Closed by LunaMoo** 2021-06-05 13:08 UTC
