### ISSUE TITLE
[PC] DEMO GE2 Trial can't be started in Opengl Backend

### ISSUE THREAD

**Issue by jack00** [hrydgard/ppsspp#9199] opened 2017-01-01 12:37 UTC
D3DBackend is no problem. When starting in OGLBackend, it freezes.
This problem results from ppsspp-v1.0-101-g1170331

There may be cause on February 24, 2015 from February 23, 2015.
https://github.com/hrydgard/ppsspp/commits/master?after=Y3Vyc29yOpjHpzvwsJ2ZUtHqmtYDpLiI1fl9KzM0OTk%3D

God Eater 2 Trial
http://www.famitsu.com/matome/ge2/event01.html
http://eb-dl.pod.tv/download/20130731_ge2_trial/ge2_trial.zip

log file
https://drive.google.com/drive/folders/0By8WbS_hvsesYnhxTmkxR1pWZkU?usp=sharing

![2017 01 01-21 04](https://cloud.githubusercontent.com/assets/4569870/21581168/0d36d2be-d068-11e6-991b-97ba1b719ec2.png)

**Comment by jack00** [comment] 2017-01-01 22:05
Please see PCspec.txt in googledrive.
Radeon HD 7700 Crimson ReLive 16.12.2

**Comment by LunaMoo** [comment] 2017-01-02 02:50
Right, so I'll close it as a duplicate of #8698
AMD drivers are currently broken for dual source blending, the only reason ancient ppsspp works for you on affected drivers is because the effect was broken/not emulated properly in the past.

For a solution either use older pre-Crimson ogl drivers(enough to dump the ogl dll's to ppsspp folder), or wait for amd to release the driver with this problem fixed, you can follow the issue also in [here](https://community.amd.com/thread/205702).

**Closed by LunaMoo** 2017-01-02 02:50 UTC
