### ISSUE TITLE
Kingdom hearts birth by sleep final mix cwcheat bad invalidate icache

### ISSUE THREAD

**Issue by daniellegal** [hrydgard/ppsspp#7435] opened 2015-02-05 00:20 UTC
when i use codes in khbbs final mix they freeze on hang in the first screen

**Comment by hrydgard** [comment] 2015-02-05 05:59
Which code? Paste it here.

**Comment by daniellegal** [comment] 2015-02-05 12:08
_C1 All capacity
_L 0x1172AC54 0x0000FFC5
_L 0x1172AC58 0x0000FEC5
_L 0x1172AC5C 0x0000FEC5
_L 0x1172AC60 0x0000FFC5
_L 0x8172AC64 0x00070002
_L 0x1000FEC5 0x00000000
_L 0x1172AC80 0x0000FFC5
_L 0x1172AC84 0x0000FFC5
_L 0x8172AC88 0x00110002
_L 0x1000FEC5 0x00000000
_C0 All synthetic material
_L 0x817291B2 0x00080002
_L 0x10003200 0x00000002
_L 0x817291B4 0x002F0002
_L 0x10000063 0x00000000
_L 0x117291D2 0x0000320F
_L 0x817291D6 0x00040002
_L 0x10004600 0x00000001
_L 0x817291E6 0x00040002
_L 0x10004605 0x00000001
_L 0x817291F6 0x00040002
_L 0x10004609 0x00000001
_L 0x81729206 0x00060002
_L 0x1000460D 0x00000001
_L 0x8172921E 0x00070002
_L 0x10004614 0x00000001
_L 0x1172923A 0x0000461C
_L 0x1172923E 0x0000461D
_L 0x81729242 0x000B0002
_L 0x10004620 0x00000001
_C0 All weapons (only Aqua)
_L 0x81729192 0x000C0001
_L 0x10000201 0x00000001
_C0 All weapons (only Terra)
_L 0x81729192 0x000C0001
_L 0x10000101 0x00000001
_C0 All weapons (only Ventus)
_L 0x8172918E 0x000E0001
_L 0x10000001 0x00000001
_C0 Full Open skills (only Aqua)
_L 0x81729C66 0x0009000A
_L 0x10000118 0x00000002
_C0 Full Open skills (only Terra)
_L 0x81729C66 0x0009000A
_L 0x10000116 0x00000002
_C0 Full Open skills (only Ventus)
_L 0x81729C66 0x0009000A
_L 0x10000117 0x00000002
_C0 Store all items
_L 0x8172A9FB 0x024C0001
_L 0x000000FF 0x00000000
and the rest of the codes make the game freeze or close anytime:
_C0 inf HP =freeze somethimes but not work
_L 0xC013386C 0x0E200800
_L 0xC0133870 0x86040392
_L 0x20002000 0xA6040390
_L 0x20002004 0x03E00008
_L 0x20002008 0x00043140
_C0 MATERIAL AND FLAVOR 99=not work
_L 0x817291BE 0x00080002
_L 0x10003200 0x00000002
_L 0x817291E2 0x00040002
_L 0x10004600 0x00000001
_L 0x817291F2 0x00040002
_L 0x10004605 0x00000001
_L 0x81729202 0x00040002
_L 0x10004609 0x00000001
_L 0x81729212 0x00060002
_L 0x1000460D 0x00000001
_L 0x8172922A 0x00070002
_L 0x10004614 0x00000001
_L 0x81729246 0x00020002
_L 0x1000461C 0x00000001
_L 0x8172924E 0x000B0002
_L 0x10004620 0x00000001
_L 0x817291C0 0x002F0002
_L 0x10000063 0x00000000
_L 0x117291DE 0x0000320F
_C0 MEDAL MAX=not work
_L 0x201A5304 0x00000000
_C0 Money MAX=not work
_L 0x2172b8c4 0x000F423F
_C1 MONEY MAX=not work
_L 0x201A5298 0x00000000
_C1 Must code=not work
_L 0x201F7878 0x0A200404
_L 0x20001010 0x00942023
_L 0x20001014 0x8E45002C
_L 0x20001018 0x24010002
_L 0x2000101C 0x50250002
_L 0x20001028 0x0A27DE1F
_C0 The maximum level playing field=freeze
_L 0xC025D644 0x3404001E
_L 0xC025D64C 0xA2040037
_C0 Unlimited companion HP=not work
_L 0xC0001020 0x864401CA
_C0 Unlimited D-Link slot=freeze
_L 0xC011E664 0xE616003C
_C0 Users=not work
_L 0x2172b8c8 0x000F423F
_C0 Express Upgrade Skills=not work
_L 0xC00E21C0 0x24062710
_C0 Focus slot usually filled=not work,make game close anythime
_L 0xC0119FD4 0xE62C0044
_L 0xC011E494 0xE60E0044
_L 0xC0126418 0x00000000
_C0 FP Fast Recovery=freeze
_L 0xC0117E24 0x3C0F42C8
_L 0xC0117E28 0x448F6000

**Comment by LunaMoo** [comment] 2015-02-05 12:15
Codes which you have marked as freeze are all starting from 0xC, but from what I can tell this is not a CW cheat code type 0xC but rather NitePR or something code type hence those codes have no sense as cw cheats and their value is taken as address, which makes it soo high it does not exist.

**Comment by daniellegal** [comment] 2015-02-05 13:22
i remove the codes i tried others cwcheats but any of then works

**Comment by LunaMoo** [comment] 2015-02-05 13:36
I checked and I pretty positive those codes are simple 32 bit write in NitePR, and are not encrypted, so by simply changing _L 0xC to _L 0x2  you would change them into proper cw cheats.(doesn't mean they will surely work, as the address might still be wrong)

BTW you are sure it's the codes with 0xC that cause freeze? If we interpret them as cw cheats which ppsspp does, they should do absolutely nothing than skipping codes or not skipping them, they do not write anything there when presented as you have them since there are no other codes under those cheats meaning they are not even working as cheats. If they cause a freeze by doing nothing, there's something wrong with them anyway.:/

**Comment by daniellegal** [comment] 2015-02-05 13:37
i tried use the convertor from raing3 and work

**Comment by LunaMoo** [comment] 2015-02-05 13:54
Ok while those were not real 0xC codes, I can confirm that 0xC does cause a freeze.

The code should do:
Code Stopper 0xCaaaaaaa 0xvvvvvvvv aaaaaaa = address (25 bit)
vvvvvvvv = value (32 bit)
All following codes will be executed only, if 32-bit value
at given address, aaaaaaa, is equal to given value, vvvvvvvv.
Otherwise, they will be skipped. Can be used to exit the code sequence at any point.
To act on all codes (like traditional “Auto Activation”), put it at the top of the code list!

Currently if value set for the code to check equals to value in memory nothing happens - that's good. However if the value in cheat doesn't match value in memory it freezes ppsspp while it should skip all codes below it.

**Comment by LunaMoo** [comment] 2015-02-05 14:35
@daniellegal by saying "work" after using converter you mean you fixed your issue? Or still there's another problem? Codes that looks ok, but not work or crash the game, are more than likely having incorrect address since it differs in ppsspp than it's on psp.

 0xC type shouldn't freeze ppsspp anymore after the small fix for it get's merged, however you should replace all _L 0xC to _L 0x2 in your codes if converter didn't do it anyway, as those codes only look alike between nitePR and CW cheat while doing something else:].

**Comment by daniellegal** [comment] 2015-02-05 15:51
thanks

**Comment by daniellegal** [comment] 2015-02-06 12:53
NOW ANOTHER CODE IS CLOSING THE GAME
_C1 Express Upgrade Skills=CONVERTED
_L 0x200E21C0 0x24062710
_C0 Express Upgrade Skills=Original
_L 0xC00E21C0 0x24062710

**Comment by LunaMoo** [comment] 2015-02-06 13:39
0x24062710 is "li a2,0x2710" writing that opcode in some function of the game seems like a legit way to make a cheat with such name, certainly more legit than using 0xC which depending on condition would either do nothing or make all codes below it do nothing.
 So I would say the address is wrong and it replaces something it shouldn't triggering a crash:|. Unfortunately making game memory on ppsspp exactly same as in psp in all games is not an easy thing, so that is a much deeper problem which will probably not be fixed anytime soon.

 You might try setting psp model to PSP-1000 in ppsspp system settings which might make it closer to the real thing, but if it doesn't help then you'll need to find a different code. You could ask around in the game thread on the forums as maybe someone already has such cheat or can do it for you. I don't have this game so can't really do that.

**Comment by unknownbrackets** [comment] 2015-12-29 17:35
Is this still a relevant issue?

-[Unknown]

**Comment by hrydgard** [comment] 2015-12-29 18:34
Hasn't been reported since, so I'm closing.

**Closed by hrydgard** 2015-12-29 18:34 UTC
Labels: Cheats
