### ISSUE TITLE
A way to disable plugin

### ISSUE THREAD

**Issue by HFPasfho** [hrydgard/ppsspp#18864] opened 2024-02-13 12:27 UTC
### What should happen

There should be a way to disable the plugin other than deleting it from plugins folder.

### Who would this benefit

People using or testing plugins. Currently, plugin management is very tedious.

### Platform (if relevant)

None

### Games this would be useful in

not applicable

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by anr2me** [comment] 2024-02-13 13:26
I agree, it should be as easy as disabling cheat.

**Comment by hrydgard** [comment] 2024-02-14 02:20
Yeah, it makes sense to have a checkbox for this.

We actually have a setting in the ini file but it's not exposed in the UI

**Comment by NABN00B** [comment] 2024-02-16 10:43
Duplicate of #15819

**Comment by hrydgard** [comment] 2024-02-16 12:36
Oh right, indeed.

**Closed by hrydgard** 2024-02-16 12:36 UTC
Labels: Feature Request
