### ISSUE TITLE
tales of destiny 2 grahpics problem and speed problem

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#7587] opened 2015-03-13 05:59 UTC
i play the game on andriod it works perfect on 1x resoution on samsung galaxy s4 but there a problem is if u put 3x resloutoin u get black screen on the background and menu even same problem is windows and andriod.

i playing it too much on my phone i  have to put 1 frameskip to play the game properly fix it for andriod.

**Comment by daniel229** [comment] 2015-03-14 06:39
The game is cpu and gpu demanding,and full speed at 60 fps.On desktop i can get 100 fps with 4x resolution, 170 fps with 2x resolution in battle, If disable slower effect,I can get 230 fps with 4x and 250 with 2x.

**Comment by unknownbrackets** [comment] 2015-03-14 07:31
Hmm, it spends 64% of its time in the texture cache in a town.  Retain changed textures doesn't help, nor does lazy texture caching.

It uses the same texture offset to get to different coordinates, which only makes the texture cache slower, but I'm not seeing the texture change... hmm.  It keeps deindexing.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-03-14 18:10
So, in town, including the dim in the cache key (as a test) makes it run much faster.  This is because it uses different dimensions (e.g. 512x512 and 512x16) of the same texture data, multiple times per frame.

I wonder how safe it would be to include dim in the cache key.

https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:texcache?expand=1

I haven't really tested it with other games, although it ought to be safe.  Does it improve battles?

Assuming it doesn't improve battles... can you give me some savedata?  Not sure how to get through the intro, haven't played this yet and my Japanese is weak.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-03-14 19:50
It also spends 10% of its time in SAS, which could probably be optimized, but also needs pitch adjustment, which I'm not planning to mess with right now since I won't be able to tell clicks and such.

Anyway, making it use a thread the easy way (not using copies or syncing, yay for non-determinism) adds about 7% performance (700% -> 750%) on my desktop.  The remaining time (the 3%) is waiting in the subsequent call to sceSasCore for the previous to finish.

Anyway, even with the above changes it still spends 30% of its time in the texture cache, now hashing (this is still because of the different offsets it uses, I think.)  Switching to lazy texture caching brings us to about 1200% (+60%), since it skips a lot of that.  With that, it spends about 36% of its time drawing in general, so I guess more time in the jit at that point.

-[Unknown]

**Comment by asbel123** [comment] 2015-03-15 01:50
tales of destiny 2 on pcsx2 emulator always go to slow alot on pc but on ppsspp always got fullspeed 0 glitches and andriod works too. pcsx2 cant run tales of destiny 2 propely some areas go slow alot

**Comment by daniel229** [comment] 2015-03-15 02:13
The battle won't get improvement unless slower effects is off,but when it off it gets improvement for speed from 250fps to 700fps.The battle does not require a savedata,it's from the new game.

savestate for the battle (rename jpg to 7z)
![uljs00097_1 00_2](https://cloud.githubusercontent.com/assets/3481559/6654387/ca2bc13c-cafb-11e4-8505-cf61b2c36de9.jpg)

**Comment by unknownbrackets** [comment] 2015-03-15 02:22
Thanks, I'll load that a bit later.

Hmm, maybe I just need to restart.  I have some savedata in the first town but the guy won't let me leave town and I can't tell why or what I'm supposed to do first...

-[Unknown]

**Comment by daniel229** [comment] 2015-03-15 04:47
That change fixes the glitch in split /second.
![01](https://cloud.githubusercontent.com/assets/3481559/6654714/66166db2-cb11-11e4-8145-2bab65bcdd31.png)

**Comment by unknownbrackets** [comment] 2015-03-15 05:02
Hmm, do you mean the circle/shadow?  Well, I guess I should figure out why it affected that because I was aiming for no functional changes, just performance.  Hmm.

-[Unknown]

**Comment by daniel229** [comment] 2015-03-15 05:05
Yes,it's the circle one.

**Comment by unknownbrackets** [comment] 2015-03-15 05:27
Ugh.  I know why.  This change might cause problems for Type-0, maybe.  In the menus....

Because it makes it so there's a different tex cache entry when using render-to-texture with a different size.

But the split/second thing is a bug, since it's always a render-to-texture, and the render size changes, so it should not reject the framebuffer.

If this doesn't cause problems for Type-0 it might be okay.  I think I could reproduce the issue in the demo, if I can remember what it was.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-03-15 06:10
This is what I was thinking of - #4274.  But actually the issue I was thinking of was related to Tactics Ogre (#3664, #2758.)  But I think it's all still working now.

-[Unknown]

**Comment by daniel229** [comment] 2015-03-15 08:10
Tested some games it seems good.it also affect https://github.com/hrydgard/ppsspp/issues/4112

with that chenge
![01](https://cloud.githubusercontent.com/assets/3481559/6655181/a7507afe-cb2d-11e4-8478-96308b53110b.png)

witout that change
![02](https://cloud.githubusercontent.com/assets/3481559/6655182/a7523952-cb2d-11e4-901c-f138bf612fe7.png)

**Comment by unknownbrackets** [comment] 2015-03-15 09:10
Okay, I have an idea what that game might be doing then, and it's nothing good.  But I don't think it's worse with this change.

-[Unknown]

**Comment by hrydgard** [comment] 2015-03-15 10:21
I somehow don't understand what it's doing to need the doubling, 
    because the original texture looks fine. It's basically halving the color
    with the vertex color and then doubling to compensate... ugh.

This is an old technique from the PSX and a similar idea was also used in Quake 3, by modifying the gamma ramp to get a 2x color. The idea is to give yourself headroom to not only darken things by setting vertex colors but also brightening them by setting them over 1.0 - which with this kind of trick is really 0.5.

Of course, it may be that the game doesn't even utilize the possibility to brighten things, if it just took parts of an engine from some older game that did..

**Comment by unknownbrackets** [comment] 2015-03-18 06:01
Does this improve anything in the battle?

https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:tex-split?expand=1

Don't have time to check myself now, but if you do before me, just wondering if I'm barking up the right tree.

-[Unknown]

**Comment by daniel229** [comment] 2015-03-18 06:12
No,it doesn't.

**Comment by unknownbrackets** [comment] 2015-11-15 08:59
I'm going to mark this fixed now that #8213 is merged.  There's always more room for improvement, but the major wins for battle and town have already been made.

-[Unknown]

**Closed by unknownbrackets** 2015-11-15 08:59 UTC
