### ISSUE TITLE
Hotono ken gaiden bug are fix in build bots

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12199] opened 2019-07-27 17:09 UTC
### What happens?
No ui

### What *should* happen?
This bug is fix or not

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Latest build bot

**Comment by hrydgard** [comment] 2019-07-27 17:14
Screenshots of working/not working?

**Comment by PilipinoAko** [comment] 2019-07-27 17:15
Ha wait that game i delete last moth i download it again ....

**Comment by PilipinoAko** [comment] 2019-07-27 17:46
Its black screen i use cheat and its works 
But u need to fix it for others has no idea for cheats

**Comment by Emulatorer** [comment] 2019-07-27 23:49
Duplicate #7932?

**Comment by PilipinoAko** [comment] 2019-07-28 00:09
Its 4 months ago need to fix it now
Some games is fix but this is not fix
For some reason

**Comment by Emulatorer** [comment] 2019-07-29 00:23
@PilipinoAko this game full title is Hokuto no Ken Raoh Gaiden Ten no Haoh (Legends of the Dark King: A Fist of the North Star Story)? if yes then it's a duplicate of #7932

**Comment by Emulatorer** [comment] 2019-07-29 00:23
@PilipinoAko this game full title is Hokuto no Ken Raoh Gaiden Ten no Haoh (Legends of the Dark King: A Fist of the North Star Story)? if yes then it's a duplicate of #7932

**Comment by Emulatorer** [comment] 2019-07-31 10:34
No feedback outdated?

**Comment by unknownbrackets** [comment] 2019-07-31 11:24
This issue is being closed as a duplicate of #7932.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-07-31 11:24 UTC
