### ISSUE TITLE
Tilt controls doesn't work on iOS 

### ISSUE THREAD

**Issue by Wh0ba** [hrydgard/ppsspp#10639] opened 2018-02-23 09:39 UTC
What happens?

When enabling the tilt controls from the menu on iOS 
It doesn't work 

Like I've been tilting my phone all around but it doesn't work 

What *should* happen?

Tilting the phone to trigger various buttons 

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

iOS 10.2
iPhone 5s

**Comment by unknownbrackets** [comment] 2020-04-12 03:54
This issue is being closed as a duplicate of #6438.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-04-12 03:54 UTC
Labels: Platform-specific (iOS)
