### ISSUE TITLE
GTA, wrong clipping on D3D and Vulkan

### ISSUE THREAD

**Issue by majesticR3** [hrydgard/ppsspp#14377] opened 2021-04-13 13:53 UTC
Hello,
I've noticed this issue a while ago, also in case checked on latest currently v1.11.2-487-gf52bef701 build.
Used default graphics settings, tried even on native PSP resolution.
Issue seems only happen when I use Direct3D 9,11 or Vulkan rendering backend. With OpenGL renderer on same build it looks normal.

Direct3D, Vulkan:
https://i.imgur.com/Org53dL.jpg

OpenGL:
https://i.imgur.com/vkPtdZv.jpeg

**Comment by ANR2ME** [comment] 2021-04-13 14:28
Please create a GE frame dump for the devs to investigate https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

PS: as i remembered there were issues related to clipping, they could be related.

**Comment by hrydgard** [comment] 2021-04-13 15:15
I believe this is a duplicate of https://github.com/hrydgard/ppsspp/issues/12060 , and I think we might have even more reports of a similar bug elsewhere.

**Closed by hrydgard** 2021-04-13 15:15 UTC
