### ISSUE TITLE
Help running 2 PPSSPP on 1 PC?

### ISSUE THREAD

**Issue by superckool** [hrydgard/ppsspp#9402] opened 2017-03-07 19:38 UTC
Alright I've looked all around and can't figure out how to make this work, trying to play Monster Hunter Portable 3rd with 2 emulators on the same PC. When I try to connect most of the time one always gets a network initialized message then the guild hall screen never shows up and I can't do anything. Also, is the PPSSPP forums down for anyone else? Or just me? Been this for for a couple days now. Thanks for any help and I'll provide any more information as necessary.

**Comment by superckool** [comment] 2017-03-15 04:58
Any help on this issue? Hate to bump but any help or information would be greatly appreciated.

**Comment by NgJinXiang14** [comment] 2017-03-22 14:01
http://forums.ppsspp.org/showthread.php?tid=12357.  Try this ppsspp build

**Comment by Hydroque** [comment] 2017-08-03 23:57
I am assuming you didn't take the steps to use your own ad hoc pro server or you are trying to connect to coldbird's server, which is dead. One last thing could be the lack of port forwarding behind a router.

**Comment by unknownbrackets** [comment] 2020-04-12 04:50
This issue is being closed as a duplicate of #5935.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-04-12 04:50 UTC
Labels: Networking / adhoc

**Comment by Panderner** [comment] 2020-04-12 10:43
> This issue is being closed as a duplicate of #5935.
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

@unknownbrackets can you Mark this as a duplicate?
