### ISSUE TITLE
[Android/OpenGL] God Eater Burst/God Eater 2 turned on white screen on City of Mercy map (Some area).

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12276] opened 2019-08-25 17:24 UTC
### What happens?

White screen in City of Mercy map, when entering Zone D, C, F, E. happen with OpenGL only, on Vulkan is work fine.
![69855909_402003433781280_296841746925486080_n](https://user-images.githubusercontent.com/26355472/63653519-efe0ff80-c797-11e9-9bbf-1ddfa0110cd5.png)

Video example.
https://youtu.be/lbFce_NzSas

GE Dump from GE2
[GE2-GEDump.zip](https://github.com/hrydgard/ppsspp/files/3538419/GE2-GEDump.zip)

### What *should* happen?

Not white screen. :)
![GE2-WC-2](https://user-images.githubusercontent.com/26355472/63652450-5d862f00-c78a-11e9-822e-1a74fcee1efb.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- PPSSPP v1.8.0-573-ge6d68698e with default settings.
- Device: Huawei P9 Plus. (HiSilicon Kirin 955/Mali-T880 MP4) and Samsung Galaxy J7 Prime (Exynos 7870 Octa/Mali-T830 MP1)

**Comment by hrydgard** [comment] 2019-08-25 18:33
Any idea if it happens in previous versions of the emulator, and if so when it started happening?

**Comment by Saramagrean** [comment] 2019-08-26 04:04
I'm not sure because... 

v0.95-0.98 =  can't start app. 
v0.9.9 = beginning to encounter white screen problems.

**Comment by hrydgard** [comment] 2019-08-26 07:29
Got another report of this by email, will try to take a quick look before 1.9.

**Comment by Saramagrean** [comment] 2019-08-27 10:13
ppdump open with Vulkan backend. 
![Screenshot_PPSSPP_20190827-171010](https://user-images.githubusercontent.com/26355472/63762846-c0440b80-c8ed-11e9-90cc-76353b0a960d.png)

ppdump open with OpenGL backend. 😂
![Screenshot_PPSSPP_20190827-171021](https://user-images.githubusercontent.com/26355472/63762922-ea95c900-c8ed-11e9-8894-60553901ca39.png)

**Comment by Saramagrean** [comment] 2019-09-01 06:30
Tested with Huawei Y5 Lite (MediaTek MT9739, PowerVR GE8100) 

OpenGL - Not white screen. :)
![Screenshot_20190901-131406](https://user-images.githubusercontent.com/26355472/64072609-3cf33300-ccbc-11e9-81ef-3b577739f7eb.png)

Vulkan - Not working, UI broken. 🤣
![Screenshot_20190901-132745](https://user-images.githubusercontent.com/26355472/64072644-9eb39d00-ccbc-11e9-9854-b7fab50de7fe.png)

**Comment by hrydgard** [comment] 2019-09-01 15:48
That really on the latest build? I thought we fixed the PowerVR stride bug. Looks like it has somehow returned... Anyway I believe that's a separate issue.

**Comment by Saramagrean** [comment] 2019-09-01 15:58
Yeah, I use latest git build (1.8.0-585).

**Comment by hrydgard** [comment] 2019-09-01 16:10
Thanks for letting me know! I have a suspicion... hm.

**Comment by hrydgard** [comment] 2019-09-01 16:23
@Saramagrean Committed a potential fix - check it out once it's built.

**Comment by unknownbrackets** [comment] 2019-09-01 16:47
If it's not fixed, please create a separate issue so we don't get distracted from the Mali issue here.  Both should get fixed.

-[Unknown]

**Comment by Saramagrean** [comment] 2019-09-01 16:49
Okay. 👌

**Comment by PilipinoAko** [comment] 2019-09-02 06:27
Reset the setting or turn of disable slower effects 🤔

**Comment by Saramagrean** [comment] 2019-09-02 06:30
I use default settings...

**Comment by PilipinoAko** [comment] 2019-09-02 06:32
I play god eater burst 2 but no white screen bug i use indo patch

**Comment by Saramagrean** [comment] 2019-09-02 06:46
@PilipinoAko What phone model are you using?

**Comment by hrydgard** [comment] 2019-09-08 23:08
Hey @Saramagrean  could you try again with the latest build ("Vulkan: Workaround ARM Mali depth hardware bug" when it's out)? It's possible this was related to that one.

**Comment by hrydgard** [comment] 2019-09-08 23:14
Uh wait never mind scratch that - it was OpenGL that was broken here, not Vulkan.

**Comment by Saramagrean** [comment] 2019-09-09 04:42
v1.8.0-615 Issue still exist. 🙃
![Screenshot_PPSSPP_20190909-113727](https://user-images.githubusercontent.com/26355472/64503756-b7443880-d2f6-11e9-8308-c31b03296224.png)

**Comment by hrydgard** [comment] 2019-09-10 21:29
Now this is a weird one - turning off Hardware Transform fixes it (but will lose you performance).

Hmmm....

**Comment by unknownbrackets** [comment] 2019-09-13 23:43
If we had a web GE debugger (I need to get around to that), we could easily verify which draw causes it, like on Windows.

I assume if you disable all framebuf draws it draws properly?

-[Unknown]

**Comment by Saramagrean** [comment] 2020-05-28 10:19
Update GE dump. (v1.9.3-973-g2ba65c831)
https://drive.google.com/file/d/11Px1VX1hHCjRA9zuA_TKyJwqzjD8SUWs/view?usp=drivesdk

**Comment by Gamemulatorer** [comment] 2020-06-04 05:53
@Saramagrean I can't reproduce using your dump weird?
![Screenshot_20200604-135154](https://user-images.githubusercontent.com/37603562/83719973-c3cda580-a66a-11ea-8060-f78db92b9497.png)
![Screenshot_20200604-135207](https://user-images.githubusercontent.com/37603562/83719979-c62fff80-a66a-11ea-9943-111dadd3065d.png)
### Mali 450 MP4 GPU

**Comment by Gamemulatorer** [comment] 2020-08-18 18:09
> Update GE dump. (v1.9.3-973-g2ba65c831)
> https://drive.google.com/file/d/11Px1VX1hHCjRA9zuA_TKyJwqzjD8SUWs/view?usp=drivesdk

Can't repro this issue anymore using ppsspp latest build.
![Screenshot_2020-08-19-02-03-48](https://user-images.githubusercontent.com/37603562/90549362-f7779080-e1c0-11ea-9e0a-959c68b471ef.png)
![Uploading Screenshot_2020-08-19-02-05-39.png…]()

**Comment by hrydgard** [comment] 2020-08-18 19:14
Nice, thanks for testing!

**Closed by hrydgard** 2020-08-18 19:14 UTC
Labels: Mali GPU, OpenGL, Platform-specific (Android)
