### ISSUE TITLE
Modnation racers crashing in design studio

### ISSUE THREAD

**Issue by wolf221** [hrydgard/ppsspp#8378] opened 2016-01-04 00:15 UTC
I'm having problems with Modnation Racers, each time i try to use the Design Studio it crashes. It's the same as with another issue for Modnation Racers but in that topic no-one actually said what other people could do to fix the problem.

**Comment by unknownbrackets** [comment] 2016-01-04 00:20
Duplicate issues only make things harder.  If you're wanting to discuss the issue, the forum is here:

http://forums.ppsspp.org/

This isn't a topic, it's an issue.

-[Unknown]

**Comment by wolf221** [comment] 2016-01-04 00:23
Thank you, should i delete this issue then?

**Comment by unknownbrackets** [comment] 2016-01-04 00:53
Do you mean it's a duplicate of the already closed #5412?  So this is happening again?

And you're using the latest git build, not some old pre-1.0 version like the one before it was fixed?

-[Unknown]

**Comment by sum2012** [comment] 2016-01-07 23:27
Do not happen to me
v1.1.1-645-g481be1c windows 64 bit
 
![1](https://cloud.githubusercontent.com/assets/2177532/12185902/3332ca36-b5d9-11e5-9f43-df2eaa754900.jpg)

**Comment by wolf221** [comment] 2016-01-11 17:41
The issue is fixed now, it works fully on the newest version of ppsspp.

**Closed** 2016-01-11 18:13 UTC
