### ISSUE TITLE
Multiplayer on Dragon Ball Z Tenkaichi Tag Team don't work

### ISSUE THREAD

**Issue by sero583** [hrydgard/ppsspp#8280] opened 2015-12-20 19:41 UTC
Setting up Multiplayer etc and Playing works fine on PPSSPP Android, but on Dragon Ball Z Tenkaichi Tag Team, it wom't work.
Please fix this as soon as possible, thanks in advance!

**Comment by magma-blaziken** [comment] 2015-12-29 05:32
Multiplayer is not working for YuGiOh TagForce (1-6) on the android version as well. Could someone please help take a look at it or should I open a new issue. Apologies in advance if I'm not suppose to post here.

**Comment by sero583** [comment] 2016-01-05 01:18
@magma-blaziken Its a issue, thats why i could say open a issue.
The developers would see it, too then mark it and fix it, as soon as possible

**Comment by sero583** [comment] 2016-12-04 13:40
Any updates?

**Comment by Anuskuss** [comment] 2016-12-04 14:52
Multiplayer is working for my with **Yu-Gi-Oh! GX Tag Force 2** between iOS and Windows. Try connecting them and host the lobby on your phone, that did the trick for me.

**Comment by sero583** [comment] 2016-12-04 15:07
@Anuskuss My problem isn't Yu-Gi-Oh! I want to play Dragon Ball Z Tenkaichi Tag Team

**Comment by Emulatorer** [comment] 2020-04-17 22:54
Still can't play multiplayer this game using ppsspp v1.9.3-683 :(

**Comment by sero583** [comment] 2020-04-19 09:14
Wow, this was almost 5 years ago.

**Comment by unknownbrackets** [comment] 2020-12-31 17:07
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by sero583** [comment] 2020-12-31 19:32
I really can't tell, since I never went in touch after it. Been years already, what I can tell my experince was, that multiplayer was only achieved in a hacky way. Will test it out today.

**Comment by ANR2ME** [comment] 2021-01-01 12:54
localhost and LAN (android vs Windows) worked fine as i remembered, not sure over the internet tho

**Comment by sero583** [comment] 2021-01-06 11:25
Sorry for late repsonse. Answer: No, the issue which used to be there still remains. Localhost doesn't work, internal network though and external also, tried everything out. Well, I guess when localhost doesn't works its still a PPSSPP issue, thats why logically internal and external doesn't works though. It says "Socket error (10061) when connecting to {ipAddr}/{ipAddr:port}" (the one I have set)

**Comment by ANR2ME** [comment] 2021-01-06 14:26
> 
> 
> Sorry for late repsonse. Answer: No, the issue which used to be there still remains. Localhost doesn't work, internal network though and external also, tried everything out. Well, I guess when localhost doesn't works its still a PPSSPP issue, thats why logically internal and external doesn't works though. It says "Socket error (10061) when connecting to {ipAddr}/{ipAddr:port}" (the one I have set)

Are you using the most up-to-date version at https://buildbot.orphis.net/ppsspp/ ? if you're not, please try it.

**Comment by Anuskuss** [comment] 2021-01-07 04:30
Always a pleasure to get a notification for an old ass thread you made an off topic comment in :P Anyway, I can confirm that this game works for me over LAN, thanks to the excellent work by @ANR2ME.
Also @ANR2ME, did you know that Adhoc even works over IPv6? Incredible stuff.

**Comment by hrydgard** [comment] 2021-01-07 08:42
Sounds like it should be working now, closing. If you really can't get it to work with the latest build @sero583 , please re-open.

**Closed by hrydgard** 2021-01-07 08:42 UTC
Labels: Networking / adhoc, No Feedback / Outdated?

**Comment by ANR2ME** [comment] 2021-01-07 12:04
> 
> 
> Always a pleasure to get a notification for an old ass thread you made an off topic comment in :P Anyway, I can confirm that this game works for me over LAN, thanks to the excellent work by @ANR2ME.
> Also @ANR2ME, did you know that Adhoc even works over IPv6? Incredible stuff.

I didn't know it can works with IPv6 O.o that's a surprise for me LOL
As i remembered AdhocServer and PPSSPP only stores IP in 32bit variable, so it can only fit IPv4, may be the OS or router is mapping the IPv4 to IPv6
