### ISSUE TITLE
Crashing issue whenever I switch to opengl after using Vulkan

### ISSUE THREAD

**Issue by JunEvergreen** [hrydgard/ppsspp#15380] opened 2022-02-07 06:45 UTC
What happens?
When I use OpenGL the games crash And the emulator closes

What should happen?
Games should go normal without crashing

What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues.
Vivo y11(2019)

Dimensions: 159.4 x 76.8 x 8.9 mm (6.28 x 3.02 x 0.35 in)

Chipset: Qualcomm SDM439 Snapdragon 439 (12 nm)

CPU: Octa-core (4x1.95 GHz Cortex-A53 & 4x1.45 GHz Cortex A53)

GPU: Adreno 505

RAM: 3GB

Storage: 32 GB

Display 
Type: IPS LCD
Size | 6.35 inches, 99.6 cm2 (~81.4% screen-to-body ratio)
Resolution | 720 x 1544 pixels (~268 ppi density)

OS: Android 11

See more info about my current phone Im using right now: https://www.gsmarena.com/vivo_y11_(2019)-9925.php

PPSSPP versión: 1.12.3

Other information
I use openGL is because it has less lag than vulkan and as I was playing kingdom hearts, whenever I choose to have a new game, there are few cutscenes along the way, then right afterwards that you can see Sora running down the stairs trying to see the meteor shower by himself, since he cant see much from where he stands, then as I was trying to move the analog stick the game crashes, it has been a issue to my phone ever since.

**Comment by unknownbrackets** [comment] 2022-02-07 06:54
Thanks, this is helpful detail to add to #15258.

This issue is being closed as a duplicate of #15258.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-02-07 06:54 UTC
