### ISSUE TITLE
Android controller mapping error

### ISSUE THREAD

**Issue by SAlesci** [hrydgard/ppsspp#9883] opened 2017-08-05 08:35 UTC
Everything works just fine, except for X O and square button. They're not recognized as pad1.B, A or Y, but as pad1.e2f?+, e2d?+, e2e?+. It would be ok if they worked in game, but no, even if I set them in the controls menu. I thought about using the second analog controller, but it's not very comfortable, and I've problems in games where I should use more than 1 button at the same time. The cause of the problem of course is the phone (galaxy s4 on stock 5.0.1) or the controller/adapter. For the phone i'll check soon on a newer phone, but if ppsspp recognize the input in the controls menu, why it shouldn't work in game?

**Comment by SAlesci** [comment] 2017-08-05 08:36
(Triangle works just fine and it's mapped on pad1.Y)

**Comment by hrydgard** [comment] 2017-08-05 16:32
The fallback key name comes from this line:

	return StringFromFormat("%02x?", key);

so the codes are e2d, e2e, e2f. e2d is 3629, which is curiously large for a keycode, hm. Googling doesn't find much. But yes, they should work if they are configurable, rather strange. We have a hack where we manually assign keycodes about 4000 to virtual axis keys, but that is above e2d.

Curious...

**Comment by SAlesci** [comment] 2017-08-05 17:28
The windows version of ppsspp works. Some android apps don't recognize those 3 buttons completely.

**Comment by SAlesci** [comment] 2017-08-05 20:39
Fixed it.

I used an app called USB/BT JoyCenter, it recognized the buttons and "redirected" the input on another key, it does not require root.

**Comment by hrydgard** [comment] 2017-08-05 22:37
Well, that's more of a workaround than a fix. Don't understand why it wouldn't work on Android, I mean, we obviously were getting keycodes since you could map them.

**Comment by unknownbrackets** [comment] 2017-08-08 06:41
Is it possible you had redirected the keys previously in some way?

-[Unknown]

**Comment by SAlesci** [comment] 2017-08-08 07:15
No. And to redirect the keys usb joycenter has to be opened in background, while the system keyboard is temporanely set to the joycenter keyboard

**Comment by unknownbrackets** [comment] 2018-04-14 17:15
Any updates / changes on what's happening here?  I've never reproduced this.

I'm moving to v1.7.0 (not that we can't fix it sooner) since it's not a regression from v1.5.4.

-[Unknown]

**Comment by hrydgard** [comment] 2019-08-23 15:16
I don't know if this is still a problem. Closing.

**Closed by hrydgard** 2019-08-23 15:16 UTC
Labels: Input/Controller
