### ISSUE TITLE
Cannot shotlock with L+R+O (Circle) in Kingdom Hearts Birth By Sleep Final Mix

### ISSUE THREAD

**Issue by buruto** [hrydgard/ppsspp#11394] opened 2018-09-17 10:05 UTC
I started new game on Critical Mode and I am in the introduction and tutorial of the game.

I am currently playing with Aqua and the INFORMATION says to use shotlock against Ventus.

I have got instructions to hold down both the L and R buttons to start focusing on the target and at last press the Circle button to shoot.

I hold down the L and R buttons and Aqua focuses on Ventus as it should, but when I press the Circle button while still holding down L and R buttons, nothing happen, but if I click the Circle button with my mouse on the screen then the shotlock performs, but I want to play the game with my keyboard only without my mouse at all.

I don't have a real PSP.

I have downloaded an ISO file of the game and I downloaded the most recent release version of the PPSSPP emulator from the EmuCR website.

I am playing the game on my PC (Personal Computer) using the PPSSPP emulator.

In my Control mapping:

I chose that holding down the 'L' key of my keyboard is to hold down the 'L' button of the PSP, holding down the 'R' key of my keyboard is to hold down the 'R' button of the PSP and pressing the 'O' key of my keyboard is to press the Circle button of the PSP.

I like this control mapping and I don't want to change it to solve this problem.

I just want to know if there is another way to solve this problem without changing my control mapping at all.

By the way that I am using the most recent version of Windows 10 Pro 64 bit.

**Comment by marosis** [comment] 2018-09-17 10:12
Just try to do combination  key 1 in the settings. It is really easy

**Comment by buruto** [comment] 2018-09-17 11:07
> This happens because your keyboard is limited

Does exist a way to remove this limitation?

Because I dislike the idea to change my control mapping to solve this problem.

> Or better, use a controller if you have one.

I have PS4 controller. Will it work?

**Comment by marosis** [comment] 2018-09-17 19:46
No you can't remove limitation. It is impossible. And PS4 Controller is really bad for playing on different mechanics. Trust me i have PS4. Bad because of different response of bluetooth conection.( Something like Slow reaction) and this you cannot fix too.😥

**Comment by marosis** [comment] 2018-09-17 19:49
You can connect it by holding OPTIONS+ PS button. He will lightning White that mean He Is ready for paring

**Comment by LunaMoo** [comment] 2018-09-17 20:34
Not a bug, closing, as mentioned above it's keyboard ghosting, some key combinations cannot be used which differ per keyboard model, the only way to avoid that limitation is to map the keys differently. Or use a different input device like a gamepad or much more expensive keyboard that is designed to avoid the problem.

**Closed by LunaMoo** 2018-09-17 20:34 UTC

**Comment by buruto** [comment] 2018-09-17 21:01
I understand you and also thanks you for your advices.
