### ISSUE TITLE
Sengoku Musou 3Z Special: Error when choosing DLC Costumes

### ISSUE THREAD

**Issue by hikarinnohikari** [hrydgard/ppsspp#9993] opened 2017-10-02 04:50 UTC
Just like in the title, i have problem concerning DLC costumes in this 

game, whenever i choose a costume the emulator freeze/Crash saying "ppsspp 

has stopped working".

I have tried with multiple version of ppsspp, (1.2.2, 1.3, 1.4, 1.4.2, 

1.4.2-196-gdfdf548-windows-amd64) and every backend resulting in the same 

error.

I've read a post on another forum, said that this DLC only work on real PSP 

with certain CFW, no one know a way to make this DLC work on emulator so i 

ask here.

This is how to reproduce the problem: (assuming you already have the game 

and its DLC) open the game, press square when in character selection screen 

and then press either L or R.

**Comment by hikarinnohikari** [comment] 2017-10-02 04:58
here is the log:

http://uploads.im/3GAiE.png

**Comment by IrfanH495** [comment] 2021-12-24 01:13
dlc works fine.  but if I choose a costume for too long it will fc or freeze fps 0/0 
like in the video
https://drive.google.com/file/d/11T5TRzlhd1xjOdP0le-oCIKzZ52zDh-h/view?usp=drivesdk
![Screenshot_20211224-080410](https://user-images.githubusercontent.com/78854859/147303589-b6b809e9-33e9-4214-8e56-8044d094130a.png)
![Screenshot_20211224-080417](https://user-images.githubusercontent.com/78854859/147303594-5c33abf9-83c2-49fd-8a5f-6949910f9fa0.png)
![Screenshot_20211224-080422](https://user-images.githubusercontent.com/78854859/147303599-8efd4b62-22ce-4d69-97ad-21687f59dd87.png)
sometimes fc if i choose costume too long.  I just added it in compat.ini
[BlockTransferAllowCreateFB]
戦国無双３ Z Special
ULJM06024 = true
[IntraVRAMBlockTransferAllowCreateFB]
戦国無双３ Z Special
ULJM06024 = true
[ForceUMDDelay]
戦国無双３ Z Special
ULJM06024 = true
what else should be added to compat.ini to avoid fc

**Comment by unknownbrackets** [comment] 2021-12-24 23:28
Okay, sounds like the crash is fixed.  Let's close this one and just leave #12512 open.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

-[Unknown]

**Comment by leoxxx** [comment] 2022-05-09 03:05
g045709dbc still error.
Try it on android device.

**Comment by IrfanH495** [comment] 2022-06-25 23:27
> g045709dbc still freeze on android device. add ULJM06024 = true in PPSSPP\assets\compat.ini, then try it on PC, still freeze, can't chage costumes. v1.12.3
@leoxxx try this one
https://youtu.be/g3ZBYmjUo-Y
ULJM06024 = true in PSP\SYSTEM\compat.ini

**Closed** 2023-11-03 14:33 UTC
Labels: I/O
