### ISSUE TITLE
Resistance Retribution crashing

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#11310] opened 2018-08-18 21:43 UTC
I am using the v1.6.3-352-gec5b0c21a on a 64 bit system, the resistance retribution keeps crashing randomly well at least after i changed the clock speed to 222 it doesn't crashes in game anymore but after the level is over it crashes quite a lot (almost every level).

I got logs for two instances 

[log.zip](https://github.com/hrydgard/ppsspp/files/2299873/log.zip)

**Comment by unknownbrackets** [comment] 2018-08-18 22:41
This issue is being closed as a duplicate of #4626.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-08-18 22:41 UTC
