### ISSUE TITLE
IR Interpreter rendering issues

### ISSUE THREAD

**Issue by soopsfiya** [hrydgard/ppsspp#11212] opened 2018-06-24 18:08 UTC
Hi!

I launched MGS:PW with JIT enabled because everyone said that it is a massive performance improvement, but PPSSPP crashed every time I opened Metal Gear Solid: Peace Walker, so I decided to use IR Interpreter instead, and everything was fine, great performance etc., except that the player model and enemy models (so basically every moving entity in the game) was a huge black "stretch" across the map. Using regular Interpreter renders the models just fine, but the performance is significantly worse.
I am using an iPad Mini 4 with the latest version of PPSSPP and iOS.
Please help!

Edit: forgot to mention that my device is not jailbroken.

**Comment by unknownbrackets** [comment] 2018-06-24 19:56
This issue is being closed as a duplicate of #10650.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-06-24 19:56 UTC
