### ISSUE TITLE
Syphon Filter Logan Shadow Auto Crashed

### ISSUE THREAD

**Issue by Suzerainity** [hrydgard/ppsspp#13013] opened 2020-06-08 13:53 UTC
On Mission: Canyon Storm

First:

When Gabe Logan calls for fire on tank to destroy the barricade. Automatically force crashed. 

Second:

When Gabe Logan told his comrade with tank to back because the bridge will explode with the setup of the bombs. When exploded, automatically force crashed.

Phone used: Realme 5 Pro 8 GB RAM/SD712

**Comment by Gamemulatorer** [comment] 2020-06-16 09:56
A logcat is usefull for crash issue

**Comment by Gamemulatorer** [comment] 2020-06-22 12:34
@Suzerainity no feedback/outdated?

**Comment by hrydgard** [comment] 2020-10-08 07:48
Duplicate of #10415

**Closed by hrydgard** 2020-10-08 07:48 UTC
