### ISSUE TITLE
ppsspp

### ISSUE THREAD

**Issue by dilmanr** [hrydgard/ppsspp#8151] opened 2015-11-03 15:32 UTC
Play games for ppsspp open gaem crash ppsspp😔😔😔😔😔new updaty no fix ppsspp

**Comment by GAMELASTER** [comment] 2015-11-03 16:01
Slovák?/Čech? Ak áno, popíšte váš problém viac, napr. aká hra, počítač/android a podobne.

Please, provide more information!

**Comment by unknownbrackets** [comment] 2015-11-03 16:02
Most likely this is iOS related, so I'm just going to close as a duplicate of #8122.  Even if it isn't, we need to know the device, game, etc.  If you respond with that information, I'll reopen.

-[Unknown]

**Closed by unknownbrackets** 2015-11-03 16:02 UTC
