### ISSUE TITLE
Black screen on Launch if closed from multitask in ios

### ISSUE THREAD

**Issue by MurakumoMobiusFF** [hrydgard/ppsspp#11998] opened 2019-04-26 10:08 UTC
### What happens?
If closed within app “close button” it works fine but if closed from multitasking the game gets (traped?) in Command line being shown as running foreground. When I try to open ppsspp then the only thing I get is a black screen.

### What *should* happen?
Should close normally

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhone 8 Plus, ios 12.1.1 beta3, ppsspp dev latest from official repo

**Comment by MurakumoMobiusFF** [comment] 2019-04-26 10:12
I am currently at work but when I get home I will upload a video to yt so people can see what I mean.

**Comment by unknownbrackets** [comment] 2019-04-26 13:24
This issue is being closed as a duplicate of #9186.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-04-26 13:24 UTC
