### ISSUE TITLE
xBRZ does not work in Angus hates Aliens

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8012] opened 2015-09-28 02:42 UTC
Since https://github.com/hrydgard/ppsspp/pull/7870

v1.0.1-2656-gd34219e
![01](https://cloud.githubusercontent.com/assets/3481559/10126970/7519a69c-65cd-11e5-94a7-078b9a708211.png)

v1.0.1-2668-g253ed9f
![02](https://cloud.githubusercontent.com/assets/3481559/10126972/751ab0e6-65cd-11e5-9b09-7784f04996d7.png)

**Comment by daniel229** [comment] 2015-09-28 02:45
Oh,it works after 18 seconds

**Comment by daniel229** [comment] 2015-09-28 02:54
Other things like the Aliens still not get the xbrz effect even wait for a few minutes
![03](https://cloud.githubusercontent.com/assets/3481559/10127084/4dccf5a6-65cf-11e5-88f3-5be1995085fd.png)

**Comment by unknownbrackets** [comment] 2015-09-28 03:33
Does anything change if you comment out this line?

https://github.com/hrydgard/ppsspp/pull/7870/files#diff-5ce09ad7d00cb20e6759a64a887cce54R794

Commenting out that line should disable that pull request's affect on xBRZ.

-[Unknown]

**Comment by daniel229** [comment] 2015-09-28 03:38
works fine.

**Comment by unknownbrackets** [comment] 2015-09-28 04:00
Maybe that means this game is using a sprite sheet or something?

What if you log when it does it?  Change:

```c++
h = std::max(272, (int)entry->maxSeenV);
```

To:

```c++
h = std::max(272, (int)entry->maxSeenV);
NOTICE_LOG(HLE, "[%d] Changed h 512->%d, w=%d", gpuStats.numFlips, h, w);
```

It should theoretically make xBZR happen more, not less... hmm.

-[Unknown]

**Comment by daniel229** [comment] 2015-09-28 04:06
The log like this.
```
04:10:558 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1464] Changed h 512->313, w=512
04:10:558 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1464] Changed h 512->486, w=512
04:10:558 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1464] Changed h 512->486, w=512
04:10:558 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1464] Changed h 512->350, w=512
04:10:559 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1464] Changed h 512->486, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->272, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->272, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->272, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->272, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->313, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->313, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->486, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->313, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->486, w=512
04:10:575 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->486, w=512
04:10:576 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->350, w=512
04:10:576 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1465] Changed h 512->486, w=512
```

**Comment by unknownbrackets** [comment] 2015-09-28 04:30
Hmm - sorry, to be sure, could you make it:
NOTICE_LOG(HLE, "[%d] %08x Changed h 512->%d, w=%d", gpuStats.numFlips, addr, h, w);

Not sure if those are all the same texture...

-[Unknown]

**Comment by daniel229** [comment] 2015-09-28 04:37
Okay.
```
36:21:337 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1098] 08bcbe40 Changed h 512->486, w=512
36:21:353 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 0984bf00 Changed h 512->272, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 0984bf00 Changed h 512->272, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 0984bf00 Changed h 512->272, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 0964bf00 Changed h 512->272, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ecbe40 Changed h 512->313, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ecbe40 Changed h 512->313, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ccbe40 Changed h 512->486, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ecbe40 Changed h 512->313, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08bcbe40 Changed h 512->486, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ccbe40 Changed h 512->486, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08dcbe40 Changed h 512->350, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08bcbe40 Changed h 512->486, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 0984bf00 Changed h 512->272, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 0984bf00 Changed h 512->272, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 0984bf00 Changed h 512->272, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 0964bf00 Changed h 512->272, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08ecbe40 Changed h 512->313, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08ecbe40 Changed h 512->313, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08ccbe40 Changed h 512->486, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08ecbe40 Changed h 512->313, w=512
36:21:370 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08bcbe40 Changed h 512->486, w=512
36:21:371 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08ccbe40 Changed h 512->486, w=512
36:21:371 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08dcbe40 Changed h 512->350, w=512
36:21:371 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1100] 08bcbe40 Changed h 512->486, w=512
```

**Comment by unknownbrackets** [comment] 2015-09-28 05:11
Thanks.  This is a bug, it's not supposed to do this:

```
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ccbe40 Changed h 512->486, w=512
36:21:354 user_main    N[HLE]: GLES\TextureCache.cpp:795 [1099] 08ecbe40 Changed h 512->313, w=512
```

Grr, hmm.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-09-28 06:27
You know, if maxSeenV is > 272, maybe we round to the nearest 64 or 128.  I think this game is going from e.g. 400 to 450, 480, etc.  It's not so bad but the hash fails are delaying scaling.  The main goal of maxSeenV is to detect when 512 or etc. is too much by like >= 30%.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-09-28 06:31
How about this:

```c++
			if (gstate.isModeThrough()) {
				u16 lastMaxV = nextTexture_->maxSeenV;
				nextTexture_->maxSeenV = std::max(nextTexture_->maxSeenV, gstate_c.vertBounds.maxV);
				// Reduce the chances of small differences.
				if (lastMaxV != nextTexture_->maxSeenV && nextTexture_->maxSeenV > 272) {
					static const u16 V_ROUND_TO = 64;
					nextTexture_->maxSeenV = ((nextTexture_->maxSeenV + V_ROUND_TO - 1) / V_ROUND_TO) * V_ROUND_TO;
				}
			} else {
```

In place of:

```c++
			if (gstate.isModeThrough()) {
				nextTexture_->maxSeenV = std::max(nextTexture_->maxSeenV, gstate_c.vertBounds.maxV);
			} else {
```

-[Unknown]

**Comment by daniel229** [comment] 2015-09-28 06:57
Some still not work
full log
https://gist.github.com/daniel229/e5bc957ebd0fcd60aadc

**Comment by unknownbrackets** [comment] 2015-09-30 03:53
How about:

```c++
			if (gstate.isModeThrough()) {
				nextTexture_->maxSeenV = std::max(nextTexture_->maxSeenV, gstate_c.vertBounds.maxV);
				// If it's above 400, it's likely using the entire thing.
				//  We're trying to detect, primarily, 272 or 320 tall textures that round to 512.
				if (nextTexture_->maxSeenV && nextTexture_->maxSeenV > 400) {
					nextTexture_->maxSeenV = 512;
				}
			} else {
```

In place of:

```c++
			if (gstate.isModeThrough()) {
				nextTexture_->maxSeenV = std::max(nextTexture_->maxSeenV, gstate_c.vertBounds.maxV);
			} else {
```

Not sure if that's terribly clean, but we really are after textures that are shorter than 400 here.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-09-30 03:57
Alternatively, maybe we rely more on the max texels per frame and juts disable the frequency check.

Meaning, change:

```c++
	if (scaleFactor != 1 && (entry->status & TexCacheEntry::STATUS_CHANGE_FREQUENT) == 0) {
```

To:

```c++
	if (scaleFactor != 1) {
```

And also:

```c++
	if (scaleFactor > 1 && (entry.status & TexCacheEntry::STATUS_CHANGE_FREQUENT) == 0)
```

To

```c++
	if (scaleFactor > 1)
```

Is this slow at all?  Any dropped frames anywhere, with high settings, compared to before?  I'm worried it could hurt performance in some areas where textures constantly change, in other games... hmm.

-[Unknown]

**Comment by daniel229** [comment] 2015-09-30 04:17
Apply all these changes,still not help all the texture.some texture need a few seconds to take the effect.Speed seems the same as before.

**Comment by unknownbrackets** [comment] 2015-12-30 22:16
Does it come back sooner now?

-[Unknown]

**Comment by daniel229** [comment] 2015-12-31 00:08
No effect and even waitting.
![3](https://cloud.githubusercontent.com/assets/3481559/12059416/ae064ed0-af95-11e5-8b9e-fbe76379b7fe.png)

**Comment by unknownbrackets** [comment] 2015-12-31 00:39
Darn, sorry.  Typos suck.  Can you try with 1072028ef54a2a32d6a112d01f9f7e6bc499fc53.

-[Unknown]

**Comment by daniel229** [comment] 2015-12-31 00:45
Looks like it take 1 second to get the effect now.

**Comment by unknownbrackets** [comment] 2015-12-31 00:48
Maybe the right solution here is to:

1. Disable the texture height optimization the moment the detected height CHANGES, and just swap to the full height.
2. Not count this as a "change" per the "frequently changing" counter.

That would allow the optimization to still improve things, but not have that major an impact here (well, one extra upload.)

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-12-31 01:20
Did that in #8340.

-[Unknown]

**Comment by daniel229** [comment] 2015-12-31 01:31
Still not help it.

**Comment by unknownbrackets** [comment] 2015-12-31 01:48
So it still takes 30 frames?  If you comment out this line entirely, it works?

```c++
h = std::max(272, (int)entry->maxSeenV);
```

I can't imagine what else would be preventing scaling right away, unless it really IS changing each frame.  But then it's not #7870's fault...

-[Unknown]

**Comment by daniel229** [comment] 2015-12-31 02:07
Not working.
but it works fine in v0.9.8-320-gd67f91d , v0.9.9.1-54-gdfbb0bd not

**Comment by unknownbrackets** [comment] 2015-12-31 02:23
Well, maybe the textures simply are changing then.  I think 1 second delay is not really that bad, if they are.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-01-23 02:44
Does it help if you find this:

```c++
					// Let's not hash less than 272, we might use more later and have to rehash.  272 is very common.
					nextTexture_->maxSeenV = std::max((u16)272, gstate_c.vertBounds.maxV);
```

And add after:

```c++
					nextTexture_->status |= TexCacheEntry::STATUS_FREE_CHANGE;
```

Maybe I should ideally recalc the hash there or defer until there...

-[Unknown]

**Comment by daniel229** [comment] 2016-01-23 02:49
No,it doesn't.

**Comment by daniel229** [comment] 2016-01-23 02:53
but,the effect applys faster than before

**Comment by unknownbrackets** [comment] 2016-05-22 07:41
How is it now compared to before?  I think some delay should be expected when a lot of things are scaled.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-04-11 04:37
I think we made some improvements here.  I'm going to mark the remaining as a duplicate of #1934.

-[Unknown]

**Closed by unknownbrackets** 2020-04-11 04:37 UTC
Labels: No Feedback / Outdated?
