### ISSUE TITLE
RetroArch: Crash on save and resolution change

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [hrydgard/ppsspp#11253] opened 2018-07-15 00:22 UTC
When compiled as libretro core if a savestate slot is occupied often PPSSPP crashes when saving the current state instead of saving it.
Also crashes when the game resolution is changed while in game from the core options and the game is resumed from the core menu.
Using Debian GNU/Linux 9 with kernel Linux 4.9.0 64bit

**Comment by orbea** [comment] 2018-11-14 21:58
I can reproduce the resolution change on Linux, I think its related to issue https://github.com/hrydgard/ppsspp/issues/10784.

**Comment by hrydgard** [comment] 2019-02-26 11:29
Should be better now, at least some cases.

**Comment by killerz298** [comment] 2019-11-09 18:54
This is still occurring for me using the Shield.

**Comment by fr500** [comment] 2019-11-09 18:57
it can't possibly happen now because the change now requires a restart

**Comment by killerz298** [comment] 2019-11-09 20:27
> 
> 
> it can't possibly happen now because the change now requires a restart

Perhaps my comment shouldn't have gone in this thread. I'm using Retroarch on Shield. When I save the game state using PPSSPP, it crashes (there is another post on this issue). Also, when I change resolution, and I go to resume the game (or go to restart), it also crashes.

**Comment by klepp0906** [comment] 2019-11-22 21:59
not sure why there would be a "resolution" change so my issue might be something separate alltogether, but whenever i load a game from a playlist, then enter the RA menu, it crashes RA.

sometimes I can get into the menu, but then when resuming the game it crashes RA.  tried vulkan and glcore

**Comment by unknownbrackets** [comment] 2020-03-08 20:21
#12338 seems to cover the save state issue.  Is this otherwise different from #10784?

It sounds like any crashing when accessing the menu is a separate issue.

-[Unknown]

**Comment by klepp0906** [comment] 2020-03-08 20:52
this was a ways back, but i think i posted this before i found out the root of the issue.

this was my issue https://github.com/libretro/RetroArch/issues/9773

and what it led me to 

https://github.com/libretro/RetroArch/issues/9787

**Comment by unknownbrackets** [comment] 2020-03-08 21:10
Okay, in that case I'm going to close this as it seems to be covered by issues in libretro / retroarch and issues that are already open.

-[Unknown]

**Closed by unknownbrackets** 2020-03-08 21:10 UTC
Labels: Libretro
