### ISSUE TITLE
Implement lamb 0.3.2 into PPSSPP

### ISSUE THREAD

**Issue by jacobparkinson1109** [hrydgard/ppsspp#7853] opened 2015-07-06 14:04 UTC
Hey, would it be possible or not to implement the "lamb" plugin into PPSSPP because it would give the emulator the functionality to export a scene of the game into an obj file for blender renders.
If you could do this I would greatly appreciate this for my school project, I want to render some phantasy star portable models.

Thanks. (I can provide the source code if you want.)

**Comment by hrydgard** [comment] 2015-07-06 14:08
"lamb" plugin? You're gonna have to explain better or provide an URL...

It's not trivial to export emulator scenes to 3ds files or similar as there's no real indicator of where one object begins and another one ends, but I suppose just exporting the whole scene and having the user clean it up may not be too bad. It's quite a bit of work, however, and not something I'm going to do anytime soon. Pull requests accepted. Best method may be to implement a special GPU backend that writes the scene to a file, save state the scene you want, switch to the new GPU backend and there you go.

**Comment by jacobparkinson1109** [comment] 2015-07-06 14:52
Okay, here it is. http://wololo.net/downloads/index.php/download/7925
It is a PRX plugin, but if you could find away to put it in it would be awesome.

**Comment by Bigpet** [comment] 2015-07-06 17:36
@jacobparkinson1109 jpcsp has the "dump scene to *.obj" function

**Comment by jacobparkinson1109** [comment] 2015-07-07 13:42
@Bigpet It does not work unless the game is running at full speed, besides I would rather go with the better emulator thanks.

**Comment by Bigpet** [comment] 2015-07-07 15:27
@jacobparkinson1109 alright, I don't understand but whatever. Just so you know it's unlikely to happen in the near future, so if you *need* to use ppsspp and you have a deadline for this project then you're probably going to need external tools like GLIntercept or 3D Ripper DX.

**Comment by GAMELASTER** [comment] 2015-07-07 22:06
If u want a dump a scene, just start a PPSSPP in DirectX mode and use:
http://www.deep-shadows.com/hax/3DRipperDX.htm
enjoy ^^

**Comment by jacobparkinson1109** [comment] 2015-07-09 21:18
@GAMELASTER Sorry bro, that software is unsafe. It has a virus, ever since it busted my last computer I've been using kaspersky antivirus ever since. Scanned that exe and it is got several threats detected.

**Comment by GAMELASTER** [comment] 2015-07-10 16:02
Well, i use this so much time and i got a ESET and never it something detected... :-) You really downloaded that tool from good site?

**Comment by Bigpet** [comment] 2015-07-10 19:19
@GAMELASTER it really depends on the anti virus software, some detect any software that hooks into other processes as a "potential threat". The way dumping the models by injecting in-between ppsspp and DX works can be seen as malicious by some security software. I guess it's best to see what it actually "found".

**Comment by jacobparkinson1109** [comment] 2015-07-12 00:19
IT HAD A TROJAN.
Look PRX is a psp executable which ppsspp can run, but it does not run them
as plugins.
Lamb, is a psp plugin that exports a scene as an obj.
God dam.

**Comment by unknownbrackets** [comment] 2015-07-12 07:09
Umm, psp plugins generally do have prx extensions.  They include executable code and sure, it's possible for one to contain a virus in MIPS code.  I would be very surprised if any virus scanner was able to detect PSP viruses but that doesn't mean they can't exist.

But I think the virus was detected in a download for 3D Ripper DX, which is not actually related to psps or prx files directly.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-12-20 04:26
I'm going to mark this as a duplicate of #2825.  Implementing kernel plugins is also a good amount of work, so I think if someone wants to try to export the scene they can do it however they want.

-[Unknown]

**Closed by unknownbrackets** 2015-12-20 04:26 UTC
