### ISSUE TITLE
[Direct3D]Kao Kangaroo / Asterix & Obelix XXL:Mission WiFix - BSOD after HOSTING Ad-Hoc server - 1.11

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#14103] opened 2021-02-10 11:36 UTC
### What happens?
When Direct3D / PC is host for Ad-Hoc modes in these 2 games,game goes BSOD,leaving Ad-Hoc up and running.However,BSOD **DOES NOT APPEAR** if Android / OpenGL Device is host in Ad-Hoc mode,so i think this is
more graphical bug.Game if hosted second way works without problem,thank you DEVS

Bug also wasn't also present at the previous versions i tested.

Also it is my guess since these 2 games have similliar developers,and actually share literally same engine,so maybe you should look at that too to resolve any possible bugs in the future

### What *should* happen?
PPSSPP should not go BSOD after resolving Ad-Hoc mode

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.

Phone:
Honor 9S
OpenGL - backend
- GPU - PowerVR GE8320
- CPU - Mediatek MT6762 Helio P22

PC:
Direct3D 11
- CPU - Intel Pentium N3520
- GPU - Intel HD Graphics

**BOTH PHONE AND PC ARE CURRENTLY NEWEST BUILD**

DUMP:
[ULUS10085_0001.zip](https://github.com/hrydgard/ppsspp/files/5957841/ULUS10085_0001.zip)

SCREENSHOT:
![Izrezak](https://user-images.githubusercontent.com/67833785/107505136-8d9ed900-6b9c-11eb-8e34-e7b6bb77f71e.PNG)

Thanks in advance

**Comment by ANR2ME** [comment] 2021-02-10 15:13
Does it also happened when using OpenGL/Vulkan on PC?

**Comment by ANR2ME** [comment] 2021-02-10 19:24
Okay i was able to reproduce this blue screen on KaoChallengers, it seems to run at 0/0 FPS/VPS.
And this is the network Logs at the time this blue screen occurred:
```
16:09:741 user_main    W[SCENET]: HLE\sceNetAdhoc.cpp:4709 UNTESTED sceNetAdhocMatchingStart(1, 16, 8192, 16, 8192, 136, 08c01ddc) at 08ac04c8
16:09:741 user_main    I[SCENET]: HLE\sceNetAdhoc.cpp:1219 sceNetAdhocPdpCreate(00:02:02:02:02:02, 1, 1024, 0) at 08ac04c8
16:09:741 user_main    D[SCENET]: HLE\sceNetAdhoc.cpp:1319 00000001=sceNetAdhocMatchingStart(1, 16, 8192, 16, 8192, 136, 08c01ddc): success
16:09:741 user_main    I[SCENET]: HLE\sceNetAdhoc.cpp:6953 EventLoop: Begin of EventLoop[1] Thread
16:09:742 idle0        I[SCENET]: HLE\sceNetAdhoc.cpp:7099 InputLoop: Begin of InputLoop[1] Thread
16:09:742 idle0        D[SCENET]: HLE\sceNetAdhoc.cpp:6003 HELLO Dump:
          00000000  41 7a 75 6b 61 00 00 00 00 00 00 00 00 00 00 00  Azuka...........
          00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000030  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000040  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
          00000080  01 00 00 00 04 00 00 00                          ........
16:09:770 user_main    D[SCENET]: HLE\sceNet.cpp:694 0=sceNetGetLocalEtherAddr(08ff4f7a)
16:09:770 user_main    D[SCENET]: HLE\sceNet.cpp:715 sceNetEtherNtostr(08ff4f7a, 09fbf8bc) at 08abd0f8
16:09:770 user_main    I[SCENET]: HLE\sceNetAdhoc.cpp:1219 sceNetAdhocPdpCreate(00:02:02:02:02:02, 29752, 16384, 0) at 08abd188
16:09:770 user_main    D[SCENET]: HLE\sceNetAdhoc.cpp:1319 00000002=sceNetAdhocPdpCreate(, 29752, 16384, 00000000): success
16:09:770 user_main    D[SCENET]: HLE\sceNet.cpp:694 0=sceNetGetLocalEtherAddr(08ff4fa2)
16:09:770 user_main    D[SCENET]: HLE\sceNet.cpp:715 sceNetEtherNtostr(08ff4fa2, 09fbf88c) at 08abd0f8
16:09:770 user_main    I[SCENET]: HLE\sceNetAdhoc.cpp:1219 sceNetAdhocPdpCreate(00:02:02:02:02:02, 29753, 8192, 0) at 08abd188
16:09:770 user_main    D[SCENET]: HLE\sceNetAdhoc.cpp:1319 00000003=sceNetAdhocPdpCreate(, 29753, 8192, 00000000): success
16:09:771 pingServer   D[SCENET]: HLE\sceNetAdhoc.cpp:1621 sceNetAdhocPdpRecv(3, 000002A189D8BE38, 000002A189D8BE3E, 000002A189D8BE50, 000002A189D8BE34, 0, 0) at 08abd6a4
16:09:771 user_main    D[SCENET]: HLE\sceNetAdhoc.cpp:490 sceNetAdhocPdpRecv[3]: Socket Error (10045)
16:09:771 user_main    D[SCENET]: HLE\sceNetAdhoc.cpp:906 Returning (ThreadId: 345, WaitID: 3408, error: 0) Result (80410715) of sceNetAdhoc[6] - SocketID: 3
16:14:829 pingServer   D[SCENET]: HLE\sceNetAdhoc.cpp:6003 HELLO Dump:
```
Looks like that socket error 10045 (WSAEOPNOTSUPP/Operation not supported.) is the cause.

@EX-e-LD
May i know what Port Offset value you are using to play this?
This games seems to use a high port number (ie.29xxxx)
So if your Port Offset value is too high, when added to the game port, it could ended exceeding the 65535 port value limit.

**Comment by ANR2ME** [comment] 2021-02-10 20:23
@EX-e-LD Try the game again after PR https://github.com/hrydgard/ppsspp/pull/14106 got merged

**Closed** 2021-02-11 11:44 UTC
Labels: Networking / adhoc
