### ISSUE TITLE
Support XMB dashboard from psp

### ISSUE THREAD

**Issue by proganime1200** [hrydgard/ppsspp#14409] opened 2021-04-25 07:06 UTC
### What should happen?
Adds or supports booting XMB dashboard on ppssp like in jpcsp

### Who would benefit from it?
Kinda nostalgia to see the dashboard boot reminds mmus of those old times

**Comment by Panderner** [comment] 2021-04-25 08:13
According @unknownbrackets' comment in #14286:

> If you want to build it, perhaps it'll be considered as an addition. However, the XMB really doesn't lend itself to the range of devices PPSSPP is run on - especially touch controlled devices.

> If we tried to run the original XMB in PPSSPP, I guarantee it would also crash a lot and stuff. The XMB uses a huge library of internal features of the PSP firmware that we don't emulate - it's a silly amount of work for a smally nostalgia trip that can mostly be satisfied using YouTube.

> That said, if you're really excited to devote countless hours of your life to getting the XMB working - all the power to you. I'm sure a handful of people will be really happy and spend about 5 minutes looking at it before going back to better UI, and those people will surely thank you.

So it's a duplicate of #14286.

**Comment by LunaMoo** [comment] 2021-04-25 08:19
Closing as explained above. XMB is neither good nor easy to support and not worth bothering with in high level, multi platform emulator like PPSSPP.

**Closed by LunaMoo** 2021-04-25 08:19 UTC
