### ISSUE TITLE
Soul Calibur BD Versus Black screen Android

### ISSUE THREAD

**Issue by cmrhere2play** [hrydgard/ppsspp#7298] opened 2015-01-09 05:32 UTC
not sure if this was fixed but I get a black screen every time I go to versus on android but i know something is working behind the scenes

**Comment by unknownbrackets** [comment] 2018-08-25 19:34
Is this only when playing with networking, or is this even single player?  I'm not familiar with the game.

People have reported that the game runs perfectly on some devices with some settings:
https://report.ppsspp.org/game/ULUS10457_1.00

I'm going to close this, assuming it has already been fixed.  If that's wrong - please reply to this issue and post a log or more information.  I'd also suggest checking the settings in the link above of the people who had no problems to see if it might be caused by a setting.

-[Unknown]

**Closed by unknownbrackets** 2018-08-25 19:34 UTC
Labels: Platform-specific (Android)
