### ISSUE TITLE
Audio Issue

### ISSUE THREAD

**Issue by JohnW1ck** [hrydgard/ppsspp#8684] opened 2016-04-08 04:25 UTC
Theres something wrong with the sound,it seems to lag horrifically and can almost to not even hear the sound because it lags, I am jailbroken on ios 9 playing Dragon Ball Z:Shin Budokai on an iphone 5s and before this issue never happened the sound was nearly perfect or somewhat acceptable but now its terrible.

**Comment by Anuskuss** [comment] 2016-04-08 05:00
JIT (huge speed improvment) isn't availible on iOS9 64bit devices, so your sound may was better before iOS9 (#8122).

**Comment by unknownbrackets** [comment] 2016-04-08 05:54
Right - this is just a performance issue and duplicate of #8122.

I wouldn't hold my breath for Apple to change their policies any time soon, but if something does happen, it'll be mentioned in #8122 (you can hit subscribe on the right side.)  Closing this.

-[Unknown]

**Closed by unknownbrackets** 2016-04-08 05:54 UTC

**Comment by JohnW1ck** [comment] 2016-04-08 13:06
No ive been on ios 9.0.2 and the sound was always better than what it is now.It was near perfect on ios 9 jailbroken and idk if a update somehow broke the sound or if its my file thats broken but it sounds like crap now

**Comment by unknownbrackets** [comment] 2016-04-09 02:26
It's going to sound terrible if it's slow.  You can try resetting your settings to defaults, in case it's related to a setting you've recently changed.

Ultimately, performance is always going to be a lot worse than other platforms on 64-bit iOS 9 devices, until that issue noted above is fixed.  That means audio will sometimes sound terrible.

-[Unknown]
