### ISSUE TITLE
Monster Hunter Portable 3rd Graphical issue

### ISSUE THREAD

**Issue by PepeJulio** [hrydgard/ppsspp#11635] opened 2018-12-04 06:15 UTC
### What happens?

At least the Tundra presents this flickering glitch that seems like a reverse z issue to me. Tested on other areas, but so far Tundra is the only one that presents it.
http://imgur.com/l5CunZD

### What *should* happen?

There shouldn't be any glitch of this kind as my ISO is definitely not the problem after testing with previous versions.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android, Xperia XA with Mediatek Helio P10 processor and Mali T-860 GPU. The glitch presents itself exactly the same on both OpenGL and Vulkan. Build v1.7.1-200-g8e56c62c2 was the last one working. The next one, v1.7.1-204-gd08a2eed6, already presents the glitch.

**Comment by Emulatorer** [comment] 2018-12-04 09:20
Already fixed by "GPU: Force use of indexes on cull mode flip" #11613
Also a duplicate issue of #11601

**Comment by unknownbrackets** [comment] 2018-12-04 13:45
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Emulatorer** [comment] 2018-12-04 17:31
@PepeJulio are you using the non-HD version of Monster Hunter 3rd Portable?

**Comment by PepeJulio** [comment] 2018-12-04 19:36
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/2645782/recording.ppdmp.zip)

Alright, there goes the dump. And no, I'm using HD version.

**Comment by Emulatorer** [comment] 2018-12-06 06:34
Wierd I didn't have issue in the latest gitbuild 1.7.1-243
### My Screenshot
![screenshot_2018-12-06-14-24-15](https://user-images.githubusercontent.com/37603562/49565935-f3133180-f963-11e8-9d95-a6227413a43d.png)
### Your Screenshot
![photogrid_1544077509345](https://user-images.githubusercontent.com/37603562/49565949-06260180-f964-11e8-98a4-78d75b411a1e.jpg)

**Comment by Emulatorer** [comment] 2018-12-06 06:35
Wierd I didn't have issue in the latest gitbuild 1.7.1-243
### My Screenshot
![screenshot_2018-12-06-14-24-15](https://user-images.githubusercontent.com/37603562/49565935-f3133180-f963-11e8-9d95-a6227413a43d.png)
### Your Screenshot
![photogrid_1544077509345](https://user-images.githubusercontent.com/37603562/49565949-06260180-f964-11e8-98a4-78d75b411a1e.jpg)

**Comment by PepeJulio** [comment] 2018-12-09 05:11
Look, there's more on the island: 
![screenshot_20181209-000857](https://user-images.githubusercontent.com/29497075/49693641-c3704f00-fb46-11e8-890a-1e2503740077.png)


![screenshot_20181209-000849](https://user-images.githubusercontent.com/29497075/49693648-d4b95b80-fb46-11e8-9bae-f7fac9740fd5.png)

**Comment by PepeJulio** [comment] 2018-12-09 05:11
Happens in places with water, I guess?

**Comment by PepeJulio** [comment] 2018-12-09 05:31
Oh, and it seems that the island glitch was present even before the culling changes in 1.7.1-204;  took these screenshots in  v1.7.1-200-g8e56c62c2. Who knows when it started... I'll try to narrow it.

**Comment by PepeJulio** [comment] 2018-12-09 06:01
Alright, the last completely working build was v1.6.3-468-gad6938de5
![screenshot_20181209-005808](https://user-images.githubusercontent.com/29497075/49693919-e5b99b00-fb4d-11e8-9c53-597308d2dd4f.png)

after that, you guys merged some range culling changes and the glitch appeared.

**Comment by Emulatorer** [comment] 2018-12-09 06:46
Yep maybe because of #11393

**Comment by Gamemulatorer** [comment] 2021-05-17 16:06
Using your ge dump 🤔
Both OpenGL and Vulkan
![Screenshot_2021-05-18-00-04-52-496_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118520609-c7b7e200-b76c-11eb-8a80-5b5a7abb3a18.jpg)
![Screenshot_2021-05-18-00-04-34-701_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118520654-cedef000-b76c-11eb-97a5-ab13aa75171a.jpg)
My phone is Redmi Note 9

**Comment by unknownbrackets** [comment] 2021-05-23 18:36
That's exactly how this dump looks on a PSP:
![ULJM05800_#11635_monster_hunter_culling](https://user-images.githubusercontent.com/191233/119272439-b894c200-bbba-11eb-8ff4-2517bb5c8974.png)

This looks a lot like #11601, which might've affected the dump somehow.  Either way, if no one can reproduce this now outside the dump - we may want to close.  I feel like if graphics that bad were still happening, we'd be getting reports at least every week.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-05-24 05:05
ppsspp latest git build apk no gfx glitch in tundra place using my Redmi Note 9.

### OpenGL
![Screenshot_2021-05-24-13-03-18-173_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119298919-91a8bf80-bc90-11eb-91ad-bd89acfeff79.jpg)
![Screenshot_2021-05-24-13-02-55-534_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119298926-95d4dd00-bc90-11eb-9273-caed41557d80.jpg)
### Vulkan
![Screenshot_2021-05-24-13-02-14-710_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119298960-a2593580-bc90-11eb-9436-81f1ab98e13b.jpg)
![Screenshot_2021-05-24-13-01-43-187_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119298971-a5542600-bc90-11eb-89ab-64bbf1d3c502.jpg)

**Comment by Gamemulatorer** [comment] 2021-08-23 15:57
@PepeJulio can still reproduce this issue on the latest git build of ppsspp?

**Comment by PepeJulio** [comment] 2021-08-23 16:13
I sadly don't have the troublesome phone in my posession anymore, and haven't tried it on my S9+ Snapdragon, but as [Unknown] said, the issue might be completely outdated by this point. It always seemed more like a Mali driver issue anyway, so I don't think many people, if at all, will be able to reproduce it.

**Comment by Gamemulatorer** [comment] 2021-08-23 16:23
> It always seemed more like a Mali driver issue anyway, so I don't think many people, if at all, will be able to reproduce it.

My Redmi Note 9 GPU is Mali but I cannot reproduce this :)

**Comment by PepeJulio** [comment] 2021-08-23 16:30
I meant it more in "old 2016 mid-lowrange Mali gpu with buggy drivers" fashion, but yeah, the point still stands. It seemed weirdly device-specific.

**Comment by hrydgard** [comment] 2021-08-23 17:41
Yeah, probably not much to do about this. Closing.

**Closed by hrydgard** 2021-08-23 17:41 UTC
Labels: No Feedback / Outdated?
