### ISSUE TITLE
Update Multithreading to improve perfomance and compatibility

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8112] opened 2015-10-26 14:16 UTC
Please update to using more than 2 core ( Mobile and PC at this time using 4 core and 8 core CPU ) , and improve compatibility games like Final Fantasy VII : Crisis Core and The 3rd Birthday , because they have issue is crash and texture glitch , you can see my picture , when i'm turn on multithreading , is have a bug texture
![bug ppsspp](https://cloud.githubusercontent.com/assets/11285640/10731201/c8e4a078-7c26-11e5-8387-0a7e64f443eb.png)

**Comment by SukharevAndrey** [comment] 2015-10-26 21:54
Dolphin devs wrote good explanation why their emulator use only 3 cores: https://dolphin-emu.org/docs/faq/#couldnt-dolphin-use-more-my-cpu-cores-go-faster
Almost the same applies to PPSSPP

**Comment by unknownbrackets** [comment] 2015-10-27 05:38
Right, there's nothing actionable here.  If you want to propose a plan for how to use more cores or spread out work (without just causing more stalls and making it slower), we're listening.  But as it is, the current issues in multithreading are caused by timing.  We already know this, and the only way to fix it would be to add more stalls - which would make it much slower, possibly even slower than when the option is off.

@hrydgard already did some initial work on a vastly different approach to threading the GPU, which is likely to have less timing issues.  But it remains to be seen if this will actually yield gains.  I've also tried to offload heavy things - like texture processing - to other cores but without success: it just introduces stalls and makes things no better.

It's possible that the different approach, which will take time to implement, will introduce a new and faster multithreading.  It's also very possible that Vulkan may allow us a lot of gains and to use a lot more cores.

But those are all separate efforts, and keeping this open won't help us with them.  I'm closing this.

-[Unknown]

**Closed by unknownbrackets** 2015-10-27 05:38 UTC

**Comment by zminhquanz** [comment] 2016-06-08 14:02
When enable multithread , is can't execute and busy

- [ 59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:146 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:147 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:148 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:149 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:150 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks
59:59:151 user_main    D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 13042 ticks]

**Comment by zminhquanz** [comment] 2016-06-08 14:20
this is ge debugger and disassembly
![image](https://cloud.githubusercontent.com/assets/11285640/15897462/c0274cb6-2dbe-11e6-9e74-3c80a84bc8ef.png)
