### ISSUE TITLE
Mahou Shojo Madoka Magica: Problem 2

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#7636] opened 2015-03-27 06:52 UTC
Hi again, well, i follow the other post of this game for the problems, but still i can't play tha game, i do a new isuue because the log is different this time, but equally has a segmentation fault. This happend finishing the first chapter.

tested in PPSSPP SDL version v1.0.1-221-g62e621f

log: https://gist.github.com/latot/53bf028cca610d210afe

Thx

**Comment by sum2012** [comment] 2015-03-27 11:15
Can you upload the game save to https://drive.google.com ?

**Comment by latot** [comment] 2015-03-27 13:41
https://drive.google.com/file/d/0B6Z4V8__Ve6rRFgzWFk3Z3ZXMWc/view?usp=sharing

Here is the save, and i'm using a english path in the iso.. i don't know if that can be the cause.

Thx

**Comment by sum2012** [comment] 2015-03-27 14:05
I am using Japan iso.
Don't crash but forever load if I use your save status.
But I find it crash before go to school from start.

**Comment by latot** [comment] 2015-12-13 22:37
Hi, more logs, logs
[Hi.txt](https://github.com/hrydgard/ppsspp/files/60634/Hi.txt)

**Comment by latot** [comment] 2015-12-14 00:52
Hi, now i get a simple way to patch this, disabling fast memory in system options.

**Comment by unknownbrackets** [comment] 2015-12-29 17:43
Does this still happen with fast memory enabled?

-[Unknown]

**Comment by latot** [comment] 2015-12-29 19:30
Yes D:

and i get htis message:

```
26:22:441 idle0        E[COMMON]: Common/FileUtil.cpp:254 CreateDir: mkdir failed on : No such file or directory
```
when the game start without system data and you create it, and a little question, is right this log?:

```
24:49:528 CRI FS File  E[FileSys]: FileSystems/DirectoryFileSystem.cpp:562 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
24:49:528 CRI FS File  E[IO]: HLE/sceIo.cpp:1280 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/psp/SAVEDATA/ULJS00430Install/INSTALL.DNS, 40004001, 000021a4) - file not found
```
(without system data)

Thx.

**Comment by unknownbrackets** [comment] 2015-12-29 19:45
Oh, `/psp/`.  It should be "auto fixing" that to `/PSP/`.  Does it help if you create a "psp" folder next to "PSP"?

I think the issue here is that the mkdir isn't auto-fixing.  Is there anything around the "mkdir" error when you change the log level (in dev tools) to DEBUG for all log types?  I'm wondering what's triggering that mkdir so we can fix it, it's probably not doing the case sensitivity fixing.

Linux is case sensitive, but Mac, Android, Windows, etc. are not.  That might explain why this is happening on SDL/Linux only.

Good catch.

-[Unknown]

**Comment by latot** [comment] 2015-12-29 20:14
Hi, i try make the psp folder but sadly any difference, and with debug and verbose logs i get the same D:

```
02:25:879 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 330=sceKernelCreateThread(CRI Server Manager, 088424dc, 00000020, 8192, 00000000, 00000000)
02:25:879 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(330, 4, 09fff390)
02:25:888 CRI FS File  E[FileSys]: FileSystems/DirectoryFileSystem.cpp:562 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
02:25:888 CRI FS File  E[IO]: HLE/sceIo.cpp:1280 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/psp/SAVEDATA/ULJS00430Install/INSTALL.DNS, 40004001, 000021a4) - file not found
02:25:931 user_main    I[UTIL]: HLE/sceUtility.cpp:289 sceUtilityLoadModule(769)
02:25:941 user_main    I[SCESAS]: HLE/sceSas.cpp:246 sceSasInit(08b348c0, 256, 32, 0, 44100)
02:25:941 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 336=sceKernelCreateThread(CsdThread, 08885844, 00000011, 1536, 00000000, 00000000)
02:25:941 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(336, 0, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 337=sceKernelCreateThread(CRI ADX Audio, 088b0338, 00000016, 24576, 00000000, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(337, 0, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 338=sceKernelCreateThread(CRI ADX File, 088b03b0, 00000018, 8192, 00000000, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(338, 0, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 339=sceKernelCreateThread(CRI Idle, 088b02c0, 00000032, 1024, 00000000, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(339, 0, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 340=sceKernelCreateThread(CRI Wave out, 088d5fe8, 00000010, 8192, 00000000, 00000000)
02:25:942 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(340, 0, 00000000)
02:25:945 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:1943 342=sceKernelCreateThread(SoundMain, 08887f24, 00000010, 4096, 00004000, 00000000)
02:25:945 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2014 0=sceKernelStartThread(342, 0, 00000000)
02:25:960 CRI FS File  E[FileSys]: FileSystems/DirectoryFileSystem.cpp:562 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
02:25:960 CRI FS File  E[IO]: HLE/sceIo.cpp:1280 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/psp/SAVEDATA/ULJS00430Install/INSTALL.DNS, 40004001, 000021a4) - file not found
02:25:999 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:420 Creating FBO for 00000000 : 480 x 272 x 1
02:25:011 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:420 Creating FBO for 00044000 : 480 x 272 x 1
02:36:089 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08e11f7c) - LIST (11)
02:36:089 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08e11f7c) : Game key (hex): 
02:51:650 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08e11f7c) - AUTOSAVE (1)
02:51:650 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08e11f7c) : Game key (hex): B0DCE35AE348726FB642F109DC7A5820
02:51:850 idle0        I[COMMON]: Common/FileUtil.cpp:226 CreateDir: directory 
02:51:850 idle0        E[COMMON]: Common/FileUtil.cpp:254 CreateDir: mkdir failed on : No such file or directory
02:51:851 idle0        I[COMMON]: Common/FileUtil.cpp:226 CreateDir: directory /home/pipe/.config/ppsspp/PSP/SAVEDATA/ULJS00430System
02:51:852 idle0        I[UTIL]: Dialog/SavedataParam.cpp:501 Saving file with size 39208 in ms0:/PSP/SAVEDATA/ULJS00430System/SYSTEM.DAT
```

But i found a weird thing, (again stating without system data), start the game, then it will say "don't exist system data" and when you are in the windows asking creating it or not, (options yes and no), default option should be in yes, first click "O", and then "X", and the game don't create the system data, i see this because with that i don't get any mkdir error.

Other things, this message:
```
Common/FileUtil.cpp:254 CreateDir: mkdir failed on : No such file or directory
```
its weird! normally this message put the directory before ":" (mkdir failed on /psp/something).

```
ERROR_LOG(COMMON, "CreateDir: mkdir failed on %s: %s", path.c_str(), strerror(err));
```

**Comment by unknownbrackets** [comment] 2015-12-29 20:18
Oh.  Well, first off, remember that as a Japanese game, O is probably "confirm" and X is probably "cancel."  So O and then X probably means "accept" and then "cancel"?

I wonder if the blank directory is either (a) the parameters not being filled early enough or (b) something we should have a default value for.  It seems like a from the log above.

-[Unknown]

**Comment by latot** [comment] 2015-12-29 20:24
Okis, well saying in other way, first cancel (there you will stay in the same windows(canceling you don't go anyway)) and then you confirm the game don't create the system data.

Thx.

**Comment by latot** [comment] 2016-01-06 22:17
Curious, when i enter to settings i get an similar error, but here is a stat to an empty path var:

log:

```
W: file_util.cpp:178: IsDirectory: stat failed on 
```

bt

```
Breakpoint 1, getFileInfo (path=0x7ffff66ed678 <std::string::_Rep::_S_empty_rep_storage+24> "", fileInfo=0x7fffe9de2600)
    at /home/pipe/Documentos/git/ppsspp/ext/native/file/file_util.cpp:178
178			WLOG("IsDirectory: stat failed on %s", path);
#0  getFileInfo (path=0x7ffff66ed678 <std::string::_Rep::_S_empty_rep_storage+24> "", fileInfo=0x7fffe9de2600)
    at /home/pipe/Documentos/git/ppsspp/ext/native/file/file_util.cpp:178
        file_info = {st_dev = 592, st_ino = 140737316434425, st_nlink = 0, st_mode = 4122623125, st_uid = 32767, st_gid = 17859435, __pad0 = 0, 
          st_rdev = 140737117038032, st_size = 140736750160112, st_blksize = 140737316011427, st_blocks = 4294967296, st_atim = {tv_sec = 140737316015235, 
            tv_nsec = 140737316013776}, st_mtim = {tv_sec = 0, tv_nsec = 0}, st_ctim = {tv_sec = 140737316014587, tv_nsec = 140737316013776}, __glibc_reserved = {
            140736750160112, 140737327847032, 9220265}}
        copy = ""
        result = -1
#1  0x0000000000a87c6e in LocalFileLoader::IsDirectory (this=0x7fffd40008c0) at /home/pipe/Documentos/git/ppsspp/Core/FileLoaders/LocalFileLoader.cpp:62
        info = {name = "", fullName = "", exists = 106, isDirectory = 131, isWritable = 16, size = 59821568}
#2  0x0000000000a87b94 in LocalFileLoader::Exists (this=0x7fffd40008c0) at /home/pipe/Documentos/git/ppsspp/Core/FileLoaders/LocalFileLoader.cpp:53
No locals.
#3  0x00000000008c8de2 in GameInfo::LoadFromPath (this=0x390cce0, gamePath="") at /home/pipe/Documentos/git/ppsspp/UI/GameInfoCache.cpp:216
        guard = {mtx_ = @0x390cce0}
#4  0x00000000008cb1ab in GameInfoWorkItem::run (this=0x226b5e0) at /home/pipe/Documentos/git/ppsspp/UI/GameInfoCache.cpp:336
        filename = "/home/pipe/Documentos/PSP Games/Madoka_Magica_Portable_v1.5.iso"
#5  0x0000000000efc8e1 in threadfunc (wq=0x222d700) at /home/pipe/Documentos/git/ppsspp/ext/native/thread/prioritizedworkqueue.cpp:98
        item = 0x226b5e0
#6  0x0000000000efefb7 in std::_Bind<void (*(PrioritizedWorkQueue*))(PrioritizedWorkQueue*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (
    this=0x222e158, __args=<unknown type in /home/pipe/Documentos/git/ppsspp/PPSSPPSDL, CU 0x17fbec2, DIE 0x180895e>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/functional:1264
No locals.
#7  0x0000000000efef0f in std::_Bind<void (*(PrioritizedWorkQueue*))(PrioritizedWorkQueue*)>::operator()<, void>() (this=0x222e158)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/functional:1323
No locals.
#8  0x0000000000efee90 in std::_Bind_simple<std::_Bind<void (*(PrioritizedWorkQueue*))(PrioritizedWorkQueue*)> ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x222e158)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/functional:1700
No locals.
#9  0x0000000000efedc2 in std::_Bind_simple<std::_Bind<void (*(PrioritizedWorkQueue*))(PrioritizedWorkQueue*)> ()>::operator()() (this=0x222e158)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/functional:1688
No locals.
#10 0x0000000000efed30 in std::thread::_Impl<std::_Bind_simple<std::_Bind<void (*(PrioritizedWorkQueue*))(PrioritizedWorkQueue*)> ()> >::_M_run() (this=0x222e140)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/thread:115
No locals.
#11 0x00007ffff6499a10 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff7bc6324 in start_thread (arg=0x7fffe9de3700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffe9de3700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737117042432, 8909439684194816216, 0, 140737488341007, 140737488341008, 140737117042432, -8909417984599830312, 
                -8909422672800558888}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
---Type <return> to continue, or q <return> to quit---
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#13 0x00007ffff5c181cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

i hope this info can help.

**Comment by latot** [comment] 2016-01-06 23:09
well, continues, now more logs! (this of the first mkdir problem

```
Breakpoint 1, File::CreateDir (path="") at /home/pipe/Documentos/git/ppsspp/Common/FileUtil.cpp:254
254		ERROR_LOG(COMMON, "CreateDir: mkdir failed on %s: %s", path.c_str(), strerror(err));
(gdb) bt full
#0  File::CreateDir (path="") at /home/pipe/Documentos/git/ppsspp/Common/FileUtil.cpp:254
        err = 2
#1  0x0000000000c53db6 in File::CreateFullPath (fullPath="/home/pipe/.config/ppsspp/PSP/SAVEDATA/ULJS00430System")
    at /home/pipe/Documentos/git/ppsspp/Common/FileUtil.cpp:292
        subPath = ""
        panicCounter = 100
        position = 0
#2  0x0000000000b67283 in DirectoryFileSystem::MkDir (this=0x3c9ef00, dirname="/PSP/SAVEDATA/ULJS00430System")
    at /home/pipe/Documentos/git/ppsspp/Core/FileSystems/DirectoryFileSystem.cpp:440
        fixedCase = "/PSP/SAVEDATA/ULJS00430System"
#3  0x0000000000b6f113 in MetaFileSystem::MkDir (this=0x16cec80 <pspFileSystem>, dirname="ms0:/PSP/SAVEDATA/ULJS00430System")
    at /home/pipe/Documentos/git/ppsspp/Core/FileSystems/MetaFileSystem.cpp:457
        guard = {mtx_ = @0x16cecf0}
        of = "/PSP/SAVEDATA/ULJS00430System"
        system = 0x3c9ef00
#4  0x0000000000b57e53 in SavedataParam::Save (this=0x16be840 <saveDialog+64>, param=0x16be868 <saveDialog+104>, saveDirName="System", secureMode=true)
    at /home/pipe/Documentos/git/ppsspp/Core/Dialog/SavedataParam.cpp:373
        dirPath = "ms0:/PSP/SAVEDATA/ULJS00430System"
        cryptedData = 0x0
        cryptedSize = 2
        sfopath = ""
        tmpData = 0x1f <error: Cannot access memory at address 0x1f>
        cryptedHash = "\000\000\000\000\000\000\000\000pD\265\000\000\000\000"
        sfoFile = {values = std::map with 0 elements}
        sfoInfo = {name = "/PSP/SAVEDATA/ULJS00430System", size = 11879536, access = 3642996656, exists = 255, type = (unknown: 0), atime = {tm_sec = -14897, 
            tm_min = 32767, tm_hour = 9077381, tm_mday = 0, tm_mon = 19051736, tm_year = 0, tm_wday = -795152384, tm_yday = 1212888301, tm_isdst = 11879536, 
            tm_gmtoff = 11892267, tm_zone = 0x0}, ctime = {tm_sec = 23849064, tm_min = 0, tm_hour = 23849024, tm_mday = 0, tm_mon = -651970368, tm_year = 32767, 
            tm_wday = 0, tm_yday = 0, tm_isdst = 0, tm_gmtoff = 140736683051224, 
            tm_zone = 0x484b34edd09af000 <error: Cannot access memory at address 0x484b34edd09af000>}, mtime = {tm_sec = 0, tm_min = 0, tm_hour = 11879536, 
            tm_mday = 0, tm_mon = -651970464, tm_year = 32767, tm_wday = 11890999, tm_yday = 0, tm_isdst = 0, tm_gmtoff = 23849064, 
            tm_zone = 0x16be840 <saveDialog+64> "h\350k\001"}, isOnSectorSystem = 192, startSector = 32767, numSectors = 0, sectorSize = 0}
        sfoData = 0x0
        sfoSize = 0
#5  0x0000000000b53e23 in PSPSaveDialog::ExecuteNotVisibleIOAction (this=0x16be800 <saveDialog>) at /home/pipe/Documentos/git/ppsspp/Core/Dialog/PSPSaveDialog.cpp:1051
No locals.
#6  0x0000000000b53c94 in PSPSaveDialog::ExecuteIOAction (this=0x16be800 <saveDialog>) at /home/pipe/Documentos/git/ppsspp/Core/Dialog/PSPSaveDialog.cpp:1028
        guard = {mtx_ = @0x16bf480}
#7  0x0000000000b54492 in DoExecuteIOAction (dialog=0x16be800 <saveDialog>) at /home/pipe/Documentos/git/ppsspp/Core/Dialog/PSPSaveDialog.cpp:1138
No locals.
#8  0x0000000000b55e7c in std::_Bind_simple<void (*(PSPSaveDialog*))(PSPSaveDialog*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x3d39e98)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/functional:1700
No locals.
#9  0x0000000000b55d62 in std::_Bind_simple<void (*(PSPSaveDialog*))(PSPSaveDialog*)>::operator()() (this=0x3d39e98)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/functional:1688
---Type <return> to continue, or q <return> to quit---
No locals.
#10 0x0000000000b55cd0 in std::thread::_Impl<std::_Bind_simple<void (*(PSPSaveDialog*))(PSPSaveDialog*)> >::_M_run() (this=0x3d39e80)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/thread:115
No locals.
#11 0x00007ffff6499a10 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6
No symbol table info available.
#12 0x00007ffff7bc6324 in start_thread (arg=0x7fffd923c700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffd923c700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736836388608, 1834386972497966860, 0, 140737488340431, 140737488340432, 140736836388608, -1834443354875070708, 
                -1834405119710300404}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#13 0x00007ffff5c181cd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

**Comment by latot** [comment] 2016-01-07 01:49
Resume all Issue:

1) Segfault backing from school, with fast memory enabled

normal log:https://gist.github.com/latot/53bf028cca610d210afe
full log:https://gist.github.com/latot/6b709d65faf2332be9a0


2) Empty path in mkdir saving system data for first time

backtrace: https://gist.github.com/latot/e059f9f3f95aa08b2bc9
```
Common/FileUtil.cpp:254 CreateDir: mkdir failed on : No such file or directory
```

3) Empty path when we open ppsspp settings, probably related with this game, check log

backtrace: https://gist.github.com/latot/bb365a3b3db1eff0a4fe
```
W: file_util.cpp:178: IsDirectory: stat failed on 
```

4) System game data don't is created if in the select menu before accept it first cancel then accept.

**Comment by unknownbrackets** [comment] 2016-01-07 04:39
The EPMap thing is probably fine.  I don't think we support PCM audio in mpeg playback.

ms0:/psp/SAVEDATA/ULJS00430Install/INSTALL.DNS is just the game checking if the install data is there.  It's doing it a lazy way, and does not care that it is causing an error doing it this lazy way.  A fact of life: many games generate errors just because they can.

Possibly the save issue is an issue of the savedata param struct being populated late.  Not sure, but maybe there's some SFO weirdness going on here.

"WriteRest: op out of range" is a separate issue.  Try again with the latest build on the segfault?

-[Unknown]

**Comment by latot** [comment] 2016-01-07 04:55
extras removed thx the clarifications, i retest this day all this points, sadly still persist

**Comment by unknownbrackets** [comment] 2016-01-07 05:04
Well, the PCM thing is probably an issue.  I just meant we don't currently support it.  Does the video play audio?

And I meant that the logs for the first one are old and talk about the "WriteRest" error.  Newer logs would help.

-[Unknown]

**Comment by latot** [comment] 2016-01-07 05:14
okis, now all logs updates

**Comment by unknownbrackets** [comment] 2019-03-23 15:29
The blank error for mkdir has been fixed, and WriteRest should be fixed too.  Has anything improved for this issue with fast memory enabled?

-[Unknown]

**Comment by hrydgard** [comment] 2020-03-09 22:16
Closing, no feedback in a long time.

**Closed by hrydgard** 2020-03-09 22:16 UTC
Labels: No Feedback / Outdated?

**Comment by Panderner** [comment] 2020-04-09 05:28
Still crashes after this savedata ends

**Comment by unknownbrackets** [comment] 2020-04-09 05:31
Okay, just going to leave this closed and #6557 open in that case.

-[Unknown]

**Comment by Panderner** [comment] 2020-04-09 05:44
After vn scene in this save state stucks at loading screen

**Comment by sum2012** [comment] 2021-01-25 13:24
v1.10.3-1639-g4eee5df2a blue screen
![1](https://user-images.githubusercontent.com/2177532/105711572-b5aefb00-5f53-11eb-9659-59093faf4515.jpg)

**Comment by unknownbrackets** [comment] 2021-01-25 15:54
Is that still affected by simulate UMD delays (i.e. #6557) or is this now always?

-[Unknown]

**Comment by sum2012** [comment] 2021-01-25 20:58
Yes,it is still affected by simulate UMD delays.
This is easier to reproduce
