### ISSUE TITLE
Ford Bold Moves Street Racing GFX issue

### ISSUE THREAD

**Issue by theboy181** [hrydgard/ppsspp#12294] opened 2019-09-01 06:35 UTC
Windows 10
ppsspp Gold 1.8

Game has an issue where the gfx look lower resolution than the first 25% of the lower screen. You can see a shadowed line across the road where the issues starts. Software doesn't have this issue, but there are LARGE blocks of garbage all over the screen.

![image](https://user-images.githubusercontent.com/9299743/64072673-cddbf700-cc47-11e9-976b-497017378e43.png)

**Comment by theboy181** [comment] 2019-09-01 06:40
Posted a video on Discord

https://cdn.discordapp.com/attachments/480103153803460614/617609566921687051/2019-08-31_23-38-18.mov

**Comment by leopard20** [comment] 2019-09-01 06:55
That looks like a PP effect (on the game side)

**Comment by theboy181** [comment] 2019-09-01 14:07
What is the PP effect? Is there more information on it?

**Comment by hrydgard** [comment] 2019-09-01 14:47
I think he just means post-processing, and it's something the game is doing on top of the image.

**Comment by LunaMoo** [comment] 2019-09-01 15:00
It's some foggy bloom effect, I remember making workarounds to remove it for a bunch of "Ford" games since they all had this problem.

**Comment by theboy181** [comment] 2019-09-01 17:00
You have these hacks available? Also this game doesn't have this issue in SW mode.

**Comment by unknownbrackets** [comment] 2019-09-01 17:18
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by leopard20** [comment] 2019-09-01 17:48
@theboy181
The workarounds are here: https://github.com/LunaMoo/PPSSPP_workarounds
Place the cheat.db file in:
PPSSPP (main folder)\ memstick\PSP\CHEATS
If the "CHEATS" folder doesn't exist, make one.
Then just enable the cheats for the game and import the cheats from the database.

**Comment by theboy181** [comment] 2019-09-01 18:04
That worked @LunaMoo   Thank you!!

Here is a code I worked on to make this game shine! 

```
_G Ford Moves Street Racing
_C1 60FPS
_L 0x2021B644 0x00000001
_C1 Improved Draw Distance
_L 0x20197B34 0xBF800000 // 08997B34
_C0 Lock Camera
_L 0x200DEB5C 0x16220007
_C1 Unlock Camera
_L 0x200DEB5C 0x12220007
_C1 Car Level Of Detail Max
_L 20176344 0x24A50000
_C0 Remove glitchy effect
_L 0xE0010002 0x00014248
_L 0x20014248 0x0000C021'''

I would like to understand how to remove these post-processing effects for other games though. How are you locating them in ppsspp to create codes?

**Comment by theboy181** [comment] 2019-09-02 14:29
@LunaMoo 

I would like to understand how to remove these post-processing effects for other games though. How are you locating them in PPSSPP to create codes?

any tips?

**Comment by Panderner** [comment] 2020-04-22 02:55
![Screenshot_2020-04-22-10-47-35-43_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79935519-b6c47080-8487-11ea-99d9-1918723c93e1.png)
Here's a GE Dump:
[GE Dump.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4513563/GE.Dump.ppdmp.zip)

**Comment by Panderner** [comment] 2020-12-21 07:59
It's seems #13256 fixes fog for Vulkan but not OpenGL:
![Screenshot_2020-12-21-15-58-39-647_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/102753021-7534ee00-43a5-11eb-9d32-9396dbbe228e.jpg)

**Comment by hrydgard** [comment] 2020-12-22 17:32
Good find, then this is just depth texturing and once I implement that for OpenGL ES 3.0, it will work on devices that support that. It's a bit trickier than VK though due to the different depth buffer range we use so it'll be a while.

**Comment by Panderner** [comment] 2021-02-19 09:05
Ford Racing: Off Road had a same problem:

OpenGL:
![Screenshot_2021-02-19-17-02-47-658_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/108482553-94cc9200-72d4-11eb-9eab-4bd458e0e2f5.jpg)

Vulkan:
![Screenshot_2021-02-19-17-02-59-681_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/108482570-9a29dc80-72d4-11eb-88fb-2275698138ae.jpg)

**Comment by Gamemulatorer** [comment] 2023-03-13 16:59
I cannot reproduce this issue after https://github.com/hrydgard/ppsspp/pull/16961 is merged.
![Screenshot_20230314_005639_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/224772340-2549c6fa-9a43-47e5-955f-cc5fc527c7ef.jpg)
![Screenshot_20230314_005425_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/224772364-6dae0c79-f9a0-43b7-80ca-5c3fd94d0bf3.jpg)

Snapdragon 439 tried and tested both opengl and vulkan.

**Comment by hrydgard** [comment] 2023-03-13 17:10
Hm, that's curious since the new stuff there is only enabled by a compatibility flag. But it might have included some bug fixes too, heh.

**Closed by hrydgard** 2023-03-13 17:10 UTC
Labels: GE emulation, Depth Texture

**Comment by Panderner** [comment] 2023-03-14 08:19
D3D9 results:
![ULUS10159_00000](https://user-images.githubusercontent.com/37503397/224938565-8ff25c93-5476-4408-8fa0-7b7066104267.jpg)

**Comment by hrydgard** [comment] 2023-03-14 08:25
Well, that's better than the early pictures in this thread, as far as I can tell, but looks like the fog is missing.
