### ISSUE TITLE
Vortex glitch in God of War - Ghost of Sparta (PSP OpenEmu)

### ISSUE THREAD

**Issue by Roanoke2015** [hrydgard/ppsspp#14565] opened 2021-06-26 22:37 UTC
Hi all, 

I am stuck in the infamous Vortex glitch in GoW Ghost of Sparta, where you are in a boat killing enemies and the next cinematic never triggers, thus making it impossible to progress in the game. There is a solution on the internet for PPSSPP (change CPU clock speed to 222MHz) but none for OpenEmu. 

I read in another forum that you can fix this in OpenEmu by assigning a key to the fast forward and just tap the fast forward a few times, but that did not work for me. Did anybody manage to solve this issue? Is the fast forward solution working for anybody else?

Cheers!

**Comment by LunaMoo** [comment] 2021-06-26 23:10
Closing as a duplicate of #8299

 Take note through that if you're requesting solution specific to OpenEmu, we don't have any integration with that project, as such you should request settings parity to Open Emu issue tracker as it's they who decide which options you have and which don't. That being said they probably aren't reprogramming PPSSPP much if at all and just don't have options present in their UI, you still can access all the settings from the ppsspp.ini file or similar if they renamed it.

**Closed by LunaMoo** 2021-06-26 23:11 UTC
