### ISSUE TITLE
Can't open app

### ISSUE THREAD

**Issue by Chichadi0s** [hrydgard/ppsspp#9033] opened 2016-10-04 21:24 UTC
I downloaded the.deb Of cydia but the appanda doesnt open

**Comment by unknownbrackets** [comment] 2018-05-31 06:36
Does this still happen in the latest version?

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-09-02 23:53
This issue is being closed because it hasn't been updated with feedback.  It could just be a duplicate of #9186.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2018-09-02 23:53 UTC
Labels: No Feedback / Outdated?, Platform-specific (iOS)
