### ISSUE TITLE
Dante's inferno have a lot of glitches And flickering on android

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10945] opened 2018-04-20 18:22 UTC
What happens?
I tried version 1.5.4 for android and for PC. On PC is fast 40/40 98%-100% speed but graphics is flickering on these two devices (OpenGL). And now Android: If you change emulated clocks lower than 222MHZ, videos running really bad- it is Slow and sound is jumming in 100% speed with 60MHZ.( sound, nothing, sound, nothing, sound, nothing. This is changing after every 0.5 second.)
![screenshot_20180420-190231](https://user-images.githubusercontent.com/33152267/39066898-04668b36-44d7-11e8-8efd-7ebe61236b9f.png) this is in version 1.5.4. Game have over screen something white. Idk. What is it. This problem is fixed with ON-Disable slower effects (speedup) but textures will flickering.
![screenshot_20180420-190312](https://user-images.githubusercontent.com/33152267/39067080-be2a9774-44d7-11e8-9ce4-f0a0e2ae1495.png) And now latest version 1.5.4 build 921. With ON- disable slower effects (speedup) you have fully White screen. If you OFF it you will get this
![screenshot_20180420-190952](https://user-images.githubusercontent.com/33152267/39067248-48164f82-44d8-11e8-8e24-1b4406f0943c.png) 

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by marosis** [comment] 2018-04-20 18:25
Sorry but flickering is not wiewable

**Comment by Jinzombie** [comment] 2018-04-21 00:57
This is a duplicate issue of #10006 ?

**Comment by marosis** [comment] 2018-04-21 12:02
Can i ask Somebody if is something of these issues on Vulkan backend?

**Comment by marosis** [comment] 2018-04-21 12:02
On android?

**Comment by marosis** [comment] 2018-04-21 13:13
I have found new issue! This is with frame skipping
![screenshot_20180421-151151](https://user-images.githubusercontent.com/33152267/39084447-91665f76-4576-11e8-8a5d-d7941d2cb8c0.png)
![screenshot_20180421-151123](https://user-images.githubusercontent.com/33152267/39084452-97f6097c-4576-11e8-8384-4844320943c9.png)

**Comment by marosis** [comment] 2018-04-21 13:14
this game is ingame unplayable

**Comment by marosis** [comment] 2018-04-21 14:16
@Hrydgard i will try to find build where that big blur effect from 1.5.4 to newest build 921. Maybe today but who know when i will have time.

**Comment by hrydgard** [comment] 2018-04-21 15:14
@marosis ok, that would be useful yes.

**Comment by marosis** [comment] 2018-04-21 18:50
I've tried random build 519 And is looks like playable but here is problem with frameskip
![screenshot_20180421-204604](https://user-images.githubusercontent.com/33152267/39087723-91d59f2e-45a5-11e8-8bbc-b9f076c85276.png)
![screenshot_20180421-204609](https://user-images.githubusercontent.com/33152267/39087727-a234054a-45a5-11e8-856e-fd0b78131ea7.png)

**Comment by marosis** [comment] 2018-04-21 18:51
Second is with frameskip

**Comment by marosis** [comment] 2018-04-21 19:11
Heureka!!!! it is +- build 643-652

**Comment by marosis** [comment] 2018-04-21 19:15
@hrydgard please we need remove- Disable slower effects (speedup). In a lot of games are with this issues

**Comment by hrydgard** [comment] 2018-04-21 19:26
643: https://github.com/hrydgard/ppsspp/commit/37f44364d
652: https://github.com/hrydgard/ppsspp/commit/90dbd9a725540bbf6221e8437adea518371a38cc

Diff: https://github.com/hrydgard/ppsspp/compare/37f44364d...90dbd9a72

there are a few builds inbetween...

**Comment by marosis** [comment] 2018-04-21 19:27
Ok, after hiding this option we only need fix drawing textures with frameskipping

**Comment by marosis** [comment] 2018-04-21 19:29
Great, but sorry i'm not programator. I don't understant C++

**Comment by hrydgard** [comment] 2018-04-21 19:39
I just posted them there for my own benefit when I take a look at it later...

**Comment by unknownbrackets** [comment] 2018-04-21 20:45
If we fixed "disable slower effects" somehow to never make graphics worse - why would we keep the option?  The option only exists because it allows you to sacrifice decent graphics for speed.  If it was magical and had no downside, we'd just make it on always right?

We should add a bunch of placebo options "Enable speed" and "Switch to fast renderer" that do absolutely nothing, just to satisfy people's need for non-default options that should always, always be on to exist.

-[Unknown]

**Comment by marosis** [comment] 2018-04-22 06:15
#10951 have same problem in game!

**Comment by leopard20** [comment] 2018-04-22 11:11
@hrydgard 
It's not just that this option speeds up or fixes glitches some games, but also some games look nicer with this option on. E.g Midnight Club LA Remix

**Comment by marosis** [comment] 2018-04-30 09:36
@hrydgard i'm sorry, I got you bad builds. Right build where it started is 686 BUT!! Here is a problem because this build fixed something in GTA games for NVIDIA Shield.

**Comment by LunaMoo** [comment] 2018-05-26 18:41
Closing as a duplicate of #4845 this game is glitchy from a long time, sometimes it appears fixed to some, but only when it's missing effects, no point opening new issue about same thing every release version.

**Closed by LunaMoo** 2018-05-26 18:41 UTC
