### ISSUE TITLE
another textures problem. (looks like a typical tiled renderer driver glitch)

### ISSUE THREAD

**Issue by sephiroth0396** [hrydgard/ppsspp#10878] opened 2018-04-05 19:42 UTC
https://m.youtube.com/watch?v=AKJXpHNV3mc skip to 0:17. What is that box thingy on the area? Is this my device bug or something?
It's also happen on the game like god eater burst and 2, monster hunter 3rd and monster hunter freedom unite.
Here is for monster hunter 3rd
https://forums.ppsspp.org/attachment.php?aid=16218

I'm sorry if it's a graphical issue thought. I started to notice it at 1.3.x version. ( not sure about the version below that. )

**Comment by sephiroth0396** [comment] 2018-04-05 20:26
So it's a bug? I see. It's infamous phone called nexian lol a old one.

**Comment by hrydgard** [comment] 2018-04-05 20:49
Ah hm, interesting. Very likely a driver bug indeed, it really looks very similar to the one I had on Galaxy. Try on PC and see if you get the same thing or not.

**Comment by sephiroth0396** [comment] 2018-04-05 20:52
I see. Will do it later then. I will ask my friends as well

**Comment by unknownbrackets** [comment] 2018-06-09 06:18
Is this a duplicate of #7218?

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-09-03 21:17
Unfortunately, I'm pretty sure this is the same driver bug.  I'm going to close this as a duplicate.

-[Unknown]

**Closed by unknownbrackets** 2018-09-03 21:17 UTC
Labels: Platform-specific (Android)

**Comment by sephiroth0396** [comment] 2018-09-11 07:57
It's worked fine since I changed my phone a month ago. LOL I think it's just a bug from my old phone, I guess.
