### ISSUE TITLE
Assassin's Creed remaining save data issue

### ISSUE THREAD

**Issue by metaasza** [hrydgard/ppsspp#7669] opened 2015-04-10 17:08 UTC
Sorry to ask this but I've read those related threads and find that this problem still happen on my ppsspp android build (v1.0.1-382-g0f06858). My device is Samsung Galaxy S III. Thank you for your attention
 :)

**Comment by CipherX** [comment] 2015-05-06 14:22
Having same issue with latest build for android.

**Comment by daniel229** [comment] 2015-05-09 03:38
Any details here?can't save? can't load?

**Comment by metaasza** [comment] 2015-05-09 05:44
Sorry for lacking of information. Whwnever I was about pass through the first chapter, it always shows an error as shown in picture below.
![11221168_10206678701914394_1165344435_o](https://cloud.githubusercontent.com/assets/10046089/7548902/bd703a36-f648-11e4-82fe-1d88a8921e64.jpg)
![11249461_10206678702154400_1895251767_o](https://cloud.githubusercontent.com/assets/10046089/7548903/c16f390c-f648-11e4-8890-fa396079c289.jpg)

**Comment by daniel229** [comment] 2015-05-09 06:48
Does the first chapter mean Memory Block 1,I just finished and seems fine here.But I had seen other people also had this problem.Is there a game save inside the savedata folder?

**Comment by metaasza** [comment] 2015-05-09 07:17
Yes, there's a save file inside ULUS10455 folder. I've also try using save from gamefaqs but it stills have the same problems like a picture above.

**Comment by daniel229** [comment] 2015-05-09 11:04
Also the game save works fine after savestate laoding,no matter when it's saved.
Is it with default setting,if not you can try it.

**Comment by unknownbrackets** [comment] 2015-12-29 21:25
Has anything improved here, even starting over from no saves and not using savestates, in the latest git build?

Not sure what could cause this.

-[Unknown]

**Comment by LunaMoo** [comment] 2017-11-15 04:31
Not sure if this is a real problem or "Time Paradox" aka #7244 happening in less control fashion here just because game has auto-save system and doesn't exactly go out of it's way to inform user when it's saving. Even has an option to disable auto save which will keep auto-saving while for example changing locations.

 The whole problem directly is caused by missmatched hash and can be worked around just like other time travel save issues via simple cwcheat, so kind of doubt it's a savedata emulation issue. We might need a compat ini option to annoy users forcing them to read about the problem and confirm at least first savestate loading in games affected by this or something alike:].

**Comment by unknownbrackets** [comment] 2019-03-23 16:30
Thanks - I'm going to close this as a duplicate of #7244 then.  That's still open and has other thoughts on workarounds too.

-[Unknown]

**Closed by unknownbrackets** 2019-03-23 16:30 UTC

**Comment by Panderner** [comment] 2019-12-07 14:05
I don't use save states but it still remains in latest version

**Comment by unknownbrackets** [comment] 2019-12-28 17:19
The rewind feature internally relies on save states, so the same may happen if using rewind.

I could see a stronger argument to "rewind" save data along with game progress, though...

-[Unknown]
