### ISSUE TITLE
Def Jam: the takeover character image not displaying

### ISSUE THREAD

**Issue by Herrsch00** [hrydgard/ppsspp#12704] opened 2020-03-12 00:34 UTC
many people encounters this bug where character image is not displaying on def jam: the takeover on ppsspp. How to fix this

**Comment by Emulatorer** [comment] 2020-03-12 00:48
http://forums.ppsspp.org/showthread.php?page=4&tid=1857

**Comment by unknownbrackets** [comment] 2020-03-13 06:36
I'm not sure what you mean - could you try exporting a GE frame dump (when seeing the bug)?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

People report that the game doesn't work, and that it does work, but it could be settings related or a bad disc.  It might also be GPU specific.  You can see a list of community reports here:
https://report.ppsspp.org/game/ULUS10100_1.01

-[Unknown]

**Comment by Emulatorer** [comment] 2020-03-14 14:24
![Screenshot_20200314-221828](https://user-images.githubusercontent.com/37603562/76683876-50eff800-6642-11ea-8f29-b612c2b2ff4d.png)
looks right to my phone I'm using ppsspp v1.9.3-481 beta build

**Comment by Emulatorer** [comment] 2020-03-15 04:07
@Herrsch00 what's your phone specs hardware and your ppsspp version?
Screenshot where the image not displaying the characters?

**Comment by Emulatorer** [comment] 2020-03-24 11:08
I think this issue can be close now I never experience character image not displaying using the latest beta build of ppsspp in my phone

**Comment by Emulatorer** [comment] 2020-04-17 10:39
I wonder why this issue still open 🤔

**Comment by hrydgard** [comment] 2020-04-17 10:42
Wait, this was a pretty new one. I think I'll reopen since obviously some people do have an issue (unless we have fixed it recently). Not sure...

**Comment by Emulatorer** [comment] 2020-04-17 12:53
> Wait, this was a pretty new one. I think I'll reopen since obviously some people do have an issue (unless we have fixed it recently). Not sure...

Not a duplicate of #5258?

**Comment by hrydgard** [comment] 2020-04-17 13:03
Duplicate of #5258. 

Indeed. Now let's see if Github duplicate thing works..

**Closed by hrydgard** 2020-04-17 13:03 UTC
Labels: No Feedback / Outdated?

**Comment by Panderner** [comment] 2020-04-17 13:05
> Duplicate of #5258.
> 
> Indeed. Now let's see if Github duplicate thing works.. Argh no :(

The original one is closed but I don't know if you produce the issue

**Comment by hrydgard** [comment] 2020-04-17 13:15
I don't know either, the whole thing is very unclear to me. @Herrsch00 will need to clarify who this is still happening for.
