### ISSUE TITLE
Disable Alpha Test on PowerVR not improve performance on many recent version

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8809] opened 2016-06-12 00:13 UTC
i don't know what happen , but on my ASUS Zenfone 4 using PowerVR enable Disable Alpha Test check , not improve performance as all in case of issue #6286
Ex : The 3rd Birthday no improve speed and FPS , it's not much difference , remain the same

**Comment by zminhquanz** [comment] 2016-06-13 00:17
@unknownbrackets can you explain this problem

**Comment by unknownbrackets** [comment] 2016-06-13 00:49
Well, it's possible that it's just not helping anymore - if you've upgraded Android, maybe the driver got smarter, and if you haven't, maybe some optimizations to PPSSPP have made it not help.

Or it could be there's a new performance problem or the alpha testing is not fully disabled.

Find a past build where it was working, for example one you remember disable alpha test improving things.  If it's faster than the latest build, it sounds like something we can fix.  With that, you can try half way between that git build and the latest one... if it's slower still, that means it happened before the one you tried, so try halfway again (1/4 the way from the old build), etc.  Just cut it down by halves a few times.

Using that method, you can cut down to right when the problem started in just a handful of tries.  And then we can look at the changes in that area and figure out the cause.

But, if you can't find a build that was faster, it could mean it either never helped that area of the game.

-[Unknown]

**Comment by zminhquanz** [comment] 2016-06-14 00:50
@unknownbrackets oh yeah , i use the past version 0.9.8 , enable disable alpha test , it's improve between 5% to 10% FPS and speed and stable than newer version 1.2.2

**Comment by unknownbrackets** [comment] 2016-06-14 02:12
Okay, so did you go by halves and find the build that changed it?  I don't have a powervr device, so if you just leave it at the above, it'll have to wait for someone other than me to come along to fix it.

If you can tell me which build stopped working (the one before it is fast, but this one is slow), then I might be able to fix it for you.  If I tried to guess, among 8000 commits I would probably never find it.

But you, since you can experience the problem, can see it in 13 tries.  That's a lot less than 8000, and I can't even tell which of those 8000 even if I tried 8000 times.

It could also be something else made it slower, like simulate block transfer or depal.  We've fixed several bugs affecting that game since v0.9.8.

-[Unknown]

**Comment by zminhquanz** [comment] 2016-06-14 03:25
i think so easy , the older version have better and it's don't have a bugs

**Comment by unknownbrackets** [comment] 2016-06-14 04:11
If you start caring about the numerous bugs fixed since v0.9.8, in that game and others, you can comment and we'll reopen.  If this is really an issue, then it'll have to wait for someone else to come along and provide information.

But this is wortheless without feedback, so closing.

-[Unknown]

**Closed by unknownbrackets** 2016-06-14 04:11 UTC
