### ISSUE TITLE
1.2.0 - things to fix before release

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#8362] opened 2016-01-02 20:21 UTC
Alright, let's do this again!

  * ~~#8347 needs merging, want this done (graphics context refactor)~~

Please comment with additional issues. Only regressions from previous versions are allowed here (and bugs in new features, of course).

**Comment by unknownbrackets** [comment] 2016-01-02 20:40
I'm aware of: #8252, #8355 (probably fixed), #8255, #8187, #8075 (but this game is already crashy AFAIK), #8220, #8195, #8261, #8298, #8269, #8012.

I think they are all regressions but I'm not certain.  I've roughly put them in order of severity.  But I also think there are improvements that offset some of these.  So not sure if it's worth holding the release for all of them.

-[Unknown]

**Comment by sum2012** [comment] 2016-01-02 21:02
Yu-Gi-Oh still crash in Android in some model
But I do not get that reporter 's contact.

**Comment by sum2012** [comment] 2016-01-02 21:10
#8187

**Comment by zminhquanz** [comment] 2016-01-03 00:29
fix missing texture on PowerVR SGX 544 some game : Dissidia Final Fantasy 012 , Final Fantasy Type-0 , ... etc

**Comment by unknownbrackets** [comment] 2016-01-03 00:33
So that was working in v1.1.1?  What is the first git build it stopped working in, and the last one it worked in?

If it was not working in v1.1.1, it does not belong here.

-[Unknown]

**Comment by zminhquanz** [comment] 2016-01-03 00:52
it's doesn't affect in 1.1.1

**Comment by HongVietNguyen** [comment] 2016-01-03 02:12
Metal Gear Solid Peace Walker still crash in android version

**Comment by daniel229** [comment] 2016-01-03 05:07
https://github.com/hrydgard/ppsspp/issues/8370 Probably would be fixed with other atrac3+ issue.

**Comment by nfjorgebueno** [comment] 2016-01-06 03:02
would be good if in the emulator also functioned tempAr codes, cwcheats are very hard to come to ppsspp and also not function as a real psp, from what I saw on the forums ppsspp several bugs in the emulator with cwcheats, thank you very much by your attention

**Comment by sum2012** [comment] 2016-01-06 22:27
#8383

**Comment by asbel123** [comment] 2016-01-06 23:24
#8387 what about andriod problem

**Comment by Amaestris** [comment] 2016-01-06 23:40
All yu gi oh tag forces still have multiplayer issues on android
(Source: http://forums.ppsspp.org/showthread.php?tid=9037 )
Yu gi oh Arc V tag force special's multiplayer dosen't work for IOS too.

**Comment by daniel229** [comment] 2016-01-07 01:31
https://github.com/hrydgard/ppsspp/issues/8401

**Comment by unknownbrackets** [comment] 2016-01-07 04:48
Remember: this issue isn't, "please build a feature list for what you want done ASAP."  It's more about making sure we're aware of things that worked in v1.1.1 and have stopped working.

TempAR wasn't a feature in v1.1.1.  Network play was not stable in v1.2.0.  Obviously those have no place here.

-[Unknown]

**Comment by sum2012** [comment] 2016-01-11 22:22
@hrydgard 
I get many report of Android user.
They play ppsspp then press "Home" press,
last back to ppsspp.
It would make ppsspp black screen.
I am unable to reproduce it.Please fix it.Thanks

**Comment by hrydgard** [comment] 2016-01-12 00:02
@sum2012  I've never seen that. Any idea what hardware they are running on?

**Comment by sum2012** [comment] 2016-01-12 00:14
i give you model first,乐檬k3闹特，荣耀3c

**Comment by sum2012** [comment] 2016-01-12 00:23
i get one feedback
http://postimg.org/image/ddmh0akt7/
http://postimg.org/image/ht02iahfn/
http://postimg.org/image/eplebp49x/

**Comment by unknownbrackets** [comment] 2016-01-12 08:09
Any chance of adb logcat data from that situation?  Presumably gl_lost is not working out.

-[Unknown]

**Comment by sum2012** [comment] 2016-01-12 13:05
I am trying to let him to find out which git version started have problem

**Comment by sum2012** [comment] 2016-01-13 22:56
The bug also happen in v0.9.7
I think that cannot solve it

**Comment by unknownbrackets** [comment] 2016-01-17 04:57
I created a milestone which might be a better way to track this than editing posts and crossing out manually when things are fixed:

https://github.com/hrydgard/ppsspp/milestones

Included only regressions from v1.1.1.  Maybe we can include things that were regressed earlier, not sure...

-[Unknown]

**Comment by nfjorgebueno** [comment] 2016-01-19 01:18
I was playing a game of 2016 would not care to put me cheating tricks, but you also have to think not all, like me, have a new pc, so I put tricks to old games, get to my on-site the other is an act of humility, thanks for listening

**Comment by hrydgard** [comment] 2016-01-20 13:29
Getting closer! Almost out of issues in the milestone: https://github.com/hrydgard/ppsspp/milestones/v1.2.0

**Comment by sum2012** [comment] 2016-01-20 13:30
@hrydgard Can we update readme now ?

**Comment by hrydgard** [comment] 2016-01-20 13:45
@sum2012 I'll commit a first update of the readme shortly, then you can remind me of all that I missed :)

**Comment by hrydgard** [comment] 2016-01-20 15:50
@sum2012  https://github.com/hrydgard/ppsspp/compare/update-readme-1.2.0

**Comment by daniel229** [comment] 2016-01-20 16:06
Don't forget add the games Phantasy Star Portable 1 and 2(jp) to PixelDepthRounding list to avoid the flickering.

**Comment by MarcoEstevez** [comment] 2016-01-20 16:13
Wow, sounds like pretty big step forward, good job Guys.

**Comment by sum2012** [comment] 2016-01-20 20:13
@hrydgard please re-build font atlas (I have updated chinese in ppsspp-lang repository)

**Comment by hrydgard** [comment] 2016-01-20 21:19
@sum2012 , yeah, I'll rebuild the atlas soon. Release will probably be next week or so.

**Comment by sum2012** [comment] 2016-01-20 23:23
@hrydgard OK

**Comment by daniel229** [comment] 2016-01-21 00:17
English font atlas missing characters.https://github.com/hrydgard/ppsspp/issues/8423

**Comment by unknownbrackets** [comment] 2016-01-21 02:44
I think #8464 will be a little journey to fix correctly.  I think it means implementing the warm-up that I'm pretty sure Mpeg has (and Psmf has as well, and is implemented.)  I know it will break things though in the interim.

It's a shame, but we might temporarily release with it reverted?

#8423 should be rendering via Windows TrueType fonts.  I'm not not sure what's happening there, it might be a font fallback issue.  But the font atlas won't affect it, I don't think.

-[Unknown]

**Comment by hrydgard** [comment] 2016-01-21 08:25
I'm fine with temporarily reverting #8437 for the release.

**Comment by sum2012** [comment] 2016-01-24 09:18
During test adhoc "port offset", I test "Metal slug xx ULUS10495 Atrac sound will stop"
It is not happened in older version
#8498

**Comment by sum2012** [comment] 2016-01-24 13:07
I heard "monster hunter 2g" ,"monster hunter p3" crash when "after do mission,do saving", his computer is Android arm 64 .I don't have time to test both PC and Android.Hope this week can test

**Comment by KinCoded** [comment] 2016-01-24 17:53
Not sure when exactly but i think some time after 1.1.1's first release, Dissidia 012 Final Fantasy started crashing on Android. Quick way to reproduce: In quick battle mode start and finish a battle, then return to battle settings and start another battle. It should crash.

Also, this is more recent but, in Dissidia 012 Final Fantasy using today's build (v1.1.1-861-g0550cd3), also on Android, lots of parts of the menu have become black. And lots of text in battle doesn't appear, most prominently the text after battles that tells you what happened with your accessories and summons. Crashing still happens too.

Sorry if this isn't the place to post these.

**Comment by unknownbrackets** [comment] 2016-01-24 19:10
What device is this on?  Not all Android devices are the same.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-01-24 22:23
I got a SIGTRAP in the intro, so I commented out the BKPTs again, and didn't get any crash finishing two quick 1v1 battles.  Related to #8104 / #8328 possibly, then...

-[Unknown]

**Comment by KinCoded** [comment] 2016-01-25 01:06
Sorry, forgot to mention. Sony Xperia Z1 running stock 5.1.1

**Comment by hrydgard** [comment] 2016-02-01 13:01
The Dissidia stuff should be fixed now. All in all, we're getting quite close now, we just need to settle on some workaround for the bizarre depth problems we are seeing on older mobile GPUs...

**Comment by sum2012** [comment] 2016-02-01 13:09
My friend said to me that his phone play "Tokimeki Memorial 4" black screen in latest git version.I am working with him.

**Comment by sum2012** [comment] 2016-02-06 02:07
I get report that Samsung GALAXY S4 black screen when start ppsspp (before load iso)
in newest git version.
But I cannot get him directly contact.

**Comment by KinCoded** [comment] 2016-02-06 23:41
Can confirm, dissidia 012 stopped crashing. The graphical stuff in the menues is still there and in battles, on-screen messages still don't always show up. Would my phone (Xperia Z1) count as an older mobile? Is this a depth issue?

**Comment by unknownbrackets** [comment] 2016-02-07 00:57
I don't know for sure, but it's probably depth issues.  Adreno 330 ought to not have major problems.

Depending on model, the Galaxy S4 would have an Adreno 320, Adreno 330, or PowerVR SGX544MP3.  I'm not sure why that would blackscreen at start.

-[Unknown]

**Comment by KinCoded** [comment] 2016-02-07 10:04
ppsspp device settings says I'm an adreno 330 with API version v3.0.0 ES

**Comment by asbel123** [comment] 2016-02-09 08:05
i am still getting black screen issue on my samsung galaxy s6 edge if u press mutitasking u get black screen issue i go no issue old version of ppsspp new version of ppsspp made it worse.

 i cant play games properly on touch screen if u press mutitasking u get black screen on new version today. old version it was perfect for my phone.

**Comment by sergiobenrocha2** [comment] 2016-02-09 22:18
Regression on ARM builds: #8569

**Comment by sum2012** [comment] 2016-02-11 12:54
#7819

**Comment by ivan13342** [comment] 2016-02-12 16:37
What thoughts about JIT support on iOS 9?

**Comment by hrydgard** [comment] 2016-02-12 18:26
@ivan13342  We don't do official releases for iOS so even if there was a method discovered to do it, it is irrelevant here.

**Comment by ekkysw** [comment] 2016-02-13 10:03
Still crash in 1.1.1-937 on android

**Comment by hrydgard** [comment] 2016-02-13 10:22
@ekkysw how am I supposed to fix that if you don't give me any details?

Just the basics would be something:

  * What device?
  * When did it crash? On startup?

**Comment by unknownbrackets** [comment] 2016-02-13 14:32
I guess he means #8576?  Although it does not have a lot of details either.

-[Unknown]

**Comment by ekkysw** [comment] 2016-02-13 15:08
My device asus zenfone 4, when exit ppsspp ,i get message "ppsspp has unfortunately has stopped"

**Comment by unknownbrackets** [comment] 2016-04-10 21:04
I think this issue has run its course - we've released v1.2.0, v1.2.1, and even v1.2.2.  Closing.

Also, there's already a new milestone we can use to track regressions as they're reported:
https://github.com/hrydgard/ppsspp/milestones/v1.3.0

We can move things out of it later when we're preparing for a release, and we can always rename it to v1.2.3 or whatever version we want.

-[Unknown]

**Closed by unknownbrackets** 2016-04-10 21:04 UTC
