### ISSUE TITLE
Windows 10 Creators Update crashing

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9577] opened 2017-04-09 03:50 UTC
When i update windows 10 creators , it's crashing , using new git build
![image](https://cloud.githubusercontent.com/assets/11285640/24834517/5f0f7784-1d12-11e7-883f-5399b92756e3.png)

**Comment by hrydgard** [comment] 2017-04-09 08:23
I'll install Creator's Update on my secondary dev machine tomorrow and fix it up, if it reproduces.

**Comment by hrydgard** [comment] 2017-04-09 08:31
Can you check if this is dependent on GPU backend? You can go into memstick/PSP/SYSTEM/ppsspp.ini and change GPUBackend to 0, 1, 2.

**Comment by sum2012** [comment] 2017-04-09 10:45
We might need to make a batch file to directly change to OpenGL,DX9,DX11 engine

**Comment by hrydgard** [comment] 2017-04-10 07:22
I heard about crashes in Creator's related to the latest nvidia driver. Try to upgrade or maybe downgrade to the last one.

I'll try it myself soon too.

**Comment by Margen67** [comment] 2017-04-10 16:30
I'm on Windows 10 Pro x64 Insider Preview build 16170 and aren't experiencing any crashes.

**Comment by Silanda** [comment] 2017-04-14 18:34
There is a conflict between old versions of Rivatuner Statistics Server (included with some graphics card utilities like MSI Afterburner) and the Creators Update. Using any version of RTSS older than the new v7 release causes PPSSPP to crash when using the DX9 backend. I have no problems when using the v7 release.

**Comment by unknownbrackets** [comment] 2017-04-21 04:42
Is anyone able to reproduce this, and install Visual Studio to get a stack trace?  There are tutorials on building PPSSPP on Windows - it only requires free software.

-[Unknown]

**Comment by hrydgard** [comment] 2017-04-21 07:28
I can't reproduce. This has to be one of those driver conflicts you often see with new OS releases that eventually get cleared up with driver or OS updates. I don't think it can be PPSSPP's fault, so I'm closing.

**Closed by hrydgard** 2017-04-21 07:28 UTC
Labels: Platform-specific (Windows)
