### ISSUE TITLE
Dtm race driver 2 and 3

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10101] opened 2017-11-12 19:08 UTC
Dtm race driver have large thick lines across the screen. I ve tried everything but it's same problem. Like this picture: https://goo.gl/images/w6Ep9A   I saw you wrote 8 months ago:Probably broken geometry that gets discarded by the real PSP because the coordinates are way outside the guardband, and the PSP doesn't do proper triangle clipping. I'll send a pull request later with an experimental fix for D3D11 but it relies on undefined behaviour in vertex shaders to kill triangles, which isn't very nice. A "correct" fix will need geometry shaders.           When You will fix this hrydgard?:).

**Comment by unknownbrackets** [comment] 2017-11-12 19:09
This issue is being closed as a duplicate of #5001.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-11-12 19:09 UTC
