### ISSUE TITLE
Ppsspp iOS 9.3.3 JIT 

### ISSUE THREAD

**Issue by Jamesthecanaidian** [hrydgard/ppsspp#8874] opened 2016-07-25 17:15 UTC
I recently jailbroke iOS 9.3.3 using the pangs semi untethered jailbreak and noticed that ppsspp ran at the same speed as when I had it and I wasn't jailbroken. Is there any reason for this or is it because the jailbreak is still really be new and ppsspp doesn't work properly on it. It would be Mitch appreciated if someone has an answer. Thanks

**Comment by Jamesthecanaidian** [comment] 2016-07-25 18:02
@hyrgard

**Comment by Fadi5555** [comment] 2016-07-25 21:35
@hrydgard isn't any news about implementing JIT on jailbroken ios 9 with 64-bit devices?
Isn't any tricks to defeat KPP in order to patch kernel? I'm really hope the new jailbreak for ios 9.3.3 could defeat KPP. To could use JIT on 64 devices again.

Anyway I have a link for someone called @WilliamLCobb he recently created iOS version of dolphin emu. So he could bringing JIT on jailbroken and non-jailbroken devices. You can ask him about that.
It could really helpful to get his method and apply it on this project to could use JIT again.
You don't lose anything if you asking about his own way to implement JIT on ios 9 functionality

This is his link:
https://github.com/WilliamLCobb/GC4iOS

Good luck.

**Comment by Jamesthecanaidian** [comment] 2016-07-25 22:07
Thanks you for responding to my question

**Comment by Fadi5555** [comment] 2016-07-25 22:38
@hrydgard is really need to ask @WiliamLCobb about his own method to implement JIT for ios 9 64-bit devices.

**Comment by Jamesthecanaidian** [comment] 2016-07-25 22:40
Well I don't think it will happen on iOS 9.2 to 9.3.3 unless a untethered jailbreak comes out. That's the real problem.

**Comment by Jamesthecanaidian** [comment] 2016-07-25 22:41
Williamcobb did realease a game cube emulated for iOS that I'm about to try. hopefully that ends up running well.

**Comment by Fadi5555** [comment] 2016-07-25 22:49
@wiliamcobb has his own way to implementing JIT on ios 9 even with jailed devices

**Comment by Jamesthecanaidian** [comment] 2016-07-25 22:56
Well I hope your right.

**Comment by unknownbrackets** [comment] 2016-07-26 02:07
This issue is being closed as a duplicate of #8122..

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2016-07-26 02:07 UTC
