### ISSUE TITLE
Gta vice city stories 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10953] opened 2018-04-22 08:22 UTC
gta vice city stories keep shuttering , blackscreen sometimes and freeze ppppss app  , but still game sound running :(
I am using latest build version of ppsspp 
Plz any solution ?

**Comment by Jinzombie** [comment] 2018-04-22 08:34
try to reset the default settings?
you already report this issue in #10824

**Comment by hrydgard** [comment] 2018-04-22 08:44
Closing as dupe of #10824.

Also, in that one, please explain what you mean by "shuttering". Stuttering?

**Closed** 2018-04-22 08:45 UTC
