### ISSUE TITLE
all new builts has performance issue

### ISSUE THREAD

**Issue by tausifj15** [hrydgard/ppsspp#9243] opened 2017-01-27 08:33 UTC
Sir henrik since 283 all builts have performance issue pls fix it

**Comment by LunaMoo** [comment] 2017-01-27 08:59
One report is enough. Closing as duplicate of #9219

 Also note, if you want to be helpful, you should check earlier builds and find which commit actually caused your "performance drop". Removing DX11 dependency from windows was definitely not affecting any android or multiplatform code.

**Closed by LunaMoo** 2017-01-27 08:59 UTC
