### ISSUE TITLE
Broken fonts for Gran Turismo for software renderer

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#15802] opened 2022-08-07 08:17 UTC
### Game or games this happens in

UCUS-98632 - Gran Turismo

### What area of the game

Main Menu 

### What happens

Fonts in Gran Turismo is broken when software rendering is used
![Screenshot (14)](https://user-images.githubusercontent.com/37503397/183281639-82c3bb00-a05f-41ef-9ade-94dc2313a987.png)

### What should happen

The font working fine in hardware renderers
![Screenshot (15)](https://user-images.githubusercontent.com/37503397/183281673-ff4e378c-1348-4dcd-b076-96b9c7dde4fe.png)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GTX 1050Ti

### PPSSPP version affected

v1.13 and newer

### Last working version

v1.12.3

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by MojoJojoDojo** [comment] 2022-08-07 09:36
I swear this game gonna be the one with most issues opened here soon lol.
The fonts also cause issues with performance on hardware renderer if I am not mistaken...

**Comment by Gamemulatorer** [comment] 2022-08-07 09:53
> I swear this game gonna be the one with most issues opened here soon lol. The fonts also cause issues with performance on hardware renderer if I am not mistaken...

Here 👉https://github.com/hrydgard/ppsspp/issues/11244 and https://github.com/hrydgard/ppsspp/issues/13460

**Comment by unknownbrackets** [comment] 2022-08-07 15:03
Can you include a GE frame dump?  I think it's fine if it's made while using hardware or software, as long as it shows the fonts that render wrong.

This is probably some annoying hazard where rendering needs to sync before some copy.

-[Unknown]

**Comment by Panderner** [comment] 2022-08-07 16:53
Here:
[UCUS98632.zip](https://github.com/hrydgard/ppsspp/files/9277167/UCUS98632.zip)

**Comment by unknownbrackets** [comment] 2022-08-07 21:41
Unfortunately, the dump isn't reproducing it.

I think this game block transfers data into texture VRAM, which it then references.  Might need to track pending read hazards, which I think I moved away from due to perf...

My assumption is that it's:
 * Block transferring to a texture.
 * Drawing from that texture to the screen.
 * Block transferring again (which doesn't flush.)
 * Drawing from that texture again (which still doesn't flush, because it's not tracked as a write region.)

Maybe the best solution is to track pending reads, separate from writes.  It'd have to do all mip levels, but could be updated just when texture params are dirty...

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-08-21 07:29
Can you try this again with the artifacts from #15873 or after it is merged?  I think that will fix it, based on how I understand this rendering to work.

-[Unknown]

**Comment by Panderner** [comment] 2022-08-21 09:33
It's fixed now:
![Screenshot (27)](https://user-images.githubusercontent.com/37503397/185784802-f5caf484-6d28-42e1-98b1-9ab118b131b1.png)

**Comment by unknownbrackets** [comment] 2022-08-21 14:02
Thanks for validating.

-[Unknown]

**Closed by unknownbrackets** 2022-08-21 14:03 UTC
Labels: Software Rasterizer
