### ISSUE TITLE
(Feature Request) Built-in Mesh extractor like in JPCSP

### ISSUE THREAD

**Issue by Back2Life888** [hrydgard/ppsspp#13870] opened 2021-01-04 10:57 UTC
JPCSP is very broken but there is one feature that it has.. A feature that I want in PPSSPP so badly.. The Mesh extractor.. It basically extracts a mesh that is rendered from a PSP game and extracts it as a .obj file (Wavefront).. It will also extract the textures that are rendered with the mesh.. Now here is the problem in JPCSP.. My mesh won't extract properly.. Its not the feature that is the problem but my game, Ridge Racer's emulation itself is the problem because some people had luck on extracting meshes on other games but Ridge Racer is broken.. When I extracted it, it has a weird shiny mesh (Somekind of shader mess) and there where missing texture mappings for the wheels.. Same thing happens in-game.. The car has a broken shader (This time, less shiny but shiny none the less) and bugged wheels (Not missing texture, but glitched texture).. So its the game's emulation's problem.. There is 1 easily fixable bug in it which is a tilted mesh.. Not much of a problem for me.. The mesh is tilted in a very weird way.. It looks like my car is doing a backwards wheelie.. So please Hrydgard, add this feature..

**Comment by LunaMoo** [comment] 2021-01-04 13:50
Closing this as a duplicate of #2825

**Closed by LunaMoo** 2021-01-04 13:50 UTC
Labels: Feature Request
