### ISSUE TITLE
[iOS 14] FFMPEG video not displaying correctly

### ISSUE THREAD

**Issue by yoshisuga** [hrydgard/ppsspp#13725] opened 2020-11-29 17:50 UTC
### What happens?

On games with FMV like Crisis Core, Parasite Eve 3 - the full motion video segments display color bands.

![93749106-0d4bed00-fb95-11ea-9ddb-329417637374](https://user-images.githubusercontent.com/564774/100549415-eb1abf00-3216-11eb-9abf-175b05e285c6.jpeg)

I mentioned this in #13451 but this issue seems distinct enough that I feel it's better tracked in a separate issue separate from some texture issues observed in that issue.

### What *should* happen?

The movies should be rendered correctly. This seems to only occur on iOS 14. I tried re-compiling the ffmpeg library in the project `ffmpeg` directory using the latest iOS SDK, and using the `.a` binaries - and it still displays the color bands.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Tested on: 

iPhone 11 Pro, iOS 14.2 - displayed color bands when playing video
iPhone XS Max, iOS 13.3 - displayed correctly

PPSSPP version: `v1.10.3-1269-gb60250fca`

**Comment by hrydgard** [comment] 2020-11-29 18:01
Duplicate of #13451

**Closed by hrydgard** 2020-11-29 18:01 UTC
Labels: Platform-specific (iOS)

**Comment by yoshisuga** [comment] 2020-11-29 19:47
Hi! I understand closing the issue but does the slimmed down ffmpeg library
used by PPSSPP need updating to a later version? I’d like to help out with
this and was wondering what needs to be done to support this (how it was
slimmed down, etc). Thanks!

**Comment by hrydgard** [comment] 2020-11-29 19:55
I don't think it needs any updating. It's slimmed down by build script excluding codecs, but it supports exactly what we need and there are no improvements needed. We've tried to upgrade to newer ffmpeg versions before and always hit some sort of breakage, so we've stopped trying.
