### ISSUE TITLE
Crashing while loading save states

### ISSUE THREAD

**Issue by Demi-Fiend** [hrydgard/ppsspp#8877] opened 2016-07-30 23:27 UTC
I currently am experiencing issues with version 0v1.2.2-786-gfa3f219 . As the title reveals i cannot load any save states and i have restored all my settings to the default setup. I am using an iphone 5s jailbroken on ios 9.3.3 and i have 1.8 gb of storage left over. Thank you for your time and i hope this issue is resolved.

**Comment by hrydgard** [comment] 2016-07-31 08:33
If you make a brand new savestate, can you load that?

**Comment by Demi-Fiend** [comment] 2016-07-31 21:03
No, if i make a new save state it crashes and if i try to load the game
without using any save states it freezes after the intro

**Comment by unknownbrackets** [comment] 2016-08-04 03:01
This issue is being closed as a duplicate of #8855.

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2016-08-04 03:01 UTC
