### ISSUE TITLE
Reported: Kingdom Hearts Birth by Sleep freezes in cutscenes

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7406] opened 2015-02-02 09:12 UTC
http://forums.ppsspp.org/showthread.php?tid=14508

Might be Android-only.

I've gotten one email about it too so it doesn't seem like an isolated issue..

**Comment by daniel229** [comment] 2015-02-02 09:52
Look fine on PC,any savefile provided.

**Comment by brujo5** [comment] 2015-02-02 16:47
more issues for windows 

http://forums.ppsspp.org/showthread.php?tid=1327&pid=101879#pid101879

**Comment by daniel229** [comment] 2015-02-02 17:17
Try 2 of Disney town games are fine here with openGL and D3D.
![01](https://cloud.githubusercontent.com/assets/3481559/6005053/57b48040-ab42-11e4-8e44-6eb2ef434a56.png)
![02](https://cloud.githubusercontent.com/assets/3481559/6005052/57b32984-ab42-11e4-95cc-0068d4d14d7e.png)

**Comment by brujo5** [comment] 2015-02-02 17:50
maybe specific gpu issue

**Comment by unknownbrackets** [comment] 2015-12-29 17:35
Does this still occur?  Is it different from #5800?

-[Unknown]

**Comment by edelgard** [comment] 2016-09-01 01:00
The specified thread does not exist

KILL ME

**Comment by unknownbrackets** [comment] 2018-08-25 19:42
Closing as a duplicate of #5800.

-[Unknown]

**Closed by unknownbrackets** 2018-08-25 19:42 UTC
Labels: Platform-specific (Android)
