### ISSUE TITLE
Stuck issue with Mega Man Maverick Hunter X 

### ISSUE THREAD

**Issue by hdd60311** [hrydgard/ppsspp#3318] opened 2013-08-22 10:35 UTC
Reported form http://forums.ppsspp.org/showthread.php?tid=384&pid=41935#pid41935
when run this game it freezes at ACCESS page, press start button can continue it.

![1](https://f.cloud.github.com/assets/5089290/1007989/6826afe8-0b16-11e3-8209-376f7585f75b.jpg)

**Comment by sergiobenrocha2** [comment] 2015-01-28 00:44
It still stucks in git version, ubuntu 14.04 64-bits. The start button tip does not work, and you have to kill ppsspp in system monitor.

**Comment by sum2012** [comment] 2015-01-28 22:19
I test no problem
v0.9.9.1-1614-g2b0b1a5-windows-amd64
https://gist.github.com/sum2012/fd6503d6a9a2711825c9

**Comment by thedax** [comment] 2015-01-29 06:34
With default settings it still hangs on the Accessing screen for me until I press start. What settings are you using?

**Comment by sum2012** [comment] 2015-01-29 11:26
I mean that " start button tip does not work,"  is work to me

**Comment by sergiobenrocha2** [comment] 2015-01-29 14:08
Default settings (removed ~/.config/ppsspp/), with these cards (with and without using bumblebee):

VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
3D controller: NVIDIA Corporation GK208M [GeForce GT 740M] (rev ff)

And it hans on the accessing screen. How press start work for you guys?

Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
Linux 3.14.30-031430-generic #201501271200 SMP Tue Jan 27 17:02:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by WeaponsHold** [comment] 2015-02-27 14:29
Try these settings... http://ppsspp-emulator.wikia.com/wiki/Mega_Man:_Maverick_Hunter_X

**Comment by sergiobenrocha2** [comment] 2015-03-01 02:02
It's working now in 1.0.1.

**Comment by daniel229** [comment] 2015-03-01 13:00
But,still have to press START button to skip that hanging video.

**Comment by sum2012** [comment] 2015-03-29 00:28
v0.8-32-gf1659a2 no problem
log:https://gist.github.com/sum2012/1d01b084488ee8ff9cd8
Have this log after "access" screen
sceMpegRingbufferPut(): unable to enqueue all added packets, going to overwrite some frames.

**Comment by sum2012** [comment] 2015-03-29 01:29
v1.0.1-233-g13c08ab log:
https://gist.github.com/sum2012/2765eb5e33ab2d94b112

good
v0.8.1
bad
v0.8.1-37-ged47eac
compare:
https://github.com/hrydgard/ppsspp/compare/v0.8.1...v0.8.1-37-ged47eac

I might need to reinstall VS2010 to more bisect

**Comment by sum2012** [comment] 2015-03-29 04:04
JPCSPTrace log:
https://gist.github.com/sum2012/e5f332933cf121d2f4af/raw/gistfile1.txt

@unknownbrackets 
Real psp return sceMpegRingbufferAvailableSize to 0  !!

**Comment by unknownbrackets** [comment] 2015-03-29 04:13
Do note that because the call can flood logs, we don't log duplicate sceMpegRingbufferAvailableSize return values.

I had a lead at one point on what this might be - I can't remember if it was from a log or something, but I think sceMpegRingbufferPut rejects invalid packets, and we don't.  Not sure if that would actually fix this.

Anyway, you can see in the log that it returns an error sometimes:
sceMpegRingbufferPut 0x9FB7464, 0x20, 0x2 = 0x806101FE

-[unknown]

**Comment by sum2012** [comment] 2015-03-29 04:32
Thanks @unknownbrackets  
I will install back VS2013 to test this

**Comment by unknownbrackets** [comment] 2015-03-29 05:27
FYI, you can install both at the same time.  I have 2008, 2010, 2012, and 2013 I think... haven't really used 2008 for a while, should probably uninstall it...

-[Unknown]

**Comment by sum2012** [comment] 2015-03-29 06:43
@unknownbrackets This commit work but make other games have problem
https://github.com/sum2012/ppsspp/commit/7662f3e8fb72f3478a084737c94ab1246c23a581
Log: https://drive.google.com/file/d/0B3OaSdeV0L8kZnFzbUpPMWtuYTA/view?usp=sharing

**Comment by unknownbrackets** [comment] 2015-03-29 06:49
Hmm, interesting.  Well, there are probably other rules to how exactly it returns the error.  I think the best way to understand it will be using a PSP and sending different data at it to see when it responds with the error code.

-[Unknown]

**Comment by daniel229** [comment] 2015-03-29 08:36
The versions around 0.9.1-716-g86caa70 may working sometime.
It randomly happens thses
1.stuck on access screen.
2.skip all videos.
3.all videos work.
![01](https://cloud.githubusercontent.com/assets/3481559/6884724/8d004e86-d631-11e4-8d19-c6a35a6b4766.png)

**Comment by sum2012** [comment] 2015-04-15 13:17
@unknownbrackets I give log to jpcsp.
it fixed in https://github.com/gid15/jpcsp/commit/f2a701b5f425f2ad67e012e9c423a1d35ffd3e93
and https://github.com/gid15/jpcsp/commit/8d10998a784ccac3be6b7c8ca3f9a9b372df3fea

**Comment by unknownbrackets** [comment] 2016-01-29 07:00
With some testing, I've determined that this behavior varies by mpeg version.

The behavior here changed in version 1.05.  Versions 1.01 - 1.04 all exhibit this behavior, but I've only tested 1.05 and 1.10 for the latter.  After 1.05, it seems the mpeg library was always part of firmware.  But it doesn't seem the sdkver affects this; I think all versions on firmware don't do this validation.

Based on my tests so far, sending even one invalid packet at the start is enough to get the error code back.  But it can also happen with valid packets - it's all about alignment.

If I have a buffer of 512 packets, and it's empty, I can add up to 1024 packets (yes, really), no error.  It will wrap around and fill the buffer twice.  No errors.  I haven't checked decoding, so it's either the offset into the ring or # of packets, but if that offset + the number I add exceeds 2 * capacity, it generates this error pretty consistently (regardless of size.)

Note that, it still calls the callback, and still reads in the packets.  I can read in 2048 packets, and it'll ask for all of them.  It's only a problem if the callback actually (with multiple iterations, of course) returns >= 2 * capacity - offset.

Anyway, I'm not sure if this latter behavior is important here, although it's the more interesting one.  What seems to happen in this log is that there's space, and it rejects the packet.  I can reproduce this one reliably by adding a single garbage data packet.

-[Unknown]

**Comment by sergiobenrocha2** [comment] 2016-02-18 22:57
It's completely hangs now with 1.2.1

**Comment by sum2012** [comment] 2016-02-19 18:58
@sergiobenrocha2  Do you mean start button cannot skip ?

**Comment by l12436** [comment] 2016-03-12 10:36
according to my test, start button can not skip..., complete stock right there.

**Comment by sum2012** [comment] 2016-03-12 13:10
Press "space bar" for keyboard for pc

**Comment by l12436** [comment] 2016-03-12 13:25
it will immediately stock when it show access. press space bar is not work. event esc is not working.

**Comment by sum2012** [comment] 2016-03-12 13:29
What is your os ? windows , linux

**Comment by l12436** [comment] 2016-03-12 13:34
linux 
ubuntu 14.04.4
kernel 4.2

**Comment by sum2012** [comment] 2016-03-12 13:36
So it don't work for linux.
We need to wait @unknownbrackets fix it.

**Comment by l12436** [comment] 2016-03-12 13:47
OK, thanks

**Comment by sonikokaruto** [comment] 2016-05-03 18:19
Exact same thing is happening on the libreto version for the raspberry pi

**Comment by klyoungblood** [comment] 2016-06-01 07:00
The Pi thread on the forums mentioned that SDL only polls inputs on video updates, which means SDL-based version including Linux and Pi can never register the button press to skip the broken video.

**Closed** 2016-06-05 11:44 UTC

**Comment by sum2012** [comment] 2016-06-05 14:24
v1.2.2-658-gce8d2be-windows-amd64 good log:
https://gist.githubusercontent.com/sum2012/d91a5d6c8459b7e03db704ecdf0b1cab/raw/63e0f90094b8ecb0fe84d48dc5f5bf5a3fa299b1/gistfile1.txt

**Comment by Voltkraken42** [comment] 2016-06-24 17:43
I have a similar issue on Openemu (core version 0.9.9.1) on Mac. It tells me about the autosave function and then goes to accessing, but it's just a static picture. How could you help me with this? (I'm not that good with changing code, and Terminal doesn't work on my mac.)

**Comment by unknownbrackets** [comment] 2016-06-24 18:22
There's no workaround for SDL, afaik.  This has been fixed in a new version, so v0.9.9.1 will forever not work.  It will be in something like v1.3 (which hasn't been released yet.)  If you want it now, you need to use a git build (check the downloads page.)

-[Unknown]
