### ISSUE TITLE
Kenka Bancho : Badass Rumble Infinite loading screen when accessing moves menu

### ISSUE THREAD

**Issue by untungkasarung** [hrydgard/ppsspp#14131] opened 2021-02-13 16:17 UTC
Everytime I try to access the moves menu, the loading screen becomes faster than usual -the loading screen contains something like pro tips and japanese vocabs and the transitions become noticably faster when loading the menu- and seems endless.

**Comment by Panderner** [comment] 2021-02-13 16:20
@untungkasarung please check if your iso is corrupted.

**Comment by untungkasarung** [comment] 2021-02-13 16:24
> @untungkasarung please check if your iso is corrupted.

Do I have to redownload or what?

**Comment by Panderner** [comment] 2021-02-13 16:31
> > @untungkasarung please check if your iso is corrupted.
> 
> Do I have to redownload or what?

@untungkasarung check your ISO size or crc.

**Comment by unknownbrackets** [comment] 2021-02-13 16:32
If the disc CRC is good, does this work in previous versions?  Or has it been happening for a while?

-[Unknown]

**Comment by sum2012** [comment] 2021-02-13 20:48
I remember you have changed my scePowerSetClockFrequency delay value
This game really have problem
Old history: https://github.com/hrydgard/ppsspp/issues/4523#issuecomment-244820733 
I will test again.

**Comment by sum2012** [comment] 2021-02-13 21:53
I can confirm again, bad dump would accessing moves menu bad
You can check your iso by extract the iso.
It will raise error on extract PSP_GAME\USRDIR\TESTDATA\WAZAEDIY.LZS
on bad dump.
![1](https://user-images.githubusercontent.com/2177532/107862644-021d9480-6e89-11eb-9bb8-ab98642516e4.png)

**Comment by LunaMoo** [comment] 2021-02-14 00:18
Duplicate of #12312 and yes it's just a bad dump, not an issue. Please dump the game again, if you downloaded a pirated copy, it's just bad.
 Closing.

**Closed by LunaMoo** 2021-02-14 00:18 UTC
Labels: Not a bug
