### ISSUE TITLE
Everybody's Golf 2: Screen goes black at end of swing (user-reported)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#6655] opened 2014-07-30 20:10 UTC
Javier writes:

> I found a graphic glitch while playing everybody's golf 2: when u fill the power bar to shoot the screen goes black until the power bar returns to its initial position, i tried with the latest builds from v. 0.9.9 and still happens and i tried to configure the emulator in many ways but with the same result.
> Now im playing it with this build 0.9.8-658-ga127ca8-windows-x86 and the issue is completely gone.

**Comment by unknownbrackets** [comment] 2015-12-24 17:36
Does the issue still happen in OpenGL today?  Can you try identifying the issue with the GE debugger?

https://github.com/hrydgard/ppsspp/wiki/How-to-find-a-graphic-issue-with-the-GE-debugger

-[Unknown]

**Comment by FlatOutPS2** [comment] 2016-04-11 12:31
OpenGL now works as well while simulate block transfer is on.
There is slowdown on this screen with D3D9, and with both backends (HUD) elements and sometimes the whole screen flicker while putting. It does a screen grab and shows the screenshot so it can run at 60fps while you power the swing, but it looks like it doesn't properly clear the previous screenshot causing it to flicker between the two. Though it's fine anywhere else on the course before you putt.

**Comment by unknownbrackets** [comment] 2019-03-10 06:10
Does this still happen?

If you open the GE debugger on Windows, and mash Record while putting, can you capture a frame that is black?

How to know if you've captured it:

1. After doing the above, you'll get a bunch of files under PSP/SYSTEM/DUMP.
2. You can drag them into PPSSPP to view them.
3. If you find one that displays as black, but the file is larger than 2 KB, then it's super useful.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-03-18 02:58
I tried the [US demo](https://report.ppsspp.org/game/NPUG70014_1.00), which does not blink/flicker in this case.  But I'm assuming that just means this doesn't reproduce in the demo, based on #12290 which I think might be a duplicate.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-03-23 02:01
I suspect this may be an issue only with skip buffer effects or block transfer disabled.  I think with #12746, we should consider this fixed.  At most maybe we add something to compat.ini about the game requiring those settings.

-[Unknown]

**Comment by nassau-tk** [comment] 2020-03-24 13:11
@hrydgard 
@unknownbrackets 

I tested ”Minna no Golf Portable2 (Japan)” ［UCJS10075］.
It is not happen the issue.

This issue will soleved by build of v1.9.3-529-ga95f3111c.

I tested at build of v1.9.3-548-gedbd01807.
It was tested several times, but a problem has not occurred.

By reference.

**Comment by nassau-tk** [comment] 2020-03-24 13:13
Oops, I tested on Android.

**Comment by unknownbrackets** [comment] 2020-03-24 14:03
Thanks, I'm going to close this then.

-[Unknown]

**Closed by unknownbrackets** 2020-03-24 14:03 UTC
Labels: GE emulation
