### ISSUE TITLE
Graphical issues in Dragon Ball Z Tag Team iOS 8

### ISSUE THREAD

**Issue by tleple** [hrydgard/ppsspp#8055] opened 2015-10-11 22:00 UTC
When starting a training fight in the game, the environment graphics glitches hardly, showing a black image.
Settings bellow

 ppsspp 1.1 version 

![image](https://cloud.githubusercontent.com/assets/7698892/10419313/358e479e-704a-11e5-9cce-fe0d1ae9d336.jpg)
![image](https://cloud.githubusercontent.com/assets/7698892/10419314/35c401ae-704a-11e5-9fa6-56b3ed75974f.jpg)
![image](https://cloud.githubusercontent.com/assets/7698892/10419315/35c9d502-704a-11e5-8374-76f8d9eb7bc0.jpg)
![image](https://cloud.githubusercontent.com/assets/7698892/10419316/35cfb404-704a-11e5-88bc-8f84545607f5.jpg)

**Comment by unknownbrackets** [comment] 2015-12-23 20:16
Closing as a duplicate of #6168.

-[Unknown]

**Closed by unknownbrackets** 2015-12-23 20:16 UTC
