### ISSUE TITLE
zill o'll infinite plus bloom effect corrupts on new builds (vulcan)

### ISSUE THREAD

**Issue by Kitsu-neechan** [hrydgard/ppsspp#11464] opened 2018-10-10 06:51 UTC
pics say it all.

![uljm05410_00573](https://user-images.githubusercontent.com/27159805/46717451-baf7b700-cc70-11e8-9032-bdaf3d6f6f5a.png)
![uljm05410_00574](https://user-images.githubusercontent.com/27159805/46717452-bdf2a780-cc70-11e8-81fc-c84bb9e40d96.png)
![uljm05410_00575](https://user-images.githubusercontent.com/27159805/46717454-c0ed9800-cc70-11e8-9755-41592cf6d45a.png)
![uljm05410_00576](https://user-images.githubusercontent.com/27159805/46717455-c34ff200-cc70-11e8-9336-b2c1cfc2094f.png)

the purple bloom glow is as it should be, but as you see, it's now full of square shaped "holes" that flicker allover the screen.

i noticed this started happening with build 1.6.3-526-g6690794, though i have not updated my sources ever since #9574 was solved, (the game ran perfect after that) so the exact point when this started happening is unknown to me. 

Im still enjoying the bug that prevents me from changing the gpubackend so can't test on other backends, (now it just closes ppsspp, doesnt crash it) but by all means, this should work, as it did on earlier builds. Not sure what changed.

**Comment by hrydgard** [comment] 2018-10-10 08:03
It would be super helpful if you could go back and try some builds to narrow down when this started happening. Also, what GPU is this on?

**Comment by Kitsu-neechan** [comment] 2018-10-10 08:07
i'll pull out a few builds and see what happens.
using GTX 980TI, win7 64bit, driver 372.90 system configuration has not changed ever since aforementioned timeframes. no updates, no new drivers, only new ppsspp build.

**Comment by Kitsu-neechan** [comment] 2018-10-10 08:46
well, i tried all of them.

it breaks between 1.5.4-708 and 1.5.4-711 (buildbot had no builds between these 2)

v1.5.4-701-ga966403de	working
v1.5.4-704-g33a1e6a08	working
v1.5.4-708-g452e29947	working
v1.5.4-711-gce18364a1	broken
v1.5.4-725-g826e8a689	broken
v1.5.4-753-g2a565199b	broken
v1.5.4-801-gc2d5ce6c3	broken
v1.6			broken
1.6.3_stable		broken
v1.6.3-510-gbd678d4f4 	broken
v1.6.3-536-g7b34eaa1f	broken

**Comment by hrydgard** [comment] 2018-10-10 09:00
So it's my barrier changes, https://github.com/hrydgard/ppsspp/commit/3e7723ea6d4e94d327fe1e53e0dc4a70c00a3d4b or https://github.com/hrydgard/ppsspp/commit/ce18364a150d3590408a48522337a907e4b2c09d . Hmmm....

**Comment by hrydgard** [comment] 2018-10-10 09:00
by the way, regarding "the bug that prevents me from changing the gpubackend", did you report that? Because that's also bad....

**Comment by Kitsu-neechan** [comment] 2018-10-10 09:07
never did so far. it only ever pops up in my head whenever i have to deal with bugreports since you and unknownbrackets always make me test things on things that are not vulcan, aside that i dont touch it, since vulcan is awesome <3

i will have to toy with what the heck actually causes it since it seems to be behaving more irrationally only on the builds i compile myself. (it does occur on stable builds too though.)

I can file a bug report from it if you wish though.

**Comment by hrydgard** [comment] 2018-10-10 09:10
Please do. Also, make sure when you compile your own builds that you're making Release builds, the Debug builds have a feature where they try to switch backend without restarting but it fails a lot for various reasons. Been thinking of getting rid of it.

**Comment by Kitsu-neechan** [comment] 2018-10-10 09:18
i will do so in a while once i play with it more to get some actually accurate information about it's behavior

**Comment by unknownbrackets** [comment] 2018-10-10 14:14
I still think it's much better when testing a small graphics issue not to have to reconnect the debugger 4 times.  Yes, Vulkan seems to die when GL has been inited for stupid driver reasons, but...

Anyway, it actually happens whenever the debugger is connected, so e.g. even in release builds.

-[Unknown]

**Comment by hrydgard** [comment] 2018-10-11 07:39
@Kitsu-neechan closing this one too, as mentioned in #11465 - confirmed to work on the latest drivers.

**Comment by Kitsu-neechan** [comment] 2018-10-11 07:40
yeah, i'll let you know if there's something further but a quick run on the game seemed to be fine.

**Closed by hrydgard** 2018-10-11 07:39 UTC
Labels: Vulkan
