### ISSUE TITLE
Keyboard problem on ppsspp emulator combo 

### ISSUE THREAD

**Issue by Turllamagoat** [hrydgard/ppsspp#8616] opened 2016-02-29 15:06 UTC
Ok,hi i have a problem with my keyboard one's i play a fighting game,you know like Tekken,DB,Guilty Gear,soul calibur and more.....well the problem is that i cant use a combo together for example:in tekken there's a combo where u need to press ->->circle and square together but it wont work  plz help me i really love this fighting game its really awesome i hope there is someone who can help me

**Comment by sum2012** [comment] 2016-02-29 15:11
Control -> Combo key setup

**Comment by LunaMoo** [comment] 2016-03-01 00:40
If the issue is about pressing some keys together on keyboard, that's not really an issue with emulator, most keyboards have limitation in their construction, if you need more info on that just google for keyboard ghosting or n-key rollover. If that bothers you, just map your keys differently or buy a controller designed for games - like a gamepad or some absurdly expensive keyboard which doesn't suffer from that.

 We don't need anything like separate combo feature for keyboards - with physical controllers you can just use control mapping which as far as I remember always allowed mixing keys/buttons any way you like which includes setting 1 input key for many different buttons or different inputs for same button. Not really sure if we have any limitations to that(other than mouse stuff) as I rarely change my keys, but it certainly can be used for key combinations.

**Comment by unknownbrackets** [comment] 2016-03-01 03:12
Right, just set some other keyboard key to map to both square and circle.

The important thing to understand is that this is a physical / electrical limitation of your keyboard.  Nothing any software can do will fix it - you either need to use a different input device or different keys.  Your keyboard is just not capable of handling those buttons being pressed simultaneously.

Closing based on that.

-[Unknown]

**Closed by unknownbrackets** 2016-03-01 03:12 UTC

**Comment by Turllamagoat** [comment] 2016-03-01 10:29
thx guys hope this works!

**Comment by Turllamagoat** [comment] 2016-03-01 10:37
oh no its still not working but i found out that once you use the arrow's and change the square,circle,triangle and x into 1,2,4,5 the combo's can work! but some combo's cant work...........well looks like i wont be having fun playying fighting games.......

**Comment by unknownbrackets** [comment] 2016-03-02 02:22
Go to the controls settings, and press `+` on "Circle", then press "1".

Next, press `+` on "Square".  Press "1" again.  Don't worry - this won't "erase" the circle 1.

Now, when you press "1", it will press BOTH square AND circle at the same time in the game.

-[Unknown]

**Comment by Ollie-B** [comment] 2018-04-02 07:37
I cant press the R key, the x key and analog key on my ppsspp, I can't enjoy my football games
