### ISSUE TITLE
Is this possible to program PPSSPP to play all sounds except background music? (feature request)

### ISSUE THREAD

**Issue by buruto** [hrydgard/ppsspp#11439] opened 2018-10-01 17:16 UTC
I want to emulate all sounds except background music, is this possible?

**Comment by LunaMoo** [comment] 2018-10-02 02:13
No it's NOT possible, for most games sounds are just sounds there's no difference between music and sfx or voices for theSpeed emulator and you can only do that by modding games ie. via cwcheat, also closing as a duplicate of #7376

**Closed by LunaMoo** 2018-10-02 02:13 UTC
