### ISSUE TITLE
Surf's Up - Sound is weird under certain circumstances - 1.10.2

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#13148] opened 2020-07-14 16:04 UTC
Hi,me *again*.I found some really amusing glitch/bug where sounds just behave weird.For example,when in menu too long,it begins to behave really weird,same when sound in game is turned to Ambience.Happened on my phone,phone of a friend and PC of a friend

Edit:**(Thanks to Reddit user u/lusid1,without him me re-discovering Jukebox mode wouldn't be possible,and of course further investigation,see latest comment,and once again credits to him,not me)**

EDIT(hydgard): It was also reported that the volume appears too low in this game.

TIA

**Comment by boy13epic** [comment] 2020-07-14 16:05
ok

**Comment by Gamemulatorer** [comment] 2020-07-14 16:17
Duplicate of #13088

**Comment by EX-e-LD** [comment] 2020-07-14 16:19
How is this duplicate?From what i understood that is quiet sound,not sound like demon screaming from hell.

**Comment by EX-e-LD** [comment] 2020-07-23 08:41
@hrydgard It is 9 days since i opened and still no feedback?Can this get looked into,and if you need i can provide you GE Dump.

TIA

**Comment by hrydgard** [comment] 2020-07-23 10:00
Definitely seems like two different issues, not a duplicate of that one.

Sound issues are tricky to debug, GE dumps won't help. I'll mark it for investigation though.

**Comment by EX-e-LD** [comment] 2020-07-23 11:03
Also yes,whoever opened that issue was right,sound even in game is too quiet,compared to Ridge Racer which.To be sure,in-game and emulator settings were to limit,so it seems it is issue too.Also when that "glitch" appears,it is louder than any OST in game,so i hope that would be fixed for anyone who plays this game actively.

**Comment by EX-e-LD** [comment] 2020-07-23 16:44
Also,this *may be* little off-topic,but can you check when investigating what does Jukebox sound option mean.I read somewhere that some PSP games support custom in-game music,here is uncomplete list:https://gamefaqs.gamespot.com/boards/918340-playstation-portable/70079845
Since i can't get to find Surf's Up manual no where,and i already did made MUSIC folder in memstick folder as well,converted to  needed Hz i believe,and it still didn't work,so is that bug as well?I'm really curious for that at the moment,and if someone could help me solve this,i would be grateful.

TIA

**Comment by EX-e-LD** [comment] 2020-07-24 05:24
@hrydgard Here,i also made recording of a glitch,it may help you out:
[Surf's Up Sound Glitch.zip](https://github.com/hrydgard/ppsspp/files/4970278/Surf.s.Up.Sound.Glitch.zip)

**Comment by EX-e-LD** [comment] 2020-07-27 06:58
Thanks to u/lusid1,i now have way to test does this bug also appear at the "Jukebox Mode",and i will be sure to report my findings on this one.

This is procedure for the custom music,**once again** thanks to u/lusid1:
- Jukebox Mode: Play MP3s from the Memory Stick Duo
 - MP3 Specifications:
 - Format: MP3
 - Directory: MUSIC/SURFSUP
 - Supported Bitrates: 32,40,48,56,64,80,96,112,128,160,192
 - Sampling Rate: 44.1khz only
 - Channels: mono or stereo
 - NOTE: The first 20 MP3s from the directory will be added to the Jukebox playlist`

**Comment by HiImBrala** [comment] 2020-07-29 08:56
Woah,this is big!I never had a chance to use the "Jukebox Mode",and this seems really neat as i couldn't find anything on web related to this.I'm sure gonna try it.

**Comment by Gamemulatorer** [comment] 2022-01-27 15:48
I cannot reproduce this issue.
Safe to close this?
![Screenshot_2022-01-27-23-47-57-186_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/151393537-14b66f42-54b3-430a-8a17-65baad28b989.jpg)

**Comment by unknownbrackets** [comment] 2022-01-27 17:13
Okay, makes sense that the recent changes may have fixed this.  I'll close.

If anyone's still seeing this issue, please comment and we'll reopen.

-[Unknown]

**Closed by unknownbrackets** 2022-01-27 17:13 UTC
Labels: Audio
