### ISSUE TITLE
sceKernelReferThreadStatus unknown syscall

### ISSUE THREAD

**Issue by Raw-man** [hrydgard/ppsspp#14153] opened 2021-02-16 03:57 UTC
### What happens?
I'm compiling a PRX plugin with the following flags:

`USE_KERNEL_LIBC=1
USE_KERNEL_LIBS=1`

In my code, I'm using the sceKernelReferThreadStatus function but in PPSSPP it shows up
as "syscall unknown", which seemed strange since other functions like sceKernelLoadModule worked fine.  Removing those flags fixes the issue but unfortunately breaks things on an actual PSP.

### What *should* happen?
It should be imported properly?

### What hardware, operating system, and PPSSPP version? 
PPSSPP  v1.11.2-75-gb0fdc7a30

**Comment by unknownbrackets** [comment] 2021-02-16 04:53
There's a lot of things that don't work with kernel mode syscalls.  This is really a duplicate of #6094.

Was a bit worried when I added support for a form of plugins that people would start expecting CFW plugins to work.  It's intentional that they use a different structure and not seplugins - they're similar, but CFW plugins aren't likely to work for a while.

Essentially, PPSSPP is like an electric car.  It doesn't even have the innards the PSP CFW had, like a carburettor.  If it had all those exact internals, it'd likely run more poorly on mobile devices.  We could try to find a way to bolt in your spark plugs - but it's not going to be seamless.  PPSSPP does not use the LLE approach to emulation, it's HLE - like how Windows 10 can run Windows XP programs.  The insides are still different, and drivers for XP may not Just Work.

As an example, kernel plugins often manage/replace/hook syscalls in a way very incompatible with how we handle them.  There's a ton of kernel syscalls (way more than games can access) that we don't even attempt to emulate.

Closing as a duplicate of #6094.  We can add this particular NID but I'm sure there'll be more.  It's better to just build a separate plugin for PPSSPP.

-[Unknown]

**Closed by unknownbrackets** 2021-02-16 04:53 UTC
Labels: Kernel mode
