### ISSUE TITLE
Vulkan backend crash after a while on GPU IMG BXM-8-256

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17825] opened 2023-08-01 09:10 UTC
This GPU is a low-power PowerVR GPU, in a Mediatek Dimensity 930 chipset. The phone model is "Motorola G Power 5G 2023".

Reported by kool-aid man on Discord.

Other affected Moto device (or possibly the same one), see #18681: Moto G54 5G

> When I start playing for 2 min then it crash for example gta vcs

https://github.com/hrydgard/ppsspp/assets/130929/735f9d28-7f3f-4918-a63c-2e23c92df599

![image](https://github.com/hrydgard/ppsspp/assets/130929/48b3fde9-ad26-4805-84bd-848c2a82436a)
![image](https://github.com/hrydgard/ppsspp/assets/130929/8c477c93-33be-45d2-8279-450c3bc1efb4)

**Comment by stereomato** [comment] 2024-01-24 19:12
Small update: Sometimes, If you reset ppsspp settings to default, you can play using Vulkan indefinitely. But closing and reopening PPSSPP and trying to play again will once again trigger the crashes. I tried to reproduce it again right now, and on the first try I got broken graphics on some parts, and re-setting the settings to default seemed to still make the emulator crash like it usually does with vulkan.

**Comment by hrydgard** [comment] 2024-09-09 12:14
My device just received a system update to Android 14, but the driver version is the same and the crash remains.

I've blacklisted this device from using Vulkan in future versions, for now it'll be OpenGL-only, as I just can't figure this out.

**Closed** 2024-09-09 12:15 UTC
Labels: PowerVR GPU

**Comment by stereomato** [comment] 2024-09-09 16:19
I also updated to Android 14, and I'm even running a custom rom, devs of the phone said that graphics blobs were updated, but I still have the issues with games that use vulkan or even opengl. This soc/gpu is just plain crap.

**Comment by hrydgard** [comment] 2024-09-09 17:19
I don't think the GPU is crap actually, it's low-end but if the driver hadn't crashed, it would be perfectly usable. But for some reason, they aren't testing it properly, which yes, is crap.

**Comment by stereomato** [comment] 2024-09-10 20:16
I don't know if I should complain on the Imagination forums (they seem to be kinda responsive), but it might be of very little use if Motorola won't update stuff.

**Comment by hrydgard** [comment] 2024-09-10 20:26
I think it's likely a lost cause... At least OpenGL is fairly playable on it.

**Comment by stereomato** [comment] 2024-09-10 20:29
Well, I'm on a custom rom group, one of the developers already asked on the imagination forums about some issues on the QPR2 version of Android 14 + Vulkan on this GPU, and according to Imagination it's up to Mediatek to fix stuff. The custom rom developer hopes to be able to pull drivers from another phone that will use also use this GPU (which will be the Motorola G64). Hopefully this proves fruitful!

**Comment by santiago046** [comment] 2025-04-13 13:08
According to this [post](https://forums.imgtec.com/t/broken-vulkan-on-android-14-qpr2-qpr3-15-dsu-powervr-bxm-8-256/3987) on the PowerVR Developer Community Forums, the vendor blobs were updated on Android 15.

After updating my Moto G54 to Android 15, I installed PPSSPP 1.17 and tested GTA: Vice City Stories with the Vulkan backend. I played for around 10 minutes with default settings, then for over 30 minutes with my usual settings and plugins. No crashes so far.

**Comment by hrydgard** [comment] 2025-04-13 13:49
@santiago046 Can you check the driver version in Settings/Tools/System info while using Vulkan?  Take a screenshot.

I can set a limit so that we permit Vulkan on this device from that version.

**Comment by santiago046** [comment] 2025-04-13 13:56
![Screenshot_20250413-105251.PPSSPP.jpg](https://github.com/user-attachments/assets/ad9b6223-9549-4cd8-bd3c-d382b7889d3a)

**Comment by hrydgard** [comment] 2025-04-13 14:00
Hm, that one is 1398 instead of 1397... 

Let's go ahead and enable Vulkan from that version on this device.

**Comment by stereomato** [comment] 2025-04-13 15:53
Ah, this is nice! I was going to do this too (i'm on a custom rom though) but I never got around doing it. I was a bit discouraged since a game I play has graphical issues, but it seems to be a game thing, not necessarily the igpu itself. Nice.
