### ISSUE TITLE
Dev-Working crashes when trying to load game

### ISSUE THREAD

**Issue by Shurikeeen** [hrydgard/ppsspp#8395] opened 2016-01-05 22:26 UTC
When I try to load a game (Persona 3 Portable), I get a black screen for a quater of a second, and the app closes. I'm using iPhone 4 on iOS 7.1.2. This issue does not happen in PPSSPP version 0.9.8-1043.

**Comment by unknownbrackets** [comment] 2016-01-06 02:43
This is a duplicate of #7360.  I think we found that some of the issues were caused by certain jailbreaks being very unstable.  There's also concern that we could be running out of memory on devices like the iPhone 4, which only has 512 MB of RAM (including GPU memory and OS.)

AFAIK, iOS will just stop an app without warning if it starts using more than a certain amount of memory (an amount much lower than your 512 MB total, again, AFAIK.)  Your best bet is to set the absolute minimum quality settings possible, since most of our memory usage is going to be video memory usage (and render resolution > 1x PSP can increase this drastically.)

We've implemented more features of the PSP since 0.9.8, so PPSSPP itself has gotten a bit larger.  That alone could be enough to tip it over the edge.

Anyway, closing this as a duplicate of #7360.  We're already aware that PPSSPP crashes on most iOS devices for various reasons.

-[Unknown]

**Closed by unknownbrackets** 2016-01-06 02:43 UTC
