### ISSUE TITLE
Resistance Retribution (US) - Effects Issues

### ISSUE THREAD

**Issue by mikhaelcool7** [hrydgard/ppsspp#13615] opened 2020-11-02 15:17 UTC
### What happens ?
- [Effects texture flickering and lights going through buildings](https://discord.com/channels/293316141479362560/480103153803460614/772595100001239070)
### What *should* happen?
- [0:51](https://www.youtube.com/watch?v=7fn9PB4XRbo&ab_channel=2old4gaming)
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Windows 10 Home | Version: 20H2 | OS Build: 19042.610 | Windows Feature Experience Pack: 120.2212.31.0
- Intel Core i7-7700HQ | NVIDIA GeForce GTX1060 (6GB VRAM) (Mobile)
- PPSSPP 1.10.3-1106 (Vulkan/OpenGL)

**Comment by Panderner** [comment] 2020-11-02 16:16
Duplicate of https://github.com/hrydgard/ppsspp/issues/9279 and https://github.com/hrydgard/ppsspp/issues/10165.

**Comment by MojoJojoDojo** [comment] 2020-11-02 16:27
The Syphon Filter issues are the same so might be duplicates too? (same engine ).

**Comment by hrydgard** [comment] 2020-11-02 20:19
Well, different games are not necessarily duplicates, even though it does seem likely.

**Closed** 2020-11-10 23:10 UTC
