### ISSUE TITLE
3D Texture filtering without 2D elements

### ISSUE THREAD

**Issue by PCPanda2** [hrydgard/ppsspp#16044] opened 2022-09-18 09:07 UTC
### What should happen

Rendering of UI and texts (globally all 2D elements) are far better without filtering than with.

![filtered 2D](https://user-images.githubusercontent.com/72814452/190894307-cc388734-dd18-46b1-8eca-70f14e8d1314.jpg)
![unfiltered 2D](https://user-images.githubusercontent.com/72814452/190894311-a982a1bd-f547-4d33-9d14-bf099b2b58ca.jpg)

### Who would this benefit

Better fidelity in rendering

### Platform (if relevant)

Windows

### Games this would be useful in

Castlevania, Crisis Core... all games basically.

### Other emulators or software with a similar feature

DuckStation, ePSXe...
![mwUN5Lr](https://user-images.githubusercontent.com/72814452/190894472-4cbea882-a555-493a-b75b-82f0c2904e78.png)

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment] 2022-09-18 10:11
Might be a duplicate https://github.com/hrydgard/ppsspp/issues/7232

**Comment by unknownbrackets** [comment] 2022-09-18 13:33
Unfortunately PSP games are way more loose about how they use 2D and 3D, I've pointed out many cases where "2D" things are actually rendered using 3D, or where 3D elements are bloomed using 2D.  Technically there's a flag in rendering (it disables viewport transform), but it's just not used the way you wish it was by actual PSP games.

Anyway, yes, closing this as a duplicate of #7232 indeed.

-[Unknown]

**Closed by unknownbrackets** 2022-09-18 13:33 UTC
