### ISSUE TITLE
Analog vertical tests still wrong

### ISSUE THREAD

**Issue by chevycam94** [hrydgard/ppsspp#9337] opened 2017-02-21 04:58 UTC
Since the commit, now when making to UP, it shows "Y-" (actually down).  And DOWN shows "Y+" (actually up).

If you ignore what it says is being mapped, and you just move the analog stick in the direction it SHOULD go, then the mapping works in the game, even though both the mapping output and the virtual analog testing screen shows that up/down is still always flipped so that up is down, and down is up, regardless of the mapping.

**Comment by hrydgard** [comment] 2017-08-16 21:08
Closing as duplicate of #9300 , further discussion should be there.

**Closed by hrydgard** 2017-08-16 21:08 UTC
