### ISSUE TITLE
Ghost of Sparta crashing with jit/ir in some situations (HW tess?)

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#10897] opened 2018-04-10 04:45 UTC
What happens?
GOW Ghost of Sparta crashed when i'm turn on HW Tessellation at this scene , when i'm turn off , it's normal , crashed appear the same in Mobile
![image](https://user-images.githubusercontent.com/11285640/38536674-9e7a8900-3cb4-11e8-9c85-c89b254640fd.png)
![image](https://user-images.githubusercontent.com/11285640/38536690-ac96e15a-3cb4-11e8-9107-6f034a007c17.png)

**Comment by unknownbrackets** [comment] 2018-04-10 04:55
That looks somewhat like jit.  If you enable the IR Interpreter instead of jit, does it still crash?  And if so, does it give a more useful Call Stack?

-[Unknown]

**Comment by zminhquanz** [comment] 2018-04-10 06:24
![image](https://user-images.githubusercontent.com/11285640/38539448-7368c1f6-3cc2-11e8-9084-1885173f2631.png)
Same for JIT , i switch to IR Interpreter , it still crashes

**Comment by zminhquanz** [comment] 2018-04-10 07:33
Oh , I find out , fast memory caused crashes , this is my mistake , so I closed this

**Comment by hrydgard** [comment] 2018-04-10 08:08
Hm. If fast memory crashes, there's still some issue, though may not really be related to tesselation..

**Comment by hrydgard** [comment] 2018-04-10 10:42
Any idea if this is new, or if it's happened for a long time in this place in the game? Do you have a savegame nearby?

**Comment by zminhquanz** [comment] 2018-04-10 10:46
@hrydgard yeah , i load game in savegame , not using save state

**Comment by hrydgard** [comment] 2018-04-10 10:55
Well I meant, can you upload the savegame? Useful for debugging this.

**Comment by zminhquanz** [comment] 2018-04-10 10:58
[GOW savedata.zip](https://github.com/hrydgard/ppsspp/files/1894275/GOW.savedata.zip)
Here is it , you can check it again

**Comment by zminhquanz** [comment] 2018-04-10 13:59
@hrydgard Hey , how was it , can you found a bug ?

**Comment by hrydgard** [comment] 2018-04-10 14:27
Sorry, today I've been working on restoring hardware skinning. But will take a look soon.

**Comment by leopard20** [comment] 2018-04-11 07:24
@hrydgard 
Sorry for asking this here. What is hardware skinning? How does it compare with software skinning?

**Comment by weihuoya** [comment] 2018-04-11 08:27
`inst.op` is `RestoreRoundingMode` 94

**Comment by hrydgard** [comment] 2018-04-11 08:29
Thanks @weihuoya , that's helpful! I'll look into this soon.

@leopard20   The PSP has a rather peculiar way of doing bones/skeletal animation ( https://en.wikipedia.org/wiki/Skeletal_animation ) in hardware.  We have to emulate it, and it can either be done by performing all the math in vertex shaders on the GPU, which is what we call "hardware skinning", or on the CPU, which we call "software skinning". Unfortunately games are not very efficient about how they use this feature, they will draw a few triangles, upload a new bone matrix, then draw a few more etc. This is expensive for us to do on the GPU since that's a lot of "draw calls", but if we do it on the CPU, we can combine them. So effectively:

  *  If games use a lot of small draws and switches bones a lot, and draw calls are slow (like OpenGL), software skinning wins since we can make much fewer draw calls, but it's a bit more CPU work.
  * If games use very large draws, or draw calls are fast, hardware skinning can be equally fast or in rare cases faster.

**Comment by hrydgard** [comment] 2018-04-11 09:18
@weihuoya  Added a fix for the IR Interpreter bug. Won't fix the JIT problem though, or whatever it is.

**Comment by weihuoya** [comment] 2018-04-11 09:29
`RestoreRoundingMode`, crash
```c++
u32 IRInterpret(MIPSState *mips, const IRInst *inst, int count) {
	default:
			Crash();
}
```

**Comment by hrydgard** [comment] 2018-04-11 09:53
Huh. Seems we never properly implemented these ops. @unknownbrackets  do you remember why we emit Apply/Restore/UpdateRoundingMode in the interpreter but don't have any code to interpret them?

**Comment by hrydgard** [comment] 2018-04-11 09:56
Added some code to ignore those for now, will need to get them implemented at some point.

**Comment by zminhquanz** [comment] 2018-04-11 10:47
Oh , look like CPU Core problem

**Comment by zminhquanz** [comment] 2018-04-11 10:48
@weihuoya Yeah , i tested with IR Interpreter and JIT , two of them crashes

**Comment by hrydgard** [comment] 2018-04-11 11:09
Yeah, seems likely. Thanks.

**Comment by unknownbrackets** [comment] 2018-04-11 14:15
@hrydgard well, I think you added them, we probably never finished with them?

We'd also added the metadata here:
https://github.com/hrydgard/ppsspp/commits/ir-fpu-round

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-04-11 16:05
We never merged that branch, I think it wasn't working still?

-[Unknown]

**Comment by hrydgard** [comment] 2018-04-11 18:02
Oh, right :/

**Comment by zminhquanz** [comment] 2018-04-12 02:49
@hrydgard I think if you didn't fix that bug , so the temporary solution is Turn off Fast Memory

**Comment by weihuoya** [comment] 2018-04-12 13:32
an invalid memory access, turn off fast memory will ignore this access

**Comment by zminhquanz** [comment] 2018-04-15 11:01
@unknownbrackets yeah , some situation , HW Tess caused crashed when turn on fast memory with JIT/IR , turn off HW Tess is temporary fix but sometimes it crashes

**Comment by zminhquanz** [comment] 2018-06-17 13:53
We need to implement to ignore this or fix this @hrydgard

**Comment by rolffot** [comment] 2019-12-28 23:04
Here you may be interested, to skip this error, you have deactivated the fast memory and set the CPU speed to 101, so it has not exploded and after jumping all the position as it was before. I comment in case someone got stuck and could not pass.

regards

**Comment by rolffot** [comment] 2019-12-28 23:07
![Screenshot_20191228-190526](https://user-images.githubusercontent.com/59321928/71550373-32645400-29a5-11ea-90e1-584e1c6eac3a.png)
![Screenshot_20191228-190623](https://user-images.githubusercontent.com/59321928/71550375-37c19e80-29a5-11ea-974e-eb5fc462a4d1.png)

**Comment by Kevin2912** [comment] 2020-04-26 10:57
I don't get it guys im on Android and ive gotten this far into the game and its crashing at the exact same spot is there any solution????

**Comment by Gamemulatorer** [comment] 2021-09-08 16:27
@zminhquanz is HW Tessellation is related to crash? or fast memory only? on android.
Recently hrydgard fixed the issue on hw tessellation on neo game stations maybe that help this.?

**Comment by Gamemulatorer** [comment] 2021-10-01 14:07
> What happens? GOW Ghost of Sparta crashed when i'm turn on HW Tessellation at this scene , when i'm turn off , it's normal , crashed appear the same in Mobile ![image](https://user-images.githubusercontent.com/11285640/38536674-9e7a8900-3cb4-11e8-9c85-c89b254640fd.png) ![image](https://user-images.githubusercontent.com/11285640/38536690-ac96e15a-3cb4-11e8-9107-6f034a007c17.png)

I cannot reproduce this issue on the latest build possibility this was fixed by https://github.com/hrydgard/ppsspp/pull/14805?

**Comment by Gamemulatorer** [comment] 2021-10-01 14:09
Here's the the proof.

https://user-images.githubusercontent.com/37603562/135634195-288edcf8-e1f5-4dd9-8443-ec7fe5b53163.mp4

**Comment by unknownbrackets** [comment] 2021-10-01 14:40
Great, thanks for checking.  I think there's a good chance that would've helped.  I'll close this.

If anyone has more information or can confirm it still happens in the latest git builds, please reply to this issue with more details (i.e. which device and specific git build version), and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2021-10-01 14:40 UTC

**Comment by Gamemulatorer** [comment] 2021-10-01 15:20
IDK why in that particular area still crashing using ir interpreter created new issue https://github.com/hrydgard/ppsspp/issues/14958
