### ISSUE TITLE
MLB 08 - The Show (USA)  crowd graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11596] opened 2018-11-26 02:41 UTC
the crowd glitches (the brown lines)
![mlb 08](https://user-images.githubusercontent.com/2696404/48989982-934ca780-f167-11e8-9f38-661a821e1bc0.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/2613887/DUMP.ZIP)

**Comment by ppmeis** [comment] 2018-12-03 10:54
Tested in latest Windows build, default settings. Depending on camera distances, it looks fine or not:
![image](https://user-images.githubusercontent.com/4381277/49369407-a58f8e00-f6f1-11e8-9310-2633f3a77ee3.png)
![image](https://user-images.githubusercontent.com/4381277/49369545-fa330900-f6f1-11e8-8b0e-b90dbfdd6131.png)

Also, the power bar y very buggy. There's no chance to do a good launch of the ball.

**Comment by unknownbrackets** [comment] 2020-04-08 05:18
My little test runner for the PSP cannot handle this dump, because it's too big.  But it did draw the crowd before dying.  It can run (and fail) the same way on a PSP as in PPSSPP, so it's still useful for comparison.

The PSP output (glitches from the dump being too large for the runner's memory handling):
![UCUS98696_#11596_the_show_crowd](https://user-images.githubusercontent.com/191233/78747014-2fbab880-791d-11ea-8769-3e5e9961ed66.png)

Our GLES output:
![UCUS98696_#11596_the_show_crowd_gles](https://user-images.githubusercontent.com/191233/78747024-39dcb700-791d-11ea-9989-d72d569eaab7.png)

The glitches are different (which is interesting, since they should correctly be the same), but ignoring those - the crowd looks the same.

Is this still an issue?  Maybe it's been fixed since, or maybe the dump didn't capture it correctly.  If that's the case, it might help to try another dump.  Also, if there are more and less complicated areas, it may help to grab a dump from a less complex area.  Not sure if that's a thing.

About launching the ball: can you describe more?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-04-16 13:03
Look's good to me.
![Screenshot_2022-04-16-21-01-51-696_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163676008-15f66de4-c508-436c-948e-a94becdd4d59.jpg)
![Screenshot_2022-04-16-21-02-30-724_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/163676012-745e2c1b-e7b3-4887-bd7a-e4f0a6b45b2f.jpg)

**Comment by unknownbrackets** [comment] 2022-10-23 17:52
I'm going to assume this is fixed now, then, since I can't reproduce issues in the frame dump.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2022-10-23 17:52 UTC
Labels: No Feedback / Outdated?, GE emulation

**Comment by ppmeis** [comment] 2022-12-16 23:08
confirmed crowd graphics are good. Tested in latest build under Vulkan backend. But there's a very strange and big issue makes game unplayable. Pitcher bar HUD is not showing charge position correctly. In software render you can see power line bar in the whole bar perfectly:

![UCUS98696_00000](https://user-images.githubusercontent.com/4381277/208202286-085659e0-517f-478a-8a07-24ea44b86bb4.jpg)

But in any other render (well at least Vulkan an Direct3D 11) power line bar dissapear up to the mid of the power bar and then comes back:

![UCUS98696_00001](https://user-images.githubusercontent.com/4381277/208202457-18108acc-1ca8-413e-a356-04757a280b33.jpg)

Here is a video to explain the issue better:


https://user-images.githubusercontent.com/4381277/208203241-912ae834-4311-43be-b4ea-edd9d921d0ed.mp4

**Comment by unknownbrackets** [comment] 2022-12-17 06:33
I think that's #9308.

-[Unknown]
