### ISSUE TITLE
About Android force Max FPS options

### ISSUE THREAD

**Issue by clondy999** [hrydgard/ppsspp#15259] opened 2021-12-29 13:53 UTC
### What should happen

About force Max FPS options

I use the Linux version of ppsspp, and the force Max FPS option will appear in the menu.

But when I used the Android version, I didn't.

This setting is important for some games. Is there no such setting in Android

### Who would this benefit

About force Max FPS options

I use the Linux version of ppsspp, and the force Max FPS option will appear in the menu.

But when I used the Android version, I didn't.

This setting is important for some games. Is there no such setting in Android

### Platform (if relevant)

Android

### Games this would be useful in

anybody

### Other emulators or software with a similar feature

About force Max FPS options

I use the Linux version of ppsspp, and the force Max FPS option will appear in the menu.

But when I used the Android version, I didn't.

This setting is important for some games. Is there no such setting in Android

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment] 2021-12-29 14:32
This option was removed from all versions and is automatic where needed because it also causes issues in some games. If your Linux version has it in menu, it's outdated or modded.

**Comment by clondy999** [comment] 2021-12-29 14:35
I use the Linux version and compile it into Android.
Strangely, Android does not have this option, but Linux does
How can I turn on this option. I can compile it myself

**Comment by LunaMoo** [comment] 2021-12-29 21:56
Your Linux build has to be outdated or modified as I said, as you can see in: https://github.com/hrydgard/ppsspp/blob/master/UI/GameSettingsScreen.cpp
PPSSPP currently has no trace of that setting in the menu. If you build android version from same version you now build your linux build from it will also have it.

 But again you don't need that option as it's applied automatically to all the heavy games people wanted to use it for where it actually did something positive, without nasty side effects. Basically it was a setting that did absolutely nothing to most of the games, improved few ones, broken few other ones. Now it's applied to those few ones it helped without allowing for users to break a bunch of others for themselves.

**Comment by ANR2ME** [comment] 2021-12-30 01:14
Btw the Max FPS option is only used to cap the FPS to no more than 60 isn't? (similar to VSync on 60hz Monitors)

**Comment by LunaMoo** [comment] 2021-12-30 03:12
It's not like Vsync since the game can still render more even if emulated PSP can display 60 max, but it's correct that it doesn't do anything else than limiting how much the game can render which is why most games aren't affected by it at all and while some might have reduced requirements others on the other hand will get no benefit with insanely increased loading times as loading screens tend to work differently than in-game.

 There's no reason for this to be an user selectable option on any platform.

 I would say however PPSSPP could use an opposite option - to easily disable all automatic hacks since most automatic hacks are added following user support and some users tend to do questionable or just very limited testing being overly confident that their experience coming from 5 minutes of gameplay will transfer to whole playthrough which can be very far from truth and historically caused regressions. If such option already exists I probably didn't pay enough attention when it was being added.;o

**Comment by clondy999** [comment] 2021-12-30 05:07
I think I know.
I use emuelec for the Linux version. It adds a path patch when compiling.
Can I use this patch file when compiling Android

**Comment by ANR2ME** [comment] 2021-12-30 05:27
You will need to build an older version of PPSSPP, because the latest version doesn't have Max FPS option anymore, including on Windows (Linux shouldn't have this setting either on the latest version)

**Comment by Gamemulatorer** [comment] 2021-12-30 07:58
This can be close as duplicate of https://github.com/hrydgard/ppsspp/issues/11843

**Closed** 2021-12-30 09:59 UTC
