### ISSUE TITLE
[feature request] Mouse map on linux version

### ISSUE THREAD

**Issue by CaioVdmm** [hrydgard/ppsspp#12170] opened 2019-07-12 21:17 UTC
Hi Hrydgard
can you add support for mouse like windows version in linux version?

**Comment by LunaMoo** [comment] 2019-07-12 21:56
Closing as a duplicate of #4650 which was never an OS specific request.

**Closed by LunaMoo** 2019-07-12 21:56 UTC

**Comment by CaioVdmm** [comment] 2019-07-13 00:11
I have specified an OS, and it is linux (Ubuntu, arch, manjaro, deepin and etc ...).
how can you say that an OS was not specified?

**Comment by unknownbrackets** [comment] 2019-07-13 20:53
It's just that #4650 isn't specific to any operating system - not Linux only but also not Windows only.  We don't need a separate issue for each operating system.

-[Unknown]

**Comment by CaioVdmm** [comment] 2019-07-14 22:37
but only windows have this feature. you need to add this feature on osx and
linux version too and this is my request.
add this feature in linux and osx too

Em sáb, 13 de jul de 2019 às 17:53, Unknown W. Brackets <
notifications@github.com> escreveu:

**Comment by unknownbrackets** [comment] 2019-07-14 23:12
Right.  That's why #4650 exists.  It hasn't been closed - it's still open.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

-[Unknown]
