### ISSUE TITLE
PPSSPP on F-Droid is more than 7 years out of date!

### ISSUE THREAD

**Issue by Nitrovenom** [hrydgard/ppsspp#17367] opened 2023-05-01 06:21 UTC
### What should happen

PPSSPP on F-Droid is still stuck on 1.1.1.0. This should be updated.

### Who would this benefit

People who use ROMs without GMS such as those using lineage OS and those live in China.

### Platform (if relevant)

Android

### Games this would be useful in

All

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment] 2023-05-01 06:22
This issue is being closed as a duplicate of #9112.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2023-05-01 06:22 UTC
