### ISSUE TITLE
[REGRESSION] Reaction to gamepad trigger presses became unpredictable

### ISSUE THREAD

**Issue by HFPasfho** [hrydgard/ppsspp#18784] opened 2024-01-29 16:03 UTC
### Game or games this happens in

All

### What area of the game / PPSSPP

I have PSP bumpers mapped to both gamepad bumpers and triggers so no matter if I press gamepad bumper or trigger PPSSPP should register this input as L or R and this is how it worked until v1.17.
In version 1.17, gamepad trigger input appears to work randomly. It works like 20% of the time. Totally unreliable. At the same time gamepad bumpers still works great.

Because it worked before I assume this may be related to [this new feature introduced in v1.17](https://github.com/hrydgard/ppsspp/pull/18621) but changing analog trigger threshold doesn't seem to change anything for me. And I don't think it should because my gamepad have digital triggers (they act like bumpers).

Also gamepad triggers presses are recognized as button combo. E.g. L bumper is recognized as pad1.L1, but L trigger is pad1.L2 + pad1.TriggerL+ + pad1.Brake+. I don't think it matters because it was like this before but maybe I'm wrong and this info is important.

### What should happen

Triggers should work on each press like they did before v1.17.

### Platform

Android

### Mobile device model or graphics card (GPU)

S9

### PPSSPP version affected

v1.17

### Last working version

v.16.6

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2024-01-29 16:11
Hm, I think the combo thing might be the problem. We now reject combos that are not made in the same "order" as when they were mapped (so Ctrl+S will not also match S+Ctrl, for example).

If you disallow combo mappings, can you map them in a way that they work?

**Comment by HFPasfho** [comment] 2024-01-29 17:01
Without combo mappings triggers works fine.
Gamepad is BSP-D3.

**Comment by hrydgard** [comment] 2024-01-29 17:08
OK. I'm making the old behavior default and the new behavior an option, since it effectively becomes a regression in your situation. Fix is in #18785

**Comment by HFPasfho** [comment] 2024-01-29 17:34
Much appreciated!

**Comment by hrydgard** [comment] 2024-01-29 21:05
I believe this is fixed now, closing.

**Closed by hrydgard** 2024-01-29 21:05 UTC
Labels: Input/Controller
