### ISSUE TITLE
Gundam Battle Universe Crash

### ISSUE THREAD

**Issue by Tktw** [hrydgard/ppsspp#7136] opened 2014-12-05 13:52 UTC
![game](https://cloud.githubusercontent.com/assets/10087510/5316499/99fd9366-7ccf-11e4-8cd7-63d7e16c7486.jpg)
crash after this screen

![debug](https://cloud.githubusercontent.com/assets/10087510/5316500/9cb8cc24-7ccf-11e4-8f52-4bc4a562b5ed.jpg)
ppsspp-v0.9.9.1-1061-gea63719

I'm sorry
I can't explain well

**Comment by issuer** [comment] 2015-01-08 20:05
Excuse me but is this fixed? Since the issue is still open i thought isn't fixed yet.
If it helps, i fixed the freezing/hanging issue in all the Gundam Battle games (which use the same engine) in old builds by enabling Sound Speed Hack in Audio.

**Comment by unknownbrackets** [comment] 2015-01-08 20:07
Still haven't tested this on real hardware.  It's hard to test.  I'm thinking this change may be safe.

I don't know much about that hack but as long as a hack is needed it's a bug.

-[Unknown]

**Comment by issuer** [comment] 2015-02-03 01:10
Seems fixed on 1.0. PLayed this game for 1 hour and i'm already 20 hours in Gundam Assault Survive which had this same issue (they use the same engine, including the Macross games).

I won't close this issue but +1 to fixed.

**Comment by daniel229** [comment] 2015-02-03 02:17
Other gundam battle games seem different.Gundam Assault Survive random hangs in battle fixed long time ago.

**Comment by issuer** [comment] 2015-02-03 03:37
I've just noticed that. Seems completely random, just crashed on the second try. Same settings as the first try. This issue is not fixed yet.

**Comment by daniel229** [comment] 2015-03-23 14:51
Changing cpu clock to 85 or 1000 helps it

**Comment by DarkD** [comment] 2015-07-20 10:17
There's a lot of issues opened for this game and only one opened. Yet it still freezes(at least on default settings, though tweaking 'em doesn't helps). Screens are taken from after confirming first mission's start.
![gbuscreen](https://cloud.githubusercontent.com/assets/6061259/8773723/2817126e-2edf-11e5-8d6b-10f7c317f22c.png)
![gbulog](https://cloud.githubusercontent.com/assets/6061259/8773724/2a13b2d4-2edf-11e5-8bec-e7d44e276ed4.png)
With debug log it spams those two lines:
17:12:883 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:2343 1=sceKernelSuspendDispatchThread()
17:12:883 user_main    D[KERNEL]: HLE\sceKernelThread.cpp:2358 sceKernelResumeDispatchThread(1) - from 0

Hopefully that'll help to get rid of this nasty freeze for good.

**Comment by FonSpaak** [comment] 2016-02-12 17:15
Is there a way to implement the game fix on ppsspp 1.1.1 version for android? if there is, i would like to know how to implement the fix on the game.

**Comment by Halcon0Negro** [comment] 2016-03-01 02:35
stil freeze in v1.2.1-31-g9bde45d...

**Comment by Kryse-777** [comment] 2016-03-06 08:50
well, I got to the settings and went YOLO in all clicking the settings, thankfully, in 1 instance, I managed to run it smoothly, sadly, the moment reopened it, it never ran again, a sad life it is

**Comment by FonSpaak** [comment] 2016-03-08 07:08
It's been confirmed that the newest of the Gundam battle series, Gundam Assault Survive™ is working well on the latest build on PPSSPP, although it lags, there is no issues on crashing, something seems to be a bit off on the two titles, 
Well, Tweaking the settings might be worth it, or we could wait for the next PPSSPP Build, see if it solve the crash on Gundam Battle Universe™

**Comment by FonSpaak** [comment] 2016-03-21 06:26
*Report For ULJS-00145*
Phone Model: 7040N
CPU: ARM7 Processor rev 3 (7l)
Cores: 4
3D API: OpenGl ES
Vendor: Qualcomm

PSP Ver. 1.2.2.0
Game title: Gundam Battle Universe™
Game ID: ULJS00145
Region: Japan
Status Report: Same As Before (Freeze before Commencing Mission)
Personal Comments: As of the latest versions of the PPSSPP, ULJS-00145 has been rendered from Playable to Menus Only, As there is no way that i could fix the problem present on ULJS-00145, Tried Switching the settings from Skip Buffered Rendering to Buffered Rendering, switching to Buffered Rendering will show you a black screen. ( Reverting to a save state might solve this. )Main problem begins when starting the script for a mission, in which it will make the PPSSPP seize functions and from there, it will force close. *ENDING REPORT/ASSISTANCE NEEDED*

**Comment by DarkD** [comment] 2016-09-23 11:56
As I promised to Daniel229 in Chronicle issue discussion I found what tweak makes game playable and not freeze on mission load - it's PSP's CPU clock being set at 1000, need to check if that'll work for Chronicle's issue too...

**Comment by finansar222** [comment] 2016-10-03 16:58
อยากลองเล่นเกม..แต่ทำไมเล่นไม่ได้

**Closed** 2017-02-03 16:20 UTC
Labels: Needs hardware testing

**Comment by DarkD** [comment] 2017-02-03 17:31
And this one works without any issues.

**Comment by unknownbrackets** [comment] 2019-07-14 21:26
I think the correct fix for this issue is now in #12160.

-[Unknown]

**Comment by LunaMoo** [comment] 2019-07-14 21:47
Still crashes without the hack.
