### ISSUE TITLE
Digimon Adventure PSP NPJH-50686 cutscene videos issue.

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#12186] opened 2019-07-20 13:59 UTC
### What happens?
When I open the game menu and then select library and then videos, the first time I select a video to play, it works normally, but then if after finishing watching that video I select another one to watch, the video doesn't appears, but you can hear the video's sound. I have to go to full screen and return back to window mode for the video to appear and plays normally (or viceversa if I'm playing in full screen, that would be going to Window Mode and then back to full screen).

Also when this happens, the transparency on the menu (when you open the menu you can see the character and the area's background behind the menu) dissappears.

At first I thought it was because of the simulate block transfer effects option being checked, but I unchecked it and there was no change.

Here is a video of the issue (what better than to see the issue in motion?) :

https://www.youtube.com/watch?v=l2O4G0E_sKM

### What *should* happen?
You should be able to play videos normally, even if you select another video after finishing watching one

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I use Windows 7 Ultimate 32 bits, ppsspp-v1.8.0-433-g37a97e741 (x86 version of course) and I have a 2GB Radeon R7 240 Graphic card, 4GB RAM, 1TB Hard disk and a 500GB Hard Disk and a Core i5 3Ghz CPU (4 cores).

As an extra note. This issue didn't happen on PPSSPP v1.6.3-561-g31893859c which was the one I had before updating to the current one which is v1.8.0-433-g37a97e741 so is hard to pinpoint where the issue started since there are a lot of builds between the versions mentioned above. Other than that the game seems to work fine, I even noticed a huge visual improvement, mostly on the characters, before with the black outline they looked really awful, but now they looked way better :)

Edit: I managed to track the build where the issue started. It was on v1.7.1-141-gdf5fbaef7 released on November 12, 2018 which is precisely where the visual improvement and the work in progress to remove the simulate block transfer option started as mentioned on the thread "WIP: Virtual readbacks" which is the pull request number 11531 located on this link https://github.com/hrydgard/ppsspp/pull/11531

The very same day v1.7.1-141-gdf5fbaef7 was released which was November 12, 2018, on the pull request 11531 the commit df5fbae was merged into master, this resulted on the next build released which is v1.7.1-143-g79d16f7b9, released On November 13. It was that commit number what made me able to pinpoint where the issue started.

The version before build v1.7.1-141-gdf5fbaef7 which is v1.7.1-132-g9c6f7000b, has no issues with Digimon Adventure's cutscenes videos.

**Comment by hrydgard** [comment] 2019-07-20 15:47
Thanks, this needs to be investigated. Not too surprised that there is a problem or two caused by it.

**Comment by LPatamon** [comment] 2019-07-20 23:48
> 
> 
> Thanks, this needs to be investigated. Not too surprised that there is a problem or two caused by it.

No problem. The good thing is that there is a lead to follow to work with that issue since I found in which build it originated :)

**Comment by hrydgard** [comment] 2019-09-17 12:48
@LPatamon  Thanks again for reporting this, it's fixed now.

**Closed** 2019-09-17 12:47 UTC

**Comment by LPatamon** [comment] 2019-09-17 13:34
> 
> 
> @LPatamon Thanks again for reporting this, it's fixed now.

It works great! Not only you fixed this issue, but on the way you also removed that annoying line that appeared on the bottom part of the videos! :D

It was a 2x1 fix :D

Thank you very much!

Now the only issue in this game is the other one I reported which is issue  #12188 but I'm sure it will be fixed sooner or later.

Again thank you very much :)
