### ISSUE TITLE
Burnout dominator have lighting issue (recursive rendering in framebuffer border)

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11100] opened 2018-05-29 07:09 UTC
![screenshot_20180529-085605](https://user-images.githubusercontent.com/33152267/40643168-76749ac2-631f-11e8-8ebc-6664bf01a05f.png)
Sun in the tunel?!? OK!!!!!
Backend: OpenGL

**Comment by hrydgard** [comment] 2018-05-29 07:36
Yeah, I believe the game is asynchronously reading from the depth buffer to figure out if the sun might be visible or not. This is hard to implement in GL without murdering performance, but we might be able to get this approximately right (with a frame delay) in Vulkan. Something for the future as it's quite tricky stuff...

**Comment by leopard20** [comment] 2018-05-29 09:35
@hrydgard 
This is probably the same as this [https://github.com/hrydgard/ppsspp/issues/10229](url), right?

**Comment by hrydgard** [comment] 2018-05-29 10:17
Not certain but quite likely!

**Comment by marosis** [comment] 2018-12-14 14:09
@hrydgard so what with this? Still waiting?( If yes no problem but depth buffer readback can fix lot of games)

**Comment by marosis** [comment] 2018-12-14 18:16
+interresting in this game Is that, when you are rotated to the sun, you will get really big performance decrease.

**Comment by hrydgard** [comment] 2018-12-14 19:09
Hm, I thought the big perf decrease was only in Burnout Legends, where it currently does do a readback when the sun is visible..

**Comment by marosis** [comment] 2018-12-18 10:09
Maybe fixing this can fix performance cause we don't have implemented readback  it throwing any error or issue?

**Comment by leopard20** [comment] 2018-12-19 13:23
@marosis Turning off "Simulate block transfer" fixes the performance issue.

**Comment by Panderner** [comment] 2020-08-06 07:00
![Screenshot_2020-08-06-14-56-59-49_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/89501113-659d7a00-d7f5-11ea-85b0-1307c29bbd21.png)
Here's a GE Dump:
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5033116/recording.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2020-09-21 06:21
> ![Screenshot_2020-08-06-14-56-59-49_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/89501113-659d7a00-d7f5-11ea-85b0-1307c29bbd21.png)
> Here's a GE Dump:
> [recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5033116/recording.ppdmp.zip)

No sun light issue on my phone mali-450 gpu opengl
I'm using your ge dump 🤔
![Screenshot_20200921-141933](https://user-images.githubusercontent.com/37603562/93737404-b20e0f00-fc15-11ea-8f8d-033421b0393c.png)

PPSSPP v1.10.3-725 git build

**Comment by Panderner** [comment] 2020-09-21 06:41
@Gamemulatorer the sun issue still happens in-game. When i making the GE Dump for sun in the tunnel or building the sun disappears.

Here's a GE Dump:
[recording (2).ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5253774/recording.2.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2020-09-21 07:29
Maybe opengl 2.0 device are not affected by this issue 😅

**Comment by Panderner** [comment] 2020-09-21 07:36
> Maybe opengl 2.0 device are not affected by this issue 😅

@Gamemulatorer could you send me the screenshot of this game are you playing?

**Comment by Gamemulatorer** [comment] 2020-09-21 07:57
This game is very very slow on my phone when the sun is showing :(
![Screenshot_20200921-154457](https://user-images.githubusercontent.com/37603562/93743622-f05dfb00-fc22-11ea-9176-6f73d6e91203.png)
![Screenshot_20200921-154508](https://user-images.githubusercontent.com/37603562/93743637-f8b63600-fc22-11ea-84e8-8f532febc310.png)
But when I'm inside the tunnel the sun doesn't show :)
![Screenshot_20200921-154621](https://user-images.githubusercontent.com/37603562/93743706-1b484f00-fc23-11ea-937c-7084436aaa3d.png)
![Screenshot_20200921-155413](https://user-images.githubusercontent.com/37603562/93743755-30bd7900-fc23-11ea-9f3d-e46b194b4978.png)

**Comment by hrydgard** [comment] 2020-09-21 08:01
Weird that it's so slow. I'm gonna have to investigate how the sun is done in this game too. We've solved the sun in Legends as good as we can get it, I think, though...

**Comment by Gamemulatorer** [comment] 2020-09-21 12:05
Performance is good on my phone with sun is showing @1X rendering resolution but the graphics is too much pixelated unlike before 🙁
![Screenshot_20200921-193543](https://user-images.githubusercontent.com/37603562/93764476-c2d67900-fc45-11ea-9e07-9369f7052d6e.png)

**Comment by Panderner** [comment] 2020-09-21 12:25
> Performance is good on my phone with sun is showing @1x rendering resolution but the graphics is too much pixelated unlike before 🙁
> ![Screenshot_20200921-193543](https://user-images.githubusercontent.com/37603562/93764476-c2d67900-fc45-11ea-9e07-9369f7052d6e.png)

@Gamemulatorer change the texture filtering to linear since the auto in texture filtering uses nearest for Burnout games all other games uses linear.

**Comment by hrydgard** [comment] 2020-09-21 13:01
There's gonna be some new mipmapping option soon that will help fight the pixellated look as well that some games have.

**Comment by hrydgard** [comment] 2020-09-24 21:08
Checked in a change that gets rid of readbacks for the sun effect, but it's still not fixed.

This game is evil and renders to the same texture it's reading from while downsampling the region around the sun, forcing a full framebuffer copy - since it does that stuff out in the border of the main render target... Sigh.

I believe it then uses the result of that as a CLUT (color palette) to adjust the strength of the sun effect. This old PR has a clue: https://github.com/hrydgard/ppsspp/pull/8246

**Comment by Panderner** [comment] 2020-09-24 23:37
The sun same happens for PS2 version of Burnout Dominator running on PCSX2 see https://github.com/PCSX2/pcsx2/issues/883 for more info for other burnout games.

**Comment by Gamemulatorer** [comment] 2020-09-30 10:49
> > ![Screenshot_2020-08-06-14-56-59-49_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/89501113-659d7a00-d7f5-11ea-85b0-1307c29bbd21.png)
> > Here's a GE Dump:
> > [recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5033116/recording.ppdmp.zip)
> 
> No sun light issue on my phone mali-450 gpu opengl
> I'm using your ge dump 🤔
> ![Screenshot_20200921-141933](https://user-images.githubusercontent.com/37603562/93737404-b20e0f00-fc15-11ea-8f8d-033421b0393c.png)
> 
> PPSSPP v1.10.3-725 git build

Sorry about this but I think I'm wrong issue also present on my phone 😅
![Screenshot_2020-09-30-16-50-28](https://user-images.githubusercontent.com/37603562/94676222-914c6480-034d-11eb-962f-6175994d9ec3.png)
But why it can't reproduce this on a ge dump?

**Comment by unknownbrackets** [comment] 2021-02-16 05:07
> This game is evil and renders to the same texture it's reading from while downsampling the region around the sun, forcing a full framebuffer copy - since it does that stuff out in the border of the main render target... Sigh.

Does it do this with region or scissor parameters that could perhaps clue us in on it being safe to use a separate framebuf?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-05-02 15:07
I can reproduce this on my Redmi Note 9 Vulkan & OpenGL graphics using latest git build.
![Screenshot_2021-05-02-23-06-28-387_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116817890-2f7e0280-ab9b-11eb-80fd-2ff80bebc4ff.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-09 18:07
> ![screenshot_20180529-085605](https://user-images.githubusercontent.com/33152267/40643168-76749ac2-631f-11e8-8ebc-6664bf01a05f.png)
> Sun in the tunel?!? OK!!!!!
> Backend: OpenGL

This is also happen on Vulkan
![Screenshot_2021-05-10-02-01-44-063_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/117582408-7ab48a00-b134-11eb-9627-239e99eff21b.jpg)
Im using the latest git build apk

**Comment by hrydgard** [comment] 2021-05-09 18:49
yeah, still have no fix for this, sorry.

**Comment by Gamemulatorer** [comment] 2021-10-05 00:53
**software rendering**
![Screenshot_2021-10-05-08-50-52-757_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135943699-0681ebc9-d89b-472e-a8ce-fbb328affca4.jpg)
**hardware rendering**
![Screenshot_2021-10-05-08-49-12-389_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135943728-3a80d700-187c-46b3-8e26-63b48d21a643.jpg)

**Comment by Gamemulatorer** [comment] 2022-05-10 13:26
I can also reproduce this in motorstorm arctic edge.

**Comment by Panderner** [comment] 2022-05-10 23:04
> I can also reproduce this in motorstorm arctic edge.

@Gamemulatorer screenshot?

**Comment by Gamemulatorer** [comment] 2022-05-11 04:24
> > I can also reproduce this in motorstorm arctic edge.
> 
> @Gamemulatorer screenshot?

![Screenshot_2022-05-11-10-29-12-700_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/167768790-cedf8ab7-7751-417b-8d12-d084cd2e5be5.jpg)

**Comment by Panderner** [comment] 2022-05-11 08:46
And also Need for Speed: Shift.
![Screenshot (40)](https://user-images.githubusercontent.com/37503397/167809063-947b1e25-1349-4136-9eac-cc9d5fb2ed75.png)

**Comment by hrydgard** [comment] 2022-09-10 21:33
[Burnout Dominator ULES00703_0002.zip](https://github.com/hrydgard/ppsspp/files/9541422/Burnout.Dominator.ULES00703_0002.zip)

VRAM locations:

00000/88000 : Main color framebuffers, 8888
04170000: Small framebuffer where we accumulate the sun copy?
04176000: This is the CLUT for the lens flare. It is treated as a framebuffer for manipulation.
04178000: Z buffer when drawing to the CLUT (!)

After step 6432, it does a block transfer, copying away the 14x14 sun location for later to RAM.

Then it draws a red 14x14 rectangle to the framebuffer at the sun position, with an ALWAYS stencil test and keep/keep/keep, ending up writing 0x02 to stencil I think. Standard alpha blend, there's an alpha test but no texture.

Then it draws another one but white, this time with depth test. I think these two draws together extracts a sky mask from the depth buffer, effectively. No difference in the stencil test, so that part might be irrelevant.

Now, for whatever reason it configures a giant 1024x1024 texture size but still 512 stride. This seems to cause us to miss matching the framebuffer, maybe? not sure, looks odd in the GE debugger. Texture and framebuffer are both 40880000 / 4000000, 8888 format.

Renders to itself multiple times out in the border, so a Killzone-like split could be workable to reduce the size of the copy. It does a 2x2 shrink at at time, except the last one is a 4x1, which now thus has a 2x1 gradient of sun brightness stretched across 4 pixels.

Then is does two block transfers: One appears to restore the 14x14 rectangle to the image from RAM (see the first copy). 

The other initializes the CLUT at 04176000 with some default data from RAM.
Then it sets up a framebuffer exactly there, 16-bit 565. (here we must initialize it with the just-copied data).
The only draw call that happens on this framebuffer, which is what we'll later use for a CLUT when rendering the flares, covering it, is:

```
X		Y		Z		U		V		Color		NX		NY		NZ
0.000000	0.000000	0.244144	1.500000	0.500000	ffffffff	0.000000	0.000000	1.000000
512.000000	1.000000	0.244144	1.500000	0.500000	ffffffff	0.000000	0.000000	1.000000
```
```
TexSync
Alpha blend enable: 0
Z test enable: 1
ZMask: disable write
MaskRGB: 071fff (bits not to write) << !!!!!!  Cutting down the 888 channels to a 565 mask, this is 01110 000111 11111, or in reverse, 10001 111000 000000, which is very weird to me. Writes a few bits to blue and green??
Stencil op: fail=REPLACE, pass/depthfail=KEEP, pass=REPLACE  (NOTE! Disabled)
Framebuf ptr: 0x04176000
Framebuf stride: 0x200 (extra 040000)
Framebuf PixelFormat: 565
Zbuf ptr: 178000
Zbuf stride: 0x200 (extra 040000)
NOP
NOP
TexFormat CLUT8
Texture size 0: 4x1 (extra 000002)
CLUT addr: high=04  <<unused
CLUT addr: low=177000 <<unused
Clut format: 00ff03 (ABGR 8888)
CLUT addr: high=08
CLUT addr: low=ae4760
Clut load: 08ae4760, 1024 bytes
TexSync
Texture stride 0: 0x0200, address high=04
Texture address 0: low=088780
Texture stride 4: 0x0010, address high=08
Texture address 4: low=809400
VADDR: 9f8570 => 089f8570
DRAW PRIM RECTANGLES: count= 2 vaddr= 089f8570
```

No idea why it sets up level 4 and 5, only 1 level is used, so we can ignore that.

This draw call is very strange because it doesn't even have blending enabled, I'd have expected it to take the value and brighten/darken the CLUT, but instead it seems to replace some bits in it using the bitmask (which we're gonna have to enable...).

Anyway, while writing to the flare CLUT, it samples a single texel from a 4x1 texture at 88780 which is an offset inside the main framebuffer, specifically the 4x1 summary texel from the pyramid downsampling. BUT! It samples it as if it was CLUT8 and at x=1.5!  What is going on... 

I'm confused.

Also it uses depth testing when drawing to the CLUT and has its own little Z buffer! No idea what for.

In the end, once it has the modified CLUT, it draws a bunch of quads using this texture:

![image](https://user-images.githubusercontent.com/130929/189500425-354adbcb-b04d-4190-99e5-31d8ab7edb02.png)

Oh found another bug in the GE debugger, block transfer size isn't consistent between disassembly and the parameter viewer tabs, there's an off by one.

**Comment by unknownbrackets** [comment] 2022-09-11 02:05
Did some tests for width/height of textures, in case related.

For 8888 textures (largest) through or transform, textures up to 512x512 work just as everyone knows and expects.
Larger textures than 512, even 1024x1, "work" but clamp/wrap behavior kicks in at the 512 boundary regardless.

For example, suppose I drew x 1024x1 texture to the screen at 256x256 with S set to CLAMP.  I would see the leftmost 512 texels reduced down to the left 128 pixels.  The right half would all be the 512th texel repeated.  Switching to WRAP would repeat the left side on the right.  It would in any case be impossible to sample the right 512 texels.  The same behavior replicates for height.

This pattern is consistent for all texture formats, from CLUT4 to 8888.

So in this case, as long as it only samples from the first 512x512, it may "just work", and only really affects the UV -> ST coordinates (1.0f would map to 1024, even though the actual texture data is 512x512.)

-[Unknown]

**Comment by hrydgard** [comment] 2022-09-11 17:32
OK, so things that go wrong right now:

* My prototype CLUT8 from 8888 at non-1x resolutions seems to read the wrong pixels or something. hard to tell
* The buffer copy to the palette that is supposed to initialize it every frame, it copies to the wrong buffer. This shouldn't matter too much though since we're overwriting the alpha bits each frame. Arguably we maybe shouldn't take seq into account for copy destinations? Or just heavily boost exact matches. Hm.
* No Z upload, so both alpha and green will be inadvertently modified.
* The rest does appear to work, the CLUT download etc, although alpha .

There's a LOT of moving parts...

**Comment by hrydgard** [comment] 2022-09-12 10:31
![image](https://user-images.githubusercontent.com/130929/189632159-3149af2f-d0e0-4e4d-90e1-95e8dd75c4a4.png)

Progress: 

* CLUT8-from-8888 now works at 1x at least
* Using CLUT downloads, so not super fast
* Not yet implemented Z upload (to mask off each half CLUT color), so evil green infects the CLUT for the flare texture

Still, the flare disappears when the sun is covered quite nicely! Getting there!

**Comment by hrydgard** [comment] 2022-09-12 13:53
https://user-images.githubusercontent.com/130929/189671832-a961cf28-57aa-4d21-80d2-686b07fd3975.mp4

Phew, with a pile of hackery it works :) Now to generalize and make nice, and also ideally make it work at higher res...

**Comment by Gamemulatorer** [comment] 2022-09-22 17:53
The SUN still no show using opengl backend.

**Comment by hrydgard** [comment] 2022-09-22 20:20
Yeah, I know. It does work on desktop GL, but I'll have a look at mobile too soon...

**Comment by hrydgard** [comment] 2023-02-04 16:47
So this broke again with e5d67119a88877b1e442b2b7be170f92186a367c , which is not all that surprising, but we'll have to add some additional checking.

**Closed** 2023-02-04 18:28 UTC
Labels: GE emulation
