### ISSUE TITLE
V8 Supercars 3 Shootout - guardband glitchfix not enabled on Mali G71

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#12008] opened 2019-04-30 08:09 UTC
### What happens?

![PPSSPP_2019-04-30-09-55-52](https://user-images.githubusercontent.com/38067925/56947877-bb816d80-6b2e-11e9-9439-85ef4c7fecbe.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos.
ppsspp-v1.8.0-143-g122f871c7-android.apk
V8 Supercars 3 Shootout - ULES00614

This problem is similar to this one: https://github.com/hrydgard/ppsspp/issues/11999

**Comment by LunaMoo** [comment] 2019-04-30 10:42
Closing as a duplicate of the mentioned issue. This is not a game specific issue, please don't open an issue for each title requiring guardband, it's bad enough to have them device specific.

**Closed by LunaMoo** 2019-04-30 10:42 UTC

**Comment by Drasikk** [comment] 2019-04-30 12:19
And it would be no better than the gentlemen @hrydgard and @unknownbrackets decide whether or not to closes.

At least I mention that it does not work in the Mali G71.

**Comment by hrydgard** [comment] 2019-04-30 12:23
I mean, it's clearly a duplicate, and yes we are now aware it doens't work on the G71. This will be fixed one way or another.
