### ISSUE TITLE
Armored Core: Last Raven and Silent Line hangs/freezes (1.5.4-673-g3cd92b4d9)

### ISSUE THREAD

**Issue by ReilerTheDragonknight** [hrydgard/ppsspp#10734] opened 2018-03-17 16:14 UTC
Last Raven: Game hangs on the first mission. Looking up to the sun seems to cause it to freeze. The emulator keeps running, but environmental audio keeps looping.
Silent Line: Game hangs on Escort Submarine mission in Zone 1, at the start of the game. When the game begins to load, the game hangs, with the last line being B-17. Audio of a mecha getting into the mission can be heard, as if the game loaded, but the emulator hangs on the screen before the game gets into the mission.
What should happen normally, is that the game loads fine, after all. However, these issues prevent me from actually progressing in the game, which is _**obviously**_ a huge issue, which makes the game **Unplayable**.

Incase you were wondering, I am running this game on Windows 7, with the specified build on the title of this issue. I am using a GeForce 6150 incase you also need that, but my game doesn't have graphical issues anyways. I did this on the default, and my personal settings, only to find that both hang on the same exact moments.

I ask you to fix this as best you can, as there are a large number of people looking to play these games aswell. Thanks for your time.

**Comment by LunaMoo** [comment] 2018-03-17 16:34
Closing as a duplicate of #5999

**Closed by LunaMoo** 2018-03-17 16:34 UTC

**Comment by ReilerTheDragonknight** [comment] 2018-03-17 18:10
That issue is over 2 years old, and there hasn't been any significant progress on it. Doesn't really make sense to say it's a duplicate when nobody even cares to touch it.

**Comment by hrydgard** [comment] 2018-03-17 18:15
Still a duplicate, although yeah, sometimes new issues can serve as reminders even though it's not the way it's supposed to work.

Reading #5999, given the misplaced lens flare too, this could actually be the game reading the depth buffer, expecting some response. Depth buffer reads are not yet implemented and definitely something I want to do at some point, though it's a tricky one.

**Comment by ReilerTheDragonknight** [comment] 2018-03-17 18:17
Oh, I understand then. Godspeed if you do decide to work on it, and best of luck.

**Comment by dulsan** [comment] 2019-03-17 05:16
This has been an on going issue, i am also having problems with it on Silent line. Any ideas of what is happening? Completing the mission is a requirement for the arena challengers. In case your are wondering its the satellite observation mission, for Mirage.

**Comment by unknownbrackets** [comment] 2019-03-17 05:56
This is still a duplicate of #5999 which is still open.  Probably best to centralize any new information there.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Comment by Kayael76** [comment] 2023-01-08 16:17
Going back to this issue, the games don't seem to crash anymore but they definitely flicker when there's this lens flare effect involved (the lens flare texture also often appear on top of everything in hardware rendering but not software)

https://user-images.githubusercontent.com/48800201/211207341-ca779567-2a5e-4ddd-b85c-9bdab416fe64.mp4
