### ISSUE TITLE
Blurry text in tactics ogre

### ISSUE THREAD

**Issue by antarusch** [hrydgard/ppsspp#9779] opened 2017-06-04 19:34 UTC
Greetings,

In the version 1.4.2 of ppsspp and I think the lastest versions of 1.4.1 the font in the game tactics ogre is all 
blurry, the game is almost unplayable because of this.

I'm using android 7.1.1 and the backend is opengl.

**Comment by LunaMoo** [comment] 2017-06-04 19:53
Closing as a duplicate of #9731 which should be already fixed in [latest versions](http://buildbot.orphis.net/ppsspp/).

**Closed by LunaMoo** 2017-06-04 19:53 UTC
