### ISSUE TITLE
PPSSPP Will Crash Then Wont Reopen on iOS

### ISSUE THREAD

**Issue by kayliekay** [hrydgard/ppsspp#10750] opened 2018-03-19 20:30 UTC
What happens?
In a number of scenarios I have had the app crash on me, regardless of settings, and regardless of game. (Both when downloaded by cydia and when installed via side loading.) When the emulator crashes, I can not reopen the app without completely restarting my device. I can technically open the app, but it is completely unusable. If I do try to open the app, it will eventually open after quite a few moments later, when it does open, it will be stuck displaying the menu of available games, and will accept no inputs. My phone will also become very unresponsive until I swipe the app away. I have also noticed when checking the program in CocoaTop, it will show a process in the background but I absolutely can not close it.

 One of three things can cause this issue:
- If I leave the app for more than a few moments via pressing the home button, the app will crash.

- If for any reason I close the app, this will happen.

- There’s also been times where I was playing and it just randomly crashes on me, putting me k to this chain of events.

What *should* happen?
I should be able to open the app normally without having to restart my phone.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

I am running PPSSPP on an iPhone 8+ on iOS 11.0.3 with Electra 1.0.4)

**Comment by unknownbrackets** [comment] 2018-03-20 05:56
Closing this as a duplicate of #9186.  You can see workarounds there and in #10704, another duplicate.

-[Unknown]

**Closed by unknownbrackets** 2018-03-20 05:56 UTC
