### ISSUE TITLE
SOCOM: FTB3

### ISSUE THREAD

**Issue by BreeshChaser** [hrydgard/ppsspp#12405] opened 2019-10-10 00:56 UTC
What happens?

During the mission Stockpile, the sky is unreasonably black (it isn't so in the real PSP version, it's just very gray but light is still visible) and certain parts of the mission are unbearably dark(once again, regular PSP version is dark, yet still completely visible). To make matters worse, once the mission concludes and reaches the end of the 2nd cut scene, the emulator will quickly stop working and return me to my device's home screen. When I reopen the app, it's as if I never even attempted the mission. Even if I save state right before this occurs, the same exact thing will take place. 

What *should* happen?

The sky should be snowy gray not black and lighting should still be affected by the 'daylight'. Since the daylight is black, any where not outdoors is way too dark and instead should be dark but actually visible. (I can't even see the staircase at the very end, I literally have to guess it's location). And the game at the end of 2nd cut scene should take me to the post mission menu, viewing my stats and credits earned for the mission, then back to the campaign menu, along with Stock pile being counted as completed. Act 2 should also commence. 

What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

 Any mobile device or tablet I use. Any version of the game I install(US, EU, Asia). PSP-1000, PPSSPP Gold and Blue(the PSP-2000/3000 does not work at all, for every game it runs SO slow). Gameplay itself for this game makes me forget it's not actually a PSP, until I reach this mission.

**Comment by Drasikk** [comment] 2019-10-10 05:43
Duplicate of https://github.com/hrydgard/ppsspp/issues/10976

**Closed** 2019-10-10 07:21 UTC

**Comment by hrydgard** [comment] 2019-10-10 09:04
I moved #6963 to the list of issues to be looked at before 1.10.

**Comment by BreeshChaser** [comment] 2019-10-10 09:58
That is wonderful news. I hope it gets resolved soon.
