### ISSUE TITLE
Text in NFS Most wanted 5.1.0

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10112] opened 2017-11-13 07:14 UTC
I have a problem with the nfs game Most wanted with the text only in the game but not in the menu. it's just text that changes its position. Screenshot: 
   https://photos.app.goo.gl/Cn3Al7C0Cajh7PWP2

**Comment by unknownbrackets** [comment] 2017-11-13 07:28
Does this happen on a desktop / laptop as well?

Has it always happened, or did it only start happening since some new version of PPSSPP?

Does this happen when you using original PSP fonts (they're copyrighted, so you probably need a PSP to get them)?

-[Unknown]

**Comment by marosis** [comment] 2017-11-13 07:37
I have this game on android And this problem wasn't in last version of ppsspp

**Comment by marosis** [comment] 2017-11-13 08:06
I tried something Now And this problem Is created by hardware transforming

**Comment by hrydgard** [comment] 2017-11-13 08:51
Vulkan or OpenGL_

**Comment by marosis** [comment] 2017-11-13 09:22
OpenGL

**Comment by marosis** [comment] 2017-11-13 09:52
When i off hardware transforming, there Is new problem. https://photos.app.goo.gl/Y6sxYq8rAR3LyNB32   I have off Disable slower effects(Speed Up). When Is on in game I can see problem what have Ridge racer( Ridgeracer dont using Hw transforming like this screenshot https://photos.app.goo.gl/Tbp3o8ojieE8hthh1 this Is on Disable slower effects(Speed Up) and this Is off  https://photos.app.goo.gl/gU8OkNylSHPkXtm72) everywhere used Buffered rendering. And offed hardware transforming

**Comment by marosis** [comment] 2017-11-13 09:53
Ridgeracer have same problem like nfs

**Comment by marosis** [comment] 2017-11-13 09:53
Sorry my bad english

**Comment by marosis** [comment] 2017-11-13 10:04
Here you can see it: https://photos.app.goo.gl/2oEGXH9zpVjMfIqm1 (ridgeracer)
        https://photos.app.goo.gl/F9MxIayOmGMrPX182 (NFS)

**Comment by 66Muramasa** [comment] 2017-11-13 21:28
I'm getting the same issue on Vulkan, as well.  Hardware Transforming unticked does allow the text to show, but causes performance issues.

**Comment by hrydgard** [comment] 2017-11-13 21:31
Interesting bug, thanks for reporting.

**Comment by marosis** [comment] 2017-11-13 21:43
:)

**Comment by marosis** [comment] 2017-11-13 22:02
I think in July

**Comment by marosis** [comment] 2017-11-13 22:11
In build 305 Is everything ok. I will trying 300 +

**Comment by marosis** [comment] 2017-11-13 22:28
Problem Is between built 305-330

**Comment by marosis** [comment] 2017-11-13 22:28
I think we can fix it

**Comment by hrydgard** [comment] 2017-11-13 22:55
Yeah, of course. I have some ideas, but it will have to wait for tomorrow.

**Comment by marosis** [comment] 2017-11-14 12:07
Hrydgard problem fixed in build 784 THX a lot.  Lets go close this issue

**Comment by marosis** [comment] 2017-11-14 12:12
Can it be closed? Working fine in Vulkan?

**Comment by hrydgard** [comment] 2017-11-14 12:20
Oh, that fixed it? Neato. The fix is independent of API so I'd expect so, closing.

**Closed by hrydgard** 2017-11-14 12:20 UTC

**Comment by 66Muramasa** [comment] 2017-11-14 20:20
Confirmed.  The issue is also fixed while using Vulkan.
