### ISSUE TITLE
[iOS] PPSSPP is becoming an in interruptable process

### ISSUE THREAD

**Issue by Wh0ba** [hrydgard/ppsspp#11716] opened 2019-01-05 15:08 UTC
### What happens?
Installed it as an IPA on my jailbroken iPhone 
And launched it played for sometime and closed it then tried to open it again and it refused to open and crashed my Springboard 
And now it keeps showing in my process list (when using ps or top)
And I cannot kill it at all 
Even after removing it and respringing
It keeps on running 
And top is showing me that it's in D state
Which forced me to reboot to kill it 
### What *should* happen?

It should run with no problems 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

iOS 10.2 iPhone 5s (latest version for iOS )

**Comment by unknownbrackets** [comment] 2019-01-05 16:58
This issue is being closed as a duplicate of #9186.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-01-05 16:58 UTC
