### ISSUE TITLE
Open GL problems on Monster Hunter Portable 3rd HD Ver.

### ISSUE THREAD

**Issue by marcusowenxx** [hrydgard/ppsspp#13275] opened 2020-08-12 06:02 UTC
Monster Hunter Portable 3rd HD Ver. always crashing on Open GL backend, the game runs very well on full speed however if I go to a quest especially on Sandy Plains map the game will start glitching and crash. If I switch the backend to Vulcan it kinda lags (60-70/100% speed) and need to enable fps cheat, however it also start to lag and crash when I start battling large monsters.

This problem only occurs on this game, I played many games like God of War, Daxter & Tekken and they all run fine. 

My Specs : 
Oppo A3s
• Android 8.1
• Snapdragon 450 1.8 GHz Octacore
• Adreno 506
• 2gb RAM 

PPSSPP ver 1.10.3 (also occurs on older versions and the latest beta)

**Comment by i30817** [comment] 2020-08-12 07:41
Did you try switching the model of the emulated psp to the max speed?

**Comment by marcusowenxx** [comment] 2020-08-12 09:04
> Did you try switching the model of the emulated psp to the max speed?



> Did you try switching the model of the emulated psp to the max speed?

The PSP Model is set to PSP 2000/3000

**Comment by Gamemulatorer** [comment] 2020-08-14 03:18
This is clearly a duplicate of #11410

**Comment by Gamemulatorer** [comment] 2020-09-09 06:56
> This is clearly a duplicate of #11410

@hrydgard ?

**Comment by hrydgard** [comment] 2020-09-09 07:14
So it seems. Closing as dupe of #11410.

**Closed by hrydgard** 2020-09-09 07:14 UTC
