### ISSUE TITLE
Danball Senki W V2.02 doesn't boot on v 1.12.3 

### ISSUE THREAD

**Issue by SFZeroEXE** [hrydgard/ppsspp#15206] opened 2021-12-06 16:35 UTC
### Game or games this happens in

NPJH50618 Danball Senki W

### What area of the game / PPSSPP

On starting the game I get black screen with no sounds or anything although the game worked on older versions and still works on them

### What should happen

I should be able to see the menu and save selection after the opening

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Poco X3 Pro

### PPSSPP version affected

1.12.3

### Last working version

1.11.2

### Graphics backend (3D API)

Vulkan/OpenGl

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2021-12-06 17:08
There are people reporting it working fine and screenshots showing it:

https://report.ppsspp.org/game/NPJH50618_1.00
https://report.ppsspp.org/game/NPJH50618_2.00

Please check your disc CRC to check for corruption.  If it looks correct, and default settings still won't boot the game, please try some git builds in between v1.11.2 and v1.12.3:

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

If you try one half-way between the two, and then another half-way between the latest working one and most recent broken one... you'd narrow it down significantly.  This might help find what's happening, especially to explain why it's not happening to everyone.

-[Unknown]

**Comment by MojoJojoDojo** [comment] 2021-12-06 18:04
Maybe it got issues with the update files for the game? Related to scoped storage on Android?

**Comment by ANR2ME** [comment] 2021-12-06 18:39
May be using texture replacement just like the other issue?

**Comment by SFZeroEXE** [comment] 2021-12-06 19:25
It's working fine on 1.11.2

**Comment by SFZeroEXE** [comment] 2021-12-06 19:25
> May be he is using texture replacement just like the other issue?

Nope not using it

**Comment by SFZeroEXE** [comment] 2021-12-06 19:27
Note that I'm using v 2.02 not v 2.00

**Comment by MojoJojoDojo** [comment] 2021-12-06 19:31
Game works for me on both Linux/Windows with the 2.02 version.
Maybe its something Android specific.

**Comment by ANR2ME** [comment] 2021-12-06 19:47
Or may be some settings he is using (ie. custom CPU clock)?
@SFZeroEXE have you tried resetting the settings to default and see if it makes any difference?

Btw, as i remembered Windows and Android have a different default settings for the "I/O Timing Method", so you may also want to test all the i/o timing method.

**Comment by SFZeroEXE** [comment] 2021-12-06 19:50
> Or may be some settings he is using (ie. custom CPU clock)? @SFZeroEXE have you tried resetting the settings to default and see if it makes any difference?
> 
> Btw, as i remembered Windows and Android have a different default settings for the "I/O Timing Method" (when reset to default), so you may also want to test all the i/o timing method.

Yes it's set to fast

**Comment by Panderner** [comment] 2021-12-07 12:23
This must be related to #15188. @SFZeroEXE are you using a latest build of PPSSPP?

**Comment by SFZeroEXE** [comment] 2021-12-07 13:07
> This must be related to #15188. @SFZeroEXE are you using a latest build of PPSSPP?

Yes and the game's not working on it

**Comment by Panderner** [comment] 2021-12-07 13:09
Good try v1.12.3-340 build

**Comment by Gamemulatorer** [comment] 2021-12-07 14:10
> Good try v1.12.3-340 build

He said it's not working since v1.12.3 playstore.

**Comment by SFZeroEXE** [comment] 2021-12-07 16:38
> Good, try v1.12.3-340 build

Not working too

**Comment by Panderner** [comment] 2021-12-08 01:44
> > Good, try v1.12.3-340 build
> 
> Not working too

Ok it's not related to #15188 good job.

**Comment by ANR2ME** [comment] 2021-12-14 03:25
According to @SFZeroEXE this game doesn't boot only on Android, while it works on Windows

**Comment by Panderner** [comment] 2021-12-14 04:11
It seems work fine for my phone:
![Screenshot_2021-12-14-12-10-27-681_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/145931688-d8b969f1-ca98-4273-b513-24ee84b159bf.jpg)

**Comment by SFZeroEXE** [comment] 2021-12-14 04:16
> It seems work fine for my phone: ![Screenshot_2021-12-14-12-10-27-681_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/145931688-d8b969f1-ca98-4273-b513-24ee84b159bf.jpg)

Which version of the iso is that?

**Comment by SFZeroEXE** [comment] 2021-12-14 04:24
Here

**Comment by Panderner** [comment] 2021-12-14 04:29
The ISO version for me is v2.00

**Comment by SFZeroEXE** [comment] 2021-12-14 04:42
Yes v 2.00 works on 1.12.3 I can confirm that ,the problem is v 2.02

**Comment by unknownbrackets** [comment] 2021-12-14 05:04
According to some quick googling, the behavior you describe occurs for people even in past versions when files under PSP/GAME are not present.  I'm suspecting that those files aren't being detected by the game.

It'd still be helpful to know which git build this stopped working in.

For now, I'd also suggest you:
1. Reselect your memory stick folder in PPSSPP system settings.
2. Validate that the update files are present in the correct location within PSP/GAME, just like on the PC where it works.
3. Try starting the game again.
4. If possible, obtain a log of any errors using this guide: https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

I'll note that for compatibility, we have a special mode where you can select a "PSP" folder and it's treated as the root AND the PSP folder of the memory stick.  This behavior is Android only, and it's possible it's somehow the cause.

If the above steps don't help it run, I suggest you move your PSP folder into a folder named "PPSSPP" using PSP's memory stick folder tool.  Make sure the game update files are moved too.  Then try again.

If that fixes it, then we'll know there's something wrong with that special PSP folder mode.

-[Unknown]

**Comment by Panderner** [comment] 2021-12-14 05:09
Umm yes v2.02 ISO requires the v2.02 update files, please place the update files to PSP/GAME directory.
If the update files are not present it won't boot.

Here's my screenshot for v2.02 ISO is working file with update files present:
![Screenshot_2021-12-14-13-08-02-787_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/145936783-da73d169-d23a-4bd9-bdc9-784a62f8944c.jpg)

**Comment by SFZeroEXE** [comment] 2021-12-14 12:00
> Umm yes v2.02 ISO requires the v2.02 update files, please place the update files to PSP/GAME directory. If the update files are not present it won't boot.
> 
> Here's my screenshot for v2.02 ISO is working file with update files present: ![Screenshot_2021-12-14-13-08-02-787_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/145936783-da73d169-d23a-4bd9-bdc9-784a62f8944c.jpg)

The update files are in that directory already and I have the extra chapter and everything also if the problem were the update files then it shouldn't be working on the older versions right?
Guess it's a MIUI compatibility

**Comment by Panderner** [comment] 2021-12-14 12:05
@SFZeroEXE what android version are you using?

**Comment by SFZeroEXE** [comment] 2021-12-14 12:19
Android 11

**Comment by Panderner** [comment] 2021-12-14 12:22
Working fine for Android 10 phone.

**Comment by SFZeroEXE** [comment] 2021-12-14 12:39
Android 11 problem then?

**Comment by SFZeroEXE** [comment] 2021-12-14 20:41
The same problem happens on Android 8 too the game just shows a black screen on v1.12.3

**Comment by SFZeroEXE** [comment] 2021-12-14 20:54
> According to some quick googling, the behavior you describe occurs for people even in past versions when files under PSP/GAME are not present. I'm suspecting that those files aren't being detected by the game.
> 
> It'd still be helpful to know which git build this stopped working in.
> 
> For now, I'd also suggest you:
> 
> 1. Reselect your memory stick folder in PPSSPP system settings.
> 2. Validate that the update files are present in the correct location within PSP/GAME, just like on the PC where it works.
> 3. Try starting the game again.
> 4. If possible, obtain a log of any errors using this guide: https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC
> 
> I'll note that for compatibility, we have a special mode where you can select a "PSP" folder and it's treated as the root AND the PSP folder of the memory stick. This behavior is Android only, and it's possible it's somehow the cause.
> 
> If the above steps don't help it run, I suggest you move your PSP folder into a folder named "PPSSPP" using PSP's memory stick folder tool. Make sure the game update files are moved too. Then try again.
> 
> If that fixes it, then we'll know there's something wrong with that special PSP folder mode.
> 
> -[Unknown]

Yes but once they put the update data in the right folder the game works , but in my case the game works on older versions and detects the update data enabling me to access the extra chapter

**Comment by Panderner** [comment] 2021-12-15 05:00
H@SFZeroEXE can you post the logs ​for errors?

Here's a log if the update files are not present:
```
57:08:041 CRI FS File  E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:57 DirectoryFileSystem::OpenFile('/PSP/GAME/NPJH50618/DA2File_psp_ex02.EDAT'): FAILED, 2 - access = 1 ''
57:08:044 CRI FS File  E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:57 DirectoryFileSystem::OpenFile('/PSP/GAME/NPJH50618/DA2File_psp_ex01.EDAT'): FAILED, 2 - access = 1 ''
57:08:059 CRI FS File  E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:57 DirectoryFileSystem::OpenFile('/PSP/GAME/NPJH50618/DA2File_psp_ex01.EDAT'): FAILED, 2 - access = 1 ''
57:08:114 CRI FS File  E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:57 DirectoryFileSystem::OpenFile('/PSP/GAME/NPJH50618/DA2File_psp_ovl.DNS'): FAILED, 2 - access = 1 ''
```

**Comment by SFZeroEXE** [comment] 2021-12-15 05:16
Nice , I'll try to get the log file today cuz y'know that this step needs a PC to be done

**Comment by ANR2ME** [comment] 2021-12-15 05:28
> Nice , I'll try to get the log file today cuz y'know that this step needs a PC to be done

i think you can also use logcat app to get the logs on android, make sure to filter the log only for PPSSPP because it's a shared logs, thus mixed with logs from others.

**Comment by Panderner** [comment] 2021-12-15 07:38
> > Nice , I'll try to get the log file today cuz y'know that this step needs a PC to be done
> 
> i think you can also use logcat app to get the logs on android, make sure to filter the log only for PPSSPP because it's a shared logs, thus mixed with logs from others.

Umm @ANR2ME it needs rooted device to get logs without a PC?
![IMG_20211215_153718](https://user-images.githubusercontent.com/37503397/146143591-4c3c47c6-ef24-47d5-922d-87af76925c14.jpg)

**Comment by Gamemulatorer** [comment] 2021-12-15 07:43
> > > Nice , I'll try to get the log file today cuz y'know that this step needs a PC to be done
> > 
> > 
> > i think you can also use logcat app to get the logs on android, make sure to filter the log only for PPSSPP because it's a shared logs, thus mixed with logs from others.
> 
> Umm @ANR2ME it needs rooted device to get logs without a PC? ![IMG_20211215_153718](https://user-images.githubusercontent.com/37503397/146143591-4c3c47c6-ef24-47d5-922d-87af76925c14.jpg)

Use LADB to grant adb permission without rooted

**Comment by Gamemulatorer** [comment] 2021-12-16 03:57
@SFZeroEXE https://youtu.be/4zKespn_OHg

**Comment by SFZeroEXE** [comment] 2021-12-16 15:42
> @SFZeroEXE https://youtu.be/4zKespn_OHg

Thx but I didn't work for some reason gonna try the PC method after all

**Comment by hrydgard** [comment] 2021-12-16 15:44
![image](https://user-images.githubusercontent.com/130929/146402696-41ef5fd5-e011-403b-8f40-4abe0fc60f1e.png)

seems like another wacky case sensitivity issue, possibly related to #15236

**Comment by SFZeroEXE** [comment] 2021-12-16 16:54
[ppsspp.log](https://github.com/hrydgard/ppsspp/files/7729050/ppsspp.log)

**Comment by SFZeroEXE** [comment] 2021-12-16 16:54
Finally

**Comment by Saramagrean** [comment] 2021-12-17 08:24
Confirm, It fixed by https://github.com/hrydgard/ppsspp/pull/15237 :)

**Comment by hrydgard** [comment] 2021-12-17 08:36
Thanks for testing @Samagrean !

I'll close this, please comment if there are any further issues booting the game, and I'll reopen.

**Closed by hrydgard** 2021-12-17 08:36 UTC
Labels: Platform-specific (Android)
