### ISSUE TITLE
God of War (CoO & GoS) - Effects applying to half of the screen in OpenGLES

### ISSUE THREAD

**Issue by BreakPoints** [hrydgard/ppsspp#11321] opened 2018-08-25 15:33 UTC
### What happens?
In both God of War games, half the screen has a different tinted colour to it and some full screen effects only apply to the top half. This only applies to OpenGLES, Vulkan and OpenGL on desktop do not have this problem.

![screenshot_20180825-161154](https://user-images.githubusercontent.com/11966090/44619657-50d2b080-a882-11e8-9c2f-7152b4f9b355.jpg)
(The explosion effect is adding bloom and an orange tint to the top half of the screen, more so than the bottom)

![screenshot_20180825-161149](https://user-images.githubusercontent.com/11966090/44619658-50d2b080-a882-11e8-9b0d-d8b764adf2cd.jpg)

(Colour difference can be difficult to see on TN monitors but is prominent on my phones AMOLED display)

### What *should* happen?
Colour tinting/post effects should fill the whole screen, like seen bellow.

![screenshot_20180825-162746](https://user-images.githubusercontent.com/11966090/44619907-123df580-a884-11e8-805e-2a32cba60824.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
OnePlus 6 - SD845
Android 8.1 - OxygenOS 5.1.11
PPSSPP v1.6.3-358-g17de6ad2d (same on latest stable release)
OpenGLES only

**Comment by unknownbrackets** [comment] 2018-09-01 04:12
According to vulkan.gpuinfo.org, that device supports dualSrcBlend on Vulkan, but does not support blend_func_extended on GLES.  My guess is missing dual source blending is the cause.

I'm not sure if there's much we can do to workaround if so, without doing two pass rendering which would probably be a good bit slower...

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-09-11 12:27
This is still an issue? mine is Redmi Note Mali-G52 GPU only fewer shaders support compare to adreno 630 high-end.
Cannot reproduce this on the latest git build.
![Screenshot_2021-09-11-20-23-16-172_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132947831-8628f3b0-7fdf-45b0-98e0-d97b2da4ee38.jpg)
![Screenshot_2021-09-11-20-23-20-719_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132947833-4ad50442-4975-4689-a8a0-95b30b729d8e.jpg)

**Comment by BreakPoints** [comment] 2021-09-11 12:32
If this issue is specific to the OnePlus 6 with SD845 then I won't be able to retest as that phone has been laid to rest ever since a chance encounter with a jacuzzi

**Comment by hrydgard** [comment] 2021-09-11 12:44
Oops! Well, I don't think we'll dig into this until the issue is reported again. Closing.

**Closed by hrydgard** 2021-09-11 12:44 UTC
