### ISSUE TITLE
The camera stuck in Vice city Stories

### ISSUE THREAD

**Issue by 3lc3z4r** [hrydgard/ppsspp#15564] opened 2022-05-31 20:28 UTC
### Game or games this happens in

ULES-00502 Gta Vice City Stories (EUR)

### What area of the game / PPSSPP

in some scenes of the game (either interior rendering scenes or real-time scenes) the camera is possibly stuck on a wall and a totally gray screen is shown even without showing subtitles (I previously saw a post similar to this but no I know if I managed to fix it).
I already made the change of graphic API and it's still the same
![imagen_2022-05-31_151822140](https://user-images.githubusercontent.com/106557341/171277398-997a8fc8-24e7-45e4-90d6-59eab7693881.png)

### What should happen

According to some information and videos as well as testimonials, in a real psp it does not happen as it is also mentioned that the error was not found in old versions (I cannot confirm this at all because even in the tutorial videos of the game played in the emulator Being the oldest, this error was still found)

### Platform

Windows

### Mobile phone model or graphics card

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz

### PPSSPP version affected

1.12.3

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-06-01 04:12
This issue is being closed as a duplicate of #12060.  If your GPU supports it, try in the latest git build.  Otherwise try with "hardware transform" disabled in the latest git build.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-06-01 04:12 UTC

**Comment by 3lc3z4r** [comment] 2022-06-01 19:31
> This issue is being closed as a duplicate of #12060. If your GPU supports it, try in the latest git build. Otherwise try with "hardware transform" disabled in the latest git build.
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

thanks for your patience, I already solved it) the other time I just checked that post but outside the same website and I didn't understand how to solve it. It really was a good decision of mine to have created a github account for these cases (reddit is not much use for this let's say)
