### ISSUE TITLE
When The iOS ppsspp working on Metal Gear Solid: Peace Walker，graphic issues happening

### ISSUE THREAD

**Issue by liuxiaohuan26** [hrydgard/ppsspp#8929] opened 2016-08-23 06:38 UTC
the ppsspp of ios version has some graohic bugs when playing the game Metal Gear Solid: Peace Walker.The apperance of Snake can not be displayed normally.Please to solve the issues.Thank you very much.

**Comment by seadil** [comment] 2016-08-27 14:55
Please provide these information:

- Device
- iOS Version
- Version of PPSSPP
- Jailbroken or not

Would be interesting to see what kind of issue you're having with this game. If possible, provide also screenshots.

**Comment by Fadi5555** [comment] 2016-08-27 15:21
Me too I have the same issue.
My device details:

iPad Air 2 / iOS 9.3.3 / jailbroken by Pangu.

This is my screenshot of the issue:

![image](https://cloud.githubusercontent.com/assets/10546081/18028281/0b1f9ff4-6c83-11e6-89e3-711acff4e32a.jpeg)

**Comment by unknownbrackets** [comment] 2016-08-27 19:37
This issue is being closed as a duplicate of #8876.

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2016-08-27 19:37 UTC
