### ISSUE TITLE
Silent Hill 0 Text Oversized

### ISSUE THREAD

**Issue by Zetchzie** [hrydgard/ppsspp#9383] opened 2017-03-04 04:53 UTC
Silent hill zero seems to have an issue with text its all oversized happens on all Backends

![ulus10285_00000](https://cloud.githubusercontent.com/assets/15071652/23576194/89a0edd8-006c-11e7-8aff-358742a2a1fc.jpg)

**Comment by LunaMoo** [comment] 2017-03-04 05:23
This is another game which uses system fonts, unfortunately Sony's font is copyrighted / part of PSP system so we can't redistribute it and the free font we do have is far from perfect. If you have PSP, you will have to get original Sony's font and replace the default PPSSPP font with it(flash0\font folder). You could also try and find a different free font that fits this game better, unfortunately there are no free PSP fonts that fit every game.

 I'm closing this since the issue is tracked already in #2788

**Closed by LunaMoo** 2017-03-04 05:23 UTC

**Comment by Zetchzie** [comment] 2017-03-04 05:28
thank you for the answer ^^
