### ISSUE TITLE
Speed up the mouse wheel

### ISSUE THREAD

**Issue by Gamernumberone** [hrydgard/ppsspp#18564] opened 2023-12-17 09:32 UTC
### What should happen

 I noticed that the buttons are faster compared to the mouse wheel

### Who would this benefit

PPSSPP

### Platform (if relevant)

Windows

### Games this would be useful in

PPSSPP

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment] 2023-12-17 10:06
Mouse Wheel "ticks" in 16 ms which means it's ~1 frame in 60 fps games. It can't really be "faster", so you probably just compare apples to oranges. Wheel triggers multiply times when scrolled and that's what it does, key while pressed is just continuosly ON, it will not behave same way in-game.

**Comment by Gamernumberone** [comment] 2023-12-17 10:33
I don't know, but for example, in the original GTA vc, we bring the rifle closer faster than if we do this stories in mouse wheel.

**Comment by LunaMoo** [comment] 2023-12-17 10:40
I know nothing about GTA VC, I do know however that if I unlock wheel on my mouse effectively simulating "key being pressed" it works exactly same as pressing key.
 But by design and in most cheaper rodents without even an option to change it, mouse wheel behaves differently. It has stepping, it stops every time you feel that step. This is as fast as it can be, so it feels like pressing key very fast instead of holding it.
 So again, you don't want it faster(it can't really be from PSP games perspective), you might want to have an option to make it slower, but doing so will have side effects of not instantly finishing when you stop scrolling, so might not be that great.

**Comment by LunaMoo** [comment] 2023-12-17 11:30
You can try #18565, after it finishes building, you can get windows build in https://github.com/hrydgard/ppsspp/actions/runs/7238190421 under "artifacts", you'll find new option under mouse control settings to delay mouse wheel, when it's slower, it should closer resemble pressing of a buttons.

**Comment by LunaMoo** [comment] 2023-12-17 13:03
Did you tried the new mouse wheel delay option in the build from https://github.com/hrydgard/ppsspp/actions/runs/7238190421 ?

**Comment by Gamernumberone** [comment] 2023-12-17 13:11
Is this the public version? I don't have anything that I can compile. Is it on the site with the latest builds?

**Comment by LunaMoo** [comment] 2023-12-17 13:17
Go to the above link and check bottom of the page to download build from that PR. You'll find new option under controls->mouse settings-> mouse wheel delay it can be set from 1 which is current behaviour(60 times per second), up to 10 which is 10 times slower, which will keep "presses" longer, but game will see it as "holding" the button for 1/6 of a second which is closer to how you'd press a key by hand, hopefully without making it laggy.

**Comment by Gamernumberone** [comment] 2023-12-17 13:31
yes, I checked it, it's a very good feature, thanks.

**Comment by LunaMoo** [comment] 2023-12-19 02:18
The setting was changed to just different standard behaviour which should be slow enough to resemble key press, closing.
@Gamernumberone please try latest version from buildbot - https://buildbot.orphis.net/ppsspp/index.php and if it doesn't work well, we can reopen.

**Closed by LunaMoo** 2023-12-19 02:18 UTC

**Comment by Gamernumberone** [comment] 2023-12-20 00:31
I like the way it was in the previous one, we could change the value. In new veriosn this removed

**Comment by hrydgard** [comment] 2023-12-20 00:53
Just curious, what gameplay aspect gets better with a shorter time here? 

I'm willing to add the setting back, as long as there's an actual improvement.

**Comment by Gamernumberone** [comment] 2023-12-20 04:15
Zoom sniper rifle GTA VCS on mouse wheel.

**Comment by hrydgard** [comment] 2023-12-20 13:11
I've added a setting, it's under Mouse Control in Control settings.

**Comment by Gamernumberone** [comment] 2023-12-20 22:35
Thanks
