### ISSUE TITLE
Dpad multitouch on a mappable controller

### ISSUE THREAD

**Issue by Kuplejas** [hrydgard/ppsspp#12950] opened 2020-05-22 15:21 UTC
Hello.
Help me understand the issue. I bought a bluetooth controller from Ipega (PG 9156).
It turns out that I have to install an app to use it. The only way this controller seems to work is when I use that damn onscreen controll mapping software. 
Anyway, I'm using ppsspp 1.93v on Android device. I tried to play Tekken 6, but it turns out that dpad multitouch is not working. I can press only one button at a time. And it is ONLY for dpad buttons. Other buttons works just fine (I can press them all at once).  When i press on-screen dpad buttons with my fingers - then multitouch works. I tried different game emulators and dpad multitouch was working fine with that controller and I'm baffled because of that.

**Comment by iota97** [comment] 2020-05-22 15:35
I think the problem is PPSSPP DPad doesn't work even with finger in multitouch: you get the diagonal with 1 finger only pressing between 2 button, you could try pressing it with 2 finger and you won't get the diagonal as well (if they get too close the touch screen might confuse them as one tho').

The controller simulate touch click, so when you press 2 button you get 2 touch rather than 1 in the middle.

Could you try to press between the 2 button with the controller config binded to the combo of 2 DPad key if it support it, but never uses such a controller so I dunno what you may be able to configure.

**Comment by Kuplejas** [comment] 2020-05-22 16:12
You were absolutely right. I just tested it - two touches are ignored. 
Well there are various key binding possibilities in this app but I have no idea how it works. The only way to play right now is to use either touch screen or analog stick (if I insist using controller). Sad.

How obout controllers that doesn't use keymapping? Will they work as intended using built in controll mapping?

**Comment by LunaMoo** [comment] 2020-05-22 16:14
Enable "disable d-pad diagonals" in control, touch control settings.

**Comment by Kuplejas** [comment] 2020-05-22 16:35
I tried that. It only disables onscreen diagonals. No effect on a controller.
Seems really strange, that action keys support multitouch but dpad doesn't. 
Support from these keymapping app sites are completely nonexistent. No way of learning how to map and use diagonals.

**Comment by iota97** [comment] 2020-05-22 17:00
Normal controller (Xbox, dualshock and so on) that doesn't output touch presses work fine and can easily be remapped under control mapping screen in PPSSPP.

Seem really weird that controller have no "standard" mode tho'.

There are some app on android that add touchscreen control outputting as a standard controller I think, you might use them and map the controller to them, but it would feel like a matryoshka.

**Comment by iota97** [comment] 2020-05-22 17:16
Actually there is a solution for this (a bit silly, but it work):

In Controls -> Combo key setup (there are custom key to press multiple button far away or so, but might just have one)

Set combo 1-4 to the 4 dpad direction

In Controls -> Edit touch control layout -> Visibility

Untick Dpad, and enable 1 to 4 (You may move them where you wish in "Edit touch control layout").

Bind the controller to them.

**Comment by Kuplejas** [comment] 2020-05-22 18:30
I found a standard mode. And my gosh there was nothing mentioned on an included manual that came with the controller. Instead I found the instruction on a random Amazon store user comment... 
Sorry guys for bothering you. Huge thanks for answering!

**Comment by Gamemulatorer** [comment] 2020-06-03 07:38
@Kuplejas youe issue is solved?

**Comment by iota97** [comment] 2020-06-03 08:37
This can be closed as a duplicate of #6585.

**Comment by unknownbrackets** [comment] 2020-06-04 06:20
Thanks.  Closing as a duplicate of #6585 then.

I had heard these things had multiple modes.  I've looked into getting one myself, but I don't want to deal with bluetooth latency or losing my headphone jack...

-[Unknown]

**Closed by unknownbrackets** 2020-06-04 06:20 UTC
