### ISSUE TITLE
[Android/Windows] Crash by Inavalid Memory Access [BLEACH SC (UCJS10085) & SC2 (UCJS10106)]

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13346] opened 2020-08-29 01:30 UTC
### What happens?
BLEACH SoulCarnival &BLEACH SoulCarnival 2 sometime crash at timing of loading.
Please see attached screenshot of inavalid memory access.

### What *should* happen?
Don't crash!! Please!!

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver. : 1.10.3-515
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

PPSSPP Ver.：1.10.3-515
OS：Windows10 (64-bit) Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

[BLEACH SoulCarnival]
![BleachSC_InvalidMem](https://user-images.githubusercontent.com/48179091/91625459-8dda5c00-e9e2-11ea-8275-1841e463bb38.png)

[BLEACH SoulCarnival2]
![BleachSC2_InvalidMem](https://user-images.githubusercontent.com/48179091/91625464-96329700-e9e2-11ea-94ff-042986f8368e.png)

**Comment by nassau-tk** [comment] 2020-08-29 08:21
@Panderner
I tried "Simulate UMD delay".
But,invalid memory error happend.
This games are my favorite.
So,I hope solve the issue as soon as possible by masters.

**Comment by hrydgard** [comment] 2020-08-29 08:51
If i started crashing recently, do you think you can go back and try to find approximatly which build it started crashing in?

**Comment by nassau-tk** [comment] 2020-08-29 09:03
@hrydgard 

OK!
I try to find it!!

**Comment by nassau-tk** [comment] 2020-08-29 10:14
@hrydgard 

I find it!! (May be)

v1.10.3-474-gd465ce512 will not happening the issue.
And, v1.10.3-477-g6d117fb53 is happening the issue.

I tried test 5 times on v1.10.3-474-gd465ce512.
It's not happening the error.

![v1 10 3-477_invalidmemoryaccess](https://user-images.githubusercontent.com/48179091/91634455-87bc9d80-ea2b-11ea-86ff-5bc0148437fc.png)

**Comment by hrydgard** [comment] 2020-08-29 10:23
That points to https://github.com/hrydgard/ppsspp/pull/13327, which is a bit unexpected. Thanks for testing!

**Comment by nassau-tk** [comment] 2020-08-29 12:04
Yes!!Master!!
Please, Beat the issue!!

**Comment by nassau-tk** [comment] 2020-11-23 10:02
I continus tested every new build by Soul Carnival1.
It is not solved yet.

But, I over looked Soul Carnival2.
And,I can't reproduce the issue on v1.10.3-1237.

I will looking for last point later.

**Comment by hrydgard** [comment] 2020-11-23 10:53
Hm, note to self, just realized that "clear-detection" could (although far-fetched) have impact since in some cases we zero the cleared area in memory, and if we detect wrong or something, that could overwrite....

I'll try to look at this more soon.

**Comment by nassau-tk** [comment] 2020-11-23 13:46
I retested v1.10.3-515.
But, I can't reproduce the issue on SC2.
Why? I can't understand!

**Comment by hrydgard** [comment] 2020-11-23 14:08
I don't understand either :)

**Comment by nassau-tk** [comment] 2020-12-21 11:41
The issue still happen v1.10.3-1375.
But,I can reproduce only BLEACH SC1.

**Comment by hrydgard** [comment] 2021-01-03 17:07
@nassau-tk If you try this: https://github.com/hrydgard/ppsspp/pull/13863

Does it still happen?

**Comment by nassau-tk** [comment] 2021-01-03 18:29
How can I try this on my phone?
Please, tell me.

**Comment by hrydgard** [comment] 2021-01-03 18:45
Right, okay, I'll just merge it so you get a build, can always revert.

**Comment by nassau-tk** [comment] 2021-01-03 20:02
v1.10.3-1471 is not solved.
![Screenshot_20210104-050033_PPSSPP](https://user-images.githubusercontent.com/48179091/103487594-f7afba00-4e49-11eb-8746-7b82339b1ff1.jpg)

**Comment by hrydgard** [comment] 2021-01-03 20:46
ok, i'll revert it then.

**Comment by sum2012** [comment] 2021-01-03 22:59
@nassau-tk Are you setting is default ?

**Comment by brujo5** [comment] 2021-01-04 01:36
you can play the game by using Interpreter.

hang/freeze in loading screen only happends with JIT or IR interpreter.

**Comment by Panderner** [comment] 2021-01-04 01:52
> ![Captura de pantalla (56)](https://user-images.githubusercontent.com/4172898/103494315-8513ef80-4df3-11eb-8eb4-52090319612d.png)
> ![Captura de pantalla (58)](https://user-images.githubusercontent.com/4172898/103494317-85ac8600-4df3-11eb-931b-7db8a6b913dc.png)
> ![Captura de pantalla (59)](https://user-images.githubusercontent.com/4172898/103494319-86451c80-4df3-11eb-93c0-c8843ee36f19.png)
> 
> You can play the game by switch to Interpreter before loading screen then switch back to Jit. or play all the whole game with interpreter CPU.
> 
> hang/freeze/crash in loading screen only happends with JIT or IR interpreter.

Oh it's a same problem for Tony Hawk's Underground 2 Remix and MTX Mototrax.

**Comment by sum2012** [comment] 2021-01-04 05:04
So it is JIT problem

在 2021年1月4日週一 上午9:52，Panderner <notifications@github.com> 寫道：

**Comment by nassau-tk** [comment] 2021-01-04 06:11
@sum2012 

Maybe, my setting is default.

**Comment by nassau-tk** [comment] 2021-01-04 07:23
> ![Captura de pantalla（56）](https://user-images.githubusercontent.com/4172898/103494315-8513ef80-4df3-11eb-8eb4-52090319612d.png)
> ![Captura de pantalla（58）](https://user-images.githubusercontent.com/4172898/103494317-85ac8600-4df3-11eb-931b-7db8a6b913dc.png)
> ![Captura de pantalla（59）](https://user-images.githubusercontent.com/4172898/103494319-86451c80-4df3-11eb-93c0-c8843ee36f19.png)
> 
> 画面をロードする前にインタープリターに切り替えてから、Jitに戻すことでゲームをプレイできます。または、ゲーム全体をインタープリターCPUでプレイします。
> 
> ロード画面でのハング/フリーズ/クラッシュは、JITまたはIRインタープリターでのみ発生します。
> 
> ここに通訳付きのログ（作業中）
> [ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5762623/ppsspplog.zip)
> 
> ここでjitでログを記録します（機能していません）
> [ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5762626/ppsspplog.zip)




> ![Captura de pantalla (56)](https://user-images.githubusercontent.com/4172898/103494315-8513ef80-4df3-11eb-8eb4-52090319612d.png)
> ![Captura de pantalla (58)](https://user-images.githubusercontent.com/4172898/103494317-85ac8600-4df3-11eb-931b-7db8a6b913dc.png)
> ![Captura de pantalla (59)](https://user-images.githubusercontent.com/4172898/103494319-86451c80-4df3-11eb-93c0-c8843ee36f19.png)
> 
> You can play the game by switch to Interpreter before loading screen then switch back to Jit. or play all the whole game with interpreter CPU.
> 
> hang/freeze/crash in loading screen only happends with JIT or IR interpreter.
> 
> here log with interpreter (working)
> [ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5762623/ppsspplog.zip)
> 
> here log with jit (not working)
> [ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/5762626/ppsspplog.zip)

Um...
I can't reproduce it.

"Way 1"
1. Start PPSSPP.
2. Set interpreter.
3. Play the game.
4. Invalid memory access happen.

"Way 2"
1. Start PPSSPP.
2. Start the game on interpreter.
3. Load save data.
4. Change to JIT.
5. Play the game.
6. Invalid memory access happen.

Is there some wrong way?

**Comment by nassau-tk** [comment] 2021-01-04 07:23
![Screenshot_20210104-155439_PPSSPP](https://user-images.githubusercontent.com/48179091/103510786-3759be80-4ea9-11eb-8da5-56789ad911e2.jpg)

**Comment by hrydgard** [comment] 2021-01-04 08:11
Hm, maybe some of you have different settings for "Ignore invalid memory accesses" system setting in PPSSPP? Or different versions of the games? Not sure..

**Comment by brujo5** [comment] 2021-01-04 14:53
Game version UCJS10085

i think you need to enable ignore bad memory acceses in system settings + interpreter cpu

tested with DX11,GL,DX9

![Captura de pantalla (61)](https://user-images.githubusercontent.com/4172898/103547421-9d225800-4e61-11eb-8ef4-4f9af66566c2.png)
![Captura de pantalla (62)](https://user-images.githubusercontent.com/4172898/103547435-a01d4880-4e61-11eb-95fd-947224190f8c.png)
 
if you uncheck that setting not work.

**Comment by nassau-tk** [comment] 2021-01-04 22:13
@brujo5 

Yes, I could reproduce your way to avoidance.

**Comment by unknownbrackets** [comment] 2021-01-18 05:13
See https://github.com/hrydgard/ppsspp/pull/13941#issuecomment-761982376 - DisableFirstFrameReadback doesn't make a difference.  LSU might just be preventing fast memory from working and triggering the crash screen, I'm not sure.

-[Unknown]

**Comment by nassau-tk** [comment] 2021-01-23 01:49
I found an another point.

PPSSPP: v1.10.3-1614
Back End:Vulkan

1. Select "Load Game".
2. Play 1st Stage and go to Boss Stage.
3. Push " L "  button at Boss Battle. (L is Special PowerUp.)
4. After 2nd time Game was freeze and "Critical dialog" was appear.
5. PPSSPP can't working that will not any response.(Need kiil from task.)

- **From 1st to 3rd times happened the issue.**
- **But, After 4th time is not happeing the issue.**
- **Invalid Memory Access is not appear.**
 
Log is here.(2nd times got it.)
https://gist.github.com/nassau-tk/9fcd630cac4b1636d6aa1c4de353d7db

Critical Dialog is below.
**1st time appear this.**
(If push Yes button then no response.)
![image](https://user-images.githubusercontent.com/48179091/105564572-242e6600-5d66-11eb-9151-45319fc2dfed.png)

**2nd time appear this.**
![image](https://user-images.githubusercontent.com/48179091/105564776-03b2db80-5d67-11eb-94d9-a313249316bf.png)

**Comment by nassau-tk** [comment] 2021-01-23 02:01
Log of when long time wait after freeze.

https://gist.github.com/nassau-tk/f891d3288b1e196ae04eb3aad04af355

**Comment by hrydgard** [comment] 2021-01-24 23:25
Given https://github.com/hrydgard/ppsspp/issues/13346#issuecomment-683270470 , maybe the game relied on something getting zeroed? I don't want to revert that for obvious reasons, but not really sure what to do for 1.11 other than introducing yet another compat.ini hack...

**Comment by unknownbrackets** [comment] 2021-01-25 00:46
Well, it's either zeroing something it shouldn't or not zeroing something it should.

Did this work in OpenGL and Vulkan for 1.9.x (before #12952)?  If it worked in Vulkan then, then it seems like we DON'T want some clear.  If it didn't work in Vulkan then there's some clearing we want.

-[Unknown]

**Comment by nassau-tk** [comment] 2021-01-25 01:17
@unknownbrackets 

I tested on v1.9.3-1077 (1.9.3 last build.).
It's working on Vulkan.

**Comment by iota97** [comment] 2021-01-27 17:50
Checking before and after changes in these [lines](https://github.com/hrydgard/ppsspp/pull/13327/files#diff-832367eae3aa9a9e71f7992d981b6ac8f6db9a70bce7bfa530220946da974062L472):

- clearingColor is false in both version
- writingColor is false in the working one, get true and it crash after the PR (clearing a 480x272 area)

Basically `gstate.getColorMask() != 0xFFFFFFFF` crash while `gstate.getColorMask() != 0` work fine.

Not sure how the color mask is meant to be used, if is "we write only to that part" I guess we write something as long as is not all 0 indeed, but could be the opposite anyway xD

**Comment by unknownbrackets** [comment] 2021-01-30 23:43
Is this reproducible in any demo?

-[Unknown]

**Comment by nassau-tk** [comment] 2021-01-30 23:43
Sometime, If use special arts (Click L Button) then it error will happen.
See below Log & Screenshot..

https://gist.github.com/nassau-tk/620f583c54fd62750a08d30e8557b186

![image](https://user-images.githubusercontent.com/48179091/106370628-19478700-639f-11eb-939b-f026a57769b5.png)

![image](https://user-images.githubusercontent.com/48179091/106370733-4fd1d180-63a0-11eb-9b67-8a110579e74d.png)

**Comment by nassau-tk** [comment] 2021-01-30 23:48
> これはどのデモでも再現できますか？
> 
> -[わからない]

I don't know it.
Because, I don't have DEMO version.

My test is checking in only 1st stage.
So, If you can play 1st stage then the issue will reproduce probably.

**Comment by nassau-tk** [comment] 2021-01-31 00:27
Bleach SC1 & SC2 background size  is not drawing correctly when enter the menu screen in game.

I can't judge the related of these issue.
So,For reference.

**[ Real PSP Bleach SoulCarnival 2 ]==> blur processing ON & The HP gage of the upper left goes off, and "NowLoading" is drawn by the lower right.**
![Bleach_SC2_Menu_Blur_RealPSP](https://user-images.githubusercontent.com/48179091/91385367-ab38ea00-e86b-11ea-888a-14e52f0cf04d.gif)

**[PPSSPP Bleach SoulCarnival 2 ]==> blur processing OFF(Maybe) & The HP gage of the upper left is expanded while being indicated.**
![Bleach_SC2_Menu_Blur_PPSSPP](https://user-images.githubusercontent.com/48179091/91385647-5b0e5780-e86c-11ea-8850-7e92bdf9c9df.gif)

NOTICE: SC1 happen same work too when enter the menu.

**Comment by unknownbrackets** [comment] 2021-01-31 02:28
The dump shows a 128x128 version of the screen being textured at 0x041d2200, but it's stretched to the full screen.

My suspicion is that we're missing some CPU copy which is actually copying the full screen to 128x128 to blur it (not sure why this would go through the CPU though.)

I don't think that's related to the crash directly, but it could be the effect is related.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-01-31 03:16
> Basically `gstate.getColorMask() != 0xFFFFFFFF` crash while `gstate.getColorMask() != 0` work fine.
> 
> Not sure how the color mask is meant to be used, if is "we write only to that part" I guess we write something as long as is not all 0 indeed, but could be the opposite anyway xD

This is a mask of bits NOT to write.  So if it's 0, it means all bits will be written.  If it's 0xFFFFFF, it means no writing of color (this might mean writing alpha or something else.)  This mask is used whether clearing or not.  If it's even 0xFFFFFE, at least one bit is being written.

The purpose of this check is: we may only be clearing the depthbuffer.  In this case, it's unsafe to memset VRAM or copy to it, because the framebuffer might not even be set properly - it could just be a clear of depth.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-01-31 07:30
Got some information from someone with the game - based on some back and forth debugging.  The game doesn't use CPU copies for that effect, and apparently it crashes soon after you trigger that effect too.

Seems like it's when going into the menu (additionally to loading?), and when you trigger this it does a PAUSE signal.  Right after the pause is a draw that textures wrong and stretches wrong, like it's drawing to the wrong target.  I suspect the safe size of this draw is involved somehow...

-[Unknown]

**Comment by nassau-tk** [comment] 2021-01-31 07:51
@unknownbrackets 

hm...Is it means that "Wrong size background has related with crash"? :sweat_smile:

**Comment by unknownbrackets** [comment] 2021-01-31 07:57
Yeah, I think you were right.  During the PAUSE, it enqueues a new list which copies the screen to a temporary, but smaller (this part makes sense.)  In the frame dump above, this temporary is simply stretched to the screen's normal framebuffer.

But instead right after the paused list unpauses, it textures to self, resulting in a stretched mess (which isn't updated, so you see it in the dump).  It never reasserts the framebuffer when doing this self-texture either.  I think this has to do with saving/restoring the list context...

-[Unknown]

**Comment by nassau-tk** [comment] 2021-01-31 08:23
Oh! I understood! It's good information for me!
I hope beat this issue and v1.11 come speedy. :wink:

**Comment by hrydgard** [comment] 2021-01-31 10:03
#14034 has been merged, which might fix this. Really nice job tracking that one down. 

Please test!

**Comment by nassau-tk** [comment] 2021-01-31 11:20
Good!
Awesome!!

[Enter the menu screen. Good background drawing.]
https://user-images.githubusercontent.com/48179091/106382165-314ff280-6401-11eb-8412-ba9ffc83bc16.mp4

[It's not coming invalid memory access when beat the boss!]
https://user-images.githubusercontent.com/48179091/106382169-3745d380-6401-11eb-8302-70a49e6e66f9.mp4

For Reference GEdump here.
[BLEACH_SC1_Background_Good_UCJS10085.zip](https://github.com/hrydgard/ppsspp/files/5899580/BLEACH_SC1_Background_Good_UCJS10085.zip)
[BLEACH_SC2_Background_Good_UCJS10106.zip](https://github.com/hrydgard/ppsspp/files/5899581/BLEACH_SC2_Background_Good_UCJS10106.zip)

Can I close?!

**Closed** 2021-01-31 11:42 UTC
Labels: GE emulation
