### ISSUE TITLE
God Eater 2 - Its hard to explain, just check it out

### ISSUE THREAD

**Issue by KenGodEaterwiki** [hrydgard/ppsspp#7765] opened 2015-05-24 03:08 UTC
Ive been trying to report this but I was caught up with a lot of stuff
![npjh50832_00025](https://cloud.githubusercontent.com/assets/10692437/7786447/4cc1e9f8-0203-11e5-9973-4ef0234f03f4.jpg)
I think its obvious enough. This "thing" happen in Direct3D9 and Disable Alpha Hack is disabled. I also did test it out with the latest build.
![npjh50832_00020](https://cloud.githubusercontent.com/assets/10692437/7786467/f9fb1e32-0203-11e5-85c5-c311ff95a676.jpg)

This "thing" also happen in Gods Eater Burst (both US and JPN).
![ulus10563_00007](https://cloud.githubusercontent.com/assets/10692437/7786474/c9eb883e-0204-11e5-9a06-4ac766b0e544.jpg)

**Comment by hrydgard** [comment] 2015-05-24 08:56
When you say "thing", I assume you mean that the map is visible outside the the circle at the top right? Only in D3D?

Probably either a stencil or scissor rect issue.. will have to see if I can repro.

**Comment by hrydgard** [comment] 2015-05-24 09:11
Are you playing with "non-buffered" rendering? If so, it's best not to do that and use buffered instead..

**Comment by KenGodEaterwiki** [comment] 2015-05-24 11:35
![npjh50832_00028](https://cloud.githubusercontent.com/assets/10692437/7787694/068d424a-024c-11e5-8544-cd1b48c04ce3.jpg)

**Comment by hrydgard** [comment] 2015-05-24 18:30
Well yes, there's the glow, but that's a completely different bug :)

Seems D3D is not a good choice for this game at the moment...

**Comment by KenGodEaterwiki** [comment] 2015-05-25 05:44
The weird thing is all other games Ive been playing are fine with DX3D9 (Dissidia 012, FF Type-0, Ace Combat JA and X, MHP3rd HD, Lord of Apocalypse, The 3rd Birthday)

**Comment by unknownbrackets** [comment] 2015-05-31 01:29
Okay, so this makes the situation clearer:
http://forums.ppsspp.org/showthread.php?tid=1552&pid=107205#pid107205

I think this is a duplicate of #5562 or whichever one is about the excessive bloom.  It's not reasonable to expect non-buffered rendering to draw things properly, because it disables the game's ability to use buffers.

It's like, if I disabled your laptop's screen (to save battery power), would you then report a bug to your laptop maker saying that you're unable to see graphics?  You can't have it both ways.  The game needs buffers to draw things properly, so when you killshot those buffers, you're pretty much living with the results.

The right solution is to solve the bugs in buffered rendering, imho.

-[Unknown]

**Comment by Krylia** [comment] 2015-06-03 05:36
On orphis build 1.0.0-559-g403f6ab
D3D9 back end, Read framebuffers to memory, simulate block transfer on Prevent FPS from exceeding 60 on (personal hardware [monitor] reasons, may vary), render res is set to auto,  pretty much everything is off except for V-sync, splines, bez curves quality is at low, anisotropic filtering off, lower resolution for effects is set to aggressive. Window size is at 2x. Audio latency is at high. Fast memory option unchecked. Dev logging unchecked. Anything not mentioned is at default settings. Control mapping irrelevant.

So, the bloom has been reduced in GEB, to where you can actually use one of the menus, however an artifact persists at the top of the screen of bloomy-glowy-ness, which is somewhat... odd. It's really weird! Also got this to occur on normal 'mass consumer' PPSSPP build.

![evidencei](https://cloud.githubusercontent.com/assets/12690054/7953262/5591508c-0988-11e5-940e-7da3312f56ab.jpg)
![evidenceii](https://cloud.githubusercontent.com/assets/12690054/7953266/59a3c29a-0988-11e5-9d3c-cb06789a1f7b.jpg)
![evidenceiii](https://cloud.githubusercontent.com/assets/12690054/7953267/5bf8656e-0988-11e5-922d-86855b5ab975.jpg)
![evidenceiv](https://cloud.githubusercontent.com/assets/12690054/7953268/5d704c68-0988-11e5-86d2-693b03f0c431.jpg)
![evidencev](https://cloud.githubusercontent.com/assets/12690054/7953269/5eebd562-0988-11e5-8db9-9273845628c4.jpg)
![evidencevi](https://cloud.githubusercontent.com/assets/12690054/7953271/614ed3cc-0988-11e5-93f5-e8612784fdf2.jpg)
![evidencevii](https://cloud.githubusercontent.com/assets/12690054/7953277/631dd126-0988-11e5-985b-b100020b4f14.jpg)

**Comment by Krylia** [comment] 2015-06-04 04:05
Was able to have BOTH bugs not occur when using OpenGL backend with Read Framebuffers to Memory (GPU) with minimalistic settings. Something else I have noticed is that the game seems to flash between a blurred text then no blur then blurred text then no blur when loading a save, and at various other times as well.

**Comment by hrydgard** [comment] 2015-06-04 13:17
Krylia, yeah, it works fine in GL, we have some bug in framebuffer management with D3D. That blur text thing would be very hard to fix - for some reason the game copies the image to RAM and draws it back out again, and there's no space in PSP RAM for higher-res pictures. Fortunately it's just in the menu so it's not that annoying.

**Comment by KenGodEaterwiki** [comment] 2015-06-04 21:17
Im fine with the overbloom (unless bunch of stuff happen on the screen) but the line that appear on top of the screen is annoying, blocking one third of the screen

**Comment by Krylia** [comment] 2015-06-04 22:14
Ken the line goes away in OpenGL render framebuffer to memory (GPU) and there is no overbloom either, AND NO MINIMAP BUG!

**Comment by KenGodEaterwiki** [comment] 2015-06-05 09:06
Opengl + Buffered Rendering lags too much for my liking especially in fast paced game. Also, Im on PC

**Comment by Krylia** [comment] 2015-06-05 15:42
Hm... what are your PC specs?

**Comment by KenGodEaterwiki** [comment] 2015-06-05 16:45
GFX: AMD/ATI Radeon Mobility HD 7130
PPSSPP res: x2
CPU: AMD E1-1200(@1400 MHZ)
Catalyst beta: Omega driver
RAM: 2.5 GB DDR3 400MHZ
OS: Window 7 Home Premium 32-bit
Setting is lowest

**Comment by Krylia** [comment] 2015-06-06 16:34
I'm gonna be blunt, your GPU and CPU are potatoes, and I don't really know how to help in this scenario anymore, other than have you turned off developer logging, are there any programs running in the background, are you doing anything else while playing, is what you are playing on not running too hot, etc etc etc. 

Basically D3D framebuffer bugs need to be fixed for your game to be more 'enjoyable' and I'm not about to bother hyrdgard about it, because they are doing what they do on their own time. I am sorry if I am being somewhat rude or harsh, hormones can give you some crazy mood swings and you might not even realize that is what is happening at times. Anyway, basically, either wait until the emulator is improved, more bugs are fixed, more optimizations, or get some new hardware. If new computer hardware is out of the question, a nice 'n shiny PSP to play the game on might be within range. Who knows.

**Comment by KenGodEaterwiki** [comment] 2015-06-06 17:17
I dont have anything open and this laptop is 3 years old. Also, PSP is dead

**Comment by MoochMcGee** [comment] 2015-06-06 20:49
@KenGodEaterwiki You can still get one new, doofus.

**Comment by KenGodEaterwiki** [comment] 2015-06-06 22:07
Theres none here dumbass

**Comment by MoochMcGee** [comment] 2015-06-07 00:46
@KenGodEaterwiki Dude, they're available worldwide.You can even get one off ebay, don't give me that crap.

**Comment by KenGodEaterwiki** [comment] 2015-06-07 06:08
You think everyone is freaking rich!? If I was rich, I wouldn't be here. Your brain is ridiculously stupid

**Comment by MoochMcGee** [comment] 2015-06-07 19:06
@KenGodEaterwiki WTF? I'm nowhere near rich, dude. Just save up for it! Besides, I found a PSP 2000 that seems to work for 6 dollars on ebay. They're REALLY not that expensive.

**Comment by Bigpet** [comment] 2015-06-07 19:19
can you guys take your off-topic fights somewhere else?

**Comment by KenGodEaterwiki** [comment] 2015-06-08 03:43
Yeah, talking to a stupid wont work. I forgot about that

**Comment by Krylia** [comment] 2015-06-08 03:52
Btw checking cache entire ISO to ram (if you have enough ram to do so) can really help with choppiness caused by effects

**Comment by unknownbrackets** [comment] 2015-06-08 04:55
I still feel like this is a duplicate and the entire discussion here belongs on forums.ppsspp.org.  The blur text issue is actually the same one probably, off-by-half-a-pixel or w/e, since the game uploads a saved copy of the frame to the screen during save operations.

Also, please attack ideas not people.  Ideas are stupid, people aren't.  Doesn't seem like this is going in a good direction, so I'm closing.

-[Unknown]

**Closed by unknownbrackets** 2015-06-08 04:55 UTC
