### ISSUE TITLE
Resistance: Retribution crashes during gameplay

### ISSUE THREAD

**Issue by murtisoft** [hrydgard/ppsspp#13356] opened 2020-08-29 21:45 UTC
(UCUS98668)Resistance: Retribution crashes during gameplay.
I have tried different renderers, turning off hacks and restarting the mission & restarting from a checkpoint to no avail.

- OS: Windows 7 x64 
- CPU: AMD Phenom x6 1100T
- GPU: Geforce GTX 750Ti
- PPSSPP: 1.10.3

Video:
Character climbs the last step, cutscene starts, he says "Fuck me!" and it crashes.
https://www.youtube.com/watch?v=0W-PG5LXOVM

SaveState if you would like to try for yourself:
https://drive.google.com/file/d/16tf97GfITDVOHpF8RcEQOGAEnSSzIHrd/view?usp=sharing

**Comment by Gamemulatorer** [comment] 2020-08-29 22:35
duplicate of #4626

**Comment by murtisoft** [comment] 2020-08-29 23:02
Really? Sorry about that.
I did check out that thread, I thought it wasnt the same.

**Comment by unknownbrackets** [comment] 2020-08-29 23:22
This issue is being closed as a duplicate of #4626.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-08-29 23:22 UTC
