### ISSUE TITLE
prince of persia rival sword (powervr/adreno black screen in game)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#6399] opened 2014-06-22 20:59 UTC
well,this game working for me since cluth textures branch + opengl 3.0 support merged.

now experience emulator crashes at any place after few min.of gameplay.

I don't know.if is caused for excesive ram usage due cluth textures on this game.

game run a full speed,no graphical gltch noticed.almost perfect.

for example playing other more demanding game like monster hunters 3rd hd and never crash.

iphone 5S ios 7.0.6

-----------------------------------------------------
edite

working on my old android galaxy s3 at turtle speed whitout issue.	ridiculous

**Comment by ppmeis** [comment] 2015-07-26 01:01
As reported on #3723 It works again under my PowerVR device.

**Comment by brujo5** [comment] 2015-07-26 02:17
No, still not fixed for ios.

**Comment by unknownbrackets** [comment] 2016-04-17 02:27
This issue is being closed as a duplicate of #3723.  The memory usage issue turned out to be a jailbreak issue, and that seems to be the only difference.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-04-17 02:27 UTC
