### ISSUE TITLE
[Request] Adding Model ripping support

### ISSUE THREAD

**Issue by Fallenleader** [hrydgard/ppsspp#8857] opened 2016-07-13 22:42 UTC
https://code.google.com/archive/p/psplamb/source/default/source

PSPlamb is a SEPlugin that allows a user to "rip" data that is sent to the display list on a psp. It reads all info about models and saves them as a .obj model file.

The source code is linked above, and implementing this shouldn't be too difficult (I would myself, but I am barely fluent in C# as is without picking up another language)

Theoretically, one could take this source and patch it in with PPSSPP to provide such a feature without hours of PITA research.

**Comment by unknownbrackets** [comment] 2016-07-15 05:53
This issue is being closed as a duplicate of #2825.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-07-15 05:53 UTC

**Comment by Fallenleader** [comment] 2016-07-17 00:33
My apologies, Forgot this was already opened and I don't remember commenting on it even though it seems I did. Wasn't meaning to cause issues.
Sincerely,
Fallenleader
