### ISSUE TITLE
Tokimeki Memorial 4 graphic issue.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6379] opened 2014-06-20 10:29 UTC
Look at the arms.

buffered rendering
![01](https://cloud.githubusercontent.com/assets/3481559/3339086/b19a2cc6-f865-11e3-8b9a-259fb1c897c4.png)

read framebuffers to memory fixes the problem,but have other problem.
![02](https://cloud.githubusercontent.com/assets/3481559/3339087/b6067206-f865-11e3-86d6-28988ef2c8e4.png)

log

```
GLES\Framebuffer.cpp:973 Creating FBO for 0015e000 : 256 x 272 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 0015e000/00110000 and 00000000/00110000
GLES\ShaderManager.cpp:139 Linked shader: vs 27 fs 34
GLES\ShaderManager.cpp:139 Linked shader: vs 36 fs 37
GLES\ShaderManager.cpp:139 Linked shader: vs 39 fs 37
GLES\Framebuffer.cpp:973 Creating FBO for 001a2000 : 256 x 240 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 001a2000/00110000 and 00000000/00110000
GLES\ShaderManager.cpp:139 Linked shader: vs 22 fs 37
GLES\Framebuffer.cpp:973 Creating FBO for 001de000 : 128 x 136 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 001de000/00110000 and 00000000/00110000
GLES\ShaderManager.cpp:139 Linked shader: vs 27 fs 42
GLES\Framebuffer.cpp:973 Creating FBO for 001f6000 : 32 x 34 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 001f6000/00110000 and 00000000/00110000
GLES\Framebuffer.cpp:973 Creating FBO for 001f0000 : 64 x 68 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 001f0000/00110000 and 00000000/00110000
GLES\ShaderManager.cpp:139 Linked shader: vs 27 fs 44
GLES\ShaderManager.cpp:139 Linked shader: vs 22 fs 46
GLES\Framebuffer.cpp:973 Creating FBO for 00154000 : 64 x 32 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 00154000/00110000 and 00000000/00110000
GLES\Framebuffer.cpp:973 Creating FBO for 00156000 : 128 x 64 x 3
GLES\Framebuffer.cpp:1016 FBO reusing depthbuffer, 00156000/00110000 and 00000000/00110000
```

Gedebugger
draw upper part of the girl
![03](https://cloud.githubusercontent.com/assets/3481559/3339213/099d2bf6-f868-11e3-854c-60ad51467a85.png)

draw lower part
![04](https://cloud.githubusercontent.com/assets/3481559/3339214/099db5b2-f868-11e3-9ad5-aa2bf3096a12.png)

then
![05](https://cloud.githubusercontent.com/assets/3481559/3339215/09a08382-f868-11e3-9a15-f0464d21cd81.png)

next step
![06](https://cloud.githubusercontent.com/assets/3481559/3339216/09a09912-f868-11e3-88de-1604789b03ea.png)

**Comment by unknownbrackets** [comment] 2015-01-07 05:01
Does #7289 fix this or are the arms still broken, just black box resolved?

-[Unknown]

**Comment by daniel229** [comment] 2015-01-07 05:14
Arms still broken

**Comment by rysss** [comment] 2015-01-07 05:19
same. tested for windows x64

**Comment by rysss** [comment] 2015-01-07 05:20
screenshot showing black bar on top arms

**Comment by daniel229** [comment] 2015-01-15 09:53
read framebuffered to memory seems draw the arm correct

![01](https://cloud.githubusercontent.com/assets/3481559/5755437/6ed34d86-9cdf-11e4-9916-1455f9018bfb.png)

read framebuffered to memory
![02](https://cloud.githubusercontent.com/assets/3481559/5755438/6ed40c62-9cdf-11e4-9116-1a94c00dda4c.png)

**Comment by daniel229** [comment] 2015-01-15 10:14
Shadow of Memories has the same problem.
![01](https://cloud.githubusercontent.com/assets/3481559/5755675/63d2d084-9ce2-11e4-8026-11da695390bc.png)
![02](https://cloud.githubusercontent.com/assets/3481559/5755676/63d4143a-9ce2-11e4-86b1-e39cd4f5f625.png)
![03](https://cloud.githubusercontent.com/assets/3481559/5755677/63d4daa0-9ce2-11e4-87a5-34274f0888a4.png)

**Comment by unknownbrackets** [comment] 2015-03-01 05:02
I think the issue in this game is basically that the game renders to two buffers that are each 256x256, and which are right next to each other.

Because it rendered, we use it as a render-to-texture, but we only have the top half of the texture, not the lower half.  We'd need to splice the two framebuffers together, or texture from both of them depending on the v coordinate.  Or be really smart and break it into two drawcalls.

Another option might be downloading both framebuffers to memory (in order to splice them.)  Since we know that the height is > 256, we can be reasonably sure about the height of the first one, but the second one is unsafe and could corrupt important memory.

I've thought before about trying to do all rendering to one big framebuffer that we try to creatively map to correct coordinates, or else use image load/store or something, but all of these are complicated or require GPU features that the devices we support don't have.

-[Unknown]

**Comment by daniel229** [comment] 2015-11-03 03:50
A little change,the lower part is cut out since https://github.com/hrydgard/ppsspp/pull/8130
![01](https://cloud.githubusercontent.com/assets/3481559/10900920/fda8c096-8220-11e5-8986-eaa3f4c8f125.png)

**Comment by unknownbrackets** [comment] 2015-11-03 04:20
I guess that means it's no longer at the edge on that side, so it's not repeating, or something.

It's annoying it even bothers to draw it in two separate render targets.

@hrydgard what do you think?  This actually happens - per my memory - in at least one or two other games.  In one of them, it's horizontally, because the game renders at a higher resolution (in two parts) and then scales it down.

To detect it, we'd have to see a framebuffer `vfb->height` away from the first framebuffer.  I'm not sure if there's any benefit in allowing n framebuffers where n > 2.  We could also cap this by maxSeenV, e.g. if the UV coords don't need to go outside the first framebuffer, just do what we do now.

Then we could just create a temp FBO, and blit the first framebuffer to the top, and blit the second to the bottom.  We'd have to do this every frame but it would probably not be too expensive.

This wouldn't lose any visual quality, but at > 1x render res, there might probably be a line between the two textures in some cases.

I think that'd be fine, does it sound like a good approach?

-[Unknown]

**Comment by daniel229** [comment] 2015-11-04 23:25
go back to the usual look since https://github.com/hrydgard/ppsspp/pull/8168

**Comment by benderscruffy01** [comment] 2019-04-02 12:18
v1.8.0-88-g24cfad87d
still happens
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3033829/DUMP.ZIP)

**Comment by unknownbrackets** [comment] 2019-04-07 20:37
Thanks, for the dump.  Dump 1 luckily reproduces the issue perfectly.

The correct output (from a PSP):
![NPJH50127_#6379_tokimeki_memorial_4_arms](https://user-images.githubusercontent.com/191233/55689245-16141900-5937-11e9-96a8-c855cf6737b9.png)

And it seems software rendering doesn't have this bug (but it's not perfect, the shadow is wrong near top left shoulder):
![NPJH50127_#6379_tokimeki_memorial_4_arms-softgpu](https://user-images.githubusercontent.com/191233/55689251-275d2580-5937-11e9-88fa-57b10041fa98.png)

GLES indeed shows this bug as in the initial report (and also seems to get the shadow wrong):
![NPJH50127_#6379_tokimeki_memorial_4_arms-gles](https://user-images.githubusercontent.com/191233/55689265-4b206b80-5937-11e9-942a-a41348f17d88.png)

In this case, it's texturing from Texture L0: 0x0415e000 (256x512), which is render-to-texture.  But it was rendered/detected as only a 256x272 texture.  We separately handle a draw into 041a2000, but this is actually supposed to be an offset into the original texture.

One way to handle this might be to detect the texture from two framebuffers, and resize the framebuffer larger.  It would mean the first frame would end up cut off, but future frames (if the offset draw was properly detected) could draw into the same framebuffer and then work.

-[Unknown]

**Comment by benderscruffy** [comment] 2022-09-05 09:53
still an issue 
here is a renderdoc of it
[Tokimeki Memorial 4.zip](https://github.com/hrydgard/ppsspp/files/9488770/Tokimeki.Memorial.4.zip)

**Comment by unknownbrackets** [comment] 2022-09-05 14:54
Yeah we either need to detect this scenario or stitch the framebuffers together.

-[Unknown]

**Comment by IrfanH495** [comment] 2022-10-28 21:11
My Samsung m20 and Sharp sh04H, also had the same issue
Vulkan & OpenGL
![Screenshot_20221029-033711_PPSSPP](https://user-images.githubusercontent.com/78854859/198733118-85a93626-3470-416b-b6b3-ad76095374e2.jpg)

**Comment by IrfanH495** [comment] 2022-11-09 16:53
vulkan ppsspp v1.13.2-1892-g65d2f9474
when I play the new game the font display looks like this
![Screenshot_20221109-234700_PPSSPP](https://user-images.githubusercontent.com/78854859/200891302-b12f536c-4559-4d60-b7f6-0be6343a1a2a.jpg)
![Screenshot_20221109-234302_PPSSPP](https://user-images.githubusercontent.com/78854859/200891443-21b84db6-b67e-47b6-940a-1f91b85b7b36.jpg)

**Comment by IrfanH495** [comment] 2023-06-03 13:00
v1.15.4-121-g27b8d27ef-android
still happens OpenGL & Vulkan.

**Comment by unknownbrackets** [comment] 2023-06-04 05:28
A GE frame dump of the font display issue would be helpful.

-[Unknown]

**Comment by IrfanH495** [comment] 2023-06-04 11:17
> A GE frame dump of the font display issue would be helpful.
> 
> -[Unknown]

sorry for the font issue like my comment has been fixed in a later version, at that time other games also experienced it.  I forgot to report it sorry 🙏🙏🙏🙏🙏.

**Comment by hrydgard** [comment] 2023-08-28 12:58
Just for the record, `[AllowLargeFBTextureOffsets]` which fixed a similar framebuffer stitching issue in Juiced doesn't help here.

**Comment by hrydgard** [comment] 2023-12-30 21:34
Nearing the 10-year-anniversary of the issue, I have a fix by expanding the framebuffer and applying a vertical offset, seems to work. Based on the old method for Juiced 2. Will gate behind a compat flag for safety.

**Comment by hrydgard** [comment] 2023-12-30 22:32
Please test new builds with that commit, and re-open if there are still issues.

**Closed** 2023-12-30 22:31 UTC
Labels: GE emulation
