### ISSUE TITLE
Me and My Katamari Visual Bug Background

### ISSUE THREAD

**Issue by haazeGalaxys5US** [hrydgard/ppsspp#6411] opened 2014-06-24 06:10 UTC
Hey guys, so tbis issue has been around since ive been trying the past year. I posted the issue in the forums but maybe this is a better spot to be seen. Im running 9.8 1385 and the problem remains in buffered and unbuffered rendering
![screenshot](http://i.imgur.com/5WcFGcOh.jpg)

Only happens when you are larger when the camera is in tight the glitch does not remain even off in the distance

Im having difficulty getting a log. Logcat apl dods not record anything when i leave and run ppsspp and come back to it. I do not have a computer at the moment either. I am rooted though.

**Comment by unknownbrackets** [comment] 2016-05-21 05:37
@LunaMoo your EU save works fine in the US version.  What's the easiest way for a Katamari n00b to experience this issue?  I tried the first couple levels but neither was outside, which I'm guessing is the reason this wasn't evident.

I have some code to probably implement depth download on desktop, although detecting the "right" depth is tricky.  I'd also like to try hardcoding depth=0 on texture and see how it looks (which is what mobile may be locked to.)

Would possibly use zero depth when "block transfer" is disabled OR "disable slow effects" is enabled.  Though I'm not sure how slow it will be, I don't expect downloading depth to RAM to be a thing GPUs like.

-[Unknown]

**Comment by LunaMoo** [comment] 2016-05-21 06:02
Well I think it only happens in stages where you grow to certain scale, for example you start in the house, when you katamari grows enough you move to the town and it would have the bug already, some stages already starts at higher levels, so for example talk to this cicada
![ules00339_00018](https://cloud.githubusercontent.com/assets/5485237/15446713/9aa75aec-1f29-11e6-9626-a6f31277f291.jpg)
 pick "yes" and then "eternal" which removes time limit and you'll start in a stage which has this issue from the start. Might even be exact stage from first screenshot here.

**Comment by unknownbrackets** [comment] 2016-05-21 06:54
Okay, confirmed (not shocking) that downloading makes it work.

One trick with zero: it's actually (of course) using a CLUT16 here.  CLUT=0 is 100%, so reading the texture data as zero would cause the artifacting.  We'd want to set the texture as zero instead.

Also, we can't just download at the end of the frame (a la "read framebuffers to memory"), because it will read zero.  The game uses the depth, and then right after texturing from it, clears the depth.

It seems mostly doable to detect depth.  One thing I think I've seen before that WILL get in the way: turning off depth write and using the depth space as a temporary color buffer / or texture memory.  I think it will be enough to prioritize color buffers, hopefully...

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-09-19 03:41
By the way, making depth clears write to memory (as in #8994 with color) makes it solid red. as mentioned here (because it clears to zero, I guess.)  I wonder if it'd help artifacts in any other game, though...

-[Unknown]

**Comment by soundyogi** [comment] 2017-07-01 23:45
Hi!

I think I am having this Issue, is it fixed? How could one help maybe :)

Thanks!

**Comment by hrydgard** [comment] 2018-03-08 09:22
Yeah, the game still has serious problems. There are at least two issues. First, it uses the depth buffer as a texture looking up into a palette to do custom fog. PPSSPP does not support that currently, I have a rough implementation in a branch but there were some problems I couldn't explain at the time, should probably give it another shot. Secondly, for window transparency in a few stages it does something similar but textures from a texture map that's black while it really shouldn't be. I dove deep into it a while ago but failed to figure it out...

**Comment by 8v3c** [comment] 2019-08-24 16:31
has anyone found a fix for this?

**Comment by Panderner** [comment] 2020-03-12 09:13
![Screenshot_2020-03-12-14-48-11-69_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/76505577-b0a0a480-6484-11ea-8504-2dc670444eaf.png)
Here:
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4323276/recording.ppdmp.zip)

**Comment by Panderner** [comment] 2020-04-20 14:42
Same happens in latest build, they removed framebuffer to memory in version 1.6.0

**Comment by LunaMoo** [comment] 2020-04-20 16:24
Read framebuffers to memory was only passing a long fixed hang, did nothing to this glitch if not making it worse.

The glitchy effect from here can be removed by my cwcheat workaround ~ https://github.com/LunaMoo/PPSSPP_workarounds

**Comment by Panderner** [comment] 2020-04-21 05:51
But how the glitchy effects to drawn? It's doesn't present on a real PSP.

**Comment by unknownbrackets** [comment] 2020-04-21 06:41
It's downloading the depth buffer and using that as a texture.  This is entirely separate from what that setting did, which was related to color buffers and is now essentially automatic.

I haven't seen it mentioned here, but software rendering (which will be pretty slow) should render this correctly.

-[Unknown]

**Comment by Panderner** [comment] 2020-04-21 08:13
This how it's looks in software renderer:
![Screenshot_2020-04-21-16-12-24-35_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/79842126-0143df80-83eb-11ea-9773-313f983de969.png)

**Comment by righthere** [comment] 2020-04-21 09:54
> Read framebuffers to memory was only passing a long fixed hang, did nothing to this glitch if not making it worse.
> 
> The glitchy effect from here can be removed by my cwcheat workaround ~ https://github.com/LunaMoo/PPSSPP_workarounds

Thank you :-) I finally have been able to play the game fully with double stick config (remapping to second gamepad stick the cross,square,triagle,circle buttons) and in hd, thanks again!

**Comment by bassilisk202** [comment] 2020-04-29 23:00
Hello! 

> 
> 
> Read framebuffers to memory was only passing a long fixed hang, did nothing to this glitch if not making it worse.
> 
> The glitchy effect from here can be removed by my cwcheat workaround ~ https://github.com/LunaMoo/PPSSPP_workarounds

Hello! Downloaded your workaround and followed the instructions and it still showing the glitch. Im currently using PPSSPP v1.9.3


![katamari](https://user-images.githubusercontent.com/64562561/80654969-22be5e80-8ab0-11ea-81f3-bde9ed186b40.png)

**Comment by LunaMoo** [comment] 2020-04-30 00:15
Did you imported the cheat then enabled it in the cheat menu like that:
![Katamari cheat](https://user-images.githubusercontent.com/5485237/80659095-3c4bb000-8a88-11ea-8a7d-bd51706aaaa1.jpg)
? Make note [Disable] cheat exists to disable the actual hack(for example to check if it's still needed), so don't use it.

**Comment by bassilisk202** [comment] 2020-04-30 01:56
> 
> 
> Did you imported the cheat then enabled it in the cheat menu like that:
> ![Katamari cheat](https://user-images.githubusercontent.com/5485237/80659095-3c4bb000-8a88-11ea-8a7d-bd51706aaaa1.jpg)
> ? Make note [Disable] cheat exists to disable the actual hack(for example to check if it's still needed), so don't use it.
> 
> Here's a diff without/with the workaround activated:
> 
> ![ULUS10094_00000](https://user-images.githubusercontent.com/5485237/80659484-62be1b00-8a89-11ea-90d3-fd307f5d528e.jpg)
> 
> ![ULUS10094_00001](https://user-images.githubusercontent.com/5485237/80659489-6782cf00-8a89-11ea-8064-ea08bfdc9150.jpg)
> 
> It completely removes the foggy effect, but it was subtle enough on real PSP that it doesn't really make the game look different

Ok got. It so happens that the disable cheat option was checked and i ddint noticed, my bad. Thanks for the workaround! Really appreciate it :)

**Comment by Instandhaltung** [comment] 2020-05-16 02:40
> Did you imported the cheat then enabled it in the cheat menu like that:
> ![Katamari cheat](https://user-images.githubusercontent.com/5485237/80659095-3c4bb000-8a88-11ea-8a7d-bd51706aaaa1.jpg)
> ? Make note [Disable] cheat exists to disable the actual hack(for example to check if it's still needed), so don't use it.
> 
> Here's a diff without/with the workaround activated:
> 
> ![ULUS10094_00000](https://user-images.githubusercontent.com/5485237/80659484-62be1b00-8a89-11ea-90d3-fd307f5d528e.jpg)
> 
> ![ULUS10094_00001](https://user-images.githubusercontent.com/5485237/80659489-6782cf00-8a89-11ea-8064-ea08bfdc9150.jpg)
> 
> It completely removes the foggy effect, but it was subtle enough on real PSP that it doesn't really make the game look different

Hey! For me, the cheat does crash the emulator on ppsspp (newest 1.9.3 build) **on Switch.** The cheats for Valkyria Chronicles do crash as well, so maybe I might do something wrong. Are there any settings that have to be enabled or disabled for this to work?

**Comment by LunaMoo** [comment] 2020-05-16 06:58
I have no idea about switch, sorry, but the port to that platform seems to still be WIP and unfinished. Maybe cheats just doesn't work there, or something's wrong with jit invalidation as cheats which modify the game code requires it.

**Comment by Instandhaltung** [comment] 2020-05-16 13:33
> I have no idea about switch, sorry, but the port to that platform seems to still be WIP and unfinished. Maybe cheats just doesn't work there, or something's wrong with jit invalidation as cheats which modify the game code requires it.

Thanks for the answer!

**Comment by hrydgard** [comment] 2020-08-09 08:52
I've got a Vulkan-only fix for this in #13262. Will extend it to the other backends except probably D3D9 (and older OpenGL devices) later.

**Comment by hrydgard** [comment] 2020-08-31 09:18
Woops, that got broken again in #13355 .  Will fix again soon.

**Comment by Panderner** [comment] 2020-10-19 01:19
The last one is OpenGL ES 3.0+. but why it's not fixable on GLES2 Devices?

**Comment by Panderner** [comment] 2021-07-10 14:42
After #14042 Here's a comparison for my PC and my android phone:

Windows PC:
![Ppsspp Screenshot 2021 07 10 - 22 35 33 14](https://user-images.githubusercontent.com/37503397/125166813-f03de480-e1cf-11eb-9e9b-96eeff4b1f83.png)

Android Phone:
![Screenshot_2021-07-10-22-35-25-091_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/125166815-f92eb600-e1cf-11eb-8f8c-63b7394450b4.jpg)

All versions tested are using latest build.

**Comment by hrydgard** [comment] 2021-07-10 14:48
Yeah, that fix isn't working for OpenGL on Android, that's known unfortunately :(

**Comment by DerGefallene** [comment] 2022-09-13 03:01
I'm still experiencing this on the latest PPSSPP version and the EU Version of Me & My Katamari. I tried switching to Vulkan but this still occurs and since the cheat file only seems to work on the US and JP version is there anything I can do?

**Comment by Panderner** [comment] 2022-09-13 03:54
@DerGefallene what device are you using?

**Comment by DerGefallene** [comment] 2022-09-13 04:03
Just my Windows PC

**Comment by Panderner** [comment] 2022-09-13 05:49
> Just my Windows PC

@DerGefallene PC specs?

**Comment by hrydgard** [comment] 2022-09-13 07:45
That's extremely weird, this should work on any Vulkan device. What GPU do you have? And are you really running a fresh-enough PPSSPP version?

**Comment by DerGefallene** [comment] 2022-09-13 11:44
> > Just my Windows PC
> 
> @DerGefallene PC specs?

Windows 10 21H2
AMD Ryzen 5 3600
Nvidia GeForce RTX 2070 Super 
32GB 3200 Mhz RAM



> That's extremely weird, this should work on any Vulkan device. What GPU do you have? And are you really running a fresh-enough PPSSPP version?

My PPSSPP version is always updating itself so I figured it would be the latest version. I have been using it for some years tho so maybe I should've tried to manually update it. At first I had been using D3D11 and the above visual bug occured and when I switched to Vulkan the slightly transparent texture becomes completely solid so after reaching a certain height I can basically only see a colored texture around my Katamari and nothing else

**Comment by Panderner** [comment] 2022-09-13 11:46
Are you using latest build?

**Comment by DerGefallene** [comment] 2022-09-13 12:29
> Are you using latest build?

That was the issue. Like I said I always thought since PPSSPP was constantly updating itself that it would be up to date. Turns out my PPSSPP version was 1.10.3. Now I've downloaded 1.13.2 and there it is fixed. I tried copying my 1.10.3 PPSSPP savestate of a game level where the bug occured and it also occurs there. But if I load up the game normally on 1.13.2 then the bug doesn't occur.
So good to know that manually updating your emulators from time to time is necessary as well haha

**Comment by hrydgard** [comment] 2022-09-13 12:41
It's not actually updating itself at all :)

Closing.

**Closed by hrydgard** 2022-09-13 12:41 UTC
Labels: OpenGL, GE emulation

**Comment by Gamemulatorer** [comment] 2022-09-13 12:48
This should be added to v1.4.0 milestones.

OpenGL

***v1.13.2***
![Screenshot_2022-09-13-20-47-18-85](https://user-images.githubusercontent.com/37603562/189904996-d0188157-7195-4a2b-a2fd-eae8b6d8ce41.png)

***1.13.944***
![Screenshot_2022-09-13-20-47-32-13](https://user-images.githubusercontent.com/37603562/189905136-cb78e836-a976-4459-b842-fd54ea705f33.png)

**Comment by hrydgard** [comment] 2022-09-13 12:56
Well, the main fix was long ago, I just extended it to work with OpenGL ES, I think...
