### ISSUE TITLE
Bad memory access detected

### ISSUE THREAD

**Issue by hpuente85** [hrydgard/ppsspp#16392] opened 2022-11-15 20:21 UTC
### Game or games this happens in

UCES01184 Resistance Retribution

### What area of the game / PPSSPP

Almost finishing the game, in a cutscene performed by the engine, a VTOL takes off, the scene ends and then seems it cannot go to the next screen.

Tried with Vulkan, OpenGL and Direct3D, also with integrated and dedicated graphics card and setting as true "ignored bad memory accesses"

Also I tried to change the emulador language, because I saw a very similar ticket with same solution.

Hint: The memory is failing (0f5cf2f0) is always the same, very weird ..

Thanks in advance!

### What should happen

It should continue

### Logs

14:24:366 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 949e4e08 (000001973E424E08)
14:24:366 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: 949e4e0c (000001973E424E0C)
14:24:367 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: a93c9c08 (0000019752E09C08)
14:24:368 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: a93c9c0c (0000019752E09C0C)
14:24:368 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: b2793808 (000001975C1D3808)
14:24:369 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: b279380c (000001975C1D380C)
14:24:369 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: c4f27008 (000001976E967008)
14:24:369 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: c4f2700c (000001976E96700C)
14:24:370 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: c9e4e008 (000001977388E008)
14:24:370 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: c9e4e00c (000001977388E00C)
14:24:371 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: d3c9c008 (000001977D6DC008)
14:24:372 user_main    E[MEMMAP]: Core\MemFault.cpp:207 Bad memory access detected and ignored: d3c9c00c (000001977D6DC00C)
14:24:390 user_main    E[G3D]: GPU\GPUCommon.cpp:723 80000104=sceGeListEnQueue(08dd40e8, 00000000, -1, 09ffd4a0[00000010]): invalid stack depth 1599031119
14:24:459 user_main    E[MEMMAP]: Core\MemFault.cpp:219 Bad memory access detected! 0f5cf2f0 (00000196B900F2F0) Stopping emulation. Info:
08bfb894_z_un_08bfb894
movss [rbx+rdi+0x50], xmm6

### Platform

Windows

### Mobile phone model or graphics card

Nvidia geforce 920MX (also tried with integrated graphics)

### PPSSPP version affected

v1.13.2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-11-15 20:45
This issue is being closed as a duplicate of #4626.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-11-15 20:45 UTC
