### ISSUE TITLE
Mobile input: Any plans for touch gestures? 

### ISSUE THREAD

**Issue by pralima87** [hrydgard/ppsspp#12166] opened 2019-07-09 15:42 UTC
Hi is there any chance the devs could consider adding touch gestures as optional inputs?

Gestures could be swipe commands (left, right, up, down)
or maybe a invisible analog on the center of the screen.

This would greatly improve the mobile input as in too much buttons on the screen gets really clunky.

**Comment by unknownbrackets** [comment] 2019-07-14 19:44
This issue is being closed as a duplicate of #6750.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-07-14 19:44 UTC
