### ISSUE TITLE
[Android]Removing the navigation bar offsets the on-screen buttons

### ISSUE THREAD

**Issue by WeirdBob** [hrydgard/ppsspp#10518] opened 2018-01-09 11:58 UTC
What happens?
When the navigation bar is removed (circle icon), the screen is scaled accordingly and the buttons move to the right but the touch input zones are not updates so I have to click on the left of the buttons

What *should* happen?
The touch input zones position should be recomputed when the screen size changes

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Tested on a OnePlus 5T, default launcher, Android Nougat, PPSSPP 1.5.4.

**Comment by unknownbrackets** [comment] 2018-01-10 08:27
This sounds like the issue noted in #9758.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-05-14 12:05
This issue is being closed as a duplicate of #9758.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-05-14 12:05 UTC
Labels: Platform-specific (Android)
