### ISSUE TITLE
Test drive unlimited extreme low fps

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10140] opened 2017-11-15 08:42 UTC
Test drive unlimited have very low fps in menu where aren't effects. I don't know if Is it normal. https://photos.app.goo.gl/ngCOiGLgZJss7TSj1

**Comment by marosis** [comment] 2017-11-15 08:45
https://photos.app.goo.gl/EkyNFNvZUbLFSphM2

**Comment by LunaMoo** [comment] 2017-11-15 08:48
Closing as a duplicate of #7347
This game is using very slow effect after it renders graphics, both me and Kabuto_Kun made different cwcheat patches to disable that effect, you can find them in the forums.

**Closed by LunaMoo** 2017-11-15 08:48 UTC
