### ISSUE TITLE
Persona 3 Portable Blank Screen

### ISSUE THREAD

**Issue by Xieyen** [hrydgard/ppsspp#5069] opened 2014-01-10 17:49 UTC
I'm going through my first play through in P3P and so far it was great until I get to 11/9 where Ryoji first appears. The screen is just blank here but the sound and everything else is working. I'm not sure what the problem is and I don't really know how to fix this. Help please? Thank you.

I'm using V 0.9.6

Windows 7
Processor: AMD Phenom™ II X4 955 Processor 3.20 GHz
RAM: 4 GB
System type: 63 bit OS

**Comment by unknownbrackets** [comment] 2015-02-23 07:06
If it happens even on a PSP, then it does sound like something was done to corrupt the savedata.

Without any feedback or information, it's hard to tell.  I know some people have said this game is fully playable, though a few people have reported crashes.  It may be that the crashes are all cheat related, but we're not getting feedback after we ask if cheats have been used.

I'm going to close this.  If you have more information, or a way to reproduce this that definitely doesn't involve cheats, please comment so we can reopen.

-[Unknown]

**Closed by unknownbrackets** 2015-02-23 07:06 UTC
Labels: No Feedback

**Comment by LoungeKatt** [comment] 2015-02-28 22:56
At the time I played it, there was no cheat file used and nothing special to cause it. I haven't played this one since shortly after my last comment in Jan. 2014, but I remember there not being any crash. That's all the info I have and far from a reason to justify reopening it.
