### ISSUE TITLE
[Mac OS] Parappa The Rapper "Try again?" effect doesn't render properly when using fast forward

### ISSUE THREAD

**Issue by mygizli04** [hrydgard/ppsspp#11729] opened 2019-01-12 18:09 UTC
### What happens?
https://youtu.be/cf0QmsKcNuE and https://youtu.be/NNM890ZOews (realized i forgot to record interpeter)
3 different cores have 3 different glitches : 
When using IR Interpeter the dark effect doesn't occour ( only the GUI pops up )
When using JIT it only shows the frame i started fast forwarding
When using Interpeter it flashes ( sometimes it flashes between the frame i started fast forwarding, in the video it flashes between black and the correct one ) (It flashes faster then shown in the video, i wonder why the QuickTime Recorder didn't get all of the frames, i guess it's compression or something )

### What *should* happen?
As shown in the ending of the first video, it should be darker and show the frame the GUI popped up ( not the frame that i started fast forwarding )

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
MacOS 10.14.2 , MacBook Air 2017

**Comment by unknownbrackets** [comment] 2019-01-12 20:04
I'm not sure why CPU cores would change anything - it may be the timing of CORE_NEXTFRAME or just random chance that seems to be a consistent difference in early tests.

This is probably a duplicate of #10519.  On everything but Windows, we frameskip when you unthrottle, which causes things to not be drawn.  This breaks effects when a game doesn't draw absolutely everything from scratch each frame (most games redraw nearly everything each frame, which is why it mostly works fine.)

-[Unknown]

**Comment by Turxy10** [comment] 2019-01-12 22:13
turxy

**Comment by mygizli04** [comment] 2019-01-12 22:14
What?

**Comment by hrydgard** [comment] 2019-01-14 11:35
Closing as dupe of #10519 . Parappa relies a lot on leaving stuff around from previous frames, which indeed isn't compatible with the frameskipping type of fast-forwarding.

**Closed by hrydgard** 2019-01-14 11:35 UTC
