### ISSUE TITLE
Missing custom textures

### ISSUE THREAD

**Issue by BonnySins** [hrydgard/ppsspp#14499] opened 2021-06-03 11:44 UTC
While i try to charge and HD texture pack for MGS peace walker 

https://github.com/AkiraJkr/Metal-Gear-Solid-Peace-Walker-HD-Textures/ 

There are a lot of texture missing and even the sky is glitched

![Screenshot_2021-06-03-10-42-24-687_org ppsspp ppsspp](https://user-images.githubusercontent.com/80979567/120626304-d25bc200-c462-11eb-8dff-919981f553b3.jpg)

As shown in the screenshot, a lot of texture are missing, sky is half light and half dark, and on the trees there are some kind of glitched colors

In using a Xiaomi Redmi Note 9S 4gb RAM 
Snapdragon 720G - Adreno 618

I'm using PPSSPP 1.11.3-432

Metal Gear Solid Peace walker EUR 
ULES01372

Graphics backend used : OpenGL

**Comment by LunaMoo** [comment] 2021-06-03 13:18
Closing as a duplicate of #14485

**Closed by LunaMoo** 2021-06-03 13:18 UTC
Labels: GE emulation
