### ISSUE TITLE
Yugi Oh!! Arc V Tag Force Special Graphic Issue

### ISSUE THREAD

**Issue by ekkysw** [hrydgard/ppsspp#8620] opened 2016-03-01 22:57 UTC
I use english patched version and everything work for me on my android Asus Zenfone 4 although when standby phase enemy turn ,speed sometimes drop .....and i have some graphic issue in this game when a monster card special summoned and their card appear, the top card is cut off,, has anyone else have experience same on me? ......
ASUS Zenfone 4
GPU PowerVR SGX 544MP2

**Comment by Amaestris** [comment] 2016-03-04 12:33
It's probably due to the powerVR speedup option in the hacks settings. Try to play with defaults settings  and tweak it one option by one to found what its making the glitch but I'm pretty sure that's the power vr speed-up option , i'll try with my phone.

**Comment by ekkysw** [comment] 2016-03-05 15:38
No, i dont use speedup powerVR option and i use default option

**Comment by unknownbrackets** [comment] 2016-03-05 22:21
Closing as a duplicate of #7124.

-[Unknown]

**Closed by unknownbrackets** 2016-03-05 22:21 UTC
