### ISSUE TITLE
Dahaka black screen problem

### ISSUE THREAD

**Issue by ROMANRING** [hrydgard/ppsspp#10517] opened 2018-01-09 06:46 UTC
What happens?
I meet dahaka first time than screen is black plz give me solution 

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by ROMANRING** [comment] 2018-01-09 06:48
I have redmi 4 and ppsspp blue

**Comment by unknownbrackets** [comment] 2018-01-09 07:06
This issue is being closed as a duplicate of #9849.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-01-09 07:06 UTC

**Comment by ROMANRING** [comment] 2018-01-09 07:09
Plz give setting for this
