### ISSUE TITLE
Qix++ Doesn't work

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#10874] opened 2018-04-05 14:25 UTC
The game crashes when starting the game after play again the save file has corrupted and displays there's is no data. The menu text is imperfect

**Comment by Panderner** [comment] 2018-04-05 14:27
Original Qix works fine

**Comment by Panderner** [comment] 2018-04-05 14:29
![screenshot_2018-04-05-22-26-28](https://user-images.githubusercontent.com/37503397/38372112-a70ce168-3920-11e8-9e67-e5a78d53ab92.png)
![screenshot_2018-04-05-22-28-53](https://user-images.githubusercontent.com/37503397/38372157-c45effbc-3920-11e8-8442-fd694728dd96.png)
![screenshot_2018-04-05-22-29-03](https://user-images.githubusercontent.com/37503397/38372169-c8033e1c-3920-11e8-9ad3-3c8ad4e831ba.png)

**Comment by unknownbrackets** [comment] 2018-04-06 06:15
This issue is being closed as a duplicate of #8214.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-04-06 06:15 UTC
