### ISSUE TITLE
Invizimals Crashes when I Open the camera

### ISSUE THREAD

**Issue by Kochlor** [hrydgard/ppsspp#12997] opened 2020-06-03 15:18 UTC
To keep it short: I open the Game and once I open the camera it starts flashing "ppsspp camera :)" in my face before crashing.

**Comment by Panderner** [comment] 2020-06-03 15:20
Did you set the PPSSPP camera permissions turned on?

**Comment by Kochlor** [comment] 2020-06-03 15:21
Yes. I tried pretty much everything I know of and it still crashes. Every other game runs fine.

**Comment by HiImBrala** [comment] 2020-06-04 05:31
That also happens to me on Redmi 6,given camera permission

**Comment by Florin9doi** [comment] 2020-06-04 16:26
Please try the latest version from https://buildbot.orphis.net/ppsspp/index.php

If it is still reproduce try to get an adb log
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

**Comment by Florin9doi** [comment] 2020-12-05 09:08
No feedback for 6 months. Probably resolved by https://github.com/hrydgard/ppsspp/commit/ef250e30d7b1682414b0051f0b23f34287a75051. 
@hrydgard, I propose this for closure

**Comment by unknownbrackets** [comment] 2020-12-27 01:56
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2020-12-27 01:56 UTC
Labels: No Feedback / Outdated?
