### ISSUE TITLE
Memory stick folder option on Android is just a text box

### ISSUE THREAD

**Issue by oldmario** [hrydgard/ppsspp#13364] opened 2020-08-31 00:11 UTC
### What happens?
when going to change the memory stick folder location option in the Android version of the app it will bring up a text box to enter the location instead of the android file browser

### What *should* happen?
The Android file browser should be popping up to allow the user to browse locations easily, it can get a bit messy with exact file locations especially when you bring memory cards into it which generate their own device location name

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
have tried it on both galaxy S6 with android 6 and a galaxy S10+ with android 10 with both v1.10.3 and v1.10.3-534-g77ac80dc0

**Comment by Panderner** [comment] 2020-08-31 00:17
@oldmario could you send me the screenshot?

**Comment by unknownbrackets** [comment] 2020-08-31 00:30
This issue is being closed as a duplicate of #10199.  #11997 is also relevant to why this is not as simple as it might seem.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-08-31 00:30 UTC
