### ISSUE TITLE
Please Fix Tekken 6 Lobby bug 

### ISSUE THREAD

**Issue by FahadAli2003** [hrydgard/ppsspp#11547] opened 2018-11-08 17:56 UTC
### What happens?
While I was playing Tekken 6  with my Cousin I tried to leave out the lobby to save my data but when I leave The lobby the game stucks there and I can't get back to lobby. so I request plz Fix this problem.
Sorry if I do anything wrong this is my first ever post here. Thanks in advance 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Hmm, I'm a android user so I find this bug in early versions also and also in this new version 1.7.1

**Comment by Emulatorer** [comment] 2018-11-08 21:39
What's your settings when you play Tekken6 both of you ? Are you using default settings?

What your android phone full specifications?

**Comment by adenovan** [comment] 2018-11-09 01:33
same issue with #9170 some older build version did not have the issues

**Comment by unknownbrackets** [comment] 2018-11-09 02:53
This issue is being closed as a duplicate of #9170.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-11-09 02:53 UTC
Labels: Networking / adhoc

**Comment by FahadAli2003** [comment] 2018-11-17 18:18
I'm using Own Settings on PPSSPP
