### ISSUE TITLE
Secret Agent Clank - Crashing on first level

### ISSUE THREAD

**Issue by CaptainAlexioC** [hrydgard/ppsspp#14431] opened 2021-05-06 13:28 UTC
#### What happens?
I am looking for help to address the issue of Secret Agent Clank (UCUS98697) crashing on the first level. It doesn't necessarily happen at the exact same point, but it seems unavoidable. I do not believe that it is related to the game, as I have seen YouTube videos of the same version run just fine without crashing. Happy to provide more details in getting to the bottom of this issue. I also have a video of the crash occurring if it helps in any way.

#### What should happen?
No crashing.

#### What hardware / device and operating system?
Windows 10
#### What graphics card (GPU) or mobile phone model?
Radeon RX 480. Tried backend setting in both Direct3D 9 and Direct3D 11 and neither setting fixes the crash.
#### What PPSSPP version (standalone/official), and did it work before?
I have tried both versions v1.11.3 and v1.10.3 and the crash occurs regardless.

#### Which game or games?
Secret Agent Clank (UCUS98697)

#### Checklist
 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2021-05-07 00:22
You may need to provide log file for the devs to investigate this crash.

1. Disable Fast memory from System settings.
2. Run `DebugLog.bat` which is located at the same folder with PPSSPP exe and play the game until crashed, it will generate a log file.
3. Zip the generated `ppsspplog.txt` log file and upload it here.

**Comment by CaptainAlexioC** [comment] 2021-05-07 03:26
Here you go. The original file size was obscenely large, too much for here even in a .zip file. So I have cut down all the lines aside from the last ~300. Hopefully it's enough to diagnose the issue.
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/6438809/ppsspplog.zip)

**Comment by ANR2ME** [comment] 2021-05-07 04:26
It's normal for debug log to have a lot of lines, and your truncated logs is probably too little.
I can't find any Warning (`W[SCE`) or Error (`E[SCE`) being logged in your truncated log.

Btw, with Fast memory being disabled does it still crashed or it's showing a blue screen? 
if it's blue screen could you show the screenshot of this blue screen?

**Comment by CaptainAlexioC** [comment] 2021-05-07 05:05
Ok, so I have had a playthrough of the first level again, and miraculously got no crash. I cannot say whether or not this was by sheer luck or if the issue randomly fixed itself. But from the information I could get yesterday and today, I can note a few things:
- While I had fast memory enabled, crashing did not immediately result in a blue screen, but trying to rewind or switch back and forth between full screen did. I have attached a screenshot of this blue screen.
- With fast memory disabled, the game would still crash on the last working frame, but I did not test to see if a blue screen would come up.
- There are about 8300000 lines on the original log file, and the last time I get a warning is around line 3640000:
58:51:701 atrac loader W[SCEIO]: HLE\sceIo.cpp:2180 8002032a=sceIoWaitAsync(11, 09f74a38[ffffffffffffffff]): no async pending
-The last time I get an error is on line 531483, reading:
53:27:195 rcp level ma E[SCEDISP]: HLE\sceDisplay.cpp:998 80000104=sceDisplaySetFrameBuf(04000000, 0, 0, 1): invalid stride

If this info doesn't help diagnose the issue, I am happy to run on the dev build to obtain more information. But I may be able to run the game fine from this point on, just can't predict if the game will crash. I will keep you updated.

**Comment by ANR2ME** [comment] 2021-05-07 06:39
The reason why we need you to test this on the latest dev build is to find out whether the issue has been fixed on recent updates or not, because there were a few updates that fixed things that could lead to a crash/blue screen recently.

Btw, are you using cheat on this game?

**Comment by CaptainAlexioC** [comment] 2021-05-07 08:54
Ok, well I have attempted to reproduce the bug on the latest dev build and I wasn't able to. So I guess it's fine for now? I can't guarantee that it won't happen again later, so I will keep track of it using said build, and provide an updated log.

I have used cheats for the game before, but I had them disabled at the time of the crashes.

**Comment by Panderner** [comment] 2021-05-07 09:23
Secret Agent Clank works fine for me in latest builds of PPSSPP. The first level doesn't crash for me in all backends.

**Comment by CaptainAlexioC** [comment] 2021-05-09 10:44
Lately I do get crashes in a similar manner, but I can work around by rewinding the frames. However, near the end of the game, I did get this on the release build.
![error](https://user-images.githubusercontent.com/83767535/117569114-9dc04900-b0f6-11eb-92a7-bbf4eae1fc00.png)

**Comment by Gamemulatorer** [comment] 2021-05-09 11:00
> Lately I do get crashes in a similar manner, but I can work around by rewinding the frames. However, near the end of the game, I did get this on the release build.
> ![error](https://user-images.githubusercontent.com/83767535/117569114-9dc04900-b0f6-11eb-92a7-bbf4eae1fc00.png)

Try the latest git build https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Panderner** [comment] 2021-05-09 11:48
Umm yes i beat the first level of this game and it didn't crash on latest build.

**Comment by ANR2ME** [comment] 2021-05-09 15:01
> 
> 
> Lately I do get crashes in a similar manner, but I can work around by rewinding the frames. However, near the end of the game, I did get this on the release build.
>
Release build is older than dev build, so it's normal for release build to have bug and got fixed later on dev build, and dev build will eventually become the next release build when it's ready to be released.

**Comment by CaptainAlexioC** [comment] 2021-05-09 16:06
Thanks for your responses. I believe I have found the source of the problem, I think the ROM I was using had been slightly corrupted. I have used a fresh one on the latest dev build and no crashes have occurred since.

**Comment by CaptainAlexioC** [comment] 2021-05-10 04:19
Uh oh, looks like the crashes haven't gone. It happens every single time I get to this level, crashing on this frame. Log is uploaded on the latest dev build.
![freeze](https://user-images.githubusercontent.com/83767535/117605305-fc82d280-b189-11eb-8cac-b62480cadf01.png)
[log.zip](https://github.com/hrydgard/ppsspp/files/6449411/log.zip)

**Comment by Gamemulatorer** [comment] 2021-05-10 05:12
> Uh oh, looks like the crashes haven't gone. It happens every single time I get to this level, crashing on this frame. Log is uploaded on the latest dev build.
> ![freeze](https://user-images.githubusercontent.com/83767535/117605305-fc82d280-b189-11eb-8cac-b62480cadf01.png)
> [log.zip](https://github.com/hrydgard/ppsspp/files/6449411/log.zip)

Can you upload your savestate data files

**Comment by CaptainAlexioC** [comment] 2021-05-10 05:21
So I managed to find a work around for that specific crash, and overwrote the save file that was causing that specific crash and have progressed later into the game. I'm afraid I can no longer reproduce the glitch, but the crashes still occur. Thing is, it's extremely difficult to get a log when the crashes occur because: 1) they are very unpredictable, 2) usually by the time they occur, the log file is multiple GB in size, and notepad doesn't allow me to open them nor can I upload them here.

Try this anyway and play for a bit and see if you can reproduce what I am getting. I really cannot pin down what is causing this.
[savedata.zip](https://github.com/hrydgard/ppsspp/files/6449647/savedata.zip)

**Comment by CaptainAlexioC** [comment] 2021-05-10 05:36
I have managed to get a log of a crash early on using the save file above. Load the file, and select the challenge "Mega Challenge: Cafeteria" and it occurred as per the log I am sending here. If you would like me to send a video of it, let me know. I apologize for making this difficult.
[log.zip](https://github.com/hrydgard/ppsspp/files/6449728/log.zip)

**Comment by Panderner** [comment] 2021-05-10 06:26
I completed "Mega Challenge: Cafeteria" arena and i didn't crash

**Comment by CaptainAlexioC** [comment] 2021-05-10 09:15
Is it possible that I could stream the bug occurring on the Discord? Seems like it's the only way I can resolve this since nobody is able to reproduce it.

**Comment by unknownbrackets** [comment] 2021-05-23 20:51
Maybe, but the problem isn't belief, it's that to fix things developers usually need to be able to reproduce them.

Think of it this way: suppose I said that I had a bookcase, but it was broken.  One of the shelves is starting to bend when you press down on it, and there's a crack.  And since you're my friend, I ask if you could help me by screwing a plate underneath the shelf to act as a splint.  That way, the crack will stop getting worse.

Sounds reasonable, right?  So you come over to my house to look at my bookcase with your screwdriver and the plate in hand, glad to do me a solid.  However, when we get to the bookcase, you press down on each of the shelves and none of them are bending.  You stand back, and ask me to show you - I press, and it does bend.  But my place is small so you're too far away to see exactly where it bends or where the crack is.

So you ask me: where should I put the plate?  Over here?  Maybe a little to the left?

I tell you that I'm not a programmer, so I don't know.  I just want it to stop bending.

You put the plate somewhere, and then step back so I can test it.  I press and tell you, you've put the plate in entirely the wrong place.  It's still bending.

This is the experience of a programmer unable to reproduce a bug.  You need to be able to do it when you're right there, so you can put the plate in the right place.  Sometimes it's easier to guess, but if you can't see and feel the crack for yourself at all, you could spend days screwing the plate into different places hoping one of these times you'll guess right.

That's why we're asking for details on how to reproduce.  We don't just want to see it from far away.

--

Cheats can sometimes cause problems even when they're off.  When you turn on a cheat, it modifies things.  Turning off the cheat doesn't undo those modifications.  If you delete all save states, turn off cheats, and load a save game does it happen?

It might also be a good idea to try resetting to default settings.  Many hack settings, such as changing the CPU clock can cause weird problems.

-[Unknown]

**Comment by benderscruffy** [comment] 2022-11-30 05:30
this doesn't crash for me 
can this be closed ???

**Closed** 2022-11-30 06:38 UTC
Labels: No Feedback / Outdated?
