### ISSUE TITLE
could add save button and load button in the android version?

### ISSUE THREAD

**Issue by Wesleyjor6** [hrydgard/ppsspp#14255] opened 2021-03-04 01:45 UTC
Hello I was trying to place an order but I couldn't do it here to see if it will result in anything, I would like to ask you if you can add two save buttons and the other one to load on the controls layout screen?  Because I bore opening the menu, they don’t have much serious precision much faster if there was a button to save and quickly press an additional button.

**Comment by LunaMoo** [comment] 2021-03-04 02:02
Closing as a duplicate of #12011 also #13869 should be a solution when accepted.

**Closed by LunaMoo** 2021-03-04 02:02 UTC
