### ISSUE TITLE
Marvel Ultimate Alliance 1 Black Screen Cutscenes

### ISSUE THREAD

**Issue by JoaoVitorApolinario** [hrydgard/ppsspp#11476] opened 2018-10-17 00:21 UTC
Hello, I'm having problems with the cutscenes on Ultimate Alliance 1, instead of showing the videos only black screens and audio appear. 
In game works fine, the cutscenes are the only problem.
Running on version 1.6.3 on android, my device is a Samsung j7 2016.
 I found this page with the exact same problem https://github.com/hrydgard/ppsspp/issues/9852

Any help is welcome

**Comment by Emulatorer** [comment] 2018-10-17 01:46
Did you try enable simulate block tranfer effects in the settings or try to use the latest git build.

Your CPU is Exynos 7870 octa-core?
sad to say ppsspp has a problem with Samsung Exynos CPU :(

**Comment by LunaMoo** [comment] 2018-10-17 03:06
Closing as a duplicate of issue mentioned above. Please don't open duplicate issues. This place exists to track PPSSPP problems, not to give personal attention.

**Closed by LunaMoo** 2018-10-17 03:06 UTC
