### ISSUE TITLE
Split Second Velocity Colour Issue.

### ISSUE THREAD

**Issue by jbakach** [hrydgard/ppsspp#4472] opened 2013-11-07 13:17 UTC
Hi, I've been trying to play this game, but there's a problem, when the first video is loaded it crashes on Android. A few seconds after the first image, it crashes for no reason, I could think is a problem of the video conversion. Who knows, also tried to disable the sound to see if it fixes the problem, but no luck.

**Comment by thedax** [comment] 2015-02-17 08:47
Is the only remaining issue here the black box? If so, I'm going to close this in favour of #7492. @daniel229, can you please see how this game is looking in the latest builds?

**Comment by daniel229** [comment] 2015-02-17 08:52
remaining issue,the black box and the colour.
![01](https://cloud.githubusercontent.com/assets/3481559/6225449/61e8adb4-b6c5-11e4-97af-52d30377e30d.png)
![02](https://cloud.githubusercontent.com/assets/3481559/6225448/61e7b968-b6c5-11e4-80b7-c1f03a6bc454.png)

**Comment by thedax** [comment] 2015-02-17 08:53
Thanks @daniel229. Renamed the issue to differentiate it from #7492.

**Comment by unknownbrackets** [comment] 2015-02-22 19:29
So, the issue with the color here is that the game is drawing to the same framebuffer using different 16-bit color formats.  For example, 4444 and 565.  This causes wrong colors, because we just take the RGB values of each one, rather than re-interpreting.

To solve this, we could do any of the following:

1. We could create a new framebuffer when the format changes, and re-interpret the rgb (similar to depal) when this happens.  This would be devastatingly slow for this game and others, I think.

2. We could choose a "master" format for each framebuffer, and eventually change it (like w/h.)  If the render doesn't match the master format, we would do extra work in the fragment shader (I guess?) to re-write the RGBA values to be more appropriate for the conversion being applied.

3. We could try some alternative method for newer GL that involves image buffers or something, which might (?) give better performance than adding lots of work to the frag shader?

Picking the right format for the framebuffer seems tricky.  I guess we want the format really to prioritize what it is used as, rather than rendered from, if there are multiple formats...

-[Unknown]

**Comment by hrydgard** [comment] 2015-02-22 20:02
The best solution is probably 1 if we make sure not to recreate the buffers every frame but instead keep a second one around for each simulated fb (both really 8888) so we could "ping-pong" at each such conversion, and while it would slow things down, it would probably not be "devastatingly" slow - just like depal isn't. It would of course not be free though and would be quite a bit of work. In modern GL we could probably even do the conversions in-place using a compute shader.

**Comment by unknownbrackets** [comment] 2015-02-22 21:18
Well, I know that Kingdom Hearts and some other games zero out framebuffers with the wrong format, and do this for shadows and things multiple times per frame IIRC.  So, I do think it could be very slow, especially on not super strong devices.

-[Unknown]

**Comment by BogdanTheGeek** [comment] 2018-06-07 23:59
This issue can be fixed by turning on buffered rendering and running in OpenGL (DX 11 is a bit more stuttery).

**Comment by unknownbrackets** [comment] 2019-02-22 03:43
Could anyone post a GE dump?  I think we know what the issue is, but it'd help debug and verify it.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy01** [comment] 2019-03-24 06:33
i think this is an android problem as it doesnt happen in windows version

**Comment by unknownbrackets** [comment] 2019-03-26 01:20
Ah, missed and forgot that there's a demo for this one.

The remaining issue is the color of the numbers:
![NPUH01972_00000](https://user-images.githubusercontent.com/191233/54964524-06093c00-4f2a-11e9-8bb1-9c3c5cf30401.png)

Dumps like [NPUH90093_#4472_hud2.zip](https://github.com/hrydgard/ppsspp/files/3006082/NPUH90093_.4472_hud2.zip) are not playing back correctly on a PSP, but the HUD is showing right:
![NPUH90093_#4472_hud2](https://user-images.githubusercontent.com/191233/54964608-5ed8d480-4f2a-11e9-92fb-df55f940e82d.png)

And I'm pretty sure those colors are right (not a side effect of whatever GE dump bug is making the sky not show), referencing this gameplay video from 2010:
https://youtu.be/PX5GTxpphKs?t=175

I think it's a framebuffer reinterpretation problem though.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-04-14 06:56
This safe close now? In favor of #13957

**Comment by hrydgard** [comment] 2022-04-14 12:21
Yeah, that issue is about the remaining problems with the game, so we don't need this one anymore.

**Closed by hrydgard** 2022-04-14 12:21 UTC
