### ISSUE TITLE
GOW - Ghost Of Sparta Segmentation fault

### ISSUE THREAD

**Issue by buuf** [hrydgard/ppsspp#6982] opened 2014-10-07 22:31 UTC
Using Linux MInt 17 64-bit
Using bumblebee/primusrun/optirun

Using ppsspp 0.9.9.1-523-g199e6bc (a dev working build, I'll give the released build a try too and it doesn't fault
![screenshot from 2014-10-07 17 39 11](https://cloud.githubusercontent.com/assets/9060726/4551939/9894eb3e-4e79-11e4-81d8-a9806a09b01b.png)

I attached an image showing when it happens in-game. Soon as I would hit L, fault.

mack@mackshit ~ $ vblank_mode=0 primusrun ~/Documents/scripts/ppsspp.sh 
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
OpenGL 2.0 or higher.
54:47:188 Core/Config.cpp:820 I[LOAD]: Loading controller config: /home/mack/.config/ppsspp/PSP/SYSTEM/controls.ini
Pixels: 960 x 544
Virtual pixels: 960 x 544
I: /home/karen/Development/ppsspp/native/gfx_es2/gl_state.cpp:130: I: GPU Vendor : NVIDIA Corporation ; GL version str: 4.4.0 NVIDIA 343.22 ; GLSL version str: 4.40 NVIDIA via Cg compiler
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
54:49:098 Core/System.cpp:328 I[BOOT]: PPSSPP v0.9.9.1-523-g199e6bc
54:49:099 Core/MemMap.cpp:339 I[MM]: Memory system initialized. RAM at 0x7fd5060ff000 (mirror at 0 @ 0x2308000000, uncached @ 0x2348000000)
54:49:099 Core/PSPLoaders.cpp:159 I[LOAD]: UCUS98737 : God of War®: Ghost of Sparta
54:49:099 Core/PSPLoaders.cpp:200 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
54:49:099 HLE/sceKernelMemory.cpp:431 I[KERNEL]: Kernel and user memory pools initialized
54:49:130 HLE/sceKernel.cpp:151 I[KERNEL]: Kernel initialized.
54:49:210 Util/BlockAllocator.cpp:381 I[HLE]: -----------
54:49:210 Util/BlockAllocator.cpp:385 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
54:49:210 Util/BlockAllocator.cpp:385 I[HLE]: Block: 08804000 - 08c5f300 size 0045b300 taken=1 tag=ELF/dax
54:49:210 Util/BlockAllocator.cpp:385 I[HLE]: Block: 08c5f300 - 0c000000 size 033a0d00 taken=0 tag=(untitled)
54:49:210 Util/BlockAllocator.cpp:387 I[HLE]: -----------
54:49:290 HLE/sceKernelModule.cpp:1028 I[LOAD]: Module dax: 00000000 08bf7510 08bf7528
54:49:291 HLE/sceKernelModule.cpp:1229 I[LOAD]: Exporting ent 0 named dax, 2 funcs, 4 vars, resident 08bf78b0
54:49:291 HLE/sceKernelModule.cpp:1557 I[LOAD]: Module entry: 08804c38
I: /home/karen/Development/ppsspp/native/file/zip_read.cpp:326: I: Not a VFS path: /home/mack/emulators/ppsspp/assets/shaders/defaultshaders.ini . Reading local file.
I: /home/karen/Development/ppsspp/native/file/zip_read.cpp:359: I: Not a VFS path: /home/mack/.config/ppsspp/PSP/shaders . Reading local directory.
54:49:296 root         N[BOOT]: UI/EmuScreen.cpp:129 Loading /home/mack/Roms/PSP/psy-gwgs.iso...
54:49:296 root         I[KERNEL]: HLE/sceKernelThread.cpp:2178 276=sceKernelCreateThread(name=user_main, entry=08804d58, prio=20, stacksize=262144)
54:49:296 root         I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=276, argSize=33, argPtr=0bfffed0)
54:49:297 root         I[KERNEL]: HLE/sceKernelThread.cpp:2318 __KernelReturnFromThread: 0
54:49:305 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 278=sceKernelCreateThread(name=ExitCallbackThread, entry=08808a40, prio=10, stacksize=4096)
54:49:305 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=278, argSize=0, argPtr=00000000)
54:49:305 user_main    I[HLE]: HLE/scePower.cpp:369 scePowerSetClockFrequency(333,333,166)
54:49:364 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 305=sceKernelCreateThread(name=DiscSpinnerThread, entry=08a77e84, prio=38, stacksize=4096)
54:49:364 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=305, argSize=0, argPtr=00000000)
54:49:365 DiscSpinnerT E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(4, 56)
54:49:366 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 307=sceKernelCreateThread(name=PowerControlThread, entry=08a76790, prio=10, stacksize=4096)
54:49:366 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=307, argSize=0, argPtr=00000000)
54:49:406 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(768)
54:49:409 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(770)
54:49:443 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(769)
54:49:459 user_main    I[SCESAS]: HLE/sceSas.cpp:106 sceSasInit(08c5e400, 256, 32, 0, 44100)
54:49:459 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 315=sceKernelCreateThread(name=snd_tick_timer_thread, entry=08aec57c, prio=2e, stacksize=4096)
54:49:459 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=315, argSize=0, argPtr=00000000)
54:49:462 snd_tick_tim I[KERNEL]: HLE/sceKernelThread.cpp:2331 sceKernelExitThread(0)
54:49:462 user_main    W[KERNEL]: HLE/sceKernel.h:460 Kernel: Bad object handle -1 (ffffffff)
54:49:462 user_main    W[KERNEL]: HLE/sceKernel.h:460 Kernel: Bad object handle -1 (ffffffff)
54:49:462 user_main    W[KERNEL]: HLE/sceKernel.h:460 Kernel: Bad object handle -1 (ffffffff)
54:49:462 user_main    W[KERNEL]: HLE/sceKernel.h:460 Kernel: Bad object handle -1 (ffffffff)
54:49:493 user_main    I[UTIL]: HLE/sceUtility.cpp:259 sceUtilityUnloadModule(769)
54:49:493 user_main    I[UTIL]: HLE/sceUtility.cpp:259 sceUtilityUnloadModule(770)
54:49:493 user_main    I[UTIL]: HLE/sceUtility.cpp:259 sceUtilityUnloadModule(768)
54:49:493 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(768)
54:49:509 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(770)
54:49:543 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(769)
54:49:559 user_main    I[SCESAS]: HLE/sceSas.cpp:106 sceSasInit(08c5e400, 256, 32, 0, 44100)
54:49:560 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 321=sceKernelCreateThread(name=snd_tick_timer_thread, entry=08aec57c, prio=2e, stacksize=4096)
54:49:560 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=321, argSize=0, argPtr=00000000)
54:49:560 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: snd_stream v1.10.1
54:49:560 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: , built Nov  2 2007 at 15:39:24
54:49:560 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: Compiled against Scream v2.6.1
54:49:561 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 322=sceKernelCreateThread(name=snd_stream_service_thread_0, entry=08afbee8, prio=2e, stacksize=32768)
54:49:561 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=322, argSize=4, argPtr=0bfff2d0)
54:49:562 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(771)
54:49:593 user_main    I[ME]: HLE/sceMpeg.cpp:412 sceMpegInit()
54:49:617 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
54:49:637 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:329 Creating FBO for 00000000 : 1 x 1 x 3
54:49:639 user_main    I[SCEGE]: GLES/Framebuffer.cpp:711 Resizing FBO for 00000000 : 480 x 272 x 3
54:49:645 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:329 Creating FBO for 0008c000 : 480 x 272 x 3
54:49:962 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
54:50:329 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
54:50:581 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
54:50:582 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(6, 26)
54:50:597 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:329 Creating FBO for 00162000 : 480 x 272 x 3
54:50:598 user_main    W[HLE]: Common/FramebufferCommon.cpp:250 Rendering to framebuffer offset: 00162000 +256x0
54:50:600 user_main    I[SCEGE]: GLES/Framebuffer.cpp:711 Resizing FBO for 00162000 : 736 x 272 x 3
54:50:603 user_main    I[SCEGE]: GLES/Framebuffer.cpp:711 Resizing FBO for 00162000 : 864 x 272 x 3
54:50:628 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
54:50:629 user_main    I[UTIL]: HLE/sceUtility.cpp:224 sceUtilityLoadModule(1280)
54:50:629 user_main    I[HLE]: HLE/scePspNpDrm_user.cpp:10 call sceNpDrmSetLicenseeKey(08c00840)
54:50:629 user_main    E[FileSys]: FileSystems/DirectoryFileSystem.cpp:503 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
54:50:629 user_main    E[IO]: HLE/sceIo.cpp:1200 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/GAME/UCUS98737/dlcarena.EDAT, 40000001, 00000000) - file not found
54:50:659 user_main    E[FileSys]: FileSystems/DirectoryFileSystem.cpp:503 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
54:50:659 user_main    E[IO]: HLE/sceIo.cpp:1200 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/GAME/UCUS98737/dlccostume.EDAT, 40000001, 00000000) - file not found
55:09:255 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2506 sceKernelTerminateThread(322)
55:09:255 user_main    W[KERNEL]: HLE/sceKernel.h:460 Kernel: Bad object handle 322 (00000142)
55:09:255 user_main    E[KERNEL]: HLE/sceKernelThread.cpp:1458 __KernelGetWaitID ERROR: thread 322
55:09:256 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(0bffee10) - AUTOLOAD (0)
55:09:256 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(0bffee10) : Game key (hex): 456E6372797074344D6533506C7A3637
55:09:461 user_main    I[UTIL]: Dialog/SavedataParam.cpp:580 Loading file with size 204800 in ms0:/PSP/SAVEDATA/UCUS98737PROFILE00/SECURE
55:09:496 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: snd_stream v1.10.1
55:09:496 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: , built Nov  2 2007 at 15:39:24
55:09:496 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: Compiled against Scream v2.6.1
55:09:496 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 333=sceKernelCreateThread(name=snd_stream_service_thread_0, entry=08afbee8, prio=2e, stacksize=32768)
55:09:496 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=333, argSize=4, argPtr=0bfff350)
55:09:570 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1320 0=sceAtracSetDataAndGetID(08c5f6c0, 0001e000)
55:09:570 snd_stream_s W[ME]: HLE/sceAtrac.cpp:1207 This is an atrac3+ stereo audio
55:09:571 snd_stream_s E[ME]: HLE/sceAtrac.cpp:955 sceAtracGetSecondBufferInfo(0, 0bfbba54, 0bfbba58)
55:09:571 snd_stream_s E[ME]: HLE/sceAtrac.cpp:1375 sceAtracSetLoopNum(0, 2147483647):no loop information
55:09:572 snd_stream_s E[ME]: HLE/sceAtrac.cpp:640 WARNING: Remaining data in packet - we currently only decode one frame per packet
55:09:774 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(6, 26)
55:09:775 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(7, 26)
55:09:775 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(8, 26)
55:11:296 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1018 sceAtracReleaseAtracID(0)
55:11:297 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2506 sceKernelTerminateThread(333)
55:11:297 user_main    W[KERNEL]: HLE/sceKernel.h:460 Kernel: Bad object handle 333 (0000014d)
55:11:297 user_main    E[KERNEL]: HLE/sceKernelThread.cpp:1458 __KernelGetWaitID ERROR: thread 333
55:11:304 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(0bffee34) - LISTLOAD (4)
55:11:304 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(0bffee34) : Game key (hex): 456E6372797074344D6533506C7A3637
55:12:250 user_main    I[UTIL]: Dialog/SavedataParam.cpp:580 Loading file with size 204800 in ms0:/PSP/SAVEDATA/UCUS98737DATA04/SECURE
55:13:204 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(0bffe7e0) - AUTOLOAD (0)
55:13:204 user_main    I[UTIL]: Dialog/PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(0bffe7e0) : Game key (hex): 456E6372797074344D6533506C7A3637
55:13:432 user_main    I[UTIL]: Dialog/SavedataParam.cpp:580 Loading file with size 204800 in ms0:/PSP/SAVEDATA/UCUS98737PROFILE00/SECURE
55:13:466 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: snd_stream v1.10.1
55:13:466 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: , built Nov  2 2007 at 15:39:24
55:13:466 user_main    I[KERNEL]: HLE/sceKernelMemory.cpp:1140 sceKernelPrintf: Compiled against Scream v2.6.1
55:13:466 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2178 340=sceKernelCreateThread(name=snd_stream_service_thread_0, entry=08afbee8, prio=2e, stacksize=32768)
55:13:466 user_main    I[KERNEL]: HLE/sceKernelThread.cpp:2277 sceKernelStartThread(thread=340, argSize=4, argPtr=0bffed20)
55:13:473 user_main    I[SCEGE]: GLES/Framebuffer.cpp:711 Resizing FBO for 00162000 : 480 x 272 x 3
55:13:481 user_main    I[SCEGE]: GLES/Framebuffer.cpp:711 Resizing FBO for 00162000 : 736 x 272 x 3
55:13:484 user_main    I[SCEGE]: GLES/Framebuffer.cpp:711 Resizing FBO for 00162000 : 864 x 272 x 3
55:13:506 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1320 0=sceAtracSetDataAndGetID(08c5f6c0, 0001e000)
55:13:506 snd_stream_s W[ME]: HLE/sceAtrac.cpp:1207 This is an atrac3+ stereo audio
55:13:507 snd_stream_s E[ME]: HLE/sceAtrac.cpp:955 sceAtracGetSecondBufferInfo(0, 0bfbba54, 0bfbba58)
55:13:550 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1018 sceAtracReleaseAtracID(0)
55:13:808 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
55:13:808 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(6, 26)
55:13:812 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1320 0=sceAtracSetDataAndGetID(08c5f6c0, 0001e000)
55:13:812 snd_stream_s W[ME]: HLE/sceAtrac.cpp:1207 This is an atrac3+ stereo audio
55:13:813 snd_stream_s E[ME]: HLE/sceAtrac.cpp:955 sceAtracGetSecondBufferInfo(0, 0bfbba54, 0bfbba58)
55:14:399 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
55:14:399 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(6, 26)
55:14:681 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:329 Creating FBO for 00161800 : 480 x 272 x 3
55:14:683 user_main    I[SCEGE]: Common/FramebufferCommon.cpp:329 Creating FBO for 00181800 : 480 x 272 x 0
55:14:683 user_main    W[SCEGE]: Common/FramebufferCommon.cpp:371 FBO reusing depthbuffer, 00181800/00118000 and 00000000/00118000
55:19:234 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(7, 47)
55:22:865 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
55:29:391 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(7, 47)
55:39:583 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(7, 47)
55:45:847 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 26)
55:45:847 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(6, 26)
55:49:787 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(7, 47)
55:59:954 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(7, 47)
56:01:475 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1018 sceAtracReleaseAtracID(0)
56:01:566 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1320 0=sceAtracSetDataAndGetID(08c5f6c0, 0001e000)
56:01:566 snd_stream_s W[ME]: HLE/sceAtrac.cpp:1207 This is an atrac3+ stereo audio
56:01:567 snd_stream_s E[ME]: HLE/sceAtrac.cpp:955 sceAtracGetSecondBufferInfo(0, 0bfbba54, 0bfbba58)
56:08:529 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
56:18:706 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
56:28:869 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
56:39:094 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
56:46:185 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1018 sceAtracReleaseAtracID(0)
56:46:229 snd_stream_s I[ME]: HLE/sceAtrac.cpp:1320 0=sceAtracSetDataAndGetID(08c5f6c0, 0001e000)
56:46:229 snd_stream_s W[ME]: HLE/sceAtrac.cpp:1207 This is an atrac3+ stereo audio
56:46:230 snd_stream_s E[ME]: HLE/sceAtrac.cpp:955 sceAtracGetSecondBufferInfo(0, 0bfbba54, 0bfbba58)
56:54:838 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
57:05:014 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
57:15:174 snd_stream_s E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(5, 47)
57:17:903 user_main    E[IO]: HLE/sceIo.cpp:1629 UNIMPL sceIoChangeAsyncPriority(6, 26)
/home/mack/Documents/scripts/ppsspp.sh: line 1:  2897 Segmentation fault      /home/mack/emulators/ppsspp/PPSSPPSDL

**Comment by unknownbrackets** [comment] 2015-02-22 22:17
Does this happen with default settings?  Does it happen with fast memory off?  Is it reproducible on Windows/WINE or other platforms?

A stack trace would really tell us more.

-[Unknown]

**Comment by buuf** [comment] 2015-02-23 11:06
What's a stack trace, how do I do that on Linux/Windows?

**Comment by unknownbrackets** [comment] 2015-12-24 17:42
A stack trace shows the path the code took to lead to a segmentation fault.  You can get one by running the executable using gdb.

The basics are:
1. You need to compile in debug mode, meaning `cmake -DCMAKE_BUILD_TYPE=Debug`.
2. You need gdb installed (ask your favorite package manager.)
3. Run PPSSPP like this from a terminal: `gdb ./PPSSPPSDL`, then type `run`.
4. When it crashes, go back to that terminal and type `bt`.
5. Copy the result.  This is the stack trace or "back trace".

A more in-depth tutorial:
https://beej.us/guide/bggdb/

On Windows, you can compile with MSVC (Community is free), and then simply press F5 within MSVC.  When it crashes, it will show the stack trace.

-[Unknown]

**Comment by daniel229** [comment] 2015-12-25 01:11
I get an Invalid address there with the same build in windows.It has been improved later,I can't reproduce wth the latest and 1.0.1,but some people still have the problem in 1.0.1
```
07:16:133 user_main    W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000094
07:16:133 user_main    W[MM]: MemmapFunctions.cpp:93 ReadFromHardware: Invalid address 00000094
```

**Comment by daniel229** [comment] 2015-12-25 01:32
It happen in v0.9.9.1-523-g199e6bc but not in v0.9.9.1-533-g2aed007 ,sound like an atrac3 issue.
https://github.com/hrydgard/ppsspp/compare/v0.9.9.1-523-g199e6bc...v0.9.9.1-533-g2aed007

**Comment by unknownbrackets** [comment] 2015-12-25 21:05
Oh okay, so that means this is potentially fixed?  We don't know how to reproduce the problem some people still have in 1.0.1?  Maybe that problem only happens using savestates.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-03 12:24
I found the problem now.
if dropping from here,it get invalid addresses.
![01](https://cloud.githubusercontent.com/assets/3481559/12078719/e739d356-b257-11e5-912b-e535dcb46dbb.png)

if dropping from here,it's fine.
![02](https://cloud.githubusercontent.com/assets/3481559/12078721/ec70c622-b257-11e5-8d10-6dfb1ccb6ee5.png)

**Comment by unknownbrackets** [comment] 2019-03-20 05:17
Has this gotten any better in recent versions like v1.8.0?

-[Unknown]

**Comment by prashanthar2000** [comment] 2020-09-01 11:29
Go into "Settings", then "System" and uncheck "Fast Memory (unstable)."
thanks to https://www.reddit.com/r/PPSSPP/comments/fk8kmq/gow_ghost_of_sparta_crash/

**Comment by hrydgard** [comment] 2020-09-01 11:32
Yeah it can be worked around that way, but it's still an issue. Very hard bug to track down though.

**Comment by prashanthar2000** [comment] 2020-09-01 11:44
ya i get it

**Comment by Gamemulatorer** [comment] 2022-07-11 13:07
> I found the problem now. if dropping from here,it get invalid addresses. ![01](https://cloud.githubusercontent.com/assets/3481559/12078719/e739d356-b257-11e5-912b-e535dcb46dbb.png)
> 
> if dropping from here,it's fine. ![02](https://cloud.githubusercontent.com/assets/3481559/12078721/ec70c622-b257-11e5-8d10-6dfb1ccb6ee5.png)

That particular area always crash using IR Interpreter but can workaround now by enabling this in JIT DEBUG TOOLS.
![Screenshot_2022-07-11-16-56-36-531_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/178270944-fafccc42-f7b8-4327-ace1-417c7c2d680d.jpg)

**Comment by unknownbrackets** [comment] 2022-10-30 00:30
This is definitely the same issue as #14958 which is not at all IR specific.  It's just that IR handles crashes a bit differently (you can't so much "ignore" them as you can with the jit.)  Either way, a crash is a crash.

I'm going to close this now as the other has more save data, save states, and technical notes, etc.  Unfortunately the issue is not yet solved, but there are two possible workarounds:
 * If using jit (not interpreter or IR interpreter), you can disable "fast memory" or in many cases just make sure "ignore bad memory access" is checked.  The game is still internally crashing (and there might be game bugs as a result), but we're forcing it to keep running.
 * Otherwise, temporarily override the CPU Mhz to 200 and it will work.  You'll want to set it back afterward.

-[Unknown]

**Closed by unknownbrackets** 2022-10-30 00:30 UTC
Labels: No Feedback / Outdated?

**Comment by bigsmoke682** [comment] 2023-01-09 06:18
> This is definitely the same issue as #14958 which is not at all IR specific.  It's just that IR handles crashes a bit differently (you can't so much "ignore" them as you can with the jit.)  Either way, a crash is a crash.
> 
> 
> 
> I'm going to close this now as the other has more save data, save states, and technical notes, etc.  Unfortunately the issue is not yet solved, but there are two possible workarounds:
> 
>  * If using jit (not interpreter or IR interpreter), you can disable "fast memory" or in many cases just make sure "ignore bad memory access" is checked.  The game is still internally crashing (and there might be game bugs as a result), but we're forcing it to keep running.
> 
>  * Otherwise, temporarily override the CPU Mhz to 200 and it will work.  You'll want to set it back afterward.
> 
> 
> 
> -[Unknown]

Hello I am having the same issue and I've tried what you said and it still won't work is there anything else ?

**Comment by casasfernando** [comment] 2023-10-22 17:08
> I found the problem now. if dropping from here,it get invalid addresses. ![01](https://cloud.githubusercontent.com/assets/3481559/12078719/e739d356-b257-11e5-912b-e535dcb46dbb.png)
> 
> if dropping from here,it's fine. ![02](https://cloud.githubusercontent.com/assets/3481559/12078721/ec70c622-b257-11e5-8d10-6dfb1ccb6ee5.png)

Thanks a lot. I was hitting this issue and simply dropping from the other spot avoided the crash. No need to change any settings.
