### ISSUE TITLE
Monster Hunter 3 HD save state bug

### ISSUE THREAD

**Issue by saber00** [hrydgard/ppsspp#7752] opened 2015-05-18 09:48 UTC
Hi, when I'm playing MHP3HD, and uses the save state function, it would break the normal save file of the game. So I save state and then load into the state again, then I save normally by sleeping, then it would appear that no save file is found and is unable to save. I am pretty sure that there is a save file in the psp folder. Also, it seems that sometimes ppsspp is unable to show Chinese characters, and replace them with a question mark. I'm using the latest working version of PPSSPP and the problem exists on OSX and windows. 
![screen shot 2015-05-18 at 5 47 26 pm](https://cloud.githubusercontent.com/assets/6960336/7678340/fc9953a2-fd85-11e4-8b0e-1a4cd8cd375d.png)

**Comment by daniel229** [comment] 2015-05-18 09:51
Duplicate of https://github.com/hrydgard/ppsspp/issues/7244

**Comment by hrydgard** [comment] 2015-05-18 10:18
Yeah, duplicate, and might not even be solvable. Stick to either save states or ingame saves to work around the problem.

**Closed by hrydgard** 2015-05-18 10:18 UTC
