### ISSUE TITLE
windows 10 mobile

### ISSUE THREAD

**Issue by zerglingno2** [hrydgard/ppsspp#8682] opened 2016-04-06 10:58 UTC
now jit is back on windows 10 
https://channel9.msdn.com/Events/Build/2015/C9-04
can you port ppsspp to windows 10 store

**Comment by unknownbrackets** [comment] 2016-04-08 06:32
This issue is being closed as a duplicate of #7854.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

-[Unknown]

**Closed by unknownbrackets** 2016-04-08 06:32 UTC
