### ISSUE TITLE
Req: Allow UI navigation with left analog stick

### ISSUE THREAD

**Issue by ds22x** [hrydgard/ppsspp#12678] opened 2020-03-07 14:38 UTC
It's currently only possible to navigate the UI with the Dpad, which for most controllers is somewhat problematic due to the placement of the Dpad and left analog stick (E.G. the Xbox controllers).
It would therefore be nice if you'd be able to navigate the UI with the left analog stick as well.

**Comment by hrydgard** [comment] 2020-03-07 22:41
I think this has been requested before but I can't find the issue so let's leave this open.

This does need fixing.

**Comment by vnctdj** [comment] 2020-03-07 22:55
@hrydgard 
Is it https://github.com/hrydgard/ppsspp/issues/10996?

**Comment by hrydgard** [comment] 2020-03-07 22:58
Indeed, closing as duplicate of that - and also tagging that for 1.10.

**Closed by hrydgard** 2020-03-07 22:58 UTC
Labels: Feature Request
