### ISSUE TITLE
Tomb raider anniversary slowdowns

### ISSUE THREAD

**Issue by Sebas365** [hrydgard/ppsspp#15391] opened 2022-02-10 21:02 UTC
### Game or games this happens in

ULES-00826

### What area of the game

Croft Mannor

If you try to move around the fps tends to go between 40-60 fps until you use the evade button, that cut fps to 30

### Speed seen in PPSSPP

50% (30fps)

### Platform

Android

### Mobile phone model or graphics card

SAMSUNG Galaxy A21S

### PPSSPP version affected

1.12.3-116

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment] 2022-02-10 21:46
Closing as a duplicate of #7677
AFAIK if your hardware is powerful enough, just overclocking emulated PSP CPU is enough to solve this problem as Tomb Raider games suffer from similar fate on real hardware, it's just an awful port.

**Closed by LunaMoo** 2022-02-10 21:46 UTC
