### ISSUE TITLE
Font Issue: Blazblue Continuum Shift 2 (subpixel handling)

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7871] opened 2015-07-22 00:39 UTC
The font in game is all garbled up and in tutorial some letters are missing. Seems like PPSSPP is using the wrong font for the game or the font is missing or something.

![ss 2015-07-22 at 02 34 49 1](https://cloud.githubusercontent.com/assets/2002038/8815521/845698a6-301a-11e5-9315-84811b7a4a82.jpg)

It happens in the USA version but i'm pretty sure it happens in all versions of the game.

**Comment by hrydgard** [comment] 2015-07-22 10:37
If you replace the fonts in flash0/ with fonts dumped from your real PSP, does that help? 

Our "copyright-free" font files are not completely compatible with the real ones, unfortunately.

**Comment by GamerzHell9137** [comment] 2015-07-22 16:50
Maybe? I dunno because i don't have a real PSP. Can't we like replace the font with a free font or something?

**Comment by hrydgard** [comment] 2015-07-22 19:09
That's exactly what we did (well, JPCSP guys, we are reusing their work in this area). But the metrics  (sizes of individual characters) don't match up very well and there may be other issues, the PSP font file format is quite complicated.

**Comment by vnctdj** [comment] 2015-07-23 08:30
@GamerzHell9137 
You have to dump the font files from the flash0 of the PSP, not the game.

1. You need a PSP with a custom firmware installed, if not, I recommend you [this tutorial](http://wololo.net/cfw4dummies/).
2. On the PSP, press the "Select" button when you are on the XMB. You will access the VSH Menu.
3. Press "down" on your D-pad to select "USB DEVICE" and then press "right" to choose "Flash 0".
4. Press the "Select" button to exit the VSH Menu.
5. Connect the PSP to the PC.
6. On the PC, open the device and **copy** the "font" folder and paste it in *your_PPSSPP_folder\memstick\PSP\flash0*, if the folder doesn't exist, create it.
**WARNING :** Don't alter or delete any file from the flash0 of your PSP or you will experience big problems...
7. You can know eject the device.
8. On the PSP, go back to the XMB and press the "Select" button to access the VSH Menu.
9. Press "down" on your D-pad to select "USB DEVICE" and then press "left" to choose "Memory Stick".
10. Press the "Select" button to exit the VSH Menu.

**Comment by GAMELASTER** [comment] 2015-07-23 14:07
Or just simply, can someone upload somewhere a PSP fonts huehuehueheue? :D

**Comment by hrydgard** [comment] 2015-07-23 14:12
No.

**Comment by ofry** [comment] 2015-07-25 01:18
Huh, I will not give link to original PSP fonts, but I found it easily just now :) Just search it, and you will find it.

2 hrydgard: if this post forbids rules, just simply delete it.

**Comment by ofry** [comment] 2015-07-25 01:44
![2015-07-25 04 43 24 2](https://cloud.githubusercontent.com/assets/11790863/8887380/cabb8fda-3287-11e5-8602-074ae9da1cf8.png)

This image I got with original fonts and unbuffered rendering.

**Comment by ppmeis** [comment] 2015-07-25 14:45
I get the same with original fonts:
![image](https://cloud.githubusercontent.com/assets/4381277/8889877/7f152392-32ec-11e5-83f6-b66290db80d4.png)

**Comment by hrydgard** [comment] 2015-07-25 15:31
That looks really weird, but good that it's the same. We do have some minor pixel positioning issues even when using real fonts, I think, but that doesn't seem to be the issue here as it's just as weird on the real hardware. What were they thinking?

**Comment by unknownbrackets** [comment] 2015-07-25 16:31
It looks like they're scaling taller letters wrong.  Bleh.

I think that sceFont supports subpixel offsets for drawing and we don't currently.

-[Unknown]

**Comment by GamerzHell9137** [comment] 2015-07-25 18:49
The PSP and PPSSPP font doesn't look the same. The L and I's look thinner than other letters.

**Comment by ppmeis** [comment] 2015-07-25 18:52
@GamerzHell9137 that's because ppsspp includes open source fonts, that's why is different than original PSP. The only way to look properly is dumping font folder from a real PSP and place them into flash0/font folder under PPSSPP.

**Comment by unknownbrackets** [comment] 2015-12-30 18:57
I'm leaving this open per the subpixel handling discussion, although I'm not certain how important it is, and it doesn't really look to be having an effect here.

Note that this issue's comments generally are a duplicate of #2788.  Maybe it'd be better to create a brand new issue for the subpixel rendering.

-[Unknown]

**Closed** 2016-01-23 23:58 UTC
