### ISSUE TITLE
Nexus 5 4.4.4 / AdHoc - Socket error 13 when connect adhocserver on local/remote 

### ISSUE THREAD

**Issue by hacker-lc** [hrydgard/ppsspp#7528] opened 2015-02-27 01:49 UTC
Device : Nexus 5 - 4.4.4
ppsspp version : Play store 1.0 / ppsspp-v1.0.1-24-g2cdb5a3-android
Game : Patapon 3
Error msg : HLE/sceNetAdhoc.cpp:313 Socket error (13) when binding port 555

Logcat with local/intranet adhocserver:
>400							10:25:616 user_main    I[NET]: HLE/proAdhocServer.cpp:134 AdhocServer: New Connection from 192.168.0.120
>401							10:25:616 user_main    I[NET]: HLE/proAdhocServer.cpp:1001 AdhocServer: Added Unknown Product ID UCAS40318 to Database
>402							10:25:616 user_main    I[NET]: HLE/proAdhocServer.cpp:221 AdhocServer: PPSSPP (MAC: FF:B4:B8:70:FA:9E - IP: 192.168.0.120) started playing UCAS40318
>403							10:25:616 user_main    I[NET]: HLE/proAdhoc.cpp:1003 FriendFinder: Begin of Friend Finder Thread
>404	02-27	09:10:25.608	0ms	W	NativeApp	21733	10:25:617 user_main    W[NET]: HLE/sceNetAdhoc.cpp:1017 UNTESTED sceNetAdhocctlAddHandler(89584c8, 8d3ec40): added handler 0
>405	02-27	09:10:25.608	0ms	I	NativeApp	21733	10:25:618 user_main    I[UTIL]: HLE/sceUtility.cpp:405 00000000=sceUtilityNetconfInitStart(08d3e374)
>406	02-27	09:10:25.628	20ms	I	NativeApp	21733	10:25:641 user_main    I[NET]: HLE/sceNetAdhoc.cpp:1298 sceNetAdhocctlCreate(LABOMAT) at 0886c0f0...
>407							10:25:641 user_main    I[NET]: HLE/proAdhocServer.cpp:488 AdhocServer: PPSSPP (MAC: FF:B4:B8:70:FA:9E - IP: 192.168.0.120) joined UCAS40318 group LABOMAT
>408							10:25:642 user_main    I[NET]: HLE/proAdhoc.cpp:1048 Received 7 Bytes of Data from Adhoc Server
>409							10:25:642 user_main    I[NET]: HLE/proAdhoc.cpp:1055 FriendFinder: Incoming OPCODE_CONNECT_BSSID
>410	02-27	09:10:25.628	0ms	E	NativeApp	21733	10:25:643 user_main    E[UTIL]: HLE/sceUtility.cpp:425 UNIMPL 00000000=sceUtilityNetconfUpdate(2)
>411	02-27	09:10:25.748	120ms	W	NativeApp	21733	10:25:759 user_main    W[NET]: HLE/sceNetAdhoc.cpp:2553 sceNetAdhocMatchingInit(32768) at 089be79c
>412	02-27	09:10:26.818	1070ms	W	NativeApp	21733	10:26:832 user_main    W[NET]: HLE/sceNetAdhoc.cpp:2591 sceNetAdhocMatchingCreate(mode=1, maxnum=4, port=555, rxbuflen=6144, hello=500000, keepalive=2000000, initcount=20, rexmt=500000, callbackAddr=089bc788) at 089bb25c
>413	02-27	09:10:26.818	0ms	I	NativeApp	21733	10:26:832 user_main    I[NET]: HLE/sceNetAdhoc.cpp:228 sceNetAdhocPdpCreate(ÿ晴púuu, 555, 6144, 0) at 089bb25c
>414	02-27	09:10:26.818	0ms	E	NativeApp	21733	10:26:832 user_main    E[NET]: HLE/sceNetAdhoc.cpp:313 Socket error (13) when binding port 555

**Comment by hacker-lc** [comment] 2015-02-27 02:42
"Permission error" should be caused by port number below 1024.

>Yes. Unless Google have changed it. From the ip man page: "The port numbers below 1024 are called reserved ports. Only privileged processes (i.e., those having the CAP_NET_BIND_SERVICE capability) may bind(2) to these sockets."

https://groups.google.com/forum/#!topic/android-ndk/H4RHw53fhgY

**Comment by unknownbrackets** [comment] 2015-02-27 02:49
Yes, this is a duplicate of #7247.  We should not allow games to use privileged ports.

-[Unknown]

**Closed by unknownbrackets** 2015-02-27 02:49 UTC
