### ISSUE TITLE
[Windows][Invalid Memory Access (Break)]GOD EATER & GOD EATER BURST (ULJS00237)(NPJH50352)(ULJS00350)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13527] opened 2020-10-10 09:33 UTC
### What happens?
Turn off "Ignore Invalid Memory Access Error" check box.
These games start,
BANDAI&namco logos appeared and screenshot appear and stop.

And,Not response any key exept "Fast Fowarding Key".
If you click "Fast Fowarding Key" then the intro movie starting.

Ofcourse, If turn on the "Ignore Invalid Memory Access Error" chekc box then error screen is not appear.

### What *should* happen?
Work correctly.(Don't show the error screen.)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver.：1.10.3-876
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

![GODEATER Seriese_InvalidMemoryAccess](https://user-images.githubusercontent.com/48179091/95651686-0296cf00-0b27-11eb-9e3c-b686b55ed82d.png)

**Comment by ANR2ME** [comment] 2020-10-10 21:24
I always wondered, does PSP game developers often use `try..catch` to handle exception and prevent crashing the game? 
because there are programmers who likes or have a habit to catching exception instead of properly check the validity upon using a variable.

**Comment by nassau-tk** [comment] 2020-10-11 00:59
I got some logs.
And,It has some red code.
So,I will report it.

**Timing of Invalid Memory Access Error.** 
![GODEATER_01](https://user-images.githubusercontent.com/48179091/95667670-264c2a80-0ba4-11eb-9228-42511310d518.png)

**Timing of intro movie skipping.** 
![GODEATER_02](https://user-images.githubusercontent.com/48179091/95667715-b0948e80-0ba4-11eb-9930-3c1374bb5210.png)

**Timing of any case...(Title/Load/etc...).** 
![GODEATER_03](https://user-images.githubusercontent.com/48179091/95667691-6a3f2f80-0ba4-11eb-97df-ed0a115fd42d.png)

**Timing of open the PPSSPP menu and stay hold it. (Press ESC key)** 
"This wasn't a red cord, but while the menu of PPSSPP was opened, it kept increasing, so I was interested."
![GODEATER_05](https://user-images.githubusercontent.com/48179091/95667723-d0c44d80-0ba4-11eb-9b89-18c121612c00.png)

@ANR2ME 
I'm sorry,I don't know about any programmers mind.
Because,I'm just a amature.
But,I know only one thing.
"Japanese like elaborate work..":laughing:
It's Good? or bad? "I don't know!!". :stuck_out_tongue_closed_eyes:

**Comment by nassau-tk** [comment] 2020-10-11 01:33
@hrydgard 

And,Invalid Memory Access Error's last line of text is overlap on before line.

**Comment by ANR2ME** [comment] 2020-10-11 05:07
That FriendFinder sending PING to AdhocServer is normal, it's to prevent it from getting kicked out by Adhoc Server due to timeout while pausing the game (ie. going to PPSSPP settings), because if it get's kicked out that player will no longer be in any group and can't progress anymore.

**Comment by nassau-tk** [comment] 2020-10-11 13:03
@ANR2ME 

OK! i understood the PING.

And,No. Not happen any error dialog.

**Comment by hrydgard** [comment] 2020-10-14 21:47
This error is not actually an invalid memory access, it's the game triggering a software breakpoint as a result of an assert that it hits. This is a long standing issue with this game, and ignoring it works, for whatever reason, so I guess nobody has felt motivated enough to dig into it...

Currently there's no neat UI to resume after this type of breakpoint except to press unthrottle or use the debugger, this will be fixed though. I've take care of the ugly overwrite that you can see in the screenshots above, at least.

**Comment by ANR2ME** [comment] 2020-10-15 07:36
How does a real PSP responds to assert? are they ignoring it too?

**Comment by hrydgard** [comment] 2020-10-15 07:58
I'm not 100% sure but I think it'll probably crash. Something is making the game feel uncomfortable, but nobody has figured out what since if you ignore the break the game runs anyway...

**Comment by sum2012** [comment] 2020-12-22 14:07
GOD EATER
v1.10.3-1375-g52c6169a5-windows-amd64 media log
https://gist.github.com/sum2012/ec213b7141b0fa08f6ae1a206faa92c7

**Comment by sum2012** [comment] 2020-12-22 22:48
Please help to test any regression of video.Thanks
windows 64 bit modify build 1
https://drive.google.com/file/d/1YamV2gBdOSZWHFSrFxda2HmdCa87FcBM/view?usp=sharing

**Comment by nassau-tk** [comment] 2020-12-23 07:41
@sum2012 
I tested on GOD EATER & GOD EATER BURST.

Result : [Break] is not happen.

**Comment by sum2012** [comment] 2020-12-23 07:48
Can you help to test OTHER game have any regression in vudeo?Thanks

在 2020年12月23日週三 下午3:42，nassau-tk <notifications@github.com> 寫道：

**Comment by nassau-tk** [comment] 2020-12-23 08:02
If can I do it then I wish help you.
But,I have a problem.
It's a ...."What is regression in video?"
Regression...?

Can I have directions in detail?

**Comment by sum2012** [comment] 2020-12-23 09:11
Something like black screen，video disappear

在 2020年12月23日週三 下午4:02，nassau-tk <notifications@github.com> 寫道：

**Comment by nassau-tk** [comment] 2020-12-23 09:21
Um...
I don't know those video.
But, I will try check some game's movie scene.

**Comment by hrydgard** [comment] 2020-12-23 10:23
The word "Regression" just means that something that worked before, no longer works.

**Comment by nassau-tk** [comment] 2020-12-23 13:11
Oh!!
Thank you!!
(My English level is so low.Sorry! :sweat_smile:)

And, I didn't find those issue  exept these games(GE) since v1.10.3-876.

Maybe, Not related below.
Please see for reference.
#12768 not solved. (Type:Freeze in game movie scene)
#11060 not solved. (Type:Freeze in game movie scene)
(Intro is OK.)

These games has not problem. (Intro movie.)
- Monster Hunter series (P/P2/P2G/3rd)
- Final Fantasy series (1/2/3/4)
- Assassin's Creed : Bloodlines
- JEANNE D'ARC
-  Danball Senki /Danball Senki Boost
- ARMORED CORE series
- Everybody Golf 1&2
- Everybody Tennis
- Everybody Stress Buster
- ProYakyu Spirits series
- GUNDAM Battle Tactics
- GUNDAM ASSAULT Survive
- GUNDAM BATTLE Chronicle
- GUNDAM BATTLE Universe
- GUNDAM BATTLE Royale
- GRAN TURISMO

**Comment by sum2012** [comment] 2020-12-23 13:23
Thanks @nassau-tk

**Comment by nassau-tk** [comment] 2020-12-23 14:39
These games has not problem. (Intro movie.)

- EXIT / EXIT2 (Kangaeru EXIT)
- KidouSenshi GUNDAM vs GUNDAM / KidouSenshi GUNDAM vs GUNDAM NEXT PLUS
- Musou OROCHI / Musou OROCHI MaouSairin / Musou OROCHI2 Special
- Toukiden / Toukiden Kiwami
- Tekken 6

**Closed** 2020-12-26 16:44 UTC
