### ISSUE TITLE
Linux users test this version - (This is not a issue)

### ISSUE THREAD

**Issue by inukaze** [hrydgard/ppsspp#13018] opened 2020-06-10 20:16 UTC
Hi there i had compile the git version for GNU/Linux using Slackware 14.2 for architectures of 32 Bits & 64 Bits. 

I just want the interest people test this build : 
https://www.mediafire.com/file/3wduzagp4ck988x/Inukaze-PPSSPP-v1.9.3.7z/file

Because some days ago i download the latest version for Linux, i notice the version was 1.7.X, and i can't use Mouse. and when i compile yesterday, yes support mouse native and works very fine.

When you download just use the script called "PPSSPP.geb" (should be executable) and the emulator start (well that is the idea) if ask for libs, just search libs for Slackware 14.2 (not current branch)

**Comment by inukaze** [comment] 2020-06-10 23:39
> SDL analog mouse was added in #12612, as such it will not be available on "main" build until v1.10, while the lastest version on ppsspp.org is really outdated most distro should have PPSSPP in the repo (v1.9.4 ATM tho').
> 
> I don't think this should be here, although it's probably worth noting that the linux download on main site should be updated with a newer version or just suggest to use the distro packet manager to get an updated version.

In the main site, if you go to [Linux Build downloads](https://build.ppsspp.org/?page/downloads#linux) and download Working ([64 Bits](https://build.ppsspp.org/builds/Linux/amd64/ppssppbuildbot-org.ppsspp.ppsspp-dev-working-linux-amd64.zip) or [32 Bits](https://build.ppsspp.org/builds/Linux/i386/ppssppbuildbot-org.ppsspp.ppsspp-dev-working-linux-i386.zip)) & Lastest ([64 Bits](https://build.ppsspp.org/builds/Linux/amd64/ppssppbuildbot-org.ppsspp.ppsspp-dev-latest-linux-amd64.zip) or [32 Bits](https://build.ppsspp.org/builds/Linux/i386/ppssppbuildbot-org.ppsspp.ppsspp-dev-latest-linux-i386.zip)) are the same version "v1.7.5-403-g128c0ad" and not have Mouse Support yet

Working Version :
![pspworking](https://user-images.githubusercontent.com/1647332/84328680-a445e980-ab50-11ea-8283-a65deb68b3d3.png)

Latest version :
![pspworking](https://user-images.githubusercontent.com/1647332/84328801-06065380-ab51-11ea-9c03-53224643cda0.png)

And the version compile by me : 
![inu-ppsspp](https://user-images.githubusercontent.com/1647332/84328874-30581100-ab51-11ea-9c80-b773374dd89e.png)

PPSSPP not exist on every repo of each distribution, for Slackware repo you can use the "sbo" repo, but that is download the source code and compile.

I share this for the Linux users want to try a more update version well if work on the distro that person try, i include some libs for solve dependencies. works in a varity of case, my telegram group test works on the follow distros : 

Slackware 14.2
Devuan Ascii -> i had test too, and yes really works.
Ubuntu 16.04 -> i try in a Live USB and works too
Debian Jessie
Manjaro
ArtixLinux -> i try in a Live USB and works too
GoboLinux -> i try in a Live USB and works too
Deepin
MX Linux
etc . . .

and well that in the users of telegram of my group, share with me.

**Comment by unknownbrackets** [comment] 2020-07-02 06:42
I think it's good to provide more builds, but we should keep things centralized.  I'm going to close this as a duplicate of #11889.

-[Unknown]

**Closed by unknownbrackets** 2020-07-02 06:42 UTC
