### ISSUE TITLE
Playable video ICON

### ISSUE THREAD

**Issue by Nugss** [hrydgard/ppsspp#15448] opened 2022-03-16 07:16 UTC
### What should happen

I don't know where to post it and I know it's not the priority now but, it's good to see this little feature just like on real PSP.

### Who would this benefit

I don't think if someone likes it or notice it, but for me it's good to see this kind of detail.

### Games this would be useful in

All psp games

### Other emulators or software with a similar feature

None.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Panderner** [comment] 2022-03-16 11:26
Duplicate of #2585

**Closed** 2022-03-16 12:23 UTC
