### ISSUE TITLE
Stays unresponsive sometimes in iOS. Only hard resets helps.

### ISSUE THREAD

**Issue by MHX792** [hrydgard/ppsspp#10704] opened 2018-03-11 11:49 UTC
Sometimes when I open ppsspp it shows the last cached screen of a game or a menu. Killing it from the app switcher doesn't help. When I reopen it the same cached screen appears and nothing happens. Only a regular restart helps in this case.

Other times it won't let me out anymore. (Double) Pressing the homebutton doesn't do anything. It can't escape the cached screen. In this case only a hard reset helps.

Hardware: 8 Plus with latest iOS 11.x.

Edit: I think I can reproduce it. While a game runs (Tekken 6 in my case) double clicking the homebutton and closing ppsspp from the appswitcher causes the above behaviour.

**Comment by unknownbrackets** [comment] 2018-03-11 19:59
If you always exit with Exit in the menu, it won't happen.  I think this may be a duplicate of another issue but can't find it just now.

-[Unknown]

**Comment by MHX792** [comment] 2018-03-11 20:12
Yea the thing is it is quite unusual to have an exit button in iOS apps. It's quite a bit inconvient to have to think about pressing the exit button in the iOS world.

**Comment by unknownbrackets** [comment] 2018-03-11 22:18
It's a bug, but apparently fixing it means not having jit.  So it can be slow and quit like other iOS apps, or fast and quit the annoying way right now.  Another option hasn't been found yet.

That's the problem with using an operating system that has a policy against apps like PPSSPP.

-[Unknown]

**Comment by MHX792** [comment] 2018-03-12 15:32
Why is that? Can you provide me with a link to more information?

**Comment by unknownbrackets** [comment] 2018-03-14 04:38
Here: #9186 (see the most recent comment.)  Which is actually the duplicate I was looking for.

Closing this as a duplicate of #9186.

-[Unknown]

**Closed by unknownbrackets** 2018-03-14 04:38 UTC
Labels: Platform-specific (iOS)
