### ISSUE TITLE
Crashes on spider man 3

### ISSUE THREAD

**Issue by Tarpehg** [hrydgard/ppsspp#18353] opened 2023-10-13 07:38 UTC
### Game or games this happens in

Spider Man 3

### What area of the game / PPSSPP

Beginning of the game and the next part of the beginning 

### What should happen

It should keep going 

### Platform

Android

### Mobile phone model or graphics card

Samsung galaxy tab s8

### PPSSPP version affected

Current 

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2023-10-13 11:35
Btw, are you using save state? 
if you are, try not loading it from save state, because i also got blue screen recently after loading an old save state on another game (Crazy Taxi 2) using the latest dev build (didn't have the time to try more builds yet, but it seems pretty recent)

**Comment by Tarpehg** [comment] 2023-10-13 13:44
> Btw, are you using save state? if you are, try not loading it from save state, because i also got blue screen recently after loading an old save state on another game (Crazy Taxi 2) using the latest dev build (didn't have the time to try more builds yet, but it seems pretty recent, loading from a new save state works fine tho)

I'm on android and I'm not using a save state

**Comment by Saramagrean** [comment] 2023-10-13 22:43
Similar?
https://github.com/hrydgard/ppsspp/issues/15825

**Comment by hrydgard** [comment] 2024-09-25 21:31
Closing this as duplicate of #15825

**Closed by hrydgard** 2024-09-25 21:31 UTC
