### ISSUE TITLE
Can't save in Persona 1

### ISSUE THREAD

**Issue by PersonaFutile** [hrydgard/ppsspp#11517] opened 2018-11-01 18:38 UTC
### What happens?
Attempting to save at the potted plant(or presumably elsewhere) causes the game to endlessly try to write to every single memory address(see picture below, note that it started from the very first address and the screenshot was taken several minutes in), fail each time, and continue to cycle through them until presumably it runs out of addresses to access. It should be noted that this also seems to occur if you try to load a save.

![image](https://user-images.githubusercontent.com/32741904/47871640-fb1b0700-dde2-11e8-8430-755f9976ee36.png)

### What *should* happen?
You should be able to save the game.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Intel Core i7 7700HQ, NVIDIA GTX 1070
Windows 10
v.1.7.1

**Comment by unknownbrackets** [comment] 2018-11-02 03:41
Not able to reproduce with ppsspp v1.7.1 and a US region version of the game.  Tried with a pre-existing save, and also tried with a brand new SAVEDATA directory, started a new game, saved, and then loaded that save.  Zero invalid memory accesses.

Probably either a bad disc, some sort of libretro issue, or a corrupt save data causing the game to break when creating/loading other saves.

Does the same save data load properly on a real PSP?  Have you tried using PPSSPP itself, not libretro?

-[Unknown]

**Comment by PersonaFutile** [comment] 2018-11-02 16:07
I used a US region as well. I don't currently own a PSP(although I used to) so I can't answer if it works on one. Using the normal PPSSPP, it works perfect. My primary reason for using Libretro is so that I can use the CRT-Royale shader.

**Comment by unknownbrackets** [comment] 2020-03-08 20:10
I think there have been attempts to update the port of PPSSPP used in libretro to work better.  Is this still an issue?

-[Unknown]

**Comment by Panderner** [comment] 2020-04-06 11:04
Saving is now working in Latest Libretro build

**Comment by hrydgard** [comment] 2020-04-06 11:23
Okay, I'm gonna close this then.

**Closed by hrydgard** 2020-04-06 11:23 UTC
Labels: Libretro, No Feedback / Outdated?
