### ISSUE TITLE
SYSTEM_SERVICE_EXCEPTION BSOD

### ISSUE THREAD

**Issue by Trigger215** [hrydgard/ppsspp#11640] opened 2018-12-06 03:51 UTC
### What happens?
When PPSSPP is started on the current Windows Insider build, the entire system crashes with a SYSTEM_SERVICE_EXCEPTION stopcode.

### What *should* happen?
The app should start up normally. Or... at all.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

HP 15-da0077 Laptop
Intel Core i5-8250U @ 1.60 GHz
Integrated graphics
8GB RAM
Win10 Home Insider ver 1809, build 18282.1000
PPSSPP 1.7.4

**Comment by unknownbrackets** [comment] 2018-12-06 04:07
This is a duplicate of #11603 - it seems to be a Windows OS bug with the insider preview.

-[Unknown]

**Closed by unknownbrackets** 2018-12-06 04:07 UTC
