### ISSUE TITLE
Maverick Hunter X not working.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8322] opened 2015-12-28 09:13 UTC
Using the latest dev version on android jellybean and that game wont start, it gets stuck in the accesing loading screen before the title screen.

**Comment by unknownbrackets** [comment] 2015-12-28 09:22
Closing as duplicate of #3318.  Please search first.

-[Unknown]

**Closed by unknownbrackets** 2015-12-28 09:22 UTC
