### ISSUE TITLE
PPSSPP crashes after booting Kingdom Hearts Birth by Sleep Final Mix.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#10941] opened 2018-04-20 08:57 UTC
What happens?
Using Vulkan ppsspp crashes after pressing circle in this screen:
![screenshot_20180420-035010](https://user-images.githubusercontent.com/6578180/39041571-a0735c2c-444e-11e8-9634-69b7e8bdde16.png)

What *should* happen?
Not crash

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Motog5 plus Android 7, latest ppsspp dev build, here is the log:
![screenshot_20180420-034534](https://user-images.githubusercontent.com/6578180/39041698-dc764a72-444e-11e8-9452-0741a08a3e2f.png)
![screenshot_20180420-034642](https://user-images.githubusercontent.com/6578180/39041751-ef180fd0-444e-11e8-8679-e98bafed074c.png)

**Comment by hrydgard** [comment] 2018-04-20 09:11
Nasty. I think this is gonna have to be a driver bug. Should ban this driver version from using Vulkan probably, can you get me the driver version info etc from the Settings/Tools/System Information screen?

**Comment by hrydgard** [comment] 2018-04-20 09:38
Huh okay, if so many games work well then blacklisting it does not seem appropriate. I wonder what Kingdom Hearts is doing so differently...

**Comment by MorrisonGamer** [comment] 2018-04-21 00:24
I recommend testing with the non-final mix versions, just to be sure it's not that specific version that causes it...And are you using a texture pack or no? Did you test a few different settings?

**Comment by unknownbrackets** [comment] 2018-04-21 06:08
Maybe this is related to #5800?

-[Unknown]

**Comment by marosis** [comment] 2018-04-21 18:10
Where Are you get that logcat of ppsspp?

**Comment by blackman91** [comment] 2018-04-21 19:58
I am using default settings, no texture packs, the log app is a logcat app from the playstore. OpenGL runs this game good too but I was reporting the bug, too see if anyone else had it.

**Comment by zminhquanz** [comment] 2018-06-06 14:49
@unknownbrackets @hrydgard i test kingdom heart again on Vulkan on 1.6.3 , it's work correctly , can you check it again , if it works , you can close this issue

**Comment by hrydgard** [comment] 2018-06-06 16:49
This is pretty clearly a duplicate of #10592 anyway, closing and leaving that open for checking.

**Closed by hrydgard** 2018-06-06 16:49 UTC
Labels: Vulkan
