### ISSUE TITLE
libretro: Crash on loading Dissidia 012 as a CSO

### ISSUE THREAD

**Issue by IngwiePhoenix** [hrydgard/ppsspp#14272] opened 2021-03-08 16:28 UTC
### What happens?
I recently compressed *all* my ISO images to CSO to save a bit of space on my HDD and reduce subsequent reads - with a little of dfragmentation, I am getting quite decemt performance out of this 10 year old HDD now ^^

However, this introduced a whole new problem... Now, I can not launch my games anymore! When doing so, Retroarch crashes. So, I used `retroarch_debug.exe` and made myself a crashdump.

### What *should* happen?
The game should launch.

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
OS: Windows 10
RetroArch: 1.9.0 (64bit)
PPSSPP core: v1.11.1-667-g409a2b5
GPU: NVIDIA 2080 TI FE
CPU: AMD R9 3900X
RAM: 4x8GB@3200MHz

### What I think...
Considering none of my CSOs is launching, my first thought would be that maybe CSO support is simply broken in the libretro core right now?

Here is the crashdump:
[crash-210308-171646.log](https://github.com/hrydgard/ppsspp/files/6102767/crash-210308-171646.log)

**Comment by unknownbrackets** [comment] 2021-03-08 23:40
I assume PPSSPP proper runs fine with the same files, right?

Is this #12841?  Otherwise it may be #12338.  The stack trace shows it's while doing something related to save states - it's probably not directly related to CSO or not.

Libretro/Retroarch was designed with emulation for older systems in mind.  Although the PSP is from 2004, it has a lot more RAM and threading capabilities than the NES.  Libretro doesn't really support multithreaded emulators and tries to force PPSSPP to handle save states at random times which might cause crashes or bugs.

In general, PPSSPP in libretro seems to be a largely unstable experience for reasons like that.  I'll note that some of the features (like run-ahead or rewind) weren't really designed thinking through systems that have 32+ MB of RAM (the PS1 only had 3MB), so they run poorly as well.

-[Unknown]

**Comment by IngwiePhoenix** [comment] 2021-03-09 12:43
> I assume PPSSPP proper runs fine with the same files, right?

Correct. Loading via PPSSPP (configured to point at the very same directories for memstick and games), the CSOs boot just fine.

> Is this #12841?

![image](https://user-images.githubusercontent.com/2893716/110469608-252f1300-80da-11eb-979c-d259ff33b234.png)
[crash-210309-132016.log](https://github.com/hrydgard/ppsspp/files/6108425/crash-210309-132016.log)
Disabling audio synchronization did cause RetroArch to hang - and when tabbing out and back in, it eventually crashed, producing this log.

> Otherwise it may be #12338.
`$RA_DIR/saves/PSP/PPSSPP_STATE` is empty, and there are no related savestates in `$RA_DIR/state`.

> like run-ahead or rewind
That gives me an idea. I'll see to turn off some of those features post-loading the PPSSPP core and see what happens.

...and wouldn't you know, it works. A core-specific settings file should do. In fact, all that I needed to run it, was:

`$RA_DIR/config/PPSSPP/PPSSPP.cfg`:
```
audio_sync = "false"
rewind_enable = "false"
```

But now, the game runs at some 700 FPS O.o... It feels as if it's completely uncapped somewhere, somewhat. Like, Fast-Forward is consistently on (which it really should not be).

Got any other ideas?

**Comment by IngwiePhoenix** [comment] 2021-03-09 12:54
Additionally:
```
> type .\retroarch-core-options.cfg | grep ppsspp
ppsspp_audio_latency = "low"
ppsspp_auto_frameskip = "disabled"
ppsspp_block_transfer_gpu = "enabled"
ppsspp_button_preference = "cross"
ppsspp_cheats = "enabled"
ppsspp_cpu_core = "jit"
ppsspp_fast_memory = "disabled"
ppsspp_frame_duplication = "disabled"
ppsspp_frameskip = "0"
ppsspp_frameskiptype = "0"
ppsspp_gpu_hardware_transform = "enabled"
ppsspp_internal_resolution = "1920x1088"
ppsspp_io_timing_method = "Fast"
ppsspp_language = "automatic"
ppsspp_locked_cpu_speed = "222MHz"
ppsspp_lower_resolution_for_effects = "off"
ppsspp_rendering_mode = "buffered"
ppsspp_separate_io_thread = "disabled"
ppsspp_texture_anisotropic_filtering = "16x"
ppsspp_texture_deposterize = "disabled"
ppsspp_texture_filtering = "auto"
ppsspp_texture_replacement = "disabled"
ppsspp_texture_scaling_level = "4"
ppsspp_texture_scaling_type = "xbrz"
ppsspp_unsafe_func_replacements = "enabled"
ppsspp_vertex_cache = "enabled"
```

**Comment by unknownbrackets** [comment] 2021-03-12 06:46
If you're not having performance issues, I suggest turning the vertex cache off.

Sounds like this is just related to the existing save state issues with how libretro works.  I'm going to close it as a duplicate then.

-[Unknown]

**Closed by unknownbrackets** 2021-03-12 06:46 UTC
Labels: Libretro
