### ISSUE TITLE
Ghostbusters Glitchy Graphics

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7332] opened 2015-01-15 18:30 UTC
The game has some weir graphics issues so i've done the usual things with ge debugger.

http://puu.sh/eyHdp/144eff384c.png
http://puu.sh/eyI3z/7a168192dd.txt
Something wrong with the font?

**Comment by GamerzHell9137** [comment] 2015-01-15 18:33
And there are more stuff like that

http://puu.sh/eyHXP/31906356d1.png

**Comment by daniel229** [comment] 2015-01-16 01:45
duplicate of https://github.com/hrydgard/ppsspp/issues/3041

**Closed** 2015-01-16 02:07 UTC
