### ISSUE TITLE
Tekken 6 Inconsistent Speed

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10765] opened 2018-03-22 13:21 UTC
What happens?
When Im playing tekken, at first it is so fast and smooth but after many battles, it became choppy and slow.

What *should* happen?
Consistent Speed during gameplay and multiple fights.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Galaxy S5
Adreno 330
Snapdragon 801
Android 6.0.1
2GB RAM

**Comment by LunaMoo** [comment] 2018-03-22 13:53
Low profile devices aren't designed to run at max speed for longer time, they physically can't sustain it and will throttle to avoid damage and/or to conserve battery power. It's maintained by operating system and PPSSPP has nothing to do about it. Also it's not true that game should run same way from start to finish consistently, every stage, character or even move of a character will require different amount of power from your hardware.

 If I recall Tekken should be a 60fps game, so I would recommend using frameskipping to play on mobile devices.
 Either way slowdowns as described here while running demanding applications are intentionally caused by operating system and PPSSPP has nothing to do about them, as such I'm closing this.

**Closed by LunaMoo** 2018-03-22 13:53 UTC

**Comment by hrydgard** [comment] 2018-03-22 14:12
Yeah, this is power throttling. You'll probably notice the device gets hot, and that causes it to reduce its speed. The only thing we can do is keep optimizing the code until it runs fast enough even at the lower frequency, and that might not be realistic.
