### ISSUE TITLE
Quake 2  by CROW_BAR: distorted music issues

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#6842] opened 2014-09-05 18:55 UTC
<b><strike>1. Lag / long start-up problem</strike></b>
The lag problem is completely gone. Tested v1.8.0-132-g c82d75c66
<b>2. Music distortion</b> 
There is a music playback issue as well. It is distorted so badly that it doesn't worth adding the music files. According to the log it keeps attempting to resample the music tracks to 44100Hz although I have the music in that sample rate.

Video showing both issues:
https://www.youtube.com/watch?v=me868bf5mHk
i got the second demo to load right at the video start.
Log screenshot showing music resampling attempts:
![quake2](https://cloud.githubusercontent.com/assets/1138235/4169713/669700da-352a-11e4-9ad2-a5cf122890a5.png)

**Comment by LunaMoo** [comment] 2017-05-24 07:02
Blah, didn't noticed that earlier, but that's probably another homebrew using same time functions, so at least half of this issue(lag part) should be fixed by #9716.
 Can't find a working download to even test this:].

**Comment by LunaMoo** [comment] 2017-05-24 16:24
Updated title to reflect what's left, the game is actually completely broken now, but with #9721 it'll work again and the "lag" was fixed yesterday, quite playable althrough default control mapping feels weird / hard to get used to:P.

**Comment by hrydgard** [comment] 2017-05-24 16:35
Got any good download links to the port BTW? Would be cool to put on the homebrew store with just the demo levels. Though perhaps it'd be a bit too big.

**Comment by LunaMoo** [comment] 2017-05-24 16:43
Unfortunately the only download I found myself potentially was a shady one ~ from description of some youtube video;] as while I was copying my own files into it, I had lots of questions to replace existing files, including one big pak file, that matched size from the full game.:]

 I could strip it off those things and upload myself, but honestly not sure which files are copyrighted there and which aren't, the copy I got didn't really came with clear instructions:|.

**Comment by LunaMoo** [comment] 2017-05-24 17:29
Ok I'm uploading it here as a jpg:
![q2 psp homebrew](https://cloud.githubusercontent.com/assets/5485237/26416454/3499a020-40b6-11e7-9247-eae33f45178e.jpg)
rename to 7z:].
 Please remove if you find anything that might be copyrighted, but I think I removed everything I could find in my full game, surely there are no pak files now, hopefully only homebrew files are there.

To note - files which I found in original game and removed from this, starting from those stored in same directory in full game:
QuakeII\baseq2\gamex86.dll
QuakeII\baseq2\maps.lst
QuakeII\baseq2\pak0.pak
QuakeII\baseq2\pak1.pak
QuakeII\baseq2\pak2.pak
whole QuakeII\baseq2\players folder

files inside QuakeII\baseq2\crbot:
pak0.pak  (in the full game I found it in Quake II\ctf)
and those which were just copies of QuakeII\baseq2 files:
MAPS.LST
GAMEX86.DLL

Stuff I figured out to do optionally:
 - QuakeII\baseq2\video folder might be copied as well(seems to work),
 - music converted to mp3 named from Track02 to Track21(full game from GOG includes ogg) can be placed into QuakeII\MP3, but it's currently buggy and will just start over a tiny loop resulting in noise:].

 This homebrew also seeks more PAK files inside "baseq2", but GOG version of the full game stores everything in separate folders starting from pak0.pak in every of them and I'm not sure which to rename to which if any order is even needed:].

**Comment by hrydgard** [comment] 2017-05-24 18:17
Alright, cool. Seems a tiny bit scary though. I might have a look when I find some time :)

**Comment by LunaMoo** [comment] 2019-04-25 01:51
Slight update, with #11993 it now spams:
````
45:50:161 mp3decode_th I[ME]: hle\scemp3.cpp:494 sceMp3SetLoopNum(00000000, 0)
45:50:470 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Opn: ./baseq2/pak0.pak w_i: 2
45:50:471 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: ICl: ./baseq2/pak0.pak w_i: 2
45:50:566 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Opn: ./baseq2/pak0.pak w_i: 2
45:50:568 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: ICl: ./baseq2/pak0.pak w_i: 2
45:50:977 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_end_play
45:50:977 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: Clear res
45:50:978 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_start_play(./MP3/Track08.mp3) @ 0
45:50:978 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: seek 0: 0/2981792
45:50:978 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Playing ./MP3/Track08.mp3
45:50:979 mp3decode_th I[ME]: hle\scemp3.cpp:494 sceMp3SetLoopNum(00000000, 0)
45:50:989 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Opn: ./baseq2/pak0.pak w_i: 2
45:50:994 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: ICl: ./baseq2/pak0.pak w_i: 2
45:51:782 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_end_play
45:51:782 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: Clear res
45:51:795 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_start_play(./MP3/Track08.mp3) @ 0
45:51:795 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: seek 0: 0/2981792
45:51:795 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Playing ./MP3/Track08.mp3
45:51:796 mp3decode_th I[ME]: hle\scemp3.cpp:494 sceMp3SetLoopNum(00000000, 0)
45:52:190 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Opn: ./baseq2/pak0.pak w_i: 2
45:52:194 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: ICl: ./baseq2/pak0.pak w_i: 2
45:52:600 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_end_play
45:52:600 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: Clear res
45:52:603 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_start_play(./MP3/Track08.mp3) @ 0
45:52:604 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: seek 0: 0/2981792
45:52:604 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Playing ./MP3/Track08.mp3
45:52:604 mp3decode_th I[ME]: hle\scemp3.cpp:494 sceMp3SetLoopNum(00000000, 0)
45:52:792 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Opn: ./baseq2/pak0.pak w_i: 2
45:52:796 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: ICl: ./baseq2/pak0.pak w_i: 2
45:53:416 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_end_play
45:53:416 mp3decode_th I[SCEIO]: hle\sceio.cpp:1031 stdout: Clear res
45:53:420 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: mp3_start_play(./MP3/Track08.mp3) @ 0
45:53:420 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: seek 0: 0/2981792
45:53:421 user_main    I[SCEIO]: hle\sceio.cpp:1031 stdout: Playing ./MP3/Track08.mp3
45:53:421 mp3decode_th I[ME]: hle\scemp3.cpp:494 sceMp3SetLoopNum(00000000, 0)
````

Using 44100mhz, 128kbps stereo mp3's(which seems to work best without any warnings), it basically starts playing an mp3 and ends instantly ~ repeats without end.

**Comment by unknownbrackets** [comment] 2019-04-25 02:06
Does it work in Jpcsp?  I took a quick look at its buffer handling to get an idea of what to test, and noticed some areas where it's probably wrong - but in a different way than PPSSPP is wrong.

What PPSSPP does is:

1. Ask the game to fill the buffer (minus workarea with that pull.)
2. Once a decode happens, ask the game to provide that additional packet.
3. Use the MP3 buffer as a place to read into a C++ managed buffer.

What Jpcsp does is:

1. Ask the game to fill half the buffer minus workarea.
2. Once a decode happens, ask the game to provide that additional packet (I think, from reading the code briefly.)
3. Unclear to me where the data is managed.

What PSP does is:

1. Ask the game to fill the buffer minus workarea.
2. When a decode happens, don't ask for more data until half the buffer has been used up.  Then ask for half.
3. Manage the data in the MP3 buffer (presumably just swapping halves and using the workarea to stitch together frames that cross boundaries.)

It's possible that Quake is getting confused because it's being asked to provide new data right away, which doesn't happen on a PSP.

-[Unknown]

**Comment by LunaMoo** [comment] 2019-04-25 02:58
Hoped I can live without Java on my pc;p, but heh ok I tried and indeed it works on jpcsp just fine, at least music, it has some other problems.

**Comment by LunaMoo** [comment] 2019-04-25 20:46
I found a demo of Quake II that can reproduce mp3 problem so I'm uploading it here:
[Quake 2 demo.zip](https://github.com/hrydgard/ppsspp/files/3118792/Quake.2.demo.zip)

 Place some mp3's into mp3 folder, they have to be named Track02.mp3 to Track21.mp3(Track02.mp3 should be enough to reproduce the problem). Run the homebrew press start and then X like two times to start a new game. It will spam some content missing making it almost impossible to see in-game the constant spam about re-starting mp3, but it can still be observed in the info log.

**Comment by pal1000** [comment] 2019-04-28 09:16
That demo version crashes almost always when starting game @LunaMoo

**Comment by LunaMoo** [comment] 2019-04-28 10:05
Disable fast memory, it's still useful to reproduce mp3 issue, but I guess the homebrew wasn't really ment for running anything else than full game so it has some problems when using content of the demo.

**Comment by unknownbrackets** [comment] 2019-04-28 16:50
Changing the ID3 handling helps (I think it may be safe to remove `ctx->EatSourceBuff(0x400);`), but I think this is actually related to sceAudioSRC*.

Commenting out `chans[PSP_AUDIO_CHANNEL_SRC].reset();` (which is probably NOT correct) makes the audio play at the right speed.  I suspect that maybe it should actually block the thread until the queue is drained or something.

-[Unknown]

**Closed** 2019-06-24 08:13 UTC
Labels: MP3
