### ISSUE TITLE
Not all buttons on the PSP are listed

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9298] opened 2017-02-11 08:11 UTC
Under the configuration, there are no buttons to set 'volume up', 'volume down', 'music symbol', 'home', 'display'.

These buttons are vital for people developing homebrew and the applications who do use them under kernel access. It is but a small improvement.

**Comment by LunaMoo** [comment] 2017-02-11 09:01
Closing as a duplicate of #6646

**Closed by LunaMoo** 2017-02-11 09:01 UTC
