### ISSUE TITLE
Small visual bug on Phantasy Star Portable 2/Infinity while playing windowed

### ISSUE THREAD

**Issue by fefo-dev** [hrydgard/ppsspp#13688] opened 2020-11-21 14:36 UTC
For some reason what seems to be part of a text box appears on the bottom right corner when opening the stash, or a shop menu if I remember corretly. Hard to notice on a picture, so check the video where I toogle between fullscreen/windowed:
https://files.catbox.moe/gxv17u.mkv
https://images2.imgbox.com/28/5d/gcdgGPYV_o.jpg

Happens consistently with all frontends and any scaling resolution. Been months since I first noticed it, but those tests are from 1.10.3-1221 which I'm currently using. Other info: Windows 18.09, i5 6300HQ and GTX 960M (452.06 driver, also updated).

PSP2 also does the same, due to a similar engine. I wouldn't be suprised if vanilla Portable does it too.
https://files.catbox.moe/3m8lp8.mkv
https://images2.imgbox.com/a9/f3/JWWIrk8N_o.jpg

I can attest that the english PSP2i version runs fine, but I found this quirk worth a report.

 Cheers.

**Comment by hrydgard** [comment] 2020-11-22 16:46
That is really weird! No idea what might be going on here, or how windowed mode might be involved, other than maybe being a smaller resolution.

**Comment by fefo-dev** [comment] 2020-11-22 17:14
Forgot to add to the main post but I also tried to jerk the window around, as it might've been some odd issue with integer scaling, but no change. Even on the minuscule x1 window you can see the blip there.

**Comment by unknownbrackets** [comment] 2021-02-19 05:04
Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by fefo-dev** [comment] 2021-02-19 15:38
There you go, with a savestate if that helps: [PSP2i.zip](https://github.com/hrydgard/ppsspp/files/6011067/PSP2i.zip)
Latest buildbot version (1.11.2-127) but I was in 1.10.3-1234 and it was the same.

**Comment by Gamemulatorer** [comment] 2022-12-09 00:24
Can you still reproduce this issue?
how about using the recently build PPSSPP?

**Comment by fefo-dev** [comment] 2022-12-09 02:01
Yes - tested on stable 1.13.2 on Windows and Android (used custom display layout to simulate a window).

On Windows 1.13.2-2369 however it also happens while fullscreen

**Comment by unknownbrackets** [comment] 2022-12-09 02:31
This happens on a PSP as well with this frame dump:
![#13688_NPJH50332_psp2i_dialog](https://user-images.githubusercontent.com/191233/206609279-78810ed8-0005-4713-80a1-fb33a2636b59.png)

At 490/611, we have finished the first couple dialogs and end up with something that looks like this:
![image](https://user-images.githubusercontent.com/191233/206609349-f232e5d0-d6eb-4a39-ab2d-efff5ff38622.png)

It then draws another dialog, which appears to be mostly offscreen.  At 497/611 and 498/611, it draws the top left which is what you see in the bottom right of the screen.  The coordinates are (468,271) - (524,277), which is why you see 1 pixel of it at 1x (the PSP screen is 272 tall.)

It actually spends a bunch of time drawing it, up through 545/611.  I think it draws multiple dialogs there - maybe they moved dialogs out that aren't active, and didn't offset them off enough.  If I force it on screen, it looks like this:

![image](https://user-images.githubusercontent.com/191233/206610391-6f1495d0-3346-457d-9576-3db5651eab81.png)

Anyway, it seems like this may just be a game bug that is more noticeable at a higher resolution (since you see more than a single pixel.)  That said, it's possible it's a CPU bug or similar - can we confirm if this shows up on an actual PSP in this same situation?

I assume the reason it's not showing in fullscreen is simply that, at full screen, we crop off the top and bottom few pixels to align with 1920x1080.  Then PSP's 480x272 is actually 1920x1088, so you don't see that bottom pixel at full screen.

-[Unknown]

**Comment by hrydgard** [comment] 2022-12-09 10:10
The fullscreen cropping would indeed explain why it's not noticable there, good point!

I think we can close this and assume it's a game bug.

**Closed by hrydgard** 2022-12-09 10:10 UTC
Labels: GE emulation
