### ISSUE TITLE
CCCR - Menu not rendering correctly.

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14546] opened 2021-06-19 23:01 UTC
### What happens?

In Capcom Classics Collection Reloaded (USA), the menu does not seem to be rendering or drawing correctly. Almost like it's artifacting / flickering (white block blobs).
![Screenshot_20210619-232744](https://user-images.githubusercontent.com/30265284/122657481-d4f53180-d15b-11eb-8c50-62301d385ac2.png)
![Screenshot_20210619-232756](https://user-images.githubusercontent.com/30265284/122657485-d9214f00-d15b-11eb-99bf-92571e8301b5.png)
![Screenshot_20210619-232805](https://user-images.githubusercontent.com/30265284/122657490-dc1c3f80-d15b-11eb-8164-f88c761ba0e1.png)
![Screenshot_20210619-232818](https://user-images.githubusercontent.com/30265284/122657492-e1798a00-d15b-11eb-8fc3-29a41733e1b0.png)

### What *should* happen?
Not sure tbh.

#### What hardware / device and operating system?
Pixel 4a. Android 11. StockOS.
#### What graphics card (GPU) or mobile phone model?
Adreno 618. Sunfish.
#### What PPSSPP version (standalone/official), and did it work before?
Tested on both 1.11.2-432 and 1.11.3-742. same issue. Unsure if it ever worked.
#### Which game or games?

ULUS10134
#### Graphics backend (Vulkan, OpenGL, etc.)?
 Vulkan.

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Try changing graphics settings to determine if one causes the bug.
 - [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-06-20 00:33
Duplicate of #13357

**Comment by unknownbrackets** [comment] 2021-06-20 01:09
This issue is being closed as a duplicate of #13357.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-06-20 01:09 UTC
