### ISSUE TITLE
FMVs not playing as intended. Potentially UWP specific

### ISSUE THREAD

**Issue by Player1LoginXBOX** [hrydgard/ppsspp#15983] opened 2022-09-07 11:47 UTC
### Game or games this happens in

The Warriors

### What area of the game / PPSSPP

The opening FMV of The Warriors was tested and does appear effected by this bug developer mode uwp.

The bug effects ALL FMVs from properly playing on an xbox platform.

GTA & Tony Hawk are a couple others which could be tested if the bug is fixed.

### What should happen

The FMVs should properly play no hitches and broken audio.

### Platform

UWP / Xbox

### Mobile phone model or graphics card

Series

### PPSSPP version affected

Newest

### Last working version

Unknown

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2022-11-07 10:02
This is not specific to neither UWP nor D3D11, it turns out.

Seems to be some weird timing error or buffering error in the mpeg playback, we know that stuff is problematic...

I'm gonna untag this for 1.14, but a bigger mpeg/atrac debugging effort is needed in the future, to fix how we buffer and so on.

**Comment by unknownbrackets** [comment] 2022-11-07 14:31
This issue is being closed as a duplicate of #8991.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-11-07 14:31 UTC
Labels: PSMF / MPEG

**Comment by Player1LoginXBOX** [comment] 2022-11-07 17:27
Thanks for info @hrydgard following #8991 seems to be a 5+ year old issue so I'll just watch for maybe any progress in the future. It doesn't effect any gameplay so that's a plus
