### ISSUE TITLE
Feature: Add UMD-Video-Game feature

### ISSUE THREAD

**Issue by sihunqu123** [hrydgard/ppsspp#11662] opened 2018-12-11 15:10 UTC
Hi dear PPSSPP-dev-team,

Thank you for offering such a nice PPSSPP. And could you add a UMD-Video-**Game** feature on PPSSPP?

Reason:

1. IMO, there are 3 types of PSP Games:
  1.1 Ordinary PSP game(e.g: `AKB1/149: Renai Sousenkyo`), which PPSSPP already supported perfectly.
  1.2 UMD-**Video**(e.g: `Miku no Hi 39′s Giving Day Project DIVA`), which is absoluty a video disk. And we are not interested in it neither.
  1.3 UMD-Video-**Game**(e.g: `Mihiro's Sexy Casino - Goldrush`), which is actually a game, though it is released as a UMD-Video-Game.
    
We really hope 1.3-type-feature could be added into PPSSPP, at least PPSSPP-gold.

2. I have checked the reasons why we should buy PPSSPP-gold, and none of them are attractive, except for the first reason(To support PPSSPP team's development), since the rest reasons are too abstract, people cannot find any powerful feature in PPSSPP-gold.
So, IMO, why not add 1.3-type-feature into PPSSPP-gold only?
As a result, people can still having fun in PPSSPP with 1.1-type-feature, while PPSSPP-gold is also comparable.

Please let me know if you need some type-1.3 game.
Please let me know if you need the list of type-1.3 game.

Note. the JCSP do can play UMD-Video, but cannot play UMD-Video-game.

Finally, feel free to edit/delete my issue cuz I am stupid, Thanks you.

**Comment by hrydgard** [comment] 2018-12-11 15:15
Gold is just there to support my work and maintenance of web sites etc. It's intentional that there are no substantial benefits - the app is open source so anyone can just make a build with whatever features they want anyway.

Now, as for video UMD, nobody seems to be interested enough in doing the work, so it's not likely to happen anytime soon unfortunately.

Closing as duplicate of #4902.

**Closed by hrydgard** 2018-12-11 15:15 UTC

**Comment by Panderner** [comment] 2020-05-05 07:23
@hrydgard how about UMD-PG Visual Novels?

**Comment by awsms** [comment] 2021-03-25 23:45
> @hrydgard how about UMD-PG Visual Novels?

This, a bunch of adult games were released as UMD-PG to avoid SONY's censorship.

**Comment by hrydgard** [comment] 2021-03-26 07:57
I don't even know what UMG-PG is

**Comment by unknownbrackets** [comment] 2021-03-28 21:48
I think it's like DVD menus, where there's a bit of "interactivity" to a video by navigating chapters.  Someone linked me to some JPCSP commit once about it, something like this code:
https://github.com/jpcsp/jpcsp/blob/d6c01b51a6dd51fbe216feede2c331f27b4e2a2f/src/jpcsp/format/rco/vsmx/interpreter/VSMXInterpreter.java#L693

My understanding is that you could write JavaScript / ECMAScript for videos and there was some bytecode compiler.  It's also used in PS3 dynamic themes.  It has nothing to do with anything games can use.

I assume anyone wanting this basic scripting to work also wants decent video player features too, so it would make a ton more sense to implement within a proper video player (unless someone is wanting to make VVIIDDEEOO indeed - which I'm by no means against someone creating a better free video player app for Android, especially without ads.)

-[Unknown]

**Comment by FMecha** [comment] 2022-09-15 18:41
For something that serves as an intermediate between UMD Video and a game-like UMDPG, there's [The Silent Hill Experience](https://www.youtube.com/watch?v=BFVY7gt7qWY)[, I guess.](https://silenthill.fandom.com/wiki/The_Silent_Hill_Experience) It runs in UMD-Video mode and has some menu interactivity for menus that lead to digital animated comics, music player (the songs can only be played from within it), and other videos (trailers, interviews, endings).
