### ISSUE TITLE
line in buffered render

### ISSUE THREAD

**Issue by daniellegal** [hrydgard/ppsspp#6634] opened 2014-07-26 00:59 UTC
during i play the emulator shows a line down in the screen while in buffered render
![npjh50686_00000](https://cloud.githubusercontent.com/assets/8229133/3709751/182252be-1460-11e4-8c04-0e2506410935.png)

**Comment by unknownbrackets** [comment] 2015-02-24 04:37
Does this happen with default settings?  Does it happen with default settings + render resolution at 1x PSP?

-[Unknown]

**Comment by daniel229** [comment] 2015-02-24 05:52
duplicate of https://github.com/hrydgard/ppsspp/issues/7470

**Closed** 2015-02-24 06:51 UTC
