### ISSUE TITLE
Keyboard still not appearing - 1.11

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#14097] opened 2021-02-09 16:59 UTC
### What happens?
Keyboard still won't appear after "fix" from previous issue,certain points like Ports for Ad-Hoc / Remote Disc Streaming / Controls sensitivity

### What *should* happen?
They should appear

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Honor 9S
OpenGL
Keyboard - GBoard

**Comment by hrydgard** [comment] 2021-02-09 17:31
Duplicate of #13716

**Closed by hrydgard** 2021-02-09 17:31 UTC
Labels: User Interface
