### ISSUE TITLE
Ghost in the Shell: Stand Alone Complex (ULES-00135) text rendering problem.

### ISSUE THREAD

**Issue by Silanda** [hrydgard/ppsspp#9614] opened 2017-04-14 18:55 UTC
I already posted this on the forum, but I'm making a bug report as I can't find any solution through the emulator settings of the latest Git build as of April 14th 2017. 

It's not a game breaking problem, but somewhat annoying. In-game subtitles can have up to three lines of text on screen at a time, however, only a maximum of two lines of text are being displayed in PPSSPP. Judging from the positions of lines that are displayed when subtitles are on-screen during missions (they appear within a frame graphic), the second and third lines are being rendered in the positions that should be for the first and second. The text of the first line is completely missing.

This occurs on all backends and also while using the software renderer. I've confirmed that it does not happen on actual hardware. This glitch is probably also present in the US release as well, though I don't have a legit copy of that to 100% confirm.

**Comment by unknownbrackets** [comment] 2017-04-14 20:53
Not sure but there's a good chance this is a duplicate of #2788.

-[Unknown]

**Comment by Silanda** [comment] 2017-04-14 21:38
Aha! Yes, I think you're right! After reading the comments on that issue, replacing PPSSPP's fonts with ones ripped from my PSP fixes the problem. Thank you.

**Comment by unknownbrackets** [comment] 2017-04-15 03:44
Okay, closing as a duplicate of #2788 then.

-[Unknown]

**Closed by unknownbrackets** 2017-04-15 03:44 UTC
