### ISSUE TITLE
Tekken 6 Graphic Bug - Legs of the characters are moving  

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#7456] opened 2015-02-08 08:41 UTC
The video shows pretty much everything.
I tried with every possible graphic option - No effect . 

http://youtu.be/j56z3Lizkyk

**Comment by Bigpet** [comment] 2015-02-08 08:42
duplicate of #5399

**Comment by AizerMortenort** [comment] 2015-02-08 08:49
Hmm a lot of time has passed since the report you mentioned and I see no progress at all. 
Well then I should accept I can't even make videos of tekken becuase of the graphical artifacts. 
Tekken 5 also has some graphical glitches.

**Comment by hrydgard** [comment] 2015-02-08 09:34
I've looked at it several times and not found any reason why the legs are shaking. Opening multiple issues is pointless.

**Closed by hrydgard** 2015-02-08 09:34 UTC

**Comment by Bigpet** [comment] 2015-02-08 09:44
@AizerMortenort if you're really really really patient you can try and trace and isolate all the calculations from reading the model vertex to issuing the draw call with the faulty positions.

That would make isolating the error easier (since it would make writing a test to compare the results of a real PSP easier) but it's incredibly tedious and would probably take days.

**Comment by hrydgard** [comment] 2015-02-08 11:56
I wonder if the game is doing some sort of inverse kinematics to place character feet on uneven ground - that type of calculation can be really sensitive to precision issues, and identities like asin(sin(x)) == x must hold, which may not be the case with various approximations...
