### ISSUE TITLE
Linear Filtering turns off by itself

### ISSUE THREAD

**Issue by ppmeis** [hrydgard/ppsspp#2843] opened 2013-07-19 12:09 UTC
During playing Dj Max series, I detect LF turns off by itself when there's any note on the gear, see pics:

LF off, gear empty:
![lfoff](https://f.cloud.github.com/assets/4381277/825549/cf23eff0-f06b-11e2-88e0-7c86cc17517e.png)

LF turns on when first note appears:
![lfon](https://f.cloud.github.com/assets/4381277/825552/dcfa6cd0-f06b-11e2-9559-09d99dff5505.png)

LF turned off again when the gear is empty again:
![lfoffagain](https://f.cloud.github.com/assets/4381277/825554/ecd0d4be-f06b-11e2-9e98-d21975957146.png)

It happens in all playing song.

**Comment by ppmeis** [comment] 2015-01-08 23:36
Tested with latest build. Now pink lines are almost gone when texture scaling is set to 5x xBRZ. Without texture scaling lines are visible like before.

Texture scaling on:
![ulks46050_00002](https://cloud.githubusercontent.com/assets/4381277/5673039/6464fe32-9797-11e4-810f-61235a627a3a.jpg)

Texture scaling off:
![ulks46050_00003](https://cloud.githubusercontent.com/assets/4381277/5673048/8e2531b0-9797-11e4-91c3-27122b02554a.jpg)

**Comment by unknownbrackets** [comment] 2017-05-14 18:47
As noted in #3468, this is only happening when using resolutions greater than 1x.  Linear filtering is bleeding pink in, because the actual pixels are surrounded with pink.  Texture scaling is able to workaround this and give more non-pink pixels to filter from.  Forcing nearest also resolves this, avoiding pink blending with other colors.

Basically this is a rendering technique that is just not very friendly to higher-resolution scaling.  The developer obviously wasn't very concerned with resolutions higher than the PSP was capable of when they implemented this.  It's likely alpha blending or something would've been used if they had.

As for the hardware testing - my mipmap testing confirmed that only the lowest bit of the magnify value is used.  Bias can cause it to use the minify value, but in no case are the higher bits of magnify used.

The best we can do here is force nearest when colortesting is enabled.  However, this makes people unhappy - #4202, #4192, #4217, #4405.

I'm going to close this.  I'd recommend using 1x rendering resolution, and possible an upscaling shader.

-[Unknown]

**Closed by unknownbrackets** 2017-05-14 18:47 UTC
