### ISSUE TITLE
Monster hunter portable 3rd issues :(

### ISSUE THREAD

**Issue by DivineKi** [hrydgard/ppsspp#12830] opened 2020-04-17 01:01 UTC
I've had this problem for a few days now and I've searched hard for a solution but I cant find anything. There was one guy who had this same issue as me 2 years ago, his post: https://github.com/hrydgard/ppsspp/issues/11410
From what I saw there wasn't a solution to his problem given, not one that was addressed at least, so I'm hoping that 2 years later the issue can be fixed for me and for anyone in the future who may have this issue.

### What happens?
Whenever I try to do any quest on the map "Plains Daylight" it crashes after it finishes loading when I set out on the quest. I tried the night time version of the map and it was totally fine, so its only day time. 
Here's a video which isn't mine but it shows the exact same issue that I'm having:
https://www.youtube.com/watch?v=wMMQw6eBaoQ&t=12s

### What *should* happen?
I should set out on the quest and be able to complete the quest without it crashing.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I'm using the HD English patched version of the game
Phone: Samsung Galaxy S7
PPSSPP version: v1.9.4
Operating System(Android Version): 8.0.0

**Comment by unknownbrackets** [comment] 2020-04-17 01:18
This issue is being closed as a duplicate of #11410.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-04-17 01:18 UTC

**Comment by Panderner** [comment] 2020-04-17 10:07
> This issue is being closed as a duplicate of #11410.
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

@unknownbrackets next time make sure you mark this duplicate. @hrydgard did this for mark as duplicate and 

> This issue is being closed as a duplicate of #11410.
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

Next Time @unknownbrackets mark this as a duplicate, @hrydgard did this and other repositories
![IMG_20200417_180653](https://user-images.githubusercontent.com/37503397/79558119-3e9c2a80-80d6-11ea-8e0e-c050ca82c098.jpg)

**Comment by hrydgard** [comment] 2020-04-17 10:13
Unknown did write "duplicate of" but Github didn't seem to do it's automatical thing like it does if you just write "Duplicate of #12726" in an issue. Maybe only works on its own line?

**Comment by Panderner** [comment] 2020-04-17 10:47
This is why I can't find any duplicate even the original one is fixed or closed
