### ISSUE TITLE
Crash on Linux when pressing the maximize to window button when launching a game 

### ISSUE THREAD

**Issue by nielsbbb** [hrydgard/ppsspp#16672] opened 2022-12-30 10:54 UTC
### Game or games this happens in

None when booting a game 

### What area of the game / PPSSPP

Hi

When I start PPSSPP and start Grand Theft Auto LCS ULES 00151. But the game doesn't really matter.
And I click to fast on the maximize button (screen adjustment button) Ppsspp crashes and the process needs to be terminated.

### What should happen

More support on Linux?

### Logs

It doesn't generate log even all settings are on.
I added a screenshot what happens.
![167239753826913588415063008150]
(https://user-images.githubusercontent.com/105968798/210062475-b9dc50d3-0e4f-4a65-a27a-f4ccd4bfe262.jpg)

### Platform

Linux / BSD

### Mobile phone model or graphics card

AMD RDNA 2 Steam Deck 

### PPSSPP version affected

1.14.1

### Last working version

I don't know 

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-12-30 16:40
Can you run it with lldb or gdb?  A stack trace would be helpful.

-[Unknown]

**Comment by nielsbbb** [comment] 2023-01-01 16:26
Hi

Can you explain in noob terms.
I don't really know what you mean.

Thanks

**Comment by unknownbrackets** [comment] 2023-01-07 19:54
See here: https://github.com/hrydgard/ppsspp/issues/14423#issuecomment-830672200

-[Unknown]

**Comment by hrydgard** [comment] 2023-03-28 10:02
I tried reproducing it on my linux laptop (don't have a Steam Deck) with no success. Bumping to next version.

**Comment by yann-boyer** [comment] 2023-11-12 18:42
It happens to me too, even when not launching a game.
Note : It doesn't happen on X11, only on Wayland.
It segfault when crashing and when closing the window segfault happens too.

**Comment by hrydgard** [comment] 2024-04-10 11:07
Still happens now?

**Comment by hrydgard** [comment] 2024-07-19 10:17
I'm gonna assume it's fixed, I can't reproduce anyway.

**Closed by hrydgard** 2024-07-19 10:17 UTC
Labels: Platform-specific (Linux/POSIX), Vulkan
