### ISSUE TITLE
Mhp3rd quest always closing

### ISSUE THREAD

**Issue by Dartfeld0** [hrydgard/ppsspp#12499] opened 2019-12-01 14:09 UTC
Can someone help me my ppsspp was always exiting when im doing a quest in mhp3rd "leading the charge" at the village girl

**Comment by Emulatorer** [comment] 2019-12-02 07:08
What's your platform Android or PC?
Are you using latest ppsspp github version
you didn't use cheat code

**Comment by Saramagrean** [comment] 2019-12-02 08:59
Similar https://github.com/hrydgard/ppsspp/issues/11410 ?

**Comment by DivineKi** [comment] 2020-04-28 17:55
It may be your backend rendering, if its OpenGL, try Vulkan

**Comment by Gamemulatorer** [comment] 2020-05-14 12:05
@hrydgard this is a duplicate of #11410

**Comment by hrydgard** [comment] 2020-05-14 12:48
Duplicate of #11410.

**Closed by hrydgard** 2020-05-14 12:48 UTC
Labels: No Feedback / Outdated?
