### ISSUE TITLE
GPD XD (original): Display resolution (HW scaler) causes crashes

### ISSUE THREAD

**Issue by radiocaravan** [hrydgard/ppsspp#11154] opened 2018-06-08 06:01 UTC
When I select a Display resolution other than the default (2x PSP), the app crashes instantly.

GPD XD (original), LegacyROM, PPSSPP Gold 1.6.3

**Comment by ChurroBoi** [comment] 2018-06-11 08:38
[gpd_xd_res-crash.txt](https://github.com/hrydgard/ppsspp/files/2089224/gpd_xd_res-crash.txt)
Here, I made a crash log.

**Comment by ChurroBoi** [comment] 2018-06-13 08:46
ALSO, if you aren't patient enough to wait for a fix you can go to the ppsspp.ini in the SYSTEM folder and set AndroidHwScale = 0 to make full resolution.

**Comment by radiocaravan** [comment] 2018-06-15 06:15
I made this change in the INI file... it worked great.  AND it also magically fixed the Manual Scaling issue.

**Comment by hrydgard** [comment] 2018-06-15 08:52
Good find. Yeah we should probably not default that to On, it causes too many issues....

**Comment by hrydgard** [comment] 2018-10-07 19:29
I'm gonna close this as a duplicate of #11063 because it's almost certainly has the same causes.

**Closed** 2018-10-20 14:01 UTC
Labels: Platform-specific (Android)
