### ISSUE TITLE
Prince of Persia Revelations title screen graphic issue

### ISSUE THREAD

**Issue by hdd60311** [hrydgard/ppsspp#6423] opened 2014-06-25 11:36 UTC
The background in menu page has wrong color since 0.9.8-890 #5767, and get some new graphic glitch since 0.9.8-1275 #6362

![1](https://cloud.githubusercontent.com/assets/5089290/3384583/b8e96eec-fc5c-11e3-996c-1fb504f7540a.jpg)
![2](https://cloud.githubusercontent.com/assets/5089290/3384585/be8107f2-fc5c-11e3-9da9-9ba4b499bb82.jpg)
![3](https://cloud.githubusercontent.com/assets/5089290/3384588/c3687188-fc5c-11e3-8974-6bc7aaaec997.jpg)
![4](https://cloud.githubusercontent.com/assets/5089290/3384591/c8a1733e-fc5c-11e3-9650-a5536fff984b.jpg)

**Comment by unknownbrackets** [comment] 2015-12-29 21:43
Just to confirm, this is also happening at 1x internal resolution right?

The clut and blending look more or less right.  It's using `(clut >> 8) & 0xff` though, which is odd.  I guess it's basically looking at A and B only.  So this could be a stencil issue.

Also, more importantly, 0x04710000 is swizzled.  Do you see it trying to draw to 0x04110000 or 0x00110000?  Does it show any FBOs created with that as the depthbuffer?  This could be a render from the depthbuffer.

-[Unknown]

**Comment by daniel229** [comment] 2015-12-30 01:11
Yes,it also happen at 1x
0x00110000 is this?
![01](https://cloud.githubusercontent.com/assets/3481559/12044952/55e9960a-aed5-11e5-92f9-aab6f6936545.png)

**Comment by unknownbrackets** [comment] 2015-12-30 01:23
That example is a shame.  It'll be slower because it's doing that, and it's hard to optimize.  Oh well, anyway back to this bug.

FMT is 1, so 5551.  If it doesn't later reuse this VRAM as a depth buffer, then this is probably where it's supposed to create it.  Or maybe we're missing a framebuffer upload.

(5551 >> 8) & 0xff is actually going to be (B / 8) G A.  That seems odd.

Comparing these two:
https://cloud.githubusercontent.com/assets/5089290/3384588/c3687188-fc5c-11e3-8974-6bc7aaaec997.jpg
http://images6.fanpop.com/image/photos/34300000/Prince-of-Persia-Revelations-screenshot-prince-of-persia-34378998-480-272.png

It really looks like it should be darkening it.  Maybe I should add a way to visualize the palette to the GE debugger...

Anyway, I feel like somewhere between the prim you've highlighted just now, and the prim you highlighted previously, it should be clearing or redrawing this framebuffer.

-[Unknown]

**Comment by unknownbrackets** [comment] 2019-03-10 00:52
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Saramagrean** [comment] 2019-03-12 17:23
Dump in main menu.
[Dump.zip](https://github.com/hrydgard/ppsspp/files/2958022/Dump.zip)

**Comment by Saramagrean** [comment] 2019-03-12 21:23
GE Dump in main menu & in-game use Vulkan

[ULUS10063_DUMP_Vulkan.zip](https://github.com/hrydgard/ppsspp/files/2958837/ULUS10063_DUMP_Vulkan.zip)


.

**Comment by hrydgard** [comment] 2020-04-26 10:00
Duplicate of #6423

**Comment by Panderner** [comment] 2020-04-26 10:56
> Duplicate of #6423

Wait what? This is the same issue here.

**Comment by hrydgard** [comment] 2020-04-26 11:38
Haha oops, I had too many tabs open.

**Comment by unknownbrackets** [comment] 2020-04-26 18:38
As noted in #11506, this is depth texturing.  Note that it uses the same address as a color buffer within the same frame, so we'll have to be smart about picking the depth buffer when we should to implement this correctly.

-[Unknown]

**Comment by hrydgard** [comment] 2020-04-26 20:13
Yeah, that's a good observation. Tricky stuff.

**Comment by Gamemulatorer** [comment] 2020-05-22 01:12
I just try ppsspp v1.9.3-913 to compare hw renderer vs sw renderer.

### HW Renderer
![hw-pop](https://user-images.githubusercontent.com/37603562/82620817-070c2b00-9c0c-11ea-9500-c1a7989adc17.png)
![hw-pop1](https://user-images.githubusercontent.com/37603562/82620858-26a35380-9c0c-11ea-920d-c92001dc6061.png)
### SW Renderer
![Screenshot_20200522-090424](https://user-images.githubusercontent.com/37603562/82620893-3a4eba00-9c0c-11ea-87b5-b418ee04ce88.png)
![Screenshot_20200522-090615](https://user-images.githubusercontent.com/37603562/82620912-48043f80-9c0c-11ea-9a23-7474687e88b3.png)

**Comment by Panderner** [comment] 2021-01-03 11:48
v1.10.3-1459-g678d881a1 results for OpenGL and Vulkan:

OpenGL: 
![Screenshot_2021-01-03-19-34-15-852_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103477736-8a296c80-4dfc-11eb-8ff2-85ce3670b8d5.jpg)
![Screenshot_2021-01-03-19-34-41-189_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103477741-8f86b700-4dfc-11eb-8621-65c0c559ed24.jpg)

Vulkan:
![Screenshot_2021-01-03-19-34-29-490_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103477745-97465b80-4dfc-11eb-8e4c-1d60bc1450a4.jpg)
![Screenshot_2021-01-03-19-34-53-776_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103477746-99101f00-4dfc-11eb-854f-ab4799fd3bf4.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-02 15:00
On my Redmi Note 9
### Vulkan
![Screenshot_2021-05-02-22-58-27-096_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116817679-2476a280-ab9a-11eb-8c8b-f4e59200de2f.jpg)
![Screenshot_2021-05-02-22-54-41-484_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116817681-28a2c000-ab9a-11eb-9ad3-e14ddc50dfba.jpg)
### OpenGL
![Screenshot_2021-05-02-22-57-12-841_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116817687-35271880-ab9a-11eb-8c30-b040c8bae096.jpg)
![Screenshot_2021-05-02-22-56-01-594_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116817692-37897280-ab9a-11eb-847b-da68115d5a60.jpg)

**Comment by benderscruffy** [comment] 2022-08-20 10:36
[v1.13.1-380-g044b8d647]
still an issue
here is a GE Dump
[ULUS10063.zip](https://github.com/hrydgard/ppsspp/files/9386877/ULUS10063.zip)

**Comment by Gamemulatorer** [comment] 2022-08-25 14:39
Software is also problematic
![Screenshot_2022-08-25-22-37-01-442_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/186694703-ca13ed2a-0989-4817-b1f0-8560011a3f87.jpg)
[ULUS10063.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9425668/ULUS10063.ppdmp.zip)

**Comment by hrydgard** [comment] 2022-09-26 10:25
The title screen should be completely fixed now.

**Closed** 2022-09-26 10:27 UTC
Labels: Depth / Z, GE emulation
