### ISSUE TITLE
[Controller Issue??]  Controller(Axis) was hold on v1.11.3-849-g25cfb92a9.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#14586] opened 2021-07-07 13:21 UTC
### What happens?
I'm playing MHP series.
1. Push little left stick any way that like a snapping and leave finger.
2. Character is starting move and "continuous walk" automatically.

Is this build related to controllers control?
v1.11.3-846 is no problem.

#### What hardware / device and operating system?
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
Resolution：2560×1440
RAM：32GB
#### What graphics card (GPU) or mobile phone model?
GPU：RADEON RX5700XT
#### What PPSSPP version (standalone/official), and did it work before?
v1.11.3-846
#### Which game or games?

MHP      ULJM05066
MHP2    ULJM05156
MHP2G  ULJM05066
MHP3rd ULJM05800/NPJB40001

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-07-07 16:53
@nassau-tk can you check if your controller analog stick is drifting?

**Comment by hrydgard** [comment] 2021-07-07 19:15
This is probably gonna be https://github.com/hrydgard/ppsspp/pull/14569 , which changes up the joystick settings a bit. Might be able to get back the old behavior by tweaking it.

I plan to implement a better joystick calibration screen...

**Comment by nassau-tk** [comment] 2021-07-07 22:22
> @ nassau-tkコントローラーのアナログスティックがドリフトしているかどうかを確認できますか？

Yes,of course.
My controller is not drifting. :grinning: 
It was become by v1.11.3-849.

**Comment by nassau-tk** [comment] 2021-07-07 22:27
> This is probably gonna be #14569 , which changes up the joystick settings a bit. Might be able to get back the old behavior by tweaking it.
> 
> I plan to implement a better joystick calibration screen...

I think about this It should revert it before v1.11.3-846.

**Comment by hrydgard** [comment] 2021-07-07 22:47
Have you tried changing the deadzone setting? (Yeah, it would of course be best if the settings that used to work still worked, there's tweaking to do, but I'd prefer not to revert as the unification of deadzone processing in #14569 is something I wanted to do anyway).

**Comment by gyf304** [comment] 2021-07-07 23:11
Currently at work, will have a look at it once I got home.

**Comment by nassau-tk** [comment] 2021-07-07 23:33
OK! I will check after my work.

**Comment by gyf304** [comment] 2021-07-08 01:33
While I'm not able to reproduce your issue. I have a theory on what's wrong, try this build and see if this fixes it for you.
https://github.com/gyf304/ppsspp/suites/3184666012/artifacts/73466762

**Comment by nassau-tk** [comment] 2021-07-08 02:01
@gyf304 

I see!
Probably, I can do that 8hours later.

**Comment by hrydgard** [comment] 2021-07-08 10:23
(So that's https://github.com/gyf304/ppsspp/commit/a17ac56e84fbbc7f3a82ec2be6e49733fe29e85d .. Hm.)

**Comment by nassau-tk** [comment] 2021-07-08 11:16
> While I'm not able to reproduce your issue. I have a theory on what's wrong, try this build and see if this fixes it for you.
> https://github.com/gyf304/ppsspp/suites/3184666012/artifacts/73466762

I tested your build.
Result: Not happen the issue.

And, Retested v1.11.3-849.
(Of course overwrite to v1.11.3-846.)

Result: It happen the issue.

Reported!!

**Comment by hrydgard** [comment] 2021-07-08 14:05
Thanks for testing nassau-tk!

I think that's indeed the culprit. I'm gonna merge gyf304's fix soon.

**Comment by unknownbrackets** [comment] 2021-07-11 05:39
Is this working with #14590 merged?

-[Unknown]

**Comment by gyf304** [comment] 2021-07-11 15:54
> Is this working with #14590 merged?
> 
> -[Unknown]

I think so.

**Closed** 2021-07-11 16:50 UTC
