### ISSUE TITLE
Can't exit to main menu in Tekken 5 Dark Resurrection

### ISSUE THREAD

**Issue by MaIevoIent** [hrydgard/ppsspp#14276] opened 2021-03-10 12:38 UTC
When playing Arcade mode, you can't exit the battle and it will just be stuck at your character/opponent's outro. Didn't try It in other modes because I'm not that interested.

You can however, continue fighting but it seems rather useless as your progress will not be saved because you can't go back to main menu. I updated my v1.11.1-xxx to v1.11.2-xxx but the bug is still there.

It's been like 2 days since I experienced this but due to my bad internet, I didn't manage to put this here on time. Sorry for that

I'm playing on my Android phone. My laptop is still at v1.10.3-xxx, I haven't updated it yet because I mainly play on the phone.

**Comment by Panderner** [comment] 2021-03-10 13:51
Duplicate of #14212

**Closed** 2021-03-10 13:54 UTC
