### ISSUE TITLE
gamepad (windows) plugged in while running

### ISSUE THREAD

**Issue by Drui7** [hrydgard/ppsspp#9131] opened 2016-11-25 21:48 UTC
if the first switch in the usb gamepad, and then turn on the emulator - everything is fine. 
if you first turn on the emulator, and then a gamepad, it is impossible to navigate through the menus using it.
all control settings have been made in previous launches, windows 10x64, the latest build.
it would be convenient to update the list of available input devices when new.

**Comment by hrydgard** [comment] 2016-11-30 18:45
Yeah, that sounds like a real problem. I think it has been working using XInput (Xbox) controllers though, but perhaps not for DirectInput. Needs looking into.

**Comment by hrydgard** [comment] 2016-12-01 16:15
Read the code now, it definitely doesn't handle this case. Should be rewritten, not sure how I will prioritize this though.

**Comment by unknownbrackets** [comment] 2018-12-02 19:40
Oops, #11446 was a duplicate of this.  It should work as of #11461.

-[Unknown]

**Closed by unknownbrackets** 2018-12-02 19:40 UTC
Labels: Platform-specific (Windows)
