### ISSUE TITLE
Visual bug issue

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#13128] opened 2020-07-12 08:20 UTC
Game: Ratchet and Clank size matters

Issue: The screen flickers with a 4 to 5 second interval but the           thing is that I can still see the sprite animation rather than the assets of the game. Is there a solution to this graphical bug?

**Comment by Gamemulatorer** [comment] 2020-07-12 11:25
Most likely duplicate of #6105? 

But could you try exporting a GE frame dump? Just make sure to export it when you see the lower performance - it's almost like a screenshot. If you make it while the FPS is good, it won't help.
See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
You can zip that and then drag and drop it into a reply here.

Can't promise there's anything we can do on that device, but a GE dump will give us an idea.

**Comment by ResurrectionRedmi9** [comment] 2021-09-16 01:34
Outdated/No Feedback.

**Comment by unknownbrackets** [comment] 2021-09-16 01:45
Closing given this is probably a duplicate and the original reporter has deleted their account, so we're unlikely to ever get confirmation.

-[Unknown]

**Closed by unknownbrackets** 2021-09-16 01:45 UTC
