### ISSUE TITLE
Smaller letters in save data description that is unreadable in 1x resolution

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13958] opened 2021-01-22 10:16 UTC
These are small letters in save data description for some games that is unreadable in 1x resolution.

For example Star Wars: The Force Unleashed:
![IMG_20210122_181438](https://user-images.githubusercontent.com/37503397/105478184-d40bc100-5cdd-11eb-9fdf-ee662a477571.jpg)

**Comment by unknownbrackets** [comment] 2021-01-23 16:53
Are you using force nearest texture filtering?  It should look better if you use Auto.

-[Unknown]

**Comment by Panderner** [comment] 2021-01-23 17:10
> Are you using force nearest texture filtering? It should look better if you use Auto. Or maybe it's a post shader?
> 
> -[Unknown]

And here's a screenshot for comparison of texture filtering

Linear:
![Screenshot_2021-01-24-01-07-48-360_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105608906-d276f180-5de0-11eb-98ff-7a47b05c24eb.jpg)


Nearest:
![Screenshot_2021-01-24-01-07-41-195_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105608899-becb8b00-5de0-11eb-8b20-d4d595cc7dd1.jpg)

I don't use post shaders at all.

**Comment by Panderner** [comment] 2021-01-23 17:15
When I upscale the resolution the small letters are readable.
![Screenshot_2021-01-24-01-15-05-224_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105609067-adcf4980-5de1-11eb-9822-eef85aa073c1.jpg)

**Comment by UbiSergei** [comment] 2021-01-23 17:59
Canvas Can't Usee Four Dimensions..

**Comment by unknownbrackets** [comment] 2021-01-23 18:16
Does it look better now?

-[Unknown]

**Comment by Panderner** [comment] 2021-01-23 18:30
It needs resize the bottom description to be readable
![Screenshot_2021-01-24-02-29-39-480_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/105610730-115e7480-5dec-11eb-9e4d-ceaaf0f7199c.jpg)

**Comment by unknownbrackets** [comment] 2021-01-23 18:34
Not sure.  Here's how it looks for me:

![Trails in the Sky with description on save](https://user-images.githubusercontent.com/191233/105610792-53dd6e00-5d66-11eb-8077-174c4fd47078.png)

Not amazing but readable.  It's not clear to me why it's so blurry and grayed out on your screenshot.

-[Unknown]

**Comment by Panderner** [comment] 2021-01-23 18:38
I'm using a android phone @unknownbrackets.

**Comment by unknownbrackets** [comment] 2021-01-23 19:09
Android isn't really much different:

![android screenshot](https://user-images.githubusercontent.com/191233/105611626-41196800-5d6b-11eb-88aa-d110b560f9ec.png)

At most we could just truncate more, but this wasn't really very readable on a PSP either...

-[Unknown]

**Comment by hrydgard** [comment] 2021-01-23 20:17
just render at 2x... :)

**Comment by Panderner** [comment] 2021-01-24 03:20
This is how it looks like in real PSP
![50727253-44325480-10cd-11e9-85cb-288b318ffd97](https://user-images.githubusercontent.com/37503397/105620271-25c75f00-5e36-11eb-8d8b-c839619d6336.png)

**Comment by ANR2ME** [comment] 2021-01-24 15:25
Based on `PSPSaveDialog::DisplaySaveDataInfo1()` the textStyle use for the Details supposed to be the same with the Date Time, how did it became so small like that? Was it because the detail's text too long?

**Comment by unknownbrackets** [comment] 2021-01-24 16:02
Okay, I had misremembered that a real PSP scaled down the text.  It just hides it.

We can remove the scale down, but at a certain point - why?  We could also remove fast forward or the ability to render at higher resolutions at all.  It's equally a bug that we incorrectly have such features that don't exist on a real PSP too.

So the problem you're reporting here is that the text is too small.  You would rather it's not shown at all.  Is that right?

-[Unknown]

**Comment by ANR2ME** [comment] 2021-01-24 18:24
I think he just want the text to be readable without upscaling since upscaling can be "expensive" on low-end devices.

So may be we can increase the scale a little bit?

Changing `float maxScaleDown = zoom == 1 ? 1.5f : 2.0f;` to `float maxScaleDown = zoom == 1 ? 1.1f : 2.0f;` seems to have better readability on 1x PSP rendering resolution when stretched to fullscreen.

**Comment by unknownbrackets** [comment] 2021-01-24 20:47
Well, I think that what you're seeing and I'm seeing is ugly, but readable.  The screenshot in https://github.com/hrydgard/ppsspp/issues/13958#issuecomment-766157223 is dimmer and even less readable (although arguably still readable.)  I still can't reproduce that, I guess it must be display stretch settings.

I actually often use 1x.  I hate the lines and things, and am not nearly as bothered by lower resolution as most.  Of course, I prefer higher resolution when it looks strictly better and doesn't have artifacts.

See #11711.  The reasons I did the scale down were:
1. Out font has different metrics so you might actually see less if we were super naive about it.
2. At higher resolutions our font looks *much* better, so switching to lower-quality PGF bitmap fonts to get the metrics is a painful sacrifice for very tiny gain.
3. Also I think our font looks better even at lower resolutions.  But that's my personal biased opinion, I like Roboto.
4. The text is there, so as I said before: "I think it's clear that the intent in this case was to expose all the levels to the user and that it doesn't is probably just a shortcoming in the UI."  It is not my believe that we should strive to emulate every shortcoming and every flaw in PSP firmware, if it has no impact on game compatibility.

Another example where I'm glad we willfully break from original firmware behavior: normally you have to cancel the save dialog after saving, you can't just mash X.  It annoyed me on real PSPs every single time.  I'm so glad we intentionally don't replicate that bad UX.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-08-07 16:09
Personally, I think this is resolved now and we haven't gotten any further complaints.  I realize we could truncate the text, but I noted my argument against that above.

Any objections to closing this?  Most people will use 2x where it looks nicer anyway.

-[Unknown]

**Closed** 2021-08-07 17:29 UTC
Labels: HLE/Kernel

**Comment by Panderner** [comment] 2021-08-07 18:31
But some games had graphical issues when the upscaled higher than 1x resolution.

For the example: as I mentioned #3332 & #3871 the lines are drawn incorrectly when the upscaled and the FMVs too (#13697)

**Comment by ANR2ME** [comment] 2021-08-08 03:06
May be using `compat.ini` to let the Details to be rendered with the same size to Date Time? which may ended truncated.

**Comment by unknownbrackets** [comment] 2021-08-08 05:41
I don't think that makes sense.

In games that already use a small amount of text, the text is the same size it is on the PSP.  There's nothing for compat.ini to do.

In games where the developer put effort into generating text that wasn't visible on the PSP, it's currently making the text a bit smaller to show all the text.  As per my argument above, I think it's better to do this.  You're suggesting we find each of these games one by one (why?) and force them to hide the text?  If you disagree with my argument above, you should explain that.  There's no need to do it one by one for each game.

Again, I also play games at 1x PSP and for me it does seem to be readable, although with stretching sometimes less so.  I can see the argument to make it exactly like the PSP, but that would seem more like an option if anything not a compat.ini value.

-[Unknown]

**Comment by Panderner** [comment] 2021-08-09 11:20
Even the resolution is upscaled Darkstalkers still uses 1x resolution due to ForceSoftwareRenderer for this game is enabled by compat.ini
![Screenshot_2021-08-09-19-15-52-211_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/128698700-0f3218bf-0f70-4d98-be78-2a24adae41d6.jpg)

**Comment by hrydgard** [comment] 2021-08-09 11:23
That's a bit of an edge case, yes. But do you have a lot of issues with too small text in that game?

**Comment by Panderner** [comment] 2021-08-09 11:32
> That's a bit of an edge case, yes. But do you have a lot of issues with too small text in that game?

Unfortunately there is only 1 slot for this game per save for progress and tower mode.

**Comment by hrydgard** [comment] 2021-08-09 12:07
Yeah, so not an issue in practice.
