### ISSUE TITLE
Naruto Impact - Crash (older android device)

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14634] opened 2021-07-23 18:39 UTC
### What happens?
Posting this on behalf of a friend. In Naruto impact (USA), when he entering a mission, in the character selection screen it just crashes. There doesn't seem to be any error message (it just brings him to his home screen). Happens both online ad-hoc netplay and offline.

### What *should* happen?
It shouldn't crash. 

#### What hardware / device and operating system?
Coolpad Legacy - (cp3705A). Running Android 9.0
#### What graphics card (GPU) or mobile phone model?
Adreno 506.
#### What PPSSPP version (standalone/official), and did it work before?
1.11.3, and unsure if it ever worked before.
#### Which game or games?

ULUS10582.

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2021-07-23 19:03
It's a fairly popular game so I would have expected to get more reports - could it be as simple as a corrupt ISO? Can others reproduce?

**Comment by Gamemulatorer** [comment] 2021-07-23 21:57
Duplicate of https://github.com/hrydgard/ppsspp/issues/12847

**Comment by samosaphile** [comment] 2021-07-23 22:20
I think this is mostly a device specific issue. Maybe a quirk with the android OEM skin or the device drivers. Now that I think about it, maybe I should ask him what backend he uses. If vulkan, try opengl. Could be due to poor device vulkan drivers maybe?

I think he tried testing other ppsspp builds once, not specifically for this game but we didn't notice much or any difference so we kinda just stopped experimenting with different builds.

**Comment by hrydgard** [comment] 2021-07-23 22:38
Does indeed seem very similar to #12847 , which occurs on devices with older Adreno GPUs for whatever reason... 

It's unfortunate and not sure how fixable. But closing as duplicate of #12847.

**Closed by hrydgard** 2021-07-23 22:38 UTC

**Comment by XiaomiRedmi9** [comment] 2021-07-23 23:04
If he @samosaphile using vulkan backend still crash!?

**Comment by samosaphile** [comment] 2021-07-27 00:06
> If he @samosaphile using vulkan backend still crash!?

He said it crashes on both.

**Comment by XiaomiRedmi9** [comment] 2021-07-27 06:26
Better to upload a crashlog here.

**Comment by hrydgard** [comment] 2021-07-27 07:00
Please post any new info in #12847 instead.
