### ISSUE TITLE
Ys vs. Sora no Kiseki - Multiplayer Functionality

### ISSUE THREAD

**Issue by Shawnjius** [hrydgard/ppsspp#13493] opened 2020-09-30 16:06 UTC
### What happens?
When trying to load into a multiplayer session, the players enter the lobby with no issue, but as the player and stage selection screens load in, the connection eventually drops. Video of the issue here:
https://youtu.be/OUsYsUItyd8

### What *should* happen?
Both players should enter the lobby, accept, and the player and stage select screens should load in without dropping the connection, allowing you to proceed to the match as normal.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Tested on various laptops, PCs, Android phones, and between a variety of players, all with the same result.

**Comment by Pik-a-boo** [comment] 2020-09-30 17:06
You should try the latest dev builds from Orphis.
The official PPSSPP is a bit outdated now with Ad-hoc.

**Comment by Shawnjius** [comment] 2020-09-30 17:13
I believe our most recent tests were on the latest Orphis build, but I will double check.

**Comment by Choojermelon** [comment] 2020-09-30 19:59
Can confirm this was tested on dev build v1.10.3-597-gfcaef648e

**Comment by ANR2ME** [comment] 2020-10-01 00:09
I have investigate this game for a few months and have no clue about the disconnection issue, probably related to PeerInfo since it's the only thing being used by this game (other than Send/Recv) during the characters selection where disconnection issue occurred.

This games used to have 3 issue in the past:
1. Host showing it self as gibberish/random name instead of Player name, which was fixed by https://github.com/hrydgard/ppsspp/pull/13393
2. Client showing the game room as MAC address instead of Player name, one thing i know that the Client get the text from HELLO data sent by the Host (which contains Player name and MAC address string), but not sure why the Client decide to use the MAC Address instead of the Player Name to be shown.
3. Disconnection issue while choosing the characters to play with, i haven't found any clue yet.

**Comment by Shawnjius** [comment] 2020-10-01 00:58
I may also be worth noting that another Falcom game with AdHoc support, Vantage Master Portable, reacts in a very similar way.

**Comment by Pik-a-boo** [comment] 2020-10-01 05:59
I guess you could play this over JPCSP but it will only work over multiple instances of it.
Same games dont even need the PRX files so they will work out of the box.

**Comment by ANR2ME** [comment] 2020-10-01 06:41
> 
> 
> I may also be worth noting that another Falcom game with AdHoc support, Vantage Master Portable, reacts in a very similar way.

LOL i ended fixed Ys vs Sora Kiseki while trying to fix Vantage Master Portable, i'm not sure how that happen, but i was right, it was related to PeerInfo's `last_recv`
![image](https://user-images.githubusercontent.com/7974720/94776290-ad064800-03eb-11eb-83bd-f79c6666a292.png)
But since i haven't been able to fix Vantage Master Portable yet, i will need to do more testing

**Comment by Choojermelon** [comment] 2020-10-01 07:46
That's very exciting news, @ANR2ME! Thank you for taking a look at it. I'm looking forward to trying it out if/when there's a build up.

Good luck with VMP in the meantime!

**Comment by Pik-a-boo** [comment] 2020-10-01 07:55
I bet its one of the PSP games that use lockstep for its netcode so dont expect full speed over internet .
Better to just use parsec and multiple instances of PPSSPP.

**Comment by ANR2ME** [comment] 2020-10-01 10:46
Hmmm.. i think Vulkan is having memory leaks O.o
After several times testing Vantage Master Portable (launch the game, do multiplayer, close PPSSPP and rebuild the exe) it will eventually getting a crash (not enough memory issue?) when launching the game
![image](https://user-images.githubusercontent.com/7974720/94799780-dfc13800-040d-11eb-9241-edcbc2487948.png)

**Comment by hrydgard** [comment] 2020-10-01 11:17
Wow, that's .. not good. Interesting

**Comment by ANR2ME** [comment] 2020-10-01 19:53
> 
> 
> That's very exciting news, @ANR2ME! Thank you for taking a look at it. I'm looking forward to trying it out if/when there's a build up.
> 
> Good luck with VMP in the meantime!

I managed to fix both games, but it will probably takes awhile before i create a PR since i currently have a bunch of uncommitted changes to fix many things, i'll need to separates them into several commits first.

Anyway, i can provide you with windows test build only for now, because apparently the latest commits from master have issue with building Android APK related to Gesture
```
../../../../../ext/native/ui/viewgroup.cpp:962: error: undefined reference to 'GestureDetector::IsGestureActive(Gesture, int) const'
```

Here is Win32/x64 test build: https://www.dropbox.com/s/xur6i1alhkrka78/PPSSPPWin32x64_v1.10.3-815_adhocfix.zip?dl=0

**Comment by ANR2ME** [comment] 2020-10-07 05:51
> 
> 
> Hmmm.. i think Vulkan is having memory leaks O.o
> After several times testing Vantage Master Portable (launch the game, do multiplayer, close PPSSPP and rebuild the exe) it will eventually getting a crash (not enough memory issue?) when launching the game
> ![image](https://user-images.githubusercontent.com/7974720/94799780-dfc13800-040d-11eb-9241-edcbc2487948.png)

Hmm.. this memory issue probably didn't came from PPSSPP, but due to high memory usage of dwm.exe :( it's using 1,3gb of RAM when PPSSPP keeps crashing today (due to vulkan unable to allocate memory)

**Comment by ANR2ME** [comment] 2020-10-08 02:20
@Shawnjius @Choojermelon could you try the test build on PR https://github.com/hrydgard/ppsspp/pull/13519 to see if that PR really resolved this issue?

**Comment by Shawnjius** [comment] 2020-10-08 03:37
We've done some initial testing and it seems like Ys vs. is working over Adhoc with the expected amount of slowdown, but it works great via Parsec using multiple instances on a single PC. Vantage Master Portable works with zero issues over Adhoc, based on the tiny bit of testing we've done. We have yet to test either game with the Android build, though. I'll report back when I know more.

**Comment by Shawnjius** [comment] 2020-10-22 22:17
How big a role would you say Vantage Master Portable had in you eventually figuring out the answer? Were you already pretty sure you knew what was wrong before then? Sorry, I know it's random, but I'm just weirdly curious and hoping you'll indulge me.

**Comment by ANR2ME** [comment] 2020-10-23 01:14
Actually, i just need another game with similar code style to confirm it. I had some suspicion in the past but due to my lacks of knowledge in MIPS opcode i couldn't really tell what's happening.
And apparently i had similar issue with my timeout code, i guess i had similar mind with Falcom's developer thinking that a timestamp would never goes backward and subtracting current timestamp with a (supposed to be) older timestamp resulting to a negative number but comparing it with a fixed timeout value as unsigned number which causing that negative number to a very big positive number and hit the timeout threshold.
Well timestamp should never goes backward in real life, but since we are talking about emulation anything could happen.

Anyway, if there is no major issue with Falcom's games, we can close this issue now.
Adhoc wasn't designed to be played over the internet in the first place, so expect some minor issue like lags, stutters, FPS drops, and sometimes disconnection due to too much lost packets when played over the internet, since not all developers create a good netcode that can be played over high latency networks with higher chance of packets lost like the internet.

**Comment by Pik-a-boo** [comment] 2020-10-23 19:57
I noticed that mostly 2D fighting games use lockstep unless they are an arena/bralwer fighting games but then they use a delay based approach (few 2D fighting games have good netcode like SB2 and BB).

**Comment by unknownbrackets** [comment] 2021-09-15 06:33
Is this working any better now?  #14506 implies that maybe the change improved, because it talks about another issue without even mentioning this one.

-[Unknown]

**Comment by Schtolteheim** [comment] 2021-09-21 03:59
> 
> 
> Is this working any better now? #14506 implies that maybe the change improved, because it talks about another issue without even mentioning this one.
> 
> -[Unknown]

I haven't run into any issues with speed or connection as of 1.11.3-742-g084f97c6c. I plan to do another regression test on 1.12, but for now, I think it's safe to close this.

**Comment by unknownbrackets** [comment] 2021-09-21 05:19
Thanks for the update.  Will close this then, glad it's working better now (or at least as of v1.11.3-742-g084f97c6c.)

-[Unknown]

**Closed by unknownbrackets** 2021-09-21 05:19 UTC
Labels: Networking / adhoc
