### ISSUE TITLE
Resistance Retribution Crashing

### ISSUE THREAD

**Issue by SuperFunker** [hrydgard/ppsspp#15246] opened 2021-12-20 17:26 UTC
### Game or games this happens in

UCAS-40233 - Resistance: Retribution

### What area of the game / PPSSPP

Mission 2 i think... 
After destroying the fuel line connecting to the gun tower there is a cutscene where grayson asks you
to enter his boat.

At the end of the cutscene the crash happens

### What should happen

It should continue the cutscene

### Logs

![Resistance Crash](https://user-images.githubusercontent.com/93083073/146806818-5b8744f8-d0de-47ac-a1c1-d480fa415d45.PNG)
![Resistance Crash2](https://user-images.githubusercontent.com/93083073/146806822-8cae7ec8-10d8-467f-a391-9cfa6f54b661.PNG)

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1050 Ti

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment] 2021-12-20 17:39
Closing as a duplicate of #4626

**Closed by LunaMoo** 2021-12-20 17:39 UTC
