### ISSUE TITLE
Voices cut off early in Hanayaka Nari Wa ga Ichizoku

### ISSUE THREAD

**Issue by akyz1** [hrydgard/ppsspp#8407] opened 2016-01-09 03:45 UTC
This game has voices, but the sound stops early every time a voice file is played. It usually cuts off around 3/4 of the way through the file. 

In the log I see a lot of stuff like this:  

44:18:207 user_main    I[ME]: HLE\sceMp3.cpp:182 sceMp3ReserveMp3Handle(09fff5b8)
44:18:223 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(280, 4, 08a621ac)
44:18:240 ThreadCtrl   I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(0)
44:18:258 user_main    I[ME]: HLE\sceMp3.cpp:314 sceMp3Init(09fff5b8)
44:18:258 user_main    I[ME]: HLE\sceMp3.cpp:332 sceMp3Init(): channels=1, samplerate=32000Hz, bitrate=48kbps
44:32:878 user_main    I[ME]: HLE\sceMp3.cpp:461 sceMp3ReleaseMp3Handle(09FFF5B8)
44:35:631 user_main    I[ME]: HLE\sceMp3.cpp:461 sceMp3ReleaseMp3Handle(09FFF5B8)
44:35:631 user_main    E[ME]: HLE\sceMp3.cpp:465 sceMp3ReleaseMp3Handle: bad mp3 handle 09fff5b8
44:35:831 user_main    I[ME]: HLE\sceMp3.cpp:182 sceMp3ReserveMp3Handle(09fff5b8)
44:35:848 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(280, 4, 08a621ac)
44:35:866 ThreadCtrl   I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(0)
44:35:883 user_main    I[ME]: HLE\sceMp3.cpp:314 sceMp3Init(09fff5b8)
44:35:883 user_main    I[ME]: HLE\sceMp3.cpp:332 sceMp3Init(): channels=1, samplerate=32000Hz, bitrate=48kbps

**Comment by unknownbrackets** [comment] 2016-01-09 04:13
Closing this as a duplicate of #5213.

-[Unknown]

**Closed by unknownbrackets** 2016-01-09 04:13 UTC
Labels: MP3
