### ISSUE TITLE
Graphic problem in Darkstalkers Chronicle: The Chaos Tower

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#8597] opened 2016-02-15 23:49 UTC
Hello, while mention this game, but it seems that there is still no improvement, since it is the same problem that had the danngaropan game on the pointer or selector object, but in the end could fix that problem.

As I say, only to activate the "READ TO MEMORY (CPU, glitches)" or "READ TO MEMORY (GPU, glitches)," The graphics of the game is improved.

I hope you can solve that little problem, because my CPU supports normally the "BUFFERED RENDERING".

Missing Option Menu:
![bug01](https://cloud.githubusercontent.com/assets/5083411/13063206/9b79d334-d413-11e5-9133-023c1b00c13f.jpg)

Missing character selection
![bug02](https://cloud.githubusercontent.com/assets/5083411/13063233/f5273836-d413-11e5-871e-a9ad82494364.jpg)

Disappears details combat environment and characters.
![bug03](https://cloud.githubusercontent.com/assets/5083411/13063258/3751ca64-d414-11e5-9e05-e63cdeed5b2c.jpg)

By selecting the option "READ TO MEMORY (CPU, glitches)" or "READ TO MEMORY (GPU, glitches)," The graphics of the game is improved.

![bug04](https://cloud.githubusercontent.com/assets/5083411/13063277/7005bf82-d414-11e5-8a87-a38f7e8811f7.jpg)

![bug05](https://cloud.githubusercontent.com/assets/5083411/13063282/8831580a-d414-11e5-8d9a-a70bb89a8c77.jpg)

![bug06](https://cloud.githubusercontent.com/assets/5083411/13063288/94b984b2-d414-11e5-812e-cbf76fefb25b.jpg)

Thanx.... Sorry my bad english XD!!

**Comment by daniel229** [comment] 2016-02-16 00:38
Duplicate of https://github.com/hrydgard/ppsspp/issues/6647

**Closed by daniel229** 2016-02-16 00:38 UTC
