### ISSUE TITLE
Xlink kai support

### ISSUE THREAD

**Issue by Puentee** [hrydgard/ppsspp#14395] opened 2021-04-21 03:09 UTC
the Xlink kai plugins for PSP are continuously receiving new updates for more compatibility in its games, if PPSSPP were to support it, it would enhance the potential games that could be played cross play with real hardware. 

Protocol needed: https://www.teamxlink.co.uk/wiki/DDS_Protocol

JPCSP with xlink kai support: https://github.com/jpcsp/jpcsp/releases/tag/XLinkKai-v1.0

**Comment by Panderner** [comment] 2021-04-21 03:34
Duplicate of #12886 i guess?

**Comment by ANR2ME** [comment] 2021-04-21 05:26
Yes, it's a duplicate.
And with current adhoc implementation PPSSPP can't generate packets compatible with PSP (without ProOnline plugin), thus can't communicate with PSP, unless PPSSPP is able to get prx files from official firmware to work (LLE) in the future, just like JPCSP.

**Comment by unknownbrackets** [comment] 2021-04-21 06:01
This issue is being closed as a duplicate of #12886.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-04-21 06:01 UTC

**Comment by unknownbrackets** [comment] 2021-04-21 06:08
> And the only way to generate compatible packet is by using LLE (prx files from firmware), or by implementing a lot of drivers HLE (which is still WIP on JPCSP) thus will take much longer time on PPSSPP since we don't even implement drivers HLE as of now.

Whether or not LLE is implemented, it's not going to make it so that raw socket packets are sent to the operating system libraries (Windows, Android, Linux, etc.)  Some of those have security restrictions preventing you from sending raw packets, and may require you to send TCP/UDP.  I'm not convinced Android would allow that in the first place, LLE, HLE, or anything but magical level emulation.

If it is over TCP/UDP, then in theory it's just a reverse engineering problem.  Although there's a lot of annoying state with the Net functions in general, in the end the system does behave like a function - if you do certain things, in a certain order, it will output specific packets.  If certain packets come in, it will do certain things.  You *can* always HLE something that behaves in such a way, although it may take significant effort.  There's nothing that makes it impossible without LLE, at most impractical.

-[Unknown]

**Comment by ANR2ME** [comment] 2021-04-21 07:15
For transmitting the raw packets XLinkKai will be handling it through their DDS protocol, we just need to generate a compatible packet just like what generated by JPCSP when using prx files (including the WLAN beacon packets).

But yeah, it probably won't work on Android due to port restriction under 1024, not sure whether XLinkKai can map the port to a different port or not, locally.

**Comment by MojoJojoDojo** [comment] 2021-05-02 17:01
> > And the only way to generate compatible packet is by using LLE (prx files from firmware), or by implementing a lot of drivers HLE (which is still WIP on JPCSP) thus will take much longer time on PPSSPP since we don't even implement drivers HLE as of now.
> 
> Whether or not LLE is implemented, it's not going to make it so that raw socket packets are sent to the operating system libraries (Windows, Android, Linux, etc.) Some of those have security restrictions preventing you from sending raw packets, and may require you to send TCP/UDP. I'm not convinced Android would allow that in the first place, LLE, HLE, or anything but magical level emulation.

When JPCSP does it for xlink kai support it seems like its not using raw sockets to do so.
It does use it for the infrastructure though lol.
I know that Citra the 3DS emulator also uses HLE for local wireless support (that could be tunnled over the internet) its also decrypted as far as I understand like Pro Online on PSP.
There is an unofficial Citra build for Android thats lets you play PC to Android as well but its not supported by the official team.
The devs talked about creating a plugin/homebrew on the 3DS side so it could transmit to the Citra emulator but never done it (a plugin similar to pro online I presume).
The only part that is (Networking) LLE on Citra is the Download Play support (equivelent to gamesharing) but it's not supported over the 3DS currently as well.
I think that are a lot of similarities between how the 3DS and PSP do the networking that might be interesting to explore but what do I know lol (Currently there is no 3DS support on Xlink Kai though).

**Comment by explanatary-273829** [comment] 2026-08-14 22:02
Someday, will this ever be possible? I read in some old posts that the developers didn’t want to support it because of the existence of PRO Online, but it would be great if this could become a reality someday. As far as I know, Team XLink devs haven’t been able to make the emulator transmit a real ad hoc signal like a PSP does, which is why they can’t make it compatible. So, from what I understand, everything depends on the PPSSPP developers.

**Comment by anr2me** [comment] 2026-08-15 04:43
It need LLE support, which is not a priority for PPSSPP, since PPSSPP mainly use HLE.
