### ISSUE TITLE
Sonic Rivals 1&2 Lag

### ISSUE THREAD

**Issue by Zetchzie** [hrydgard/ppsspp#8511] opened 2016-01-26 11:37 UTC
I've been keeping upto date with the latest gits and Still Sonic Rivals runs slow AF. Everything runs fine in menus and screens but as soon as a race begins the framerate drops to a crawl. Im using Win10 x64 Intel Pentium 2020M. I figured I would put this up if this issue isnt on here already.

**Comment by hrydgard** [comment] 2016-01-26 15:07
Yeah, this has been discussed, and yes, it's still a problem.

Duplicate of https://github.com/hrydgard/ppsspp/issues/6117

**Closed by hrydgard** 2016-01-26 15:07 UTC
