### ISSUE TITLE
Tenchu San Portable major issues!

### ISSUE THREAD

**Issue by wolfokami321** [hrydgard/ppsspp#7234] opened 2014-12-29 01:28 UTC
Tenchu san portable is currently unplayable because ingame some of the levels have no collision loaded meaning you and the enemies can walk through walls... not only that but the in game loading screens are infinite.

Note: I've tested two different rips of the game along with my original.
To reiterate:
-missing unrendered collision? 
-infinite ingame loading screen

**Comment by wolfokami321** [comment] 2015-01-03 14:36
Please fix these two issues, also kurenai portable has infinite loading aswell

**Comment by wolfokami321** [comment] 2015-01-03 14:39
Also I have used the latest buildbot put out this morning to no avail

**Comment by hrydgard** [comment] 2015-01-04 14:23
Does it work now, or why did you close it?

**Comment by wolfokami321** [comment] 2015-01-04 14:46
Closed it because it wasn't getting any attention. .. ive been trying every build. What is the difference between the windows and android builds? They are both compiled from the same source right?

**Comment by hrydgard** [comment] 2015-01-04 14:56
Not the JIT, which has to be done separately for ARM and x86. So it's very likely an ARM JIT bug.

**Comment by wolfokami321** [comment] 2015-01-04 21:36
Bro I see at least 20 new builds a day XD im pretty sure you guys make a living doing this... Anyways is there any progress on making the Jit code for ARM(Android) the same as x86(windows)

**Comment by wolfokami321** [comment] 2015-01-04 21:52
Also I disabled JIT and nothing changed, it probably means it isn't JIT related. Also, why is there no option to disable attrac because that could be what's causing in level loading issues?

**Comment by Bigpet** [comment] 2015-01-04 21:54
@wolfokami321  so the collisions work on PC but they don't work on mobile, even if you disable JIT?

**Comment by wolfokami321** [comment] 2015-01-04 22:09
Yes

**Comment by wolfokami321** [comment] 2015-01-05 21:25
Now on pc and mobile the infinite loading is still there in level

**Comment by Bigpet** [comment] 2015-01-05 21:30
Just assume that we still think it's broken unless we either ask you to retest or you tell us something changed. There's no need to remind us that it's still broken with this frequency.

**Comment by wolfokami321** [comment] 2015-01-06 01:31
Also why was the attrac option removed, some games have terrible attrac related issues still

**Comment by wolfokami321** [comment] 2015-01-15 03:35
Bump...

**Comment by sum2012** [comment] 2015-04-03 02:11
For the graphic problem "enemies can walk through walls"
My best freind @xiushudongfang Test 
last work: v0.9.8-103-g5c81434
first break: v0.9.8-104-gb158824

It mean
https://github.com/hrydgard/ppsspp/commit/b1588240149bd8b97138b4caef6c9dad84537637
or
https://github.com/hrydgard/native/commit/3139ac497f434f9daebb3db8b4cb062d6a739296

@hrydgard @unknownbrackets hope you have idea to fix.Thanks

**Comment by sum2012** [comment] 2015-04-03 02:53
I compile to @xiushudongfang to test
Revert https://github.com/hrydgard/native/commit/3139ac497f434f9daebb3db8b4cb062d6a739296 fix the graphic issue

**Comment by hrydgard** [comment] 2015-04-03 09:51
@sum2012  interesting, thanks! That might explain it.. I suppose we shouldn't enable that, or only when the PSP game requests flush-to-zero fp rounding...

**Comment by unknownbrackets** [comment] 2015-04-03 16:29
Is the graphic issue Android only?

There's a setting in ppsspp.ini for flush to zero - it defaults to true on Android:
ForceFlushToZero = True

Does changing it to False improve anything?  This will only impact jit, so if the problem is outside jit it won't make a difference (for example, interp will still use flush to zero.)

-[Unknown]

**Comment by hrydgard** [comment] 2015-04-03 16:30
I think we probably should kill that setting, it's dangerous and I don't think there's enough speed difference to motivate it. Better to strive to be as accurate as reasonably possible with rounding..

**Comment by xiushudongfang** [comment] 2015-04-03 16:43
@unknownbrackets ，  unfortunately,I have tested it .It  did not  work.

**Comment by hrydgard** [comment] 2015-04-03 17:21
Here's the documentation for the FPSCR register on Cortex A8 (and later, probably):

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0344b/Chdfafia.html

Mostly, it just masks away "DNM" bits (do not modify), the only relevant thing that is different after that commit is that it forces the rounding mode to NEAREST. So that might not be good then..

Another interesting thing is that both before and after, it doesn't just set the flush-to-zero bit but also the "DN" bit (Default NaN)... I wonder if that's good.

Anyway, can you try this:

In FPU_SetFastMode, change 0x04086060  to 0x04c86060. This should keep the original rounding mode.

If that doesn't do it, I'll just revert it or remove SetFastMode entirely.

**Comment by unknownbrackets** [comment] 2015-04-03 17:37
@hrydgard well, I kept the setting mostly to maintain old behavior on arm (since I didn't know how much it might affect other devices) and so we had another datapoint.  I'm totally okay with killing the setting.

Do we have any numbers on actual improvements SetFastMode even does?

I should note that some tweaks to the armjit SetRoundingMode() logic might be needed if fastmode is not enabled by default on ARM.  Also, that logic assumes nearest is the default mode.

-[Unknown]

**Comment by hrydgard** [comment] 2015-04-03 17:47
I don't have any numbers, but I doubt it's a lot, especially on newer cores than Cortex-A8 that don't have this "fast-mode" distinction..

**Comment by sum2012** [comment] 2015-04-03 23:56
@hrydgard change 0x04086060 to 0x04c86060 don‘t help.

**Comment by sum2012** [comment] 2015-04-04 00:01
My graphic probrem more serious
Lg nexus 5
http://postimg.org/image/ue7adfka7/a26e3814/

**Comment by unknownbrackets** [comment] 2015-04-04 00:13
How is it supposed to look?

If you change 0x03000000 to 0x00000000, it works?  That will force nearest but keep FZ and DN off.

-[Unknown]

**Comment by sum2012** [comment] 2015-04-04 00:24
It supposed to look http://postimg.org/image/lk0k0le2n/
I am at work so that I cannot compile

**Comment by unknownbrackets** [comment] 2015-04-04 00:30
Hmm... I guess depth testing related?

-[Unknown]

**Comment by sum2012** [comment] 2015-04-04 00:48
Revert https://github.com/hrydgard/native/commit/3139ac497f434f9daebb3db8b4cb062d6a739296 fix it

**Comment by sum2012** [comment] 2015-04-04 00:48
Revert https://github.com/hrydgard/native/commit/3139ac497f434f9daebb3db8b4cb062d6a739296 fix it

**Comment by sum2012** [comment] 2015-04-04 00:50
Revert https://github.com/hrydgard/native/commit/3139ac497f434f9daebb3db8b4cb062d6a739296 fix it

**Comment by xiushudongfang** [comment] 2015-04-04 03:46
@unknownbrackets   change 0x03000000 to 0x00000000 ,works well.

**Comment by sum2012** [comment] 2015-04-04 06:41
@unknownbrackets change 0x03000000 to 0x00000000 ,works well in my case too

**Comment by sum2012** [comment] 2015-06-07 06:24
@hrydgard ,revert  https://github.com/hrydgard/native/commit/3139ac497f434f9daebb3db8b4cb062d6a739296
or use @unknownbrackets fix ?

**Comment by hrydgard** [comment] 2015-07-19 16:26
With that, we no longer try to get arm cpus into "fastmode" globally. Should help.

Later, might add some smarter tracking of what flags we've set, so we can still use fastmode for things like software T&L etc, but not sure there's much of a win, really.

**Comment by sum2012** [comment] 2015-07-19 21:53
@hrydgard Thanks,fixed grahic ,test in v1.0.1-777-gf4e0034.
Remain "infinite ingame loading screen" issue relate to atrac problem

**Comment by krispra** [comment] 2015-08-10 03:15
sorry for my bad english...  i hope you can understand what i mean :)

i've tried almost every build  old build & lates build & i found 1 the best for playing tenchu sqn/ kurenai on android

i use ppsspp gold v0.7.6 to play tenchu san & tenchu kurenai on my android tab... and it work great there are no character through the wall / infinite loading screen both in tenchu san/ kurenai... but NO sound

**Comment by sum2012** [comment] 2015-08-10 22:33
@krispra no character through the wall has been fixed in  v1.0.1-772
But infinite loading screen have not been fixed.

This is hack version that fix these https://drive.google.com/file/d/0B3OaSdeV0L8kY3VXaXYyNkRRdmM/view?usp=sharing

**Comment by sum2012** [comment] 2015-10-25 08:08
The reamin infinite ingame loading screen issue same same #6370 
I think that can close this

**Comment by unknownbrackets** [comment] 2015-10-25 08:14
Thanks.

-[Unknown]

**Closed by unknownbrackets** 2015-10-25 08:14 UTC

**Comment by Trokinos** [comment] 2015-11-15 15:26
A good update about that bug, after noticing an user reporting that the "eternal loading" bug is not present anymore for Tenchu Kurenai in recent PPSSPP builds, and as it's the same engine as Tenchu San, i gave a try with my current build from a few days ago.

And i was able to complete the 1st mission of the Rikimaru path without a problem, the mission has several location in which there's a loading, but PPSSPP does not get stuck anymore on any of them.
I don't have time to play more mission (as they're rather long) , but it looks like that game breaking bug is now fixed ! Thanks.
Not sure which commit did it, the version i am playing is :
1.1.1-273-g419ea84
on win32

**Comment by aquilsamuel** [comment] 2015-12-19 05:55
This is what I get when playing this game, even on version 1.1.1 on the PPSSPP for windows 8 32 bit. The music still plays but this loading screen just freezes the video and nothing can be done. I am a Tenchu fan and would love to play and have this game really bad. Can anyone solve this annoying problem??? Thanks ![tenchu san portable screenshot](https://cloud.githubusercontent.com/assets/16358888/11911650/7a8418a8-a5d1-11e5-8ff5-0ca01a8f0d40.jpg)

**Comment by daniel229** [comment] 2015-12-19 08:18
Download the latest build from http://buildbot.orphis.net/ppsspp/index.php

**Comment by aquilsamuel** [comment] 2015-12-19 13:09
@daniel229 Thank you for your response and help, the new version of PPSSPP runs the game well and I was able to finish the first stage without any loading bugs. 
![uljm05505_00003](https://cloud.githubusercontent.com/assets/16358888/11913141/adc3fffc-a60e-11e5-899f-c7a44966e485.jpg)
![Uploading ULJM05505_00004.jpg…]()
![uljm05505_00005](https://cloud.githubusercontent.com/assets/16358888/11913143/bbdf37e6-a60e-11e5-9fae-8276ef2642e1.jpg)
![uljm05505_00006](https://cloud.githubusercontent.com/assets/16358888/11913144/bbf60caa-a60e-11e5-9800-dbfea93f631f.jpg)

**Comment by kedamtac** [comment] 2016-01-10 14:18
thankkkkkkkkkkkk
