### ISSUE TITLE
Mac OSX Network Mode Crash

### ISSUE THREAD

**Issue by JohnTitor95** [hrydgard/ppsspp#9870] opened 2017-07-28 23:15 UTC
Me and a friend are attempting to play yugioh tagforce 5 over lan, but we cannot seem to get him to connect using network mode. Whenever he does, one of two things happens, either he black screen freezes, or it will say network initialized but immediately return him to the main menu. When i do it on PC, everything works fine. It seems with both the enable networking and ad-hoc options turned on, he gets returned to the main menu whenever attempting to do network mode, however, whenever he does just enable networking, it seems to blackscreen freeze. How can we get him to successfully use networking mode?

Seems to be same issue as: #9623

**Comment by unknownbrackets** [comment] 2018-12-04 02:14
This issue is being closed as a duplicate of #9623.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-12-04 02:14 UTC
Labels: Networking / adhoc
