### ISSUE TITLE
Graphic, speed very bad on samsung devices after update android 6.0

### ISSUE THREAD

**Issue by Alien1204** [hrydgard/ppsspp#8776] opened 2016-05-27 11:08 UTC

**Comment by asbel123** [comment] 2016-05-29 02:09
i trying tell u now u beleve me i  give the discreption on  the other issue u closed alien
my speed of ppsspp is not good to play 2d game speed is like samsung galaxy s4 snapdragon 600.

old firmware 5.11 is fullspeed to play ppsspp but one game u cant play is suikoden 3d version u get white screen on samsung galaxy s6 edge i am in new firmware 6.0.1 it fix white screen issues sukioden 3d version perfect its werid is speed is crap its not like old firmware i tried latest build from orphis i need help this ppsspp is crap. 

 i have to wait samsung galaxy s8.

**Comment by unknownbrackets** [comment] 2016-05-29 02:31
Closing as a duplicate of #8730.  Not sure what the point of closing one issue and creating another one is.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-05-29 02:31 UTC

**Comment by Alien1204** [comment] 2016-06-18 10:49
Ur s6 still lagging wit pspspp ???
Vào 29-05-2016 09:09 AM, "asbel123" <notifications@github.com> đã viết:
