### ISSUE TITLE
Newest version causes crashes when loading games from external drive/USB on Xbox

### ISSUE THREAD

**Issue by Crosa1933** [hrydgard/ppsspp#15346] opened 2022-01-24 23:08 UTC
### Game or games this happens in

All

### What area of the game / PPSSPP

N/A

### What should happen

It shouldn’t crash

### Platform

Windows

### Mobile phone model or graphics card

-

### PPSSPP version affected

v1.12.3-759-g5a6bf8b43

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-01-25 02:33
I'm able to load content from other storage just fine on Windows.  We just ask Windows for the file data, we don't treat storage devices in any special way.  Whether it's an SSD, HDD, remote file share, USB stick... it's all treated the same way.

If you're getting crashes, it's probably caused by something else.  There are a few ways to validate this:

 * You said newest version, but you didn't say what older version worked.  Did you try an older version to see if it still works?  Maybe it's an issue on your system, and the old version doesn't work anymore either.
 * Your storage may have developed issues.  Try checking the CRC of the disc in question, to make sure it's still valid.
 * Is it really crashing while loading, or shortly after loading?  It could be that you've enabled a setting that is causing PPSSPP to crash, or that it's your audio or graphics drivers crashing.
 * Try updating all your drivers.
 * Do other games work?  Try the cube demo.  Does it only fail when loaded from your USB storage?

If you find that it only crashes when PPSSPP loads games from your USB storage, it's very likely that you have an issue with your USB controller or cable.

-[Unknown]

**Comment by Crosa1933** [comment] 2022-01-25 02:37
So there was no option for Xbox one/series consoles and that’s where the
crash is happening. I (erroneously) selected windows because it seemed to
be the closest option. I felt like selecting other was almost like giving
no info at all. All previous versions worked fine.

**Comment by unknownbrackets** [comment] 2022-01-25 03:07
It's very strange if v1.12.3-755-g130b7d71a worked and v1.12.3-759-g5a6bf8b43 stopped working, because that change affected code that wouldn't even be used on Xbox.  A specific version number of the last working version would help.

-[Unknown]

**Comment by Crosa1933** [comment] 2022-01-25 14:47
V1.11.3-1636-gb1b761290 is the last working version. Hope that helps.
Appreciate all of the correspondence so far. Thanks

**Comment by unknownbrackets** [comment] 2022-01-25 14:59
https://github.com/hrydgard/ppsspp/compare/b1b761290...5a6bf8b43

This is a range of 863 commits, changing 471 files.

It does include clip and cull distance changes, maybe those misbehave on Xbox?

If it's possible to try a couple more versions, it would help narrow it down.  One about ~400 commits ago would have the range, since it'd tell us which of the 863 commits didn't cause it (the number "-759" in the version is commits since that stable release.)  The more we can narrow it down, the better.

I was expecting maybe to see significant Path changes, since that wasn't long ago, but it looks like the working version was after those.  So doesn't seem like it's caused by that.

-[Unknown]

**Comment by Crosa1933** [comment] 2022-01-25 19:33
Don’t have access to other versions unfortunately. But after
troubleshooting with some colleagues one of them came up with a temporary
solution. Editing the ini file on a PC allowed us to set the current dir to
D:/ROMS/Handheld - Sony/
And it worked. Even displayed thumbnails in the main page when you load up
PPSSPP. Please let me know if you guys can figure anything out. The method
above is kind of neat though. Anyway, thanks for your time.

**Comment by dominater01** [comment] 2022-04-14 07:19
heres video on this issue https://www.youtube.com/watch?v=tVgw4bdoULA

**Comment by hrydgard** [comment] 2022-04-14 07:40
Right, I'll get to it soon.

**Comment by hrydgard** [comment] 2022-04-16 08:29
I believe this is fixed now, please test.

**Comment by GABO1423** [comment] 2022-04-16 18:13
@hrydgard I decided to make a build based on the latest master branch to test this on my Xbox Series X, and can confirm that the issue is indeed fixed. This can be closed now.

**Comment by hrydgard** [comment] 2022-04-16 18:14
Thanks for testing!

**Comment by Crosa1933** [comment] 2022-04-16 18:14
Thanks guys I appreciate the hard work!

**Closed by hrydgard** 2022-04-16 18:14 UTC
Labels: No Feedback / Outdated?
