### ISSUE TITLE
TIL that CTRL + W crashes entire emulator - 1.11

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#14095] opened 2021-02-09 16:44 UTC
### What happens?
When closing game on PPSSPP using Pause [CTRL +B],entire emulator just crashes

### What *should* happen?
Emulator should NOT crash when CTRL + W is pressed

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Windows 8.0
Direct3D 9/11
Intel (HD) Graphics?

**Comment by unknownbrackets** [comment] 2021-02-09 17:13
This issue is being closed as a duplicate of #11255.  This is actually intentional.  Try pressing Ctrl-W in a web browser.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-02-09 17:13 UTC

**Comment by hrydgard** [comment] 2021-02-09 17:26
Well, Ctrl-W is a bit drastic indeed - it probably should require confirmation.
