### ISSUE TITLE
Game specific issue: - Armored Core: Silent Line crashing on specific mission, cannot continue

### ISSUE THREAD

**Issue by gannon345** [hrydgard/ppsspp#8273] opened 2015-12-15 04:41 UTC
Armored Core: Silent Line crashes on mission "Elephant" regardless of settings. Attempted with all speedhacks enabled, and all disabled as well, no change. I've also attempted with multiple versions of the emulator to the same result.

I have both a save file before the mission, and a save state at the launch prompt for the mission. I couldn't upload it (the files are zipped but Github won't allow the upload). Feel free to contact me for the files.

UPDATE: seems the same freeze occurs during the first mission of Armored Core: Last Raven, right at the beginning of the game. May be a related issue, I think the games run on the same engine (save data from AC3 and AC:SL is transferable to Last Raven).

**Comment by daniel229** [comment] 2015-12-15 06:14
duplicate of https://github.com/hrydgard/ppsspp/issues/5999

**Closed** 2015-12-15 06:22 UTC
