### ISSUE TITLE
MGS Peace Walker stuck at loading screen

### ISSUE THREAD

**Issue by BennyBeah** [hrydgard/ppsspp#6592] opened 2014-07-20 12:00 UTC
When I select Mission Selector the game remains stuck at the loading screen with the little logo at the bottom

Using 0.9.8-1662

**Comment by unknownbrackets** [comment] 2015-03-03 06:55
All that completely useless discussion aside, I'm still unclear.

If you start over with a completely brand new fresh ppsspp install, with a59d8b5c1f3b50d672937e5b134cd485da736a48 included, and delete all savedata/installdata/anything that isn't the iso or a brand new fresh copy of ppsspp, and then you install it, does that commit make it crash?  Or do you need to not burn the old data with fire to get this problem?

Just wondering.  But, again, if only the demo cares about that (the boss has been fixed), maybe we just forget it and close this issue?

-[Unknown]

**Comment by ppsspp213** [comment] 2015-08-29 18:39
Stuck for me on win x64 build with both win7 & 10 pro, tried the usual jit, fastmem, multithreaded off but doesn't go in-game.
GPU: NVS 4200M, Intel HD 3000
CPU: i5-2520M, 2nd gen Sandy Bridge, Dual Core (2.5 - 3.2Ghz Turbo Boost)
RAM: 4GB

**Comment by thedax** [comment] 2015-09-19 17:58
A year later, and I still can't reproduce this. I still suspect bad ISOs for those affected.. :/

**Comment by thedax** [comment] 2015-09-19 18:31
Okay, I managed to reproduce this, but not in the ways they've said. I had to start a completely new game with no save or install data, and then install the "full" data, play through the first mission, then it hangs after the interactive cutscene, spinning the loading logo forever. I added back in the anti-cheat hash stuff that @unknownbrackets  asked for while testing this. I'll test again without it in a while, I have to go grocery shopping.

**Comment by ppsspp213** [comment] 2015-09-19 21:21
Save states will you get you in-game but it hangs when you move  snake with DynamicRecompiler off.

**Comment by ppsspp213** [comment] 2015-09-20 06:44
^ above is true for windows only, Android is able to grind along at 1-5fps whilst DynamicRecompiler is off. I guess you need at least a quad core cpu to run this whilst DynamicRecompiler is off, my i5-2520M just sits their doing nothing vs the APQ8064 grinds away at 3fps.

**Comment by bababoombatman** [comment] 2018-10-31 07:41
Maybe we can close this one, it seems a repetition of #11514 to me and that issue has been resolved ☺

**Comment by hrydgard** [comment] 2018-10-31 08:41
Would be good to figure out why savestates break it, but it could be some realtime clock comparison or something that gets screwed up, and that's hard to do anything about..

**Closed by hrydgard** 2018-10-31 08:41 UTC
