### ISSUE TITLE
Sonic Rivals 2 Issue 

### ISSUE THREAD

**Issue by TKC2802** [hrydgard/ppsspp#8005] opened 2015-09-26 14:03 UTC
I tried to play sonic rivals 2, but when I start the race, the whole thing just lags badly and the screen turns very bright. This is in buffered rendering mode. When I changed to non-buffered rendering mode, the whole thing ran smoothly. However, the screen turned totally black instead. I am using redmi 1s. Is there any way to resolve this problem? Frameskip doesn't work too; it just makes it even laggier and more impossible to play.

**Comment by hrydgard** [comment] 2015-09-26 14:09
Duplicate of #6117 , already reported.

**Closed by hrydgard** 2015-09-26 14:09 UTC
