### ISSUE TITLE
I have an Amazing news about JIT and how to fix micro stutter finally.

### ISSUE THREAD

**Issue by iOS4all** [hrydgard/ppsspp#9253] opened 2017-01-30 03:20 UTC
@hrydgard hi there I just want to tell you the waiting for fix micro stutter on iOS is over because the creator of the jailbreak iOS 10 is completely defeated KPP (kernel Patch Protection) and he able to get JIT functionality works even without any patches in kernel. I said that when I was on iOS 8.4 by TaiG jailbreak I didn't notice any micro stutter this is because of the TaiG jailbreak includes JIT. Now the time repeated itself. So all you have to do is bringing back the old JIT in order to get the new JIT functionality like before. For more information just see his link in Reddit. He also added a deb file to let people test JIT also including a jailbroken iOS 9.3.3.

This is his link
https://www.reddit.com/r/jailbreak/comments/5qy2x0/beta_jitsupport_kernelless_jit_support_for_ios_9/

He said it will helps emulation projects to increase the performance a lot. So if we take this JIT it'll also fix the micro stutter forever.

**Comment by hrydgard** [comment] 2017-01-30 09:37
I'm not convinced that the "micro stutter" issue is at all related to the "new" (avoiding WX) Jit, but this seems useful.

We need a way to detect it and a way to load it dynamically, so that the emulator will still run on devices that don't have this thing installed. Unless we can of course integrate it directly, which would be nicer. There aren't many details in the thread...

**Comment by iOSSOi** [comment] 2017-01-30 10:58
The micro stutter is still there even after disabling the JIT,  that's why I'm pretty convinced JIT isn't the source to the micro stutter. @hrydgard   Please correct me if I'm wrong ,  I am no developer = )

**Comment by iOS4all** [comment] 2017-01-30 13:01
@hrydgard thank you for replying. I meant here this is an old JIT implementation like when we on iOS 8.4 by TaiG jailbreak. Which is running all games 30/60 fps without even a little drop of the speed. The speed is very stable. I know you said that a long go. (The new JIT maybe we'll see a micro slowdown) so that's why I suggest at least to bringing new edit version of ppsspp and of course including this old JIT. Believe me if you do tha you'll notice all problems are gone specially micro stutter forever. As you see while ago we could implement the new way of JIT and from this JIT problem is micro stutter.

So please as a try after editing any version of ppsspp and try implement old JIT in order to see the results. For more information this is his link in GitHub:
https://github.com/kpwn/yalu102

Good luck.

**Comment by iOSSOi** [comment] 2017-01-30 13:06
@iOS4all what? My friend, please try to understand. Enabling or disabling JIT,  it doesn't matter, the micro stutter still appears. How would implementing the old JIT help?

**Comment by iOS4all** [comment] 2017-01-30 13:34
@iOSSOi no this is not correct at all. I'll correct your information.
The micro stutter is happening because of the new way of JIT. And even @hrydgard said this new JIT maybe you'll notice a little slowdown (maybe he refers to this micro stutter. Unlike an old JIT which can you get it after aa good jailbreak like TaiG. Long ago when I was on iOS 8.4 and after jailbreaking by TaiG I used ppsspp on it. And believe me there's no micro stutter AT ALL. All games running on stable speed 30/60 fps. so now after this solid jailbreak iOS 10 we can get JIT functionality like before.

The conclusion:
There's two kind of JIT
1- an old one which is implemented after a solid jailbreak which has free bug.
2-the new JIT which is implemented recently and it has a very known issue which is causing of micro stutter.

I hope you're now understand everything about this stuff.

**Comment by hrydgard** [comment] 2017-01-30 13:40
"The micro stutter is happening because of the new way of JIT"

I doubt this. I believe what you call microstutter is caused by something else, but I can't figure out what.

There are not two kinds of JIT, there's just two kinds of code memory management, what we call "WX-exclusive" which is needed for newer iOS versions and "normal" which is what all other platforms used, and what we previously used on iOS. This requires RWX memory which is no longer available.

**Comment by iOS4all** [comment] 2017-01-30 13:48
@hrydgard thank you for replying 

The creator of iOS 10 jailbreak is this a functionality JIT which we can take it if we completely defeat KPP and it has RWX unlike the new one.

Just see his twitters 
![img_0003](https://cloud.githubusercontent.com/assets/24762554/22425341/b499de84-e70b-11e6-87f2-d837b7257c3c.PNG)

It's interesting isn't it?

We could also have RWX like before. As I said we get all that functionality because of fully defeated KPP finally.

**Comment by iOSSOi** [comment] 2017-01-30 13:52
@hrydgard @iOS4all now you heard it from man himself,  he doubts the micro stutter is caused by the JIT. Can you (iOS4all aka Fadi555) please stop talking about how the JIT is the cause, please!!

**Comment by iOS4all** [comment] 2017-01-30 13:57
@iOSSOi I just give him some clues about this stuff. Don't worry about bothering him he is a creator and it's normal to give him issues and fix that. Go and see how many issues there? And how many people talk about their issues it's normal bro.

You most stop thinking in negative way. At least this issue is related to you as well. Because you have an iOS device.

**Comment by iOSSOi** [comment] 2017-01-30 14:20
@iOS4all @hrydgard "Don't worry about bothering him he is a creator and it's normal to give him issues and fix that"

 Boy, we do not create issues to bother any developer!! We create issues because we want to help developers!  It doesn't matter if I think in a positive way,  me  nagging about something that is wrong with this emulator again and again wont help anyone.

**Comment by iOS4all** [comment] 2017-01-30 14:34
Anyway I just give him a very known clues about this thing.
I won't saying anything but you'll see the results. You'll said wow it fixed.
Because RWX is implementing here as well as an old JIT.
So that's enough even for retroarch pcsx dynarc core.

**Comment by LunaMoo** [comment] 2017-01-30 14:43
We really don't need X number of issues for same thing just so you can spam and nag Henrik @iOS4all / fadi / whatever.
 Closing as duplicate of #9197, the issue is opened nobody needs to be reminded 11 times a day about it.

**Closed by LunaMoo** 2017-01-30 14:43 UTC

**Comment by Anuskuss** [comment] 2017-02-01 01:43
@LunaMoo You should unlock #9197 again so we can discuss there :smiley: 

Anyway, I think it could be worth a try to implement this and see if something changes.
```cpp
jit_mach_vm_allocate(mach_port_t task, mach_vm_offset_t* address, mach_vm_size_t size, int flags)
```

Users would have to install the `.deb` to run the the library though.

**Comment by LunaMoo** [comment] 2017-02-01 02:24
Done, just  behave this time, I closed the discussion due to insults flying around, someone else removed them later on.

 And really to all iOS users - remember nobody here has any interest in braking iOS version every X months nor cause any weird behaviour, all of that comes from apple OS updates and it might not always be possible to fix it and even if it might take months, it's not exactly first time and quite likely not last, just get used to it already;p.

**Comment by iOS4all** [comment] 2017-02-01 02:51
@Anuskuss thanks for sharing this idea. It could fix this issue. Because @hrydgard said this micro stutter was happened because of avoiding RWX and the latest iOS 10.2 as well as other jailbroken versions are now able to use JIT and RWX again like before. So bringing this back to ppsspp it could really useful to fix it permanently.

@LunaMoo I know maybe there's a few devs here how interesting to work on iOS version of ppsspp but as you can see this project is for all platforms including (win, mac , Linux , raspberry ,iOS ,android)
so it's very nice to work with all platforms.
Thank.

**Comment by Anuskuss** [comment] 2017-02-01 03:08
So the situation right now is
**< iOS 8:** RWX JIT (but uses WX)
**= iOS 9:** WX JIT only
**= iOS 10:** (possibly) RWX (but uses WX)

I'm fine with always using **W^X** on **iOS**. But the thing is that **iOS 8** and lower can use the **normal JIT** just fine. Also every device capable of running **iOS 9** can also run **iOS 10**, and most of the **iOS 9** users could (and should) upgrade to **iOS 10** and keep the jailbreak.

**qwertyoruiop** said that the function behaves just like `mach_vm_allocate` except that it actually returns **RWX pages**, so (and I'm no developer) it shouldn't be super hard to implement it (if there's even demand).

We would end up with **WX** on **> iOS 9** and **RWX²** on **iOS 10**, but if we would simply ignore **iOS 9**, and add a simple check if the `.dylib` is loaded and apply the prefix (if it behaves 100% like the old function), we would have clean code and everything should work.

**Comment by iOS4all** [comment] 2017-02-01 15:56
@Anuskuss thank you very much for this helpful information. We'll wait patiently for @hrydgard to see your info and do what's is good for this.
Thanks a lot.

**Comment by dankcushions** [comment] 2017-02-01 16:20
enough is enough, can someone please block fadi/ios4all from this repo? how many 100s of comments about the same issue? none of them helpful, but all of them sent to ~350 people. even adding them to personal blocklists isn't enough because other people reply, etc.

their old account was banned from github for this kind of thing. they won't start behaving now.

**Comment by UeeKui** [comment] 2017-02-01 16:50
Yeah that's enough @dankcushions you have to stop saying that you're lack of feeling 😡 What's wrong if someone talks about some issues here even if he reply same issue? Maybe it could not fixed yet who knows? Dude you must be more behave than that.

**Comment by Orphis** [comment] 2017-02-01 17:23
The problem is that he can just create another account...

**Comment by iOS4all** [comment] 2017-02-01 17:39
Well you're right guys. I talked about this issue many times. so I was thinking about fixing it. But I guess I have to stop talking about this issue forever. And just leave this issue for @hrydgard if he could it's ok if he can't it's ok as well. So I have to say sorry for all you guys for being not very nice to talk about this issue.
🌹

**Comment by kpwn** [comment] 2017-02-03 15:15
First of all: iOS4all is fucking annoying. He opened multiple pull requests on yalu over this.

Second: JITSupport provides RWX support by MAP_JIT means, without however needing the entitlement due to some other magic. This is should work on both iOS 9 and 10, and requires no patches except the ability to make jitsupportd run (i.e. codesign).

I am honestly amazed that after a year that @comex suggested this, people went with hacking up the JIT engine to support W^X rather than an extremely easy fix. Anyhow, JITSupport abstracts this for you with an extremely easy to use API. 

Additionally, I believe that future jailbreaks will move on to things similar to this for all patches, not necessarily just vm_protect. This is because it allows jailbreak developers to provide a unified, stable API to handle these cases. Also, I can definitively see how having to mprotect every time can slow this down (especially on Yalu102, where syscalls have an additional overhead due to KPP bypass trashing at least 1 TLB entry (worse on some devices, however, where both the instruction cache and the TLB are wiped)).

**Comment by hrydgard** [comment] 2017-02-03 16:22
@kpwn thing is, it's not at all clear how to best use it. We must obviously still work even if JITSupport is not installed, and I have no idea how to detect and load it dynamically.

Also if it's so easy, where's the source code to JITSupport so we can just integrate it directly?

**Comment by kpwn** [comment] 2017-02-03 16:30
mmap with MAP_JIT on a process with dynamic-codesign in entitlements. 1 LoC.

**Comment by kpwn** [comment] 2017-02-03 16:31
Anyhow, if you give a look at the jitsupport thing, you can simply dlopen the path where the dylib is installed at, and possibly fall back to either RWX (pre-9) or just avoid jit entirely.

**Comment by hrydgard** [comment] 2017-02-03 16:35
Pull requests or links accepted for the entitlements thing, I really have no idea how that stuff works. iOS has not been a prioritized platform for me for obvious reasons of Apple being hostile to emulators.

**Comment by kpwn** [comment] 2017-02-03 16:36
I suggest anyway to rely on JITSupport for reasons of providing a stable, portable across jailbreaks API.

This should future proof the entire deal.

**Comment by kpwn** [comment] 2017-02-03 16:43
An idea would be to either jit_mach_vm_allocate or mach_vm_allocate (both use the same argument types and return value, so you can just use a function pointer and simply define some stub eg. try_jit_mach_vm_allocate that does the 'right' thing based on availability) passing RWX on both, then checking resulting protection (many mach APIs can be used for this), and accordingly fall back to W^X jit when required. It should be a very minimal change code wise, I'd expect.
