### ISSUE TITLE
Qix++ (Japan) (v1.02) stuck at loading screen after one stroke level is completed

### ISSUE THREAD

**Issue by Cibomatto2002** [hrydgard/ppsspp#13724] opened 2020-11-29 15:23 UTC
can't get past loading a save game

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP  1.10.3

  Operating System
	Windows 10 Home 64-bit
CPU
	AMD Ryzen 7
	Summit Ridge 14nm Technology
RAM
	16.0GB Dual-Channel Unknown @ 1197MHz (17-17-17-39)
Motherboard
	Dell Inc. 0VYXHD (AM4)
Graphics
	C27F390 (1280x720@60Hz)
	4096MB ATI AMD Radeon RX 580 (Dell)
Storage
	931GB Seagate ST1000DM010-2EP102 (SATA)
Optical Drives
	No optical disk drives detected
Audio
	High Definition Audio Device

**Comment by hrydgard** [comment] 2020-11-29 22:45
Duplicate of #9466 

Fixed in the latest builds, see https://buildbot.orphis.net/ppsspp/

**Comment by nassau-tk** [comment] 2020-11-29 23:16
@hrydgard 

Really?

@Cibomatto2002 says "Can't load the old save data."

**Comment by hrydgard** [comment] 2020-11-30 00:40
Hm, maybe confusing the issues.

**Comment by Panderner** [comment] 2020-11-30 08:02
@Cibomatto2002 are you using latest build of PPSSPP?

**Comment by nassau-tk** [comment] 2020-11-30 08:19
@Cibomatto2002 
save issue was solved on v1.10.3-695.
https://github.com/hrydgard/ppsspp/issues/8214



You must not install form GoogPlay or Appstore.
You must download & install from here!
https://www.ppsspp.org/downloads.html
If you already installed latest build then you should write more detail.

![image](https://user-images.githubusercontent.com/48179091/100584419-6f606580-332f-11eb-9279-fa6ce71f507b.png)
![image](https://user-images.githubusercontent.com/48179091/100584776-e695f980-332f-11eb-9b03-79a79343ba7f.png)

**Comment by Cibomatto2002** [comment] 2020-11-30 15:02
i'm not using the nightly build I will try them out.

**Comment by Cibomatto2002** [comment] 2020-11-30 16:05
Saves load now but I see a new problem the game is stuck at now loading.  I made a savestate and a video.Emulator  v1.10.3-1269-gb60250fca

[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/5617028/PPSSPP_STATE.zip)

https://www.youtube.com/watch?v=LVStA66LXro

**Comment by Panderner** [comment] 2020-12-01 03:32
Yes @Cibomatto2002 it seems the game stucks at loading screen after one stroke level is completed.

**Comment by nassau-tk** [comment] 2020-12-01 04:39
**[Timing of switc to Loading Screnn]**
![image](https://user-images.githubusercontent.com/48179091/100697877-814b1280-33da-11eb-93c1-c91ff6633c40.png)

**[And,The after]**
![image](https://user-images.githubusercontent.com/48179091/100697950-a2136800-33da-11eb-8c87-98cc6edd1a5f.png)

**Comment by nassau-tk** [comment] 2020-12-06 15:53
@Cibomatto2002 

You should "Edit the Title" to correctlly detail.

**Comment by nassau-tk** [comment] 2022-12-16 05:33
This issue still happen on v1.14-2.

**Comment by sum2012** [comment] 2023-10-16 12:57
The youtube I cannot see now.
https://www.youtube.com/watch?v=LVStA66LXro
What mean  "one stroke level "?

**Comment by sum2012** [comment] 2023-10-17 12:46
Thanks.
The log doesn't have unusual thing
ppsspp-v1.16.6-235-g3611b4d94-windows-amd64 log
https://gist.github.com/sum2012/9e29ff8072713398b2c5f337ae25a299
Just a note : Jpcsp emulator (another PSP emulator) can run the game mode.

**Comment by sum2012** [comment] 2023-10-17 12:54
e can fix it by using Simulate UMD Delay
![1](https://github.com/hrydgard/ppsspp/assets/2177532/da2cc925-e0bc-43d7-99b2-77ad1c21c594)
![2](https://github.com/hrydgard/ppsspp/assets/2177532/12ccbe70-8297-4a33-ad60-33a1f8cc6bc8)

**Comment by hrydgard** [comment] 2023-10-17 13:26
Ah, good reminder.

I added a compat.ini entry under [ForceUMDDelay], should take care of it from now on.

**Comment by sum2012** [comment] 2023-10-17 13:41
let @nassau-tk to confirm ,then close.
Anyway , I have another idea to fix.

**Comment by nassau-tk** [comment] 2023-10-17 14:07
Yes, it's working on UMD Delay.

**Comment by sum2012** [comment] 2023-10-17 14:17
Thanks @nassau-tk confirm

**Closed by sum2012** 2023-10-17 14:17 UTC
Labels: I/O
