### ISSUE TITLE
Sengoku Hime 4 black screen

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6374] opened 2014-06-19 09:54 UTC
It's not hanging,we can hear sound.A lot of files can not be found in the log.the video was not black before,video is black since https://github.com/unknownbrackets/ppsspp/commit/2042672ec718b177268f590c9f10e43a6fbf6a00

info log:
https://gist.github.com/daniel229/22561bdfcc55fa8c603d

debug log(rename jpg to rar):
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3326036/8fda4b26-f797-11e3-9772-dda57f3645fc.jpg)

**Comment by daniel229** [comment] 2015-01-09 07:40
The game crashes or get invalid addresses since https://github.com/hrydgard/ppsspp/commit/28b3b841d57158800d7f60983bc8522445183720

**Comment by unknownbrackets** [comment] 2015-01-09 08:02
Is that even with an uncompressed iso?  There must be something pretty wrong for that to happen.

-[Unknown]

**Comment by daniel229** [comment] 2015-01-09 08:09
it's an uncompressed iso

**Comment by daniel229** [comment] 2015-01-09 08:15
run the build 0.991-729 in VS2013 debug get the error
![01](https://cloud.githubusercontent.com/assets/3481559/5677003/b8b30212-981a-11e4-8d41-ae212166cf3e.png)

**Comment by unknownbrackets** [comment] 2015-01-09 16:45
Can you get a stack trace in the latest git build?

On this line in Core/Loaders.cpp:
```c++
return fread(data, bytes, count, f_);
```

I suppose that either `bytes` or `count` are silly unrealistic numbers.  I'm wondering where it's trying to read that many bytes, which the call stack will tell me.

-[Unknown]

**Comment by sum2012** [comment] 2015-01-09 23:10
v0.9.9.1-1442-g534bf6d Windows 64 bit I only get invalid address
debug log:
https://gist.github.com/sum2012/2b3057e14e6ede29d5a2

**Comment by sum2012** [comment] 2015-01-09 23:17
@unknownbrackets 
v0.9.9.1-1442-g534bf6d  stack trace 
turn of io mutithread to reproduce
![1](https://cloud.githubusercontent.com/assets/2177532/5688965/9b0881f0-9898-11e4-9ec0-628b6e6c67b9.png)

**Comment by unknownbrackets** [comment] 2015-01-09 23:37
Hmm.  That `size` is `0xffffffff00036941`.  That doesn't make much sense, since presumably that means the original size was `0x00036941`, so why did it sign extend negative?  If it was negative it would have to be `0xffffffff80036941`... wouldn't it?

Anyway, clearly it's not handling negative sizes correctly but something odd is happening here.

-[Unknown]

**Comment by sum2012** [comment] 2015-01-09 23:47
I have left the home

**Comment by daniel229** [comment] 2015-01-10 01:14
The e
![01](https://cloud.githubusercontent.com/assets/3481559/5689828/e5bb5d3e-98a8-11e4-97fe-8fbce5335ce8.png)

**Comment by unknownbrackets** [comment] 2015-01-10 02:38
Any luck with #7304?

-[Unknown]

**Comment by daniel229** [comment] 2015-01-10 02:53
Fixed in https://github.com/hrydgard/ppsspp/pull/7304 .

**Comment by unknownbrackets** [comment] 2015-01-10 03:53
So we're left with things caused by uninitialized values / etc. that rely on stack clearing / something by usermode libraries like sceFont and scePsmf, etc., which is causing all sorts of things to be black/missing it sounds like. (just to keep the issue on track.)

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-03-01 05:07
In the functions from the JPCSP commit that have stackUsage other than 0, can you try this at the end of the func?

```c++
Memory::Memset(currentMIPS->r[MIPS_REG_SP] - stackUsage, 0, stackUsage);
```

I just want to make sure our problem is the same problem that was fixed here.  I plan to write pspautotests for sceFont and scePsmf to see what stack they zero exactly, and so we can automated test it.

-[Unknown]

**Comment by sum2012** [comment] 2015-03-01 05:30
@unknownbrackets Yes it fixed with this commit.
https://github.com/sum2012/ppsspp/commit/aa245edb9a45eed9e90babd07d32fff24510d33e

![2](https://cloud.githubusercontent.com/assets/2177532/6429578/102cc96e-c017-11e4-8133-a34eeae0f9b0.jpg)

**Comment by daniel229** [comment] 2015-03-01 08:38
Look playable with @sum2012 's patch

**Comment by hrydgard** [comment] 2015-03-01 11:31
OK. Might as well do a generic thing like JPCSP where you can mark functions with stack usage, so we don't have to add code to each one. I'll get on that later.

**Comment by unknownbrackets** [comment] 2015-03-01 22:38
For sceFont at least, definitely many values other than 0 are written.  sceFontNewLib() uses the most so far at 1440 bytes.

-[Unknown]

**Closed** 2015-03-05 09:37 UTC
