### ISSUE TITLE
Prince of Persia Rival Swords - Black Screen!

### ISSUE THREAD

**Issue by jsarathchandra** [hrydgard/ppsspp#7314] opened 2015-01-11 11:46 UTC
Hello there... Just wanted to point out that Prince of Persia Rival Swords has become unplayable with the latest versions of PPSSPP...

**Comment by hrydgard** [comment] 2015-01-11 12:40
Any idea which version was the first build where it wouldn't play?

**Comment by jsarathchandra** [comment] 2015-01-11 15:19
I just downloaded this github version and it didn't work...

ppsspp-v0.9.9.1-1405-g61d43f1-android

**Comment by hrydgard** [comment] 2015-01-11 16:46
Do you know an earlier version on which is does work? Preferably the last one? That way we can pinpoint when it broke and hopefully find a fix faster.

**Comment by 007flawless** [comment] 2015-01-11 18:24
I think it's an Adreno thing.. I tested Rival Swords on an HTC One M8 device some weeks ago and it had Black Screen Issues.. U could see only the HUD.. But on my PowerVR based device, everything shows well, and plays well.. So I think it's an Adreno issue

**Comment by brujo5** [comment] 2015-01-11 18:37
https://github.com/hrydgard/ppsspp/issues/6399

for some razon happend only in powervr and afreno

**Comment by jsarathchandra** [comment] 2015-01-12 02:18
I'll test a few github builds and let you know...
But it might take some time... Is that Ok?

**Comment by unknownbrackets** [comment] 2015-01-12 02:44
Sure, but just to say, the fastest way is to go by halves.  For example, let's say that you try v0.9.9.1-840-ga19d0b6, and it works.  That means the problem is between ~1481 and ~840.  That's about 640 changes to test, sounds like a lot, right?

If you test the one in the middle of those two, you can rule out half of them in one test.  After that, you just try half way between the next two.  Doing it this way, you can find the problem in about 10 tries.  Only someone with the game can do this - I don't have it, so I'm left with staring at the 640 different changes.

That being said, if it is the depal thing, then all we know is something is wrong.  Before the change that enabled depal, it was getting a compile error.

-[Unknown]

**Comment by jsarathchandra** [comment] 2015-01-12 04:13
Thanks for the tip @unknown!

**Comment by jsarathchandra** [comment] 2015-01-12 04:14
I have the game... Will test and tell you... I'm currently out now... Will start doing it in sometime today... 😀

**Comment by jsarathchandra** [comment] 2015-01-12 06:29
@unknown @hrydgard @brujo5

Just for your information, I have a Xiaomi Mi3 Indian version with Adreno 330 GPU... I have it rooted...

**Comment by jsarathchandra** [comment] 2015-01-12 09:04
![screenshot_2015-01-12-14-23-56](https://cloud.githubusercontent.com/assets/10485112/5700683/8ce2324e-9a67-11e4-8c83-6fbaac4f7200.png)
Hey guys, just a quick update. Non of the versions from 323 (last version said to be working from the forums) till 133x show any improvement (including 323)... Plain black screen... Also there is no audio in the movie sequence. But I can hear the audio in game. Another weird thing I noted was that when I switched on Software Rendering, it showed the prince covered in a pattern of some thumbnail. Not sure what that is. For your information.

**Comment by jsarathchandra** [comment] 2015-01-12 09:09
Looks like the prince is covered with thumbnails of the prince himself! 😂😜

**Comment by jsarathchandra** [comment] 2015-01-15 11:36
Any news guys?

**Comment by jsarathchandra** [comment] 2015-01-15 11:38
I'm unable to get it working in any of the builds! 😞

**Comment by Nekrose** [comment] 2015-01-27 16:17
Is there anyone else having the audio issue in the cinematic cutscenes? I can't seem to fix it...

**Comment by unknownbrackets** [comment] 2015-02-23 21:39
Has anything changed here with the blending change for PowerVR devices?

-[Unknown]

**Comment by brujo5** [comment] 2015-02-24 06:50
For ip5S still the same.

**Comment by leopard20** [comment] 2018-06-04 12:31
@hrydgard I think this is yet another duplicate.

**Comment by hrydgard** [comment] 2018-06-04 12:41
Let's assume that and close this.

**Closed by hrydgard** 2018-06-04 12:41 UTC
