### ISSUE TITLE
(Libretro) "Not enough free space available" if save data doesn't already exists.

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#13552] opened 2020-10-17 14:37 UTC
### What happens?
If no save data exists yet, when launching a game it will ask to create it but then say "Not enough free space available", example with Mega Man Powered Up:

![image](https://user-images.githubusercontent.com/33353403/96339710-af78cb00-1096-11eb-8566-d00d49c70124.png)

And yes, I tried deleting a few saves just to be sure, it didn't help. It happens even with an empty "SAVEDATA" folder.

No issue with standalone. And if I grab the save folder from standalone and put it in the RetroArch saves folder, the game launches perfectly fine.

I've bisected already, first bad commit seems to be 166035a87b4906e6f77e40c46b685eb683500e25.

### What *should* happen?
Save data should be created.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
i5-4670K, GTX970, Windows 10 (**edit:** just tested on my Linux VM, same issue), latest RetroArch and PPSSPP core nightlies (90ba3a2 when typing this).

**Comment by icenine451** [comment] 2022-10-21 19:28
This issue appears to still be happening. I am able to recreate it with the game Bomberman on RetroArch 1.12.0

**Comment by medeirosT** [comment] 2022-10-26 04:53
Same here

**Comment by medeirosT** [comment] 2022-10-26 08:21
Seems this issue came back, was broken here : https://github.com/hrydgard/ppsspp/commit/6db91abf171335ca7df184b162079e7fd798d77a

**Comment by bslenul** [comment] 2022-10-26 08:34
Device? OS? PPSSPP version?

Can't reproduce on Windows 10, I deleted my Mega Man save and it's created properly:

![image](https://user-images.githubusercontent.com/33353403/197976135-4421cd60-d82f-4082-b2bb-9ae0c93f8be1.png)

![image](https://user-images.githubusercontent.com/33353403/197976163-5652f4ab-0839-4496-ac26-4e272c56e438.png)

**Comment by hrydgard** [comment] 2022-10-26 08:36
Might be something that only happens on unix systems for whatever reason? reopening for investigation someday

**Comment by medeirosT** [comment] 2022-10-26 08:38
Device : Embedded ARM System
Version : 41f344398844b4596e48de1122d443c621a39864
OS : Linux

Using retroarch 1.12.0

I tried applying the patch in the commit that fixed it again, let's see if it works. I'll let you know.

**Comment by bslenul** [comment] 2022-10-26 09:16
Just tried on my Linux Mint VM out of curiosity, no issue with Mega Man and Bomberman. Can't test on the only ARM device I own however, as it still crashes on 32bit devices (#12464).

Would you mind posting a log file (enable BOTH "verbose" and "log to file" in Settings > Logging, restart RA and trigger the issue again)? Maybe it'll tell what's going on.

**Comment by icenine451** [comment] 2022-10-26 12:43
I actually tracked this down to being caused by #15437 and was able to work around it by adding a save sort core override for PPSSPP.

**Comment by hrydgard** [comment] 2022-10-26 13:17
OK, I think we can close this then, or is there some default we can chnage to make this easier for users?

**Closed** 2022-10-26 14:23 UTC
Labels: Saving issue
