### ISSUE TITLE
[PowerVR] [Android] Machi-ing Maker 3 x Tousouchuu - Menu bug

### ISSUE THREAD

**Issue by meowthed** [hrydgard/ppsspp#15913] opened 2022-08-28 02:25 UTC
### Game or games this happens in

ULJS00242 - 街ingメーカー３×凍傷中

### What area of the game

When moving from the next screen in the menu.

### What happens

Vulkan screenshot:
![Screenshot_2022-08-28-10-08-43-85_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/41223243/187054677-113c06f7-1947-4a73-a229-67cca63ddf73.jpg)
OpenGL Screenshot:
![Screenshot_2022-08-28-10-09-31-65_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/41223243/187054678-e4d5c4fc-8350-4dac-a169-f61bb68997b1.jpg)

### What should happen

It should transition fine as it did on PPSSPP emulation on Windows, as well as on real hardware like in this video.
https://youtu.be/Gcuz0Roc7MY

### Platform

Android

### Mobile phone model or graphics card

OPPO:CPH2349

(PowerVR GE8320)

### PPSSPP version affected

1.13.1

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-08-28 03:45
This looks very much like it might be depth, stencil, or alpha related.  Please try the latest git build - you noted v1.13.1 which is now many fixes behind the latest git build.

Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a 3D screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Panderner** [comment] 2022-08-28 06:04
GE dumps here:
[Title Screen.zip](https://github.com/hrydgard/ppsspp/files/9439186/Title.Screen.zip)
[Level Select.zip](https://github.com/hrydgard/ppsspp/files/9439187/Level.Select.zip)

**Comment by unknownbrackets** [comment] 2022-10-23 04:02
The title starts with a clear, and clears everything.  So it shouldn't be some prior state.

It first draws the background (which we see apparently stenciled out), and then the logo at 3/26.  When it's clearing (by the end), depth is non-zero in exactly the places we see the background.  There's no actual stencil usage.

The clear is a true clear and in throughmode, but does accidentally have depth testing enabled (should not apply.)  I can't see a reason it wouldn't clear in GLES.

The background is drawn with a lot of things enabled:
 * Depth clamp + min/max Z + reduced viewport Z... but it's throughmode anyway.
 * Cullface
 * Standard alpha blend, > 1 alpha test (texture is 100% alpha anyway.)
 * Stencil test dst.a == 0 (which it does.)
 * Color test color != rgb(0, 0, 0)

Most of these things are enabled during the clear too.  Of course, the tests shouldn't apply in clearmode.  They're also enabled for the logo, which is NOT throughmode.  But the Z should be fine.

Even forcing depth clamp, accurate depth, clip/cull distance, dual src blending, etc. off and using GLES (to best simulate this) on Windows doesn't show the same results.  I wonder if it's a bug already fixed in the latest git, or if it's some sort of weird driver bug?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2023-02-27 16:16
Can you still reproduce this issue using the recently build?
how about the performance after https://github.com/hrydgard/ppsspp/pull/16734 is merge.

**Closed** 2023-12-06 09:41 UTC
Labels: PowerVR GPU, GE emulation
