### ISSUE TITLE
PPSSPP Emulator Dante´s Inferno

### ISSUE THREAD

**Issue by Sonnebirke** [hrydgard/ppsspp#10747] opened 2018-03-19 13:46 UTC
What happens?
First, sorry for my bad english,
I want to report a problem for the PPSSPP emulator. In the game Dante's Inferno I have strong screen problems. The textures are flicking and I have a Rainbow effect in part, too.
Other games, like both God of War, work perfectly. I am using the PPSSPP 1.5.4 and have not changed any default settings. So it runs in OpenGL and buffered rendering.
Maybe someone has a clue for me to solve the problem.

What *should* happen?
?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
I 5 760 2,8 (not overclocked)
AMD 7850 2GB (Driver 02.2018)
8GB
![dante 1](https://user-images.githubusercontent.com/37542915/37599124-409f7c6e-2b84-11e8-9a3d-0ee83da63dfa.jpg)
![dante 2](https://user-images.githubusercontent.com/37542915/37599126-40c42974-2b84-11e8-8e96-a60d42f1f98a.jpg)
![dante 3](https://user-images.githubusercontent.com/37542915/37599127-40eb2dd0-2b84-11e8-8528-e3b8e767c728.jpg)

**Comment by hrydgard** [comment] 2018-03-19 14:29
Closing as duplicate of #10006, already reported.

**Closed by hrydgard** 2018-03-19 14:29 UTC
