### ISSUE TITLE
PPSSPP's fonts are too wide compared to the original system fonts

### ISSUE THREAD

**Issue by pretochines** [hrydgard/ppsspp#8380] opened 2016-01-04 09:02 UTC
Can anyone help me? I am playing Jeanne D'arc and the game screen is cropped on the right side so i can not read everything lol i tried every setting on the graphic menu and none of it make what i want. with fullscreen the game is still cropped and with the display fit option also still cropped :/

**Comment by hrydgard** [comment] 2016-01-04 09:20
What are you running on, Android, Windows? What hardware?

**Comment by pretochines** [comment] 2016-01-04 09:21
i am running os x yosemite ppsspp 1.0

**Comment by hrydgard** [comment] 2016-01-04 09:38
Oh, I think I know what this is. The fonts we use don't have exactly the same character widths as the fonts from the real PSP, and some games can't handle it properly. If you dump the fonts from flash0: on a real PSP and put them in PPSSPP/flash0 things should look right.

Can you post a screenshot so I can confirm this is the issue?

**Comment by pretochines** [comment] 2016-01-04 09:43
i think that is the problem! can you help me with that? i do not have a psp anymore so i can't access the flash0 folder. where can i find this file you're talking about to replace and solve my problem? 
![captura de ecra 2016-01-4 as 10 41 12](https://cloud.githubusercontent.com/assets/16536520/12087043/d6b34d1e-b2cf-11e5-9fc3-784efbcaf6f1.png)

**Comment by hrydgard** [comment] 2016-01-04 09:47
Well, I can't as they are copyrighted. you'll have to dump them off a PSP yourself, should be one you own.

We need more accurate free fonts...

**Comment by pretochines** [comment] 2016-01-04 10:12
yeah it's ok. now i know what the problem is. thanks. i will play it like that. EDIT: i found the fonts online :)))))) ehehehe thanks again now its all ok
![captura de ecra 2016-01-4 as 11 12 13](https://cloud.githubusercontent.com/assets/16536520/12087521/0682c3f4-b2d4-11e5-80f7-088d92a653f9.png)

**Comment by hrydgard** [comment] 2016-01-04 10:13
I'm leaving this open because it's still an issue that we need to fix.

**Comment by pretochines** [comment] 2016-01-04 10:14
ok :+1:

**Comment by unknownbrackets** [comment] 2016-01-04 15:15
This is the same as #2788, so closing as a duplicate.

-[Unknown]

**Closed by unknownbrackets** 2016-01-04 15:15 UTC

**Comment by hrydgard** [comment] 2016-01-04 15:21
Ah, I thought we had an issue like that, missed it somehow when searching though...
