### ISSUE TITLE
NFS: Most Wanted: Graphics Dust, Smoke, Lights Glitches on last update.

### ISSUE THREAD

**Issue by patocius** [hrydgard/ppsspp#15129] opened 2021-11-11 22:06 UTC
### Game or games this happens in

Tested in Most Wanted and Pulse

### What area of the game

Usually happend on lights and smoke.

### What happens

You can see a video of the issue in this link.

https://cdn.discordapp.com/attachments/869601237522337862/907711236660150272/VID_20211109_161923.mp4

### What should happen

Lights and dust must showed properly like in other versions of ppsspp

### GE frame capture

![2021-11-11 19_03_49-beta-feedback - Discord](https://user-images.githubusercontent.com/62677324/141375460-5d6ff41b-299b-447e-a2ca-c69c217bec98.png)

### Platform

SDL2

### Mobile phone model or graphics card

Anbernic 351P (351Elec)

### PPSSPP version affected

v1.12.3-182+g4d3890547

### Last working version

v1.11

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by patocius** [comment] 2021-11-11 22:49
Another related issue is when you skip buffer effects the game got unplayable, gui and graphics glitch harder than in other versions of ppssspp.

**Comment by Gamemulatorer** [comment] 2021-11-11 23:16
Related https://github.com/hrydgard/ppsspp/issues/15056?
This issue cannot reproduce in other graphic backend right?

**Comment by dhwz** [comment] 2021-11-11 23:45
Wait that's not the libretro version, that's the SDL2 frontend used in the screenshot.

**Comment by patocius** [comment] 2021-11-12 05:20
> 
> 
> Related #15056? This issue cannot reproduce in other graphic backend right?

I didnt test it in other graphic backend.

**Comment by patocius** [comment] 2021-11-12 05:23
> 
> 
> That's not the libretro version, that's the SDL2 version used in the screenshot.

Fixed the report and put it as SDL2 thx dhwz.

**Comment by unknownbrackets** [comment] 2021-11-12 05:32
Please include a GE frame dump, which is like a 3D screenshot:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You've instead attached a 2D screenshot.  That's not very helpful.

Also, there are about 1800 different changes between the versions you posted.  Without a GE frame dump, we're left guessing.  If you could try a git build in between or try the stable version (v1.12.3), that would help at least narrow it down further.

-[Unknown]

**Comment by patocius** [comment] 2021-11-12 06:08
> 
> 
> Please include a GE frame dump, which is like a 3D screenshot: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump
> 
> You've instead attached a 2D screenshot. That's not very helpful.
> 
> Also, there are about 1800 different changes between the versions you posted. Without a GE frame dump, we're left guessing. If you could try a git build in between or try the stable version (v1.12.3), that would help at least narrow it down further.
> 
> -[Unknown]

ok will try tomorrow thx.

**Comment by Panderner** [comment] 2021-11-12 08:43
Here's a GE dump:
[DUMP.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7526071/DUMP.ppdmp.zip)

**Comment by Panderner** [comment] 2021-11-12 08:44
I can reproduce this issue for me:
![Screenshot_2021-11-12-16-44-13-509_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/141437615-22775116-8b66-4a31-82d5-e91d5ec58cd0.jpg)

**Comment by hrydgard** [comment] 2021-11-12 21:08
@Panderner what's your device again? I'm having problems getting this to repro.

**Comment by Panderner** [comment] 2021-11-13 05:57
> @Panderner what's your device again? I'm having problems getting this to repro.

@hrydgard i'm using POCO M3

**Comment by unknownbrackets** [comment] 2021-11-13 06:15
Based on the positions of the artifacts (which I also don't experience), it looks like maybe draw 398/462 (or maybe 397.)

This should be a texture from RAM that shows as a light spot.  Maybe there's some interaction with creating framebuffers in RAM here or something?  Not sure if that flag is on for these games.

Another interesting thing: a VRAM texture is set at level 1, but mipmapping is not enabled.  I don't think we have a bug there in GL, though...

Anyway, the texture in question is only 32x32, so that's why I kinda suspect RAM framebuffers, the artifacting in the screenshot looks higher res than that, though it is set to wrap textures...

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-11-14 00:11
I cannot reproduce this on my phone 🤔

**Comment by hrydgard** [comment] 2021-12-07 22:34
Bisected a bit. Weirdly, the HUD text changes color from white to black, as reported in #15212, in commit 5315c404c55778b48ab7dbf41295ed3904d0ce54 .

**Comment by hrydgard** [comment] 2021-12-10 19:28
Unknown's related comment in Discord:

> I added software transform culling but I didn't actually suppress the incorrect triangle culling that happens on the split triangles
> because it'd mean passing in prim as a uniform value and I hoped it wouldn't matter...

Wait, which split triangles? you mean splitting rectangles into triangles? And the depth part of it won't be that incorrect, right? These particular rectangles don't seem to be anywhere close getting culled at the sides....

Alternatively, instead of a uniform for prim, maybe we can squeeze a bit into the vertex attributes somewhere... Although a uniform is probably fine too.

**Comment by hrydgard** [comment] 2021-12-10 19:43
To get the current master to behave like the build prior to the commit that "broke" this, comment out the following two lines in SoftwareTransform.cpp:

```
				if (tlz <= minZValue && brz <= minZValue)
					continue;
```

It's very weird to me how this change causes the effects we see, but there might be some offscreen processing step of font textures that break, or something.

**Comment by hrydgard** [comment] 2021-12-14 07:58
Closing this as fixed, since correctly culling rects/triangles is not really something that should affect this once it's working.

**Closed by hrydgard** 2021-12-14 07:58 UTC
Labels: GE emulation

**Comment by Maarcis12** [comment] 2021-12-14 14:36
thank you very much, that fixed it indeed.
