### ISSUE TITLE
gundam battle universe freezes when starting a mission

### ISSUE THREAD

**Issue by tiamat999** [hrydgard/ppsspp#8154] opened 2015-11-03 22:25 UTC
You start the mission and it freezes on the latest build

**Comment by sum2012** [comment] 2015-11-03 22:53
I test no problem
v1.1.1-194-g44be9f2 windows 64 bit
![2](https://cloud.githubusercontent.com/assets/2177532/10924291/ae67e188-82c0-11e5-984b-c7d5ca9e7834.jpg)

**Comment by daniel229** [comment] 2015-11-03 23:54
Duplicate of https://github.com/hrydgard/ppsspp/issues/7136

**Closed** 2015-11-04 00:22 UTC

**Comment by Halcon0Negro** [comment] 2016-03-01 02:29
still freezes in v1.2.1-31-g9bde45d

**Comment by unknownbrackets** [comment] 2016-03-01 03:18
It doesn't help anyone to spam duplicates.  Please stop.  Annoying people is probably not the best path to getting those people to spend their free time improving things for no other reason than to make you happier.

-[Unknown]
