### ISSUE TITLE
God Eater Burst (JP) - Crash when loading savedata. 

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#10004] opened 2017-10-07 06:37 UTC
My Device: Huawei P9+ (Android).
Settings: default.

Last work: v1.4.2-359-g4e2726f54.
First break: v1.4.2-361-gb9b2656e9.

Latest build (473) still this same issue.

![videotogif_2017 10 07_13 34 24](https://user-images.githubusercontent.com/26355472/31305457-69a127ac-ab64-11e7-984b-d0f324578064.gif)

**Comment by TediExcaliber** [comment] 2017-10-09 08:17
Maybe all version of GEB, i had same problem too when load data with US version, and iam using the latest build, sorry forgot what version

**Comment by unknownbrackets** [comment] 2017-11-07 07:11
Does the same save data load fine on Windows / desktop, or does it crash there too?

Presumably this was caused by b9b2656, which enabled lwl/lwr or ed776d8, which enabled vi2x.

-[Unknown]

**Comment by Saramagrean** [comment] 2017-11-07 07:32
I tried latest build 663 on my PC is work fine (Win 10/64 bit), this problem is found on android only.

**Comment by unknownbrackets** [comment] 2017-11-09 02:20
Seems like this is the same as #10020 and may be fixed now.

-[Unknown]

**Comment by Saramagrean** [comment] 2017-11-09 02:56
Latest build (672) is not work, The problem is the same.
//Sorry for my english. 😂

**Comment by TediExcaliber** [comment] 2017-11-09 03:21
Right, the build 672 is not work

Then i try to download and install build 668 *LIST 668 in Build Orphis*,
but when I install it, it list 663, i think its typo...

And when using that build I can Load my geb savedata >w<

Then its freezing again in 672.

Pada tanggal 9 Nov 2017 9.56 AM, "Nichakorn Permphol" <
notifications@github.com> menulis:

**Comment by Saramagrean** [comment] 2017-11-14 14:14
More detail from ADB logcat. :)
https://gist.github.com/Saramagrean/25af83b9a1951f10cfb77308f2fd93e5

**Comment by unknownbrackets** [comment] 2017-12-04 04:42
Is this savedata that was created with an old version?  It might've created wrong savedata even, unfortunately.  There's a workaround here, but I don't know if it will work:

https://github.com/hrydgard/ppsspp/issues/10020#issuecomment-344904985

Does it happen with fresh savedata?

-[Unknown]

**Comment by Saramagrean** [comment] 2017-12-04 10:16
OK. Tried with fresh savedata, It's not crash.

**Comment by Saramagrean** [comment] 2018-04-02 01:24
Try v1.5.4 & latest git build haven't encountered this issue. I think it's fixed. 😀

**Closed** 2018-04-02 01:24 UTC
Labels: arm64jit
