### ISSUE TITLE
Disappearing Character on Warriors Orochi Series

### ISSUE THREAD

**Issue by TediExcaliber** [hrydgard/ppsspp#9953] opened 2017-09-03 10:50 UTC
Help me, i have problem with this game, the character including AI and player is disappearing!

I cant attack cause that bug, i have try with Warriors Orochi 1 & 2 with both US and EU disc and all got the bug!

I have search many info about that bug, someone says, using ppsspp v09.?? Will fix the bug (sorry i forgot what version :D) but its stay disappearing, and someone say again that bug only come for Android v6 (M) but i have try to android L but the result is like M, (currently I use Re*mi 4X to play that game, please fix this sh*t bug! Thx :)

**Comment by leo412** [comment] 2017-09-08 04:06
Have you tried buffered/non-buffered rendering?

**Comment by TediExcaliber** [comment] 2017-09-10 02:45
Yeah, i have try to changing all the setting but it still like this..

**Comment by unknownbrackets** [comment] 2017-11-12 19:01
This issue is being closed as a duplicate of #9843.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-11-12 19:01 UTC
