### ISSUE TITLE
ppsspp iOS 8.x MFi controllers - Right Analog Stick - LEFT and DOWN no longer working

### ISSUE THREAD

**Issue by pralima87** [hrydgard/ppsspp#7440] opened 2015-02-06 00:37 UTC
Hi,

I would like to report that ppsspp  running on all iOS 8.x devices there is a issue with the MFi controllers.
The right analog stick LEFT and DOWN are not being recognized by ppsspp.
According to some users this was not happening in iOS 7.x.

This happens to actual MFi controllers and people using the MFi controller emulator:
"Controllers For All" (PS3/PS4/iPega).

Some topics describing the issue:
http://forums.ppsspp.org/showthread.php?tid=11837
http://forums.ppsspp.org/showthread.php?tid=14236

I hope it gets fixed eventually. 
Much thanks to all the devs!!

**Comment by sum2012** [comment] 2015-03-01 04:26
Reported in chinese ppsspp forum too
http://tieba.baidu.com/p/3609513964?share=9105&fr=share
![1](https://cloud.githubusercontent.com/assets/2177532/6429464/3d75e436-c00e-11e4-8d3e-46f0611f150e.jpg)

**Comment by sum2012** [comment] 2015-03-01 04:31
In the right analog stick,
Top -> Left and Top
Right -> Right and bottom
Left and bottom no use.

**Comment by pralima87** [comment] 2015-04-20 01:28
Any chance they will fix this?

**Comment by unknownbrackets** [comment] 2015-04-20 01:39
Pull requests are accepted.

-[Unknown]

**Comment by Bigpet** [comment] 2015-04-27 23:37
I took a quick look at the documentation and from what I saw the value range of   `GCControllerButtonInput.value`  is always between `0.0` and `1.0`

So the problem is probably here: https://github.com/hrydgard/ppsspp/blob/master/ios/ViewController.mm#L568-L574

either change the `< -0.5` to `> 0.5` or adapt the right stick handling to the same way the left-stick handling works (just with `JOYSTICK_AXIS_Z` and `JOYSTICK_AXIS_RZ` like the XB360 mapping)

**Comment by unknownbrackets** [comment] 2015-04-28 03:15
Assuming it works, replacing sounds right to me.  Map axis to axis.  Potentially it might need deadzone handling.

-[Unknown]

**Comment by Fadi5555** [comment] 2015-05-22 19:14
Is there any fix for this bug?

**Comment by angelXwind** [comment] 2015-05-22 19:25
@Fadi5555 Oh, I see what you mean now. Well, I can't test to see if the code above works or not since I don't have any controllers at all, but maybe I can compile you a deb for you to test?

**Comment by Fadi5555** [comment] 2015-05-22 19:27
I make a thread about the issue

**Comment by Fadi5555** [comment] 2015-05-22 20:26
Please I have another thing and I'm sure you can do it. Please can you make a port of Dolphin emu on our iOS devices. Android and iOS are sharing most of things. I know you are interested on iOS. actually this is our dream for long time. Please make it come true.
If you need anything like to be your own tester I'm completely ready for that.
Again I'm sorry for any trouble. Thanks again.

‏‫من جهاز الـ iPad الخاص بي‬

‫في May 22, 2015، الساعة 10:25 PM، كتب ‏Karen Tsai ‏<notifications@github.com>:‬

**Closed** 2015-05-25 02:52 UTC
Labels: Platform-specific (iOS)
