### ISSUE TITLE
[Direct3D9] No Text in Phantasy Star Portable 2

### ISSUE THREAD

**Issue by Ich2222** [hrydgard/ppsspp#7662] opened 2015-04-06 18:27 UTC
I get no text. Some text is there, but i think its only the text that is already on the image, like the "Press Start" at the beginning.

I am using the PPSSPP v1.0.1-341-g8afab3f.
With the same settings in PPSSPP v0.9.9.1 it works.

![ules01439_00002](https://cloud.githubusercontent.com/assets/11821649/7009476/cbc21ea0-dc9a-11e4-92d0-f9d66445b584.jpg)

**Comment by sum2012** [comment] 2015-04-06 22:09
Same with
https://github.com/hrydgard/ppsspp/issues/3777
@hrydgard do we need to add option to fix it ?

**Comment by unknownbrackets** [comment] 2015-04-07 01:03
Definitely not the same.  Text shows up fine for me on a desktop with an NVIDIA 9800GT.

Not only that, but the depth values for the text and its background are different and definitely not equal even at fixed 16 bit, so it is nothing related to the issue in the first game.  I said this on the forum recently too, people keep assuming the two games must draw text the same way.

Probably this is caused by some hack settings or something.  Hard to tell without any information about the device.

-[Unknown]

**Comment by zackdreaver** [comment] 2015-05-04 05:31
Still not fixed in
v1.0.1-455-gde525f3

**Comment by unknownbrackets** [comment] 2015-05-04 06:49
And still no information about the device.  Might never get fixed without that essential information.

-[Unknown]

**Comment by zackdreaver** [comment] 2015-05-04 06:55
Ups, sorry @unknownbrackets, i thought op already mention it.
OS : WinXP
Backend: Direct3d 9 (Opengl 1.4)
Build : v1.0.1-455-gde525f3

**Comment by unknownbrackets** [comment] 2015-05-04 07:22
And what video card?  You can see under System Settings -> Developer Tools.

But it sounds like it's probably an old Intel card.  It works for me in Direct3D 9 as well.  If you're on default settings, then I'm not sure exactly what it might be.  Could be some limitation in depth precision or something, e.g. lower than 16 bit?

-[Unknown]

**Comment by zackdreaver** [comment] 2015-05-04 08:47
i already checked the "Depth range hack (PSP2)", and this is my video card:
http://s15.postimg.org/5816ykvd7/MENU_00000.jpg
http://s4.postimg.org/6x0k98sf1/MENU_00001.jpg
http://s7.postimg.org/n6jx7s1nf/MENU_00002.jpg

Resolution setting: 1024x600 32bit

**Comment by Ich2222** [comment] 2015-05-04 18:14
This are my Specs. It only happens on Direct3D9, the text shows when i start it with OpenGL. But with OpenGL i get really low FPS, what makes it not very fun.

![1](https://cloud.githubusercontent.com/assets/11821649/7459059/9347754c-f299-11e4-927d-9845303142fc.PNG)
![2](https://cloud.githubusercontent.com/assets/11821649/7459060/934a672a-f299-11e4-8c07-004d3932dec4.PNG)

**Comment by zackdreaver** [comment] 2015-05-05 11:55
The text issue is not exist in "Import character mode"
gladly i have a "save" from PSP1

**Comment by thedax** [comment] 2015-05-29 02:23
I can't reproduce this with default settings and D3D9, using 1.0.1-555-gee1299b, with a Geforce GTX 670. You might want to make sure your video card driver is up to date, and that you're using default settings.

**Comment by sum2012** [comment] 2015-08-16 08:44
v1.0.1-809-gee2238d windows 64 bit
Test in OpenGL with default setting also no text
![1](https://cloud.githubusercontent.com/assets/2177532/9292591/1b9f19de-4436-11e5-8309-ccee06e8a156.jpg)

**Comment by sum2012** [comment] 2015-08-16 12:04
Fast test

good
v0.9.8-323-gf2bf8df

bad
v0.9.8-337-ge8d0cc6

**Comment by sum2012** [comment] 2015-08-16 12:27
git bisect result
this pull request https://github.com/hrydgard/ppsspp/pull/5857/
So that @unknownbrackets  same depth problem with Phantasy Star Portable 1

**Comment by thedax** [comment] 2015-08-16 17:54
I still can't reproduce this even with the latest development build, making this quite a frustrating issue..

**Comment by LunaMoo** [comment] 2015-08-16 20:29
I still can see text normally in v1.0.1-811-g14fd313 for both OGL and D3D, also can't seem to find any hack which would affect it for me.

 This issue has issues:], from above most affected people seem to experience this differently. Reminds me of adhoc connection for those games which is also working only for some people without much sense that could link the affected systems together with a chance that OS upgrading might change it, but it's actually nothing sure.

 Maybe that series has some timing issues which cause those issues differently for other people? In that case then recent windows upgrade from ms could certainly change the status of this issue for some people, just as it does with adhoc ~ althrough not necessarily for the better:].

**Comment by sum2012** [comment] 2015-08-16 21:22
@thedax @LunaMoo 
USA and Eur version no problem
Only Japan version has problem

**Comment by sum2012** [comment] 2015-08-17 22:48
Test with Phantasy Star Portable 1
same result:
USA and Eur version no problem
Only Japan version has problem

Interesting:
Phantasy Star Portable 2 Infinity -Japan version no problem

**Comment by unknownbrackets** [comment] 2015-08-18 02:04
Umm, I'm pretty sure that the US version of Phantasy Star Portable 1 does have this problem.  It's the only region I've tested for the 1st game.

-[Unknown]

**Comment by sum2012** [comment] 2015-08-19 12:10
yes,re-test US version (ULUS10410) have this problem

**Comment by sum2012** [comment] 2015-08-30 10:06
The menu has no text ,I think that is display card \ drivers 's problem

**Comment by unknownbrackets** [comment] 2015-12-30 18:36
Has this changed / improved in the latest version and with the latest video card drivers?

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-02-07 22:56
There's a good chance this is working in the latest version, at least in Direct3D 9.

Marking as no feedback for now, and will close sometime later if there's no confirmation either way.

-[Unknown]

**Comment by Zetchzie** [comment] 2016-02-07 23:10
Ill see if this issue is still present in opengl later

**Comment by sum2012** [comment] 2016-02-07 23:15
I test first.No problem in opengl and directx 9 in v1.1.1-906-g4a38a41

**Comment by Zetchzie** [comment] 2016-02-07 23:18
@sum2012 i can confirm no issues here either opengl in v1.1.1-906-g4a38a41

**Comment by unknownbrackets** [comment] 2016-02-07 23:20
Cool, closing.  If anyone's still experiencing, feel free to comment with more detail.

-[Unknown]

**Closed by unknownbrackets** 2016-02-07 23:20 UTC
Labels: Platform-specific (Windows)

**Comment by AlyceOsbourne** [comment] 2020-01-08 00:11
Hey, So I am having this problem on the switch version of ppsspp, any tips on fixing it?

**Comment by LunaMoo** [comment] 2020-01-08 00:23
Don't know anything about switch port, but you need compat.ini in the assets folder for things fixed by game specific hacks like this to work.
