### ISSUE TITLE
Analog stick issues in 1.1

### ISSUE THREAD

**Issue by Konuchi** [hrydgard/ppsspp#8028] opened 2015-10-05 12:40 UTC
When moving the stick at max distance in between a diagonal and non-diagonal direction (like between up and up-right), ppsspp is acting as if the stick is not at its maximum distance.  This makes movement in games like The 3rd Birthday very awkward as you are forced to walk instead of run in certain directions.

1.0.1 did not do this.

**Comment by hrydgard** [comment] 2015-10-05 14:18
Do you see this behaviour in the analog stick testing screen in the control setting?

I'm not aware of any major changes we've made to the joystick range, although the last release was quite some time ago...

**Comment by Konuchi** [comment] 2015-10-06 00:02
I'm using the windows version on a PC, not a touch device.  My controller is a Wii Classic controller with the Mayflash USB adapter.  This is what the test analog thing looks like when rotating the stick, keeping it at max distance at all times in 1.1: http://i.imgur.com/F04mfsH.png

This is in 1.0.1 where the problems do not occur: http://i.imgur.com/29bqX0W.png

These are on fresh versions of ppsspp with every setting at the default.

Calibrating the controller has had no effect.  This affects every game that has different movement speeds for how far you move the stick and makes them unplayable.

**Comment by unknownbrackets** [comment] 2015-10-08 05:37
I thought there was a new setting for the deadzone added?  Check in the controls settings.

Theoretically, we could add a "boost joystick range" setting or calibration, I guess, to account for this problem.  Realistically, most PSP games only support at most 100% and like 50% because the nub is not great.

-[Unknown]

**Comment by Konuchi** [comment] 2015-10-09 02:05
There are some new deadzone settings but they don't fix the problem.  I tried them before making my original post.

**Comment by vnctdj** [comment] 2015-10-12 10:00
I can't reproduce the issue with my gamepad (a USB PS3/PC one).
Therefore I think the problem is caused by your controller.
It's strange that the deadzone settings don't help you...

**Comment by hrydgard** [comment] 2015-10-12 11:11
Maybe we need some "reverse deadzoning" that expands "weak" input out into the corners...

**Comment by restion** [comment] 2015-10-24 17:13
It appears that games like peace walker has a analog sensitivity setting that affects other games somehow. Try setting it to maximum in peace walker and see if it improves.

**Comment by nickolind** [comment] 2017-04-29 01:10
Hi! Stumbled upon the same issue as topic starter. The program detects the left stick like on the screenshot 

https://drive.google.com/file/d/0BzpnPEq2hmIPTjR4ZDJBYXFjQnc/view?usp=drivesdk 

 and there are no way to increase the sensitivity. In games like Splinter Cell Essentials this results in walk-only gameplay (the signal doesn't reach the 100% threshold, especially on diagonals). And this happens only in the PPSSPP, among all possible android or windows games. 

I bet it is not hard to add a little entry in setup to multiply the signal of the gamepad sticks.

**Comment by hrydgard** [comment] 2017-04-29 16:45
Yeah, makes sense. I'm gonna do the 1.4.1 release in a couple weeks, I'll squeeze this in before then.

**Comment by nickolind** [comment] 2017-05-01 14:01
Great news, thanks!

**Comment by hrydgard** [comment] 2017-05-10 12:29
For the PC, the "Analog mapper high end" setting should fix this, just increase it. For other platforms, there wasn't any support but I'm adding a single basic sensitivity setting.

Really though, this should be redesigned, and the sensitivity processing should be done after combining the axis (when putting together the struct for the PSP to read) and not in the input layer.

**Comment by hrydgard** [comment] 2017-05-24 09:02
The new sensitivity setting should be enough to work around this, closing.

**Closed by hrydgard** 2017-05-24 09:02 UTC
