### ISSUE TITLE
Code Lyoko Audio Issues

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#7866] opened 2015-07-17 00:16 UTC
In code lyoko, when you talk to an npc with audio sync turned on you can hear the speech, but it loops after its done, softlocking the game. if you have sync turned off you cant hear the speech but you can escape the interaction and it doesnt softlock

ppsspp ver = ppsspp-v1.0.1-765-g47f68ae-windows-amd64
cpu = intel celeron G1610 @ 2.6 GHz
gpu = intel integrated
full log
http://pastebin.com/kFT1ysFu

**Comment by thedax** [comment] 2015-07-19 17:20
Closing as duplicate of https://github.com/hrydgard/ppsspp/issues/2539.

**Closed by thedax** 2015-07-19 17:20 UTC
