### ISSUE TITLE
[Major Issue] Tenchu san portable and kurenai portable

### ISSUE THREAD

**Issue by wolfokami321** [hrydgard/ppsspp#7272] opened 2015-01-04 14:24 UTC
Tenchu san portable has missing collission on the android version.  Both Tenchu San and Tenchu Kurenai have infinite loading issues on both windows and android platforms.

**Comment by Bigpet** [comment] 2015-01-04 14:30
duplicate of https://github.com/hrydgard/ppsspp/issues/7234 , please don't open duplicates, it's harder to follow all the available information that way

**Comment by wolfokami321** [comment] 2015-01-04 14:32
Funny how you respond to this thread because its a duplicate but a whole week goes by with no more responses on my other one...

**Comment by Bigpet** [comment] 2015-01-04 14:35
There was no new information, I didn't have the game and was not interested in solving the issue, I am however interested in keeping the issues organized.

Not everything will get solved immediately, try to be a little bit more patient.

**Closed** 2015-01-04 14:43 UTC

**Comment by unknownbrackets** [comment] 2015-01-04 15:22
Understand that most people work on PPSSPP because it's interesting to do so; when you bug and nag, you make whatever you're asking about less interesting.  Why should I finish a hard day's work just to deal with that?  Instead, I'll go mess with something else that actually is interesting and fun.

Open source isn't a place where you nag.  You're actually sabotaging your own issue.

-[Unknown]

**Comment by aquilsamuel** [comment] 2015-12-19 06:00
@wolfokami321 I know what you mean. I'm a new member and would love if this problem is fixed. This is what I get when playing this game, even on version 1.1.1 on the PPSSPP for windows 8 32 bit. The music still plays but this loading screen just freezes the video and nothing can be done. I am a Tenchu fan and would love to play and have this game really bad. Can anyone solve this annoying problem??? Thanks![tenchu san portable screenshot](https://cloud.githubusercontent.com/assets/16358888/11911679/9b61bfca-a5d2-11e5-9b93-9eed2a7341e8.jpg)

**Comment by kedamtac** [comment] 2016-01-09 14:27
jpcsp no problem,but my computer configuration is not enough
