### ISSUE TITLE
[macOS] PPSSPP no longer opens after homebrew update

### ISSUE THREAD

**Issue by Diamondog36** [hrydgard/ppsspp#10594] opened 2018-02-08 13:04 UTC
What happens?
PPSSPP doesn't open after updating libzip to 1.4.0 (crashes immediately before it opens). The crash report is attached. It doesn't seem to be compatible with the new version of libzip.

[PPSSPPSDL crash report.txt](https://github.com/hrydgard/ppsspp/files/1707072/PPSSPPSDL.crash.report.txt)

What *should* happen?
It should be able to open.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Macbook Pro Late 2013 13'' Retina
CPU: Intel i5 (4th generation)
GPU: Intel Iris Graphics 5100
Ram: 8 GB (DDR3)
OS: macOS 10.13.3 (High Sierra)

**Comment by hrydgard** [comment] 2018-02-08 13:25
Duplicate of #10575. 

This should be fixed in current and future builds already.

**Closed by hrydgard** 2018-02-08 13:25 UTC
