### ISSUE TITLE
Tantei Jinguji Saburo Hai to Diamond crashes with jpn0.pgf

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7690] opened 2015-04-17 02:49 UTC
Remove jpn0.pgf or replace it with the PSP one,it won't crash.it's always happen.
![01](https://cloud.githubusercontent.com/assets/3481559/7195264/5b31d27c-e4ef-11e4-9017-7c4637b8b1ef.png)
![02](https://cloud.githubusercontent.com/assets/3481559/7195263/5b31b5d0-e4ef-11e4-8917-6bd98eb0275e.png)

**Comment by unknownbrackets** [comment] 2015-04-17 02:59
If you uncomment that debug code, does it trip there?

Although, I guess this is caused by the incorrect sizes of the fonts that come with PPSSPP.

-[Unknown]

**Comment by daniel229** [comment] 2015-04-17 03:09
No,it doesn't trip into the debug code.

**Comment by unknownbrackets** [comment] 2015-04-17 05:39
Hmm, does disabling SSE help this time?  Just to be sure.

Does it reproduce with `#pragma optimize("", off)`?  The `a` address looks super invalid, but I'm thinking it's probably just garbage again.  That said, `idx` definitely looks dangerous.  If those are real values, that's definitely bad.

-[Unknown]

**Comment by daniel229** [comment] 2015-04-17 05:52
No,disabling SSE and <code>#pragma optimize("", off)</code> won't help,and it also happen in debug build.

**Comment by hrydgard** [comment] 2015-04-17 06:00
Okay, so this time it crashes in the debug build too, that's good for debugging.

Looks like idx has become negative somehow. I guess we need even more checks against bad input data (like spline patches that are smaller than 4x4 or something maybe).. can you check spatch.u_count and v_count?

**Comment by unknownbrackets** [comment] 2015-04-17 06:08
Yeah, "won't help" is good news.  This screenshot except with `#pragma optimize("", off)` in the code would be awesome:

https://cloud.githubusercontent.com/assets/3481559/7195263/5b31b5d0-e4ef-11e4-8917-6bd98eb0275e.png

Because otherwise any of the variables in the lower left can be lies.  So it might not even be negative at all.  Turning off optimizations in this file will give us useful numbers.

-[Unknown]

**Comment by hrydgard** [comment] 2015-04-17 06:10
The debugger screenshot is of a Debug build, which can be clearly seen. Optimization should already be off.

**Comment by daniel229** [comment] 2015-04-17 06:27
Add <code>NOTICE_LOG(G3D, "spatch.count_u = %i, spatch.count_v = %i", spatch.count_u, spatch.count_v);</code> right before <code>SimpleVertex *a = spatch.points[idx];</code>
26:01:675 user_main    N[G3D]: Common\SplineCommon.cpp:402 spatch.count_u = 1, spatch.count_v = 1

**Comment by unknownbrackets** [comment] 2015-04-17 06:29
Oops, my bad.  Well, yeah, clearly they must be 1 for that to happen then.

`patch_div_s` is clamped in that case... but a couple things look questionable with that small a count_u/count_v...

-[Unknown]

**Comment by hrydgard** [comment] 2015-04-17 06:34
I simply made it reject patches < 4x4.

**Comment by daniel229** [comment] 2015-04-17 06:43
Still crash,get a different stacktrace
![01](https://cloud.githubusercontent.com/assets/3481559/7197147/07fbc5ec-e510-11e4-85b3-3644741336f9.png)

**Comment by unknownbrackets** [comment] 2015-04-17 06:58
Hmm, looks like garbage.  And none of this happens with PSP fonts?

-[Unknown]

**Comment by daniel229** [comment] 2015-04-17 07:02
No,it does not happen with PSP fonts.

**Comment by hrydgard** [comment] 2015-04-17 07:19
So, most likely our font is so much too large that some memory gets corrupted and it does bogus gpu commands. The right fix is to fix our font. We should be more resilient, though..

**Comment by unknownbrackets** [comment] 2015-04-18 06:22
I agree.  For the resilience, we probably need a few more tests.  I don't really understand splines or beziers well, though...

In this latest crash, I guess one of the steps became null.  fmt = 00000008 - so that means it's one of the nulls in `colstep`, right?  Maybe we should stub those as long as they're possible, to prevent crashes?

-[Unknown]

**Comment by daniel229** [comment] 2015-04-18 06:42
The game still crashes with that change,
Stack trace get this one.
```
>	0000000004cb1278()	未知
```

**Comment by unknownbrackets** [comment] 2015-04-18 07:01
Hmm, no idea what that is.  Maybe jit or vertexjit... the trace doesn't go farther?

-[Unknown]

**Comment by daniel229** [comment] 2015-04-18 07:08
No,just get a stack like that address.

**Comment by unknownbrackets** [comment] 2015-11-02 06:41
What happens if you change this, in GPU/Common/VertexDecoderCommon.cpp:

```c++
if (jitCache && g_Config.bVertexDecoderJit) {
```

To:

```c++
if (jitCache && false) {
```

Does the crash change?  Just wondering if we can get a clean stack.

-[Unknown]

**Comment by daniel229** [comment] 2015-11-02 07:42
Anything useful?
![01](https://cloud.githubusercontent.com/assets/3481559/10876485/4f44bf6c-8178-11e5-8b77-d1034b894e87.png)

**Comment by unknownbrackets** [comment] 2015-11-02 15:47
Well, definitely looks like the source is invalid.  ptr_ is not even either, it ends in 9.  That's odd, I wonder if we should align vertex addresses to 4.

-[Unknown]

**Comment by hrydgard** [comment] 2015-11-02 16:09
I think vertices can legitimately be at odd addresses, as long as all components are byte-sized.

**Comment by unknownbrackets** [comment] 2015-11-02 16:34
Ah, right, of course.  Well, we still might want to align the pointer to the vertex align size maybe?  Should test what really happens...

-[Unknown]

**Comment by xebra** [comment] 2017-01-19 16:41
This issue occurs when open the inventory.

From this screen to next screen
![uljm05529_00000](https://cloud.githubusercontent.com/assets/1607422/22113492/ccb8cb66-dea9-11e6-94c5-82d897f2cd29.jpg)
Crash on this screen
![uljm05529_00001](https://cloud.githubusercontent.com/assets/1607422/22113493/ccb911de-dea9-11e6-978b-9e9e6f9d29eb.jpg)

I think this issue may relate to using Chinese font instead of Japanese font.
Chinese font seems very similar as Japanese one. However it's really different.
Chinese Kanji glyph is not same as Japanese one. So I think we need use Japanese font to fix this issue.
Also our Japanese font(jpn0.pgf) has no shadow glyphs, so it may be the reason to crash the game. And current our font is very huge.

Anyway, our font is broken, I think it cause this issue.
I think this is memory overflow/overwrite issue, so it does not relate to any GPU/CPU issue.

BTW, now I'm developing PGF viewer/converter with GUI  on C# based on ttf2pgf to fix any font issue.

**Comment by nassau-tk** [comment] 2020-10-14 16:59
@hrydgard 
@unknownbrackets 

I tested on v1.10.3-876 and v1.10.3-878 both on Windows10(64-bit).
But,It's not crash both builds version.
Reason:v1.10.3-878 was updated the jpn0.pgf to font of Japansese base.
But,not related? Maybe?
Log has not red code.

>@xebra commented on 20 Jan 2017
>This issue occurs when open the inventory.
>From this screen to next screen

@xebra said clash will happen when open the inventory and select the item.
But, It's will not happen the case.
I'll just report .

(If exists "@xebra's PGF Viewer" then I want it. :smile: )

**Comment by nassau-tk** [comment] 2020-11-23 03:27
v1.10.3-1234
I tested latest modified jpn0.pgf.
The issue will not happen on this version too.

Should this issue be made OPEN?

**Comment by Panderner** [comment] 2020-11-23 04:11
> v1.10.3-1234
> I tested latest modified jpn0.pgf.
> The issue will not happen on this version too.
> 
> Should this issue be made Keep OPEN?

@nassau-tk still not crashing for real PSP font?

**Comment by nassau-tk** [comment] 2020-11-23 04:28
@Panderner 

>@nassau-tk
>still not crashing for real PSP font?

What does it means?
[This issue will not hapeen if you installed "Orignal PSP font".]
I was understanding like above.

And,I tested Original PSP font on PPSSPP just in case.
**The issue is not happen.**

**Comment by hrydgard** [comment] 2020-12-13 16:11
Is this still an issue?

**Comment by nassau-tk** [comment] 2020-12-20 02:40
> Is this still an issue?

I can't reproduce the issue.

**Comment by unknownbrackets** [comment] 2020-12-26 01:49
There have been other font related fixes, such as the allocation callbacks.  Maybe those changes fixed this.

-[Unknown]

**Comment by sum2012** [comment] 2020-12-26 14:18
v1.10.3-1319-gc546c6032-windows-amd64 test no problem
Closing

**Closed by sum2012** 2020-12-26 14:18 UTC
Labels: No Feedback / Outdated?, PGF / sceFont
