### ISSUE TITLE
Slow Voice Playback Problem in Hanayaka Nari, Waga Ichizoku

### ISSUE THREAD

**Issue by nefikys** [hrydgard/ppsspp#13333] opened 2020-08-25 12:32 UTC
Hello, I'm translating the game Hanayaka Nari, Waga Ichizoku on russian. I faced the problem of incorrect playback of voice files on the emulator: all that before 0.9.9.1 - without sound at all, from 0.9.9.1 to 1.8.0 - cut off voice, speed is normal, from 1.9.3 onwards - slow sound velocity. Please help to solve this problem.

**Comment by Panderner** [comment] 2020-08-25 13:29
is this really duplicate of #5213?

**Comment by nefikys** [comment] 2020-08-25 14:22
I read everything in #5213. But I never found a definitive solution there.

**Comment by nefikys** [comment] 2020-08-25 14:23
> is this really duplicate of #5213?

I read everything in #5213. But I never found a definitive solution there.

**Comment by unknownbrackets** [comment] 2021-01-18 23:24
This issue is being closed as a duplicate of #5213.  Thanks for the additional information that it's slower now, rather than too fast.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-01-18 23:24 UTC
Labels: Audio
