### ISSUE TITLE
Ppsspp Does Not Work on Android Oreo 8.0 on Nvidia Shield Tv 2017

### ISSUE THREAD

**Issue by suatdon** [hrydgard/ppsspp#11243] opened 2018-07-07 04:50 UTC
Hello everyone. How are you? Hope all of you are good

This is my first post about an issue

I have Nvidia shield tv 2017 2nd generation

Ppsspp was working very well on Android 7.0 Nougat. Just last week the device update automatically from 7.0 Nougat to Oreo 8.0

After that i tried to run ppsspp it is opening and shows the games in my library but when i click any game it is closing. Select button was A and then start button the game was runing on previous android version but not now

Current ppsspp version is 1.6.3 installed

Can anyone has same problem and has a solve

Thank you

**Comment by unknownbrackets** [comment] 2018-07-07 05:38
Can you get an adb logcat?

Also, try changing the backend in the settings between Vulkan and OpenGL.

-[Unknown]

**Comment by hrydgard** [comment] 2018-07-07 06:33
Will investigate soon.

**Comment by unknownbrackets** [comment] 2018-07-07 17:38
It's working fine on a SHIELD TV from 2015.

https://logmatic.io/blog/a-how-to-guide-to-debugging-with-android-logcat/

This might help.

-[Unknown]

**Comment by suatdon** [comment] 2018-07-08 00:06
Did you update to oreo 8.0?
Also i clicked the link ghat you give but very complicate for me:(

**Comment by suatdon** [comment] 2018-07-08 04:06
I installed https://buildbot.orphis.net/ppsspp/

But stil does not work

**Comment by suatdon** [comment] 2018-07-08 04:15
The best way is think rset the device with old firmware

**Comment by 7th-son** [comment] 2018-07-08 07:50
I also have an issue since the Oreo update. (also the 2017 version). I have tried the latest Playstore version and the latest Nightly of PPSSPP.
I think I have about the same issue as you do **suatdon** , but my games do start, but after a short while PPSSPP quits too, mostly during loading screens. Also my games freeze for a few seconds every now and then...

PS: the strange thing is, that it does almost exactly the same with retroarch, none of the games work good, and all get the corresponding app to crash and exit to the Shield main screen...

**Comment by hrydgard** [comment] 2018-07-08 12:51
If anyone with a 2017 Shield TV could get some ADB logs of the crash, that would be very helpful.

I

**Comment by unknownbrackets** [comment] 2018-07-08 14:07
It's not that hard - if you install the Android SDK, you just need to connect a USB cable to the SHIELD TV, then open a Terminal window (Mac) or Command Prompt window (Windows) and type:

```
adb logcat > ppssppcrash.txt
```

After typing that, press enter/return.

Now go and reproduce the issue.  Once you've reproduced it, go back to the Terminal/Command window, and press Ctrl-C (even on Mac, don't press Command-C.)  Then, on Windows type:

```
start .
```

Or, on Mac, type:

```
open .
```

The dot is important for either one.  Again, press enter/return afterward.

The folder should open and have ppssppcrash.txt in it.  Zip that up and attach it here.

--

Separately, you could also try older versions of PPSSPP.  For example, if 1.5.4 works on Oreo, that would be useful.l  If you find an older version that works, try git builds in between (go by halves - it's the most efficient way, provably) which will narrow it down.  But it's possible every version is affected by this.

-[Unknown]

**Comment by suatdon** [comment] 2018-07-09 00:46
I did reset the device yesterday night but unfortunatally installed oreo not nougat. Then install ppsspp 1.6.3 still doesn’t work. I removed 1.6.3 and install 1.5.4 then let you know here what is gonna happen

**Comment by 7th-son** [comment] 2018-07-09 05:12
I will try to make ADB logs tonight, when I get home from work and stuff.

**Comment by suatdon** [comment] 2018-07-15 05:55
Hi again everyone. Just let you know. I remove ppsspp 1.6.3 and install 1.5.4 but everything is still same. Only diffrent thing is
1.6.3 was closing whwn i want to select the game. This cersiyon 1.5.4 does not. It is bringing next screen of game and then staying like that

**Comment by 7th-son** [comment] 2018-07-15 18:47
I have the feeling its te usb drive in my case. When i inserts this into my Windows laptop, it says it has ground a problem.

I will try this soon, and try to make a log too. 
Sorry if it takes longer then expected!

**Comment by hrydgard** [comment] 2018-07-21 14:53
Got my hands on a 2017 Shield TV and I was able to reproduce the problem on PPSSPP from the Play Store. It's use of a null texture when displaying game icons. However I also tried a fresh build and it would not reproduce, so seems it's already fixed, and thus will be fixed in 1.7. It's really not a good experience as is though.. I'm thinking of having 1.7 being a small release, I mean, the current master is pretty nice and stable so why not just push it out as 1.7 pretty soon and push the harder tasks along to 1.8...

**Comment by hrydgard** [comment] 2018-07-21 20:50
If you're still seeing issues with the latest build, that commit could help.

**Comment by hrydgard** [comment] 2018-07-23 16:45
I'm gonna close since it should be fixed in development builds.

**Closed by hrydgard** 2018-07-23 16:45 UTC
Labels: Platform-specific (Android)

**Comment by stoneule** [comment] 2018-08-26 11:09
Any progress on this? Issue still exists on shield tv

**Comment by LunaMoo** [comment] 2018-08-26 12:08
We can reopen, but first confirm if it actually happens on latest PPSSPP ~ ie from buildbot [here](https://buildbot.orphis.net/ppsspp/). The version you get from google play store (1.6.3) is outdated and will always be buggy until next release.
