### ISSUE TITLE
Trollstore installation with JIT entitlement

### ISSUE THREAD

**Issue by ansinerd** [hrydgard/ppsspp#16019] opened 2022-09-12 23:24 UTC
### What happens?
On non jailbroken IOS devices JIT does not work, the emulator is exceptional but certain games like Metal gear solid have so many graphical issues unless JIT is enabled through altstore (altjit) else they don’t run well.

### What *should* happen?

On recent reddit post about trollstore someone claimed that due to core trust bug the trollstore is able to sign apps as system apps with entitlements, oatmealdome of dolphinios confirmed that some codes can enable JIT entitlement in emulators when installed with trollstore even in non jailbroken state. He said, upto developers to add the code and update the apps to support JIT natively enabled. Its a request to you to please do the needful if its possible, it will massively help me and hundreds like me with many games.

### What are you using?

ipad pro 2018
Iphone 13 

#### What hardware / device and operating system?

ipad pro and iphone 13 both on ios 15.1

#### What graphics card (GPU) or mobile phone model?
Iphone 13 and Ipad pro 2018

#### What PPSSPP version (standalone/official), and did it work before?
latest one from your website

#### Which game or games?

metal gear solid 3

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2022-09-13 06:37
According to https://www.reddit.com/r/jailbreak/comments/x44cpj/free_release_trollstore_jailed_permasigned_app/
> Apps installed through TrollStore can have any entitlement they want (excluding com.apple.private.cs.debugger, dynamic-codesigning and com.apple.private.skip-library-validation on iOS 15 because those are locked behind PPL unfortunately, so probably no JIT for iOS 15).

Since you're using non-jailbroken iOS 15, JIT won't work even with TrollStore, right?
Also, relying on a bug will eventually got patched and won't work on newer iOS, right?

**Comment by ansinerd** [comment] 2022-09-13 08:26
> 

https://www.reddit.com/r/jailbreak/comments/xcd2v4/news_found_way_to_achieve_wx_jit_for/

I was talking about this one. Apparently jit can still be debugged after all on ios 15. Anyways you have a point, the trollstore core trust bug is patched in ios 15.5 and above. But if trollstore kinda gives a jailbreak like solution for non jailbroken people like me, it was a long shot though 😅 . Anyways thanks a lot for the reply.

**Comment by unknownbrackets** [comment] 2022-09-18 17:03
I don't think you should expect anything to happen as a result of this issue, unfortunately.

If someone wants to come along and contribute something to make jit work on these iOS versions, they're welcome to.  This has happened for past iOS jit methods.  It's unlikely anyone would do so as a response to this issue - it's usually the result of someone wanting PPSSPP to run faster on their device, and having the time and interest to figure out how to make it work.

PPSSPP on iOS is not well supported, in part because Apple doesn't want it to work.  Any time PPSSPP does work, you can essentially assume Apple's developers have a bug open to make it stop working.  Personally, I used to use an iPhone and switched to Android - I'd rather spend my time making PPSSPP better than just fighting with silly people who want more ways to make money.

The best way for you to make this happen is either to dedicate time to learning how to make a pull request yourself, or look for people interested in iOS jit methods and request they make a pull request.

Still unclear to me if this is even viable still in recent versions, but like I said, I'm not really planning to spend my time researching this.

-[Unknown]

**Comment by kero990** [comment] 2022-11-03 05:45
According to the https://p.xx.wtf/ website, now jit works fine on ios, but the ios version they compile is for jailbreak, the default settings folder is in the program private directory instead of the public directory, and There are no quick links to access public directories. In addition, ppsspp does not have a default directory setting option, which results in that although you can manually select a complex path to locate the public directory and run the game, the archive cheats and even screenshots are still in the program's private path and cannot be imported or exported.
While I feel like this should be pretty easy to fix on source code, I don't, expecting someone to do the work.

**Comment by Halo-Michael** [comment] 2023-02-21 14:15
> The current situation is that if you use 1.11 and earlier versions, a configuration file will be created in the program's private directory, but you can't see any other directories, so you can only find a way to import the iso file into the program directory, and 1.11 cannot open jit, you must Use ir, otherwise it will crash.
> 
> If you use the newer 1.13 version, then no configuration file directory will be created, and even if you use other tools such as filza to force import configuration and mirroring, it will not be visible in ppsspp. The strange thing is that this version can't see the files in its own program directory, but can see other directories, you can manually navigate to the public directory to select the mirror, but can't save any configuration and archives. but can enable jit
> 
> The above are all compiled versions of the https://p.xx.wtf/ website. According to its Chinese instructions, donate ￥99 to give away the no-jailbreak version. It is estimated that this donation version can be used normally.

It's basically caused by bad codesign way. They use ldid sign PPSSPP main binary but not specific a right platform-id. You can try my build for now ,and I guess it will works fine.
https://github.com/Halo-Michael/halo-michael.github.io/tree/master/ipas

**Comment by Halo-Michael** [comment] 2023-02-21 14:23
Self JIT enable is possible but you may loss some details: It only works on arm64 devices(not arm64e device, which means only work for A11-)with just "get-task-allow" entitlement, which is already by used by many builds like mine, and doesn't need any code change or sth. You can see Apple is tightening some policy on arm64e devices(newer), like you can't sign "com.apple.private.cs.debugger" "dynamic-codesigning" "com.apple.private.skip-library-validation" entitlements in arm64e, iOS15+ devices, and arm64e only. So unfortunately it's impossible to self JIT enable on your iPhone13, and nothing we can do.
You guys can close this thread now.

**Comment by unknownbrackets** [comment] 2023-02-22 05:30
Yeah, they might also be using pointer authentication etc. to prevent it now with arm64e.

Going to close this given the notes above.  Thanks for investigating.

-[Unknown]

**Closed by unknownbrackets** 2023-02-22 05:30 UTC
Labels: Platform-specific (iOS)
