### ISSUE TITLE
Screen freeze

### ISSUE THREAD

**Issue by Sunil2735** [hrydgard/ppsspp#10374] opened 2017-12-08 09:34 UTC
When loading the save states for second time screen freezes. It's happens on both god of war ppsspp games don't know about other games. There was no problem prior to this.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.01
Latest version ppsspp
Sd 506

**Comment by hrydgard** [comment] 2017-12-08 09:34
"prior to this" ? Prior to what, which version?

**Comment by Sunil2735** [comment] 2017-12-08 09:36
I am using v1.5.4-34-g253bba28d

**Comment by hrydgard** [comment] 2017-12-08 09:47
Yes but which is the last version in which it worked for you? Knowing that makes it easier to find the problem.

**Comment by Sunil2735** [comment] 2017-12-08 10:04
It was working fine in v1.5.3-40-g7f5ba2140

**Comment by brujo5** [comment] 2017-12-08 15:47
Repost

https://github.com/hrydgard/ppsspp/issues/10364

**Comment by hrydgard** [comment] 2017-12-08 18:24
Yeah, closing as dupe of #10364. I'll have a look soon.

**Closed by hrydgard** 2017-12-08 18:24 UTC
