### ISSUE TITLE
Steam Deck - Can't Hold Select Button

### ISSUE THREAD

**Issue by ASatiricalDalek** [hrydgard/ppsspp#15635] opened 2022-06-28 14:59 UTC
### Game or games this happens in

Grand Theft Auto Chinatown Wars

### What area of the game / PPSSPP

Chinatown Wars has players tap the select button to open the weapon wheel, and hold the select button to interact with objects (starting side missions in taxis or ambulances or opening containers, for example). Any time one of these interactions appears, holding the select button opens the weapon wheel as though the button had just been tapped. This issue appears to have existed in a previous version as well according to this forum post - https://forums.ppsspp.org/showthread.php?tid=24949 

### What should happen

Holding the select button should allow interaction with the environment while tapping it should open the weapon wheel. 

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

SteamDeck  AMD Van Gogh processor

### PPSSPP version affected

1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ASatiricalDalek** [comment] 2022-07-01 03:38
This bug does not seem to affect other games. God of War: Chains of Olympus has many "Hold O to open" moments that work just fine. Either the issue is specifically with GTA (maybe the fact that tapping and holding the button in that moment do different things whereas in GoW tapping the button wouldn't do anything in this instance) or the bug is specific to the Select button.

**Comment by unknownbrackets** [comment] 2022-07-02 15:58
If you map it to another button, does this happen?  Maybe there's something special about that button on this device that makes it send presses differently?

-[Unknown]

**Comment by ASatiricalDalek** [comment] 2022-07-02 16:08
I did try mapping the select button to a different button on the Deck using Steam's built-in control mapping feature, same result. I also tried mapping a keyboard button (which I assigned to one of the Deck's back bumpers) as an alternate binding for select. This didn't seem to work at all. 

I could try mapping select in PPSSPP to another button entirely emulator-wide I suppose.

**Comment by unknownbrackets** [comment] 2022-07-02 16:11
I would suggest you try:
 * Remove all mappings for the PSP select button.
 * Pick another button you will use as select.
 * Remove all mappings for that other button.
 * Map that button to ONLY the PSP select button.

So at this point, you should have a single button that only presses PSP select, and does nothing else.

Then try holding and see if anything changes.  If that changes it, could be there's something conflicting with other buttons.

-[Unknown]

**Comment by ASatiricalDalek** [comment] 2022-07-03 04:10
Good news, this does work. I rebound the L2 button on the deck to be select in GTA Chinatown Wars through Retroarch instead of the controller mapping function in SteamOS and the button behaved as expected. So it seems to be something with the select button, maybe specific to the Deck?

**Comment by hrydgard** [comment] 2022-07-03 13:08
That pretty much confirms that the issue is not in PPSSPP, but somehow in the Steam Deck itself, or retroarch I guess.

I'm gonna close this, but thanks for reporting, good to have the issue here so that people can find it by googling.

**Closed by hrydgard** 2022-07-03 13:08 UTC
Labels: Input/Controller, HLE/Kernel

**Comment by whallup** [comment] 2023-04-10 17:16
> Good news, this does work. I rebound the L2 button on the deck to be select in GTA Chinatown Wars through Retroarch instead of the controller mapping function in SteamOS and the button behaved as expected. So it seems to be something with the select button, maybe specific to the Deck?

I might be stupid, but would you be able to explain how you did that with the L2 button through retroarch? Running into the same issue at the moment.
