### ISSUE TITLE
Shortcuts with image automatically.

### ISSUE THREAD

**Issue by CristobalManga** [hrydgard/ppsspp#16320] opened 2022-11-01 22:48 UTC
### What should happen

Good afternoon mates.
Perhaps it is not a very important function.
But it would be great if when making a shortcut, it was already with the game image. There are launchers that let you resize a set of shortcuts, and it's possible to set them to 300x100 resolution.
From what I see PPSSPP, it creates shortcuts when it looks for the game file. Perhaps this is a limitation.
Unlike other emulators like epsxe or Aethersx2, where they create shortcuts in a different way.

![2022_06_25_20_51_24](https://user-images.githubusercontent.com/78171867/199356499-aa6d879e-650d-480c-afbf-ae412aae2d98.jpg)

### Who would this benefit

Make it easy to make shortcuts without having to search for images of the game on the internet.

### Games this would be useful in

All

### Other emulators or software with a similar feature

Aethersx2, Epsxe, duckstation.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Gamemulatorer** [comment] 2022-12-12 01:43
Related or Dup of https://github.com/hrydgard/ppsspp/issues/10885?

**Comment by hrydgard** [comment] 2023-08-18 08:51
Yes, this is a duplicate of #10885.

**Closed by hrydgard** 2023-08-18 08:51 UTC
Labels: Platform-specific (Android), Feature Request
