### ISSUE TITLE
Issue with Prince of persia revelation (fight with Shahdee, crash)

### ISSUE THREAD

**Issue by Night-Hawk2000** [hrydgard/ppsspp#12196] opened 2019-07-26 15:39 UTC
During fight with shahdee game ask me press hit key rapidly. Initially the hit command seems to work but later it seems no effect of pressing key.
I am using PPSSPP 1.8 on android 8.1.

**Comment by unknownbrackets** [comment] 2019-07-27 13:23
Does this happen with default settings?  Things that could cause this:

 * Altering the CPU speed.
 * Cheats
 * Getting worse than 100% speed (check "Show FPS -> Both" in graphics settings)

-[Unknown]

**Comment by ashutoshmaurya1122** [comment] 2019-07-31 08:03
I would like add an additional problem i am facing game crash issue with same game.

**Comment by unknownbrackets** [comment] 2019-08-03 23:23
Can you confirm if those settings affect it (or the crash)?

-[Unknown]

**Comment by ashutoshmaurya1122** [comment] 2019-08-04 02:56
I don't altered the CPU speed and disable the cheats but game crashes at a particular point.
I have played game before compleated it without   
crash.

**Comment by ashutoshmaurya1122** [comment] 2019-08-04 03:23
I don't alter the cpu speed and disable cheats. I have played this game before and completed it.
Here is my crash report.
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/vince/vince:8.1.0/OPM1.171019.019/V10.2.3.0.OEGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 993, tid: 1051, name: Emu  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x2300003a70
    x0   0000000008d89180  x1   00000000000000aa  x2   0000000000000000  x3   0000000000000002
    x4   0000000000000000  x5   00000077845fef98  x6   ffffffffffffffff  x7   0000000000000000
    x8   0000000000000000  x9   000000777f8d0b80  x10  0000000000000040  x11  ffffffffffffffc0
    x12  000000777f8d0b80  x13  0000000000000040  x14  0000000000000040  x15  0000000000000040
    x16  000000777f8d0ae0  x17  0000000000000068  x18  00000000000010f1  x19  0000002309ffae10
    x20  0000000000003a70  x21  0000002300003a70  x22  0000000000000001  x23  0000000008ba94bc
    x24  000000000003d148  x25  0000000060000000  x26  000000777f71b000  x27  0000007786149a70
    x28  0000002300000000  x29  00000077845ff100  x30  000000777f71b19c
    sp   00000077845ff100  pc   000000777f8d0b0c  pstate 0000000060000000

backtrace:
    #00 pc 00000000001b5b0c  <anonymous:000000777f71b000>
    #01 pc 0000000000000198  <anonymous:000000777f71b000>

**Comment by unknownbrackets** [comment] 2020-03-15 06:24
Just noting so it's easier to find in search: this is crashing on an access near the scratchpad.  We've seen similar odd behavior in #10196 and #12510, although the other direction.

If possible, can you check if this occurs on a PC?  It'd help to understand if this is potentially a jit bug that only affects ARM devices (i.e. phones and tablets, not Intel desktops/laptops.)

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-05-02 18:00
@ashutoshmaurya1122 can upload a savestate I will test game in order to reproduce

**Comment by ashutoshmaurya1122** [comment] 2021-05-03 12:31
> @ashutoshmaurya1122 can upload a savestate I will test this game in try to reproduce the issue on my Redmi Note 9.

Sorry dude it was long time ago , I have lost that.

**Comment by unknownbrackets** [comment] 2021-05-04 05:16
We have had reports of another game that had some weird scratchpad behavior also being fixed, so it's definitely possible this bug is fixed now.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-09-14 15:18
Cannot reproduce this crash.
![Screenshot_2022-09-14-23-16-41-90](https://user-images.githubusercontent.com/37603562/190195231-4bd93a1b-a2ca-4b9f-bbe8-331a86010487.png)

**Closed** 2022-09-14 16:52 UTC
