### ISSUE TITLE
Vulkan Juiced 2 Black menu

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10169] opened 2017-11-21 15:35 UTC
Vulkan 
![screenshot_2017-11-21-23-31-09-460_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33081118-6c219b32-cf14-11e7-89f6-49411027067e.png) 
Opengl   
![screenshot_2017-11-21-23-32-15-044_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33081163-94091738-cf14-11e7-8a88-6924e8369115.png)

**Comment by Blacob777** [comment] 2017-11-21 15:47
And grafical bug opengl and vulkan 
![screenshot_2017-11-21-23-45-00-130_org ppsspp ppsspp](https://user-images.githubusercontent.com/29165096/33081861-44667232-cf16-11e7-9125-f8e1ca05ae48.png)

**Comment by hrydgard** [comment] 2017-11-21 15:52
Duplicate of #7295 (except the Vulkan issue which is new I guess, I'll move it over).

**Closed by hrydgard** 2017-11-21 15:52 UTC
