### ISSUE TITLE
Jeanne d'Arc - the character invisinle problem on 1.1.1 version

### ISSUE THREAD

**Issue by ivyking007** [hrydgard/ppsspp#8114] opened 2015-10-26 21:50 UTC
on 1.1.1 version when skip the animation the character will became invisible

**Comment by unknownbrackets** [comment] 2015-10-27 05:39
What device, specifically?  If a PC, what video card specifically, what OS version, and are the drivers completely up to date?

What's the first git build of PPSSPP where it starts happening, and the last one where it was still working?

-[Unknown]

**Comment by ivyking007** [comment] 2015-10-27 09:52
pc win7 64bit , driver already up to date , when start the new game and then skip the animation

**Comment by vsub** [comment] 2015-10-27 16:26
I don't know if this game actually work in Direct3D9 but in that mode the first two logos\intros are white screen,then at the title screen the menus are not visible,then the intro is black screen and then the characters are missing

In OGL works fine but the text don't look good unless you use your fonts.

**Comment by ivyking007** [comment] 2015-10-27 17:06
i use opengl also have this problem

**Comment by vsub** [comment] 2015-10-27 19:53
Well it works fine here when I use my GTX750TI or HD4600 video card in OGL mode.

**Comment by ivyking007** [comment] 2015-10-28 00:06
i use intel graphic hd video card

**Comment by unknownbrackets** [comment] 2015-10-31 03:32
So, we require OpenGL 3.0 for this workaround, iirc, or at least the framebuffer blit extension.  We have never had a solution for Intel cards that lack modern OpenGL support, or even Android devices using GLES 2.0.

This is a duplicate of #1283.

-[Unknown]

**Closed by unknownbrackets** 2015-10-31 03:32 UTC
