### ISSUE TITLE
Motorstorm graphical glitches on shadows

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#13064] opened 2020-06-28 07:45 UTC
### What happens?
black textures

### What *should* happen?
proper shadows

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPad 6 with jit,iOS,1.10 and A10

**Comment by Panderner** [comment] 2020-06-28 07:47
Duplicate of #7552

**Closed** 2020-06-28 07:49 UTC
