### ISSUE TITLE
libretro/jni  compile error

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#16525] opened 2022-12-08 02:28 UTC
### Platform

libretro / Retroarch

### Compiler and build tool versions

NDK e21

### Operating system version

ubuntu 20.04

### Build commands used

$NDK/ndk-build -B

### What happens

[armeabi-v7a] Compile++ thumb: retro <= StencilCommon.cpp
[armeabi-v7a] Compile++ thumb: retro <= TransformUnit.cpp
In file included from /home/xielei/ppsspp/libretro/jni/../../GPU/Software/TransformUnit.cpp:33:
In file included from ../../GPU/Software/BinManager.h:22:
../../GPU/Software/Rasterizer.h:50:20: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED = 0x0001'0000,
                          ^
../../GPU/Software/Rasterizer.h:50:20: error: expected '}' or ','
../../GPU/Software/Rasterizer.h:51:30: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_BLEND_SRC = 0x0002'0000,
                                    ^
../../GPU/Software/Rasterizer.h:52:30: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_BLEND_DST = 0x0004'0000,
                                    ^
../../GPU/Software/Rasterizer.h:53:30: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_BLEND_OFF = 0x0008'0000,
                                    ^
../../GPU/Software/Rasterizer.h:54:31: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_TEXREPLACE = 0x0010'0000,
                                     ^
../../GPU/Software/Rasterizer.h:55:28: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_FOG_OFF = 0x0020'0000,
                                  ^
../../GPU/Software/Rasterizer.h:56:37: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_ALPHATEST_OFF_NE = 0x0040'0000,
                                           ^
../../GPU/Software/Rasterizer.h:57:37: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_ALPHATEST_OFF_GT = 0x0080'0000,
                                           ^
../../GPU/Software/Rasterizer.h:58:33: warning: missing terminating ' character [-Winvalid-pp-token]
        OPTIMIZED_ALPHATEST_ON = 0x0100'0000,
                                       ^
../../GPU/Software/Rasterizer.h:62:24: error: use of undeclared identifier 'OPTIMIZED_TEXREPLACE'
        OPTIMIZED_SAMPLERID = OPTIMIZED_TEXREPLACE,
                              ^
9 warnings and 2 errors generated.
make: *** [/home/xielei/android-ndk-r21e/build/core/build-binary.mk:478: /home/xielei/ppsspp/libretro/obj/local/armeabi-v7a/objs/retro/__/__/GPU/Software/TransformUnit.o] Error 1

### PPSSPP version affected

commit bafe14e9eec38e484dccb19df5ae5b5c12b83893

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment] 2022-12-08 08:40
PPSSPP requires using std c++14.  If you're trying to compile with an older standard, it won't work and there's probably more problems than just this one.

-[Unknown]

**Comment by hrydgard** [comment] 2022-12-08 10:04
NDK 21e surely supports std c++14, btw, so this should just be a case of some missing compile flag somewhere.

**Comment by hsoftxl** [comment] 2022-12-11 14:04
NDK e25 is error too.

**Comment by unknownbrackets** [comment] 2022-12-11 17:26
It's because the problem isn't the NDK version, it's the parameters being passed to clang.  No idea where this build script is, it seems like libretro sent a pull with cmake but literally none of the builds actually use cmake?

We currently compile each commit using cmake and the makefile under libretro, which were both created by the team that get patreon donations to maintain this stuff.

-[Unknown]

**Comment by LibretroAdmin** [comment] 2022-12-13 10:41
the Android libretro build is compiled using CMake. You can see this in .gitlab-ci.yml.

https://github.com/hrydgard/ppsspp/blob/master/.gitlab-ci.yml

Most likely you're just missing some environment variables that need to be defined. It builds fine on our Gitlab CI.

**Comment by fr500** [comment] 2022-12-14 01:26
The core is completely broken anyway and has been for about a year.
Standalone is way to go for anything post mednafen.

**Comment by hrydgard** [comment] 2022-12-14 10:50
As @LibretroAdmin says, the problem has got to be with your setup. Follow how the libretro CI is setup.

The reason it's a bit shaky is that not enough effort has been put into the integration between libretro's API and PPSSPP's threading model, which is tricky and needs a real effort.

Closing this issue.

**Closed by hrydgard** 2022-12-14 10:50 UTC
Labels: Libretro
