### ISSUE TITLE
Motorstorm:AE stuck loading screen v1.6 and later

### ISSUE THREAD

**Issue by sisxgame** [hrydgard/ppsspp#11261] opened 2018-07-22 10:27 UTC
In the MotorStorm AE (EUR)
Stuck loading screen every time in ppsspp v1.6 and later
In the 1.5.4 working fine 
Im save the game while im racing in the v 1.5.4 and i load the game in the v1.6.3 and the game working properly. But im finish the race in the v1.6.3 then stucking the liading screen again.

My device 
Snapdragon 820
Android 6.0 marshmallow
OpenGl

I dont test it whith newer  firmware. 

Sorry for my english

**Comment by 1234Sameer** [comment] 2018-07-22 12:47
Check out #11019 .

**Comment by unknownbrackets** [comment] 2018-07-22 14:56
Can you try this with the latest git build from the downloads page?  Do default settings help?

Are you running any citrus scanner that could be interfering?  Do you have the dlc?  Is this the Europe version of the game?

I'm going to close this as a duplicate of #11019.  But it would help to know the answers - just reply to that other issue.  Thanks for the help.

-[Unknown]

**Closed by unknownbrackets** 2018-07-22 14:56 UTC

**Comment by sisxgame** [comment] 2018-07-22 15:16
Yes im trying with latest git build and now im reset the settings but not fixed. I dont use citrus scanner.
And dond have dlc. 
and yes his is europe version.
Thanks
