### ISSUE TITLE
Guardband glitchfix not enabled on Mali G71 (Toca Race driver 2, others)

### ISSUE THREAD

**Issue by Drasikk** [hrydgard/ppsspp#11999] opened 2019-04-26 18:44 UTC
### What happens?

![PPSSPP_2019-04-26-20-23-54](https://user-images.githubusercontent.com/38067925/56829120-2e56c400-6863-11e9-8c91-3135b2c37b3c.jpg)

### What *should* happen?

I tested it with the version that is in the Google Play and the latest build And in both of them the same thing happens. I have also tried both with Open GL and Vulkan.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 8 Oreo 8.0.0 Exynos.

I think it has been commented but has not been able to find a solution.

**Comment by LunaMoo** [comment] 2019-04-26 20:42
Closing as a duplicate of #5001 ~ which was fixed actually, but the solution doesn't work on most old and poor hardware like mobiles with bad drivers

**Comment by Drasikk** [comment] 2019-04-26 22:13
> Closing as a duplicate of #5001 ~ which was fixed actually, but the solution doesn't work on most old and poor hardware like mobiles with bad drivers

Arreglado? jajaja!! Pero si este problema es de este emulador y no de los smartphones. Este error lleva desde hace años y no se porqué no se encuentra una solución.

**Comment by LunaMoo** [comment] 2019-04-26 23:43
You missunderstand - I said that the solution for that problem only works on decent and modern hardware like most decent PC's, if you want to play the game use a PC with modern gpu for now and if you want, subscribe to the issue I linked when closing yours as it's already tracked and we don't need more issues opened for the same problem. It might be impossible to fix on all hardware through.

**Comment by unknownbrackets** [comment] 2019-04-27 21:44
Hm, I am a bit surprised it doesn't work on a Note 8.  It's unfortunate a Mali-G71 doesn't work with this means of guardband.  I think there may be other ways to implement it, which I think there's already a separate issue for.

-[Unknown]

**Comment by Drasikk** [comment] 2019-04-28 07:58
> Hm, I am a bit surprised it doesn't work on a Note 8. It's unfortunate a Mali-G71 doesn't work with this means of guardband. I think there may be other ways to implement it, which I think there's already a separate issue for.
> 
> -[Unknown]

Your message gave me a little hope That the problem can be solved. Thank you!

**Comment by hrydgard** [comment] 2019-04-28 09:48
I think our current Mali version detection is wrong. I'm gonna rework it, which will probably fix this. Reopening.

**Comment by LunaMoo** [comment] 2019-04-28 10:01
So we should close the other issue then? It's duplicate of the same thing.

**Comment by hrydgard** [comment] 2019-04-28 10:19
Well, this one could be specifically about the ARM Mali version detection problem. I'll change the title.

**Comment by unknownbrackets** [comment] 2019-04-28 16:29
Hm, but does the Mali version detection affect use of this?

-[Unknown]

**Comment by hrydgard** [comment] 2019-04-28 18:11
Uhm, nope, looks like I was confusing it with something else while being too lazy to check the code. That makes this kinda mysterious.

**Comment by Drasikk** [comment] 2019-04-29 12:57
> Uhm, nope, looks like I was confusing it with something else while being too lazy to check the code. That makes this kinda mysterious. (The accurate depth force-enable has a wrong version check).

DTM Race Driver 2 (ULES00041) It also has the same problem.

![PPSSPP_2019-04-29-14-53-30](https://user-images.githubusercontent.com/38067925/56897561-18c5e200-6a8f-11e9-96b5-86ca994612cc.jpg)

**Comment by Drasikk** [comment] 2019-05-27 09:53
It's been a month and there's still no answer, no solution. If I had known I would not have said anything, because when you find a solution I will have a new mobile.

**Comment by unknownbrackets** [comment] 2019-06-02 16:43
Hardware problems are tricky to workaround.  While it may seem like there are two kinds of humans - regular ones, and superhumans that can program and write emulators - it's actually not true.  We're all just regular amazing superhumans.

So far, no one knows how to fix this.  It's kinda like writer's block - no great ideas.  Saying "you just gotta finish the story" isn't gonna just make it happen.  If you want this to get done, the best idea is to roll up your sleeves, crack your knuckles, and dig in for some ideas.  Even if one superhuman such as yourself can't fix it alone, if you can find some leads it may get things moving again.

-[Unknown]

**Comment by Drasikk** [comment] 2019-06-04 07:41
I close it, to read disrespect to me person I spare.

**Comment by blisstik** [comment] 2019-07-27 15:27
Confirmed the same issue for Mali T628MP6 and Mali G52

**Comment by shantigilbert** [comment] 2019-08-04 00:05
Not sure if this is the same issue, but here is a video 

https://www.youtube.com/watch?v=Z91kLA-z1-U

**Comment by iXmerof** [comment] 2019-08-04 16:26
Hi, I am having exactly same issue on Galaxy S7 with Mali-T880 MP12. This happens to DTM Race Driver 2 (Toca Race Driver, Europe edition too) and Toca Race Driver 3 Challenge the same way. I am new on the psp emulation scene but I can deliver you all information required/run test versions once you'll tell me how.

**Comment by hrydgard** [comment] 2019-08-08 19:55
Recent ARM Mali drivers have geometry shaders, so that would be an alternative solution for implementing the culling. Not a fan of the idea of having geometry shaders always on for everything though...

**Comment by shantigilbert** [comment] 2019-08-08 20:14
@hrydgard how about it being optional? or is that not possible?

**Comment by hrydgard** [comment] 2019-08-08 21:16
I found a simpler solution :)

**Comment by shantigilbert** [comment] 2019-08-08 22:02
Cool but in my case (on Issue #12222) I am not using Vulkan, will this also fix it?

**Comment by hrydgard** [comment] 2019-08-08 22:07
Oh, right. Well, I'll try the same fix on GL. Stay tuned

**Closed** 2019-08-08 22:09 UTC
Labels: Guardband / Range Culling, Mali GPU, Platform-specific (Android)

**Comment by blisstik** [comment] 2019-08-09 01:21
@hrydgard - the latest version fixes guardband but has now created a new issue where the water areas of the first stage of Outrun is now all black.

**Comment by blisstik** [comment] 2019-08-09 03:29
Here a picture of the black water

https://imgur.com/oTHyYba

**Comment by Drasikk** [comment] 2019-08-09 09:19
To watch...

![PPSSPP_2019-08-09-08-54-31](https://user-images.githubusercontent.com/38067925/62768386-05b3ac80-ba97-11e9-952d-3ad78f84f607.jpg)

Thank you very much @hrydgard and everyone. Yes!! 😀 🎉 😀

**Comment by iXmerof** [comment] 2019-08-09 13:11
I build a normal optimized version for Android with your change and that worked super well for DTM/Toca Race Driver editions 2 and 3. Previously glitches were affecting the performance a lot - each of the big gray bar was causing significant fps drop, now that issue is gone graphically and from performance perspective.
I played an hour both games and discovered that my S7 is on the edge of performance, but setting these helped for both games:
Graphics: Vulkan, Buffered Rendering, Simulate block transfer effects; OFF (significant improvement once disabled), Frame skipping: OFF (even 1% of frame skipping causes bad steerability and audio glitches), Postpro shader: OFF, Resolution: 2xPSP (for looks) Display resolution: Auto, rest from that group ON but Retain changed textures and Disable slower effects which are OFF, Texture scaling 2x, Linear 4x anisotropic filtrering.
With these settings both games stared to be super playable and started keeping the constant 40fps (I added a cheat for Toca 3 to switch to 60fps but that is not always constant, but with lowest of 50fps for few secs).
I must admit that this game looks lots better on PPSSPP than on original PSP not only due to the resolution but the PSP version is not rendering all pixels from the original resolution looking like a tiny grid overlay, here on the emulator it is gone.
Some attachments:
Toca2:
![Screenshot_20190809-144416_PPSSPP](https://user-images.githubusercontent.com/6281100/62781281-2be14880-baa7-11e9-8fbf-1db66b93d4b3.jpg)
![Screenshot_20190809-144426_PPSSPP](https://user-images.githubusercontent.com/6281100/62781282-2be14880-baa7-11e9-8f55-7169812cab20.jpg)
![Screenshot_20190809-144439_PPSSPP](https://user-images.githubusercontent.com/6281100/62781284-2c79df00-baa7-11e9-9f73-8248650ba3ee.jpg)
Toca3:
![Screenshot_20190809-145230_PPSSPP](https://user-images.githubusercontent.com/6281100/62781298-33085680-baa7-11e9-8af4-3902b5ba103a.jpg)
![Screenshot_20190809-145619_PPSSPP](https://user-images.githubusercontent.com/6281100/62781300-33085680-baa7-11e9-8747-9e027e81eb59.jpg)
![Screenshot_20190809-145648_PPSSPP](https://user-images.githubusercontent.com/6281100/62781301-33085680-baa7-11e9-9403-abda40466e53.jpg)

Thank you for the fix!

**Comment by hrydgard** [comment] 2019-08-09 13:15
@blisstik Black water in outrun happens on other GPUs too, so at least the glitches are in sync now, heh..

**Comment by hrydgard** [comment] 2019-08-09 13:15
@iXmerof  Glad you're getting good results!

**Comment by Drasikk** [comment] 2019-08-09 16:16
@iXmerof I've tried that setup you've put in me Samsung Galaxy Note 8 and... ¡¡¡wow!!! It goes much better than with the configuration that comes with the emulator as standard. As you said it stays at 40-44fps.

Thanks to you too! 😀 

![PPSSPP_2019-08-09-18-06-54](https://user-images.githubusercontent.com/38067925/62793191-416b6800-bad1-11e9-99e7-4341c599c950.jpg)
