### ISSUE TITLE
iOS version freezes if quit improperly

### ISSUE THREAD

**Issue by mygizli04** [hrydgard/ppsspp#11645] opened 2018-12-07 16:39 UTC
### What happens?
When quit improperly ( go to the home screen and kill through the app switcher ) PPSSPP will NOT work unless the device is rebooted ( It'll get stuck in the default launch screen, which is just a plain blue background ) . Switching to IR Interpeter doesn't help, and i don't even think changing the CPU Core worked ( even after a reset ) since i had no graphical/performance changes whatsoever so i'll open another issue about that.

### What *should* happen?
It should be able to relaunch without having to reboot device in case of a forced termination.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
iPhone 6, iOS 12.0.1 ( cleaned up the jailbreak by DFU restore so no jailbreak trails should be left ) , PPSSPP version 1.6.3-456-g6d0ed4a.

**Comment by mygizli04** [comment] 2018-12-07 18:43
Something leds me to believe this is an iOS problem, since you can’t single click the home button to leave, you have to click twice to bring the app switcher, then leave.

**Comment by unknownbrackets** [comment] 2018-12-08 05:50
This issue is being closed as a duplicate of #9186.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-12-08 05:50 UTC
