### ISSUE TITLE
WLAN control binding does nothing

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#15420] opened 2022-02-26 20:35 UTC
### Game or games this happens in

All Games

### What area of the game / PPSSPP

PPSSPP control settings got a way to bind the WLAN button that the PSP got but it doesn't really work.
![image](https://user-images.githubusercontent.com/33392696/155858279-be2f6e0d-9071-4ab9-af89-c769a309f637.png)

### What should happen

It should toggle WLAN on/off.

### Platform

Linux / BSD

### Mobile phone model or graphics card

AMD GPU

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by MojoJojoDojo** [comment] 2022-02-27 04:02
It could be used to save resources I suppose.
As I understand the option "Built-in proadhocserver" could take more CPU time and therefore battery life when its active.
So if you finished playing multiplayer and wanna just play single player and vice versa it could be useful without going each time to menu manually.

**Comment by ANR2ME** [comment] 2022-02-27 11:12
I'm planning to make built-in adhoc server to run as soon as it's enabled from networking settings, regardless whether there are games running or not, which also regardless whether the WLAN is on/off.

Because there are games which seems to reboot the emulation when loading a new module (ie. when selecting one of the game on Star stone collection, or when loading multiplayer module on a game.. i forgot which game)
This will trigger the shutdown process and reinitialize PSP emulation, which will also triggers the adhoc server to shutdown and cause connectivity issue on players already connected to the adhoc server (may also cause unexpected behavior on some games when the adhoc server suddenly disappear)


So disabling WLAN just to disable built-in server is kinda overkill, since built-in adhoc server is disabled by default.
Even when adhoc server is running, as long nobody connected to it, most of the time the adhoc server thread will be sleeping (or blocked by `select` waiting for incoming data) anyway.

**Comment by MojoJojoDojo** [comment] 2022-02-27 12:03
> 
> PS
While the only useful use case of toggling WLAN is probably for testing purpose, to compare the game behavior with real PSP when WLAN is turned off in the middle of multiplayer, whether it will shows an error dialog (expected behavior), or shows unexpected behavior (freezes/crashed)

Yeah thats the use case I have mentioned...
Because on real PSP you can disable it in real time.

**Comment by ANR2ME** [comment] 2022-02-27 14:29
> 
> Also if adhoc server is sleeping in the background why not enable it all the times anyway? lol.

because it will open the port if you have UPnP enabled, and opening a port when not using it is kinda unsafe.

**Comment by xiaolang0668** [comment] 2022-03-03 04:37
Can you get an ad hoc server and go P2P online.

I want to build one for community members to play together.

**Comment by ANR2ME** [comment] 2022-03-03 06:37
> Can you get an ad hoc server and go P2P online?
> 
> I want to build one for community members to play together.

If you want to run your own public server, you can find "adhoc server" on github, but this is out of topic.

**Comment by xiaolang0668** [comment] 2022-03-03 06:40
I built one before, I couldn't see the team members, I could only chat.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hrydgard/ppsspp] WLAN control binding does nothing (Issue #15420)





  
Can you get an ad hoc server and go P2P online?
 
I want to build one for community members to play together.
  
If you want to run your own public server, you can find "adhoc server" on github, but this is out of topic.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NABN00B** [comment] 2024-01-31 16:49
I think we can close this with #17352 for now. At one point we should make a discussion regarding virtual keys vs system keys.

**Closed** 2024-01-31 17:07 UTC
