### ISSUE TITLE
Implement ABI detection for ARM targets.

### ISSUE THREAD

**Issue by Sonicadvance1** [hrydgard/ppsspp#7394] opened 2015-01-31 09:04 UTC
Currently the ffmpeg linux scripts assume soft ABI while building.
Instead of assuming, detect the ABI in cmake and build ffmpeg and tools appropriately.

**Comment by Sonicadvance1** [comment] 2015-01-31 09:06
This is in relation to issue #7372

**Comment by sergiobenrocha2** [comment] 2015-02-03 04:49
One question related: why the path for ffmpeg is "linux/armv7"? Maybe it should be linux/armv7l, like what uname -m gives

**Comment by unknownbrackets** [comment] 2022-11-20 23:17
I think our only real problem here is ffmpeg, and so this is essentially the same issue as #15969.  That has more activity, so I'm going to close this one (despite it being older) as a duplicate of it.

-[Unknown]

**Closed by unknownbrackets** 2022-11-20 23:17 UTC
Labels: Platform-specific (Linux/POSIX), Feature Request
