### ISSUE TITLE
Odd texture issue with the flashlight in Silent Hill: Origins

### ISSUE THREAD

**Issue by KojiKenshiro** [hrydgard/ppsspp#19123] opened 2024-05-10 14:22 UTC
### Game or games this happens in

ULUS-10285 Silent Hill: Origins

### What area of the game

Various spots throughout the game.
![ULUS10285_00001](https://github.com/hrydgard/ppsspp/assets/46720179/9d54bf56-eed5-4714-a5de-6c0a3b0fd738)
![ULUS10285_00000](https://github.com/hrydgard/ppsspp/assets/46720179/62a9a9d8-5758-4fc9-bc5e-897f693af712)

### What happens

Wierd texture mapping issue relating to using the flashlight.

### What should happen

Flashlight should light textures as intended.

### Platform

Windows

### Mobile device model or graphics card (GPU)

GeForce RTX 3060

### PPSSPP version affected

All-Latest Dev Build

### Last working version

None

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2024-05-10 16:05
Yeah, it's well known that the graphics are broken in this game. Will get back to it eventually but it's a hard one. 

So, closing as a duplicate of #16126

**Closed by hrydgard** 2024-05-10 16:05 UTC
