### ISSUE TITLE
Spider-Man 3 Crashes once I reach an enemy

### ISSUE THREAD

**Issue by MDr4gonX** [hrydgard/ppsspp#17655] opened 2023-07-02 16:49 UTC
### Game or games this happens in

ULUS-10317

### What area of the game / PPSSPP

When I reach an enemy, a 99.9% chance I get a ton of "Invalid memory acceses" screens, and in the end I get a "Bad Execution Adress" which makes me exit the game
![Screenshot_20230630_113950_PPSSPP Gold](https://github.com/hrydgard/ppsspp/assets/138389633/4b567f9e-81f2-4603-801d-3edddbb54428)

### What should happen

The game should not crash, I tried it on all my family members phones and it works perfectly fine. But just on mine it crashes

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy S22

### PPSSPP version affected

V1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2023-07-03 10:44
It's strange if it only happened on your Samsung Galaxy S22
I think you'll need to provide a savestate near/before the crash location for the devs to test it.

**Comment by MDr4gonX** [comment] 2023-07-03 16:51
> It's strange if it only happened on your Samsung Galaxy S22. I think you'll need to provide a savestate near/before the crash location for the devs/others to test it.

Well here

**Comment by ANR2ME** [comment] 2023-07-03 18:54
You can zip the savestate and upload it here along with your post, and make sure it have the .zip extension otherwise github will rejects the file.

**Comment by MDr4gonX** [comment] 2023-07-04 01:26
> You can zip the savestate and upload it here along with your post, and make sure it have the .zip extension otherwise github will rejects the file.

Thanks, here it is 
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/11943390/PPSSPP_STATE.zip)

**Comment by unknownbrackets** [comment] 2023-07-15 20:07
This sounds like a duplicate of #15825 or #10196.

-[Unknown]

**Closed** 2023-07-15 20:08 UTC

**Comment by hrydgard** [comment] 2023-07-15 20:23
Yeah I guess we have a bunch, but they're strangely a bit different (one crashes immediately, the other when beating some enemies). Fair closing this one though.
