### ISSUE TITLE
Add: Run / Verify / Unpack .pkg files

### ISSUE THREAD

**Issue by IX-285** [hrydgard/ppsspp#15790] opened 2022-08-05 13:12 UTC
### What should happen

PPSSPP by default has no available support for .pkg files,which are in (rare) ocassions used in dumps of some PSP games

There are 3rd party tools,but this common feature should be in PPSSPP

### Who would this benefit

Game owners that go through tedious processes,game preservation people and more...

### Games this would be useful in

For all games in .pkg format

### Other emulators or software with a similar feature

While not exactly .pkg,other emulators do support other formats other than this formats already available at PPSSPP

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment] 2022-08-05 13:34
Closing as a duplicate of https://github.com/hrydgard/ppsspp/issues/14957

**Closed by LunaMoo** 2022-08-05 13:34 UTC
