### ISSUE TITLE
Graphic problems in Star Wars - The Force Unleashed

### ISSUE THREAD

**Issue by CristobalManga** [hrydgard/ppsspp#15026] opened 2021-10-17 22:47 UTC
### Game or games this happens in

ULUS-10345

### What area of the game

in the whole game
![image](https://user-images.githubusercontent.com/78171867/137646554-9b900b75-957f-4790-9ea1-bd6b216c236f.png)

### What happens

When starting the game in Windows with DirectX 11, or OpenGL, the error that we see on the screen appears.

The problem is corrected when putting it in DirectX 9, but that brings other problems, such as lack of light etc.

I did the test on Android and the same happens with OpenGL.

Now here comes the big surprise that takes me.

Use the "Remote Disc Streaming" feature to play the game on Android and magically the game runs flawlessly without any graphics glitch with OpenGL.

I did it in Vice versa, and it also worked on PC with DirectX 11.

So when sharing the game via "Remot disc streaming" the error is corrected. quite strange, but real.

But use the ISO hosted on PC or Android, it doesn't work. It only works when I run the game via streaming

### What should happen

Be without the graphic error lol

### Platform

Android

### Mobile phone model or graphics card

Pixel 2

### PPSSPP version affected

1.12.2

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2021-10-17 22:57
This issue is being closed as a duplicate of #9572.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-10-17 22:57 UTC

**Comment by Gamemulatorer** [comment] 2021-10-18 00:32
@CristobalManga try this https://github.com/hrydgard/ppsspp/issues/12949#issuecomment-934251037
