### ISSUE TITLE
Star Ocean First Departure weird stuff when change rendering resolution

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13476] opened 2020-09-24 21:55 UTC
Usually i change my game to 3x in rendering resolution but in SOFD when I do that the sprite is completely missing from screen and when I change it to 2x the character is cut in half. The only normal one is when I use 1x rendering resolution. Is this a bug or not? 

1x 
![Screenshot_20200925-045031](https://user-images.githubusercontent.com/67026697/94204303-35b44e00-feeb-11ea-8474-572dee7aa374.png)

2x
![Screenshot_20200925-045002](https://user-images.githubusercontent.com/67026697/94204314-3a790200-feeb-11ea-834a-6fe0d6fd794a.png)
![Screenshot_20200925-045009](https://user-images.githubusercontent.com/67026697/94204318-3cdb5c00-feeb-11ea-8f67-efaab54a8a04.png)

3x
![Screenshot_20200925-045019](https://user-images.githubusercontent.com/67026697/94204338-4238a680-feeb-11ea-876b-ca8d8553de7e.png)

**Comment by hrydgard** [comment] 2020-09-24 21:59
That's a bug, strange.

**Comment by Panderner** [comment] 2020-09-25 09:16
It's seems the older versions and builds of PPSSPP works in upscaled resolution of this game. Investigate when the last build worked.

**Comment by Gamemulatorer** [comment] 2020-09-30 17:14
This issue is related to this two #12385 & #10634 ?
Also what device are you using and what is ths specs!? 🤔

**Comment by Lemoncak3** [comment] 2020-09-30 17:35
I don't know but in 1x it works though but when i raised the resolution until 3x resolution the sprite were all gone from the screen. Using asus max pro M2, snapdragon 660 with 4gb ram.

**Comment by Gamemulatorer** [comment] 2020-10-01 03:23
> Usually i change my game to 3x in rendering resolution but in SOFD when I do that the sprite is completely missing from screen and when I change it to 2x the character is cut in half. The only normal one is when I use 1x rendering resolution. Is this a bug or not?
> 
> 1x
> ![Screenshot_20200925-045031](https://user-images.githubusercontent.com/67026697/94204303-35b44e00-feeb-11ea-8474-572dee7aa374.png)
> 
> 2x
> ![Screenshot_20200925-045002](https://user-images.githubusercontent.com/67026697/94204314-3a790200-feeb-11ea-834a-6fe0d6fd794a.png)
> ![Screenshot_20200925-045009](https://user-images.githubusercontent.com/67026697/94204318-3cdb5c00-feeb-11ea-8f67-efaab54a8a04.png)
> 
> 3x
> ![Screenshot_20200925-045019](https://user-images.githubusercontent.com/67026697/94204338-4238a680-feeb-11ea-876b-ca8d8553de7e.png)

I can't reproduce this issue on my old Mediatek Mali-450 GPU android phone 🤨
### 1X PSP Resolution
![Screenshot_2020-10-01-11-19-03](https://user-images.githubusercontent.com/37603562/94761662-301da300-03d8-11eb-8421-8fff8253aca4.png)
### 2X PSP Resolution
![Screenshot_2020-10-01-11-16-30](https://user-images.githubusercontent.com/37603562/94761700-475c9080-03d8-11eb-8de8-c2fffdc5694e.png)
### 3X PSP Resolution
![Screenshot_2020-10-01-11-16-52](https://user-images.githubusercontent.com/37603562/94761735-5c392400-03d8-11eb-9621-71c4ed453339.png)
### 4X PSP Resolution
![Screenshot_2020-10-01-11-17-47](https://user-images.githubusercontent.com/37603562/94761763-6eb35d80-03d8-11eb-89d2-d934aac0b3f2.png)

Probably this is a specific adreno gpu issue? 🤔

**Comment by Panderner** [comment] 2020-10-01 04:48
> > Usually i change my game to 3x in rendering resolution but in SOFD when I do that the sprite is completely missing from screen and when I change it to 2x the character is cut in half. The only normal one is when I use 1x rendering resolution. Is this a bug or not?
> > 1x
> > ![Screenshot_20200925-045031](https://user-images.githubusercontent.com/67026697/94204303-35b44e00-feeb-11ea-8474-572dee7aa374.png)
> > 2x
> > ![Screenshot_20200925-045002](https://user-images.githubusercontent.com/67026697/94204314-3a790200-feeb-11ea-834a-6fe0d6fd794a.png)
> > ![Screenshot_20200925-045009](https://user-images.githubusercontent.com/67026697/94204318-3cdb5c00-feeb-11ea-8f67-efaab54a8a04.png)
> > 3x
> > ![Screenshot_20200925-045019](https://user-images.githubusercontent.com/67026697/94204338-4238a680-feeb-11ea-876b-ca8d8553de7e.png)
> 
> I can't reproduce this issue on my old Mediatek Mali-450 GPU android phone 🤨
> 
> ### 1X PSP Resolution
> ![Screenshot_2020-10-01-11-19-03](https://user-images.githubusercontent.com/37603562/94761662-301da300-03d8-11eb-8421-8fff8253aca4.png)
> 
> ### 2X PSP Resolution
> ![Screenshot_2020-10-01-11-16-30](https://user-images.githubusercontent.com/37603562/94761700-475c9080-03d8-11eb-8de8-c2fffdc5694e.png)
> 
> ### 3X PSP Resolution
> ![Screenshot_2020-10-01-11-16-52](https://user-images.githubusercontent.com/37603562/94761735-5c392400-03d8-11eb-9621-71c4ed453339.png)
> 
> ### 4X PSP Resolution
> ![Screenshot_2020-10-01-11-17-47](https://user-images.githubusercontent.com/37603562/94761763-6eb35d80-03d8-11eb-89d2-d934aac0b3f2.png)
> 
> Probably this is a specific adreno gpu issue? 🤔

@Gamemulatorer what region of this game are you using?

**Comment by Gamemulatorer** [comment] 2020-10-01 05:10
USA 🇺🇲

**Comment by Panderner** [comment] 2020-10-01 05:45
> USA 🇺🇲

Check your refresh rate of your phone

**Comment by Gamemulatorer** [comment] 2020-10-01 05:57
> > USA 🇺🇲
> 
> Check your refresh rate of your phone @Gamemulatorer

What's the connection of refresh rate in this issue!?🙃

**Comment by Panderner** [comment] 2020-10-01 06:00
> > > USA 🇺🇲
> > 
> > 
> > Check your refresh rate of your phone @Gamemulatorer
> 
> What's the connection of refresh rate in this issue!?🙃

because your phone is locked at 56 fps

**Comment by Lemoncak3** [comment] 2020-10-01 06:04
Well i don't know, i am using asus max pro m2 with snapdragon 660 chipset with 4gb ram.

**Comment by Gamemulatorer** [comment] 2020-10-01 06:25
> > What's the connection of refresh rate in this issue!?🙃
> 
> because your phone is locked at 56 fps

@Panderner I really don't get it what is the connection of refresh rate in this issue about 2D sprite missing character when psp resolution is set to 2X resolution or more on adreno gpu phone 🧐🤔

Because on my phone with mali gpu I don't have this issue using ppsspp latest git build.

Na buang nako sa imo 🤪

**Comment by Gamemulatorer** [comment] 2020-10-01 06:28
> Well i don't know, i am using asus max pro m2 with snapdragon 660 chipset with 4gb ram.

You better upload this game ge dump here :)

**Comment by Gamemulatorer** [comment] 2020-11-05 16:16
I can also reproduce this issue on my new phone 😶 I'm using the latest ppsspp git build

###Phone Specs
[DevCheck-20201105-2245.txt](https://github.com/hrydgard/ppsspp/files/5495543/DevCheck-20201105-2245.txt)

**Comment by Gamemulatorer** [comment] 2020-11-05 16:20
X1 rendering resolution & Native Display
![Screenshot_20201105-170837](https://user-images.githubusercontent.com/37603562/98266555-6e087b00-1fc5-11eb-918a-59ff4444f5cc.png)
X2 rendering resolution & Native Display
![Screenshot_20201105-170902](https://user-images.githubusercontent.com/37603562/98266637-824c7800-1fc5-11eb-9b0c-3ceecd32a19f.png)
X3 rendering resolution & Native Display
![Screenshot_20201105-170914](https://user-images.githubusercontent.com/37603562/98266835-b6c03400-1fc5-11eb-90da-a6ff58ea7dfb.png)
X3 rendering resolution & 1X resolution display
![Screenshot_20201105-170935](https://user-images.githubusercontent.com/37603562/98266947-d192a880-1fc5-11eb-87cc-628a8be579c6.png)

**Comment by hrydgard** [comment] 2020-11-11 22:15
Note to self: Got repro on my Pocophone F1, OpenGL only.

**Comment by hrydgard** [comment] 2020-11-11 22:49
Should be fixed now.

**Closed by hrydgard** 2020-11-11 22:49 UTC
Labels: GE emulation, OpenGL
