### ISSUE TITLE
games closing in the new vesao of ppsspp v1.5.3

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10235] opened 2017-12-02 22:09 UTC
these two games are closing in 5 to 2 minutes of emulation by the vulkan api are they guiltar gear xx acentecore plus and blazblue continuum shift

**Comment by LunaMoo** [comment] 2017-12-02 22:33
Closing this as a duplicate of #10220.

 Please don't open new issues about same thing for attention. Also understand that while currently noone might have idea how to help you not being able to reproduce such problem and/or don't have time to even think about it. If you choose to become annoying things will likely change, but instead getting the attention you want, you will quite the opposite end up being ignored.

**Closed by LunaMoo** 2017-12-02 22:33 UTC
