### ISSUE TITLE
Motorstorm Arctic Edge: Black shaped textures under every vehicles and no sound at all

### ISSUE THREAD

**Issue by Bliean** [hrydgard/ppsspp#12027] opened 2019-05-10 03:25 UTC
### What happens?
At the beginning of playing the game the audio works just fine and i can hear everything perfectly fine but the moment I play a race the audio doesn't play and these black shaped textures under every vehicle.

### What *should* happen?
It should play perfectly fine and run well I would assume.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I am using a Gaming PC with windows 10. The version of PPSSPP is 1.8.0 and the GPU I use to play the game is a Titan X Maxwell 12GB with an Intel i5-7600k CPU running at 3.8GHz.

### Recording.
https://www.mediafire.com/file/t4ctov41t927m2r/recording_%281%29.ppdmp/file

**Comment by benderscruffy** [comment] 2019-05-10 07:14
duplicate of #7552 and #7445

**Comment by LunaMoo** [comment] 2019-05-10 10:04
Closing as a duplicate of the mentioned issues.

**Closed by LunaMoo** 2019-05-10 10:04 UTC
