### ISSUE TITLE
SOCOM: U.S. Navy SEALs Fireteam Bravo 3 ( Bug )

### ISSUE THREAD

**Issue by EPIC3477** [hrydgard/ppsspp#16935] opened 2023-02-08 10:30 UTC
### Game or games this happens in

UCES-01242 - SOCOM: U.S. Navy SEALs Fireteam Bravo 3

### What area of the game / PPSSPP

![bug1](https://user-images.githubusercontent.com/91116523/217502356-475b0a49-8a62-4b23-ba39-c6d3be095c39.JPG)
![bug2](https://user-images.githubusercontent.com/91116523/217502382-05f16a09-ed98-4c7e-a8b4-292c22eeb2aa.JPG)
![bug 3](https://user-images.githubusercontent.com/91116523/217502404-8601cb62-141f-4ed3-ac49-5ac74fadfbcd.JPG)

### What should happen

I played it for the 1st time and I saw that the character customization did not appear, and the grass flickered and glitched

(sorry for bad english)

### Platform

Windows

### Mobile phone model or graphics card

windows 7 intel core i5-3210M

### PPSSPP version affected

v1.14.4

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment] 2023-02-08 11:28
Duplicate https://github.com/hrydgard/ppsspp/issues/6963
Related https://github.com/hrydgard/ppsspp/issues/11814, https://github.com/hrydgard/ppsspp/issues/10461, https://github.com/hrydgard/ppsspp/issues/9802, https://github.com/hrydgard/ppsspp/issues/16747 and https://github.com/hrydgard/ppsspp/issues/16210

**Comment by hrydgard** [comment] 2023-02-15 11:26
Closing as duplicate of #6963 indeed.

**Closed by hrydgard** 2023-02-15 11:26 UTC
Labels: GE emulation
