### ISSUE TITLE
Graphics Bugs in MH 3rd HD in Mali 450 & 400 GPU 

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#11159] opened 2018-06-09 03:55 UTC
### What happens?

As the title say there's a grapics bugs in Mali-450 & 400 but didn't happen in Mali-T GPU above
### What *should* happen?
Maybe you can fix this same way you fix in Mali-T GPU?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Mali-450 & 400
Android 5.1 & 6.0
PPSSPP 1.6.3

**Comment by Jinzombie** [comment] 2018-06-09 03:56
![fb_img_15285033197387720](https://user-images.githubusercontent.com/37603562/41187446-0d57ee40-6b99-11e8-90da-500d173e5720.jpg)
In mali-450 & 400 gpu

**Comment by Jinzombie** [comment] 2018-06-09 03:58
![fb_img_15285033254258626](https://user-images.githubusercontent.com/37603562/41187462-3b3ee052-6b99-11e8-9666-30b6d3df0db3.jpg)
In Mali 450 & 400 gpu

**Comment by unknownbrackets** [comment] 2018-06-09 06:14
This issue is being closed as a duplicate of #7218.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-06-09 06:14 UTC
