### ISSUE TITLE
[Android] Metal Gear Solid Peace Walker Freeze When Playing Extra Ops 38/67 And Main Mission Zadornov Search 3

### ISSUE THREAD

**Issue by FalloutClassicGamer** [hrydgard/ppsspp#19453] opened 2024-09-13 05:05 UTC
i tried 2 different saves its just freeze when playing that level

**Comment by hrydgard** [comment] 2024-09-13 10:36
Duplicate ofr #19452, closing

**Closed by hrydgard** 2024-09-13 10:36 UTC
