### ISSUE TITLE
Vulkan Glitches Midnight Club 3

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#11709] opened 2019-01-03 02:10 UTC
I bought the Redmi Note 6 Pro yesterday, and when I tried to play MC3 with Vulkan, I noticed very broken graphics. I noticed too that I only get 60 FPS in menu at 1x resolution, but with OpenGL I can run the game fine at 2x resolution, I just don't have stable gameplay at 60 FPS with OpenGL (even lowering the resolution). I reduced the internal CPU clock to lock the game to 30 FPS so I can run at 3x resolution.

I heard that most recent Adreno drivers have broken Vulkan, but I'm not sure if it's the problem. Did someone complain about this before?

**Comment by GuilhermeGS2** [comment] 2019-01-03 15:23
Some samples:

https://i.imgur.com/0sMuDrC.jpg
https://i.imgur.com/tWkQ7Rt.jpg

**Comment by hrydgard** [comment] 2019-01-03 15:53
It has a 500-series Adreno, so it's affected by the stencil bugs. But this might be a different one, I think it's been reported before though?

**Comment by GuilhermeGS2** [comment] 2019-01-03 17:00
I don't know if it was reported before. I tested old releases, and the last official release without that issue was 1.5.4 (actually I only noticed a minor issue with the mini map, it doesn't fit in the circle), but this version had the issue with save data, the game stuck on menu after loading the save (I reported this issue before).

**Comment by GuilhermeGS2** [comment] 2019-01-03 17:03
I found this report with same issue: https://github.com/hrydgard/ppsspp/issues/10473

**Comment by GuilhermeGS2** [comment] 2019-01-04 13:41
I don't know if a need to create another issue, but with latest builds I have a lot o

**Comment by unknownbrackets** [comment] 2019-01-05 17:56
This issue is being closed as a duplicate of #10473.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-01-05 17:56 UTC
Labels: Vulkan
