### ISSUE TITLE
Thrillvile off the rails ad hoc problem

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#15160] opened 2021-11-22 13:12 UTC
### What happens?
whenever i tried the multiplayer mode we can see each other but when i connect the other player got kicked out and when she connect i got disconnected. Can you look into it? I remember can play it before but didn't remember when..

### What *should* happen?
We should get connected without the other gor disconnected

#### What hardware / device and operating system?
Zenfone max pro m2
#### What graphics card (GPU) or mobile phone model?
Snpadragon 660
#### What PPSSPP version (standalone/official), and did it work before?
1.12.3-230, the last version when it work I don't remember
#### Which game or games?

ULUS1306

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2021-11-22 16:49
If it worked before, please try to find out which version it was.
You can get all the older version from here https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
Try 1.11.x to 1.10.x and may be 1.9.x if it still didn't work

**Comment by ANR2ME** [comment] 2021-11-22 18:57
Okay i can reproduce this on localhost.
However, when i tested this using my test build that fixed Super Pocket Tennis, this game also worked fine, so i guess this game will be fixed along with Super Pocket Tennis (which had AdhocMatching issue)

**Comment by Lemoncak3** [comment] 2021-11-24 09:20
So i need to download the newest ppsspp build then?

**Comment by ANR2ME** [comment] 2021-11-24 15:28
I haven't made the PR yet, just a test build as it will affects many games since the timing was changed, thus some games might be broken while others got fixed (there are about 4 or 5 games that got fixed along with Super Pocket Tennis)
Since i'm planning to changed AdhocMatching threads and the way it "delays" the loop to check events, that PR might no longer be needed.

It seems you won't be able to download the fix anytime soon, since i didn't have much time to do coding, and when i do have the time, i always fall asleep a few minutes after opening Visual Studio and decides to go to bed instead (i've been lacking of sleep recently), so the progress is really slow.

**Comment by Lemoncak3** [comment] 2021-11-24 17:45
Okay take your time, real life is more important will wait patiently :)

**Closed** 2022-01-19 21:09 UTC
Labels: Networking / adhoc
