### ISSUE TITLE
Android:Cannot install newer version over old one 

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#12029] opened 2019-05-11 16:58 UTC
I don't know if this is some kind of limitation or restriction on the OS(Lollipop 5.1.0)or there is something wrong with ppsspp but for example
If install 1.8.0 and then try to install the latest beta,the installation fails

This happens almost always when I try to update ppsspp  on my phone(which is something I don't do often)

If I uninstall it first then there is no problem
Edit:I am downloading ppsspp from the main page,not from playstore

**Comment by hrydgard** [comment] 2019-05-11 17:57
Different signing keys are used unfortunately, not trivial to fix. Just something to live with for now.

**Comment by vsub** [comment] 2019-05-11 20:50
Ok then,thanks for the info
I am not sure if I should close this.

**Comment by hrydgard** [comment] 2019-05-12 03:53
Let's leave it open.

**Comment by Emulatorer** [comment] 2019-05-12 05:03
@vsub  If ever your phone is rooted just download JasiPatcher and enable the Disable Signature Check setttings inside Hook
![Screenshot_2019-05-12-13-00-54](https://user-images.githubusercontent.com/37603562/57578005-46128700-74b6-11e9-9707-92cdfe675fd9.png)
You can now install ppsspp beta from buildbot without uninstalling the older version

**Comment by vsub** [comment] 2019-05-12 08:52
It is not rooted and I have tons of problems because of that but I don't want to risk it trying to root it because it is some weird unknown brand(ever heard of Landvo)

**Comment by Emulatorer** [comment] 2019-05-12 09:53
Rooting is safe as long as you follow the right procedure to root
especially android 5.1 or below like my phone (cloudfone excite prime) but
still depend on you Im just suggesting the best option or wait the
developers to fixed this issue somewhere in the future :)

**Comment by marosis** [comment] 2019-05-13 11:32
If you have downloaded version from google play and now you want update to beta for example 1.8.0 abc123 you can't! Firstly uninstal google play version and after that instal beta version.(you will not lose any data or savestates)

**Comment by hrydgard** [comment] 2019-05-13 11:37
indeed. I do want to fix this before the new storage changes for post-Q Android, since for people who have upgraded, fully uninstalling will cause an annoying experience....

**Comment by marosis** [comment] 2019-05-13 11:38
Yeah little bit but issue is only with no build versions

**Comment by vsub** [comment] 2019-05-13 15:10
I download 1.8.0 from the main download page,not from google play(I am not sure if there is any difference)and then when I tried to install the beta,I get an error

**Comment by hrydgard** [comment] 2019-05-13 15:28
As previously discussed in the thread, that's currently expected but I hope to find a fix in the future.

**Comment by unknownbrackets** [comment] 2022-07-13 03:10
I'm going to close this as a duplicate of #15612 which has more technical discussion.  I realize that one was created more recently.  This is the issue I was thinking of there in my first comment...

-[Unknown]

**Closed by unknownbrackets** 2022-07-13 03:10 UTC
Labels: Platform-specific (Android)

**Comment by MojoJojoDojo** [comment] 2022-07-13 08:48
TBH I really tried to find another issue and never found one like I always do before opening an issue.
