### ISSUE TITLE
[Android][OpenGL]Traxxpad lag - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13178] opened 2020-07-22 06:36 UTC
Hi,me again.Today i came across interesting bug.Simple game called Traxxpad (well,more music studio than game) runs good in menus,but when you make music,game is just slow,it can't reach 60FPS.To be sure it is not device issue,game is tested on NVIDIA SHIELD Android TV,here is link:https://www.youtube.com/watch?v=rU-NghmyjaU.I can provide GE Dump tomorrow if you need it,i'm busy today with investigating #13141 ,but if you want,i could do so by evening.

TIA

**Comment by Panderner** [comment] 2020-07-22 07:46
@EX-e-LD have you tried this game without frameskip?

**Comment by Panderner** [comment] 2020-07-22 07:49
it's seems it's a duplicate of #11067

**Comment by hrydgard** [comment] 2020-07-22 08:34
Duplicate of #11067

**Closed by hrydgard** 2020-07-22 08:34 UTC
Labels: Audio

**Comment by Gamemulatorer** [comment] 2020-07-22 09:36
This is not a game?
![1595410525489](https://user-images.githubusercontent.com/37603562/88160909-e4b18080-cc41-11ea-9fd7-918ee6759c3a.png)
