### ISSUE TITLE
Crash Tag Team Racing - All Dark Textures on Pi 3

### ISSUE THREAD

**Issue by autumnation** [hrydgard/ppsspp#11491] opened 2018-10-26 14:37 UTC
### What happens?
Textures in-game (meaning, not cutscenes or menus) are all black / dark. Some look fine, such as crash himself, arrows, buttons, and gears, but that is it.

### What *should* happen?
Textures should be visible. According to the [PSP compatibility list for RetroPie](https://docs.google.com/spreadsheets/d/1V-MEx1tOXqCcJL1fQzGh9xLHny-qL-PSWqvY7F80Y90/edit#gid=139803120), PPSSPP supports CTTR on the Pi 3. I am running on the Pi 3, overclocked in fact, using default settings for PPSSPP, no hacks, and yet the textures are not properly visible.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Raspberry Pi 3 Model B+, Retropie 4.4, PPSSPP latest version as of 10/26/2018. GPU is only capable of running OpenGL but again, people have successfully ran the game in the past with no issues.

**Comment by LunaMoo** [comment] 2018-10-26 23:39
If you can test, check which was the last one working/which was first broken, I would suspect v1.6.3-478-gacfd68864 as this is probably another case where vertex range culling will have to be disabled.

**Comment by rowanaut20** [comment] 2018-10-27 01:09
I do not know how to test for that unfortunately. How would I disable this vertex range culling thing?

**Comment by AkiraJkr** [comment] 2018-10-27 01:12
You can't really "disable" it, but more like, downgrade to a version before it was implemented.

You can check the full list of builds here. Just pick the one before the vertex range was implemented.

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by rowanaut20** [comment] 2018-10-27 01:15
Couldn't I manually just edit the file(s) related to that pull request? Can't really downgrade to any of those versions as I am on Linux and most of those versions dont support Android.

**Comment by hrydgard** [comment] 2018-10-27 07:41
@rowanaut20  We should detect your GPU and turn it off. If you go to Settings / Tools / System Information, what does it say under "Vendor" and "Vendor (detected)"?  Exact quotes or a screenshot should be fine.

**Comment by rowanaut20** [comment] 2018-10-27 12:36
Vendor: Broadcom
Vendor (Detected): VENDOR_BROADCOM
Driver Version: VideoCore IV HW

ABI: armeabi

**Comment by unknownbrackets** [comment] 2018-10-27 15:32
Find this line:

https://github.com/hrydgard/ppsspp/blob/fa40bcff8d90cdb08117e95bee9c3a4ecb6b0b56/GPU/GLES/GPU_GLES.cpp#L171

And comment it out.  If that makes it start working, then yeah, VideoCore is not liking the range culling code.

In the GPU extensions list, do you have EXT_clip_cull_distance / GL_EXT_clip_cull_distance?

-[Unknown]

**Comment by rowanaut20** [comment] 2018-10-27 23:18
No, that didn't work. In fact, even if I go back to 1.5.4 it still does not work.

**Comment by unknownbrackets** [comment] 2018-10-28 01:01
Ah, maybe this is a duplicate of #5468?  It seems like if you set the hack to change the CPU clock, that can cause it to lock up.

-[Unknown]

**Comment by rowanaut20** [comment] 2018-10-28 01:08
I did not touch any sort of PSP hacks.

**Comment by unknownbrackets** [comment] 2019-06-23 20:39
Has this changed or improved at all?  We have fixed other bugs related to the Pi 3.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-09-15 03:21
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2021-09-15 03:21 UTC
Labels: No Feedback / Outdated?
