### ISSUE TITLE
How can I still not have an abnormal exit in the case of building a xcode project with the latest SDK?

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#11966] opened 2019-04-12 01:29 UTC
### What happens?
If PPSSPP was built by use the SDK of 12.0 or above to build the xcode project, When kills the PPSSPP from iOS App Switcher, It is not terminated properly. After this happens, Launching again PPSSPP from SpringBoard causes making iPhone unresponsive until reboot.
https://github.com/hrydgard/ppsspp/issues/9186#issue-197551130
https://github.com/hrydgard/ppsspp/issues/11905#issuecomment-476447186
https://github.com/hrydgard/ppsspp/issues/11905#issuecomment-482139285

### What *should* happen?
How can I still not have an abnormal exit in the case of building a xcode project with the latest SDK?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Only on iOS, v1.5.4 or above

**Comment by unknownbrackets** [comment] 2019-04-12 01:40
This issue is being closed as a duplicate of #9186.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-04-12 01:40 UTC
