### ISSUE TITLE
[iOS] Dynamic (JIT) on PPSSPP v1.4.2 does not work on ANY game 

### ISSUE THREAD

**Issue by Vertpin** [hrydgard/ppsspp#9864] opened 2017-07-25 18:35 UTC
tried anything, nothing works. :(

**Comment by i30817** [comment] 2017-07-26 12:23
[it's apple's fault](http://lmgtfy.com/?q=JIT+on+iOS).

It's historically know for ages that the iOS walled garden is hostile to emulators. Requesting devs to solve this for you won't change anything, because it's the kernel itself getting in the way.

**Comment by Vertpin** [comment] 2017-07-26 15:05
I was pretty certain it had worked before on non-jailbroken devices, is the weird thing. I swear I read posts about it?

**Comment by i30817** [comment] 2017-07-26 18:12
Maybe they found a hack that was then closed later by a update. *shrug*. You've got to realize this is not a accident, but policy, so even if something is found to workaround, a update risks it getting shut down hard. It's not the job of emu devs to be iOS hackers.

**Comment by unknownbrackets** [comment] 2017-07-30 17:48
Closing this as a duplicate of #7360.

Remember that basically, whenever PPSSPP works on an iOS device, someone files a bug in Apple's issue list.  Eventually they may fix that bug, and it will stop working.  When it keeps working, it just means Apple hasn't gotten around to fixing that bug yet.

It's completely expected that new iOS releases will include iOS bug fixes, so it makes sense that updating would've made PPSSPP stop working.

This will be a never ending problem as long as Apple's policies stay the same.  You can either switch vendors, somehow convince them to change their policies, or just live with the problem that updates *will* stop PPSSPP from working.

-[Unknown]

**Closed by unknownbrackets** 2017-07-30 17:48 UTC
Labels: Platform-specific (iOS)
