### ISSUE TITLE
Madden 12 Black Screen during Save creation

### ISSUE THREAD

**Issue by isbilly** [hrydgard/ppsspp#11422] opened 2018-09-25 16:31 UTC
### What happens?
When loading Madden 12 it gives me a black screen

### What *should* happen?
It should prompt to choose a save name for profile

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

GPD XD Plus - CleanRom

**Comment by isbilly** [comment] 2018-09-25 16:37
On a Windows 10 PC with PPSSPP 1.6.3 it opens and works fine.  

It shows the EA Sports intro and goes right to the main screen.  On the GPD XD Plus it goes to a black screen and you can hear the EA intro but it stays black.

**Comment by unknownbrackets** [comment] 2020-04-04 19:55
Has this improved in the latest git builds?  Are you able to try connecting the debugger and look at logs?

To do this, enable "remote debugging" in system settings, and then go to http://ppsspp-debugger.unknownbrackets.org/.  Once there, play the game until the issue occurs.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2020-05-12 05:42
Can't reproduce this issue anymore using ppsspp latest git.
screen recording as a proof :3
[recording_20200512_133032.zip](https://github.com/hrydgard/ppsspp/files/4613594/recording_20200512_133032.zip)

but this game is super lag on ma phone :/

**Comment by unknownbrackets** [comment] 2020-05-12 06:06
Thanks for checking.  I'll close this then.

-[Unknown]

**Closed by unknownbrackets** 2020-05-12 06:06 UTC
Labels: OpenGL, Platform-specific (Android)
