### ISSUE TITLE
Salvamento Manual No Moster hunter freedom 1 Nao fuciona

### ISSUE THREAD

**Issue by Hellaquismt** [hrydgard/ppsspp#17681] opened 2023-07-10 05:44 UTC
### Game or games this happens in

Monster hunter freedom 1

### What area of the game / PPSSPP

![Screenshot_20230710_023145_PPSSPP Gold](https://github.com/hrydgard/ppsspp/assets/139101427/8bc5a9c4-2e58-4cc8-b2dd-4466241d3a33)

### What should happen

O jogo deveria salvar normalmente  mas diz que o memory stick duo não está inserido 

### Platform

Android

### Mobile phone model or graphics card

Sansung galaxy a03

### PPSSPP version affected

1.15.4

### Last working version

1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2023-07-16 03:43
This issue is being closed as a duplicate of #7244.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2023-07-16 03:43 UTC

**Comment by Luchitogamer** [comment] 2024-06-12 10:45
Tengo el mismo problema 😞 ayuda xfavor.
