### ISSUE TITLE
Ace combat x sudden fps drop when playing intro video

### ISSUE THREAD

**Issue by dikorommel** [hrydgard/ppsspp#11533] opened 2018-11-05 01:02 UTC
https://imgur.com/a/pSl5YFj
ppsspp 1.7.1
buffered rendering,Open GL
Windows 7
device spec:
- Intel® Core i3-380M processor (3 MB L3 cache, 2.53GHz, DDR3 1066 MHz, 35 W)
- 2GB DDR3 RAM (upgradeable to 8GB)
- 500GB SATA HDD
- ATI Mobility Radeon™ HD 5470 with 512 MB of dedicated DDR3 VRAM
- 14' HD 1366 x 768 pixel resolution, high-brightness (200-nit) Acer CineCrystal™ TFT LCD
- 8X DVD Super Multi Plus Drive

**Comment by LunaMoo** [comment] 2018-11-05 10:06
If you're using video aware AA or supersampling post process, disable it, your hardware is not be fast enough for that, you should also avoid using higher rendering res multipliers as that gpu althrough dedicated is very weak.
 Same if you're using texture scaling. In theory it shouldn't work on videos, but in some games it still happens and again your cpu is not strong enough to scale video frames. Then again I don't think this game's videos are affected by texture scaling in any way.
 
 One more thing, which you could accidently use is enabling texture dump, this could potentially spam a lot of png's causing extreme lag on hdd's, potentially even on ssd's, so go into tools->dev tools->texture replacement and make sure "Save new textures" is disabled. it should never be used for playing games, it's only useful when creating texture packs.
 
 Either way I can't reproduce any video slowdown on my pc, On all backends it easily goes to around 2000% with unthrottle outside of direct 3D 9 backend which is limited to display refresh.

**Comment by unknownbrackets** [comment] 2018-12-02 22:33
Another user reported accidentally enabling video or audio recording, which could also be a factor here.

Hopefully that helped.  I'm going to close this assuming it did, but feel free to reply if it didn't.  That said, it might be better for the forum - this is meant as an issue tracker.

-[Unknown]

**Closed by unknownbrackets** 2018-12-02 22:33 UTC
Labels: No Feedback / Outdated?
