### ISSUE TITLE
Tony Hawk's Underground 2 Remix: Crash after a few seconds of gameplay (0.9.9.1-1061, Windows)

### ISSUE THREAD

**Issue by cmexp** [hrydgard/ppsspp#7210] opened 2014-12-22 01:35 UTC
Ever since this game was able to work without severe graphical glitches, it seems as if it crashes after less than a minute of gameplay (or in the case of Story Mode, the in-engine opening cutscenes if you don't skip them fast enough). The latest build I tried this on was 0.9.9.1-1061 on Windows 7 x64, but this issue had occurred for me ever since the 0.9.8 stable release, so I'm sure the newer builds have it too. With the default settings, the entire emulator crashes to desktop without a warning. With all the "unstable" and "experimental" features turned off, the game just gives a black screen and I'm able to exit into the main emulator menu.

Here's the log file after the black screen:

![ppsspp log](https://cloud.githubusercontent.com/assets/6110397/5520475/7496d3a2-8950-11e4-9676-f482952bab07.png)

**Comment by LunaMoo** [comment] 2017-05-09 02:31
Closing this as a duplicate of #3854

**Closed by LunaMoo** 2017-05-09 02:31 UTC
