### ISSUE TITLE
PSP Quake distorted sound

### ISSUE THREAD

**Issue by st1x51** [hrydgard/ppsspp#12095] opened 2019-06-10 13:45 UTC
PSP Quake mp3 have a distorted sound and playing very fast.
its uses this mp3 player
https://github.com/st1x51/ADQuake/blob/master/psp/mp3.c

in the last ppspp autobuild sound a little slower,but still playing fast

**Comment by LunaMoo** [comment] 2019-06-10 15:45
I'll close this as a duplicate of #6842 as it doesn't matter which quake or other game it's modded to run, it's still the same engine affected by same issue and was broken even worse in the past.

 Currently music in that Quake engine will only play correctly with a hack that [Unknown] mentions in that Quake 2 issue, my custom branch ~ https://github.com/LunaMoo/ppsspp/releases ~ includes that hack in case you're on windows and want to quickly test it. That hack will probably not end up in official PPSSPP releases since the project spirit goes against hacks, through as far as I tested, it doesn't negatively affect other mp3 playback.

**Closed by LunaMoo** 2019-06-10 15:45 UTC

**Comment by st1x51** [comment] 2019-06-10 17:38
yes,its working,big thanks
