### ISSUE TITLE
Gripshift crashes a lot

### ISSUE THREAD

**Issue by eltomas2003** [hrydgard/ppsspp#13801] opened 2020-12-20 18:54 UTC
### What happens?
It randomly crashes when selecting continue stage during gameplay.

### What *should* happen?
It should continue onto the next stage

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Ryzen 5 3500u with vega graphics, windows 10, 
ppsspp 1.10.3

**Comment by Panderner** [comment] 2020-12-20 19:12
Duplicate of #7601

**Comment by hrydgard** [comment] 2020-12-20 19:34
Yeah unfortunately this game still doesn't run well.

**Closed by hrydgard** 2020-12-20 19:34 UTC
