### ISSUE TITLE
Prince of Persia Revelations - Graphical issues and Sound delay

### ISSUE THREAD

**Issue by PlayerGameSK** [hrydgard/ppsspp#11506] opened 2018-10-28 18:07 UTC
### What happens?
SOUND DELAY - In-game it seems to be fine though in cutscenes (the "in-game" ones, not the FMVs... maybe even the FMVs, not entirely sure) it's too slow. Like that the voices don't sync with the characters mouths and so on... I think you get the idea.

GRAPHICAL ISSUES - We've already talked about this in the #help-support-questions channel of the PPSSPP official Discord server with one of the members, where I also posted a handful of screenshots so you can take a look there as well.
Basically, there are some problems with every single one of the cores:

OpenGL: After saving the game, parts of the "Do you want to save...?" prompt get "imprinted" on screen and stay there. I think saving again gets rid of them sometimes though I'm not sure. 
Also, this doesn't happen only when saving though it's probably the easiest way to reproduce the issue (try saving multiple times if it doesn't happen the 1st time).

Vulkan: Has two big squares starting at the top-left corner of the screen ever since you get to the main menu (I've posted a screen in #help-support-questions on Discord). Not sure if it also "imprints" stuff on screen like the previous one.

DX11: Same as Vulkan, but additionally has the entire main menu background (only the background, not the actual menu) black for some reason.

DX9: Same as OpenGL, with the exception that the main menu background (only the background, not the actual menu) AND the "imprints" I mentioned earlier are upside-down. The Dahaka chase scenes (when the screen gets kind of "sepia" themed) are also upside-down, though return to normal after the chase ends.

### What *should* happen?
- I don't really think I need to answer this one...

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- PPSSPP version: 1.7
- PC specs - OS: Windows 10 Home 64-bit
                    CPU: Intel Core i5-7400 3.00GHz
                    GPU: MSI GeForce GTX 1060 3GB
                    RAM: 16GB

I think that's pretty much all that's required... though if I missed something, feel free to ask! :)

Thanks in advance for any responses!

**Comment by unknownbrackets** [comment] 2018-10-28 18:42
Graphical glitches sounds the same as #11038 and #6423.

Is the sound delay new, or does it also happen in v1.6.3 and v1.5.4, etc?  I don't think that's been reported before, and I'm surprised.  This occurs even with default settings, right?

-[Unknown]

**Comment by PlayerGameSK** [comment] 2018-10-28 19:20
I think it does happen in 1.5.4 as well, though I'm not a 100% sure (might test it out later). And yeah, I'm fairly sure occurs with the default settings as well (I tried changing pretty much everything to various options and nothing seemed to change).

**Comment by LunaMoo** [comment] 2018-10-28 19:34
The lack of lipsync might be worth testing on real hardware, most psp games didn't had a proper lipsync and might appear bad on big screen despite working same as on psp.

**Comment by leopard20** [comment] 2018-11-03 13:09
@unknownbrackets
The sound problem is not new. In fact, I've been experiencing that since v.1.4.x

**Comment by PlayerGameSK** [comment] 2018-11-04 00:54
What about the graphics though?

**Comment by PlayerGameSK** [comment] 2018-11-24 19:41
Just started the game after some time of not playing it and it looks like it got even worse, the artifacts even jitter around though you obviously won't see that from a screenshot. The fun part is though... I didn't change a single thing. Everything's the same... the PC, the emulator version, the settings,... 🤔

![image](https://user-images.githubusercontent.com/13349715/48972358-dfdd9900-f028-11e8-9920-af472c77a8bc.png)

**Comment by unknownbrackets** [comment] 2018-11-24 19:45
#11584 will probably fix the D3D11 and D3D9 specific issues.

Not sure why it would jitter around.  If you try the latest git build, we've fixed some things with GE frame dumps.  It may help to create one and attach it here.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy** [comment] 2018-11-25 02:59
have just noticed as well on the top of the fires are glitchy lines
![prince](https://user-images.githubusercontent.com/2696404/48974896-27ebd280-f0a0-11e8-8d58-22aab1907de9.PNG)
here is a dump for opengl
[ULUS10063_0003.zip](https://github.com/hrydgard/ppsspp/files/2612784/ULUS10063_0003.zip)
and in dx11 it still has the 2 white squares on screen
![prince dx11](https://user-images.githubusercontent.com/2696404/48974940-05a68480-f0a1-11e8-8efb-6b3302bb4972.PNG)
[ULUS10063_0001 DX11.zip](https://github.com/hrydgard/ppsspp/files/2612789/ULUS10063_0001.DX11.zip)

**Comment by unknownbrackets** [comment] 2020-04-08 05:48
An early observation: this is texturing from depth in the dump.  That's where the lines and boxes come from.

Specifically, it textures at 12074/12102 from 0x04710000 using CLUT16 (ind >> 8).  So basically taking the high bits of depth.  This ends up using an older color framebuffer from earlier in the frame.

-[Unknown]

**Comment by hrydgard** [comment] 2020-04-26 10:00
Graphics issues are the same as #6423 , linking for reference.

**Comment by hrydgard** [comment] 2022-09-26 10:26
I'm gonna close this as a duplicate of #6423, in addition most of this is fixed. There's a remaining glitch with some fires having a glitchy repeated texture on them.

**Closed by hrydgard** 2022-09-26 10:26 UTC
Labels: Depth / Z, GE emulation

**Comment by antipirgos** [comment] 2026-03-11 23:54
@hrydgard With the Skip Buffer Effect, the game works great, but when I use the power of time, the screen goes black, the same with the appearance of Dahaka when I need to run away from him. That's the only way I can play the game on Huawei Mediaped T3 10 Android 8.0 Oreo. Can you fix that please???
