### ISSUE TITLE
God of War Ghost of Sparta screen flickering in Vulkan

### ISSUE THREAD

**Issue by Deivmsr** [hrydgard/ppsspp#12215] opened 2019-08-04 19:11 UTC
### What happens?
God of War Ghost of Sparta keeps the screen flickering when using Vulkan. This happened more often when my phone upgraded to Android 9.0.

### What *should* happen?
I note that this only happens in God of War Ghost of Sparta. Other games run normal on Vulkan. I believe the right thing would be that this game could run without this problem.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I using Galaxy Note 8, Exynos processor, Android 9.0, Mali G71 GPU.

EDIT: Video and repro dump https://github.com/hrydgard/ppsspp/issues/12215#issuecomment-518707474

**Comment by marosis** [comment] 2019-08-05 04:11
Picture?

**Comment by Deivmsr** [comment] 2019-08-05 04:24
Screen capture does not catch the moment when the graphics flash. I also tried to record a video from the phone itself but it does not show the problem. Let's say areas like the walls of the game scene, for example, keep flashing all the time and even as Kratos moves. I do not know how to best record this problem. The good thing would be that someone like hydgard could test on an exynos processor phone and Mali G71 GPU, like the S8, to see if that would reproduce this problem of which I describe.

**Comment by marosis** [comment] 2019-08-05 04:48
Frameskipping turned off?

**Comment by Deivmsr** [comment] 2019-08-05 04:49
Yes

**Comment by unknownbrackets** [comment] 2019-08-05 04:51
Are you using any post-shaders?  Does it help to turn them off?

Does the rotation of your device change this flashing?

-[Unknown]

**Comment by marosis** [comment] 2019-08-05 04:59
Try create DUMP FILE

**Comment by Deivmsr** [comment] 2019-08-05 05:07
I am not using post shader. I put to change the screen orientation in automatic mode and it happened that when rotating the phone from portrait mode to landscape the screen went black. But switching to portrait mode did not affect the problem and continued the same thing.

**Comment by Deivmsr** [comment] 2019-08-05 05:19
The problem only happens in buffered rendering mode. In skipping buffer effects the image gets cropped (I know there is a warning that the game only works on buffered rederization).

**Comment by Deivmsr** [comment] 2019-08-05 05:23
![Screenshot_20190805-011912_PPSSPP](https://user-images.githubusercontent.com/40547165/62440741-71a4b680-b71f-11e9-9d35-bdb4bcd8a6fd.jpg)
In portrait mod and in skipping buffer effects.

**Comment by Deivmsr** [comment] 2019-08-05 05:23
³

**Comment by Deivmsr** [comment] 2019-08-05 05:24
Sorry. It was a typo.

**Comment by hrydgard** [comment] 2019-08-05 07:09
This might be related to https://github.com/hrydgard/ppsspp/issues/11937 . I will investigate that one in detail soon.

**Comment by hrydgard** [comment] 2019-08-06 14:26
This indeed seems to be some driver regression? Sigh.

**Comment by Deivmsr** [comment] 2019-08-06 14:35
I'm not sure. Could you test this game on your S8 (is yours exynos?) To see if it happens to you too?

**Comment by hrydgard** [comment] 2019-08-06 14:36
I did, and it flickers on it too.

**Comment by Deivmsr** [comment] 2019-08-06 14:38
Good thing it's not a restricted issue just on my phone.

**Comment by hrydgard** [comment] 2019-08-06 14:58
Very clear repro right here at the beginning:

[gow_glitch_video.zip](https://github.com/hrydgard/ppsspp/files/3472877/gow_glitch_video.zip)

**Comment by Deivmsr** [comment] 2019-08-06 15:00
I test the European version. The same thing happens.

**Comment by hrydgard** [comment] 2019-08-08 11:16
Note to self, this is very likely the game doing multiple renderpasses to the same rendertarget, with no barrier in between (just another tiny renderpass).

Looking at the RenderDoc dump, we could do so much better (and eliminate this) by reordering and merging a few render passes. However, it's probably best to first add code that inserts the appropriate barriers, and only then experiment with such tricks.

**Comment by hrydgard** [comment] 2019-08-08 14:02
This should now be fixed in new builds.

**Closed** 2019-08-08 14:02 UTC
Labels: Mali GPU, Vulkan
