### ISSUE TITLE
OGL backend broken since "Use mapped device memory" on AMD gpu

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10647] opened 2018-02-25 14:29 UTC
Black screen when launching PPSSPP with OGL backend since #10604 no error messages or any hints what happens, no freezes either(can use drop down menu to switch backend just fine), just black color.

 Probably related to #10633

**Comment by LunaMoo** [comment] 2018-02-25 15:49
Black screen doesn't mean issues are related, it could only if in your old config you used OGL backend as this issue has nothing to do with Vulkan, which btw doesn't produce any error messages on exit for me.

**Comment by FlatOutPS2** [comment] 2018-02-25 17:56
Duplicate of https://github.com/hrydgard/ppsspp/issues/10613

**Closed** 2018-02-25 20:34 UTC
Labels: OpenGL
