### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by YatoGami** [hrydgard/ppsspp#7882] opened 2015-07-29 13:05 UTC
when I am using the emulator with the sound enable and I get a notification, like "20% battery remaining" or "time done", the sound stops working on the emulator

**Comment by ppmeis** [comment] 2015-08-10 00:13
@YatoGami please add more info like your device or if your are using Windows or Android...

**Comment by unknownbrackets** [comment] 2015-08-12 23:56
You're probably using iOS because that has exactly this bug and also provides exactly that notification iirc.  Closing as duplicate of #2865.

If it's actually a different device, reply with full details and we'll reopen.

-[Unknown]

**Closed by unknownbrackets** 2015-08-12 23:56 UTC
