### ISSUE TITLE
Raspberry pi running Retropie trying to update from source so i can update my ppsspp 

### ISSUE THREAD

**Issue by Mouzouris** [hrydgard/ppsspp#10448] opened 2017-12-25 20:03 UTC
What happens?
it doesn't allow me to update and it tells me that it couldn't locate the PPSSPPSDL not found 
i'm not sure if it's my fault or i'm such a newbie to workaround a fix

![win_20171225_21_57_24_pro](https://user-images.githubusercontent.com/33848299/34342647-fe3cd152-e9be-11e7-91b4-beffb90c66ef.jpg)
one more thing that i have found when it was going through the building process it goes all the way to 100 and then when it does
Linking CXX executable PSSPPSDL
it then outputs 
ext/valkan/libvalkan.so: file not recognised:File format not recognised

![screenshot 82](https://user-images.githubusercontent.com/33848299/34342733-f9757d24-e9c1-11e7-8e38-cb160eae95e5.png)

What *should* happen?
should install and tell me that it has been done

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
well i'm on a Raspberry pi 3 model b

**Comment by mrcmunir** [comment] 2017-12-25 20:54
see https://github.com/hrydgard/ppsspp/issues/10433

It's broken with recents changes.

**Comment by unknownbrackets** [comment] 2017-12-25 22:05
Closing this as a duplicate of #10433 then, let's centralize.  The issue is, I think, that the .so is presumably x86_64.  It probably also fails on x86_32, as well as arm32/arm64?

-[Unknown]

**Closed by unknownbrackets** 2017-12-25 22:05 UTC
