### ISSUE TITLE
Analog vertical tests are always wrong

### ISSUE THREAD

**Issue by chevycam94** [hrydgard/ppsspp#9300] opened 2017-02-11 22:32 UTC
No matter how the connected controller is configured, and no matter how the left and right analog sticks are mapped in PPSSPP, the result is always the same.

In the "Test analogs" section, Left/Right work fine for both sticks.  But Up/Down are always wrong.  No matter how the Y axis is mapped, pushing UP will make the test "X" go DOWN, and pressing DOWN will always make it go UP.

Even if both Y+ and Y- are mapped to analog up, pressing up will still make it go down.

Odd thing is, when in a game, when the analog sticks are mapped as they "should be" (Y- = down, Y+ = up), the resulting control is correct.  Up is up, down is down.

BTW, I'm using a PS3 controller and Sixaxis Controller app for Android (on 7.1.1).

**Comment by hrydgard** [comment] 2017-02-15 09:55
Hm, so this is odd, because it works correctly with Xbox 360 controllers on my PC.

Though I seem to recall compensating for this difference elsewhere. I'll take a look.

**Comment by hrydgard** [comment] 2017-02-15 10:03
Right, yes, the testing screen shows raw axis values without taking into account mapping at all. These happen to be backwards on some platforms.

I'm not going to prioritize this very highly but it would be nice if it were as consistent as possible.

**Comment by chevycam94** [comment] 2017-02-15 13:16
No problem.  I spent about 30 minutes trying to map them, and could never get them right.  Finally said screw it and started playing.  Happen to be working.

**Comment by hrydgard** [comment] 2017-02-15 13:55
Oh, I never realized that a use for it would be to confim mappings. My only intention was for stock dead-zone and responsiveness curve testing, after some complaints from confused people.

Should probably simply move it to the development tools section. If you successfully map an analog direction, it will work in-game, so there's no use to keep it there as a testing tool.

**Comment by chevycam94** [comment] 2017-02-15 14:20
The default mailings for the PS3 controller were similar to the Xbox controller.  The left analog and d-pad mappings were swapped.  Analog was the d-pad, d-pad was the analog.

Either way, if you get an update pushed (I always download the newest posted apk), I check it out.  If something new comes up, I'll let you know.

Thanks for all your hard work!

**Comment by hrydgard** [comment] 2017-02-16 00:35
That's good to know that the DPad and stick are swapped - might get around to fix that sooner than the testing screen.

**Comment by hrydgard** [comment] 2017-02-19 13:37
Found the cause I think and committed a fix.

**Comment by Anuskuss** [comment] 2017-02-23 14:35
Still not fixed for DS4 controller.

**Comment by unknownbrackets** [comment] 2017-07-15 23:36
@Anuskuss so to confirm, if you map the controls so that the directions work properly, it still shows the wrong directions in the test tool?

Note that this won't help the defaults - if up is down and down is up by default, you'll need to swap the mappings.  Improving defaults could be a separate issue, but might even be a driver settings problem and not really a bug.

-[Unknown]

**Comment by hrydgard** [comment] 2017-07-16 08:28
No, this is definitely a bug. If I map up and down backwards, it still looks right for me with my X360 controller, which is unexpected.

**Comment by hrydgard** [comment] 2017-09-29 18:53
Turns out this was just a stupid typo :(

**Closed** 2017-09-29 18:53 UTC
