### ISSUE TITLE
[Feature request]  Auto holding keys.

### ISSUE THREAD

**Issue by 1234Sameer** [hrydgard/ppsspp#11034] opened 2018-05-12 07:12 UTC
Please add an option for auto holding keys. I can't find such option in the settings. There is an option for combo key setup but it is not enough in the situations where we have to first hold a trigger key then press another key. For example in GTA games we have to first aim by holding R and then press circle to fire . We can do this manually but we can't move using analog stick at the same time. This option should be useful for touch devices. Please add this feature if it is possible. Currently I am using v1.5.4-988-gd10d57bc0.

**Comment by leopard20** [comment] 2018-05-12 17:32
Duplicate request

**Comment by 1234Sameer** [comment] 2018-05-13 01:58
If it is a duplicate request who is the original author of the same request. And when will this feature be added to ppsspp.

**Comment by LunaMoo** [comment] 2018-05-13 12:04
Dupe of #10159, ignore that the actual request is different as nobody would care to do it as limited as it was requested. Also understand this is a free open source project, so you can't ask when something will be done - nobody can answer that. Maybe someone new will join just to add such tiny, platform specific feature or maybe nobody will ever bother adding it, noone can tell.
Closing.

**Closed by LunaMoo** 2018-05-13 12:04 UTC
