### ISSUE TITLE
How to disable on-screen Buttons diagonals

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9025] opened 2016-09-30 13:50 UTC
How to have a 4-way touch for any on-screen button like D-pad option?(action buttons are very annoying)

**Comment by unknownbrackets** [comment] 2016-10-01 03:47
Can you clarify?  Are you asking for:

 * The ability to create an "onscreen d-pad" where the arrows actually correspond to buttons?  If so why?
 * The ability to prevent two d-pad directions from being pressed at the same time, like up and right?  If so, why?
 * Something else?

This may be a duplicate of #6585.

-[Unknown]

**Comment by Juliex** [comment] 2016-10-02 07:52
No, I mean the ability to prevent press ∆ n O in same time,

Means the:

DisableDpadDiagonals = True

,but this time for action buttons.
maybe you have confused with Windows version...my is Android.

**Closed** 2016-10-26 20:01 UTC
