### ISSUE TITLE
Kill All Gnomes nothing but a blank screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11049] opened 2018-05-19 01:06 UTC
PPSSPP v1.5.4-993-gab65c5210 Windows 64 bit
nothing but a blank screen
http://www.consolespot.net/uploads/downloads_downloads/GNOME.zip

**Comment by unknownbrackets** [comment] 2018-05-19 01:14
Looks like it's caused by:

```
12:22:315 User Mode Th E[FILESYS]: FileSystems/DirectoryFileSys VFSFileSystem failed to open /vsh/etc/version.txt
12:22:315 User Mode Th E[SCEIO]: HLE/sceIo.cpp:1385 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(flash0:/vsh/etc/version.txt, 00000001, 000001b6) - file not found
```

I guess we could expose some files via flash0:.  Since we have a version config setting, I wonder if we would want to dynamically serve this file (a lot more work) or just hardcode 6.60.

-[Unknown]

**Comment by LunaMoo** [comment] 2018-05-19 02:33
That's a duplicate of #9073 as mentioned there that's not worth fixing, it's not even a playable game.

**Comment by leopard20** [comment] 2018-05-19 06:00
What an intriguing game!

**Comment by LunaMoo** [comment] 2019-06-14 20:35
I'll close this following Henrik's decision in the other issue about same thing.
This app is a really awful work-in-progress without really much if any gameplay or graphics if someone really want to run this refer to my post in [here](https://github.com/hrydgard/ppsspp/issues/9073#issuecomment-304797476)

**Closed by LunaMoo** 2019-06-14 20:35 UTC
