### ISSUE TITLE
Grip Shift Not Loading Levels

### ISSUE THREAD

**Issue by Quatopygia** [hrydgard/ppsspp#11871] opened 2019-03-06 23:28 UTC
### What happens?
When I play Grip Shift, the game runs perfectly for about 15-30 seconds. After that, the audio becomes distorted (playing the same short bit of audio on loop), and if I attempt to open a level after that distortion begins to occur, the game freezes. However, the looping audio continues to play.
Screenshot of console log: https://gyazo.com/3cad2013dddaa26718604c579a15c653

### What *should* happen?
The audio should not become distorted, and all levels should load normally.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
nVidia GeForce GTX 1070 (GPU), Intel i7 4790k (CPU), Windows 10 Home 64-bit (latest version), PPSSPP version 1.7.4

**Comment by unknownbrackets** [comment] 2019-03-07 05:38
Is this a duplicate of #7601?

-[Unknown]

**Comment by benderscruffy** [comment] 2019-03-14 11:49
yep duplicate of #7601

**Closed** 2019-03-14 12:04 UTC
