### ISSUE TITLE
Dante's Inferno text texture issues

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#11076] opened 2018-05-26 18:08 UTC
I am using 1.6 version on windows 10 x64 and noticed graphical issues.

![dante](https://user-images.githubusercontent.com/5770076/40579099-5a4e1e80-6131-11e8-9473-2420a755f4e7.gif)

**Comment by unknownbrackets** [comment] 2018-05-26 18:36
Does this happen even with default settings?  What video card are you using?

-[Unknown]

**Comment by LunaMoo** [comment] 2018-05-26 18:41
Closing as a duplicate of #4845 this game is glitchy from a long time, sometimes it appears fixed to some, but only when it's missing effects, no point opening new issue about same thing every release version.

**Closed by LunaMoo** 2018-05-26 18:41 UTC
