### ISSUE TITLE
Missing Vulkan support on Linux

### ISSUE THREAD

**Issue by davidbepo** [hrydgard/ppsspp#9031] opened 2016-10-03 20:37 UTC
i have an hd 5500 with anv (intel vulkan linux driver) installed and working
![captura de pantalla de 2016-10-03 22-36-35](https://cloud.githubusercontent.com/assets/18667173/19053134/dff01cec-89b9-11e6-9226-57dbc36defc6.png)
 but no vulkan option shows up

**Comment by sergiobenrocha2** [comment] 2016-10-04 01:41
PPA? I need to figure out how to enable vulkan in the build

**Comment by unknownbrackets** [comment] 2016-10-04 05:29
The Linux code (Qt or SDL) is not ready for Vulkan.  It needs to prepare a surface that Vulkan can use - so the problem is in the init code.

Generally all the actual Vulkan rendering code is cross platform, so once the display is set up properly we should be good to go.  Someone just needs to hook it up.

-[Unknown]

**Comment by davidbepo** [comment] 2017-02-19 14:11
qt 5.10 will have vulkan support:
https://phoronix.com/scan.php?page=news_item&px=Qt-5.10-Vulkan-Support

**Comment by davidbepo** [comment] 2017-09-03 21:49
sdl will have vulkan support too:
https://phoronix.com/scan.php?page=news_item&px=Vulkan-Support-In-SDL

**Comment by TotalCaesar659** [comment] 2017-09-24 14:50
SDL 2.0.6 released with Vulkan support
https://discourse.libsdl.org/t/sdl-2-0-6-released/23109

**Comment by hrydgard** [comment] 2017-09-25 07:03
That's good news - probably the best way for us to support this.

**Comment by unknownbrackets** [comment] 2017-12-04 13:30
It looks like even without that, you can do this:
https://gist.github.com/flibitijibibo/715a319fcdf6a78e5a2885146ede37da

Although you have to think about which window manager is being used:
https://github.com/googlesamples/vulkan-basic-samples/blob/master/loader/wsi.h#L30

The new way is this, but means changing more of the loader:
https://github.com/SDL-mirror/SDL/blob/master/test/testvulkan.c

-[Unknown]

**Comment by hrydgard** [comment] 2017-12-04 14:26
Yeah, I'm not sure what's best. I'm probably not gonna have time to dive into that for a while though...

**Comment by hrydgard** [comment] 2017-12-15 16:00
Initial stab for the SDL build: https://github.com/hrydgard/ppsspp/pull/10413

**Closed** 2017-12-21 13:52 UTC
Labels: Platform-specific (Linux/POSIX), Vulkan
