### ISSUE TITLE
Crash after first Launch

### ISSUE THREAD

**Issue by gevin456** [hrydgard/ppsspp#11262] opened 2018-07-23 06:45 UTC
### What happens?
repo Added           - DONE
tweak installed      - DONE
First Launch          - DONE
install a game         - DONE
Play the game       - DONE
exit the app           - DONE
relaunch                - FAILED
freeze the app , and i cannot do anything

### What *should* happen?
after relaunch it should be work perfectly

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

iPhone 6SPLUS
iOS 11.2.6
PPSSPP (dev-Latest)
1.6.3-301-ge51ea8561

Please help guys!!!

**Comment by TehPlayer14** [comment] 2018-07-23 14:51
Does the stable version work?

**Comment by TheEpicPie3** [comment] 2018-07-24 04:48
Neither stable nor dev latest version is working for me either.

**Comment by unknownbrackets** [comment] 2018-07-27 07:02
This issue is being closed as a duplicate of #9186.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-07-27 07:02 UTC
