### ISSUE TITLE
Flatout Head On soundtrack data bug

### ISSUE THREAD

**Issue by NightWolf2014** [hrydgard/ppsspp#15419] opened 2022-02-24 14:40 UTC
### Game or games this happens in

All versions

### What area of the game / PPSSPP

The songs of the game loads for 5-8 seconds and choose another song, but doesn't play the song for complete.

### What should happen

The song should be played from the begin to the end.

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy Tab E and Moto G7 Plus.

### PPSSPP version affected

All versions.

### Last working version

None.

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by EternalsDarkhole** [comment] 2022-02-24 15:12
Duplicate? of https://github.com/hrydgard/ppsspp/issues/6663

**Comment by quicksilver7837** [comment] 2022-02-24 17:27
Yes unfortunately this has been a long time issue. I have been setting the in game music volume to 0 as a work around.

**Comment by NightWolf2014** [comment] 2022-02-25 13:37
But i don't want to play the game without soundtrack, its boring.
Em 24/02/2022 15:27, "quicksilver7837" ***@***.***> escreveu:

**Comment by unknownbrackets** [comment] 2022-02-27 01:21
This issue is being closed as a duplicate of #6663.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-02-27 01:21 UTC

**Comment by NightWolf2014** [comment] 2022-02-27 19:52
Sorry for the duplicate, i don't through someone already reported the same
inssue years ago.

Em Sáb, 26 de fev de 2022 23:21, Unknown W. Brackets <
***@***.***> escreveu:
