### ISSUE TITLE
[Feature Request] Option to cache textures to RAM

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#12332] opened 2019-09-17 13:00 UTC
I'm guessing there's no way to cache textures we want to replace to RAM? Games are lagging when the textures are being loaded. Or maybe there's a way to cache them but you gotta change something in the ini?

**Comment by AkiraJkr** [comment] 2019-09-17 13:14
I second this. It would be really useful specially for the larger texture packs, I'm sure it'll be fine, I doubt someone can make something that can surpass 1 GB...right?

**Comment by GamerzHell9137** [comment] 2019-09-17 13:18
@AkiraJkr Depends on the type of the game. Patapon Remaster is x8 times the native resolution (4K textures?) and it weighs around 300 MB but so i guess if someone done an RPG and really upped the textures then it could be done? (Tho i doubt someone would do that but you never know)

**Comment by unknownbrackets** [comment] 2019-09-18 00:53
I'm not sure, but the most expensive part might be the PNG decoding (filters + zlib) or even more likely texture upload.  You're talking about the PNG compressed sizes, and that might not really save a lot of time.

Decompressed images would be at least 2x up to 10x the size.  Formula: `# of images` * `average width` * `average height` * 4 bytes.  So 500 images of 128x128 textures at 8x would be about 2GB (but the PNGs would be much smaller.)  That much VRAM is probably acceptable, at least outside mobile.

You could verify if saving just the PNG data in RAM would help: open up a game with replacements, and reproduce the loading delays and problems.  Now exit PPSSPP completely, and restart it.  After that, play the game again and see if you still experience them.

Your OS file cache will prevent the problem the second time if a PPSSPP PNG cache would.  If it still happens, then we'd need to cache them decompressed (possibly in VRAM if texture upload is the slow part.)

-[Unknown]

**Comment by GamerzHell9137** [comment] 2019-09-19 13:59
@unknownbrackets Tried it, the hitches still occur.

**Comment by unknownbrackets** [comment] 2019-09-20 04:08
Right, so then we definitely don't want to just cache the PNGs in RAM, won't help.  Might need to preload (perhaps in a background thread on Vulkan?) the textures into VRAM.

Best case for that might be load groups or some way to indicate priority.  If it hitches on upload for one, just imagine if PPSSPP was just spinning while it loaded every possible texture.  Some form of prioritization should make background loading viable.

-[Unknown]

**Comment by hardBSDk** [comment] 2019-09-26 22:07
What about Intel HD/UHD Graphics or AMD APUs?

Both of them (Radeon and Vega I'm not sure) share the OS memory to upload textures, then don't have dedicated video memory chip on his chip (not board because sits inside de processor).

as the driver allocates some RAM for the GPU, while traditional GPUs have dedicated VRAM on his board, there's any optimization for Dedicated GPUs in this case?

**Comment by unknownbrackets** [comment] 2019-09-27 00:03
In practice, for most GPUs the texture data must be reorganized in some way for speedier access when rendering.  So, when I'm talking about upload to VRAM - I mean this too, not just the memory transfer itself.

-[Unknown]

**Comment by hardBSDk** [comment] 2019-10-04 01:06
@unknownbrackets Thanks! Love your work plus @hrydgard

**Comment by superostrich** [comment] 2020-02-22 19:31
Would https://github.com/hrydgard/ppsspp/issues/12059 be a potential solve for the stuttering caused by texture loads?

**Comment by LunaMoo** [comment] 2020-02-22 21:33
Huge improvement over PNG's for sure, whenever it would be a "solution" it could still depend on other factors like how many and how big textures would have to load at once and or even what people care about as it's a lossy format.

 To fully solve something like that would be to pre-cache textures in vram, maybe even with an textures.ini option to set which textures should be pre-cached and which doesn't need to be.

**Comment by superostrich** [comment] 2020-03-04 20:23
An option to pre-cache in the INI file would be nice.   For example keeping all font textures cached would help with stuttering.

**Comment by unknownbrackets** [comment] 2021-05-24 05:53
With #14467 merged, there's an option to improve loading speed over PNGs.  This will help confirm if the load delay times are caused by PNG decoding or not (based on some profiling, I expect it to be the case, but I didn't reproduce hitching.)

To be clear, this new option (ZIM) is likely not as fast as Basis would be, and does not perform any preloading.  However, if using ZIM reduces hitching, that will provide strong indications as to how we could preload and how much alternative formats such as basis could help.

To create ZIM files, you'll need zimtool, which currently has to be built from PPSSPP.  If you are on Windows, just compile the Visual Studio solution - it will create ext\native\tools\build\zimtool.exe.  You can then experiment with creating ZIM texture replacements.

How to use:

1. You must explicitly set the filename in a texture ini to "foo.zim" or else name the file "foo.png" (actual content will be autodetected, even if the extension is incorrectly ".png".)
2. Run zimtool using a command prompt with arguments like:
   ```cmd
   zimtool image.png image.zim -f=8888 -z1
   ```
3. You can remove the `-z1` parameter to create an uncompressed ZIM.  The filesize will be about the size it requires in RAM/VRAM.  Alternatively, you can adjust the number to compress more strongly - any number between 1 and 22 is supported.  See #14467 for a limited benchmark (one image) of how this affects decode speed.
4. You may want to convert to zims in a new folder using a batch file, and then swap out the folders.
5. Note that the disk size will influence how much is cached by your OS.  So there are tradeoffs to the compression beyond read speed alone - more compressed textures can fit in the cache at the same time.

If anyone seeing hitching would be willing to try this out and report back on how it impacts hitching, it would be helpful.  I see a few possible outcomes (maybe others too):
1. It solves hitching, indicating that the cause was almost entirely PNG.  Complexities of preloading may not be needed, even if we ultimately use a better format than ZIM.
2. It doesn't solve hitching, but it improves it to a very notable degree.  This would suggest that preloading and decoding the images to RAM only would likely be sufficient to reduce stutter, or potentially using a better (faster to decode or less total bytes) format.
3. It doesn't solve hitching, only slightly improving the problem.  This would suggest the problem may be elsewhere, and preloading might need to load all the way into VRAM to improve things, or we may even be dealing with memory contention.
4. It makes it worse.  This would indicate the problem is IO, and preloading from disk might help (without predecoding.)

-[Unknown]

**Comment by LunaMoo** [comment] 2021-06-06 07:39
I created a somewhat stuttery x4 texture pack for testing and tested it in both standard SSD and from a RAM disk(which didn't really differ in noticeable way), I did not measured timings in any way, but from observation the conclusion is ZIMS does help reducing the stutter to at least 1/3(easily noticeable also on savestate load into a scene full of replaced textures which takes ages to load).
 This was enough to completely solve stutter in many cases when loading just 1-2 new textures, however the stutter was still very noticeable whenever switching to a model that had more new textures to load at once. (I used a Macross game and switched between various textured 3D models for testing.)

 Guess a faster format like BASIS could still help a ton, not sure if could completely solve the problem through.

 On a side note ZIM's aren't fully functional right now. That is they have to be defined in textures.ini for replacement to work, PNG's also work by just keeping the original filenames and storing it in the right folder.

**Comment by unknownbrackets** [comment] 2021-06-06 08:02
Well, ZIMs are partly just for testing or simpler use cases (they are closer to uncompressed textures.)  That said, if you name the file ".png" but it's actually a ZIM, it will work.  In that way, you don't need to specify in the ini.

These are interesting results.  A 30% improvement is a good improvement, but definitely means there's more to this.  If that was also from a ramdisk, that implies preloading to RAM likely won't be sufficient.

-[Unknown]

**Comment by LunaMoo** [comment] 2021-06-06 08:12
By saying the stutter was it's 1/3 of what it was with PNG's I ment it's more around x3 improvement. :) This is just an observation not a measure through. Not sure how to measure that properly, it was significant enough to completely solve many stutters, just not all.

**Comment by LunaMoo** [comment] 2021-06-06 15:32
Made a video for reference:
https://www.youtube.com/watch?v=nF226u3mbWs

Two clips combined first one with ZIM, then PNG, loading savestate during a logo fadeout animation to mark when the load starts, then going through player setup changing mechs/vehicles as each of them loads from 1 to multiply new textures easily reproducing the issue and also showing how much better ZIM's are. My observation seemed decently accurate as the savestate load does go from 1s with ZIM's to 3s with PNG's. The rest is harder to measure, but very easy to hear with sound popping and stopping all the time with PNG, rarely with ZIM.

**Comment by unknownbrackets** [comment] 2021-06-12 04:05
I wonder if a strategy might be to decode all PNGs into RAM (we could even do this on many worker threads on powerful systems), but then compress than at a very fast and low level using zstd.  This might maximize the number of textures we can load into RAM with a small impact on performance.

Preload order won't be perfect, but if we're constantly loading on say 4 threads, it might go pretty quickly.  We could potentially even do something like the shader cache, to track the most important textures to preload for save states to load quickly.

Biggest problems to consider with that would be: making sure we don't starve threads doing other operations and likely tracking available RAM so we know a reasonable limit of textures to decode into RAM.

It sounds like simply loading into RAM will be a big help for performance and going further to decode into VRAM might just trap us in a tighter space without significant performance advantages.

That said, perhaps ZIM/Basis would give us enough improvement not to need this.  Given that there's still minor hitching, it'd be nice to still have the preload option....

-[Unknown]

**Comment by IrfanH495** [comment] 2021-07-31 22:07
where can i get zim files on android

**Comment by oabdellatif** [comment] 2023-02-02 05:45
Thanks for the detailed instructions @unknownbrackets, for my usage this eliminates all visible stuttering in Persona 3 Portable when using TridentOfTheAbyss' HD texture pack from [here](https://forums.ppsspp.org/showthread.php?tid=26547). This is with the 3x version on a handheld device with pretty modest hardware, though the size does almost double from 848 MB to 1.40 GB uncompressed. I should note I'm also taking advantage of the ZIP support you implemented, which I believe also helps quite a bit.

**Comment by hrydgard** [comment] 2023-03-18 20:25
I think the need for this has been greatly diminished now, especially now that we support UASTC through ktx, with with a quarter of the memory usage don't require compression in RAM, and still look really good and [load as fast as zim](https://github.com/hrydgard/ppsspp/issues/12059#issuecomment-1474975884).

See the new documentation on https://www.ppsspp.org/docs/reference/texture-replacement , specifically the section on supported image formats.

**Closed by hrydgard** 2023-03-18 20:25 UTC
Labels: Feature Request
