### ISSUE TITLE
Phantasy Star Portable 2 Infinity

### ISSUE THREAD

**Issue by Morrow457** [hrydgard/ppsspp#12212] opened 2019-08-02 13:25 UTC
What happens?
I just updated ppsspp to the latest version and when I played Phantasy Star Portable 2 Infinity, this happens:
![Screenshot_20190802_201946](https://user-images.githubusercontent.com/53612708/62370587-23e44e80-b565-11e9-857c-39062bbdf2c6.jpg)
This is suppose to be the message when the save data is loaded. The japanese letters are missing.
![Screenshot_20190802_202705](https://user-images.githubusercontent.com/53612708/62370495-df58b300-b564-11e9-88d6-0ff0aa3dc600.jpg)
After that, there is black screen and the save data won't appear.
Black screen also happens when I started a new game and go to character creation menu.

What *should* happen?
The japanese characters should be there and the save data should appear. And when I started a new game, the character creation menu should appear.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Hardware and OS are in these screenie:
![Screenshot_20190802_201828](https://user-images.githubusercontent.com/53612708/62370879-ef24c700-b565-11e9-97b0-7c456ed7ca7b.jpg)
![Screenshot_20190802_201843](https://user-images.githubusercontent.com/53612708/62370885-f51aa800-b565-11e9-856e-f59781a0425a.jpg)
Info about the ppsspp version, it's 1.8.0 that has the issue, and 1.7.5-455-g9e8341cf8 is the old version that I used and it worked before I updated it.

**Comment by Morrow457** [comment] 2019-08-02 14:18
While I was looking at the old builds, I've found out that it was v1.7.5-488-g13c85b127 that started to stopped working on this game...

**Comment by unknownbrackets** [comment] 2019-08-03 17:26
Right, this is actually a known issue.  13c85b127 extended the problem in #8492 to more games.  Unfortunately, it's dependent on graphics card / drivers.

Closing as a duplicate of #8492.

-[Unknown]

**Closed by unknownbrackets** 2019-08-03 17:26 UTC
