### ISSUE TITLE
Resistance - Retribution crashing

### ISSUE THREAD

**Issue by techsmo** [hrydgard/ppsspp#14498] opened 2021-06-03 07:41 UTC
### What happens?
so the game had a few issues here and there where i could work around with, but then area 5 happend at one point i get blue screened with this 
![afbeelding](https://user-images.githubusercontent.com/85279035/120604495-691d8400-c44d-11eb-864d-6ec7579900b3.png)

### What *should* happen?
it shouldnt crash

### What are you using?
1.11.3 

#### What hardware / device and operating system?
windows 10 pc

#### What graphics card (GPU) or mobile phone model?
RTX 2070

#### What PPSSPP version (standalone/official), and did it work before?
i dont know, this is the first time i'm using this emulator

#### Which game or games?
Resistance: Retribution (UCUA98668) USA

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [x] Include logs or screenshots of issue.

**Comment by Panderner** [comment] 2021-06-03 08:47
Maybe Duplicate of #4626 I guess?

**Comment by LunaMoo** [comment] 2021-06-03 10:48
Closing as a duplicate of the issue mentioned above.

**Closed by LunaMoo** 2021-06-03 10:48 UTC
