### ISSUE TITLE
Resistance:retribution glitch

### ISSUE THREAD

**Issue by abdellahking** [hrydgard/ppsspp#10665] opened 2018-03-01 12:22 UTC
I just played resistance:retribution on the last update on buildbot and whene i go  to the first boss its just Disappears and the fps drop to 8fps

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
I use opengl 3.1 mali t720 with 3GB ram and 1.3Ghz quad Processor and gpu vendor is ARMv8l 
And if youneed anything just ask

**Comment by hrydgard** [comment] 2018-03-01 13:07
Did this work in older versions of PPSSPP?

**Comment by abdellahking** [comment] 2018-03-01 15:24
No. This (bug) wos on every version of ppsspp on my device.

**Comment by abdellahking** [comment] 2018-03-01 16:42
Here some screenshot

1:https://drive.google.com/file/d/1C8R7mSTc_jHLa38Rt0iS-BiuXDHB4FLH/view?usp=drivesdk

2:https://drive.google.com/file/d/1C8R7mSTc_jHLa38Rt0iS-BiuXDHB4FLH/view?usp=drivesdk

**Comment by hrydgard** [comment] 2018-03-01 20:18
Both links go to the same picture, just so you know.

**Comment by abdellahking** [comment] 2018-03-01 20:53
Sorry its mistake here is:

2:https://drive.google.com/file/d/1MKImPRQfGz0Z2e-NfUmvKYgmwHl9w62M/view?usp=drivesdk

**Comment by LunaMoo** [comment] 2018-03-01 22:05
That game(and some other using same engine) is definitely not playable, it suffers from not-soo-random crashes and other issues most likely related to bad timing as messing with cpu clock can allow passing some(not all, and emulation has to be restarted / mission replayed for cpu clock setting to do anything) of the problems, through it can also cause different ones, if I recall that boss disappearing happens far more often with forced cpu clock, but either way can disappear if the fight takes too long.

 Closing as a duplicate of #4626

**Closed by LunaMoo** 2018-03-01 22:05 UTC
