### ISSUE TITLE
Flat Out head On

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10100] opened 2017-11-12 18:31 UTC
big problem in Flat Out Head On with music! Music is automatically skipped after the information reel has disappeared. Pls can it be fixed?

**Comment by hrydgard** [comment] 2017-11-12 18:34
Known (and unsolved) issue, dupe of #6663

**Closed by hrydgard** 2017-11-12 18:34 UTC

**Comment by marosis** [comment] 2017-11-12 18:47
Ok thank you:)
