### ISSUE TITLE
Valkyria Chronicles 3 graphics glitch android

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#14105] opened 2021-02-10 12:38 UTC
### What happens?
Only vulkan
OpenGL fine, but if I play long time it gets hot and fps drop,
because my device is snapdragon 820
please fix it for Vulkan

Opengl
https://drive.google.com/file/d/10iRTBEf0kwmb-GVRICmiydCDRcPpo9Mp/view?usp=drivesdk
Vulkan
https://drive.google.com/file/d/10iRTBEf0kwmb-GVRICmiydCDRcPpo9Mp/view?usp=drivesdk
### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Sharp SH-04H
Snapdragon 820
Adreno 530

**Comment by Panderner** [comment] 2021-02-10 12:42
unfortunately duplicate of #13462

**Closed** 2021-02-10 13:08 UTC
