### ISSUE TITLE
[Feature Request]Mouse controls cannot be mapped to analog controls in macOS

### ISSUE THREAD

**Issue by navneetrajoriya** [hrydgard/ppsspp#12610] opened 2020-02-03 14:14 UTC
Mouse controls cannot be mapped to analog controls in ppsspp. There is no such option for MacOS.

**Comment by iota97** [comment] 2020-02-03 16:53
This is duplicate of #4650

**Comment by LunaMoo** [comment] 2020-02-03 22:21
Yeah, one generic issue about it is enough, closing as a duplicate od the mentioned issue. 
It was made only for windows so far and this might not change until some Linux/MacOS user/dev implements it and opens a Pull Request with his code, soo far there were no takers.

**Closed by LunaMoo** 2020-02-03 22:21 UTC

**Comment by navneetrajoriya** [comment] 2020-02-04 07:14
Can I take this issue for MacOS? I'll try and once done I'll create a Pull Request and it could be reviewed.

**Comment by hrydgard** [comment] 2020-02-04 08:39
@navneetrajoriya Sure!
