### ISSUE TITLE
Coded Arms Graphic bugs

### ISSUE THREAD

**Issue by Zetchzie** [hrydgard/ppsspp#8622] opened 2016-03-03 20:40 UTC
Im using the very latest GIT PPSSPP x64, Windows 10 x64, Intel HD Graphics, Intel Pentium 2020M, OpenGL backend

![ulus10019_00000](https://cloud.githubusercontent.com/assets/15071652/13508633/d379b8e0-e155-11e5-89f0-677897a74bf8.jpg)
![ulus10019_00001](https://cloud.githubusercontent.com/assets/15071652/13508634/d37bc41e-e155-11e5-8464-1b6e5860d183.jpg)
![ulus10019_00002](https://cloud.githubusercontent.com/assets/15071652/13508635/d37ddf60-e155-11e5-9353-72393cce0a39.jpg)

**Comment by LunaMoo** [comment] 2016-03-03 23:31
Closing this as duplicate of #4551

 Also if you want to play this game now, just change spline/bezier curves quality to low and it should display most graphics properly except one side of doors at close range.

**Closed by LunaMoo** 2016-03-03 23:31 UTC

**Comment by Zetchzie** [comment] 2016-03-04 00:58
ok what dies that setting do anyways?

**Comment by LunaMoo** [comment] 2016-03-04 03:45
It just allows to change it to less accurate, lighter version of the code since spline/bezier curves have to be emulated on hardware ppsspp runs on and that can get very heavy in some games that abused it.
 Setting it to low is usually bad as it will make round objects using it very blocky to the point of turning circles into squares, however this game uses it for squares to begin with so you really doesn't loose "quality" by doing so.

 You can also additionally try "lower resolutions for effects" hack in graphics settings - this generally aims to fix some effect, mostly bloom around objects which by default when using high rendering res would looks like a ghost copy of the object(ie collectibles in this game). This effect in Coded Arms is pretty ugly either way, but if you get sick having double/triple vision whenever looking at some collectible, then that's always an option to try. Balanced preset for that hack should be fine in most cases, the other two presets are just extra "in case of problems".
