### ISSUE TITLE
Performance issues on Pi 4 after recent update

### ISSUE THREAD

**Issue by SeraphisCain** [hrydgard/ppsspp#13260] opened 2020-08-08 23:22 UTC
Prior to the most recent update, I was able to play Tekken 6, Soulcalibur Broken Destiny, and Ridge Racer 2 at full speed on Pi 4 with no frameskip (Tekken 6 and Ridge Racer 2 had to be non-buffered however, and Tekken 6 experienced some lag in the matchup screen, but gameplay was fine). Now, after a recent update, Tekken 6 constantly runs at 30 FPS instead of 60, Soulcalibur runs at 60 with random drops into 30 (sometimes not recovering back to 60), and Ridge Racer 2 mostly runs like it used to but will drop to 30 at certain sections of track. 

(Since initially typing this post up but prior to submitting, I downgraded PPSSPP to v1.10.2 and the issues are completely gone. It seems something changed between 1.10.2 and now that's causing these performance issues.)

**Comment by hrydgard** [comment] 2020-08-09 00:55
It would be extremely useful if you could try some builds in between, to try to pinpoint which commit slowed it down for you.

**Comment by SeraphisCain** [comment] 2020-08-09 01:58
I don't actually know how to downgrade to non-versioned builds. I can downgrade/upgrade to 1.10.3/1.10.2/1.10.0 etc. by putting the version number in the PPSSPP scriptmodule and having RetroPie Setup build it from source (and I only learned how to do that today, while trying to fix this issue), but for other builds, putting the hash in the scriptmodule doesn't work. So I'm not really sure how to test those builds.

**Comment by hrydgard** [comment] 2020-08-09 07:50
can you point me to the script you're using? I'm sure this is possible. Maybe @twinaphex can help.

**Comment by SeraphisCain** [comment] 2020-08-09 14:09
This is the scriptmodule:

https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/ppsspp.sh

Adding `v1.10.2` to the line `gitPullOrClone "$md_build/$md_id" https://github.com/hrydgard/ppsspp.git` and then updating from source in RetroPie-Setup allowed me to downgrade PPSSPP. However when I tried adding the hash from a non-versioned commit, it didn't work.

**Comment by hrydgard** [comment] 2020-08-09 14:52
That is quite weird, seems to me that it should work. Did you try full or truncated hash?

**Comment by hrydgard** [comment] 2020-08-09 14:53
Also note, if you're trying to clone v1.10.3-332-gf23a367c2 , you should use f23a367c2.  The 'g' is not included!

**Comment by SeraphisCain** [comment] 2020-08-09 15:28
I tried both the truncated and full hashes. Both give me a "returned 128" error. 

Here's the contents of the log:

`git clone --recursive --depth 1 --branch 70802e61d "https://github.com/hrydgard/ppsspp.git" "/home/pi/RetroPie-Setup/tmp/build/ppsspp/ppsspp"

Cloning into '/home/pi/RetroPie-Setup/tmp/build/ppsspp/ppsspp'...

warning: Could not find remote branch 70802e61d to clone.

fatal: Remote branch 70802e61d not found in upstream origin

fatal: cannot change to '/home/pi/RetroPie-Setup/tmp/build/ppsspp/ppsspp': No such file or directory

fatal: cannot change to '/home/pi/RetroPie-Setup/tmp/build/ppsspp/ppsspp': No such file or directory

HEAD is now in branch '' at commit ''

/home/pi/RetroPie-Setup/scriptmodules/emulators/ppsspp.sh: line 29: cd: ppsspp: No such file or directory

sed: can't read ffmpeg/linux_arm.sh: No such file or directory

sed: can't read cmake/Toolchains/raspberry.armv7.cmake: No such file or directory

sed: can't read cmake/Toolchains/raspberry.armv7.cmake: No such file or directory

sed: can't read cmake/Toolchains/raspberry.armv7.cmake: No such file or directory

sed: can't read cmake/Toolchains/raspberry.armv?.cmake: No such file or directory

/home/pi

Error running 'git clone --recursive --depth 1 --branch 70802e61d https://github.com/hrydgard/ppsspp.git /home/pi/RetroPie-Setup/tmp/build/ppsspp/ppsspp' - returned 128`

**Comment by iota97** [comment] 2020-08-09 15:52
Could you try to change line 30 to `git checkout <hash>` like this:

```
function sources_ppsspp() {
    gitPullOrClone "$md_build/$md_id" https://github.com/hrydgard/ppsspp.git
    cd "$md_id"
    git checkout 70802e61de670fc66de23356a6ffab9b4b018d9b
    # remove the lines that trigger the ffmpeg build script functions - we will just use the variables from it
```

If it work check the commit list [here](https://github.com/hrydgard/ppsspp/commits/master) (hash are on the right) and test commit half way in between a working and a broken one:

Let's say this is the list of commit:

```
A [not working]
B [?]
...
C [?]
...
D [?]
E [working]
```

If C work fine the problem is between A and B, if is broken the problem it's between C and D, basically every step you half the range of commit until you find the commit that caused the problem (this is way faster than checking every single one, if you have 1000 commit you would need about 10 step this way).

**Comment by SeraphisCain** [comment] 2020-08-09 16:40
That didn't work either. Tried to go to commit `2af805dbc2edf9725ebe517ba91bb9b49fc27c38`, but it just put me on the most recent commit. Seems to have ignored the `git checkout` line completely.

**Comment by hrydgard** [comment] 2020-08-17 13:36
So, I've got a raspberry pi 4 on the way.

Can you guide me how to reproduce this problem @SeraphisCain ? Like, exactly which distro to install, and so on and so forth. As complete as possible would be best :)

**Comment by SeraphisCain** [comment] 2020-08-17 19:50
The only thing I did was update PPSSPP to the most recent precompiled binary via RetroPie-Setup (standalone PPSSPP, not lr-PPSSPP). I'm also on the most recent Pi firmware, although I'm not sure if that's relevant to this problem. That should be all the relevant steps needed to reproduce.

**Comment by SeraphisCain** [comment] 2020-09-11 02:42
@hrydgard Any update on this? I tried out the most recent commit as of a few days ago and the problem was still present. Went back down to 1.10.3 afterwards and again, everything worked fine.

**Comment by gouchi** [comment] 2024-06-02 18:33
@SeraphisCain Is it still an issue using latest update ?

Thank you.

**Comment by hrydgard** [comment] 2024-06-02 20:33
I'm gonna close this as outdated. Please create a new issue if you have new similar issues.

**Closed by hrydgard** 2024-06-02 20:33 UTC
Labels: No Feedback / Outdated?, Libretro
