### ISSUE TITLE
Graphics Issues PPSSPP iOS 0v1.1.1-934-gbc1ed6e (Dev-Working)

### ISSUE THREAD

**Issue by BlahSay** [hrydgard/ppsspp#8584] opened 2016-02-13 09:21 UTC
Whenever I attempt to play Thrillville: Off The Rails, the start of the game flashes the text very fast and when shown the start screen, all of the graphics are gone it's either black or blue behind the menu options. By the way, I downloaded an older version and this issue was partially fixed. When running the outdated version (Which is now deleted and I have updated) I at least saw the player figures but they seemed to look like spilled paint and were smeared all over the screen and some parts were plain light blue. Please fix this problem, I was looking forward to playing this. And thanks for all the hard work, even if it can't be fixed!

**Comment by hrydgard** [comment] 2016-02-13 18:47
Duplicate of #7459  (which we really should get around to looking at some day...)

**Closed by hrydgard** 2016-02-13 18:47 UTC
