### ISSUE TITLE
Crashing when lauching games

### ISSUE THREAD

**Issue by cksbisqui** [hrydgard/ppsspp#8121] opened 2015-10-29 23:54 UTC
The app is running fine but it is not playing any games. It always crashes when starting any games.

**Comment by unknownbrackets** [comment] 2015-10-30 03:02
This sounds like you're using iOS.  You should search, especially when upgrading your OS makes apps start crashing.  Closing as a duplicate of #8122.

-[Unknown]

**Closed by unknownbrackets** 2015-10-30 03:02 UTC
