### ISSUE TITLE
Silverfall opening video flickering

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6707] opened 2014-08-11 06:07 UTC
The opening video only works with FuncReplacements on,otherwise the video would not be displayed and Gedebugger deos not work on the video.

(rename jpg to mp4)
![01-muxed_0](https://cloud.githubusercontent.com/assets/3481559/3872503/43af2f5a-211d-11e4-8bd5-03562c4775d3.jpg)

**Comment by unknownbrackets** [comment] 2015-02-23 06:59
In Core/HLE/ReplaceTables.cpp, try changing:

```c++
static int Replace_memcpy() {
	u32 destPtr = PARAM(0);
	u32 srcPtr = PARAM(1);
	u32 bytes = PARAM(2);
```

To:

```c++
static int Replace_memcpy() {
	u32 destPtr = PARAM(0);
	u32 srcPtr = PARAM(1);
	u32 bytes = PARAM(2);

	if (Memory::IsVRAMAddress(destPtr) || Memory::IsVRAMAddress(srcPtr)) {
		NOTICE_LOG(HLE, "memcpy(%08x, %08x, %x)", destPtr, srcPtr, bytes);
	}
```

Then we can look at what the memcpy size if.  If that doesn't log anything, just take off the `if (Memory...)` part, and always log... though that might be a lot of unrelated logging.

Anyway, this + the "Creating FBO" etc. lines will tell us if it's trying to copy both frames at the same time or something.

-[Unknown]

**Comment by daniel229** [comment] 2015-02-23 07:09
log these during the video.That flickering is randomly happen.
```
07:13:126 videoThread  N[HLE]: HLE\ReplaceTables.cpp:111 memcpy(04090000, 04154000, 88000)
07:13:143 videoThread  N[HLE]: HLE\ReplaceTables.cpp:111 memcpy(04000000, 04154000, 88000)
07:13:160 videoThread  N[HLE]: HLE\ReplaceTables.cpp:111 memcpy(04090000, 04154000, 88000)
07:13:176 videoThread  N[HLE]: HLE\ReplaceTables.cpp:111 memcpy(04000000, 04154000, 88000)
07:13:193 videoThread  N[HLE]: HLE\ReplaceTables.cpp:111 memcpy(04090000, 04154000, 88000)
07:13:210 videoThread  N[HLE]: HLE\ReplaceTables.cpp:111 memcpy(04000000, 04154000, 88000)
``

**Comment by benderscruffy** [comment] 2019-03-14 12:08
still happens
![silverfall](https://user-images.githubusercontent.com/2696404/54355729-d1c58e00-4694-11e9-958e-7df51e51bb61.PNG)

**Comment by Gamemulatorer** [comment] 2022-04-17 08:00
I cannot reproduce this.

https://user-images.githubusercontent.com/37603562/163705936-725b1d2c-7885-4cdf-86fa-f929fcaab774.mp4

**Comment by hrydgard** [comment] 2022-04-17 09:01
Guess it got fixed somehow, closing. Please re-open if it occurs again.

**Closed by hrydgard** 2022-04-17 09:01 UTC
