### ISSUE TITLE
Juiced Eliminator (JPN) freeze

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7744] opened 2015-05-15 01:05 UTC
Since https://github.com/hrydgard/ppsspp/pull/5369

debuglog(rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/7645029/463d9268-fae1-11e4-9006-58e2afa1a03a.jpg)

jpcsptrace of savedata
https://gist.github.com/daniel229/2e4e7400226856f9c8e2

**Comment by daniel229** [comment] 2015-05-17 04:06
Changing CPU clock to 53 or smaller also helps it.

**Comment by unknownbrackets** [comment] 2015-11-02 06:22
A JpcspTrace including sceUtilityMsgDialogGetStatus would be helpful.

It seems the first call to sceUtilitySavedataGetStatus should return 2, not 1.

08:49:30.991542 init start
08:49:31.222627 get status

The delta here is about 0.2 seconds.  That sounds about right - we change the status after 200000us, which is 0.2 seconds.  Likely, things aren't consuming as much time as they should.  It's hard to tell if this wrong return value is the problem or not.

Does reducing SAVEDATA_INIT_DELAY_US to e.g. `SAVEDATA_INIT_DELAY_US = 100;` change things?  If so, that indicates something it is doing after (or including) calling InitStart is not consuming enough cycles.  If it doesn't help, the problem is likely something else.

-[Unknown]

**Comment by daniel229** [comment] 2015-11-02 08:04
new log
https://gist.github.com/daniel229/491ec7bc14cee21e58ae
 reducing SAVEDATA_INIT_DELAY_US to 100 not help it.

**Comment by unknownbrackets** [comment] 2015-11-02 15:52
Hmm, I think you named them both save so it's a bit hard to read, heh, but I think I got it.

Should be returning 0x801103C7, seems like.  Hmm.

-[Unknown]

**Comment by daniel229** [comment] 2015-12-27 01:36
Copy paste error,sorry

**Comment by unknownbrackets** [comment] 2016-05-28 21:40
Does it still never call `sceUtilitySavedataUpdate` even with the lower delay?

-[Unknown]

**Comment by daniel229** [comment] 2016-05-28 23:35
No,it doesn't.

**Comment by benderscruffy** [comment] 2019-03-15 11:22
v1.8.0-2-g7f1e10a93
still happens
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2970749/ppsspplog.zip)

**Comment by hrydgard** [comment] 2022-07-24 19:14
Still happens?

**Comment by unknownbrackets** [comment] 2022-07-24 19:16
Relatively decent chance that the volatile stuff might've helped this, yeah...

-[Unknown]

**Comment by sum2012** [comment] 2022-09-04 09:28
I forget how to reproduce it.
Close it ?

**Closed** 2022-09-04 11:07 UTC
Labels: Saving issue, No Feedback / Outdated?
