### ISSUE TITLE
Phantasy Star Portable 2/Infinity Direct3D 11 Black Screen Issue

### ISSUE THREAD

**Issue by Peduls** [hrydgard/ppsspp#13641] opened 2020-11-09 05:00 UTC
### What happens?
Attempting to play either Phantasy Star Portable 2 or Phantasy Star Portable 2 Infinity shows a black screen. Opening video plays fine but after the intro it's just a black screen. First build to have this issue was v1.10.3-1080-g45218ec73

### What *should* happen?
Game should be visible after opening video. Last working build was v1.10.3-1055-gee11f6af7

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Operating System
	Windows 10 Enterprise 64-bit
CPU
	Intel Core i7 7700 @ 3.60GHz
	Kaby Lake 14nm Technology
RAM
	32.0GB
Motherboard
	Micro-Star International Co. Ltd. Z390-A PRO (MS-7B98) (U3E1)
Graphics
	VG248 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	2794GB TOSHIBA HDWD130 (SATA )
Optical Drives
	ASUS DRW-24B1ST j
Audio
	Realtek High Definition Audio

**Comment by thedax** [comment] 2020-11-09 10:56
Does the issue persist in D3D9, OpenGL, or Vulkan as well? I can't reproduce this with OpenGL or Vulkan on Linux.

**Comment by sum2012** [comment] 2020-11-09 14:45
I test on windows 7 no problem

**Comment by sum2012** [comment] 2020-11-09 14:50
I confirm Direct3D 11 Black Screen Issue since   v1.10.3-1080-g45218ec73

48:14:680 idle0        E[G3D]: d3d11\d3d11util.cpp:32 errors: E:\ppsspp\ppsspp-v1.10.3-1176-g5668ad9e0-windows-amd64\ppsspp\Shader@0x000000000FF0BCB0(57,19-30): error X3004: undeclared identifier 'gl_FragCoord'

v1.10.3-1176-g5668ad9e0 full log: https://gist.github.com/sum2012/d3090c2eeeb995e608c55d6b6b71a5db

**Comment by hrydgard** [comment] 2020-11-09 14:54
thanks, that should be an easy fix.

**Comment by hrydgard** [comment] 2020-11-09 15:06
Should be fixed now, let me know if there are any more issues.

**Closed** 2020-11-09 15:06 UTC
Labels: D3D11

**Comment by sum2012** [comment] 2020-11-09 22:48
I test v1.10.3-1186-g9f33a82b4-windows-amd64 in directx 11 no problem now
