### ISSUE TITLE
Graphical bugs in Colin McRae Rally 2005

### ISSUE THREAD

**Issue by enomat** [hrydgard/ppsspp#7810] opened 2015-06-13 16:59 UTC
The sky doesn't appear when the weather is rainy.

![screenshot_2015-06-13-18-46-29](https://cloud.githubusercontent.com/assets/12612250/8145187/50aa76a6-11fe-11e5-95e1-8ecff52afdd9.png)

**Comment by ppmeis** [comment] 2015-07-27 01:01
For now I detect these issues on Windows:

Sun is a black square:
![image](https://cloud.githubusercontent.com/assets/4381277/8896844/df41192a-3408-11e5-88ad-904e3a907c53.png)

Also, shadow flickering in almost all objects:
![image](https://cloud.githubusercontent.com/assets/4381277/8896849/0102f7cc-3409-11e5-9f2a-39a4fd6a3491.png)
![image](https://cloud.githubusercontent.com/assets/4381277/8896850/06804e66-3409-11e5-9008-81600f19a511.png)

It's curious, but when the car is completely stopped, shadows look fine I think.

But I don't get any problem with weather, even snow works fine. Which device are you using? Maybe it could be a PowerVR bug...

**Comment by ppmeis** [comment] 2015-07-27 01:04
Also, when I tried to use a 100% savefile from Gamefaqs, game detects it as corrupted. Checking in real hardware what happens...

**Comment by ppmeis** [comment] 2015-12-06 23:00
Tested with latest build, now the sky is completely black:
![image](https://cloud.githubusercontent.com/assets/4381277/11616148/ef7cd70a-9c74-11e5-974d-e48343ad0f0a.png)

Fortunately, shadows are good now:
![image](https://cloud.githubusercontent.com/assets/4381277/11616166/83494630-9c75-11e5-8697-5e8d8490f717.png)

**Comment by unknownbrackets** [comment] 2015-12-24 06:32
Can you try to catch when it's rendering the sky in the GE debugger?

Skies can be tricky to catch, especially when they're drawn black.  It might be the first thing it renders (before it draws other stuff on top), but it might also be something it draws near the end (stenciled in using depth testing or otherwise.)  Best to check the texture on the left to be sure.

It also might be separately applying the rain effect: for example, it might first apply the sky, and then do something tricksy to the sky to make it look like rain.  It could be that this is now generating black, if you initially see sky and then it's erased.

-[Unknown]

**Comment by hrydgard** [comment] 2017-12-13 11:04
Seems the sky is no longer black, but the shadows are blinking.

**Comment by ppmeis** [comment] 2017-12-13 11:16
Tested with latest build, It looks like one frame draw shadows and one not. Here an example:

No shadows:
![image](https://user-images.githubusercontent.com/4381277/33936018-439f9ad8-dffe-11e7-8f76-bdb93c0ab73c.png)
![image](https://user-images.githubusercontent.com/4381277/33936194-03ac4308-dfff-11e7-9ea1-521f89bd5353.png)


When shadows are ok:
![image](https://user-images.githubusercontent.com/4381277/33936169-e329dd5c-dffe-11e7-85ad-6a0367e1af01.png)
![image](https://user-images.githubusercontent.com/4381277/33936044-63e763a2-dffe-11e7-9337-872ecc57c12d.png)
![image](https://user-images.githubusercontent.com/4381277/33936058-702db81e-dffe-11e7-8aa7-8cc0a03e2a52.png)

**Comment by unknownbrackets** [comment] 2018-11-18 15:55
Could you try exporting a GE frame dump?  If possible, it'd be great to have one with and one without the shadows (I'd suggest just mashing record, and then checking the dumps that result to find two useful ones.)

You can check a dump simply by opening it with PPSSPP.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-11-24 00:53
Hm, both of those dumps seem to have proper shadows (same as PSP rendering, and they look right too) when played back alone.  That means it could be some sort of state issue, or it could be some texture/framebuffer overlap.

-[Unknown]

**Comment by nassau-tk** [comment] 2020-09-25 12:07
Oops!! I duplicated.
#13478 
Sorry.
for reference.

**Comment by Gamemulatorer** [comment] 2021-10-09 00:55
Sun still got a blackbox similar to burnout legend
if I enable SBTE doesn't help on this game graphics issues and also the game is slow.
![Screenshot_2021-10-09-08-44-26-026_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136637965-acb55a2e-b0d6-4aac-af85-54e219135b33.jpg)

**ge dump** 
[Colin McRae.zip](https://github.com/hrydgard/ppsspp/files/7314745/Colin.McRae.zip)

**Comment by unknownbrackets** [comment] 2021-10-18 04:45
Now, shadows:

Initially, it draws the ground.  Here's a screenshot:
![Ground before any shadows, trees, or objects](https://user-images.githubusercontent.com/191233/137669975-8b7f7f7b-082e-4e9d-a75a-9be3499d99e5.png)

At 152/1499, it draws an offwhite from a texture to  0x040cc000 (5551.)  Then it proceeds to draw the shadows to this other buffer, through 367/1499.  At 368/1499, it blends some white to brighten it up a bit.  It textures that using dst + ZERO blend, which applies the shadows to the actual scene.  Here's the shadows drawn:
![Scene without trees, but with shadows on the ground](https://user-images.githubusercontent.com/191233/137669916-d2f32153-26a2-4cf6-b6c4-98d2f720cc76.png)

But this blend just... doesn't work the first time around.  It doesn't blend.  And the reason is that the shadows never even get drawn, that first time.  And that's all because of depth.

At 151/1499, we've created a new and beautiful depth buffer at 0x04088000.  We reuse this depth buffer for the shadows, just with depth write disabled.  But it's not copying the first time.

If I make it copy the depth buffer on create (not just switch), then this works for the first frame and everything is fine.  I'm thinking we should do that, but I don't see why that would cause flicker?  Maybe there's more happening with that temp buffer, or it's misdetecting the levels of separation?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-10-22 02:53
This game required buffered rendering warning in compat ini because skipp buffering cause graphics issue
![Screenshot_2021-10-22-10-36-10-829_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/138385512-1da4d09e-a748-4b9a-a07d-1f9af7204592.jpg)

The sun still causing lag if SBTE is enable
![Screenshot_2021-10-22-10-52-51-174_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/138385707-0c77ff85-62d3-43e6-8581-133bee9f622f.jpg)

**software rendering**
![Screenshot_2021-10-22-10-46-14-867_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/138385658-1c7708fa-166f-41a8-bc3c-bb98f8c4bffd.jpg)

**Comment by QrTa** [comment] 2022-08-29 18:13
To "correct" lens flare until it get fixed. Use this cheat. 

_S ULES-00111
_G Colin McRae Rally 2005 Plus
_C1 Correct Lens Flare
_L 0xE01C2025 0x00197CA4
_L 0x2019925C 0x0E200800
_L 0x20199260 0x00115040
_L 0x20002000 0x16800007
_L 0x20002004 0x3C1BB504
_L 0x20002008 0x277B0040
_L 0x2000200C 0x17630004
_L 0x20002010 0x00000000
_L 0x20002014 0x00002821
_L 0x20002018 0x00004021
_L 0x2000201C 0x00004821
_L 0x20002020 0x03E00008
_L 0x20002024 0x022A5026
_L 0x20198AC8 0x0A20080A
_L 0x20198ACC 0x7D05B804
_L 0x20002028 0x3C1BE100
_L 0x2000202C 0x17650009
_L 0x20002030 0x3C1BE100
_L 0x20002034 0x277BFFFF
_L 0x20002038 0x17640006
_L 0x2000203C 0x8D64FFFC
_L 0x20002040 0x3C1BCB00
_L 0x20002044 0x277BFFFF
_L 0x20002048 0x17640002
_L 0x2000204C 0x3C1BE200
_L 0x20002050 0x2765FFFF
_L 0x20002054 0x0A2662B4
_L 0x20002058 0xAD650008
_L 0x20197CA4 0x00002021
_C0 Correct Lens Flare [Disable]
_L 0xE0052021 0x00197CA4
_L 0x2019925C 0x00115040
_L 0x20199260 0x022A5026
_L 0x20198AC8 0x7D05B804
_L 0x20198ACC 0xAD650008
_L 0x20197CA4 0x00852025

**Comment by nassau-tk** [comment] 2022-11-26 13:07
The sun will drawn correctly on v1.13.2-2076.
*No appear the black box.
But FPS goes down on Android more than before fix it.

Galaxy S20/Android12
Snapdragon865 /Adreno650/RAM12GB

But Windows work smooth.
Windwos 10
Ryzen7 3800X
Nvidia Geforce RTX3060
RAM32GB

**Comment by hrydgard** [comment] 2022-11-26 17:33
Oh indeed, the shadows work too now, that's nice.

The slowdown looks to be caused by a GPU readback, I'm gonna see if it's avoidable or not.

**Comment by hrydgard** [comment] 2022-11-26 17:55
That wasn't too hard, fix committed.

I'm gonna go ahead and close this. Please re-open if you see any new graphical issues.

**Closed by hrydgard** 2022-11-26 17:55 UTC
