### ISSUE TITLE
Phantasy Star Portable graphics issues on Adreno 3xx GPUs

### ISSUE THREAD

**Issue by zero295** [hrydgard/ppsspp#11732] opened 2019-01-15 18:40 UTC
### What happens?

Several different things, which I will detail in order.

1: Character Model is missing during character creation/customization, except for a brief moment when changing race.

2: Character art is missing from the text sections of the game.

3: missions become unplayable because depending on graphics settings, I either get a black screen that freezes, or a blinking rendered map with no characters, which eventually freezes. Sometimes the message "Video Memory Full" will pop up right before this, during the loading screen.

4: Occasionally, while cycling through settings, I come across a rainbow colored bug/glitch screen of doom.

### What *should* happen?

1: model should be clearly visible during character creation/customization.

2: Characters should show up when talking.

3: A fully rendered, populated, and non-flickering map.

4: depends on when it shows up.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Moto e5 Play (Motorola)
Android 8.0.0
PPSSPP 1.7.5-363-ge3dd1553f

**Comment by Emulatorer** [comment] 2019-01-16 06:19
hmm.. this #11576

**Comment by Abbanon** [comment] 2019-01-16 08:37
@Emulatorer No, this looks like a different issue entirely. Likely hardware specific.

**Comment by hrydgard** [comment] 2019-02-08 15:40
Screenshots of the problems could be helpful.

**Comment by Supereor** [comment] 2019-04-23 19:39
I'm having these exact same issues, and I also have a Moto E5 Play.  Some screenshots:
![Screenshot (192)](https://user-images.githubusercontent.com/33299788/56610293-ae1b2f00-65d4-11e9-9c24-9f2d76d72781.png)
This was recorded from my phone, then I took a screenshot of it on my desktop because it only appears for a split second when switching races

![Screenshot_20190423-141501](https://user-images.githubusercontent.com/33299788/56610441-06523100-65d5-11e9-9185-4e1a9e44362b.png)
This actually is a phone screenshot, and is what you would get after switching races

![Screenshot_20190423-141828](https://user-images.githubusercontent.com/33299788/56610524-3c8fb080-65d5-11e9-9981-f34e4c719ab1.png)
Some issues with the text

![Screenshot_20190423-142013](https://user-images.githubusercontent.com/33299788/56610539-487b7280-65d5-11e9-80fc-754b623bb722.png)
Character art isn't showing up, and text box is also absent

**Comment by unknownbrackets** [comment] 2019-04-24 04:51
It's clear in those screenshots that depth is very broken.

Note: the Moto E5 Play has Adreno 3xx.

-[Unknown]

**Comment by ViciousJCK** [comment] 2020-11-15 11:33
Is... it fixed? Im New to Github😅 Idk if um.. Closed means its fixed

**Comment by hrydgard** [comment] 2020-11-15 17:09
Well, it's not closed - that closed sign is for a related issue.

**Comment by Gamemulatorer** [comment] 2022-11-24 15:01
@zero295 how about now?

**Comment by Gamemulatorer** [comment] 2022-11-25 18:34
Can still reproduce this issue tried and tested on my vivo y51a adreno 306
![Screenshot_20221126_023237](https://user-images.githubusercontent.com/37603562/204039992-7b3cc605-a01d-42e2-ab89-ccc1063865f4.png)
[ULUS10410.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/10094656/ULUS10410.ppdmp.zip)

**Comment by unknownbrackets** [comment] 2022-12-05 04:19
I created #16504, which removes the old hack (which I wonder if was somehow misbehaving here) for the better tested accurate depth path.  I don't know if that fixes this issue, though.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-12-05 08:53
I will test later Phantasy Star Portable 1 & 2 on my vivo y51a using the recently build.

**Comment by Gamemulatorer** [comment] 2022-12-05 14:47
Can safely close this issue.
Phantasy Portable 1 and 2 issue resolved.
![Screenshot_20221205_224129](https://user-images.githubusercontent.com/37603562/205665773-9d5a5ad6-da64-44bf-8246-919aa6c7bd21.png)
![Screenshot_20221205_224228](https://user-images.githubusercontent.com/37603562/205665799-53d22f8c-5bd9-4ab0-b302-7451e569e2b9.png)

**Closed** 2022-12-05 15:01 UTC
Labels: Adreno GPU
