### ISSUE TITLE
Carsh on Retroarch When set RenderMode as non-buffered rendering

### ISSUE THREAD

**Issue by xiejinglan** [hrydgard/ppsspp#14664] opened 2021-07-31 07:09 UTC
Some game need set rendermode as  non-buffered  ,When i set is on Retroarch, it's carshed

**Comment by Panderner** [comment] 2021-07-31 07:20
@xiejinglan any games affected?

**Comment by xiejinglan** [comment] 2021-07-31 07:40
For example  <Mortal Kombat : Unchained> is Running too slow, And my cpu was Qualcomm snapdragon 865

**Comment by xiejinglan** [comment] 2021-07-31 07:41
For example  Mortal Kombat : Unchained  is Running too slow
And my cpu was qualcomm snapdragon 865

**Comment by Gamemulatorer** [comment] 2021-07-31 08:21
> Some game need set rendermode as non-buffered ,When i set is on Retroarch, it's carshed

Which games need non-buffered? 🤔

**Comment by bslenul** [comment] 2021-07-31 11:06
To add a bit more info...

Vulkan (full log: https://pastebin.com/kVdXD5dE):
```
[libretro ERROR] [SYSTEM] (..\Common/GPU/Vulkan/VulkanRenderManager.h:VulkanRenderManager::BindPipeline:155) Critical: [curRenderStep_ && curRenderStep_->stepType == VKRStepType::RENDER] *** Assertion ***
```
GL/GLcore (rest of the log is pretty much the same as Vulkan):
```
[libretro ERROR] [SYSTEM] (..\Common/GPU/OpenGL/GLRenderManager.h:GLRenderManager::SetNoBlendAndMask:764) Critical: [curRenderStep_ && curRenderStep_->stepType == GLRStepType::RENDER] *** Assertion ***
```
Black screen with D3D11 but audio can be heard in the background.

Only tested on Windows 10, I could try on my Linux VM if needed (GL only tho, it doesn't support Vulkan).

**Comment by Panderner** [comment] 2021-07-31 15:31
> For example Mortal Kombat : Unchained is Running too slow
> And my cpu was qualcomm snapdragon 865

Mortal Kombat: Unchained running smoothly for me. I'm using POCO M3 using buffered rendering. 
![Screenshot_2021-07-31-23-25-57-312_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/127744790-5ad1ab70-c52e-4354-a3ce-e81d880f9027.jpg)

**Comment by Panderner** [comment] 2021-07-31 15:47
And same goes to RetroArch version
![Screenshot_2021-07-31-23-46-34-844_com retroarch](https://user-images.githubusercontent.com/37503397/127745245-370782f6-d9d7-4303-9b37-ce222549780e.jpg)

**Comment by xiejinglan** [comment] 2021-07-31 18:19
@Panderner Ye , I saw it, but set RenderMode as non-buffered should be not carsh.

**Comment by bslenul** [comment] 2023-05-26 10:27
While messing with something else I think I've found the cause of the crash, the non-buffered mode is simply "applied" too soon during the starting process, if I delay it a bit on startup it doesn't crash anymore.

However... it doesn't seem to do anything, I tested with Daxter since the setting makes it pretty obvious when it's applied:

Standalone:

![image](https://github.com/hrydgard/ppsspp/assets/33353403/bf869609-5e21-4419-82d6-36822d99d7e1)

Libretro core:

![image](https://github.com/hrydgard/ppsspp/assets/33353403/a866efbb-9172-4627-83b5-abcf8eedf54f)

So yeah, I don't think the setting works at all with the core :/

**Comment by hrydgard** [comment] 2023-05-26 10:56
It should not be used anyway. Just don't expose it in retroarch..

**Comment by bslenul** [comment] 2023-05-26 11:10
OK, done. This issue can be closed then I guess :p

**Comment by gouchi** [comment] 2024-06-03 19:48
@hrydgard @unknownbrackets Please close this issue. Thank you.

**Closed** 2024-06-03 20:09 UTC
Labels: Libretro
