### ISSUE TITLE
Sound stops in Castlevania DXC

### ISSUE THREAD

**Issue by SuperSaiyanMusashi** [hrydgard/ppsspp#19583] opened 2024-11-04 21:50 UTC
### Game or games this happens in

ULUS-10277 Castlevania Dracula X Chronicles 

### What area of the game / PPSSPP

When playing Rondo of Blood under the 'Original Games' option, during the opening cutscene, right around where Dracula turns into a bat, the sound suddenly mutes.  Video keeps playing without it.

### What should happen

The sound for the cutscene should keep playing

### Platform

Windows

### Mobile device model or graphics card (GPU)

NVIDIA GForce GTX 980Ti

### PPSSPP version affected

v1.18.1

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2024-11-04 22:13
I think this is a dupe of the ancient #5564 . 

Related to a bunch of other Atrac playback issues.

There's a chance my work-in-progress Atrac rewrite will fix it, but can't say for sure yet. We'll see.

**Closed** 2024-11-04 22:13 UTC
Labels: Atrac3+

**Comment by SuperSaiyanMusashi** [comment] 2024-11-04 23:07
It might be.  I figured I'd bring it up since PPSSPP was just updated.
