### ISSUE TITLE
[Monster Hunter Freedom Unite] Freeze... crash !

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#5843] opened 2014-04-12 09:18 UTC
I noticed that when I do a Training quest, a freeze occurs at the moment the music is changing (it's when you enter in the zone where the monster is).
Normally, the freeze lasts 1 or 2 seconds but this time it has crashed PPSSPP.

But I succeeded to do a screenshot of the log and I have seen this line : 
![0](https://cloud.githubusercontent.com/assets/3978690/2686846/0158a270-c223-11e3-9e82-26e668277042.png)

What do you think about this, developers ? ;)

**Comment by sum2012** [comment] 2015-01-15 23:09
Update debug log to  v0.9.9.1-1502-g8a574e5
https://gist.github.com/sum2012/73d4eb45c6d54ee9efdb

@vnctdj can you provide game 's save instead of save status ? Thanks

**Comment by vnctdj** [comment] 2015-01-18 20:59
Why do you want a save instead of a save state ?
I don't think the bug is related to the save, it only happens when you play since a pretty long time (I would say few hours), and most of the time, at the moment a sound effect is played.
So, if you really want a save, just create one, given that any save will be able to reproduce the bug :)

**Comment by sum2012** [comment] 2015-01-19 11:06
I want to modify some functions,but can not load status

**Comment by vnctdj** [comment] 2015-01-19 17:27
I suppose you have the game, so why not creating a new save and loading the save status afterwards ?
I don't know what I can do more... Or maybe I don't understand what you need exactly :-/

**Comment by i30817** [comment] 2015-01-20 04:43
why don't you try this, if it is the problem: https://github.com/hrydgard/ppsspp/issues/6615#issuecomment-49828380

**Comment by vnctdj** [comment] 2015-02-13 00:15
@sum2012 
Trokinos has provided a save state + the corresponding in-game save on the forum, here is the link to his post >> http://forums.ppsspp.org/showthread.php?tid=1095&pid=102710#pid102710
I hope it will be useful for you :)

**Comment by vnctdj** [comment] 2015-02-13 14:08
Here is a new error noticed by Trokinos in the forum, maybe it can be relevant :
![0](https://cloud.githubusercontent.com/assets/3978690/6188521/2a7c2b70-b392-11e4-8bac-e2d4ca26c237.png)

**Comment by vnctdj** [comment] 2015-02-19 15:23
Apparently the same freeze/crash has been found on *Dissidia 012: Duodecim Final Fantasy*, you can see it in the forum, courtesy of Trokinos : http://forums.ppsspp.org/showthread.php?tid=1272&pid=103085#pid103085

**Comment by vnctdj** [comment] 2015-03-09 17:55
Here is another occurrence with *Monster Hunter Portable 3rd* : http://forums.ppsspp.org/showthread.php?tid=1983&pid=104037#pid104037

**Comment by unknownbrackets** [comment] 2016-01-27 03:54
Any chance this has improved with the latest savestate fixes?  Thinking it might've been related.

-[Unknown]

**Comment by Trokinos** [comment] 2016-01-27 19:28
I'll play several missions on MHFU and GEB while laregly using the save/load states using current latest build ( v1.1.1-870-g194e9ed) and will report in a few days (or before in case i run into one) if i get a crash or not.

**Comment by unknownbrackets** [comment] 2016-01-28 04:02
Well, that sounds very promising already.

The bug fixed in #8471 basically would've only affected certain games - specifically games that have pending drawing commands right when the display changes to the next frame.  Most of the time, games finish everything before displaying a frame - and so, it might be only when certain effects are used, or something.

So for example, maybe it's only if you save a state while a certain effect is being drawn.  Or even if you save a state during a very active scene with lots of things moving around.  Those are things that might make it have some pending drawing commands at a frame switch.

Will wait to hear more.  But if it seems like it's not reproducing, we can close this and always reopen (or create a new one, in case it's different / more reproducible) if it happens again.

-[Unknown]

**Comment by Trokinos** [comment] 2016-01-28 18:43
Today i played 4 longer hunts in GEB (between 10 and 15 minutes)  from the difficulty 9 and 10 as monsters are more resilient, i imagine if time is a factor in the crash it would lead into more possibility to get it, andi  did a very lot save state - reload state during those hunts.
No crash at all.

Notably i took out a Fallen Ouroboros (hunt "Restoration of Myth) in difficulty 10, and those huge guys in the past seemed to trigger the crash much more than other monsters , and there no problem despite the several dozen of save - reload state i did during the whole battle.
And with the amount of special effect and you being hit (blocking hits) very often due to the monster size/range, i think this is challenging for the states.

I played too 1 of the challenge mission, that was interesting for this test as it involved killing a very lot of minor monsters , the specific is that they were spawning constantly after other minor monster were killed, so i imagine for a save state it would be more difficult to reload it correctly, but again using a lot of them displayed no problems.

I don't know if it's still too early, but what i'm sure is that doing that in past versions, i mean several dozen of save - reload in a single mission and playing multiple mission on the same PPSSPP session after abusing the states that much, i would have crashed several times.

So, hopefully, this may be truly fixed, at least for GEB, and maybe let's hope for MHFU (though as said the bug was not happening often in MHFU and i've not seen it in months) and other game that exhibited the problem.

**Comment by hrydgard** [comment] 2016-01-28 20:03
Alright, that sounds like enough testing to conclude that it's likely fixed, so let's close. If it reappears we can always reopen.

**Closed by hrydgard** 2016-01-28 20:03 UTC

**Comment by vnctdj** [comment] 2016-01-28 21:40
Cool ! Thank you for your tests @Trokinos, I really hope we will never see this issue again !

Too bad I don't have the time to also do some tests myself, though...
