### ISSUE TITLE
[Feature Request] Real Fullscreen Mode

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7953] opened 2015-09-08 11:07 UTC
We already have Borderless Fullscreen mode but can we get real Fullscreen mode for PPSSPP?
There are couple of benefits of it like better performance and being able to set custom resolutions.
And it seems like 3D Vision 2 would benefit from it too. 
Ongoing discussion: http://forums.ppsspp.org/showthread.php?tid=16538&pid=110425#pid110425

**Comment by i30817** [comment] 2015-09-10 17:15
I always hate apps forcing fullscreen mode because GNOME et al is full of bugs on fullscreen handling and alt+tab.

**Comment by hrydgard** [comment] 2015-09-10 17:40
It seems most useful for Windows so that's what I'll implement first when I get to this. So you probably don't need to worry about that for a while, heh.

**Comment by GamerzHell9137** [comment] 2015-09-10 22:03
Thumps up, can't wait hrydgard :dancer:

**Comment by GamerzHell9137** [comment] 2016-02-09 18:56
No news about the feature? I guess DSR would work too if we add it?

**Comment by Prcuvu** [comment] 2016-03-01 13:51
+1 to this idea.

If PPSSPP runs with both Direct3D9 and real fullscreen mode, NVIDIA ShadowPlay will be able to capture it.

**Comment by unknownbrackets** [comment] 2019-03-24 04:04
Closing this as a duplicate of #9408 since the other has a milestone set currently.

-[Unknown]

**Closed by unknownbrackets** 2019-03-24 04:04 UTC
Labels: Feature Request, Platform-specific (Windows)
