### ISSUE TITLE
Feature request sticky button

### ISSUE THREAD

**Issue by Lemoncak3** [hrydgard/ppsspp#13468] opened 2020-09-23 08:43 UTC
Hi, just want to ask if its posibble to add sticky button to the combo button maybe? So if i am playing game that need to hold button and press another button it won't be too hard on virtual pad. Example : Silent hill Origins, Crisis Core FF VII, Kingdom Heart Birth by Sleep.

**Comment by Gamemulatorer** [comment] 2020-09-23 09:47
Duplicate of #10051

**Closed** 2020-09-23 09:52 UTC

**Comment by iota97** [comment] 2020-09-24 07:06
Combo button already have it, it's just called "Toggle mode".
