### ISSUE TITLE
Fight Night Round 3 super slow loading at start

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10680] opened 2018-03-03 14:28 UTC
Ive noticed that the ppsspp has loading stuff before it starts, in my other games, it is normal to fast but when I launch fight round 3, it is very slow, it takes me 10-15 minutes before it starts.

**Comment by hrydgard** [comment] 2018-03-03 16:50
I've also noticed that loading seems to have slowed down substantially since the introduction of background loading. @unknownbrackets what do you think, maybe the loader thread gets less prioritized? Still, the render thread should not be particularly busy...

**Comment by leopard20** [comment] 2018-03-03 20:41
@hrydgard
I also noticed that unthrottling GoW during the splash screens makes it take longer to load (and as I described in this issue https://github.com/hrydgard/ppsspp/issues/10668 it lags in transitions too).
It's not as long as Fight Night here, but still around 2x longer.

**Comment by unknownbrackets** [comment] 2018-03-04 02:26
@hrydgard I thought it was fast when I introduced it, at least.  It definitely seems like it's gotten a lot slower, though.  There's definitely a bug.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-03-04 02:55
Hmm v1.5.4-581-gbeeb9cc3a is actually quite fast on Android - about 0.3s.  I definitely saw it take a while even on desktop a couple times but having trouble reproducing.

-[Unknown]

**Comment by marosis** [comment] 2018-03-08 17:47
same problem #10622

**Comment by hrydgard** [comment] 2018-03-08 18:17
Yeah, closing as dupe of #10622

**Closed by hrydgard** 2018-03-08 18:17 UTC
