### ISSUE TITLE
Black Screen at Menu OutRun 2006 Coast 2 Coast USA when Resolution (5X or above). 

### ISSUE THREAD

**Issue by tabnk** [hrydgard/ppsspp#7634] opened 2015-03-26 04:56 UTC
Black Screen at Menu but In game ok OutRun 2006 Coast 2 Coast USA.

All default setting except Internal Resolution (5X or above). 

Tested on ppsspp-v1.0.1-95-g8186278-windows-amd64 and Latest Version.

**Comment by unknownbrackets** [comment] 2015-03-26 07:08
Isn't this a duplicate of #5726?  It's been fixed in a much more recent git build.  It's not fixed in the latest stable version.

-[Unknown]

**Closed by unknownbrackets** 2015-03-26 07:08 UTC
