### ISSUE TITLE
Obscure: The Aftermath - adhoc issues

### ISSUE THREAD

**Issue by Xemiru** [hrydgard/ppsspp#6693] opened 2014-08-05 14:46 UTC
v0.9.9-68-g404766c, Windows 7 x64bit, ULUS10484
Networking must be enabled, otherwise the game works fine as far as I know.

Game spams a disconnect function upon starting the game. If networking is off, stops upon starting a new game.
![screenshot 2014-08-05 07 40 07](https://cloud.githubusercontent.com/assets/1240058/3812924/c810b624-1cae-11e4-9f15-c94cee0c3306.png)

Upon starting a new game, the game blackscreens with the console spamming attempts of using an unimplemented[?] function.
![screenshot 2014-08-05 07 40 32](https://cloud.githubusercontent.com/assets/1240058/3812950/054ca9ee-1caf-11e4-8723-acbd3b50a3be.png)

**Comment by benderscruffy** [comment] 2018-05-21 06:07
PPSSPP v1.5.4-995-g373366911 Windows 64 bit
when you choose join game the emulator freezes up 
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2021410/ppsspplog.zip)

**Comment by Pik-a-boo** [comment] 2020-09-21 13:57
Well it's still a thing but I also got that issue with The Warriors.
Here is an updated log :
![image](https://user-images.githubusercontent.com/48792756/93775834-901f8700-fc2b-11ea-8127-0761c4dee930.png)
maybe @ANR2ME knows something about this.

**Comment by ANR2ME** [comment] 2020-09-22 00:12
> 
> 
> Well it's still a thing but I also got that issue with The Warriors.
> Here is an updated log :
> ![image](https://user-images.githubusercontent.com/48792756/93775834-901f8700-fc2b-11ea-8127-0761c4dee930.png)
> maybe @ANR2ME knows something about this.

Some games really like to do weird stuff like spamming the logs with AdhocctlDisconnect repeatedly even though they're already disconnected.

But what about the multiplayer it's self? Did you have any issue playing multiplayer on The Warriors? like unable to see each other? disconnections issue?

**Comment by Pik-a-boo** [comment] 2020-09-22 04:22
The Warriors seems like a different issue that is not related to adhoc apparently.
It just shows a black screen like this game though.

**Comment by ANR2ME** [comment] 2020-09-22 04:30
Obscure the Aftermath was having frozen issue instead of black screen, but it's fixed now with this PR https://github.com/hrydgard/ppsspp/pull/13463

Black screen usually caused by a crash in PSP game, did you see any Error (red) message in the Logs during this black screen?

**Comment by Pik-a-boo** [comment] 2020-09-22 10:32
Still not fixed with obscure because the other player keep disconnecting when he tries to join.

**Comment by ANR2ME** [comment] 2020-09-22 15:59
I never test this over the internet, i can only test on localhost and LAN (android vs pc)

**Comment by Pik-a-boo** [comment] 2020-09-22 17:28
yeah you need to join really quick so it wont work over the internet maybe.

**Comment by ANR2ME** [comment] 2020-09-24 05:58
@Pik-a-boo is this games still have difficulties to Join a room over the internet using my latest PR?

**Comment by Saramagrean** [comment] 2021-02-07 15:39
PPSSPP latest git build (1.10.3-1728), Multiplayer mode work fine with ZeroTier (Android).

![147429578_766832570901429_3674675989897380235_o](https://user-images.githubusercontent.com/26355472/107151403-f74c9680-6994-11eb-9c91-66cccef991b3.jpg)

**Comment by unknownbrackets** [comment] 2021-02-07 15:54
Thanks for confirming.

-[Unknown]

**Closed by unknownbrackets** 2021-02-07 15:54 UTC
Labels: Networking / adhoc
