### ISSUE TITLE
build crashed in tekken games

### ISSUE THREAD

**Issue by tausifj15** [hrydgard/ppsspp#9128] opened 2016-11-23 03:43 UTC
Since build 146 all builds r crashed in tekken game while  fight is going to start

11-23 09:10:14.916 E/RemoteViews(1367): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:14.928 E/RemoteViews(840): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:14.930 E/RemoteViews(840): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:15.471 D/jdwp    (24441): Can't connect to ADB control socket:Connection refused
11-23 09:10:15.510 E/        (840): Could not open '/data/data/hotplug/cmd'
11-23 09:10:15.510 E/        (840): error : 2, No such file or directory
11-23 09:10:15.564 E/        (840): Could not open '/data/data/hotplug/cmd'
11-23 09:10:15.564 E/        (840): error : 2, No such file or directory
11-23 09:10:15.934 E/RemoteViews(1367): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:16.052 E/RemoteViews(840): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:16.053 E/RemoteViews(840): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:16.916 E/        (840): Could not open '/data/data/hotplug/cmd'
11-23 09:10:16.916 E/        (840): error : 2, No such file or directory
11-23 09:10:16.997 D/wpa_supplicant(30760): wlan0: Control interface command 'SIGNAL_POLL'
11-23 09:10:16.998 D/wpa_supplicant(30760): nl80211: survey data missing!
11-23 09:10:17.126 E/AudioService(840): handleConfigurationChanged() createInstance IAudioServiceExt fail
11-23 09:10:17.145 E/        (840): Could not open '/data/data/hotplug/cmd'
11-23 09:10:17.145 E/        (840): error : 2, No such file or directory
11-23 09:10:17.313 E/RemoteViews(1367): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:17.333 E/RemoteViews(840): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:17.334 E/RemoteViews(840): ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
11-23 09:10:17.469 I/NativeApp(2603): g_Config.screenRotation = 1
11-23 09:10:17.469 I/NativeActivity(2603): Setting requested rotation: 1 ('1')
11-23 09:10:17.471 I/NativeActivity(2603): onResume
11-23 09:10:17.471 I/NativeGLView(2603): onResume
11-23 09:10:17.471 D/jdwp    (24441): Can't connect to ADB control socket:Connection refused
11-23 09:10:17.475 I/NativeApp(2603): NativeApp.resume() - resuming audio
11-23 09:10:17.475 I/NativeApp(2603): Calling OpenSLWrap_Init_T...
11-23 09:10:17.513 I/NativeApp(2603): Returned from OpenSLWrap_Init_T
11-23 09:10:17.531 E/        (2603): appName=org.ppsspp.ppsspp, acAppName=/system/bin/surfaceflinger
11-23 09:10:17.531 E/        (2603): 0
11-23 09:10:17.550 I/NativeApp(2603): NativeApp.displayInit()
11-23 09:10:17.550 I/NativeApp(2603): Flushed 0 un-executed tasks
11-23 09:10:17.563 I/NativeApp(2603): gl_lost() clearing 3 items:
11-23 09:10:17.563 I/NativeApp(2603): gl_lost(1 / 3, 0x64780ec0, 62698f80)
11-23 09:10:17.563 I/NativeApp(2603): gl_lost(2 / 3, 0x64782378, 62698f80)
11-23 09:10:17.563 I/NativeApp(2603): gl_lost(3 / 3, 0x6478f9d0, 62698fc8)
11-23 09:10:17.563 I/NativeApp(2603): gl_lost() completed on 3 items:
11-23 09:10:17.563 I/NativeApp(2603): gl_restore() restoring 3 items:
11-23 09:10:17.563 I/NativeApp(2603): gl_restore(1 / 3, 0x6

**Comment by LunaMoo** [comment] 2016-11-23 05:33
If by "146" you mean v1.3-146-g9c08b60, then it surely isn't that as that merge didn't affected any PPSSPP code at all.
 You can try to find actual commit which caused that regression, through I suspect this is just duplicate of  #9114

**Comment by tausifj15** [comment] 2016-11-23 05:46
Yeah

**Comment by tausifj15** [comment] 2016-11-23 05:47
I reported it before but its fixed in 143 build but still started in 146 builds and the latest one 150 build

**Comment by LunaMoo** [comment] 2016-11-23 05:57
Then check v1.3-144-g5df685f as that's more likely to do anything.

 v1.3-146-g9c08b60 only affects one post process shader which you probably aren't even using and it doesn't even change any logic in that effect, just corrects one type.

**Comment by tausifj15** [comment] 2016-11-23 06:26
So u r not going to fix it

**Comment by Nucleoprotein** [comment] 2016-11-24 11:31
@tausifj15 Fix what ? Developers need to reproduce crash first. 
I think your issue is related to AMD OpenGL crash (you are using AMD GPU ?), which is crashing also Tekken games (tested).

**Comment by tausifj15** [comment] 2016-11-24 11:54
My android version is kitkat 4.4.2

**Comment by Nucleoprotein** [comment] 2016-11-24 11:55
I think this is duplicate of https://github.com/hrydgard/ppsspp/issues/9114

**Comment by tausifj15** [comment] 2016-11-24 11:55
Florence castle fixed it in build 143 but its still started

**Comment by tausifj15** [comment] 2016-11-24 11:56
No

**Comment by tausifj15** [comment] 2016-11-24 11:57
This issue is in only tekken  games

**Comment by Nucleoprotein** [comment] 2016-11-24 11:57
Please edit your post do not write next one ...

**Comment by tausifj15** [comment] 2016-11-24 12:01
So in next build this issue fixed or not

**Comment by tausifj15** [comment] 2016-11-24 12:02
But next time i told him and he fixed it

**Comment by tausifj15** [comment] 2016-11-24 12:05
So its going tofix or not im using stable one now

**Comment by Nucleoprotein** [comment] 2016-11-24 12:07
Yes you want next build to fix you issue ... this is stupid as there are about 650 opened issues and few active developers so you need to wait for your issue.

**Comment by tausifj15** [comment] 2016-11-24 12:52
Ok thankx for respond sir

**Comment by hrydgard** [comment] 2016-12-01 15:38
That may have fixed it, please try a new build.

**Closed** 2016-12-02 08:57 UTC
