### ISSUE TITLE
Performance regression in God Of War (1.8.0)

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11953] opened 2019-04-01 11:16 UTC
I have found massive performance regression in GoW. From 25-30 fps to 10-15 fps. Tested 1.8.0 And 1.7.5.
Tested OpenGL (mali)
Issue is only with buffered rendering!!
1.7.5
![Screenshot_20190401-135608](https://user-images.githubusercontent.com/33152267/55325676-05225e00-5486-11e9-958f-f67abf052f19.png)
1.8.0
![Screenshot_20190401-135843](https://user-images.githubusercontent.com/33152267/55325791-5af70600-5486-11e9-899e-012f9b359e9c.png)

more information i will post later and will try find build of version where it started

**Comment by hrydgard** [comment] 2019-04-01 12:12
With default settings?

**Comment by marosis** [comment] 2019-04-01 12:20
Yeah

**Comment by marosis** [comment] 2019-04-01 13:31
GOTCHA!!! It Is 1.7.5-435

**Comment by LunaMoo** [comment] 2019-04-01 13:37
Then it can't be with default settings. That change just reduced number of effects disabled by the speedhack that disables heavy effects.

**Comment by marosis** [comment] 2019-04-01 13:42
Ok sry. Now default (only off blocktransfler effects and set 1xPSP resolution)
1.7.5 435
![Screenshot_20190401-154019](https://user-images.githubusercontent.com/33152267/55332020-c942c500-5494-11e9-95fc-e4ee621f9d4b.png)

**Comment by hrydgard** [comment] 2019-04-01 13:54
Does blocktransfer effects off affect anything in the graphics? If not, then that commit is a list of stuff that we do that God of War doesn't need, so maybe a place to dig for speedhacks. And now the commit also fulfilled its purpose - I did it to see if there were stuff that the option disabled unnecessarily.

**Comment by marosis** [comment] 2019-04-01 13:59
Simulate block transfler effect Is here really interresting for improving performance. I off it to better see differents but i can post when is ON if you want

**Comment by marosis** [comment] 2019-04-01 14:06
![Uploading Screenshot_20190401-160116.png…]()

**Comment by unknownbrackets** [comment] 2019-04-02 02:48
I seem to remember the fireballs in the sky used block transfer and looked really weird with it off (they might be fine if you start the game with it on and then turn it off later, though.)

-[Unknown]

**Comment by marosis** [comment] 2019-04-02 05:30
I havve never seen anything and never found any graphics issue

**Comment by marosis** [comment] 2019-04-02 06:29
#11776 Hrydgard as you said: The idea of doing this step by step is to get reports about bad performance regressions so we can fix them.

**Comment by Emulatorer** [comment] 2020-03-18 08:42
This is God of War - Chain of Olympus?

**Comment by Gamemulatorer** [comment] 2020-05-08 00:19
God of War Chain of Olympus Demo ISO
the still very lag even using 30fps cheat code
![Screenshot_20200508-081645](https://user-images.githubusercontent.com/37603562/81356669-4d3d9680-9104-11ea-8b24-94c374fb82bc.png)

I cannot capture GE dump always stuck on blackscreen but full iso version is ok, why?
![Screenshot_20200508-081412](https://user-images.githubusercontent.com/37603562/81356786-9c83c700-9104-11ea-85d2-2873f4b1078e.png)

**Comment by Panderner** [comment] 2020-05-09 14:48
> this game still very lag even using 30fps cheat code

This is why God of War games needs a Stronger Processor. Gow games runs smoothly on a Snapdragon 660 Device (tested on Realme 2 Pro and Xiaomi Mi Pad 4 without frameskip. You need a Snapdragon 835 and higher or a recent Android phones with 4 GB of RAM. Too bad  for older android devices including recent budget android phones and tablets with 2 GB RAM.

**Comment by Gamemulatorer** [comment] 2020-05-09 16:45
> > this game still very lag even using 30fps cheat code
> 
> This is why God of War games needs a Stronger Processor. Gow games runs smoothly on a Snapdragon 660 Device (tested on Realme 2 Pro and Xiaomi Mi Pad 4 without frameskip. You need a Snapdragon 835 and higher or a recent Android phones with 4 GB of RAM. Too bad for older android devices including recent budget android phones and tablets with 2 GB RAM.

Looks ok now I use different region of this game :) 
![Screenshot_20200510-004151](https://user-images.githubusercontent.com/37603562/81479698-6acf4500-9257-11ea-958f-8bfe602dbd49.png)

**Comment by Gamemulatorer** [comment] 2021-05-18 17:14
In the latest version of ppsspp GoW Chain of Olympus is only lag on OpenGL but in Vulkan this game is stable on 60FPS default settings.
![Screenshot_2021-05-19-01-02-42-123_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118695225-89d7be00-b83f-11eb-9672-0d97133ada96.jpg)
![Screenshot_2021-05-19-01-03-00-159_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118695233-8c3a1800-b83f-11eb-89ba-3ab562d97c4e.jpg)
![Screenshot_2021-05-19-01-02-19-316_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118695237-8d6b4500-b83f-11eb-9f79-408cd1a9636e.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-18 17:35
OpenGL performance still very slow on ppsspp using my Redmi Note 9 🤔
![Screenshot_2021-05-19-01-33-59-295_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118698039-8abe1f00-b842-11eb-9ede-13ba3f9b4755.jpg)
![Screenshot_2021-05-19-01-33-51-254_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118698049-8c87e280-b842-11eb-911c-29d312096a45.jpg)

**Comment by Panderner** [comment] 2021-05-19 00:14
@Gamemulatorer have you tried to lower the resolution to 1x?

The game runs fine for me for my POCO M3 using OpenGL with some Slow Downs

![Screenshot_2021-05-19-08-10-14-918_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/118738702-3b93e080-b87a-11eb-8786-b09d7c858bf9.jpg)
![Screenshot_2021-05-19-08-12-00-857_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/118738707-40589480-b87a-11eb-99fc-ed33f59dcf9d.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-19 00:54
Yeah it's improve on 1X rendering resolution but it should be smooth on default settings in OpenGL like Vulkan 🤷
![Screenshot_2021-05-19-08-52-13-339_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118740951-b57a9880-b87f-11eb-882f-92666520d437.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-19 01:05
But in ppsspp v1.7.1 this game running full speed on OpenGL using default settings 🤔
![Screenshot_2021-05-19-09-02-58-235_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/118741619-41d98b00-b881-11eb-9ea5-113af91de17c.jpg)
![Screenshot_2021-05-19-09-02-51-313_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/118741624-443be500-b881-11eb-9856-103b1be49f59.jpg)
![Screenshot_2021-05-19-09-02-45-582_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/118741626-456d1200-b881-11eb-8a0e-953a40930ade.jpg)
![Screenshot_2021-05-19-09-02-24-858_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/118741628-4736d580-b881-11eb-8283-a161cdc0e344.jpg)
I also notice HW Tessellation can also enable on OpenGL unlike in the latest version it's grey out 🤔

**Comment by Gamemulatorer** [comment] 2021-05-19 01:22
#11776 reduce the effect on disable slower effects that's why this game become lag on OpenGL.

**Comment by Gamemulatorer** [comment] 2021-05-24 06:23
This issue should label as OpenGL only because on Vulkan this game is really smooth

**Comment by Panderner** [comment] 2021-05-24 08:36
I managed that OpenGL had Better Performance than Vulkan for my POCO M3 in 4x resolution.

OpenGL:
![Screenshot_2021-05-24-16-34-00-344_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/119320434-2837a980-bcae-11eb-9095-b644406cefce.jpg)

Vulkan:
![Screenshot_2021-05-24-16-32-35-517_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/119320462-2ec62100-bcae-11eb-8f23-b266f88f209f.jpg)

**Comment by Panderner** [comment] 2021-05-31 00:26
Note: Vulkan performance for God of War for Gamemulatorer's Redmi Note 9 runs faster than OpenGL but runs slower than OpenGL for my POCO M3.

**Comment by Gamemulatorer** [comment] 2021-07-11 18:19
I test this game again on latest development apk using Opengl backend again and the performance still worst here the log hope it can help determine what is the cause of performance decrease on opengl.
[logs-2021-07-12-02-16-39.zip](https://github.com/hrydgard/ppsspp/files/6797425/logs-2021-07-12-02-16-39.zip)

**Comment by Gamemulatorer** [comment] 2021-09-11 12:08
The GoW games performance on OGL still slow compare to VK.
[GoW_CoO.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7147763/GoW_CoO.ppdmp.zip)

**Comment by Gamemulatorer** [comment] 2022-07-11 13:03
@Marosis try to enable GoWframeratehack30fps in compat.ini for this game.

**Comment by Gamemulatorer** [comment] 2022-09-02 14:24
https://user-images.githubusercontent.com/37603562/188169968-6495027a-7476-4736-ae3e-b18acf3a0859.mp4

Looks optimize now on opengl backend.

**Comment by hrydgard** [comment] 2022-09-02 14:29
Yeah, I think I'm just gonna close this. The game runs well, and not worse than it has before anymore, as far as I can tell.

**Closed by hrydgard** 2022-09-02 14:29 UTC
Labels: OpenGL
