### ISSUE TITLE
Invizimals: Shadow Zone Bugged Capture

### ISSUE THREAD

**Issue by Maglor-El-Mago** [hrydgard/ppsspp#14118] opened 2021-02-11 16:55 UTC
<!-- Want the issue fixed faster?  Check the wiki for tips:
https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue

I'm not sure if this issue has already been reported but I will do it anyway
### What happens?

The capture of the Invizimal Draco is bugged 

### What *should* happen?

The quartz should break with the laser but it doesn't

**Comment by hrydgard** [comment] 2021-02-11 17:38
Please add some more information. Early in the game? What do you need to do to trigger the error?

**Comment by Maglor-El-Mago** [comment] 2021-02-12 17:07
Well, that bug happens in the early game, when you have to capture the 3 first Invizimals, the bug is something strange because if you can’t break the quartz you can’t progress in the game, I mean, you have a laser and the laser must to break the quartz that covers Draco but in the emulator doesn’t happens, you can spam the laser but the laser will not break the quartz. I I don't think this is a hardware error because I know that there are people who have had this bug (by the way, this bug exists  since version 1.9.3 of the emulator, if I'm not mistaken)

**Comment by unknownbrackets** [comment] 2021-03-28 21:51
Closing this as a duplicate of #14309, which although newer has a lot more information.  I'll paste the comment over there too.

-[Unknown]

**Closed by unknownbrackets** 2021-03-28 21:51 UTC
