### ISSUE TITLE
Game: Silent hill: Shattered Memories

### ISSUE THREAD

**Issue by Chomuske** [hrydgard/ppsspp#11284] opened 2018-08-05 11:54 UTC
### What happens?

◽️ I tried playing Silent hill: Shattered memories and the flashlight isn't working, I can see the light reflection on doors and other objects I can interact with, but everything else is dark(not black), it works while opening doors(only time when it's working) with disable slower effects disabled. I tried the disable stencil test but it's not working. I can see the doors and other objects I can interact with through the walls when I turn on the flashlight.The game is running almost smoothly tho. 

### What *should* happen?
I think I should be able to see the light from the flashlight on other objects that cannot be interacted. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I'm using: - 
◽️ Android 6.0.1 MMB29M
◽️ Redmi note 3, 3gb ram & 32gb internal storage 
◽️ PPSSPP 1.6.3
◽️ Rendering backend used: openGl            

Is there anything I can do? The stencil effect one doesn't work, even with disabling the disable slower effects.

**Comment by 1234Sameer** [comment] 2018-08-05 12:24
Duplicate of #6265

**Comment by LunaMoo** [comment] 2018-08-05 22:15
Closing as a duplicate as noted above.

**Closed by LunaMoo** 2018-08-05 22:15 UTC
