### ISSUE TITLE
Crisis core

### ISSUE THREAD

**Issue by shae23** [hrydgard/ppsspp#7412] opened 2015-02-02 18:28 UTC
after starting a new game the opening video does not play and the game cannot be started

**Comment by Bigpet** [comment] 2015-02-02 18:35
duplicate of #7095 ?

**Comment by shae23** [comment] 2015-02-02 19:03
Yes

**Comment by shae23** [comment] 2015-02-02 19:04
Only happens on iOS though works perfectly on android

**Comment by unknownbrackets** [comment] 2015-02-02 19:58
We don't really need multiple issues for iOS being broken.  It won't make it get fixed faster, it'll just make anyone who might be able to fix iOS issues waste more time looking at issues instead of fixing it.

-[Unknown]

**Closed by unknownbrackets** 2015-02-02 19:58 UTC
