### ISSUE TITLE
Cant save state on ios

### ISSUE THREAD

**Issue by Bananarain** [hrydgard/ppsspp#14524] opened 2021-06-11 16:15 UTC
When I try to save state, it always says failed to dave state.

It should save state

Im  on an iPhone 8, ios 14.6

it has not worked before, and I'm using the one I downloaded from ppsspp.org

all games don't save

please help

**Comment by Panderner** [comment] 2021-06-12 10:39
@Bananarain what PPSSPP version are you using?

**Comment by unknownbrackets** [comment] 2021-06-13 04:20
Sometimes on iOS there are permission issues with data.  Does this happen even with games you've not created a save state in before?  Or only when trying to overwrite an existing save state?

-[Unknown]

**Comment by metehan989** [comment] 2021-06-19 05:03
Download the latest ppsspp IPA. I just did and saving works now.

**Comment by Bananarain** [comment] 2021-06-19 15:58
how do i download the latest ipa?

**Comment by metehan989** [comment] 2021-06-20 07:38
Here is the link: https://p.xx.wtf
(i know its a weird url but its the buildbot for ios versions)

**Comment by unknownbrackets** [comment] 2021-07-18 02:14
Did that help?

-[Unknown]

**Comment by metehan989** [comment] 2021-07-21 12:27
Yeah the problem is fixed with the latest builds.

**Closed** 2021-07-21 14:36 UTC
Labels: I/O, No Feedback / Outdated?, Platform-specific (iOS)
