### ISSUE TITLE
[Windows] Ignore "Render Duplicate Frames to 60 Hz" when unthrottling

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#12975] opened 2020-05-25 10:31 UTC
On Windows (and maybe Linux too), you should ignore the Render Duplicate Frames to 60 Hz setting when unthrottling, otherwise unthrottle doesn't work.

**Comment by unknownbrackets** [comment] 2020-05-25 13:58
It already does this, although only when you've enabled vsync in PPSSPP settings.  What backend are you using where this doesn't work?

-[Unknown]

**Comment by leopard20** [comment] 2020-05-26 02:54
Latest git build, Vulkan backend, using PPSSPP's vsync option.

It was weird though, it was as if the emulator was skipping frames when I unthrottled. The audio was playing normally.

P.S: When I turn on Vsync from the Nvidia Control Panel, unthrottle simply has no effect at all. I'm not sure if you can fix this case though.

**Comment by leopard20** [comment] 2020-05-26 03:06
Another question: can you add an option to bring the "Android-style" frameskipping to Windows? (if not too much work and worth the effort, of course)

**Comment by unknownbrackets** [comment] 2020-05-26 03:11
Hm.  Maybe we should just recreate the swapchain (like when you resize the window) when toggling unthrottle if vsync is on.  That may give better results and be more consistent across drivers.

There's an ini setting for unthrottle to frameskip - although I plan to change it in #12970.

-[Unknown]

**Comment by leopard20** [comment] 2020-05-26 13:59
> It was weird though, it was as if the emulator was skipping frames when I unthrottled. The audio was playing normally.

My apologies. It seems like I was mistaken. The culprit for this was the **Render Duplicate Frames to 60 Hz** option, not vsync.

I'd also like to report another problem which is probably related to frame pacing. 
In every game I tested, I get a sudden lag every few seconds (like 10~15 s). However, the FPS counter showed the game was running at full speed; in fact, I noticed that my framerate was even higher that the maximum (e.g getting 61/60 101%), which makes me think it is related to frame pacing. Turning on vsync can alleviate the lag (vsync off: ~ 1s lag; vsync on: a few ms lag). 
Using the Nvidia Control Panel vsync almost completely fixes the problem.
I was wondering if changing the vsync frequency to 59.94 instead of 60 (on a 60Hz monitor) could help?

**Comment by hrydgard** [comment] 2020-05-26 14:47
We try to actually run the timing using the display and instead adjust the audio frequency to match so that should already be happening. That said, we also control game speed using the clock and it might be that it's a little too strict. There's definitely work to be done in this area.

**Comment by Anuskuss** [comment] 2020-06-28 01:48
Can confirm. Fast forwarding Vulkan+Vsync+DupeFrames does halve the frame rate instead of unthrottling it. I do hate how Dolphin flickers when fast forwarding Vulkan+Vsync so it would like to keep the current behaviour but just deactivate duplicate frames temporarily.

**Comment by Anuskuss** [comment] 2020-07-14 23:19
Can you guys replace `g_Config.bFrameSkipUnthrottle` here https://github.com/hrydgard/ppsspp/blob/f1e5dd2449b87c0f97c14ab9606a259c4c5a6f0c/Core/HLE/sceDisplay.cpp#L762-L768 with `unthrottleNeedsSkip` from here
https://github.com/hrydgard/ppsspp/blob/f1e5dd2449b87c0f97c14ab9606a259c4c5a6f0c/Core/HLE/sceDisplay.cpp#L564-L567 to make it work in Vulkan+Vsync+DuplicateFrames?

**Comment by hrydgard** [comment] 2020-07-16 18:18
@Anuskuss  Looking at it, I've decided that I want to fix it properly instead and allow Vulkan to change vsync mode as you throttle/unthrottle, so we can remove the hack. It's not that hard to do actually (just gotta be careful and not destroy the whole surface, just recreate the swapchain ... it's a little involved).

**Comment by Anuskuss** [comment] 2020-07-16 19:49
@hrydgard That will make it flicker (like Dolphin) right? Probably should be configurable like #12970.

**Comment by hrydgard** [comment] 2020-07-16 20:26
Ideally it shouldn't flicker if implemented correctly. I know early VK drivers had trouble with this though, don't know if it's still an issue.

**Comment by hrydgard** [comment] 2020-07-18 20:48
Decided to try your fix in the meantime, included it in #13164 . After that's merged, let me know if it works.

**Comment by Anuskuss** [comment] 2020-07-18 23:22
Yep, it works. One tiny difference between Vsync off and on is that it shows 60/30 when untrottling instead of an useful value (count the skipped frames?) but that's by design right? You can see the performance in percent right next to FPS and one could argue that you shouldn't use Vsync for bechmarking anyway so it'd say it's not worth it to "fix" that.

**Comment by unknownbrackets** [comment] 2020-07-18 23:32
The 60/30 is correct in that it is drawing 60 frames per second, and skipping the others.  The FPS and speed indicators measure different things.

When you see 300/30 it means 300 frames rendered per second, which does also mean 1000%.

But when you see 1000% it just means speed is keeping up with real time, more or less, but could be 15/30, 30/30, 60/30, etc.

-[Unknown]

**Comment by Anuskuss** [comment] 2021-02-08 04:18
This can be closed, right?

**Closed** 2021-02-08 08:06 UTC
