### ISSUE TITLE
[Windows][Stuck/Freeze] UNO (NPJH00016) is stuck at card distributing.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13481] opened 2020-09-25 16:33 UTC
### What happens?
Game is stuck at play screen.
Game is not start.
Because, Card is not distributed.
Sound is playing but any work stop.
I find a red code on the Log.
Please see attached screenshot.

Log.txt here.

[UNO_NPJH00016_Log.zip](https://github.com/hrydgard/ppsspp/files/5284046/UNO_NPJH00016_Log.zip)

### What *should* happen?
Don't stop.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver.：1.10.3-769
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

![UNO_Log_redcode_01](https://user-images.githubusercontent.com/48179091/94292032-5f2ab380-ff97-11ea-9e9a-fc1766215800.png)

**Comment by Panderner** [comment] 2020-09-25 16:34
Duplicate of #9035

**Closed by Panderner** 2020-09-25 16:34 UTC
