### ISSUE TITLE
Black/Dark shades on Naruto UNH3

### ISSUE THREAD

**Issue by cheding09** [hrydgard/ppsspp#11585] opened 2018-11-25 01:54 UTC
### What happens?
Black/Dark Shades on Latest build

![screenshot_201811329-094033](https://user-images.githubusercontent.com/39876882/48974533-ef93c680-f096-11e8-92c3-c7cc891867f2.JPEG)
![screenshot_201811329-093948](https://user-images.githubusercontent.com/39876882/48974573-e3f4cf80-f097-11e8-87fa-17ccba75e5f1.JPEG)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

this happens on latest build 1.7.186,190 & 195 . this did not happen on 1.7.182

Android 5.1
OpenGL ES 2.0
Mali 450 Mediatek
1.3ghz
Armv7

**Comment by Emulatorer** [comment] 2018-11-25 03:09
I'm currently experiencing the same issue as ee have the same specs of phone 😅
[Black Shade Background In The Hachibi]
![screenshot_2018-11-25-10-57-45](https://user-images.githubusercontent.com/37603562/48974997-c3f4ea00-f05e-11e8-841c-b29b7557ed2e.png)

But Im Find A solution :) just enable 4X MSAA in the developers option of your android phone fixe the issu 👍
[With 4X MSAA Enable Skipp-Buffered]
![screenshot_2018-11-25-10-58-24](https://user-images.githubusercontent.com/37603562/48975037-76c54800-f05f-11e8-855c-e743008aba03.png)

**Comment by Emulatorer** [comment] 2018-11-29 12:43
[Naruto-UNH3.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/2629106/Naruto-UNH3.ppdmp.zip)

We have same specs :)

**Comment by unknownbrackets** [comment] 2018-11-29 20:55
Are you sure that reproduces the issue?  I don't really see any flat shading in use there.

GLES, latest:
![gles actual - now](https://user-images.githubusercontent.com/191233/49251216-ca27f500-f3d5-11e8-9772-d6e17009eaad.png)

GLES - v1.7.1-182-g3d20ddecc:
![gles v1 7 1-182-g3d20ddecc](https://user-images.githubusercontent.com/191233/49251217-ceeca900-f3d5-11e8-8419-0814fad079f6.png)

PSP:
![ulus10518_ 11585_naruto_shading](https://user-images.githubusercontent.com/191233/49251234-d7dd7a80-f3d5-11e8-9012-5234f8c64ac0.png)

The background is incorrectly too bright, although it could just be bitdepth.  But it's unchanged since v1.7.1-182-g3d20ddecc.

-[Unknown]

**Comment by Emulatorer** [comment] 2018-11-29 23:13
Yeah I didn't notice any flat shading
I just wanted to help him/her 😅
### Screenshot
![screenshot_2018-11-30-06-52-25](https://user-images.githubusercontent.com/37603562/49258111-3af9fc00-f42c-11e8-973a-cd22c9354ded.png)
ppsspp v1.7.1-210 git build

**Comment by Emulatorer** [comment] 2018-12-01 12:43
@cheding09 are you using default settings and the rom you use is iso format not cso?
because I didn't experience what are saying about black/dark shading :/

**Comment by cheding09** [comment] 2018-12-04 00:16
Oh . Im very sorry for the late reply . This issue is fix on latest build 1.7.1-210 and up it only happens on builds 1.7.1-186,1.7.1-190 & 1.7.1-195 . Thanks for the hardwork👍

**Comment by unknownbrackets** [comment] 2018-12-04 01:30
Glad to hear.  Probably was related to #11172 and fixed by the culling fixes.

-[Unknown]

**Closed by unknownbrackets** 2018-12-04 01:30 UTC
