### ISSUE TITLE
Chat not closing

### ISSUE THREAD

**Issue by boy13epic** [hrydgard/ppsspp#14277] opened 2021-03-10 15:32 UTC
### What happens?
chat does not close

### What *should* happen?
Chat closes

### Please test newest version in https://buildbot.orphis.net/ppsspp/
iPad on iOS 13.3.1,using vulkan and 1.11.2-301

**Comment by ANR2ME** [comment] 2021-03-10 16:04
A duplicate of https://github.com/hrydgard/ppsspp/issues/14268 ?
May be related to this comment https://github.com/hrydgard/ppsspp/issues/14240#issuecomment-788709409 ?

**Comment by unknownbrackets** [comment] 2021-03-12 06:48
This is definitely a duplicate of one or both of the above, so closing.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-03-12 06:48 UTC
