### ISSUE TITLE
(Android 12) Monster Hunter 3rd HD  cannot savedata sometimes corrupt data

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14757] opened 2021-08-23 16:16 UTC
### Game or games this happens in
NPJB40001 MH3RD HD
![Screenshot_2021-08-24-00-05-13-641_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130480689-4e8ec201-6fc1-4eeb-af16-45460d025c97.jpg)
### What area of the game / PPSSPP
PPSSPP latest build always show this
![Screenshot_2021-08-23-23-55-38-015_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130480630-294bfa4f-3fbe-4c49-9b9b-715a609018b6.jpg)
![Screenshot_2021-08-23-23-55-42-382_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130480643-79026115-fc3d-4960-81b0-c164986cce68.jpg)
[ppsspp_latest_build.mp4.zip](https://github.com/hrydgard/ppsspp/files/7033366/ppsspp_latest_build.mp4.zip)

### What should happen

This should be like this no savedata corrupt warning because I don't have a savedata 😅
[ppsspp_v1.11.3_clone.mp4.zip](https://github.com/hrydgard/ppsspp/files/7033371/ppsspp_v1.11.3_clone.mp4.zip)

Im using the psp rocket because it's the clone of the ppsspp v1.11.3 also doesn't ruin my ppsspp settings on external storage.
Maybe this issue is related to scoop storage?🤔

### Logs

[logcat_08-24-2021_00-14-43.txt](https://github.com/hrydgard/ppsspp/files/7033398/logcat_08-24-2021_00-14-43.txt)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 11

### PPSSPP version affected

v1.11.3-1184

### Last working version

1.11.3 stable

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2021-08-23 16:59
Strange, not seeing anything more interesting than this in the log....

```
java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/SAVEDATA/ULJM05800/ICON0.PNG is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/SAVEDATA/ULJM05800/ICON0.PNG at /storage/3136-6161/PSP/SAVEDATA/ULJM05800/ICON0.PNG
```

which is normal, I think, for a file existence check...

**Comment by Gamemulatorer** [comment] 2021-08-24 00:14
> If you actually do save, does that work?

No I can't save after character creation :(
![Screenshot_2021-08-24-08-13-18-427_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130535439-33b25fa7-051b-4987-80f3-f1e951e66c9a.jpg)

**Comment by unknownbrackets** [comment] 2021-08-24 01:48
That's the error code returned if the PARAM.SFO file doesn't exist during load.

Could there be some asynchronous thing happening here?  Like Android_CreateFile doesn't create a file that exists, immediately?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-08-24 04:27
When I deleted the corrupted data even though I don't have this will show.
![Screenshot_2021-08-24-12-01-30-490_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130555715-6d292841-2a4f-40ff-8d69-a9c3d7250878.jpg)
![Screenshot_2021-08-24-12-25-39-450_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/130555725-8936cef8-98d7-45e4-81bd-8f6cac24ce68.jpg)

[logcat_08-24-2021_12-26-08.txt](https://github.com/hrydgard/ppsspp/files/7036432/logcat_08-24-2021_12-26-08.txt)

**Comment by ANR2ME** [comment] 2021-08-24 08:25
Not sure whether this is related or not, because i'm also surprised when i saw the same error code on InviZimals Shadow Zone
I'm getting the same error code when loading my old savedata
![image](https://user-images.githubusercontent.com/7974720/130583080-51b29a91-d4d5-4994-91d1-346d5ccfa079.png)
That error code seems to shows up too when the save wasn't saved from the same PSP (ie. different MAC address)
![image](https://user-images.githubusercontent.com/7974720/130583129-0540abef-d839-470a-ac88-1eb34c471bf2.png)

**Comment by Gamemulatorer** [comment] 2021-09-12 14:44
Try this again on the latest git build and deleted the folder ULJM05800 but I cannot reproduce this issue anymore 🤔

**Comment by unknownbrackets** [comment] 2021-09-12 14:47
I've had weird issues with scoped storage where, even after granting access to a folder, some files in it weren't accessible by PPSSPP.

The steps I went through were:
 * Uninstall PPSSPP
 * Install it again
 * Grant it access to my PSP folder in the splash screen
 * Saving worked, etc. but I couldn't see some game files inside the PSP folder
 * Browsed to PSP from the games section
 * Suddenly I could see those files now

I wonder if something similar happened here, where the old folder didn't give permission to PPSSPP to interact with all its save files...

-[Unknown]

**Comment by hrydgard** [comment] 2021-09-12 18:16
Weird :(. Maybe the workaround in such cases is to simply pick the same folder again, from the memstick settings dialog.

I think we're gonna have to chalk this one up to Android flakiness then, I'm at least gonna untag 1.12.

**Comment by Gamemulatorer** [comment] 2022-08-04 10:53
Cannot save again :(
![Screenshot_2022-08-04-18-38-40-828_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/182830030-ba7391f6-5237-4e35-b09f-9c14781d6115.jpg)

**Comment by hrydgard** [comment] 2022-08-04 11:18
Did it work in some version before?

**Comment by hrydgard** [comment] 2022-08-04 18:34
Yeah, save states clashing with savegames is an issue with a few games unfortunately :(

**Comment by LunaMoo** [comment] 2022-08-04 21:38
Isn't it now just a duplicate of #7244?
Also didn't #14434 do it's thing(show a warning)?

It would be pretty bad to lock out savestates for a problem that's easily hackable, unless providing option to disable it.

**Comment by ANR2ME** [comment] 2022-08-05 04:17
> Isn't it now just a duplicate of #7244? Also didn't #14434 do it's thing(show a warning)?
> 
> It would be pretty bad to lock out savestates for a problem that's easily hackable, unless providing option to disable it.

But based on the screenshot at https://github.com/hrydgard/ppsspp/issues/14757#issuecomment-904313629
MH game showing save data from Yu-gi-oh game, are games supposed to have access to other games' save data like that?

**Closed** 2022-08-05 05:03 UTC
Labels: Saving issue, I/O

**Comment by PedroMHp3** [comment] 2023-01-05 12:33
Eu estou com um problema diferente, eu não consigo iniciar as missões urgentes, aparece esse erro...

![IMG-20230104-WA0018](https://user-images.githubusercontent.com/122025422/210781112-e38c0f50-78ce-4a39-80d8-e312e823ef56.jpg)

**Comment by PedroMHp3** [comment] 2023-01-05 12:34
Queria a ajudar não estou conseguindo avançar no jogo
