### ISSUE TITLE
OutRun2006 Coast 2 Coast - Some textures are weird and gameplay is choppy

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12867] opened 2020-05-01 05:00 UTC
### What happens?
Game has wrong textures,for example on first area beach is white no matter what,water is reflected wrong,also game is really unplayable

### What *should* happen?
Game should display normal textures

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Phone:Xiaomi Redmi6
GPU:PowerVR Rogue GE8320
CPU:Mediatek Helio P22
Backend:OpenGL

PC Specs
GPU:Intel (HD) Graphics
CPU:Intel Pentium Quad-Core N3520
Backend:DirectX

Note:i used buffered rendering

**Comment by Panderner** [comment] 2020-05-01 08:36
It's a duplicate of #11928. Software renderer to display the water correctly but Software rendering is super slow on all Android Devices even a Flagship Snapdragon Chipset.

**Comment by HiImBrala** [comment] 2020-05-01 10:18
> It's a duplicate of #11928. Software renderer to display the water correctly but Software rendering is super slow on all Android Devices even a Flagship Snapdragon Chipset.

If i understand good,it is not problem of my PC but EMU?

**Comment by hrydgard** [comment] 2020-05-01 12:15
Correct, it's a bug (or missing functionality) in the emulator.

**Closed by hrydgard** 2020-05-01 12:15 UTC
