### ISSUE TITLE
Game crashed Blue Screen

### ISSUE THREAD

**Issue by jaum20** [hrydgard/ppsspp#17542] opened 2023-06-01 23:07 UTC
### Game or games this happens in

UCES01401 1.00 Ghost of Sparta

### What area of the game / PPSSPP

As soon as I push L in this part:
https://i.imgur.com/lgiPDKm.png

Using opengl it do not crash

### What should happen

Blue screen crash:

https://i.imgur.com/18JckOB.png

### Platform

Linux / BSD

### Mobile phone model or graphics card

Intel HD GRaphics 5500

### PPSSPP version affected

V1.15.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment] 2023-06-02 01:26
Closing as a duplicate of #14958

**Closed by LunaMoo** 2023-06-02 01:26 UTC
