### ISSUE TITLE
Mouse as Analog Stick

### ISSUE THREAD

**Issue by jdcrux** [hrydgard/ppsspp#11263] opened 2018-07-23 07:50 UTC
Pretty much self-explainable...

**Comment by LunaMoo** [comment] 2018-07-23 13:11
Closing as a duplicate of #4650 also this was partially completed - mouse control is supported on windows systems.

**Closed by LunaMoo** 2018-07-23 13:11 UTC

**Comment by jdcrux** [comment] 2018-07-28 13:39
I didn't thought it was a duplicate, tried searching for this but haven't found anything... thanks btw.
