### ISSUE TITLE
Problems with the computer mouse in PPSSPP or help, please teapot (the man who little understood in this emulator)!

### ISSUE THREAD

**Issue by JoRaD-TM** [hrydgard/ppsspp#8499] opened 2016-01-24 13:52 UTC
To properly play through the emulator need a gamepad (I have it), but I'm not used to playing with a gamepad. Since my childhood I played with a keyboard and a computer mouse. And it turned out that I can not properly use the mouse to play, because it works just right click (aiming in shooters), and the left and the other - no. I poked around a bit in the internet and found the following: "Mouse buttons could not be used on controls because emulator use them for navigating under menus."

So I can properly navigating under menus without a mouse, how can I get around this limitation cursed? That is how to remove almost all of the mouse from the blacklist. I would also like to tie the mouse movement on all axes as the movement of the camera in the game. 

I really want to play normally in Call of Duty Road to Victory (exclusive on PSP)
P.S. Sorry for bad English.

**Comment by JoRaD-TM** [comment] 2016-01-24 13:57
And another question: where i can take a table of all the buttons?
For example: 2-1003 is in the emulator Mouse.MB2

**Comment by unknownbrackets** [comment] 2016-01-24 16:23
Someone else has already requested mouse input.  Personally, I don't think it will work out well because PSP games were not designed for mouse input (especially the limited number of buttons.)  Anyway, closing as duplicate of #4650.

-[Unknown]

**Closed by unknownbrackets** 2016-01-24 16:23 UTC
