### ISSUE TITLE
Huge fps slowdown after 0.9.9.1-54 (Android)

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#7336] opened 2015-01-16 16:39 UTC
Since official ppsspp 0.9.9.1 was working great, it's been a "long" time that I didn't try another build, so when I installed 0.9.9.1-1498 on my Android tablet device (Asus ME173X - quad core 1.2 - PowerVR SGX 544MP) I was almost "shocked" to see that the emulator had become so slow.
Where it was at 30 fps with 9.9.1, now using 9.9.1-1498 is at around 25 fps (almost 20% speed loss)...so I began to track down what revision caused this problem and found out that 0.9.9.1-54 is the last available build with the great "old" speed, while starting with 9.9.1-65  begins (my?) Android slowness problems (Windows 8.1 64bit version doesn't seem to be affected)

So one of these commits should be responsible for this problem (unfortunately there are no builds about them to test):

0.9.9.1-55: https://github.com/hrydgard/ppsspp/commit/808f05da8978fc2fa2ea046c43a7a1be433f98d4

0.9.9.1-56: https://github.com/hrydgard/ppsspp/commit/92c3775d95d8c10fedac77817c6f00182252d49e

0.9.9.1-57: https://github.com/hrydgard/ppsspp/commit/e539c7009f6f63385572b30587cb72ea647000de

0.9.9.1-58: https://github.com/hrydgard/ppsspp/commit/e2ecbb7a4ddab2c83fe9d6ca3552d5944a36e6e9

0.9.9.1-59: https://github.com/hrydgard/ppsspp/commit/00d5793f7dacc22bfd46238ac98f2d86b00e8f8b

0.9.9.1-60: https://github.com/hrydgard/ppsspp/commit/a758917919179b6bf8e0297197d36f759787246e

0.9.9.1-61: https://github.com/hrydgard/ppsspp/commit/155623482503ed03065b97a958b92aa07ebfd77b

0.9.9.1-62: https://github.com/hrydgard/ppsspp/commit/0f973a327604a2b55db4908b9f7354a5576cedf7

0.9.9.1-63: https://github.com/hrydgard/ppsspp/commit/0bed77ed0da4d9aa1973922f2e75fd7170575c67
https://github.com/hrydgard/ppsspp/commit/7f4758baae87f1b67449a5824fb675a1fe9c58b9

0.9.9.1-64: https://github.com/hrydgard/ppsspp/commit/4231af2c0f70b21bb346f3430c20b006abc9af47

0.9.9.1-65: https://github.com/hrydgard/ppsspp/commit/2faf15f2e698366e3f0341aa58702d99a2f7a2de

**Comment by brujo5** [comment] 2015-01-16 17:06
some commit are specific for windows.Not think it affects android

**Comment by Bigpet** [comment] 2015-01-16 17:07
Well there is an additional level of indirection with the thin3d abstraction in some cases. So it may blow the icache under some conditions.

What are the games that you tried?

**Comment by psennermann** [comment] 2015-01-16 17:26
3rd birthday,Obscure: the Aftermath, Gods Eater Burst, Crisis Core Final Fantasy...

**Comment by hrydgard** [comment] 2015-01-16 17:40
thin3d should only really affect the UI, it's barely used at all during gameplay except for things like the FPS counter etc.

**Comment by Bigpet** [comment] 2015-01-16 18:09
Just tested both versions (54 and 65) on a Nexus 4 and couldn't reproduce, so it's definitely not something across all Android devices.

**Comment by unknownbrackets** [comment] 2015-01-16 18:37
Well, the clearing thing on PowerVR doesn't sound crazy at all to me.  Would also explain why it wasn't caught earlier.

-[Unknown]

**Comment by ThePhoenixRises** [comment] 2015-01-17 06:19
Wouldn't Clearing the frame at the beginning slow PowerVR down further as its another option for the device to have to cope with?
Disabling Alpha channel is supposed to help speed things up, as its cutting out GPU intensive routines, was that option available back then -  0.9.9.1-65: 2faf15f

**Comment by psennermann** [comment] 2015-01-25 22:49
So I suppose there's no easy fix for this...

**Comment by hrydgard** [comment] 2015-01-25 22:52
There might be. I'm gonna make an experimental commit, hang on..

**Comment by hrydgard** [comment] 2015-01-25 23:27
Argh, did not mean to auto-close this... github triggered on "trying to fix" heh

**Comment by psennermann** [comment] 2015-01-26 17:28
Just tried 0.9.9.1-1603 with 3rd Birthday, but unfortunately it is still much slower than 0.9.9.1-54...

**Comment by psennermann** [comment] 2015-01-26 18:17
Maybe it's just an impression, but for example in 3rd birthday the major slowdown seems to be due to the fog: I mean when the winds blows some more fog (when it gets thicker) the game suffers a lot (that didn't happen until revisions after 0.9.9.1-54)...I think that now the slowdown is noticeable because the global speed has dropped, or maybe is the fog itself...I really don't know

**Comment by hrydgard** [comment] 2015-01-26 19:44
There's no such thing as "global speed", we have to be doing something differently enough to trigger some bad behaviour in gpu drivers, or something... I'm puzzled.

**Comment by unknownbrackets** [comment] 2015-03-12 22:14
@hrydgard I get a lot of these logs on my phone (Adreno):

<core_glInvalidateFramebuffer:682>: GL_INVALID_ENUM

I noticed the code was as follows:
```c++
GLenum attachments[3] = { GL_DEPTH, GL_STENCIL };
glInvalidateFramebuffer(GL_FRAMEBUFFER, 3, attachments);
```

I notice that it says `3` but it also specifies only 2 values.  Clearly the 3rd value, a 0, is causing GL_INVALID_ENUM.  Could this be related, perhaps?

i wonder if we would win anything by invalidating temp FBOs (depal, block transfers, render-to-self) after using them....

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-12-19 22:14
Has this changed at all?  I know we fixed the API usage per my comment above.

-[Unknown]

**Comment by psennermann** [comment] 2015-12-20 11:04
Tried 1.1.1-370 and unfortunately it's still much slower than 0.9.9.1-54...

**Comment by leopard20** [comment] 2018-06-10 10:56
@hrydgard @unknownbrackets 
Doesn't matter anymore. Those builds are too old anyway. Plus now that OGL is multi threaded all games should be fine! :)

**Comment by unknownbrackets** [comment] 2018-06-10 13:46
I think it's very likely we've gotten performance back up to better than before, although it would've been nice to solve the mystery of what impacted performance here.

Please comment/reopen/create a new issue if performance is still impacted.

-[Unknown]

**Closed by unknownbrackets** 2018-06-10 13:46 UTC
Labels: Platform-specific (Android)
