### ISSUE TITLE
Only One XInput Controller is detected

### ISSUE THREAD

**Issue by TehMadHelm** [hrydgard/ppsspp#8426] opened 2016-01-14 22:33 UTC
The controller detected as being in the first slot is detected just fine. No keypresses on controllers in the second, third, and fourth slot are detected.

I use the following:
Dualshock 3 Wireless Controller with Scptool (spoofing as an xbox 360 controller). Plugged into first slot.
Xbox 360 Wired USB Controller. Plugged into second slot. No keypresses on this controller are detected by PPSSPP, but antimicro and other games respond fine with both controllers.

**Comment by unknownbrackets** [comment] 2016-01-15 00:23
Closing as a duplicate of #8250.

-[Unknown]

**Closed by unknownbrackets** 2016-01-15 00:23 UTC
