### ISSUE TITLE
(Android) Silent Hill Shattered Memories issues with "simulate block transfer effects"

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10189] opened 2017-11-25 00:01 UTC
I get massive FPS drop (from 60 to 20) by checking the mentioned option. 
If I don't, then the FMV cutscenes can't be displayed correctly (just a white screen is shown). There are other problems as well (if I don't check the option), such as not being able to see the check marks on the "evaluation" form (after the cutscene) and minor lighting issues (I think they were previously mentioned for the PC version with DirectX 11)

**Comment by hrydgard** [comment] 2017-11-27 12:51
Unchecking the option can cause all sorts of bad effects, and that's to be expected since we're skipping things the game wants to do. In some games it does speed things up without bad side effects, in some games it breaks them. We might be able to improve the performance of some of the block transfer effects in the future, but it's not a bug that it's slow, so I'm closing.

**Closed by hrydgard** 2017-11-27 12:51 UTC
