### ISSUE TITLE
The 3rd birthday washed out image (Galaxy Tab S2)

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#9800] opened 2017-06-16 18:55 UTC
I've just bought a Samsung Galaxy tab S2 for having a better performing tablet and was also very sad to notice that in-game image in 3rd birthday is somewhat washed out (like when you set full brightness on a monitor); in fact there are no real blacks like with the old tablet (Asus Memo Pad HD7) or PC: with Galaxy Tab S2 in this game black is in fact a bright semi-dark blue.
Also notice that menus and intro-movie images are perfect and other games don't seem to be affected by this "overbright-blu color" problem (although I haven't had enought time to test so many).
(ppsspp 1.4.2)

**Comment by psennermann** [comment] 2017-06-16 19:38
![screenshot_20170616-213338](https://user-images.githubusercontent.com/6342467/27242087-d0c05476-52db-11e7-900c-386c234f552d.png)

Here you can see the washed out imege, although the grabbed screenshot file shows more a yellow tending image while real tablet output is more on the blue side...

**Comment by psennermann** [comment] 2017-06-16 19:44
Tablet model is Samsung Galaxy Tab S2 (T719N - 8.0'') - GPU Adreno 510 -  Android 7.0

**Comment by unknownbrackets** [comment] 2017-06-16 19:50
Looks like a duplicate of #6526.

-[Unknown]

**Comment by psennermann** [comment] 2017-06-16 19:52
I found out that enabling "Disable slower effects" fixes the problem

**Comment by psennermann** [comment] 2017-06-16 20:00
In fact in this game, "slower effect" on Galaxy Tab S2 (Adreno 510) put something like a white-blue filter on the image, while powerVR 544 seems ok (tested on Asus Mem PAd HD7 and the image doesn't get washed out)

**Comment by unknownbrackets** [comment] 2017-06-16 21:03
Okay, well, it sounds like it's a duplicate - the behavior is the same.  Closing.

I seem to remember this game requires dual source blending (not supported by all mobile GPUs / drivers.)

-[Unknown]

**Closed by unknownbrackets** 2017-06-16 21:03 UTC
