### ISSUE TITLE
[Feature Request] Auto-Frameskip: Use Frameskip only if FPS is lower than a set number

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#11372] opened 2018-09-09 01:09 UTC
The current issue I'm having with auto frameskip is that as soon as the emulation speed falls below 100%, frameskip is applied even though it may not be necessary. This leads to less than satisfactory game speed 90% of the time. 
However, if frameskip was applied when the emualtion speed is below, say, 80% (i.e. 48 FPS for a game that runs at 60 FPS) it would be a lot better. Not sure if it's possible though!

**Comment by marosis** [comment] 2018-09-26 09:29
With #8717 it would be really useable combination

**Comment by unknownbrackets** [comment] 2021-08-14 04:04
Although this is older, there's more notes in #14315 (including the technical challenge), so I'm going to close this as a duplicate of that.

-[Unknown]

**Closed by unknownbrackets** 2021-08-14 04:04 UTC
Labels: Feature Request
