### ISSUE TITLE
More Skin pad in ppsspp 

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12259] opened 2019-08-20 06:46 UTC
### What happens?
Needs more skin pad 

### What *should* happen?
Need more skin pad

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
1.80 beta

**Comment by hrydgard** [comment] 2019-08-20 07:20
skin pad? you mean different looks for the on-screen controls? That's https://github.com/hrydgard/ppsspp/issues/5624 (kind of)

**Comment by unknownbrackets** [comment] 2019-08-20 14:08
This issue is being closed as a duplicate of #5624.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-08-20 14:08 UTC
