### ISSUE TITLE
ppsspp ios 9.3.3 jailbroken

### ISSUE THREAD

**Issue by zakusa** [hrydgard/ppsspp#8927] opened 2016-08-22 05:54 UTC
Ya ok I have iPad Air 2 and iOS 9.3.3 jailbreak and i tried all the ppsspp versions the latest one the dev working one and the old version one. The old version one wouldn't open. The latest one opens games but ya it's laggy even on lowest settings ( I had iOS 8.3 before and it was constant 60 fps with my games ) so ya anyone knows how to fix the lag on it

**Comment by unknownbrackets** [comment] 2016-08-22 06:32
This issue is being closed as a duplicate of #8122.

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2016-08-22 06:32 UTC

**Comment by zakusa** [comment] 2016-08-22 22:27
thank you i didnt know there was a thread on this and sorry i made another one i didnt know before
