### ISSUE TITLE
Regression : FMV cutscene stutter and perfomance are worse than older version

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9262] opened 2017-01-31 13:45 UTC
I have a tablet using Mali and PowerVR , both tablet I'm tested in newer build and it doesn't fixed , perfomance ingame and FMV cutscene are worse than older version , these picture below are same setting config
Game tested : Patapon 3 , Star Ocean , P3P , The 3rd Birthday

In 1.3.0.1 and newer build , is stutter and worse perfomance
![2017_1_31_8_15_7_126_pm](https://cloud.githubusercontent.com/assets/11285640/22467118/f2156f90-e7f5-11e6-80fd-d2b03cb7dc51.png)
![2017_1_31_8_17_15_686_pm](https://cloud.githubusercontent.com/assets/11285640/22467119/f23b949a-e7f5-11e6-8693-fb022655cd7f.png)
![2017_1_31_8_18_4_644_pm](https://cloud.githubusercontent.com/assets/11285640/22467120/f2431134-e7f5-11e6-80d8-6a26b1477bab.png)
![2017_1_31_8_19_45_862_pm](https://cloud.githubusercontent.com/assets/11285640/22467121/f266a702-e7f5-11e6-98b0-6179ab5cc194.png)

In 1.2.2 and older , is better and stable
![2017_1_31_8_28_12_67_pm](https://cloud.githubusercontent.com/assets/11285640/22467134/005301a8-e7f6-11e6-81af-7916ee7c169a.png)
![2017_1_31_8_28_39_533_pm](https://cloud.githubusercontent.com/assets/11285640/22467135/00541106-e7f6-11e6-9cf7-c9050c32ca90.png)
![2017_1_31_8_29_23_155_pm](https://cloud.githubusercontent.com/assets/11285640/22467136/005d6f4e-e7f6-11e6-8581-37eabf86bd46.png)
![2017_1_31_8_29_50_723_pm](https://cloud.githubusercontent.com/assets/11285640/22467137/00617684-e7f6-11e6-84a8-b537a54e09f7.png)

**Comment by hrydgard** [comment] 2017-01-31 13:55
Thanks for reporting, that's quite unexpected..

**Comment by DonelBueno** [comment] 2017-01-31 14:06
Is texture scaling enabled? Maybe it's the same issue as #9125

**Comment by hrydgard** [comment] 2017-01-31 14:21
Good thought, could very well be. I plan to look into that one soon.

**Comment by zminhquanz** [comment] 2017-01-31 15:53
@DonelBueno no , they aren't , i'm not prefer to turn texture upscaling on mobile

**Comment by zminhquanz** [comment] 2017-02-01 03:35
@hrydgard i have old tablet is using Rockchip ( Mali-400) and Mediatek (PowerVR SGX 544)

**Comment by hrydgard** [comment] 2017-02-19 13:35
I now believe this is indeed related to #9125 even if no scaling is enabled. Will investigate soon.

**Comment by unknownbrackets** [comment] 2017-03-18 18:57
I'm not sure if this has a shared cause - the biggest difference is we'd be checking the alpha on the entire video texture on more frames.  I hope that's not enough to lose 30% of performance.

Maybe it's the validation of the frame packets?  Can you identify which build first had worse performance, and which build most recently was still fine?  As narrow a range as possible, from the builds on the buildbot, please.

-[Unknown]

**Comment by zminhquanz** [comment] 2017-03-19 12:04
@unknownbrackets i'm mention this above , using version 1.2.1 , FMV FPS and performance are good 100% , switch to 1.3.1 , it's drop FPS

**Comment by unknownbrackets** [comment] 2017-03-19 14:09
Which git build specifically started this problem?  There are about 1000 changes between v1.2.1 and v1.3.  If you tried 8 builds you'd narrow that down to less than 5 changes, which might make the bug easy to find.

-[Unknown]

**Comment by zminhquanz** [comment] 2017-03-19 14:16
oh , i don't know because between 1.2.1 to 1.3.1 , i'm busy and don't have to test this build

**Comment by zminhquanz** [comment] 2017-03-22 04:50
ok , i will try to find git build in 1.2.1 version have to this issues

**Comment by zminhquanz** [comment] 2017-03-22 15:12
it start this issue and slow down from this @g51bcb02

**Comment by hrydgard** [comment] 2017-03-22 15:17
That's https://github.com/hrydgard/ppsspp/commits/51bcb02  but that can't be the one, got to be a nearby one.

**Comment by hrydgard** [comment] 2017-03-22 15:20
http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Right before is the merge of the IR interpreter #8725, after is https://github.com/hrydgard/ppsspp/commit/1f28d802a3fefa8acf4b09f909c39cb055302c3a which does not seem relevant... 

Pretty odd

**Comment by zminhquanz** [comment] 2017-03-22 16:06
wait a minute , it's start to slowest down on between git geac1848  #8867 ( v1.2.2-821-geac1848 )

**Comment by zminhquanz** [comment] 2017-03-22 16:33
Newer build git than 821 #8867 , it's slow down it's doesn't fixed in #9447

**Comment by unknownbrackets** [comment] 2017-03-23 01:07
Just to be sure: you don't have the rewind feature enabled, right?

-[Unknown]

**Comment by zminhquanz** [comment] 2017-03-23 01:15
@unknownbrackets nope , i started game normally , no load save state

**Comment by unknownbrackets** [comment] 2017-03-23 02:55
Okay, I'm reproducing.  It almost seems like ffmpeg may not be using threads now, or something is different about what happens in it.  Must be an init problem - was caused by 558b462.

It definitely looks like ffmpeg is using threads to decode before, and is not using threads to decode now.  Skipping `SetupStreams()` makes it use threads again, so something about `avformat_find_stream_info` is enabling threads that isn't happening in `SetupStreams()`.

-[Unknown]

**Comment by zminhquanz** [comment] 2017-03-23 02:59
Yeah , i see , i was find out the git build to easy to find problem

**Comment by zminhquanz** [comment] 2017-03-23 10:35
@unknownbrackets test again new build , it's temporary fixed

**Comment by hrydgard** [comment] 2017-03-23 11:32
temporary?

**Comment by zminhquanz** [comment] 2017-03-23 12:27
I mean it's fixed for me , what about of the others ?

**Comment by hrydgard** [comment] 2017-03-23 12:29
Well, it's obviously fixed for Unknown as well. I will try it soon also, but I'm closing. Let's reopen if anyone still see slowdowns.

**Closed by hrydgard** 2017-03-23 12:29 UTC
