### ISSUE TITLE
PPSSPP hangs when switching away and back (previously crashes)

### ISSUE THREAD

**Issue by SukharevAndrey** [hrydgard/ppsspp#8546] opened 2016-02-02 23:43 UTC
PPSSPP crashes right after pressing exit button in menu. It happens on NVIDIA Shield Tablet K1 running Android 6.0.

**Comment by hrydgard** [comment] 2016-02-03 00:02
Yeah, I've been meaning to look at quitting more cleanly for a while, but it doesn't really hurt the user experience as normally you don't even get one of those "force closed" boxes, and you're exiting anyway. But yes, definitely an issue.

**Comment by itornukem64** [comment] 2016-02-06 03:31
Hi, there's other bug, that is when I block the screen and then when I unlock the phone the app is freeze.  I don't wanted to open other issue because it seems related to this.

**Comment by unknownbrackets** [comment] 2016-02-07 22:15
Hmm.  That seems to be a new bug.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-02-07 22:36
@hrydgard so it seems like the render loop is exiting when the screen goes dark, and then nothing is bringing it back.  I tried rekicking the thread from Java,but I get this:

```c++
E libEGL   : eglCreateWindowSurface: native_window_api_connect (win=0xaeb19208) failed (0xffffffea) (already connected to another API?)
E libEGL   : eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
I NativeApp: Error: eglCreateWindowSurface failed: native_window=0xaeb19208 error=EGL_BAD_ALLOC ctx_attribs[1]==3
```

So it seems like it's not cleaning up properly?

-[Unknown]

**Comment by hrydgard** [comment] 2016-02-07 23:00
interesting, I'll take a look tomorrow.

**Comment by unknownbrackets** [comment] 2016-02-13 17:03
Forgot to note, the EGL thing should've been fixed in #8561.

I don't think that solves the shutdown crash though.

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-02-13 19:54
#8590 probably should've fixed this, right?

-[Unknown]

**Comment by SukharevAndrey** [comment] 2016-02-15 11:12
I have tried 1.2 release version. It seems there are no more crashes on exit.

**Comment by hrydgard** [comment] 2016-02-15 11:30
There are on some devices, but I've fixed it and 1.2.1 will be released soon.

**Comment by sum2012** [comment] 2016-02-15 11:43
@SukharevAndrey Can  you try does this hang\black screen ? Thanks
Press "Home" key while in-game , then return to ppsspp.

**Comment by SukharevAndrey** [comment] 2016-02-15 12:19
@sum2012 Yes, PPSSPP hangs and shows black screen after return in 1.2 version.

**Comment by hrydgard** [comment] 2016-02-15 12:25
@SukharevAndrey  How about the latest (misnumbered) build from the buildbot?

**Comment by SukharevAndrey** [comment] 2016-02-15 12:37
@hrydgard Nope, still hangs :(

**Comment by hrydgard** [comment] 2016-02-15 12:56
Hm, ok. thanks.. I'll take yet another look :)

**Comment by sum2012** [comment] 2016-02-15 13:21
It is not happen on my phone (Asus zenfene 2)
But my mother phone happen (https://cloud.githubusercontent.com/assets/2177532/12729570/729bc988-c962-11e5-85c8-d70a6afd617d.png https://cloud.githubusercontent.com/assets/2177532/12729572/72a9f83c-c962-11e5-805c-b3f6c0fccb6a.png https://cloud.githubusercontent.com/assets/2177532/12729571/72a93870-c962-11e5-9ef9-14925982423e.png) !!
I will try to get log when mother sleep....

**Comment by hrydgard** [comment] 2016-02-15 17:31
Committed one more attempt at a fix.

**Comment by hrydgard** [comment] 2016-02-15 19:55
@sum2012  can you try again with the latest and get a log if it doesn't work?

**Comment by sum2012** [comment] 2016-02-15 23:31
now hang rather than crash
the driver hard to install
i will try again in tonight

**Comment by hrydgard** [comment] 2016-02-16 00:41
ok. the log will be interesting. I'll wait with the release a little bit.

**Comment by sum2012** [comment] 2016-02-16 11:44
@hrydgard 
log: https://gist.github.com/sum2012/02e1e211f2b004f6ce85
(I need to press "home key" two times to reproduce,
btw:OMG ,I make my mother total hang here phone black screen

**Comment by hrydgard** [comment] 2016-02-16 12:06
Thank you! I think I have an idea...

**Comment by unknownbrackets** [comment] 2016-08-29 05:03
This was "fixed" by using JavaGL right?  I think we should reassign to Future if so, since this won't be an issue in v1.3.0 even if we don't fix it by then (we have the `androidJavaGL` query workaround.)

-[Unknown]

**Comment by hrydgard** [comment] 2017-11-15 11:26
GL is staying on the Java path, the future is Vulkan. Closing.

**Closed by hrydgard** 2017-11-15 11:26 UTC
