### ISSUE TITLE
[libretro] abysmal performance on android

### ISSUE THREAD

**Issue by andres-asm** [hrydgard/ppsspp#15561] opened 2022-05-29 19:32 UTC
### Game or games this happens in

Tried several, RIDGE RACER in this case

### What area of the game / PPSSPP

Performance is a crapshoot on the libretro core now, but I don't think it's a performance issue per se, more like the core is implemented incorrectly or something like that because I get full speed sound but ~20fps video.

The core used to be fine ~6 months ago, I played ridge racer and peace walker to completion using this core.

Video of the issue (recording is not what is causing this at all)
https://photos.app.goo.gl/Fk5ydfiiLSBG7mnB7

### What should happen

Performance should be as before.

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

Samsung Galaxy S22

### PPSSPP version affected

164c1b5

### Last working version

sadly the libretro versions are not stored

### Graphics backend (3D API)

Direct3D 9

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2022-05-29 20:04
Are you using Auto-frameskipping? if you are, try disabling it (ie. not using any frameskipping) and see if it makes a difference

**Comment by hrydgard** [comment] 2022-05-29 21:02
Could be related to https://github.com/hrydgard/ppsspp/pull/15541 ?

**Comment by fr500** [comment] 2022-05-30 01:21
no I don't think so, I have seen this for months, it was fine ~6 months ago but I didn't backup the core so it's hard to tell

**Comment by Jetup13** [comment] 2022-12-23 01:32
Didn't want to create another issue but I'm having the same issue with performance on the Android Libretro PPSSPP core. Doesn't matter what device I'm on (Retroid Pocket 2+, Retroid Pocket 3+, Samsung S10e SD855, Samsung Galaxy S22, ROG Phone 5) I seem to get around -25% to -30% performance hit on the core. 

Seen someone over on the Libretro discord mention it might of had a regression over time. Went back on what they mentioned that the last build that had better performance seems to be in RetroArch Plus (maybe -20% performance hit).  

Only reason why I want to use the core over the standalone is for RetroAchievements 😅

**Comment by yudhiyou** [comment] 2023-01-15 12:39
This issue is happening to me also. Even if I tried on not demanding game like Street Fighter Alpha 3 the framerate is really struggling.

**Comment by yudhiyou** [comment] 2023-01-29 12:42
So this issue is impossible to fix? Because I haven't seen any progress in years.

**Comment by hrydgard** [comment] 2023-01-29 12:45
It's a libretro issue, and the libretro core is not officially supported by the project, it's just on a level of minimal effort to keep it working. I have enough to do with the standalone builds...

So it's up to someone interested to go investigate and fix it, I'm happy to merge fixes.

**Comment by yudhiyou** [comment] 2023-01-29 14:10
I see :(

**Comment by yudhiyou** [comment] 2023-02-12 00:20
For temporary until this is fixed, is using highrange soc like snapdragon 8 gen 2 will help to solve this issue?

**Comment by ANR2ME** [comment] 2023-02-12 03:06
I don't think this is hardware issue, but you're free to try it if you had the device :)

You can use standalone builds until this issue fixed.

PS: Since iOS also suffers from FPS issue where the FPS is capped at 45 FPS (which is about -25% performance hit from 60 FPS), so may be both Android and iOS have similar issue?

**Comment by fr500** [comment] 2023-02-12 18:46
using standalone fixes everything, so just use that :)

**Comment by yudhiyou** [comment] 2023-02-12 22:35
> using standalone fixes everything, so just use that :)

That is not an option because I need some of retroarch's features like overlay layout, shaders, etc.

**Comment by fr500** [comment] 2023-02-13 14:25
ahh...
I'd rather play games

**Comment by fr500** [comment] 2023-03-21 14:47
it's more like libretro and no quality assurance whatsoever

**Comment by ygordreyer** [comment] 2023-03-26 21:02
Well. I'll ward this issue here. 
I'm a developer, but I have 0 experience with libretro and PPSSPP. 

If there is anything I can to do help, or any clue regarding this issue, feel free to contact me.

**Comment by hrydgard** [comment] 2023-03-26 21:31
@warmenhoven is looking into this, I gave him a few pointers.

**Comment by yudhiyou** [comment] 2023-06-20 02:52
Is using high-end cpu like snapdragon 8 gen 2 will help to remedy this issue?

**Comment by warmenhoven** [comment] 2023-06-20 17:53
I don't know for a fact that Android and iOS have the same issue, but I'm assuming they do. If so, then no, a faster cpu won't help, as it's not a performance problem exactly, it's a buffer blocking problem. On iOS the audio buffer gets filled, and the main thread then gets blocked waiting to add more audio data to the queue.

**Comment by yudhiyou** [comment] 2023-06-21 03:57
> I don't know for a fact that Android and iOS have the same issue, but I'm assuming they do. If so, then no, a faster cpu won't help, as it's not a performance problem exactly, it's a buffer blocking problem. On iOS the audio buffer gets filled, and the main thread then gets blocked waiting to add more audio data to the queue.

I see. Have you managed to fix it for android?

**Comment by warmenhoven** [comment] 2023-06-21 04:11
No. I have an open PR that sort of works around the issue when using vulkan on iOS. I'm currently pondering how to fix the issue on iOS in a better way without potentially breaking all of the other cores, which would hopefully also fix it for the GL renderer. However, neither the workaround PR nor the theoretical fix would help Android at all. I think I understand the issue well enough that someone who can work on Android should be able to confirm whether it's the same issue and look at potentially similar solutions.

**Comment by ANR2ME** [comment] 2023-06-21 05:29
If you can find out which commit causing PPSSPP to push more audio data than it should for the buffer to gets filled too fast like that, the other devs might be able to come up with a proper fix generally.

**Comment by warmenhoven** [comment] 2023-07-10 21:46
Pretty sure #17687 fixes this for both iOS and Android.

**Comment by yudhiyou** [comment] 2023-07-10 22:47
> Pretty sure #17687 fixes this for both iOS and Android.

Wow... Finally! Thank you so much.

**Comment by trotsky40** [comment] 2023-07-11 04:42
Confirming that https://github.com/hrydgard/ppsspp/pull/17687 resolved the issue for me with Android running on an Odin Pro.

**Comment by LunaMoo** [comment] 2023-07-12 22:19
Closing as it's reported fixed.

**Closed by LunaMoo** 2023-07-12 22:19 UTC
Labels: Libretro

**Comment by andres-asm** [comment] 2023-07-13 15:59
thanks @warmenhoven good to see someone in libretro is willing to put the work 😄
