### ISSUE TITLE
Invizimals black screen ( sceusb issue )

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7580] opened 2015-03-10 12:34 UTC
PPSSPP v1.0.1-158-g33b291a log:
https://gist.github.com/sum2012/67019d08b0df36dbcd5b
JPCSP log:
https://gist.github.com/sum2012/35a482354a2b29e8d43f

JPCSP code:
fakeModule.write(Memory.getInstance(), fakeModule.address);
Managers.modules.addModule(fakeModule);

I think we can try that write memory and add module to module list to fix  black screen

**Comment by benderscruffy01** [comment] 2019-04-09 13:06
does this just happen on windows ???
or does it happen on androids aswell

**Comment by LunaMoo** [comment] 2019-04-10 00:20
I believe it wasn't really a duplicate of the closed issue mentioned above. Back when this was opened, cam was unsupported, currently it's partially supported on android and the game no longer shows "black screen", but as reported goes in-game with some glitches. The missing video from the closed issue might simply be a result of speedhacks like skipping buffer effects, disabling simulate block transfer or other heavy effects which are commonly disabled by android users. Could also be a real problem which needs it's own issue, either way I'll mark this one as outdated for now.

 Also to note, camera is not supported on other OS's, but still should show some pre-set image in place of captured video when other things work correctly.

**Comment by unknownbrackets** [comment] 2019-09-08 15:35
As I understand from #8521, it's more or less working now with the exception of microphone.  But it probably does indeed not work on all platforms.

-[Unknown]

**Comment by hrydgard** [comment] 2019-09-08 16:06
This can indeed be closed.

**Closed by hrydgard** 2019-09-08 16:06 UTC
