### ISSUE TITLE
Prince Of Persia Revelations : Black Screen problem during Dahaka Chase

### ISSUE THREAD

**Issue by aksolid7** [hrydgard/ppsspp#9849] opened 2017-07-17 11:01 UTC
Ok, So I am also getting black screen during Dahaka Chase. Prince of Persia Revelations. I have used both PPSSPP Gold and normal version and tried all possible combinations without any luck.

My Device is - Yu Yureka Black
CPU - SD430
GPU - Adreno 505
OpenGL ES 3.1 V@145.0 (GIT@lebe23be877)

Please somebody help me to overcome this problem...

**Comment by leopard20** [comment] 2017-11-23 20:16
@hrydgard 
I've also encountered this on Vulkan (my device can't run the game on OpenGL). It only happens when I check "disable slower effects". What's strange is that the issue only occurs at that point of the game. I've played the game to that point with the option checked and had no issue.
However, if I uncheck that option then it's like you have applied an old movie brown effect to the game! 
(Before this point in the game you can see a weird transparent overlay. That's why I disable slower effects)
I could send you the game save file if you want. 
I could also submit a new issue about the effects.

**Comment by leopard20** [comment] 2017-11-23 20:48
Update: After playing a bit more I realized the "brown effect" issue fixes automatically later on. Definitely weird!

**Comment by Aguszero** [comment] 2018-01-02 06:03
When i sett default dahaka not black screen but slow and graphic look crash square,still after losing from him screen got brown. Sory my bad english

**Comment by ROMANRING** [comment] 2018-01-09 06:21
Hey , Guy's plz help for this problem

**Comment by ROMANRING** [comment] 2018-01-09 06:23
I have redmi 4 and this pop revaluation when  dahaka near black screen in ppsspp

**Comment by unknownbrackets** [comment] 2018-06-05 05:08
Was this fixed by #10597?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-10-05 15:22
Anyone with the save state, near Dahaka Chase??

**Comment by Gamemulatorer** [comment] 2022-09-14 15:17
Cannot reproduce this issue.
![Screenshot_2022-09-14-23-16-41-90](https://user-images.githubusercontent.com/37603562/190194987-bbf9e05f-61cc-4ab3-9603-50ef5ddc6d99.png)

**Comment by hrydgard** [comment] 2022-09-14 16:45
Probably some visual effect that now works, closing.

**Closed by hrydgard** 2022-09-14 16:45 UTC
