### ISSUE TITLE
Hardware transform bug

### ISSUE THREAD

**Issue by Sunil2735** [hrydgard/ppsspp#12835] opened 2020-04-18 19:28 UTC
### What happens?
Frame drop or stutters when Hardware transform is on. This happens in both God of war games.

### What *should* happen?
There should be no frame drop stutter

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

One Plus 7 pro
Android 10
1.9.3 but has been happening on all th builds
Snapdragon 855
Adreno 640

**Comment by unknownbrackets** [comment] 2020-04-19 01:26
Just to confirm, you get better/more consistent performance with hardware transform OFF?  Is this with all other settings set to defaults?

That device has a pretty fast CPU, I wonder if that's related.  Does sustained performance impact this?  If you play for at least 10 minutes with hardware transform off, does it stay faster than 10 minutes with it on?

-[Unknown]

**Comment by Sunil2735** [comment] 2020-04-19 13:15
Please check video:
1st part.... Handware tranform is On... Stutters when using blades. This stutters usually happens when stage changes..
2nd part... Hardware tranform is Off... No stutters when using baldes.
3rd part... Hardware transform is Off.. frame drops during few scenes but there is no stutter like part 1

**Comment by Sunil2735** [comment] 2020-04-19 13:29
[20-04-19-18-40-09.zip](https://github.com/hrydgard/ppsspp/files/4499123/20-04-19-18-40-09.zip)

**Comment by Sunil2735** [comment] 2020-04-19 13:29
Please unzip the file and play the video

**Comment by Sunil2735** [comment] 2020-04-19 13:33
For your question, after I turn off hardware transform, I get slightly better performance as there is no stutter but in few scenes the frame drops slightly because it's turned off.. I've faced this issue on poco and one plus 6 as well
 This issue is on all the builds..

**Comment by Emulatorer** [comment] 2020-04-19 16:25
> For your question, after I turn off hardware transform, I get slightly better performance as there is no stutter but in few scenes the frame drops slightly because it's turned off.. I've faced this issue on poco and one plus 6 as well
> This issue is on all the builds..

your not using ppsspp latest build from buildbot
because there's no Render Duplicate Frames To 60Hz in graphics settings in your video recording.

Try and test the ppsspp apk here https://buildbot.orphis.net/ppsspp/index.php?m=fulllist and see if God of War improve the performance on your Snapdragon 855 phone

**Comment by Sunil2735** [comment] 2020-04-19 17:04
[20-04-19-22-27-18.zip](https://github.com/hrydgard/ppsspp/files/4499769/20-04-19-22-27-18.zip)
1st part.... Handware tranform is On... Stutters when using blades. This stutters usually happens when stage changes..
2nd part... Hardware tranform is Off... No stutters when using baldes.
3rd part... Hardware transform is Off.. frame drops during few scenes but there is no stutter like part 1

Same issue with the new build as well...

**Comment by Emulatorer** [comment] 2020-04-19 17:28
> [20-04-19-22-27-18.zip](https://github.com/hrydgard/ppsspp/files/4499769/20-04-19-22-27-18.zip)
> 1st part.... Handware tranform is On... Stutters when using blades. This stutters usually happens when stage changes..
> 2nd part... Hardware tranform is Off... No stutters when using baldes.
> 3rd part... Hardware transform is Off.. frame drops during few scenes but there is no stutter like part 1
> 
> Same issue with the new build as well...

Just use ppsspp default settings I saw on your video that you enable the speedup in graphics settings like disable slower effects, retained change textures and lazy textures caching.

If you want to reset your ppsspp settings to default just go to settings > system > general > restore ppsspp settings to default.

**Comment by Sunil2735** [comment] 2020-04-19 17:31
Same issue even with default settings... Done restore ppsspp settings..

**Comment by unknownbrackets** [comment] 2020-04-19 18:25
It's probably not causing this hardware transform difference, but beware that retain changed textures will often make games slower.  It makes a few games much faster, and the majority of games a bit slower.

We will compile and use new shaders more often for hardware transform.

Also, vertex cache only works when using hardware transform.  Maybe the issue is only from that.  Does anything change if you disable?  On Vulkan it doesn't help as much anyway.

-[Unknown]

**Comment by Sunil2735** [comment] 2020-04-19 18:40
All the textures options are turned off...issue persists with opengl as well. No the only option was toggling was hardware transform.

**Comment by LunaMoo** [comment] 2020-04-20 20:32
You had them on on the video that's why he commented about it. Either way it's probably as [Unknown] said in his first reply. Your device DOESN'T want to give PPSSPP enough power to run smoothly, when you disable hardware transform it immediately becomes much more demanding and your device decides it needs to run CPU with higher clocks. There's a joke that we should add a bitcoin miner for people with such devices to provide better experience, but nobody's going to do that so you might as well run your own bitcoin miner in the background to enforce higher CPU clocks.

 PPSSPP has no real control over that outside of sustained performance mode, but this be even worse or same as without it depending on the device.

 That's just how android works, how mobile devices in general work. They sell you the "oh ah" specs, but then try hard to never use it outside of selected benchmarks and very popular mobile games, because those specs used at full power would kill your battery and overheat the device very quickly.

**Comment by Sunil2735** [comment] 2020-04-27 16:32
Lunamoo... Thanks your advise didn't help..

**Comment by Gamemulatorer** [comment] 2020-04-28 10:55
@Sunil2735 why closing this?

**Comment by hrydgard** [comment] 2020-04-28 10:59
Because it's not an actual bug but some kind of power management issue that we don't have control over...

**Comment by unknownbrackets** [comment] 2020-06-04 06:30
I think there are apps which allow you to monitor the CPU usage and mhz, you might want to compare using them.  You definitely want sustained performance mode on, but that may not change what's happening here.

You'll most likely find that hardware transform on - although it stutters more - drains your battery slower.

In contrast, your battery will run out faster with hardware transform off, even if there's less stutters (even still some.)

This is a very tricky - almost impossible - problem for PPSSPP to solve itself.  As I've explained before:

> This is one of those strange, paradoxical things about mobile devices.  Basically, device makers had these options:
> 
> 1. Run apps like PPSSPP at MAX SPEED ALL THE TIME, and have a battery life of 30 minutes.
> 2. Run apps only as fast as they absolutely NEED to be, and have hours or days of battery life.
> 
> Some device makers picked option 1, but no one bought their phones because crappy battery life sucks, so those companies or divisions received Darwin Awards and everyone left was choosing option 2.  Now they had a new choice:
> 
> 1. Ask apps how fast they want to run.
> 2. Decide on the operating system level how fast the apps ought to run.
> 
> Some device makers again picked option 1.  Unfortunately, app makers all wanted their apps (and only theirs, not other loser apps made by other people) to be FAST, so it became the same as option 1 the other time around (since every app said it wanted MAX SPEED.)
> 
> Again, no one bought those phones because bad battery life sucks.  A new round of Darwin Awards, and all the phone makers left had chosen option 2.
> 
> And that's where we are now.  Phone makers call the shots and "figure out" what speed your phone should be when running PPSSPP.

Different devices make different guesses about when might be a good time to "power up" the CPU.  Sustained performance mode at least asks for a consistent speed - so it doesn't suddenly get slower after a few minutes.  But it usually means a slower speed.

But your device may still be making decisions about how slow is acceptable even with sustained performance mode on.  Outside of the bitcoin miner or something else to intentionally burn your battery, there's not much we can do to force the issue.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-09-03 05:37
Turning off HW Transform the game become slow...
![Screenshot_2022-09-03-13-34-40-177_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/188257423-502d3cec-9e7b-485d-bfb3-c01fb9cf4909.jpg)
![Screenshot_2022-09-03-13-33-41-896_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/188257425-7d635c65-f5f5-4f78-a10b-be86a9a6f640.jpg)

HW Transform ON smooth both open/vulkan.
![Screenshot_2022-09-03-13-34-07-013_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/188257446-3760712a-accc-4c14-9fdf-8ce24a57e358.jpg)

**Comment by unknownbrackets** [comment] 2022-09-03 06:27
That's the normally expected result, when power management isn't skewing things.  Software transform is slower, because it does all the lighting math and similar on the CPU instead of GPU.  Might be a difference of the governor.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-11-08 09:29
@Sunil2735 how about now?

**Comment by unknownbrackets** [comment] 2022-11-12 19:39
If not from CPU governance, this was likely fixed by the lighting ubershader change.  I'm going to close this, since I suspect it's fixed as much as we can fix it.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2022-11-12 19:39 UTC
Labels: Platform-specific (Android), Vulkan, OpenGL, Adreno GPU
