### ISSUE TITLE
Vulkan (linux): wrong image size

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#10458] opened 2017-12-27 08:10 UTC
What happens?
When PPSSPPSDL (v1.5.4-181-g4657397b5) starts with vulkan renderer in fullscreen, the image takes only 1/4 of the screen (top left corner, width and height are halved). It can be temporarily fixed by exiting fullscreen and entering it again. That works until next start of the application.

What *should* happen?
PPSSPPSDL should use entire screen after start in vulkan mode

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Intel Core i7 3630QM, GPU Intel HD4000, OS Linux Fedora 27, mesa-vulkan-drivers-17.2.4-2.fc27.x86_64, vulkan-1.0.65.1-2.fc27.x86_64

**Comment by psyke83** [comment] 2017-12-29 04:49
This is not limited to Vulkan - it's also happening on Raspberry Pi 3. The most recent builds choose set up a pixel size of:
```
I: Config.cpp:440: Longest display side: -1 pixels. Choosing scale 1
Pixels: 960 x 544
Virtual pixels: 960 x 544
```

The last confirmed build that worked correctly on Pi was: https://github.com/hrydgard/ppsspp/commit/c27d64f273c231241e84498eb9392fbc05635780 - and would set up the window size identical to the actual display resolution:
```
Pixels: 1360 x 768
Virtual pixels: 1360 x 768
```

It's been hard to bisect on Pi because the build was broken by the Vulkan changes that began in the very next commit and only got fixed in the last few days via https://github.com/hrydgard/ppsspp/issues/10433

**Comment by unknownbrackets** [comment] 2017-12-29 07:39
You can try editing CMakeLists.txt, basically just remove all lines that reference `Vulkan_LIBRARY` or `VULKAN_STATIC` in CMakeLists.txt between each checkout.

-[Unknown]

**Comment by psyke83** [comment] 2017-12-29 07:43
Thanks - but the build errors were not all related to the linking of the x86/amd64 vulkan library; there were also miscellaneous errors such as egl functions not being declared that started cropping up immediately after the good commit I referenced above, but I'll try to narrow down the problem regardless.

**Comment by psyke83** [comment] 2018-01-02 08:00
Some notes:
* the fullscreen setting in the configuration is being ignored
* using the "--fullscreen" argument during execution works as expected

The problem is related to (but not directly caused by) this commit:
https://github.com/hrydgard/ppsspp/commit/fe45a059b5ab8546968e27d65eab9cbde42be6bb

Looking at the reference revision that worked properly (c27d64f273c231241e84498eb9392fbc05635780), the above logic was present in a different place and with different bitwise mask:

https://github.com/hrydgard/ppsspp/blob/c27d64f273c231241e84498eb9392fbc05635780/SDL/SDLMain.cpp#L468-L472

Initially, I thought that this could be the solution:
```
diff --git a/SDL/SDLMain.cpp b/SDL/SDLMain.cpp
index acc5cc0..6746c93 100644
--- a/SDL/SDLMain.cpp
+++ b/SDL/SDLMain.cpp
@@ -795,6 +795,10 @@ int main(int argc, char *argv[]) {
                mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
        }

+        // Use the setting from the config when initing the window.
+        if (g_Config.bFullScreen)
+                mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
+
        if (mode & SDL_WINDOW_FULLSCREEN_DESKTOP) {
                pixel_xres = g_DesktopWidth;
                pixel_yres = g_DesktopHeight;
@@ -847,10 +851,6 @@ int main(int argc, char *argv[]) {

        NativeInit(remain_argc, (const char **)remain_argv, path, "/tmp", nullptr);

-       // Use the setting from the config when initing the window.
-       if (g_Config.bFullScreen)
-               mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
-
        int x = SDL_WINDOWPOS_UNDEFINED_DISPLAY(getDisplayNumber());
        int y = SDL_WINDOWPOS_UNDEFINED;

```
However, it doesn't work. It appears that g_Config.bFullScreen is either set to false or not initialized when put here, despite my config having fullscreen set to true. I'm not certain if a function needs to be called first to instantiate g_Config properly.

The follow patch works, though. Is this the proper fix or is it better solution needed?
```
diff --git a/SDL/SDLMain.cpp b/SDL/SDLMain.cpp
index acc5cc0..5bdc000 100644
--- a/SDL/SDLMain.cpp
+++ b/SDL/SDLMain.cpp
@@ -250,11 +250,6 @@ int SDLGLGraphicsContext::Init(SDL_Window *&window, int x, int y, int mode, std:
 #endif
        };

-#ifdef USING_GLES2
-       mode |= SDL_WINDOW_OPENGL | SDL_WINDOW_FULLSCREEN;
-#else
-       mode |= SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE;
-#endif
        SDL_GLContext glContext = nullptr;
        for (size_t i = 0; i < ARRAY_SIZE(attemptVersions); ++i) {
                const auto &ver = attemptVersions[i];
@@ -721,6 +716,11 @@ int main(int argc, char *argv[]) {
        const char *remain_argv[256] = { argv[0] };

        Uint32 mode = 0;
+#ifdef USING_GLES2
+        mode |= SDL_WINDOW_OPENGL | SDL_WINDOW_FULLSCREEN;
+#else
+        mode |= SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE;
+#endif
        for (int i = 1; i < argc; i++) {
                if (!strcmp(argv[i],"--fullscreen"))
                        mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
```

**Comment by psyke83** [comment] 2018-01-02 08:27
Update: it seems that with my proposed patch, it sets up a fullscreen window no matter the setting. In other words, FullScreen = "false" gets ignored.

Instead of my previous patch, this one fixes the issue with the configuration not being respected:

```
diff --git a/SDL/SDLMain.cpp b/SDL/SDLMain.cpp
index acc5cc0..fb3239b 100644
--- a/SDL/SDLMain.cpp
+++ b/SDL/SDLMain.cpp
@@ -790,6 +790,24 @@ int main(int argc, char *argv[]) {
        SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
        SDL_GL_SetSwapInterval(1);

+        // Mac / Linux
+        char path[2048];
+        const char *the_path = getenv("HOME");
+        if (!the_path) {
+                struct passwd* pwd = getpwuid(getuid());
+                if (pwd)
+                        the_path = pwd->pw_dir;
+        }
+        strcpy(path, the_path);
+        if (path[strlen(path)-1] != '/')
+                strcat(path, "/");
+
+        NativeInit(remain_argc, (const char **)remain_argv, path, "/tmp", nullptr);
+
+        // Use the setting from the config when initing the window.
+        if (g_Config.bFullScreen)
+                mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
+
        // Is resolution is too low to run windowed
        if (g_DesktopWidth < 480 * 2 && g_DesktopHeight < 272 * 2) {
                mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
@@ -833,24 +851,6 @@ int main(int argc, char *argv[]) {
        dp_xres = (float)pixel_xres * dpi_scale;
        dp_yres = (float)pixel_yres * dpi_scale;

-       // Mac / Linux
-       char path[2048];
-       const char *the_path = getenv("HOME");
-       if (!the_path) {
-               struct passwd* pwd = getpwuid(getuid());
-               if (pwd)
-                       the_path = pwd->pw_dir;
-       }
-       strcpy(path, the_path);
-       if (path[strlen(path)-1] != '/')
-               strcat(path, "/");
-
-       NativeInit(remain_argc, (const char **)remain_argv, path, "/tmp", nullptr);
-
-       // Use the setting from the config when initing the window.
-       if (g_Config.bFullScreen)
-               mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
-
        int x = SDL_WINDOWPOS_UNDEFINED_DISPLAY(getDisplayNumber());
        int y = SDL_WINDOWPOS_UNDEFINED;

```

...but there's an unfortunate side-effect: fullscreen mode will be set to false when launched without an initial ppsspp.ini configuration present. This is the default setting as specified in Config/Core.cpp, but it's not a good default for Pi since it's not even running in an X11 session.

**Comment by vnctdj** [comment] 2018-05-07 13:12
I can reproduce the 1/4 of the screen bug when going fullscreen on Vulkan, using PPSSPP v1.5.4-971-g97546d30f.
However I don't experience exactly the same problem, as it never gets temporarily fixed as @thesourcehim said. But I think this may be caused by [an other issue I created here](https://github.com/hrydgard/ppsspp/issues/11014).

**Comment by thesourcehim** [comment] 2018-06-06 10:54
Works properly in v1.6.3-10-gb22c48858

**Comment by unknownbrackets** [comment] 2018-06-06 12:42
May have been improved by ##11144.

-[Unknown]

**Comment by GrieverV** [comment] 2018-06-16 16:30
Resizable is definitely still broken on Linux (RADV) using the Vulkan backend, although it now allows you to attempt to resize which I assume it did not before.

 * Any attempt to resize the window will cause it to freeze (minimize/maximize, grow/shrink, enter/exit fullscreen)
 * Starting PPSSPP with fullscreen set in the config causes only the upper-left section to be displayed, the rest flashes garbage. Related to [SDLMain.cpp#L437](https://github.com/hrydgard/ppsspp/blob/master/SDL/SDLMain.cpp#L437)?
 * Launching with --fullscreen results in proper fullscreen

Like above, the following patch at least fixes fullscreen by reordering the config check, although I have no idea if it's correct:  

```
--- a/SDL/SDLMain.cpp
+++ b/SDL/SDLMain.cpp
@@ -429,6 +429,24 @@ int main(int argc, char *argv[]) {
     mode |= SDL_WINDOW_RESIZABLE;
 #endif
 
+	// Mac / Linux
+	char path[2048];
+	const char *the_path = getenv("HOME");
+	if (!the_path) {
+		struct passwd* pwd = getpwuid(getuid());
+		if (pwd)
+			the_path = pwd->pw_dir;
+	}
+	strcpy(path, the_path);
+	if (path[strlen(path)-1] != '/')
+		strcat(path, "/");
+
+	NativeInit(remain_argc, (const char **)remain_argv, path, "/tmp", nullptr);
+
+	// Use the setting from the config when initing the window.
+	if (g_Config.bFullScreen)
+		mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
+
 	if (mode & SDL_WINDOW_FULLSCREEN_DESKTOP) {
 		pixel_xres = g_DesktopWidth;
 		pixel_yres = g_DesktopHeight;
@@ -467,24 +485,6 @@ int main(int argc, char *argv[]) {
 	dp_xres = (float)pixel_xres * dpi_scale;
 	dp_yres = (float)pixel_yres * dpi_scale;
 
-	// Mac / Linux
-	char path[2048];
-	const char *the_path = getenv("HOME");
-	if (!the_path) {
-		struct passwd* pwd = getpwuid(getuid());
-		if (pwd)
-			the_path = pwd->pw_dir;
-	}
-	strcpy(path, the_path);
-	if (path[strlen(path)-1] != '/')
-		strcat(path, "/");
-
-	NativeInit(remain_argc, (const char **)remain_argv, path, "/tmp", nullptr);
-
-	// Use the setting from the config when initing the window.
-	if (g_Config.bFullScreen)
-		mode |= SDL_WINDOW_FULLSCREEN_DESKTOP;
-
 	int x = SDL_WINDOWPOS_UNDEFINED_DISPLAY(getDisplayNumber());
 	int y = SDL_WINDOWPOS_UNDEFINED;
 
```

**Comment by Sanaki** [comment] 2018-08-16 06:27
For what it's worth, this still happens on OpenGL for me, not just vulkan. Vulkan instead continues to just clone the bottom row of pixels down the screen when I fullscreen it, which isn't terribly helpful for attempting... well, anything.

**Comment by Sanaki** [comment] 2018-08-16 06:30
While this issue definitely persists on the latest working build, adding --fullscreen to my launch options is an acceptable fix for me personally in the meantime.

**Comment by unknownbrackets** [comment] 2018-08-18 01:01
Re: the edit - we do allow resize down to 1x, but we default to 2x.  So I think it isn't necessary to force it non-resizable in that case.  It's probably rare anyway.

This is definitely caused by Resize() not being implemented:
https://github.com/hrydgard/ppsspp/blob/f999830027ce2b523330240ce00a917cead7cf59/SDL/SDLVulkanGraphicsContext.h#L27-L38

Perhaps it just needs to use pixel_xres / pixel_yres.

-[Unknown]

**Comment by vnctdj** [comment] 2019-04-15 20:35
I can't reproduce this issue anymore, it seems to be fixed :)

**Closed** 2019-04-15 21:06 UTC
Labels: SDL2, Vulkan
