### ISSUE TITLE
After an update controls have become very, very weird

### ISSUE THREAD

**Issue by AverArt** [hrydgard/ppsspp#13034] opened 2020-06-19 00:55 UTC
### What happens?
I'm using a Supreme Duo image on my Raspberry pi4 and everything was fine. While troubleshooting another issue, I updated everything (as you do) with both the built in Retropie and the supreme duo script they added in. And now, get this, all the controls on PSP are like... shifted down a few spots on a list. As in, now triangle is my hotkey/escape button, R is select, X is Circle, etc. And even if I remap the controls, inside the PPSSPP menus, up and down on my analogue stick is reversed. No matter how many times I reset and remap the controls. And I believe in game it thinks right on the analogue stick is a button, so it doesn't feel right. I've tried it with my 8bitdo and a ps4 controller, same thing. Like... an update seriously put this through the blender. ANYONE have any idea wtf is happening?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Rasberry Pi 4 4gig. Was working perfect yesterday...

**Comment by hrydgard** [comment] 2020-06-27 16:07
Really bizarre, doesn't sound like a PPSSPP change....

**Comment by SeraphisCain** [comment] 2020-08-08 17:20
I'm having almost the exact same issue with PPSSPP on Pi 4, using a self-built image (so OP's Supreme Duo script isn't the cause). With Dualshock 4, everything is fine except for analog up/down being reversed, and only in the PPSSPP menus, in-game everything works fine. But the 8bitdo controls are absolutely wrecked. Same analog problem in the menu as Dualshock 4, d-pad isn't detected at all, both Start and R1/RB are detected as pad1.ThumbL, the analog it isn't responding in-game at all, it's a mess.

**Comment by SeraphisCain** [comment] 2020-08-09 05:04
Okay, so I managed to figure out what the problem was for me. MacOS mode kinda worked but it was really only a workaround, emulating a DS4. Turns out the SN30 Pro+ isn't listed in the controller database, and the autodetected configuration PPSSPP was using for the controller's Dinput mode was ALL wrong (it was setting the d-pad to buttons that don't even exist, b13, b14, etc)  Adding the following to gamecontrollerdb.txt allows the 8bitdo SN30 Pro+ to be properly recognized by PPSSPP:

`03000000c82d00000260000011010000,8Bitdo SF30 Pro   8BitDo SN30 Pro+,platform:Linux,a:b1,b:b0,x:b4,y:b3,back:b10,guide:b2,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,`

(This still doesn't fix the reversed up/down analog thing in the emulator's menu, but as that happens with a Dualshock 4 as well, I think that may be a separate issue.)

**Comment by hrydgard** [comment] 2020-08-17 13:38
Reverse up/down should be fixed now. I'm going to add that line to gamecontrollerdb.txt as well, which should take care of the rest of this problem.

**Closed by hrydgard** 2020-08-17 13:38 UTC
Labels: Input/Controller, Platform-specific (Linux/POSIX)
