### ISSUE TITLE
Disable Slower Effects (speed up)

### ISSUE THREAD

**Issue by Sunil2735** [hrydgard/ppsspp#11045] opened 2018-05-16 09:57 UTC
### What happens?
Disable Slower Effects doesnt't work on Opengl but is fine on Vulkan

### What *should* happen?
Should disable Slower Effects like Smoke or other unwanted graphics.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 7.0
Snapdragon 625
lenovo p2

**Comment by hrydgard** [comment] 2018-05-16 10:39
What? The option should do the exact same thing in both APIs. Please list the games that are affected.

**Comment by Sunil2735** [comment] 2018-05-16 16:38
God of War Ghost of Sparta
God of War Chain of olympus

**Comment by leopard20** [comment] 2018-05-16 17:01
I can confirm this.

**Comment by Sunil2735** [comment] 2018-05-16 21:25
![screenshot_20180516-220530](https://user-images.githubusercontent.com/10764283/40144932-b877e3b2-597d-11e8-946a-a1fbc8f082fc.jpeg)

**Comment by Sunil2735** [comment] 2018-05-16 21:26
![screenshot_20180516-220541](https://user-images.githubusercontent.com/10764283/40144976-d7c0a9c0-597d-11e8-8c78-73ea019f0d7a.jpeg)

**Comment by Sunil2735** [comment] 2018-05-16 21:26
![screenshot_20180516-220604](https://user-images.githubusercontent.com/10764283/40144990-e3284e6c-597d-11e8-9de9-ed597108b87f.jpeg)

**Comment by Sunil2735** [comment] 2018-05-16 21:26
![screenshot_20180516-220614](https://user-images.githubusercontent.com/10764283/40145006-f0644afe-597d-11e8-8780-c77c4059d1ad.jpeg)

**Comment by hrydgard** [comment] 2018-05-16 21:53
That is odd indeed...   As far as I can tell, the checks are identical for all the APIs...

**Comment by Sunil2735** [comment] 2018-05-16 21:59
There is difference in look for vulkan with and without disable slower effects. Vulkan with Disable slower effects have sharper look, bloom is less and smoke effect is removed.

**Comment by Sunil2735** [comment] 2018-05-16 21:59
But there is no difference at all in Open Gl with or without Disable slower effects.

**Comment by AkiraJkr** [comment] 2018-05-17 23:35
For some reason, I feel like the same can be applied to Direct3D9 as well...no difference whatsoever when I enable/disable it. Tested in God Eater Burst.

**Comment by ShadowLady** [comment] 2018-05-18 04:34
"Disable Slower Effects" works different on the APIs and different games. 

An example with dante's inferno:
https://imgur.com/a/jRsagx3

Can't test vulkan tho :p

**Comment by asbel123** [comment] 2018-05-19 10:30
Brave story work with disable slower effect get more fullspeed on Samsung galaxy s6 edge

**Comment by unknownbrackets** [comment] 2018-05-20 20:49
Just a list of what this (currently) does:
 * Prevents flushing on every rectangle draw to the current texture.
 * Skips uploading current RAM into new framebuffers (e.g. transitions, device reset, etc.)
 * Skips copying the depth buffer on framebuffer switch (e.g. Jeanne d'Arc requires depth to be kept.)
 * Skips downloading new framebuffers to RAM after first draw.
 * Discards framebuffer contents on detected resize.
 * Ignores rendered CLUTs (Brave Story mainly.)
 * Ignores unsupported blend factors and approximates instead (always ignored on Direct3D 9 which doesn't support it anyway.)
 * Ignores CLUT effects on render-to-texture usage.
 * Uses unspecified behavior on render-to-self-texture.  This varies wildly between backends.

Everything should be the same on all backends, with the exception of render-to-self.

On OpenGL and Direct3D 9, we try to render anyway, which may sometimes actually work... or may cause weird graphical corruption.

On Direct3D 11 and Vulkan, we explicitly bind a null texture, which is probably black/transparent, and use it.

So for example - the God of War screenshot of Vulkan is likely darker because we're overlaying black on top of the screen.  But this avoids an expensive copy.  Dante's Inferno is probably showing the "weird graphical corruption" case of OpenGL.

So this is all about render-to-self, really.

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-01-03 15:27
Differences have likely improved since this was filed as much as they can.  This is a hack and is definitely expected to cause incorrect graphics.  What graphics will depend on device and backend - on some devices, "disable slower effects" disables less, because those devices have features that don't require disabling as much.

Please don't rely on what "disable slower effects" disables precisely.  In future versions, it may disable more or less things.  If there are specific effects you want disabled, that's an area for a cheat, plugin, or hack to the game specifically.

As such, I'm going to close this.

-[Unknown]

**Closed by unknownbrackets** 2021-01-03 15:27 UTC
