### ISSUE TITLE
R-type command 1 and 2, fail to create groupname for adhoc

### ISSUE THREAD

**Issue by Willburd** [hrydgard/ppsspp#9863] opened 2017-07-25 11:19 UTC
A bit of a fore-warning. I've practically no experience with programming emulators, and mostly tried to debug backwards till I made some progress. I've not solved the issue myself, but hope I've at least pointed a way forwards for someone with actual experience on this project to know what's wrong. 

All of this is in Core\HLE\sceNetAdhoc.cpp . No groupname is provided by the game, or some thread made to collect it does not do it in time, resulting in a nullptr being passed into:

`line: 1384    static int sceNetAdhocctlConnect(u32 ptrToGroupName)`

 If we force it to proceed past by replacing the return line in the function with something like like... 

```
static int sceNetAdhocctlConnect(u32 ptrToGroupName) {
	if (Memory::IsValidAddress(ptrToGroupName)) {
		INFO_LOG(SCENET, "sceNetAdhocctlConnect(groupName=%s) at %08x", Memory::GetCharPointer(ptrToGroupName), currentMIPS->pc);
		return sceNetAdhocctlCreate(Memory::GetCharPointer(ptrToGroupName));
	} 
		
	//This is the important edit here VVVVVV
	return sceNetAdhocctlCreate("backup"); //return ERROR_NET_ADHOC_INVALID_ARG; // ERROR_NET_ADHOC_INVALID_ADDR;
}
```

Once all the checks are done, we finally reach the packet with the groupname being sent out. However no connection appears to happen between client and host.

`line   1344:   int iResult = send(metasocket, (const char *)&packet, sizeof(packet), 0);`

It fails silently with a socket error after a few moments of waiting. Likely because the socket from before is not released, as the game appears to just try to connect out again. Interestingly, in some cases it 
seems the silent failure code still runs even when the send function doesn't return a -1 socket error. This might be a networking failure on my end however, but the upside to this is that both R-type tactics 1 and 2 now actually try to create a socket.

A thread also closes incorrectly a bit before this this. It may be friend finder's, the dummy thread created earlier on, or something related. It appears even if you don't do this hack of a "fix", and happens before "backup" is even used as a substitute group name. Hopefully this points someone in the right direction. It might just be unimplemented stuff.

**Comment by unknownbrackets** [comment] 2017-07-30 18:06
The ideal thing would be to test what actually happens when `sceNetAdhocctlConnect(NULL)` is called on a real PSP.  This could be done using JpcspTrace or psplink, as long as you have a real PSP to test with.

It's possible that NULL could mean "use last name" or "generate one".  Maybe `ERROR_NET_ADHOC_INVALID_ARG` is correct, but only when it hasn't been called with a name previously.

Or, even simpler, it could be the wrong error code.  Many games call functions with invalid arguments, and expect a certain error code.  You can imagine a PSP game with this code:

```c++
int err = sceNetAdhocctlConnect(groupName);
if (err == SCE_ERROR_BAD_GROUP_NAME) {
    // This must be the first time through the loop, let's initialize.
    // It sure is convenient we get this error code and can be lazy.
    groupName = generateGroupName();

    err = sceNetAdhocctlConnect(groupName);
}
```

But indeed it could be other unimplemented, or incorrectly implemented, stuff.

-[Unknown]

**Comment by adenovan** [comment] 2017-07-31 08:06
many games also create empty group name when first connected to adhoc network.  some example god eater burst and phantasy star portable 2 . The game  created an empty string group name as a lobby to find other peer in the network. once the lobby process complete it create a unique name for each group something like random hash. 

did the game also passing empty group name when it call int sceNetAdhocctlCreate(const char *groupName) ?

**Comment by darklord92** [comment] 2017-08-21 22:43
-adenovan
Using the backup name results in  sceNetAdhocctlCreate(const char *groupName) getting the same name, however the socket failure stuff stops any multiplayer session from properly starting. if I use the current code sceNetAdhocctlConnect(u32 ptrToGroupName) returns ERROR_NET_ADHOC_INVALID_ARG and seems to drop the connection attempt entirely. There was also a commented out ERROR_NET_ADHOC_INVALID_ADDR. However that just results in a different error number returned by the game (matching the ERROR enum, so the game is directly returning that as a failure.) 

-unknownbrackets
I'm going to try and use one of those psp debuggers. I'll need to clear things up in my rather small memory card however if I'm going to use tactics 2. I want to keep the tests I've been doing consistent with the same game, as I can't assume they use the exact same code despite the two games very likely using the same engine. I'll see what I can report back, but it does seem like something is likely just "not implemented," as the game doesn't jump into other adhoc code if an error is returned to it from sceNetAdhocctlConnect(u32 ptrToGroupName).

**Comment by unknownbrackets** [comment] 2017-08-23 04:01
Well, you definitely can't make assumptions about how games will use these APIs - there will be an off game that does something funny.

But, if you use an API in the same way as the game, you can create a simple situation that you can control.  Back when I [implemented mutexes](https://github.com/hrydgard/ppsspp/pull/70), most games didn't even go in game, but I still could see how they were trying to use mutexes, and test them myself.

Debugging one function looking at one game can be dangerous - because maybe another function didn't do the right thing, and that's just causing the game to call the second function wrong.  That's why controlling the situation is best: if you know what should really happen when you call network functions in the same sequence, it helps you much more quickly figure out which function of functions are the problem.

Don't be too quick to assume that because there's a log message for a function, it's definitely the only function with a bug.

-[Unknown]

**Comment by adenovan** [comment] 2017-11-08 09:50
One thing that can be done here to solve the issue is trace the succesfull adhoc session on this game. What group name is give on the real psp, proadhocserver.cpp has some character checking on the game group that can make the adhoc session failed also. Can you try trace that on jpcsp? Or maybe its caused by the wrongly implemented connect function also. That function is just using the return code fron the create function. Its can be the wrong return code is given by the create function because its incorrectly implemented. 

The create function is connected to the ctlserver created by coldbird. AFAIK on real psp its only compatible with 50++ games. If the aemu plugin created by coldbird worked correctly in psp  its mean we have wrong implemented function on the adhoc code. Try it with real psp if you have one

**Comment by unknownbrackets** [comment] 2020-12-31 16:48
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment] 2021-01-16 07:57
NULL group issue has been fixed on the latest dev build as i remembered, at least one of the game that use it (ie. PSP2) is working properly by now, not sure about God Eater Burst.

**Comment by hrydgard** [comment] 2021-01-16 08:48
Let's close for now and see if it comes up again.

**Closed by hrydgard** 2021-01-16 08:48 UTC
Labels: Networking / adhoc, No Feedback / Outdated?
