### ISSUE TITLE
Dragon ball z tenkiachi Tag team (outline vulkan bug)

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#15005] opened 2021-10-10 02:55 UTC
### Game or games this happens in

ulus10537

### What area of the game

In game fight.

### What happens

Outline wrong colour

![Screenshot_2021-10-09-20-27-24-608_org ppsspp ppsspp](https://user-images.githubusercontent.com/4172898/136679322-59385862-a1cf-4db6-9695-e16bb8757e81.jpg)
![Screenshot_2021-10-09-20-26-48-604_org ppsspp ppsspp](https://user-images.githubusercontent.com/4172898/136679323-7c03d5fa-ac6d-4d7c-840f-621ac74368d9.jpg)
Stock settings with 6x resolution

### What should happen

![Screenshot_2021-10-09-20-54-46-055_org ppsspp ppsspp](https://user-images.githubusercontent.com/4172898/136679680-8831ab3f-f4f4-4b03-bb95-1a8584ba9b17.jpg)

Look fines with opengl.

### GE frame capture

[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7316743/recording.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Pocox3 pro sd860 Adreno 640 8gb ram

### PPSSPP version affected

v1.12.1-3-gfbf9b7f54

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment] 2021-10-10 07:48
Cannot reproduce this on my RN9 MTK Helio G85 Mali-G52 GPU.
**Vulkan**
![Screenshot_2021-10-10-15-45-26-317_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136687263-2c3b191a-e59c-4fd4-9e5d-44329ea262ee.jpg)
**Opengl**
![Screenshot_2021-10-10-15-46-08-709_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/136687275-ab6630e9-88dd-4461-947c-d0547c5b9b40.jpg)

**Comment by Panderner** [comment] 2021-10-10 09:57
I cannot reproduce this for my PC:
![Screenshot (43)](https://user-images.githubusercontent.com/37503397/136690955-8e618885-32ba-46bb-a50c-a66fa8f48f55.png)

**Comment by Panderner** [comment] 2021-10-10 17:38
I can reproduce this for my POCO M3:
![Screenshot_2021-10-11-01-37-24-866_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/136707088-7a7fe1cf-5dea-4f83-b4f5-23b1cee52419.jpg)

**Comment by Gamemulatorer** [comment] 2022-09-13 15:22
Cannot reproduce this on my Oppo a3s adreno 506 vulkan latest build ppsspp.
![Screenshot_2022-09-13-23-21-32-60](https://user-images.githubusercontent.com/37603562/189941573-151f9bb3-ec2b-43de-8fa7-e5dc11a59310.png)

**Comment by hrydgard** [comment] 2022-09-14 21:41
I think this is likely to have been fixed at some point. Closing.

**Closed by hrydgard** 2022-09-14 21:41 UTC
Labels: Adreno GPU, GE emulation
