### ISSUE TITLE
tenchu shadow assassins lag area 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#13410] opened 2020-09-10 06:23 UTC
### What happens?

The first stage of the game is dropping a lot of frames in this place, now why is this happening? I changed the setting but it is not working
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Latest build , adreno 505 gpu , sd430

**Comment by fahadfoyjur** [comment] 2020-09-10 06:23
![Screenshot_20200910-121209](https://user-images.githubusercontent.com/30353841/92689220-76935b00-f360-11ea-8e54-0496e669b9e4.png)

**Comment by fahadfoyjur** [comment] 2020-09-10 06:24
![Screenshot_20200910-121240](https://user-images.githubusercontent.com/30353841/92689255-8612a400-f360-11ea-9be4-1c607d70d477.png)

**Comment by Panderner** [comment] 2020-09-10 06:49
@fahadfoyjur have you tried to drop the resolution to 1x?

**Comment by fahadrashid7705** [comment] 2020-09-10 06:57
1 x resolution dosent effect any fps boost i tryed

**Comment by Panderner** [comment] 2020-09-10 07:36
> 1 x resolution dosent effect any fps boost i tryed

@fahadrashid7705 send me the Screenshot in 1x resolution

**Comment by Panderner** [comment] 2020-09-10 07:56
I'm using Realme C2 and this how i improved the performance using fast memory on

Fast memory off:
![Screenshot_2020-09-10-15-51-44-07_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/92697614-16131680-f37e-11ea-8702-1344ce14972e.png)

Fast memory on:
![Screenshot_2020-09-10-15-53-12-27_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/92697678-24f9c900-f37e-11ea-9c4b-03b4b7990823.png)

**Comment by fahadfoyjur** [comment] 2020-09-10 08:07
Realme c2 is a good phone , if i active turned of fast memory the game more laggy

**Comment by fahadfoyjur** [comment] 2020-09-10 08:08
Maybe this game's render too demanded

**Comment by Gamemulatorer** [comment] 2020-09-10 08:46
Can you upload a ge dump 🤔

**Comment by Panderner** [comment] 2020-09-10 09:28
> Maybe this game's render too demanded

Maybe your phone does not support vulkan.

**Comment by fahadrashid7705** [comment] 2020-09-10 11:53
no not support vulkan in 6.0.1

**Comment by fahadrashid7705** [comment] 2020-09-10 13:39
i am always select fast memory on

**Comment by fahadrashid7705** [comment] 2020-09-10 14:12
snapdragon 430  device symphony z8

**Comment by fahadrashid7705** [comment] 2020-09-10 14:12
i think the game's fog effect is very cpu demanded .

**Comment by Panderner** [comment] 2020-09-10 15:14
So it's a power issues because your phone is not powerful enough to run this game full speed

**Comment by fahadfoyjur** [comment] 2020-09-10 17:11
I dont know what is the actual problem , but many psp games cannnot run in my device in proper speed . snapdragon 430 is a very bad processor  ?  What is your feedback ?

**Comment by Panderner** [comment] 2020-09-10 23:03
> I dont know what is the actual problem , but many psp games cannnot run in my device in proper speed . snapdragon 430 is a very bad processor ? What is your feedback ?

Maybe check your refresh rate or have you tested least demanding games?

**Comment by Gamemulatorer** [comment] 2020-09-11 00:45
>> I dont know what is the actual problem , but many psp games cannnot run in my device in proper speed . snapdragon 430 is a very bad processor ? What is your feedback ?

YES! your phone gpu/cpu is not good enough for ppsspp to play fullspeed on demanding games..

**Comment by fahadrashid7705** [comment] 2020-09-12 04:54
is ppsspp needs a flugship powered phone ?

**Comment by Panderner** [comment] 2020-09-12 06:16
> is ppsspp needs a flugship powered phone ?

@fahadrashid7705 You don't need a flagship phone to run most games least demanding stuff runs ok for your phone but heavy stuff like God of War, Killzone and Midnight Club needs a beefy devices with vulkan support in 1x resolution

**Comment by Gamemulatorer** [comment] 2020-09-12 08:50
> is ppsspp needs a flugship powered phone ?

Can you upload your ge dump for this game?

**Comment by fahadfoyjur** [comment] 2020-09-12 13:31
Ok i am uploading a dump . can you fix this issue ?

**Comment by fahadfoyjur** [comment] 2020-09-12 13:33
The fog use the cpu hard i thik , but how ? How to remove this effect ?

**Comment by fahadrashid7705** [comment] 2020-09-12 13:48
https://drive.google.com/drive/folders/1XJApIe0nqJeqnmBdVP9oZSeW8QjWue4U?usp=sharing

**Comment by Gamemulatorer** [comment] 2020-09-12 22:36
fahadrashid7705 are you using default settings?
your ge dump look weird on my phone 🤔😅
![Screenshot_20200913-063349](https://user-images.githubusercontent.com/37603562/93006160-7aef8c00-f58b-11ea-8284-46ca4ad1eac6.png)
![Screenshot_20200913-063503](https://user-images.githubusercontent.com/37603562/93006161-7dea7c80-f58b-11ea-863c-eb10bd2d0a79.png)

**Comment by Panderner** [comment] 2020-09-13 01:21
> The fog use the cpu hard i think

@fahadfoyjur the fog doesn't affect performance but based on draw distance as mentioned in https://github.com/hrydgard/ppsspp/issues/12437#issuecomment-544427513

**Comment by fahadrashid7705** [comment] 2020-09-13 06:21
this is a fog issue not draw distances

**Comment by Panderner** [comment] 2020-09-13 06:49
> this is a fog issue not draw distances

Fog is only appeared when the draw distance limit is reached it draws fog as a hardware limitations of a PSP. Lower Draw Distance with fog should be good enough for Lower powered devices.

**Comment by Gamemulatorer** [comment] 2021-05-18 10:57
This is clearly a duplicate of #12437

**Comment by unknownbrackets** [comment] 2021-05-21 05:04
Sounds right - we're always trying to improve performance on all devices, but some games are very demanding for weaker devices.  I'm going to close this - it doesn't look like there's an obvious way to improve performance of this game on weaker devices.  Devices are continuing to get more powerful every year, so hopefully this situation will improve with time.

If you see any specific performance regressions, or areas in the game which have sudden performance drops, please do report them.

I'm going to close this as a duplicate of #12437.

-[Unknown]

**Closed by unknownbrackets** 2021-05-21 05:04 UTC
