### ISSUE TITLE
Phantasy Star rendering issue, probably Z-buffer precision

### ISSUE THREAD

**Issue by mlwj1993** [hrydgard/ppsspp#10710] opened 2018-03-11 21:10 UTC
What happens?
Model / texture on boots of character gets overlapped by leg model / texture
![improperly rendered](https://user-images.githubusercontent.com/37276043/37258472-de35bbc6-2578-11e8-8d5d-9715ee986a49.jpg)

What *should* happen?
Model / texture of boots should be rendered on top of the legs texture.
![properly rendered](https://user-images.githubusercontent.com/37276043/37258473-e6995ebc-2578-11e8-913d-91164aee3fcc.png)
(it renders properly on character select screen)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Windows 10 Home 64 bits (10.0, build 16299).

Intel core i7-6700HQ @2.60 GHz (8 CPU's)
Intel HD Graphics 530
Nvidia Geforce GTX960M (Geforce game ready driver 391.01)

Happens in PPSSPP Build 1.5.4-657-g3c16f8437 (Dev Build), Works fine on latest stable release (1.5.4)
Forgot to note this happens independent of Rendering backend

**Comment by unknownbrackets** [comment] 2018-03-12 03:03
This might be related to the depth hacks for Phantasy Star Portable.

-[Unknown]

**Comment by mlwj1993** [comment] 2018-03-12 20:17
After looking into it further it might also be just a gamebug. Since the character wasn't wearing anything in the pants slot that happened, after putting something in that slot the boots render normally.
Too bad my PSP died on me so I can't really check if it does indeed do that on a real psp as well...

**Comment by benderscruffy** [comment] 2022-09-05 09:32
i dont think this is an issue anymore
could not reproduce it

**Comment by Gamemulatorer** [comment] 2022-12-08 11:58
Might improve this now after https://github.com/hrydgard/ppsspp/pull/16504

**Comment by unknownbrackets** [comment] 2022-12-08 19:02
I think it's likely this is fixed.  If it's not, a GE frame dump would be very helpful to confirm against a PSP.  It may in fact be a game bug as noted if it's not fixed now.

Given that, I'm going to close this.  If you're still seeing it in a recent git build, please add a comment (ideally with a GE frame dump.)  If it's another depth issue in this or a different game, better to create a new issue.

-[Unknown]

**Closed by unknownbrackets** 2022-12-08 19:02 UTC
