### ISSUE TITLE
Allow > 5x PSP resolution for mobile devices

### ISSUE THREAD

**Issue by JuliusSenkus** [hrydgard/ppsspp#12815] opened 2020-04-12 12:35 UTC
Hi, 

This is this is feature request related to #8714, additionally would like to request same for android.
My android box is pretty powerful ([Khadas VIM3 Pro](https://www.khadas.com/vim3) with [A311D](https://androidtvbox.eu/amlogic-a311d-s922x-b-vs-rk3399-s912-comparison/)) my 4k TV and games emulated should have no problem running in higher resolutions. 
As I see from [MOBILE_DEVICE](https://github.com/hrydgard/ppsspp/blob/6df422800506236e6703f3a114dd0ade976ac3c9/UI/GameSettingsScreen.cpp#L318) flag, as mobile devices are becoming more powerful, [that branchout](https://github.com/hrydgard/ppsspp/blob/6df422800506236e6703f3a114dd0ade976ac3c9/UI/GameSettingsScreen.cpp#L318) should disappear (or should be adjusted in other way). 
Or are there any other issues that this change should not be applied (as I'm not owner of this repository have no such deep domain knowledge)?

**Comment by Emulatorer** [comment] 2020-04-12 12:41
![Screenshot_20200412-204030](https://user-images.githubusercontent.com/37603562/79069071-ee9c1d00-7cfd-11ea-9e6b-5219f747162e.png)
This ss is from my android device :)

**Comment by Panderner** [comment] 2020-04-12 12:46
Neither of 4k Android TV boxes does not run well for PSP Games in 4k. Above 5x resolution is only available on X86 platforms. So it's a duplicate of #8714

**Comment by Panderner** [comment] 2020-04-12 12:59
Only of 4k Android phone displays are Xperia XZ Premium and Xperia XZ2 Premium. Most of Flagship Android phones offers 1440p display.

**Comment by unknownbrackets** [comment] 2020-04-12 14:01
This issue is being closed as a duplicate of #8714 (it's not just related, it's a duplicate.)

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Comment by Panderner** [comment] 2020-04-12 14:34
> This issue is being closed as a duplicate of #8714 (it's not just related, it's a duplicate.)
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

@unknownbrackets can you mark as a duplicate? I can't find any duplicates even the original one is closed or fixed.

**Comment by JuliusSenkus** [comment] 2020-04-12 14:49
Sorry to disturb again @Panderner, but if I create PR with solution and provide tested results with devices that have higher resolution screens and can run games at higher resolutions, PR will be accepted (if it will match code requirements and rules)? Also I could test only Android, Linux and Windows builds.

**Comment by unknownbrackets** [comment] 2020-04-12 15:09
Most likely it would be nowadays.  Generally we like to avoid having settings where people can too easily shoot themselves in the foot, but tablets and phones are able to support much higher resolutions and fill rates these days.

Biggest thing worth confirming is what happens if you select 10x (perhaps even on a phone) and have the display resolution (HW scaler) setting set to auto.  Possibly we already handle this.

-[Unknown]

**Comment by JuliusSenkus** [comment] 2020-04-12 15:26
So the biggest problem is here that this functionality could flood github with new created issues, that should be maintained and would consume one's sanity... :upside_down_face: Understood, will comeback with testing results and PR in couple of days (or this evening), but will attach everything on #8714.

**Closed** 2020-04-12 18:41 UTC
