### ISSUE TITLE
I believe it’s a graphic issue 

### ISSUE THREAD

**Issue by Chaoscat666** [hrydgard/ppsspp#19514] opened 2024-10-09 21:10 UTC
### Game or games this happens in

Silent hill shattered memories 

### What area of the game

After a new game starts like right at the start of game play.

### What happens

The flight light keeps having these weird barcodes lines on anything it shines on.
![IMG_1859](https://github.com/user-attachments/assets/32e3d696-4899-4626-ae5b-9f55aee59a91)
![IMG_1858](https://github.com/user-attachments/assets/a9e8a746-4b2d-41f4-a331-6d0279d5f49e)
![IMG_1856](https://github.com/user-attachments/assets/62ded513-247d-4b95-aa00-7aa9c64b5102)

### What should happen

![IMG_1862](https://github.com/user-attachments/assets/2d874652-6fd5-41a0-941b-13ddda5169de)

### Platform

iOS

### Mobile device model or graphics card (GPU)

Apple A16 GPU

### PPSSPP version affected

V1.17.4-1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2024-10-09 21:23
This is a duplicate of  #6265 which affect both silent hill games, slightly differently. Well known, old and very difficult-to-fix issue unfortunately.

**Closed by hrydgard** 2024-10-09 21:23 UTC
