### ISSUE TITLE
March cores crashes retroarch

### ISSUE THREAD

**Issue by Adnan1091** [hrydgard/ppsspp#12715] opened 2020-03-16 07:08 UTC
### What happens?
I have 2 issues.Firstly,Even through  my phone supports vulkan renderer,it automatically switches to gl driver.Finally,the cores between 1 march to latest day crashes retroarch.

### What *should* happen?
It should open and work.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Libretro ppsspp latest core-android ARM64

**Comment by Panderner** [comment] 2020-03-16 07:35
@Adnan1091 what phone are you using?

**Comment by unknownbrackets** [comment] 2020-03-16 13:57
This issue is being closed as a duplicate - looks the same as #12679 and #11836.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-03-16 13:57 UTC
Labels: Libretro

**Comment by Panderner** [comment] 2020-03-16 14:13
> This issue is being closed as a duplicate - looks the same as #12679 and #11836.
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

Why you don't mark duplicate because I can't find any duplicates even the original one is closed or fixed
