### ISSUE TITLE
Official PlayView titles crash out emulator trying to play videos

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#10971] opened 2018-04-27 06:23 UTC
v1.5.4-933-g386c9d4fc
any of the playview titles click on the videos and it crashes out the emulator straightaway
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/1954034/ppsspplog.zip)
could be
10:33:086 user_main    E[ME]: HLE\sceMp4.cpp:75 UNIMPL sceMp4GetMovieInfo(mp4 145497920, unknown2 09fff150)

**Comment by LunaMoo** [comment] 2018-04-28 10:16
sceMp4 is not emulated at all, so nothing else should be expected, we don't need separate issues for each application using them, so I'll close this as a duplicate of #1755
 ~ jpcsp seems to be ahead in media engine emulation so it probably can be watched using it.

**Closed by LunaMoo** 2018-04-28 10:16 UTC
