### ISSUE TITLE
Sometimes, sometimes not xbrz and filtering.

### ISSUE THREAD

**Issue by clort81** [hrydgard/ppsspp#14314] opened 2021-03-24 11:28 UTC
OS: Devuan Linux,  Arch: Aarch64 (armv8), Drivers Panfrost, GPU mali g52.
PPSSPPSDL and PPSSPPQt 1.11.2-209-g39198b53a and some prior builds

In the Legend of Heroes games (FC, SC, Zero) and possibly others too, I get "sometimes, sometimes not" xbrz and filtering.  Often different layers in the same scene.

![SomeThingsSmoothed](https://user-images.githubusercontent.com/51511737/112301167-ef715900-8c99-11eb-89b9-c89cbeb1f292.png)

Can't supply online debug because Online Debugger causes Segmentation fault.
Enabling DevMenu and Dump frame GPU commands generates this log:
[testrun_clort_2021_03_24.log.zip](https://github.com/hrydgard/ppsspp/files/6196684/testrun_clort_2021_03_24.log.zip)

#### Which game or games?
ULES01556, NPEH00166, NPJH50311, prob others 

#### Graphics backend (Vulkan, OpenGL, etc.)?
OpenGL-ES (eglinfo attached)
[eglinfo.txt.zip](https://github.com/hrydgard/ppsspp/files/6196707/eglinfo.txt.zip)

 - [X] Test in v1.11.2-209-g39198b53a and prior
 - [X] [Search for other reports] Not found 
 - [X] Try resetting settings - cannot identify when it happens or doesn't

PPSSPP ini file
[ppsspp.ini.zip](https://github.com/hrydgard/ppsspp/files/6196762/ppsspp.ini.zip)

Not a showstopper problem.  May be related to WIP panfrost drivers.
Just *interesting* :)

**Comment by LunaMoo** [comment] 2021-03-24 20:33
Texture scaling in PPSSPP runs on CPU and is too slow, so it's intentionally not affecting textures that change too often and also limited to set texels per frame, so it can't instantly scale everything either. That's an important performance feature, not a bug.

 With Vulkan you can use hardware texture scaling which is much faster and limit-free, needs a decent GPU for full speed through.

 Also on fully 2D games, using xbrz/5xbr post process effects can give similar results that are much lighter.

**Comment by unknownbrackets** [comment] 2021-03-25 05:15
Closing this as a duplicate of #1934.  Which I guess would only be closed when we remove CPU based scaling and just don't allow scaling for people whose GPUs can't do texture scaling.

To avoid this problem as LunaMoo noted:

1. Switch to the Vulkan graphics backend in settings.
2. Make sure your GPU is powerful enough (otherwise you'll get frame drops.)
3. Choose the 4xBRZ or MMPX for the texture shader setting.  Separate setting from post-processing.

-[Unknown]

**Closed by unknownbrackets** 2021-03-25 05:15 UTC
