### ISSUE TITLE
Star Wars The Force Unleashed.- list of issues I have seen

### ISSUE THREAD

**Issue by andy0232** [hrydgard/ppsspp#14184] opened 2021-02-20 00:40 UTC
Here I go......

Let's start with the performance 
Performance is not good when buffered rendering is on without the red overlay cheat on. However performance is increased when red overlay hack is on. Yet the hack also glitches things out. Here are the glitches with the hack on:

![Screenshot_20210219-174606](https://user-images.githubusercontent.com/66369667/108574297-03195080-72e5-11eb-9bde-9e2c6044604c.png)
This happens when the hack is on, however when the hack and buffered rendering are off it has the same rectangle shape yet the fill is black

https://user-images.githubusercontent.com/66369667/108574398-4d9acd00-72e5-11eb-96cd-50400ece7afb.mp4
This happens when the hack is on as do the two issues i am showing after this

https://user-images.githubusercontent.com/66369667/108574426-64d9ba80-72e5-11eb-8785-b0b10362c99d.mp4

Hack is on so is br 

https://user-images.githubusercontent.com/66369667/108574470-82a71f80-72e5-11eb-9c21-bb383fc64fe6.mp4

Br and hack are on

Now the next issue is odd:

This is performance without the cheats and br is on
https://youtu.be/VHBpLz5V030

But when i enable the cheats for the red overlay and then turn "enable cheats" off and then continue playing without exiting the game, it runs the same as when using the red overlay hack and buffered rendering is on, but when I exit out and then go back in the game is the same as in the video above.

Also there are red lines sometimes when booting it up with cheats disabled. But the red overlay usually resolves that, but I want to play with it off so the red lines still appear a lot

Performance wise it should run at either 60 or 30fps. There should be no bugs from above and the smoke bug should be clear. There should be no red lines at all. But that is all. Have a good day and I hope these issues can be resolved without upgrading my device

Samsung Galaxy s6 (yes ik my phone is old no need to tell me)
Drivers: Exynos
Mali

PPSSPP 1.11.2 or whatever the latest version is.

Here are my settings

![Scree
![Screenshot_20210219-195839](https://user-images.githubusercontent.com/66369667/108576910-48418080-72ed-11eb-855f-1cf9d94008bb.png)
![Screenshot_20210219-195845](https://user-images.githubusercontent.com/66369667/108576923-50012500-72ed-11eb-86b7-01b12208de13.png)
![Screenshot_20210219-195851](https://user-images.githubusercontent.com/66369667/108576934-57c0c980-72ed-11eb-9ea1-cb7a355a8468.png)

nshot_20210219-195822](https://user-images.githubusercontent.com/66369667/108576894-37910a80-72ed-11eb-89b2-5be130691de9.png)
![Screenshot_20210219-195828](https://user-images.githubusercontent.com/66369667/108576899-3e1f8200-72ed-11eb-9ba7-cc93bcb266d7.png)

![Screenshot_20210219-195822](https://user-images.githubusercontent.com/66369667/108577004-8b035880-72ed-11eb-9298-7bd3d7ee763e.png)

**Comment by Panderner** [comment] 2021-02-20 01:36
Do you turned off red line overlay workaround cheat and used buffered rendering?

**Comment by MojoJojoDojo** [comment] 2021-02-20 09:37
There is also that red graphics bug when you play it on PC (at least thats what i got once)...

**Comment by andy0232** [comment] 2021-02-20 15:50
> Do you turned off red line overlay workaround cheat and used buffered rendering?

That is what is causing the bugs in the 1st link and the 2 videos

**Comment by andy0232** [comment] 2021-02-20 15:51
> There is also that red graphics bug when you play it on PC (at least thats what i got once)...

Yeah it happens often but sometimes it doesn't happen but the performance is generally the same

**Comment by Gamemulatorer** [comment] 2021-05-17 00:29
This is a duplicate of #9572

**Comment by unknownbrackets** [comment] 2021-05-17 01:18
While this talks more about the performance aspects and issues going on, it's definitely the same real cause - the problems with the red overlay.  Going to close indeed as a duplicate of #9572.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-05-17 01:18 UTC
