### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MasterHalo** [hrydgard/ppsspp#7409] opened 2015-02-02 14:23 UTC
the ppsspp emulator crashes when ever I reach a certain point in the game and the game is : Crash Of The Titans

**Comment by hrydgard** [comment] 2015-02-02 14:34
What point in the game? Do you have a savegame file or a save state?

**Comment by sum2012** [comment] 2015-02-04 23:17
What device ? (Windows 32 bit,64bit,Android,ios)

**Comment by MasterHalo** [comment] 2015-02-05 14:17
Before a cutscene in crash of the Titans

**Comment by MasterHalo** [comment] 2015-02-05 14:20
Yes I have a save file and it crashes before a cutscene in crash of the Titans and it's on iOS 8.1.2

**Comment by unknownbrackets** [comment] 2015-02-05 17:01
Okay, then closing as a duplicate of #7360 (most all games crash on iOS, apparently depending on jailbreak used and possibly how many other apps you have running.)

-[Unknown]

**Closed by unknownbrackets** 2015-02-05 17:01 UTC
