### ISSUE TITLE
Optimization problem for Sonic Rivals games

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12243] opened 2019-08-14 08:35 UTC
Sonic rivals has massive lag even with somewhat enough gpu and quad-core gpu.Issue is same on every device.I already tried settings and i highly doubt my pc is potato because PPSSPP runs great on big number of games on default settings.

**Comment by hrydgard** [comment] 2019-08-14 08:42
Yes, unless you switch the graphics backend to Vulkan, where we have a fix. The game does stuff that's extremely unfriendly to modern GPUs, and I've implemented a pass that reorders rendering to work much better, but it only works with the Vulkan backend.

**Comment by HiImBrala** [comment] 2019-08-14 09:23
But what if i am playing on pc.I have Direct3d 11 Direct3d9 and OpenGL

**Comment by hrydgard** [comment] 2019-08-14 09:27
Install the latest drivers for your GPU, and Vulkan should appear (unless you have an old Intel GPU).

I might get around to implementing the workaround for OpenGL as well one day..

**Comment by LunaMoo** [comment] 2019-08-14 09:34
In case of EU versions you can use my cheats from https://github.com/LunaMoo/PPSSPP_workarounds and disable slow effects. They're correcting graphics with effects disabled, so the game should run fine even on potato/outdated pc's.

**Comment by HiImBrala** [comment] 2019-08-14 09:40
Thing is i already have new gpu and i have old intel gpu so its not helping

**Comment by HiImBrala** [comment] 2019-08-14 15:37
sorry to be boring but besides vulkan is there way to play i have d3d11 d3d9 and open gl and rendering devices microsoft basic rendering device and intel.so which one is working

**Comment by hrydgard** [comment] 2019-08-14 18:34
There's no other way right now, sorry.

**Comment by unknownbrackets** [comment] 2019-08-18 03:26
It's surely faster than it was in #6117.  Isn't this now a duplicate of #10908?

-[Unknown]

**Closed** 2019-08-26 18:45 UTC
Labels: OpenGL
