### ISSUE TITLE
Please add UMD video player browser like as JPCSP

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8060] opened 2015-10-14 01:50 UTC
The next version of PPSSPP , please developer add this
![jpcsp12](https://cloud.githubusercontent.com/assets/11285640/10472935/8df58976-7250-11e5-8aad-06a807b7369e.png)

**Comment by LunaMoo** [comment] 2015-10-14 02:09
Not exactly same, but you have an answer in #4902
~ devs are not interested in making video player out of PPSSPP.

**Comment by unknownbrackets** [comment] 2015-10-14 04:09
Well, playing the little preview video might possibly be nice.  I think this is a duplicate of #2585.

-[Unknown]

**Closed by unknownbrackets** 2015-10-14 04:09 UTC

**Comment by zminhquanz** [comment] 2015-10-14 04:38
and some game not playing sound when show the game background by controller , keyboard
