### ISSUE TITLE
[Bug] [Android] Configs are overwritten on first launch

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10670] opened 2018-03-02 11:29 UTC
When you run PPSSPP for the first time (e.g after a fresh installation or clearing app data) the configs are overwritten when you grant the storage access permission.
However, if you grant storage permission before launching the app (from phone settings) the app loads the pre-existing configs correctly.

**Comment by hrydgard** [comment] 2018-03-02 13:39
Config overwrite sounds like a bug, that's not supposed to happen, will have to look into that. That's really a separate issue from this though.

**Comment by leopard20** [comment] 2018-03-02 17:24
If you know you're not gonna accept this request (changing package name) I could change the topic and only keep the config overwrite issue. Or I could make two different posts for each one.
Which one is it gonna be?! 😉

**Comment by leopard20** [comment] 2018-03-22 12:53
@hrydgard
Were you able to reproduce the issue or should I close this?

**Comment by hrydgard** [comment] 2018-03-22 14:15
I've reproduced it, it happens when you install a slightly older version and PPSSPP loses its disk read/write permission. At that point it will generate a new config on startup, and when you give it permission it will write that new config to disk.  There are a few ways we can fix this:

  * Move PPSSPP.ini into app-specific storage. Unfortunately this makes it inaccessible from USB storage which is annoying sometimes.
  * After getting permission, re-read the config ASAP in order to not overwrite with the new one the next time it's written. However if you do a downgrade on PPSSPP and exit the app before you give it permission, you'll still be screwed.

Leaning towards the latter.

**Comment by leopard20** [comment] 2018-03-22 18:04
Taking into account what I said before:
> if you grant storage permission before launching the app (from phone settings) the app loads the pre-existing configs correctly.

Why not ask for permission automatically before the app actually starts (i.e pause the splash screen until permission is granted)? Then, once the storage permission is granted by user, and the splash screen has passed (and we're in the menu), check for existing configs, and write/overwrite configs if necessary.

I'm not sure if it'll be better. It's just an idea.

**Comment by hrydgard** [comment] 2018-03-22 19:16
Yeah, that's an idea for sure. @unknownbrackets  do you remember why we went with a button instead of automatically asking on startup?

**Comment by unknownbrackets** [comment] 2018-03-24 03:11
@hrydgard hasn't this been a bug since the permission request was first implemented in #8225?  It was for "Runtime permissions".  Wasn't it to implement permission explanation requirements/etc.?

-[Unknown]

**Comment by hrydgard** [comment] 2018-03-24 08:27
Hm, yeah, you're right. I think I'll do the minimal change for now: redesign it to always ask permission immediately on launch if existing (if rejected, the button will still be there), and reload config immediately after permission is granted. Should at least mitigate the downgrade issues.

**Comment by hrydgard** [comment] 2018-03-24 13:18
This should be pretty much fixed now.

**Closed by hrydgard** 2018-03-24 13:18 UTC
Labels: Platform-specific (Android)

**Comment by leopard20** [comment] 2018-03-24 14:30
@hrydgard 
I noticed a strange behavior. The config overwrite issue is fixed, but it seems like the app still uses the default settings on first launch. I noticed that the app runs at the default 2x PSP Display Res, while in the settings it was Native (1080p on my device). After a restart the configs are read properly.
