### ISSUE TITLE
1.5.4-997 Unavoidable crashing issue

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11069] opened 2018-05-25 00:11 UTC
This is reported by one and the same person, and unnecessarily had multiple issues replicated in this repo.

The issue is, when you go into a game, you can go through it just fine, but the catch is, it goes just fine if you're not playing a constant audio in the background, if the game tries to start playing ANY kind of constant audio background(FMVs, Main Menu songs like MHP3rd Character Select), the game will either show issues(like not playing anything at all), or just blatantly CRASH. This was tested with multiple games, namely these:

Black Rock Shooter
Dissidia 012
Fate/Extra - CCC
Final Fantasy Type-0
God Eater Burst
Kingdom Hearts
Metal Gear Solid Peace Walker
Persona 3 Portable
The 3rd Birthday

That's more than enough clue that there is a problem with this build in specific to be fixed. I have been mislead for a few hours thinking it was my HDD, but when I reverted to 1.5.4-993, everything was fixed. Like that problem never happened.
I feel like this is a issue that needs to be fixed ASAP.

EDIT: 1.5.4-995 was tested, 1.5.4-997 is the one that began the issue, 1.5.4-995 works fine.

Replicated Issues Below:
https://github.com/hrydgard/ppsspp/issues/11068
https://github.com/hrydgard/ppsspp/issues/11067
https://github.com/hrydgard/ppsspp/issues/11066

**Comment by unknownbrackets** [comment] 2018-05-25 02:19
Does this only happen when using save states?  Are you using default settings and have you verified this happens with default settings?

The changed code in v1.5.4-997-g3472d62ff affects only save states.

-[Unknown]

**Comment by AkiraJkr** [comment] 2018-05-25 03:04
Nope, I tested each game individually with and without touching savestates, mostly without, so I doubt it is a problem. Also for some reason, savestates do not work in v1.5.4-995, the game just resets.

**Comment by unknownbrackets** [comment] 2018-05-25 04:10
Strange.  I'm not reproducing any of these issues on Windows 64.  I tried The 3rd Birthday and Kingdom Hearts from your list specifically.

-[Unknown]

**Comment by AkiraJkr** [comment] 2018-05-25 18:02
Weird. I can't reproduce it anymore either. Build 997 is working just fine now, both on loading things and savestates too. I just redownloaded it for a final test and the results are it works just fine again. And this is the 7th time I redownloaded it.

**Comment by unknownbrackets** [comment] 2018-05-26 03:07
Could you have been running an app at the time?  Some people have reported features of Windows 10, like game recording features, causing PPSSPP to crash.

-[Unknown]

**Comment by AkiraJkr** [comment] 2018-05-26 05:49
Not that I remember. No. It was just Steam and Chrome, plus OVPN for going in a server...but even after closing everything, the problem had persisted. So I doubt it's one of the causes.

**Comment by unknownbrackets** [comment] 2018-05-27 02:12
Strange.  It's going to be really hard to figure this out if no one can reproduce.

It might be worth trying this (perhaps at night before you go to sleep):
https://technet.microsoft.com/en-us/library/ff700221.aspx

The same instructions should work for Windows 10 as well.  This will run a test of your RAM, in case there's a hardware issue.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-06-16 15:40
I'm going to close this now.  Sounds like it's possibly hardware related or caused by other software.

If it happens again or you find more information, please comment and we'll reopen.

I think the other 3 issues are actually sceAtrac or similar bugs in emulation, and not related to this problem.

-[Unknown]

**Closed by unknownbrackets** 2018-06-16 15:40 UTC
Labels: No Feedback / Outdated?
