### ISSUE TITLE
Motorstorm Arctic Edge Vehicle Select Screen Crash

### ISSUE THREAD

**Issue by Defreezer** [hrydgard/ppsspp#17624] opened 2023-06-26 05:41 UTC
### Game or games this happens in

UCES01250 - Motorstorm Arctic Edge

### What area of the game / PPSSPP

Not an emulator issue. Sorting through the vehicle select screen as the game loads the different vehicle models (no savedata needed) crashes the game in two ways when the 60 fps cheat is in use: Either by stopping with the crash log shown below (usually happens when coming back to the vehicle select screen after finishing a race) or by softlocking. It happens regardless of backend.

The cheat in question dates from January 2017 (likely tested on build 1.3?) and is as follows:
_C1 60 FPS
_L 0xE0060001 0x102794A8
_L 0x20010858 0x34050001
_L 0x200C379C 0x34040001
_L 0x200C539C 0x34040001
_L 0x202794A8 0x00000001
_L 0x2011CDB8 0x3C043F00
_L 0x2029EAB8 0x3C88AB86

![35645](https://github.com/hrydgard/ppsspp/assets/79490923/b4a18925-35a1-4880-9ebb-fecfbe82968a)

### What should happen

Just wanted to report this very minor issue on the off-chance that a workaround would be considered, since this game still has performance issues that are resolved/sidestepped by cheats. Unless it requires a more sophisticated 60 fps cheat? It's quite an essential improvement at this point. Sorry for the inconvenience.

### Logs

[log.txt](https://github.com/hrydgard/ppsspp/files/11861520/log.txt)

### Platform

Windows

### Mobile phone model or graphics card

RX 570 4gb

### PPSSPP version affected

v1.2.2
v1.3
v1.15.3
v1.15.4-267-gf02ccfc6d

### Last working version

v1.0.0 (possibly)

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2023-06-26 12:41
Have you confirmed that the cheat worked on PPSSPP v1.3 or any old version ?
Because if it's only known to work on a real PSP, it may or may not worked on PPSSPP due to different memory allocations, thus some addresses might be different between real PSP and PPSSPP.

**Comment by Defreezer** [comment] 2023-06-26 14:10
I've just tested with 1.3 and yeah, it also crashes. This particular cheat was designed for PPSSPP, while real PSPs have a separate, specialized dynamic FPS cheat that is not to be used in an emulator. They originate from here:
https://forums.ppsspp.org/showthread.php?tid=4799&pid=125104#pid125104

**Comment by LunaMoo** [comment] 2023-06-29 03:16
If the cheat didn't caused a crash in some past version just ask it's author to update.

Closing in favour of https://github.com/hrydgard/ppsspp/issues/11167
PPSSPP memory allocation is not perfect and whenever it improves it breaka most cheats which depend on variables stored in the game memory. I can blindly guess 3 last lines of that cheat are doing exactly that. Preferably the author should check which code wrote those variables and change the code instead of variables themselves as that's often not safe even if memory management would match PSP.

**Closed** 2023-06-29 03:17 UTC
Labels: Cheats
