### ISSUE TITLE
MHP3RD HD(npjb40001) still force close

### ISSUE THREAD

**Issue by John-Wicky101** [hrydgard/ppsspp#14322] opened 2021-03-27 11:09 UTC
Yeah,, I tried again to play MHP3RD HD (NPJB40001) on every latest version of ppsspp. But I still get error(force close).
Here I use on Android 10 Samsung Galaxy A6+. But when I played the game on ppsspp v1.4 and below, everything went well but the speed dropped not the same when using the latest version. 
Here I use ppsspp v1.4. It's possible that game can run properly because there is a hack setting (disable alpha test). But the texture has become very ugly.

![20210327_174356](https://user-images.githubusercontent.com/81464443/112718264-c941f800-8ee9-11eb-83c9-78743300059e.jpg)

I really hope to be able to play that game on the latest version of PPSSPP.

**Comment by nassau-tk** [comment] 2021-03-28 01:49
When did you shut down the game?
1. Boot => shut down?
2. In game (in village? in field?) => shut down?

**Comment by Gamemulatorer** [comment] 2021-03-28 19:37
Duplicate of #11410

**Comment by unknownbrackets** [comment] 2021-03-28 21:33
This issue is being closed as a duplicate of #11410.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it (even if you *still* didn't have it yet), right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-03-28 21:33 UTC
