### ISSUE TITLE
[libretro] Black boxes over text in many games (offending commit identified)

### ISSUE THREAD

**Issue by hizzlekizzle** [hrydgard/ppsspp#18483] opened 2023-12-07 05:46 UTC
### Game or games this happens in

ULUS-10522 Disgaea Infinite

### What area of the game

The very first screen with the gray background and white menu text. This problem happens in a lot of games but this is a very easy one to test.

### What happens

Instead of the normal white text, each letter is replaced with a black box. This started with commit 5373b8c5b3838aa22bccb2f3e181d2684ca00aea. It happens with both vulkan and opengl renderers, so I figure it's the bit in TextureCacheCommon.cpp where it refuses to load invalidly sized textures (i.e., ones >512x512), as this appears in the log:
`[libretro ERROR] [G3D] Bad texture dimensions: 2048x2048`
This was reported on the RetroArch subreddit by someone using Android, but I was able to reproduce it in desktop Linux. I checked against standalone/Qt PPSSPP and the problem doesn't happen there, so it's libretro-specific.

### What should happen

The text should render readable and white instead of black boxes, like this:
![image](https://github.com/hrydgard/ppsspp/assets/2805586/2ab8387b-601e-49aa-b940-f96b70b43586)

### GE frame capture

![image](https://github.com/hrydgard/ppsspp/assets/2805586/69f942a4-5729-4014-b79e-26d49f30c187)

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

Intel IGP

### PPSSPP version affected

all builds since 5373b8c5b3838aa22bccb2f3e181d2684ca00aea

### Last working version

fb8ad0c33a5ea173d0cb3289b3773492f976d9e7

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by justafella** [comment] 2023-12-07 13:50
I had a similar issue to report. I've downloaded the latest build but for me there is still something missing: the selector rectangle.

Before latest build:
![Screenshot_2023-12-07-09-19-48-542_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/65559598/94272fd5-244a-440f-985d-467522a34cd4)

After latest build:
![Screenshot_2023-12-07-09-46-03-446_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/65559598/3047112b-cb05-4115-a131-b28cc4bc543d)

I can still save/load from deduction

**Comment by hizzlekizzle** [comment] 2023-12-07 14:00
@hrydgard oh man, thanks for the rapid response! Cheers!

**Comment by hispanico957** [comment] 2023-12-07 14:18
I update now the core but the problem is present, i try Ace Combat and Fifa 14

[img]https://i.ibb.co/4Wd996W/20231207-151535.png[/img]
[img]https://i.ibb.co/Y0Nk39h/20231207-151511.jpg[/img]

Hispa

**Comment by hrydgard** [comment] 2023-12-07 14:25
Okay, that's really weird.. reopened.

**Comment by bslenul** [comment] 2023-12-07 16:55
It's normal, the updated version of the core is not yet available from the core downloader, atm it's still downloading a previous version where the issue is not fixed yet.

But I can confirm it's fixed (tested with 8dab823936ac573e8ac0a9d020a86deb881eaf4c):

![image](https://github.com/hrydgard/ppsspp/assets/33353403/ac1f3b9b-6691-48e7-ab9c-e8bc179138f2)

**Comment by LunaMoo** [comment] 2023-12-07 16:59
Thanks for the input @bslenul closing again.

**Closed by LunaMoo** 2023-12-07 16:59 UTC

**Comment by hispanico957** [comment] 2023-12-07 17:43
YESSSSSSSS i try games and confirm :-) 

**Thank mate**
Hispa
