### ISSUE TITLE
Missing text in Lunar : Silver Star Harmony

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8262] opened 2015-12-09 11:35 UTC
![untitled 1](https://cloud.githubusercontent.com/assets/11285640/11684337/9195a410-9ea3-11e5-8de6-3b00a94405ac.png)
Red square is missing text

**Comment by vsub** [comment] 2015-12-09 11:42
All text looks fine if you use the fonts from your psp.
It's known problem with this game

**Comment by unknownbrackets** [comment] 2015-12-11 12:18
Closing as a duplicate of #2788.

-[Unknown]

**Closed by unknownbrackets** 2015-12-11 12:18 UTC
