### ISSUE TITLE
medal of honor 2 usa

### ISSUE THREAD

**Issue by livisor** [hrydgard/ppsspp#9304] opened 2017-02-13 23:20 UTC
Hey guys, I am starting to become active again and will try to test as many bugs as possible with the newest release and close old issues which have been solved but not tested.
I have medal of honor usa version and the textures are all bad, here are the issues from the debug log:

11:56:035 user_main    W[G3D]: Common\FramebufferCommon.cpp:918 Memcpy fbo upload 04400000 -> 04000000
11:56:038 user_main    W[G3D]: Common\TextureCacheCommon.cpp:377 Render to texture with incompatible formats 3 != 0 at 00000000

11:56:241 user_main    E[IO]: HLE\sceIo.cpp:1873 UNIMPL sceIoChangeAsyncPriority(4, 107)

11:56:496 user_main    W[KERNEL]: HLE\sceKernelSemaphore.cpp:236 sceKernelCreateSema(SNDMUTEX) unsupported options parameter, size = 167768800

11:56:499 user_main    E[AUDIO]: HLE\sceAudio.cpp:263 sceAudioSetChannelDataLen(00000000, 00000200) - channel not reserved

11:56:665 user_main    W[ME]: HLE\sceMpeg.cpp:1671 Audio end reach. pts: 105968 dts: 735735

12:01:572 user_main    W[KERNEL]: 266e7aa46db16f98\Core/HLE/sceKernel.h:457 Kernel: Bad object handle 304 (00000130)

**Comment by LunaMoo** [comment] 2017-02-14 08:17
Best way to be active is to use search before posting :] aka this is a known issue.
Closing as duplicate of #3607

**Closed by LunaMoo** 2017-02-14 08:17 UTC
