### ISSUE TITLE
Some games cutscene video unplayable/flickering

### ISSUE THREAD

**Issue by C4rrotMilk** [hrydgard/ppsspp#10862] opened 2018-04-03 06:17 UTC
What happens?
Final Fantasy Type 0
Some cutscene unplayable(Blackscreen and no sound at all,but skip-able)

Shin Sangoku Musou 5 Speacial
Cutscene Flickering

Cutscene play normally on 1.4 and older version

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Snapdragon 801 Adreno 330 OpenGL Backend

**Comment by C4rrotMilk** [comment] 2018-04-03 06:19
Forgot to say i using newest Dev build v1.5.4-819-gd70568abd

**Comment by MorrisonGamer** [comment] 2018-04-04 00:48
Can confirm this happens.

Final Fantasy Type-0
Movies were previously working JUST fine, never flickering, full speed even with frameskip off, now they are randomly flickering, but still work fine. Tested with Simulate Block Transfer effect on/off.

Specs on info box: http://steamcommunity.com/id/AkiraPlays

**Comment by unknownbrackets** [comment] 2018-04-04 01:03
This sounds like a duplicate of #10694?

Interesting that it's happening on an Intel card too.

-[Unknown]

**Comment by MorrisonGamer** [comment] 2018-04-04 01:13
Well, I'm not having any blackscreen, but I've never felt flickering audio on the opening scene or any movies in Type-0. No matter what settings I change, FPS remains the same, 30/100% speed and the audio just randomly flickers. Never happened before.

**Comment by hrydgard** [comment] 2018-04-05 17:57
Can you go back and find the first build where this problem appears?

**Comment by C4rrotMilk** [comment] 2018-04-07 10:29
v1.4.2-199-g3249d8165 is the last build tht still work properly

**Comment by hrydgard** [comment] 2018-04-07 11:29
So 1.4.2-208 doesn't work? That would implicate https://github.com/hrydgard/ppsspp/pull/9810 which seems a bit unlikely..

**Comment by C4rrotMilk** [comment] 2018-04-07 13:05
It doesn't work on 1.4.2-208,something might be messed up in 1.4.2-200 maybe.I have zerp knowledge about coding,sry can't help u on this :(

**Comment by hrydgard** [comment] 2018-04-07 14:12
Hm. Do the various I/O timing settings under Settings/System make any difference?

**Comment by unknownbrackets** [comment] 2018-04-07 14:35
If this is happening specifically with Type-0, my recollection is that it was > 2GB.

Does it happen even when compressed as cso, or does that affect it?  Note that not all compressors support >= 2GB files, but maxcso for example does.

-[Unknown]

**Comment by C4rrotMilk** [comment] 2018-04-08 12:53
It worked just like Unknown said,can close the issue now

Thanks for the trouble :)

**Comment by unknownbrackets** [comment] 2018-04-08 16:14
Can you try this again - with the original iso - to see if that bug is fixed?

It's better to use the cso, but want to make sure people using the iso without knowing that don't get crashes.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-04-09 03:31
Also, is Shin Sangoku Musou 5 Special also fixed by using a cso?  How large is that ISO?

-[Unknown]

**Comment by C4rrotMilk** [comment] 2018-04-09 13:46
The bug is fixed,Shin Sangoku is around 1.5GB but i don't have the game right now,have to ask my friend test it later.

**Comment by C4rrotMilk** [comment] 2018-04-10 07:09
Shin Sangoku got fixed as well,guess can finally close the issue now.

Thanks for the hardwork 🙂

**Comment by unknownbrackets** [comment] 2018-04-10 14:01
Thanks - I'm going to close.  @MorrisonGamer it sounds like your issue might be a different one?  Can you open a new issue if it still happens?

-[Unknown]

**Closed by unknownbrackets** 2018-04-10 14:01 UTC
Labels: Platform-specific (Android)
