### ISSUE TITLE
NFS:MW 5.0.1 framedrop map/area

### ISSUE THREAD

**Issue by cheding09** [hrydgard/ppsspp#11764] opened 2019-02-05 03:39 UTC
### What happens?

On Great Northern Way map, both Forward and Reverse have the same area where the Framedrop occurs and this is the only Map/area that has framedrop issue.

OpenGL✔
Buffered Rendered✔
Block Effect✔
Frameskip Off / Autoskip On

https://m.youtube.com/watch?feature=youtu.be&v=JagsP4WScDI
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/2830624/PPSSPP_STATE.zip)
![screenshot_20190236-105438](https://user-images.githubusercontent.com/39876882/52251718-8dc6c700-2939-11e9-8715-8debef2d188e.JPEG)

By the way Im using 15Fps cheat because this Fps suits the Game with a better performance .

[ULUS10036.zip](https://github.com/hrydgard/ppsspp/files/2830639/ULUS10036.zip)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PpsspP 1.7.5-403

My Unit::
CloudFone Excite Prime
2GB ram
1.3ghz ARMv7 8cores
Mali-450 (720x1280)
OpenGL 2.0

**Comment by Emulatorer** [comment] 2019-02-05 03:45
We same unit lol 🤣
here's my video settings
https://youtu.be/p1CNWwe-dpA
Im using 20 fps cheat code Im also experiencing a frame drop from a certain map or areas

**Comment by cheding09** [comment] 2019-02-05 03:51
Its because we are on the same Group in FB👍😂 and yeah I already watched almost all of the Psp games you uploaded on Youtube 👍. 20Fps is Good but many areas has Framedrop promblem with that Fps thats why I try to edit the cheat down to 15fps and its somehow better now .

**Comment by Emulatorer** [comment] 2019-02-05 04:03
Frameskipping x1 = 15 fps no need for 15fps cheat code because NFS Most Wanted 5-1-0 Maximum FPS is 30 🤔
30fps is reduced by half when frameskipping is set to x1 :)

**Comment by cheding09** [comment] 2019-02-05 04:09
Tried and tested that, but it really is better with Frameskip:Off and 15Fps and all the other options to be default👍

**Comment by Emulatorer** [comment] 2019-02-05 06:38
Didn't notice any major fps drops from the latest build v1.7.5-403 vs v1.7.5 Playstore
My settings are both the same but I use your savestates 🤔

### PPSSPP Latest Build
![screenshot_2019-02-05-14-27-54](https://user-images.githubusercontent.com/37603562/52256822-35042800-2953-11e9-83f1-9cd2a024c6c2.png)
![screenshot_2019-02-05-14-27-40](https://user-images.githubusercontent.com/37603562/52256846-4816f800-2953-11e9-8304-f11307c09b97.png)
### PPSSPP v1.7.5 Playstore
![screenshot_2019-02-05-14-26-50](https://user-images.githubusercontent.com/37603562/52256894-6f6dc500-2953-11e9-808b-f23c0bac8be3.png)
![screenshot_2019-02-05-14-26-42](https://user-images.githubusercontent.com/37603562/52256904-7a285a00-2953-11e9-8654-62f0933cd662.png)

**Comment by marosis** [comment] 2019-02-05 07:18
This framedrop i can confirm.

**Comment by cheding09** [comment] 2019-02-05 07:52
@Emulatorer - the FPS drop on your video is at 1:40 
https://m.youtube.com/watch?v=p1CNWwe-dpA&feature=youtu.be

**Comment by Emulatorer** [comment] 2019-02-05 08:10
@cheding09 that's normal because the framedrops was cause by my screen recording app without screen recording the game only framedrops from 1-2 fps not a major problem for me 🙂

**Comment by cheding09** [comment] 2019-02-05 08:47
Ayayay . You really dont get it or me, oh well. I'll just wait for the others to see this👍

Thanks to the developer of this emulator and to those who are working hard to fix bugs and issues of this emulator👍

**Comment by Emulatorer** [comment] 2019-02-05 09:01
@marosis thanks for subscribing

@cheding09 I know what you mean that ares has e framedrops only in the latest build but didn't happen in v1.7.5 stable version?

but for me as I tested nothing changes in thw performance from v1.7.5 stable version vs the latest build that area always have a frame drop and for me is not an issue it's the hardware specifications that's really matters as we both have the same unit/device using 😅

so wait for the developers if they can really do solve this issue or not 🙂
but for me the only way to fixed this issue is to buy a new phone with 64bit processors and then use 20fps cheat code then problem solve 👍

sorry for the long reply and for my poor english (tagalog is my native language)

**Comment by Emulatorer** [comment] 2019-02-10 12:49
@cheding09 try to capture the GE
debbuger frame log using your android phone so that's the developers know how to fixed this issue

http://ppsspp-debugger.unknownbrackets.org/gpu

**Comment by GuilhermeGS2** [comment] 2019-02-12 17:39
This issue is likely due to weak hardware (Cortex-A7 CPU). Consider buying a new phone with at least Cortex-A53 CPU, which can handle this game fine with default settings. Be awere that using low cpu clocks and cheats also can cause performance problems, but it doesn't seem to be the case here.

**Comment by cheding09** [comment] 2019-02-13 05:54
My problem is already solve and playing in full perfomarnce now . 99-100% speed in all maps👍

I'm using a Force 15Fps cheat - 
Buffered render - 
Frameskip off - 
X3 Auto resolution - 
All Speed up option checked-
Artifacts in Aggresive mode-
Cpu clock 90mhz(this solve my problem)-

PS : I have notice that 15Fps cheat + frameskip off is FAR way different from 60 or 30fps + Frameskip 1/2/3/4,etc. Also I have tested in on NFS Undergroud Rivals, Carbon Own the City and NFS undercover . Though Carbon OTC and Undercover are playable at 10-15Fps(via cheat)

**Comment by Emulatorer** [comment] 2019-02-13 09:31
@cheding09 you can close this issue now 🤔

**Closed** 2019-02-14 08:39 UTC
