### ISSUE TITLE
Tilt control doesn't work

### ISSUE THREAD

**Issue by VoidXH** [hrydgard/ppsspp#7475] opened 2015-02-14 11:38 UTC
That's all. Tilting doesn't work on iOS nor Android.

**Comment by unknownbrackets** [comment] 2015-03-03 06:41
Tilt works fine for me on Android.  Have you checked the settings and calibration?

-[Unknown]

**Comment by VoidXH** [comment] 2015-03-03 07:19
Yes. It still doesn't work with the latest commit.

**Comment by unknownbrackets** [comment] 2015-03-03 07:22
What device are you using?  Does tilt work in other applications / games?

Are you sure that you've set it to the right input method?  For example, some games do not respond to the analog stick, so you must use the d-pad.  If tilt is not associated with the d-pad, it will do nothing.

-[Unknown]

**Comment by VoidXH** [comment] 2015-03-03 07:27
I have an iPhone 5S, but I tried it on a Galaxy Ace III too, with an older version. None worked. Tilting works in other apps. The D-Pad setting also doesn't work.

**Comment by unknownbrackets** [comment] 2015-03-03 07:33
I think this is just a duplicate of #6438.  Unfortunately, we don't have any iOS developers actively maintaining things right now.

-[Unknown]

**Closed by unknownbrackets** 2015-03-03 07:33 UTC
