### ISSUE TITLE
Retroarch Windows PPSSPP God of War games black screen and not responding

### ISSUE THREAD

**Issue by carlhr93** [hrydgard/ppsspp#12622] opened 2020-02-11 23:33 UTC
### What happens?
As the title says, God of War games not working (Chains of Olympus and Ghost of Sparta), I have 40 PSP games and they all run (they boot at least) but God Of War games just show a black screen and don’t do anything after, no logos, just nothing, I’ve tried with a clean Retroarch installation with the same results, obviously I have the assets folder in place, I tried using iso and cso files, trying files with different regions (I was able to see a warning screen for epilepsy stuff in Ghost of Sparta but then it stops working) and nothing seems to fix it… core is updated, latest version and even my phone can boot the game with no problems at all

### What *should* happen?
The games work on my phone, they should work on my PC and as I said, I tested with a clean install of Retroarch and that didn't work either.

### What hardware, operating system, and PPSSPP version? 
Ryzen 3600, GTX 1080, 16GB RAM, Windows 10 Pro 64 Bit, Version 1909, PPSSPP version is the latest available in Retroarch (0b17dd0)

Thanks in advance!

**Comment by unknownbrackets** [comment] 2020-03-08 22:56
The same games work fine for you in PPSSPP proper, right?

I seem to remember these games require buffered rendering and flip the screen differently than other games do.

-[Unknown]

**Comment by carlhr93** [comment] 2020-04-09 22:31
Sorry, didn't see the answer, lol.

Yeah, the games work fine in the standalone PPSSPP and in Retroarch with my Phone, is just Retroarch PPSSPP with my PC that is not booting, even with a clean installation and different drivers (gl or vulkan)

**Comment by igoracmelo** [comment] 2021-06-21 18:16
In my case RetroArch just crashes when I try to open Chains of Olympus.
Ghost of Sparta worked fine though.

**Comment by Sanaki** [comment] 2021-06-22 04:11
That's a different issue, and is likely a simpler one (probably outdated or missing assets).
This explains how to place/update the assets in question if need be. If this does not solve your issue, I recommend you inquire further on the libretro discord, since we can likely help you there without derailing this issue.
https://docs.libretro.com/library/ppsspp/#bios

**Comment by gouchi** [comment] 2021-08-14 22:16
I could not reproduce the issue. GoW games are working fine.

@carlhr93 if you don't reproduce the issue anymore please close it.

**Comment by Sanaki** [comment] 2021-08-16 19:06
I used to be able to reproduce this by disabling audio sync (to bypass the freeze on close content with glcore), then opening the game, closing it, and opening it again. I can no longer reproduce the issue in this fashion.

I tried it with vulkan as well (which doesn't have the async bug), and equally could not reproduce it. I think this issue is indeed resolved.

**Comment by unknownbrackets** [comment] 2021-08-17 04:41
Great, I'm going to close this then - if it was broken before and isn't now, that sounds like fixed.

@carlhr93, if you're still seeing this after all just comment and we can reopen.

-[Unknown]

**Closed by unknownbrackets** 2021-08-17 04:41 UTC
Labels: Libretro
