### ISSUE TITLE
Me & My Katamari Fog/Draw Distance coloured solid plane/pixel garbage

### ISSUE THREAD

**Issue by fpiesche** [hrydgard/ppsspp#8721] opened 2016-05-06 21:19 UTC
This has been reported in the past, but ended up being rolled into (har) other issues. I'm running the 64bit Windows build of 1.2.2-353-ga4ca07e on Windows 10 in OpenGL (though the problem also occurs on DirectX).

Me & My Katamari has what looks like a clipping plane or fog in levels that is rendering as a solid single-colour plane or with patterns of transparent pixels in its texture (see attached screenshot). There is no fog or visible effect attached to the screen regions this covers on actual hardware, however.

This is very visible when the Katamari is about 10m in size, and moves closer to it as it grows; once the katamari reaches around 20-25m it's sitting basically right in front of it, rendering the game pretty much unplayable. The first level this becomes very obvious in is the Cicada level; it's visible right from the start here and within about a minute or two of gameplay blocks you from seeing pretty much anything at all.

Stepping through things in the GE debugger, the texture causing this is 04288000, which is drawn immediately after the Katamari itself. Looking at the debugger it seems the game's drawing this across the entire screen in stripes, as a white-ish texture, before a few further instructions cause the entire thing to turn brightly coloured (with the colour consistent within levels, but differing between levels and even segments within them - in the Cicada level it starts out orange and turns cyan once the level moves on to "night").

Comparing the emulated game to a real PSP, I can't see anything on the screen in that region - there MIGHT be a very, very subtle dithered grain effect in the portion of the screen this covers? I've only got a PSP-3000 to hand so I'm not sure if that's just the (notorious for being slightly grainy) screen on that model or actually a subtle grain effect on the game. The way that the game draws it across the entire screen certainly seems to suggest some kind of fog effect or such to me...

![screenshot 2016-05-06 21 34 52](https://cloud.githubusercontent.com/assets/393620/15085479/8271cbc2-13d2-11e6-8e2b-da58b1934855.png)

**Comment by unknownbrackets** [comment] 2016-05-07 03:17
This game uses 0x04088000 for the depth buffer.  When it textures from 0x04288000, it's trying to use the depth as a texture - possibly to create an effect based on how far away things are.

I think this is the same as #7695 / #6411.

I'm not sure if this is a draw distance issue as much as a drawing-garbage issue.  Since we don't support depth buffering, the game draws whatever happens to be at 0x04088000.  In some ways, it might be more ideal to intentionally draw a black transparent texture instead of garbage.

-[Unknown]

**Comment by hrydgard** [comment] 2016-05-07 07:45
Yeah, we could either decide that all textures from the "vram mirrors" read as zero or that textures whose address matches that of a depth buffer of a recent framebuffer read as zero. Both would probably solve it and not break games that don't rely on this feature...

Or we could implement depth texturing properly but that's a bit complicated - for one thing, we keep around duplicates of depth buffers right now as we attach them to color buffers instead of treating them as a separate thing (due to the stencil/alpha issue). Which one to texture from? Hm, maybe simply avoid the one attached to the framebuffer being rendered to...

**Comment by fpiesche** [comment] 2016-05-07 14:25
Just as an aside, the main reason I marked this as "draw distance" is that that seems to be a common thing people refer to the problem as from my googling around to figure out if there's a workaround or such :)

**Comment by unknownbrackets** [comment] 2016-05-20 04:16
Okay, closing this as a duplicate of #6411.

-[Unknown]

**Closed by unknownbrackets** 2016-05-20 04:16 UTC
