### ISSUE TITLE
Update ppsspp 1.8.0 linuxbuilds

### ISSUE THREAD

**Issue by mrdeathjr28** [hrydgard/ppsspp#11889] opened 2019-03-14 15:28 UTC
### What happens?

PPSSPP linuxbuilds dont have 1.8.0 version

https://build.ppsspp.org/?page/downloads#linux

### What *should* happen?

PPSSPP 1.8.0 must be stay avalaible on linuxbuilds

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Nvidia Drivers 418.31 (run package from nvidia drivers homepage)

Xubuntu 18.04 x64 - Kernel 4.17.12 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + CoolerMaster Hyper T4

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by hrydgard** [comment] 2019-03-14 16:05
@angelXwind  maintains that build thing...

**Comment by mrdeathjr28** [comment] 2019-03-14 16:18
> @angelXwind maintains that build thing...

Hi this downloads is official builds right ?

**Comment by josehfurtado** [comment] 2019-06-20 08:35
Flathub have 1.8.0 version. [https://github.com/flathub/org.ppsspp.PPSSPP](url) . Hope they keep this package updated.

**Comment by TranceLove** [comment] 2020-02-01 15:45
If you are using Ubuntu who misses the [PPA](https://launchpad.net/~ppsspp/+archive/ubuntu/stable) so much, I tried to reproduce one using the files found on [the git repository the PPA uses](https://git.launchpad.net/~ppsspp/ppsspp/+git/debian/), so I can enjoy a 1.9.4 with OpenGL on an Ubuntu Disco w/ Wayland on my GPD WIN 1. Only a 5-minute check with Densha de Go, seems working.

No, I'm not the one to provide Ubuntu builds, just some guide to build your own `.deb` package.

And I made it into a repository so it looks better than a github gist. 

[TranceLove/ppsspp-debian](https://github.com/TranceLove/ppsspp-debian)
(OK, the name is so misleading...)

If anyone want to take over, please do.

**Comment by unknownbrackets** [comment] 2021-01-03 19:04
Closing this since we have #11661 and other issues for this already.  Additionally, you can download a build (not sure which versions of Linux it will work on, though) from GitHub Actions builds now.

-[Unknown]

**Closed by unknownbrackets** 2021-01-03 19:04 UTC
