### ISSUE TITLE
Disgaea: Afternoon of Darkness (ULES 00999) crash

### ISSUE THREAD

**Issue by q3cpma** [hrydgard/ppsspp#11463] opened 2018-10-09 20:08 UTC
### What happens?
I've had one recurrent crash in this game when some monster in the Item World casts "Giga Wind" on my team and a recent one (which is the one concerned here): when my archer casts "Zielregen" in the Item World with some other unknown conditions (it didn't crash before I changed my bow to an "Infernal Bow")

### What *should* happen?
No crash.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
With ppsspp 1.6.3 with the opengl backend
AMD FX-8350, AMD RX580
Gentoo GNU/Linux with mesa 18.1.9

Here's the full backtrace:
```
(gdb) bt full
#0  0x0000000040172146 in ?? ()
No symbol table info available.
#1  0x00007fffd67fc700 in ?? ()
No symbol table info available.
#2  0x00007fffd67fc700 in ?? ()
No symbol table info available.
#3  0x00007fffd5ffc000 in ?? ()
No symbol table info available.
#4  0x00007fffffffdd9f in ?? ()
No symbol table info available.
#5  0x00005555565621c0 in ?? ()
No symbol table info available.
#6  0x000000000152bec0 in ?? ()
No symbol table info available.
#7  0x00004e07bc660d65 in ?? ()
No symbol table info available.
#8  0x000055555581e0e2 in MIPSComp::Jit::RunLoopUntil (this=<optimized out>, globalticks=<optimized out>) at /home/hadrien/Downloads/ppsspp-1.6.3/Core/MIPS/x86/Jit.cpp:313
No locals.
#9  0x00005555557d54fd in MIPSState::RunLoopUntil (this=<optimized out>, globalTicks=150323855360, globalTicks@entry=85795132542309) at /home/hadrien/Downloads/ppsspp-1.6.3/Core/MIPS/MIPS.cpp:314
No locals.
#10 0x00005555558028b1 in PSP_RunLoopUntil (globalticks=85795132542309) at /home/hadrien/Downloads/ppsspp-1.6.3/Core/System.cpp:430
No locals.
#11 0x00005555558028da in PSP_RunLoopFor (cycles=22200000, cycles@entry=1) at /home/hadrien/Downloads/ppsspp-1.6.3/Core/System.cpp:435
No locals.
#12 0x0000555555637aaa in EmuScreen::render (this=0x7fffbc032ca0) at /home/hadrien/Downloads/ppsspp-1.6.3/UI/EmuScreen.cpp:1202
        thin3d = <optimized out>
        blockTicks = <optimized out>
#13 0x00005555559f90dd in ScreenManager::render (this=0x5555562dd870) at /home/hadrien/Downloads/ppsspp-1.6.3/ext/native/ui/screen.cpp:145
No locals.
#14 0x00005555556219a0 in NativeRender (graphicsContext=0x5555565218b0) at /home/hadrien/Downloads/ppsspp-1.6.3/UI/NativeApp.cpp:879
        xres = 960
        yres = 544
        ortho = {{{xx = 0.00208333344, xy = 0, xz = 0, xw = 0, yx = 0, yy = -0.0036764706, yz = 0, yw = 0, zx = 0, zy = 0, zz = 1, zw = 0, wx = -1, wy = 1, wz = -0, ww = 1}, m = {0.00208333344, 0, 0, 0, 0, -0.0036764706, 0, 0, 0, 0, 1, 0, -1, 1, -0, 1}}}
#15 0x00005555556d8df1 in UpdateRunLoop () at /home/hadrien/Downloads/ppsspp-1.6.3/Core/Core.cpp:193
No locals.
#16 0x00005555555e27b5 in MainUI::EmuThreadFunc (this=0x5555562dc900) at /home/hadrien/Downloads/ppsspp-1.6.3/Qt/QtMain.cpp:203
No locals.
#17 0x00005555555e27e5 in MainUI::<lambda()>::operator() (__closure=<optimized out>) at /home/hadrien/Downloads/ppsspp-1.6.3/Qt/QtMain.cpp:213
        this = <optimized out>
        this = <optimized out>
#18 std::__invoke_impl<void, MainUI::EmuThreadStart()::<lambda()> > (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/invoke.h:60
No locals.
#19 std::__invoke<MainUI::EmuThreadStart()::<lambda()> > (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/invoke.h:95
No locals.
#20 std::thread::_Invoker<std::tuple<MainUI::EmuThreadStart()::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/thread:234
No locals.
#21 std::thread::_Invoker<std::tuple<MainUI::EmuThreadStart()::<lambda()> > >::operator() (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/thread:243
No locals.
#22 std::thread::_State_impl<std::thread::_Invoker<std::tuple<MainUI::EmuThreadStart()::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/thread:186
No locals.
#23 0x00007ffff48f25ce in std::execute_native_thread_routine (__p=0x55555653b850) at /tmp/portage/sys-devel/gcc-7.3.0-r3/work/gcc-7.3.0/libstdc++-v3/src/c++11/thread.cc:83
        __t = std::unique_ptr<std::thread::_State> containing 0x55555653b850
#24 0x00007ffff7bbf8da in start_thread (arg=0x7fffd67fc700) at pthread_create.c:465
        pd = 0x7fffd67fc700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736792086272, -2972774388951905183, 140737488346526, 140737488346527, 140736783695872, 140736792086272, 2972720514849868897, 2972791396913679457}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#25 0x00007ffff3ffb10f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```
Here's the log: https://my.mixtape.moe/rytlfg.log
and the save (xz compressed): https://my.mixtape.moe/yqxsjt.xz

**Comment by unknownbrackets** [comment] 2018-10-10 05:10
You've attached a save state.  Sometimes save states carry along with them bugs from previous versions, so it's hard to tell the cause.

Just to be sure: if you go back, save the game as you would on a real PSP, restart PPSSPP and the game without using any save states, and then load the in-game save - does it still happen?

This will reset things that might've been broken at some point by using cheats, hacks, or CPU clock adjustments.  I can tell something "dangerous" has been done for this save state, because there's a flag in the save state saying as much.  The flag makes it so we prevent reporting any errors to the compatibility server, because a setting or cheat has been used that is known to cause false errors.

The flag can also be set if the fonts weren't found in the right path, so I could be wrong:
https://github.com/hrydgard/ppsspp/tree/master/assets/flash0/font

Anyway, the crash is from the PSP game itself making an invalid memory access.  If this happened on a real PSP, the PSP would just turn itself off.

There is a setting to "ignore illegal memory access" (on by default - but only works when "fast memory" is off), and the game is able to power through the bug with this setting on.  So if you're just wanting to try to recover your save state, it's possible to just turn off "fast memory".

If this does actually happen without using save states or dangerous settings, then it's a bug we should fix, though.  Turning off "fast memory" is a hack, basically.

-[Unknown]

**Comment by q3cpma** [comment] 2018-10-10 14:09
On Tue, Oct 09, 2018 at 10:10:18PM -0700, Unknown W. Brackets wrote:
> You've attached a save state.  Sometimes save states carry along with them bugs from previous versions, so it's hard to tell the cause.
>
> Just to be sure: if you go back, save the game as you would on a real PSP, restart PPSSPP and the game without using any save states, and then load the in-game save - does it still happen?
>
> This will reset things that might've been broken at some point by using cheats, hacks, or CPU clock adjustments.  I can tell something "dangerous" has been done for this save state, because there's a flag in the save state saying as much.  The flag makes it so we prevent reporting any errors to the compatibility server, because a setting or cheat has been used that is known to cause false errors.
>
> The flag can also be set if the fonts weren't found in the right path, so I could be wrong:
> https://github.com/hrydgard/ppsspp/tree/master/assets/flash0/font
>
> Anyway, the crash is from the PSP game itself making an invalid memory access.  If this happened on a real PSP, the PSP would just turn itself off.
>
> There is a setting to "ignore illegal memory access" (on by default - but only works when "fast memory" is off), and the game is able to power through the bug with this setting on.  So if you're just wanting to try to recover your save state, it's possible to just turn off "fast memory".
>
> If this does actually happen without using save states or dangerous settings, then it's a bug we should fix, though.  Turning off "fast memory" is a hack, basically.
>
> -[Unknown]
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/hrydgard/ppsspp/issues/11463#issuecomment-428439849


Indeed, using a save instead of a savestate prevents the crash. Now, I'd really
like to know the "why" here, since I've been on 1.6.3 since the beginning and
never fiddled with the hack options or cheats (other than activating filtering
and incrementing the resolution).

**Comment by LunaMoo** [comment] 2018-10-10 21:09
Pretty sure Disgaea series is just unstable. After few hours of playing, doesn't matter if it's PSP, PS2 or even steam(pc) version the game will get a chance of crashing and the problem like explained is just easier to notice on emulators with savestate abuse.

**Comment by unknownbrackets** [comment] 2018-11-19 02:56
My memory of playing it on the PSP wasn't full of crashes, but I might've just forgotten. 

Given that flag was set and there's been no further feedback, I'm going to close this.  We've added a warning when logging too much game time using save states exclusively, which will hopefully help prevent people from hitting game bugs.

If you're seeing this from save data, reply and we'll reopen.  Would be good to validate if the crash doesn't happen on a PSP at that point.

-[Unknown]

**Closed by unknownbrackets** 2018-11-19 02:56 UTC
