### ISSUE TITLE
Hexyz force rendering bug

### ISSUE THREAD

**Issue by 71knight** [hrydgard/ppsspp#13124] opened 2020-07-11 18:20 UTC

**Comment by Panderner** [comment] 2020-07-14 05:03
um @71knight could you send me the screenshot?

**Comment by Panderner** [comment] 2021-09-11 04:00
No feedback?

**Comment by Gamemulatorer** [comment] 2021-09-11 04:00
Reopening? Please complete the details of your issue. Upload a screenshot and ge dump.

**Comment by 71knight** [comment] 2021-09-11 04:11
> um @71knight could you send me the screenshot?

Here is a picture...you might need to brighten it. 
![ULUS10506_00000](https://user-images.githubusercontent.com/62399979/132935812-f362d00d-8212-467e-b29d-f6494a99ebf2.jpg)

**Comment by Gamemulatorer** [comment] 2021-09-11 04:18
What platform android? Backend OGL or VK? UPLOAD a ge dump.

**Comment by Gamemulatorer** [comment] 2021-09-11 04:22
Or try the latest git build apk on ppsspp buildbot
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Gamemulatorer** [comment] 2022-10-09 17:57
@71knight can you still reproduce this issue?

**Comment by unknownbrackets** [comment] 2022-10-10 04:48
I can't reproduce on desktop - just tried a game over, looks fine.  It draws the effect in a standard way that I would expect to work across devices - but it does require stencil upload on framebuffer create (this game generally does.)  That may have previously been a "slower effect."  Maybe that or block transfer were disabled.

Maybe there's some case we don't detect where a write to alpha goes undetected, though.

I'm going to close this, though, assuming it was a setting.

For posterity, here's a frame dump (I did force this frame dump to mark the render a non-target, because otherwise the CPU-written stencil/alpha values were ignored.  This is just a dump mechanics issue, and caused it not to render right in software or on the PSP without forcing it.  Works in hardware rendering either way.

[#13124_ULUS10506_hexyz_force_game_over.zip](https://github.com/hrydgard/ppsspp/files/9743404/13124_ULUS10506_hexyz_force_game_over.zip)

![#13124_ULUS10506_hexyz_force_game_over](https://user-images.githubusercontent.com/191233/194800611-4ccc8ede-306b-4b89-82f6-ef601cd9d534.png)

-[Unknown]

**Closed by unknownbrackets** 2022-10-10 04:48 UTC
