### ISSUE TITLE
Zelda - Navi's Quest will not run at all (Homebrew)

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#11935] opened 2019-03-25 05:36 UTC
im not sure whats wrong with this but on both pc and xbox one it just crashes with no error

https://sourceforge.net/projects/zeldansq/

**Comment by LunaMoo** [comment] 2019-03-25 08:28
It does show errors, this most likely not-soo-legal homebrew expects to create new empty file and fails to do so.

````
22:19:030 core\psploaders.cpp:67 I[LOADER]: Game requested full PSP-2000 memory access
22:19:031 core\memmap.cpp:292 I[MEMMAP]: Memory system initialized. Base at 0000025268CE0000 (RAM at @ 0000025270CE0000, uncached @ 00000252B0CE0000)
22:19:031 core\loaders.cpp:252 I[LOADER]: File is a PBP in a directory!
22:19:031 core\psploaders.cpp:358 I[LOADER]: ZELD00738 : ZeldaNSQ
22:19:032 hle\scekernelmemory.cpp:434 I[SCEKERNEL]: Kernel and user memory pools initialized
22:19:035 hle\scenet.cpp:217 I[SCENET]: LocalHost IP will be 127.0.0.1
22:19:035 hle\proadhocserver.cpp:1703 I[SCENET]: AdhocServer: Begin of AdhocServer Thread
22:19:036 hle\proadhocserver.cpp:1718 I[SCENET]: AdhocServer: Listening for Connections on TCP Port 27312
22:19:057 hle\scekernel.cpp:154 I[SCEKERNEL]: Kernel initialized.
22:19:061 util\blockallocator.cpp:392 I[SCEKERNEL]: -----------
22:19:061 util\blockallocator.cpp:396 I[SCEKERNEL]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
22:19:061 util\blockallocator.cpp:396 I[SCEKERNEL]: Block: 08804000 - 08b01c00 size 002fdc00 taken=1 tag=ELF/"ZELDANSQ"
22:19:061 util\blockallocator.cpp:396 I[SCEKERNEL]: Block: 08b01c00 - 0c000000 size 034fe400 taken=0 tag=(untitled)
22:19:061 util\blockallocator.cpp:398 I[SCEKERNEL]: -----------
22:19:062 hle\scekernelmodule.cpp:1255 I[LOADER]: Module "ZELDANSQ": 08aacd90 08a50cb0 08a50cc8
22:19:111 hle\scekernelmodule.cpp:1348 I[LOADER]: Exporting ent 0 named "ZELDANSQ", 1 funcs, 1 vars, resident 08a50e40
22:19:111 hle\scekernelmodule.cpp:1658 I[LOADER]: Module entry: 088040ac
22:19:192 root         N[BOOT]: ui\emuscreen.cpp:293 Loading D:/ppsspp/memstick/PSP/GAME/ZeldaNSQ...
22:19:193 root         I[SCEKERNEL]: hle\scekernelthread.cpp:1996 276=sceKernelCreateThread(user_main, 08804000, 00000020, 196608, 80004000, 00000000)
22:19:193 root         I[SCEKERNEL]: hle\scekernelthread.cpp:2087 0=sceKernelStartThread(276, 33, 0bfffed0)
22:19:193 root         I[SCEKERNEL]: hle\scekernelthread.cpp:2126 __KernelReturnFromThread: 0
22:19:201 user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:1996 281=sceKernelCreateThread(SDL thread, 0894ea70, 00000020, 32768, 00004000, 00000000)
22:19:201 user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:2087 0=sceKernelStartThread(281, 4, 0bfbfd68)
22:19:203 user_main    W[FILESYS]: filesystems\metafilesystem.cpp:220 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
22:19:203 user_main    W[FILESYS]: filesystems\metafilesystem.cpp:220 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
22:19:203 user_main    E[FILESYS]: filesystems\directoryfilesystem.cpp:61 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
22:19:203 user_main    E[SCEIO]: hle\sceio.cpp:1393 80010002=sceIoOpen(/timidity.cfg, 00000001, 000001b6)
22:19:204 user_main    E[MEMMAP]: core\memmapfunctions.cpp:56 Unknown GetPointer 0099c360 PC 0099c360 LR 0099c360
````

Tu run the game it's enough to create "timidity.cfg" in it's folder.

**Comment by dominater01** [comment] 2019-03-25 08:41
you are right this does fix the issue i just wonder why it didnt come with one

i swear this has worked in the past without creating one but i dont remember

**Comment by hrydgard** [comment] 2019-03-25 08:49
Hm, could be a real bug but not sure. If it works as is on a real PSP without creating the file, we do have a bug.

**Comment by unknownbrackets** [comment] 2020-03-06 05:58
I just tried this with a recent git build and it worked fine.  I suspect it was fixed by #12509.

I'm going to close this based on that, but if it's not working for others, please comment and we can reopen.

-[Unknown]

**Comment by Panderner** [comment] 2020-03-25 11:26
After #12509 the game still not fixed please reopen

**Comment by unknownbrackets** [comment] 2020-03-25 13:21
You're using the latest release of the game and have it in PSP/GAME/ correct?  I was not able to reproduce any issue.

-[Unknown]

**Comment by Panderner** [comment] 2020-03-25 16:20
> You're using the latest release of the game and have it in PSP/GAME/ correct? I was not able to reproduce any issue.
> 
> -[Unknown]

Yes i'm using latest build.

**Comment by unknownbrackets** [comment] 2020-03-26 00:22
Can you post the log?  I get this:

```
user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
user_main    E[SCEIO]: hle\sceio.cpp:1476 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/timidity.cfg, 00000001, 000001b6) - no current working directory
user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
user_main    E[SCEIO]: hle\sceio.cpp:1476 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/saves/records.dat, 00000001, 000001b6) - no current working directory
user_main    I[HLE]: hle\scepower.cpp:439 scePowerSetClockFrequency(333,333,166)
user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:1984 283=sceKernelCreateThread(update_thread, 08894c70, 00000011, 4000, 00000000, 00000000)
user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:2075 0=sceKernelStartThread(283, 0, 00000000)
```

It then prompts me to select widescreen or not.  Boots just fine.

-[Unknown]

**Comment by Panderner** [comment] 2020-03-26 06:06
> Can you post the log? I get this:
> 
> ```
> user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
> user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
> user_main    E[SCEIO]: hle\sceio.cpp:1476 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/timidity.cfg, 00000001, 000001b6) - no current working directory
> user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
> user_main    W[FILESYS]: filesystems\metafilesystem.cpp:221 Path is relative, but current directory not set for thread 276. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
> user_main    E[SCEIO]: hle\sceio.cpp:1476 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/saves/records.dat, 00000001, 000001b6) - no current working directory
> user_main    I[HLE]: hle\scepower.cpp:439 scePowerSetClockFrequency(333,333,166)
> user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:1984 283=sceKernelCreateThread(update_thread, 08894c70, 00000011, 4000, 00000000, 00000000)
> user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:2075 0=sceKernelStartThread(283, 0, 00000000)
> ```
> 
> It then prompts me to select widescreen or not. Boots just fine.
> 
> -[Unknown]

I don't have a PC or rooted phone to post the logs for crashes, both options crashes

**Comment by Panderner** [comment] 2020-03-27 13:11
Here's a log:
```
08:38:812 user_main    E[SCEIO]: HLE/sceIo.cpp:1476 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/timidity.cfg, 00000001, 000001b6) - no current working directory
08:38:824 user_main    E[SCEIO]: HLE/sceIo.cpp:1476 SCE_KERNEL_ERROR_NOCWD=sceIoOpen(/saves/records.dat, 00000001, 000001b6) - no current working directory
08:42:026 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
08:42:026 user_main    E[SCEIO]: HLE/sceIo.cpp:1481 80010002=sceIoOpen(ms0:/seplugins/pspirkeyb.ini, 00000001, 000001b6)
08:42:110 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
08:42:110 user_main    E[SCEIO]: HLE/sceIo.cpp:1481 80010002=sceIoOpen(ms0:/PSP/GAME/ZeldaNSQ/saves/records.dat, 00000001, 000001b6)
08:44:566 user_main    E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:567 user_main    E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:567 user_main    E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:567 user_main    E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:568 user_main    E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:568 user_main    E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:651 SDL thread   E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
08:44:652 SDL thread   E[JIT]: ARM64/Arm64CompBranch.cpp:475 Jump to invalid address: 02a868c0
```

**Comment by Gamemulatorer** [comment] 2020-06-04 10:00
Using ppsspp latest git build this game is fully playable :)
![Screenshot_20200604-175300](https://user-images.githubusercontent.com/37603562/83743353-2fc10580-a68d-11ea-8a39-0b85446a2c5a.png)
![Screenshot_20200604-175439](https://user-images.githubusercontent.com/37603562/83743362-33548c80-a68d-11ea-8ac8-0395a78947ef.png)

**Comment by Gamemulatorer** [comment] 2020-06-04 10:15
Using ppsspp latest git build.
### HW rendering
![Screenshot_20200604-180938HW](https://user-images.githubusercontent.com/37603562/83744835-48cab600-a68f-11ea-94c5-ad45cf8b73e4.png)
![Screenshot_20200604-181233](https://user-images.githubusercontent.com/37603562/83744853-4f592d80-a68f-11ea-928f-24b918d493f3.png)
### SW rendering
![Screenshot_20200604-181022SW](https://user-images.githubusercontent.com/37603562/83744873-5718d200-a68f-11ea-9295-ea24f6d11a44.png)
@dominater01 Still an issue on your platform?

**Comment by Panderner** [comment] 2020-06-04 10:20
Oh. the game is now working in latest build now.

**Comment by dominater01** [comment] 2020-06-04 15:53
all is good now thx

**Comment by unknownbrackets** [comment] 2020-06-05 00:37
Thanks for confirming.

-[Unknown]

**Closed by unknownbrackets** 2020-06-05 00:37 UTC
Labels: Homebrew
