### ISSUE TITLE
Syphon Filter Logan's Shadow flickering legs and hangs

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7320] opened 2015-01-12 04:01 UTC
In stage 5-1,hide behind the tank,the legs flickering,and then get invalid adresses and hangs.

a video show that bug
http://youtu.be/iy5kKc2uYgY

Disable jit won't help.

**Comment by unknownbrackets** [comment] 2015-01-12 05:44
Is this new or did it not used to happen, e.g. in v0.9.9.1?

-[Unknown]

**Comment by daniel229** [comment] 2015-01-12 06:02
0.991,0.972,0.96-420 still happen.

**Comment by unknownbrackets** [comment] 2015-11-02 06:52
Has this improved at all?  I'm wondering if it was some bug related to replacements or something.

-[Unknown]

**Comment by daniel229** [comment] 2015-11-02 07:16
Still happen,with FuncReplacements = False is the same.

**Comment by unknownbrackets** [comment] 2018-08-25 19:48
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by hrydgard** [comment] 2020-10-08 07:49
Duplicate of #10415. That one has more information even if this one is older, so closing this.

**Closed by hrydgard** 2020-10-08 07:49 UTC
