### ISSUE TITLE
Strange reproducible crash with Persona 3 Portable

### ISSUE THREAD

**Issue by rincebrain** [hrydgard/ppsspp#9756] opened 2017-06-01 05:17 UTC
Hi,
So, on 1.4.0 (Windows 32bit), I had the odd experience of attempting to open a particular in-game menu I had opened many times before, and having the emulator crash with what looks, if I understand the exception code right, like a wild pointer.

Great, I reopen 1.4.0, load my last save state, and promptly hit this again.

Try 1.4.2, same again.

Tried downloading dev builds (32 and 64-bit), but they all seem to crash - I'm going to file an issue about that in a second, since I don't think "unzip to new folder, execute" is usually considered holding it wrong.

Since I'm pretty certain GH won't let me attach process crash dumps...
https://www.dropbox.com/s/gmag5fnlfne11it/PPSSPPWindows.exe_170601_011145.dmp?dl=0 is 1.4.2 32-bit having crashed in this way

**Comment by unknownbrackets** [comment] 2017-06-01 05:43
Which menu?  I have P3P, how can I attempt to reproduce?

Did it used to work in v1.3.0?  It'd be great if you could try the builds in between.  There are almost 1200 builds, which means if you go by halves and try 10 or 11 builds, you'll be able to narrow it down very close to when the issue started happening.  Just go halfway each time, and go to a newer build if it doesn't crash, older if it didn't.

http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

What backend are you using - does it happen in OpenGL and Direct3D 11?  What GPU are you using (asked in #9757 also)?

If it's easy to reproduce, can you try enabling the software renderer (in Graphics near the top as of v1.4.2) and see if it crashes too?  It'll be pretty darn slow, but if it doesn't crash, that helps narrow down the cause.

-[Unknown]

**Comment by rincebrain** [comment] 2017-06-01 05:48
It's just the specific per-character equipment menu after you go into Menu->Equipment - picking any character crashes.

It's literally 30 seconds to try reproducing, I can try the software renderer, but I can tell you I already tried swapping from OGL to DX11 and got no change.

As I just noted in #9757, Intel HD Graphics 4000.

I'm familiar with bisecting, sure. :) I'll try the older stable builds first to get data points, and go from there.

**Comment by rincebrain** [comment] 2017-06-01 05:55
Well, that'll put a damper in testing.

The problem doesn't reproduce if I use the in-game save mechanism and then load that save, on 1.4.2 or 1.3.0, and 1.3.0 can't load savestates from 1.4.2.

**Comment by rincebrain** [comment] 2017-06-01 06:05
Here, a breakdown of what versions can load savestates from 1.4.2 and can't, and which ones crash. (tldr all the versions of PPSSPP that can load the savestate crash on it)

1.3.399 can't load
1.3.417 can't load
1.3.425 can't load
1.3.433 crash
1.3.456 crash
1.3.508 crash
1.4.0 crash
1.4.2 crash

If you'd find it faster to just iterate on yourself, https://www.dropbox.com/s/djoy00rkwk9x2m3/PPSSPP_STATE.7z?dl=0 is an archive of my savestate folder - 1 and 5 demonstrate this problem, the rest don't.

**Comment by rincebrain** [comment] 2017-06-01 06:38
Well that's interesting.

I discovered that if I repeatedly reload the same save state, sometimes the rendering comes back horrendously mangled (which persists), and ultimately the game hangs.

http://imgur.com/a/69e6Y are two screenshots from the same savestate on different loads.
https://www.dropbox.com/s/bmkb69myqc7z4hu/munging_savestate.zip?dl=0 is a link to said savestate, if that's useful.

I'd hypothesize that what happened to put my problematic savestates in that position was a more subtle form of whatever corruption is so readily demonstrated there, and then taking a savestate after it happened?

**Comment by unknownbrackets** [comment] 2017-06-01 06:42
Well, when loading the state, it tries to read from invalid memory - with "fast memory" enabled (on by default), this will crash PPSSPP, just like a real PSP would crash the game.

With fast memory disabled and "Ignore Illegal Reads/Writes" enabled (on by default), it doesn't crash.  Not sure what might be going wrong, though.  If you want to continue your game, you could try that way.

Ultimately this is caused by a null pointer in the game, calculated at 089845B4, and loaded from 08C3E764.  It's hard to say what might've caused this - but that location should be within the ELF.  So it's likely a global/static variable of the game code that ended up getting set to the wrong value somehow.

So a few possibilities:
 * Something you did earlier triggered PPSSPP to behave wrong, and caused the game to corrupt this memory.
 * The game has a bug, potentially from "long play sessions" simulated via save states, and you were lucky enough to trigger it at some point.
 * You've used cheats or another feature (maybe some time ago) which corrupted this memory.
 * In an older version of PPSSPP, you triggered a bug, but because you were using save states, you carried the bug (corrupt memory) along with you.

Unfortunately, it's hard to say.  If you know of events that occurred between a working state and a broken state, it might be possible to try to reproduce.  Ultimately we need to find "patient zero".

I know we have some graphics bug in D3D 11 that triggers on some save state loads.  Does this happen in GLES too?  It looks like some sort of texturing glitch.

-[Unknown]

**Comment by rincebrain** [comment] 2017-06-01 06:46
While I can't give you much definitively, I haven't gone in at any point and used any form of cheating or otherwise manipulating game state outside of the game itself.

I'll test it on GL, but would a texturing glitch also cause the game to eventually become entirely unresponsive to input while continuing to play the background music?

**Comment by unknownbrackets** [comment] 2017-06-01 06:57
Well, maybe.  Depends how the drawing state was corrupted.  I think the bug causes us to start drawing state incorrectly or drawing to the wrong framebuffers.  So, yes, that's possible.

FWIW, in a game I loaded just now, that memory points to 08EED4F0.  It seems to write that value during initial load.  But even restoring that value, there are other values that are corrupt (seems like nearby potentially.)

-[Unknown]

**Comment by unknownbrackets** [comment] 2017-12-02 02:41
FWIW the D3D11 load state bug is probably fixed now.  It could've caused some weird things.

Has this happened again since loading the in-game save?

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-06-05 04:08
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2018-06-05 04:08 UTC
Labels: No Feedback / Outdated?
