### ISSUE TITLE
ppsspp install problem

### ISSUE THREAD

**Issue by usoppp16** [hrydgard/ppsspp#14578] opened 2021-07-01 21:29 UTC
i tried to install ppsspp via terminal with iMac high sierra 10.13.6
and this pops up
![Schermafbeelding 2021-07-01 om 22 14 16](https://user-images.githubusercontent.com/86806101/124191409-0b1fa300-dac4-11eb-99d7-8e790c61f06e.png)
 and i can't install it now

**Comment by LunaMoo** [comment] 2021-07-01 21:36
You can't simply "install" PPSSPP on that platform and even if, I dunno what you expected writing "ppsspp" as a command, you will need to build it yourself from source or find someone you can trust that builds it for you.

 Either way follow https://github.com/hrydgard/ppsspp/wiki/Build-instructions making sure you follow downloading source with  submodules as well as installing prerequisites, before jumping to build instructions for your platform.

**Comment by usoppp16** [comment] 2021-07-01 22:07
first i typed the command brew install ppsspp and this popped. then i maybe tried opening ppsspp by typing it
so this happened out of nowhere trying to install ppsspp

**Comment by iota97** [comment] 2021-07-02 06:48
Brew seem unable to download theora (needed by ffmpeg that is needed by ppsspp), you may try again and see if the problem is solved, if not you should probably ask to brew community as the may know more about the error.

**Comment by unknownbrackets** [comment] 2021-07-02 22:04
https://docs.brew.sh/Installation

Brew no longer fully supports macOS 10.13, which you're using.  Your error isn't even about PPSSPP, it's about installing a dependency brew has decided to install (I suspect because they are using system FFmpeg, which we don't recommend.)

You should look here:
https://github.com/Homebrew/discussions/discussions

In fact, your problem is already being discussed there:
https://github.com/Homebrew/discussions/discussions/1752

Closing this issue because it's not a PPSSPP issue.

-[Unknown]

**Closed by unknownbrackets** 2021-07-02 22:04 UTC
