### ISSUE TITLE
Rockman Dash 2 - Vulkan Flicker on Screen Transition

### ISSUE THREAD

**Issue by JMC47** [hrydgard/ppsspp#11443] opened 2018-10-04 08:00 UTC
### What happens?

When using the Vulkan backend, you'll get flickering during certain transitions.  From what I can tell, it only flickers the first time you go into that area, after that the transition works correctly.  It could be loading the minimap, as the minimap has caused problems for me in the stable version.

![unfoldedwellinformedkitfox-size_restricted](https://user-images.githubusercontent.com/6598209/46460417-e3237980-c789-11e8-9b2d-02c042717d06.gif)

D3D is not afflicted by this issue.  OpenGL is afflicted by a different issue.

### What *should* happen?

No flicker.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I'm on a Core i7-6700K, GTX 1070, Windows 10.  Tested on PPSSPP v1.6.3-536-g7b34eaa1f and 1.6.3 stable.

**Comment by hrydgard** [comment] 2018-10-04 08:07
looks like it's drawing something differently when the HUD elements slide in on the screen, which somehow temporarily breaks rendering or causes a clear...

**Comment by JMC47** [comment] 2018-10-04 08:08
The minimap has issues on OpenGL, so I assume it's related to that.

**Comment by hrydgard** [comment] 2018-10-04 08:12
Yeah, very likely related to #11444.

These PSX ports tend to do weird stuff...

**Comment by JMC47** [comment] 2018-11-10 19:00
Vulkan is still broken despite OpenGL now working.  The black flicker still happens, though the other minimap issues don't.

**Comment by hrydgard** [comment] 2018-11-10 23:11
Interesting. Good to get confirmation that GL works correctly though.

**Comment by hrydgard** [comment] 2019-02-06 19:02
Just to be sure, does this still happen?

**Comment by ResurrectionRedmi9** [comment] 2021-09-14 09:30
How about this now?

**Comment by Gamemulatorer** [comment] 2022-09-30 07:42
There's a minor flickering on the npc.

https://user-images.githubusercontent.com/37603562/193217961-1bac7e0b-8da0-471e-ac0f-3529be0b32e0.mp4

Can also reproduce in software.
![Screenshot_2022-09-30-15-39-06-29](https://user-images.githubusercontent.com/37603562/193218030-c1daf76b-97da-49cf-b91f-93fa02867032.png)
[ULJM05037.zip](https://github.com/hrydgard/ppsspp/files/9681858/ULJM05037.zip)

**Comment by hrydgard** [comment] 2022-09-30 08:46
I think that might just be an artifact of the PSX-style the game renders at, with pixel snapped vertex positions etc. What does it look like on the real hardware?

And is the original issue here solved?

**Comment by Gamemulatorer** [comment] 2022-09-30 08:51
> I think that might just be an artifact of the PSX-style the game renders at, with pixel snapped vertex positions etc. What does it look like on the real hardware?

I don't have PSP :(

> And is the original issue here solved?
Yes.

**Comment by hrydgard** [comment] 2022-09-30 09:07
I'm gonna close this then, as the little flicker in the character almost certainly is a different problem, if it is one at all.

**Closed by hrydgard** 2022-09-30 09:07 UTC
Labels: No Feedback / Outdated?, Vulkan

**Comment by unknownbrackets** [comment] 2022-10-01 01:13
Just to confirm ,this is the rendering of that frame dump on a PSP (UI think the margin ended up with some copy along the way):

![#11443_ULJM05037_rockman_gaps_software](https://user-images.githubusercontent.com/191233/193377358-958760a7-9f32-4e86-9238-b80c1cdf6921.png)

It looks to be pretty close to our rendering in hardware and software.

-[Unknown]
