### ISSUE TITLE
Gripshift USA - Stuck/Hang Randomly

### ISSUE THREAD

**Issue by tabnk** [hrydgard/ppsspp#8372] opened 2016-01-03 05:47 UTC
Stuck or Hang on save screen.

On latest build ppsspp-v1.1.1-582-g18dbaac-windows-amd64.

![name](https://cloud.githubusercontent.com/assets/10874582/12077473/86006730-b220-11e5-8707-a314c0e19cf1.png)

**Comment by unknownbrackets** [comment] 2016-01-03 05:50
Pretty sure this is a duplicate of #7601.

-[Unknown]

**Closed by unknownbrackets** 2016-01-03 05:50 UTC
