### ISSUE TITLE
Why this happen?

### ISSUE THREAD

**Issue by MatthewChin96** [hrydgard/ppsspp#8394] opened 2016-01-05 19:47 UTC
![untitled](https://cloud.githubusercontent.com/assets/16511076/12125753/170c6b62-b428-11e5-9d7c-c9d14af50803.png)

**Comment by hrydgard** [comment] 2016-01-05 20:51
What game is that? What device are you running on? What is happening, just the lack of text?

Can't do anything about it without this information.

**Comment by daniel229** [comment] 2016-01-05 23:27
Can you try the lateset build if still happening.I think is the same as v https://github.com/hrydgard/ppsspp/issues/8353 .

**Comment by MatthewChin96** [comment] 2016-01-06 06:36
I'm using ppsspp Windows and the game is sd Gundam g generation world.

**Comment by daniel229** [comment] 2016-01-06 06:40
Still happen in the latest build from http://buildbot.orphis.net/ppsspp/index.php ？

**Comment by daniel229** [comment] 2016-01-06 06:55
That text works for me。
![01](https://cloud.githubusercontent.com/assets/3481559/12136708/7e4214c8-b485-11e5-94bc-400fb5eac7b0.png)

**Comment by unknownbrackets** [comment] 2016-01-06 06:58
Okay, I'm closing this as a duplicate of #8353.  If it's still happening, include the version number and more detail.

-[Unknown]

**Closed by unknownbrackets** 2016-01-06 06:58 UTC
