### ISSUE TITLE
(suggestion) Make buttons enlarge less upon press (Android)

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10162] opened 2017-11-19 19:35 UTC
I think the buttons get too big when you press them. I know most of the time your finger is on the button and you can't see that but if you use key combos then it gets really annoying. Especially on larger displays.

**Comment by leopard20** [comment] 2017-11-22 13:53
@hrydgard 
So, what do you think? If you think it's irrelevant I could close the issue.

**Comment by leopard20** [comment] 2017-11-22 13:55
Also, can you please check out my other suggestion as well?

**Comment by hrydgard** [comment] 2017-11-22 14:49
Yeah, I can agree that they grow too large. I think I'm actually going to replace the growth with some sort of glow, or similar. That's for the next version though.

**Comment by leopard20** [comment] 2017-12-06 15:19
@hrydgard 
You can also add a slider to tweak the enlargement multiplier. There's a similar feature in ePSXe called "Button magnification on press".

**Comment by hrydgard** [comment] 2018-06-10 18:57
Indeed, closing this as dupe of #5624. They're similar enough and you can make a comment on the other one to add your slider idea..

**Closed by hrydgard** 2018-06-10 18:57 UTC
Labels: Feature Request
