### ISSUE TITLE
Missaligned controls for stretched phone screens?

### ISSUE THREAD

**Issue by supermilleno** [hrydgard/ppsspp#9758] opened 2017-06-01 07:17 UTC
When using Immersive mode, the whole screen is filled up, but the controls are not in the right position horizontally; for example, the Square and Circle buttons are on the wrong places so that when I tap its missaligned.

I'm using an LG G6, which has an aspect ratio of 18:9.

**Comment by hrydgard** [comment] 2017-06-01 07:19
It works fine on my S8 which is 18.5:9 but I have seen issues with immersive mode on my N5 so I do believe there's some kind of bug here.

**Comment by unknownbrackets** [comment] 2017-06-01 14:30
Hmm, I never noticed any issue on the Nexus 5, even with immersive.

It makes no difference if you use buffered rendering, Vulkan, or which game you're playing?

-[Unknown]

**Comment by hrydgard** [comment] 2017-06-01 14:44
I noticed once that touches were somewhat off on my Nexus 5x in immersive mode. It seems the screen ended up being stretched in one direction more than the other for whatever reason. I'll see soon if I can reproduce.

**Comment by Michal1324** [comment] 2017-07-09 14:44
You can use the double window and they probably gonna have their detection boxes misalligned

**Comment by hrydgard** [comment] 2017-11-12 16:21
How is this in the latest builds? Should be fixed.

https://buildbot.orphis.net/ppsspp/

**Comment by unknownbrackets** [comment] 2018-01-01 22:06
FWIW I locked and unlocked my Pixel a bunch of times, and eventually got misaligned controls.  Two different ways:

Way 1: Controls were aligned to the button bar, even though I was in immersive.
Way 2: Controls were stretched, about as much as the button bar or so, beyond the right side.

Locking again and unlocking would usually return it to its previous alignment.  Maybe this is an issue with the timing of resize events?

-[Unknown]

**Comment by hrydgard** [comment] 2018-01-01 22:23
Were only the controls misaligned or the entire image? Did they react to touch as if they were in the proper positions or the wrong positions?

I don't know why resizing code always ends up a mess of race conditions, but that seems to be the case :P

**Comment by unknownbrackets** [comment] 2018-01-01 23:31
Only the controls are misaligned, and only their display.  When I touch where they SHOULD be, they are pressed.  They grow from their incorrect position and stay there, though.

Returning to the menu (back) and then resuming the game draws the controls in the right places.

-[Unknown]

**Comment by unknownbrackets** [comment] 2018-05-14 12:05
@hrydgard I've figured out roughly how to reproduce this, although it's not an exact science.

Basically, the issue is with how `setDisplayParameters` is called.  Sometimes when I wake my phone (potentially if it had the navigation bar visible), we end up with `dp_xres=1025 dp_yres=617` instead of `dp_xres=1097 dp_yres=617` (Pixel 1), which corresponds to `pixel_xres=1794 pixel_yres=1080`.

But, when surfaceChanged happens and we get `pixel_xres=1920 pixel_yres=1080`, the display size is not updated so we keep `dp_xres=1025 dp_yres=617`.  Thus, the X coord of controls are scaled wrong.

I think the goal of display_xres is to store the original size of the display.  But it's also called on surfaceCreated with the actual surface size.  If it's really meant to be the display size, it probably shouldn't scale touches?

-[Unknown]

**Comment by maddog02** [comment] 2018-05-14 12:13
LENOVO A5000
ANDROID 4.4.2
MALI-400MP
NOT SUPPORTED TO VULKAN

PLEASE FIX THIS EMULATOR BECAUSE THE OTHER GAME ON PSP IS FORCE CLOSE

**Comment by maddog02** [comment] 2018-05-14 15:18
DANTE'S INFERNO [EUR]

Fix this because i want to play this game and what required specs for this
game thank you

**Closed** 2019-05-13 11:34 UTC
Labels: Input/Controller, Platform-specific (Android)
