### ISSUE TITLE
Vulkan alt+enter/F11 Fullscreen blocks keyboard/mouse/controller input

### ISSUE THREAD

**Issue by pitrako** [hrydgard/ppsspp#12757] opened 2020-03-23 21:06 UTC
### What happens?
When vsync is enabled in emulator when using vulkan and then using alt+enter or F11 for fullscreen mode input is blocked (mouse/keyboard/controller) and stuck on fullscreen. But game keeps running.

### What *should* happen?
Correct transition between fullscreen mode and windowed mode in vulkan.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Hardware: RTX 2080 driver 445.75, I7-9700K, TV HDMI connected to the graphics card.

Operating System: Windows 10 Pro 1909.

PPSSPP version: Currently I'm in v1.9.3-558-gef4ecb0e8

**Comment by LunaMoo** [comment] 2020-03-23 23:02
Can't reproduce this.
 Do you have any third party overlays/filters/info(cpu usage etc)? If you do, try disabling those.

**Comment by pitrako** [comment] 2020-03-24 08:46
RTSS and MSI Afterburner, but I tried without those and the result It's the same.

**Comment by hrydgard** [comment] 2020-03-29 13:06
Doesn't happen for me either.. Weird.

**Comment by unknownbrackets** [comment] 2020-03-29 14:03
I do get a long delay when switching away from full screen in Vulkan if vsync is enabled.  During this time, input (keyboard, mouse, system keys, etc.) doesn't work but the game and other apps keep running.  I'm pretty sure it's a driver thing, though.  Once it finishes switching to windowed, everything is responsive again.

-[Unknown]

**Comment by pitrako** [comment] 2020-03-29 14:58
That is exactly what happens to me, maybe I did not explain myself well.

**Comment by LunaMoo** [comment] 2020-04-01 16:22
Seems to be a duplicate of #12302 ? So not really OS specific?
Maybe caused by some non default settings? I don't get any pauses with Vulkan even if only looking at switching from fullscreen and made sure vsync is set to use application setting and enabled in PPSSPP. Maybe having a variable refresh rate display could still be a factor here somehow preventing the problem through.

**Comment by hrydgard** [comment] 2020-05-10 16:36
I can't seem to repro this at all (nvidia card, Win 10).

**Comment by unknownbrackets** [comment] 2020-05-10 16:57
Sounds positive, still reproduces on an older driver.  My exact steps:

1. Open PPSSPP with backend set to Vulkan.
2. Enable Vsync in Windows menu.
3. Drag PPSSPP onto secondary monitor.
4. Start a game going
5. Press Alt-Enter to make it full screen.
6. Press Alt-Enter again.

Since even the mouse won't move, Alt-Tab and Ctrl-Alt-Delete won't work, etc... it's pretty obviously a driver bug.

-[Unknown]

**Comment by hrydgard** [comment] 2020-05-10 17:58
I didn't move it to a secondary monitor though, so in theory there could still be something there.

**Comment by hrydgard** [comment] 2020-05-26 22:04
@unknownbrackets  Did you get around to trying on a newer driver?

**Comment by unknownbrackets** [comment] 2020-05-30 23:55
Sorry, yes - it works fine now.  I'm going to close this given that.

-[Unknown]

**Closed by unknownbrackets** 2020-05-30 23:55 UTC
Labels: Platform-specific (Windows)
