### ISSUE TITLE
WO series Bug on ARM A53 Architecture on Android

### ISSUE THREAD

**Issue by TediExcaliber** [hrydgard/ppsspp#10017] opened 2017-10-16 00:58 UTC
The bug is making the character and npc is blinking, sometime gone and sometime appear, when gone, the npc cannot be attack, that i know, this bug only happen in Android that using Architecture ARM Cortex-A53, cuz the android that using x86 is okay...

Please fix this bug.

**Comment by unknownbrackets** [comment] 2017-10-16 02:18
Does it work if you go to developer tools and change the CPU core to "IR Interpreter" or "Interpreter"?  It will be slower, but this will confirm if it's a jit bug or not.

-[Unknown]

**Comment by TediExcaliber** [comment] 2017-10-16 14:14
Thanks for replying my email.

Yes, i have change that setting too, when use Interpreter the ppsspp is
Force Close, when using the IR Interpreter the result is same like using
JIT (still buggy)

Pada tanggal 16 Okt 2017 9.18 AM, "Unknown W. Brackets" <
notifications@github.com> menulis:

**Comment by hrydgard** [comment] 2017-11-14 10:25
"WO series", which games is that? The closest I can find is "World series of Poker"?

**Comment by TediExcaliber** [comment] 2017-11-14 10:29
Warriors orochi

Pada tanggal 14 Nov 2017 5.25 PM, "Henrik Rydgård" <notifications@github.com>
menulis:

**Comment by unknownbrackets** [comment] 2017-11-15 05:01
I guess this is the same issue as #9843 then?

If this didn't happen in some past version, it'd help to know when it stopped working.

-[Unknown]

**Comment by unknownbrackets** [comment] 2017-11-22 23:07
This issue is being closed as a duplicate of #9843.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-11-22 23:07 UTC
