### ISSUE TITLE
Iron Man - half of the screen in black (Vulkan)

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#12256] opened 2019-08-18 15:15 UTC

**Comment by Drasikk** [comment] 2019-08-18 15:17
I tried to make a DUMP file, but when I open the Google Chrome browser and go back to the emulator, it goes black or paralyzes.

**Comment by hrydgard** [comment] 2019-08-18 15:26
That's interesting, thanks for reporting.

Any chance you could try to make a dump file with the Windows build?

**Comment by unknownbrackets** [comment] 2020-02-15 22:10
See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Drasikk** [comment] 2020-03-16 20:35
@hrydgard 
@unknownbrackets 
[DUMP.zip](https://github.com/hrydgard/ppsspp/files/4340262/DUMP.zip)

**Comment by unknownbrackets** [comment] 2020-04-12 02:15
I'm not seeing the black issue in this dump - or the overlay on top.

That said, it's texturing from 0x04088780 (which is the part between the buffer and the stride) near 3165/3180, maybe that's behaving wrong.

Interestingly, this dump draws 5 frames - each is 636 draws.  That seems like a bug if it really renders 5x...

-[Unknown]

**Comment by Panderner** [comment] 2021-01-11 04:45
I can't reproduce this issue on POCO M3 using Vulkan in latest build
![Screenshot_2021-01-11-12-29-25-941_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/104147445-41c80b00-5409-11eb-96e5-1f20822b2404.jpg)

**Comment by ppmeis** [comment] 2021-01-11 22:17
It seems fine on latest windows build too
![image](https://user-images.githubusercontent.com/4381277/104244658-31dd1500-5463-11eb-88d1-ab756ccff634.png)

**Comment by unknownbrackets** [comment] 2021-03-05 06:26
I think there's a decent chance this may have been #14233.

Going to close this, assuming it's been fixed by that since we're not likely to get testing feedback now from anyone who can reproduce.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2021-03-05 06:26 UTC
Labels: No Feedback / Outdated?, Vulkan
