### ISSUE TITLE
Resistance - Retribution Display issues

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#10717] opened 2018-03-13 08:08 UTC
What happens?
1.5.4 develop version
![2](https://user-images.githubusercontent.com/3827333/37329155-8e71c872-26d7-11e8-81be-4e1080990d95.png)

1.5.4 release version
![4](https://user-images.githubusercontent.com/3827333/37329393-99ae9854-26d8-11e8-88ab-72be36c84f36.png)

What *should* happen?
![3](https://user-images.githubusercontent.com/3827333/37329161-963e0d4a-26d7-11e8-99d5-325567a61f5c.png)

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

window10, vulkan backend

**Comment by hrydgard** [comment] 2018-03-13 09:48
But it looks right in the last screenshot? Is the error specific to the Vulkan backend?

**Comment by weihuoya** [comment] 2018-03-13 09:53
last screenshot is What should happen, opengl has this issue, too

**Comment by hrydgard** [comment] 2018-03-13 09:54
Yes but if it's broken, how did you take the last screenshot? :)  D3D?

**Comment by weihuoya** [comment] 2018-03-13 09:55
not broken, just Display issues

**Comment by hrydgard** [comment] 2018-03-13 09:56
It sometimes draws correctly and sometimes not? flickers?

**Comment by weihuoya** [comment] 2018-03-13 09:58
happend at fixed place

**Comment by LunaMoo** [comment] 2018-03-13 10:09
All the crashes and graphic corruption of this game are caused by timing issues this game suffers from, if anything went different it might be due to new gpu code ending up with slightly different timing, but it was always happening, affected easily by psp cpu clock and the game is overall broken.

 I will close this as a duplicate of #9279, however imo that one should be closed as well as it doesn't matter how and by what change game graphics get's affected, it's all related to inaccurate timing of ppsspp and ultimately just a duplicate of #4626. It's really a poorly coded game that will probably never work unless we get all the timing right, all it's graphic corruption are just game running stuff at wrong times, it messes up vertices, causing "bad textures" as well as "invisible enemies" and ofc crashes.

**Closed by LunaMoo** 2018-03-13 10:09 UTC
