### ISSUE TITLE
Unrealated textures allover the screen and performance loss

### ISSUE THREAD

**Issue by Nydrogen** [hrydgard/ppsspp#8964] opened 2016-09-09 11:42 UTC
1.I have this weird problem that textures from the game and/or the emulator cover the screen after a level is loaded.
2.I get moderately less performance on 1.2.2 than 1.2.1.

Note: any different rendering mode than non-buffered results with blurry image and lags.

Specs:
![screenshot_2016-09-09-13-05-56](https://cloud.githubusercontent.com/assets/22097458/18385606/4c81fcb4-769a-11e6-9c8c-d7676efa3703.png)

1.2.2:
![screenshot_2016-09-09-13-09-29](https://cloud.githubusercontent.com/assets/22097458/18385539/efc59c10-7699-11e6-8cf3-a0d0445b2313.png)
![screenshot_2016-09-09-13-10-33](https://cloud.githubusercontent.com/assets/22097458/18385575/2a06b65c-769a-11e6-9e82-3f34f300011d.png)

1.2.1:
![screenshot_2016-09-09-13-02-20](https://cloud.githubusercontent.com/assets/22097458/18385632/6a0a8ee0-769a-11e6-82f9-caa0f4c26376.png)
![screenshot_2016-09-09-13-00-34](https://cloud.githubusercontent.com/assets/22097458/18385644/799bf678-769a-11e6-95f8-14793eb8a2d6.png)

Tanks for the help!

**Comment by unknownbrackets** [comment] 2016-09-10 13:25
It's expected that "Skip Buffer Effects" (used to be confusingly called "Non-Buffered") rendering mode would cause artifacts and glitches.  That's exactly what it is - a faster, but inherently glitchy, option that ignores parts of effects that games try to draw (like these.)

Like any shortcut, "Skip Buffer Effects" doesn't work long term.  It's just a hack to try to get speed at the expense of doing things right.  We could "fix" this bug by doing things right, but then you lose the speed.

For any blurriness, there's a resolution setting that only applies for regular rendering.  But raising that probably won't improve speed.

As to differences in [v1.2.1 and v1.2.2] (https://github.com/hrydgard/ppsspp/compare/v1.2.1...v1.2.2), mainly we reverted a change from v1.2.0 that made us pick the rendering surface differently.  We had to change it because it was causing crashes on a lot of devices - we're still not sure of a better fix.

You can follow that last issue in #8618.  Closing this since it's a duplicate of that and doesn't have any unique issues.  You can find more information on trying to speed up your device [on the forum](http://forums.ppsspp.org/).

-[Unknown]

**Closed by unknownbrackets** 2016-09-10 13:25 UTC

**Comment by Nydrogen** [comment] 2016-09-10 18:51
Thank you!,
Though the change from v1.2.0 didn't cause crashes to me at all.
The performance are fine for me with 1.2.1.
I don't get how my issues are a duplicate of #8618,
but at least excpet for the artifacts,everything is perfectly fine for me with 1.2.1.

**Comment by unknownbrackets** [comment] 2016-09-10 18:58
The change in v1.2.0 that was reverted in v1.2.2 was reverted because it caused #8618.  When #8618 is fixed, the change will be brought back, and so also will the performance improvement.

-[Unknown]
