### ISSUE TITLE
Tenchu shadow assasins black screen on Android

### ISSUE THREAD

**Issue by oleyansen** [hrydgard/ppsspp#7663] opened 2015-04-06 20:04 UTC
Hi

Seems bug #4971 reproduced again on Android devices.
It appear as black screen during hissatsu sequence (which is temporary and disappear after performing hissatsu), and shuriken kill (which is permanent and make game unplayable).

This is how it looks during hissatsu (before and after):
![img_20150406_222429](https://cloud.githubusercontent.com/assets/11784075/7011375/28d5ef84-dcb1-11e4-9786-03d82bc99433.jpg)
![img_20150406_222600](https://cloud.githubusercontent.com/assets/11784075/7011376/28d7be18-dcb1-11e4-9192-dae0b8dd8893.jpg)

And this is how it looks during shuriken (before and after):
![img_20150406_225104](https://cloud.githubusercontent.com/assets/11784075/7011380/2ef4d254-dcb1-11e4-88f4-87921efcd4e0.jpg)
![img_20150406_225203](https://cloud.githubusercontent.com/assets/11784075/7011381/2f0d031a-dcb1-11e4-8d12-d2252eaca41f.jpg)

Shuriken black screen appears after targeting throwable, and game react as usual (you can hear you character jump and panting) but cant see a thing.
Tested on Samsung tablet and Jiayu S3 smartphone.
Please let me know if you need additional information.

**Comment by sum2012** [comment] 2015-04-07 20:10
Try to find out
Which version last good ?
Which version first break ?
http://pan.baidu.com/s/1hqqVjpE

**Comment by oleyansen** [comment] 2015-04-08 08:36
Sorry Sum

I don't have Baidu account and can't download this attachment. What is inside?
However I did some research and found following:

This is exactly what happened during shuriken aim:
   https://www.youtube.com/watch?v=NHxAaME9tW0

Searching PPSSPP forum reveal following posts:
People reporting version 0.9.6 (for PC?) is ok. Can't find this version on buildbot though.
   http://forums.ppsspp.org/showthread.php?tid=694&pid=93594#pid93594
Version 0.9.9.1 on PC don't work.
   http://forums.ppsspp.org/showthread.php?tid=694&pid=104655#pid104655
Problem with D3D render, but OpenGL is ok on PC
   http://forums.ppsspp.org/showthread.php?tid=694&pid=104655#pid104655

**Comment by sum2012** [comment] 2015-04-09 22:03
You should no need baid account to download
![1](https://cloud.githubusercontent.com/assets/2177532/7077898/36e75412-df47-11e4-9125-7f54d5adc616.jpg)

**Comment by oleyansen** [comment] 2015-04-10 18:36
Hi

I tested following versions:
0.7.6-996 - stack on start screen
0.8-91 - black shuriken screen
0.9.6-96 - black shuriken screen
0.9.7-38 - black shuriken screen
0.9.8-1149 - black shuriken screen
0.9.9-20140722 - black shuriken screen
0.9.9.1-1619 - black shuriken screen
1.0.1-343 - black shuriken screen
Tested both on buffered and non-buffered render.
Maybe if you provide me version diapason I can test more thoroughly.

**Comment by oleyansen** [comment] 2015-05-13 18:21
Any update about this issue?

**Comment by sum2012** [comment] 2015-05-13 22:31
It seem that never work

**Comment by bababoombatman** [comment] 2015-09-16 16:31
i've tested it with the version v1.0.1-2668-g253ed9f (14-09-2015) and the black screen is still present

**Comment by bababoombatman** [comment] 2015-11-25 08:35
[primary%3ADownload%2FNuovo%20documento%205Pagina%201.pdf](https://github.com/hrydgard/ppsspp/files/43610/primary.3ADownload.2FNuovo.20documento.205Pagina.201.pdf)
Now it display withe screen with some items (1.1.1-324-gce05930)

**Comment by aquilsamuel** [comment] 2016-01-07 15:00
Hello. I have tested Tenchu: Shadow Assassins on ppsspp version 0.9.9.1, as for the blackscreen it is not present at least not anymore after changing the graphic settings in ppsspp. However, when stage one is complete, you go to the second and for some reason it just just freezes and the in game sound loops endlessly while it's frozen.

![ulus10419_00002](https://cloud.githubusercontent.com/assets/16358888/12173390/6d43f20a-b50b-11e5-9468-e2f5dc13274f.jpg)
![ulus10419_00003](https://cloud.githubusercontent.com/assets/16358888/12173391/6d4bcab6-b50b-11e5-8d1a-dc8c097d6f62.jpg)
![ulus10419_00004](https://cloud.githubusercontent.com/assets/16358888/12173392/6d4e872e-b50b-11e5-899c-ab5c3005d082.jpg)
![tenchu_shadow assassins issue](https://cloud.githubusercontent.com/assets/16358888/12173497/fc6609f0-b50b-11e5-9190-adb0eec6c179.png)
This the last image is where it is stuck and that about the furthest I've reached before the frozen screen. Anyone else has this problem???

**Comment by daniel229** [comment] 2016-01-08 00:16
In version 0.9.9.1 it freezed by GHA phase shifting problem,everything should work fine in the latest build with default setting on desktop.

**Comment by unknownbrackets** [comment] 2016-01-08 03:18
Can anyone experiencing this issue try to get a log from their device?  It sounds like it's mobile only.

-[Unknown]

**Comment by aquilsamuel** [comment] 2016-01-08 22:09
@daniel229 It's the same problem with this screen.
![ulus10419_00000](https://cloud.githubusercontent.com/assets/16358888/12210786/6195aef6-b611-11e5-838f-cf24b26665c1.jpg)

**Comment by daniel229** [comment] 2016-01-09 00:22
Version 1.1.1 absdiff blending is broken,Can you try the latest,It works fine for me,and what is your video card.
![01](https://cloud.githubusercontent.com/assets/3481559/12212863/0ced293a-b6aa-11e5-8f7d-14edf1f605c8.png)
![02](https://cloud.githubusercontent.com/assets/3481559/12212864/0cef7cf8-b6aa-11e5-8941-cf963b1241e2.png)

**Comment by aquilsamuel** [comment] 2016-01-11 06:16
@daniel229 I am sorry but I don't know how to view my video card.
My laptop is: Lenovo Win7 32 bit operating system
Processor: T4400 @ 2.20 GHz 
Rating: 3.3

I also tried the very latest build which was up on the 1st of January, but it is all the same. Same white screen. There is one ppsspp emu. that when I configured it to suit this game, it was not happening entirely, but it would stick in second stage where i told you before. So there are two major issues with Tenchu: Shadow Assassins, ans that is the white / black screen for almost any stealth kills, and the game just freezes in second stage. Those two are the problems that seem like they can not be conquered. PPSSPP 1.1.1 - 658-gd479990 & PPSSPP 1.1.1 - 647-gd41a9e00 have not solved that problem. I guess it's just my laptop.

**Comment by daniel229** [comment] 2016-01-11 06:28
Did you try Direct3D9 backed,is it better than OpenGL?

**Comment by aquilsamuel** [comment] 2016-01-11 22:50
@daniel229 Yes it did, it worked and may i say: no issues with white or black screen or any frozen stages. Direct3D9 allows the game to work well. It slows down and lags in some stages but it's not that bad, i'd say it passable. Thanks a lot for the tips Daniel, you know your stuff :)

Here are some screenshots I took.

![ulus10419_00004](https://cloud.githubusercontent.com/assets/16358888/12249090/79542686-b872-11e5-9cf1-87e3ff089e0f.jpg)
![ulus10419_00005](https://cloud.githubusercontent.com/assets/16358888/12249091/796d65d8-b872-11e5-885b-cd2aaa333f4b.jpg)
![ulus10419_00008](https://cloud.githubusercontent.com/assets/16358888/12249092/797f02d4-b872-11e5-8031-299f18baa9c5.jpg)
![ulus10419_00009](https://cloud.githubusercontent.com/assets/16358888/12249094/79951060-b872-11e5-9d2e-4da500d11b21.jpg)
![ulus10419_00013](https://cloud.githubusercontent.com/assets/16358888/12249093/7991ca4a-b872-11e5-9388-0703174e21e9.jpg)
![ulus10419_00015](https://cloud.githubusercontent.com/assets/16358888/12249096/79b960dc-b872-11e5-8d55-3371b3154d7f.jpg)
![ulus10419_00020](https://cloud.githubusercontent.com/assets/16358888/12249097/79d00530-b872-11e5-83bd-3849e211f871.jpg)
![ulus10419_00042](https://cloud.githubusercontent.com/assets/16358888/12249098/79d0fea4-b872-11e5-85a2-b697b4135ca1.jpg)
![ulus10419_00045](https://cloud.githubusercontent.com/assets/16358888/12249099/79ef8e6e-b872-11e5-90e3-3291970a8b41.jpg)

**Comment by bababoombatman** [comment] 2016-01-13 08:59
sorry but i don't know to create a log on android and i can't find a step by step guide

**Comment by bababoombatman** [comment] 2016-01-13 09:53
after some attempts found that disabling slower effect fix the bug...don't know if it can help

**Comment by unknownbrackets** [comment] 2016-01-14 06:02
> Version 1.1.1 absdiff blending is broken

Disabling slower effects will disable absdiff blending.  Try a git build.

-[Unknown]

**Comment by oleyansen** [comment] 2016-01-14 18:51
Have try it on my JIAYU G3
Issue still present on latest git build (v1.1.1-660-g4a337f7) even with slower effects disabled.
Any chance to fix it for Android? :)

**Comment by unknownbrackets** [comment] 2016-01-14 20:17
If this only happens on MT6589, it's probably not an Android issue.  #7961 / #1313 both cover major compatibility issues with PowerVR 54x GPUs and I'm not sure there's a lot we can do about them.

Does this work on Android devices with GPUs that generally do work in PPSSPP?

-[Unknown]

**Comment by oleyansen** [comment] 2016-01-15 07:03
Will check this on Samsung Galaxy Tab this evening

**Comment by oleyansen** [comment] 2016-01-16 06:09
So seems this is Mali-T760 GPU issue.
I have checked on Galaxy Tab and there no issue with absdiff blending (slower effects) disabled.

**Comment by unknownbrackets** [comment] 2016-01-16 07:43
Oh, Google led me to believe JIAYU G3 had a PowerVR 5xx GPU.  I would expect a Mali-T760 to not have problems, normally.  That's fairly modern GPU, especially in comparison with the PowerVR 5xx.

Also, absdiff should be working in the latest git builds just fine.  Though, I don't know much about Vivante GPUs.  It also supports GLES3 so it's probably relatively modern.

Are you able to check the log from adb?  Does anything show up at all on either device when the glitch happens?

Just to make sure I understand, disabling "slower effects" helps the Vivante, but not Mali.  With "disable slower effects" off, it's broken the same way on both GPUs, and it's also broken the same way on the Mali even with "disable slower effects" checked.

Does it change anything to toggle the "simulate block transfer" setting?

-[Unknown]

**Comment by oleyansen** [comment] 2016-01-16 14:21
Yes, disabling "slower effects" helps on the Vivante, but not on Mali GPU.
Here is logs I grabbed from Mali with "slower effects" disabled and enabled for both 'buffered' and 'not-buffered' render.
PPSSPP version is v1.1.1-663-g03674fd

On this version for buffered render/"slower effects" enabled black screen is white as in aquilsamuel comment :)
On buffered render/"slower effects" disabled black screen is black.

[adb_logs.zip](https://github.com/hrydgard/ppsspp/files/92910/adb_logs.zip)

**Comment by unknownbrackets** [comment] 2016-01-16 17:29
Interesting.  Unfortunately, I don't see anything in the logs - was hoping there was an error.

It might help to understand what effect it's doing there in the first place.  Are you able to use a Windows build (with WINE or etc.) to use the GE debugger and check on what it's trying to render using the absdiff effect?  It'd be fine to try it after you've thrown the shuriken, I think, even if the screen appears to render fine.

Tricks with absdiff can be weird though.  Maybe it's even a precision issue, so the difference is coming out wrong.

-[Unknown]

**Comment by oleyansen** [comment] 2016-01-17 16:20
I run GE debugger on Windows box with saved state and it definitely found wrong (red) render.
Unfortunately I have no expertise in using this amazing tool so I just prepare savestates pack available on this link:
https://drive.google.com/file/d/0B5thjmtEXXMyT1JDc2dKeGh6aXM/view?usp=sharing

This is single zipfile with size 71 Mb containing 5 saves:
1. Initial scene before shuriken pickup
2. Shuriken aimed, white screen appear for absdiff render
3. Shuriken thrown, white screen still present for absdiff render
4. Shuriken aimed, black screen appear absdiff render disabled
5. Shuriken thrown, black screen still present absdiff render disabled

**Comment by aquilsamuel** [comment] 2016-01-18 12:52
@oleyansen Hi there, try changing the settings in the graphics section under "rendering mode"
![capture](https://cloud.githubusercontent.com/assets/16358888/12391678/6c0e700e-bd9e-11e5-94b2-e41903480d16.JPG)
 Change "Backend" from "OpenGL" to "Direct3D9". Hope it helps.

**Comment by oleyansen** [comment] 2016-01-18 15:54
@aquilsamuel I have no this option on my Mobile Phone (JIAYU G3) :-)

**Comment by aquilsamuel** [comment] 2016-01-19 01:30
No problem @oleyansen I just try to help. The real guys are people like daniel and others like him props to them. If it weren't for the info he gave me, I'd still be in misery. So I hope that you get through with this problem bro.

**Comment by unknownbrackets** [comment] 2018-08-25 19:53
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by oleyansen** [comment] 2018-08-27 11:52
Will do this today, as soon as get to my windows computer :)

**Comment by oleyansen** [comment] 2018-08-28 19:17
I just checked this scene on GPD XD and can confirm cause of issue in GPU chip on Jiayu.
GPD have GPU ARM Mali-T764 as Jiayu have PowerVR SGX531
On GPD I have clear picture similar to the one I have on Linux/Windows. On the Jiayu picture is different.
For example see on the stealth indicator (moon) in left bottom on my very first screenshots. It looks like it have black square object placed upon it.
I hope this information have some value or you guys. And thanks again for great emulator!

**Comment by unknownbrackets** [comment] 2018-08-29 04:06
Hm.  Well Mali-T764 supports GLES3.

This uses absdiff dst, src to create those dark rings.  If this doesn't work properly, it could easily cause the screen to be mostly black.  The moon also uses absdiff, but for effects.

Slower effects tries to simulate absdiff.  On Mali, it probably does this relatively optimally using EXT_shader_framebuffer_fetch or ARM_shader_framebuffer_fetch.  On PowerVR and Vivante, it should be making a copy of the destination buffer (which will be slow) to attempt to do the effect manually since it's not supported by hardware.

It should be simulating absdiff in the same way it's simulated on desktop (which doesn't support the more optimal method.)  So when allowing the game to use buffers in its rendering and enabling slow effects, I'm not sure why it would turn white.

That being said, we've seen issues where on PowerVR devices certain math equations were calculated incorrectly.  Made something could be wrong with `abs()` here.

As for slow effects DISABLED, that will be affected by GLES2 vs GLES3.  Mali-T76x supports GLES3, so it will simulate this with `max(dst, src)` which is wrong, but not horribly wrong.  Will just cause the circular lines to be solid white, I suppose.

Unfortunately, GLES2 doesn't even support MAX, so it will simulate using `src * dst + dst * src`.  That ends up being a really unfortunate fallback in this case, because most of the texture (src) is black or zero.  Zero times anything is zero, so it means `zero + zero`.

We could probably improve this by forcing the blend factors to something else when absdiff is used... not sure what would work well, though.

-[Unknown]

**Comment by ResurrectionRedmi9** [comment] 2021-09-14 09:01
This is still an issue?

**Comment by oleyansen** [comment] 2021-09-19 09:31
> This is still an issue?

I have checked on my old Jiayu S3 smartphone with last version of PPSSPP (1.11.3), and yes it still an issue.
But @unknownbrackets * in the post above explained why it hard to fix this.

**Comment by Gamemulatorer** [comment] 2021-09-19 09:49
> I have checked on my old Jiayu S3 smartphone with last version of PPSSPP (1.11.3), and yes it still an issue.
> But @unknownbrackets * in the post above explained why it hard to fix this.

I cannot reproduce your issue using the latest ppsspp git build.
Redmi Note 9 Mali-G52 GPU

https://user-images.githubusercontent.com/37603562/133922998-a194024c-e123-49ef-9c4b-e8c9e65a79aa.mp4
https://user-images.githubusercontent.com/37603562/133923000-5eee275a-197d-4326-be8e-7afe2a090da0.mp4

**Comment by ResurrectionRedmi9** [comment] 2021-09-19 11:59
@oleyansen use latest github apk.

**Comment by oleyansen** [comment] 2021-09-19 16:28
> @oleyansen use latest github apk.

Checked with latest version from github (v1.11.3-1440-gde206611e) still the same issue which making game unplayable after shuriken kill.
However GPU on this phone is quite old: ARM Mali-T760 MP2, don't think it make sense to support it.

**Comment by Gamemulatorer** [comment] 2021-09-20 01:24
> Checked with latest version from github (v1.11.3-1440-gde206611e) still the same issue which making game unplayable after shuriken kill.
> However GPU on this phone is quite old: ARM Mali-T760 MP2, don't think it make sense to support it.

Maybe there's a problem on your phone?
Because I also tested this game on my ancient phone Mali-450 GPU GLES 2.0. Throwing shuriken doesn't make this game black screen.

https://user-images.githubusercontent.com/37603562/133949726-7a896e4f-2ff1-462e-9eb5-bb9ce1387e1a.mp4

**Comment by Gamemulatorer** [comment] 2021-09-20 06:36
@oleyansen can you screenrecord and upload how you reproduce the issue?

**Comment by oleyansen** [comment] 2021-09-20 06:45
No, this happened at first episode "Kill evil merchant" on the scene where you have to shuriken kill guard to take a key.
It contain death animation which probably have some influence on the bug.
This scene: https://cloud.githubusercontent.com/assets/3481559/12212863/0ced293a-b6aa-11e5-8f7d-14edf1f605c8.png

**Comment by Gamemulatorer** [comment] 2021-09-20 07:16
@oleyansen ok can you upload your savestates on that particular area?

**Comment by oleyansen** [comment] 2021-09-20 07:27
Sure @Gamemulatorer 
Here you are.
[ULUS10419.zip](https://github.com/hrydgard/ppsspp/files/7194155/ULUS10419.zip)

**Comment by Gamemulatorer** [comment] 2021-09-20 07:33
> Sure @Gamemulatorer
> Here you are.
> [ULUS10419.zip](https://github.com/hrydgard/ppsspp/files/7194155/ULUS10419.zip)

Thanks

**Comment by Gamemulatorer** [comment] 2021-09-20 07:43
Ok your using the usa version and I confirm that there's an issue.
As you can see in the picture below.
![Screenshot_2021-09-20-15-37-08-025_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133969865-d4c77999-0cf9-4748-b386-99bc98735591.jpg)
[ULUS10419.zip](https://github.com/hrydgard/ppsspp/files/7194227/ULUS10419.zip)

But I finally also go to that area and I'm using the europe version of the game and there's no issue, as you can see in this picture below. 
![Screenshot_2021-09-20-15-39-18-208_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133970116-26bd4409-d7ec-4ecf-946b-0ea39bd34dad.jpg)

Maybe you should try the europe version @oleyansen and see if you can still reproduce this issue on your phone?

**Comment by Gamemulatorer** [comment] 2021-09-20 07:48
For better comparison I screenrecord.

### USA VERSION

https://user-images.githubusercontent.com/37603562/133970634-1140422f-7bd4-4c82-9fc3-1bf3ae2701a6.mp4

### EUROPE VERSION

https://user-images.githubusercontent.com/37603562/133970659-1f0aadb7-05f5-49e8-9f4b-1b8f1fb6e0b0.mp4

**Comment by ResurrectionRedmi9** [comment] 2021-09-20 11:08
@oleyansen no feedback/outdated?

**Comment by oleyansen** [comment] 2021-09-20 11:12
> @oleyansen no feedback/outdated?

Just checked and it is still reproducible for EU version, having this black screen after suriken kill.
Will upload screenrecord later, have to work :)

**Comment by ResurrectionRedmi9** [comment] 2021-09-20 12:06
> > @oleyansen no feedback/outdated?
> 
> Just checked and it is still reproducible for EU version, having this black screen after suriken kill.
> Will upload screenrecord later, have to work :)

No problemo amigo I'm just trying to help you :)

**Comment by oleyansen** [comment] 2021-09-20 16:45
Well the phone is so old I can not find suitable screen recording software :)
will try also to check on ancient Samsung Galaxy Tab 4 with **Vivante GC1000** GPU

**Comment by oleyansen** [comment] 2021-09-21 06:15
> will try also to check on ancient Samsung Galaxy Tab 4 with **Vivante GC1000** GPU
I can confirm latest git version works well with Samsung Galaxy Tab

**Comment by ResurrectionRedmi9** [comment] 2021-09-21 06:26
> > will try also to check on ancient Samsung Galaxy Tab 4 with **Vivante GC1000** GPU
> 
> I can confirm latest git version works well with Samsung Galaxy Tab 4
> Thank you a lot for support !

Nice to know that 👍
But both US and EU version of the game?

**Comment by oleyansen** [comment] 2021-09-21 07:32
> > > will try also to check on ancient Samsung Galaxy Tab 4 with **Vivante GC1000** GPU
> > 
> > 
> > I can confirm latest git version works well with Samsung Galaxy Tab 4
> > Thank you a lot for support !
> 
> Nice to know that 
> But both US and EU version of the game?

Okay, I have checked again and both versions (EU and USA) works only for "Buffered rendering" mode.
But infamous black screen appears in "Skip buffer effects" mode for both versions on GalaxyTab 4.

**Comment by ResurrectionRedmi9** [comment] 2021-09-21 07:52
> Okay, I have checked again and both versions (EU and USA) works only for "Buffered rendering" mode.
> But infamous black screen appears in "Skip buffer effects" mode for both versions on GalaxyTab 4.

That's normal to black screen while skip-buffered rendering is enable because that's a hack.

@oleyansen This can be closed now? Or still happen on your Jiayu S3 and work fine only on Samsung Galaxy Tab 4?

**Comment by oleyansen** [comment] 2021-09-21 08:58
It still happen on Jiayu S3 in both modes and work fine only on Samsung Galaxy Tab 4.
But I'd rather close this issue as not relevant if this is ok with you.
Can I close it?

**Comment by hrydgard** [comment] 2021-09-21 09:05
Yeah, it's probably one of those driver bugs then that we'll in practice never get around to trying to work around. Closing.

**Closed by hrydgard** 2021-09-21 09:05 UTC
Labels: GE emulation

**Comment by Gamemulatorer** [comment] 2021-09-21 12:25
Yes I can confirm that both USA (undub) and EUROPE version has no graphics glitch on my ancient phone mali-450 gpu, so technically confirmed this is a driver bug.
