### ISSUE TITLE
[iOS] Cannot switch between OpenGL ES 3 and OpenGL ES 2 rendering backends

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#7759] opened 2015-05-21 00:12 UTC
This really isn't an useful feature for anyone other than developers, but it'd be nice to have an OpenGL ES 3/OpenGL ES 2 switcher in the Developer Tools menu so some bugs like #7756 can be tested across both backends.

Note: While the issue title does say iOS, this feature is relevant to Android, too.

**Comment by unknownbrackets** [comment] 2015-05-21 03:59
These aren't separate backends really.  We dynamically enable features based on what the card supports - and GLES3 features are just some of that mix.  Most of the drawing is the same, though.

You can find the differences here:
https://github.com/hrydgard/ppsspp/search?utf8=%E2%9C%93&q=gles3

Anyway, asking for a different context would probably require a restart or something at best.  Config settings aren't even loaded yet right now, I think.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-12-23 20:24
We're currently moving closer to making it so that the differences between desktop GL and GLES are more centralized.  So it might be possible to allow a user selection.

That being said, I personally think this is only really useful for developers.  Not only do we check GLES3, we also check individual extensions.  I think trying to build an interface to enable/disable each extension etc. would lead to a very confusing experience for some users.

In general, `gl_extensions.GLES3` can be set to false to simulate a GLES2 device, but if there are GLES3-specific problems, they may be caused by an extension being improperly implemented by a driver or anything.  Also, on desktop, we enable most of the same features for desktop GL 4.something+, because GLES3 is a subset of it, AFAIK.

I'm going to close this, because I don't think a user-facing option makes a lot of sense, and this hasn't generated any interest since it was filed.  But if you disagree, feel free to reply and I can reopen.

-[Unknown]

**Closed by unknownbrackets** 2015-12-23 20:24 UTC
Labels: Platform-specific (iOS)
