### ISSUE TITLE
Vulkan: Black screen on AMD with multithreading on

### ISSUE THREAD

**Issue by CesarAxe** [hrydgard/ppsspp#10097] opened 2017-11-12 16:03 UTC
This happens when switching from OpenGL or Directx to Vulkan backend and when starting the program.
Tested in Windows 10 Fall Creators Update 16299, Amd Radeon r7 250 with latest drivers.
![error1](https://user-images.githubusercontent.com/17837481/32700850-08fb0d36-c799-11e7-87d2-177b1609dc9e.PNG)

**Comment by hrydgard** [comment] 2017-11-13 09:10
Very odd, seems to work for everyone else. Was this self-built or a binary from https://buildbot.orphis.net/ppsspp/ ?

**Comment by CesarAxe** [comment] 2017-11-13 17:29
I'm testing with the binaries of https://buildbot.orphis.net/ppsspp/

**Comment by CesarAxe** [comment] 2017-11-16 08:48
I tried with a self-built and and I have the same problem, previous constructions for example  v1.4.2-534-ga33daa498 work without problems.

**Comment by hrydgard** [comment] 2017-11-16 09:23
You think you could try to figure out exactly when it broke? I'm stumped.

**Comment by hrydgard** [comment] 2017-11-16 15:31
@CesarAxe Is it the case that 534 works but 563 doesn't? Changed pretty much everything about the Vulkan backend in between there so this could be anything.

If it is, since you can build yourself, feel like trying a git bisect? https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git has a guide if you scroll down a bit.

**Comment by CesarAxe** [comment] 2017-11-16 16:02
No, the build 563 works properly. At this time I was testing and working properly until build v1.4.2-649-gb280e30a2 and fails from build v1.4.2-660-gea2fc5521 onwards. 
(binaries of https://buildbot.orphis.net/ppsspp/)

**Comment by hrydgard** [comment] 2017-11-16 16:17
Just to double-confirm before I dig deep, you're 100% sure that exactly 649 works and 660 doesn't? There is little in 660 that's vulkan-specific.

If it indeed is as above, can you check out 660 and change true to false on "useThread = true" in VulkanRenderManager.cpp? Also try without memstick/PSP/SYSTEM/ppsspp.ini to see if it's some setting.

To check out 660:

    git checkout ea2fc5521

**Comment by CesarAxe** [comment] 2017-11-16 16:42
Screenshots
![649](https://user-images.githubusercontent.com/17837481/32903177-5dc733b8-cac2-11e7-9fef-2b68f3dd34c6.png)
![660](https://user-images.githubusercontent.com/17837481/32903194-692d1362-cac2-11e7-86aa-c6d282052138.PNG)

It was solved by changing true to false on "useThread = true" in VulkanRenderManager.cpp
I try without memstick/PSP/SYSTEM/ppsspp.ini and not solve the problem.

**Comment by hrydgard** [comment] 2017-11-16 16:45
Thanks! If you check out master, change useThread to false, and build that, does it work?

Our Vulkan threading seems solid on all other platforms, curious that it wouldn't work on yours. But might have to blacklist it then.

With it working, then please go to Settings / Tools / System Information and take as screenshot there of vendor, driver version etc.

**Comment by CesarAxe** [comment] 2017-11-16 17:30
Yes, this solution works. I have installed Windows 10 Pro 16299.64, I could not say it because I have not tried in previous versions of Windows 10.
![vendor](https://user-images.githubusercontent.com/17837481/32906060-d4c5ed54-cac9-11e7-8a40-9f51cddc7fb5.png)

**Comment by unknownbrackets** [comment] 2017-11-17 03:23
If you can try building it in debug mode, and with useThread back on, it might log or alert errors about our Vulkan usage.

It'd be ideal if we were just doing something wrong, or something these AMD drivers doesn't like...

-[Unknown]

**Comment by CesarAxe** [comment] 2017-11-17 05:29
I built in debug mode with useThread true. A screenshot: 
![ddd](https://user-images.githubusercontent.com/17837481/32930657-fa14931c-cb2d-11e7-921e-24fcfe175e96.PNG)

**Comment by hrydgard** [comment] 2017-11-17 09:09
Yeah, that doesn't say very much. Two things about that though: Unless you have the Vulkan SDK installed, validation layers won't kick in. Also, the validation layers are mostly agnostic about what GPU they're running on so if we did something really wrong, we'd already have seen it. Probably...

**Comment by unknownbrackets** [comment] 2017-11-17 15:02
Ah right.  I was mostly hoping for an assert, though.

-[Unknown]

**Comment by CesarAxe** [comment] 2017-11-17 15:52
I have had installed vulkan SDK 1.0.65 from the beginning of the tests..

**Comment by hrydgard** [comment] 2017-11-17 15:59
Alright, then it should have asserted if it had found something and it didn't so this is really smelling like a driver bug..

**Comment by LunaMoo** [comment] 2017-11-18 07:15
I think this problem might be limited to windows 10 creator's update or any third party software that got buggy from that win10 update like all kinds of info overlays which were known to get broken from it. Can't reproduce this issue on windows 10 pre-creators update and frankly I'm scared to re-enable update services on my win 10 as it will take over my pc for long hours and then probably even more when I try to turn it off, don't have much reason to deal with this for now;p.

 On a side note I don't see any speed difference between Vulkan Multithreading On and Off, so if this isn't just my fast cpu + so-so gpu combo causing this lack of speed boost, current MT might as well not matter for AMD users.:]

**Comment by unknownbrackets** [comment] 2017-12-11 08:14
Has anything changed here (when updating it back to using threading and using the latest drivers available)?

-[Unknown]

**Comment by CesarAxe** [comment] 2017-12-16 02:57
@unknownbrackets @hrydgard I tried the new driver 17.12.1 on build 1.4.2-660-gea2fc5521 and it does not give that problem anymore.

**Comment by LunaMoo** [comment] 2017-12-16 12:04
Not sure if it's worth enabling this on AMD, from enabling MT I only get slight slowdown on Vulkan. It's not noticeably big, but it's unnecessary.

**Comment by unknownbrackets** [comment] 2018-02-25 02:31
I think there was a benefit for AMD with OpenGL from using a separate thread.  So that suggests this isn't categorically a pointless thing to enable on AMD.

But to keep sanity, I'm going to close this (it WAS fixed in 1.6.0) and create a new issue to reflect the threading problem as a future thing.

-[Unknown]

**Closed by unknownbrackets** 2018-02-25 02:31 UTC
Labels: Vulkan
