### ISSUE TITLE
[D3D9?][Fate/Extra] Weird clipping(?) issue in a specific area of the tutorial

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11397] opened 2018-09-18 02:01 UTC
Tested in last git as of this date.

Best to just present it with screenshots.

![image](https://user-images.githubusercontent.com/27028529/45659963-2ebcfe80-bacd-11e8-8edb-30c6242fadef.png)

![image](https://user-images.githubusercontent.com/27028529/45659983-41cfce80-bacd-11e8-8460-4b7fd66e8d0a.png)

It gets even weirder if your camera isn't even inside.

![image](https://user-images.githubusercontent.com/27028529/45660017-5b711600-bacd-11e8-9681-aab4790a68d0.png)

**Comment by unknownbrackets** [comment] 2021-05-16 23:51
Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by AkiraJkr** [comment] 2021-05-17 06:36
[ULUS10576_0001.zip](https://github.com/hrydgard/ppsspp/files/6491625/ULUS10576_0001.zip)

**Comment by unknownbrackets** [comment] 2021-05-23 19:57
Between 295/431 and 306/431, it looks like it should draw there.  And it does, if I disable depth testing.  It uses a >= depth test.

D3D 9 doesn't show the depth in the debugger, which makes things harder (actually, I thought my GPU did support that?)  If I ignore the fboINTZ check, I see the depth is maybe approximately equal.  Depth rounding doesn't appear to help.  And using a `>` test in other backends doesn't replicate the issue.

Forcing it to flush after a single triangle doesn't even help:
![image](https://user-images.githubusercontent.com/191233/119274728-2f838800-bbc6-11eb-9297-09d267075f57.png)

Seems a bit strange...

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-10-23 16:47
This was fixed, I did a quick bisect because I was curious - fixed by #15794.  I think it was probably a vertexFullAlpha state issue.

-[Unknown]

**Closed by unknownbrackets** 2022-10-23 16:47 UTC

**Comment by hrydgard** [comment] 2022-10-23 16:50
Nice, thanks for checking.
