### ISSUE TITLE
[iOS] PPSSPP won't launch and gets stuck in springboard after quitting it.

### ISSUE THREAD

**Issue by sherlockeb** [hrydgard/ppsspp#10872] opened 2018-04-04 17:50 UTC
I'm using and iPad mini 2 on iOS 9.3.3 jail broken with Pangu and have the most recent PPSSPP(dev-latest) version from the  Cydia repo

When I launch PPSSPP for the first time everything works as expected but when i close the app and try to relaunch it again nothing happens, and after I press the PPSSPP icon  nothing launches when I press any  apps icons. I get stuck in springboard and while I can move around the pages, pressing icons doesn't do anything and I can't enter multitasking or anything. 

When this happens I'm forced to reset my device and reapply jailbreak. Then I can launch PPSSPP one more time but if I quit PPSSPP same thing happens all over again.

**Comment by unknownbrackets** [comment] 2018-04-05 13:51
This issue is being closed as a duplicate of #9186.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-04-05 13:51 UTC
Labels: Platform-specific (iOS)
