### ISSUE TITLE
Prince of Persia Revelations graphics bugs.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#11038] opened 2018-05-14 04:56 UTC
### What happens?
See those squares with default settings:
![screenshot_20180513-234416](https://user-images.githubusercontent.com/6578180/39978977-39c3fcf2-5709-11e8-8925-622bc3f78c60.png)

### What *should* happen?
Not that

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 7, latest ppsspp dev, happens in both gl and vulkan.

**Comment by marosis** [comment] 2018-05-14 06:33
Is this problem without HW transforming? Is this bug in older builds? If not, can you find build where it started?

**Comment by leopard20** [comment] 2018-05-14 18:25
@marosis Actually, It's always been like this.

**Comment by hrydgard** [comment] 2018-05-14 19:19
Not sure exactly what trick they're trying to do in this game, hard to say...

**Comment by unknownbrackets** [comment] 2018-05-14 22:40
I'm guessing it's probably some stencil/RGBA mask/logic op issue?  I feel like there may be another issue about this... maybe.

-[Unknown]

**Comment by Jinzombie** [comment] 2018-05-15 00:34
look similar issue #10977 but different games

**Comment by leopard20** [comment] 2018-05-15 08:26
Actually, I think it's the same issue!

**Comment by leopard20** [comment] 2018-06-04 12:37
@hrydgard This is more or less a duplicate of https://github.com/hrydgard/ppsspp/issues/6423.

**Comment by hrydgard** [comment] 2018-06-04 12:59
@weihuoya , that's really interesting, thanks for reporting that.

**Comment by hrydgard** [comment] 2020-04-26 09:58
Duplicate of #6423

**Closed by hrydgard** 2020-04-26 09:58 UTC
