### ISSUE TITLE
project diva extend multi-thread lag issues

### ISSUE THREAD

**Issue by AkagiShiroe** [hrydgard/ppsspp#9625] opened 2017-04-17 18:37 UTC
first sorry for my bad english,then let me explain my problem.
im using this version : ppsspp-v1.4-87-g627c280
im encountering an issue where FPS drop a lot if use Multi-threaded and have a lag latency with button with/without that settings. also in "world is mine" song there's a few second in scene where vertex are screw-up all-over with/without tesselation.
i use this setting:
Mipmapping
Hardware transform
Software skinning
Vertex cache
Anistropic filtering 16x
Force real clock sync

i hope this issue solved.

**Comment by unknownbrackets** [comment] 2017-04-18 03:43
This issue is being closed as a duplicate of #6441.

This is an issue tracker - there's a [forum if you want to discuss things] (http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2017-04-18 03:43 UTC
