### ISSUE TITLE
Feature Request CHD file support

### ISSUE THREAD

**Issue by Augusto7743** [hrydgard/ppsspp#15667] opened 2022-07-11 01:27 UTC
### What should happen

Thanks for read my topic.
Any chance to add CHD file support in PPSSPP ?
CHD save much disk space.
Thanks very much PPSSPP creator.
Have an nice week.

### Who would this benefit

users

### Games this would be useful in

any game

### Other emulators or software with a similar feature

MAME use CHD for cd, hdd and others media dumps.
Retroarch use chd and has an PPSSPP core, but not chd support.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment] 2022-07-11 01:38
This issue is being closed as a duplicate of #10417.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-07-11 01:38 UTC
