### ISSUE TITLE
Cars RaceORama Screen lines and low FPS

### ISSUE THREAD

**Issue by Gelo021** [hrydgard/ppsspp#17719] opened 2023-07-14 22:12 UTC
Hi my son wants to play cars so i put Car Raceorama
But there are so many bugs and issue like lines and super low fps. 
![Screenshot_2023-07-15-06-10-21-57_2f85358b2198d26f8aca533d68bee793](https://github.com/hrydgard/ppsspp/assets/67460268/140dd4af-edd9-4ce5-9919-5c05fa90ae53)

**Comment by Gelo021** [comment] 2023-07-14 22:45
@hrydgard

**Comment by hrydgard** [comment] 2023-07-15 10:07
@Gelo021 This is a well known issue, the game is very problematic with how it does rendering. It took a lot of work to even get it to this point, and it'll take even more very specific work to fully fix it. It will be done, but there are also other priorities.

The issue report to follow is #15914  .

Closing as duplicate of that one.

**Closed by hrydgard** 2023-07-15 10:07 UTC

**Comment by Gelo021** [comment] 2023-07-15 14:14
Thanks for the info @hrydgard

**Comment by hrydgard** [comment] 2026-06-28 09:22
@cevamnelampaplagin #15914 is still open, no need to bump this.

**Comment by luisgabrielalvesmartins1-maker** [comment] 2026-07-22 20:33
eu estou com o mesmo problema, o meu moto g24 roda este jogo que nem o meu galaxy j8, eu tentei baixar os graficos, mas não adiantou. vocês poderia resolver este problema? é que faz 3 anos
