### ISSUE TITLE
Some problems if  mhfu saves

### ISSUE THREAD

**Issue by splosions** [hrydgard/ppsspp#12078] opened 2019-06-03 01:25 UTC
I need help solving something with the monster hunter freedom unite saves,
start with me playing mhfu I made 3 different characters and put each one in a different slot, I played with them for a while only using save state until I decided not to use more save state, but after a while the game simply stopped saving and give an error saying that there is no memory stick duo in my psp, and I tried reloading the characters using save state but they started to say that there was no mhfu character in psp and that I had to do another, and even I wanted save with the save state characters they just do not work

ppsspp 1.8.0, android, my cell phone is samsung, 4 gb of memory (the game gets at least 16 fps)

I have some screenshots 
![Screenshot_2019-05-31-05-10-47](https://user-images.githubusercontent.com/51303463/58770443-51247880-8585-11e9-8b5a-c2c5df1ec2d3.png)

![Screenshot_2019-05-31-05-09-35](https://user-images.githubusercontent.com/51303463/58770130-5bde0e00-8583-11e9-9375-52d0ce99780b.png)

**Comment by unknownbrackets** [comment] 2019-06-03 05:16
You can TRY going into settings, setting "memory stick inserted" off, play the game for a bit, then go back and set it back to on.  Probably it won't help.

Unfortunately, the game gets confused and angry when you use magic / time travel in front of it.  It doesn't like what it doesn't understand.  See here:

https://forums.ppsspp.org/showthread.php?tid=445&pid=106844#pid106844

I'm going to close this as a duplicate of #7244.

-[Unknown]

**Closed by unknownbrackets** 2019-06-03 05:16 UTC
