### ISSUE TITLE
Can't download any file

### ISSUE THREAD

**Issue by vikas2316** [hrydgard/ppsspp#11698] opened 2018-12-25 21:19 UTC
PPSSPP was open in background and i was downloading a software, i was getting a error again and again, i tried using idm but it didn't work after that i realized PPSSPP was using that folder, can something be done about it, if not is it possible to add error message?

        8 GB Ram
        i5 8400
        GTX 1060
        Windows 10 1809
        PPSSPP 1.7.4 latest stable version at the moment.

**Comment by unknownbrackets** [comment] 2018-12-26 18:47
I've never seen PPSSPP interfere with file downloads in any way.  That said, if you open a file in a folder, PPSSPP may "use" the folder until you close it or open a different file.

What was the error message you got again and again?

It sounds like you need a clearer error message from the other program you were using.

-[Unknown]

**Comment by hrydgard** [comment] 2019-02-25 20:47
Think I found the cause, finally. #11842 should fix this.

**Closed** 2019-02-25 20:49 UTC
