### ISSUE TITLE
Monster Hunter Freedom Unite broken on Mali GPUs with Vulkan

### ISSUE THREAD

**Issue by PepeJulio** [hrydgard/ppsspp#9895] opened 2017-08-12 00:48 UTC
Would you say that, right now, Vulkan backend is more likely to present bugs on Mali GPUs than Adreno GPUs?

**Comment by hrydgard** [comment] 2017-08-12 08:11
I haven't seen anything to indicate that.

**Comment by PepeJulio** [comment] 2017-08-12 15:41
This is MHFU on a Mali T-860MP2:

https://m.imgur.com/riHlwRa

And this is MHFU on Adreno 530:

http://i.imgur.com/Xnd0Jmu.jpg

**Comment by hrydgard** [comment] 2017-08-12 15:54
Well, that's clearly a case where something goes wrong on Mali. Could be either a bug in PPSSPP or in the Vulkan driver.

**Comment by Michal1324** [comment] 2017-08-13 17:41
I would assume game specific issue

**Comment by Hydroque** [comment] 2017-08-15 04:22
It isn't the game thats the problem. The rip looks fine under one architecture.

**Comment by hrydgard** [comment] 2017-08-17 19:10
Should be fixed in the last few builds, it really doesn't like out of range viewport depth values.

**Comment by PepeJulio** [comment] 2017-08-18 15:02
Sorry if this starts to get annoying, but everything is exacly the same.

**Comment by hrydgard** [comment] 2017-08-18 15:25
Tried it on an S8 with Mali, it worked. Strange.

**Comment by PepeJulio** [comment] 2017-08-18 15:40
What are the settings you used on S8?

**Comment by PepeJulio** [comment] 2017-08-18 16:34
In any case, here is actual footage of the issue:

https://www.youtube.com/watch?v=cYtolz1Srhc

**Comment by Michal1324** [comment] 2017-08-18 16:53
So its device or setting specific issue so I was pretty close

What phone Pepe is it that you are using?

**Comment by PepeJulio** [comment] 2017-08-18 17:00
Sony Xperia XA

**Comment by Michal1324** [comment] 2017-08-18 17:10
I've checked Xperia Xa and ultra they seem the same I happen to have ultra will give more info after the test

**Comment by Michal1324** [comment] 2017-08-18 17:24
I've checked it yep it appears that Vulkan appears to be broken on that game on Xpiera's XA's

Can confirm the game suffers from the issue Pepe mentioned

**Comment by hrydgard** [comment] 2017-08-18 21:57
It's really hard to tell whether PPSSPP is accidentally mis-using Vulkan somehow, or whether the GPU driver is buggy. PPSSPP's Vulkan code still fails a few tests when running with the Vulkan validation layers on PC, I aim to clear that up in the near future, which may help.

**Comment by Hydroque** [comment] 2017-08-19 05:54
Does software rendering work? Maybe that would eliminate some probable faults. It isn't a work-around, but we do know then if it is the CPU (telling vulkan to set things up) or the GPU (being buggy with given information).

**Comment by PepeJulio** [comment] 2017-08-19 13:29
Where was that option again? Cant seem to find it.

**Comment by hrydgard** [comment] 2017-08-19 16:10
Since it's usually a really bad idea to use SW rendering on Android, I removed it. You can manually enable it anyway by setting SoftwareRendering = False under [Graphics] in PSP/SYSTEM/ppsspp.ini on your device.

But I'm pretty sure this is an issue with the Vulkan code so doing so is unlikely to be of any use.

**Comment by PepeJulio** [comment] 2017-08-19 16:29
Look at this:

http://m.imgur.com/elL7tjX

That was software rendering with Vulkan, meaning that our problem is the CPU giving wrong instructions.

**Comment by Hydroque** [comment] 2017-08-20 04:52
That was actually software rendering, without vulkan. This means that the graphics card's drivers or a bug is present.

**Comment by PepeJulio** [comment] 2017-11-05 23:36
@hrydgard 
Hello, Henrik. Since we're having some vulkan changes around, I figured it'd be good to try again something regarding this issue. 

@Hydroque proposed testing a bit with software rendering in trying to pinpoint a sollution, so I just checked again and this is MHFU on Vulkan backend with software rendering right now:

https://imgur.com/gallery/calPw

As you can see, nothing draws, which is different from last time.

Now, this is MHFU on OpenGL with software rendering right now:

https://imgur.com/gallery/b4pjC

Hardware is exactly the same. I'm no good guessing what this means, so I'd like any of you to interpret it.

I'd also like to know how to take logs so I can upload them to you. That's probably the best way fix this issue.

Regards,
 Pepe

**Comment by Hydroque** [comment] 2017-11-06 00:57
I was bringing up a point to validate the environment because lack of full standards. Everything needed should be set. This is a good set to prevent a mysterious error. We also had some z fighting issues that could be related.

**Comment by unknownbrackets** [comment] 2017-11-06 03:30
There's a bug in Vulkan right now causing software rendering to be black.

When using software rendering, the backend code does only one operation: copy the result of the software render to the screen.  That means it uses a small subset of the features of your Vulkan driver, and also a small subset of the Vulkan code in PPSSPP.

So, regardless of the result of software rendering, this could still be a bug in PPSSPP's Vulkan backend code in hardware mode.  It's hard to tell.

-[Unknown]

**Comment by Hydroque** [comment] 2017-11-06 05:51
Your software mode is ambiguous

**Comment by unknownbrackets** [comment] 2017-11-06 06:43
Software rendering draws everything - really, everything - in software.

The benefit is it's not restricted by silly rules like "you can't just access the depth buffer like that" or "that's not how alpha blending ought to work" that OpenGL and Vulkan and Direct3D drivers impose.  It's total freedom.

We have workarounds for almost all of the differences between the PSP's rules and modern driver's rules.  But they're complex and not all perfect.  Testing in software rendering is a good way to figure out if the bug is caused by a rule we're not dodging properly, or maybe it's not even a bug in our rendering code at all.

About the bug: very strange.  Have you tried toggling software skinning (this applies "skinning", a model technique, on software where it typically ends up faster), and vertex caching?

I wonder if we're somehow ending up with the wrong kind of depth buffer...

-[Unknown]

**Comment by PepeJulio** [comment] 2017-11-06 10:56
Yes, I've tried with those two options on and off. Everything is still like in the attached video above.

**Comment by Hydroque** [comment] 2017-11-07 01:49
I wonder if the depth buffer is inverted >.>

**Comment by hrydgard** [comment] 2017-11-08 16:17
Just worked around a depth-buffer related Mali bug, it might be completely unrelated though, but might be worth giving it another try with the latest build. Works for me though on S8, as usual.

**Comment by PepeJulio** [comment] 2017-11-08 18:58
"Unable to open the svn log file rev/gitlog.xml" 
says buildbot page.

**Comment by PepeJulio** [comment] 2017-11-08 23:52
Sadly, it keeps failing.

**Comment by PepeJulio** [comment] 2017-11-11 17:06
Hey, surprise! It's working now!!

**Comment by hrydgard** [comment] 2017-11-11 17:21
Cool! I guess older Mali drivers also had problems with reverse Z, which was worked around by https://github.com/hrydgard/ppsspp/pull/10086 .

**Closed by hrydgard** 2017-11-11 17:21 UTC
Labels: Vulkan

**Comment by Hydroque** [comment] 2017-11-15 23:55
Hey I was right!

**Comment by hrydgard** [comment] 2017-11-16 00:19
Congrats :)
