### ISSUE TITLE
you can support 320x160 pixel?

### ISSUE THREAD

**Issue by tee4341** [hrydgard/ppsspp#13988] opened 2021-01-28 09:50 UTC
you can support 320x160 pixel?
![GifMaker_lowquality16](https://user-images.githubusercontent.com/48321898/106120486-03f90f80-6189-11eb-9ed5-641e199b868f.gif)

**Comment by hrydgard** [comment] 2021-01-28 09:56
Duplicate of #13984 and #12644 . Please don't create additional issues about the same thing.

**Closed by hrydgard** 2021-01-28 09:56 UTC
