### ISSUE TITLE
Daxter: rendering issues on Adreno 640 and Vulkan backend

### ISSUE THREAD

**Issue by l0ud** [hrydgard/ppsspp#12487] opened 2019-11-13 21:53 UTC
### What happens?
Daxter have multiple small visual glitches when using Vulkan backend on Adreno 640 (Mi9T Pro). Glitches don't happen on OpenGL backend.

- Daxter has green teeth and features (UPDATE: Seems fixed now)
![Screenshot_2019-11-13-22-40-46-955_org ppsspp ppsspp](https://user-images.githubusercontent.com/778851/68807103-80c4ca00-0667-11ea-8cdd-41370bbc85e2.png)
- There is no shadow or shadow is misaligned and flickering. I can also see some flickering on ground.
![Screenshot_2019-11-13-22-35-55-128_org ppsspp ppsspp](https://user-images.githubusercontent.com/778851/68807158-9d610200-0667-11ea-8286-0a0a03b97dd5.png)

### What *should* happen?
Game should look as on OpenGL backend.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- PPSSPP v1.9.4 (newest from Google Play)
- Mi9T Pro
- Snapdragon 855
- Adreno 640
- Android 9

Rendering resolution is set to Auto (glitch happen as well on 1x, 2x and 3x resolutions). Buffered rendering is on.

**Comment by hrydgard** [comment] 2019-11-13 22:55
Wow, that's an odd glitch. Should be looked into for sure.

**Comment by unknownbrackets** [comment] 2019-12-25 07:07
Does it look fine on other devices?

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-03-18 07:49
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by l0ud** [comment] 2020-03-18 21:46
Here you are, two captures from main menu, where green features can be observed.

[recordings.zip](https://github.com/hrydgard/ppsspp/files/4351495/recordings.zip)

**Comment by l0ud** [comment] 2020-03-18 23:13
And this one is for hub are, for some reason there is no green stuff this time, but I can see wrong Daxter shadow and terrrain texture flickering at seams.
[recording(3).ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4351809/recording.3.ppdmp.zip)

**Comment by unknownbrackets** [comment] 2020-03-22 22:57
It seems to draw the shadow from 0x04161800, and it draws that from the primary framebuffer apparently without clearing it.  Maybe we're missing or optimizing away a memset that would clear that and make the shadow more correct.

Hard to say about flickering.

For the green, assuming it still happens, a frame dump of the "New Game" menu screen would be ideal.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-03-22 23:42
The goggle things are initially drawn (134/4556) drawn with a pretty normal, but solid gray, texture.  There's no RGB mask or crazy blend/logic ops, but it is using weights for the vertices.  The vertex colors alternate between two shades of brown, which is about the right color.  Lighting is enabled, but none of the lighting colors are very green.

It goes over them again (154/4556) and uses blending to add some glow.  The texture is grayscale and there's still no green involved.  That said, the parts that are wrongly green are also the places that have this glow added.

Does disabling hardware transform change any of this?

-[Unknown]

**Comment by l0ud** [comment] 2020-03-23 00:07
Disabling hardware transform doesn't seem to change anything, all issues are still present.

**Comment by hrydgard** [comment] 2020-11-11 10:24
Still the case in the latest builds?

**Comment by Panderner** [comment] 2021-02-08 11:50
In latest builds of PPSSPP the green teeth and features are fixed.
![Screenshot_2021-02-08-19-44-14-083_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/107215866-e0ff1300-6a46-11eb-8e89-13aa503770b7.jpg)

But the shadows are not fixed
![Screenshot_2021-02-08-19-46-50-837_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/107215884-e9efe480-6a46-11eb-9455-3e6c4339a097.jpg)
![Screenshot_2021-02-08-19-47-01-855_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/107215887-eb211180-6a46-11eb-971b-4458f8556f75.jpg)

**Comment by unknownbrackets** [comment] 2022-01-09 04:17
Is this any better now?  I think there's a decent chance #15024 may have fixed this.

-[Unknown]

**Comment by Panderner** [comment] 2022-01-09 07:43
Still happens in latest version.
![Screenshot_2022-01-09-15-42-15-871_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/148673660-3098f3fc-1e98-498d-bd93-9f2977f11361.jpg)

**Comment by Panderner** [comment] 2022-01-12 03:29
Shadows works fine for my PC using Vulkan.
![PPSSPP v1 12 3-607-g2d7a7fd34 - UCUS98618 _ Daxter 1_12_2022 11_24_55 AM (1)](https://user-images.githubusercontent.com/37503397/149058760-e9138f15-ff20-472b-ba3d-3aced9f01369.png)

**Comment by unknownbrackets** [comment] 2022-10-26 04:38
Shadow is drawn at 1246/4087:
 * Blend: ZERO + (1.0 - src.a) * dst (aka darken by alpha amount)
 * Texture matrix from position.
 * Depth clamp (no verts near clipping or outside z)
 * Lighting and colors (which are pointless because it blends away the color - maybe could detect this and optimize in softgpu?)
 * Depth <= test.

I suspect the problem is the depth test.  Before, depth is 248,243: 58130 / 0.887007... after, unchanged.  So it must rely on an exact equals for the depth.

Depth is initially cleared at 29/4087, in strange horizontal strips (most games use vertical strips.)  It then clears 38/4087 using a subsection clear only, irregular but works.  Then it draws the shadow to the primary framebuffer (so unusual) and blits it to a temporary buffer.  It uses a stencil test to bring over the alpha (either 0 or 7F) with a > 0 alpha test and stencil pass set.  It does this to resize the shadow down to 64x64, but it's kinda pointless because the stencil technique it uses still results in a single-color shadow, bunt I guess this enlarges the edges a little.

At 97/4087, it tries to clear the stencil it rendered to the primary buffer for the shadow, but forgets to enable stencil testing or clear mode so just wastes its time.  RGB mask=FFFFFF, stencil off, zwrite off.  Could maybe optimize this out in softgpu too.

At this point, depth is 100% 0xFFFF, which it seems to define as far.

The floor is drawn at 1232/4087.  Float positions, same as the shadow.  It seems to send exactly the same positions and exactly the same matrix, so one would hope that it calculates exactly the same depth.

This only happens in Vulkan?  Does PixelDepthRounding prevent it?

-[Unknown]

**Comment by hrydgard** [comment] 2022-11-29 14:00
How is this now?

**Comment by Panderner** [comment] 2022-11-30 01:56
It seems it's fixed now for latest builds.
![Screenshot_2022-11-30-09-54-32-242_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/204688567-24ba2f57-b50f-4843-acb3-0c925583f094.jpg)

**Closed** 2022-11-30 07:03 UTC
Labels: Vulkan
