### ISSUE TITLE
Performance loss from 1399 build ppsspp and above

### ISSUE THREAD

**Issue by ASKUTKRIMSON** [hrydgard/ppsspp#14965] opened 2021-10-04 13:32 UTC
### Game or games this happens in

ULUS-10466 (Tekken 6)

### What area of the game / PPSSPP

When I play the 1402 - fps game build, it immediately starts to go from 20 to 35 fps (everywhere), while in the 1399 build, the game goes to 60 fps in all places. What I just didn't do to fix it, I had to make a new PSP folder several times, edit textures.ini several times and reset the settings in the UI. All my friends have the same problem, they all have android and before build 1402 everything was going fine at 60 fps. The problem does not lie at all in the enabled vertical synchronization on android, since the low fps does not disappear when switching to OpenGL, all my friends did everything I told above, but we could not figure out what the error was. This problem is also observed in Tekken 5 dark resurrection and Metal gear solid peace walker.  Please help

### What should happen

All games must go to 60 fps, because when updating the build to a new one, all settings are saved, which means that if the old build has 60 fps, then there can be no 20-35 on the new one

### Logs

I don't know how to save logs on android

### Platform

Android

### Mobile phone model or graphics card

Xiaomi redmi note 8 pro

### PPSSPP version affected

v1.11.3 - 1402

### Last working version

v1.11.3 - 1399

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2021-10-04 13:41
Just checking, you already confirmed that it's not fixed in the very latest builds, right? (after 1632)?

**Comment by Gamemulatorer** [comment] 2021-10-04 14:00
No changes in performance on my phone (Redmi Note 9) still the same both OGL and VK using default settings.
![Screenshot_2021-10-04-21-50-41-774_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135864888-5431783f-9233-4d36-83c0-7aa47007f3cc.jpg)
![Screenshot_2021-10-04-21-50-08-198_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135864895-c48e9de5-d2bb-43fc-a074-76e94e45ca39.jpg)
![Screenshot_2021-10-04-21-56-59-230_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135864896-0faa8813-d395-4c55-9be1-b12cda2232e3.jpg)

**Closed** 2021-10-04 15:50 UTC
Labels: Performance

**Comment by Gamemulatorer** [comment] 2021-10-04 15:55
@ASKUTKRIMSON closing without explaining why?
are you using replace textures pack on Tekken6?

**Comment by unknownbrackets** [comment] 2021-10-04 16:00
Turns out this happens when the vsync flag is enabled in ppsspp.ini on Android.  Maybe we should remove the half-working vsync code path on Android, in case someone copies settings across...

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-10-04 16:11
I try to enable vsync flag on Tekken6 and my phone performance still the
same 🤔

**Comment by unknownbrackets** [comment] 2021-10-04 16:16
It's not a well tested path or one lots of people might use, it may even be a driver issue or specific to certain refresh rates, etc.  It wasn't a path we meant to be used yet, because you can't enable vsync on Android directly, only by editing the ini.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-10-04 16:20
> It wasn't a path we meant to be used yet, because you can't enable vsync on Android directly, only by editing the ini.
> 
> -[Unknown]

This is it right?
![Screenshot_2021-10-05-00-19-42-071_com rhmsoft edit](https://user-images.githubusercontent.com/37603562/135887768-58d22788-61e0-42e5-b11b-19eb0f767c90.jpg)

**Comment by unknownbrackets** [comment] 2021-10-04 16:22
Yeah, that's right.

-[Unknown]
