### ISSUE TITLE
Invizimals crash when camera initialized  - 1.10.1

### ISSUE THREAD

**Issue by Ex-e-LD** [hrydgard/ppsspp#13091] opened 2020-07-04 16:25 UTC
This is my first time writing here,so i will try to help as much as i could,i'm open to anything,GitHub is new to me and PPSSPP as well,i'm veteran in Gameboy Advance emulation on Android with emulator called MyBoy! GBA Emulator.

I got an USA .ISO game Invizimals,and when i tried 1.5.4 back in the day,game showed some bad written **PPSSPP Camera :)**
Since really lot of time passed since that version,i decided i should give it a try and i basically did,and i noticed some new settings that seem to optimize emulation and i was lucky to give it a try,including Invizimals,but when i saw it still crashes,i decided i should report bug to you developers in order for you to fix it

Phone:Honor 9S
GPU:PowerVR GE8320
CPU:Metiatek MT6762R Helio P22
Camera:8 MP, f/2.0, (wide), AF
Phone camera is 
- 0:Back Camera

**Camera permission is enabled in Settings,and Location is too as well**

TIA

Edit:
- 0 is Back Camera,not Front

**Comment by Panderner** [comment] 2020-07-04 16:27
Duplicate of #12997

**Comment by Ex-e-LD** [comment] 2020-07-04 16:31
> Duplicate of #12997

If you haven't seen,this is 1.10.1 version,that being 1.9.4 i believe,and if i'm not wrong,1.10.1 is newest one,3 weeks being released (my friend told me this at the Gilded server i'm member of that is focused around GBA emulation)

**Comment by hrydgard** [comment] 2020-07-04 21:24
Thanks for reporting. I'm seeing some strange camera-related crashes from primarily Huawei phones. Will investigate.

**Comment by hrydgard** [comment] 2020-07-04 22:35
```
07-05 00:33:19.558 12358 12358 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-05 00:33:19.559 12358 12358 E AndroidRuntime: FATAL EXCEPTION: main
07-05 00:33:19.559 12358 12358 E AndroidRuntime: Process: org.ppsspp.ppsspp, PID: 12358
07-05 00:33:19.559 12358 12358 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=38016; index=-11416
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at org.ppsspp.ppsspp.CameraHelper.rotateNV21(CameraHelper.java:76)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at org.ppsspp.ppsspp.CameraHelper$1.onPreviewFrame(CameraHelper.java:116)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1167)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6861)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
07-05 00:33:19.559 12358 12358 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Got this out of an Honor phone. Looks like at least one problem is some logic bug in rotateNV21. Looking into it.

**Comment by hrydgard** [comment] 2020-07-04 22:42
Okay so it turns out the preview of the camera on these cheap phones is incredibly tiny, 176x144. This breaks the logic in rotateNV21.

**Comment by hrydgard** [comment] 2020-07-04 22:56
Actually, seems the previewSize loop is kinda broken. It stops on the first preview size it finds that's smaller than 640x480, which isn't the best strategy.

**Closed** 2020-07-04 23:52 UTC

**Comment by Le-O-LD** [comment] 2020-07-06 10:46
@hrydgard Can we expect this as update as 1.10.2 or it will be 1.11?

**Comment by hrydgard** [comment] 2020-07-06 10:53
It will be v1.10.2.

**Comment by EX-e-LD** [comment] 2020-07-06 10:58
> It will be v1.10.2, quite soon.

Thank for your hard work,i will report any more issues if i find them,if not problem ofc

**Comment by HiImBrala** [comment] 2020-08-07 19:24
> GitHub is new to me and PPSSPP as well,i'm veteran in Gameboy Advance emulation on Android with emulator called MyBoy! GBA Emulator.

Nice,do you know how to use IRC Freenode?I would like to talk to you at #PPSSPP freenode,i have few questions to ask you,since i also was at GBA scene,it was my first thing in my first year of getting into emulation.I understand if i disturb you or something

**Comment by EX-e-LD** [comment] 2020-08-07 19:31
@HiImBrala 
Hi.No,sorry,i don't,i can try to use it if it doesn't need any installation or register account process,as i'm really tired.Could you explain or give me a link for process?

TIA

**Comment by HiImBrala** [comment] 2020-08-07 19:41
@EX-e-LD 
Unfortunately,#ppsspp doesn't work anymore,just follow this and message me on ID Brala3101
https://freenode.net/kb/answer/registration

**Comment by EX-e-LD** [comment] 2020-08-07 19:48
@HiImBrala 
Sorry,i could not understand this,way too complicated.Can you make repo here,give me link,and when we start conversation delete the link?

TIA

**Comment by HiImBrala** [comment] 2020-08-07 20:04
@EX-e-LD 
https://github.com/HiImBrala/brala3101/issues/1
Take your time to answer,i consider this bit rude,but it is your opinion after all.
