### ISSUE TITLE
nascar 07 graphical issues on android

### ISSUE THREAD

**Issue by Jordan24241** [hrydgard/ppsspp#6583] opened 2014-07-20 03:46 UTC
![screenshot_2014-07-19-20-41-35](https://cloud.githubusercontent.com/assets/8213223/3636432/7962c9ea-0fc0-11e4-80df-c4a704d5cc92.png)
Nascar 07 has problems with invisible track peices random objects on the track and black walls?
![screenshot_2014-07-19-20-42-17](https://cloud.githubusercontent.com/assets/8213223/3636429/4a03ce38-0fc0-11e4-9d21-c0ac3d037dd3.png)
![screenshot_2014-07-19-20-42-39](https://cloud.githubusercontent.com/assets/8213223/3636428/3d9c13b2-0fc0-11e4-9c02-34bb571c9738.png)

**Comment by unknownbrackets** [comment] 2015-02-24 04:49
It's not likely, but does #7515 improve this at all?

-[Unknown]

**Comment by unknownbrackets** [comment] 2016-01-22 06:28
It's also possible recent depth issues or flat shading I guess even could've helped.  Would be great if you could try this in the latest git build.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-22 16:05
Still the same

**Comment by unknownbrackets** [comment] 2017-12-11 08:29
Closing in favor of #9948, which is more direct and the problem is now known there.

-[Unknown]

**Closed by unknownbrackets** 2017-12-11 08:29 UTC

**Comment by QWEmct** [comment] 2018-03-25 18:42
Hi. Could you make it possible to use Doom 3 using PPSSPP ?
