### ISSUE TITLE
Yugioh Arc V tag force special CRASH during End Phase

### ISSUE THREAD

**Issue by mike13dash** [hrydgard/ppsspp#8383] opened 2016-01-04 11:21 UTC
before upgrading my android from kitkat to lollipop i never had this issue but now i couldn't play this game due to crash when i end my turn (end phase)... btw how do i generate crash log on ppsspp android? im using the ppsspp svn latest version...

-- Note: broken by fed687f / #7839

**Comment by unknownbrackets** [comment] 2016-01-04 15:17
You'll need to use adb logcat to get a log:

https://www.google.com/search?q=how+to+adb+logcat&ie=utf-8&oe=utf-8

-[Unknown]

**Comment by sum2012** [comment] 2016-01-06 22:22
In the chinese forum ,there are many people report this bug,but I don't repoduce this bug.
My phone "Asus zenfene 2"

**Comment by sum2012** [comment] 2016-01-06 22:25
Can you try v1.0 work or not ?
http://www.ppsspp.org/files/1_0/ppsspp.apk

**Comment by sum2012** [comment] 2016-01-12 21:15
I heard from chinese baidu forum,that maybe 8 core cpu bug

**Comment by unknownbrackets** [comment] 2016-01-13 03:32
Are you sure they're not using multithreading, then?

-[Unknown]

**Comment by sum2012** [comment] 2016-01-13 06:45
He tell me that do not effect mutithreadding.
v1.01 work
v1.1 not work

**Comment by sum2012** [comment] 2016-01-15 11:40
Today he test v1.0.1-781-gabc0f88 not work

**Comment by sum2012** [comment] 2016-01-15 12:36
My friend tested that is #7839 break

**Comment by sum2012** [comment] 2016-01-15 13:35
@unknownbrackets @hrydgard 
I compile to my friend to more test.
This is
https://github.com/unknownbrackets/ppsspp/commit/fed687fb59ef29fd1ad3f151465f4f0a036dd389
break.
Any idea to fix ?

**Comment by unknownbrackets** [comment] 2016-01-15 16:13
Try putting a `DISABLE;` below `case 24: //mult (the most popular one). lo,hi  = signed mul (rs * rt)` and each of the cases below it in the *latest* git build.  Does that make it work?

Not suggesting that as a fix at all, just want to confirm.  If that does help, it'd be great to see which of those can be disabled to make it work, which again would not be a fix.  Note that disabling the mtlo/etc. instructions might make it work, but only because they would also disable the other ones.

-[Unknown]

**Comment by sum2012** [comment] 2016-01-16 13:29
@unknownbrackets It is case 18

**Comment by unknownbrackets** [comment] 2016-01-16 17:35
So even if you disable ALL the cases below 24 it doesn't help?

The reason I ask is, disabling case 18 basically just prevents certain scenarios for the other cases.  So it could just be making it so the bug never happens, even though the bug doesn't have anything to do with case 18 itself.

-[Unknown]

**Comment by sum2012** [comment] 2016-01-17 09:45
Sorry,I am misleading.
Yes,disabling case 24 also fix.
What is the next step to test ?

**Comment by unknownbrackets** [comment] 2016-01-17 10:01
This helps, thanks.

Another thing to try - instead of DISABLE, put `gpr.FlushR(MIPS_REG_LO);` right below case 24.  And then also try putting that right below `SMULL(EncodeRegTo64(gpr.R(MIPS_REG_LO)), gpr.R(rs), gpr.R(rt));` (instead, not both places.)

Sorry, this is always troublesome to test.  But if flushing the reg BEFORE fixes it, and flushing AFTER does not fix it, then we can be pretty sure the bug is inside case 24 specifically.  If both fix it, it could be inside 24, or it could just be something paired with 24 later.

You can also try logging the instructions, although the log might be a lot.  To do that, above `void Arm64Jit::Comp_MulDivType(MIPSOpcode op) {` add:

```c++
#include "Core/MIPS/MIPSTables.h"

const char *MIPSDisasmOp(MIPSOpcode op) {
	static char temp[256];
	MIPSDisAsm(op, 0, temp);
	return temp;
}
```

Then, underneath each case:

```c++
		NOTICE_LOG(HLE, "muldiv: %s", MIPSDisasmOp(op));
```

This will log each and every muldiv type of op.  Maybe with some luck, I can construct a test using the ops around where it fails and figure out where it's failing.  It could be another clobber bug, I suppose...

-[Unknown]

**Comment by sum2012** [comment] 2016-01-17 10:06
This is not possible to let my friend to do logging.
They may not have windows to do logging.

**Comment by unknownbrackets** [comment] 2016-01-17 10:22
Well, `adb logcat` can also get the log.  But okay.

Technically, this was caused by #7839 and is present in v1.1.1.  But, still a fairly recent regression...

-[Unknown]

**Comment by hrydgard** [comment] 2016-01-17 10:23
Yeah, I think it qualifies.

**Comment by sum2012** [comment] 2016-01-17 10:40
@unknownbrackets 
Do you mean this change ?
https://github.com/sum2012/ppsspp/commit/ccc56d39554697fafd8c43896defa603b35d79c3

If yes,it crash

**Comment by sum2012** [comment] 2016-01-17 12:06
@unknownbrackets sorry, I did not see "instead, not both places"
Anyway, both change still crash

**Comment by unknownbrackets** [comment] 2016-01-17 18:40
Oh.  What if you try `gpr.FlushAll()` then?  Hmm.  So it's not LO...

-[Unknown]

**Comment by sum2012** [comment] 2016-01-18 11:53
Put it below case 24,it doesn't crash
Put it  below `SMULL(EncodeRegTo64(gpr.R(MIPS_REG_LO)), gpr.R(rs), gpr.R(rt));` 
it crash

**Comment by mike13dash** [comment] 2016-01-18 14:32
BTW im using Huawei Honor 4X Che2-L11 variant smartphone, just what i said before i never had this issue with kitkat OS, but it started to crash after I upgraded my phone's OS to lollipop

**Comment by hrydgard** [comment] 2016-01-18 14:49
@mike13dash most likely your Kitkat OS was 32-bit and Lollipop 64-bit, and you have a 64-bit CPU. This bug affects 64-bit execution only.

**Comment by unknownbrackets** [comment] 2016-01-18 16:20
@sum2012 okay, what if you put `gpr.FlushAll();` immediately above `gpr.MapDirtyInIn(MIPS_REG_LO, rs, rt);`?  If that helps, we're definitely getting somewhere good.  Next question: if that helps, what if you put `gpr.FlushR(rs); gpr.FlushR(rt);` above instead of `gpr.FlushAll()`?

If that does not help, what if you put `gpr.FlushR(MIPS_REG_LO);` right below `gpr.SetImm(MIPS_REG_LO, (u64)result);`?

Sorry again for all the tests, especially if you're having to compile and send to someone else... I don't know a faster process.  If we can find another game suffering crashes only in arm64, maybe one I have, that would be great too.

-[Unknown]

**Comment by sum2012** [comment] 2016-01-18 19:20
@mike13dash It is very interesting your phone of cpu also 8 cores and 64 bit.
You can use this build until we fix
https://drive.google.com/file/d/0B3OaSdeV0L8kTFlGUXNoLU41NUk/view?usp=sharing

**Comment by sum2012** [comment] 2016-01-19 10:31
put `gpr.FlushAll();` immediately above `gpr.MapDirtyInIn(MIPS_REG_LO, rs, rt);`  It crash

put `gpr.FlushR(MIPS_REG_LO);` right below `gpr.SetImm(MIPS_REG_LO, (u64)result);` It does not crash

I just hope my friend that keep testing

**Comment by hrydgard** [comment] 2016-01-19 22:27
@sum2012  I committed a small bugfix that may be related, can you get your friend to test this build?

**Comment by sum2012** [comment] 2016-01-19 22:32
@hrydgard OK ,I will give him to test

**Comment by mike13dash** [comment] 2016-01-20 07:57
ive tried using the updated version of ppsspp with ur smallbug fix and happy to say it never crashed during end phase, thanks for the effort guys! you may close this issue now...

**Comment by unknownbrackets** [comment] 2016-01-20 08:03
Hurray.  Will close then, can reopen if there are still problems.

Thanks for the typo fix, I wonder how long I would've stared at the code before finally seeing that...

-[Unknown]

**Closed by unknownbrackets** 2016-01-20 08:03 UTC
Labels: arm64jit, Platform-specific (Android)
