### ISSUE TITLE
Glitchy sky in Midnight Club 3

### ISSUE THREAD

**Issue by iArti** [hrydgard/ppsspp#10157] opened 2017-11-19 07:46 UTC
I'm running -819 build on Xiaomi Mi Max (Snapdragon 650) (Vulkan renderer)
Sky in MC3 is flickering
In early 1.4.2 builds (I can't name exactly, sorry) there was everything OK

![screenshot_20171119-104013](https://user-images.githubusercontent.com/23010139/32988470-8ee31d9e-cd16-11e7-9054-3b3077c6de66.png)
![screenshot_20171119-104010](https://user-images.githubusercontent.com/23010139/32988471-8f2a91e2-cd16-11e7-8ad6-a27e9355d246.png)

**Comment by hrydgard** [comment] 2017-11-19 08:40
Thanks for reporting - but it's a duplicate of #10087 , closing.

**Closed by hrydgard** 2017-11-19 08:40 UTC
