### ISSUE TITLE
Rewind feature for Retroarch (PC)

### ISSUE THREAD

**Issue by ShadowOfPripyat** [hrydgard/ppsspp#15829] opened 2022-08-10 23:30 UTC
### What should happen

Well, it should rewind when I press my mapped key in Retroarch, preferably without audio crackling (i know it's a bit hard)
I've seen we already have rewind on Android, but what about Retroarch?

### Who would this benefit

**A lot of people** who actually plays some PSP games. From **casual players** to **Streamers**.
Rewind feature is very useful sometimes while playing, mostly if you did something wrong and don't wanna open a save. Even when a dialog scene or when characters are speaking, it's funny to hear distorted words using the rewind.

### Platform (if relevant)

libretro / Retroarch

### Games this would be useful in

Any game(this feature is for all games)

### Other emulators or software with a similar feature

For Example, PCSX(PSone) or Beetle PSX, Mupen64Plus- Next for Nintendo 64.

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment] 2022-08-11 01:15
I suppose this is a duplicate of #12841.  PPSSPP supports rewind, but it seems to be issues with the libretro API that make things not work.

Libretro was, unfortunately, designed with weaker systems involved and doesn't really support things like multithreading being used by the emulator.  Since the PSP is much more powerful (10x Mhz, 16x RAM, etc.) than systems like the PS1, it's more necessary to use modern software techniques for good speed and so it causes problems that libretro was designed in such an antiquated way.

Anyway, I'm going to close this as there's already an issue about rewind working and another issue about the various crashes you get only with libretro.

-[Unknown]

**Closed by unknownbrackets** 2022-08-11 01:15 UTC

**Comment by ShadowOfPripyat** [comment] 2022-08-11 22:34
I agree that libretro its what it is, and the PSP is much more powerful than a PS1 obviously. I reviewed the already implemented "rewind" feature on PPSSPP, but its not much what I expected. Its more like an auto-snapshot than a rewind thing. Well, thanks for answering.

**Comment by LunaMoo** [comment] 2022-08-12 02:59
That's pretty much the same way rewind works in any other emulators, the primary difference is amount of memory and complexity which makes something like PSP rewind much more limited in how it can work and not used by most people due to crazy hardware requirements to be smooth despite tons of optimizations.

**Comment by ShadowOfPripyat** [comment] 2022-08-12 22:58
Yeah I see it's not worth it enough to implement it yet.
