### ISSUE TITLE
Texture Follwing Pixels [ Mobile ]

### ISSUE THREAD

**Issue by cmrhere2play** [hrydgard/ppsspp#7348] opened 2015-01-18 15:31 UTC
In MHP3rd HD small pixel square graphics seems to be flying around my character ...this only happens in certain places
![screenshot_2015-01-18-10-10-26](https://cloud.githubusercontent.com/assets/6509547/5792915/fba2a6b6-9efc-11e4-9698-283ca01c6cbb.png)

![screenshot_2015-01-18-10-10-10](https://cloud.githubusercontent.com/assets/6509547/5792916/0f8fd4c8-9efd-11e4-8bda-1e8a5312ca7a.png)

![screenshot_2015-01-18-10-09-51](https://cloud.githubusercontent.com/assets/6509547/5792920/1fdb1388-9efd-11e4-9484-f981ef4b5e92.png)

**Comment by cmrhere2play** [comment] 2015-01-18 15:34
This happens on mobile

**Comment by unknownbrackets** [comment] 2018-08-25 19:31
This issue is being closed as a duplicate of #7218.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-08-25 19:31 UTC
