### ISSUE TITLE
Remote Disc Streaming

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12248] opened 2019-08-16 18:25 UTC
hello.in ppsspp there is bug with remote disc streaming where icon of games are blank and if i run them its just black screen.Is there fix

**Comment by unknownbrackets** [comment] 2019-08-16 21:37
What operating system are you using for the device sharing the games, and for the device where your trying to play the games?  Have you tried using the latest git build on both devices?

This probably means it can't read the game data or the connection is really bad.  But it could be related to ipv6 which I think was fixed after v1.8.0.

-[Unknown]

**Comment by HiImBrala** [comment] 2019-08-17 06:01
I am sharing on laptop with latest build from ppsspp website and playing on samsung galaxy core prime  android 5.1.1 running latest build from google play store

**Comment by unknownbrackets** [comment] 2019-08-17 06:38
Try the latest git build:
https://buildbot.orphis.net/ppsspp/

The Play Store has a version of PPSSPP released in March 2019.  It's been about 5 months since then, and we've made around 500 changes since then - some might've fixed your problem, although it's possible new bugs have also been introduced.  It's best to validate if the latest and greatest fixes your issue.

-[Unknown]

**Comment by HiImBrala** [comment] 2019-08-17 07:24
thanks i will give it a try

**Comment by HiImBrala** [comment] 2019-08-17 08:50
> Try the latest git build:
> https://buildbot.orphis.net/ppsspp/
> 
> The Play Store has a version of PPSSPP released in March 2019. It's been about 5 months since then, and we've made around 500 changes since then - some might've fixed your problem, although it's possible new bugs have also been introduced. It's best to validate if the latest and greatest fixes your issue.
> 
> -[Unknown]

it didnt work

**Comment by HiImBrala** [comment] 2019-08-17 15:04
can someone help with this issue or patch it for next update

**Comment by unknownbrackets** [comment] 2019-08-17 16:21
It'd help to check for log messages - on your PC, you can go to Debug -> Log Console.  It's also possible to get the logs from the phone using this:

https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

This feature is working for other people (including me.)  Even if there's a bug, no one knows what the bug is.  We need your help to figure out the problem.

Often, this is caused by not being connected to the same wifi router, or certain firewall settings.  See for example #11853.

-[Unknown]

**Comment by unknownbrackets** [comment] 2019-10-06 19:44
Any feedback?  Is this working with the latest version of PPSSPP?  It'd help to show logs if possible.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-04-08 04:33
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other problems, and we've recently improved error messaging for this feature.  See #11853.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2020-04-08 04:33 UTC
Labels: No Feedback / Outdated?
