### ISSUE TITLE
[Vulkan] 魔法少女リリカルなのはA's Portable - Gears of Destiny: Graphical glitch

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#11980] opened 2019-04-17 10:35 UTC
The characters' pictures during dialogs is not displaying correctly.
Vulkan:
![Screenshot_2019-04-17-14-54-41-305_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/56281558-2d66b980-6122-11e9-83a9-c2b966a428c8.png)

OGL:
![Screenshot_2019-04-17-14-53-57-732_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/56281570-35bef480-6122-11e9-9fde-1f074e24d1f1.png)

[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/3089186/recording.ppdmp.zip)

Device: Mi 5s Plus, Android 8.0

**Comment by hrydgard** [comment] 2019-04-17 11:44
Pretty likely to be the same old alpha test issue we've seen on Adreno 500 drivers...

**Comment by leopard20** [comment] 2019-04-17 19:20
Ah...again?!

**Comment by unknownbrackets** [comment] 2019-04-19 00:25
Draw 1281/1282, it draw s abox that contains the face, using:

 * Stencil test ALWAYS REPLACE ff
 * Alpha test: a > 2 (means discard)
 * Depth test off, but depth write enabled.

This definitely activates the driver bug that the Adreno 5xx has.  Our workaround doesn't activate because depth write is enabled (despite depth test being off.)

I suspect it would workaround it to add more to the check:

```c++
id.SetBit(FS_BIT_NO_DEPTH_CANNOT_DISCARD_STENCIL, !IsStencilTestOutputDisabled() && !gstate.isDepthWriteEnabled());
```

Replace with:

```c++
id.SetBit(FS_BIT_NO_DEPTH_CANNOT_DISCARD_STENCIL, !IsStencilTestOutputDisabled() && (!gstate.isDepthTestEnabled() || !gstate.isDepthWriteEnabled()));
```

Not sure if this would have negative impacts in other games.

-[Unknown]

**Comment by hrydgard** [comment] 2019-04-19 20:07
Hm, that feels like it should be safe-ish because with the depth test disabled, depth write does nothing.

**Comment by Panderner** [comment] 2020-12-27 05:27
This issue does not occur for POCO M3, Android 10 in Vulkan:
![Screenshot_2020-12-27-13-26-14-105_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103164517-4906ea80-4847-11eb-9dc2-a2cad11e8e48.jpg)

**Comment by ss8688** [comment] 2021-02-22 04:45
I have a same problem on a Mail-G52 GPU

**Comment by Panderner** [comment] 2021-02-22 05:47
It does not occur for my POCO M3 using Vulkan in latest build.
![Screenshot_2021-02-22-13-45-47-777_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/108667546-6ccb7180-7514-11eb-8120-6316b1fce771.jpg)

**Comment by unknownbrackets** [comment] 2021-02-23 14:48
Is this working now?

-[Unknown]

**Comment by unknownbrackets** [comment] 2021-02-23 16:14
Noted as not working in #13599.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-05-02 13:02
I can't reproduce this issue on my Redmi Note 9 Mali GPU Vulkan
![Screenshot_2021-05-02-20-59-59-116_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116814091-a1e5e700-ab89-11eb-97fa-99514f3826e4.jpg)

**Comment by Panderner** [comment] 2021-05-02 15:27
> I can't reproduce this issue on my Redmi Note 9 Mali GPU Vulkan
> ![Screenshot_2021-05-02-20-59-59-116_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116814091-a1e5e700-ab89-11eb-97fa-99514f3826e4.jpg)

Hmm @Gamemulatorer that screenshot lied.

**Comment by ss8688** [comment] 2021-05-02 15:50
@Gamemulatorer It do appears on my honor 9x with mail g52 .Same as Leopard20's Mi 5s
But not on my redmi k40 with Snapdragon 870
You are using a different device,I think

**Comment by ss8688** [comment] 2021-05-02 15:54
It just reproduces on certain devices
I heard that it can be reproduced on HUAWEI mate 30. but don't kown if it is true.
Because I don't have one.

**Comment by unknownbrackets** [comment] 2021-05-02 17:05
Right, this is a driver issue.  I'm not sure specifically what devices are affected but I think it is only:

 * Adreno 5xx GPUs (not Adreno 6xx or newer), AND if they have an older driver (typically, lower than Android 10, but varies by device manufacturer.)
 * Mali devices (not sure which), probably also only older than certain drivers but not sure.

The devices mentioned:
 * Honor 9x: Mali-G52, Android 10 (affected)
 * Huawei Mate 30: Mali-G76, Android ver unknown but >= 10 (affected)
 * Redmi Note 9: Mali-G52, Android ver unknown but >= 10 (affected)
 * Mi 5s Plus: Adreno 530, Android 8 (affected)
 * Redmi K40: Adreno 650 (unaffected)
 * Poco M3: Adreno 610 (unaffected)

So on the Mali front, this probably affects all of Bifrost.  It'd be interesting to know if any phone with the below SoC has the issue (these are all Valhall, like Adreno 5xx -> 6xx):
 * Mali-G57 (Kirin 820, Dimensity 8xx)
 * Mali-G68 (not sure)
 * Mali-G77 (Kirin 985, Dimensity 1000, Exynos 990)
 * Mali-G78 (Kirin 9000, Exynos 1080, Exynos 2100)

If we can narrow down the range we at least would know for sure what devices are and are not affected and might be able to get some info from Mali.

-[Unknown]

**Comment by ss8688** [comment] 2021-05-03 04:02
@unknownbrackets 

> I can't reproduce this issue on my Redmi Note 9 Mali GPU Vulkan
> ![Screenshot_2021-05-02-20-59-59-116_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116814091-a1e5e700-ab89-11eb-97fa-99514f3826e4.jpg)
As he says
Redmi note 9 is not affected

**Comment by unknownbrackets** [comment] 2021-05-03 04:06
Well, yes, but it sounds like it might be a mistake or typo because the provided screenshot does show the issue as Panderner and Leopard20 noted.

If it's indeed not affected, that could mean a driver update fixed it which would be good and might mean a driver update would fix the others if available.  In that case, Mali might know more about the details of the glitch and if a workaround is possible.  But like I said, I suspect it was a mistake and that device is also affected.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-07-12 05:54
This can be fixed now via https://github.com/hrydgard/ppsspp/pull/15671/commits/c5a10a5501108dbb60014981e8b68762f12050c8

**Comment by unknownbrackets** [comment] 2022-07-12 06:32
I assume the latest change triggers this since depth test is off.  So I'm going to close.

Please comment if it's not actually fixed.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-09-15 17:11
This issue can still reproduce on adreno gpu in vulkan.

https://user-images.githubusercontent.com/37603562/190467982-02c3dc37-2cf5-4902-a250-2213f918dcda.mp4

**Comment by Gamemulatorer** [comment] 2022-09-15 17:13
PixelDepthRounding can fix this issue on adreno gpu in vulkan.

**Comment by unknownbrackets** [comment] 2022-09-17 21:37
I wonder if this just means there's something wrong with the workaround in recent versions.  Was it working in older git builds (around when it was confirmed before)?  If yes, it must've broken at some time.

PixelDepthRounding is a bit expensive and can reduce quality (like forcing 1x PSP render resolution), so it may not be the ideal fix.

-[Unknown]

**Comment by hrydgard** [comment] 2022-09-17 21:58
Hm, we only activate the workaround on certain driver versions:

https://github.com/hrydgard/ppsspp/blob/master/Common/GPU/Vulkan/thin3d_vulkan.cpp#L807

Maybe the range is simply too narrow. Can you check your GPU and driver version in Settings/Tools/System Information?

**Comment by unknownbrackets** [comment] 2022-09-17 22:35
It was definitely fixed on version 0x80180000 with a Adreno 530, but maybe driver versions are not so linear.  And it was not seen on Adreno 620 or 630 devices.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2022-09-18 00:42
> Hm, we only activate the workaround on certain driver versions on Adreno:
> 
> https://github.com/hrydgard/ppsspp/blob/master/Common/GPU/Vulkan/thin3d_vulkan.cpp#L807
> 
> Maybe the range is simply too narrow. Can you check your GPU and driver version in Settings/Tools/System Information?

![Screenshot_2022-09-18-08-41-15-35](https://user-images.githubusercontent.com/37603562/190880801-9bbc98cc-c145-4f77-a890-b6c0f5a2274b.png)

**Comment by hrydgard** [comment] 2022-09-18 08:51
Seems on Adreno we were still using the old check, refined it for the Mali bug. Testing on the dump, only the Mali check catches it.

So decided to finally merge these two bug workarounds, and also remove the compat flag and just activate it universally when we detect stencil without depth.

Should work once #16043 is merged.

**Closed** 2022-09-18 08:57 UTC
Labels: Vulkan, Adreno GPU, Mali GPU

**Comment by hrydgard** [comment] 2022-09-18 10:11
Please check if that fixed it.

**Comment by Gamemulatorer** [comment] 2022-09-18 10:37
Yes, this was fix via https://github.com/hrydgard/ppsspp/pull/16043/commits/4045de8d565d215e7dd1e399040bad1e51397c1e
