### ISSUE TITLE
implement advance frameskipping

### ISSUE THREAD

**Issue by emmauss** [hrydgard/ppsspp#5630] opened 2014-03-10 10:20 UTC
can any of the devs implement an advance frameskipping feature.something like a delayed frameskip.to elabrate,make the emulator skip "y" frames after every "x" frames drawn.for example you could make the emulator skip 1 frame after every 3 frames.this could help smoothen gameplay when frameskip is set, and also fix certain flickering when playing games on low end devices when using frameskip.

**Comment by unknownbrackets** [comment] 2015-12-23 20:55
Auto frameskip already skips frames "as needed".  Essentially, we skip a frame whenever the current frame goes over budget.

Here's an example:

```
+------+------+------+------+------+------+------+
|      |      |      |      |      |      |      |
+------+------+------+------+------+------+------+
       ^              <---->
       1 frame        time game has to render frame
```

Some games render at 60fps, others at 30fps.  So first off, we detect that to get the size of those boxes right.  Next, whenever a game runs over:

```
+------+------+------+------+------+------+------+
|++++  1+++++ 2+++   3++++  4++++++++
+------+------+------+------+------+------+------+
       ^      ^      ^      ^       ^
	   safely rendered frames       oh no, we ran over
```

It skips the next frame.  The `+`s above represent time the game is busy rendering for - so as you can see it "missed the cut" for frame 5.  We already dropped a frame, at this point.  To avoid getting slower, we simply skip frame 6:

```
+------+------+------+------+------+------+------+
|++++  1+++++ 2+++   3++++  4++++++++     5+++++ 7
+------+------+------+------+------+------+------+
                                          ^
										  6 was skipped
```

So, this will already automatically determine to have a "draw 3, skip 1" pattern.

That being said, I can see the motivation to have it not automatic - just to set a fixed pattern.  We could default it to 1, since the current frameskip setting works that way.

-[Unknown]

**Comment by ResurrectionRedmi9** [comment] 2021-09-14 08:49
This is not a duplicate of https://github.com/hrydgard/ppsspp/issues/14315?

**Comment by hrydgard** [comment] 2021-09-14 10:07
Doesn't seem like the same thing. But also we're unlikely to implement this, closing.

**Closed by hrydgard** 2021-09-14 10:07 UTC
Labels: Feature Request
