### ISSUE TITLE
Both GOW games giving black screen after loading.

### ISSUE THREAD

**Issue by jvhellraiser** [hrydgard/ppsspp#12428] opened 2019-10-18 12:27 UTC
### What happens?
GOW games giving black screen after loading
game only loads if there a save state available only.

### What *should* happen?
load both GOW normally. like it did before this nonsense happen.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Desktop I5 3470  Intel HD graphics CPU running at 3.40 mhz with 16 gb ram.
and Yes PPSSPP was working just fine all games load fine before this release.

**Comment by LunaMoo** [comment] 2019-10-18 12:37
Closing as a duplicate of #12400 use search before posting in the future.

**Closed by LunaMoo** 2019-10-18 12:37 UTC
