### ISSUE TITLE
The 0v1.2.2-973-g2019542 version of ppsspp is just 10.1kb

### ISSUE THREAD

**Issue by liuxiaohuan26** [hrydgard/ppsspp#8981] opened 2016-09-15 13:43 UTC
The 0v1.2.2-973-g2019542 ios version of ppsspp is just 10.1kb . 
And it can not be displayed on desktop after set up。

**Comment by LunaMoo** [comment] 2016-09-15 14:44
Closing as duplicate of #8978

**Closed by LunaMoo** 2016-09-15 14:44 UTC
