### ISSUE TITLE
After Burner - Black Falcon

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#9854] opened 2017-07-18 21:39 UTC
PPSSPP v1.4.2-267-g033676ca4 Windows 64 bit
The game sounds horrible in mission otherwise it's ok

See the attached video but lower volume before starting the video 

[video.zip](https://github.com/hrydgard/ppsspp/files/1157358/video.zip)

[log.zip](https://github.com/hrydgard/ppsspp/files/1157356/log.zip)

**Comment by unknownbrackets** [comment] 2017-07-30 18:11
Did this always happen, or was there a previous version in which it worked?

-[Unknown]

**Comment by ppmeis** [comment] 2017-12-31 00:23
Tested with latest Windows build, default settings. A lot of sound issues.

- There's a noisy beep after you begin a mission. If you press start and continue noisy beep disappears. But when I use the machine gun, its sound goes in a loop until you press start again.
- Intro logo videos are blinking all the time.

**Comment by benderscruffy01** [comment] 2019-03-23 02:48
this is a duplicate  of #8514

**Comment by unknownbrackets** [comment] 2019-03-23 13:28
This issue is being closed as a duplicate.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-03-23 13:28 UTC
