### ISSUE TITLE
how i can play with 2 xbox controllers??

### ISSUE THREAD

**Issue by slzr** [hrydgard/ppsspp#8703] opened 2016-04-20 05:01 UTC
following [this tutorial](https://www.youtube.com/watch?v=HqHRefuOLfI) how i can play with 2 xbox 360 controllers??

**Comment by unknownbrackets** [comment] 2016-04-24 21:48
This issue is being closed as a duplicate of #8250.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-04-24 21:48 UTC
