### ISSUE TITLE
[Android][OpenGL&Vulkan][BlackOut&Freez] JeanneD'arc (USJS10048)

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#12728] opened 2020-03-18 10:24 UTC
### What happens?
Can't start the game.

### What *should* happen?
Start the game.
It happen after updating the 1.9.3-507.

Remark: 1.9.3-500 is working!!

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

PPSSPP Ver. : 1.9.3-507 to 517
OS: Android 9.0
DeviceName: SONY SO-02K / Xperia XZ1 Compact (Japan)
CPU: Snapdragon835 (Octa-core)
GPU: Adreno 540
Resolution: 720×1280
RAM: 4GB
ROM:32GB
ExternalStrage: microSDXC 512GB

**Comment by Emulatorer** [comment] 2020-03-18 10:26
duplicate #12726

**Comment by hrydgard** [comment] 2020-03-18 12:59
yeah, closing as dupe.

**Closed by hrydgard** 2020-03-18 12:59 UTC

**Comment by Panderner** [comment] 2020-03-18 15:50
@hrydgard can you mark as a Duplicate? I can't find any duplicates even the original issue is closed or fixed

**Comment by hrydgard** [comment] 2020-03-18 15:53
Right, I forgot the necessary comment syntax. (you simply type Duplicate of (number) and github does the rest)

**Comment by Panderner** [comment] 2020-03-19 00:14
Thank you
