### ISSUE TITLE
Is there a way to simulate homehook functions?

### ISSUE THREAD

**Issue by strikersix23** [hrydgard/ppsspp#12855] opened 2020-04-26 00:52 UTC
I'm testing a homebrew from this site
Link:
https://m.emuparadise.me/Super_Nintendo_Entertainment_System_(SNES)_Emulators/PSP/Snes9x_Euphoria/89

I tested it on windows 10
And android 9.0 samung j7 crown
I have a log from the pc will upload log from android soon but it's most likely the same problem
Running on latest nightly as of this moment

**Comment by strikersix23** [comment] 2020-04-26 00:53
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/4534423/ppsspplog.txt)

**Comment by unknownbrackets** [comment] 2020-04-26 01:31
This is probably a duplicate of #12481.

I think "homehook" is a library that the game hasn't loaded yet.  Most likely it doesn't work because of using the ME.

In general, PPSSPP does not emulate all the internals of the PSP firmware.  There are several reasons for this:

1. Performance - PPSSPP is not a "low level" emulator, it's a "high level" emulator.  I like to use the analogy of an electric car - it doesn't actually have spark plugs, but from the outside it behaves largely the same.  This makes it possible to run at least some games full speed on Android phones.  A low level PSP emulator might struggle to get full speed even on powerful desktops.

2. Complexity - we emulate something like 1000 sycalls right now.  There's probably 10,000 kernel level functions we'd have to emulate if we wanted to fully replicate the PSP kernel.  It'd be a mountain of work, and for what - getting a SNES emulator working?  There's already SNES emulators.  It's not a prize exciting enough that anyone has decided to dedicate thousands of hours of their life to.

3. Bugs - even if someone spent the next couple years to get old emulators running at bad FPS on their Android phone, that's all it would be used for.  We already have a way to run most games at good FPS, so we'd keep using that way for games.  Eventually, we'd make some change or performance enhancement that would break old emulators, and very few people would be testing to even notice.  It would guarantee that support for these obscure features would *always* be buggy.

4. Motivation - even if it weren't for how hard it was, how slow it'd make PPSSPP, or how poor quality it would inevitably result in the long run... the fact is, there are other emulators for these systems.  If a developer really wants to run SNES games on their Android phone or PC or whatever - why would they want to debug TWO (PPSSPP and say SNES9x) emulators?  I guarantee, both would have bugs - it's not like SNES9X is perfect.  Why not just debug one made directly for their phone, and make that one better?  Sounds way easier.

As to this specific issue - we don't emulate the second CPU (the "media engine") in the PSP at all.  Instead, we just emulate the syscalls that used it.  The Vita works the same way.  It has a PSP CPU in it (the primary CPU games run on), but when those same syscalls that use the ME are run, it emulates them.  So Sony made the same choice we did.  I'm sure it's true of their PSP emulator for the PS3 also.

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-04-26 01:35
Going to actually close this as a duplicate of #12481.

-[Unknown]

**Closed by unknownbrackets** 2020-04-26 01:35 UTC
