### ISSUE TITLE
Gallery Fake color is not correct

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8406] opened 2016-01-08 08:51 UTC
Since https://github.com/hrydgard/ppsspp/pull/8389

right color
![01](https://cloud.githubusercontent.com/assets/3481559/12194072/f5973c94-b627-11e5-8aa6-4f7923fab749.png)

wrong color
![02](https://cloud.githubusercontent.com/assets/3481559/12194073/f59ebb0e-b627-11e5-9056-5a451968811c.png)

**Comment by daniel229** [comment] 2016-01-08 09:13
current master log
```
11:07:566 voice[0]     I[ME]: HLE\sceAtrac.cpp:1558 sceAtracReleaseAtracID(1)
11:09:102 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:416 Creating FBO for 001fc000 : 64 x 4 x 3
11:09:117 user_main    W[G3D]: Common\FramebufferCommon.cpp:914 Block transfer upload 09006230 -> 041fc000
11:09:117 user_main    I[G3D]: GLES\ShaderManager.cpp:160 Linked shader: vs 19 fs 29
11:10:087 user_main    W[FileSys]: FileSystems\ISOFileSystem.cpp:573 Reading beyond end of file, clamping size 263168 to 20400
11:10:088 voice[0]     I[ME]: HLE\sceAtrac.cpp:1892 1=sceAtracSetDataAndGetID(08a7b7c0, 00040400)
11:10:088 voice[0]     W[ME]: HLE\sceAtrac.cpp:1779 This is an atrac3+ mono audio
11:10:089 voice[0]     E[ME]: HLE\sceAtrac.cpp:1491 sceAtracGetSecondBufferInfo(1, 09ff2e80, 09ff2e84)
11:18:228 voice[0]     I[ME]: HLE\sceAtrac.cpp:1558 sceAtracReleaseAtracID(1)
11:19:781 user_main    W[FileSys]: FileSystems\ISOFileSystem.cpp:573 Reading beyond end of file, clamping size 263168 to 45592
11:19:781 voice[0]     I[ME]: HLE\sceAtrac.cpp:1892 1=sceAtracSetDataAndGetID(08a7b7c0, 00040400)
11:19:781 voice[0]     W[ME]: HLE\sceAtrac.cpp:1779 This is an atrac3+ mono audio
11:19:782 voice[0]     E[ME]: HLE\sceAtrac.cpp:1491 sceAtracGetSecondBufferInfo(1, 09ff2e80, 09ff2e84)
11:19:831 user_main    W[G3D]: GLES\TextureCache.cpp:1333 Using texture with rendered CLUT: texfmt=5, clutfmt=3
```

before
```
13:21:210 voice[0]     I[ME]: HLE\sceAtrac.cpp:1558 sceAtracReleaseAtracID(1)
13:22:749 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:420 Creating FBO for 001fc000 : 64 x 4 x 3
13:22:753 user_main    W[G3D]: Common\FramebufferCommon.cpp:631 Memcpy fbo download 041fc000 -> 045fc000
13:22:760 user_main    W[G3D]: Common\FramebufferCommon.cpp:833 Block transfer upload 09006230 -> 041fc000
13:22:761 user_main    I[G3D]: GLES\ShaderManager.cpp:160 Linked shader: vs 19 fs 29
13:22:762 user_main    W[G3D]: GLES\TextureCache.cpp:1329 Using texture with rendered CLUT: texfmt=5, clutfmt=3
```

**Comment by unknownbrackets** [comment] 2016-01-08 15:26
It's funny that the colors in the wrong image look right.

Could you try to bisect which change broke it, and see the GE debugger?  I'm guessing it's because we're not downloading the entire framebuffer.  But it might also be caused by my checking the stride - this CLUT is 64x4 rather than 256x1.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-09 00:45
Since https://github.com/unknownbrackets/ppsspp/commit/28a07c70c6786765bb12dae0658c2c76f5f2b2a3 ,it's black,and then https://github.com/unknownbrackets/ppsspp/commit/095d8cb52a7ddbb361b36a5c4bca14d091e0650a it looks what it looks now.

Is it one?
![03](https://cloud.githubusercontent.com/assets/3481559/12213074/2a1b8a3a-b6ad-11e5-8fa8-cf5ff1b7a1a5.png)
https://gist.github.com/daniel229/0d2eb63089b3ff6e5c22

**Comment by unknownbrackets** [comment] 2016-01-09 04:17
Watch for the CLUT field under Texture to show an address that starts with 0x04.

-[Unknown]

**Comment by daniel229** [comment] 2016-01-09 04:40
Got it
![04](https://cloud.githubusercontent.com/assets/3481559/12214406/efa1ab8e-b6cd-11e5-9250-f4224573d78b.png)
https://gist.github.com/daniel229/a8707fd9873da2284aed

**Comment by unknownbrackets** [comment] 2016-01-09 07:04
Well, it definitely drew brown in the CLUT, and it seems like it ought to be brown... Hmm maybe it needs a flush before copy.

Try adding:
```c++
	FlushBeforeCopy();
```

Just after:
```c++
	PackFramebufferAsync_(nullptr);
```

-[Unknown]

**Comment by daniel229** [comment] 2016-01-09 07:13
Is it each <code>PackFramebufferAsync_(nullptr);</code>? I added them and still not work.

**Comment by daniel229** [comment] 2016-01-09 09:19
<code>13:47:989 user_main    W[G3D]: GLES\TextureCache.cpp:1333 Using texture with rendered CLUT: texfmt=5, clutfmt=3</code> 
This log posting up is 4.976 seconds later than before.

**Comment by unknownbrackets** [comment] 2016-01-17 19:49
Was this originally working correctly in v1.1.1?

-[Unknown]

**Comment by daniel229** [comment] 2016-01-18 02:00
No.

**Comment by unknownbrackets** [comment] 2016-01-26 08:23
Find, GPU/GLES/Framebuffer.cpp:

```c++
		int w = std::min(pixels % vfb->fb_stride, (int)vfb->width);
		int h = std::min((pixels + vfb->fb_stride - 1) / vfb->fb_stride, (int)vfb->height);
```

Add after:

```c++
		if (w == 0 || h > 1) {
			// Exactly aligned.
			w = std::min(vfb->fb_stride, (int)vfb->width);
		}
```

Does this help?

-[Unknown]

**Comment by daniel229** [comment] 2016-01-26 08:30
Yes,it does.

**Comment by unknownbrackets** [comment] 2016-01-26 08:41
Cool, okay so that is the fix for this issue, and might fix others... but umm, #8509 will look pretty terrible with that fixed, right now.  Hmm.

-[Unknown]

**Comment by hrydgard** [comment] 2020-11-10 22:54
Got re-broken since I reverted the fix: d8db8ec

**Comment by unknownbrackets** [comment] 2022-09-21 06:51
Is this working in the latest git versions?

-[Unknown]

**Comment by Panderner** [comment] 2022-09-21 09:32
Here in the latest build:
![ULJS00024_00001](https://user-images.githubusercontent.com/37503397/191469630-59682744-02bf-4358-9093-63f34b8aaedf.jpg)

**Comment by hrydgard** [comment] 2022-09-21 09:59
Oh, interesting. That almost looks right, but not quite.

Can I have a GE dump? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Panderner** [comment] 2022-09-21 10:13
Here:
[ULJS00024.zip](https://github.com/hrydgard/ppsspp/files/9615603/ULJS00024.zip)

**Comment by hrydgard** [comment] 2022-09-21 11:35
Interesting one, the palette is loaded from a 64x4 framebuffer:

![image](https://user-images.githubusercontent.com/130929/191493822-05271ae8-c783-4952-91e9-83a38a5dc4a1.png)

But we only look at the first line when loading palettes. Fixable with a little extra shader work, will take care of this soon.

Great test case!

**Closed** 2022-09-21 21:34 UTC
Labels: GE emulation
