### ISSUE TITLE
Save data corrupted - tekken dark resurrection

### ISSUE THREAD

**Issue by zayakazama** [hrydgard/ppsspp#14937] opened 2021-09-26 15:11 UTC
### Game or games this happens in

ULUS-10139

### What area of the game / PPSSPP

When trying to load the save data I get the grey screen telling me that it's corrupted.
I tried deleting the old data, overwriting it and nothing happened.
I really am not looking forward to starting the game over.
(The game data was created on the android version of PPSSPP and I'm wanting to move over to PC so that's why)
![image](https://user-images.githubusercontent.com/91424190/134813499-bf04136c-12bc-4d2f-803e-30e265da8478.png)

### What should happen

The save data should load normally like in other games.

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon HD 6570

### PPSSPP version affected

v1.11.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment] 2021-09-26 15:24
Duplicate of https://github.com/hrydgard/ppsspp/issues/13540

**Comment by zayakazama** [comment] 2021-09-26 15:35
> 
> 
> Duplicate of #13540

That thread has a different device model and version of PPSSPP tho..

**Comment by unknownbrackets** [comment] 2021-09-26 15:35
What version of PPSSPP was the save data created using on Android?  Was it an older version as in #13540?

It shouldn't have much to do with the device model at all.

-[Unknown]

**Comment by zayakazama** [comment] 2021-09-26 15:36
> 
> 
> What version of PPSSPP was the save data created using on Android? Was it an older version as in #13540?
> 
> It shouldn't have much to do with the device model at all.
> 
> -[Unknown]

No, the save data was created a few days ago. It's not as old as the version in #13540

**Comment by unknownbrackets** [comment] 2021-09-26 15:39
Does the save data still load fine on your Android device?

If you create a save state there, and copy that over, are you able to load that on the PC and then save and load normal save data on the PC?

That may be a workaround, but I'm also trying to use it to understand what might be happening here.  It's possible the game requires the MAC address to match, and it's rejecting the save because it doesn't.  Some games do that (this might even explain #13540 because I think we regenerated MAC addresses that were invalid near then.)

-[Unknown]

**Comment by zayakazama** [comment] 2021-09-26 15:42
> 
> 
> Does the save data still load fine on your Android device?
> 
> If you create a save state there, and copy that over, are you able to load that on the PC and then save and load normal save data on the PC?
> 
> That may be a workaround, but I'm also trying to use it to understand what might be happening here. It's possible the game requires the MAC address to match, and it's rejecting the save because it doesn't. Some games do that (this might even explain #13540 because I think we regenerated MAC addresses that were invalid near then.)
> 
> -[Unknown]

The save data still loads on my android device.

I copied the data from the android device already, overwrote the old files on PC and tried loading it that way- did not work. I got the response from the screenshot above everytime I tried loading it.

It might be the problem with the MAC address but I don't know.

**Comment by unknownbrackets** [comment] 2021-09-26 15:57
In PPSSPP, you can create save data (like you would on a real PSP), but you can also create save states.  This is done from the pause menu.

I'm talking about save states.  These are in PSP -> PPSSPP_STATE instead of PSP -> SAVEDATA.  Normally, it's better to use save data, but since it's not working here, I'm just wondering if it helps to transfer and use the save state instead.

What might be happening is the game might be validating the MAC address in the save data on load.  It can't do this from a save state, because PPSSPP loads save states (to the game, it just seems like you never stopped playing.)  Save states have some downsides though, since PSP games sometimes had bugs if you played them for 10s of hours straight (which is what using save states simulates.)

-[Unknown]

**Comment by zayakazama** [comment] 2021-09-26 15:58
> 
> 
> In PPSSPP, you can create save data (like you would on a real PSP), but you can also create save states. This is done from the pause menu.
> 
> I'm talking about save states. These are in PSP -> PPSSPP_STATE instead of PSP -> SAVEDATA. Normally, it's better to use save data, but since it's not working here, I'm just wondering if it helps to transfer and use the save state instead.
> 
> What might be happening is the game might be validating the MAC address in the save data on load. It can't do this from a save state, because PPSSPP loads save states (to the game, it just seems like you never stopped playing.) Save states have some downsides though, since PSP games sometimes had bugs if you played them for 10s of hours straight (which is what using save states simulates.)
> 
> -[Unknown]

I can try that right now.
I'll go do it and I'll be back to give more info.

**Comment by zayakazama** [comment] 2021-09-26 16:23
> 
> 
> In PPSSPP, you can create save data (like you would on a real PSP), but you can also create save states. This is done from the pause menu.
> 
> I'm talking about save states. These are in PSP -> PPSSPP_STATE instead of PSP -> SAVEDATA. Normally, it's better to use save data, but since it's not working here, I'm just wondering if it helps to transfer and use the save state instead.
> 
> What might be happening is the game might be validating the MAC address in the save data on load. It can't do this from a save state, because PPSSPP loads save states (to the game, it just seems like you never stopped playing.) Save states have some downsides though, since PSP games sometimes had bugs if you played them for 10s of hours straight (which is what using save states simulates.)
> 
> -[Unknown]

It worked!! It loaded the state and after I tried saving, closing and reopening, it opened the save data perfectly fine! Thank you!

**Closed** 2021-09-26 19:54 UTC
