### ISSUE TITLE
Crazy Taxi: Fare Wars

### ISSUE THREAD

**Issue by HelicopterP** [hrydgard/ppsspp#2451] opened 2013-06-24 18:54 UTC
The game freezes at loading after selecting Crazi Taxi 1. The log is really huge but it goes something like this:
a few MB of this lines -
36:53:926 idle0        W[HLE]: HLE\sceKernelThread.cpp:2598 sceKernelSuspendThread(314)
36:53:926 user_main    W[HLE]: HLE\sceKernelThread.cpp:1926 800201a4=sceKernelStartThread(thread=314, argSize=16, argPtr=0986be40): thread already running
36:53:926 user_main    W[HLE]: HLE\sceKernelThread.cpp:2629 sceKernelResumeThread(314)
36:53:926 idle0        W[HLE]: HLE\sceKernelThread.cpp:2598 sceKernelSuspendThread(314)
36:53:926 user_main    W[HLE]: HLE\sceKernelThread.cpp:1926 800201a4=sceKernelStartThread(thread=314, argSize=16, argPtr=0986be40): thread already running
36:53:926 user_main    W[HLE]: HLE\sceKernelThread.cpp:2629 sceKernelResumeThread(314)
36:53:926 idle0        W[HLE]: HLE\sceKernelThread.cpp:2598 sceKernelSuspendThread(314)

than this:

36:53:943 user_main    I[HLE]: HLE\sceKernel.cpp:461 KO 297: Alarm "[Alarm]": -
36:53:944 user_main    I[HLE]: HLE\sceKernel.cpp:461 KO 298: Alarm "[Alarm]": -
36:53:944 user_main    I[HLE]: HLE\sceKernel.cpp:461 KO 299: Thread "idle0": 

than some stuff mentioning sceMp3 than a lot of Alarms again than crash.

Here is a full log: http://www.sendspace.com/file/fwuiss

**Comment by sum2012** [comment] 2015-01-16 12:26
v0.9.9.1-1503-gc250074 same problem
ct1 debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kQWk2SE5zTHAwbDA/view?usp=sharing

ct2 debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcXIxU1pzdzBnMEk/view?usp=sharing

**Comment by ppmeis** [comment] 2015-07-25 19:45
Tested with latest build. It crash in both CT1 and CT2 after a while. Maybe related to #3854?¿

**Comment by sum2012** [comment] 2015-07-31 12:57
@ppmeis It doesn't work with interpreter mode,so that it is not related to #3854

**Comment by ppmeis** [comment] 2015-12-06 22:12
Tested with latest build. Same status.

**Comment by sum2012** [comment] 2016-10-30 10:33
Update debug log to v1.3-135-g934aff4
https://drive.google.com/file/d/0B3OaSdeV0L8kV1Bmc21NQ3lGU0E/view?usp=sharing

**Comment by ppmeis** [comment] 2017-01-10 10:08
Tested with latest build. Instant crash in CT1 character select screen. CT2 goes ingame but also crash:
![image](https://cloud.githubusercontent.com/assets/4381277/21801775/68b927d8-d723-11e6-8dd6-264a807d1c5c.png)

**Comment by benderscruffy** [comment] 2018-04-27 06:49
v1.5.4-933-g386c9d4fc
still present both crash before they go ingame

**Comment by Cade-H** [comment] 2018-07-07 00:41
v1.6.3-285-g1f60c85cb
Crazy Taxi crashes before character select screen.
Crazy Taxi 2 graphics are now fixed, but crashes before you can drive:
![crazytaxi2](https://user-images.githubusercontent.com/40903969/42404962-63e282b8-8154-11e8-9d4a-adaec8ec8665.png)

**Comment by unknownbrackets** [comment] 2018-08-25 17:52
Do any of the I/O timing settings change whether this crashes?

-[Unknown]

**Comment by HelicopterP** [comment] 2018-08-25 18:16
[ppsspp.zip](https://github.com/hrydgard/ppsspp/files/2320926/ppsspp.zip)
CT1 crashes at character select screen, CT2 crashes after character select screen

**Comment by Cade-H** [comment] 2018-09-01 23:34
v1.6.3-404-ga004196d4 (default settings)
Crazy Taxi 2 is no longer crashing on Small Apple, but there are still some apparent issues. I am not sure which commit changed this unfortunately.
![ct2ingame](https://user-images.githubusercontent.com/40903969/44950743-94df2b80-ae15-11e8-8c98-38537a272659.png)
![ct2bug](https://user-images.githubusercontent.com/40903969/44950744-97418580-ae15-11e8-9d25-34325feb740f.png)

**Comment by unknownbrackets** [comment] 2018-09-03 21:06
That looks bad - but I can't tell how incorrect it is.  From Google, the shadow and top screenshot look like they could be right.  Any chance you could try to compare with a screenshot from a PSP (even if you have to drive to the same place or something?)

If so - in addition to the good and bad screenshot, could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Cade-H** [comment] 2018-09-06 04:59
@unknownbrackets Unfortunately I do not have access to a PSP, but I did as you said in PPSSPP. I attached it to this comment, hope that helps.

I used v1.6.3-426-gf42065ed3 (Default settings)
[ULUS10273_0001.zip](https://github.com/hrydgard/ppsspp/files/2355486/ULUS10273_0001.zip)

**Comment by unknownbrackets** [comment] 2018-09-09 07:41
This game draws the scene to a 512x480 wide buffer, then downloads that framebuffer to RAM, then stretches that to 480x272.

There are a couple verts outside the guardband, but nothing significant.  The texture it's trying to draw there is some sort of granite pattern or something, but it's far away and ends up looking ugly.  Not sure.

https://www.neogaf.com/threads/crazy-taxi-fare-wars-looks-awful.145578/
https://i.neoseeker.com/p/Games/PSP/Racing/Car/crazy_taxi_fare_wars_image3.jpg

It's not a beautiful game, but I didn't find any screenshots that look as bad - I'm guessing somehow we have the wrong texture.

-[Unknown]

**Comment by unknownbrackets** [comment] 2019-02-22 01:52
The latest version of git has some changes that might help debug this better - any chance you could upload a new dump?

It works on more platforms now:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

-[Unknown]

**Comment by ppmeis** [comment] 2019-02-24 00:05
I tested with latest build and CT1 still crashing the same. CT2 crash in both game modes so I can't create a frame dump. Here's the debuglog_
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2897420/ppsspplog.zip)

**Comment by ppmeis** [comment] 2020-02-08 11:38
Tested in latest Windows Build. Same status (offtopic last commit a year ago wow lol).

**Comment by unknownbrackets** [comment] 2020-04-07 03:09
An update GE dump would still help.

-[Unknown]

**Comment by Panderner** [comment] 2020-04-07 05:37
Here's a log that spam this error in crazy taxi 1's title screen:
```
28:56:299 idle0        E[SCEKERNEL]: HLE/sceKernelThread.cpp:2721 sceKernelSuspendThread(287): thread not running
```
And this one crashes after crazy taxi 1 character select screen:
```
31:56:359 user_main    E[G3D]: GPU/GPUCommon.cpp:1243 CALL to illegal address 00000000 - ignoring! data=000000
```

**Comment by Panderner** [comment] 2020-04-07 05:48
And this in crazy taxi 2 in-game:
```
46:21:523 user_main    E[G3D]: GPU/GPUCommon.cpp:716 No DL ID available to enqueue
```

**Comment by oskarangure** [comment] 2020-06-27 01:04
Here's a GE dump of the american version using v1.9.3:
[ULUS10273_0001.zip](https://github.com/hrydgard/ppsspp/files/4839747/ULUS10273_0001.zip)

Also here's how it appears in ppsspp vs how it should be using an actual psp. The marble-like texture in the middle is similar (maybe the same) as the texture of the surface of the water/ocean in the game.
![ct_ppsspp](https://user-images.githubusercontent.com/56091094/85910912-cb521b80-b7de-11ea-946d-02d4a48a1bbe.png)
![ct_psp](https://user-images.githubusercontent.com/56091094/85910928-f177bb80-b7de-11ea-8c3b-28e60d41af47.png)

**Comment by sum2012** [comment] 2020-08-18 14:14
CT1:
Remove spam of these Log:
23:873 user_main    I[SCEKERNEL]: hle\scekernelthread.cpp:2102 -2147352156=sceKernelStartThread(287, 16, 0986be40)
00:23:873 user_main    W[SCEKERNEL]: hle\scekernelthread.cpp:2094 800201a4=sceKernelStartThread(287, 16, 0986be40): thread already running

v1.10.3-449-g8c859ef0f Log:
https://gist.github.com/sum2012/b008d1153068232604115af4d9fea054

debug log:
[ppsspplogv1.10.3-449-g8c859ef0f.txt.zip](https://github.com/hrydgard/ppsspp/files/5090836/ppsspplogv1.10.3-449-g8c859ef0f.txt.zip)

We may need to do thing in sceKernelExitThread  (// TODO: This should trigger ON the thread when it exits.)
and sceKernelTerminateDeleteThread do not same as jpcsp method https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules/ThreadManForUser.java#L3998

**Comment by hrydgard** [comment] 2020-08-18 14:20
Does the game work in JPCSP now?

**Comment by sum2012** [comment] 2020-08-18 14:37
Yes, the game work at least in 2014 year
Newest log: https://gist.github.com/sum2012/6a6e7c5de2b4c1f7a882e3a3c0db9892
Some interested log:WARN hle.ThreadManForUser - Decompress - checkAlarmID unknown uid=0x73

**Comment by sum2012** [comment] 2020-08-18 23:01
unlucky,in jpcsp ignore checkAlarmID check still in-game.

**Comment by sum2012** [comment] 2020-08-30 06:17
I make some hack in sceatrac raise unusual error :/
![image](https://user-images.githubusercontent.com/2177532/91652591-627f6c00-eacb-11ea-8b5e-5c3699b9fc16.png)

**Comment by unknownbrackets** [comment] 2020-08-30 07:34
That seems like a broken memcpy?

`// TODO: This should trigger ON the thread when it exits.` is only for thread event handlers - is this game actually registering any?  Most games don't.  If it really does use them, it's very likely related - they are not well tested.

I've been meaning for a while to try to properly simulate the delayed-delete behavior the actual firmware has.  It is possible that could be a factor here too, but hard to say.

A JpcspTrace could verify if "thread already running" is a problem or just something the game normally does.

-[Unknown]

**Comment by sum2012** [comment] 2020-08-30 10:17
JPCSPTrace log of @unknownbrackets  https://gist.github.com/sum2012/066c74fbefff9a85d507c8e05e9d9c8e
@unknownbrackets why your jpcsptrace don't return
<- _sceKernelExitThread 
or  <- sceKernelExitThread  ?

**Comment by sum2012** [comment] 2020-09-01 12:47
Thanks @shenweip 
confirm v1.10.3-543-ge8c2fce1b-windows-amd64 fixed CT1 and CT2
Closing
![1](https://user-images.githubusercontent.com/2177532/91853058-3c58f800-ec94-11ea-9d3f-b6b1fdeafa03.jpg)
![2](https://user-images.githubusercontent.com/2177532/91853077-44b13300-ec94-11ea-982d-0fd398d635a1.jpg)

**Comment by shenweip** [comment] 2020-09-01 12:55
Good news!

**Comment by hrydgard** [comment] 2020-09-01 12:58
Wow! Fantastic work shenweip. That such a little thing fixed it...

**Comment by sum2012** [comment] 2020-09-01 13:09
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules/ThreadManForUser.java#L488

@shenweip @hrydgard 
Just a bit worry that need for more  hleReSchedule for thread function.

**Comment by unknownbrackets** [comment] 2020-09-02 03:59
Very nice.  Shows the importance of each function and tests.

> JPCSPTrace log of @unknownbrackets https://gist.github.com/sum2012/066c74fbefff9a85d507c8e05e9d9c8e
> @unknownbrackets why your jpcsptrace don't return
> <- _sceKernelExitThread
> or <- sceKernelExitThread ?

It just runs code before and after the function to do that.  There's no after sceKernelExitThread(), so the code can't run.

As for other areas - we should be careful about assumptions, but we may definitely need more tests.

-[Unknown]

**Comment by SilentMRG** [comment] 2021-07-05 22:30
Hi...

Crazy Taxi 2 works perfectly in version 1.11.3, however Crazy Taxi 1 freezes the screen after selecting the game.

I am playing on Windows 7 Ultimate 64bit and with Direct3D 9 API.

I apologize for posting this information in a thread that was closed, but it's just that I don't have any information about the bug, and I thought it would be unnecessary to open a thread to just cite an old bug,

**Comment by SilentMRG** [comment] 2021-07-05 23:05
I just did a quick test here using the OpenGL API, and the game froze 1 time when selecting Crazy Taxi 1 and froze again when selecting Crazy Taxi 2, that is, 1 freeze for each game when selecting them.

In Diretc3D 9, the game froze, several times, and randomly, when selecting CT 1 and 2.

Unfortunately, my video card doesn't support Direct3D 11, so I can't test this API.

I think this old bug is still present, however, randomly, in the above two APIs. Perhaps, in D3D11 this bug does not appear.

I leave this simple warning to those involved in the project.

**Comment by hrydgard** [comment] 2021-07-06 08:09
I don't think the hangs are API-related, though you never know, of course. It's clear that the game isn't completely fixed, so I'll re-open (although the situation is of course a lot better now than when this issue was originally reported).

**Comment by Panderner** [comment] 2021-07-06 15:29
@SilentMRG what specs for your PC are you using?

**Comment by SilentMRG** [comment] 2021-07-06 17:23
> @SilentMRG what specs for your PC are you using?

Laptop:

Windows 7 Ultimate 64 bits
i5 2.67 GHz
4GB DDR3
Intel HD Graphics 1000

Note: Obviously it's a low performance machine, however it manages to run both GOW at 60 fps at default settings. Anyway, I don't believe the bug is hardware related.

**Comment by Panderner** [comment] 2021-07-07 01:29
Works fine for me:
I tested OpenGL and D3D9 for Both CT games when i swap CT games it didn't freeze and Crazy Taxi 1 works fine in-game.

**Comment by Panderner** [comment] 2021-07-07 01:32
Here's my Specs:

AMD A8-7680
Nvidia GTX 1050 Ti
8GB RAM DDR3 1333 MHz
Windows 10 Pro

**Comment by SilentMRG** [comment] 2021-07-07 02:53
> Works fine for me:
> I tested OpenGL and D3D9 for Both CT games when i swap CT games it didn't freeze and Crazy Taxi 1 works fine in-game.

CT 1 and 2 working perfectly here too. The only problem is this random bug that freezes the screen when I select one of the games. Today I played CT 1 for 2 hours and didn't notice any bugs. Then I went to play CT 2 and the screen froze when selecting the game; I closed the emulation and went back to emulating CT 2, and it worked for 30 minutes without bugs.

Note: When the screen freezes the fps stays at 0/0 (100%) and sometimes drops to 90% or 80%, while the fps stays at 0/0, sometimes going up to 02/02.

I have 32 games here and this is the only one with a problem.

Because it's a random bug, it might not happen to everyone.

**Comment by unknownbrackets** [comment] 2021-07-11 05:35
If you can find a way or place to reproduce the issue more frequently, that may help.  I don't personally have the game, but bugs that take hours to reproduce are typically very hard bugs to fix even when you do own the game in question.

Sometimes, a thing that takes a long time to reproduce just actually needs 2 uncommon things to both happen in a specific order.  That's not always the case, but figuring out those kinds of things can help significantly in making bugs easier to fix.

If you see 0/0, that means the game has gone an extended period of time without attempting to draw to the screen and this most likely means an emulation issue.  It can also be caused by cheats, disc issues (please double check your CRC), savedata, or certain settings like the CPU clock speed setting.

Such an issue should definitely not be graphics backend specific (the screen locking up certainly can, be showing 0/0 or 2/2 shouldn't be.)

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-07-27 12:29
@SilentMRG did you also try this game on android and the issue can reproduce?

**Comment by SilentMRG** [comment] 2021-07-27 13:40
> If you can find a way or place to reproduce the issue more frequently, that may help. I don't personally have the game, but bugs that take hours to reproduce are typically very hard bugs to fix even when you do own the game in question.
> 
> Sometimes, a thing that takes a long time to reproduce just actually needs 2 uncommon things to both happen in a specific order. That's not always the case, but figuring out those kinds of things can help significantly in making bugs easier to fix.
> 
> If you see 0/0, that means the game has gone an extended period of time without attempting to draw to the screen and this most likely means an emulation issue. It can also be caused by cheats, disc issues (please double check your CRC), savedata, or certain settings like the CPU clock speed setting.
> 
> Such an issue should definitely not be graphics backend specific (the screen locking up certainly can, be showing 0/0 or 2/2 shouldn't be.)
> 
> -[Unknown]

I understand. And I'll try as soon as I have time, because at the moment I have a lot of work.

**Comment by SilentMRG** [comment] 2021-07-27 13:40
> @SilentMRG did you also try this game on android and the issue can reproduce?

Unfortunately, I don't have a good Android to test, and that makes me stuck on the PC.

**Comment by Gamemulatorer** [comment] 2021-09-09 03:54
> > @SilentMRG did you also try this game on android and the issue can reproduce?
> 
> Unfortunately, I don't have a good Android to test, and that makes me stuck on the PC.

I cannot reproduce this on my android phone.
![Screenshot_2021-09-09-11-53-20-406_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132619691-6750c055-591e-4da5-bf0a-d5301e87fcdd.jpg)
@iota97 why calculate crc is gone?

**Comment by hrydgard** [comment] 2021-09-09 07:10
Huh that is weird! CRC button should be there...

**Comment by Gamemulatorer** [comment] 2021-09-09 08:01
> ![Screenshot_2021-09-09-11-53-20-406_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132619691-6750c055-591e-4da5-bf0a-d5301e87fcdd.jpg)
> @iota97 why calculate crc is gone?

Never mind about the calculate crc.
I forget to scroll down ✌️😂

**Comment by hrydgard** [comment] 2021-09-09 08:35
Ah yeah. we should probably make it more obvious that it's scrollable somehow...

**Comment by Gamemulatorer** [comment] 2021-09-11 13:21
This should be added to the future-prio milestone.

**Comment by hrydgard** [comment] 2021-09-11 13:51
Thanks, missed that.

**Comment by benderscruffy** [comment] 2022-12-07 01:34
i have played it a fair bit and no problems so far
is anyone else still having problems ???
if not please close

**Comment by ppmeis** [comment] 2022-12-17 13:08
Tested in latest windows build. It works just fine.

**Closed** 2022-12-17 13:18 UTC
Labels: HLE/Kernel

**Comment by sum2012** [comment] 2023-10-20 13:35
@ANR2ME in https://github.com/hrydgard/ppsspp/issues/11062#issuecomment-1769770354 reported that Crazy Taxi Fare Wars can sometimes stuck/freezes after selecting either Crazy Taxi or Crazy Taxi 2 (still showing the game selection screen while it stucks

@ANR2ME Can you try Simulate UMD delays ?

**Comment by ANR2ME** [comment] 2023-10-20 19:20
Ah right, i was using the default I/O timing method (Fast) when i was testing the graphical glitches back then, haven't tried using Simulate UMD yet.

Even with Fast it was quite difficult to reproduce it.
