### ISSUE TITLE
Retroach hangs/crashes going from windowed to fullscreen

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#11135] opened 2018-06-04 07:36 UTC
### What happens?
When launching a psp game with retroarch set to window mode, switching to fullscreen mode causes retroach to become unresponsive and crash. If i pause the game by using the quick menu i can switch between window and fullscreen without a crash, but if the game is running it crashes. I use the default f key to toggle window and fullscreen mode. 

### What *should* happen?
I should be able to gracefully switch between windowed and exclusive fullscreen without issue.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
i7 7700k @4.9GHz, Asus GTX 1080ti, 32gb ram, Windows 10 64bit. Desktop.

**Comment by hrydgard** [comment] 2018-06-04 07:53
Does it matter if you use OpenGL or Vulkan?

**Comment by unknownbrackets** [comment] 2018-06-04 14:10
At some point I was led to believe retroarch sometimes uses a core profile without telling us.

-[Unknown]

**Comment by i30817** [comment] 2018-06-04 23:44
It also crashes on load state here with a segmentation fault (but i don't want to bother to build the core just to get a stacktrace).

**Comment by Tatsuya79** [comment] 2018-06-20 16:54
I'm also experiencing the random black screen or/and crash on fullscreen switch or savestate loading in opengl, win7 x64.
Vulkan seems to work better as it didn't do that at all, but crashed on exit though.
In both renderers loading a state is making a huge stutter and you can hear the audio resynchronising for a bit.
I tried playing around with the core options to see if they could fix that but no luck.

**Comment by orbea** [comment] 2018-11-16 23:10
Duplicate of https://github.com/hrydgard/ppsspp/issues/10784.

**Comment by orbea** [comment] 2018-11-16 23:40
Also for the save state crashes see https://github.com/hrydgard/ppsspp/issues/11429

**Comment by unknownbrackets** [comment] 2020-03-08 20:21
Closing this as a duplicate of #10784 per the above.

-[Unknown]

**Closed by unknownbrackets** 2020-03-08 20:21 UTC
Labels: Libretro
