### ISSUE TITLE
Crisis core.

### ISSUE THREAD

**Issue by cwh83** [hrydgard/ppsspp#7287] opened 2015-01-06 16:33 UTC
Not loading past cinematic on jailbroken iphone 6+, just a black screen with subtitles.

**Comment by Bigpet** [comment] 2015-01-06 16:36
duplicate of  #7145 ? well maybe better duplicate of #7095 since it limits itself to one game

**Comment by cwh83** [comment] 2015-01-06 17:59
Yes, it is a duplicate, but none of the threads post a possible solution.

**Comment by unknownbrackets** [comment] 2015-01-06 18:13
@cwh83 we don't have an iOS maintainer.  Creating duplicates is just a way of being rude.  I realize your all-important issue has not been solved so naturally, every person should be sent multiple emails daily until it is solved.

Apparently iOS is broken because the jailbreaks are buggy.  If you want to work on the iOS port, be my guess.  We accept pull requests.

-[Unknown]

**Closed by unknownbrackets** 2015-01-06 18:13 UTC

**Comment by cwh83** [comment] 2015-01-06 18:52
I did not post to this to be rude, I apologize for that. i realize that the ios versions are buggy, I just wanted to see if other users had the same issues.
