### ISSUE TITLE
The MSVC team recently test Ppsspp project run "python test.py --graphics=software 2>&1" test on Windows_x86, the test log seems be blocked

### ISSUE THREAD

**Issue by rachelhe123** [hrydgard/ppsspp#15434] opened 2022-03-11 11:20 UTC
### Game or games this happens in

None

### What area of the game / PPSSPP

Hi All,

The MSVC team recently test Ppsspp project failed to run "python test.py --graphics=software 2>&1" test on release and debug configuration on Windows_x86, seems like the test log be blocked print.

**Describe the bug**

Ppsspp project failed to run "python test.py --graphics=software" test on release configuration on Windows_x86. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**To Reproduce on Windows**

1. git clone https://github.com/hrydgard/ppsspp F:\hrydgard\ppsspp
2. cd F:\hrydgard\ppsspp
3. git submodule update --init --recursive
4. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
5. mkdir F:\hrydgard\ppsspp\build_x86
6. cd F:\hrydgard\ppsspp\build_x86
7. msbuild /m /p:Platform=Win32 /p:Configuration=Release ../Windows/PPSSPP.sln /t:Rebuild /p:OutDir=F:\gitP\hrydgard\ppsspp\build_x86 2>&1
8. cd F:\hrydgard\ppsspp
9. python test.py --graphics=software 2>&1
 

**Error message**

…

pspautotests/tests/font/fontinfobyindex.prx:

  font/fontinfobyindex - passed!

pspautotests/tests/font/fontlist.prx:

  font/fontlist - passed!

pspautotests/tests/font/optimum.prx:

Ran build_x86\PPSSPPHeadless.exe --root pspautotests/tests/../ --compare --timeout=5 @- --graphics=software
 

### What should happen

Test should be run pass and output total test log on the windows_x86.

### Logs

[test.log](https://github.com/hrydgard/ppsspp/files/8231410/test.log)
[test.log.2.txt](https://github.com/hrydgard/ppsspp/files/8231415/test.log.2.txt)

### Platform

Windows

### Mobile phone model or graphics card

None

### PPSSPP version affected

None

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-03-13 20:40
This was probably caused by a leak that was introduced not long ago, and should be fixed in #15440.

-[Unknown]

**Closed** 2022-03-13 20:56 UTC
