### ISSUE TITLE
[Android] [SD Card]That path couldn't be used to save Memory Stick files

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12651] opened 2020-02-28 15:36 UTC
### What happens?
Using Android,MIUI 10 exactly,when trying to change Memory Stick folder,i put exactly right folder path for MicroSD Card,and when i press Confirm,it says:

*That path couldn't be used to save Memory Stick files.*

### What *should* happen?
It should change Memory Stick to that folder

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Phone:Xiaomi Redmi 6
GPU:PowerVR Rogue GE8320
CPU:Mediatek Helio P22
MicroSD:Toshiba M203 32GB
System:Android 8.0.0 running MIUI 10 2.3.0 Stable Release

**Comment by Saramagrean** [comment] 2020-02-28 16:21
Try...

use file manager app goto SD card > "Android" > "data" and create new folder "org.ppsspp.ppsspp" (if u use PPSSPP stable/build) ...or create... "org.ppsspp.ppssppgold" (if u use PPSSPP Gold).

then open app PPSSPP goto settings change memory stick folder to "/storage/(SD card name)/Android/data/org.ppsspp.ppsspp/" (if u use PPSSPP stable/build) ...or... "/storage/(SD card name)/Android/data/org.ppsspp.ppssppgold/" (if u use PPSSPP Gold).

**Comment by Emulatorer** [comment] 2020-02-29 03:27
https://github.com/hrydgard/ppsspp/pull/11812#issuecomment-481489948

**Comment by HiImBrala** [comment] 2020-02-29 07:42
> Try...
> 
> use file manager app goto SD card > "Android" > "data" and create new folder "org.ppsspp.ppsspp" (if u use PPSSPP stable/build) ...or create... "org.ppsspp.ppssppgold" (if u use PPSSPP Gold).
> 
> then open app PPSSPP goto settings change memory stick folder to "/storage/(SD card name)/Android/data/org.ppsspp.ppsspp/" (if u use PPSSPP stable/build) ...or... "/storage/(SD card name)/Android/data/org.ppsspp.ppssppgold/" (if u use PPSSPP Gold).

Will try later,thanks bro

**Comment by HiImBrala** [comment] 2020-02-29 08:12
> Try...
> 
> use file manager app goto SD card > "Android" > "data" and create new folder "org.ppsspp.ppsspp" (if u use PPSSPP stable/build) ...or create... "org.ppsspp.ppssppgold" (if u use PPSSPP Gold).
> 
> then open app PPSSPP goto settings change memory stick folder to "/storage/(SD card name)/Android/data/org.ppsspp.ppsspp/" (if u use PPSSPP stable/build) ...or... "/storage/(SD card name)/Android/data/org.ppsspp.ppssppgold/" (if u use PPSSPP Gold).

Is it possible to use same folder for 2 apps

**Comment by unknownbrackets** [comment] 2020-02-29 19:05
Depends on Android permissions.  Sometimes, no.  See #11997 as well - they plan to make situation more confusing.

This seems like it's essentially a duplicate of #10199.  Closing.

-[Unknown]

**Closed by unknownbrackets** 2020-02-29 19:05 UTC
