### ISSUE TITLE
Everybody's tennis(Europe). Stuck on 'checking storage media'

### ISSUE THREAD

**Issue by GigaMoonOfficial** [hrydgard/ppsspp#14688] opened 2021-08-05 13:25 UTC
![Screenshot_20210805-141833_PPSSPP.jpg](https://user-images.githubusercontent.com/84454254/128357342-38a8c25a-b492-43ca-8201-8fadc69d0adc.jpg)

It's just stuck on this screen forever. This happens after the first tennis game you play.

**Comment by Gamemulatorer** [comment] 2021-08-05 15:11
Platform?
Android, PC?
What ppsspp version are you using?

**Comment by unknownbrackets** [comment] 2021-08-09 01:35
Are you using the latest git build?  Can you provide the logs?  Does it create any save data?  Did you use the data install feature?

Did you check the CRC of your disc to make sure you rippped it cleanly?  Sometimes bugs like this are caused by bad rips.

People have reported this game working with a good CRC:
https://report.ppsspp.org/game/UCES01420_1.01

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-09-01 09:04
I can reproduce this.
![Screenshot_2021-09-01-16-59-16-885_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131643880-121745a9-c371-4b7f-bb95-cb7af3e6c06c.jpg)
[logcat_09-01-2021_16-59-50.txt](https://github.com/hrydgard/ppsspp/files/7089776/logcat_09-01-2021_16-59-50.txt)

**Comment by Gamemulatorer** [comment] 2021-09-01 09:17
Ok what's the meaning of this.?
![Screenshot_2021-09-01-17-08-42-917_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131645932-671656e6-d006-4ba8-b29b-a7de31495ce5.jpg)
Game Details
![Screenshot_2021-09-01-17-14-27-543_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131645973-c1df1de9-6ab2-454f-bf99-cabd773a55ba.jpg)

**Comment by hrydgard** [comment] 2021-09-01 09:25
It may be some new issue related to the new Android scoped storage stuff :(  

Probably related to #14757

**Comment by Gamemulatorer** [comment] 2021-09-01 09:42
Hot Shots Tennis: Get a Grip USA suffer the same issue.
![Screenshot_2021-09-01-17-41-04-279_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131649687-5b672b9a-d5fd-4be4-ae88-13b90b6cf5dd.jpg)
![Screenshot_2021-09-01-17-41-19-017_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/131649711-8fca1c57-b342-4b23-9112-385b068062cb.jpg)

**Comment by Gamemulatorer** [comment] 2021-09-09 17:29
![Screenshot_2021-09-10-01-29-26-573_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132734017-26287ded-1a7f-46fc-8ecf-b5f166736096.jpg)

**Comment by hrydgard** [comment] 2021-09-11 10:20
I'm trying to figure out what might be going on here in general, didn't figure out much.

This is only on Android, right? Which version, and hardware? Where have you placed your memstick folder?

**Comment by Gamemulatorer** [comment] 2021-09-11 11:04
> I'm trying to figure out what might be going on here in general, didn't find much in the log above.
> This is only on Android, right? Which version, and hardware? Where have you placed your memstick folder?

Latest version and stable version can reproduce this issue. Android 11 my games is located to my sccard I try also to put  it on phone storage same issue.

**Comment by Gamemulatorer** [comment] 2021-09-11 11:21
I can also reproduce this on my ancient phone
the 1st time you open this game it's not corrupted but will stuck on checking storage then a second open of this game result to corrupted.
![IMG_20210911_191816](https://user-images.githubusercontent.com/37603562/132946147-6936fbb2-b243-4376-899a-7f4aabba582e.jpg)
![IMG_20210911_191843](https://user-images.githubusercontent.com/37603562/132946150-549b107f-707c-41a7-872f-46b3fabd0996.jpg)

**Comment by hrydgard** [comment] 2021-09-11 11:32
Hm, okay. Would be really useful to figure out when this error started happening. Is it present in the latest official version, for example? Or is it a later change?

**Comment by Gamemulatorer** [comment] 2021-09-11 11:52
I try older version of ppsspp 1.1.1 but same issue game still corrupted.
![Screenshot_2021-09-11-19-50-42](https://user-images.githubusercontent.com/37603562/132947013-356dc334-d808-482a-a761-6c3b28d939b2.png)
Maybe this game never work before? or some copyright protection of the iso :\

**Comment by hrydgard** [comment] 2021-09-11 11:55
Okay, well that's useful information. At least it's not a scoped storage related regression then, though it should of course be investigated.

**Comment by unknownbrackets** [comment] 2021-09-11 13:58
Can you check the CRC of the game to make sure it's not patched for old CFW?

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-09-11 14:22
> Can you check the CRC of the game to make sure it's not patched for old CFW?
> 
> -[Unknown]

![Screenshot_2021-09-11-22-21-44-164_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132951019-d2a3a6fd-3b0e-46e4-8853-04287f070411.jpg)

**Comment by unknownbrackets** [comment] 2021-09-11 15:27
Thanks, okay.  And going back to my earlier comment, are you using the install feature?

Apparently, the game asks you to install data when you start a new game.  What I'm thinking is maybe this only happens when you hit yes?  Or does it always happen?  It might be an issue with install data, and not actually an issue with savedata specifically.  Installation data in PPSSPP is a lot less stable.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-09-11 15:48
> Thanks, okay. And going back to my earlier comment, are you using the install feature?
NO
> Apparently, the game asks you to install data when you start a new game. What I'm thinking is maybe this only happens when you hit yes? Or does it always happen?
> -[Unknown]
Alwayd happen.

**Comment by Gamemulatorer** [comment] 2021-09-11 15:59
I also found a different issue about graphics on my ancient phone.
![Screenshot_2021-09-11-23-43-18](https://user-images.githubusercontent.com/37603562/132953907-5edf4136-042e-4f24-9af0-4e52a3454d06.png)

![Screenshot_2021-09-11-23-44-31](https://user-images.githubusercontent.com/37603562/132953899-c00d38a3-be8b-44d9-925c-0ff0a0e34188.png)

**Comment by Gamemulatorer** [comment] 2021-09-11 16:21
Sad for my android 11 always corrupted :(
![Screenshot_2021-09-12-00-15-40-010_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132954478-046456c0-4a5d-4dd1-a21f-80b6f59055b4.jpg)

**Comment by Gamemulatorer** [comment] 2021-09-11 16:41
> Sad for my android 11 always corrupted :(
> ![Screenshot_2021-09-12-00-15-40-010_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/132954478-046456c0-4a5d-4dd1-a21f-80b6f59055b4.jpg)

Cannot reproduce this on ppsspp gold playstore 🤔

**Comment by sum2012** [comment] 2022-08-21 01:09
I test in windows 7,ppsspp v1.13.1-381-g5046cbd01
When game install, produce UCAS40307GAMEDATA\GAMEDATA.BDL with size 0 !!!
This is game install log: https://gist.github.com/sum2012/6b24685d6d3d31bc3953d83c2a3e8a54

**Comment by sum2012** [comment] 2022-08-21 02:27
On hand build test
v1.1.1-440-g7eb662f good
v1.1.1-458-g29eea47 bad
compare:  https://github.com/hrydgard/ppsspp/compare/v1.1.1-440-g7eb662f..v1.1.1-458-g29eea47

**Comment by unknownbrackets** [comment] 2022-08-21 02:35
Hm.  What files are on the disc in PSP_GAME/INSDIR?  Is it just GAMEDATA.BDL, and how big is that file?

I don't really see anything in that log that shows gamedata install finishing?  It only calls `sceUtilityGamedataInstallUpdate()` once?  That seems odd...

-[Unknown]

**Comment by sum2012** [comment] 2022-08-21 02:40
![1](https://user-images.githubusercontent.com/2177532/185772982-e75e23c6-ce36-4257-a988-5a15b5cc1acd.png)

> Hm. What files are on the disc in PSP_GAME/INSDIR? Is it just GAMEDATA.BDL, and how big is that file?
> 
> I don't really see anything in that log that shows gamedata install finishing? It only calls `sceUtilityGamedataInstallUpdate()` once? That seems odd...
> 
> -[Unknown]
So do I, It only call once in log

**Comment by sum2012** [comment] 2022-08-21 07:52
Here is JPCSPTrace log: https://gist.github.com/sum2012/ce506bd5e4726db44c975f2b6ca34ac8
There are many sceUtilityGamedataInstallUpdate ,also have sceUtilityGamedataInstallShutdownStart 
We are missing game install screen.
https://ibb.co/1GwbRm9
https://ibb.co/FKzJpkc
https://ibb.co/dW0qDSR
https://ibb.co/pbpJTYn

**Comment by sum2012** [comment] 2022-08-22 13:59
Upload full debug log
[ppssppfulldebuglog.zip](https://github.com/hrydgard/ppsspp/files/9394967/ppssppfulldebuglog.zip)

**Comment by sum2012** [comment] 2022-09-12 05:09
The sceUtilityGamedataInstallUpdate(0 fixed in v1.13.1-676-gcd0fff2df (#15948)
I think that remain interface

**Comment by Gamemulatorer** [comment] 2022-10-10 06:06
Still stuck on loading game.
But I notice the loading text doesn't show up in hw unlike in sw.

HW
![Screenshot_2022-10-10-14-04-36-55](https://user-images.githubusercontent.com/37603562/194806674-8b161120-8b10-4c9b-9b88-b3945c5b30a3.png)
SW
![Screenshot_2022-10-10-14-04-56-59](https://user-images.githubusercontent.com/37603562/194806684-8c101b3d-f992-4ac8-9c6a-096eb5ea5b20.png)

**Comment by sum2012** [comment] 2022-10-10 22:19
@Gamemulatorer What is your GAMEDATA.BDL of file's size ?

**Closed** 2023-08-17 22:57 UTC
Labels: Saving issue, User Interface
