### ISSUE TITLE
FIFA serie seems to have some missing UI parts in D3D9

### ISSUE THREAD

**Issue by Trokinos** [hrydgard/ppsspp#8057] opened 2015-10-13 01:16 UTC
Tested with PPSSPP 1.1.1 on winXP (win32) , it's been a very long time i didn't played it on PPSSPP so i couldn't notice before (but i guess it has to do with the same problem as Final Night Round 3 i reported some time ago.
https://github.com/hrydgard/ppsspp/issues/8004

FIFA10 has missing icons, logos and ingame player arrows missing when playing in D3D9. while when playing in OpenGL it's perfect. Everything else run perfectly in D3D9, it's only those 2D UI elements that aren't displayed

I noticed today on the ppsspp board, someone mentionned the same problem, but with FIFA 14 :
http://forums.ppsspp.org/showthread.php?tid=6645&pid=111395#pid111395

As i guess all those EA FIFA games are using the same engine and so probably UI display tricks, it's very likely the whole FIFA serie has that problem on D3D9 with PPSSPP

If i check in PPSSPP , the code for FIFA10 (the european version, but i guess alll versions are affected) is ULES01326 , no idea unfortunately for the other FIFA games or language variant

**Comment by Trokinos** [comment] 2015-10-17 20:09
As i had some time today, i could download and test several builds of PPSSPP to find which one broke FIFA 2010 (and very likely all the FIFA serie) in D3D9

last time FIFA 2010 worked perfectly in D3D9 
ppsspp-v1.0.1-856-g9bf5d40-windows-x86.7z

first build that had FIFA 2010 broken in D3D9 (the UI broken with stuff not displayed anymore i mean)
ppsspp-v1.0.1-857-g08b340f-windows-x86.7z

According to the build list , it's
"More D3D hackery: Take inverted Z in proj matrix into account. Also, *2 breaks it for no good reason so don't do that."
that's responsible

**Comment by unknownbrackets** [comment] 2015-10-17 20:29
So 08b340f, then, from #7920 (although after that merge.)  Maybe there are cases where we do and don't get squashed, or maybe it's clipping?

-[Unknown]

**Comment by ThePhoenixRises** [comment] 2015-10-17 23:50
Yes i can confirm FIFA 2013 & FIFA 2014 both have same problem.
![ppssppwindows 2015-10-17 23-38-28-77](https://cloud.githubusercontent.com/assets/6565304/10561786/b4330fd0-7531-11e5-9de2-64a6b5dbef24.png)
![ppssppwindows 2015-10-17 23-38-16-93](https://cloud.githubusercontent.com/assets/6565304/10561788/c02d6a1a-7531-11e5-8ef2-d4047ef3f639.png)
![ppssppwindows 2015-10-17 23-42-25-92](https://cloud.githubusercontent.com/assets/6565304/10561789/cb9cd5fc-7531-11e5-915b-a012a8f5d509.png)
![ppssppwindows 2015-10-17 23-42-02-20](https://cloud.githubusercontent.com/assets/6565304/10561790/d5618fe2-7531-11e5-8621-48c6121d1be8.png)

Strangely though, FIFA Soccer, the first version released on PSP works fine.

**Comment by Trokinos** [comment] 2016-01-12 03:06
I tested today   v1.1.1-658-gd479990  (window32) and the game is still missing lots of things ingame in D3D9
I mean i still see ingame this :
http://i.imgur.com/dSIuAPv.jpg

Instead of the correct :
http://i.imgur.com/giPoyBk.jpg

And of course some missing pointers and icons during the game in the same way, players name are displayed under the player controlled character though despite the missing stuff.

There's a positive though in this version, in the pre-match i can see the flags now , in past version when i reported the problem i could only seethe  similar lack of flags and emblems as in ThePhoenixRises  screenshots.

**Comment by Trokinos** [comment] 2016-01-21 13:48
Hello, 

I just tried v1.1.1-797-gcd35684 and it appears the FIFA 10 game is now completely fixed in D3D9 , there are no more missing UI element in pre-match and during the match.
Great job !

I am not closing this report, as i can only say that for FIFA 10 , i don't own any other FIFA game of the serie and can't say if the similar problems are fixed in the recent builds like they are for FIFA 10

**Comment by unknownbrackets** [comment] 2016-02-13 02:52
I think there's good reason to expect that it's fixed in the others too.  Since there's been no other noise for a few weeks, I'm going to close this.

If it's still happening in the other versions, we can reopen - just comment.

-[Unknown]

**Closed by unknownbrackets** 2016-02-13 02:52 UTC
Labels: Depth / Z
