### ISSUE TITLE
Pre-rendered Cutscene Issue

### ISSUE THREAD

**Issue by TheRhysWyrill** [hrydgard/ppsspp#17300] opened 2023-04-17 14:37 UTC
### Game or games this happens in

ULES00483 - The Warriors

### What area of the game / PPSSPP

Intro cutscene upon starting a new game appears to stutter constantly as shown below.

https://user-images.githubusercontent.com/27123572/232518002-76f38141-2522-42a7-bb2e-0d256f86d3ae.mp4

### What should happen

The cutscene should play without issue.

### Platform

Windows

### Mobile phone model or graphics card

RTX 2060

### PPSSPP version affected

v1.14.4-1361-g1143661de

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2023-04-17 15:01
The Warriors have known cutscene issues unfortunately. Duplicate of #8991

**Closed by hrydgard** 2023-04-17 15:01 UTC
