### ISSUE TITLE
Crash in Recent list view

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#11615] opened 2018-12-01 08:15 UTC
I got a totally strange crash:
```*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
ABI: 'arm64'
pid: 25476, tid: 26111, name: RenderMan  >>> org.ppsspp.ppsspp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x78
Cause: null pointer dereference
    x0   0000000000000000  x1   0000007590987b00  x2   000000000000003c  x3   000000757da15e00
    x4   0000000000000000  x5   000000758bdc1ac0  x6   000000759fd14000  x7   0000000000143834
    x8   000000759b496000  x9   00000075908d3818  x10  0000000000000000  x11  000000759081cc10
    x12  0000000000000018  x13  000000005c02420a  x14  00209d8329be3cfc  x15  0000d9ea5613f04d
    x16  000000759f1f0fe0  x17  000000759e5c22b0  x18  0000000000000000  x19  0000000000000000
    x20  000000757da15e00  x21  000000000000003c  x22  000000758c41b400  x23  00000075908d425c
    x24  000000757da15e00  x25  000000759b54c360  x26  0000000000000001  x27  0000000000000001
    x28  0000000000000108  x29  000000757eda22e0  x30  000000759f1e49cc
    sp   000000757eda21b0  pc   000000757ffd2d88  pstate 0000000000000000

backtrace:
    #00 pc 0000000000055d88  /system/vendor/lib64/hw/vulkan.msm8996.so (_ZN11qglinternal21vkAcquireImageANDROIDEP10VkDevice_TP9VkImage_TiP13VkSemaphore_TP9VkFence_T+92)
    #01 pc 00000000000139c8  /system/lib64/libvulkan.so (_ZN6vulkan6driver19AcquireNextImageKHREP10VkDevice_TP16VkSwapchainKHR_TmP13VkSemaphore_TP9VkFence_TPj+604)
  ```

Probably happened when I deleted a bunch of dump files which consequently couldn't be found when the app was looking them up.

**Comment by hrydgard** [comment] 2018-12-03 08:36
If you can reproduce this at all, it could be important. If not, meh indeed :)

**Comment by hrydgard** [comment] 2018-12-12 22:55
Hey actually that means that you could reproduce it - which makes it a worthwhile bug since it should be an easy fix once for example I can repro it too. I'm reopening it for 1.8.0.

**Comment by hrydgard** [comment] 2018-12-12 22:55
Although ... can you repro it on Windows too?

**Comment by unknownbrackets** [comment] 2018-12-13 03:48
I think PPSSPP actually locks isos while running so you can't delete them.  This is probably only possible on POSIX/Linux, but typically those don't delete unodes until all open handles are closed?

-[Unknown]

**Comment by leopard20** [comment] 2018-12-13 07:55
The reproduction is a bit hit-or-miss though. I can't say I can reproduce it all the time. I have to try it multiple times to get it right! Maybe that's not the real cause after all (I'm actually starting to think it's a task switching bug, because like I said, it happens when PPSSPP is still open and I switch back to it). I'll do more tests later to find out what's wrong.

**Comment by unknownbrackets** [comment] 2020-03-15 06:48
I think we did fix an issue where we were leaking a file handle.  Has anything improved here?

-[Unknown]

**Comment by hrydgard** [comment] 2020-03-15 09:42
I also believe this is likely to be fixed. I'm gonna close this, let's reopen if we see this again.

**Closed by hrydgard** 2020-03-15 09:42 UTC
