### ISSUE TITLE
Sonic Rivals 2 very slow

### ISSUE THREAD

**Issue by Retr0b0y** [hrydgard/ppsspp#6849] opened 2014-09-06 22:29 UTC
I noticed Sonic Rivals 2 was very very grainy when playing it on ppsspp for iPad 4, is there a fix for this? Please help. Oh and I am using the latest ppsspp version of course.

-Retr0B0y

**Comment by unknownbrackets** [comment] 2015-04-13 18:21
Closing as duplicate of #6117.

-[Unknown]

**Closed by unknownbrackets** 2015-04-13 18:21 UTC
