### ISSUE TITLE
mac OS 13.0.1 and ppsspp 1.13.2 - PPSSPP crashes on load of multiple games tested (gow, gta, tekken)

### ISSUE THREAD

**Issue by f4ts0** [hrydgard/ppsspp#16568] opened 2022-12-13 13:28 UTC
### Game or games this happens in

God of war, GTA vice city, tekken 6

### What area of the game / PPSSPP

Right after game load 

### What should happen

It should not crash

### Logs

Crash logs :

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               PPSSPPSDL [83733]
Path:                  /Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
Identifier:            org.ppsspp.ppsspp
Version:               1.13.2 (1.13.2)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-13 14:18:32.1048 +0100
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Bridge OS Version:     7.0 (20P420)
Anonymous UUID:        414637FE-6458-9091-CF7D-D5405799712E

Sleep/Wake UUID:       6F7581A8-B772-4E09-AD1C-E0C514CCA461

Time Awake Since Boot: 130000 seconds
Time Since Wake:       11656 seconds

System Integrity Protection: enabled

Crashed Thread:        38  Mach exception thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [83733]

VM Region Info: 0 is not in any region.  Bytes before following region: 4315996160
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10140e000-10251e000    [ 17.1M] r-x/r-x SM=COW  ...cOS/PPSSPPSDL

Thread 0::  Dispatch queue: com.apple.main-thread

### Platform

macOS

### Mobile phone model or graphics card

Intel UHD Graphics 630 1536 MB

### PPSSPP version affected

1.13.2

### Last working version

unknown

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2022-12-13 13:31
Duplicate of #16376. It is fixed in the latest builds, and there will be a new release real soon now (tomorrow, likely).

**Closed by hrydgard** 2022-12-13 13:31 UTC

**Comment by f4ts0** [comment] 2022-12-13 17:30
thanks!
