### ISSUE TITLE
Texture Filtering/Scalling

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#6868] opened 2014-09-09 22:30 UTC
While playing Persona 3 Portable i didn't like that the 2D elements had weird lines during the whole
![ules01523_00006](https://cloud.githubusercontent.com/assets/2002038/4209778/8ee53e12-386d-11e4-9754-850b73120739.jpg)

To fix that we would need to change the Texture filtering to Nearest but the thing is that the 3D elements and Background would get pixelated too.
![ules01523_00023](https://cloud.githubusercontent.com/assets/2002038/4209887/ec0b9216-386e-11e4-8725-8c6b19e9c7c6.jpg)
![ules01523_00025](https://cloud.githubusercontent.com/assets/2002038/4209886/ebffcbf2-386e-11e4-9932-f57a27d826ab.jpg)

Is it maybe possible to make the 3D elements be filtered with the auto option while simultaneously filtering the 2D elements with Nearest?

I know that PCSX2 can do that
![0123](https://cloud.githubusercontent.com/assets/2002038/4210043/836092c8-3870-11e4-9a0d-9eaf48601db6.png)
![354](https://cloud.githubusercontent.com/assets/2002038/4210053/a6aecfc4-3870-11e4-8727-aab90387806b.png)

**Comment by unknownbrackets** [comment] 2015-12-23 20:40
A lot of games will render graphics like that using 3D rendering.  The current "Auto" already means "follow what the game says to do", and sometimes the game says things that aren't ideal for increased resolutions.

I don't know that there is a good solution to this with the way that PSP games render.  At best we could try to do it based on number of vertices or something, or hope that the game uses rectangles in that case (definitely not guaranteed.)

Not really very excited about a "it will barely sometimes work" feature, though.  Seems like a great way to confuse users, mostly.

-[Unknown]

**Comment by unknownbrackets** [comment] 2019-03-11 14:56
This is essentially a duplicate of #7232, and doesn't have any specific technical plan, so I'm going to close.

-[Unknown]

**Closed by unknownbrackets** 2019-03-11 14:56 UTC
