### ISSUE TITLE
Vulkan : God Of War Chains Of Olympus flicker lighting on texture

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#10132] opened 2017-11-14 14:20 UTC
![bugs](https://user-images.githubusercontent.com/11285640/32784553-bb8d18ce-c981-11e7-8691-e518d7d683b1.png)

You can see this , using NVIDIA GPU driver

**Comment by marosis** [comment] 2017-11-14 14:46
Yes same problem have lot of games like Assassin's creed Bloodlines or Need for Speed, but only with Buffered rendering. Me little helped off-Disable stencil test

**Comment by marosis** [comment] 2017-11-14 15:06
Assassin's creed Bloodlines                               https://photos.app.goo.gl/ofGaY1US0nqnBwx22   you can see the sword several times.               Need for Speed Most Wanted 5.1.0.   https://photos.app.goo.gl/AYMAlXIc7puytKz32

**Comment by zminhquanz** [comment] 2017-11-15 01:29
@hrydgard

**Comment by LunaMoo** [comment] 2017-11-15 03:27
That's a bloom effect, games commonly make it by reducing framebuffer sizes to create a reduced quality / blurry image which later can be used as a smooth effect. If for some reason like using higher rendering resolution in emulator image is sampled at higher quality it will look bad hence we even have an optional hack that works around it.

 However it seems that in Vulkan currently those effects might not be reducing framebuffer size at all creating a double, sharp image, it also makes optional hack to always fail.

**Comment by LunaMoo** [comment] 2017-11-15 04:05
Oh actually the GOW issue is different, this is a duplicate of #10010 so I'll close it. Also disregard what I said about bloom, I only checked AC right now and it needs separate issue. Other games with bloom like GEB seems fine.

**Comment by hrydgard** [comment] 2017-11-15 13:34
Bloom is implemented differently in different games, hard to consider it one and the same issue. There are a few bugs left with framebuffer blending. Also the flicker mentioned seems different than #10010 , so reopening.

**Comment by Blacob777** [comment] 2017-11-15 15:44
this effect have in dantes inferno too

**Comment by hrydgard** [comment] 2017-11-16 14:03
I think dante's inferno is a different problem.

I don't remember, is this spot far into the game or early? If it's late, got a save?

**Comment by GuilhermeGS2** [comment] 2017-11-16 16:59
@LunaMoo is this hack "Disable stecil test"? I tried it, the graphics look a little blurry even rendering 4x resolution.

Hack off: https://imgur.com/Ui8RepH
Hack on: https://imgur.com/WsswyNm

**Comment by hrydgard** [comment] 2017-11-16 17:05
Disable Stencil Test should not be used for almost any reason, avoid.

**Comment by GuilhermeGS2** [comment] 2017-11-16 17:10
So is there any hack that skips bloom effect to make the image shaper? Some games use it too much, MC LA is an example.

https://imgur.com/VQF3W7v

**Comment by hrydgard** [comment] 2017-11-16 17:40
Unless the guys over at the forums have made cheat codes, then no.

**Comment by hrydgard** [comment] 2017-11-21 13:54
@zminhquanz   Does this happen both on PC and mobile? When in the game is this, is a save needed to reach it? And is it serious enough to block 1.5? :)

**Comment by zminhquanz** [comment] 2017-11-23 09:47
@hrydgard on mobile platform , i don't know because i used the old device ( isn't support Vulkan ) , but on PC it's have a issue

**Comment by marosis** [comment] 2017-11-23 15:45
On mobile Is it same issue. (I have OpenGL)

**Comment by hrydgard** [comment] 2017-11-24 09:58
Does hardware/software transform make a difference?

**Comment by Lotv** [comment] 2017-11-24 13:57
with Hardware Transform off the flickering on the Textures on destructed Boxes is gone.... i don´t now if it´s the same problem.

**Comment by zminhquanz** [comment] 2017-11-24 15:01
![image](https://user-images.githubusercontent.com/11285640/33215538-d12cbfc0-d162-11e7-8a9b-a0546261b9e4.png)
@hrydgard YEAH , The flickering it's gone when i'm turning off hardware transfom , on PC using NVIDIA driver

**Comment by hrydgard** [comment] 2017-11-24 15:54
Okay, interesting...

**Comment by SamueldeSena** [comment] 2017-12-06 14:14
apparently the new version of ppsspp seems to have solved this problem v1.5.4 this topic can already be closed

**Comment by hrydgard** [comment] 2017-12-06 14:38
Closing, please re-open if it's still an issue @zminhquanz .

**Comment by Krusher97** [comment] 2017-12-12 02:17
Using 1.5.4-96 the issue still seems to exist.
![ucus98653_00006](https://user-images.githubusercontent.com/25664221/33864016-9765205a-df10-11e7-98be-a2f318ea823e.jpg)
Disabling hardware transform fixes that specific lighting issue but causes certain metallic objects to act weird. 
![ucus98653_00008](https://user-images.githubusercontent.com/25664221/33864030-b0c731a0-df10-11e7-8ae8-d4a7c3213910.jpg)

**Comment by marosis** [comment] 2018-01-04 10:15
i found new issue like this you can see it in these pictures https://photos.app.goo.gl/mBtWW08Am7DduGPG2   this picture have ON-Disable slower effects (Speed Up)      https://photos.app.goo.gl/KOYyJIRagnEGcoIM2        And this have OFF-Disable  slower effects (Speed Up) first picture is very blury!

**Comment by hrydgard** [comment] 2018-03-24 23:21
Found the issue I think, at least this fixes a different lighting flicker I found early in GoW:COO. Fix submitted.

**Closed** 2018-03-24 23:21 UTC
Labels: Vulkan
