### ISSUE TITLE
Graphical Inconsistency

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#10558] opened 2018-01-23 08:44 UTC
What happens?
When playing hunting horns on MHFU on ppsspp v1.5.2-318 and earlier, notes appear to other players as underscores. When in the Felyne Kitchen, they also appear as underscores when you talk to cats. This happens across DX9/11/GL but I haven't record of Vulkan.

What *should* happen?
Notes should appear green, yellow, red, etc as needed. They should appear as notes when you play the hunting horn to other players.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Seems to affect everyone consistently without exception.

**Comment by unknownbrackets** [comment] 2018-01-23 14:42
This is possibly the same as #2788.  Have you tried using Sony's fonts from a real PSP?

-[Unknown]

**Comment by vnctdj** [comment] 2018-01-23 21:05
@unknownbrackets 
You guessed right : 

our fonts : 
![ppsspp](https://user-images.githubusercontent.com/3978690/35300582-2b7e77a2-0089-11e8-8c83-1a4d1819c1f7.jpg)

Sony's fonts : 
![psp](https://user-images.githubusercontent.com/3978690/35300594-32b10328-0089-11e8-968d-66aecfbb780c.jpg)

**Comment by Hydroque** [comment] 2018-01-24 06:37
I had no clue about this.

**Comment by hrydgard** [comment] 2018-02-08 20:38
Closing as dupe of https://github.com/hrydgard/ppsspp/issues/2788 . We really need to improve our fonts..

**Closed by hrydgard** 2018-02-08 20:38 UTC
