### ISSUE TITLE
Keyboard Functionality for iOS chat support

### ISSUE THREAD

**Issue by silentthorn** [hrydgard/ppsspp#14312] opened 2021-03-22 22:40 UTC
![IMG_0216](https://user-images.githubusercontent.com/81196250/112067021-68a36b80-8b35-11eb-8c91-3208e2e93152.jpg)

This shouldn't be an issue for iOS devices to get implemented as  chat support for Android users has already had support right?

**Comment by ANR2ME** [comment] 2021-03-23 03:24
Not sure whether changing the line `#if PPSSPP_PLATFORM(WINDOWS) || defined(USING_QT_UI) || defined(__ANDROID__)` to add ` || defined(__APPLE__)` would be sufficient or not, since i'm not familiar with iOS/MacOS

**Comment by unknownbrackets** [comment] 2021-03-28 21:59
No that wouldn't be enough.  The actual platform keyboard would need to be hooked up, like on Android.  No one has written any code to activate the iOS native keyboard tray.

This issue is being closed as a duplicate of #13065.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-03-28 21:59 UTC
