### ISSUE TITLE
Crash in Patapon 3

### ISSUE THREAD

**Issue by BolverkWasAnyMore** [hrydgard/ppsspp#7297] opened 2015-01-09 03:00 UTC
when i play patapon 3 it crash

**Comment by hrydgard** [comment] 2015-01-10 19:48
Please add some more information. Were you playing on Android or PC? Where in the game did it crash?

**Comment by ppmeis** [comment] 2015-04-07 07:50
Tested in Windows and Android with latest build. Seems to work fine for me.

**Comment by unknownbrackets** [comment] 2015-04-07 15:29
Closing, in that case.  May be caused by cheats or something, but we can't do anything without more information.

-[Unknown]

**Closed by unknownbrackets** 2015-04-07 15:29 UTC
Labels: No Feedback
