### ISSUE TITLE
[Direct3D]Sims 2 Castaway crash upon simple actions - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13162] opened 2020-07-18 07:04 UTC
Hi,me again.I was playing Sims 2 Castaway pretty fine,when **crash of the emulator** disrupted me.I thought:bug can happen,maybe just random crash.Hours later,everytime i do something like simply going from area to area crashes the emulator.It is really weird and annoying,and if someone can help me out i would be grateful.

TIA

**Comment by Gamemulatorer** [comment] 2020-07-18 07:45
> Hi,me again.I was playing Sims 2 Castaway pretty fine,when **crash of the emulator** disrupted me.I thought:bug can happen,maybe just random crash.Hours later,everytime i do something like simply going from area to area crashes the emulator.It is really weird and annoying,and if someone can help me out i would be grateful.
> 
> TIA

Duplicate of #8999
Comments from @ TAbdiukov.
> While the issue is closed and 95% of crash causes seem to be fixed (thanks a lot for that!); the game still crashes once in a while.
> 
> To be clear, it doesn't get stuck in a glitchy loop and made unplayable (like before), but rather occasionally crashes the whole emulator. I played through the game a week.

**Closed** 2020-07-18 09:24 UTC
