### ISSUE TITLE
Very Laggy Framerate Performance on Retroarch Android 

### ISSUE THREAD

**Issue by yudhiyou** [hrydgard/ppsspp#16811] opened 2023-01-15 12:13 UTC
### Game or games this happens in

All Games

### What area of the game

All areas 

### Platform

Android

### Mobile phone model or graphics card

Vivo V9 Pro

### PPSSPP version affected

The latest version

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

What is causing ppsspp core on retroarch android laggy framerate? Even I tried it on not demanding game like Street Fighter Alpha 3 the framerate is really struggling.
This is not happening on retroarch pc. 

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by yudhiyou** [comment] 2023-01-15 12:14
What is causing ppsspp core on retroarch android laggy framerate? Even I tried it on not demanding game like Street Fighter Alpha 3 the framerate is really struggling.
This is not happening on retroarch pc.

**Comment by bslenul** [comment] 2023-01-15 12:26
Duplicate of #15561

**Comment by LunaMoo** [comment] 2023-01-15 12:42
Closing as a duplicate.

**Closed by LunaMoo** 2023-01-15 12:42 UTC
