### ISSUE TITLE
Using nControl to play on my iPhone 6

### ISSUE THREAD

**Issue by poulet0306** [hrydgard/ppsspp#12440] opened 2019-10-22 05:04 UTC
### What happens?
I used nControl and connected my Dualshock 4 to my iPhone 6. But when I open PPSSPP, it doesn't work.

I should be able to browse the menu using the controller, or bind the controller. But PPSSPP doesn't feedback with the controller.

iPhone 6 iOS 12.4
PPSSPP 1.9.2
Dualshock 4

Does anyone have the same issue?

**Comment by unknownbrackets** [comment] 2020-04-11 17:20
Duplicate of #12311.

-[Unknown]

**Closed by unknownbrackets** 2020-04-11 17:20 UTC
Labels: Input/Controller, Platform-specific (iOS)
