### ISSUE TITLE
Compiling latest PPSSPP build for iOS 11

### ISSUE THREAD

**Issue by andyroid1023** [hrydgard/ppsspp#11886] opened 2019-03-14 12:35 UTC
I have this weird issue on jailbroken iPhone 6 running iOS 11.4.1. PPSSPP runs fine but after a few days, it will just stuck on blue screen every time I’ll open PPSSPP. I have to reboot my phone and rejailbreak every time PPSSPP will stuck on the blue screen.

Many said that 1.6.3-456 has still 32 bit binaries which it doesn’t support on iOS 11, which has 64 bit binaries only. 

I was thinking of using the latest source code and test if this could solve our common issues on iOS 11-12. Since I don’t have a Mac, maybe one of you could help me in compiling the latest source code. 

Thanks and have a nice day :)

**Comment by unknownbrackets** [comment] 2019-03-15 05:29
Is this the same as #9186?  The required reboot you describe sounds the same.

-[Unknown]

**Comment by thorieo** [comment] 2019-03-17 10:31
Same here. A reboot (and rejailbreak) will have it fine again. You just cannot swipe and close it on your app switcher. It must stay open

**Comment by unknownbrackets** [comment] 2019-03-17 12:19
This issue is being closed as a duplicate.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-03-17 12:19 UTC
Labels: Platform-specific (iOS)
