### ISSUE TITLE
 On-screen action buttons have slight offset detection problem.

### ISSUE THREAD

**Issue by 007flawless** [hrydgard/ppsspp#11680] opened 2018-12-17 23:33 UTC
### What happens?

On-screen action buttons have slight offset detection problem. Basically, i have to tap a little bit to the left of the button, for example the Cross (X) button, for it to detect perfectly. Otherwise, it doesn't detect or is ignored

I noticed this after updating from 1.7.2 (64bit) to 1.7.5 (64bit) on Playstore

I have also tested the latest build as at this time of posting, v1.7.5-277, and the bug is still there

### What *should* happen?

Onscreen buttons should detect directly on input surface and as good as they have always been

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Xiaomi Redmi Note 5 Pro
Android 9.0 Stock AOSP
PPSSPP 1.7.5 (64Bit)

**Comment by hrydgard** [comment] 2019-02-12 12:35
I'm gonna close this as a dupe of #11526, it's very similar or the same.

**Closed by hrydgard** 2019-02-12 12:35 UTC
Labels: Input/Controller, Platform-specific (Android)
