### ISSUE TITLE
[Update Suggestion] Make support for emulating OR2006C2C (Outrun 2006 Coast 2 Coast)

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13105] opened 2020-07-08 11:11 UTC
Hi,it is me again,i'm opening issue for developers to see this,or give some suggestions.I got the game yesterday and i was testing it out when i saw it is laggy.At first i always think it is because of my phone,so i tested on neighbor's device (Samsung Galaxy S10) and it was same.Frameskipping does job very well,but game is turning into slideshow,also to mention that some textures,for example sand and water,are wrong or glitched.I hope we will see fix for this.

TIA

**Comment by Panderner** [comment] 2020-07-08 13:02
Have you lowered the internal resolution? and changing the backend? but i think it's a duplicate of #11928

**Comment by MiguelCardonaG** [comment] 2020-07-09 06:53
Hello.

I tested this game on my Samsung Galaxy Note 8 SM-N950F and it works perfectly. The speed (fps) and image are correct.

![PPSSPP_2020-07-09-08-44-42](https://user-images.githubusercontent.com/65356692/87006606-404f2900-c1c1-11ea-8c58-87699d94f92d.jpg)

![PPSSPP_2020-07-09-08-44-48](https://user-images.githubusercontent.com/65356692/87006644-52c96280-c1c1-11ea-9f58-7a61bcd300e4.jpg)

You have to activate this cheat before 

![PPSSPP_2020-07-09-08-52-05](https://user-images.githubusercontent.com/65356692/87006831-97ed9480-c1c1-11ea-92ff-67314a25607d.jpg)

**Comment by EX-e-LD** [comment] 2020-07-09 08:54
Hi,thanks for sharing this out,would you be kind enough to share the cheat in .ini file or here in general @MiguelCardonaG 

TIA

**Comment by MiguelCardonaG** [comment] 2020-07-09 09:38
> Hi,thanks for sharing this out,would you be kind enough to share the cheat in .ini file or here in general @MiguelCardonaG
> 
> TIA

Sure.

https://github.com/Saramagrean/CWCheat-Database-Plus-/archive/master.zip

**Comment by EX-e-LD** [comment] 2020-07-09 10:42
> > Hi,thanks for sharing this out,would you be kind enough to share the cheat in .ini file or here in general @MiguelCardonaG
> > TIA
> 
> Sure.
> 
> https://github.com/Saramagrean/CWCheat-Database-Plus-/archive/master.zip

Thank you very much,i will try it out later,thanks a lot.

**Comment by Gamemulatorer** [comment] 2020-07-09 11:15
@EX-e-LD This is a duplicate of #11928.

**Closed** 2020-07-09 11:21 UTC
