### ISSUE TITLE
Final fantasy type zero rainbow color, and ureasonable slowdown

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#11017] opened 2018-05-08 00:43 UTC
This appears on opengl backend when the whole screen supposed to become redish brown (cause of explosions or when combat end displays on the screen) , and when accessing this menu it displays Rainbow color tirangles like the issue from brave story.. 

Talking to the object:
![screenshot_20180508-030429](https://user-images.githubusercontent.com/5791856/39731642-63118902-529b-11e8-8e49-5dac449cf049.png)

![screenshot_20180508-030407](https://user-images.githubusercontent.com/5791856/39731677-8596f35e-529b-11e8-855e-3d99d48b4072.png)

Fps drop:
I've played this game with a smooth fps but when i use "gathering phantoma" my fps really drop.

there are some cases that this fps drop occur from other games like from star ocean 2nd evolution,  when using "fairy light" the fps really drop even though it only display a simple special effects..but this issue has been fixed in star ocean 2nd evolution.. and i hope that you can do it to here in final fantasy type zero.

### What *should* happen?

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

Update:
This rainbow issue has been fix when my android os updated from nougat to oreo, weird..

**Comment by Saramagrean** [comment] 2018-05-08 01:11
I'm having a very similar problem. 😂

**Comment by unknownbrackets** [comment] 2018-05-08 02:48
This looks like a duplicate of #9926 - right?

-[Unknown]

**Comment by joelolopez** [comment] 2018-05-22 01:38
Update:
This rainbow issue has been fix when my android os updated from nougat to oreo, weird..

**Comment by Saramagrean** [comment] 2018-05-22 12:32
Maybe, next month my smartphone is update to Oreo too, i will try to test again. 😀

**Comment by hrydgard** [comment] 2018-05-22 12:46
Yeah, duplicate of #9926 , and also even more evidence that this is just some kind of driver bug. One that we could probably work around with enough investigation, but meh..

**Closed by hrydgard** 2018-05-22 12:46 UTC
