### ISSUE TITLE
SteelSeries Stratus XL Controller causes app UI highlight to skip across pages of options

### ISSUE THREAD

**Issue by butcher-of-golyat** [hrydgard/ppsspp#12427] opened 2019-10-18 04:23 UTC
Using a SteelSeries Stratus XL on PPSSPP via BlueTooth for Android (phone is Xiaomi Mi Max 3) causes the D-pad to skip over several options on the app UI. It's like the D-pad was on "burst/autofire" mode, pressing the buttons like 15 times. It's the most up to date version of PPSSPP Gold (v1.9.3)

(Note: The d-pad works normally in-game. So the only issue is on the app UI.)

**Comment by LunaMoo** [comment] 2019-10-18 13:40
Closing as a duplicate of #12423

**Closed by LunaMoo** 2019-10-18 13:40 UTC
