### ISSUE TITLE
Vulkan: vsync has to be forced in nvidia contol panel driver or doesn't work

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#11136] opened 2018-06-04 07:49 UTC
### What happens?
When using vulkan the vsync option in the ppsspp gui has no effect. Screen tearing is still visible. Screen tearing is gone when forced in the nvidia control panel.

### What *should* happen?
Vsync should not have to be forced in the nvidia control panel to eliminate screen tearing.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
i7 7700k @4.9GHz, Asus GTX 1080ti, 32gb ram, Windows 10 64bit. Desktop.

**Comment by hrydgard** [comment] 2018-06-04 07:51
Since your other issue was about RetroArch, is this also about PPSSPP inside retroarch, or standalone?

I've never seen tearing with Vulkan, we use MAILBOX or FIFO present mode which should not tear no matter what. Tearing should only happen if present mode is IMMEDIATE.

**Comment by ShadowLady** [comment] 2018-07-13 13:35
I recently got a card that can use Vulkan and I can add some info to this.

I can confirm Vulkan Vsync is not working with my machine either as of 1.6.3-293. 
Windows 10 x64, nvidia 1050ti. 60Hz monitor. 
No Optimus and no other display adapters enabled.


How Vsync behaves currently for me with different backends:


**_Fullscreen - Application Controlled VSync:_**
**OpenGL** - Smooth Vsync.  Works as expected by enabling/disabling the option. Smooth when enabled, tearing when disabled. Can use uncapped FPS, VSync gets disabled when using over 100% speed and has tearing at that point only.
**Vulkan** - Vsync not working. Tearing with VSync both enabled/disabled on PPSSPP.
**Direct3D11** - No tearing regardless of enabling/disabling the option. Not smooth, it drops frames in order to avoid tearing (probably from the DWM?). Can use uncapped FPS, no tearing regardless of speed.
**Direct3D9** - No tearing. Ignores the VSync option after ppsspp launches until restarted. Smooth when enabled, drops frames when disabled but no tearing either way. Capped FPS at monitor refresh rate (60fps in my case) when enabled, games that run at lower speed can only reach that much when using alternate speed. Can use uncapped FPS if Vsync was disabled in PPSSPP before launching it.

**_Windowed - Application controlled Vsync:_**
**OpenGL, Vulkan:** No tearing. No apparent difference with Vsync enabled/disabled on PPSSPP. Not smooth (drops frames to avoid tearing). Can use uncapped FPS.
**Direct3D11, Direct3D9:** No apparent difference compared to Fullscreen.

**_Fullscreen\Windowed - Forced VSync (nvidia CP):_**
**OpenGL, Vulkan:** Smooth Vsync.  Capped FPS.
**Direct3D11, Direct3D9:** No change.


So from my test...
Seems like Direct3D11 just ignores everything.
Direct3D9 only changes with the PPSSPP option but only if it was launched with VSync enabled/disabled.
OpenGL fullscreen is probably the wanted behavior for vsync?

Vulkan vsync is currently not working for me on Fullscreen but can be enabled by forcing it on nvidia control panel which makes it smooth but caps the fps, or running it windowed which has no tearing or fps cap.
The "Buffer-flipping mode" OGL_FORCE_BLIT_ON flag on nvidia inspector also works for vulkan without the fps cap or smoothness but removes the tearing.

**Comment by Narugakuruga** [comment] 2019-01-01 12:16
Vulkan vsync option also doesn't work on my Win 10 PC. This is why I use OpenGL rather than Vulkan.
I tried many different graphic cards, Nvidia GT 1030, Nvidia GTX 1050Ti, Intel UHD Graphics 630. All the drivers are the latest ones from official websites.
Also, OpenGL and Direct3D11 vsync options work normally.

**Comment by SpiffyJUNIOR** [comment] 2019-01-25 18:50
Yeah... not working on mine either. I have a 1050Ti, W10-64x, and the latest drivers. I have to force vsync in the Nvidia control panel instead.

**Comment by Narugakuruga** [comment] 2019-03-13 23:37
I tested Intel vulkan driver and its vsync works perfectly with ppsspp.
So may I consider it's a bug in Nvidia driver and report to Nvidia?

**Comment by ShadowLady** [comment] 2019-03-14 20:24
It would seem it's an nvidia issue with MAILBOX.

RPCS3 had a similar issue with vulkan vsync on nvidia. They seem to have resorted to "Use the slow FIFO mode for vsync instead of mailbox which is broken on nvidia anyway." and it definitely fixed it on my case with RPCS3.

https://github.com/RPCS3/rpcs3/pull/5612

**Comment by unknownbrackets** [comment] 2019-03-15 05:22
Hm, someone claimed that particular issue was fixed, but I guess not so:
https://www.gamedev.net/forums/topic/686349-screen-tearing-with-vulkan-mailbox-present-mode-on-fullscreen/

-[Unknown]

**Comment by hrydgard** [comment] 2019-06-16 22:27
I finally realized why I wasn't seeing this - I almost never run in full screen.

The NVIDIA driver indeed seems to tear in MAILBOX mode in full screen.  It does not tear in a large window, at least not for me.

A clear driver bug that I'll try to get reported.

**Comment by hrydgard** [comment] 2019-06-18 08:01
https://devtalk.nvidia.com/default/topic/1055177/vulkan/vk_present_mode_mailbox_khr-behaving-incorrectly/

Driver fix is on the way, will close when I have confirmed. I don't want to put a pile of ugly workarounds into PPSSPP for this kind of issue, so affected users will need to upgrade their graphics drivers.

**Comment by Narugakuruga** [comment] 2019-06-18 08:10
Thank you so much hrydgard!

**Comment by hrydgard** [comment] 2019-06-18 08:40
Well, I'm just the messenger, I didn't fix it :)

**Comment by hrydgard** [comment] 2019-06-27 07:31
I'm gonna close this as there's nothing to do except to wait for the mainstream driver to get the feature. Beta driver has it now.

**Closed by hrydgard** 2019-06-27 07:31 UTC
Labels: Vulkan

**Comment by klepp0906** [comment] 2019-11-14 22:55
assume that fix never came? i just swapped to OGL for streaming reasons since steam still doesnt have vulkan working right - and its tearing ><

**Comment by Narugakuruga** [comment] 2019-11-14 23:28
After I updated the Nvidia driver, I even found that screen will not tear when vsync option is off.
So it has been fixed.

**Comment by klepp0906** [comment] 2019-11-14 23:31
hmm interesting.  it never fails :P

I was using vulkan universally but the workaround i had for it working over steamlink, stopped working (presumably due to an nvidia driver update) so i swapped back and upon opening ppsspp it was tearing right away.

perhaps it was just the loading screen, didnt try in game.

**Comment by hoholee12** [comment] 2019-11-22 02:18
dx11 tears badly with or without vsync option enabled....
switching to opengl makes vsync work properly
