### ISSUE TITLE
accessing screen stuck 

### ISSUE THREAD

**Issue by swiftnova** [hrydgard/ppsspp#8829] opened 2016-06-26 08:25 UTC
so i have tried many downloads of mega man maverick x for the psp and so far out of all the downloads i have tried only the cool rom us and Europe download will work and by work i mean start up and then immediately freeze on the accessing screen. i have tried pressing start and that has not helped at all idk if this issue is closed but if there is someone out there that can help me fix this issue i would really appreciate it thanks in advance also i'm using open emu on my mac if that helps at all

**Comment by unknownbrackets** [comment] 2016-06-26 13:46
This issue is being closed as a duplicate of #3318.  Also, please don't pirate games.

This isn't a forum - it's an issue tracker.  When you have a grocery list, you wouldn't add "bread" to it every time you thought about bread, you'd only add bread once.  We do the same thing here.  We already have bread on our list.

It's also best to keep all information about a particular issue centralized.  This is open source, so if and when someone becomes interested in fixing the issue, we want to make sure all the information they need to fix it is available.  When information is spread out, bugs get fixed more slowly.

And remember - even if, unfortunately, there's nothing new happening in an issue, creating a duplicate won't get it fixed faster.  Try to find new and useful information, and add it to the original.  And if you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP is open source, and gets better the more people contribute.

-[Unknown]

**Closed by unknownbrackets** 2016-06-26 13:46 UTC

**Comment by swiftnova** [comment] 2016-06-26 15:09
so instead of an answer i get some sad fucking retarted american cunt that
dose not know what the hell he is talking about or has an answer? no really
thanks for the fucking info man it really helps do me a favor and next time
you want to slit your wrists actually do it you worthless piece of shit
