### ISSUE TITLE
Crash in texture pack persona 3 portable

### ISSUE THREAD

**Issue by KaiFujiro** [hrydgard/ppsspp#14252] opened 2021-03-03 06:57 UTC
as the title suggests, I had a random crash when playing Persona 3 portable using a custom texture pack
* I'm using Android Lollipop 5.1.1
* I'm using the ppsspp version 1.11.2-275-g6e4dc3f46

I've done what it says on https://github.com/hrydgard/ppsspp/wiki/Help:-PPSSPP-is-crashing.
But still it didn't work

Please help😭

**Comment by hrydgard** [comment] 2021-03-03 07:55
Thanks, duplicate of #14251 . Fix coming up

**Comment by KaiFujiro** [comment] 2021-03-03 11:29
I will try it

**Comment by KaiFujiro** [comment] 2021-03-03 14:58
Not Working :(

**Comment by hrydgard** [comment] 2021-03-03 15:51
@KaiFujiro is it still crashing on the latest build from https://buildbot.orphis.net/ppsspp/ ?

**Comment by KaiFujiro** [comment] 2021-03-04 02:01
I haven't tried the last build 
But I will try now

**Comment by KaiFujiro** [comment] 2021-03-04 02:08
tbh I still don't really understand how the orphis ppsspp buildbot works.
Does he apply the fix method from the previous build version? And will reapply to the build afterwards.
Or is he just building a version of the ppsspp for that particular problem ?,
For example he made a build version of ppsspp-v1.11.2-279-g8abe7791d That's for my problem now, right after that he made another build with a name v1.11.2-293-gaf5637ecc, Will the fix method that was applied in the previous version also be applied to the later version ?
Sorry if my writing is so convoluted

**Comment by unknownbrackets** [comment] 2021-03-04 03:01
Every time a change is made, it automatically generates a new build there.  Yes, the more recent versions also have the fix.

What you see is a list of changes - and it's true they aren't necessarily "in order".  The "279" number represents how many changes were made since v1.11.2.  But I might make two changes and test them at the same time - if they aren't "official" yet, they'd both have the same number.

Here's an image of what's happening, it's a bit confusing indeed:
![image](https://user-images.githubusercontent.com/191233/109904698-78c0dd00-7c52-11eb-942f-878065b0c0ff.png)

That's why there's multiple v1.11.2-276.  Basically, 276 is the horizontal position in the above image.  v1.11.2-276-gd010f0752 is the change that actually fixed this issue.  v1.11.2-276-g2303cad68 fixed another issue.  Since neither change was "final", they both show as 276 (like two blue dots, one above the other.)

v1.11.2-279-g8abe7791d is where that earlier change, v1.11.2-276-gd010f0752, was "merged" into PPSSPP.  This is final (the green dots above.)  I had already made other changes before it was merged, which is why there's a v1.11.2-279-gd9aecffd7 also.  That's similar to the orange dot.

In the end, the latest one has all the final ones before it.

-[Unknown]

**Comment by KaiFujiro** [comment] 2021-03-04 03:28
so that's how it works, in conclusion the latest version has a fix method of the previous version and the latest build adds another fix method as someone has another problem,is that so?

**Comment by KaiFujiro** [comment] 2021-03-04 03:28
sorry if im wrong

**Comment by KaiFujiro** [comment] 2021-03-04 03:29
Btw last version fixed my problem

**Comment by KaiFujiro** [comment] 2021-03-04 03:31
But there is still a bug where some of the scene textures become black boxes, I pause my ppsspp for a while and come back again, it will fix this problem, but is there a way to permanently fix the problem?

**Comment by unknownbrackets** [comment] 2021-03-04 03:43
> so that's how it works, in conclusion the latest version has a fix method of the previous version and the latest build adds another fix method as someone has another problem,is that so?

Yes.

> But there is still a bug where some of the scene textures become black boxes, I pause my ppsspp for a while and come back again, it will fix this problem, but is there a way to permanently fix the problem?

This is beacause texture packs are usually very high resolution.  All the textures the game is using at once have to be in your phone's memory (different from storage, phones usually have 1GB to 8GB at most of memory.)

If you don't have enough memory for all the high resolution textures uncompressed, some will fail.  These textures will show as black usually.  It's already trying to cut back on texture usage as much as it can when this happens.  Most likely, this means the texture pack is too high resolution for your device.

-[Unknown]

**Comment by KaiFujiro** [comment] 2021-03-04 04:07
okay thanks for answering my question

**Comment by KaiFujiro** [comment] 2021-03-04 04:08
Can I request a feature ?

**Comment by KaiFujiro** [comment] 2021-03-04 04:12
I have an idea to add a feature in this ppsspp, namely the texture scan feature, which is useful for checking if there are corrupt textures and can give a warning if the texture is too big to load, and will display a popup notification if there is a problem

**Comment by KaiFujiro** [comment] 2021-03-04 04:13
I thought that would help a little

**Comment by KaiFujiro** [comment] 2021-03-04 08:24
Nooooo keep crashing on latest version of ppsspp :(

**Comment by hrydgard** [comment] 2021-03-04 08:33
Strange, okay, I'll reopen.

**Comment by KaiFujiro** [comment] 2021-03-04 08:41
yeah it's weird, the texture I use is not corrupt, I check it using zarchive

**Comment by KaiFujiro** [comment] 2021-03-04 08:41
My settings are the same as what is needed to run this texture

**Comment by hrydgard** [comment] 2021-03-04 08:47
Can you link to the texture pack your using? or if it's small, zip it up and attach it to a message here by dragging the zip into it?

**Comment by KaiFujiro** [comment] 2021-03-04 09:28
wait I have the post link

**Comment by KaiFujiro** [comment] 2021-03-04 09:29
Here
https://forums.ppsspp.org/showthread.php?tid=26547

**Comment by KaiFujiro** [comment] 2021-03-04 09:34
Not really about performance, because it runs perfectly on my device with Shader

**Comment by ANR2ME** [comment] 2021-03-04 16:44
Btw, what device are you using? 

Android Lollipop might be an old device with low memory, since the black textures already shown a symptom of running out of memory, and if the games need to allocates more memory (and failed to allocate) it will eventually crashed.

**Comment by KaiFujiro** [comment] 2021-03-04 17:05
I tried it on the J1 Ace J111F device [Root]
I tried it before it didn't crash or anything, Just a little problem in performance (maybe because of the old version of ppsspp)

**Comment by KaiFujiro** [comment] 2021-03-05 00:50
I used to try it on the ppsspp version 1.9.4 and it went well without problems, but now it crashes frequently

**Comment by eleriaqueen** [comment] 2021-03-06 08:43
Hello, I've noticed dev builds after "ppsspp-v1.11.2-245-g91c0ef237-windows-amd64" crash on my PC when loading "Phantasy Star Portable 2 - Infinity" custom textures, not sure if related.
I have a Nvidia GTX 1660 Ti and am using "461.72-desktop-win10-64bit-international-dch-whql" drivers

**Comment by unknownbrackets** [comment] 2021-03-14 19:36
Are there still any crashes left in the latest git builds?

-[Unknown]

**Comment by eleriaqueen** [comment] 2021-03-15 05:37
There doesn't seem to be any crashes of this nature left in latest Git builds. Thanks !

**Closed** 2021-03-15 06:23 UTC
