### ISSUE TITLE
Strange behavior with Japanese dakuten and handakuten characters (examples ギ、パ)

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#2400] opened 2013-06-22 14:33 UTC
![image](https://f.cloud.github.com/assets/1980487/690911/6906e262-db4a-11e2-9d52-6db870b3790c.jpg)
![image](https://f.cloud.github.com/assets/1980487/690906/95871470-db49-11e2-880a-6f20d8cddb8e.jpg)
The UI appears to give the dakuten and handakuten characters their own character space, which is incorrect behavior

Dakuten and Handakuten are the circle and " markings you see on some Japanese characters

Like the " in "gi" -> ギ
Or the circle in "pa" -> パ

To reproduce the problem: put the characters ギ and/or パ in a filename and view it in PPSSPP.

Dakuten and Handakuten display properly in the PPSSPP pause screen.

EDIT: Screenshot attached. 「コードギアス 反逆のルルーシュ LOST COLORS」 is the title.

**Comment by unknownbrackets** [comment] 2020-04-11 22:39
Going to close this as a duplicate of #9958.  As mentioned by xsacha, Qt, Windows, and Android should now render this right using native font rendering.

-[Unknown]

**Closed by unknownbrackets** 2020-04-11 22:39 UTC
Labels: Font Atlas, Platform-specific (iOS)
