### ISSUE TITLE
PPSSPP iOS 13 - Launch = Black Screen

### ISSUE THREAD

**Issue by xSimone** [hrydgard/ppsspp#13373] opened 2020-09-02 17:33 UTC
### What happens?
I open PPSSPP and there's a black screen, nothing else.

### What *should* happen?
It should show the blue screen with the menu, etc.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

I was running 1.9.3 fine, but I wanted to try out 1.10.3 but it had issues for me.  I then tried out the 0v1.6.3 version by accident, because it's on the Cydia Repo. I uninstalled it, and went back to 1.9.3 but now I get black screen upon launch.

Not sure how to fix my issue, or completely remove the issues that may have been made by 0v1.6.3

**Comment by unknownbrackets** [comment] 2020-09-02 17:45
It's very likely that this is a duplicate of #9186.

-[Unknown]

**Comment by SolidSnacke** [comment] 2020-09-05 11:29
Maybe this instruction will help.
1. remove ppsspp
2.Disable jailbreak
3. Reinstall AltStore and download unc0ver through it
4. Jailbreak again
5.Download ppsspp 1.9.3 and install (Since 1.10 for some reason, after several closings it stops working)
For example, I solved the problem like this. (I am writing all this through a translator, since English is not my main language, sorry.)

**Comment by xSimone** [comment] 2020-09-05 12:40
Hi, thanks for the step by step, Solid.

I just wiped and ReJailBroke and I will not be screwing around with different versions anymore.

**Comment by unknownbrackets** [comment] 2020-09-06 21:46
It's not about the number of times you close it, it's just about how you close it, as described in #9186.  Closing this as a duplicate.

-[Unknown]

**Closed by unknownbrackets** 2020-09-06 21:46 UTC
Labels: Platform-specific (iOS)
