### ISSUE TITLE
PPSSPP warns about bad performant CHD while using ZSTD

### ISSUE THREAD

**Issue by LodanZark** [hrydgard/ppsspp#18925] opened 2024-03-13 16:02 UTC
### Game or games this happens in

None

### What area of the game / PPSSPP

![image](https://github.com/hrydgard/ppsspp/assets/11250310/a2e95953-4c0e-41c7-bc05-841c16cadf57)

using the follow command:
`chdman createdvd -c "zstd,zlib,huff,flac" -i "game.iso" -o "game.chd"`

the emulator identifies as bad performant CHD, zstd should be more performant than lzma...

PS: using the MAME 0.263 chdman.

### What should happen

It should identify the CHD as good one.

### Platform

Windows

### Mobile device model or graphics card (GPU)

AMD 7900 XT

### PPSSPP version affected

1.17.1 (stable)

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment] 2024-03-13 16:26
Hm, strange. I'll look into it.

**Comment by LunaMoo** [comment] 2024-03-13 19:12
Probably the issue is caused by what's mentioned here: https://github.com/hrydgard/ppsspp/pull/18803#issuecomment-1928704176
That chdman changed default hunk size in some recent version. As such it's not enough to use createdvd anymore, but also change hunk size to what it should be if there's an option for it.

**Comment by hrydgard** [comment] 2024-03-13 20:31
My god, chdman finds ever more ways to make trouble for us..

I suppose we could add a bit of caching, which would improve performance with larger hunks, but would rather not add the complexity when a 2048 hunk size will perform just fine.

**Comment by LunaMoo** [comment] 2024-03-13 20:51
Or just change the guide and warning message to include the specific hunk size and let people who're in love in container format heavily linked to an arcade cabinet emulation deal with it on their own as this might change again in the future and the setting to specify it to what it should be will probably always work.

**Comment by cuavas** [comment] 2024-03-16 17:20
> I suppose we could add a bit of caching, which would improve performance with larger hunks, but would rather not add the complexity when a 2048 hunk size will perform just fine.

People have been complaining that `chdman createdvd` gives lower compression than `chdman createcd` because of the smaller default hunk size.  I expect you’ll get more users complaining that they can’t use perfectly valid CHDs with your emulator when they increase the hunk size up to 8 sectors to get comparable compression.

Variable hunk size has always been a feature of the CHD format.  The hunk size is always a whole multiple of the sector size.

> ~Just to vent I detest mame for one new reason, building it on windows was a chore, heh all just to get that new, broken chdman.

* You could grab the Windows release binaries from GitHub or SourceForge, as linked on our web site, or grab an up-to-the-minute CI build from GitHub Actions.
* Numerous chdman issues were fixed in 0.263 – it’s *less* broken than 0.262.
* It’s not chdman that’s “broken” – it’s an emulator not supporting a baseline feature.

**Comment by hrydgard** [comment] 2024-03-16 17:44
PPSSPP accesses ISOs in 2048-byte increments since it's the natural sector size, games often do things by sector.

It seems ridiculous to want to create CHDs with non-native sector sizes.

**Comment by cuavas** [comment] 2024-03-16 17:50
> PPSSPP accesses ISOs in 2048-byte increments since it's the natural sector size, games often do things by sector.
>
> It seems ridiculous to want to create CHDs with non-native sector sizes.

People use CHD format because they want compression.  That works better with larger hunk sizes.

Would you also complain that hard disk CHDs aren’t limited to 512-byte hunks to match the sector size?  Compression isn’t very effective at that size because the compressor doesn’t have much to work with and won’t find much redundancy.

Every emulator for CD-based systems has been working fine with the default of 8 sectors/hunk for CD-ROM/GD-ROM, and every emulator for hard disk-based systems has been working fine with the default of 16 sectors/hunk for regular ATA/SCSI hard disks.

**Comment by hrydgard** [comment] 2024-03-16 18:38
But before CHD, there was never any reason for us to implement sector caching. CSO is in the native sector size.

So supporting the CHD format adds additional hassle.

**Comment by cuavas** [comment] 2024-03-16 18:45
Why are you guys taking it out on us?

> My god, chdman finds ever more ways to make trouble for us..

For a feature of the format that’s been there forever and works with every other emulator.

> It seems ridiculous to want to create CHDs with non-native sector sizes.

You *know* the users want CHD format for compression.  Let’s face it, the majority of them probably aren’t asking for it for the SHA1 digests in the header or something.  Giving the compressor more data gives better compression, at the cost of needing to decompress more if the software only wants a single sector.  A lot of the time, software does linear reads anyway, so it’s a performance win with zlib or Zstandard due to less I/O (it’s less of a win with LZMA due to high decompression overhead).

> ~Just to vent I detest mame for one new reason, building it on windows was a chore, heh all just to get that new, broken chdman.

Going out of your way to do things the hard way, then blaming the developers for it, and “detest” is pretty strong language.

**Comment by hrydgard** [comment] 2024-03-16 18:55
> Why are you guys taking it out on us?

Simply because PPSSPP's I/O code relies on a 2048-byte hunk size, and it was working fine with the createdvd command until you guys changed it. It's a bit frustrating.

PPSSPP could probably support other hunk sizes too but it makes CHD support much less of a drop-in change than people advocating for supporting it had claimed.

**Comment by cuavas** [comment] 2024-03-16 19:03
> Simply because PPSSPP's I/O code relies on a 2048-byte hunk size, and it was working fine with the createdvd command until you guys changed it. It's a bit frustrating.

We had a bunch of PPSSPP users complaining on reddit about lower compression ratios with default `chdman creatdvd` options compared to default `chdman createcd` options.  We obviously told them that it’s because `createcd` uses 8-sector hunks by default while `createdvd` used 1-sector hunks by default.  One way or another, you were going to end up with people using CHD files with other hunk sizes.

> PPSSPP could probably support other hunk sizes too but it makes CHD support much less of a drop-in change than people advocating for supporting it had claimed.

I fail to see how what these advocates did or didn’t say is our fault.

Anyway, my main points are:
* Your users clearly weren’t happy with results when using 1 sector/hunk given the feedback on r/emulation over at reddit.
* Variable hunk sizes has always been a baseline feature of the CHD format available for users to set at creation time.  We didn’t add it recently.  If you don’t support it, you don’t support CHD format.
* Being accused of breaking something when I actually fixed a lot of issues in it by someone who apparently “detests” me and the rest of the hyperbole here leaves a pretty bad taste in my mouth.

**Comment by LunaMoo** [comment] 2024-03-16 19:04
Just to note, CHD compression of PSP games is on average better with 2048 than 4096. It varies per game, but 2048 wins, so if CHD users care only about that, CHD should actually work like maxcso and test every sector size for every file to find the best compression. Good luck 😆

**Comment by cuavas** [comment] 2024-03-16 19:06
> Just to note, CHD compression of PSP games is on average better with 2048 than 4096.

Did you compare it to 16384?  Because that’s equivalent to the 8-sector hunks used for CDs.

**Comment by hrydgard** [comment] 2024-03-16 19:13
@cuavas I concede the point that what the advocates said isn't your fault, and as for "detesting", that's not me.

I'll look into how hard it would be to at least make larger hunk sizes work faster in the common large-read cases. But the 2048-byte assumption permeates our I/O code (and the PSP's APIs) so it may be hard to avoid overlapping reads in some cases.

**Closed** 2024-03-16 21:01 UTC
Labels: Loader

**Comment by hrydgard** [comment] 2024-03-16 21:02
OK, turns out our already existing block read combination code is mostly sufficient, just with a bug that made it do redundant reads.

With #18931, it performs quite a bit better. Still, for best performance, I'll keep recommending 2048.

**Comment by Anuskuss** [comment] 2024-04-28 04:55
Just wanna leave this here for future reference:
I initially converted my entire PSP collection from CHD-CD to CHD-DVD after I noticed some music stuttering and while a few files were bigger after the conversion, overall the size went down (don't remember the exact amount but definitely worth it).
Then I tried to push it further by increasing the hunk size. At first I could trigger the stutter at 4x but after #18931 I can't even trigger at it the max hunk size (512x). Anyway, most of the files were bigger going from 1x to 8x but I still went ahead and converted my entire collection in the hopes that it would be a win overall; unfortunately it wasn't and my collection grew by 1.1% (24GB).
So yeah, that was pretty unexpected. I don't know what went wrong but CHD seems to indeed have some problems (for another example look at [how badly CHD handles data that can easily be regenerated](https://github.com/mamedev/mame/issues/7402#issuecomment-2080148679)). I'd hate to say it but I kinda have to agree with LunaMoo: Yes, CHD beats CSO by 5.8% (125GB) but maybe CHD isn't as awesome as I initially thought it would be. Maybe [Aaru Format](https://github.com/aaru-dps/Aaru) will save us all?

**Comment by fx2811p** [comment] 2025-02-26 11:06
hello, what script that I should use to make a chd files without giving "bad chd" warning and give good performance?

**Comment by hrydgard** [comment] 2025-02-26 16:03
The "Bad chd" warning is gone in the latest builds, as performance is now pretty good with all settings.

For optimal performance, see the command line settings documented here: https://www.ppsspp.org/docs/getting-started/dumping-games/

**Comment by fx2811p** [comment] 2025-02-27 13:40
> The "Bad chd" warning is gone in the latest builds, as performance is now pretty good with all settings.
> 
> For optimal performance, see the command line settings documented here: https://www.ppsspp.org/docs/getting-started/dumping-games/

thank you, it works with last ver of ppsspp

anyway I tried 3 times compressing to .chd with normal command, with zstd command and with hs 2048 command.

all running perfectly without fps drop or bad chd warning

**Comment by 1dolla** [comment] 2025-05-23 12:26
Hmm... It's a little concerning to read people conflating hunk sizes with sector sizes, and then blaming what appears to be the author (?) of a piece of software for their own inability to support that format...

I actually stumbled my way here trying to figure out if PPSSPP fully supports the CHD format, which would include support for parent CHDs and and child delta-based CHDs as well. Does it? The storage savings when converting a handful of variants of a given PSP title using a carefully picked parent with lots of data shared between other version can reach upwards of 99% for child delta CHDs.

And does the code now properly support different hunk sizes? No corner cases?

Cheers.

**Comment by hrydgard** [comment] 2025-05-24 09:56
@1dolla We only support full CHDs. However for those, we should now support all available variants including zstd, and using small hunk sizes are not as critical anymore (after a bugfix), though I recommend keeping them relatively small for the best performance (say up to 16 or 32K, no bigger).

The reason we don't support child/parent is that scanning directories for parents would be quite expensive on Android with scoped storage, so haven't bothered adding support.

**Comment by 1dolla** [comment] 2025-05-31 07:00
All right. I did test with large chunk sizes, and it indeed seemed to work just fine with no apparent detriments — and this was on spindle media.

Do you always rescan the files on startup? I mean, there's no index? Because if you indexed the SHA1s along with names, you'd be able to pick the parent @ O(1) speed from a hash. I mean, if that's the only reason it's not supported?

e.g., parent:

```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.277 (unknown)
Input file:   parent-d-eu08psp.chd
File Version: 5
Logical size: 1,458,077,696 bytes
Hunk Size:    4,096 bytes
Total Hunks:  355,976
Unit Size:    2,048 bytes
Total Units:  711,952
Compression:  lzma (LZMA), zlib (Deflate), huff (Huffman), flac (FLAC)
CHD size:     1,096,902,745 bytes
Ratio:        75.2%
SHA1:         ddf6a46055f7f01f927e1a6bdede912a0b78f0cc
Data SHA1:    5e18d82d87f9568d086c8cbf3629c1e17a357ea4
Metadata:     Tag='DVD '  Index=0  Length=1 bytes
              .

     Hunks  Percent  Name
----------  -------  ------------------------------------
    32,333     9.1%  Uncompressed                            
    67,968    19.1%  Copy from self                          
   237,513    66.7%  LZMA                                    
     7,611     2.1%  Deflate                                 
     9,500     2.7%  Huffman                                 
     1,051     0.3%  FLAC   
```

and child:

```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.277 (unknown)
Input file:   child-b-uefa08.chd
File Version: 5
Logical size: 1,379,237,888 bytes
Hunk Size:    4,096 bytes
Total Hunks:  336,728
Unit Size:    2,048 bytes
Total Units:  673,456
Compression:  lzma (LZMA), zlib (Deflate), huff (Huffman), flac (FLAC)
CHD size:     455,818,098 bytes
Ratio:        33.0%
SHA1:         cd64be193a8a2f7d540368ab553b32458ab20dd2
Data SHA1:    f5244b862402552a4236a071873161777eccae4d
Parent SHA1:  ddf6a46055f7f01f927e1a6bdede912a0b78f0cc
Metadata:     Tag='DVD '  Index=0  Length=1 bytes
              .

     Hunks  Percent  Name
----------  -------  ------------------------------------
     2,117     0.6%  Uncompressed                            
        12     0.0%  Copy from self                          
   220,869    65.6%  Copy from parent                        
   112,306    33.4%  LZMA                                    
       851     0.3%  Deflate                                 
        12     0.0%  Huffman                                 
       561     0.2%  FLAC           
```


I haven't actually created CHDs before, but it seems like this parent-child relationship with CHDs was almost made for PSP isos. Some UFA 2008 ISOs:

```
1391M	UEFA.EURO.2008.PAL.PSP-DOMESTIC/d-eu08psp.iso
1391M	UEFA.EURO.2008.USA.PSP-Micronauts/uefa.euro.2008-mcrnts.iso
1316M	UEFA.Euro.2008.EUR.MULTi2.READNFO.PSP-BAHAMUT/b-uefa08.iso
1391M	UEFA.Euro.2008.PROPER.EUR.PSP-ACCiDENT/acdt-euro08.iso
5487M	total
```

As 2k-CHDs:
```
1M	child-acdt-euro08.chd
438M	child-b-uefa08.chd
9M	child-uefa.euro.2008-mcrnts.chd
1039M	parent-d-eu08psp.chd
1485M	total
```

**Comment by hrydgard** [comment] 2025-05-31 07:53
Yeah, it's technically cool, but 99% of users are never going to use parent/child CHDs. If you are legimitately dumping your own UMDs, it's not that likely that you have multiple regions of the same game.
