### ISSUE TITLE
Issue with windowed mode in Linux

### ISSUE THREAD

**Issue by spawn2099** [hrydgard/ppsspp#8679] opened 2016-03-30 17:45 UTC
I'm using Linux Mint 17.3 Cinnamon edition (based on Ubuntu 14.04)
I installed ppsspp from this ppa:
https://launchpad.net/~ppsspp/+archive/ubuntu/stable

My issue is about the following:

When I start ppsspp --windowed it seems it reads the config file and it looks for the config about the PSP Rendering Size option to use it to show me the window in that Size (can be checked through Menu bar > Options > Video > Size > x1). So, to make it readable I change through menu bar the size to x2, and then I check the PSP Rendering Size is now PSP x2 instead PSP x1.

Next thing I do is loading the rom (in my case is Metal Slug Anthology) but it shows some glitches as you can see in this link http://i.imgur.com/Qnsrvtd.png?1

Now, as I said before, the PSP Rendering Size is PSP x2, if I go to the Emulator menu and change it by PSP x1, the window is still x2 size but the game is shown in the right way as you can see here http://i.imgur.com/ApgFZdm.png?1

The problem is, next time I launch ppsspp --windowed is still in x1 size and I have to repeat this workaround.

I congratulate your great job!

**Comment by akien-mga** [comment] 2016-04-01 15:02
I'm seeing the same issue with the Qt version on Mageia (1.2.2.0).

The window shows up by default in 480x272, which is kinda small on a 1920x1080 monitor:
![screenshot_20160401](https://cloud.githubusercontent.com/assets/4701338/14210918/867af922-f82b-11e5-911d-bbd8093278ae.png)

**Comment by akien-mga** [comment] 2016-04-30 20:35
Trying a ``git bisect`` between 1.1.1 and 1.2.2 to see if I can nail down the regression.

**Comment by akien-mga** [comment] 2016-04-30 21:36
Hm, doesn't appear to be a regression in PPSSPP code directly. 1.1.x exhibited to same issue so I went to compile 1.0, and there the behaviour is similar (can't resize the window, relatively small too), but mitigated by the fact that back then the default emulation size was PSP x2.

In my memory it was behaving better a year ago though, so it might be an issue with recent Qt versions (I have Qt 5.6). At any rate, if someone knowledgeable would look into improving the usability of the main menu in windowed mode, I'd be very glad (if there's no technical reason to keep in bound to the emulation resolution, I think the window should be made resizable and with a default size of 1024x768 or higher).

**Comment by Sunderland93** [comment] 2016-05-01 03:23
Same bug i have on Cinnamon and Unity

**Comment by akien-mga** [comment] 2016-05-21 12:33
I'd like to implement a workaround for my Linux package, I don't feel like shipping a stable version that is so hard to use due to a super small size. I guess I could switch my build to the SDL version instead of Qt, but according to the docs the Qt version is the recommended one for desktop Linux. I could maybe patch the default parameters to start in fullscreen mode by default, but then it's hard to access the various Qt menus to learn the useful shortcuts, such as how to go out of fullscreen mode.

Any suggestion?

**Comment by unknownbrackets** [comment] 2016-05-21 15:01
Does `--windowed` actually do anything on Qt?  I'm not sure if that's a supported parameter.

-[Unknown]

**Comment by akien-mga** [comment] 2016-05-21 15:04
@unknownbrackets ``--fullscreen`` works, for ``--windowed`` I can't really tell as the Qt application runs in windowed mode by default (actually even if it was fullscreen the last time it was used - the menu shows "Fullscreen" ticked on, but it still starts in windowed mode).

**Comment by unknownbrackets** [comment] 2016-05-21 15:28
I think the Qt menu system was written before we added the distinction between window size and resolution, and hasn't been updated... I guess the window doesn't resize if you change it from the Settings UI inside the window (i.e. not the menu bar)?

-[Unknown]

**Comment by akien-mga** [comment] 2016-05-21 15:54
If you talk about the "Rendering resolution" in the settings, changing it does not seem to change the window size indeed. I haven't found any other relevant setting for the window size within the custom UI.

The Options > Video > Screen Size parameters work in the Qt menu bar though. (And they impact the "Rendering resolution" in the UI).

**Comment by unknownbrackets** [comment] 2016-05-21 16:23
Yeah, those are supposed to be disconnected.

Does #8759?  I don't actually have a Qt environment to test it on, so I'm committing a bit blind.  But, that should make the menu just update the display size.

-[Unknown]

**Comment by akien-mga** [comment] 2016-05-22 09:53
As far as I'm concerned, this issue is fixed by #8759.

Just a side question: should I try to cherry-pick the patch for 1.2.2, or would I have to resolve too many conflicts?

**Comment by unknownbrackets** [comment] 2016-05-22 14:17
If you skip the files under UI/ and Windows/ (which there's no need to backport), it should apply cleanly.

-[Unknown]

**Closed** 2016-05-22 14:17 UTC
Labels: Qt
