### ISSUE TITLE
Improved texture hashing for texture replacing (multiples of same texture, but different hash)

### ISSUE THREAD

**Issue by xan1242** [hrydgard/ppsspp#14803] opened 2021-09-07 13:00 UTC
### What should happen

I apologize in advance if this is a known issue or there is an opened one already. I couldn't find anything on Github.

Currently there is a problem I've run into with the texture replacer where it dumps/hashes the same texture multiple times regardless of the hashing algo (quick, xxh32 or xxh64). So sometimes when the exact same GIM/texture gets drawn to the screen, it gets a different hash and the hash collision fails.

Tested game was Yu-Gi-Oh! Tag Force 3 ULES-01183

Would it be possible to hash more consistent data of the texture?

So for example, would it be possible to catch the GIM before it's decoded and hash based on that?

Or would it be possible to generate a hash based on the generated PNG and find the collisions after the fact (and add them in the textures.ini accordingly)?

I imagine it's a slow operation but it shouldn't be on modern machines considering the size of PSP textures.

### Who would this benefit

Texture modders, players

### Games this would be useful in

Any

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment] 2021-09-07 13:56
This issue is being closed as a duplicate of #6256.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-09-07 13:56 UTC

**Comment by xan1242** [comment] 2021-09-07 14:30
Kind of an unhelpful response, marking it as duplicate would've been enough, thanks.

**Comment by unknownbrackets** [comment] 2021-09-07 14:58
Sorry if it's patronizing, it's just a saved reply - I use the same message for all duplicates.

-[Unknown]
