### ISSUE TITLE
Bug with replaced textures 

### ISSUE THREAD

**Issue by Gamer1hg** [hrydgard/ppsspp#16966] opened 2023-02-14 16:51 UTC
### Game or games this happens in

Ulus10160

### What area of the game / PPSSPP

I play gta vcs with replaced textures and sometimes they changed random textures 

### What should happen

I don't know this problem

### Platform

Windows

### Mobile phone model or graphics card

Gtx 1050ti

### PPSSPP version affected

1.14.4

### Last working version

1.13.2

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamer1hg** [comment] 2023-02-14 16:55
![Kv_AsZVK7tA](https://user-images.githubusercontent.com/124669787/218804646-c025a99c-a4f9-4277-9ca6-2ddde53eedff.jpg)
Something changed random

**Comment by hrydgard** [comment] 2023-02-14 17:39
Could you give a download link to the texture pack you used?

**Comment by Gamer1hg** [comment] 2023-02-14 17:42
I use ps2 assets mod for PSP , but in old version I don't have bugs https://forum.mixmods.com.br/f22-graficos-interface/t7359-stories-psp-hd-ui-para-o-ps2-assets-mod

**Comment by Gamer1hg** [comment] 2023-02-14 17:44
For some reason it happens if you play for about 40 minutes or an hour

**Comment by Gamer1hg** [comment] 2023-02-14 17:45
> Не могли бы вы дать ссылку на скачивание пакета текстур, который вы использовали?
> 
> Кроме того, происходит ли это в последней сборке с https://buildbot.orphis.net/ppsspp/ ?

I use ps2 assets mod for PSP , but in old version emulator I don't have bugs https://forum.mixmods.com.br/f22-graficos-interface/t7359-stories-psp-hd-ui-para-o-ps2-assets-mod

**Comment by hrydgard** [comment] 2023-02-14 17:56
Which ps2 assets mod for PSP? I'm not gonna google around.

**Comment by hrydgard** [comment] 2023-02-14 18:30
We have fixed a few bugs around texture replacement since 1.14.4, but possibly not all.

**Comment by chrisfand** [comment] 2023-02-19 20:23
I can confirm it also happened to me and some other people for Tag Force 3 once after a while of playing. Seems hard to replicate but if it happens again I'll try to get a savestate or something. I want to say it was a regression introduced in 1.14 as I didn't encounter this in 1.12 or even 1.13.

**Comment by unknownbrackets** [comment] 2023-02-19 20:27
Have you seen it with a git build of PPSSPP newer than v1.14.4?  Specifically v1.14.4-124-g10d7b2d41 or newer.  That fixed an issue with replacements that exists in 1.14.4.

-[Unknown]

**Comment by hrydgard** [comment] 2023-03-02 16:05
In #16991, similar things are reported in quite a new build, so I don't think this is solved.

**Comment by unknownbrackets** [comment] 2023-03-03 02:52
Bad Things could happen if you run out of VRAM.  Not sure if I'd call that an "accidental limit", but I think we've essentially and systematically removed all the low-memory checks that used to run, so hard to tell if that's the case.

-[Unknown]

**Comment by hrydgard** [comment] 2023-03-03 08:26
Well, I would agree that we (or I) simplified away too much of the low-memory checking. And also that various out-of-memory conditions absolutely could be the cause here.

But I plan to start in a different end, by fixing some pathological memory use from texture upload. When a game, through a texture pack, uploads multiple uncompressed 4096x4096 textures in a single frame, our pushbuffers bloat excessively, and stay bloated.

So the ideas I have are:

* Our current push buffers can be improved to bloat less in certain conditions, but better would probably be replacing them with ring buffers or something more akin to the old memory allocator with frame tagging, to make better use of the allocations across frames. Maybe even stall the GPU and flush when full instead of just allocating more and more memory...
* Cap how much replaced-texture data to upload per frame.
* * For PC-only giant packs like this one, supporting DDS textures (BC* compression) make sense. Support for BC compressed formats is slowly starting to appear on mobile too. I previously mentioned Basis, but I am not sure the tradeoffs are worth it.

**Comment by TehPlayer14** [comment] 2023-03-03 20:50
I will see how big the vram usage is during that and report my findings as well

Spreading out multiple textures replace in time sounds like a good idea

With as massive as texturepack is for Patapons, there's tradeoff to how it worked before it broke, and by that I mean, emulator could really stutter at times because it was trying to swap texture as fast as possible

**Comment by hrydgard** [comment] 2023-03-03 22:28
Yeah we don't want to go back to heavy stutter, but also need to make it fast and reliable. I've been messing around in the code a bit and successfully added BC texture compression as an experiment, but also, I feel things can be simplified a bit, which may or may not help.

I am absolutely convinced it's possible to make a pack like the Patapon 3 pack perform and work just great, it's just not exactly trivial, and the images may indeed need to be converted to something other than PNG.

**Comment by TehPlayer14** [comment] 2023-03-05 12:59
As to vram in question, texture pack enabled on Patapon 3, I'm seeing about max of 1.1GBs of vram being allocated, it could be slightly more at times but it shouldn't go beyond 2GBs

**Comment by Gamemulatorer** [comment] 2023-03-08 15:22
Texture in zip format doesn't work in byild https://github.com/hrydgard/ppsspp/commit/625d93a2aeb5e1b69d1ecf80becfa9850f1ee396

**Comment by hrydgard** [comment] 2023-03-08 16:15
Really? Worked for me (on Windows). I'll look into it soon though on Android

**Comment by Gamemulatorer** [comment] 2023-03-09 09:06
Another crash using zim files
```
lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0858.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0858.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0858.EDAT
03-09 17:04:41.277  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0856.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0856.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0856.EDAT
03-09 17:04:41.288  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0854.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0854.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0854.EDAT
03-09 17:04:41.296  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0852.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0852.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0852.EDAT
03-09 17:04:41.306  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0850.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0850.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0850.EDAT
03-09 17:04:41.316  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0848.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0848.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0848.EDAT
03-09 17:04:41.324  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0846.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0846.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0846.EDAT
03-09 17:04:41.334  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0844.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0844.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0844.EDAT
03-09 17:04:41.343  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0842.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0842.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0842.EDAT
03-09 17:04:41.353  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0840.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0840.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0840.EDAT
03-09 17:04:41.365  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0838.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0838.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0838.EDAT
03-09 17:04:41.374  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0836.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0836.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0836.EDAT
03-09 17:04:41.383  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0834.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0834.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0834.EDAT
03-09 17:04:41.392  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0832.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0832.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0832.EDAT
03-09 17:04:41.402  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0830.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0830.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0830.EDAT
03-09 17:04:41.416  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0828.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0828.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0828.EDAT
03-09 17:04:41.424  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0826.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0826.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0826.EDAT
03-09 17:04:41.435  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0824.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0824.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0824.EDAT
03-09 17:04:41.443  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0822.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0822.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0822.EDAT
03-09 17:04:41.454  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0820.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0820.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0820.EDAT
03-09 17:04:41.468  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0818.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0818.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0818.EDAT
03-09 17:04:41.477  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0816.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0816.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0816.EDAT
03-09 17:04:41.488  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0814.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0814.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0814.EDAT
03-09 17:04:41.496  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0812.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0812.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0812.EDAT
03-09 17:04:41.506  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0810.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0810.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0810.EDAT
03-09 17:04:41.517  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0808.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0808.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0808.EDAT
03-09 17:04:41.525  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0806.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0806.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0806.EDAT
03-09 17:04:41.535  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0804.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0804.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0804.EDAT
03-09 17:04:41.543  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0802.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0802.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0802.EDAT
03-09 17:04:41.552  7152  7220 E PpssppActivity: openContentUri exception: java.lang.IllegalArgumentException: Failed to determine if 3136-6161:PSP/GAME/NPJH50878/DATA/00/0800.EDAT is child of 3136-6161:PSP: java.io.FileNotFoundException: Missing file for 3136-6161:PSP/GAME/NPJH50878/DATA/00/0800.EDAT at /storage/3136-6161/PSP/GAME/NPJH50878/DATA/00/0800.EDAT
03-09 17:04:42.590  7291  7291 F DEBUG   : Softversion: PD1930CF_EX_A_6.8.55
03-09 17:04:42.590  7291  7291 F DEBUG   : Time: 2023-03-09 17:04:42
03-09 17:04:42.590  7291  7291 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-09 17:04:42.590  7291  7291 F DEBUG   : Build fingerprint: 'vivo/1906/1906:11/RP1A.200720.012/compiler0316164337:user/release-keys'
03-09 17:04:42.590  7291  7291 F DEBUG   : Revision: '0'
03-09 17:04:42.591  7291  7291 F DEBUG   : ABI: 'arm64'
03-09 17:04:42.591  7291  7291 F DEBUG   : Timestamp: 2023-03-09 17:04:42+0800
03-09 17:04:42.591  7291  7291 F DEBUG   : pid: 7152, tid: 7220, name: EmuThread  >>> org.ppsspp.ppsspp <<<
03-09 17:04:42.591  7291  7291 F DEBUG   : uid: 10407
03-09 17:04:42.591  7291  7291 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x71
03-09 17:04:42.591  7291  7291 F DEBUG   : Cause: null pointer dereference
03-09 17:04:42.591  7291  7291 F DEBUG   :     x0  0000000000000001  x1  0000000000080000  x2  0000000000000040  x3  0000000000000040
03-09 17:04:42.591  7291  7291 F DEBUG   :     x4  0000000000000040  x5  0000000000000004  x6  0000000000000000  x7  0000000000000000
03-09 17:04:42.591  7291  7291 F DEBUG   :     x8  00000000110f040e  x9  00000000110f040e  x10 0000000000000000  x11 0000000000000000
03-09 17:04:42.591  7291  7291 F DEBUG   :     x12 000000705df900e0  x13 0000000004000000  x14 000000705df83668  x15 000000705df8fd74
03-09 17:04:42.591  7291  7291 F DEBUG   :     x16 0000000008000000  x17 0000000000000006  x18 00000070488c4000  x19 00000070ab6bc600
03-09 17:04:42.591  7291  7291 F DEBUG   :     x20 000000703e355f40  x21 000000703e355f40  x22 000000705df8fa90  x23 000000705df8e1f0
03-09 17:04:42.591  7291  7291 F DEBUG   :     x24 000000705df8fa90  x25 000000705df900e0  x26 0000007040f5d1a8  x27 00000070ab6bc600
03-09 17:04:42.591  7291  7291 F DEBUG   :     x28 0000007049054000  x29 00000070490533e0
03-09 17:04:42.591  7291  7291 F DEBUG   :     lr  000000705d3b1ee4  sp  00000070490532f0  pc  000000705d3b1f88  pst 0000000080000000
03-09 17:04:42.775  7291  7291 F DEBUG   : backtrace:
03-09 17:04:42.775  7291  7291 F DEBUG   :       #00 pc 000000000062cf88  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (TextureCacheGLES::BuildTexture(TexCacheEntry*)+236) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #01 pc 0000000000699958  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (TextureCacheCommon::ApplyTexture()+440) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #02 pc 000000000062fc48  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (DrawEngineGLES::DoFlush()+2064) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #03 pc 00000000006c07ec  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (GPUCommonHW::FastRunLoop(DisplayList&)+284) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #04 pc 00000000006b9fa4  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (GPUCommon::InterpretList(DisplayList&)+596) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #05 pc 00000000006b94dc  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (GPUCommon::ProcessDLQueue()+100) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #06 pc 00000000006b9360  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (GPUCommon::EnqueueList(unsigned int, unsigned int, int, PSPPointer<PspGeListArgs>, bool)+2036) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.775  7291  7291 F DEBUG   :       #07 pc 00000000004ef570  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (sceGeListEnQueue(unsigned int, unsigned int, int, unsigned int)+56) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.776  7291  7291 F DEBUG   :       #08 pc 0000000000618cd0  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (PPGeEnd()+212) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.776  7291  7291 F DEBUG   :       #09 pc 000000000048c938  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (PSPMsgDialog::Update(int)+440) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.776  7291  7291 F DEBUG   :       #10 pc 00000000005aa074  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.776  7291  7291 F DEBUG   :       #11 pc 00000000004c7764  /data/app/~~78Y1eA_AKkMZIp8gScH9TA==/org.ppsspp.ppsspp-dr-8EeZrXyK9-St3b2JrdQ==/lib/arm64/libppsspp_jni.so (CallSyscallWithoutFlags(HLEFunction const*)+52) (BuildId: f72cf2811d4b499114ae79c72d293652e67a3bda)
03-09 17:04:42.776  7291  7291 F DEBUG   :       #12 pc 0000000000114f5c  <anonymous:703fc2e000>
03-09 17:04:43.373  7152  7152 I PPSSPPNativeActivity: onPause
```

**Comment by Gamemulatorer** [comment] 2023-03-12 01:12
Does replacement texture isn't really work in software mode?

**Comment by hrydgard** [comment] 2023-03-12 06:06
That's right, it doesn't work in software mode. Not planning to support that.

**Comment by hrydgard** [comment] 2023-03-18 14:13
I believe all of this is fixed now. Closing.

**Closed by hrydgard** 2023-03-18 14:13 UTC
Labels: GE emulation, User Interface
