### ISSUE TITLE
birth by sleep crash

### ISSUE THREAD

**Issue by LuisFellp** [hrydgard/ppsspp#13593] opened 2020-10-27 20:35 UTC
### What happens?
kingdom hearts birth by sleep crashes after final (i think?) cutscene, in the loading screen. 
https://youtu.be/ZVvZ3A_Il8Y it's a translated rom, but the crash isn't related to it, since the normal version crashes too https://youtu.be/da70i4RU7Ao

first time it happened i tried twerking various options, but I don't remember which ones because it was 7 months ago.

this time i disabled I/O timing, fast memory and changed API to OpenGL
### What *should* happen?
not crash

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Exynos 7 Octa (7904), Android ppsspp-v1.10.3-1017-g71706724e-android

**Comment by Panderner** [comment] 2020-10-27 22:05
Duplicate of #12539

**Closed** 2020-10-28 08:34 UTC
