### ISSUE TITLE
Gangs of london crashes in random spots.

### ISSUE THREAD

**Issue by eltomas2003** [hrydgard/ppsspp#14055] opened 2021-02-03 00:19 UTC
UCES00113_1.00 

### What happens?
It randomly crashes when I do free driving.

### What *should* happen?
It should play as normal

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.

Windows 64 | AMD Radeon(TM) Vega 8 Graphics | ppsspp ver. v1.10.3/ opengl backend
-- | -- | --

lenovo s340 amd ryzen 5 3500u windows 10

### Please test newest version in https://buildbot.orphis.net/ppsspp/
![image](https://user-images.githubusercontent.com/75139775/106679879-5a43c500-6572-11eb-8cda-a9bb4811b0df.png)

**Comment by Panderner** [comment] 2021-02-03 00:25
Duplicate of #7239

**Comment by LunaMoo** [comment] 2021-02-03 03:01
Closing as a duplicate of issue mentioned above.

**Closed by LunaMoo** 2021-02-03 03:01 UTC
