### ISSUE TITLE
UI menu is very bigger. for low resolution....please fix...!!!!!

### ISSUE THREAD

**Issue by tee4341** [hrydgard/ppsspp#13678] opened 2020-11-19 18:48 UTC
UI menu is very bigger. for low resolution....please fix...!!!!!
phone low spec  need switch to low resolution different methods for each person

https://vimeo.com/user127494518/review/481357663/71fde3b3c2

video is lg g6 swith 720x1440 to 360x720 (by opengl es 2.0 detection app control)
menu ui is not small to use
control move menu and size is  missing

From my experience everyone change resolution from adb command tool 
each person sclip shotcut

(why you not run 1x frome negative resolution frome you phone   I think best way from play emulator  I can control everything is play game on negative resolution in low resolution phone)
![GifMaker_lowquality1](https://user-images.githubusercontent.com/48321898/99755688-f9cdeb80-2b1d-11eb-8130-ca81a135ae38.gif)

**Comment by Panderner** [comment] 2020-11-19 23:02
are you sure it's a duplicate of #12644? or what device are you using?

**Comment by tee4341** [comment] 2020-11-19 23:37
yes

**Comment by unknownbrackets** [comment] 2021-01-19 06:44
Closing this as a duplicate of #12644, which I've renamed to be a bit more generic.

-[Unknown]

**Closed by unknownbrackets** 2021-01-19 06:44 UTC
Labels: User Interface
