### ISSUE TITLE
Eragon - Font issue - 1.10.2

### ISSUE THREAD

**Issue by EX-e-LD** [hrydgard/ppsspp#13118] opened 2020-07-10 08:42 UTC
### What happens?
Font is wrong,words overlap eachother and aren't in corresponding places

### What *should* happen?
Well,i'm not really sure,i can't find Eragon PSP gameplay,but i can tell this sure isn't normal

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Phone:Honor 9S
GPU:PowerVR GE8320
CPU:Mediatek MT6762R Helio P22
![Screenshot_2020-07-10-10-34-34-494_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87135191-01d96d00-c29a-11ea-8c21-983f1bdbf4af.png)
![Screenshot_2020-07-10-10-34-45-297_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87135194-030a9a00-c29a-11ea-89d9-73f54147fe52.png)
![Screenshot_2020-07-10-10-35-26-936_org ppsspp ppssppgold](https://user-images.githubusercontent.com/67833785/87135197-03a33080-c29a-11ea-856f-3d0c12138873.png)

**Comment by Panderner** [comment] 2020-07-10 08:59
@EX-e-LD You need a real PSP Font. Due to copyright issues PPSSPP does not include the Real PSP font.
I order to fix font issues for some games place the real PSP Font folder to /PSP/FLASH0/ Directory.
Here's a Screenshot of PPSSPP looks like this game with Real PSP Font:
![Screenshot_2020-07-10-16-50-16-71_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/87136718-77f7c700-c2ce-11ea-8c8a-8ace089ba5f5.png)

Duplicate of #2788

**Comment by EX-e-LD** [comment] 2020-07-10 09:07
How do i get the font?If you could answer,i would be grateful.

TIA

**Closed** 2020-07-10 09:12 UTC
