### ISSUE TITLE
4xBRZ in texture shader need highest gpu.....!!!!!

### ISSUE THREAD

**Issue by tee4341** [hrydgard/ppsspp#13679] opened 2020-11-20 04:18 UTC
4xBRZ is hi gpu.....!!!!!
I play every emulator  n64  psx  is use texture fillers linear. is every game fillers creates boarder line on screen

(line  on left-down )( texture fillers linear )

![GifMaker_lowquality5](https://user-images.githubusercontent.com/48321898/99758606-b9be3700-2b24-11eb-8512-17166d41c6f7.gif)
![Capture 2020-11-20 11 35 39](https://user-images.githubusercontent.com/48321898/99761016-a5c80480-2b27-11eb-8cc2-d499b5663ded.jpg)

remove by turn off texture fillers linear

![GifMaker_lowquality3](https://user-images.githubusercontent.com/48321898/99759009-043fb380-2b25-11eb-8953-004875b74e10.gif)

but is effects particle. pixel broken////  T_T
  

fix by. turn on BRZ 2x and tune on 4xBRZ.  

!
(but is shader for pc need highest-gpu )
you can create low spec shader (2xBRZ or BRZ normally for low spec android) please......!!!!!!!!

**Comment by Chriszxz** [comment] 2020-11-20 07:04
wtf I can't even understand your english. XD

**Comment by LunaMoo** [comment] 2020-11-23 02:19
"4x" in 4xBRZ is confusing as it's not really about the resulting size or it's requirements, but an algorithm name. The size is still set by upscale level and the timex X in the name has nothing to do with how light or heavy a shader is. For example 5xBR is a lighter variant of same family of upscaling algorithms, but 2xBR is actually doing more work than 5xBR, there's also a 5xBR with added smoothing that's heavier than all of them and a freescale variants which I don't even remember how demanding are.

 Either way the differences between different variants of xBR and xBRZ aren't that huge without mixing in extra effects as the algorithm still works on same principle and has to sample multiply pixels surrounding each pixel to decide on how it invents new pixels, it can't just sample half pixels to give you a faster variant. 4xBRZ is a basic filter without any fancy additions, so in other words it's as light as it can get while still doing the effect you desire and how demanding it get's is still mostly set by upscale level.

 There might be some uglier, but lighter upscaling algorithms than the xBR/xBRZ family, there might also be shaders useful for upscaling textures to hide artifacts caused by increased rendering res without really inventing new pixels and that would be really interesting as not everyone likes xBR based effects while pretty much everyone would like to get rid of the artifacts in higher render res and disabling texture filtering is really awful workaround.

 But you should understant that x2 2xBRZ(which doesn't even exist and if we follow the xBR variants it would actually be heavier) would be just as laggy on your hardware as x2 4xBRZ which simply can't handle upscaling in real time. For bottom end hardware especially with small screen like phones a better solution would be to simply use native rendering res(x1) as increasing that value is exactly what causes the artifacts you're later trying to hide.

**Comment by tee4341** [comment] 2020-11-23 03:24
hoooo.....

super very thankkkkk!!

**Comment by unknownbrackets** [comment] 2020-12-23 18:14
I'm going to close this as it seems resolved.  We're always trying to make PPSSPP, shaders, etc. more efficient though and will continue to do so.

-[Unknown]

**Closed by unknownbrackets** 2020-12-23 18:14 UTC
