### ISSUE TITLE
Crash in game info screen (Android)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12408] opened 2019-10-11 04:54 UTC
### What happens?
Crash in game info screen after switch to other app and back to PPSSPP. happen on Vulkan only, OpenGL not crash.

Example video.
https://youtu.be/EjaNjEY3tT4

### What *should* happen?
Not crash. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- Huawei P9 Plus (Kirin 955, Mali T-880, Android 8.1)
- PPSSPP v1.9.3-64-g0b17dd04e with default settings

**Comment by hrydgard** [comment] 2019-10-11 07:21
Thanks, this is a great find - seen this crash in Android crash logs and couldn't find a repro.

Will fix soon.

**Comment by hrydgard** [comment] 2019-10-11 14:53
The problem is that it's not safe to take the texture out of a ManagedTexture and assign to a textureview. If the app loses the context, it will try to draw the old, now invalid, texture for a frame before it restores it.

Instead we need to have a TextureView object that holds a reference to a ManagedTexture. Will fix.

**Comment by hrydgard** [comment] 2019-10-11 15:10
Hm, since the ManagedTexture lives in the game info cache, and that gets cleared when we task switch away, i think we'll have to update these frame by frame instead before. gah.

**Closed** 2019-10-11 18:20 UTC
Labels: Vulkan
