### ISSUE TITLE
Metal gear solid peace walker:peace wlaker boss isn't finish

### ISSUE THREAD

**Issue by Sittidet** [hrydgard/ppsspp#7910] opened 2015-08-18 00:45 UTC
peace walker isn't finish,because the last hp bar of peace walker isn't delete on last lunch the nuke.i play ppsspp on lastest build isn't work for me.i play on android device.some one have ppsspp build is work or the problem is fix on next build.(i don't strong english,some word is wrong,i sorry about that)

**Comment by thedax** [comment] 2015-08-18 02:13
Dupe of https://github.com/hrydgard/ppsspp/issues/2845. Continue discussion there.

**Closed by thedax** 2015-08-18 02:13 UTC
