### ISSUE TITLE
Dynasty Warriors Multi Raid 2 (真·三国无双：联合作战2)Online questions

### ISSUE THREAD

**Issue by xiaolang0668** [hrydgard/ppsspp#13667] opened 2020-11-16 14:30 UTC
![真三国无双2](https://user-images.githubusercontent.com/74450832/99263854-ad9f5480-285a-11eb-8e33-6d5951ad3c34.jpg)

Test dynastyy warriors multi raid 2 game, only 2 people successfully enter the battlefield, more than three people enter the battlefield directly offline, hope the gods repair.

**Comment by xiaolang0668** [comment] 2020-11-16 14:45
![aaa](https://user-images.githubusercontent.com/74450832/99265987-4505a700-285d-11eb-931f-ea3fd58bcb2a.jpg)
![bb](https://user-images.githubusercontent.com/74450832/99266124-6797c000-285d-11eb-857c-2a9b98f5951d.jpg)


> 
> Test dynastyy warriors multi raid 2 game, only 2 people successfully enter the battlefield, more than three people enter the battlefield directly offline, hope the gods repair.

**Comment by MojoJojoDojo** [comment] 2020-11-16 14:51
Huh what is this issue about lol?
You cant play the game with over 2 players?

**Comment by xiaolang0668** [comment] 2020-11-16 16:40
> Huh what is this issue about lol?
> You cant play the game with over 2 players?

Three players have an invisible task, leave one, can not see the task of the player, can not see, more than three players, after the start of the task into the field, not all offline, only two players online, the rest are offline.

**Comment by xiaolang0668** [comment] 2020-11-16 17:27
![20201117011843](https://user-images.githubusercontent.com/74450832/99285825-05e25080-2873-11eb-9617-5c878af95ef6.jpg)
![20201117011708](https://user-images.githubusercontent.com/74450832/99285840-0bd83180-2873-11eb-89e3-3428d6265476.jpg)


![dxl0](https://user-images.githubusercontent.com/74450832/99286562-00393a80-2874-11eb-9bef-8528ecd6742c.gif)

**Comment by ANR2ME** [comment] 2020-11-16 23:06
@xiaolang0668 have you tried to Enable "Forced First Connect" in Networking settings?

**Comment by xiaolang0668** [comment] 2020-11-17 01:43
> @xiaolang0668 have you tried to Enable "Forced First Connect" in Networking settings? on all players

Whether the test switch is opened or not is dropped.

**Comment by xiaolang0668** [comment] 2020-11-18 13:51
![22](https://user-images.githubusercontent.com/74450832/99538478-fb959300-29e7-11eb-9117-261f61e26f87.png)
Four people can not receive tasks in normal synchronization, and there will be problems when they enter the game.

**Comment by xiaolang0668** [comment] 2020-11-18 14:35
Players who can't see the first mission,Is there a better way to solve the problem of the group of four.

**Comment by xiaolang0668** [comment] 2020-11-18 14:36
> Huh what is this issue about lol?
> You cant play the game with over 2 players?

YES

**Comment by xiaolang0668** [comment] 2020-11-18 15:44
![The remaining two players cannot accept the mission](https://user-images.githubusercontent.com/74450832/99552470-00fad980-29f8-11eb-954b-84787b6b63fa.png)
The remaining two players cannot accept the mission

**Comment by ANR2ME** [comment] 2020-11-19 11:13
> ![22](https://user-images.githubusercontent.com/74450832/99538478-fb959300-29e7-11eb-9117-261f61e26f87.png)
> Four people can not receive tasks in normal synchronization, and there will be problems when they enter the game.

These errors Unimplemented functions are part of Infrastructure API, and PPSSPP doesn't support it yet, probably not going to be supported anytime soon.

May i know how to setup the mission on this game? since i can't read japanese text

**Comment by MojoJojoDojo** [comment] 2020-11-19 11:19
It looks similar to how 

> > Four people can not receive tasks in normal synchronization, and there will be problems when they enter the game.
> 
> These errors Unimplemented functions are part of Infrastructure API, and PPSSPP doesn't support it yet, probably not going to be supported anytime soon.
> 
> May i know how to setup the mission on this game? since i can't read japanese/chinese text

By seeing the pictures it looks similar to how Dynasty Warriors Strikeforce does it .
You need to see how it is there to understand how it is in that game though I think.

**Comment by ANR2ME** [comment] 2021-01-21 12:27
@xiaolang0668 is this still issue happening with the latest dev build from https://buildbot.orphis.net/ppsspp/ ?

**Comment by ANR2ME** [comment] 2021-01-30 08:28
@xiaolang0668 Please try again after PR https://github.com/hrydgard/ppsspp/pull/13997 got merged.

I only tested this on localhost
![image](https://user-images.githubusercontent.com/7974720/106351579-cf639000-630f-11eb-97f8-b202ad5416e0.png)

**Comment by xiaolang0668** [comment] 2021-03-07 14:46
Thank you for your repair, you can play with friends~\(≧▽≦)/~.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AdamN"<notifications@github.com&gt;; 
发送时间: 2021年1月30日(星期六) 下午4:28
收件人: "hrydgard/ppsspp"<ppsspp@noreply.github.com&gt;; 
抄送: "小狼"<kll1000@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hrydgard/ppsspp] Dynasty Warriors Multi Raid 2 (真·三国无双：联合作战2)Online questions (#13667)





 
@xiaolang0668 Please try again after PR #13997 got merged.
 
I only tested this on localhost
 
 
&mdash;

**Comment by xiaolang0668** [comment] 2021-03-07 14:58
![002](https://user-images.githubusercontent.com/74450832/110244158-6b7c5900-7f98-11eb-9d9d-1ecf8d0e8efa.jpg)
![001](https://user-images.githubusercontent.com/74450832/110244162-720ad080-7f98-11eb-83f1-0367cee1eefd.jpg)
current version: ppsspp-v1.11.2-299

**Comment by ANR2ME** [comment] 2021-03-07 15:53
Okay, thanks for confirming it. 
If this is fixed, i'll close this now

**Closed by ANR2ME** 2021-03-07 15:53 UTC
Labels: Networking / adhoc

**Comment by xiaolang0668** [comment] 2021-03-07 15:59
I'm still testing and found some bugs. If there are two accepted tasks and the third one comes in, sometimes it only shows that one player has a task, and the task menu cannot be displayed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AdamN"<notifications@github.com&gt;; 
发送时间: 2021年3月7日(星期天) 晚上11:53
收件人: "hrydgard/ppsspp"<ppsspp@noreply.github.com&gt;; 
抄送: "小狼"<kll1000@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hrydgard/ppsspp] Dynasty Warriors Multi Raid 2 (真·三国无双：联合作战2)Online questions (#13667)





 
Okay, thanks for confirming it.
 If this is fixed, i'll close this now
 
&mdash;

**Comment by xiaolang0668** [comment] 2021-03-07 16:00
Can other games solve the online problem?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AdamN"<notifications@github.com&gt;; 
发送时间: 2021年3月7日(星期天) 晚上11:53
收件人: "hrydgard/ppsspp"<ppsspp@noreply.github.com&gt;; 
抄送: "小狼"<kll1000@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hrydgard/ppsspp] Dynasty Warriors Multi Raid 2 (真·三国无双：联合作战2)Online questions (#13667)





 
Okay, thanks for confirming it.
 If this is fixed, i'll close this now
 
&mdash;

**Comment by ANR2ME** [comment] 2021-03-07 16:22
> 
> Can other games solve the online problem?
> 
what other game?

**Comment by ANR2ME** [comment] 2021-03-07 16:26
> 
> I'm still testing and found some bugs. If there are two accepted tasks and the third one comes in, sometimes it only shows that one player has a task, and the task menu cannot be displayed.
> 
Is this happened often? otherwise it will be hard to reproduce
As i remembered sometimes it takes longer for the connection to be established, may be you just need to wait for a bit longer before the task can be displayed properly.

**Comment by xiaolang0668** [comment] 2021-03-07 16:29
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AdamN"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 凌晨0:22
收件人: "hrydgard/ppsspp"<ppsspp@noreply.github.com&gt;; 
抄送: "小狼"<kll1000@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hrydgard/ppsspp] Dynasty Warriors Multi Raid 2 (真·三国无双：联合作战2)Online questions (#13667)





  
Can other games solve the online problem?
  
what other game?
 
&mdash;

**Comment by xiaolang0668** [comment] 2021-03-07 16:33
机动战士高达 高达对高达Next Plus

&nbsp;Kidou&nbsp;Senshi&nbsp;Gundam&nbsp;:&nbsp;Gundam&nbsp;vs.&nbsp;Gundam&nbsp;Next&nbsp;Plus






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AdamN"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 凌晨0:26
收件人: "hrydgard/ppsspp"<ppsspp@noreply.github.com&gt;; 
抄送: "小狼"<kll1000@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hrydgard/ppsspp] Dynasty Warriors Multi Raid 2 (真·三国无双：联合作战2)Online questions (#13667)





  
I'm still testing and found some bugs. If there are two accepted tasks and the third one comes in, sometimes it only shows that one player has a task, and the task menu cannot be displayed.
  
Is this happened often? otherwise it will be hard to reproduce
 As i remembered sometimes it takes longer for the connection to be established, may be you just need to wait for a bit longer before the task can be displayed properly.
 
&mdash;
