### ISSUE TITLE
iOS graphics issue - blank textures in Persona 3

### ISSUE THREAD

**Issue by leegendary813** [hrydgard/ppsspp#13573] opened 2020-10-22 12:21 UTC
People are saying that ios 14 is the main problem that is causing these weird glitches, but as you can see on the picture below the character portraits showing HP and SP are gone so it makes it impossible to battle while watching your health. Also the attack buttons are gone making it hard to fight in the game’s main dungeon. If there are any solutions please let me know right away! Thank you!
![185CD388-C6FE-41C1-94C3-0E230575F1AE](https://user-images.githubusercontent.com/73291596/96870909-90d05680-143f-11eb-970f-1fa2e869a5eb.png)

**Comment by Panderner** [comment] 2020-10-22 12:27
@leegendary813 have you used ir interpreter?

**Comment by hrydgard** [comment] 2020-10-22 12:30
Are you not on iOS 14? Otherwise this is of course a duplicate of #13451 .

**Comment by Quietninja0954** [comment] 2020-10-23 22:46
@leegendary813 yes the first picture is when I used that

**Comment by Quietninja0954** [comment] 2020-10-23 22:47
@hrydgard I am on iOS 14

**Comment by hrydgard** [comment] 2020-11-02 23:17
Duplicate of #13451

**Closed by hrydgard** 2020-11-02 23:17 UTC
Labels: Platform-specific (iOS)
