### ISSUE TITLE
PPSSPP on iOS audio and game lags hardcore

### ISSUE THREAD

**Issue by Vertpin** [hrydgard/ppsspp#9856] opened 2017-07-21 05:02 UTC
Using IR Interpreter (JIT crashes)

Iphone 7 Plus

Playing Persona 3 Portable. The game has choppy audio and lags slows down quite a bit and gets worse even time. 

Any idea when there will be a fix? Does JIT compiler really help that much? Game goes down to like 5FPS a lot.

**Comment by unknownbrackets** [comment] 2017-12-29 08:25
Compared to my Pixel, it seems like an iPhone 6 definitely runs slower, especially during loading.  Jit is definitely significant.  We already have bugs for the reasons - jit issues (fixed in #10465), bad GLES drivers (#9309), and the snipe hunt called microstutter (#9197.)

If you compiled it yourself using Xcode, make sure it's a Release build, since Debug builds are much slower.

There's a forum (http://forums.ppsspp.org/) if you want to discuss things, but this is an issue list - like a grocery list, there's no need to put things like "bread" on it twice.  So, closing as a duplicate of #9232 / #9309 / #9197.

-[Unknown]

**Closed by unknownbrackets** 2017-12-29 08:25 UTC
Labels: Platform-specific (iOS)
