### ISSUE TITLE
Texture Stretching in Gundam Assault Survive and Ridge Racer on S8 (GL)

### ISSUE THREAD

**Issue by animalvgamer** [hrydgard/ppsspp#9981] opened 2017-09-25 23:09 UTC
Device: Samsung Galaxy S8 (Exynos version)
I believe this issue has to do with the extra wide display on the S8 causing texture coordinates to be calculated incorrectly despite the sprite locations being correct. It also seems to only occur with specific text, the pause map, and the character face sprites in the corner.

![screenshot_20170925-141753](https://user-images.githubusercontent.com/1676773/30835202-e4fead96-a20b-11e7-8490-6dcb2be15db5.png)

**Comment by hrydgard** [comment] 2017-09-28 07:31
I don't think it's the wide display, it's just a driver bug. It does not happen with Vulkan.

I've got a different repro (Ridge Racer) which I will look at and see if there's an easy workaround.

**Comment by hrydgard** [comment] 2017-11-14 11:03
Can't repro on any other phone, this appears to be a driver bug. Funny thing is the game is not doing anything weird when it happens, it's just doing a regular through-mode rectangle. 

Doesn't happen in Vulkan so on the S8 I'd just recommend switching to that. Bumping to 1.6.0 instead of closing in case anyone want to investigate deeply...

**Comment by unknownbrackets** [comment] 2017-12-02 02:50
This is the same issue as #9645, right?

-[Unknown]

**Comment by hrydgard** [comment] 2017-12-02 08:36
Duplicate of #9645 indeed, closing. It's a very strange one...

**Closed by hrydgard** 2017-12-02 08:36 UTC
Labels: OpenGL
