### ISSUE TITLE
Tas problems linux only

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#11860] opened 2019-03-02 19:12 UTC
I know I’ve been writing issues related to libtas here before, but desyncs problems are still an issue and we are lost on what to do. Inputs go out of sync sometimes for some reason and even with the save state work around for deterministic rng, it still doesn’t sync all the way(especially when encoding). 

https://github.com/clementgallet/libTAS/issues/151

That’s all the testing we done with ppsspp desync problems. Is there some rng api we didn’t hook maybe? I really would want to get this fixed. But like I said, we are lost.

**Comment by unknownbrackets** [comment] 2020-04-11 22:12
Going to close this as a duplicate of #12501.

-[Unknown]

**Closed by unknownbrackets** 2020-04-11 22:12 UTC
