### ISSUE TITLE
Camera don't work (Invizimals)

### ISSUE THREAD

**Issue by Abi148** [hrydgard/ppsspp#12195] opened 2019-07-26 12:36 UTC
### What happens?
The game gives way to the "supposed" camera of the device, but you can't see anything.
Although the emulator itself asks you for permission to use both camera and video.
![Screenshot_20190726-143059](https://user-images.githubusercontent.com/53340788/61951907-ae9bdb00-afb2-11e9-8f03-f69be282850b.png)

### What *should* happen?
When the camera starts you should see something.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Hello, my name is Gabriel and I am using a Xiamoi MiA1, Android 9 with PPSSPP 1.8 version.
Im try to play Invizimals in the emulator but the Camera don't work.

**Comment by unknownbrackets** [comment] 2019-07-27 13:21
This issue is being closed as a duplicate of #8521.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-07-27 13:21 UTC
