### ISSUE TITLE
PPSSPP crashes when trying to play burnout legends on ios

### ISSUE THREAD

**Issue by Stevie-T** [hrydgard/ppsspp#14559] opened 2021-06-24 08:50 UTC
### What happens?
Burnout legends crashes PPSSPP when I try to start a race. The game launches fine and I am able to navigate through the game menu. However, when I select 'start race' ppsspp force closes and I land up on the ios homescreen.

#### What hardware / device and operating system?
iPhone on ios 14.5

#### What PPSSPP version (standalone/official), and did it work before?
build version - v1.11.3-634-ge7253ddf1
Has never worked before

#### Which game or games?
Burnout legends

**Comment by Panderner** [comment] 2021-06-24 09:07
Are you using IR Interpreter?

**Comment by Stevie-T** [comment] 2021-06-24 09:09
Yes, I am. Forgot to mention that.

**Comment by Gamemulatorer** [comment] 2021-06-24 09:11
Another related/duplicate issue of https://github.com/hrydgard/ppsspp/issues/14196

**Comment by Stevie-T** [comment] 2021-08-03 15:56
Update: Ran this game on an android device as well in IR Interpreter mode. Force closes there as well. Works fine when JIT is enabled.

**Comment by Gamemulatorer** [comment] 2021-09-15 08:58
I can also reproduce this but it didn't crash but stuck up on this images.

![Screenshot_2021-09-15-16-53-25-339_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133403294-c9a2e1a4-7b3d-4f06-ad7b-65d31abc2ed5.jpg)

![Screenshot_2021-09-15-16-54-39-991_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/133403278-977bc0de-e95d-4e6f-87c8-eaf251221407.jpg)

### Dump
[burnout_legend.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7168505/burnout_legend.ppdmp.zip)
### Logs
[logcat_09-15-2021_16-54-23.txt](https://github.com/hrydgard/ppsspp/files/7168518/logcat_09-15-2021_16-54-23.txt)

**Comment by Gamemulatorer** [comment] 2021-10-01 16:02
I think this is really a duplicate of https://github.com/hrydgard/ppsspp/issues/11169

**Comment by Gamemulatorer** [comment] 2022-07-22 06:08
This should be fixed now https://github.com/hrydgard/ppsspp/pull/15713

**Closed** 2022-07-22 14:04 UTC
Labels: IRInterpreter
