### ISSUE TITLE
Armored Core 3 Portable Hangs, "[Nature Area] Prevent Capsule Theft"

### ISSUE THREAD

**Issue by stonelike** [hrydgard/ppsspp#12128] opened 2019-06-24 02:53 UTC
### What happens?
I am using the "Hang cheat" fix found in the AC forum community.  The game has mostly performed flawlessly, with the exception of this one mission, "Prevent Capsule Theft".  On starting the mission, as the blue mission details loading screen appears and starts filling in, the game partially hangs, although the emulator does not crash outright.  Ocean/environmental sound effects can be heard, but the graphics are frozen and no further interaction seems possible.

I have disabled all emulator tweak settings which might cause emulator instability, but the behavior remains unchanged after multiple settings tweaks and attempts.  Notably, this appears to be the only mission/level I have encountered in the entire game so far which displays this behavior.

### What *should* happen?

The mission "Prevent Capsule Theft" should load and run normally, like every other mission in the game.  It is unclear why this one mission is not working while all others work without problems.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Lenovo x140e laptop.  Arch Linux, linux kernel 5.2.  Using Lutris as a configuration/install wrapper.  PPSSPP version 1.3-146-g9c08b60.

Thank you all for your work.  I have been very impressed with how well this emulator performs on my system, and find it comfortable to use.

**Comment by stonelike** [comment] 2019-06-24 02:57
After some more looking through existing issue threads I see a reference to some other related issues in the AC Portable line.

https://github.com/hrydgard/ppsspp/issues/5999#issuecomment-89251889

I can also confirm that the "Elephant" Mission hang also still occurs for me with the same setup in AC: Silent Line as well.

**Comment by stonelike** [comment] 2019-06-24 03:18
EDIT: I am realizing now that Lutris seems to be using a very outdated version of PPSSPP, so I am unsure of whether this issue still remains in the latest version.  I will attempt to upgrade my installed version and see if that fixes things.

**Comment by stonelike** [comment] 2019-06-24 03:40
UPDATE: Now using PPSSPP v1.7.5-403-g128c0ad, and similar settings to before, the behavior is slightly improved; the hang now still occurs, but now at least the freeze only happens right after the start of the level (the level seems to have loaded correctly before it froze).

**Comment by stonelike** [comment] 2019-06-24 03:44
Mission "Elephant" in AC:SL Portable also hangs in a similar way still with the updated version as well.

**Comment by unknownbrackets** [comment] 2019-06-24 04:05
It's sounding like this might ultimately be a duplicate of #5999?

-[Unknown]

**Comment by stonelike** [comment] 2019-06-30 06:58
I'd assume so, having read through those threads.  In the one frame of the "recover capsules" level that loads, there is seemingly a significant lens flare effect.  It could be insta-crashing on level load due to the starting angle of the player's viewpoint relative to the skybox.

The other crash in the Arena level I mention is an indoor area with no lens flare, though, that I could see.  Seems like it crashes when a particular part of an animated texture comes onscreen though it I had to guess (the level wall is stylized after an endlessly lowering elevator platform).

**Comment by hrydgard** [comment] 2019-08-06 22:23
How is this now? If you turn off the hang cheat?

**Comment by unknownbrackets** [comment] 2020-01-01 03:16
There's a good chance we fixed this, but it's been a while and we haven't gotten any feedback - I'm going to close it assuming it was fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Closed by unknownbrackets** 2020-01-01 03:16 UTC
Labels: No Feedback / Outdated?
