### ISSUE TITLE
Project Diva Extend: Stargazer is way out of sync

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#8660] opened 2016-03-22 12:54 UTC
I thought something was wrong with the game but it seems the emulator itself is making huge desyncs with the buttons on screen and the song itself making it unplayable. The huge delay is only in the song Stargazer.

https://www.youtube.com/watch?v=iQC67NereT4&feature=youtu.be

**Comment by leopard20** [comment] 2018-06-10 11:12
@hrydgard @unknownbrackets 
First of all it's a duplicate of other input lag issues.
Second of all, there's no such issue to begin with!

Guess I should've said the second one first! :)

**Comment by unknownbrackets** [comment] 2022-11-21 00:20
I'm going to close this based on the above comment.  Maybe the game can be patched via rom hacking or something to make the targets on this song more reasonable.

-[Unknown]

**Closed by unknownbrackets** 2022-11-21 00:20 UTC
