### ISSUE TITLE
Need For Speed: Shift start animation error

### ISSUE THREAD

**Issue by iamqk** [hrydgard/ppsspp#15605] opened 2022-06-17 11:37 UTC
### Game or games this happens in

Need For Speed: Shift

### What area of the game / PPSSPP

Before start get into game, game start animation

### What should happen

there are a lot texture error. I use the same setting test other version, confirmed from release v1.11 the error start. I found this issue is because I play in openemu the same game, and they use release v1.10.3 as a base version, their version don't have this issue, so I dig out. I also compile and test other version, it seemed come from  v1.11 to newest code.
<img width="1072" alt="截屏2022-06-17 19 36 00" src="https://user-images.githubusercontent.com/281031/174290976-323c3a2d-e02f-49c5-bb77-555d8ac834eb.png">

### Logs

none

### Platform

macOS

### Mobile phone model or graphics card

MBP 2015 M370X

### PPSSPP version affected

release v1.11-76a568a and after

### Last working version

release v1.10.3-087de84

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [x] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment] 2022-06-18 01:10
Between release v1.0.3 and release v1.11 there are many commits, it would be nice if you can bisect them to shorten the gap https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game

And, apparently the buildbot didn't have any records of the changes between them either https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by iamqk** [comment] 2022-06-18 10:21
> Between release v1.0.3 and release v1.11 there could be too many commits, it would be nice if you can bisect them to shorten the gap https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game
> 
> And, apparently the buildbot didn't have any records of the changes between them either https://buildbot.orphis.net/ppsspp/index.php?m=fulllist
> 
> Okay, these are probably the changes [v1.10.3...v1.11](https://github.com/hrydgard/ppsspp/compare/v1.10.3...v1.11) certainly will need to be biscted

0b64d58c7d03cf23e2c689932a78fdbc3ed2f0ef is the first bad commit
commit 0b64d58c7d03cf23e2c689932a78fdbc3ed2f0ef
Author: shenweip <1037567878@qq.com>
Date:   Wed Nov 18 10:59:45 2020 +0800

    Fix mistake.

 Core/HLE/sceMpeg.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)


PS：errors may not blue screen as I post above, but still some errors on animations

**Comment by Gamemulatorer** [comment] 2022-07-23 11:32
How about this now?

**Comment by Gamemulatorer** [comment] 2022-07-23 11:34
Ok, this a duplicate of https://github.com/hrydgard/ppsspp/issues/14645

**Comment by hrydgard** [comment] 2022-07-23 11:47
OK, closing as duplicate.

**Closed by hrydgard** 2022-07-23 11:47 UTC

**Comment by DavidAriyan** [comment] 2024-10-05 18:06
This still happening on newest android build I got from PPSSPP website. I thought the Rom is bad at first.

**Comment by anr2me** [comment] 2024-10-06 01:29
Because it's not fixed yet, since this issue is a duplicate of existing issue at https://github.com/hrydgard/ppsspp/issues/14645 you'll need to wait until that issue to be fixed.
