### ISSUE TITLE
Mouse scroll doesn't work in PPSSPP menus (regression)

### ISSUE THREAD

**Issue by JimsAlliance** [hrydgard/ppsspp#12156] opened 2019-07-06 14:20 UTC
Mouse scrolling in the PPSSPP menus no longer works as of the merger of pull request #12110 (ppsspp-v1.8.0-298).

There is no issue in ppsspp-v1.8.0-296.
I used the default settings of the builds in question.
OS: Windows

**Comment by LunaMoo** [comment] 2019-07-06 16:09
Which menus? It works fine here in settings and all game's lists.

**Comment by unknownbrackets** [comment] 2019-07-07 05:01
It's still working for me too, but then I don't have anything mapped to scroll wheel / mouse.

I will say, I've seen focus issues before where it doesn't work, and only starts working if I focus something else and focus back.  I think it's a bug, but it only happens rarely (for me, at least) and I haven't figured out the reproduction case.

-[Unknown]

**Comment by LPatamon** [comment] 2019-07-21 10:07
I can confirm scrolling with mouse wheel doesn't works for me.  I'm using v1.8.0-433-g37a97e741 x86 on Windows 7 Ultimate 32 bits.

I would need to check on which versions it still worked though.

**Comment by LunaMoo** [comment] 2019-07-22 02:45
So this might be limited to ancient windows version, either way there are only 2 things which changed that could be causing it:
 - moving mouse wheel event from to WndProc to DisplayProc, it had a comment "// For some reason, need to catch this here rather than in DisplayProc.", but it didn't specified why and was working fine in DisplayProc where it fits better,
 - releasing wheel with a delay - this has to stay as games can't see input pressed if it's de-pressed instantly, but if it causes mouse wheel events to fail on outdated OS, it might be reverted for UI and just left wheel not working in-game for people with old pc's.

 I think the first one is more probable so I'll leave it here:
https://github.com/hrydgard/ppsspp/compare/master...LunaMoo:oldWinWorkaroundTest?expand=1
Should be tested first as it still could be the other thing.

**Comment by vnctdj** [comment] 2019-07-28 14:28
For what it's worth, I can't reproduce the issue on Linux.

**Comment by sum2012** [comment] 2019-07-30 21:17
@LunaMoo  your change don't work for me for windows 7 64 bit

**Comment by LunaMoo** [comment] 2019-07-30 22:54
Try this one then https://github.com/hrydgard/ppsspp/compare/master...LunaMoo:oldWinWorkaroundTest2?expand=1

It instantly releases wheel in the UI only, also removes an unnecessary bool which really was just a leftover from previously tested code;p. Mouse Wheel was never working in-game before adding a release with a delay, so no changes there.

**Comment by LPatamon** [comment] 2019-07-30 23:52
I think I'm starting to see why the mouse wheel isn't working. I noticed that the UI uses the same control mapping you have configured, I mean the UI behaves like if you're using a real PSP, you move with the arrows to select the game you want to play, and you use the key you have assigned as the X button of the PSP to start the game. 

I think that is the reason why the mouse wheel isn't working. the emulator is seeing everything as if it was an in game UI or PSP UI and thus blocks the mouse wheel.

**Comment by sum2012** [comment] 2019-07-31 06:26
@LunaMoo your second change don't work

**Comment by LunaMoo** [comment] 2019-07-31 07:10
@LPatamon nothing blocks the mouse wheel, it's mapped input is ignored in the UI. Also it works perfectly fine on modern windows versions.

 As noted earlier there were only 2 things that changed so with them reverted not helping as sum2012 tested, I have absolutely no clue what would cause this, maybe some random compiler issue affecting only old windows.

**Comment by sum2012** [comment] 2019-07-31 07:59
@LunaMoo  before #12110  WM_MOUSEWHEEL 's code is active when mouse scroll
after merge, WM_MOUSEWHEEL 's code is NOT active when mouse scroll.

**Comment by LunaMoo** [comment] 2019-07-31 08:48
@sum2012 except you tested 2 things that reverted those changes for UI and as you said neither helped which doesn't really have any sense as long as you tested correctly;p.

**Comment by LPatamon** [comment] 2019-07-31 10:47
> 
> 
> @LPatamon nothing blocks the mouse wheel, it's mapped input is ignored in the UI. Also it works perfectly fine on modern windows versions.
> 
> As noted earlier there were only 2 things that changed so with them reverted not helping as sum2012 tested, I have absolutely no clue what would cause this, maybe some random compiler issue affecting only old windows.

Well I downloaded your ppsspp wheel on outdated win tests 32 bit file and tested the .exe combining the two test and the mouse wheel works on it without problem.

I think that since Windows 8 and 10 are way different to Windows 7 on many ways, that also may have be the case for how Win 8 and 10 work with the mouse wheel. I really don't know. All I know is that it was a really odd issue

**Comment by LunaMoo** [comment] 2019-07-31 10:50
So neither test 1 or 2 helped separately? Only when they are combined? Weird.

**Comment by LPatamon** [comment] 2019-07-31 10:55
> 
> 
> So neither test 1 or 2 helped separately? Only when they are combined? Weird.

No, no. I haven't tested them separately yet, let me check those. I simply grabbed the exe with the two tests combined to try first n.nU

Edit: tested test 1 and test 2 exe files. only test 1 one worked. On the Test 2 one the wheel didn't work at all.

**Comment by LunaMoo** [comment] 2019-07-31 10:58
Ah ok then, that's pretty much best case as if it required both or test 2, win 7 users would be left without being able to use mouse wheel in-game. I'll make some comment changes and open a PR with a fix for this in a bit.

**Comment by LPatamon** [comment] 2019-07-31 11:02
> 
> 
> Ah ok then, that's pretty much best case as if it required both or test 2, win 7 users would be left without being able to use mouse wheel in-game. I'll make some comment changes and open a PR with a fix for this in a bit.

Very well. Also Thank you very much for all you're doing to get this issue fixed. It is really appreciated :)

Also on PPSSPPWindows test combine 1 and 2.exe the wheel works. I guess it is because it has the test 1 workaround in it and didn't got affected to be combined with test 2.

So to put it short:

PPSSPPWindows test 1.exe = Wheel works
PPSSPPWindows test 2.exe = Wheel doesn't work
PPSSPPWindows test combine 1 and 2.exe = Wheel works

**Comment by LunaMoo** [comment] 2019-07-31 11:14
BTW if you use mouse control can you map mouse movement(by using "M" instead of "+" in control mapping screen) and does it work in-game? Doesn't matter what ppsspp build for that, just curious because all other mouse events are in DisplayProc ~ the same function where mouse wheel doesn't work on Win 7.

**Closed** 2019-07-31 11:33 UTC
Labels: Input/Controller

**Comment by LPatamon** [comment] 2019-07-31 23:57
> 
> 
> BTW if you use mouse control can you map mouse movement(by using "M" instead of "+" in control mapping screen) and does it work in-game? Doesn't matter what ppsspp build for that, just curious because all other mouse events are in DisplayProc ~ the same function where mouse wheel doesn't work on Win 7.

Just checked that on PPSSPPWindows test 1.exe and you can map the mouse wheel if you enable mouse control. This wasn't working on other builds like v1.8.0-446-g61c9d2258

I did think on the mapping thing and enabled mouse control on previous builds and the only thing I wasn't able to map, was the mouse wheel. You could map everything else from the mouse like moving it up, down, left and right to map the respective in-game control, map the buttons, but the wheel wasn't recognized so you couldn't set it to do anything in game.

But on PPSSPPWindows test 1.exe the wheel is now recognized and gets mapped correctly
