### ISSUE TITLE
Gladiator Begins: Menu text is cut off

### ISSUE THREAD

**Issue by saintschultz** [hrydgard/ppsspp#9141] opened 2016-12-02 21:36 UTC
When navigating the armory and arena menus, certain text is cut off and/or won't fit in its margins.

![screenshot 2016-12-02 15 28 09](https://cloud.githubusercontent.com/assets/12510825/20851277/178839cc-b8a5-11e6-9c7b-e3acf0fba251.png)
![screenshot 2016-12-02 15 28 26](https://cloud.githubusercontent.com/assets/12510825/20851278/17b73bb4-b8a5-11e6-8745-3de09b835be0.png)

**Comment by hrydgard** [comment] 2016-12-02 21:43
Likely to be yet another problem where our replacement font doesn't match the real one, and thus a dupe of #2788. 

Have you tried with the real font file dumped from a PSP, as mentioned in that issue? Should really make a tutorial about that..

**Comment by saintschultz** [comment] 2016-12-02 23:13
Ah, I see. Thanks for that suggestion - I used the fonts from the link provided in the wiki. Fixed!

**Comment by hrydgard** [comment] 2016-12-03 00:24
Alrighty, closing this as dupe of #2788 then.

**Closed by hrydgard** 2016-12-03 00:24 UTC
