### ISSUE TITLE
Darkstalkers Chronicle no sprites visible

### ISSUE THREAD

**Issue by DarkD** [hrydgard/ppsspp#8585] opened 2016-02-13 09:36 UTC
Game is Darkstalkers Chronicle - The Chaos Tower ULUS10005.
That's how it looks:
![ulus10005_00000](https://cloud.githubusercontent.com/assets/6061259/13026952/f1c883fc-d24c-11e5-848a-475d8435d5a8.jpg)
![ulus10005_00001](https://cloud.githubusercontent.com/assets/6061259/13026951/f1befae4-d24c-11e5-8086-9015f2a6caec.jpg)
![ulus10005_00002](https://cloud.githubusercontent.com/assets/6061259/13026950/f1ba226c-d24c-11e5-9283-4b57ef948737.jpg)
On Software rendering it looks like this:
![ulus10005_00003](https://cloud.githubusercontent.com/assets/6061259/13026955/14f159e4-d24d-11e5-8f2f-bcea44195b44.jpg)
![ulus10005_00004](https://cloud.githubusercontent.com/assets/6061259/13026953/14d5907e-d24d-11e5-91bb-ec934453a9b8.jpg)
![ulus10005_00005](https://cloud.githubusercontent.com/assets/6061259/13026954/14dbdf56-d24d-11e5-9616-7b1c06270c80.jpg)
(last screenshot with different stage, but that's not the point - no characters and lifebars is the point)
Forwarding your question - nay, it never worked nor on OGL, nor on DX9 backend previously. Just in case I've tried adding it VertexDepthRounding, PixelDepthRounding and DepthRangeHack and it was fruitless.

**Comment by hrydgard** [comment] 2016-02-13 10:03
Already reported, duplicate of #6647

**Closed by hrydgard** 2016-02-13 10:03 UTC

**Comment by DarkD** [comment] 2016-02-13 10:25
Damnation! I've thought it was reported somewhere, but than today I specifically looked for it, entered "darkstalkers", "dark stalkers", "chronicle" in search field than in issues in filter field and surprised by zero results added it here... What magic it was? O.o
