### ISSUE TITLE
Secret Agent Clank: Light bleeding through walls

### ISSUE THREAD

**Issue by Radu13** [hrydgard/ppsspp#11486] opened 2018-10-22 22:43 UTC
Looks like another depth issue, it happens with smoke, nanotech and other things.

Texture L0: 0x04154000 (256x128)
i post the screenshots below
![clank](https://user-images.githubusercontent.com/25487544/47323541-85819f00-d65c-11e8-9a8f-f01ee80c8920.PNG)
![clank1](https://user-images.githubusercontent.com/25487544/47323542-85819f00-d65c-11e8-809d-8f1458eb6839.PNG)

**Comment by unknownbrackets** [comment] 2018-10-22 22:55
This issue is being closed as a duplicate of #6105.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2018-10-22 22:55 UTC
