### ISSUE TITLE
[Feature Request] Modifying sounds in the game

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10768] opened 2018-03-23 03:05 UTC
Since textures can be modified in the game, how about modifying sounds to add more entertainment in the game. Is it possible or difficult to make?

**Comment by Rokkest** [comment] 2018-03-23 14:26
for sound try search/ask for patch like japanes clean speak & pes mod thats need open ur .iso on some modifer games

**Comment by LunaMoo** [comment] 2018-03-23 14:59
Closing as a duplicate of #10640, also see [this thread to see why it might not happen.](https://forums.ppsspp.org/showthread.php?tid=19289)

**Closed by LunaMoo** 2018-03-23 14:59 UTC
