### ISSUE TITLE
Crash at a specific spot: syphon filter logan's shadow

### ISSUE THREAD

**Issue by murtisoft** [hrydgard/ppsspp#13352] opened 2020-08-29 14:49 UTC
Hello
I have crashes at a specific spot while playing syphon filter logan's shadow.(UCUS98606)
I have tried all 4 renderers, turning off hacks, restarting the mission & restarting from a checkpoint.

- OS: Windows 7 x64 
- CPU: AMD Phenom x6 1100T
- GPU: Geforce GTX 750Ti
- PPSSPP: 1.10.3

Video:
There are two barricades side by side, ordering the tank to shoot the left one, causes the crash. Both shown in the video.
https://www.youtube.com/watch?v=Q-tP7BAPiOA

Someone was stuck at the same place, but the thread was locked since the op did not give enough feedback.
https://github.com/hrydgard/ppsspp/issues/10415

SaveState if you would like to try for yourself:
https://drive.google.com/file/d/10qP6OGSJeWJNa1f1KcQeq0cnVJJW6htr/view?usp=sharing

_PS. Can someone guide me as how to get a log out of the emulator? The forum post from 2013 didnt help._

**Comment by Gamemulatorer** [comment] 2020-08-29 22:36
duplicate of #10415

**Comment by murtisoft** [comment] 2020-08-29 23:03
I read that thread, issue wasnt resolved, and also mentioned it in op.

**Comment by unknownbrackets** [comment] 2020-08-29 23:21
This issue is being closed as a duplicate of #10415.

Can you post savedata (not a save state - save states save even bugs - they save eveything) in that other issue?  It's not locked, it's just waiting for someone to help us move it forward.  Sounds like you may be that someone.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2020-08-29 23:21 UTC

**Comment by murtisoft** [comment] 2020-08-30 00:42
My bad, thanks for the patience.
