### ISSUE TITLE
Android: Texture Replacement not working (should warn about '\' in paths)

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11081] opened 2018-05-27 06:29 UTC
I can't exactly tell what is the problem, as I am not the one facing it(mostly for not using PPSSPP on Android), but I have seen several people, including [this guy](https://forums.ppsspp.org/showthread.php?tid=24126&pid=131301#pid131301), have been facing problems regarding loading my [texture pack](https://forums.ppsspp.org/showthread.php?tid=24126), which seems to be the only one having trouble of doing such, but what is more weird, is that this only happens on Android, and not Windows. I believe anyone can reproduce this.

**Comment by unknownbrackets** [comment] 2018-05-27 06:34
There was a bug with the texture replacement hash in 1.5.4.  It's fixed in 1.6.0 and recent git builds.

Is the affected Android version 1.5.4?

-[Unknown]

**Comment by Saramagrean** [comment] 2018-05-27 10:44
I think, I found the cause of this problem. When edit the symbol from "\" to "/", in texture.ini file, the texture is work on android.

Before (use " \ ")
![33601906_696411427356788_4114351362718826496_n](https://user-images.githubusercontent.com/26355472/40584994-527c5a24-61d5-11e8-92f3-93135cef8e7d.jpg)

After (use " / ")
![33776000_696411410690123_5206692387975331840_n](https://user-images.githubusercontent.com/26355472/40585005-6fa46c22-61d5-11e8-8b2e-95f1a3fb241a.jpg)

**Comment by unknownbrackets** [comment] 2018-05-27 14:51
Oh, you can't use Windows style \ slashes in the ini file, always use / which will work on all platforms.

I guess we could alert about this when someone is on Windows and we see \...

-[Unknown]

**Comment by AkiraJkr** [comment] 2018-05-27 15:05
Well, maybe there could be a way to auto-convert in the go to /, so no one in the future would suffer from such a mistake like that? But well, since I know it won't fixed right now, I'll make the change for now., specially since I know people with older versions will report this issue.

**Comment by unknownbrackets** [comment] 2018-05-27 15:18
Well, \ can appear in Linux paths.  While Windows is popular, it can be surprising for non-Windows people when weird Windows rules suddenly pop up and start applying to them when they are not on Windows.

Another example is case sensitivity.  On Windows, "MY\HeLlO.pNg" will find a file named "My/Hello.png".  On Linux, it won't - because there, it's possible for "Hello.png" and "HeLlO.pNg" to exist in the same folder.  It's complex and annoying to deal with this at the application level, and forcing Linux people to only use lowercase makes people grumpy too.

The simpler thing is probably to show a message on Windows when something looks wrong.  For example, we could check if the filename case matches exactly too.  That way you wouldn't get surprises on other platforms.

Windows also has [ADS](http://techgenix.com/alternate_data_streams/), which could silently cause issues if you use `:` in filenames.  This is more likely to be an issue if a Linux user is creating textures, since many Windows programs will complain if you put a `:` in a filename.  So we should probably show a message to Linux users when textures contain any of a short list of special characters in them too.

-[Unknown]

**Comment by hrydgard** [comment] 2018-05-27 19:33
This is now a feature request for warning about '\' characters in paths.

**Comment by LunaMoo** [comment] 2018-05-27 23:58
Unknown just explained that \ can be in linux path;p so for example fonts/ming\hd.png would be a valid path to the "ming\hd.png" file inside a "fonts" folder, if all \ were replaced by / it would no longer work so that shouldn't be done;p.

 Warning message itself feels bad as well, because it's either a message to windows users as a reminder that non windows OS exist, which many windows users don't care about and might want to keep their "\" or a message to linux users that their paths might be incorrect if the texture pack was created on windows which they also might not care about as linux vs windows for some people have way too serious meaning.
 I would propose to instead simply add a note that says:
````
 # Please avoid using "\" in path/filename for compatibility on various OS's, see #11081 for details.
````
or something similar to the default ini file created from ui;p.

 Also "manually fixing" ini file is not an headache, it literally takes 2 seconds to fix a very long file with lots of "\" entries by using replace all function of any even most basic(ie notepad) text editor;p.

**Comment by AkiraJkr** [comment] 2018-05-28 01:48
No, I don't mean that it's a hard task, of course it is very easy, specially with Notepad++, just select all '\' and replace with '/', but I mean that by very casual people, users who don't even mess around with emulator settings, or the folder, they just are there to play on convenience, and don't even know what a .ini is. That simply got everything set up by a friend or familiar.

**Comment by unknownbrackets** [comment] 2018-05-28 02:00
I guess I'm making the possibly mistaken assumption that people who create texture packs test them before releasing them to the masses, and therefore would see such warnings.  I'm not against adding the message to the ini - it might be worth mentioning special characters, e.g.:

```
# If you want your textures to work on mobile and other devices (see #11081):
#  - Always use lowercase for filenames (scenery/water.png not SCENERY/Water.png)
#  - Use / for folders, not \ which won't work everywhere.
#  - Avoid special characters, except spaces, underscores, and dashes.
```

If this seems like a huge hassle, someone could probably write a Windows program that would take a texture directory and "fix" it by stripping special characters, lowercasing, and replacing \ with / for you and then zipping it up.

But I would argue that shouldn't be in PPSSPP.  I mean sure, it's kinda an operating system, but not really.  Maybe it sounds like a great idea if PPSSPP manages your network webcam devices and runs your antivirus software too, but it's really best if it keeps to its goal: emulating PSP games, and doing so fast and as accurately as possible.

-[Unknown]

**Closed** 2018-10-04 05:47 UTC
Labels: Feature Request
