### ISSUE TITLE
“Blue Screen” on start of PPSSPP

### ISSUE THREAD

**Issue by tankcsgo** [hrydgard/ppsspp#11962] opened 2019-04-06 01:18 UTC
### What happens?
I tried to play Naruto games. I passed through the “save game creation” part but it got black screen right after.
I re-installed ppsspp and it just got the whole blue screen and didnt work at all

### What *should* happen?
Well, it should work properly when i reinstall it?
Whatsoever:/

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I’m on iPad Pro with ios 12.0
I installed the latest-dev version on cydia repo.

**Comment by tankcsgo** [comment] 2019-04-06 04:06
@hrydgard please fix it. Thanks

**Comment by unknownbrackets** [comment] 2019-04-08 04:55
Sounds like this is just a duplicate of #9186.

-[Unknown]

**Comment by hrydgard** [comment] 2019-04-08 07:17
The blue screen part surely is, the black screen in Naruto might not be - although those games are supposed to work. If that turns out to be a real issue, please open a new issue with that one separately.

**Closed by hrydgard** 2019-04-08 07:17 UTC
Labels: Platform-specific (iOS)
