### ISSUE TITLE
Escape menu cannot properly show pause menu (it is shown and then closes)

### ISSUE THREAD

**Issue by neoh4x0r** [hrydgard/ppsspp#9421] opened 2017-03-13 16:07 UTC
The escape key can be bound under Settings->Controls->Pause (this is the default)

However escape is internally bound to menu exit (to go back to the last menu) -- this is not exposed through the control scheme.

When escape is pressed the pause will will appear and then immediately disappear.

Pause can be bound to any keyboard key/gamepad button other than escape -- and the issue does not occur.

The default binding for pause should be set to something other then escape.

**Comment by LunaMoo** [comment] 2017-03-13 18:41
The only bad thing about pause button I can find is that when user removes all mapping for it, they can't exit the game(on platforms other than windows which can do it from windows menu/hotkey) without closing ppsspp until they map some button again.

 Nothing bad happens with esc being mapped as default here and since there's no "back" functionality that could be triggered from in-game and cause instant return from "pause" the situation as described in here can't really happen, unless you hold the button instead of pressing it or have some hardware problems which doesn't pass the input correctly. Possibly caused by third party software messing with input as well.

 Either way remapping the defaults for everyone that got used to it and works properly for is really not an acceptable solution for one user issue.

**Comment by unknownbrackets** [comment] 2017-03-13 23:26
I think we should wait for a release of Esc before returning back to the game, ideally, to require two presses.  Holding down ideally shouldn't swap back and forth.

Maybe it's some weird repeat rate issue here.

-[Unknown]

**Comment by neoh4x0r** [comment] 2017-03-14 02:23
@LunaMoo 
@unknownbrackets 
I am pressing the button and not holding it down and again ESC is the only button that causes this issue (if I remap pause to another button it works correctly) -- so I'm not sure if waiting for two button presses will make any difference.

**"the situation as described in here can't really happen"**.
I'm sorry but that statement does not appear to be valid in this case -- if it were impossible for it to happen then there would have been no issue to report.

I am running this on Debian/Stretch 9 amd64.

**Comment by unknownbrackets** [comment] 2017-03-14 02:48
SDL or Qt?  Maybe this is a Linux only problem, then.

-[Unknown]

**Comment by LunaMoo** [comment] 2017-03-14 02:50
Google for weird behaviour of escape key on debian first result brings "ESC key causes a small delay in terminal due to its Alt+ behavior" so basically when you press an esc key on that system it might be equivalent of holding that key on most other platforms.

**Comment by neoh4x0r** [comment] 2017-03-14 03:49
@LunaMoo 
Those issues only affect the terminal/vim and would not affect ppsspp.

I am using sdl and it may only affect linux users.

**Comment by LunaMoo** [comment] 2017-03-14 03:56
From my personal experience including sdl build on ubuntu there are no problems like that in ppsspp.
You're on desktop or laptop? Some of the latter might use esc as a switch for function keys which I'm guessing would also "keep it pressed". As that's really the only way I can reproduce such problem, by intentionally holding the key.

**Comment by neoh4x0r** [comment] 2017-03-14 04:20
@LunaMoo 
I'm on a desktop and no other programs are having issues with proper escape key handling (just this one).

--------------------------------------------------

The problem stems from the escape key being set as a hardcoded cancel key in Common/KeyMap.cpp::void UpdateNativeMenuKeys()

Notice this part: **const KeyDef hardcodedCancelKeys[] = { KeyDef(DEVICE_ID_KEYBOARD, NKCODE_ESCAPE),**

I removed this entry from the array and the problem went away.

Honestly I don't see the need to have these keys hard coded because properly setting up the key bindings on the control page should be enough.

Any key that is hard coded here cannot be overridden and will conflict with any duplicate key binding if they should be used.

--------------------------------------------------
Common/KeyMap.cpp::void UpdateNativeMenuKeys()
--------------------------------------------------
```
// TODO: This is such a mess...
void UpdateNativeMenuKeys() {
	std::vector<KeyDef> confirmKeys, cancelKeys;
	std::vector<KeyDef> tabLeft, tabRight;
	std::vector<KeyDef> upKeys, downKeys, leftKeys, rightKeys;

	int confirmKey = g_Config.iButtonPreference == PSP_SYSTEMPARAM_BUTTON_CROSS ? CTRL_CROSS : CTRL_CIRCLE;
	int cancelKey = g_Config.iButtonPreference == PSP_SYSTEMPARAM_BUTTON_CROSS ? CTRL_CIRCLE : CTRL_CROSS;

	KeyFromPspButton(confirmKey, &confirmKeys);
	KeyFromPspButton(cancelKey, &cancelKeys);
	KeyFromPspButton(CTRL_LTRIGGER, &tabLeft);
	KeyFromPspButton(CTRL_RTRIGGER, &tabRight);
	KeyFromPspButton(CTRL_UP, &upKeys);
	KeyFromPspButton(CTRL_DOWN, &downKeys);
	KeyFromPspButton(CTRL_LEFT, &leftKeys);
	KeyFromPspButton(CTRL_RIGHT, &rightKeys);

#ifdef __ANDROID__
	// Hardcode DPAD on Android
	upKeys.push_back(KeyDef(DEVICE_ID_ANY, NKCODE_DPAD_UP));
	downKeys.push_back(KeyDef(DEVICE_ID_ANY, NKCODE_DPAD_DOWN));
	leftKeys.push_back(KeyDef(DEVICE_ID_ANY, NKCODE_DPAD_LEFT));
	rightKeys.push_back(KeyDef(DEVICE_ID_ANY, NKCODE_DPAD_RIGHT));
#endif

	// Push several hard-coded keys before submitting to native.
	const KeyDef hardcodedConfirmKeys[] = {
		KeyDef(DEVICE_ID_KEYBOARD, NKCODE_SPACE),
		KeyDef(DEVICE_ID_KEYBOARD, NKCODE_ENTER),
		KeyDef(DEVICE_ID_ANY, NKCODE_BUTTON_A),
	};

	// If they're not already bound, add them in.
	for (size_t i = 0; i < ARRAY_SIZE(hardcodedConfirmKeys); i++) {
		if (std::find(confirmKeys.begin(), confirmKeys.end(), hardcodedConfirmKeys[i]) == confirmKeys.end())
			confirmKeys.push_back(hardcodedConfirmKeys[i]);
	}

	const KeyDef hardcodedCancelKeys[] = {
		KeyDef(DEVICE_ID_KEYBOARD, NKCODE_ESCAPE),
		KeyDef(DEVICE_ID_ANY, NKCODE_BACK),
		KeyDef(DEVICE_ID_ANY, NKCODE_BUTTON_B),
	};

	for (size_t i = 0; i < ARRAY_SIZE(hardcodedCancelKeys); i++) {
		if (std::find(cancelKeys.begin(), cancelKeys.end(), hardcodedCancelKeys[i]) == cancelKeys.end())
			cancelKeys.push_back(hardcodedCancelKeys[i]);
	}

	SetDPadKeys(upKeys, downKeys, leftKeys, rightKeys);
	SetConfirmCancelKeys(confirmKeys, cancelKeys);
	SetTabLeftRightKeys(tabLeft, tabRight);
}
```

**Comment by unknownbrackets** [comment] 2017-03-14 05:24
The reason that it's hardcoded there is to theoretically prevent you from "trapping yourself" when configuring the mapping.  It's been proposed to remove this, but right now, that's why it's there.

But, that's not actually your problem.  See, what's supposed to happen is:

1. You tap Esc.
2. EmuScreen detects this [Back button] (https://github.com/hrydgard/ppsspp/blob/56e0d5ece2ea58b75b965d30b509c075f33122d5/UI/EmuScreen.cpp#L597) or [Pause keypress] (https://github.com/hrydgard/ppsspp/blob/56e0d5ece2ea58b75b965d30b509c075f33122d5/UI/EmuScreen.cpp#L424).
3. [`releaseButtons()`] (https://github.com/hrydgard/ppsspp/blob/56e0d5ece2ea58b75b965d30b509c075f33122d5/UI/EmuScreen.cpp#L882) is called, in case you're holding any other buttons down.  Maybe this is part of the problem.
4. The pause screen is shown.
5. If and when you tap Esc a second time (after releasing it), you [leave the dialog] (https://github.com/hrydgard/ppsspp/blob/fb0b82f6e8087f9b0eaf2ff07df3d92eb53fd648/ext/native/ui/ui_screen.cpp#L127).  All dialogs, including the pause screen, behave this way.

So, what's happening for you is that `key()` is being triggered on the pause screen as if you pressed Esc again.  To me, it looks like `releaseButtons()` is likely the problem here.

Does your change if you make the cancel key and the pause screen trigger button the same (i.e. both Esc)?  Because that is supposed to work.  If that doesn't work, there's still a bug, no matter what other workaround is applied.

-[Unknown]

**Comment by neoh4x0r** [comment] 2017-03-14 13:17
@unknownbrackets 
Yes it seems to record two button down events....I'm looking at ways to eliminate the double key down event.

Also if I make this change to keyMap.cpp:

```
const KeyDef hardcodedCancelKeys[] = {
	//KeyDef(DEVICE_ID_KEYBOARD, NKCODE_ESCAPE),
	KeyDef(DEVICE_ID_ANY, NKCODE_BACK),
	KeyDef(DEVICE_ID_ANY, NKCODE_BUTTON_B),
};
```
And set the pause button to Esc it works correctly.

**The reason that it's hardcoded there is to theoretically prevent you from "trapping yourself" when configuring the mapping.** 

I don't know if that is needed since there is a cancel button that can be pressed to get out of key mapping and most menu screens have a 'Back' button.

**Comment by unknownbrackets** [comment] 2017-03-14 14:34
Nicely investigated.  Hmm, what we could do is (PCMain.cpp):

```c++
key.flags = KEY_DOWN | (event.key.repeat ? KEY_IS_REPEAT : 0);
```

And then maybe change this part (ui_screen.cpp):

```c++
if (!retval && (key.flags & KEY_DOWN) && UI::IsEscapeKey(key)) {
```

To perhaps:

```c++
if (!retval && (key.flags & (KEY_DOWN | KEY_IS_REPEAT)) == KEY_DOWN && UI::IsEscapeKey(key)) {
```

Which would ensure that repeats are ignored for leaving dialogs (this seems to make more sense to me anyway.)

The main place we *might* want repeats is when typing into fields - there aren't many, but there are a couple in settings, mostly related to network.  But maybe indeed it might be better to just ignore repeats, especially if sometimes it sends them very soon.

-[Unknown]

**Comment by neoh4x0r** [comment] 2017-03-14 16:41
@unknownbrackets 
But like I mentioned only doing this for the ESC key means that things like fullscreen toggle will not work and any button press will be duplicated.

I really don't see this affecting text input, since once SDL_TEXTINPUT is sent a flag could be set and any SDL_KEYDOWN / SDL_KEYUP events can be ignored by checking if textinput is active.

**Comment by unknownbrackets** [comment] 2017-03-15 03:42
You're right, we should just ignore the repeats.  Want to PR?

Hmm, the missing text input sounds like an oversight.  Looks like the issue is here:
https://github.com/hrydgard/ppsspp/blob/b9a9a509ae2dacee42251b5efc4983214a2b174b/UI/GameSettingsScreen.cpp#L587
https://github.com/hrydgard/ppsspp/blob/b9a9a509ae2dacee42251b5efc4983214a2b174b/UI/GameSettingsScreen.cpp#L728

Which should probably better be `#if !defined(MOBILE_DEVICE) && !defined(USING_QT_UI)`, since apparently Qt doesn't support KEY_CHAR either right now.  I guess that'd be better for Windows Mobile too, @hrydgard - assuming that sets MOBILE_DEVICE.

-[Unknown]

**Comment by neoh4x0r** [comment] 2017-03-15 15:32
@unknownbrackets 
Yeah PR'ing this sounds good

**Comment by neoh4x0r** [comment] 2017-03-22 20:23
@unknownbrackets 

Here's the git diff:
```
diff --git a/ext/native/base/PCMain.cpp b/ext/native/base/PCMain.cpp
index a7a676f05..256bcd1b2 100644
--- a/ext/native/base/PCMain.cpp
+++ b/ext/native/base/PCMain.cpp
@@ -734,6 +734,7 @@ int main(int argc, char *argv[]) {
 #endif
                        case SDL_KEYDOWN:
                                {
+                                       if (event.key.repeat > 0) { break;}
                                        int k = event.key.keysym.sym;
                                        KeyInput key;
                                        key.flags = KEY_DOWN;
@@ -753,6 +754,7 @@ int main(int argc, char *argv[]) {
                                }
                        case SDL_KEYUP:
                                {
+                                       if (event.key.repeat > 0) { break;}
                                        int k = event.key.keysym.sym;
                                        KeyInput key;
                                        key.flags = KEY_UP;
```

**Comment by hrydgard** [comment] 2017-03-22 20:47
@neoh4x0r  just PR it yourself :)

**Comment by neoh4x0r** [comment] 2017-03-22 21:41
@hrydgard 
How do I PR this when I don't have a branch to pull the change from ?

**Comment by hrydgard** [comment] 2017-03-22 22:05
What? You should clone, make a branch, do the change, then make a pull request. That's how it's done.

**Comment by unknownbrackets** [comment] 2017-03-23 00:00
Yep, go here:
https://github.com/hrydgard/ppsspp/fork

Then you can clone:

```bash
git clone git@github.com:neoh4x0r/ppsspp.git
git remote add upstream https://github.com/hrydgard/ppsspp.git
git fetch upstream

git checkout -b sdl-repeat upstream/master

# Or your editor of choice.
vim ext/native/base/PCMain.cpp

git add -p
git commit

git push origin sdl-repeat
```

And then go to https://github.com/hrydgard/ppsspp and open a pull request.

-[Unknown]

**Comment by neoh4x0r** [comment] 2017-03-23 03:08
@unknownbrackets 
@hrydgard 
I just created the branch and pull request.

When dealing with github I almost never needed to create a fork and pull request -- most of the time providing a patch in a issue was enough -- but now I know how to do it....thanks.

**Comment by hrydgard** [comment] 2017-03-23 07:43
Great! People will be happier when you provide pull requests instead of patches - much faster to merge and easier to review with inline comments.

Thanks!

**Comment by hrydgard** [comment] 2017-11-14 11:29
So did that take care of all the issues here? 

Bumping to 1.6.0 anyway.

**Comment by neoh4x0r** [comment] 2017-11-14 13:45
@hrydgard You said you would look into the other issue with the inputbox.
That PR  resolved the double key_down events (the issue with the ESC key pausing and closing the menu)...so I guess this issue can be closed.

**Closed** 2017-11-14 13:46 UTC
Labels: SDL2

**Comment by unknownbrackets** [comment] 2017-11-15 04:18
I think that was done in 35e2a5a7d1db4ae83c8d80187efdb0bfaf8ab7bb, wasn't it?

-[Unknown]
