### ISSUE TITLE
God Eater Burst/God Eater 2 turned on white screen on Abandon City map when update android 6.0   

### ISSUE THREAD

**Issue by Alien1204** [hrydgard/ppsspp#8746] opened 2016-05-16 04:46 UTC

**Comment by Alien1204** [comment] 2016-06-02 19:21
Graphic error when turned on hardware transform...

**Comment by unknownbrackets** [comment] 2016-06-03 01:25
This issue is being closed as a duplicate of #8730.

Would you like me to email you every day to ask you if you've learned programming and fixed it yet?

-[Unknown]

**Closed by unknownbrackets** 2016-06-03 01:25 UTC

**Comment by vjjulius** [comment] 2016-07-07 14:10
I have the same issue. White screen on city.
build ppsspp-v1.2.2-758-g1f8afd7-android
Samsung S7 edge
