### ISSUE TITLE
Persona 3 Portable crashes at gender select

### ISSUE THREAD

**Issue by duskshadowbrony** [hrydgard/ppsspp#11984] opened 2019-04-20 20:03 UTC
### What happens?
I can get through the title screen just fine. However, when I select 'new game', and immediately once it tells me to pick a gender, the game crashes back to my phone's homescreen.

### What *should* happen?
It should let me pick a gender and play the game.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Hardware: Samsung Galaxy S7 (SM-G930P)
Android Version: 8.0.0
PPSSPP: 1.8.0 (crashes on dev build 1.8.0-111 as well)

**Comment by duskshadowbrony** [comment] 2019-04-20 20:05
I have tried turning off Fast Memory and Buffered Rendering. I have tried changing Backend's settings, changing JIT settings, and resetting PPSSPP to default settings.

**Comment by duskshadowbrony** [comment] 2019-04-20 21:57
Errors on PC, too. Entering the save menu makes the game drop to 1 FPS, the save menu does not load. I have to mash the circle button to back out of it, mashing X to try and save does not work.

Hardware:
- CPU: i7-6700k unlocked
- GPU: Nvidia GTX 1070- Latest Stable Drivers
- OS: Windows 8.1
- RAM: 16 GB DDR4
PPSSPP: 1.8.0

**Comment by unknownbrackets** [comment] 2019-04-21 00:51
This is a driver bug - duplicate of #11355.

You can work around it by changing to the Vulkan backend, but beware that the device also has bugs in its Vulkan implementation.  I'd suggest you save near the start and switch back to OpenGL ES.

-[Unknown]

**Closed** 2019-04-21 00:52 UTC
