### ISSUE TITLE
No options appear in the menu to choose the option "ARCADE" in the game DARKSTALKERS CHRONICLE THE CHAOS TOWER (ULUS10005)

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7654] opened 2015-04-03 23:14 UTC
Hi, while I put the problem of menu options within the "ARCADE" option in a ISSUE

As I said, in the "Buffered Rendering" only that mistake not display the menu options within the option ARCADE occurs.

In this image with window CE BUG in the tab "DISPLAY LIST", so this lead color, would be the letters of the options menu which is displayed as a red box. Apparently this as hidden, and below it appears as a pink line that supposedly this erroneous code or detect out the result:

With SETP PRIM

![01](https://cloud.githubusercontent.com/assets/5083411/6990198/f982dcdc-da2c-11e4-9bfa-9dcdb236363f.jpg)

With SETP INTO

![03](https://cloud.githubusercontent.com/assets/5083411/6990202/07a080a8-da2d-11e4-95d9-8fe1ab85764d.jpg)

It also happens when you do not go the way of gameplay that automatically passed as a short play, which characters do not appear and little graphic in the environment.

Here a picture of what is:

![02](https://cloud.githubusercontent.com/assets/5083411/6990205/1fc46fd2-da2d-11e4-924f-4fe4d6956e5c.jpg)

Well, this "unique" error is in all versions (BUILD and official). I do not know what I'm showing is correct so they can improve error Hopefully they can make to fix.

Sorry my bad english XD

**Comment by daniel229** [comment] 2015-04-04 01:30
Duplicate of https://github.com/hrydgard/ppsspp/issues/6647

**Closed** 2015-04-04 02:11 UTC
