### ISSUE TITLE
Not fullscreen on ipad mini

### ISSUE THREAD

**Issue by mezzocrip** [hrydgard/ppsspp#16623] opened 2022-12-19 09:40 UTC
### Game or games this happens in

Every game 

### What area of the game / PPSSPP

Whenn i start the app

### What should happen

Full screen without blacc bar on sides

### Platform

iOS

### Mobile phone model or graphics card

Ipad mini 6

### PPSSPP version affected

1.14

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2022-12-19 15:40
This issue is being closed as a duplicate of #14990.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2022-12-19 15:40 UTC
