### ISSUE TITLE
PPSSPP-sdl version string possibly corrupt

### ISSUE THREAD

**Issue by Joelgp83** [hrydgard/ppsspp#7378] opened 2015-01-26 21:57 UTC
Hey guys.  Got another UI bug for you.  I'm not entirely sure if its related to my install or an error in the install script in the ppa package here: https://launchpad.net/~ppsspp/+archive/ubuntu/testing

I'm using the git unstable branch, so of course ppsspp should be indicating the particular release being used.  Instead, it just says "unknown".

Pic here:
![version error](https://cloud.githubusercontent.com/assets/7368696/5909209/3af30e48-a563-11e4-970b-00966c89eae2.png)

**Comment by pal1000** [comment] 2015-01-27 08:32
It seams it cannot find Git due to an unknown reason. Is the window title affected as well?

**Comment by Joelgp83** [comment] 2015-01-27 08:36
Indeed.  Here's another screenie.  Both the window title and the entry on the panel/dock is affected.

Running Linux Mint 17.1.
![screenshot from 2015-01-27 00 34 39](https://cloud.githubusercontent.com/assets/7368696/5915604/909c224a-a5bc-11e4-82c2-1d6ada3efdb7.png)

**Comment by pal1000** [comment] 2015-01-27 12:06
Is this your first time building PPSSPP?
If so check if git is installed correctly. It appears that it doesn't find it some reason.

**Comment by Joelgp83** [comment] 2015-01-27 12:11
No compiling was done.  I've been installing from the Ubuntu ppa linked to in my opening post.

**Comment by sergiobenrocha2** [comment] 2015-01-28 03:02
It's not a bug, I just didn't uploaded git stuff to lauchpad branch...

In stable ppa, I changed version manually I think, in the code.

**Comment by sergiobenrocha2** [comment] 2015-01-28 03:05
.git folder has 84.6 MB, I will not upload it just for git commit version. And I think you get lintian errors in the packaging with revision system stuff in the source.

**Comment by Joelgp83** [comment] 2015-01-28 04:36
Wow.  I'm surprised it needs all that just to pull the proper git commit version.  I understand now why you did not include it.  However, perhaps we should have something else more meaningful than unknown displayed there if it can't find the git version?   Like git unstable branch or something?

Or would installing git locally on my machine let it pull the necessary info?

**Comment by sergiobenrocha2** [comment] 2015-01-28 13:16
If you install git, and git clone the repo and build a new package, yes, you will have the version instead "unknown"

**Comment by Joelgp83** [comment] 2015-01-28 18:51
I see.  Well, thank you for explaining why it says unkown, and providing a decent reason for why you left it purposefuly like that.  I had merely brought it up incase this was actually an oversight and wasn't intentional.  In fact, thank you for setting up the ppa in the first place, I had been waiting a very long time for someone to do that before you set it up so kudos. :)

Also, if you notice on my second screenshot, you'll notice that on the taskbar/panel at the bottom, it seems PPSSPP is not loading its icon.  Is this also intentional,or is that actually a bug in the packaging?

**Comment by sergiobenrocha2** [comment] 2015-01-28 19:32
In my system icon doesn't appears either, in panel and Alt+Tab. Dunno why.

**Comment by sergiobenrocha2** [comment] 2015-09-21 21:49
Just a side note: If you use -DCMAKE_BUILD_TYPE=Release, it should use 1.0.1.0 or last version like Qt does, right? The only place I found to change the version is here https://github.com/hrydgard/ppsspp/blob/master/git-version.cmake#L2, but should be something here maybe https://github.com/hrydgard/ppsspp/blob/master/CMakeLists.txt#L194, to stable releases.

**Comment by unknownbrackets** [comment] 2015-12-22 03:30
Closing this.  PPSSPP_GIT_VERSION_NO_UPDATE is the way to not update if you don't want the git version.

-[Unknown]

**Closed by unknownbrackets** 2015-12-22 03:30 UTC
Labels: Platform-specific (Linux)
