### ISSUE TITLE
[Android][Vulkan] Midnight Club 3 Dub Edition

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13833] opened 2020-12-29 08:48 UTC
### What happens?
Hello!

This game has the map broken.

![IMG_20201229_093937](https://user-images.githubusercontent.com/65356692/103271456-98b9f300-49ba-11eb-8563-e11f87457997.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy Note 10 Plus Exynos.
ppsspp-v1.10.3-1404-g8d2fdfc73-android.apk

Dump:
[ULUS10021_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5750081/ULUS10021_0001.ppdmp.zip)

**Comment by Panderner** [comment] 2020-12-29 09:01
Midnight Club L.A Remix also affected this issue

**Comment by Panderner** [comment] 2020-12-29 09:07
Midnight Club games works fine for me. I'm using POCO M3 Using Vulkan
![Screenshot_2020-12-29-17-03-40-407_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103272595-3c75c400-49f8-11eb-873b-1c571a8164d8.jpg)
![Screenshot_2020-12-29-17-05-12-291_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103272601-3e3f8780-49f8-11eb-8b7a-a7e28c948d83.jpg)

**Comment by Panderner** [comment] 2020-12-29 09:07
@MiguelCardonaG have you tried OpenGL?

**Comment by MiguelCardonaG** [comment] 2020-12-29 09:26
> @MiguelCardonaG have you tried OpenGL?

Yes, with Opengl the map looks good. Only the error comes from Vulkan.

**Comment by Panderner** [comment] 2020-12-29 10:23
It does not occur for my POCO M3 using Vulkan

**Comment by sum2012** [comment] 2020-12-29 13:51
Where is the map broken ?
I cannot see from the picture

**Comment by MiguelCardonaG** [comment] 2020-12-29 14:03
> Where is the map broken ?
> I cannot see from the picture

The map has to come round (see screenshot of @Panderner) and it's square to me.

**Comment by sum2012** [comment] 2020-12-29 15:11
I don't have problem in windows.
@MiguelCardonaG can you test  v1.7.4 ?
https://www.ppsspp.org/files/1_7_4/ppsspp.apk
and test v1.8 ?
https://www.ppsspp.org/files/1_8_0/ppsspp.apk

**Comment by MiguelCardonaG** [comment] 2020-12-29 15:55
Version 1.7.4 (Vulkan)

![Screenshot_20201229-162100_PPSSPP](https://user-images.githubusercontent.com/65356692/103294588-704deb00-49f2-11eb-8301-37b1d05a5ecb.jpg)

1.8. (Vulkan) 

![Screenshot_20201229-162358_PPSSPP](https://user-images.githubusercontent.com/65356692/103294637-86f44200-49f2-11eb-9aab-99a44f656edb.jpg)

v1.7.4 & 1.8 OPENGL:

![Screenshot_20201229-162358_PPSSPP](https://user-images.githubusercontent.com/65356692/103296471-72b24400-49f6-11eb-8911-c6bd29830980.jpg)

**Comment by sum2012** [comment] 2020-12-29 22:49
We have many issue for Mali gpu

**Comment by sum2012** [comment] 2020-12-30 14:58
I have download eclipse for android from
http://dl.google.com/android/adt/adt-bundle-windows-x86-20140702.zip
Hope this week can test build ppsspp's apk

**Comment by sum2012** [comment] 2021-01-01 12:41
I still fail to build ppsspp's apk

**Comment by sum2012** [comment] 2021-01-09 22:58
I reproduce in my sister with Samsung Tab A with S Pen (SM-P200) tablet
PPSSPP cannot detect CPU
https://ibb.co/Y7hZbkV
https://ibb.co/gSrGNBP

**Comment by sum2012** [comment] 2021-01-09 23:09
I forget this page
https://ibb.co/gdSnrV1

**Comment by ANR2ME** [comment] 2021-01-16 16:41
@hrydgard is there any recommendation of which Android Studio version, SDK, and NDK that worked the best for PPSSPP project?

It seems @sum2012 is having difficulty trying to build android version of PPSSPP (ndk path issue or something) to investigate this vulkan issue.

**Comment by hrydgard** [comment] 2021-01-16 16:47
You should not try to use Eclipse.

Install Android Studio 4.0  (not 4.1!) and open the project directory. It'll try to configure itself for a while, then find the Build Variants window and choose normalOptimized as Active Build Variant. Then run.

**Comment by sum2012** [comment] 2021-01-16 22:00
Build->Generate Signed APK / APK -> APK  -> Choose key file->finish

Error:Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
java.lang.ClassNotFoundException: com.google.wireless.android.sdk.stats.IntellijIndexingStats$Index
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.intellij.util.indexing.counters.IndexCounters.<clinit>(IndexCounters.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:92)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:108)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex$CompilerMapReduceIndex.<init>(CompilerReferenceIndex.java:274)
	at org.jetbrains.jps.backwardRefs.index.CompilerReferenceIndex.<init>(CompilerReferenceIndex.java:110)
	at org.jetbrains.jps.backwardRefs.JavaCompilerBackwardReferenceIndex.<init>(JavaCompilerBackwardReferenceIndex.java:13)
	at org.jetbrains.jps.backwardRefs.JavaBackwardReferenceIndexWriter.initialize(JavaBackwardReferenceIndexWriter.java:80)
	at org.jetbrains.jps.incremental.java.JavaBuilder.buildStarted(JavaBuilder.java:152)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:361)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:140)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hrydgard** [comment] 2021-01-16 22:50
You don't need to sign if you just want to build and debug. normalOptimized builds have debug keys.

If you do want to sign, there's another mechanism for it. Make a normalRelease build instead. In a gradle.properties file in, for example, your home folder, add these entries:

```
RELEASE_STORE_FILE=xxx
RELEASE_STORE_PASSWORD=xxx
RELEASE_KEY_ALIAS=xxx
RELEASE_KEY_PASSWORD=xxx
```
where you replace xxx with the appropriate values for your keystore. build.gradle will pick those values up.

**Comment by sum2012** [comment] 2021-01-17 01:45
There is no option to me that don't sign.
![1](https://user-images.githubusercontent.com/2177532/104827970-47a56c80-589f-11eb-87d6-9d92008e4f90.jpg)

**Comment by ANR2ME** [comment] 2021-01-17 02:17
It's easier to choose the Debug/NormalOptimized instead of Release Build for testing purpose, you don't need to dealt with keystore. 
And then choose Build APK instead of Build Bundle.

**Comment by ANR2ME** [comment] 2021-01-17 03:27
Do you have python 3.x ? I think it's one of the requirements.

**Comment by sum2012** [comment] 2021-01-17 11:26
Re-doing flash new source.
![1](https://user-images.githubusercontent.com/2177532/104839034-b57e8200-58f9-11eb-813a-25d166adb9bd.jpg)

**Comment by ANR2ME** [comment] 2021-01-17 13:20
Are you not using NDK from SDK Manager? as i remembered the folder will be named "ndk-bundle"

Also check if you had NDK_HOME in system environment variable or not.
![image](https://user-images.githubusercontent.com/7974720/104844198-5cb2e780-5901-11eb-84c2-c05e57a164a5.png)

**Comment by MiguelCardonaG** [comment] 2021-03-03 11:14
So how's it going? Is it going to be fixed?

**Comment by Gamemulatorer** [comment] 2021-05-02 12:57
Using latest git build ppsspp apk
![Screenshot_2021-05-02-20-56-07-288_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116813911-de651300-ab88-11eb-8b0f-30ef96043a69.jpg)

**Comment by unknownbrackets** [comment] 2021-05-02 17:25
In the dump, it draws the circle backplate using a standard triangle strip, depth clamp (not clamping here), alpha blend/test (standard / always), and depth test (always.)  It draws again using a stencil test, ALWAYS REPLACE FF, and an alpha test for > 0x64 alpha.  So clearly, the intent is that the map area is stenciled with FF.  The framebuf is 8888, so this sets actual FF.

Because of the alpha, the interior of the backplate (the part the map should show in) is the only part stenciled.

It then draws the map using a large textured draw well outside the backplate in every direction.

So for this not to work, like the first screenshot, it would mean that STENCIL REPLACE occurred even when the alpha test failed.  That sounds like a driver bug, and likely would occur on Adreno 5xx and certain Mali-Gxx devices (the same bug discussed in #11980.)

However, this octagon in the latest screenshot is a bit different.  It indicates perhaps that the alpha test succeeded for some parts of the triangle strip, since it's not square.  This might reveal more about the mechanics of Mali's version of the driver bug.

We might be able to workaround this specific case since depth write is disabled here, which we tried in #14207 but didn't fix the expected issue and seemed to potentially cause another, so was reverted in 5794823.

Can you try v1.11.2-214-ga64737f7f and see if it works in that version?  If so, I might try reinstating that workaround.  I'm no longer sure it caused the negative side effects it had seemed to.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2021-10-06 23:14
Change the title to mali gpu racing games has some broken map on vulkan backend?

**Comment by MiguelCardonaG** [comment] 2022-03-11 08:00
Any news?

**Comment by ANR2ME** [comment] 2022-03-11 09:14
> Any news?

You can try using the workaround mentioned in https://github.com/hrydgard/ppsspp/issues/15016 (ie. PixelDepthRounding)

**Comment by MiguelCardonaG** [comment] 2022-03-11 09:34
> > Any news?
> 
> You can try using the workaround mentioned in #15016 (ie. PixelDepthRounding)

And how do I put it? I don't get it...

**Comment by EternalsDarkhole** [comment] 2022-03-12 07:35
> > > Any news?
> > 
> > 
> > You can try using the workaround mentioned in #15016 (ie. PixelDepthRounding)
> 
> And how do I put it? I don't get it...

Create compat.ini or download the compat.ini file here in github and find the line pixeldepthrounding then add the id of midnight club games.

**Comment by hrydgard** [comment] 2022-06-19 09:18
Closing this since #15611 works around it fine. The driver version cutoff might need adjustment, please comment if it's still not working for you.

**Closed by hrydgard** 2022-06-19 09:18 UTC
Labels: Vulkan, Mali GPU

**Comment by Gamemulatorer** [comment] 2022-06-20 14:05
I can still reproduce this issue using the latest build on my Redmi note 9.
![Screenshot_2022-06-20-22-05-33-377_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/174619465-c59d1d30-a3ca-413b-adc3-3f4b47f9ff23.jpg)

**Comment by Gamemulatorer** [comment] 2022-06-20 14:13
> @Gamemulatorer if you go into settings / tools / system info, what GPU driver version does it show?

![Screenshot_2022-06-20-22-12-21-825_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/174621070-7c9cb9e1-6dfd-4daa-9a17-d6395c7d9866.jpg)

**Comment by hrydgard** [comment] 2022-06-20 14:16
Okay, looks like I need to apply this to some higher driver versions too then. Thanks!

**Comment by hrydgard** [comment] 2022-06-20 14:47
@MiguelCardonaG Please also report your GPU driver version, like GameEmulatorer did.

**Comment by MiguelCardonaG** [comment] 2022-06-20 15:10
![Screenshot_20220620-170751_PPSSPP](https://user-images.githubusercontent.com/65356692/174631934-c4a09e00-2061-49c9-8550-5eb8fb98c3e6.jpg)

**Comment by hrydgard** [comment] 2022-06-20 15:37
Thanks. Maybe it just isn't fixed, I'll remove the version limitation, and will also try to report it to ARM.

**Comment by hrydgard** [comment] 2022-06-20 15:38
That latest commit should fix it.

**Comment by MiguelCardonaG** [comment] 2022-06-20 15:55
Well, it keeps giving me the same error on the map.

**Comment by hrydgard** [comment] 2022-06-20 16:53
Even 1.12.3-1292 ?

**Comment by MiguelCardonaG** [comment] 2022-06-20 16:57
With version 1292 it works well. Thank you!

![PPSSPP_2022-06-20-18-56-01](https://user-images.githubusercontent.com/65356692/174649016-e06efe5f-5ce6-46cb-b67d-28cca7c48747.jpg)
