### ISSUE TITLE
Hide mouse cursor in fullscreen SDL

### ISSUE THREAD

**Issue by rcampbel3** [hrydgard/ppsspp#9548] opened 2017-04-04 03:38 UTC
I notice that this closed ticket addressed hiding the cursor in QT builds:
https://github.com/hrydgard/ppsspp/issues/4434
but it didn't address hiding the cursor in the SDL build.

I did a quick search, and it looks like this should be simple in SDL:
https://wiki.libsdl.org/SDL_ShowCursor

Code Example

int main(int argc, char *argv[]) {
    /* creates a blank cursor */
    SDL_ShowCursor(SDL_DISABLE);
    /* ... */
    return 0;
}

and then un-hide it after exiting a game.

**Comment by unknownbrackets** [comment] 2017-04-04 04:32
If you'd like to give a pull request a shot, it'd be very welcome.

Closing this as a duplicate of #6564.

-[Unknown]

**Closed by unknownbrackets** 2017-04-04 04:32 UTC

**Comment by Bracket-** [comment] 2017-09-28 17:18
From what I understand, this isn't a duplicate but a regression. The functionality was introduced in hrydgard/native@c2b558e / hrydgard/native@4a85cbe.

I assume the macro 'PPSSPP' no longer exists after the native merge and should be removed. I can confirm removing 'PPSSPP' macro tests fixes the issue and the mouse properly disappears.

**Comment by hrydgard** [comment] 2017-09-28 17:34
Oh good catch. Removing, #9985.

**Comment by unknownbrackets** [comment] 2017-09-30 23:29
Does that mean this is fixed now?  What about #6564?

-[Unknown]

**Comment by Bracket-** [comment] 2017-10-01 18:47
Yes, this is fixed as far as I can tell. Mouse is visible in windowed mode and hidden in fullscreen which I believe matches PPSSPPQt behavior, though I don't have PPSSPPQt handy right now to test. It should be noted that mouse may be hidden in windowed mode sometimes due to #9086.  

#6564 may be able to be closed but it mentions a timeout so the user may expect the cursor to be visible when active and hidden while inactive which isn't the current behavior. The user also didn't mention whether they expected the mouse to be hidden in windowed or fullscreen mode.
