### ISSUE TITLE
[Android][OpenGL/Vulkan][Sound Issue] SEGA RALLY REVO (ULJM05302) is not play any Voice in game.

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13445] opened 2020-09-17 14:48 UTC
### What happens?
Android is not play any voice in game.
Example) Voice of "3! 2! 1!" at start.
Example) Voice of "Easy Right! Easy Left" at curve.

### What *should* happen?
Play all voice corectly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver.：1.10.3-700
OS：Android 9.0
DeviceName：SONY SO-02K / Xperia XZ1 Compact（Japan）
CPU：Snapdragon835（Octa-core）
GPU：Adreno 540
Resolution：720×1280
RAM：4GB
ROM：32GB
ExternalStrage：microSDXC 512GB

**Comment by Panderner** [comment] 2020-09-18 14:39
Pacenotes voices are only heard for headphones and stereo speakers and this does not heard for mono speakers.

**Comment by Panderner** [comment] 2020-09-18 14:40
and still happens on youtube videos of this game recorded on real hardware.

**Comment by hrydgard** [comment] 2020-09-18 18:03
Huh! That would seem to indicate they're played with inverted phase on one speaker, so they cancel out in the mono mix. Wonder why...

**Comment by nassau-tk** [comment] 2020-09-18 20:03
Um....
I have a blutooth earphone.
But,Voice sound is not play in SEGA RALLY REVO.

**Comment by Panderner** [comment] 2020-09-18 22:59
> Um....
> I have a blutooth earphone.
> But,Voice sound is not play in SEGA RALLY REVO.

@nassau-tk have you turned off mono audio in accessibility settings?

**Comment by nassau-tk** [comment] 2020-09-18 23:53
> @nassau-tk have you turned off mono audio in accessibility settings?

@Panderner 
Does it means "Audio Settings in PPSSPP"? or "Audio Settings in My Phone"?
Anyway, I can't find any settings of stereo/mono audio bothof PPSSPP / Phone .

**Comment by Panderner** [comment] 2020-09-19 00:07
> > @nassau-tk have you turned off mono audio in accessibility settings?
> 
> @Panderner
> Does it means "Audio Settings in PPSSPP"? or "Audio Settings in My Phone"?
> Anyway, I can't find any settings of stereo/mono audio bothof PPSSPP / Phone .

in android settings find accessibility and turn off mono speakers. @nassau-tk Android settings not PPSSPP settings

**Comment by nassau-tk** [comment] 2020-09-19 00:26
> in android settings find accessibility and turn off mono speakers. @nassau-tk Android settings not PPSSPP settings

@Panderner 
Yes!! I found it and turn off mono speaker then voice has come back on SEGA RALLY REVO!!

**Comment by Panderner** [comment] 2020-09-20 10:49
Close this as it's not a bug because pacenote voices doesn't play on mono speakers even real hardware recorded on youtube and PSP-E1000's speakers.

**Closed** 2020-09-20 14:28 UTC
Labels: Audio

**Comment by Panderner** [comment] 2020-09-20 14:54
and mark this not a bug since the voices are not played on mono speakers. and here's a youtube video recorded on real PSP: https://youtu.be/LmkopjzWfXs

this is not a PPSSPP issue as they confirmed for PSP-E1000's speakers. we required to use headphones and stereo speakers unless your phone or tablet has stereo speakers.
