### ISSUE TITLE
Character broken in Saint Seiya Omega

### ISSUE THREAD

**Issue by xsm1997** [hrydgard/ppsspp#7000] opened 2014-10-13 23:43 UTC
Sorry for my bad English. In my android phone, the character of the game breaks whether I turned on "Force depth write". The character sometimes appears almost fully, sometimes appears only a half, and sometimes completely disappears.
![4](https://cloud.githubusercontent.com/assets/4453837/4621865/25037272-5332-11e4-8b84-21220364e014.png)
![1](https://cloud.githubusercontent.com/assets/4453837/4621867/2fcdf038-5332-11e4-9241-2f91bc798acd.png)
![5](https://cloud.githubusercontent.com/assets/4453837/4621869/40514680-5332-11e4-9b36-beed6e4287b3.png)
![3](https://cloud.githubusercontent.com/assets/4453837/4621876/4fa24abc-5332-11e4-9f1a-bd2d8f438097.png)
![2](https://cloud.githubusercontent.com/assets/4453837/4621883/5cf74672-5332-11e4-98c2-ad108e9c71d5.png)
By the way, my CPU model is MT6592.
Thanks in advance.

**Comment by unknownbrackets** [comment] 2015-02-22 22:04
Well, this also affects Jeanne d'Arc, and a few other games.  Unfortunately, if we share depth buffers, we also share stencil buffers, which will come with its own set of new glitches.  There's no perfect option, at least that we've thought of so far, for GLES 2 devices.

I think we should probably consolidate any open issues we have for depth on GLES2 into one, if we have any idea how to fix it.  I'm not sure if it makes sense to keep multiple open for the same problem, which we know is fixed by the GLES3-only method.

-[Unknown]

**Comment by unknownbrackets** [comment] 2015-12-30 18:40
This is actually a duplicate of #1808.  Closing.

-[Unknown]

**Closed by unknownbrackets** 2015-12-30 18:40 UTC
