### ISSUE TITLE
armored core last raven not playable

### ISSUE THREAD

**Issue by croserII** [hrydgard/ppsspp#9964] opened 2017-09-12 18:55 UTC
this game will freeze after you move the camera toward sun during first mission,,I try the latest build ppsspp-v1.4.2-436-g4f7b023cf-windows-amd64,I also try old build 1.2.2.634

**Comment by LunaMoo** [comment] 2018-03-17 16:35
Closing as a duplicate of #5999

**Closed by LunaMoo** 2018-03-17 16:35 UTC
