### ISSUE TITLE
Discussion : LLVM Recompiler

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#9924] opened 2017-08-22 10:07 UTC
Have you ever to build a new recompiler in the future on roadmap ?
https://llvm.org/

**Comment by hrydgard** [comment] 2017-08-22 17:50
PSP games tend to load and unload code dynamically and some even modify it dynamically. The reason RPCS3 can make such good use of LLVM to precompile is that all such operations are forbidden on the PS3 so games don't do them. 

Besides, GPU emulation takes more time than CPU emulation in most heavy games. 

But yeah, there are still improvements that can be made to the existing recompiler, for example the function return optimization that Dolphin does could be implemented and would yield a few %.

**Comment by zminhquanz** [comment] 2017-08-23 01:55
I think you can do that

**Comment by unknownbrackets** [comment] 2017-08-23 03:44
Isn't this a duplicate of #5925?

-[Unknown]

**Comment by zminhquanz** [comment] 2017-08-23 05:46
@unknownbrackets no , i'm not mention about the JIT or AOT Compiler

**Comment by hrydgard** [comment] 2017-08-23 08:49
LLVM is only really useful for AOT (technically you can use it for a block JIT as well but it's not very meaningful) so I'd agree that it's a dupe of #5925. Closing.

**Closed by hrydgard** 2017-08-23 08:49 UTC
