### ISSUE TITLE
The warrior psp

### ISSUE THREAD

**Issue by fokee** [hrydgard/ppsspp#10608] opened 2018-02-12 04:49 UTC
http://forums.ppsspp.org/showthread.php?tid=1373

Trying with latest PPSSPP stable 1.5.4 android but still same error with vulkan and I forget to try opengl 😂

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by fokee** [comment] 2018-02-12 04:50
Android (c106) CPU 652 GPU 510 Nougat

**Comment by ppmeis** [comment] 2018-02-12 10:26
Tested with latest Windows build, default settings. It seems to be broken by various sides but 100% playable:

Cinematic Movies are very slow:
![image](https://user-images.githubusercontent.com/4381277/36091928-d13402e6-0fe5-11e8-92de-50f910f8fb75.png)

Light is blinking while moving camera view:
![image](https://user-images.githubusercontent.com/4381277/36092033-3af5b7f6-0fe6-11e8-967f-99b00ce406e2.png)
![image](https://user-images.githubusercontent.com/4381277/36092044-41878e46-0fe6-11e8-87d7-aac8d73fa1dd.png)

**Comment by ppmeis** [comment] 2018-02-12 10:28
Log:
![image](https://user-images.githubusercontent.com/4381277/36092483-cf55c804-0fe7-11e8-95d2-56c18a14bd3c.png)

**Comment by benderscruffy** [comment] 2018-05-26 01:00
this can be closed as a duplicate of #8991

**Comment by ppmeis** [comment] 2018-05-27 11:44
This should not be closed, because here we are talking about lightning issues.

**Comment by unknownbrackets** [comment] 2018-05-27 14:27
Wait, so, does that mean it is fixed or still na issue?

-[Unknown]

**Comment by ppmeis** [comment] 2018-05-27 15:13
Lightning issues are fixed @unknownbrackets. Cinematic movies are tracked on #8991 

Thanks for your hard work.

**Comment by unknownbrackets** [comment] 2018-05-27 15:19
Oh, okay then, closing this again.  Yay.

-[Unknown]

**Closed by unknownbrackets** 2018-05-27 15:19 UTC
