### ISSUE TITLE
[MGSPW/PO] Clipping issues?

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#12348] opened 2019-09-23 09:58 UTC
I don't know when this started happening, but playing Portable Ops & Peace Walker, both games seem to present a similar issue to the one I made for Kingdom Hearts of the ground suddenly going invisible, and I made several GE Dumps. The problem still seems to happen in any backend.

The Peace Walker GE Dumps seem to work fine as opposed to the Portable Ops ones.

PW GE Dumps: 
https://cdn.discordapp.com/attachments/478294170662862852/625631606207676452/recording_pw1.ppdmp
https://cdn.discordapp.com/attachments/478294170662862852/625631604945059850/recording_pw2.ppdmp
https://cdn.discordapp.com/attachments/478294170662862852/625631605230272517/recording_pw3.ppdmp
https://cdn.discordapp.com/attachments/478294170662862852/625631604076707850/recording_pw4.ppdmp

And here's the Portable Ops ones, that apparently don't work.
https://cdn.discordapp.com/attachments/478294170662862852/625631805881581579/recording_po1.ppdmp
https://cdn.discordapp.com/attachments/478294170662862852/625631809392345098/recording_po2.ppdmp

And here's some images, comparing some of the GE Dumps in each backend.
https://github.com/AkiraJkr/imgur-sucks/issues/4

**Comment by unknownbrackets** [comment] 2019-10-01 06:57
Correct result:
![ULUS10509_#12348_mgs_peace_walker_clipping](https://user-images.githubusercontent.com/191233/65939104-c4c27f00-e3d9-11e9-9ca6-0048633c0f50.png)

Software result:
![ULUS10509_#12348_mgs_peace_walker_clipping_softgpu](https://user-images.githubusercontent.com/191233/65939118-d1df6e00-e3d9-11e9-8b7a-1b10da61b9e9.png)

GL:
![ULUS10509_#12348_mgs_peace_walker_clipping_gl](https://user-images.githubusercontent.com/191233/65939124-d572f500-e3d9-11e9-88d3-628617e8f593.png)

This is caused by draw 1703/4984, which is getting partially culled, but some par of it shouldn't.
 * It's a triangle strip with 9 verts (so 7 triangles)
 * Depth clamp is enabled
 * Viewport depth is unusual (center = 30000, scale = -20000 -> 2710-C350)
 * Min/max Z matches the viewport depth range (2710 / C350)
 * Looking casually, only two points look like they'd trigger culling: (-10398.887695, -3312.689453, -293688.593750) and (2609.670898, 735.081543, 55598.062500)
 * Since those have clampable depths, they should not be culled.

This probably means there's still some misbehavior like culling when depth is outside the viewport/minmaxz range or something.

-[Unknown]

**Comment by hrydgard** [comment] 2020-05-31 22:18
As far as I know, these games don't need range culling anyway - as a quickfix, I'll just disable that for them, then leave this open.

**Comment by unknownbrackets** [comment] 2021-09-08 01:22
The vert triggering cull (incorrectly) is (2609.670898, 735.081543, 55598.062500).  Not sure why I said it was mistakenly outside [0, 65535] before.

Its pre-viewport/offset coordinates are (9.873632,-4.405027, -1.279904).  Although I haven't implemented it to verify yet, this strongly suggests that as per #14168 / #12058, pre-viewport Z < -1 should trigger triangle to be clipped and no longer outside the guardband for culling.  It looks like implementing that would fix this.

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-10-02 15:16
This was fixed in #14833, with or without hardware clip/cull/geometry support.  The frame dump renders correctly without any compat flags, etc. As such, closing this.

We should probably remove the use of the compat flag.  It might be that there are scenes in this game which do rely on range culling.  In the specific case of this bug, it was the viewport Z and the previous culling was incorrect and culling things it shouldn't.

-[Unknown]

**Closed by unknownbrackets** 2022-10-02 15:16 UTC
Labels: Depth / Z, Guardband / Range Culling
