### ISSUE TITLE
Metal gear solid portable ops terrible lag 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#12963] opened 2020-05-24 11:11 UTC
### What happens?
Metal gear solid portable ops is terrible lagging , if i see in debug statics flushes 2013 . sorry for my bad English 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Snapdragon 430 , adreno 505 gpu

**Comment by Panderner** [comment] 2020-05-24 12:34
Sorry your phone is not powerful enough to run this game at Full Speed. if you want to increase performance lower the Internal Resolution to 1x

**Comment by fahadrashid7705** [comment] 2020-05-24 13:25
the game runs at lagest area in 2-3 fps

**Comment by Panderner** [comment] 2020-05-24 14:06
all had to do to restore to default settings

**Comment by fahadrashid7705** [comment] 2020-05-24 14:10
All settings are default

**Comment by Panderner** [comment] 2020-05-24 15:22
> the game runs at lag area in 2-3 fps

But what area? I'm using a Helio P22 Phone the game works fine.

**Comment by Panderner** [comment] 2020-05-24 15:24
@fahadrashid7705 OpenGL or Vulkan?

**Comment by fahadrashid7705** [comment] 2020-05-24 15:28
open gl , my device not support vulkan api

**Comment by fahadrashid7705** [comment] 2020-05-24 15:31
in game start i am in a cell , i turn back wall the game heavyly lag and fps drop down in 2 and 3 if i turn  in cells gate some fps encrease 18-20

**Comment by Panderner** [comment] 2020-05-24 15:51
> in game start i am in a cell , i turn back wall the game heavyly lag and fps drop down in 2 and 3 if i turn in cells gate some fps encrease 18-20 hope you undestand my issue

can you summit a save state? but i don't know how can you do this?

**Comment by fahadrashid7705** [comment] 2020-05-25 09:21
this issue in my pc too cpu clock speed 333mhz,250, or  default but other psp games run proper speed. i dont know what is this issue . plz any solution

**Comment by Panderner** [comment] 2020-05-25 09:37
> this issue in my pc too cpu clock speed 333mhz,250, or default but other psp games run proper speed. i dont know what is this issue . plz any solution

Because this game is capped at 20 FPS Similar to Peace Walker.

**Comment by fahadrashid7705** [comment] 2020-05-25 12:25
hmm but peace walker better run in my device , maybe portable ops and plus optimization very poor

**Comment by Panderner** [comment] 2020-05-25 12:37
> hmm but peace walker better run in my device , maybe portable ops and plus optimization very poor

can you summit the screenshot of the frame rate?

**Comment by fahadfoyjur** [comment] 2020-05-25 12:40
Ok

**Comment by Panderner** [comment] 2020-05-25 12:51
@fahadfoyjur you forgot to post the screenshot.

**Comment by fahadrashid7705** [comment] 2020-05-25 14:25
![Screenshot_20200525-201903](https://user-images.githubusercontent.com/56797244/82821407-e242dc80-9ec5-11ea-81d3-1322bf6f13a2.png)

**Comment by fahadrashid7705** [comment] 2020-05-25 14:26
![Screenshot_20200525-202003](https://user-images.githubusercontent.com/56797244/82821443-f4247f80-9ec5-11ea-8c42-2cf2e848a074.png)

**Comment by fahadrashid7705** [comment] 2020-05-25 14:27
![Screenshot_20200525-202113](https://user-images.githubusercontent.com/56797244/82821505-11594e00-9ec6-11ea-9579-932bb1465f3a.png)

**Comment by fahadrashid7705** [comment] 2020-05-25 14:29
here the three screenshots ,first ss is in cell's back wall turn 1-2 fps , 2nd cell's gate if i turn in cell gate fps 22-17

**Comment by Panderner** [comment] 2020-05-25 14:43
can you submit the save state?

**Comment by Panderner** [comment] 2020-05-25 14:50
@fahadrashid7705 Original MGSPO or MGSPO Plus?

**Comment by fahadrashid7705** [comment] 2020-05-25 15:46
yes both

**Comment by fahadrashid7705** [comment] 2020-05-25 15:49
the fist mission

**Comment by unknownbrackets** [comment] 2020-05-25 15:52
Wonder if there's a way to reduce draw calls here.

Could you try exporting a GE frame dump?  Just make sure to export it during the slow performance - it's almost like a screenshot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by fahadrashid7705** [comment] 2020-05-25 16:23
[recording.zip](https://github.com/hrydgard/ppsspp/files/4678092/recording.zip)

**Comment by fahadrashid7705** [comment] 2020-05-25 16:35
and one more game same prob here name tenchu shadow assassins hugh draw calls and flushes

**Comment by Panderner** [comment] 2020-05-25 16:42
@fahadrashid7705 i can't produce this issue I'm using Realme C2 running PPSSPP in Latest build.

**Comment by fahadrashid7705** [comment] 2020-05-25 16:44
i give you the dump file

**Comment by unknownbrackets** [comment] 2020-05-25 16:47
That dump was empty, it might be from frameskipping.  Try turning off frameskipping when creating the dump.

-[Unknown]

**Comment by fahadrashid7705** [comment] 2020-05-25 16:48
frameskipping off

**Comment by unknownbrackets** [comment] 2020-05-25 16:50
Hm, I'm not sure then.  It's only 2 KB and doesn't really include any drawcalls.  If you try recording a couple times, is one of the dumps larger?

-[Unknown]

**Comment by fahadrashid7705** [comment] 2020-05-25 16:53
ok trying

**Comment by fahadrashid7705** [comment] 2020-05-25 17:26
ok recorded but the recorded file location ?

**Comment by fahadrashid7705** [comment] 2020-05-25 17:31
[ULUS10202_0001.zip](https://github.com/hrydgard/ppsspp/files/4678285/ULUS10202_0001.zip)

**Comment by fahadrashid7705** [comment] 2020-05-25 17:34
[ULUS10202_0002.zip](https://github.com/hrydgard/ppsspp/files/4678295/ULUS10202_0002.zip)

**Comment by Gamemulatorer** [comment] 2020-05-25 17:34
Snapdragon 430 has some problems on ppsspp
like in HM boy & girl even the game is 2d only
https://github.com/hrydgard/ppsspp/issues/12824
cannot run the game in full speed so expect a low performance on a full 3D game like this.

**Comment by Gamemulatorer** [comment] 2020-05-25 18:14
> [ULUS10202_0002.zip](https://github.com/hrydgard/ppsspp/files/4678295/ULUS10202_0002.zip)

@fahadrashid7705 your dump is blank :/
I test this game and it's running smooth on my phone 🤔 JK😂
![Screenshot_20200526-020540](https://user-images.githubusercontent.com/37603562/82835418-893f6c80-9ef6-11ea-9ade-754b95f9123c.png)
Ge dump 
[metal-gear-solid-portable-ops-plus-europe.zip](https://github.com/hrydgard/ppsspp/files/4678424/metal-gear-solid-portable-ops-plus-europe.zip)

**Comment by fahadfoyjur** [comment] 2020-05-25 18:19
this is imposible

**Comment by Gamemulatorer** [comment] 2020-06-03 07:39
@fahadrashid7705 @fahadfoyjur No feedback/outdated!?

**Comment by fahadrashid7705** [comment] 2020-06-05 12:37
still having this problem .

**Comment by fahadrashid7705** [comment] 2020-06-05 12:39
why my dump is blank ?  i am not undestanding .

**Comment by Gamemulatorer** [comment] 2020-06-05 13:10
> why my dump is blank ? i am not undestanding .

Better to close this issue since your phone specs is not very likely to play this game at full speed or without lag but if your phone support vulkan better to use that and see if it's improve the game speed.

**Comment by fahadrashid7705** [comment] 2020-06-07 05:48
i think a very big bug or problem in this game , because my pc cannot handle this issue too , 333mhz cpu speed and default speed not worked too . thanks for reply

**Comment by fahadrashid7705** [comment] 2020-06-07 05:49
android 6.0 not support vulkan , i think this game not good optimized

**Comment by Gamemulatorer** [comment] 2020-06-22 01:57
> Seems to be a device power issue, unclear what can be done, closing.

Closing my issue #13040 because of device power and why this issue still open? 😔

**Comment by fahadrashid7705** [comment] 2020-08-31 06:30
this is a terrible issue . in my pc ? same issue here

**Comment by Gamemulatorer** [comment] 2022-04-25 08:49
@fahadfoyjur no feedback outdated?

**Comment by Gamemulatorer** [comment] 2022-12-08 07:40
Can you still reproduce this terrible lag, using the recently build?

**Comment by hrydgard** [comment] 2022-12-08 10:05
Closing, unlikely to do any specific thing about this other than generally optimizing the emulator. One day it might be fast enough on this device, or maybe it won't...

**Closed by hrydgard** 2022-12-08 10:05 UTC
