### ISSUE TITLE
PoP Revelations-grey screen filter

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#12210] opened 2019-08-01 11:02 UTC
#What happens?
![Screenshot_2019-08-01-12-50-22](https://user-images.githubusercontent.com/33152267/62287977-a08b0600-b45b-11e9-9146-a7a5c0561647.png)

![Screenshot_2019-08-01-13-56-23](https://user-images.githubusercontent.com/33152267/62291533-7853d500-b464-11e9-927d-bcb86c308a8d.png)
Like this it is lookslike without hack. To fix this i using disabling slower effects
![Screenshot_2019-08-01-12-50-34](https://user-images.githubusercontent.com/33152267/62288104-f069cd00-b45b-11e9-927e-55f5b5489d75.png)
![Screenshot_2019-08-01-13-56-35](https://user-images.githubusercontent.com/33152267/62291497-5fe3ba80-b464-11e9-9d79-7dd86448a323.png)
Does it mean effects are in game broken and for fixing it i need to use hacks?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
![Screenshot_2019-08-01-13-01-13](https://user-images.githubusercontent.com/33152267/62288358-7f76e500-b45c-11e9-85f9-0cf11716e3af.png)
Huawei cun-L21

Here is frame dump file:
[DUMP.zip](https://github.com/hrydgard/ppsspp/files/3456508/DUMP.zip)

**Comment by Emulatorer** [comment] 2019-08-01 12:27
Same with #11573 disable slower effects fixed the graphics issue in MALI-GPU?

**Comment by marosis** [comment] 2019-08-01 12:32
Maybe it is just only improving... but i still think, it is still not natural paint of screen with that hack(somezhing like dante's inferno)

**Comment by PilipinoAko** [comment] 2019-08-03 01:49
Saan ilalagay yung dump file/what file i place dump file

**Comment by marosis** [comment] 2019-08-03 07:18
Please only english!!! Not Philipines. Look at this https://github.com/hrydgard/ppsspp/wiki
Here you have what is is, for what it is and how to get it. But it was little bit problematic for my phone. Everything working fine but after touching 'record' button ppsspp had everytime black screen maybe because of low ram capacity and slow perf.

**Comment by marosis** [comment] 2019-08-06 20:24
I want ask if is in this kind of issue right create Frame DUMP or log. I know logcat will show you all operations what was done and DUMP show textures and graphics issues?

**Comment by hrydgard** [comment] 2020-04-26 10:01
Duplicate of #6423

**Closed by hrydgard** 2020-04-26 10:01 UTC
