### ISSUE TITLE
PPSSPP 0.9.8 Crash on Sleep

### ISSUE THREAD

**Issue by Tommyx** [hrydgard/ppsspp#6157] opened 2014-05-27 10:01 UTC
If I hit the PWR Button of my Xperia Z1 (Android 4.4.2) ppsspp freezes and not only this .. it tears down the whole system with it. The phone is a fast & powerful one .. it takes a lot to get this device frozen .. jerky

;) 

Any Ideas?!

**Comment by unknownbrackets** [comment] 2015-01-20 04:35
There haven't been any other reports.  Maybe it'd be good to look at your configuration more and try a cleaner environment, or Android 5.0, or etc.

Anyway, I'm going to close this since the Z1 is not exactly an unpopular phone, and I'd expect us to get at least another report of this within the last 6 months.  It might be better to discuss this on the forum if it's specific only to your device / Windows.  It really should not be possible for us to cause this on Windows unless you have a very broken driver.

But if there's more information that could lead us to a fix / more reproduction information, please comment and we'll reopen.

-[Unknown]

**Closed by unknownbrackets** 2015-01-20 04:35 UTC
