### ISSUE TITLE
Graphics issue with Persona 3 Portable on iOS 14

### ISSUE THREAD

**Issue by Quietninja0954** [hrydgard/ppsspp#13581] opened 2020-10-23 22:44 UTC
### What happens?
Most of the battle menu and the UI graphics are gone.
![E2E30BCC-62FD-453A-B80E-4401D72F8394](https://user-images.githubusercontent.com/66715677/97059239-e3079980-155d-11eb-9197-fae12cff5ef4.png)

### What *should* happen?
The graphics should appear like this
![80126CED-2716-455F-9AC5-AD70AD7F98B7](https://user-images.githubusercontent.com/66715677/97059424-61fcd200-155e-11eb-8aec-fd5da89ec6cd.jpeg)

### What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues. 

I’m on a iPhone XR (IOS 14.1) using IR interpreter and using ppsspp non- jailbroken dev working (v1.6.3-456-g6d0ed4ad0) sideloaded with AltStore.

Extra notes: It was working fine when I was using JIT on iOS 13.5.1 (which is the second photo I provided) but when I got iOS 14 the app crashed when the cpu was JIT. So I changed it to interpreter can it ran fine but the graphics were missing and ir interpreter had the same effect. Is there anything I can do at the moment?

**Comment by Panderner** [comment] 2020-10-23 22:45
Is this really Duplicate of #13573?

**Comment by Quietninja0954** [comment] 2020-10-23 22:49
Seems so

**Comment by hrydgard** [comment] 2020-11-02 23:16
Indeed, closing as duplicate.

**Closed by hrydgard** 2020-11-02 23:16 UTC
