### ISSUE TITLE
[Windows] Spider-Man 3 [ULUS10317] Crash

### ISSUE THREAD

**Issue by Lerianis** [hrydgard/ppsspp#12579] opened 2020-01-14 22:14 UTC
What happens: When you jump in the hole to transition between the first "Chase the Lizard" mission in the game, no matter which option you pick to return to the city or continue the mission, the game crashes and takes down PPSSPP as well.

What should happen: The game should send you to the next mission or back to the city streets depending on which option you choose.

Running on a P50 Toshiba laptop with an Intel HD4400 graphics chip, Windows 10 Home, PPSSPP 1.9.3 from the main site.

I have tried messing with various settings from switching to OpenGL to DirectX9 to DirectX11 and the crash keeps on happening. I have also tried turning off all the 'graphical prettiness' things like hardware transform and vertex caching with no change in this behavior.

**Comment by Lerianis** [comment] 2020-01-14 22:21
I have turned on Debug console and apparently the game is not sending up any error messages before the crash.
Would a save file at the exact spot of the crash help?

**Comment by Emulatorer** [comment] 2020-01-15 05:47
#10196

**Comment by hrydgard** [comment] 2020-01-17 10:30
Good to confirm that. The fact is though that the game does work for some people, and it makes sense to try to narrow down what the difference is. Having a confirmed report that a non-modified ISO has the issue proves that it's indeed a real problem, thanks for reporting that!  Is your ISO US or EU?

**Comment by MojoJojoDojo** [comment] 2020-01-17 15:18
The game is problematic on PCXS2 as well (random freezes and other stuff).
Don't know if related though.
that's what the pcsx2 guys tell about the issues : " The game can freeze randomly at some specific checkpoints, with a distorted looping sound playing over. It seems to be related to the game trying to play multiple sounds\tracks at the same time.".

**Comment by Lerianis** [comment] 2020-01-19 05:53
I found out what the problem is: It's something with the sound processing. I hard disabled the sound at the point where the game was crashing PPSSPP and instantly, no more crashes at that point and I could get to the next part of the game.

**Comment by MojoJojoDojo** [comment] 2020-01-22 14:43
Now I really thinks there is a overlap here lol.

**Comment by hrydgard** [comment] 2020-01-22 15:10
It does seem likely to be a game bug that survived the port, and somehow doesn't get triggered on actual hardware. Kind of odd that it would affect both platforms...

**Comment by unknownbrackets** [comment] 2020-02-14 00:20
It doesn't sound like this information is more useful in a separate issue than in #10196.  If the answer is that it depends on sound settings (in PPSSPP?  in game?), that's definitely helpful and may explain why some users report no issues.

I'm going to close this as it seems to be a duplicate of #10196.  If a developer who can reproduce this issue becomes interested in fixing it, it will be more useful to have the information all together.  Spreading it out like this will probably only make them unable to reproduce it, and make sure the bug doesn't get fixed.

-[Unknown]

**Closed by unknownbrackets** 2020-02-14 00:20 UTC
