### ISSUE TITLE
Socom fireteam bravo 3 graphic error

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11814] opened 2019-02-19 05:47 UTC
screenshot:https://imgur.com/a/ihOUiAj
this happen when changing non buffered rendering to buffered rendering
ppsspp android version:v1.7.5-473-g4d8f3c48a

**Comment by hrydgard** [comment] 2019-02-19 08:16
OK, so that's the classic case of buffers not being cleared every frame sticking around. I'm not sure there's a good solution to this, but leaving open in case we think of something.

**Comment by kyousuke77** [comment] 2019-02-19 08:22
iam not using save state and this issue only happen when i'm playing multiplayer ad-hoc
everything normal on singleplayer

**Comment by kyousuke77** [comment] 2019-02-19 08:26
another screenshot
https://imgur.com/xttKeR0

**Comment by hrydgard** [comment] 2019-02-19 08:48
Thanks. But if you avoid switching between buffered/unbuffered, everything is fine, right?

**Comment by unknownbrackets** [comment] 2019-02-19 11:18
Wasn't this what that code to clear RAM on a clear was for?  See #8994 and https://github.com/hrydgard/ppsspp/issues/8973#issuecomment-246225702.  Basically, iirc, it does a clear in an FBO, then a while later after that FBO is destroyed, it uses the memory since it's "quite sure" that it's all zeros.

-[Unknown]

**Comment by kyousuke77** [comment] 2019-02-19 23:05
graphic bug sometime occurs when i'm going to some place in the game 
only happen in multiplayer.
Everything normal in singleplayer

**Comment by kyousuke77** [comment] 2019-02-19 23:06
another screenshot
https://imgur.com/a/3iKqh3M

**Comment by hrydgard** [comment] 2019-02-20 12:57
@kyousuke77  can you check the Game ID of your ISO? (hold-press on the icon, the letters and numbers after the name of the game). That last commit could have helped.

**Comment by kyousuke77** [comment] 2019-02-20 13:27
UCUS98716

**Comment by hrydgard** [comment] 2019-02-20 13:39
Thanks, that rules out one possible explanation.

**Comment by Gamemulatorer** [comment] 2020-05-26 23:21
I can repro this issue by changing buffered rendering to skip buffered rendering, not only that I can also repro this issue by loading a savestate hm. 🤔

• Loading from savestate
![Screenshot_20200527-071259](https://user-images.githubusercontent.com/37603562/82959384-23341180-9fea-11ea-8e61-18769174e62c.png)
• Changing buffered to skip buffered
![Screenshot_20200527-071252](https://user-images.githubusercontent.com/37603562/82959445-4ced3880-9fea-11ea-8848-672dc2c59089.png)
• GE Dump
[SOCOM3.zip](https://github.com/hrydgard/ppsspp/files/4685464/SOCOM3.zip)

**Comment by Gamemulatorer** [comment] 2021-09-27 12:57
@unknownbrackets removing this game id to ClearToRam and move to DisableReadBack compatibility fixes this issue on my phone 🤔

**Comment by Gamemulatorer** [comment] 2021-09-27 13:12
This issue can be fixed by enabling Disable Slower Effects tried and tested both VK and OGL.

**Comment by Gamemulatorer** [comment] 2021-09-27 13:39
Ok I finally found a proper fix no need disable slower effects I put this game id to DisableFirstFrameReadback compat and it's totally fixed now.

**Comment by Gamemulatorer** [comment] 2021-09-27 13:42
DisableFirstFrameReadback OFF

https://user-images.githubusercontent.com/37603562/134920237-b6c3349c-7f50-44e3-917d-2485c52eb8f1.mp4

DisableFirstFrameReadback ON

https://user-images.githubusercontent.com/37603562/134920271-46ec55da-1b1d-4238-9f45-5170c48284c7.mp4

**Comment by Gamemulatorer** [comment] 2021-09-29 10:03
@hrydgard it's unsafe to add this game to DisableFirstFrameReadback? but it fixes this issue as I tested both on my android phones.

**Comment by Gamemulatorer** [comment] 2021-09-29 12:33
@hrydgard  after you added this game to DisableFirstFrameReadback you can also remove this to ClearToRam because it doesn't help this game.

**Comment by hrydgard** [comment] 2021-09-29 19:06
Done. Bumping further work here to Future.l

**Comment by StilMuz** [comment] 2021-10-04 13:51
> I can repro this issue by changing buffered rendering to skip buffered rendering, not only that I can also repro this issue by loading a savestate hm. 🤔
> 
> • Loading from savestate ![Screenshot_20200527-071259](https://user-images.githubusercontent.com/37603562/82959384-23341180-9fea-11ea-8e61-18769174e62c.png) • Changing buffered to skip buffered ![Screenshot_20200527-071252](https://user-images.githubusercontent.com/37603562/82959445-4ced3880-9fea-11ea-8848-672dc2c59089.png) • GE Dump [SOCOM3.zip](https://github.com/hrydgard/ppsspp/files/4685464/SOCOM3.zip)

I can probably solve this issue i just press select 2x and then it would not have the bug anymore

**Comment by Gamemulatorer** [comment] 2021-10-04 14:03
> > I can repro this issue by changing buffered rendering to skip buffered rendering, not only that I can also repro this issue by loading a savestate hm. 🤔
> > • Loading from savestate ![Screenshot_20200527-071259](https://user-images.githubusercontent.com/37603562/82959384-23341180-9fea-11ea-8e61-18769174e62c.png) • Changing buffered to skip buffered ![Screenshot_20200527-071252](https://user-images.githubusercontent.com/37603562/82959445-4ced3880-9fea-11ea-8848-672dc2c59089.png) • GE Dump [SOCOM3.zip](https://github.com/hrydgard/ppsspp/files/4685464/SOCOM3.zip)
> 
> I can probably solve this issue i just press select 2x and then it would not have the bug anymore

No need to that using ppsspp latest git build try it.

**Comment by Gamemulatorer** [comment] 2021-10-04 14:31
> > No need to that using ppsspp latest git build try it.
> 
> Thank you so much man the bug never appears again 😀

Yeah because of this
https://github.com/hrydgard/ppsspp/issues/11814#issuecomment-927887767

**Comment by benderscruffy** [comment] 2022-11-30 01:45
is this still a problem ???

**Comment by Gamemulatorer** [comment] 2022-11-30 10:45
Try it and see what happens.

**Comment by hrydgard** [comment] 2023-04-20 07:06
Gotta be a duplicate of #16210. Closing as fixed.

**Closed by hrydgard** 2023-04-20 07:06 UTC
Labels: Networking / adhoc, GE emulation
