### ISSUE TITLE
MHP3rd font issue in build 1.5.4

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#10703] opened 2018-03-10 23:14 UTC
![npjb40001_1 00_2](https://user-images.githubusercontent.com/37251822/37247942-7841e7f4-2492-11e8-9a7d-c13838b93888.jpg)
I updated to build 1.5.4 and I'm noticing font is cut off at the bottom in MHP3rd 
with the letters "j," "g," "y," and "q."

~~Also on a side note "half-width" English is not available anymore in the PSP keyboard. 
Why is that? Can it be re-enabled in any way? Is this causing the impact on the cut off letters?~~ (duplicate of #10512)

**Comment by unknownbrackets** [comment] 2018-03-11 03:53
Is this just a duplicate of #2788?  Are you using fonts from a real PSP, or the open source fonts that came with PPSSPP?

-[Unknown]

**Comment by Abbanon** [comment] 2018-03-11 06:08
It's occurring with the basic fonts that come with PPSSPP, yes. 
This issue wasn't present in previous versions, and copying the flash0/fonts files from said previous versions has not fixed it.
Alternatively, I've discovered using a custom font set is an effective workaround that prevents the cut off from happening.

**Comment by hrydgard** [comment] 2018-03-11 12:25
What custom font set?

**Comment by Saramagrean** [comment] 2018-03-11 12:42
For me, I use this font. :)
https://drive.google.com/file/d/11QmS7HBVkToXfNGAKje-GOX01oEJV4B0/view?usp=drivesdk

It's workaround for MonHun game & other games.  (like Metal Gear Solid: Peace Walker)
![comb11032018073001](https://user-images.githubusercontent.com/26355472/37253424-2677bfb6-2564-11e8-8c97-dab51615d076.jpg)

**Comment by Abbanon** [comment] 2018-03-11 15:59
Saramagrean beat me to it. 
But anyhow, yes, that is identical to the font set that I'm using now, although likely from a different source.
It actually works great because it's very similar (if not exactly like) the actual PSP's font, at least for English. It replaces Japanese font as well, but I'm unsure of its accuracy since I can't read that language.

The only difficulty so far, very very rarely it takes a few seconds for some letters/symbols to load in.
Example: This took about 6 to 8 seconds to fully load in
![npjb40001_00002](https://user-images.githubusercontent.com/37251822/37255484-8cb05f54-2523-11e8-8b30-e34547839d9c.png)
![npjb40001_00003](https://user-images.githubusercontent.com/37251822/37255487-914f8b34-2523-11e8-8a96-7350a6b3c986.png)

**Comment by unknownbrackets** [comment] 2018-03-11 19:46
About the load time: do you have "lazy texture hashing" enabled?

I feel like at some point we implemented subpixel rendering for PGF, maybe that's why newer builds cut off the font and older builds didn't.  Ultimately, though, it's probably because the metrics in the font are both wrong (we have hacks to try to workaround the buggy metrics) and the size is different than games expect from default fonts.

-[Unknown]

**Comment by Abbanon** [comment] 2018-03-11 20:12
I did have Lazy Texture Cache enabled, yes.
It's disabled now, and I will provide any input if this has resolved the text loading issue.

On another note, do you think it would be a good idea to make a new open-source/default font for PPSSPP that would display properly with the subpixel rendering (if that is what causes the cut off)?

**Comment by Abbanon** [comment] 2018-03-11 22:12
Alright, so after a few hours of testing, having Lazy Texture Cache disabled has resolved the issue with custom fonts not loading in.

**Comment by unknownbrackets** [comment] 2018-03-11 22:39
Yes, creating a custom font would do the trick, but no one has volunteered to do so yet.

Closing this as a duplicate of #2788, in that case.

-[Unknown]

**Closed by unknownbrackets** 2018-03-11 22:39 UTC
Labels: PGF / sceFont
