### ISSUE TITLE
[Libretro] Add "Lower resolution for Effects" Option

### ISSUE THREAD

**Issue by ToniBC** [hrydgard/ppsspp#13627] opened 2020-11-05 23:38 UTC
The Libretro version of this emulator does not have this option or hack (Lower resolution for Effects), which avoids in many games Bloom defects and strange artifacts when using resolutions higher than the native one.

It would be good to incorporate this option, since I think that due to some oversight it was not added to the Libretro version.

Thank you.

**Comment by LunaMoo** [comment] 2020-11-06 00:39
Closing as a duplicate of #11099

**Closed by LunaMoo** 2020-11-06 00:39 UTC
