### ISSUE TITLE
"The Warriors" does not work in new build versions (black screen)

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#13595] opened 2020-10-28 14:24 UTC
### What happens?
Hello! 

I wanted to play this game (The Warriors ULES-00483) but with new versions of PPSSPP it doesn't work properly. When this sign comes out:

![Screenshot_20201028-150914_PPSSPP](https://user-images.githubusercontent.com/65356692/97448054-7f4fe880-1930-11eb-9a28-01357820f5ff.jpg)

The image goes black.

I tested with version ppsspp-v1.10.3-1019-gc97af17db-android And it doesn't work.
I've tried the "1.5.4—144 that one works well.
With the version "1.6.1-4" it also works well.
With version "1.10.3-343" not work.

**Comment by Panderner** [comment] 2020-10-28 14:56
Maybe Duplicate of #8991?

**Comment by MiguelCardonaG** [comment] 2020-11-01 15:04
> Maybe Duplicate of #8991?

And how did it work well in previous versions and in new ones didn't?

What do I do while they fix it or not fix it? Do I start the game with an old version that if it works? Will I do well with a hypothetical new version?

**Comment by MiguelCardonaG** [comment] 2020-11-01 17:30
I tested version 1.9.4 and it works well.
I tested version 1.10.3 (Gold) and it works well.
I tested the ppsspp-v1.10.3-2-g80386ca19-android version and it works well.
I tested the ppsspp-v1.10.3-1081-gfb785f5f0-android version and it doesn't work.

So the problem starts from ppsspp-v1.10.3-9-g406c06cca-android (allegedly) up to the version ppsspp-v1.10.3-1083-g5568ad2bc-android something or someone has "put" a mistake. Which one? That's the big question.

**Comment by Panderner** [comment] 2020-11-01 17:33
> I tested version 1.9.4 and it works well.
> I tested version 1.10.3 (Gold) and it works well.
> I tested the ppsspp-v1.10.3-2-g80386ca19-android version and it works well.
> I tested the ppsspp-v1.10.3-1081-gfb785f5f0-android version and it doesn't work.
> 
> So the problem starts from ppsspp-v1.10.3-9-g406c06cca-android (allegedly) up to the version ppsspp-v1.10.3-1083-g5568ad2bc-android something or someone has "put" a mistake. Which one? That's the big question.
> 
> @hrydgard

@MiguelCardonaG Investigate when the last build works

**Comment by MiguelCardonaG** [comment] 2020-11-01 17:40
@Panderner is that there are a lot of builds 😓 and to find what the problem is it's going to cost me my life. 🤣🤣

**Comment by hrydgard** [comment] 2020-11-01 18:12
it's less than a thousand builds, with a binary search (serach by halving) you can find it in 10 or 11 tries :)

**Comment by MiguelCardonaG** [comment] 2020-11-02 11:25
I've got it!!! 😀

The latest version that works well is the ppsspp-v1.10.3-129-g44954cff3-android.apk

The problem starts with this version ppsspp-v1.10.3-133-g5010fc846-android.apk up to the version ppsspp-v1.10.3-1083-g5568ad2bc-android.apk

@hrydgard

**Comment by hrydgard** [comment] 2020-11-02 11:40
Awesome!

Here are the suspects:

https://github.com/hrydgard/ppsspp/commit/dae9df38295f6034b416a0b62d74c6c414e67b15
https://github.com/hrydgard/ppsspp/commit/c5e0b799d9197e56f49a9531d64dd97f6d8f6261
https://github.com/hrydgard/ppsspp/commit/fa59be7e5db1526d07de75f6d7c14b94e98809e6

Seems the third one is by far the most likely. Maybe it's a little too strict with its checks?

**Comment by MiguelCardonaG** [comment] 2020-11-02 12:54
Well I don't know, I only see numbers and letters hahaha

**Comment by hrydgard** [comment] 2020-11-02 12:56
They are clickable and point to the source changes :) But yeah I'm mostly putting that as a note for myself.

**Comment by sum2012** [comment] 2020-11-08 21:14
v1.10.3-1169-g7632c1218-windows-amd64 log:
https://gist.github.com/sum2012/807f2cd3b8d0e05e37988118a5b53bfa

It is keeping
 displayThrea W[ME]: hle\scempeg.cpp:1957 sceMpegAvcCsc(09fff450, 09589400, 09fb7230, 512, 04000000) returning ERROR_MPEG_INVALID_VALUE
04:37:012 

So that It is my bad commit https://github.com/hrydgard/ppsspp/commit/fa59be7e5db1526d07de75f6d7c14b94e98809e6
Jpcsp have a little other problem of this game.
It will more check later

**Comment by hrydgard** [comment] 2020-11-08 22:57
Should I just revert https://github.com/hrydgard/ppsspp/commit/fa59be7e5db1526d07de75f6d7c14b94e98809e6 for now?

**Comment by sum2012** [comment] 2020-11-08 23:03
i want to test real psp first
but i need to go out to work now

在 2020年11月9日週一 上午6:58，Henrik Rydgård <notifications@github.com> 寫道：

**Comment by hrydgard** [comment] 2020-11-08 23:04
ok!

**Comment by sum2012** [comment] 2020-11-09 12:43
20:42:50.691198 displayThread - <- sceMpegAvcCsc 0x9FFB050, 0x9589400, 0x9FB3630, 0x200, 0x4000000 = 0x0

It is ok to revert.
But how about below part ?

	if (x < 0 || y < 0 || width < 0 || height < 0) {
		WARN_LOG(ME, "sceMpegAvcCsc(%08x, %08x, %08x, %i, %08x) returning ERROR_INVALID_VALUE", mpeg, sourceAddr, rangeAddr, frameWidth, destAddr);
		return SCE_KERNEL_ERROR_INVALID_VALUE;
	}

**Comment by hrydgard** [comment] 2020-11-09 12:45
If it works with that one, let's keep it.

**Comment by sum2012** [comment] 2020-11-09 12:46
Okay

**Closed** 2020-11-09 13:18 UTC
Labels: PSMF / MPEG

**Comment by MiguelCardonaG** [comment] 2020-11-09 16:27
@hrydgard @sum2012 It works fine now, thank you. 👍😀

**Comment by ridgekuhn** [comment] 2020-11-15 05:27
Apologies for commenting on a closed issue, but I just wanted to leave my thanks for getting this working again! For me, this is THE game on PSP! <3

**Comment by sum2012** [comment] 2020-11-15 05:30
This make me learn again Jpcsp 's emulator 's code is not 100% work

**Comment by hrydgard** [comment] 2020-11-15 08:53
Yeah, learning between the emulators goes in both directions :)
