### ISSUE TITLE
iOS14.2  v1.10.3version  still issue!!

### ISSUE THREAD

**Issue by chinalhx** [hrydgard/ppsspp#13861] opened 2021-01-03 09:41 UTC
### What happens?
Well,when I play Silent hill origin&memory ,both all flashlight textures issue.all of people said:just  try to disable "block transfer effects",it will can fix it,but sometimes,"SH:origin" this game,I enabled flashlight to close something, the person it will be transparent.
and SH:memory this game,if I enable flashlight textures  will show the grid
btw,i'm playing Tenchu 4 this game,it will automatic crash(for old version,I remember it can be play).so i try to change same silent hill  settings,emmm it's not work

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
my device is iPhone XS ,using ios14.2 non-jb system,cpu core choose JIT
and using ppsspp version is v1.10.3-1438

other things! I've iphone4 using ios6 system.so,what's the ppsspp version I can be used?for this system

**Comment by chinalhx** [comment] 2021-01-03 09:43
I need some help!can someone to tell me how to fix it?(note:SH:origin SH:memory Tenchu4)

**Comment by Panderner** [comment] 2021-01-03 09:45
For flashlight issue for silent hill games go to #6265

**Comment by chinalhx** [comment] 2021-01-03 09:52
> For flashlight issue for silent hill games go to #6265

but there's new question is here,why the 'Tenchu4' this game will be crash?and go back to 'home'?

**Comment by chinalhx** [comment] 2021-01-03 09:54
> For flashlight issue for silent hill games go to #6265

and can u tell me 'SH' this game how to correct settings? I can't see pic,cuz I'm live in China ,u know IP address can't load other people pic

**Comment by Panderner** [comment] 2021-01-03 10:07
> > For flashlight issue for silent hill games go to #6265
> 
> but there's new question is here,why the 'Tenchu4' this game will be crash?and go back to 'home'?

Tenchu: Shadow Assassins works fine for android devices. @chinalhx have you tried to change the CPU core to IR Interpreter?

**Comment by chinalhx** [comment] 2021-01-03 10:28
now ,Tenchu4 it can play ty:)dude!emmm for iOS 14.2system how to correct set silent hill this game?

**Comment by chinalhx** [comment] 2021-01-03 10:28
> > > For flashlight issue for silent hill games go to #6265
> > 
> > 
> > but there's new question is here,why the 'Tenchu4' this game will be crash?and go back to 'home'?
> 
> Tenchu: Shadow Assassins works fine for android devices. @chinalhx have you tried to change the CPU core to IR Interpreter?

now ,Tenchu4 it can play ty:)dude!emmm for iOS 14.2system how to correct set silent hill this game?

**Comment by chinalhx** [comment] 2021-01-03 10:30
cuz,my IP address is block!can't open github pic and y2b website :(

**Comment by unknownbrackets** [comment] 2021-01-17 17:08
It sounds like the Tenchu issue here is the known iOS jit issue, and the Silent Hill issue is the known torch issue.  Closing this as a duplicate of those.

-[Unknown]

**Closed by unknownbrackets** 2021-01-17 17:08 UTC
