### ISSUE TITLE
PPSSPP on PiBoy DMG - inverted left analog

### ISSUE THREAD

**Issue by Silasm11** [hrydgard/ppsspp#14258] opened 2021-03-04 11:19 UTC
### What happens?
Hi, I recently set up a retropie image for a PiPBoy DMG and when using PPSSPP emulator, controls do not work properly: 

- The left analog of the Piboy is inverted (i.e. pushing the analog up moves the cursor down, and pushing down moves cursor up)
- The D-pad only works for left (which moves cursor up) and right (which moves the cursor down). The 'up' and 'down' presses do not seem to be mapped to anything. 

Is there a way to fix this? It must be a software issue as the same controls work fine i Emulation Station and with other emulators in ES too. Only PPSSPP standalone has this issue. 

I am using the latest official image from Experimental Pi (1.0.3).

Thanks!

**Comment by Panderner** [comment] 2021-03-04 11:38
Can you change the controls using controller configuration?

**Comment by Silasm11** [comment] 2021-03-04 12:23
> 
> 
> Can you change the controls using controller configuration?

Yes, but nothing changes for the analog and D-pad. All other mappings work fine (x, o, start select etc) and i can change them in controller configuration within PPSSPP. But D-pad and analog do not change no matter what i do.

**Comment by GentMAB** [comment] 2021-03-09 06:17
This error also happens on iOS using the current IPA file and any controller.  Even changing it manually does nothing.

**Comment by unknownbrackets** [comment] 2021-03-28 22:12
This is essentially a duplicate of #6297, basically the issue is that your controller exposes an inverted Y axis (which isn't "wrong" because there's no standard, so it can make up any direction it wants), and the UI doesn't give you any option to remap.  The controller mapping settings currently only affect in game, and the intent of that is to avoid locking you out of using the UI by accident (especially on i.e. Android TV.)

That said, on Linux/SDL platforms, you can change gamecontrollerdb to invert things, I believe.

Closing this as a duplicate of #6297.

-[Unknown]

**Closed by unknownbrackets** 2021-03-28 22:12 UTC
