### ISSUE TITLE
PoP rival swords yellow screen issue on android

### ISSUE THREAD

**Issue by gyanprakash13** [hrydgard/ppsspp#10693] opened 2018-03-06 15:09 UTC
What happens?
After the intro cutscene only a yellow screen appears and nothing else

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
1.4ghz octa core sd435

**Comment by leopard20** [comment] 2018-03-06 16:29
This issue has been submitted before.

If your phone supports Vulkan API, switching from openGL to Vulkan resolves the problem.

**Comment by lim2222** [comment] 2018-03-07 01:52
If your phone without vulkan try the old version1.0.1

**Comment by vaguerant** [comment] 2018-03-08 04:27
Dupe of #10522.

**Closed** 2018-03-08 09:19 UTC
