### ISSUE TITLE
[Vulkan] [Android] Broken rendering on Burnout Dominator

### ISSUE THREAD

**Issue by mgemt** [hrydgard/ppsspp#11771] opened 2019-02-06 12:09 UTC
### What happens?
Broken Rendering on Cars and Roads with Vulkan

![screenshot_20190206-190710](https://user-images.githubusercontent.com/44252828/52342585-67dc1800-2a48-11e9-98ee-5a75335a3241.png)
![screenshot_20190206-190721](https://user-images.githubusercontent.com/44252828/52342593-6ad70880-2a48-11e9-8bbc-d391e701aee0.png)
![screenshot_20190206-190730](https://user-images.githubusercontent.com/44252828/52342596-6dd1f900-2a48-11e9-90c7-360b0904e9ad.png)

### What *should* happen?
Cars and Roads Rendered properly as on OpenGL Backend
![screenshot_20190206-190600](https://user-images.githubusercontent.com/44252828/52342966-6ced9700-2a49-11e9-999b-3b29be736880.png)
![screenshot_20190206-190604](https://user-images.githubusercontent.com/44252828/52342969-6e1ec400-2a49-11e9-8214-d4daa102e8df.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP v1.7.5-414-g210e84869 on Snapdragon 636 Asus Zenfone Max Pro M1
it also happen on my previous device Snapdragon 652 Xiaomi Mi Max
I Tried on The PC The Problem Didn't exist on Vulkan backend (v1.6.3 454)

**Comment by hrydgard** [comment] 2019-02-06 12:24
Please add some screenshots or at least description of what's wrong.

In addition, please answer the question about hardware, os and PPSSPP version...

**Comment by hrydgard** [comment] 2019-02-06 12:25
Duplicate of #11557 ?

**Comment by mgemt** [comment] 2019-02-06 12:45
I'm having trouble posting image on Android and Forgot my password when try to log on PC :(

Yeah it's perhaps a Duplicate on #11557

**Comment by hrydgard** [comment] 2019-02-06 13:07
Yeah, gonna call it a duplicate of that. Seems to be specific to that generation of Adreno GPUs.

**Closed by hrydgard** 2019-02-06 13:07 UTC
Labels: Adreno GPU, Platform-specific (Android)
