### ISSUE TITLE
Yu Gi Oh GX / Blazblue Broken font

### ISSUE THREAD

**Issue by NekoArcueid** [hrydgard/ppsspp#7550] opened 2015-03-03 00:32 UTC
the font gets to big in yu gi oh and sometimes end out of the screen, also blazblue has same issue with the plus of many missing characters on screen

**Comment by Warriors-Blade** [comment] 2015-03-09 09:04
Have you tried using the official PSP fonts?

That should fix any of those kinds of issues.

**Comment by NekoArcueid** [comment] 2015-03-09 13:05
where i need to put them? and which format they're supposed to have? I get a bunch of *.pgf fonts

**Comment by Warriors-Blade** [comment] 2015-03-09 13:39
You can get it off of your actual PSP or by doing a search, they are in .pgf format.

The reason they are not included is the official font is copyrighted they the PPSSPP team had to improvise , too bad most games kind of need the official fonts .

**Comment by NekoArcueid** [comment] 2015-03-09 13:52
ohh I see, in android is the same?

**Comment by Warriors-Blade** [comment] 2015-03-09 17:03
Here is where you can get the font ,

http://emulation-general.wikia.com/wiki/PPSSPP

Not sure if posting that is against any rules.

**Comment by unknownbrackets** [comment] 2015-12-29 17:39
Closing this as a duplicate of #2788.

-[Unknown]

**Closed by unknownbrackets** 2015-12-29 17:39 UTC
