### ISSUE TITLE
Silent Hill Zero graphics issue on Android

### ISSUE THREAD

**Issue by GriffenJohn** [hrydgard/ppsspp#14295] opened 2021-03-15 01:21 UTC
### What happens?

Silent Hill Zero graphics issue in v1.11.3
The graphic is wrong when flashlight is turned on.
PPSSPP v1.10.3 and older version don't have this problem.
![微信图片_20210315085550](https://user-images.githubusercontent.com/36688398/111092038-c8de5000-852c-11eb-8d94-b73e6baebd6b.jpg)
![微信图片_20210315085556](https://user-images.githubusercontent.com/36688398/111092039-cbd94080-852c-11eb-9b21-c8351c02b92a.jpg)

#### What hardware / device and operating system?
Android, Vivo z1x
#### What graphics card (GPU) or mobile phone model?
Snapdragon 765G
#### What PPSSPP version (standalone/official), and did it work before?
1.11.3
#### Which game or games?

Silent Hill Zero (ULJM05281)
#### Graphics backend (Vulkan, OpenGL, etc.)?
Vulkan, but same problem width OpenGL

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [X] Try changing graphics settings to determine if one causes the bug.
 - [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment] 2021-03-15 01:24
Is this not the same as #6265?

-[Unknown]

**Comment by BankofFunny** [comment] 2021-03-15 01:51
NO, not the same

**Comment by unknownbrackets** [comment] 2021-03-15 02:20
Well, the character getting "seen through" looks similar.  It also sounds like #14265, which I'm not entirely clear isn't a duplicate too.

The reason to avoid duplicates is to make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

If you attach a GE frame dump, I could compare with a real PSP rendering and check:
See: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

But I assume it draws the torch the same as I described in https://github.com/hrydgard/ppsspp/issues/6265#issuecomment-447602810, so it's probably still depth issues.

-[Unknown]

**Comment by Lemoncak3** [comment] 2021-03-16 11:26
Isn't this an old issue? Since i have tested it from previous version before 11.3 and it always glitch like that whenever i turn the flashlight on just like the one in screenshot.

**Comment by BankofFunny** [comment] 2021-03-18 02:53
What version have you tested? I have tested 1.10.3 & 1.9.4 Android release ver,  no such bug
1st pic is from v1.10.3 release, 2nd from v1.11.3 release
![微信图片_20210318105204](https://user-images.githubusercontent.com/36688398/111566387-09152b00-87d8-11eb-95ce-496ccbfec8b8.jpg)
![微信图片_20210318105211](https://user-images.githubusercontent.com/36688398/111566403-0e727580-87d8-11eb-85c4-ffa289f0ff2d.jpg)

**Comment by Gamemulatorer** [comment] 2021-05-19 14:16
@GriffenJohn upload a ge dump
 https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Gamemulatorer** [comment] 2021-05-19 18:09
This is a duplicate of https://github.com/hrydgard/ppsspp/issues/8497

**Comment by unknownbrackets** [comment] 2021-05-23 17:41
This issue is being closed as a duplicate of #8497.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-05-23 17:41 UTC
