### ISSUE TITLE
Tekken save data corrup

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#14210] opened 2021-02-23 15:03 UTC
### What happens?
save data corrup tekken drak resurrection
ULUS10139
![Screenshot_20210223-220209](https://user-images.githubusercontent.com/78854859/108862457-d5087900-7622-11eb-9094-17afced3e882.png)

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Sharp SH04H & Sony Xzs
Snapdragon 820

**Comment by Panderner** [comment] 2021-02-23 15:16
@IrfanH495 have you using latest build?

**Comment by IrfanH495** [comment] 2021-02-23 15:19
> @IrfanH495 have you using latest build?

Yes i use last bulid after play & quit save data will corrup.

**Comment by Panderner** [comment] 2021-02-23 15:25
Have you tried to delete save data?

**Comment by IrfanH495** [comment] 2021-02-23 15:30
> Have you tried to delete save data?

Yes i have tried many times, occurs in the play store ver and last bulid

**Comment by Panderner** [comment] 2021-02-23 15:37
@IrfanH495 how's the older versions worked?

**Comment by IrfanH495** [comment] 2021-02-23 15:40
> @IrfanH495 how's the older versions worked?

it happens if I play & exit, and continue the game the save data becomes corrupted ,.  It has been a long time since ppsspp bulid v1.10.3, after my friend tried the PlayStore version I became convinced this was an issue.
last work on playstore v1.10.3

**Comment by unknownbrackets** [comment] 2021-02-23 16:11
Are you sure you're not using a pirated iso?  Sometimes they patch the save data to be able to hack older PSP firmware.  PPSSPP operates like firmware 6.60, and often these hacks cause problems.  Please make sure you're using your own rip of the disc and double check the CRC.

Is this #13540?

-[Unknown]

**Comment by IrfanH495** [comment] 2021-02-23 16:16
> Are you sure you're not using a pirated iso? Sometimes they patch the save data to be able to hack older PSP firmware. PPSSPP operates like firmware 6.60, and often these hacks cause problems. Please make sure you're using your own rip of the disc and double check the CRC.
> 
> Is this #13540?
> 
> -[Unknown]

I don't understand the file size.
![Screenshot_20210223-231243](https://user-images.githubusercontent.com/78854859/108872446-c3c46a00-762c-11eb-9a90-9438c3259fab.png)

**Comment by unknownbrackets** [comment] 2021-02-23 16:20
The size at the bottom is just its guess from the ISO contents.  There's definitely different CRCs floating around:
https://report.ppsspp.org/game/ULUS10139_1.00

This issue is being closed as a duplicate of #13540.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-02-23 16:20 UTC

**Comment by IrfanH495** [comment] 2021-02-23 16:28
> The size at the bottom is just its guess from the ISO contents. There's definitely different CRCs floating around:
> https://report.ppsspp.org/game/ULUS10139_1.00
> 
> This issue is being closed as a duplicate of #13540.
> 
> This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/). You wouldn't add another "bread" item to a grocery list every time you thought about it, right? We do the same here - we already have "bread" (this issue) on our list.
> 
> By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips. When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly. Duplicates won't make fixes appear faster.
> 
> And remember - PPSSPP is open source. Try to find _new and useful information_, and add it to the original issue. If you can't wait any longer, muster up your courage and try fixing it yourself. PPSSPP gets better the more people contribute. You could be that amazing person who solves this problem for everyone.
> 
> -[Unknown]

I'm sorry, I didn't know anyone had reported this issue.  thanks for explaining it.
good work

**Comment by IrfanH495** [comment] 2021-02-23 17:49
@Panderner sorry my report, I closed it accidentally https://github.com/hrydgard/ppsspp/issues/14211

**Comment by IrfanH495** [comment] 2021-02-23 18:08
@unknownbrackets Help me I closed it accidentally 🙏🙏🙏
