### ISSUE TITLE
Autosave wont work on mod nation racer please fixs

### ISSUE THREAD

**Issue by omarguerrero5310** [hrydgard/ppsspp#9517] opened 2017-03-31 15:12 UTC

**Comment by unknownbrackets** [comment] 2017-04-09 07:27
What happens?  Did it used to work?  What platform are you using?  Can't be fixed without more information.

-[Unknown]

**Comment by omarguerrero5310** [comment] 2017-07-10 18:04
Android and Windows and iOS

**Comment by omarguerrero5310** [comment] 2017-07-10 18:05
Yes it did work before but now it doesn't

**Comment by unknownbrackets** [comment] 2017-07-16 23:04
Thanks - I'll close this as a duplicate of #6078.

-[Unknown]

**Closed by unknownbrackets** 2017-07-16 23:04 UTC
Labels: No Feedback, Saving issue
