### ISSUE TITLE
[Feature Request] Ability to dump or rip models to Obj/Fbx + Save file de/re-encryption

### ISSUE THREAD

**Issue by Fallenleader** [hrydgard/ppsspp#8580] opened 2016-02-12 09:42 UTC
Back in the day, JCPSP had an interesting feature that allowed one to rip what was on the screen similar to how ninja ripper or 3d ripper snagged models from games.

Unfortunately, JCPSP is way behind in comparison with PPSSPP AND never seems to work for me.

I figured I would request this as a feature for PPSSPP.
While ripping from the scene itself would be sufficient, I would love to see things taken a step further and models/textures being dumped decrypted and converted to a usable format.

And to avoid making another section for a second feature request, can we please have the save decryption/re-encryption feature back? Some of us used that feature back in the day.

**Comment by unknownbrackets** [comment] 2016-02-12 15:15
Closing as a duplicate of #2825.  We'll just get confused if we have multiple issues for the same thing.

The other, that's still an ini option.  You can edit ppsspp.ini manually if you want to toggle it.

-[Unknown]

**Closed by unknownbrackets** 2016-02-12 15:15 UTC
Labels: Feature Request
