### ISSUE TITLE
Ape Escape Saru Saru Big Mission graphical distortions

### ISSUE THREAD

**Issue by Kuriatsu2501** [hrydgard/ppsspp#12436] opened 2019-10-21 03:16 UTC
### What happens?
When I try to boot into Ape escape Saru Saru Big mission, the title screen and all gameplay outside of stages shows an indigo colouring and certain models are pure white.

### What *should* happen?
When booting the game, there should be no graphical distortions.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
HP Omen,  Windows 10 build 1903, Intel I7-7700 3.6GHz.
PPSSPP version is 1.7.5 and 1.9.3
Graphics card: Nvidia GTX 1070

Screenshots of what it looks like and how its supposed to look: 
![AESSBM](https://user-images.githubusercontent.com/56810729/67174252-a7505780-f37e-11e9-925e-bb55ab7f4548.PNG)
![AESSBM-Working](https://user-images.githubusercontent.com/56810729/67174253-a7505780-f37e-11e9-9fff-d6ed8cb741e7.PNG)

**Comment by unknownbrackets** [comment] 2019-10-21 03:27
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Kuriatsu2501** [comment] 2019-10-21 06:21
Sure, here it is. I hope it helps to get to the bottom of this. Thanks for the instructions :)

[recording (1).zip](https://github.com/hrydgard/ppsspp/files/3749259/recording.1.zip)

**Comment by Panderner** [comment] 2019-10-22 09:25
Have you tried opengl, vulkan, d3d9, d3d11?

**Comment by Kuriatsu2501** [comment] 2019-10-23 02:07
> Have you tried opengl, vulkan, d3d9, d3d11?

Yes, that's actually the first thing I tried, along with various post-render settings such as inverting the colour :)

**Comment by Kuriatsu2501** [comment] 2019-10-27 00:39
I took a look around and I had an idea to check the oldest version I could get of PPSSPP.
I got 1.6.3 and it looks like ape escape saru saru big mission works pretty well on there.
Something may have broken for that game between 1.6.3 and 1.7.5. I figured I'd report back.

**Comment by unknownbrackets** [comment] 2020-01-02 01:09
This is very similar to #12519.  The fog parameters are the same - INF and -NAN, but the color is ffcccc.  That's where the solid color is coming from.

![UCJS10060_#12436_ape_escape_indigo_blend](https://user-images.githubusercontent.com/191233/71648462-5ed7e300-2cb9-11ea-95d2-1b469a5fe874.png)

Again, in this case the same dump played back on a PSP also renders wrong, so it seems like it may somehow be an issue generating the display list?

-[Unknown]

**Comment by unknownbrackets** [comment] 2020-04-05 23:39
Does this look correct on Android?  It may be fixed by #12800 if it's only on PC.

-[Unknown]

**Comment by Panderner** [comment] 2020-04-06 00:03
> Does this look correct on Android? It may be fixed by #12800 if it's only on PC.
> 
> -[Unknown]

Yes it works correctly when I using Android
![Screenshot_2020-04-06-08-01-45-57_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/78513285-0561e180-77dd-11ea-93a7-314289659931.png)

**Comment by LunaMoo** [comment] 2020-04-06 07:19
Found a demo of this:
https://forums.exophase.com/attachments/eboot-pbp.1565/
But I can't reproduce on windows even before the fix was merged(demo will not work in much older versions of PPSSPP without decrypting it first through).

**Comment by unknownbrackets** [comment] 2020-04-06 13:46
It looks like someone flagged this issue in reporting with an NVIDIA card:

https://report.ppsspp.org/game/UCJS10060_1.00#report-compat-252681

The demo unfortunately is not drawing the same way - it is drawing a screenshot of that scene, whereas the dump implied that the scene is dynamic in the real game (notice also the Windows and Android screenshots are different.)  I think maybe the demo just doesn't reproduce the issue...

-[Unknown]

**Comment by Panderner** [comment] 2020-11-19 13:02
It's now fixed on x86 Windows
This can be closed now 
![Screenshot (2)](https://user-images.githubusercontent.com/37503397/99669603-44158500-2aaa-11eb-96ab-53322d277dd6.png)

**Closed** 2020-11-19 13:48 UTC
Labels: No Feedback / Outdated?, x86jit
