### ISSUE TITLE
PPSSPP crashes when loading pspkvm.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#9386] opened 2017-03-04 23:12 UTC
Using the latest dev build PPSSPP crashes immediately when loading pspkvm, this does not happen in the stable version.

Pspkvm is this:
http://dedomil.net/forum/showthread.php?tid=1737

**Comment by LunaMoo** [comment] 2017-03-05 04:07
Boots fine here using v1.3-776-g91ebdf0:
![menu_00000](https://cloud.githubusercontent.com/assets/5485237/23584417/70b9a832-0161-11e7-9865-a0bb20fbe290.jpg)
~ It shows 0/0 fps because it's only updating screen on input.

**Comment by ThePhoenixRises** [comment] 2017-03-05 04:33
Yes I can confirm no problems using latest version PSPKVM on my Nexus 7 tablet.
#
![screenshot_20170305-042523](https://cloud.githubusercontent.com/assets/6565304/23584553/c7bb3236-015c-11e7-848d-9d8d77380b4c.png)

**Comment by LunaMoo** [comment] 2017-03-05 04:53
Tested some demo from http://rzr.online.fr/wap.html works fine as well:
![menu_00001](https://cloud.githubusercontent.com/assets/5485237/23584664/f929e82a-0167-11e7-8dcc-8730e8405c76.jpg)
Guess this means we can close this as well as #8237.

 @blackman91 if it still doesn't work for you, we can reopen, but please first test by resetting settings to default since we have quite a lot dangerous/game breaking settings especially speedhacks, and if that doesn't help, reply again listing your hardware/os since the problem would in that case be specific to your system.

**Comment by blackman91** [comment] 2017-03-05 17:18
It keeps crashing for me using the latest dev on default settings, I am on android 4.2.2 using archos gamepad 2. Here is some info from log, please reopen:
![screenshot_2017-03-05-11-10-01](https://cloud.githubusercontent.com/assets/6578180/23589586/50c32128-0195-11e7-893c-7d86a0fe222b.png)
![screenshot_2017-03-05-11-10-14](https://cloud.githubusercontent.com/assets/6578180/23589590/5be438e4-0195-11e7-91e0-62e836b277f6.png)
![screenshot_2017-03-05-11-10-46](https://cloud.githubusercontent.com/assets/6578180/23589593/63b3fdca-0195-11e7-9e37-6d7769f7c2bb.png)

**Comment by LunaMoo** [comment] 2017-03-05 18:01
Ok, reopening.

 Althrough to note most of the errors generated in this homebrew doesn't really matter. It doesn't need network connection nor any *.raw/*.txt files in pspkvm/appdb/, those show up as errors even when it works fine.

 So the problem is probably those missing lib/skin.bin or some other things. In case this homebrew actually saves some path to it's config files, I would recommend renaming it's folder and getting a fresh copy of this pspkvm to test if that doesn't fix the problem on it's own since some paths probably changed and that does not mean they were correct in the past, quite the opposite old incorrect paths could be breaking it now.
 Or it's just some weirdness of your device.

**Comment by blackman91** [comment] 2017-03-05 19:04
I took a quick video of what happens with a clean install of ppsspp when opening a clean pspkvm:

https://www.dropbox.com/s/3dbqxy09f5z8y3h/SCR_20170305_124719.mp4?dl=0

As you can see it crashes on pspkvm start up.

**Comment by LunaMoo** [comment] 2017-03-05 20:30
I see one bad thing there ~ you're launching this homebrew from the root of your sdcard.

 Homebrew is kind of a special case and might became even more special now where previously it could work by accident - it should be ran only from inside memstick/PSP/GAME that means on android place it inside your sdcard/PSP/GAME/ and it should work.

**Comment by hrydgard** [comment] 2017-03-05 20:55
We should probably warn when trying to run homebrew outside PSP/GAME or maybe offer to copy or move it there...

**Comment by blackman91** [comment] 2017-03-05 21:15
Thanks a lot LunaMoo that did it! Weird that the stable 1.3 can  launch the homebrew from the sdcard or from the internal memory outside the psp/Game folder. You can close this now.

**Comment by hrydgard** [comment] 2017-03-05 21:28
Made some changes to how paths work to fix other issues, probably related...

**Closed by hrydgard** 2017-03-05 21:28 UTC

**Comment by iOS4all** [comment] 2017-03-06 14:55
Please can you help us with this?
I can't run any jar/jad apps by pspkvm on iOS. It says can't connect to wifi.

For mire information see my thread.
https://github.com/hrydgard/ppsspp/issues/9393
Thanks.
