### ISSUE TITLE
god eater 2 v140: ppsspp black screen or force cloce , when finished the first mission from julius

### ISSUE THREAD

**Issue by Laxbert** [hrydgard/ppsspp#8734] opened 2016-05-13 23:23 UTC
please help me

**Comment by benderscruffy01** [comment] 2019-04-02 11:46
can be closed ???

**Comment by unknownbrackets** [comment] 2019-04-03 06:36
This issue is being closed as a duplicate of #8075.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2019-04-03 06:36 UTC
