### ISSUE TITLE
Switching render backend and restarting causes the instance number to increase

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13247] opened 2020-08-04 21:22 UTC
Instances other than the first no longer save their config (in order to avoid them stomping on each other), so you can't change the backend again until you completely exit PPSSPP and start it again.

Need better instance counting :)

**Comment by unknownbrackets** [comment] 2020-08-10 05:16
I think this was intended to be closed by that pull request.

-[Unknown]

**Closed by unknownbrackets** 2020-08-10 05:16 UTC
Labels: User Interface
