### ISSUE TITLE
Invizimals - can't capture the first invizimal

### ISSUE THREAD

**Issue by Lyuu17** [hrydgard/ppsspp#12638] opened 2020-02-23 12:18 UTC
### What happens?
I can't capture the first invizimal - you have to slap the invizimal.

### What *should* happen?
Capture the invizimal.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Xiaomi Mi A3 (SD 665, Adreno 610), Android 9, latest PlayStore version.

I'm not sure but it could be the camera render, because it seems to have low fps compared with the graphics game.

**Comment by Panderner** [comment] 2020-02-23 14:49
You need a Trap Card like This
![unnamed](https://user-images.githubusercontent.com/37503397/75114102-2ee00700-568e-11ea-95a6-09508ebefb55.jpg)

Step 1. Get some Hard Paper
Step 2. Print the trap card
Step 3. Put trap card to anything on a flat surface notebook for example

Although this is not a Bug.

**Comment by Lyuu17** [comment] 2020-02-24 08:43
No shit sherlock. I'm stuck here: https://youtu.be/-oqXztohj9c?t=258 but with the initial invizimals. Again, not sure if it's the camera FPS or something related with the emu.

**Comment by Florin9doi** [comment] 2020-02-24 12:27
Duplicate of #12336

**Comment by Panderner** [comment] 2020-02-24 17:42
> Duplicate of #12336

No @Florin9doi this is not a duplicate of #12336. I don't think a microphone is used for this game

**Comment by Lyuu17** [comment] 2020-02-24 19:43
> > Duplicate of #12336
> 
> No @Florin9doi this is not a duplicate of #12336. I don't think a microphone is used for this game

Mic is used for the game, but since is not being detected it's 0 in the noise bar, so I guess it's not a mic issue.

**Comment by Florin9doi** [comment] 2020-02-24 19:50
How is the game supposed to detect noise without a microphone?

**Comment by Lyuu17** [comment] 2020-02-28 14:55
> How is the game supposed to detect noise (a slap) without a microphone?

i dunno, the sound bar doesn't seem to increase but internally might use the noise for detection. will keep this open until sound support is added anyway (or @hrydgard decides)

**Comment by hrydgard** [comment] 2020-02-28 15:10
Microphone isn't implemented yet so it won't work.

**Comment by Zaine6** [comment] 2020-05-30 07:19
Game is unplayable without the microphone!

**Comment by Florin9doi** [comment] 2020-12-05 09:19
This ticket is resolved and the support for other platforms is tracked in #12336. 
@hrydgard, I propose this for closure

**Closed** 2020-12-05 09:22 UTC
