### ISSUE TITLE
release tarball including all submodule sources please ?

### ISSUE THREAD

**Issue by rofl0r** [hrydgard/ppsspp#13973] opened 2021-01-25 02:26 UTC
### What happens?

the build page explicitly states that for a release tarball all git submodules need to be downloaded manually, which is logical, as the release tarball is [provided by github](https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck).

### What *should* happen?

When tagging the release, the maintainer should run a 10 line shell script that downloads the contents of all submodules at the specified version, and then pack everything into a tarball, which is then manually attached to the tag.

**Comment by unknownbrackets** [comment] 2021-01-25 03:59
This issue is being closed as a duplicate of #11090.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

That being said, `git` is a mostly superior means of downloading a copy of the source code, since it will check that it saved to disk and downloaded correctly for you.

-[Unknown]

**Closed by unknownbrackets** 2021-01-25 03:59 UTC

**Comment by rofl0r** [comment] 2021-01-25 12:49
i'm not talking about consumer downloads, i talk about downloads used from my (and other) distro's build recipes like here:
https://github.com/sabotage-linux/sabotage/blob/master/pkg/visualboyadvance

it already checks checksums and stuff as you can see.

and i can't see how, if you need a flat copy of the sources and no history, running git 10x with different URLS should be superior than downloading a single compressed file. it certainly is a lot effort, if you mean that by superior.

i'm certain you'd agree that

**Comment by rofl0r** [comment] 2021-01-25 12:52
i'm not talking about consumer downloads, i talk about downloads used from my (and other) distro's build recipes like here:
https://github.com/sabotage-linux/sabotage/blob/master/pkg/visualboyadvance

it already checks checksums and stuff as you can see.

and i can't see how, if you need a flat copy of the sources and no history, running git 10x with different URLS should be superior than downloading a single compressed file. it certainly is a lot effort, if you mean that by superior.

i'm certain you'd agree that

**Comment by unknownbrackets** [comment] 2021-01-25 15:07
You can run git once using recursive, and you can tell it to make a shallow clone.  You don't need to run it 10 times.

It's not like submodules are some PPSSPP custom feature.  They're a built-in function of git.  Of course it has ways to download them along with the original repo code.

Every pull request / commit on this repo generates a build from a shallow clone with all submodules, downloaded fresh to a new cloud instance (in fact, downloaded several times concurrently for different platforms.)  Windows, macOS, and Ubuntu binaries are generated from this for testing/validation.  It's not like I'm talking something theoretical.

The other issue is still open, maybe someone will start creating tars for people who hate git at some point.

-[Unknown]

**Comment by rofl0r** [comment] 2021-01-25 15:18
> maybe someone will start creating tars for people who hate git at some point.

it's not that we hate git, it's that package build systems are made for tarballs.
additionally my distro has a guideline that package recipes shall not access internet (enforced via unshare) other than for the download of the source tarball, which can be provided in advance. this makes it possible to hack on and rebuild packages even if the internet is not accessible, once you completed the download step.
we have some users that actually do not have an internet connection at home and go to a bar with wifi when they need to download some package tarballs, and then build them at home. the package manager has a special subcommand for that (butch download).

**Comment by unknownbrackets** [comment] 2021-01-25 18:37
I get it, although git also has the concept of a "bare clone" (basically, just the `.git` folder packs) which can be obtained in advance, and then decompressing the files from the bare clone can be obtained at any later point.  Git is actually very intentionally designed to allow this model and to not require Internet access for common operations (unlike, say, Subversion.)

Developers can be in the same situation without Internet access (or with restricted access) at home, for a large variety of reasons.  That use case is absolutely used by developers with git every day.

-[Unknown]

**Comment by rofl0r** [comment] 2021-01-25 18:57
> Git is actually very intentionally designed to allow this model and to not require Internet access for common operations

that is of course possible, but then the user has to clone and build his stuff from hand, outside of the realm of the package manager.
