### ISSUE TITLE
Arabic text not working on Linux

### ISSUE THREAD

**Issue by moceap** [hrydgard/ppsspp#9855] opened 2017-07-19 15:54 UTC
![2017-07-19 18-47-11](https://user-images.githubusercontent.com/4345211/28376610-39a5c444-6cb3-11e7-9185-289a238542f4.png)

Arabic letters can't  read by PPSSPP, Tried on Fedora and Android!

**Comment by hrydgard** [comment] 2017-07-19 19:51
This has been fixed for Android in 1.5. Try the latest builds from https://buildbot.orphis.net/ppsspp/ .

Needs more work to fix it for Linux, we need to use some kind of native font system.

**Comment by moceap** [comment] 2017-07-20 19:33
You can try DejaVu which included in all Linux distros.

**Comment by hrydgard** [comment] 2017-07-20 20:57
That's a font, not a rendering system. I guess we need something like https://www.freedesktop.org/wiki/Software/HarfBuzz/ plus freetype.

**Comment by moceap** [comment] 2017-07-21 06:59
Use LibRaqm:
https://github.com/HOST-Oman/libraqm

**Comment by ebraminio** [comment] 2018-12-28 20:38
Hey there. Why not Pango? It is a system library already uses harfbuzz and freetype correctly and is well tested.

**Comment by ebraminio** [comment] 2018-12-28 21:11
That applies to libraqm also but pango is usually installed on every distribution.

**Comment by hrydgard** [comment] 2019-03-03 10:07
Closing as duplicate of #9958

**Closed by hrydgard** 2019-03-03 10:07 UTC
Labels: Platform-specific (Linux/POSIX)
