### ISSUE TITLE
MGS: Peace Walker (greatest hits) model bug

### ISSUE THREAD

**Issue by Seta193** [hrydgard/ppsspp#14726] opened 2021-08-14 04:37 UTC
### Game or games this happens in

ULUS-10509GH

### What area of the game

On the beach during the prologue.

### What happens

Character models appear as distorted lines.

### What should happen

Character models should appear normally. 

### GE frame capture

![360FD345-A9FE-46CF-9715-53DAFBE5DF48](https://user-images.githubusercontent.com/38902763/129433949-802dfe60-ef97-4f93-b266-99677cc6f681.png)
![B17CF6BC-E9AE-4906-A5AD-AA0273C9B31F](https://user-images.githubusercontent.com/38902763/129433953-689b5880-506b-49b2-b51b-ad6f59af91f4.png)
![D35A829A-77FB-45AF-9FED-F372ADFA60B1](https://user-images.githubusercontent.com/38902763/129433955-fa742364-ac37-42da-9e93-52e216a27cfa.png)

### Platform

iOS

### Mobile phone model or graphics card

Iphone 12 Pro Max

### PPSSPP version affected

V1.11.3-1066-g8fa52cd03

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [x] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [x] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment] 2021-08-14 04:40
Duplicate https://github.com/hrydgard/ppsspp/issues/14693

**Comment by Gamemulatorer** [comment] 2021-08-14 04:41
Also this https://github.com/hrydgard/ppsspp/issues/10650

**Comment by Seta193** [comment] 2021-08-14 05:06
Thanks for the links. It seems like the topic creator of #14693 fixed the issue, but I’m not sure how he did it.

**Comment by unknownbrackets** [comment] 2021-08-14 05:45
This issue is being closed as a duplicate of #10650.

To workaround this issue, you can switch to the (slower) interpreter.

This is an issue tracker - there's a [forum if you want to discuss things](http://forums.ppsspp.org/).  You wouldn't add another "bread" item to a grocery list every time you thought about it, right?  We do the same here - we already have "bread" (this issue) on our list.

By keeping the list clean, we can also make sure all the information a developer needs to fix the issue is at their finger tips.  When there are multiple issues, information gets lost and it becomes hard to fix things, so they are fixed more slowly.  Duplicates won't make fixes appear faster.

And remember - PPSSPP is open source.  Try to find *new and useful information*, and add it to the original issue.  If you can't wait any longer, muster up your courage and try fixing it yourself.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone.

-[Unknown]

**Closed by unknownbrackets** 2021-08-14 05:45 UTC
