### ISSUE TITLE
[Answer] Yes! Is threre any console manufacturer licensed game supports screen rotation?

### ISSUE THREAD

**Issue by soundsnow** [hrydgard/ppsspp#16973] opened 2023-02-16 05:38 UTC
These are pasted from my another issue, if you have seen some of them, do not reply to me

Licensed Commercial and Homebrew Games
Orientation: Auto, Portrait, Landscape
Screen Rotation: 0, 90°, 180°, 270°
4:3 to 3:4
16:9 to 9:16
21:9 to 9:21

This game Ikaruga is made by a famous video game developer. Treasure released this game for Sega Naomi Arcade Machine and Dreamcast Home Console. Dreamcast version is made for rotating monitor obviously.
To play this game like Arcade version
Open Game: Config - Monitor Type (Vertical 1/Vertical 2)
Vertical 1: Default D-Pad Direction
Vertical 2: Follow Screen Rotation D-Pad Direction
Rotate your monitor
If you don't have a Rotating Monitor, Emulator Settings - Screen Rotation (0, 90°, 180°, 270°)

Portrait Orientation and Screen Rotation are both required

Screen Rotation supported video game devices
Wii U
Lynx
WonderSwan
DS
DSi
3DS
New 3DS
PSP with 2 (Right) Analog Sticks
PSVita
Switch
Arcade Machine
Rotation Monitor (Home Console & PC)
Wireless Controller (Handheld Console)
Symbian, Windows Phone, iPhone, Android (Cellphone)
Emulator (Software Simulation)

![image58](https://user-images.githubusercontent.com/109885044/219099264-7d4044e4-507e-480c-a1c4-f8ce186cb737.png)
![image61](https://user-images.githubusercontent.com/109885044/219247030-a65484dd-79af-4371-9494-cd91899a8b74.png)
![image62](https://user-images.githubusercontent.com/109885044/219275604-a3c93f7f-185d-434c-a7b5-da6e1fcd0de2.png)

**Comment by soundsnow** [comment] 2023-02-16 05:40
PPSSPP doesn't support all rotation degrees
PPSSPP Vertical Video Position Center, it's not friendly for Android Touch Button users

**Comment by unknownbrackets** [comment] 2023-02-16 05:52
I'm not really sure, but this doesn't seem different from your other issues, and you are saying you're copy pasting from the other issues.  I've already felt like some of the previous issues are duplicates.

Please understand from a developer's perspective, this is like saying, "I thought about it and figured this remark would be offensive to you:".  Please try instead to avoid being offensive.  Creating multiple issues about the same thing is unkind and disrespectful.  It is better when asking people to make changes that you would like to try to be kind to them.  You are asking them to do things for you for free.

I understand that from your perspective, it may seem like the best way to get people to do things for you is to open a new issue about what you want every few days.  I can assure you that doing this will be bad.  It will only decrease the chances of getting what you want.

-[Unknown]

**Comment by Gamemulatorer** [comment] 2023-02-16 07:30
This is a duplicate of https://github.com/hrydgard/ppsspp/issues/16776

**Closed** 2023-02-16 09:14 UTC
