### ISSUE TITLE
Shrek Smash n Crash Racing issue

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12438] opened 2019-10-21 09:57 UTC
### What happens?
Game freezes at start menu and at begin of race

### What *should* happen?
The game should work fine

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Using D3D11 on PPSSPP v1.9.3.Game is from US region.

**Comment by hrydgard** [comment] 2019-10-21 09:58
Duplicate of https://github.com/hrydgard/ppsspp/issues/10139 , closing.

**Closed by hrydgard** 2019-10-21 09:58 UTC
