### ISSUE TITLE
can libretro jni so support x86_64 platform (ffmpeg)

### ISSUE THREAD

**Issue by hsoftxl** [hrydgard/ppsspp#16020] opened 2022-09-13 02:21 UTC
### What should happen

libretro jni so  not support x86_64

### Who would this benefit

..

### Games this would be useful in

..

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hsoftxl** [comment] 2022-09-13 10:14
[x86_64] Compile        : retro <= rtime.c
[x86_64] Compile        : retro <= vfs_implementation.c
[x86_64] Compile        : retro <= filter_neon.S
[x86_64] SharedLibrary  : libretro.so
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_qpel_10bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_1023' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_qpel_8bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_5' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_cabac.o): requires dynamic R_X86_64_PC32 reloc against 'ff_h264_cabac_tables' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h263_loopfilter.o): requires dynamic R_X86_64_PC32 reloc against 'ff_h263_loop_filter_strength' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_chromamc.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_8' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_chromamc_10bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_8' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_deblock.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pb_1' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_deblock_10bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_4' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_idct.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_32' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_idct_10bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pd_32' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_intrapred.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pb_3' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_intrapred_10bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_1' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(h264_weight_10bit.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_1' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(qpeldsp.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_3' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(simple_idct10.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pw_1023' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(fft.o): requires dynamic R_X86_64_PC32 reloc against 'ff_cos_32' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(hpeldsp.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pb_1' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(idctdsp.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pb_80' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(me_cmp.o): requires dynamic R_X86_64_PC32 reloc against 'ff_pb_1' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libavcodec.a(sbrdsp.o): requires dynamic R_X86_64_PC32 reloc against 'ff_ps_neg' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libswscale.a(swscale.o): requires dynamic R_X86_64_PC32 reloc against 'ff_M24A' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: /home/xielei/ppsspp/libretro/jni/../../ffmpeg/android/x86_64/lib/libswscale.a(rgb2rgb.o): requires dynamic R_X86_64_PC32 reloc against 'ff_w1111' which may overflow at runtime; recompile with -fPIC
/home/xielei/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: warning: shared library text segment is not shareable
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/home/xielei/ndk/android-ndk-r21e/build/core/build-binary.mk:725: /home/xielei/ppsspp/libretro/obj/local/x86_64/libretro.so] Error 1
xielei@DESKTOP-T3240L7:~/ppsspp/libretro/jni$

**Comment by ANR2ME** [comment] 2022-09-13 17:04
According to this https://codegrepr.com/question/how-to-recompile-with-fpic/
```
x86_64/libavcodec.a(h264_qpel_10bit.o): 
requires dynamic R_X86_64_PC32 reloc against 'ff_pw_1023' 
which may overflow at runtime; recompile with -fPIC
```
> Briefly, the error means that you can’t use a static library to be linked w/ a dynamic one.
> The correct way is to have a libavcodec compiled into a .so instead of .a, so the other .so library you are trying to build will link well.
>
> The shortest way to do so is to add --enable-shared at ./configure options. Or even you may try to disable shared (or static) libraries at all… you choose what is suitable for you!
>

**Comment by hsoftxl** [comment] 2022-09-14 02:37
thanks

**Comment by unknownbrackets** [comment] 2022-09-14 02:41
On Android, it's more of a pain to use .so files and might cause problems for jni as well as the headless binary, because of OS restrictions.  On Windows, it can also cause DLL confusion.  We also need a specific version of FFmpeg that other people are unlikely to use - shared objects aren't designed for this use case.

Really you just need to compile ffmpeg.  See #15969 and #15814 (which is essentially a duplicate at this point, really this and that both are duplicates of #15969.)

I think this is the same error I mentioned with the latest NDK, and we're still compiling with an older NDK.

-[Unknown]

**Comment by unknownbrackets** [comment] 2022-11-20 23:16
I'm going to close this as a duplicate of #15969.

-[Unknown]

**Closed by unknownbrackets** 2022-11-20 23:16 UTC
Labels: Libretro
