### ISSUE TITLE
Feature : UMD Video Player

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8077] opened 2015-10-17 03:35 UTC
When using keyboard to select game , is auto to play this UMD Video Player , hold down the left mouse button or click right mouse button , to go to game setting background and auto play UMD Video Player , my concept
![umd video player](https://cloud.githubusercontent.com/assets/11285640/10556820/e75bca68-74ba-11e5-95bb-3ee9162d4ecc.png)
![umd video player 2](https://cloud.githubusercontent.com/assets/11285640/10556821/e75e2434-74ba-11e5-90b0-ea1011ded86b.png)

**Comment by unknownbrackets** [comment] 2015-10-17 04:41
Still a duplicate of #2585.  This is "ICON1.PMF".

-[Unknown]

**Closed by unknownbrackets** 2015-10-17 04:41 UTC
