### ISSUE TITLE
Toggle between native texture pack and custom texture pack with a click

### ISSUE THREAD

**Issue by gamaghostmagus** [hrydgard/ppsspp#11906] opened 2019-03-17 10:36 UTC
This is not really an issue but, suggestion (i'm not expert with github, sorry if this is the wrong place)

### What happens?
everytime when i need see the changes of texture pack, i need to go into menu  

### What *should* happen?

With one command it will toggle between the textures, it will be useful to make the HD texture pack, i made a texture pack with more than 20 thousands of image, and it's the best and the fastest way to see the changes.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Linux (antergos)

**Comment by LunaMoo** [comment] 2019-03-17 11:36
Closing as a duplicate of #11734

**Closed by LunaMoo** 2019-03-17 11:36 UTC
