### ISSUE TITLE
Compiling on Raspberry Pi 5 64 bit.

### ISSUE THREAD

**Issue by TotalCoolness** [hrydgard/ppsspp#18605] opened 2023-12-24 00:48 UTC
Im trying to compile for the Pi 5.

Following the instructions here: https://github.com/hrydgard/ppsspp/wiki/Build-instructions#building-for-raspberry-pi-os-64-bit

I get the error:

`
./b.sh --rpi64

Building for native host.
~/ppsspp-code/ppsspp/build ~/ppsspp-code/ppsspp
CMake Error at cmake/Toolchains/raspberry.armv8.cmake:8 (message):
  RaspberryPI platform not recognized
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
`

Any help ?

**Comment by anr2me** [comment] 2023-12-24 01:56
You already opened an issue https://github.com/hrydgard/ppsspp/issues/18583 before, doesn't need to open another one with the same issue.

If anyone know whats wrong with it they will reply.
If you somehow figured out what's wrong, please let us know, so other people having the same issue know how to fix it.

For the meantime, you can try checking the solution from here (in case you're missing the toolchain installation too) https://github.com/orgs/micropython/discussions/13019

PS: i'm not familiar with Linux nor RPI

**Comment by hrydgard** [comment] 2023-12-24 08:47
Closing as dupe of #18583

**Closed by hrydgard** 2023-12-24 08:47 UTC
