### ISSUE TITLE
Naruto Impact graphic problem

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#10616] opened 2018-02-15 12:33 UTC
What happens?
The game was good on the start but when the fight starts the background is black when I changed it to buffered rendering, framedrops occur.

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Im using Samsung Galaxy S5
Android 6.0.1
Adreno 330
Snapdragon 801
2GB RAM

**Comment by GuilhermeGS2** [comment] 2018-02-15 12:58
Disable "simulate block transfer effects" helps? At least on my phone the Naruto Ultimate Ninja Impact FPS goes from 15 to full speed by disabling this.

**Comment by HypeChangerIvan** [comment] 2018-02-15 13:47
While its on buffered rendering?

**Comment by HypeChangerIvan** [comment] 2018-02-15 13:48
When its on skip buffer, its fast but the graphics have a problem, then when buffered, it lags crazy

**Comment by GuilhermeGS2** [comment] 2018-02-15 15:00
This option I mentioned is below buffer rendering, if I'm not wrong it's enabled by default, so disable. Your GPU should not have problem to run this game buffered, mine runs fine.

**Comment by HypeChangerIvan** [comment] 2018-02-15 15:02
The sound is very choppy and the game is slow but the graphics became fine

**Comment by GuilhermeGS2** [comment] 2018-02-15 16:54
Are you using the last build?

**Comment by HypeChangerIvan** [comment] 2018-02-15 21:23
Yes sir

**Comment by GuilhermeGS2** [comment] 2018-02-16 04:43
You really got a problem, here I'm running 30 FPS rare drops to 26-27 with 2x rendering resolution.

Galaxy J7 2015 (J700M)
-Exynos 7850 (8xCortex A53 @1.7GHz OC)
-Mali T720MP2 @680MHz
-1.5GB LPDDR3
-Android 6.0.1

Much weaker than yours.

**Comment by unknownbrackets** [comment] 2018-02-18 00:03
We intentionally have bugs when "buffered rendering" is not selected.  If it rendered exactly as "buffered rendering" the option would be removed.

Basically, turning off buffered rendering is like using the internet with images disabled.  Faster, but is it worth it?  Either way, it's not a bug when images don't render if you've disabled them.  Same here: it's not a bug that buffers don't render properly.  It's expected, doing exactly as you told it to.

You might try using the latest git build to improve performance, if you weren't already.  If it's possible to update Android, this may help too.

Closing because buffered rendering works as expected.  We're always working to improve performance where we can.  You can still comment, though, or you can ask others on the forum.

-[Unknown]

**Closed by unknownbrackets** 2018-02-18 00:03 UTC

**Comment by Rayanfer32** [comment] 2020-01-10 12:51
on a mali gpu things are different and suprisingly better than adreno... i dont know how is this possible

**Comment by hrydgard** [comment] 2020-01-10 13:16
Despite older Mali being terrible, modern Mali has become a pretty good architecture with less driver bugs than Adreno. Not so mysterious.

**Comment by Rayanfer32** [comment] 2020-01-10 15:37
yes mali has come a long way... indeed everything has changed .... oh and i
forgot to mention .... the new psp version breaks some games.... like
naruto ultimate ninja impact..
